### ISSUE TITLE
Support “HTTP” URIs (HTTP Upgrade mechanism) 

### ISSUE THREAD

**Issue by JanAndersson** [square/okhttp#1019]
As far as I understand this isn't supported in OkHttp. As it is part of the HTTP/2.0 standard I beleive this would be of great value to OkHttp...

**Comment by yschimke** [comment]
I'm working with a backend that supports plaintext assumed http/2.  So I'd like to look into this, ideally both

- plainttext h2c via upgrade
- http/2 only for both http and https e.g. assumed without ALPN

Specifically this could relax OkHttpClient.Builder.protocols

```
     * @param protocols the protocols to use, in order of preference. The list must contain {@link
     * Protocol#HTTP_1_1}. 
```

**Comment by swankjesse** [comment]
There's no spec for plaintext assumed HTTP/2. That's nonstandard and won't work with other tools.

**Comment by yschimke** [comment]
Isn't this section "3.4 Starting HTTP/2 with Prior Knowledge"

http://http2.github.io/http2-spec/index.html#rfc.section.3.4

**Comment by swankjesse** [comment]
Ah you're right. I still think it’s unwise to skip the upgrade path.

**Comment by yschimke** [comment]
Unfortunately, if the server also assumes h2c over plaintext then the initial HTTP/1.1 request with upgrade header will cause the server to barf

**Comment by yschimke** [comment]
Minus the plaintext Upgrade support which I'm still working on this turned out pretty easy to add assumed h2c mode, and http/2 only via ALPN.  Do you see any reason why this couldn't land once completed with proper tests etc?

https://github.com/yschimke/okhttp/pull/1/files

**Comment by JaySWang** [comment]
Hi guys, do you have any plan to support h2c?

**Comment by swankjesse** [comment]
None currently.

**Comment by jpitz** [comment]
I have an h2c prior knowledge solution out for review. Changes to critical code paths was rather minimal and I was able to leverage much of the existing test infrastructure. See gh-3873

**Comment by swankjesse** [comment]
We did HTTP/2 prior knowledge in 3.11. I’m not planning anything further here!
