### ISSUE TITLE
Make Cache class more flexible, add in memory cache

### ISSUE THREAD

**Issue by DASAR** [square/okhttp#1021]
Please make Cache class more flexible. Right not it's difficult to implement different kind of cache mechanism like hybrid (ram+disk) or in memory cache. Cache is final class and cannot be extended/changed by developers. OkHttp.setCache(cache) API as I think must accept java interface as   input.
Also it will be great if OkHttp team will implement more smart cache which will use ram memory also. In memory cache is required because of speed and also Android device memory (especially low end SD card) can be really slow.
Thanks for your project.

**Comment by KostyaSha** [comment]
Hi, any plans to have in memory cache? Today ram is enough and having 20Mb for cache in ram is more effective then using 20Mb of files.

**Comment by snodnipper** [comment]
a cache interface / more flexible cache would be great.  I have a use case where certain cached items / URLs should not be automatically evicted regardless of their age (offline mode) whereas newer items can be.  The permanently cached resources (aka offline resources) should, however, still be updated if the etag changes etc.

**Comment by swankjesse** [comment]
@snodnipper this issue is mostly about flexible storage for the current cache. It sounds like you're more interested in policy. Mind opening a separate issue to track that?

**Comment by swankjesse** [comment]
We’re going to cover some of these ideas in DiskLruCache2.
https://github.com/square/okhttp/issues/2682
