### ISSUE TITLE
Illegal character ((CTRL-CHAR, code 31))

### ISSUE THREAD

**Issue by stephano88** [square/okhttp#1026]
Hi,

I am getting this error when calling a Jax-rs Webservice using the Jackson libraries.

the problem is same to that one https://github.com/square/okhttp/issues/635

Does someone have an idea of how to resolve the problem ? 
Many thanks

**Comment by Rajini89prog** [comment]
@stephano88 - Having same problem, just want to check if you were able to find a solution for this (I understand this post is very old)..

**Comment by AllureLovew** [comment]
咋解决的

**Comment by monperrus** [comment]
This is caused by transparent GZIP compression.

To remove compression, add a header `request.header("Accept-Encoding", "identity")`

**Comment by roostinghawk** [comment]
my solution: set header as following to prevent gzip
`requestTemplate.header("Accept-Encoding", "identity");`

**Comment by Jodiss8** [comment]
Jodik
