### ISSUE TITLE
SocketTimeoutException with OkHttp 2.0.0 + Retrofit 1.6.1

### ISSUE THREAD

**Issue by laurentiuonac** [square/okhttp#1037]
Hello. I've been getting SocketTimeoutException intermittently. This is not an Internet connection issue. If I access the same link from the phone's browser it will open.

It happens mostly on WiFi, but it happens on mobile data also from time to time. After a random number of calls (usually below 20), the timeout occurs and any subsequent call will have the same result. It recovers after a while and works for another 20 calls or so. I cannot get an exact pattern or reason why this happens.

The endpoint is not blocking the app, tested with the backend guys.

``` java
mOkHttpClient = new OkHttpClient();
mOkHttpClient.setCache(cache);
mOkHttpClient.setConnectTimeout(REQ_TIMEOUT, TimeUnit.SECONDS);
mOkHttpClient.setReadTimeout(REQ_TIMEOUT, TimeUnit.SECONDS);

RestAdapter restAdapter = new RestAdapter.Builder()
                .setEndpoint(sEndpoint)
                .setClient(new OkClient(mOkHttpClient))
                .setLogLevel(RestAdapter.LogLevel.HEADERS)
                .build();
```

Any help will be greatly appreciated.

`retrofit.RetrofitError: failed to connect to api.xyz.ro/89.xx.yy.37 (port 80) after 15000ms`

**Comment by apoorvparijat** [comment]
@Zhelyazko's solution worked. You need to disable `tcp_timestamp` by changing `sysctl` configuration on the API server. Also, if you have other services on the same machine i.e. Redis etc., you should watch out for how this affects them.

**Comment by tbnzey** [comment]
http://www.jianshu.com/p/dde236d7211d

**Comment by tbnzey** [comment]
Solution details address:http://www.jianshu.com/p/dde236d7211d
