### ISSUE TITLE
Android support in 2.0.0+

### ISSUE THREAD

**Issue by delor** [square/okhttp#1052]
OkHttp 2.0.1-SNAPSHOT-c3a3199 uses OkIO 1.0.1 which uses Java 7 API.
Does that mean that OkHttp will no longer be usable in Android?

**Comment by yoganlegendkiller** [comment]
can you guys please tell me how to resolve this issue

**Comment by swankjesse** [comment]
@yoganlegendkiller ignore this warning. If your program is crashing, this is not the cause.
