### ISSUE TITLE
Do cookies in OkHttp

### ISSUE THREAD

**Issue by swankjesse** [square/okhttp#1061]
Right now we're using the platform's cookies, and that's broken. For example, [AOSP issue 75182](https://code.google.com/p/android/issues/detail?id=75182).

If we implemented our own cookie parsing, we could ship correct a cookie implementation on all platforms. Also, we could build a disk-based cookie store.

**Comment by swankjesse** [comment]
More reason: this is the last thing holding us to `java.net.URI`.
https://github.com/square/okhttp/issues/1836

**Comment by rfc2822** [comment]
I have found another bug in Android's CookieStore which will cause URLs with explicit port numbers to be ignored (`CookieStore.get()` always returns `null`, even if a cookie for exactly this URL was set before): https://code.google.com/p/android/issues/detail?id=193475

**Comment by swankjesse** [comment]
Current plan: change the `CookieJar` interface to accept a new `Cookie` type. Then consider this case closed.

**Comment by swankjesse** [comment]
https://github.com/square/okhttp/pull/2162
https://github.com/square/okhttp/pull/2167
https://github.com/square/okhttp/pull/2173
https://github.com/square/okhttp/pull/2176
