### ISSUE TITLE
Throw IOException in onResponse looks odd

### ISSUE THREAD

**Issue by floating-cat** [square/okhttp#1066]
Look at this [example](https://github.com/square/okhttp/blob/master/samples/guide/src/main/java/com/squareup/okhttp/recipes/AsynchronousGet.java) for Asynchronous Get

``` java
@Override public void onResponse(Response response) throws IOException {
    if (!response.isSuccessful()) throw new IOException("Unexpected code " + response);
    ...
```

When you throw `IOException` which would catch in [Call.java](https://github.com/square/okhttp/blob/2d6b3770d9ef3424a12c4c243596a34cc07cbef1/okhttp/src/main/java/com/squareup/okhttp/Call.java) 

``` java
@Override protected void execute() {
  boolean signalledCallback = false;
  try {
    Response response = getResponse();
    if (canceled) {
      signalledCallback = true;
      responseCallback.onFailure(request, new IOException("Canceled"));
    } else {
      signalledCallback = true;
      engine.releaseConnection();
      responseCallback.onResponse(response);
    }
  } catch (IOException e) {
    // Look at this line
    if (signalledCallback) throw new RuntimeException(e); // Do not signal the callback twice!
      responseCallback.onFailure(request, e);
  } finally {
    dispatcher.finished(this);
  }
}
```

If you want throw `IOException` in `onResponse`. The OkHttp will catch it and throw `RuntimeException`, then program would crash and you could never handle this `IOException`.

**Comment by olayinkasf** [comment]
I can't understand why the IOException is handled by the API. The callbacks are well defined IMO. Methods that throws IOException when invoked in the onResponse callback should be handled by the implementing class. It is confusing. I am using it in a background thread and whatever Runtime exception thrown by the API didn't propagate to the UI which makes an application difficult to debug.
