### ISSUE TITLE
Explore Mock OkHttpClient Testing Implementation

### ISSUE THREAD

**Issue by JakeWharton** [square/okhttp#1096]
An `OkHttpClient` instance which can be scripted similar to `MockWebServer`. The advantages here are explicit control over the objects passed back to the caller and much lower overhead.

**Comment by JakeWharton** [comment]
https://github.com/square/retrofit/blob/763fe1639e3348480214873323caacd00cbd7fa6/retrofit/src/test/java/retrofit/MockClient.java

**Comment by gmazzo** [comment]
Hi guys, based on @swankjesse comment I've created this repo: https://github.com/gmazzo/okhttp-client-mock. I can make a PR to include it in your mock API if you like it.

**Comment by lucasoares** [comment]
Hello guys.. Any updates here? I'd love to see this feature as native on okhttpclient.

**Comment by yschimke** [comment]
Closing out as https://github.com/gmazzo/okhttp-client-mock is probably the right way to go here.

**Comment by gmazzo** [comment]
> Closing out as https://github.com/gmazzo/okhttp-client-mock is probably the right way to go here.

So, @yschimke are you interested in making it official?

**Comment by yschimke** [comment]
I think official is a link here https://square.github.io/okhttp/works_with_okhttp/ and you are already there.

**Comment by gmazzo** [comment]
Ohh great then, I didn't note it before
