### ISSUE TITLE
Blacklist pinned certificate

### ISSUE THREAD

**Issue by veeti** [square/okhttp#1135]
A nice addition to the pinning API would be the ability to blacklist individual certificates (for example, if one is compromised yet the user still wants to trust the CA).

**Comment by mpp-doric** [comment]
Dead link update https://github.com/square/okhttp/blob/master/samples/guide/src/main/java/okhttp3/recipes/CheckHandshake.java

**Comment by doridori** [comment]
dead link update https://github.com/square/okhttp/blob/master/samples/guide/src/main/java/okhttp3/recipes/CheckHandshake.java
