### ISSUE TITLE
Investigate http2 extensions

### ISSUE THREAD

**Issue by adriancole** [square/okhttp#1180]
[http2 may be extended](http://tools.ietf.org/html/draft-ietf-httpbis-http2-16#section-5.5) via settings, frames, and error codes. Our current implementation must ignore unknown or unexpected values accordingly.

In the future, we may want to support extensions such as [AltSvc](http://tools.ietf.org/html/draft-ietf-httpbis-alt-svc-05) or [WebSocket](http://tools.ietf.org/html/draft-hirano-httpbis-websocket-over-http2-01).

Supporting an extension could be as easy as adding a frame reader by type. However, the spec allows extensions to modify existing frames, for example, allowing frame length to be longer.

At the moment, there are few http2 extension drafts in the [ietf](https://datatracker.ietf.org/doc/search/?name=http2&rfcs=on&activedrafts=on&sort=). The most mature extension is [AltSvc](http://tools.ietf.org/html/draft-ietf-httpbis-alt-svc-05), used to facilitate discovery of alternate endpoints based on an alpn id.

Before we start, we need to decide on the following:

Do we support extensions via curation (ex. add code to okhttp for each desired extension) or do we open extension points (settings, frames, and error codes)?

**Comment by swankjesse** [comment]
I'm going to close this, and re-open a specific issue for AltSvc if/when there's a demand.
