### ISSUE TITLE
Stream was reset: PROTOCOL_ERROR, while using Retrofit in 3G network

### ISSUE THREAD

**Issue by WOSHICAIXIANFENG** [square/okhttp#1195]
I am using Retrofit for networking calls in my application. The app is really working fine with great speed. Thanks for the wonderful library. But, It is working only in wi-fi. If i run the app in 3G network, throwing the error. stream was reset: PROTOCOL_ERROR,  while using Retrofit in 3G network

Refer to:
http://stackoverflow.com/questions/26971008/stream-was-reset-protocol-error-while-using-retrofit-in-3g-network

**Comment by swankjesse** [comment]
Not actionable. If you could tell us the URL you're seeing this on, that'll help.

**Comment by mgp** [comment]
I can reproduce this with the URL https://www.khanacademy.org/api/internal/articles/xbdcfe503?casing=camel.

Here's a code snippet:

```
Request request = new Request.Builder()
    .url("https://www.khanacademy.org/api/internal/articles/xbdcfe503?casing=camel")
    .build();

OkHttpClient client = new OkHttpClient();
Call call = client.newCall(request);
call.enqueue(new Callback() {
  @Override
  public void onFailure(Request request, IOException e) {
    System.err.println("article error=" + e);
  }

  @Override
  public void onResponse(Response response) throws IOException {
    System.out.print("article response!");
  }
});
```

It fails with:

```
article error=java.io.IOException: stream was reset: PROTOCOL_ERROR
```
Upon switching to [android-async-http](http://loopj.com/android-async-http/), I can download the content correctly.
