### ISSUE TITLE
Pre-encoded name and/or value strings for form URL bodies.

### ISSUE THREAD

**Issue by JakeWharton** [square/okhttp#1215]
Retrofit allows specifying pre-encoded values for both name and value. Putting this capability in OkHttp would allow a Retrofit v2 to completely remove its knowledge of form URL encoding.

The API for this is pretty awful, not sure if we can come up with something better.
```java
void add(String name, boolean encodeName, String value, boolean encodeValue);
```

**Comment by swankjesse** [comment]
Punting to 2.4, wherein I'm going to add our own URL class.
