### ISSUE TITLE
ConnectionPool is broken with MAX_CONNECTIONS_TO_CLEANUP

### ISSUE THREAD

**Issue by swankjesse** [square/okhttp#1239]
After merging @nfuller's recent leak fix, I noticed we have a new problem. Previously we were pretty eager to trim the idle connections down to the promised limits. An application that quickly created 100 connections would just as quickly see 95 of those connections evicted!

With the new fix, it looks like we won't evict more than once every 5 minutes, and we won't evict more than 2 connections per round. That means that we can exceed our promised limits.

We can fix this by replacing `Thread.sleep()` with `wait()` and invoke `notify()` where we're currently calling `scheduleCleanupAsRequired`. That'll cause the cleanup thread to take immediate action.

**Comment by nfuller** [comment]
Thanks for fixing this!
