### ISSUE TITLE
java.lang.IllegalStateException: closed when trying to access response in onResponse(Response response)

### ISSUE THREAD

**Issue by maboueita** [square/okhttp#1240]
I get 

```
java.lang.IllegalStateException: closed
            at com.squareup.okhttp.internal.http.HttpConnection$FixedLengthSource.read(HttpConnection.java:455)
            at okio.Buffer.writeAll(Buffer.java:594)
            at okio.RealBufferedSource.readByteArray(RealBufferedSource.java:87)
            at com.squareup.okhttp.ResponseBody.bytes(ResponseBody.java:56)
            at com.squareup.okhttp.ResponseBody.string(ResponseBody.java:82)
```

when trying to access the response body using: 

```
response.body().string();
```

inside onResponse(Response response) callback.

**Comment by GavinDon** [comment]
You can only call string() once.  true

**Comment by fattoLiu** [comment]
You can call string() once. But I don't know why

**Comment by artem-zinnatullin** [comment]
Because response body can be huge so OkHttp doesn’t store it in memory, it reads it as a stream from network when you need it.

When you read body as a string() OkHttp downloads response body and returns it to you without keeping reference to the string, it can’t be downloaded twice without new request.

On Tue, Jul 19, 2016 at 5:46 PM fattolium

<
mailto:fattolium <notifications@github.com>
> wrote:

You can call string() once. But I don't know why

—

You are receiving this because you are subscribed to this thread.

Reply to this email directly,
https://github.com/square/okhttp/issues/1240#issuecomment-233655904
, or

**Comment by GavinDon** [comment]
once requst  once download

**Comment by wuzhaohui026** [comment]
response.body.string should be defined as a variable.but in fact ,i also don't why this.

**Comment by n-belokopytov** [comment]
Pffft. At least give people the option to do that if they want! Exceptions don't help much.

**Comment by fattoLiu** [comment]
@artem-zinnatullin thanks very much!

**Comment by choudhury-abhishek29** [comment]
Thanks a lot....solved a huge problem for me 👍

**Comment by eywalink** [comment]
if you have used response.body().string() once then you can new one same response  and return in case that you will use  response.body().string() again.

**Comment by rozhok** [comment]
At least it would be nice to add explanation to javadocs about this.
I just broke my production because of twice call to `string()`

**Comment by swankjesse** [comment]
Which Javadocs did you read? That’s where we should add such a note.

**Comment by JakeWharton** [comment]
It's documented on ResponseBody.

**Comment by rozhok** [comment]
I've read javadocs for `string()` method in `ResponseBody`.

**Comment by KaNcHeR** [comment]
Try the following:

```
ResponseBody responseBodyCopy = response.peekBody(Long.MAX_VALUE);
responseBodyCopy.string();
```

it works for me

**Comment by MarcinMoskala** [comment]
@KaNcHeR It looks like a dirty hack, but it works :D Thanks a lot

**Comment by quanglth** [comment]
Don't try to use response.body.string() directly. Just using like below:
`ResponseBody responseBody = response.body();`
`String content = responseBody.string();`
`// Do something with "content" variable`

**Comment by gelbertgel** [comment]
@Override
            public void onResponse(@NonNull Call call, @NonNull Response response) {
                if (response.isSuccessful()) {

                    try {

                        final String url = response.request().url().toString();
                        Log.i(TAG, " url: " + url);

                        Thread diffThread = new Thread(new Runnable() {
                        @Override
                         public void run() {

                                try {

                                    System.setProperty("http.keepAlive", "false");

                                    ResponseBody responseBody = response.body();

                                    if (responseBody == null) {
                                        return;
                                    }

                                    String source = responseBody.string();
                                    } catch(Exception e){
                                      ---> Exception! message:closed
                                    }
      }

How can I do that? It gives an error if it is in a different thread ?

**Comment by wnchen** [comment]
Response body is not stored in memory. .string() reads as stream from network. That is it.

**Comment by sumanpula** [comment]
Try storing response in in string variable separately like this,

String res = response.body().string();

Then res.

**Comment by yaitskov** [comment]
how come. it is not working

**Comment by Dreamerpro** [comment]
For me the problem was the wrapper function that returned `Response `object. Like this
```
callAPI(...){
.....
client.newCall(request).execute().also { 
        return it
    }
...
```

**Comment by ramchhabra** [comment]
I tried something like this 

Response response =  chain.proceed(newRequest);
Response responseTmp =  chain.proceed(newRequest);

responseTmp.body().string();

and it works

**Comment by JakeWharton** [comment]
That makes two HTTP requests. You don't want to do that.

**Comment by ernest-kiwele** [comment]
Adding this bit as it may help someone else. I was puzzled to encounter the very same exception while calling `ResponseBody.string()` **only once**.

The problem, I realized later, was due to the execution context of my request: using a try with resources block with the response causes the same problem when the response body is read outside of the try block:

	try (Response response = client.newCall(request.build()).execute()) {
		return response;
	} //response.close() called implicitly by the JVM

If `response` is processed outside this method, the `IllegalStateException` is equally thrown. That's because the try with resources block will call `response.close()`. An easy workaround for such a design is to read the body in the try block itself and return it (or both it and the response object in a different data structure)

**Comment by mrHesham** [comment]
just call response.close();


@Override
                public void onResponse(Call call, Response response) throws IOException {


                    try {


                        final int code  = response.code();
                        final String body = response.body().string();
                        response.close();

                        Login.this.runOnUiThread(new Runnable() {
                            @Override
                            public void run() {
		                //do any thing with body variable 
				Print(body);	
                            }
                        });
                    } catch (Exception ex) {
                        String sss = ex.getMessage().toString();
                    }

                }

**Comment by mvrueden** [comment]
I encountered the same issue, receiving an Exception when reading the response, e.g. `responseBody.string()`.
However in my code I only use it once.
BUT: When debugging, I added (by accident) a watch expression to `responseBody.string()` which then caused the actual execution to fail.

**Comment by arsalanImtiaz455** [comment]
> Try the following:
> 
> ```
> ResponseBody responseBodyCopy = response.peekBody(Long.MAX_VALUE);
> responseBodyCopy.string();
> ```
> 
> it works for me

why each api gets called twice ?
I am stuck with this
