### ISSUE TITLE
HTTP Alternative Services

### ISSUE THREAD

**Issue by adriancole** [square/okhttp#1258]
Alternate Services push alternate means to access resources of an origin, particularly on a different host/port or even protocol. This is works via headers in http 1.1 or an extension frame in HTTP 2.

https://datatracker.ietf.org/doc/draft-ietf-httpbis-alt-svc/

**Comment by swankjesse** [comment]
https://www.mnot.net/blog/2016/03/09/alt-svc

**Comment by yschimke** [comment]
Won't fix.  last asked for in 2016.

**Comment by adriancole** [comment]
plus no end user asked (i only did from a spec completion pov and thought it was neat)
