### ISSUE TITLE
Feature request: Control the pipelines

### ISSUE THREAD

**Issue by hrj** [square/okhttp#1281]
### Goal
In [gngr](https://github.com/UprootLabs/gngr), we would like to reap the benefits of `http(s)/SPDY` pipelining, but would also like to ensure that requests from different contexts (windows / frames / tabs) are not multiplexed on the same socket since it allows the server to track the user across those different contexts.

Aside, it would be fine to have a common thread pool since it has no privacy implications AFAICT. It will actually be desirable to have a common thread pool since it will conserve resources.

### Questions / Ideas
Is it possible to avoid this *mixing* of contexts while pipelining? If so, what is the best way to do it?
  * Should we create a separate OkHttpClient for every context? Will this result in separate thread pools?
  * Is it possible to indicate the context through a request header (that will be stripped by OkHttp on the way out)? The header could be a simple integer value. The advantage with this method may be that a single OkHttpClient (and its associated thread pool) can be shared by the entire app.

**Comment by swankjesse** [comment]
It's a tough situation because everything has the potential of leaking user information. For example, the response cache can leak user identity if servers use unique ETags or even unique modified dates!

Right now OkHttp doesn't offer trust zones within one OkHttp client, and some design decisions unfortunately assume mutual trust. For example, OkHttp will use one shared ConnectionPool even if you use multiple OkHttpClient instances. You need to manually set up a ConnectionPool to avoid that.

My best advice is to use distinct OkHttpClient instances in each trust zone. You'll need to manually configure each with its own connection pool.

Choosing many smaller zones instead of fewer large zones will have a performance cost. Also its potentially annoying if I keep getting signed out everytime I change tabs!

**Comment by hrj** [comment]
Thanks for the response. I think we can live with separate connection pools per profile (user / incognito profiles) for now. I will analyse it further.

--------

Agreed, there is potential for leaking information through other sources, and we want to tackle each source separately, wherever we can.

> Also its potentially annoying if I keep getting signed out everytime I change tabs!

Agreed; though I am not sure if this is directly related to distinct connection pools. Cookies, when enabled, will be shared across tabs. And for those domains with cookies enabled, sharing connections is not a concern.

**Comment by hrj** [comment]
(This is rather long-winded and off-topic; can be safely ignored. If an okhttp client provides a way to isolate the connection pools it would simplify our design. But I totally understand if it is not going to be on okhttp's roadmap.)

-----------

I just realized that I didn't communicate the idea in detail, and have a hunch about what led to this response by you ( @swankjesse ):
 
> Also its potentially annoying if I keep getting signed out everytime I change tabs!

We don't intend to isolate *all* tabs and their associated requests but only those with a separate tab origin. (Replace tab with window / frame for more variations on the theme). Some examples:

#### scene 1
Two tabs, both viewing `x.y.z.com`. Here it is fine to share connection pools, cookies and other state in the two tabs (modulo the usual same-origin policies).

#### scene 2
Two tabs, one tab is viewing `x.y.z.com` while the other is viewing `p.q.r.com`. These two would need to be isolated as much as possible:
  * Connection pools need to be isolated
  * Cookie store would be shared, but the choice of enabling cookies is isolated.
  * Request Cache could be potentially shared. Whether to share the cache or not in this scenario is an open question right now; the choice could be made configurable perhaps. This is because the cache could leak information via headers (as you pointed out) or even timing profiles. This also applies to other state such as HSTS headers.

#### scene 3
Two tabs, one viewing `y.z.com` and the other viewing `x.y.z.com`.
This is a grey area, and there are many variations possible here. A strict profile will behave similar to scene 2, else it will be similar to scene 1.
