### ISSUE TITLE
java.lang.NoClassDefFoundError: com.squareup.okhttp.OkUrlFactory

### ISSUE THREAD

**Issue by Ke3rthi** [square/okhttp#1303]
Hello,

I am currently using Picasso 2.4.0 along with okhttp 2.2.0 to place a list of images from a Secured set of URLs in a listView.

                Picasso.Builder builder = new Picasso.Builder(context);
                Picasso picasso =  builder.downloader(new OkHttpDownloader(context) {
                    @Override
                    protected HttpURLConnection openConnection(Uri uri) throws IOException {
                        HttpURLConnection connection = super.openConnection(uri);
                        HashMap<String,String> headers = new HashMap<String, String>();
                        addCookieInHashmap(headers);
                        connection.setRequestProperty("Cookie", headers.get("Cookie"));
                        return connection;
                    }
                }).build();
                picasso.load("xxxxx").into(holder.user_thumbnail);

I keep getting "java.lang.NoClassDefFoundError: com.squareup.okhttp.OkUrlFactory" error at line number 2 of the above code. I am using IntelliJ IDE for development. Please suggest anything that would help fix this error.

Thanks.

**Comment by swankjesse** [comment]
This question is more appropriate for Stackoverflow, not GitHub. Here we only want feature requests & bug reports, not configuration questions.
