### ISSUE TITLE
IOException from com.squareup.okhttp.Callback 

### ISSUE THREAD

**Issue by andrewchen5678** [square/okhttp#1335]
When an IOException occurs inside com.squareup.okhttp.Callback.onResponse or onFailure. It is swallowed instead of rethrown, which sometimes causes surprise because other exceptions are not swallowed.

**Comment by swankjesse** [comment]
@andrewchen5678  any recommendations?

**Comment by andrewchen5678** [comment]
I think this part needs to be refactored, it is catching IOException from onFailure and onResponse but not other exceptions: com.squareup.okhttp.Call.AsyncCall#execute

```
    @Override protected void execute() {
      boolean signalledCallback = false;
      try {
        Response response = getResponseWithInterceptorChain();
        if (canceled) {
          signalledCallback = true;
          responseCallback.onFailure(originalRequest, new IOException("Canceled"));
        } else {
          signalledCallback = true;
          responseCallback.onResponse(response);
        }
      } catch (IOException e) {
        if (signalledCallback) {
          // Do not signal the callback twice!
          logger.log(Level.INFO, "Callback failure for " + toLoggableString(), e);
        } else {
          responseCallback.onFailure(engine.getRequest(), e);
        }
      } finally {
        client.getDispatcher().finished(this);
      }
    }
```

**Comment by swankjesse** [comment]
What behavior would you like?

**Comment by andrewchen5678** [comment]
Don't catch IOException and other exceptions from onFailure or onResponse I guess.

**Comment by JakeWharton** [comment]
That won't change behavior. It will just propagate and silently crash a
thread in the pool which will be transparently recreated.
