### ISSUE TITLE
OkHttpClient API to trust a PEM file

### ISSUE THREAD

**Issue by Lobooo** [square/okhttp#1336]
Hi, how can I load a self signed certificate using okhttp?
Using apache standard library I just register my SocketFactory and it works like this:

public class HttpClientUtil {
    public static DefaultHttpClient getNewHttpClient() {
        try {
            KeyStore trustStore = KeyStore.getInstance(KeyStore.getDefaultType());
            trustStore.load(null, null);

            SSLSocketFactory sf = new MySSLSocketFactory(trustStore);
            sf.setHostnameVerifier(SSLSocketFactory.ALLOW_ALL_HOSTNAME_VERIFIER);

            HttpParams params = new BasicHttpParams();
            HttpProtocolParams.setVersion(params, HttpVersion.HTTP_1_1);
            HttpProtocolParams.setContentCharset(params, HTTP.UTF_8);

            SchemeRegistry registry = new SchemeRegistry();
            registry.register(new Scheme("http", PlainSocketFactory.getSocketFactory(), 80));
            registry.register(new Scheme("https", sf, 443));

            ClientConnectionManager ccm = new ThreadSafeClientConnManager(params, registry);

            return new DefaultHttpClient(ccm, params);
        } catch (Exception e) {
            return new DefaultHttpClient();
        }
    }

}

public class MySSLSocketFactory extends SSLSocketFactory {
    SSLContext sslContext = SSLContext.getInstance("TLS");

    public MySSLSocketFactory(KeyStore truststore) throws NoSuchAlgorithmException, KeyManagementException, KeyStoreException, UnrecoverableKeyException {
        super(truststore);

        TrustManager tm = new X509TrustManager() {
            public void checkClientTrusted(X509Certificate[] chain, String authType) throws CertificateException {
            }

            public void checkServerTrusted(X509Certificate[] chain, String authType) throws CertificateException {
            }

            public X509Certificate[] getAcceptedIssuers() {
                return null;
            }
        };

        sslContext.init(null, new TrustManager[] { tm }, null);
    }

    @Override
    public Socket createSocket(Socket socket, String host, int port, boolean autoClose) throws IOException, UnknownHostException {
        return sslContext.getSocketFactory().createSocket(socket, host, port, autoClose);
    }

    @Override
    public Socket createSocket() throws IOException {
        return sslContext.getSocketFactory().createSocket();
    }
}

**Comment by JakeWharton** [comment]
Register your socket factory with your OkHttpClient.

**Comment by Lobooo** [comment]
@JakeWharton Sorry I cannot find how to Register in OkHttp,can you give me some details？

**Comment by Lobooo** [comment]
I did something as below，but not work，how to Register？

public class OkHttpClientUtil {
    public static OkHttpClient getUnsafeOkHttpClient() {

        try {
            // Create a trust manager that does not validate certificate chains
            TrustManager[] trustAllCerts = new TrustManager[] {
                    new X509TrustManager() {
                        @Override
                        public void checkClientTrusted(java.security.cert.X509Certificate[] chain, String authType) throws CertificateException {
                        }

                        @Override
                        public void checkServerTrusted(java.security.cert.X509Certificate[] chain, String authType) throws CertificateException {
                        }

                        @Override
                        public java.security.cert.X509Certificate[] getAcceptedIssuers() {
                            return null;
                        }
                    }
            };

            // Install the all-trusting trust manager
            SSLContext sslContext = SSLContext.getInstance("TLS");
            sslContext.init(null, trustAllCerts, new java.security.SecureRandom());
            // Create an ssl socket factory with our all-trusting manager
            SSLSocketFactory sslSocketFactory = sslContext.getSocketFactory();
            OkHttpClient okHttpClient = new OkHttpClient();
            okHttpClient.setFollowSslRedirects(true);
            okHttpClient.setSslSocketFactory(sslSocketFactory);
            okHttpClient.setHostnameVerifier(new HostnameVerifier() {
                @Override
                public boolean verify(String hostname, SSLSession session) {
                    return true;
                }
            });

            return okHttpClient;
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
}

**Comment by JakeWharton** [comment]
That's precisely what I would have suggested. What errors are you seeing?

**Comment by Lobooo** [comment]
I get two ssession through OkHttp，one is for login，another for captcha getting，but sometimes captcha return null，It works well when I use HttpClient

发自我的 iPhone

**Comment by manuel-sejourne** [comment]
I need to do this too. Can someone have a sample working ?

**Comment by swankjesse** [comment]
Needs a recipe for our recipes page.

**Comment by swankjesse** [comment]
There's a lot to cover on how to to customize trust with OkHttp:

 * Which certificate authorities to trust, including self-signed certificates
 * How to get the PEM files for their root certificates
 * How to import them into a JKS (Java Key Store) or BKS (Bouncy Castle Key Store for Android)
 * How to load that keystore at runtime, and use it to get a SslSocketFactory.

Plus the keystores need passwords, but those passwords don't add security. At least on Android, the keystore and its password hold no secrets, and are expected to be installed on untrusted user's devices.

To do this properly we'd want a sample program that can accept `.pem` files and emits the corresponding `.jks` / `.bks` file. Even better, teach OkHttp to accept PEM files natively. (Is this actually hard?)
