### ISSUE TITLE
1XX response codes should work properly

### ISSUE THREAD

**Issue by swankjesse** [square/okhttp#1337]
Making this work for uploads is worth doing. We should do it, being mindful of the consequences for http/2.0.

**Comment by swankjesse** [comment]
Tagged for 2.3, though I might push it back.

**Comment by swankjesse** [comment]
This elite issue is a duplicate!
https://github.com/square/okhttp/issues/675

**Comment by guillerodriguez** [comment]
Issue #2257 ("Support HTTP status 102 Processing") was closed as a duplicate of this one, and this one in turn was closed as a duplicate of #675. However #675 only added support for HTTP status 100, not for 102. Perhaps this issue should be reopened?
