### ISSUE TITLE
Option to bind MockWebServer not on loopback

### ISSUE THREAD

**Issue by swankjesse** [square/okhttp#1342]
Per https://twitter.com/b4taylor/status/558017198107537408

**Comment by JakeWharton** [comment]
:+1:

I don't think I can emoji in email...

**Comment by brennantaylor** [comment]
What do you guys think? Implementing `start(String hostname, int port)` where hostname is default `"localhost"` in the other versions of `start(...)`?

**Comment by JakeWharton** [comment]
Maybe `start(InetAddress, int port)`?

**Comment by JakeWharton** [comment]
And oh, hey. My email emoji worked!

**Comment by swankjesse** [comment]
Would `start(InetSocketAddress)` work? 

I like that and `start(InetAddress, port)`.

**Comment by JakeWharton** [comment]
This happened. On `master`.
