### ISSUE TITLE
TLS fallback negotiation could be smarter

### ISSUE THREAD

**Issue by nfuller** [square/okhttp#1343]
Demonstrated by tests in this commit:

https://github.com/nfuller/okhttp/commit/a590ddb385d699ecf1d8968bf5e75f5d97120299

This is a compact demonstration of the behavior that is being fixed/modified by square#1339.

2 of the tests actually pass before and after but are useful demonstrations of behavior and act as regression tests for square#1339.

The tests (with minor changes) are included in square#1339.

3 new tests in CallTest:

firstConnectionSpecAvoidedWhenPrimaryTlsVersionNotSupported
- Fails because the connection is being attempted twice with the same
  enabled protocols (TLSv1). OkHttp should only make one attempt to
  connect  to the server with any given configuration.

secondConnectionSpecAvoidedWhenPrimaryTlsVersionNotSupported
- Succeeds, but only because the second connection attempt is being
  made with zero enabled TLS versions. It finds this out too late:
  it should not have made the raw socket connection in the first place.

requestExceptionDoesNotCauseTlsDowngrade
- Succeeds. OkHttp correctly recognizes that the DISCONNECT_AFTER_REQUEST
  causes an Exception that should not cause a re-negotiation. This
  is achieved in the RouteSelector in the existing code and because negotiation is handled by
  Connection / SocketConnector in square#1339

**Comment by swankjesse** [comment]
I think we've got this fixed with https://github.com/square/okhttp/pull/1388.

**Comment by swankjesse** [comment]
(@nfuller correct me if I'm wrong!)

**Comment by nfuller** [comment]
I think one "issue" remains, but I may be the only person who cares. I'm planning to do a follow up fix for it and we can discuss that then.

firstConnectionSpecAvoidedWhenPrimaryTlsVersionNotSupported
- Fails because the connection is being attempted twice with the same
  enabled protocols (TLSv1). OkHttp should only make one attempt to
  connect  to the server with any given configuration.
