### ISSUE TITLE
Should OkHttp always add Proxy.NO_PROXY to the results of ProxySelector.select()?

### ISSUE THREAD

**Issue by nfuller** [square/okhttp#1344]
Not sure this is actually an issue and what the implications are if it is removed.

It seems odd that when I have a ProxySelector set there will be an attempt to connect directly even when the ProxySelector doesn't suggest doing so.

For multi-homed hosts with N IPs this could lead to another N socket connection attempts. I assume if people have set a proxy they're not expecting to try direct connections.

RouteSelector.resetNextProxy() is directly injecting a direct connection to whatever result ProxySelector returns.

**Comment by swankjesse** [comment]
Any change here could break applications. At the moment it's completely safe to install a ProxySelector that returns an unreachable proxy.

**Comment by nfuller** [comment]
Not sure where I stand on this one myself. I created this to have / record the debate. I'll see if anybody on the Android side has a strong opinion.

When I saw the direct connection attempts I was surprised, given the configuration I had.

I assume one implication of the direct connection being tried last is that any failures the caller ends up seeing will be from the direct attempt might mask failures from any previous, failed proxied attempts.

Any appetite for making this configurable (with the default to be to leave it on)?

**Comment by nfuller** [comment]
Also in support of Jesse's response: If I'm reading it correctly it looks like Android has done it at least as far back as JB, suggesting we wouldn't want to change it there.

https://android.googlesource.com/platform/libcore/+/jb-mr2-release/luni/src/main/java/libcore/net/http/HttpConnection.java

Line 128.

**Comment by swankjesse** [comment]
Yup. I don't particularly like proxy selectors, and we don't use them in our applications, so I'm not in any rush to improve their weird behavior.

**Comment by swankjesse** [comment]
No action to take here.
