### ISSUE TITLE
alternatives to content-length -1 MultipartBuilder

### ISSUE THREAD

**Issue by felipeska** [square/okhttp#1349]
I am doing the following test:
````
 @Test
  public void testMultipartBuilder() throws Exception {
    MockWebServer mockWebServer = new MockWebServer();
    mockWebServer.play();
    OkHttpClient client = new OkHttpClient();
    mockWebServer.setDispatcher(new Dispatcher() {
      @Override
      public MockResponse dispatch(RecordedRequest request) throws InterruptedException {
        if (request.getHeader("Content-Length") == null) {
          return new MockResponse()
                  .setStatus("HTTP/1.1 411")
                  .setResponseCode(411)
                  .addHeader("content-type: text/plain; charset=utf-8")
                  .setBody("Length Required");
        } else
          return new MockResponse()
                  .setStatus("HTTP/1.1 200")
                  .setResponseCode(Constants.HTTP_OK)
                  .addHeader("content-type: text/plain; charset=utf-8")
                  .setBody("server: nginx");
      }
    });

    RequestBody requestBody = new MultipartBuilder()
            .type(MultipartBuilder.FORM)
            .addFormDataPart("title", "Square Logo")
            .addFormDataPart("image", null,
                    RequestBody.create(MediaType.parse("image/png"),
                            new File("website/static/logo-square.png")))
            .build();
    com.squareup.okhttp.Request request = new com.squareup.okhttp.Request.Builder()
            .url(mockWebServer.getUrl("/images/"))
            .post(requestBody)
            .build();
    com.squareup.okhttp.Response response = client.newCall(request).execute();
    assertTrue(response.isSuccessful());
  }
```
 the  ```contentLength()``` from ```MultipartBuilder``` returns the number of bytes that will be written to out in a call to ```writeTo```, or -1 if that count is unknown.

As this happens it does not send the header  ``Content-Length``, and my need this header to process the request.

what options exist to obtain the content-length?

**Comment by JakeWharton** [comment]
Write the multipart body to a `Buffer`. Then use that `Buffer` as the body for the actual request.

**Comment by felipeska** [comment]
Can be?
``` 
Buffer buffer = new Buffer();
requestBody.writeTo(buffer);
com.squareup.okhttp.Request request = new com.squareup.okhttp.Request.Builder()
            .url(mockWebServer.getUrl("/images/"))
            .post(RequestBody.create(MultipartBuilder.FORM,buffer.readByteArray()))
            .build();
```

**Comment by JakeWharton** [comment]
Hmm, it's unfortunate that you to call `.readByteArray()`. Maybe we should allow passing a `Buffer`. I'll have to see if that has any adverse effects.

**Comment by felipeska** [comment]
I Agree. 
```
public static RequestBody create(final MediaType contentType, final Buffer buffer) {
    return new RequestBody() {
      @Override public MediaType contentType() {
        return contentType;
      }

      @Override public long contentLength() {
        return buffer.readByteArray().length;
      }

      @Override public void writeTo(BufferedSink sink) throws IOException {
        Source source = buffer;
        try {
          sink.writeAll(source);
        } finally {
          Util.closeQuietly(source);
        }
      }
    };
  }
```

**Comment by JakeWharton** [comment]
Use `buffer.size()`

**Comment by felipeska** [comment]
works fine , but it would be a viable option ``Request`` accepted ``Buffer``  as a parameter?

**Comment by swankjesse** [comment]
Unfortunately since `Buffer` is mutable, we'd need to defensively copy in that case, which would be inefficient. Does tempt me to offer an optimized `Buffer.byteString()` that shares pages with the backing-buffer.

**Comment by felipeska** [comment]
Definitely not a good choice
in this case is possible create a method that takes a ``RequestBody`` and new ``RequestBody`` that knows its content length. It is not always necessary to know the content-length

**Comment by vbokan** [comment]
I'm currently having similar situation where server didn't want to work with <code>Transfer-Encoding=chunked</code> instead of <code>Content-Length</code> header so I had to use @felipeska 's approach with one change which made it complete.

Passing <code>MediaType.FORM</code> to <code>create</code> method removed boundary which rendered multipart request useless. Instead of it, I've passed <code>requestBody.contentType()</code> and maintained same <code>Content-Type</code> which was built by <code>MultipartRequestBuilder</code>.

TBH, not very happy and proud with solving it this way (allocating buffer for request just to be rewritten) since I feel there should be some way to choose this due to different server support.

**Comment by swankjesse** [comment]
@vbokan yup. We can make `MultipartRequestBuilder` compute the content-length in its content-length method, but doing so is somewhat ugly. Made less so by an Okio change that's currently stalled:
https://github.com/square/okio/pull/98

**Comment by felipeska** [comment]
@swankjesse There is the possibility to change a Request with an interceptor (Network Interceptors)?

**Comment by felipeska** [comment]
@vbokan You can also use an Application Interceptor. still not the best option.

```
public class ContentLengthInterceptor implements Interceptor {
  @Override
  public Response intercept(Chain chain) throws IOException {
    Request originalRequest = chain.request();
    if (originalRequest.body().contentLength() != -1) {
      return chain.proceed(originalRequest);
    }

    Request customRequest = originalRequest.newBuilder()
            .method(originalRequest.method(), requestBodyWithContentLength(originalRequest.body()))
            .build();
    return chain.proceed(customRequest);
  }

  private RequestBody requestBodyWithContentLength(RequestBody requestBody) throws IOException {
    Buffer buffer = new Buffer();
    try {
      requestBody.writeTo(buffer);
    } catch (IOException e) {
      throw new IOException("Unable to copy RequestBody");
    }
    return new RequestBody() {
      @Override
      public MediaType contentType() {
        return requestBody.contentType();
      }

      @Override
      public long contentLength() {
        return buffer.size();
      }

      @Override
      public void writeTo(BufferedSink sink) throws IOException {
        sink.write(ByteString.read(buffer.inputStream(), (int) buffer.size()));
      }
    };
  }
}
```

**Comment by tals** [comment]
I was just bitten by the same issue when trying to upload to S3.

The proposed workaround is problematic:
- It requires you to buffer the entire thing in-memory.
- It is very non-obvious.

**Comment by Sheikh-Aman** [comment]
I hope it is put in 2.3, would be great.
Till then, trying to use the `Buffer` method and get the work done..

**Comment by felipeska** [comment]
@Sheikh-Aman is sad to have to do this, if you can avoid using multipartBuilder .. or take the multipartBuilder legacy as he solves.

**Comment by sdholbs** [comment]
As a temporary workaround for me, I ended up going with using [ion](https://github.com/koush/ion#post-multipartform-data-and-read-json-with-an-upload-progress-bar) just for multipart image uploads.  Worked like a charm if anyone wants an alternative
