### ISSUE TITLE
Certificate pinning for self signed certificates

### ISSUE THREAD

**Issue by lwasyl** [square/okhttp#1352]
I've tried to pin certificate using example from `CertificatePinner` code, but it doesn't work. Specifically it instructs user to to:

```
String hostname = "publicobject.com";
CertificatePinner certificatePinner = new CertificatePinner.Builder()
    .add(hostname, "sha1/BOGUSPIN")
    .build();
OkHttpClient client = new OkHttpClient();
client.setCertificatePinner(certificatePinner);

Request request = new Request.Builder()
    .url("https://" + hostname)
    .build();
client.newCall(request).execute();
```
and then catch `SSLPeerUnverifiedException`. Unfortunately I only get following error: 
```
javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
```

Adding `client.setSslSocketFactory()` with socket factory that doesn't check certificates at all makes code fail with `HostnameNotVerified` error, and finally adding `setHostnameVerifier` makes certificate pinner work as expected.

Is it correct way to use certificate pinning for self signed certificates?

**Comment by swankjesse** [comment]
Certificate pinning adds additional constraints on which certificates are trusted. It doesn't replace the certificate-authority requirements, it adds to them. If you want to do self-signed certificates, you need to do that with a trust manager.
