### ISSUE TITLE
Verify timeouts don't round to zero

### ISSUE THREAD

**Issue by dain** [square/okhttp#1356]
The code for setting timeouts looks like
```java
  /**
   * Sets the default connect timeout for new connections. A value of 0 means no timeout.
   *
   * @see URLConnection#setConnectTimeout(int)
   */
  public final void setConnectTimeout(long timeout, TimeUnit unit) {
    if (timeout < 0) throw new IllegalArgumentException("timeout < 0");
    if (unit == null) throw new IllegalArgumentException("unit == null");
    long millis = unit.toMillis(timeout);
    if (millis > Integer.MAX_VALUE) throw new IllegalArgumentException("Timeout too large.");
    connectTimeout = (int) millis;
  }
```
The docs don't make clear that times less than 1ms will be rounded down to 0, which means no timeout.  This is obvious if you have an understanding of the Java socket apis, but is not to anyone else.  I suggest making any value between 1 and 999,999 nano seconds illegal.

**Comment by JakeWharton** [comment]
Why illegal and not just clamp to 1ms?

**Comment by JakeWharton** [comment]
Although I guess that's on parity with not allowing more than `Integer.MAX_VALUE`.
