### ISSUE TITLE
OutOfMemory

### ISSUE THREAD

**Issue by ppamorim** [square/okhttp#1362]
Hi , I'm using the library and on some devices is being invoked OutOfMemory When I of the .string().
The problem is notified by Crashlytics , it has helped me a lot to find out the problems in my app .
The problem occurs when performing this:

  response.body().string();

**Comment by JakeWharton** [comment]
Your response bodies are so large and/or so many that creating the byte arrays necessary to read them into memory and then creating the character arrays for creating the string is too large for your app to handle. Consider using either the byte stream or character stream methods on `ResponseBody` to read the response progressively.

There's no action for the library to take here.
