### ISSUE TITLE
Handilng authentication exception

### ISSUE THREAD

**Issue by busylee999** [square/okhttp#1395]
I faced the problem, now realization of Client use this scenario:
1. make request, if error (401 - Unauthenticate, interesting for issue context)
2. if 401 code of previous response, invoke Authenticator for specifying credentials and follow up request.

Consider credentials is wrong (for example user specified wrong credentials).
than next request will return 401 again, and this repeats MAX_FOLLOW_UPS times. After all it throws ProtocolException("Too many follow-up requests: ").

And question is: "How I can detect wrong credentials?"

There is urge way for client uses this HTTPClient is to detect count of equal requests or something the same now. It seems as spike.

Is there any different way to handle bad credentials?

**Comment by swankjesse** [comment]
You can test your credentials against the credentials of the unauthenticated request:
```
      @Override public Request authenticate(Proxy proxy, Response response) {
        System.out.println("Authenticating for response: " + response);
        System.out.println("Challenges: " + response.challenges());
        String credential = Credentials.basic("jesse", "password1");

        if (credential.equals(response.request().header("Authorization"))) {
          return null; // If we already failed with these credentials, don't retry.
        }

        return response.request().newBuilder()
            .header("Authorization", credential)
            .build();
      }
```

**Comment by swankjesse** [comment]
I've added this example and another to our recipes doc.
