### ISSUE TITLE
Not caching files that doesn't end with file extension

### ISSUE THREAD

**Issue by tajchert** [square/okhttp#1398]
Using Okhttp as Downloader cache for Picasso library.

Images from url's that ends with (example) ".png" are cached offline, but when url has some parameters (example) "...image.png?152354254" they are not cached offline at all. Default Downloader has same issue.

I had found problem when looking at that comment to other issue as I suspected wrong HTTP headers from server (which was not the case in my case): https://github.com/square/picasso/issues/237#issuecomment-25356614

Maybe showing some error in log and trying to cache it with removing everything after ".png? (jpg.. etc.) would be good solution?

**Comment by swankjesse** [comment]
It's actually the query string that's interfering. Here's a comment from the relevant code:
        // As recommended by the HTTP RFC and implemented in Firefox, the
        // max age of a document should be defaulted to 10% of the
        // document's age at the time it was served. Default expiration
        // dates aren't used for URIs containing a query.

**Comment by swankjesse** [comment]
The fix is for your server set a Cache-Control header explicitly.
