### ISSUE TITLE
OkHttpClient.setRetryOnConnectionFailure(true) 

### ISSUE THREAD

**Issue by akhilc1** [square/okhttp#1438]
Hi, I am trying to understand the use of retrying a connection and I checked inside OkHttpClient class. The value is set to an internal boolean variable 'retryOnConnectionFailure' inside the OkHttpClient class, but I don't see it being referenced anywhere else. Could anybody please help me understand how a connection retry happens inisde OkHttp?

**Comment by swankjesse** [comment]
Probably a better question for stackoverflow.

**Comment by swankjesse** [comment]
(This issues tracker is strictly for bug reports and feature requests.)
