### ISSUE TITLE
response.body().string and big data 

### ISSUE THREAD

**Issue by irut** [square/okhttp#1441]
hi boys, i have a problem con okhttp response data:

 final OkHttpClient client = new OkHttpClient();       
        Request request = new Request.Builder()               
                .url("https://dl.dropboxusercontent.com/u/3852318/test.json")
                .build();       
        client.newCall(request).enqueue(new Callback() {
            @Override
            public void onFailure(Request request, IOException e) {
                e.printStackTrace();
            }
            @Override
            public void onResponse(Response response) throws IOException {
                if (!response.isSuccessful()) throw new IOException("Unexpected code " + response);
                Headers responseHeaders = response.headers();
                for (int i = 0; i < responseHeaders.size(); i++) {
                    System.out.println(responseHeaders.name(i) + ": " + responseHeaders.value(i));
                }
              System.out.println("###"+response.body().string());
     }
 });

but the response string is incomplete
{"infoStruttura":[{"id":"68","apertura_da":"2015-01-01","apertura_a":"2015-12-31","superficie":"70000","sitoWeb":"www.google.it","dist_territorio":"10","email":"campingroma@ezcamping.it","nome":"Camping Village Roma","cod_comune":"058091","voto":"0.00","cell":null,"tel_fisso":"066623018","tel_fisso_inv":null,"fax":"0666418147","via":"via Aurelia","civico":"831","territorio":"pianura","num_piazzole":"100","num_stelle":"4","latitudine":"41.887575","longitudine":"12.404525","descrizione":"\r\nIl campeggio in centro a Roma\r\n\r\nSegnalato come miglior camping nella classifica Mondiale di El Mundo nel circuito low cost, il Camping Village Roma \u00e8 la base perfetta per una vacanza nella Capitale.\r\n\r\nUna volta raggiunta la vostra sistemazione nelle piazzole, case mobili o Bungalow vi bastano 15 minuti.. e siete a Roma, in centro, Piazza San Pietro, Vaticano.A tutto questo aggiungete tutte le comodit\u00e0 ed i divertimenti che si possano desiderare in un campeggio, come le Piscine, l\u2019Idromassaggio, il Discopub e il Ristorante con la migliore cucina Italiana..ecco il Camping Village Roma.","descr_servizi":"Ampie e ombreggiate, tutte dotate di prese per l\u2019elettricit\u00e0 e fontanelle per l\u2019acqua, le piazzole al Roma Camping Village sono perfette per una vacanza in tenda, camper e roulotte.","validita_listino":"2015","apertura_Da":"2015-01-01","apertura_A":"2015-12-31"}],"serviziGratis":[{"id":"21","nome":"piscina","categoria":"Sport Acquatico","note":" Una grande piscina all'aperto"},{"id":"25","nome":"Beach volley","categoria":"Sport e giochi","note":null},{"id":"29","nome":"Ristorante","categoria":"Market e ristorante","note":"servizio di take away"},{"id":"40","nome":"bar","categoria":"Market e ristorante","note":null},{"id":"100","nome":"animali consentiti","categoria":"Animali","note":"gratis"},{"id":"149","nome":"Market","categoria":"Market e ristorante","note":"ogni genere di prodotto, dalla frutta fresca ai souvenir, dalle attrezzature per il campeggio ai prodotti per l'igiene personale."},{"id":"179","nome":"Bus navetta","categoria":"Varie","note":"Roma centro in 15 minuti, ogni ora dalle 8.30 alle 11.30 e dalle 15.30 alle 18.30"}],"listinoPiazzole":[{"id":"69","nome":"Adulto","periodoStag":[{"data":[{"periodo_da":"0000-01-07","periodo_a":"0000-04-02","idPeriodo":"212","prezzo":"8.30","stagione":"1"},{"periodo_da":"0000-04-07","periodo_a":"0000-04-23","idPeriodo":"213","prezzo":"8.30","stagione":"1"},{"periodo_da":"0000-11-03","periodo_a":"0000-12-25","idPeriodo":"214","prezzo":"8.30","stagione":"1"}]},{"data":[{"periodo_da":"0000-08-24","periodo_a":"0000-11-02","idPeriodo":"217","prezzo":"9.90","stagione":"2"},{"periodo_da":"0000-06-03","periodo_a":"0000-06-28","idPeriodo":"216","prezzo":"9.90","stagione":"2"},{"periodo_da":"0000-05-04","periodo_a":"0000-05-28","idPeriodo":"215","prezzo":"9.90","stagione":"2"}]},{"data":[{"periodo_da":"0000-04-03","periodo_a":"0000-04-06","idPeriodo":"218","prezzo":"12.50","stagione":"3"},{"periodo_da":"0000-04-24","periodo_a":"0000-05-03","idPeriodo":"219","prezzo":"12.50","stagione":"3"},{"periodo_da":"0000-05-29","periodo_a":"0000-06-02","idPeriodo":"220","prezzo":"12.50","stagione":"3"},{"periodo_da":"0000-06-29","periodo_a":"0000-08-23","idPeriodo":"221","prezzo":"12.50","stagione":"3"}]}],"note":"12 anni in su"},{"id":"94","nome":"camper","periodoStag":[{"data":[{"periodo_da":"0000-01-07","periodo_a":"0000-04-02","idPeriodo":"212","prezzo":"9.20","stagione":"1"},{"periodo_da":"0000-04-07","periodo_a":"0000-04-23","idPeriodo":"213","prezzo":"9.20","stagione":"1"},{"periodo_da":"0000-11-03","periodo_a":"0000-12-25","idPeriodo":"214","prezzo":"9.20","stagione":"1"}]},{"data":[{"periodo_da":"0000-08-24","periodo_a":"0000-11-02","idPeriodo":"217","prezzo":"10.90","stagione":"2"},{"periodo_da":"0000-06-03","periodo_a":"0000-06-28","idPeriodo":"216","prezzo":"10.90","stagione":"2"},{"periodo_da":"0000-05-04","periodo_a":"0000-05-28","idPeriodo":"215","prezzo":"10.90","stagione":"2"}]},{"data":[{"periodo_da":"0000-04-03","periodo

can you help me?

**Comment by JakeWharton** [comment]
Logcat truncates at ~4000 characters. When I run `len()` on that string I get 4050.
