### ISSUE TITLE
Mockserver start method

### ISSUE THREAD

**Issue by arkangelx** [square/okhttp#1444]
Using mockserver-1.2.1.jar and the start method not supported. Downloaded jar as couldn't get gradle version and package name right. Please advise

**Comment by artem-zinnatullin** [comment]
@arkangelx

For `Gradle` you can set dependency like this (example for Android):
```groovy
dependencies {
    // To compile it with main app configuration
    compile 'com.squareup.okhttp:mockwebserver:2.2.0' 

    // Or if you need mockwebserver only for unit tests configuration (since Android Gradle plugin v1.1.0)
    testCompile 'com.squareup.okhttp:mockwebserver:2.2.0'

    // Or if you use it in androidTest configuration
    androidTestCompile 'com.squareup.okhttp:mockwebserver:2.2.0'

    // dependency format 'group:artifact:version'
    // I suggest you to check Gradle documentation for more info
}
```

Also, you can download jar of required version from [search.maven.org](http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.squareup.okhttp%22%20AND%20a%3A%22mockwebserver%22) - link to mockwebserver artifacts

**Comment by JakeWharton** [comment]
Let us know if you have more problems. StackOverflow with the `okhttp` is also usually a better place for usage problems and questions as it will be seen by more people and will be archived and searchable by others.

**Comment by arkangelx** [comment]
Thanks...couldn't get it to work...another issue to do with okhttp nio

**Comment by arkangelx** [comment]
Thanks

**Comment by arkangelx** [comment]
Resolved the previous issue

Did you encounter this?
Test running startedTest running failed: Instrumentation run failed due to
'java.lang.IncompatibleClassChangeError'
Empty test suite.

this is my build.gradle file
compile 'com.squareup.okhttp:okhttp:2.2.0'
    compile 'com.squareup.okhttp:mockwebserver:2.2.0'
    // Or if you use it in androidTest configuration
    androidTestCompile 'com.squareup.okhttp:mockwebserver:2.2.0'

and this is my test method

    public void testMockWebServerTest() throws Exception {
        // Create a MockWebServer. These are lean enough that you can
create a new
        // instance for every unit test.
        MockWebServer server = new MockWebServer();
        // Schedule some responses.
        server.enqueue(new MockResponse().setBody("hello, world!"));
        server.enqueue(new MockResponse().setBody("sup, bra?"));
        server.enqueue(new MockResponse().setBody("yo dog"));

        // Start the server.
        server.play(9999);
}
