### ISSUE TITLE
Update for non-draft HTTP/2

### ISSUE THREAD

**Issue by JakeWharton** [square/okhttp#1446]
https://tools.ietf.org/html/draft-ietf-httpbis-http2-17
https://tools.ietf.org/html/draft-ietf-httpbis-header-compression-12

Should mostly involve changes around removing "draft"y bits. We'll also want to update links to point at the RFC which probably will take a few weeks to be out.

**Comment by swankjesse** [comment]
Tracking as the last bit of https://github.com/square/okhttp/issues/262
