### ISSUE TITLE
MockWebServer not picking up tests

### ISSUE THREAD

**Issue by arkangelx** [square/okhttp#1447]
Test running startedTest running failed: Instrumentation run failed due to
'java.lang.IncompatibleClassChangeError'
Empty test suite.

this is my build.gradle file
compile 'com.squareup.okhttp:okhttp:2.2.0'
    compile 'com.squareup.okhttp:mockwebserver:2.2.0'
    // Or if you use it in androidTest configuration
    androidTestCompile 'com.squareup.okhttp:mockwebserver:2.2.0'

and this is my test method

    public void testMockWebServerTest() throws Exception {
        // Create a MockWebServer. These are lean enough that you can
create a new
        // instance for every unit test.
        MockWebServer server = new MockWebServer();
        // Schedule some responses.
        server.enqueue(new MockResponse().setBody("hello, world!"));
        server.enqueue(new MockResponse().setBody("sup, bra?"));
        server.enqueue(new MockResponse().setBody("yo dog"));

        // Start the server.
        server.play(9999);
}

**Comment by JakeWharton** [comment]
> Test running startedTest running failed: Instrumentation run failed due to
> 'java.lang.IncompatibleClassChangeError'
> Empty test suite.

This is a problem with your instrumentation testing setup, not OkHttp. I would suggest gathering more information and posting to StackOverflow. The fact that you use MockWebServer doesn't appear to be a factor.
