### ISSUE TITLE
Release user agent string contains "SNAPSHOT"

### ISSUE THREAD

**Issue by orrc** [square/okhttp#1451]
I just upgraded from version 2.1 to 2.2 (`com.squareup.okhttp:okhttp:2.2.0` in my Gradle build file), rebuilt my app, and then noticed that HTTP requests are being made with the user agent `okhttp/2.3.0-SNAPSHOT`.

Not really a big deal, but perhaps it points to something that may be broken in the release process.

**Comment by swankjesse** [comment]
That's not working as intended! Will fix for 2.3 final.

**Comment by swankjesse** [comment]
Fixed in 2.3.
