### ISSUE TITLE
CertificatePinner does not support wildcards

### ISSUE THREAD

**Issue by bryanstern** [square/okhttp#1454]
I want to pin everything at `*.example.com` to a specific certificate, but `CertificatePinner#check` does not resolve `beers.example.com` to `*.example.com` and the certificates permitted by it.

Is there a reason why OkHttp does not support this? If not, I'm more than happy to submit a PR to add wildcard support.

**Comment by artem-zinnatullin** [comment]
JFYI recently I found that domain name wildcards are weird (in compare to regular wildcards in Unix).

I bought wildcard certificate for domain `*.example.com` and everything was okay for first level subdomains like `sub.example.com`, but for next sub-levels it won't work `sub.sub.example.com` won't be trusted :disappointed: 

Here is some useful information: http://security.stackexchange.com/questions/10538/what-certificates-are-needed-for-multi-level-subdomains
RFC 2818 http://tools.ietf.org/html/rfc2818

I think @swankjesse will want to have wildcards support similar to RFC 2818

P.S. very funny, that security.stackexchange.com does not use https by default

**Comment by swankjesse** [comment]
Sure. The format should be consistent with hostname verifier. In particular, `*` shouldn't match through`.`.

**Comment by bryanstern** [comment]
Yep, each wildcard should only match a single level. I'll take a stab this.

**Comment by swankjesse** [comment]
Nice. The crazy method you'll want to use is here: https://github.com/square/okhttp/blob/master/okhttp/src/main/java/com/squareup/okhttp/internal/tls/OkHostnameVerifier.java#L165

**Comment by artem-zinnatullin** [comment]
@swankjesse can I prepare PR for this?

**Comment by swankjesse** [comment]
@artem-zinnatullin sure. Send the tests first!

**Comment by swankjesse** [comment]
Fixed!
