### ISSUE TITLE
HTTP/2 not used when testing with Golang's HTTP/2 test server

### ISSUE THREAD

**Issue by sawrubh** [square/okhttp#1455]
I wrote a very basic app using code from http://square.github.io/okhttp/#examples and testing by trying to fetch https://http2.golang.org/file/gopher.png (basically an object from Golang's HTTP/2 test server) but I get the following message which says that HTTP/2 isn't supported. Here's the code: https://pastebin.mozilla.org/8823133 fwiw.
![screenshot_2015-02-24-23-36-31](https://cloud.githubusercontent.com/assets/1197583/6355970/15bd6874-bc80-11e4-8ea3-2bfb006515f0.png)

**Comment by JakeWharton** [comment]
OkHttp is on a newer draft of HTTP/2, draft 16. Go is behind on draft 14. We'll soon be reporting HTTP/2 final with #1446 which is currently in the RFC editor queue on its way to a published RFC.

**Comment by sawrubh** [comment]
@JakeWharton isn't there supposed to be compatibility with draft 14?

**Comment by JakeWharton** [comment]
No. Changes were not always made in backwards compatible ways. In this case, however, nothing changed between 14 and 16 but since we do not know how to negotiate h2-14 it will always fail.

If you're feeling ambitious you can simply change the string in the `Protocol` class to "h2-14" and compile your own jar. The current code will work with draft 14 servers just fine.

This is an unfortunate period of growing pains as the spec is finalized. In a month everyone will be updating to the the final RFC and everything will start playing nicely with each other.

**Comment by hrj** [comment]
I am trying to check for HTTP/2 support in okhttp using https://http2.akamai.com/ but the site reports negative.

Here's my quick test in kotlin + okhttp2.4

```kotlin
package test

import com.squareup.okhttp.*

fun main(args: Array<String>) {
	val client = OkHttpClient()
	client.setProtocols(listOf(Protocol.HTTP_1_1, Protocol.HTTP_2))

	val url = HttpUrl.parse("https://http2.akamai.com/")
	val request = Request.Builder()
		.url(url)
		.build()

	val response = client.newCall(request).execute().body().string()
	val stringsContainingHTTP2 = response.splitBy("\n").filter {it.contains("HTTP/2")}
	println(stringsContainingHTTP2.map{it.trim()}.join("\n"))
}
```

Negotiation failure? (I am not versed with the standard to do a wire-level analysis.)

**Comment by JakeWharton** [comment]
If you are testing on the JVM you need to add the Jetty ALPN jar to your bootclasspath in order for it to work.

**Comment by hrj** [comment]
Thanks; that worked!

After reading up more on it... I can't use that in production. I guess I will wait for native support in Java 9.

**Comment by hrj** [comment]
Update: Modified the above kotlin code to print the protocol related headers, and then tried running the code with JRE 9 EA b74 and it works! I see these headers in the response:
```
myproto: [h2]
protocol_negotiation: [h2]
```

However, it doesn't seem to work in gngr, where we are using `okhttp-urlconnection`. The headers I see in the response are:
```
    myproto : []
    protocol_negotiation : [h1]
```

Is this is a known problem or needs more investigation?

**Comment by hrj** [comment]
Sorry, scratch that. It seems Eclipse was caching the ALPN jar. When I tried with the command line, I get the same results with or without `okhttp-urlconnection`.

For reference, here's my test code in kotlin:
```kotlin
package test

import com.squareup.okhttp.*

fun main(args: Array<String>) {
	val client = OkHttpClient()
	client.setProtocols(listOf(Protocol.HTTP_1_1, Protocol.HTTP_2))

	fun directConnect() {
		val url = HttpUrl.parse("https://http2.akamai.com/")
		val request = Request.Builder()
			.url(url)
			.build()

		val response = client.newCall(request).execute()
		println("Headers from direct connection")
		response.headers().names().forEach { if (it.contains("proto")) {println(it +  response.headers().values(it))} }
	}

	fun urlConnect() {
		val url = java.net.URL("https://http2.akamai.com/")
		val urlFactory = com.squareup.okhttp.OkUrlFactory(client)
		java.net.URL.setURLStreamHandlerFactory(urlFactory);
		val connection = url.openConnection()
		val headers = connection.getHeaderFields()
		println("Headers from url connection")
		headers.keySet().forEach{ if (it != null && it.contains("proto")) {println(it +  headers.get(it))} }
	}
	
	println(System.getProperty("java.home"))
	directConnect()
	println("--------------")
	urlConnect()
	
}
```
