### ISSUE TITLE
Set header in Interceptor without creating a new Request

### ISSUE THREAD

**Issue by sockeqwe** [square/okhttp#1462]
Hi, as far as I know the only possibility to add a header from an `Interceptor` is to create a new `Request` object using the `Builder` like this:

```java
class MyInterceptor implements Interceptor {

    @Override public Response intercept(Chain chain) throws IOException {
          return chain.proceed(
			chain.request().newBuilder()
        		.addHeader("foo", "value")
        		.build()
		);
    }
}
```
I really like the builder pattern. However, isn't it to expensive to create a new `Request` object every time I want to manipulate the headers or is there another way I haven't seen yet?

**Comment by swankjesse** [comment]
Nope, this is efficient, and the right approach. (The cost of the allocation is dwarfed by the cost of the network call.)
