### ISSUE TITLE
security scan fail

### ISSUE THREAD

**Issue by Dnyanoba-Kantode** [square/okhttp#1466]
Hi, 

We have run security scan on this lib using our tool and it's getting fails because following threat is found.

Description: This function uses the java.security.MessageDigest.getInstance() function, which uses a hash algorithm that is considered weak. In recent years, researchers have demonstrated ways to breach many uses of previously-thought-safe hash functions such as MD5.

Remediation: Consider using a stronger algorithm in order to prevent attackers from being able to manipulate hash results. If passwords are being stored, consider using an algorithm that is computationally expensive in order to prevent dictionary attacks. Examples of algorithms designed to safeguard passwords are bcrypt and scrypt.

Can you please look into and update me.

**Comment by swankjesse** [comment]
We aren't using MD5 for anything security-related. It's just a hash.

**Comment by Dnyanoba-Kantode** [comment]
Thanks for quick update
