### ISSUE TITLE
Recipe: Unable to chain timeout methods

### ISSUE THREAD

**Issue by phileo** [square/okhttp#1470]
the set (connect, read, write) timeout methods return void, so I cannot chain the method calls as per recipe:

    try {
        Response response = client.clone() // Clone to make a customized OkHttp for this request.
            .setReadTimeout(500, TimeUnit.MILLISECONDS)
            .newCall(request)
            .execute();
            System.out.println("Response 1 succeeded: " + response);
    } catch (IOException e) {
         System.out.println("Response 1 failed: " + e);
    }

**Comment by JakeWharton** [comment]
This is a binary-incompatible change. No client would be able to support both the current version and the version if this was changed.

**Comment by phileo** [comment]
I'm ok with leaving the timeout methods as is, however, perhaps the recipe documentation should be updated - I don't seem to have editing permissions for that page....

**Comment by JakeWharton** [comment]
Ah, I see. Yes we should update.

**Comment by swankjesse** [comment]
Fixed!
