### ISSUE TITLE
Recipe: upload & download progress

### ISSUE THREAD

**Issue by swankjesse** [square/okhttp#1471]

**Comment by yschimke** [comment]
Can we close this, as addressed? https://github.com/square/okhttp/blob/master/samples/guide/src/main/java/okhttp3/recipes/Progress.java

**Comment by swankjesse** [comment]
I wanna do upload progress ’cause the examples on StackOverflow are wrong and people will copy+paste it until we provide a better one.

**Comment by aried3r** [comment]
Whoops, this is partly on me, I began work on this more than 3 years ago but never got around to fixing it. And I don't have time right now to rebase and and adapt to the new API. 🙈 

https://github.com/square/okhttp/pull/1528

**Comment by thalisvilela** [comment]
@aried3r Any update on this matter? Nothing works! The progress just goes to 100 while the file still being uploaded.

**Comment by Shusshu** [comment]
> I wanna do upload progress ’cause the examples on StackOverflow are wrong and people will copy+paste ’em until we provide a better one.

Is there a nice approach to this today?

**Comment by vincent-paing** [comment]
> I wanna do upload progress ’cause the examples on StackOverflow are wrong and people will copy+paste ’em until we provide a better one.

Any updates on this?

**Comment by yschimke** [comment]
Better as a standalone library or a canonical stackoverflow post.
