### ISSUE TITLE
Max concurrent streams for HTTP/2

### ISSUE THREAD

**Issue by swankjesse** [square/okhttp#1484]
Not implemented yet. We need policy, both for synchronous and asynchronous calls into a socket that's hit its limit.

**Comment by Ankit-tyagi-05** [comment]
Does max concurrent streams is configurable at OkHttpClient level?
I don't find any way to configure this at client side with OkHttp

**Comment by swankjesse** [comment]
I made a feature request for that here:
https://github.com/square/okhttp/issues/5950
