### ISSUE TITLE
OkHttp Url API

### ISSUE THREAD

**Issue by swankjesse** [square/okhttp#1486]
An immutable value class with a builder. Features to support:

 * [x] toUrl()
 * [x] toUri()
 * [x] toString()
 * [x] resolve(String link)
 * [x] compose from scheme, authority, path, query, fragment
 * [x] compose query parameters, which may come already-encoded or not
 * [x] Pragmatic validation. For example, permit `|` chars. See [issue 1044](https://github.com/square/okhttp/issues/1044).
 * [x] effectivePort() method that knows HTTP is 80 and HTTPS is 443
 * [x] static defaultPort(String scheme) method to lookup 80 and 443
 * [x] static parse(String) method that returns null if the input is not well formed
 * [x] Pragmatic canonicalization. `HTTP://SQUARE.COM:80` should be canonicalized to `http://square.com/`.
 * [x] equals and hashCode that leverage the pragmatic canonicalization

We need to be thoughtful around how the APIs work when data needs encoding. If I call `path()` does that return `/foo%7cbar` or `/foo|bar` ? My guess is that as a rule, we _never_ decode `%7c` into `|` because encoding and decoding URL components necessarily lives at the application level. (Otherwise consider the path `/foo%2fbar/baz`, which decodes to `/foo/bar/baz`). This strategy makes more sense when you recognize that the charset is itself unspecified and lives at the application level.

I'd like to consider deliberately not supporting URL schemes other than `http` and `https`. There's marginal benefit to handling `mailto:` and `file:` in the same class, and it means that more code would need to validate that the URL they're holding is of the type they expect. (What about `ws:` and `wss:` ?)

I'd like to support internationalized domain names, though not necessarily immediately.

What do we name it? `Url`? `HttpUrl` ? `OkUrl` ?

Resources:
http://developer.android.com/reference/java/net/URL.html
http://developer.android.com/reference/java/net/URI.html
http://developer.android.com/reference/android/net/Uri.html

**Comment by JakeWharton** [comment]
Great coverage of features. You hit almost everything I'd want (read: Retrofit would want). The missing things could probably be supported on top of it (e.g., templating path parts).

**Comment by JakeWharton** [comment]
Reposting https://github.com/square/okhttp/issues/1044#issuecomment-68342233, because I think it's good to 

> This API should be mindful of both URL constructors and URL deconstructors. Retrofit wants this badly (it has its own purpose-built solution right now) but also interceptors, MockWebServer, and a potential future OkHttpServer callback/route would benefit greatly from having a clean API to decompose.

**Comment by felipecsl** [comment]
+1 for `OkUrl`

**Comment by marshallpierce** [comment]
You may find the url-encoding parts of https://github.com/palominolabs/url-builder helpful.

**Comment by felipeska** [comment]
:+1: okUrl

**Comment by yogurtearl** [comment]
I vote for calling it YogurtUrl

**Comment by swankjesse** [comment]
That would certainly stir things up!

**Comment by swankjesse** [comment]
`ws://` and `wss://` are explicitly called out by the spec I'm using, which has me slightly tempted to support them out-of-the-box: https://url.spec.whatwg.org/#query-state

**Comment by frownlee** [comment]
Automatic punycode conversion?

**Comment by swankjesse** [comment]
@frownlee thats the plan!

**Comment by swankjesse** [comment]
A few last things until this is ready to release:

 * [ ] Rename encode / decode methods
 * [ ] Handle `+` or `%20` for space in queries.
 * [ ] Canonicalization documentation.
 * [ ] Support in `Request`. (But not in HttpEngine yet until after the release is cut.)

And for follow-up, potentially after the 2.4 release:

 * [ ] APIs for IDNs (☃.net)
 * [ ] Hostname label limits
 * [ ] Canonical form for IPv6 addresses
 * [ ] Don't percent-encode non-ASCII characters in fragments

**Comment by swankjesse** [comment]
* [ ] APIs like `addQueryParameter` should not discard newline characters; they can be encoded. We only discard those characters when the input is already encoded.

**Comment by felipecsl** [comment]
do you guys plan to repackage this outside out of OkHttp into it's own lib?

**Comment by swankjesse** [comment]
@felipecsl no plans currently. Should we?

**Comment by felipecsl** [comment]
yeah, I'd like to see it happening

**Comment by JakeWharton** [comment]
What's your use case for it, out of curiosity?

**Comment by felipecsl** [comment]
Don't have a clear use case yet, but would always nice to have other options

**Comment by Tolriq** [comment]
@swankjesse 
Do you think that it's possible to have the HttpUrl canonicalize made public and official ?

Your code is so much more configurable, efficient and memory friendly than Uri.encode and the equivalents.

**Comment by swankjesse** [comment]
@Tolriq Unlikely there's much I can do without breaking compatibility.

**Comment by Tolriq** [comment]
@swankjesse  Thanks :( 

I'm not an licensing expert, is it ok to copy paste this part of the code in closed source application ? There's already disclaimers and everything for using okhttp library.

**Comment by swankjesse** [comment]
Yes, please do!

**Comment by Tolriq** [comment]
My users then thank you :)

**Comment by Tolriq** [comment]
@swankjesse I suppose this is just a typo but in https://github.com/square/okhttp/blob/master/okhttp/src/main/java/com/squareup/okhttp/HttpUrl.java 

```
  static final String USERNAME_ENCODE_SET = " \"':;<=>@[]^`{}|/\\?#";
  static final String PASSWORD_ENCODE_SET = " \"':;<=>@[]\\^`{}|/\\?#";
```

Unless I'm missing something obvious, the password set is the same as the username but with the \ character 2 times ?
