### ISSUE TITLE
java.net.ProtocolException: unexpected end of stream with 204 response

### ISSUE THREAD

**Issue by Zaxim** [square/okhttp#1490]
So I reported this error on square/retrofit#776, but upon further investigation it might be a bug in okhttp.

I'm making a DELETE request to a server, the server responds with a 204 status for successful deletions. As below in my curl request
```
curl -v -X DELETE -H "Authorization: Bearer <REDACTED>" -H "Zotero-API-Version: 3" https://api.zotero.org/users/2351631/items?itemKey=QV7ZX6VZ
*   Trying 54.236.91.231...
* Connected to api.zotero.org (54.236.91.231) port 443 (#0)
<SNIPPED>
> DELETE /users/2351631/items?itemKey=QV7ZX6VZ HTTP/1.1
> User-Agent: curl/7.40.0
> Host: api.zotero.org
> Accept: */*
> Authorization: Bearer <REDACTED>
> Zotero-API-Version: 3
> 
< HTTP/1.1 204 No Content
< Date: Thu, 12 Mar 2015 16:57:24 GMT
< Server: Apache/2.4.10 (Amazon)
< Zotero-API-Version: 3
< Last-Modified-Version: 173
< Content-Length: 0
< Content-Type: text/html; charset=UTF-8
< Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
< 
* Connection #0 to host api.zotero.org left intact
```

However, when I try and make the same request using okhttp, I get a `java.net.ProtocolException: unexpected end of stream`. I've identified that the error is being thrown here: https://github.com/square/okhttp/blob/96dfaaa817816b2dc191d4d075a07aeb0c808694/okhttp/src/main/java/com/squareup/okhttp/internal/http/HttpConnection.java#L382
Looking at the debugger, it's expecting `length` to be 20 bytes, but the `source.read()` is failing for some reason and resulting in this stack trace

```
Caused by: java.net.ProtocolException: unexpected end of stream
	at com.squareup.okhttp.internal.http.HttpConnection$FixedLengthSource.read(HttpConnection.java:411)
	at okio.RealBufferedSource.read(RealBufferedSource.java:50)
	at okio.RealBufferedSource.request(RealBufferedSource.java:71)
	at okio.RealBufferedSource.require(RealBufferedSource.java:64)
	at okio.GzipSource.consumeHeader(GzipSource.java:114)
	at okio.GzipSource.read(GzipSource.java:73)
	at okio.RealBufferedSource$1.read(RealBufferedSource.java:298)
	at java.io.InputStream.read(InputStream.java:101)
	at retrofit.Utils.streamToBytes(Utils.java:43)
	at retrofit.Utils.readBodyToBytesIfNecessary(Utils.java:81)
	at retrofit.RestAdapter.logAndReplaceResponse(RestAdapter.java:483)
	at retrofit.RestAdapter.access$500(RestAdapter.java:107)
	at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:338)
	... 26 more
```

I'm totally willing to accept that the issue may be caused due to a malformed response from the server.

**Comment by swankjesse** [comment]
Seeing `GzipSource` in the stacktrace, I suspect that could be the difference here vs. curl. What happens if you include `--compressed` as an argument to curl? Does it still work/

**Comment by Zaxim** [comment]
Oooh! Very interesting. When I use the --compressed flag, the `Content-Length` is indeed 20

```
curl -v --compressed -X DELETE -H "Authorization: Bearer OKACcwpcH6VerQon87QWa6rU" -H "Zotero-API-Version: 3" https://api.zotero.org/users/2351631/items?itemKey=24237PGT                                                                                                                             
*   Trying 54.236.91.231...
* Connected to api.zotero.org (54.236.91.231) port 443 (#0)
<SNIPPED>
> DELETE /users/2351631/items?itemKey=24237PGT HTTP/1.1
> User-Agent: curl/7.40.0
> Host: api.zotero.org
> Accept: */*
> Accept-Encoding: deflate, gzip
> Authorization: Bearer <REDACTED>
> Zotero-API-Version: 3
> 
< HTTP/1.1 204 No Content
< Date: Thu, 12 Mar 2015 21:03:49 GMT
< Server: Apache/2.4.10 (Amazon)
< Zotero-API-Version: 3
< Last-Modified-Version: 175
< Content-Encoding: gzip
< Vary: Accept-Encoding
< Content-Length: 20
< Content-Type: text/html; charset=UTF-8
< Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
< 
* Connection #0 to host api.zotero.org left intact
```

So is this an Apache problem then?

**Comment by swankjesse** [comment]
`204 No Content` and `Content-Length: 20` disagree. My guess is that you've got some filter somewhere in Apache that's taking a zero-byte document, compressing it, and getting a 20 byte document as a result. (20 bytes for the gzip header & footer).

**Comment by swankjesse** [comment]
It's a problem with your server, I'm closing this bug! If you need to work-around, add the header "Accept-Encoding: identity" on the client side.

**Comment by manmohansoni** [comment]
I have also got the same bug. But if i hit the same api from Postman it works fine.
