### ISSUE TITLE
Please provide ability to remove cache entry for a specific request

### ISSUE THREAD

**Issue by inder123** [square/okhttp#1496]
Here is my detailed request posted on StackOverflow.
http://stackoverflow.com/questions/29053156/how-to-tell-okhttpclient-to-ignore-cache-and-force-refresh-from-server

**Comment by JakeWharton** [comment]
Add `CacheControl.FORCE_NETWORK` on your request object.

**Comment by inder123** [comment]
Does it evict the current cache entry first? 
For example, if the call with FORCE_NETWORK fails, does any previously existing cached entry still stands? 

My preference will be that it clears the current cached entry regardless if FORCE_NETWORK is set.

**Comment by swankjesse** [comment]
It'll overwrite the current entry with the new entry, if that is cacheable. If it isn't, the old, stale entry sticks around. I'll try to see if there's something better we can do here.

**Comment by inder123** [comment]
How do I do this with Retrofit since I don't have direct access to the request object?

**Comment by inder123** [comment]
This stackoverflow entry provide some clues:
http://stackoverflow.com/questions/25481403/does-retrofit-cache-the-authorization-requests

Do I set a requestInterceptor that adds the CacheControl? However, I don't see an ability to get to the OkHttp request object there.

**Comment by inder123** [comment]
any thoughts on how to do this with Retrofit?

**Comment by JakeWharton** [comment]
`@Headers("Cache-Control: no-cache")` on the method should work. If you want to do it dynamically you can add a `@Header("Cache-Control") String cacheControl` parameter and pass `null` or `"no-cache"`.

**Comment by inder123** [comment]
@Headers doesn't work for me since that will disable caching in all cases.
@Header method parameter looks like a good idea. I will try it out.

**Comment by inder123** [comment]
If I want to use FORCE_CACHE, what do I pass in the Cache-Control header?

pass "force-cache" instead of "no-cache" in here?
(@Header("Cache-Control") String cacheControl)

**Comment by inder123** [comment]
It would be great if OkClient provided access to the OkHttpRequest so that I can write my own Client.
In my client, I will just set request.cacheControl(CacheControl.FORCE_NETWORK)

**Comment by swankjesse** [comment]
@inder123 you can do that with an interceptor if you like.

**Comment by inder123** [comment]
How do I do it with an Interceptor? Interceptor does not expose any ability to set cacheControl. It only allows me to set headers. How do I access the underlying okhttp request object?

**Comment by inder123** [comment]
Update on this? 
BTW, I saw that new OKHttp versions got released recently, and it seemed to be a little incompatible with Retrofit (OkClient needs to throw IOException for some methods).
so I presume a new retrofit is coming soon as well. 

Is there a possibility of adding support for CacheControl in Retrofit interceptor?

**Comment by swankjesse** [comment]
@inder123 You can set cache control directly as a header. `Cache-Control: max-age=0` for example!

**Comment by inder123** [comment]
@swankjesse  is max-age=0 equivalent to FORCE_CACHE or FORCE_NETWORK?
I understand how to do FORCE_NETWORK., However, I don't know how to do FORCE_CACHE.

**Comment by JakeWharton** [comment]
To force a cache response you can do `only-if-cached` as a value. You can also add a very large `max-age=` value (separated by comma) if you want to allow a stale response (e.g., `only-if-cached,max-age=31536000`).

**Comment by inder123** [comment]
@JakeWharton That works for me. In our app, we have a requirement for an "offline" mode. Some countries, I think China, require user's permission for network access, even if WiFi.

**Comment by swankjesse** [comment]
No further action for us to take here.

**Comment by shubhral** [comment]
ok

**Comment by raphaelbgr** [comment]
What's the smartest way to disable it on an Instrumented test?
