### ISSUE TITLE
LoggingInterceptor Recipe Can Crash

### ISSUE THREAD

**Issue by GrahamFirst** [square/okhttp#1512]
I've experience code based on the LoggingInterceptor recipe crashing with a null pointer exception because chain.proceed() returned null (probably because the call was cancelled).

**Comment by swankjesse** [comment]
Strange, I didn't anticipate that `chain.proceed()` would ever return null. Are you using any other interceptors?

**Comment by swankjesse** [comment]
Nope, it's my own fault. Canceling a request can cause it to return null. Hmm.

**Comment by swankjesse** [comment]
We should fix Call#getResponse to throw rather than returning null when a call is canceled. That should fix the problem!
