### ISSUE TITLE
Compatibility with nghttp2

### ISSUE THREAD

**Issue by dhkim7** [square/okhttp#1513]
Hi all,

I am currently testing a okhttp client with a nghttp2 server.
I have tested with okcurl source code.
After successful SSL handshake, server does not accept the connection with the error message 'Client did not advertise HTTP/2 protocol. (nghttp2 expects h2-14)'.
I checked nghttp2 server accepts h2, h2-14, h2-16 and okhttp client supports h2.

Does anyone get the same issue?
Thanks.

**Comment by swankjesse** [comment]
Are you connecting from a desktop client? You'll need jetty-alpn on your boot classpath. For Java 8u40, it looks something like this:

````
   java -ea -Xbootclasspath/p:/Users/jwilson/.m2/repository/org/mortbay/jetty/alpn/alpn-boot/8.1.2.v20141202/alpn-boot-8.1.2.v20141202.jar  ...
```

**Comment by swankjesse** [comment]
(Please ask questions like this on Stackoverflow. This tracker is for bugs and feature requests only!)
