### ISSUE TITLE
Websocket: Connection header missing

### ISSUE THREAD

**Issue by StanKocken** [square/okhttp#1522]
Just by trying your experimental WebSocket support, I had an issue with an header.

Into the answer of the initial request, the headers into the answer are:

    HTTP/1.1 101 Switching Protocols
    Upgrade: websocket
    Connection: Upgrade
    Sec-WebSocket-Accept: 1IY6qmG8rC2qfPo5cpnqwY7nqlg=

Into WebSocketCall you're checking:

    String headerConnection = response.header("Connection");
    if (!"Upgrade".equalsIgnoreCase(headerConnection)) {

But I have the exception because "headerConnection" is null. Any idea why?

Is this condition necessary? Because just after you're checking:

    String headerUpgrade = response.header("Upgrade");
    if (!"websocket".equalsIgnoreCase(headerUpgrade)) { 

So if my connection is not "Upgrade", the header "Upgrade" should be null, right? 
In my case "headerUpgrade" is equals to "websocket". 
It's working when I tested to remove your condition on the "Connection" header.

Thanks.

**Comment by JakeWharton** [comment]
RFC 6455 states:

 > The `Connection` and `Upgrade` header fields complete the HTTP Upgrade.

There should be no reason to remove the check since every valid response will have both.

How are you determining that your response includes the "Connection" header?

**Comment by StanKocken** [comment]
Ok I understand.
I determined that by listening my connection with Charles Proxy.

**Comment by StanKocken** [comment]
I don't understand how, but I'm not able to reproduce this issue now. I let you know if I have a similar issue.
Thanks.

**Comment by pepyakin** [comment]
This one is related to the Charles. It is not forwarding `Connection` header.

**Comment by blusewang** [comment]
Damnt! v2ray alse drop `Connection` and `Upgrade` header!!!
