### ISSUE TITLE
Missing WebSocketCall.java

### ISSUE THREAD

**Issue by compguy30** [square/okhttp#1524]
The WebSocketEcho sample won't compile because it's missing WebSocketCall.

Also, I've noticed that some branches either include or are missing some packages in com.squareup.okhttp.internal entirely.  Even if a package is included, sometimes the files it contains vary.  WebSocketEcho is only one example.  It's very inconsistant.

Thanks.

**Comment by JakeWharton** [comment]
The `samples/guide/` module [has a dependency][1] on 'okhttp-ws' which is where `WebSocketCall` resides. The guide is compiled as part of the regular build to ensure that all the samples compile.

If you are copy/pasting it, you'll need to add the 'okhttp-ws' dependency or jar as well as the regular 'okhttp' one.

 [1]: https://github.com/square/okhttp/blob/762fd6f90be1912c66809da9ecb6972c8b84f7f4/samples/guide/pom.xml#L21-L25
