### ISSUE TITLE
SPDY connections continuously timeout

### ISSUE THREAD

**Issue by yihuanzhou** [square/okhttp#1525]
I sometimes get into a state where all connections fail due to a SocketTimeoutException and no requests will succeed until I switch my network connectivity from wifi to cellular data. I did some googling and it seems that OkHttp returns the longest living connection. Since our application usually only keeps 1-2 SPDY connections alive, I'm guessing it would continuously reuse these potentially bad connections? This sounds similar to #202/#797, but are there any possible work arounds for this issue?

**Comment by swankjesse** [comment]
No workarounds at the moment. I'd like to fix our implementation to properly fail SPDY connections, possibly by using PING to confirm that they're unresponsive at the transport level.

**Comment by swankjesse** [comment]
I believe this was fixed with the new allocations model.
https://github.com/square/okhttp/pull/2045
