### ISSUE TITLE
Slow establishing connection to one site but not others

### ISSUE THREAD

**Issue by mntgoat** [square/okhttp#1531]
If I try the code below on my Nexus 4, it takes over 60 seconds (about 63 usually) to establish the connection.  If I change the url from http://media.w3.org/2010/05/sintel/trailer.mp4 to http://www.w3.org then it works in just 300 milliseconds. Is it maybe trying one route first and timing out and then trying another? any way to make it work faster?

```
OkHttpClient client = new OkHttpClient();


                    Request request = new Request.Builder()
                            .url("http://media.w3.org/2010/05/sintel/trailer.mp4")
                            .build();

                Response response = null;
                try {
                    long start = System.currentTimeMillis();
                    response = client.newCall(request).execute();
                    long len  = response.body().contentLength();
                    Log.w(TAG,"Took " + (System.currentTimeMillis()-start));
                } catch (IOException e) {
                    e.printStackTrace();
                }
```
Thanks.

**Comment by swankjesse** [comment]
I couldn't reproduce this on my home network. Possibly a problem with a timeout. Shrinking your timeouts might help. Also, Happy Eyeballs is a thing that we might do someday.
https://github.com/square/okhttp/issues/506

No action to take here.

**Comment by mntgoat** [comment]
Could it have something to do with IPv6? when I get the Inet addresses I get the following for media.w3.org
```
media.w3.org/2001:470:8b2d:804:52:0:47:0
media.w3.org/128.30.52.47
```
but when I do it for www.w3.org I only get this:
```
 www.w3.org/128.30.52.37
```
This is what I used to print those:
```
 try {
                    InetAddress[] addresses =  InetAddress.getAllByName("www.w3.org");
                    for(InetAddress address : addresses){
                        Log.w(TAG,address.toString());
                    }
                } catch (UnknownHostException e) {
                    e.printStackTrace();
                }
```
