### ISSUE TITLE
Support sha256 digest on CertificatePinner

### ISSUE THREAD

**Issue by geovanisouza92** [square/okhttp#1538]
Hello guys,

I'm using this awesome project to build an app to manage [flynn](https://flynn.io/) clusters, however, it generates a sha256 digest for its self-signed TLS certificate.

Currently, I see that OkHttp supports [only sha1](https://github.com/square/okhttp/blob/master/okhttp/src/main/java/com/squareup/okhttp/CertificatePinner.java#L180) hashes. There is a way to add support for sha256 too?

**Comment by swankjesse** [comment]
I'd prefer to keep one hash mechanism only. If you'd like another, consider following this example:
https://github.com/square/okhttp/blob/master/samples/guide/src/main/java/com/squareup/okhttp/recipes/CheckHandshake.java

**Comment by geovanisouza92** [comment]
I don't understand your decision, but thank you anyway. :smile:

**Comment by Nathan-Smith** [comment]
The standard is now to use SHA256
https://tools.ietf.org/html/rfc7469#section-2.4
https://developer.mozilla.org/en-US/docs/Web/Security/Public_Key_Pinning#Enabling_HPKP
