### ISSUE TITLE
CertificatePinner uses sha1 hashes

### ISSUE THREAD

**Issue by Wick3r** [square/okhttp#1539]
This is not my main domain, so i am maybe wrong with this:

Using a sha1 hash is a security issue, since sha1 should not be used for signing certificates anymore, so it should not for pinning.

Sincerely

**Comment by swankjesse** [comment]
We're using Chromium's format.
http://src.chromium.org/viewvc/chrome/trunk/src/net/http/transport_security_state_static.certs

If you can convince them to change, we'll change too. But for now the tangible benefits of consistency with chrome outweigh the attack vector. Remember, pinning is a 2nd layer of security; the attacker still needs to compromise a CA.

**Comment by tbroyer** [comment]
FYI, HPKP uses sha256: https://tools.ietf.org/html/rfc7469
Given the authors, I suspect Chrome will update soon ;-)

**Comment by bottiger** [comment]
@swankjesse I would also like to place a vote for sha256 support since Google have already begun phasing out sha1

http://googleonlinesecurity.blogspot.dk/2014/09/gradually-sunsetting-sha-1.html
https://www.digicert.com/sha-2-ssl-certificates.htm

**Comment by mhoogenboom** [comment]
Will the conversion to SHA256 hashing be reconsidered in the near future?

**Comment by swankjesse** [comment]
Let's do it.
