### ISSUE TITLE
Response missing Content-Length header

### ISSUE THREAD

**Issue by kraizman** [square/okhttp#1542]
When i make request via okhttp on android i did not get Content-Length header but when i do same request via curl i to have it. Why can be this difference?

Okhttp code:
String url = "http://www.kissfm.ua/static/img/content/gallery_foto/8/20/1/o.jpg";
Request.Builder builder = new Request.Builder().url(url).get();
Response response = client.newCall(builder.build()).execute();
response.body().contentLength() return -1and yes Content-Length is not presented in headers when i print them
    Content-Type: image/jpeg
    Transfer-Encoding: chunked
    Connection: keep-alive
    Server: nginx/1.6.0
    Date: Wed, 01 Apr 2015 05:24:27 GMT
    Last-Modified: Fri, 27 Mar 2015 13:03:53 GMT
    ETag: "55155539-7795a"
    OkHttp-Selected-Protocol: http/1.1
    OkHttp-Sent-Millis: 1427865867781
    OkHttp-Received-Millis: 1427865867929

But, when i do same request via curl:
curl -v -I http://www.kissfm.ua/static/img/content/gallery_foto/8/20/1/o.jpg

* Hostname was NOT found in DNS cache
*   Trying 89.184.69.170...
* Connected to www.kissfm.ua (89.184.69.170) port 80 (#0)
> HEAD /static/img/content/gallery_foto/8/20/1/o.jpg HTTP/1.1
> User-Agent: curl/7.37.1
> Host: www.kissfm.ua
> Accept: */*
>
< HTTP/1.1 200 OK
HTTP/1.1 200 OK

* Server nginx/1.6.0 is not blacklisted
< Server: nginx/1.6.0
Server: nginx/1.6.0

< Date: Wed, 01 Apr 2015 06:06:54 GMT
Date: Wed, 01 Apr 2015 06:06:54 GMT

< Content-Type: image/jpeg
Content-Type: image/jpeg

< Content-Length: 489818
Content-Length: 489818

< Last-Modified: Fri, 27 Mar 2015 13:03:53 GMT
Last-Modified: Fri, 27 Mar 2015 13:03:53 GMT

< Connection: keep-alive
Connection: keep-alive

< ETag: "55155539-7795a"
ETag: "55155539-7795a"

< Accept-Ranges: bytes
Accept-Ranges: bytes

<
* Connection #0 to host www.kissfm.ua left intact

As you can see Content-Length is presented. So why is that difference?

**Comment by swankjesse** [comment]
What happens if you pass `--compressed` to curl?

**Comment by kraizman** [comment]
Looks like Content-Length gone. Is there way to explicitly request not compressed version?
curl -v -I --compressed http://www.kissfm.ua/static/img/content/gallery_foto/8/20/1/o.jpg
* Hostname was NOT found in DNS cache
*   Trying 89.184.69.170...
* Connected to www.kissfm.ua (89.184.69.170) port 80 (#0)
> HEAD /static/img/content/gallery_foto/8/20/1/o.jpg HTTP/1.1
> User-Agent: curl/7.37.1
> Host: www.kissfm.ua
> Accept: */*
> Accept-Encoding: deflate, gzip
>
< HTTP/1.1 200 OK
HTTP/1.1 200 OK
* Server nginx/1.6.0 is not blacklisted
< Server: nginx/1.6.0
Server: nginx/1.6.0
< Date: Wed, 01 Apr 2015 11:14:49 GMT
Date: Wed, 01 Apr 2015 11:14:49 GMT
< Content-Type: image/jpeg
Content-Type: image/jpeg
< Last-Modified: Fri, 27 Mar 2015 13:03:53 GMT
Last-Modified: Fri, 27 Mar 2015 13:03:53 GMT
< Connection: keep-alive
Connection: keep-alive
< Content-Encoding: gzip
Content-Encoding: gzip

<
* Connection #0 to host www.kissfm.ua left intact

**Comment by swankjesse** [comment]
Try `Accept-Encoding: identity` as a request header.

**Comment by kraizman** [comment]
I am getting this:    
    Content-Type: image/jpeg
    Transfer-Encoding: chunked
    Connection: keep-alive
    Content-Encoding: gzip
    Server: nginx/1.6.0
    Date: Wed, 01 Apr 2015 05:24:27 GMT
    Last-Modified: Fri, 27 Mar 2015 13:03:53 GMT
    ETag: "55155539-7795a"
    OkHttp-Selected-Protocol: http/1.1
    OkHttp-Sent-Millis: 1427865867781
    OkHttp-Received-Millis: 1427865867929

**Comment by swankjesse** [comment]
That's odd. You're calling it like so?
```
    Request request = new Request.Builder()
        .url(url)
        .header("Accept-Encoding", "identity")
        .build();
```
Can you print your request headers to confirm that it’s being included?

**Comment by kraizman** [comment]
Sure, its same code as on top but with addHeader
```Java
Request.Builder builder = new Request.Builder().url(url).get();
builder.addHeader("Accept-Encoding","identity");
Request request = builder.build();
Response response = client.newCall(request).execute();
int responseCode = response.code();

Logger.w("pasha", request.headers().toString());
Logger.d("pasha", "response code "+responseCode);
Logger.d("pasha", response.headers().toString());
```

>04-01 16:21:46.673  19694-19817/*.*.* W/pasha﹕ Accept-Encoding: identity
>04-01 16:21:46.673  19694-19817/*.*.* D/pasha﹕ response code 200
>04-01 16:21:46.673  19694-19817/*.*.* D/pasha﹕ Content-Type: image/jpeg
    Transfer-Encoding: chunked
    Connection: keep-alive
    Content-Encoding: gzip
    Server: nginx/1.6.0
    Date: Wed, 01 Apr 2015 13:21:46 GMT
    Last-Modified: Wed, 25 Mar 2015 12:47:59 GMT
    ETag: "5512ae7f-18ae8"
    OkHttp-Selected-Protocol: http/1.1
    OkHttp-Sent-Millis: 1427894506505
    OkHttp-Received-Millis: 1427894506676

**Comment by kraizman** [comment]
@swankjesse  Looks like problem gone after reinstall of app. Is headers saved in some place and reused somehow? How you can explain this?

**Comment by swankjesse** [comment]
@kraizman possibly in the response cache.
