### ISSUE TITLE
Support NOTIFY/M-SEARCH

### ISSUE THREAD

**Issue by ened** [square/okhttp#1544]
It would be helpful if OKHttp can support HTTPU calls (used for UPnP and others):
 NOTIFY
 M-SEARCH

This would enable the SSDP protocol in general.

At some stage, discovery of services (through dedicated M-SEARCH calls & results) might be helpful as well.

**Comment by swankjesse** [comment]
Are these custom methods or something else?

**Comment by ened** [comment]
Yes they are custom methods.
However, maybe okhttp is the wrong place for them. M search, to my
knowledge, is UDP based.

**Comment by swankjesse** [comment]
I don't think we're going to implement UDP. If you'd like to try it, fork & show!
