### ISSUE TITLE
Https connection cannot use TLS_RSA_WITH_3DES_EDE_CBC_SHA cipher suite

### ISSUE THREAD

**Issue by ValleZ** [square/okhttp#1545]
Hi! I've noticed that an update in okhttp 2.3 removed TLS_RSA_WITH_RC4_128_SHA cipher suite support by default.
This removal made impossible to connect to https://service-payment.groceries.asda.com with no extra setup.
I find this bit surprising because all browsers connects to the domain using TLS_RSA_WITH_3DES_EDE_CBC_SHA cipher suite and it is declared in ConnectionSpec.MODERN_TLS. However for some reason connection fails if TLS_RSA_WITH_RC4_128_SHA is not defined in connection specs.

Can you please check that there is no mistake about ciphersuite use in okhttp? It also may be purely android specific thing but I don't know how to verify this.

**Comment by swankjesse** [comment]
We deliberately dropped support for RC4 because it's lost our trust. Best fix is to ask your server to upgrade to something more modern.

**Comment by ValleZ** [comment]
Yes, the server does support TLS_RSA_WITH_3DES_EDE_CBC_SHA and it even works in android emulator. However it doesn't work for unknown reason on real devices - that's what the task is about. Maybe you can check why does this happen or tell what can I do to gather this info. I've requested server encryption upgrade but it may be beneficial for others to figure out what's going on.

**Comment by swankjesse** [comment]
According to SSL labs, this site only supports 2 cipher suites, and both of them use RC4. You'll need to explicitly configure OkHttp to connect to it until they upgrade their crypto.
https://www.ssllabs.com/ssltest/analyze.html?d=https%3A%2F%2Fservice-payment.groceries.asda.com

Chrome says _obsolete cryptography_:
![screen shot 2015-04-03 at 12 10 09 am](https://cloud.githubusercontent.com/assets/133019/6977918/d7330360-d995-11e4-916b-1933191b6ad5.png)

Firefox says it isn't encrypted:
![screen shot 2015-04-03 at 12 11 27 am](https://cloud.githubusercontent.com/assets/133019/6977930/0987d05c-d996-11e4-83af-464360499118.png)

No action for us to take here. Sorry about your old bad server!

**Comment by ValleZ** [comment]
okay, thank you for checking!

**Comment by swankjesse** [comment]
...You should give them a hard time about this. When the world's largest company uses obsolete crypto for URLs containing the word `payment`, somebody is doing a bad job.

**Comment by ValleZ** [comment]
Indeed. While practically it's still a pretty secure it does look like a very old server.
