### ISSUE TITLE
Is there a downloadable version of the JavaDoc ?

### ISSUE THREAD

**Issue by JonasCz** [square/okhttp#1546]
Is there a downloadable version of the docs somewhere, so I can refer to them while offline ? I've googled around, but can't find anything..

**Comment by swankjesse** [comment]
Maven central has all of our artifacts.

http://search.maven.org/#artifactdetails%7Ccom.squareup.okhttp%7Cokhttp%7C2.3.0%7Cjar

**Comment by JonasCz** [comment]
Thanks.
