### ISSUE TITLE
Custom verbs wont be allowed to have a request body

### ISSUE THREAD

**Issue by Cheesebaron** [square/okhttp#1549]
All custom verbs will be refused to have a request body and building the request will throw a `IllegalArgumentException`.

https://github.com/square/okhttp/blob/master/okhttp/src/main/java/com/squareup/okhttp/internal/http/HttpMethod.java#L32

https://github.com/square/okhttp/blob/master/okhttp/src/main/java/com/squareup/okhttp/Request.java#L233

Is it possible to get some way to override this behavior?

**Comment by JakeWharton** [comment]
Dupe of #229.
