### ISSUE TITLE
having problem with resume download

### ISSUE THREAD

**Issue by xxxifan** [square/okhttp#1551]
I want to resume download a canceled file,I added ranges in header like this:

        if (targetFile.exists()) {
            long downloaded = targetFile.length();
            requestBuilder.addHeader("Ranges", "bytes=" + downloaded + "-");
        }

while I get a response header:

    Date: Mon, 13 Apr 2015 07:41:08 GMT
    Content-Type: application/octet-stream
    Content-Length: 72940103
    Last-Modified: Fri, 10 Apr 2015 03:28:28 GMT
    Connection: keep-alive
    Accept-Ranges: bytes
    OkHttp-Selected-Protocol: http/1.1
    OkHttp-Sent-Millis: 1428910675075
    OkHttp-Received-Millis: 1428910675081

I checked ths request have a header
    Ranges: bytes=7535104-
but it seems it didn't sent to server, and I confirmed the server is support Ranges.

and I have used interceptor for progress like the demo, is something messed up with this?

**Comment by swankjesse** [comment]
Can you please hook up a network interceptor to log the request headers? We should confirm that the header is being dropped before anything else.

(Using a tool like charlesproxy.com or Stetho is just as good.)

**Comment by xxxifan** [comment]
thanks for reply.
I've test it, it's like it has been dropped while it response
the original code is

    client.networkInterceptors().add(new Interceptor() {
            @Override
            public Response intercept(Chain chain) throws IOException {
                Request request = chain.request();

                Log.e("", request.headers().toString());

                Response originalResponse = chain.proceed(request);

                Log.e("", originalResponse.headers().toString());

                return originalResponse.newBuilder()
                        .body(new ProgressResponseBody(originalResponse.body()))
                        .build();
            }
        });

first log
    Ranges: bytes=7163808-
    Connection: Keep-Alive
    Accept-Encoding: gzip
    User-Agent: okhttp/2.3.0

second
    Date: Mon, 13 Apr 2015 13:15:31 GMT
    Content-Type: application/zip
    Content-Length: 72940103
    Connection: keep-alive
    Set-Cookie: __jsluid=30482be645cfabce41a46721efc6ba83; path=/
    Last-Modified: Wed, 08 Apr 2015 10:02:01 GMT
    ETag: "5524fc99-458fa47"
    Accept-Ranges: bytes
    X-Cache: pipe
    OkHttp-Selected-Protocol: http/1.1
    OkHttp-Sent-Millis: 1428930930389
    OkHttp-Received-Millis: 1428930930496

**Comment by swankjesse** [comment]
It's possible that OkHttp's transparent Gzip is interfering. Consider adding `Accept-Encoding: identity` as a request header. Other than that, it could be a problem with your server not supporting range requests. What's the status code of the response?

**Comment by swankjesse** [comment]
There's no action for us to take here. If this is a bug report, please provide a test case. Otherwise it might be best to go to stackoverflow with this issue.

**Comment by chiara-jm** [comment]
If anyone is here for the same problem, I believe `Range` is the name of the header instead of `Ranges`
