### ISSUE TITLE
New breakages in OkHttp tests on Android AOSP/master

### ISSUE THREAD

**Issue by nfuller** [square/okhttp#1552]
Just putting together a pull of recent changes to OkHttp for Android. These changes failed 2 out of 2 runs on Android. The test may actually be flaky, not sure yet. All in SpdyConnection. Death of the worker thread takes down the test process, as they would (by default) an Android app.

In the past these kind of problems have not always been from the test that fails, but something happening in the tear down from a prior tests.

This is a heads up. I'll look closer and there may be fixes coming. Any insights from OkHttp about recent changes from maintainers would be appreciated. Because the problems are related to SPDY they won't necessarily stop me from committing.

WIP Android commit is here: https://android-review.googlesource.com/146428

Not looked if there are related changes in the commits I have pulled, which are:

    OkHttp:
    From b609edd07864d7191dcda8ba1f6c833c9fe170ad
    to b40f99a950cb407eff52537a97420bd253a64f63
    
    Okio:
    From 654ddf5e8f6311fda77e429c22d5e0e15f713b8d
    to b5811711b141b230e4e58f577c79cfbf4c2d4028

Stack traces below:

04-13 08:07:25.218  8560  8576 I TestRunner: started: cancelInFlightBeforeResponseReadThrowsIOE_SPDY_3(com.squareup.okhttp.CallTest)
04-13 08:07:25.218  8560  9199 E AndroidRuntime: FATAL EXCEPTION: OkHttp SpdyConnection
04-13 08:07:25.218  8560  9199 E AndroidRuntime: Process: android.core.tests.runner, PID: 8560
04-13 08:07:25.218  8560  9199 E AndroidRuntime: java.lang.RuntimeException: java.io.IOException: stream was reset: CANCEL
04-13 08:07:25.218  8560  9199 E AndroidRuntime:        at com.squareup.okhttp.internal.spdy.SpdyConnection$Reader$1.execute(SpdyConnection.java:644)
04-13 08:07:25.218  8560  9199 E AndroidRuntime:        at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
04-13 08:07:25.218  8560  9199 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
04-13 08:07:25.218  8560  9199 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
04-13 08:07:25.218  8560  9199 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:818)
04-13 08:07:25.218  8560  9199 E AndroidRuntime: Caused by: java.io.IOException: stream was reset: CANCEL
04-13 08:07:25.218  8560  9199 E AndroidRuntime:        at com.squareup.okhttp.internal.spdy.SpdyStream.checkOutNotClosed(SpdyStream.java:572)
04-13 08:07:25.218  8560  9199 E AndroidRuntime:        at com.squareup.okhttp.internal.spdy.SpdyStream.access$1200(SpdyStream.java:34)
04-13 08:07:25.218  8560  9199 E AndroidRuntime:        at com.squareup.okhttp.internal.spdy.SpdyStream$SpdyDataSink.flush(SpdyStream.java:521)
04-13 08:07:25.218  8560  9199 E AndroidRuntime:        at okio.RealBufferedSink.flush(RealBufferedSink.java:217)
04-13 08:07:25.218  8560  9199 E AndroidRuntime:        at com.squareup.okhttp.mockwebserver.MockWebServer.throttledTransfer(MockWebServer.java:748)
04-13 08:07:25.218  8560  9199 E AndroidRuntime:        at com.squareup.okhttp.mockwebserver.MockWebServer.access$2300(MockWebServer.java:88)
04-13 08:07:25.218  8560  9199 E AndroidRuntime:        at com.squareup.okhttp.mockwebserver.MockWebServer$SpdySocketHandler.writeResponse(MockWebServer.java:902)
04-13 08:07:25.218  8560  9199 E AndroidRuntime:        at com.squareup.okhttp.mockwebserver.MockWebServer$SpdySocketHandler.receive(MockWebServer.java:839)
04-13 08:07:25.218  8560  9199 E AndroidRuntime:        at com.squareup.okhttp.internal.spdy.SpdyConnection$Reader$1.execute(SpdyConnection.java:642)
04-13 08:07:25.218  8560  9199 E AndroidRuntime:        ... 4 more

04-13 08:09:23.208  9256  9272 I TestRunner: started: responsesAreCached(com.squareup.okhttp.internal.http.HttpOverHttp2Test)
04-13 08:09:23.241  9256 11131 I MockWebServer: MockWebServer[38617] starting to accept connections
04-13 08:09:23.302  9256 10764 E AndroidRuntime: FATAL EXCEPTION: OkHttp SpdyConnection
04-13 08:09:23.302  9256 10764 E AndroidRuntime: Process: android.core.tests.runner, PID: 9256
04-13 08:09:23.302  9256 10764 E AndroidRuntime: java.lang.RuntimeException: java.io.IOException: closed
04-13 08:09:23.302  9256 10764 E AndroidRuntime:        at com.squareup.okhttp.internal.spdy.SpdyConnection$Reader$1.execute(SpdyConnection.java:644)
04-13 08:09:23.302  9256 10764 E AndroidRuntime:        at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
04-13 08:09:23.302  9256 10764 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
04-13 08:09:23.302  9256 10764 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
04-13 08:09:23.302  9256 10764 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:818)
04-13 08:09:23.302  9256 10764 E AndroidRuntime: Caused by: java.io.IOException: closed
04-13 08:09:23.302  9256 10764 E AndroidRuntime:        at com.squareup.okhttp.internal.spdy.Http2$Writer.data(Http2.java:486)
04-13 08:09:23.302  9256 10764 E AndroidRuntime:        at com.squareup.okhttp.internal.spdy.SpdyConnection.writeData(SpdyConnection.java:305)
04-13 08:09:23.302  9256 10764 E AndroidRuntime:        at com.squareup.okhttp.internal.spdy.SpdyStream$SpdyDataSink.close(SpdyStream.java:546)
04-13 08:09:23.302  9256 10764 E AndroidRuntime:        at okio.RealBufferedSink.close(RealBufferedSink.java:235)
04-13 08:09:23.302  9256 10764 E AndroidRuntime:        at com.squareup.okhttp.mockwebserver.MockWebServer$SpdySocketHandler.writeResponse(MockWebServer.java:903)
04-13 08:09:23.302  9256 10764 E AndroidRuntime:        at com.squareup.okhttp.mockwebserver.MockWebServer$SpdySocketHandler.receive(MockWebServer.java:839)
04-13 08:09:23.302  9256 10764 E AndroidRuntime:        at com.squareup.okhttp.internal.spdy.SpdyConnection$Reader$1.execute(SpdyConnection.java:642)
04-13 08:09:23.302  9256 10764 E AndroidRuntime:        ... 4 more

04-13 08:01:47.430  6129  6145 I TestRunner: started: setFixedLengthStreamingModeSetsContentLength(com.squareup.okhttp.internal.http.HttpOverSpdy3Test)
04-13 08:01:47.434  6129  6188 E AndroidRuntime: FATAL EXCEPTION: OkHttp SpdyConnection
04-13 08:01:47.434  6129  6188 E AndroidRuntime: Process: android.core.tests.runner, PID: 6129
04-13 08:01:47.434  6129  6188 E AndroidRuntime: java.lang.RuntimeException: java.io.IOException: closed
04-13 08:01:47.434  6129  6188 E AndroidRuntime:        at com.squareup.okhttp.internal.spdy.SpdyConnection$Reader$1.execute(SpdyConnection.java:644)
04-13 08:01:47.434  6129  6188 E AndroidRuntime:        at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
04-13 08:01:47.434  6129  6188 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
04-13 08:01:47.434  6129  6188 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
04-13 08:01:47.434  6129  6188 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:818)
04-13 08:01:47.434  6129  6188 E AndroidRuntime: Caused by: java.io.IOException: closed
04-13 08:01:47.434  6129  6188 E AndroidRuntime:        at com.squareup.okhttp.internal.spdy.Spdy3$Writer.sendDataFrame(Spdy3.java:397)
04-13 08:01:47.434  6129  6188 E AndroidRuntime:        at com.squareup.okhttp.internal.spdy.Spdy3$Writer.data(Spdy3.java:392)
04-13 08:01:47.434  6129  6188 E AndroidRuntime:        at com.squareup.okhttp.internal.spdy.SpdyConnection.writeData(SpdyConnection.java:305)
04-13 08:01:47.434  6129  6188 E AndroidRuntime:        at com.squareup.okhttp.internal.spdy.SpdyStream$SpdyDataSink.close(SpdyStream.java:546)
04-13 08:01:47.434  6129  6188 E AndroidRuntime:        at okio.RealBufferedSink.close(RealBufferedSink.java:235)
04-13 08:01:47.434  6129  6188 E AndroidRuntime:        at com.squareup.okhttp.mockwebserver.MockWebServer$SpdySocketHandler.writeResponse(MockWebServer.java:903)
04-13 08:01:47.434  6129  6188 E AndroidRuntime:        at com.squareup.okhttp.mockwebserver.MockWebServer$SpdySocketHandler.receive(MockWebServer.java:839)
04-13 08:01:47.434  6129  6188 E AndroidRuntime:        at com.squareup.okhttp.internal.spdy.SpdyConnection$Reader$1.execute(SpdyConnection.java:642)
04-13 08:01:47.434  6129  6188 E AndroidRuntime:        ... 4 more

**Comment by nfuller** [comment]
Think these failures might be related to commit f78f74f5a2cf1f73f974487816f998a6e37a9cf1 
From issue: https://github.com/square/okhttp/issues/1294

At first glance, it's not obvious why the tests were hanging in that issue. Is it because of non-daemon threads? SpdyConnection creates a non-daemon thread to handle the readerRunnable. Perhaps it should add an uncaught exception handler to avoid the Android default, or use an executor that will handle the exception?

**Comment by nfuller** [comment]
Pull #1554 should get things passing on Android again.
#1555 hopefully locks the Android "uncaught exceptions are bad" behavior in place to avoid any accidental regressions.

**Comment by swankjesse** [comment]
I've fixed some of the underlying problems:
https://github.com/square/okhttp/pull/1658
https://github.com/square/okhttp/pull/1659

No further action here.
