### ISSUE TITLE
Download pictures, the size of the flow is 0

### ISSUE THREAD

**Issue by DukeLee1989** [square/okhttp#1556]
public static InputStream getLoadPicHttp(String url) throws IOException {
        Request request = new Request.Builder().url(url).build();
        Response response = client.newCall(request).execute();
        if (response.isSuccessful()) {
            Log.e("OkHttpUtils","isSuccessful"+response.body().toString());
            return response.body().byteStream();
        } else {
            Log.e("OkHttpUtils",response.body().string());
            return new InputStream() {
                @Override
                public int read() throws IOException {
                    return 0;
                }
            };
        }
    }
  finallly
                    InputStream is = (InputStream) msg.obj;
                    Bitmap bitmap = BitmapFactory.decodeStream(is);
                    mImageView.setImageBitmap(bitmap);

Is this way right？Why can't I get corrent   InputStream？

**Comment by swankjesse** [comment]
From the Response doc, _"Instances of this class are not immutable: the response body is a one-shot value that may be consumed only once. All other properties are immutable."_

You can't call `response.body().string()` multiple times.

**Comment by DukeLee1989** [comment]
thank you!
