### ISSUE TITLE
Support HPKP

### ISSUE THREAD

**Issue by tbroyer** [square/okhttp#1567]
See https://tools.ietf.org/html/rfc7469

**Comment by swankjesse** [comment]
Nice.

**Comment by jamak** [comment]
Hey all,
I'm adding hpkp to my fork of OkHttp, and I was hoping to get some guidance on
how to actually serialize the pinned public keys. It makes sense to store the
public keys in whatever keystore, but
I'm unsure where the best place to place the `maxAge` of a given pin (to verify that a
pin is still valid) would be — at least for something that's platform-agnostic.

**Comment by originx** [comment]
What is the current status for HPKP implementation, are you still working on the fork?

**Comment by mkochenough** [comment]
Any update on this? I would also be interested in HPKP support for OkHttp.

**Comment by yschimke** [comment]
Can we close this given chrome is deprecating it in favour of Expect-CT?

**Comment by swankjesse** [comment]
Definitely.
