### ISSUE TITLE
How to get the download progress

### ISSUE THREAD

**Issue by liaibai** [square/okhttp#1568]
How to get the download progress

When I want to download pictures to show the progress bar

**Comment by liaibai** [comment]
Request.Builder requestBuilder = new Request.Builder()
                .url(url.toStringUrl());
        for (Map.Entry<String, String> headerEntry : url.getHeaders().entrySet()) {
            requestBuilder.addHeader(headerEntry.getKey(), headerEntry.getValue());
        }
        Request request = requestBuilder.build();

        Response response = client.newCall(request).execute();
        responseBody = response.body();
        if (!response.isSuccessful()) {
            throw new IOException("Request failed with code: " + response.code());
        }

**Comment by JakeWharton** [comment]
There is a progress recipe here: https://github.com/square/okhttp/blob/master/samples/guide/src/main/java/com/squareup/okhttp/recipes/Progress.java

**Comment by huanzhiyazi** [comment]
Hi, @JakeWharton, the url you provide here is closed...

**Comment by NightlyNexus** [comment]
@huanzhiyazi The package name changed. :)
updated: https://github.com/square/okhttp/blob/master/samples/guide/src/main/java/okhttp3/recipes/Progress.java

**Comment by huanzhiyazi** [comment]
@NightlyNexus awsome! thx for your reply!

**Comment by WalkingRoy** [comment]
hi, i can download a file successfully and get the correct progress well .
but i am confused that， it means clone a new OkHttpClient instance and set a new ProgressListener for every request , if i want to download multi file and get these progress simultaneously ?

I don't understand my idea is correct or not,or there is other way to implement that download multi file and get progress ?

**Comment by WalkingRoy** [comment]
Hi , @JakeWharton , i can download a file successfully and get the correct progress well .
but i am confused that， it means clone a new OkHttpClient instance and set a new ProgressListener for every request , if i want to download multi file and get these progress simultaneously ?

I don't understand my idea is correct or not,or there is other way to implement that download multi file and get progress ?

**Comment by khalilsam** [comment]
hi, @WalkingRoy  i' v  got the same issue  ( i must show the progress of multiple request) did you resolve it ??

**Comment by anastr** [comment]
this is [multi-file downloader](https://gist.github.com/anastr/cad4b6db4da141c5b124ab6629d1100a) with progress.
