### ISSUE TITLE
response already "consumed"

### ISSUE THREAD

**Issue by rehacktive** [square/okhttp#1576]
I'm trying to use this  interceptor for authentication:

public class CustomInterceptor implements Interceptor {

    @Override
    public Response intercept(Chain chain) throws IOException {
        Request request = chain.request();

        // try the request
        Response response = chain.proceed(request);

        if (response shows expired token) {

            // get a new token (I use a synchronous Retrofit call)

            // create a new request and modify it accordingly using the new token
            Request newRequest = request.newBuilder()...build();

            // retry the request
            return chain.proceed(newRequest);
        }

        // otherwise just pass the original response on
        return response;
    }

}

The problem is that my check (response shows expired token) is not status-related, I need to check the actual response (body content).
So after the check, the response is "consumed" and any attempt to ready the body will fail.

I've tried to "clone" the response buffer before read, like:

public static String responseAsString(Response response ){
     Buffer clonedBuffer = response.body().source().buffer().clone();
     return ByteString.of(clonedBuffer.readByteArray()).toString();
   }

but it doesn't work, the clonedBuffer is empty.
 Any help will be appreciated.

**Comment by swankjesse** [comment]
Can you ask this on stackoverflow? This is neither a bug report nor a feature request.
