### ISSUE TITLE
Http Connection not getting closed ( CLOSE_WAIT)

### ISSUE THREAD

**Issue by harmanjassal** [square/okhttp#1577]
Using OkHttp results in too many connections in CLOSE_WAIT if a service behind loadbalancer is not responding.

Seems like HttpURLConnectionImpl.getResponse() is not handling the exception scenarios.

**Comment by swankjesse** [comment]
Can you provide a short test case for this?

**Comment by harmanjassal** [comment]
Below is the code, but to reproduce the issue you will need to specify the loadbalancer url with endpoint being down.
I think issue is occurs when HttpURLConnectionImpl.getResponse() throws exception during execute.

public class ReproduceLeakOkHttp {

    public static final int TOTAL_RETRIES = 10;
    private InfluxDB influxDB;

    private RestAdapter restAdapter;

    private InfluxDBService influxDBService;

    @Before
    public void setUp() {

        OkHttpClient okHttpClient = new OkHttpClient();
        restAdapter = new RestAdapter.Builder().setEndpoint("loadbalancerurl")
            .setErrorHandler(new ErrorHandler() {
                @Override
                public Throwable handleError(RetrofitError cause) {

                    Response r = cause.getResponse();
                    if (r != null && r.getStatus() >= 400) {
                        try {
                            return new RuntimeException(CharStreams.toString(new InputStreamReader(r.getBody().in(),
                                Charsets.UTF_8)));
                        } catch (IOException e) {
                            // LOG
                        }
                    }
                    return cause;
                }
            }).setClient(new OkClient(okHttpClient)).build();
        restAdapter.setLogLevel(LogLevel.FULL);
        influxDBService = restAdapter.create(InfluxDBService.class);
    }

    @Test
    public void leak() {

        for (int i = 0; i < TOTAL_RETRIES; i++) {


            try {
                influxDBService.ping();
            } catch (Exception e) {

            }
        }
        System.out.println("Run netstat -an or use TCP view to monitor TCP connections");
    }

    private static interface InfluxDBService {

        @GET("/ping")
        public Pong ping();

        @GET("/interfaces")
        public Response version();
    }
}

**Comment by swankjesse** [comment]
Does adding a timeout fix the problem?

**Comment by harmanjassal** [comment]
No. The only option is to kill the client using okhttp. We have seen this issue in production and had to restart the application because OkHttp was using too many File Descriptors.

I am able to reproduce the scenario in lower environment and I can reproduce this every single time.  I have tried the similar test with Apache Http and it works without any issue,

**Comment by swankjesse** [comment]
Ahh, got it. It's a resource leak. Are you calling `close()` after the connection fails?

**Comment by harmanjassal** [comment]
I think restAdapter does not provide access to the connection.

**Comment by harmanjassal** [comment]
I think this is similar to 1502

**Comment by swankjesse** [comment]
Connections in flight are not returned to the pool until their response bodies have been consumed. Imagine a large streaming response: we don't want to buffer it; it's the application's job to close the response body.

**Comment by harmanjassal** [comment]
But what happens if application is down but load balancer is returning the response. In this framework should return the connection to pool.
