### ISSUE TITLE
Do not unzip if Accept-Encoding header is set

### ISSUE THREAD

**Issue by mhausherr** [square/okhttp#1579]
If a custom Accept-Encoding header like "gzip,deflate" is set OKHttp doesn't unzip the response.

Can be reproduced with okcurl:

    okcurl -H "Accept-Encoding: gzip,deflate" "https://squareup.com/global/fr/register"

return gzipped content

    okcurl "https://squareup.com/global/fr/register"

return correct content. TransparentGzip mode is active so compressed data travels over the network.

**Comment by swankjesse** [comment]
If you omit the `Accept-Encoding` header, you get the behavior you want.

(OkHttp assumes that if you're providing the header, then you're also handling its consequences.)

**Comment by pdegand** [comment]
I understand the choice that if the end user provides the header, he is responsible for decoding, but I think this should be clearly documented somewhere. (wiki ?)

Currently, the only way to find this out is to read [HttpEngine.java](https://github.com/square/okhttp/blob/master/okhttp%2Fsrc%2Fmain%2Fjava%2Fcom%2Fsquareup%2Fokhttp%2Finternal%2Fhttp%2FHttpEngine.java#L127) comments.

**Comment by swankjesse** [comment]
Sure, we can do that. Which documentation did you read before running into this problem?

**Comment by swankjesse** [comment]
('cause that's where the documentation needs to go)

**Comment by pdegand** [comment]
I think it could be in the Wiki, Calls section

Something like this would have totally helped us :

### About transparent Gzip compression

OkHttp will automatically add `Accept-Encoding: gzip` header to your requests and will decode them if the response contains the `Content-Encoding: gzip` header.

However, if you manually set an `Accept-Encoding` header to your requests, OkHttp will NOT decode the response even though the `Content-Encoding: gzip` header is present. You are then responsible of the decoding.

If you just want Gzip compression, let OkHttp do the work for you and don't force any `Accept-Encoding` header.
