### ISSUE TITLE
CertificatePinner not checking whole chain?

### ISSUE THREAD

**Issue by aradomski** [square/okhttp#1583]
Hi!
I've tested certificate pinning on https://google.pl and i think i found some strange bug.

The proper pins for google.pl are (shown by library in logcat):

    builder.add("www.google.pl", "sha1/9bN1Z2tDICtsshLb3mdhnl1i5E4=")
    .add("www.google.pl", "sha1/Q9rWMO5T+KmAym79hfRqo3mQ4Oo=")
    .add("www.google.pl", "sha1/wHqYaI2J+6sFZAwRfap9ZbjKzE4=");

But when I change it to

    builder.add("www.google.pl", "sha1/raaandom=")
    .add("www.google.pl", "sha1/Q9rWMO5T+KmAym79hfRqo3mQ4Oo=")
    .add("www.google.pl", "sha1/wHqYaI2J+6sFZAwRfap9ZbjKzE4=");

everything still works fine. Shouldn't i check whole chain of cert pins?

In CertificatePinner in check(String hostname, List<Certificate> peerCertificates) method I found that only one of pins match is enough to accept certificate as valid. Shouldn't it check whole chain?

**Comment by swankjesse** [comment]
Certificate pinning is in addition to regular certificate trust checking. What's the attack that checking the entire chain prevents?

**Comment by aradomski** [comment]
When your certificate is compromised you simply update your app with your new key sha1. When whole chain is checked you are safe from this point. When only one of the  certificate is checked you are still vulnerable (During the gap between certificate compromising and system certificates updates).  

It also brings me a question. In every tutorial i saw there was told to use whole chain of certificate. Why should I do that when only one is checked?
In my opinion pinning only your certificate gives your higher level of safety than pinning whole chain.

**Comment by swankjesse** [comment]
If you'd like this behavior, you can implement it yourself using an interceptor. There's already an example recipe of a blacklisted certificate that you can use as a starting point.

Forcing all of your users to update your app from the Play Store each time you update your certificates is lousy. It's safer, but only in the way that wearing a helmet while you drive to work is safer.
