### ISSUE TITLE
Vary headers not working on Android

### ISSUE THREAD

**Issue by nfuller** [square/okhttp#1589]
This exception showed up during Android testing with ToT:

04-25 09:19:23.659  5471  5495 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'com.android.okhttp.Request com.android.okhttp.Response.request()' on a null object reference
04-25 09:19:23.659  5471  5495 E AndroidRuntime:         at com.android.okhttp.internal.http.OkHeaders.varyHeaders(OkHeaders.java:180)
04-25 09:19:23.659  5471  5495 E AndroidRuntime:         at com.android.okhttp.Cache$Entry.<init>(Cache.java:547)
04-25 09:19:23.659  5471  5495 E AndroidRuntime:         at com.android.okhttp.Cache.put(Cache.java:228)
04-25 09:19:23.659  5471  5495 E AndroidRuntime:         at com.android.okhttp.Cache.-wrap0(Cache.java)
04-25 09:19:23.659  5471  5495 E AndroidRuntime:         at com.android.okhttp.Cache$1.put(Cache.java:142)
04-25 09:19:23.659  5471  5495 E AndroidRuntime:         at com.android.okhttp.AndroidShimResponseCache.put(AndroidShimResponseCache.java:71)
04-25 09:19:23.659  5471  5495 E AndroidRuntime:         at android.net.http.HttpResponseCache.put(HttpResponseCache.java:209)
04-25 09:19:23.659  5471  5495 E AndroidRuntime:         at com.squareup.okhttp.internal.http.ResponseCacheAdapter.put(ResponseCacheAdapter.java:109)
04-25 09:19:23.659  5471  5495 E AndroidRuntime:         at com.squareup.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:633)
04-25 09:19:23.659  5471  5495 E AndroidRuntime:         at com.squareup.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:381)
04-25 09:19:23.659  5471  5495 E AndroidRuntime:         at com.squareup.okhttp.internal.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:328)
04-25 09:19:23.659  5471  5495 E AndroidRuntime:         at com.squareup.okhttp.internal.http.HttpURLConnectionImpl.getHeaderFields(HttpURLConnectionImpl.java:175)
04-25 09:19:23.659  5471  5495 E AndroidRuntime:         at com.squareup.okhttp.internal.http.DelegatingHttpsURLConnection.getHeaderFields(DelegatingHttpsURLConnection.java:178)
04-25 09:19:23.659  5471  5495 E AndroidRuntime:         at com.squareup.okhttp.internal.http.HttpsURLConnectionImpl.getHeaderFields(HttpsURLConnectionImpl.java:25)

It's a valid failure - the app in question is bundling a version of OkHttp and so the shim layer (converting between java.net and OkHttp classes) is being used. It's not handling Vary headers properly. I'm going to upload a fix.

**Comment by swankjesse** [comment]
@nfuller  Any further action required here?

**Comment by nfuller** [comment]
AFAIK, done.
