### ISSUE TITLE
Remove Apache and UrlConnection shims?

### ISSUE THREAD

**Issue by JakeWharton** [square/okhttp#1609]
Towards the end of this year, an idea of v3 will begin to take shape and it should probably also include the removal of these two shims along with it.

OkHttp v1 was an `HttpUrlConnection` implementation and we offered an `HttpClient` shim for easy integration into existing code that used it. OkHttp v2 had its own API and we updated the `HttpClient` to use it and switched the `HttpUrlConnection`-based API to run on internal classes (including special-cased paths). OkHttp v3 will be an evolution of the API for new features and as those are being implemented having these two shims will only serve to slow us down.

The `HttpClient` integration in Android has been deprecated. Providing a shim for it will serve little value by the time v3 is completed. Java users are unlikely to have been benefitting from such feature as they can just choose between the two. Additionally, these APIs are similar in their object-oriented nature so someone could very easily write the shim themselves if one was actually required.

The `HttpUrlConnection` shim is an interesting one in that it is what contributed to OkHttp powering the Android OS. While this issue does not cover the part of the shim that applies to Android (which is also partially covered by the 'android-support' module), offering the shim as supported solution for _any_ `HttpUrlConnection` usage should be removed.

**Comment by swankjesse** [comment]
They've served their purpose. The critical question is how much of HttpURLConnection's interaction model we support going forward.

**Comment by swankjesse** [comment]
I’m quite eager to nuke the `HttpURLConnection` shim because it significantly complicates the implementation of OkHttp. I don’t care nearly as much about the Apache API since it’s easily implemented atop our public API.

**Comment by swankjesse** [comment]
https://publicobject.com/2015/12/15/okurlfactory-is-going-away/

**Comment by swankjesse** [comment]
Now HttpURLConnection is also implemented on top of our native API. It is much less of a burden going forward.
