### ISSUE TITLE
Consider upgrading HttpUrl to IDNA 2008

### ISSUE THREAD

**Issue by swankjesse** [square/okhttp#1615]
We're currently using `java.net.IDN` which implements IDNA 2003 on the systems I tried.
http://www.unicode.org/reports/tr46/

I actually wrote & discarded a nearly-complete implementation here:
https://github.com/square/okhttp/pull/1612

The PR does mapping, but not punycode or deviants.

**Comment by yschimke** [comment]
IDN hasn't taken over, we don't see enough usage to justify owning custom implementation, so closing.  Following the JVM and Android platform.

Won't fix.
