### ISSUE TITLE
Allow CertificatePinner.java to be extended

### ISSUE THREAD

**Issue by superyair** [square/okhttp#1622]
It would be nice to be able to extend CertificatePinner.java to, for example, use sha2 instead of sha1 algorithm. In order to do this it would suffice deleting the word 'final' from the definition of this class. A better alternative would be to parametrize the class allowing to pass the hashing algorithm as an argument. 

Is there any reason for this class being final?

**Comment by swankjesse** [comment]
We're going to do this natively with HPKP.
https://github.com/square/okhttp/issues/1567

If you'd like to do your own trust mechanism, you can. See this example:
https://github.com/square/okhttp/blob/master/samples/guide/src/main/java/com/squareup/okhttp/recipes/CustomTrust.java

**Comment by swankjesse** [comment]
The certificate pinner isn't designed for inheritance. I'd much rather implement HPKP (or similar) for everyone instead of each user doing their own subclasses.
