### ISSUE TITLE
Implement & enforce hostname label limits

### ISSUE THREAD

**Issue by swankjesse** [square/okhttp#1637]
The spec is particular about 253 characters for the domain (without dot) and 1..63 characters for each label. See http://www.unicode.org/reports/tr46/#ToASCII

(Follow up to https://github.com/square/okhttp/issues/1486)

**Comment by swankjesse** [comment]
Turns out neither Chrome, Safari, nor Firefox impose these limits, at least not in their JavaScript APIs. I'm going to icebox this.

**Comment by yschimke** [comment]
Won't fix.
