### ISSUE TITLE
Make all setter methods in OkHttpClient return `this` or add Builder

### ISSUE THREAD

**Issue by sherter** [square/okhttp#1643]
I'm wondering why some setter methods in `OkHttpClient` return `this` (which is very convenient) and some return `void`. Are there any reasons for this? If there are reasons, a `OkHttpClient.Builder` would be great.

These return void:
- `setConnectTimeout`
- `setFollowRedirects`
- `setReadTimeout`
- `setRetryOnConenctionFailure`
- `setWriteTimeout`

**Comment by swankjesse** [comment]
The change is not binary compatible so changing will break all clients.

**Comment by swankjesse** [comment]
https://github.com/square/okhttp/pull/2090/files
