### ISSUE TITLE
CertificatePinner not working on Android

### ISSUE THREAD

**Issue by baszn** [square/okhttp#1644]
I tried to implement the CertificatePinner as described in the documentation (http://square.github.io/okhttp/javadoc/com/squareup/okhttp/CertificatePinner.html). I've tested it on the oneplus one, Android 5.0.2 official rom (minSdk15, targetSdk 22). The request is completing successfully, without any exception being thrown. It should throw an exception as described in the documentation. What's going wrong here? Or is it just a bug? I've included my code below:

```java
RequestBody body = new FormEncodingBuilder()
                .add("test1", "lorem")
                .add("test2", "ipsum")
                .build();

        CertificatePinner certificatePinner = new CertificatePinner.Builder()
                .add(httpshostname, "sha1/testest")
                .build();

        OkHttpClient client = new OkHttpClient();
        client.setCertificatePinner(certificatePinner);

        Request request = new Request.Builder()
                .url(httpshostname)
                .addHeader("Cookie", "cookiename" + cookievalue)
                .addHeader("Content-Type", "application/x-www-form-urlencoded")
                .post(body)
                .build();

        Response response = client.newCall(request).execute();
```

**Comment by artem-zinnatullin** [comment]
Please add content or at least format of the `httpshostname`.

It should be a host name without protocols and slashes, for example: `test.com`

**Comment by baszn** [comment]
@artem-zinnatullin Thanks! That was the problem. The certificatePinner expects an hostname without a protocol, and I was giving it with the protocol. This issue is closed now, but maybe an idea to add a warning in the future? Or maybe give a clear indication in the documentation? Thanks for your help again!

**Comment by artem-zinnatullin** [comment]
@swankjesse let's add hostname format validation to `CertificatePinner.Builder#add()`?

Users expect increase of security from `CertificatePinner`, better to fail early, otherwise `CertificatePinner` will silently skip the check.

**Comment by swankjesse** [comment]
@artem-zinnatullin sure, hostname validation is a good idea. I'll accept PRs. Unfortunately, what constitutes a valid hostname is non-trivial. We might be able to reuse code from HttpUrl, once that's ready.

**Comment by artem-zinnatullin** [comment]
Great, saw your PRs for HttpUrl, I'll wait for it.

чт, 14 мая 2015, 22:58, Jesse Wilson <notifications@github.com>:

**Comment by artem-zinnatullin** [comment]
@baszn can you close the issue?
