### ISSUE TITLE
Change to HttpUrl breaks API expectations for okhttp-ws

### ISSUE THREAD

**Issue by pwerry** [square/okhttp#1652]
This commit: https://github.com/square/okhttp/commit/2b236fd66abbfffeb1c07a22dde5dcb8d3a2032c

Forces the url to begin with `http://` or `https://` or it will return null. The `WebSocketCall` class will handle the conversion from ws to http, but the `Request` must accept url's that begin with `ws://` or `wss://`

Workaround is to pre-parse ws urls to http before firing them to the `Request`

**Comment by swankjesse** [comment]
Yeah, agreed on both the problem on the workaround. Not sure what the solution is. I don't love the idea of making `HttpUrl` accept `ws:` addresses, since ws/http are not interchangeable throughout the API.

**Comment by swankjesse** [comment]
@JakeWharton thoughts?

**Comment by VicV** [comment]
Just a note, this completely breaks https://github.com/nkzawa/engine.io-client.java

They recently switched from Java-Websocket to okhttp Websocket. 

This function specifically breaks down with it: https://github.com/nkzawa/engine.io-client.java/blob/master/src/main/java/com/github/nkzawa/engineio/client/transports/WebSocket.java#L194

Curious whether or not this will affect any other major libs.

**Comment by swankjesse** [comment]
@VicV @pwerry 

For now you can workaround like this:

```
    String wsOrHttpUrl = ...
    String httpUrl = wsOrHttpUrl.replaceFirst("^ws:", "http:").replaceFirst("^wss:", "https:");
```

**Comment by VicV** [comment]
@swankjesse Unfortunately its not my library that's broken due to this, its his, and then by extension my own.

 I'll submit a PR to his library and see if everything works without the ws schemas...

**Comment by JakeWharton** [comment]
`HttpUrl` could be responsible for coalescing the 'ws' and 'wss' schemes into 'http' and 'https', respectively. Other than that, I don't see many options on making this work.

**Comment by swankjesse** [comment]
How about coalescing in `Request.Builder`? https://github.com/square/okhttp/pull/1663

**Comment by maillouxc** [comment]
> For my specific use case, I ended up needing to manipulate a WS URI, and ended up using the android.net.Uri builder instead

Can you elaborate? I need to actually send a ws: uri over the wire, in my use case the http: converted one will not work.

**Comment by swankjesse** [comment]
My recommendation is for you to create a `WebsocketUrl` class with methods like `toString()` and `toHttpUrl()`. We don’t include such a class in OkHttp but you shouldn’t have much trouble writing your own. You can even delegate to `HttpUrl` if you want it to do your parsing etc.

**Comment by maillouxc** [comment]
I'm not sure I follow - how would this solve my problem? It would still have to be handled by OkHttp which doesn't allow for such urls, unless I am missing something here.

**Comment by mdnt** [comment]
> I'm not sure I follow - how would this solve my problem? It would still have to be handled by OkHttp which doesn't allow for such urls, unless I am missing something here. HttpUrl is final, so I can't just extend it and override the method that enforces parsing, and I'm not sure that would work even if I could.

You could use java reflection to instaniate HttpUrl and fix isHttps status
