### ISSUE TITLE
Add hostname validation to CertificatePinner.Builder 

### ISSUE THREAD

**Issue by artem-zinnatullin** [square/okhttp#1653]
Related to #1644.

Requires `HttpUrl`:

> @swankjesse:  hostname validation is a good idea. I'll accept PRs. Unfortunately, what constitutes a valid hostname is non-trivial. We might be able to reuse code from HttpUrl, once that's ready.

**Comment by swankjesse** [comment]
HttpUrl is ready, though we don't yet have great hostname validation there.

**Comment by swankjesse** [comment]
Fixed by https://github.com/square/okhttp/pull/2617
