### ISSUE TITLE
Throw ProtocolException on non-empty 204s and 205s

### ISSUE THREAD

**Issue by swankjesse** [square/okhttp#1664]
Currently Retrofit is guarding against this manually. The HTTP client should do it.
https://github.com/square/retrofit/pull/845/files#diff-826f81c41efbd1fcc363bccd4dbc4f17R143

**Comment by JakeWharton** [comment]
This seems to be explicitly allowed in `UrlConnection.responseCodeDisagreesWithHeaders`. Le sigh.
