### ISSUE TITLE
Multi-tag support for cancel request by tag(s)

### ISSUE THREAD

**Issue by michaelchucoder** [square/okhttp#1666]
i found OkHttp does not support multi-tag, i build the request with tag(defaultQueryTag)
and tag(url)

            resultRequest = new Request.Builder()
                    .url(UrlConstants.baseUrl+url)
                    .headers(builder.build())
                    .post(body)
                    .tag(defaultQueryTag)
                    .tag(url)
                    .build();

now i want to cancel by urlTag also cancel by defaultQueryTag (cancel all the request)

how can i make it.

    /**
     * cancel  request by Url
     *
     * @param urlTag
     */
    public static void cancelUrl(String urlTag) {
        client.cancel(urlTag);
    }
    /**
     * cancel a request
     *
     * @param call
     */
    public static void cancelCall(Call call) {
        call.cancel();
    }
    /**
     * cancel all the request
     */
    public static void cancelAll() {
        client.cancel(defaultQueryTag);
    }

**Comment by swankjesse** [comment]
Canceling by tags is a mistake in our design. Your best bet is to retain a reference to the `Call` and call `cancel` on that.
