### ISSUE TITLE
WebSocket onOpen / onMessage race

### ISSUE THREAD

**Issue by JakeWharton** [square/okhttp#1667]
`WebSocketCall` used to have the following for opening a web socket:
```java
    // Start a dedicated thread for reading the web socket.
    new Thread(new NamedRunnable("OkHttp WebSocket reader %s", request.urlString()) {
      @Override protected void execute() {
        while (webSocket.readMessage()) {
        }
      }
    }).start();

    listener.onOpen(webSocket, response);
```

This is racy in that a message could be read and delivered to the `onMessage` callback before `onOpen` had a chance to store a reference to the `WebSocket` in a field for a reply.

In the Autobahn testing, I naively made a change to the code:
```java
    listener.onOpen(webSocket, response);

    // Start a dedicated thread for reading the web socket.
    new Thread(new NamedRunnable("OkHttp WebSocket reader %s", request.urlString()) {
      @Override protected void execute() {
        //noinspection StatementWithEmptyBody
        while (webSocket.readMessage()) {
        }
      }
    }).start();
```

This fixes the race but presents a problem if `onOpen` does all of their interaction in a blocking fashion.

I have two ideas for rectifying this, and I am looking for more:
 * Expose an explicit call to start the reader thread in `onOpen` which would be called automatically after `onOpen` returned.
 * Start the reader thread on first interaction with the `WebSocket` instance or automatically after `onOpen` returned.

**Comment by swankjesse** [comment]
Another option:

```
    new Thread(new NamedRunnable("OkHttp WebSocket reader %s", request.urlString()) {
      @Override protected void execute() {
        listener.onOpen(webSocket, response);
        while (webSocket.readMessage()) {
        }
      }
    }).start();
```

**Comment by JakeWharton** [comment]
That still assumes `onOpen` does not block.
```java
@Override void onOpen(WebSocket ws, Response response) {
  while (ping.get()) {
    ws.sendPing(new Buffer().writeUtf8("Ping!"));
    SystemClock.sleep(1000);
  }
  ws.close();
}
```

**Comment by swankjesse** [comment]
Someday we want to break the 1:1 relationship between sockets and threads. But we need to make sure that calls to webhooks are properly serialized: we never callback with a message until the previous callback has returned.

**Comment by JakeWharton** [comment]
Consensus: `onOpen` will not be allowed to block indefinitely. Reading messages will not spawn their own thread but instead use the same thread on which `onOpen` is called. This means that reading messages will not start until `onOpen` has returned and will need documented as such. Bonus: this also means that the thread which calls `onOpen` is the same that calls `onMessage`/`onPing`/`onClose`!
