### ISSUE TITLE
More info on https://github.com/square/okhttp/issues/1531

### ISSUE THREAD

**Issue by mntgoat** [square/okhttp#1671]
I've continued to have the issue described on #1531 however today I realized I can turn off IPv6 on my router and as soon as I did that (after a router reboot) the page started loading in 1 second instead of 60 seconds. So I don't know if this is something that needs to be fixed or the expected behavior but I figured I should report it.

**Comment by swankjesse** [comment]
It's difficult to say what OkHttp should do here. From its perspective the IPv6 address should work. Happy Eyeballs might be our best bet. Other ideas?

**Comment by mntgoat** [comment]
Figured as much. Personally I think my ATT router has issues with IPv6 because if enabled Chrome can take a long time to load Google searches, but when disabled it will load them right away. And it isn't just on one machine, happens on both my Mac and my Linux machine. So maybe/hopefully this is just an isolated issue affecting only me :)

**Comment by swankjesse** [comment]
Cool. Hopefully this gets better with happy eyeballs.
