### ISSUE TITLE
Builder for RecordedResponse

### ISSUE THREAD

**Issue by phajduk** [square/okhttp#1672]
Newbie here. I've started digging in tests and noticed following [RecordedResponse](https://github.com/square/okhttp/blob/master/okhttp-tests/src/test/java/com/squareup/okhttp/RecordedResponse.java) constructor calls:
```java
new RecordedResponse(networkResponse.request(), networkResponse, null, null, null);
```  
```java
new RecordedResponse(priorResponse.request(), priorResponse, null, null, null);
```
etc.

I want to implement builder:
```java
new RecordedResponse.Builder().request(priorResponse.request()).response(priorResponse)
        .build();
```
Does it make sense?

**Comment by swankjesse** [comment]
Neat idea.

But it's support code for tests. Any investment in making the API nice might not be worthwhile, particularly since this sort of thing is subject to frequent & aggressive refactoring.
