### ISSUE TITLE
IllegalArgumentException in Request.Builder().url()

### ISSUE THREAD

**Issue by Tolriq** [square/okhttp#1673]
Okhttp 2.4.0 now produce java.lang.IllegalArgumentException with malformed urls while it was not the case in 2.3.0 where you can catch MalformedURLException in the call.

This is a major API change and should be present in the changelog.

This will trigger a lot's of problem to users that miss this change.

**Comment by Tolriq** [comment]
And I do not know how it works internally in Android Studio but adding automated try catch on the url command does not work, maybe it should have throws IllegalArgumentException so that users are easily aware of this possibility.

**Comment by swankjesse** [comment]
IllegalArgumentException? Could you provide a short test case?

**Comment by Tolriq** [comment]
```
Request.Builder request = new Request.Builder()
.url("http://" + ip + ":" + port + "/jsonrpc")
.header("connection", "close");

```

Use "aaa aaaa" with a space for ip and you get the IllegalArgumentException.

To be honest I never thought of this use case in my app but seeing all the crashes with today release users have lot's of imagination when talking about an ip / hostname field.

Previously those error where catched at execute level
```
httpClient.newCall(request.build()).execute()
```

With MalformedURLException but now the crash is earlier, and I'm sure lot's of people rely on MalformedURLException to check for user input failure and not on requestbuilder errors as there was not before :(

Not a big deal when you know it but this passed my 1800 beta testers tests and triggered lot's of crash, and usually on first start wizard so loosed users :(
Anyway this look like a normal error to catch just needs proper documentation to avoid problem as major API change.

**Comment by swankjesse** [comment]
Ahh, yeah, you're right. I'll update our changelog to note this explicitly.

**Comment by Tolriq** [comment]
Thanks.

And I don't know the best way but either url javadoc should say  throws IllegalArgumentException or explicitely add the throws in function so that advanced editors warns users as it's easy to miss this during tests.
