### ISSUE TITLE
URLConnection.getInputStream().read() does not always timeout with SocketTimeoutException

### ISSUE THREAD

**Issue by nfuller** [square/okhttp#1676]
The docs for URLConnection.setReadTimeout() suggest a SocketTimeoutException should be thrown. 

Instead, in some cases, an InterruptedIOException is thrown.

e.g.

java.io.InterruptedIOException: timeout
at com.android.okhttp.okio.AsyncTimeout.exit(AsyncTimeout.java:258)
at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:215)
at com.android.okhttp.okio.RealBufferedSource.read(RealBufferedSource.java:50)
at com.android.okhttp.internal.http.HttpConnection$FixedLengthSource.read(HttpConnection.java:398)
at com.android.okhttp.okio.RealBufferedSource$1.read(RealBufferedSource.java:338)
at libcore.java.net.URLConnectionTest.testReadTimeouts(URLConnectionTest.java:1796)

The behavior was changed in OkHttp commit 411a33810512340fd68fc5c33423badd52d290e9

On Android we should continue with the documented behavior.

**Comment by nfuller** [comment]
@swankjesse : Here's a commit. It's not nice but I can see why you don't want to use SocketTimeoutException. Would it be possible to have an identifiable subclass of InterruptedIOException out of Okio rather than matching the message string? e.g. TimeoutIOException?

https://github.com/nfuller/okhttp/commit/789c1f95dc924965cb9bd7fe33a528d181010674

**Comment by swankjesse** [comment]
Yep, we should throw SocketTimeoutException. Probably wants an update to Okio to trigger the throw.

**Comment by nfuller** [comment]
@swankjesse Does that mean you're ok with a new exception in Okio, or were you thinking of something else?

**Comment by swankjesse** [comment]
Okio's `AsyncTimeout` has two methods that throw:

```
  /**
   * Throws an InterruptedIOException if {@code throwOnTimeout} is true and a
   * timeout occurred.
   */
  final void exit(boolean throwOnTimeout) throws IOException {
    boolean timedOut = exit();
    if (timedOut && throwOnTimeout) throw new InterruptedIOException("timeout");
  }

  /**
   * Returns either {@code cause} or an InterruptedIOException that's caused by
   * {@code cause} if a timeout occurred.
   */
  final IOException exit(IOException cause) throws IOException {
    if (!exit()) return cause;
    InterruptedIOException e = new InterruptedIOException("timeout");
    e.initCause(cause);
    return e;
  }
```

I think we want to change that to allow the subclass to provide its own exception type. Probably just a method like `protected IOException newTimeoutException(IOException cause)` that accepts a nullable cause. That way OkHttp can use SocketTimeoutExceptions, but timeouts to file systems or in-memory pipes don't have to.

**Comment by swankjesse** [comment]
... @nfuller if you wanna send a PR that adds this, I'll merge it!

**Comment by nfuller** [comment]
@swankjesse Works for me. Thanks. I'll put something together.

**Comment by nfuller** [comment]
If the Okio change is taken, there's a possible follow-up here: commit 028a6c75ebf311b34b2f04c08eeef31a002c5396

I haven't looked at why, but Spdy still throws InterruptedIOException, not SocketTimeoutException. I assume because the Spdy code is wrapping a stream, not a socket, but I'm ok with it throwing InterruptedIOException if you are. HttpURLConnection correctly throws SocketTimeoutException with the Okio change.

**Comment by swankjesse** [comment]
Hmm. . .  I'm guessing for SPDY you need to configure it in `SpdyConnection.java`, which also subclasses `AsyncTimeout`.

**Comment by nfuller** [comment]
Yes - you're right. Which behavior would you prefer?

**Comment by swankjesse** [comment]
I think I want to see socket timeouts in SPDY also. The catch is that we need to use the okio snapshot to get that method.

**Comment by swankjesse** [comment]
All fixed.
