### ISSUE TITLE
Exceptions in HttpUrl

### ISSUE THREAD

**Issue by ericedens** [square/okhttp#1677]
@swankjesse , I was reading through HttpUrl, and I have some (unsolicited :) ideas on the exceptions:

Maybe IllegalArgumentException here? That would be more consistent with what you have elsewhere in the class, and more descriptive.
https://github.com/square/okhttp/blob/master/okhttp/src/main/java/com/squareup/okhttp/HttpUrl.java#L316
````java
  /** Returns this URL as a {@link URL java.net.URL}. */
  public URL url() {
    try {
      return new URL(url);
    } catch (MalformedURLException e) {
      throw new RuntimeException(e); // Unexpected!
    }
  }
````

I usually associate IllegalStateException with calling a method at an innapropriate time for the underlying system -- like if a socket is already closed. Maybe IllegalArgumentException?
https://github.com/square/okhttp/blob/master/okhttp/src/main/java/com/squareup/okhttp/HttpUrl.java#L331

````java
  public URI uri() {
    try {
      return new URI(url);
    } catch (URISyntaxException e) {
      throw new IllegalStateException("not valid as a java.net.URI: " + url);
    }
  }
````

I think IllegalArgumentException might be a better translation, since getByAddress throws UnknownHostException when the IP address is of an illegal length.  (http://download.java.net/jdk7/archive/b123/docs/api/java/net/InetAddress.html#getByAddress(byte[])). Also, passing the cause could help a client with debugging by preserving the stack trace.
https://github.com/square/okhttp/blob/master/okhttp/src/main/java/com/squareup/okhttp/HttpUrl.java#L1271
````java
      try {
        return InetAddress.getByAddress(address);
      } catch (UnknownHostException e) {
        throw new AssertionError();
      }
 ````

**Comment by swankjesse** [comment]
For both the URL and the InetAddress, we don't expect either exception to ever be thrown. If you can create a test case that causes these exceptions to be thrown, I'll be impressed.

For the URI, `IllegalArgumentException` is not appropriate because the method doesn't accept any arguments.

**Comment by ericedens** [comment]
@swankjesse , So it is! I spent a bit of time trying to find a case where URL or InetAddress throws, and indeed, you've got it locked down really well.
