### ISSUE TITLE
okhttp default protocol，http/1.1 not http/2

### ISSUE THREAD

**Issue by stdying** [square/okhttp#1678]
```java
public class GetExample {

  OkHttpClient client = new OkHttpClient();


  String run(String url) throws IOException {
    Request request = new Request.Builder()
        .url(url)
        .build();
    Response response = client.newCall(request).execute();
    return response.body().string();

  }

  public static void main(String[] args) throws IOException {
    GetExample example = new GetExample();

    String response = example.run("https://http2.golang.org/reqinfo");
    System.out.println(response);
  }

}
```

https://http2.golang.org/reqinfo use http/2

but the example result
> Method: GET
> Protocol: HTTP/1.1
> Host: http2.golang.org   .........

not 
> Method: GET
> Protocol: HTTP/2.0
> Host: http2.golang.org

how to use http2 in example

**Comment by swankjesse** [comment]
You need to configure ALPN in your VM. See OkHttp’s tests for an example of how to do this with maven. It's awkward on the desktop because ALPN requires modifying the boot classpath.

**Comment by swankjesse** [comment]
Some ALPN examples: https://github.com/square/okhttp/wiki/Building

**Comment by stdying** [comment]
good
