### ISSUE TITLE
CertificatePinner is pinning against public key rather than SPKI

### ISSUE THREAD

**Issue by anirudhgargsc** [square/okhttp#1679]
It seems like [CertificatePinner](https://github.com/square/okhttp/blob/master/okhttp/src/main/java/com/squareup/okhttp/CertificatePinner.java#L230) is extracting the public key and pinning against that, rather than pinning against the SPKI.
Pinning against SPKI is what [Adam Langley's blog](https://www.imperialviolet.org/2011/05/04/pinning.html) recommends to avoid misinterpretation attacks:
> Also, we're hashing the SubjectPublicKeyInfo not the public key bit string. The SPKI includes the type of the public key and some parameters along with the public key itself. This is important because just hashing the public key leaves one open to misinterpretation attacks. Consider a Diffie-Hellman public key: if one only hashes the public key, not the full SPKI, then an attacker can use the same public key but make the client interpret it in a different group. Likewise one could force an RSA key to be interpreted as a DSA key etc.

Are there plans to move from public key to SPKI?

Thanks!

**Comment by swankjesse** [comment]
OkHttp uses the exact same pinning mechanism as Chrome.
