### ISSUE TITLE
Reply executor sharing in okhttp-ws.

### ISSUE THREAD

**Issue by pepyakin** [square/okhttp#1681]
It is some kind of dull that it is not possible to share reply executor created in `WebSocketCall`. It would be cool to use single executor for writing.

**Comment by JakeWharton** [comment]
We don't have access to the executor on which you are writing. For all we know you're blocking a single thread and writing in a tight loop.

**Comment by pepyakin** [comment]
Oh, I see. I didn't think about tight loop thing. 
But anyway thought about there is periodically and non-deterministically (I mean on server's behalf) spawning thread makes me sad. Especially on the Android.

**Comment by JakeWharton** [comment]
Here's another counter-example, what if you never write and only read? How are pongs and responding to close supposed to happen?

**Comment by pepyakin** [comment]
Why not to just pass executor like that?

```java
public final class WebSocketCall {

  public static WebSocketCall create(OkHttpClient client, Request request) {
    ThreadPoolExecutor replyExecutor =
          new ThreadPoolExecutor(1, 1, 1, SECONDS, new LinkedBlockingDeque<Runnable>(),
              Util.threadFactory(String.format("OkHttp %s WebSocket", url), true));
      replyExecutor.allowCoreThreadTimeOut(true);
 
      return create(client, request, replyExecutor);
  }

  public static WebSocketCall create(
      OkHttpClient client, Request request, Executor executor) { /* ... */ }
  
  // ... and so on
}

**Comment by JakeWharton** [comment]
Even that has problems. If I enqueue 1000 writes on that executor and then receive a ping, the pong has to wait until those 1000 writes succeed in order to send the pong. The current behavior will write the pong between the first and second writes (or if the first write is framed it will go between the frames).

**Comment by pepyakin** [comment]
OK, you win. All I came up with requires to break clients, change API greatly, which is not feasible to solve such minor issue like this.

**Comment by JakeWharton** [comment]
Yeah I'm open to something better, but with all the requirements that are needed we couldn't come up with anything better. Hopefully you either have a ping-free peer which means the thread is never started or you have a ping-heavy peer which means the thread is always doing work and isn't interfering with your writes.
