### ISSUE TITLE
HttpUrl encodes `+` to `%20` which makes OkHttp unusable with base64 URLs such as Cloudfront signed URLs

### ISSUE THREAD

**Issue by SalomonBrys** [square/okhttp#1682]
We are using Cloudfront to store our images. These images are displayed on our Android app via Picasso which uses OkHTTP.

The problem is that OkHTTP re-encode the URLs, changing `+` to `%20`.

    HttpUrl.parse("http://test.org/res?signature=a+b=").toString() == "http://test.org/res?signature=a%20b="

As cloudfront URLs contains base64 encoded signatures and because `+` is one of the 64 characters used by Base64, the fact that OkHttpUrl replaces those `+` by `%20` breaks the signature. Cloudfront therefore shows a "Could not unencode Signature" error.

**Comment by swankjesse** [comment]
Yikes.

**Comment by swankjesse** [comment]
Seems like you probably want base64url. http://en.wikipedia.org/wiki/Base64#URL_applications

**Comment by swankjesse** [comment]
Just curious: does switching to Base64url work in your use case?

**Comment by SalomonBrys** [comment]
This does work:

    url = url.replaceAll("\\+", "%2B").replaceAll("/", "%2F").replaceAll("=", "%3D")

**Comment by swankjesse** [comment]
The alternative is that in OkHttp 2.5 we don't canonicalize pre-encoded `foo+bar` to `foo%20bar`. I'm open to that.

**Comment by SalomonBrys** [comment]
While I understand the need to encode spaces to `%20`, what is the reason to encode pluses ?

**Comment by swankjesse** [comment]
The spec requires we encode plus.

**Comment by swankjesse** [comment]
I'm not going to take action on this; I think the best fix is for you to use base64url.
