### ISSUE TITLE
Inability to send an empty body with PUT request in 2.4.0

### ISSUE THREAD

**Issue by Tagakov** [square/okhttp#1686]
After updating from okhttp:2.3.0 to okhttp:2.4.0. I have many crashes linked to subject. 
I am doing PUT request like this
```Java
    @PUT("/user/subscribe/{friend_id}")
    Observable<Response> subFriend(@Path("friend_id") long friendId);
```
Unfortunately I dont have access to a server implementation, is there any workaround except providing `@Body String stub` parameter and passing empty string to it?

**Comment by JakeWharton** [comment]
This is Retrofit you are referring to, and no, there is no workaround except that you provided. The disconnect between Retrofit and OkHttp around empty bodies has already been fixed on Retrofit's `master` and will be included in the next release. Either downgrade to 2.3.0 or do the empty body workaround for now.
