### ISSUE TITLE
OkHttp don't encode non-ASCII User-Agent.

### ISSUE THREAD

**Issue by yyjdelete** [square/okhttp#1688]
OkHttp don't encode non-ASCII User-Agent.
That will make an invalid request on some Android with non-ASCII model name.

![image](https://cloud.githubusercontent.com/assets/1819074/8028576/47bf0c38-0de3-11e5-9c7b-ed93933ed693.png)

**Comment by yyjdelete** [comment]
com.squareup.okhttp:okhttp-urlconnection:2.3.0

**Comment by JakeWharton** [comment]
Dupe of #891. Can you comment with your case on that issue?
