### ISSUE TITLE
(Suggestion) Allow and check for null values in HttpUrl.parse()

### ISSUE THREAD

**Issue by hzsweers** [square/okhttp#1690]
Using some of our code as an example since we've run into this recently:

Consider the case where you're consuming JSON data from an API, and you want to extract metadata from a `url` field. `HttpUrl` is great for this, but it assumes that the passed in value is not null (it calls `.length()` early on). 

The result is that you have to do two null checks before you can safely start real work.

```java
if (url != null) {
  HttpUrl httpUrl = HttpUrl.parse(url);
  if (httpUrl != null) {
    // Do stuff
  }
}
```

If it is lenient enough to take empty strings, I think it would make sense to also accept null values (the result is the same right?)

```java
HttpUrl httpUrl = HttpUrl.parse(url);
if (httpUrl != null) {
  // Do stuff
}
```

What do you think? Obviously it's a trivial issue, but I think this solution would prove useful to the many that allowed try/catch + MalformedUrlException to catch potentially null values as well. It should be fairly easy to add in, but I'd be happy to submit a PR if you're open to it.

**Comment by swankjesse** [comment]
I don't like it because it hides bugs. In particular it collapses two cars together:

 * I have a URL, but it's not valid
 * I don't have a URL

You could imagine your JSON app failing because you mistyped "url" as "ur1" but not crashing.

**Comment by hzsweers** [comment]
I guess that's fair. I think it's also valid for the case of "I might have a URL and it might be invalid", but we might be an overly specific use case.
