### ISSUE TITLE
When WebSocketWriter encounteres a logical error / protocol violation, delegate the exception to onFailure

### ISSUE THREAD

**Issue by borg972** [square/okhttp#1691]
The server I'm working against (which I don't own) sometimes closes the connection badly without conforming with the protocol. 

WebSocketWriter  in that case throws a ilegalArgumentException. see this line:

https://github.com/square/okhttp/blob/master/okhttp-ws/src/main/java/com/squareup/okhttp/internal/ws/WebSocketWriter.java#L102

Since this runs in an internal thread it can't be caught by my code and thus it crashes my app. 
 
Althow the server shouldn't do that, the app shouldn't crash eitther, so I think I should be able to handle this. I suggest delegating the exception to onFailure.

**Comment by JakeWharton** [comment]
Out of curiosity, what code does it use to close the connection?

**Comment by borg972** [comment]
It sends 0 for the code and the reason isn't null, I think it's an empty string but I don't remember for sure, I can check if it helps..

**Comment by JakeWharton** [comment]
Do you have any idea what software the server is running? I'm really hesitant to violate the spec but this case isn't terribly bad.

**Comment by borg972** [comment]
All I know is It's built with python, I don't know what libraries they use, but I can ask.. I guess whatever they use allows them to send any code and any reason with no logical/protocol restrictions. 

And I see what you mean about the spec, but shouldn't there be always at least an option to treat a violation that originates on the other side more nicely than crashing the app? as long as it's a logical error..

**Comment by JakeWharton** [comment]
Is this still happening? I'm having trouble seeing how it could happen in the code. It looks like it was fixed on April 20th, but your report is much newer than that. I'll try writing a test case.

**Comment by borg972** [comment]
It definitely happened when I reported this, I was using 2.4 

Now I can't check since I no longer work on that project

**Comment by JakeWharton** [comment]
Exception handling is vastly more robust now with many more tests around behavior. No one change contributed to fixing this issue. There was a lot of internal refactoring that all contributed to it generally being more stable. Currently there's only one place where we allow exceptions to escape to the enclosing thread and that's when an exception is thrown _inside_ of `onFailure`.

**Comment by borg972** [comment]
This is great news! thanks!
