### ISSUE TITLE
OkHttp should provide an option to automatically retry connections that return http status 408

### ISSUE THREAD

**Issue by ahanhine** [square/okhttp#1693]
I am experiencing intermittent http 408 status errors when using OkHttp 2.4.0 or 2.3.0 and Android 5.0 or M Preview. When I downgrade to OkHttp 2.2.0 the problem does not occur.

Http specification states that:
408 Request Timeout
The client did not produce a request within the time that the server was prepared to wait. The client MAY repeat the request without modifications at any later time.

If we add following to HttpEngine.followUpRequest()
case HTTP_CLIENT_TIMEOUT:
  return userRequest.newBuilder().build();
The problem does not occur any more.

Could there be an option in OkHttp to allow retry when http status 408 is returned?

**Comment by swankjesse** [comment]
Dumb question: if it timed out on the first attempt, why would it succeed on attempt #2?

**Comment by ahanhine** [comment]
The 408 response usually comes in milliseconds, for example 15ms. This leads me to think that the socket connection has been used previously and the server at some point has decided that the connection is no longer valid and written the status 408 to sockets stream. When our application or in this case OkHttp, tries to reuse that socket, the status 408 is returned almost instantly. Also retrying the request, usually suceeds.

**Comment by swankjesse** [comment]
Got it. Is this a quirk of your particular application server? I've never heard of this.

**Comment by ahanhine** [comment]
It could be a a quirk, because the problem is not present in all our test environments. My coworker studied the issue and found similar problems reported to for example web browsers. I'll try to attach links to those when I get a chance.

**Comment by ahanhine** [comment]
Here are the issues that seem similar:
https://bugzilla.mozilla.org/show_bug.cgi?id=248827
https://code.google.com/p/chromium/issues/detail?id=377581

**Comment by swankjesse** [comment]
Strange, yeah it looks like this is a thing we should handle. Thanks for the links.

**Comment by ahanhine** [comment]
No broblem, thanks for the great library.

**Comment by dave-r12** [comment]
Are you still in favor of supporting this? At first glance, it looks small in scope, mind if I grab it?

**Comment by swankjesse** [comment]
Do it!

**Comment by dave-r12** [comment]
Should the HttpURLConnection API be ignored? Using the default JDK implementation, it returns the 408 response.

**Comment by swankjesse** [comment]
I think what you have for HttpURLConnection is right. We’re not particular about being consistent with the JDK’s implementation, it’s stuck in 1995.

**Comment by dave-r12** [comment]
Closed with #2302 ?
