### ISSUE TITLE
HttpUrl#canonicalize() is not escape `;`(semicolon) character 

### ISSUE THREAD

**Issue by keima** [square/okhttp#1694]
I'm using OkHttp for sending html tags (contains style attributes).
In 2.2.0, okhttp is running perfectly.
But I upgrade it to 2.4.0, server received corrupted html.
This server treats '&' and ';' as separator.
(hoge=fuga&foo=bar -> {hoge: fuga, foo: bar} , hoge=fuga;foo=bar -> {hoge: fuga, foo: bar} )
http://www.w3.org/TR/1999/REC-html401-19991224/appendix/notes.html#h-B.2.2

Result of investigation, I found that incompatible changes from 2.2.0 to 2.4.0.

As 2.2.0, value of `FormEncodingBuilder.add(key,value)` is escaped `URLEncoder.encode(value, "UTF-8")`.
(hoge=fu;ga&foo=bar -> {hoge: fu%3Bga, foo: bar})

But 2.4.0, value is escaped `HttpUrl#canonicalize()`.
This method (or, `HttpUrl.QUERY_COMPONENT_ENCODE_SET`) is not treated ';'. So value data is still alive semicolon!
(hoge=fu;ga&foo=bar -> {hoge: fu, ga:null , foo: bar})
(sorry, ga:null is no confidences... In any way, hoge's value is corrupted.)

I think, Add semicolon to `HttpUrl.QUERY_COMPONENT_ENCODE_SET`.
https://github.com/square/okhttp/blob/master/okhttp/src/main/java/com/squareup/okhttp/HttpUrl.java#L262
But I don't try yet and there are no confidences for me :(

**Comment by swankjesse** [comment]
OkHttp's behavior is consistent with web browsers.

**Comment by keima** [comment]
If OkHttp's behavior is (largely) similar to modern web browsers, I hope it should follow [RFC 3986](http://www.ietf.org/rfc/rfc3986.txt) and [W3C HTML5 recommendation](http://www.w3.org/TR/html5/forms.html#url-encoded-form-data).

There are various views about what is escaped ( `(` is escaped or not ), 
In all documents which I read, semicolon is handled as escape.
Therefore, I think OkHttp's `FormEncodingBuilder ` should be escape `;` just like `&`.

If you say OkHttp don't treat semicolon as escaped, I want to know why it is.

**Comment by swankjesse** [comment]
Try this in your browser's JavaScript console:
```
  new URL("http://host/path?fun;ga").href
```

**Comment by swankjesse** [comment]
...though reading the HTML spec, it suggests we might want different behavior for FormEncodingBuilder vs. canonicalizing the query of a URL. We can do that.

**Comment by swankjesse** [comment]
https://github.com/square/okhttp/pull/1714
