### ISSUE TITLE
Evaluate removing IOException from ResponseBody close

### ISSUE THREAD

**Issue by JakeWharton** [square/okhttp#1696]
Propagating the already-rare exception that can be thrown when closing the underlying `Source` of a `ResponseBody` is not actionable and puts the caller in an awkward position. Is there any use to this exception? Or should we simply swallow it for the caller's convenience since it's what they are going to do anyway?

**Comment by swankjesse** [comment]
Let's do this in 3.0. Should we do likewise for `Source.close()` ?
