### ISSUE TITLE
can okhttp build post parameters with http entity

### ISSUE THREAD

**Issue by coderlin** [square/okhttp#1697]
how to set multi post body?
I found the sample, but it only provide json type

**Comment by JakeWharton** [comment]
A multipart example is here: https://github.com/square/okhttp/blob/97262e523d16ea2ee9060c25d720cab593bf5641/samples/guide/src/main/java/com/squareup/okhttp/recipes/PostMultipart.java#L40-L45

**Comment by JakeWharton** [comment]
If you have usage questions about OkHttp please as on StackOverflow with the 'okhttp' tag.
