### ISSUE TITLE
CertificatePinner pinning against public key of root cert

### ISSUE THREAD

**Issue by anirudhgargsc** [square/okhttp#1699]
Servers often send a certificate chain without the self-signed root cert at the end of the chain, because clients usually contain that cert in their trust store.
For instance, running CertificatePinner with a bogus pin on www.google.com returns the following chain:
>sha1/QO5igIZiHh7a+KVqv8Yc5acwgzM=: CN=www.google.com,O=Google Inc,L=Mountain View,ST=California,C=US
>sha1/Q9rWMO5T+KmAym79hfRqo3mQ4Oo=: CN=Google Internet Authority G2,O=Google Inc,C=US
>sha1/wHqYaI2J+6sFZAwRfap9ZbjKzE4=: CN=GeoTrust Global CA,O=GeoTrust Inc.,C=US

If we look at the certificate chain sent by www.google.com through OpenSSL, it shows that that last cert is not self signed, and is in fact signed by Equifax Secure CA which is the root in this case. But because the Equifax Secure CA cert is not a part of the chain, CertificatePinner doesn't check its public key.

So in scenarios like these, where the certificate chain does not contain the root cert, is there any way to pin against the public key of the root cert?

Thanks!

**Comment by swankjesse** [comment]
Yeah, that's a good idea. We should fix `CertificatePinner` to use the CA cert if it's used for trust.

**Comment by anirudhgargsc** [comment]
Yea I think it will be useful to have the option of pinning against all the certs in the chain and the issuer root if not in the chain.
Are you guys planning on adding this in a future release?

**Comment by swankjesse** [comment]
Yes, we'll add this. It's a bug that we don't have it.

**Comment by swankjesse** [comment]
I suspect I might need hacks or reflection to extract the trusted certificate! I’m anxiously awaiting a better answer here: http://stackoverflow.com/questions/31920719/getting-the-trusted-x509certificate-for-a-java-sslsocket

**Comment by swankjesse** [comment]
I think we're going to need to capture the TrustManager when we create the initial SSLContext, and keep that around so we can use it to look up the trusted cert. It's a hassle!

**Comment by anirudhgargsc** [comment]
Yea that makes sense. Doesn't seem like there's a straightforward way to do this. What a headache.
