### ISSUE TITLE
FormEncodingBuilder throws exception when empty

### ISSUE THREAD

**Issue by Wopple** [square/okhttp#1704]
I am trying to build a POST request, and in some cases there are no parameters that I need to provide. However, when I go to build the request without adding parameters, this line throws:

https://github.com/square/okhttp/blob/master/okhttp/src/main/java/com/squareup/okhttp/FormEncodingBuilder.java#L58

Is this intended behavior? Is this a limitation imposed by HTTP?

**Comment by swankjesse** [comment]
Seems like we're being overzealous. If you want to send a PR to remove that (and the corresponding test if there is one) please do. Otherwise we'll take care of it soon.
