### ISSUE TITLE
okhttp application level OkHttpClient instance

### ISSUE THREAD

**Issue by mutindaz** [square/okhttp#1707]
I was wondering if there will be any performance bottleneck or issues if I create one instance of OkHttpClient to serve my "entire android application". I.e.In my Application class, I create a static public variable that will contain a instance of OkHttpClient and whenever I need to do an http request I basically build a request object then use the created okhttpclient instance to fire the request.

Sample snippet
```java
public class MyApplication extends Application {
    public static OkHttpClient httpClient;
	
	@Override
	public void onCreate() {
		super.onCreate();
		
		httpClient = new OkHttpClient();
	}
	
}

// Making request 1
Request request1 = new Request.Builder().url(ENDPOINT).build();
Response response = MyApplication.httpClient.newCall(request1).execute();

// Making request 2
Request request2 = new Request.Builder().url(ENDPOINT).build();
Response response = MyApplication.httpClient.newCall(request2).execute();
```

**Comment by JakeWharton** [comment]
The use of a single instance is the preferred pattern. This allows requests to share things like caching, a connection pool, information about routes to IP addresses, and thread pools.

The mechanism for how you do this is up to you and yes, a "global" static variable is one easy way to accomplish this.

**Comment by mutindaz** [comment]
@JakeWharton thanks.

**Comment by newmanw** [comment]
@JakeWharton you mention 

> The use of a single instance is the preferred pattern

IMHO adding this to the recipes section would be helpful.

**Comment by JakeWharton** [comment]
It's the very first thing in the documentation for the `OkHttpClient` type:

> ### OkHttpClients should be shared
>
> OkHttp performs best when you create a single OkHttpClient instance and reuse it for all of your HTTP calls. This is because each client holds its own connection pool and thread pools. Reusing connections and threads reduces latency and saves memory.

**Comment by newmanw** [comment]
@JakeWharton agree, however since you provided and awesome recipe section, the javadoc is not the first place I looked.  No worries, just thought it might help others that look to the recipes first.
