### ISSUE TITLE
Add basic authentication support

### ISSUE THREAD

**Issue by vicmosin** [square/okhttp#1721]
Couldn't find any examples or tests of basic authentication of OkHttp with mockwebserver. Would be nice  to add that feature

**Comment by swankjesse** [comment]
https://github.com/square/okhttp/wiki/Recipes#handling-authentication

**Comment by vicmosin** [comment]
Yes, but what about server-side? I am talking about checking valid authentication within MockWebServer...

**Comment by fhaertig** [comment]
I had the same issue: only return a valid MockResponse when the request contained a "Authorization" header. Spent some hours with that, but the solution is very simple:
okhttpclient seems to try the url first without authorization header and only if the response is "HTTP/1.1 401 Not Authorized" it will add the header and make a new request. So you need to set a dispatcher at MockWebServer and in case of missing "Authorization" header, `return new MockResponse().setStatus("HTTP/1.1 401 Not Authorized")`
