### ISSUE TITLE
Connection reset by peer

### ISSUE THREAD

**Issue by Grozny** [square/okhttp#1724]
Anyone knows this error?

- recvfrom failed econnreset (connection reset by peer)

**Comment by shurane** [comment]
@Grozny is the error reproducible? What version of `okhttp` are you on? Can you post a gist of a small project where the error happens?

**Comment by Grozny** [comment]
I'm using okhttp v2.4.0, and this error occured while testing my app on 2G.
Thanks for the support.

2015-06-25 5:22 GMT+01:00 Ehtesh Choudhury <notifications@github.com>:

**Comment by swankjesse** [comment]
Likely a network hiccup. No action for us to take here.
