### ISSUE TITLE
[HttpUrl] '+' getting encoded to '%20'

### ISSUE THREAD

**Issue by sushantkhanna** [square/okhttp#1726]

**Comment by sushantkhanna** [comment]
Certain encoders change it to '%2B'.
Not sure if this was intended, or was against standards.
Reporting just in case.

**Comment by swankjesse** [comment]
It's deliberate. Is it causing you grief?

**Comment by sushantkhanna** [comment]
Was. But worked around it. :)

Just for knowledge sake, What should the proper encoding according to standard? Saw a bit of debate on this earlier.

**Comment by swankjesse** [comment]
There’s no universal standard. `%20` requires fewer special cases; `+` is shorter.

**Comment by sushantkhanna** [comment]
Ok. Closing this.
