### ISSUE TITLE
Support Certificate Pinning

### ISSUE THREAD

**Issue by swankjesse** [square/okhttp#173]
We should support it. Possibly with help from conscrypt.

**Comment by 0xced** [comment]
For reference, certificate pinning is now implemented: https://github.com/square/okhttp/wiki/HTTPS#certificate-pinning

**Comment by nelenkov** [comment]
This design is a bit weird -- why does the pinner know about hostnames? Best practice is to pin the issuer of the server certificate (i.e., intermediate CA, etc.), pinning host certificates is asking for trouble.

**Comment by swankjesse** [comment]
@nelenkov that's what chrome does.

**Comment by scottyab** [comment]
I thought you're better off pinning your host/leaf certificate as you have control of that? but interested to hear otherwise. I've not found that definitively recommends which public key/cert in the chain to pin.

**Comment by swankjesse** [comment]
The goal of pinning is to reduce how many CAs you trust. Without pinning, any rogue or compromised CA can impersonate your server.

Pinning the leaf allows you to trust zero CAs, but at great operational risk: if you lose/compromise/expire your one pinned certificate you're in trouble.

Pinning a few CAs or intermediate CAs gives you more operational freedom without significant exposure. You're only in trouble if those CAs are compromised.

**Comment by doridori** [comment]
I think that the approach pinning leaf or intermediate certs are both valid and really depends on the situation and how and where the code is deployed.

> You're only in trouble if those CAs are compromised.

May be too high risk for some implementations, which also may be able to handle the case that...

> if you lose/compromise/expire your one pinned certificate...

can be handled via out of bound update triggers etc.

> The goal of pinning is to reduce how many CAs you trust

Many approaches do use pinning to achieve this goal - while some go the leaf node route to reduce the amount of trusted certs to (effectively) one.

> pinning host certificates is asking for trouble.

@nelekov would be interested to know if this is due to the cert update / rotation paths or you are referring to something else here

**Comment by swankjesse** [comment]
@doridori yeah, the network interceptors API can be used to do arbitrary verification. The built-in pinner exists to make the common case easy. Most application developers shouldn't need to spend a lot of time worrying about this.

**Comment by nelenkov** [comment]
@doridori I was referring to the host cert update, introduction of reverse proxies/SSL gateways and the like. 

As for my original comment, the code/interface is fine, I was mislead by the documentation waring ('pinning is dangerous'). The only problem might be with misconfigured hosts who return unrelated certificates, not sure if the underlying SSL impl checks for that. Also cf. `CertificateChainCleaner`  in the original Moxie code
