### ISSUE TITLE
Determine if network error

### ISSUE THREAD

**Issue by Leland-Takamine** [square/okhttp#1730]
On a mobile device, it's common to run into connectivity problems. Is there any way to determine if the IOException thrown by Call.execute() is a temporary network error? Or alternatively, is there a way to determine if a retry (with exponential backoff) makes sense in the case of an error?

**Comment by swankjesse** [comment]
It's always a temporary network error. What else would it be?

**Comment by Leland-Takamine** [comment]
UnknownHostException is thrown by the code below:
```java
Request request = new Request.Builder().url("http://thisHostDoesNotExist1234.com").build();
client.newCall(request).execute();
```

When there is no network connectivity, UnknownHostException is also thrown here:
```java
Request request = new Request.Builder().url("http://google.com").build();
client.newCall(request).execute();
```

In the first example it doesn't make sense to retry since the url is incorrect. So it seems like it's not always "safe" to retry the network request upon an IOException (ie: it will fail forever). I was wondering if there are other exceptions that are thrown that might result in this same situation.

**Comment by swankjesse** [comment]
I just registered thisHostDoesNotExist1234.com, so you're going to need to come up with another example.

**Comment by JakeWharton** [comment]
@Leland-Takamine See also http://developer.android.com/training/monitoring-device-state/connectivity-monitoring.html which can help you make decisions.
