### ISSUE TITLE
Consider permessage-deflate extension for WebSocket

### ISSUE THREAD

**Issue by JakeWharton** [square/okhttp#1733]
The HyBi IETF WG has picked up recently and it looks to be moving this to RFC. Chrome, Firefox, and many libraries support this extension. Given the widespread use of text-based messages for content, compression has an opportunity for giving [up-to 75% reduction in payload size](https://www.igvita.com/2013/11/27/configuring-and-optimizing-websocket-compression/#parameters). The [latest draft](https://tools.ietf.org/html/draft-ietf-hybi-permessage-compression-24) was just published two days ago.

**Comment by JakeWharton** [comment]
I think this just got a thumbs up on its way to publication (if i'm reading the email correctly): https://datatracker.ietf.org/doc/draft-ietf-hybi-permessage-compression/

**Comment by ashoemaker** [comment]
:+1:

**Comment by OFmarting** [comment]
It is not possible to fully implement the specification on Android/with Java. This is the case because the Android/Java API doesn't offer the possibility to set the window bits of the Inflater/Deflater. Further the required SYNC_FLUSH option is not supported in Java until Java 7 and on Android until API Level 19 (as @swankjesse  pointed out in the [Okio source](https://github.com/square/okio/blob/4023ed0d4a6a09a485963a1d608030bdeeea8135/okio/src/main/java/okio/DeflaterSink.java#L89)). Although the option can be used since Android 2.3.

**Comment by swankjesse** [comment]
Not a big fan of that spec. Seems like a lot more machinery than should be necessary. I think we'll be able to implement enough of the spec to be useful!

**Comment by gdaniels** [comment]
Is this still on the radar?  The spec is an RFC now... https://tools.ietf.org/html/rfc7692.  Would love to see this in okhttp.

**Comment by b95505017** [comment]
Any news? BTW nv-websocket-client support this spec.
https://github.com/TakahikoKawasaki/nv-websocket-client

**Comment by JakeWharton** [comment]
At this time we don't have plans to implement.

**Comment by yosiat** [comment]
Hi @JakeWharton ,
Will you accept any PR for implementing per message deflate in okhttp?

**Comment by monil1334** [comment]
@JakeWharton  any updates on implementing the extension?

**Comment by JakeWharton** [comment]
No plans to. Feel free to send a PR

**Comment by swankjesse** [comment]
Just confirmed that this interops nicely with the [NodeJS Web Sockets](https://github.com/websockets/ws) library. That library has many tuning parameters; OkHttp currently has none. But their defaults are reassuring; both chose 1024 as the threshold to trigger compression.

https://github.com/square/okhttp/pull/5839
https://github.com/square/okhttp/pull/5848
https://github.com/square/okhttp/pull/5851
https://github.com/square/okhttp/pull/5867
https://github.com/square/okhttp/pull/5869
https://github.com/square/okhttp/pull/5871

**Comment by swankjesse** [comment]
Huge thanks to @AntonRutkevich for pushing this forward!

**Comment by AntonRutkevich** [comment]
Thanks @swankjesse for the implementation!
With your deep OkHttp understanding, it's much cleaner and simpler than the original one.
