### ISSUE TITLE
Default header

### ISSUE THREAD

**Issue by stdex** [square/okhttp#1734]
RequestBody formBody = new FormEncodingBuilder()
                .add("data", json)
                .build();

        com.squareup.okhttp.Request request = new com.squareup.okhttp.Request.Builder()
                .url(url)
                .post(formBody)
                .addHeader("Content-Type", "application/x-www-form-urlencoded; charset=UTF-8")
                .addHeader("Accept-Language", "ru-RU,ru;q=0.8,en-US;q=0.5,en;q=0.3")
                .build();

        Headers requestHeaders = request.headers();
        for (int i = 0; i < requestHeaders.size(); i++) {
            Log.d("requestTT:", requestHeaders.name(i) + ": " + requestHeaders.value(i));
        }

It's return:
>D/requestTT:﹕ Content-Type: application/x-www-form-urlencoded; charset=UTF-8
>D/requestTT:﹕ Accept-Language: ru-RU,ru;q=0.8,en-US;q=0.5,en;q=0.3

Where Host? Where User-Agent?
What about this pull: https://github.com/square/okhttp/pull/1063 ?

**Comment by swankjesse** [comment]
Those headers are added later, as OkHttp prepares your request for the network. You can observe the raw network data with an HTTP debugging tool like [Charles](http://www.charlesproxy.com/) or by using an OkHttp [network interceptor](https://github.com/square/okhttp/wiki/Interceptors).
