### ISSUE TITLE
Malformed URL RuntimeException thrown on internal thread during asynchronous request

### ISSUE THREAD

**Issue by UrK** [square/okhttp#1735]
It seems OkHttp crashes application due to malformed URL. Below is the sample code to crash it. There is no way to catch the exception, as it happens on on internal thread, hence- application crash

    void testCrash() {
        OkHttpClient okclient = new OkHttpClient();
        Request request = new Request.Builder().url("10.0.0.1").build();
        okclient.newCall(request).enqueue(new Callback() {
            @Override
            public void onFailure(Request request, IOException e) {
                Log.v("foo", "Failure", e);
            }

            @Override
            public void onResponse(Response response) {
                Log.v("foo", "success");
            }
        });
    }

**Comment by swankjesse** [comment]
Are you on 2.4.0? I would have expected the crash on the call into `url()`.

Mind pasting the exception?

**Comment by UrK** [comment]
Ooops.
I copied configuration from [Retrofit docs](http://square.github.io/retrofit/#download) and have not paid attention, I was using version 2.0.0 instead of a more recent 2.4.0.
Updating OkHttp to 2.4.0 solved the issue and the exception is thrown as expected in Request builder where it can be caught.

**Comment by swankjesse** [comment]
https://github.com/square/retrofit/pull/929
