### ISSUE TITLE
My program doesn't stop immediately after onResponse

### ISSUE THREAD

**Issue by haidaraM** [square/okhttp#1739]
Hello.
First, thanks for your library which is awesome and sorry for my English.
I use okhttp to do some simple asynchronous calls but my program doesn't stop immediately after the call of onResponse. It takes some seconds and then stops. I don't have this issue on Android but on my desktop. I have the same issue with others URLs. Maybe there is something I did wrong.
I use : `okhttp-2.4.0` and `okio-1.4.0` and java8. 

This is my code : 

    private final OkHttpClient client = new OkHttpClient();

    public void run() throws Exception {

        Settings.setProxy();
        Request request = new Request.Builder()
                .url("http://openlibrary.org/search.json?q=la+famille")
                .build();

        client.newCall(request).enqueue(new Callback() {
            @Override
            public void onFailure(Request request, IOException e) {
                e.printStackTrace();
            }

            @Override
            public void onResponse(Response response) throws IOException {
                if (!response.isSuccessful()) throw new IOException("Unexpected code " + response);

                System.out.println(response.body().string());
            }
        });
    }

**Comment by swankjesse** [comment]
The dispatcher is pooling threads, and those threads are keeping your VM alive. Fix by installing your own Executor in the Dispatcher returned from OkHttpClient.

**Comment by haidaraM** [comment]
Thx for your reply. This my solution which works. Can you just tell me if i'm doing right : 

private final OkHttpClient client = new OkHttpClient();

    public void run() throws Exception {

        ExecutorService executorService = Executors.newSingleThreadExecutor();
        Dispatcher dispatcher2 = new Dispatcher(executorService);

        client.setDispatcher(dispatcher2);

        Settings.setProxy();
        Request request = new Request.Builder()
                .url("http://openlibrary.org/search.json?q=la+famille")
                .build();

        client.newCall(request).enqueue(new Callback() {
            @Override
            public void onFailure(Request request, IOException e) {
                e.printStackTrace();
                System.out.println("error");
            }

            @Override
            public void onResponse(Response response) throws IOException {
                if (!response.isSuccessful()) throw new IOException("Unexpected code " + response);

                System.out.println(response.body().string());
                executorService.shutdown();
            }
        });
    }

**Comment by JakeWharton** [comment]
You can also call
```java
client.getDispatcher().getExecutorService().shutdown();
```
at the end of the program.

In such a trivial program, however, you'd probably want to use `execute()` instead of `enqueue()`.

**Comment by haidaraM** [comment]
Ok thx. This program is just for test. I will okHttp in an Android application in which I can't perform synchronous calls.
