### ISSUE TITLE
API that makes it easy to read the response body without consuming it

### ISSUE THREAD

**Issue by swankjesse** [square/okhttp#1740]
So that interceptors can log the body or whatever.

Here's a strawman:

```
public final class Response {
  ...

  /**
   * Buffers the entire body into memory and returns a copy of it. Future
   * calls to {@link #body()} will consume this buffered data.
   */
  public ResponseBody bufferedBody()
```
Zero or more callers can call `bufferedBody()`, and then only one caller can call `body()`. And once anyone calls body, that's the last one we'll return.

**Comment by MichaelEvans** [comment]
@swankjesse I'm interested in working on this, couple questions:

0. Is this still of interest?
1. What's the expected behavior if a caller tries to call `bufferedBody()` after `body()`? Or `body()` twice?  (I guess I'm unsure what "that's the last one we'll return." means)

**Comment by swankjesse** [comment]
1. Yes!
2. bufferedBody() after body() throws. All calls to body() return the same shared instance. As you read it, you consume it!

**Comment by cemo** [comment]
@swankjesse Please make it. I am pretty much new to Android world and trying to log response body. I really could not find a way to logging buffered response with interceptors.

**Comment by swankjesse** [comment]
```
  /**
   * Returns a copy of {@code body} without consuming it. This buffers up to {@code limit} bytes of
   * {@code body} into memory.
   *
   * @throws IOException if {@code body} is longer than {@code limit}.
   */
  private ResponseBody copy(ResponseBody body, long limit) throws IOException {
    BufferedSource source = body.source();
    if (source.request(limit)) throw new IOException("body too long!");
    Buffer bufferedCopy = source.buffer().clone();
    return ResponseBody.create(body.contentType(), body.contentLength(), bufferedCopy);
  }
```

**Comment by JakeWharton** [comment]
Clever. Stealing that (for now)!
