### ISSUE TITLE
HttpUrl encodedPath clears encodedPathSegments

### ISSUE THREAD

**Issue by fuwaneko** [square/okhttp#1742]
I'm using retrofit 2.0.0 from snapshots (mainly because it's cleaner than 1.9, does not depend on GSON which I don't use, and allows for better error processing). If I set up retrofit endpoint to something like "http://127.0.0.1/api" that "/api" part is ignored resulting in invalid urls. I've debugged up to HttpUrl Builder encodedPath and resolvePath methods. First one does not allow urls which not begin in "/", second clears encodedPathSegments if url begin with "/" (thus in retrofit case "/api" is always removed from resulting url). Please, advise.

**Comment by swankjesse** [comment]
Try `http://127.0.0.1/api/` with a trailing slash.

**Comment by fuwaneko** [comment]
@swankjesse no, it does not change anything. If you look at resolvePath logic, it always clears encodedPathSegments [if it's argument begins with "/"](https://github.com/square/okhttp/blob/master/okhttp/src/main/java/com/squareup/okhttp/HttpUrl.java#L1010), so it doesn't matter what I have in endpoint url — it's path will always be neglected. And encodedPath method which is called from retrofit [does not allow](https://github.com/square/okhttp/blob/master/okhttp/src/main/java/com/squareup/okhttp/HttpUrl.java#L732) it's argument not to begin with "/", it throws.

**Comment by JakeWharton** [comment]
Don't use a leading slash in the relative URL.

**Comment by fuwaneko** [comment]
As I've mentioned *twice* already if I don't use leading slash in the relative URL, encodedPath will throw IllegalArgumentException. I even pointed to the LOC, where this check happens. And actually, retrofit itself will not allow that and throw the same thing even before HttpUrl.

**Comment by JakeWharton** [comment]
Retrofit is happy with non-leading slash or even a full URL with a
different host. It uses resolve, not encodedPath.

**Comment by fuwaneko** [comment]
I see, snapshot version of retrofit on sonatype is very different from master. After compiling retrofit from master, adding trailing slash to endpoint url and removing trailing slash from REST resource urls it works as expected.
