### ISSUE TITLE
Make it possible to update a cache entry?

### ISSUE THREAD

**Issue by snowpong** [square/okhttp#1750]
I know that through the Cache urls() iterator it is possible to remove cache entries, but I was wondering if it could also be possible to update an entry?

Either in a nice way, or if there us a hacky way that works too :)

My use case is: I want to change a boolean property in a JSON object (and invalidate the ETag) without having to do a server roundtrip again. Now I can of course just introduce some local storage in SQLite and manipulate it there, but I'm trying to avoid that in this case.

**Comment by swankjesse** [comment]
Sorry, there's way too many moving parts to offer this: headers, checksums, etags, etc. would all be incorrect.

**Comment by snowpong** [comment]
Fair enough, I knew it was a long shot :)
