### ISSUE TITLE
Can't use the spdy connection in android 4.4

### ISSUE THREAD

**Issue by LineLin** [square/okhttp#1751]
I test to send a request to a server which support http2.0 or spdy3.1 , but I see it only work on the old protocol http1.1 ，my device is  4.4.2， okhttp version is 2.4.

Through Wireshark , I saw there has not ALPN or NPN in Client Hello during handshake. When I use demo on Android L(5.0) , I can see the ALPN but server hello can't contain NPN or ALPN , it confuse me .

I can access  my website in chrome, that show the server is not problem!

Can anyone give some advice to me ?

Client hello in 5.0
![image](https://cloud.githubusercontent.com/assets/3251196/8665292/d77c1288-2a14-11e5-8bf1-159f71a8eb92.png)

Server hello in 5.0
![image](https://cloud.githubusercontent.com/assets/3251196/8665298/ea9c5a58-2a14-11e5-963c-3e0b05479566.png)

**Comment by swankjesse** [comment]
You'll get better results on Stackoverflow. This tracker is for bug reports with test cases and feature requests only.

**Comment by LineLin** [comment]
NPN is not support on okhttp?

**Comment by swankjesse** [comment]
NPN is no longer supported in OkHttp.

**Comment by LineLin** [comment]
it's means that if i wan to use okhttp  to enjoy the feature of http2.0 ,there has some limit:
1.  the device android version must be 5.0 or higher
2.  the server must support ALPN ,not NPN

But it's so confuse me , when i access google's image resources , it also work in http1.1 。
@swankjesse

**Comment by swankjesse** [comment]
What action would you like us to take here?
