### ISSUE TITLE
[Question] Performance of a singleton instance OkHttpClient

### ISSUE THREAD

**Issue by huyduongtu** [square/okhttp#1752]
I'm using `OkHttp` at the first time. I see the tutorial said that If wanna use `Response Caching`, I must call `new OkHttpClient(`) exactly once (a singleton instance). `OkhttpClient` is thread-safe by `synchronized` methods. But there are many threads connects to the network to get remote data simultaneously in my application, some threads must wait for a thread have done getting data to execute its operation.
So Is it's performance not better than normal?
I mean If I don't enable `Reponse Caching`, Should I call `new OkHttpClient()` many times for better performance?
Thanks

**Comment by swankjesse** [comment]
You'll get a better answer faster on stackoverflow. This issues tracker is for bugs with test cases and feature requests only.

**Comment by huyduongtu** [comment]
I also posted on stackoverflow but haven't get the answer yet. 
[This is the link on stackoverflow.](http://stackoverflow.com/questions/31423154/performance-of-a-singleton-instance-okhttpclient)
You can answer my question on this.
My question is which one get the better performance? Singleton instance OkHttpClient or not?
