### ISSUE TITLE
Does BufferedSource and BufferedSink in HttpConnection need to be closed?

### ISSUE THREAD

**Issue by onlychoice** [square/okhttp#1754]
https://github.com/square/okhttp/blob/master/okhttp/src/main/java/com/squareup/okhttp/internal/http/HttpConnection.java#L79-L80

I haven't found any close call on source and sink referenced in FixedLengthSink, FixedLengthSource etc, is this intend behavior?

**Comment by swankjesse** [comment]
If youd like to report a bug, please provide a test case. As-is the public API requires you close the response body.

**Comment by onlychoice** [comment]
@swankjesse I have tried two ways:

1. InputStream is = response.body().byteStream(); is.close();
2. response.body().close();

both failed to closed the source generated by https://github.com/square/okio/blob/master/okio/src/main/java/okio/Okio.java#L128

**Comment by swankjesse** [comment]
Those streams are reused when the connection is pooled. So that a single socket can be used for multiple sequential calls.
