### ISSUE TITLE
MockWebServer SocketPolicy interrupting request

### ISSUE THREAD

**Issue by zack-shoylev** [square/okhttp#1755]
SocketPolicy has DISCONNECT_AFTER_REQUEST. Is there a way to force the socket to disconnect during the request, i.e. while the request is being read but before it is finished?

**Comment by JakeWharton** [comment]
This was added on master already and will be in 2.5. I forgot the exact
name of it, but it disconnects halfway through.

**Comment by zack-shoylev** [comment]
Is it done through SocketPolicy?

https://github.com/square/okhttp/blob/master/mockwebserver/src/main/java/com/squareup/okhttp/mockwebserver/SocketPolicy.java

I see DISCONNECT_DURING_RESPONSE_BODY, but don't see anything for the request.

**Comment by JakeWharton** [comment]
Ah, sorry. I read on mobile and all I saw was "read" and assumed response. I can look and see if it's feasible to add something similar for requests.

**Comment by swankjesse** [comment]
This is very difficult to do in a way that's useful. The writer can buffer as much as it wants, and it won't necessarily fail until it's done writing.

What case are you trying to test?

**Comment by zack-shoylev** [comment]
The specific case is testing uploading files and large files to a server.

**Comment by zack-shoylev** [comment]
Here is some extra info I got from a user who it seeing a problem I would like to reproduce with a test:

java.io.IOException: Error writing request body to server
        at sun.net.www.protocol.http.HttpURLConnection$StreamingOutputStream.checkError(HttpURLConnection.java:3478)
        at sun.net.www.protocol.http.HttpURLConnection$StreamingOutputStream.write(HttpURLConnection.java:3461)

**Comment by swankjesse** [comment]
Pull requests welcome. They should contain a test!

**Comment by JakeWharton** [comment]
I have this on a branch from long ago. Will PR.
