### ISSUE TITLE
No way to use HttpEngine directly since OkHttpClient is not able to be fully configured by outside packages

### ISSUE THREAD

**Issue by joshzana** [square/okhttp#1761]
I am writing some code that uses HttpEngine directly, in a manner similar to how Call or HttpUrlConnectionImpl use it, but customized for my use case.  In order to do this I need to get an instance of OkHttpClient that is fully configured, with none of the needed fields null.  If any are null, exceptions are thrown at various points later in the request/response.

I can manually mimic the behavior of copyWithDefaults using set* methods, but the problem is that at least one field (network) is not settable.

The way that Call gets around this is by issuing copyWithDefaults to get all the fields set up to the right defaults.

External code that wants to do the same does not have access to copyWithDefaults for a reason I can't see.

While exposing copyWithDefaults would be my preferred solution, other solutions include fixing missing setters, or adding a factory method that will return a client with defaults set.

**Comment by swankjesse** [comment]
The `internal` package is an out-of-bounds implementation detail. If you want to use code from within that package you need to fork OkHttp.

**Comment by joshzana** [comment]
Hmmm fair enough.  Didn't realize HttpEngine was internal.

What about adding a method to get a default-configured OkHttpClient similar to what copyWithDefaults does?

**Comment by swankjesse** [comment]
Use case?

**Comment by joshzana** [comment]
I take it back - the only use cases I can think of for that method would be using HttpEngine directly.

The real use case is that I want to adapt an existing HttpUrlConnection codebase to use OkHttp.  For GET I can just use Call and it suits my purposes, but for POST/PUT I need to build an intermediary that returns a writeable OutputStream for the request body, let the caller put some bytes into it, and call a finish() method, which will return the response code/inputstream/headers.

I'l have to figure out how to do this with just Call and a custom RequestBody.

Thanks for the help!
