### ISSUE TITLE
Cannot post cyrillic symbols with OkHttp.

### ISSUE THREAD

**Issue by whyte624** [square/okhttp#1764]
I'm trying to post cyrillic login and password with OkHttp:

    RequestBody formBody = new FormEncodingBuilder()
        .add("login", user)
        .add("pass", password)
        .build();

    Request request = new Request.Builder()
        .addHeader("User-Agent", USER_AGENT)
        .addHeader("Connection", "keep-alive")
        .url(URL)
        .post(formBody)
        .build();

    OkHttpClient client = new OkHttpClient();
    Response response = client.newCall(request).execute();
    if (!response.isSuccessful()) throw new IOException("Unexpected code " + response);
    String responseBody = response.body().string();

With latin symbols it works just fine.

**Comment by swankjesse** [comment]
Could you provide a test case with the expected behavior? FormEncodingBuilderTest should get you started.

**Comment by whyte624** [comment]
I've tried to post some data on a website. I cannot give you exact example.
I've managed to solve the issue with such code:

    .addEncoded("login", URLEncoder.encode(user, "CP1251"))
    .addEncoded("pass", URLEncoder.encode(password, "CP1251"))

As far as I understood, I should have encode my encoding and then use existing method addEncoded.

**Comment by swankjesse** [comment]
Cool. By the way, you should try to convince the webservice that expects CP1251 to upgrade their systems to also support UTF-8.
