### ISSUE TITLE
PATCH Request cannot be empty in 2.4.0 but can be 2.3.0

### ISSUE THREAD

**Issue by AndreasBackx** [square/okhttp#1778]
I updated to 2.4.0 and it wasn't mentioned in the changelog that PATCH requests can no longer be empty. Is it possible to add this to the changelog or perhaps even allow it again?

#1581 Might be relative as PATCH might've been missed?

**Comment by swankjesse** [comment]
Yeah, our support for exotic methods has always been pretty lame. Wanna send a pull requst?

**Comment by AndreasBackx** [comment]
Sure, shouldn't take too long looking at #1581.

**Comment by AndreasBackx** [comment]
Seems to be already fixed in 2.5. Do you still want me to make a pull request for adding the test in? The test is basically just a copy and paste of the put and post request empty test.

**Comment by swankjesse** [comment]
Nope. All good.
