### ISSUE TITLE
HTTP requests going out without TCP connection setup

### ISSUE THREAD

**Issue by shalindalal** [square/okhttp#1795]
I was observing a bunch of IOException due to connection being reset by server so I decided to get packet captures. What I observe in wireshark is that there are a number of HTTP requests going out on sockets that have not been setup correctly (shown below)
![screen shot 2015-08-06 at 8 36 21 pm](https://cloud.githubusercontent.com/assets/3520990/9128317/325ede06-3c7b-11e5-9a6b-ec646e7e9c9d.png)

The same request is successful on the second try on a different socket with proper connection setup (shown below)
![screen shot 2015-08-06 at 8 40 36 pm](https://cloud.githubusercontent.com/assets/3520990/9128340/6c3a3544-3c7b-11e5-9cdc-2009b0a6bbad.png)

I am testing this on Moto X with 5.1.1 and I have seen the same behavior on other versions too.

I am not sure how is this even possible that TCP packets are sent out on sockets without proper tcp handshake.

**Comment by swankjesse** [comment]
Is this a bug we can fix? Seems like a problem with your set set up. If you have any ideas on things we can change about our codebase to fix this, I'd love to hear 'em. Otherwise I'm closing this 'cause I don't think there's anything we can do.

**Comment by shalindalal** [comment]
I'll try to get some more details on this but I didn't see this when we were using HttpUrlConnection directly. I was wondering if there's something in the protocol stack that would allow trying to send data over sockets that have not been established or that have been closed.
