### ISSUE TITLE
SPDY/HTTP2 don't support connecting to a specific host of a Virtual Host

### ISSUE THREAD

**Issue by yschimke** [square/okhttp#1809]
Using HTTP/1.1 I can set the Host header e.g. example.org, but connect to a specific host by setting the direct ip in the url.  The HTTP/1.1 code doesn't set the Host header if already present.  This is useful for two scenarios

1) I want to connect to a specific host that is behind a load balancer and test it for errors.
2) I want to run a development instance of a webserver that uses self signed certs and I want to connect to localhost and also disable the trust manager and hostname verification.

However SPDY and  HTTP/2 both seem to always take the host from the request.  Apart from hacking /etc/passwd there doesn't appear to be a way to achieve this. e.g a proxy is logically different.  There are no obvious hooks for re-routing this request e.g. to CDNs, or overriding in an interceptor.

I am happy to make a pull request for this change if you think the current HTTP/1.1 logic also works for SPDY and HTTP/2.  OTherwise I'll make a reproduction test case and I'd be happy to hear any suggested workarounds.  n.b. this is for development testing only.

**Comment by swankjesse** [comment]
Hmm. . . the previous behavior was definitely a happy accident. I’m anxious about the consequences for other features, like cookies and caching. I think we’d be better off giving you the option to force the DNS of a host than to force the Host header.

**Comment by swankjesse** [comment]
You've now got the option of setting DNS explicitly.
