### ISSUE TITLE
How to inspect RequestBody

### ISSUE THREAD

**Issue by akhyrul** [square/okhttp#1812]
Is there any way to inspect RequestBody content after created?

I need it to write my own custom HttpRequest adapter for [SignPost](https://github.com/mttkay/signpost) library. [The `RequestBody#writeTo()` seems to work with `OutputStream` before](https://github.com/pakerfeldt/signpost-retrofit/blob/master/src/main/java/se/akerfeldt/signpost/retrofit/HttpRequestAdapter.java#L74-L81), why is it removed in the newest OkHttp library? How do I get the content? Should I extend it?

> tl;dr The whole point is about converting `RequestBody` content to `InputStream` 

Any advice appreciated. Thanks!

**Comment by JakeWharton** [comment]
Write it to a Buffer instance.

**Comment by akhyrul** [comment]
@JakeWharton thanks! I didn't realize Buffer is implementing Sink interface

**Comment by JakeWharton** [comment]
I meant to write more in a followup, but I'm on mobile and forgot. Glad you
got it sorted.
