### ISSUE TITLE
Cookie Manaager Problem

### ISSUE THREAD

**Issue by VieonyDaCosta** [square/okhttp#1814]
Hi,

I am developing 2 apps that use the same server and each of the App can set cookies on the server.
I am using okhttp to make request and have set cookies in a Singleton class as follows for both the Apps

 public static synchronized OkHttpClient GetInstance() {
    if (instance_ == null) {
      instance_ = new OkHttpClient();
      CookieManager cookieManager = new CookieManager();
      cookieManager.setCookiePolicy(CookiePolicy.ACCEPT_ALL);
      instance_.setCookieHandler(cookieManager);
    }
    return instance_;
  }

when both apps are installed on the same device the cookies interfere and are not set.

**Comment by swankjesse** [comment]
Nothing we can do here. Use two OkHttpClient instances or one, share your cookie store or don't; those are your application-layer's concerns.

If you can rephrase this question as a failing test, that'd be more actionable!
