### ISSUE TITLE
Invalid use of SingleClientConnManager

### ISSUE THREAD

**Issue by licongqi** [square/okhttp#1820]
I used volley with okHttp 2.4 in my project, and I got this warning:
SingleClientConnManager﹕ Invalid use of SingleClientConnManager: connection still allocated.
    Make sure to release the connection before allocating another one.
Should I disable connection pooling in okHttp to avoid this warning. If I should , how to disable it?
Thanks!

**Comment by swankjesse** [comment]
That error is not coming from OkHttp..

**Comment by licongqi** [comment]
I used volley with okHttp by using this OkHttpStack, https://gist.github.com/bryanstern/4e8f1cb5a8e14c202750
When I dropped this stack, there was no problem.
Dose it have something to do with OkHttp ?
Thanks again!

**Comment by licongqi** [comment]
And is there any way to disable connection pool? I just want to have a try, because this problem has troubled me for a long time.

**Comment by swankjesse** [comment]
You'll probably get better support asking on stackoverflow.

**Comment by licongqi** [comment]
Sorry , it's my problem, I finally find it! Thanks.
