### ISSUE TITLE
NPE in ConnectionSpec.tlsVersions()

### ISSUE THREAD

**Issue by juergenzimmermann** [square/okhttp#1831]
At line 110 in ConnectionSpec.tlsVersions() a NPE will occur, when
tlsVersions is null (e.g. for HTTP connections).
Therefore above the line
```
    TlsVersion[] result = new TlsVersion[tlsVersions.length];
```
these lines should be inserted
```
    if (tlsVersions == null || tlsVersions.length == 0) {
        return Collections.emptyList();
    }
```

**Comment by swankjesse** [comment]
We should probably throw an `IllegalStateException` in this case.

**Comment by swankjesse** [comment]
Or UnsupportedOperationException.
