### ISSUE TITLE
okhttp and soket io

### ISSUE THREAD

**Issue by jishuo1213** [square/okhttp#1832]
I use okhttp and webSoket (https://github.com/socketio/socket.io-client-java) in my app, I found a problem, when I compile okhttp.jar into my project , my websoket disconnect and reconnect repeatedly,then I remove okhttp.jar (delete the compile in gradle file),websoket works well ,I dont konw why will this happen  @swankjesse

**Comment by swankjesse** [comment]
Can you isolate this problem into a test case that fails? See `CallTest.java` for some examples.

**Comment by jishuo1213** [comment]
@swankjesse  thank you for replay me.My english is not very good.

I don't know how to show this use testcase,In my test project ,  I  hava a webSocket in my MainActivity
 <code> 
  private Socket mSocket;

    {
        try {
            mSocket = IO.socket(SERVER_ADDRESS);
        } catch (URISyntaxException e) {
            e.printStackTrace();
        }
    }
<code/>

and in onCreate(), I set some event listeners and connect to server

<code>

setContentView(R.layout.activity_main);

        mSocket.on(Socket.EVENT_CONNECT, new Emitter.Listener() {
            @Override
            public void call(Object... args) {
                Log.i(TAG, "connect to server");
            }
        });

        mSocket.on(Socket.EVENT_RECONNECT, new Emitter.Listener() {
            @Override
            public void call(Object... args) {
                Log.i(TAG,"reconnect to server");
            }
        });

        mSocket.on(Socket.EVENT_DISCONNECT, new Emitter.Listener() {
            @Override
            public void call(Object... args) {
                Log.i(TAG, "disconnected to server");
            }
        });
        mSocket.connect();
<code/>
In Logcat I see this logs:

09-02 13:57:36.898  com.inspur.fan.mytestapp I/MainActivity﹕ connect to server

09-02 13:57:41.984  com.inspur.fan.mytestapp I/MainActivity﹕ disconnected to server

09-02 13:57:43.578  com.inspur.fan.mytestapp I/MainActivity﹕ reconnect to server

09-02 13:57:58.140  com.inspur.fan.mytestapp I/MainActivity﹕ connect to server

09-02 13:58:18.617  com.inspur.fan.mytestapp I/MainActivity﹕ disconnected to server

09-02 13:58:27.945  com.inspur.fan.mytestapp I/MainActivity﹕ reconnect to server

09-02 13:58:28.132  com.inspur.fan.mytestapp I/MainActivity﹕ connect to server

09-02 13:58:38.218  com.inspur.fan.mytestapp I/MainActivity﹕ disconnected to server

09-02 13:58:59.484  com.inspur.fan.mytestapp I/MainActivity﹕ reconnect to server

In my build.gradle 
<code>

compile 'io.socket:socket.io-client:0.6.1'
compile 'com.squareup.okhttp:okhttp:2.5.0'
<code/>

then I remove okhttp compile,WebSocket will connect once and wont disconnect,in my test project i did not called any okhttp class or method.that's all

**Comment by jishuo1213** [comment]
Additional， I use Samsung SM-3818 to test

**Comment by swankjesse** [comment]
Until you can give us a test case, you're better off seeking support on stackoverflow. Right now I consider this to be non-actionable!

If you do isolate, don't hesitate to reopen this issue.
