### ISSUE TITLE
HttpURLConnection: Behavior change around non-LDH ASCII characters in host names

### ISSUE THREAD

**Issue by nfuller** [square/okhttp#1833]
Creating to have a discussion. If I create a URL containing ASCII codes besides letters, digits and hyphens in the authority/host I get a failure. e.g.

    String host = "host\u0001";
    HttpUrl expected = HttpUrl.parse("http://" + host + "/");
    assertEquals(host, expected.host());

The ASCII code 0x01 in the host is not transformed (underneath, because IDN.toAscii(host) is used). 

After the switch to HttpUrl internally, this can leads to problems with the host header with HttpURLConnectionImpl. The host header checking is currently more strict than the host parsing.

In HttpEngine this code fails with an IllegalArgumentException here:

    if (request.header("Host") == null) {
      result.header("Host", Util.hostHeader(request.httpUrl()));
    }

Previous behavior was to encode the host: e.g. "host\u0001" -> "host%01"

Ideally from a "least likely to break apps" PoV we would keep the old behavior.
The new behavior seems likely to have an impact because it involves throwing a runtime exception.
I could see us throwing an UnknownHostException instead but I'd need to check the implications. (For automatic following of redirects I can see us refusing to follow the redirect if the Location is found to be incorrect).

https://url.spec.whatwg.org/#host-parsing suggests the OkHttp implementation is correct, but https://url.spec.whatwg.org/#host-syntax suggests codes like 0x01 are not valid.

The whatwg spec also suggests that an encoded value (like %01) would break the host-parsing rules, but probably not the host-syntax.

Any suggestions?

**Comment by swankjesse** [comment]
Right now we have this inside `canonicalizeHost`:

      // Confirm that the decoded result doesn't contain any illegal characters.
      int length = idnDecoded.length();
      if (delimiterOffset(idnDecoded, 0, length, "\u0000\t\n\r #%/:?@[\\]") != length) {
        return null;
      }

I see no harm in strengthening this to forbid all control characters and 0x7f. Would that solve the problem?

**Comment by nfuller** [comment]
I started down that road yesterday but backed off when I saw the list of existing chars came from the WHATWG spec.
I shall resurrect the change and see if there are any problems. I think it will result in the UnknownHostException / not following redirect behavior mentioned above, which constitutes a behavior change but not one that I can (currently) see causing too many problems.

**Comment by swankjesse** [comment]
Yeah, I think it's better behavior.

**Comment by swankjesse** [comment]
@nfuller any further action worth taking here?

**Comment by nfuller** [comment]
No, AFAIK it's fixed.
