### ISSUE TITLE
Websocket creates threads with url as name, which captures tokens in urls in crashlytics

### ISSUE THREAD

**Issue by osama-lionheart** [square/okhttp#1838]
We use okhttp-ws to communicate with our server, and as an optimization step, we pass an `oauth2` token in the websocket url to the server (to avoid making an extra auth request every time we connect), and since we use crashlytics as a reporting tool for our exceptions, we noticed that oauth2 tokens are captured in the url as the name of thread that the websocket creates.

**Comment by swankjesse** [comment]
Yup, we should partially redact the URL before using it to name a thread. We already have some code like this in `Call`. If you'd like to send a pull request, please do!

**Comment by JakeWharton** [comment]
Unless I'm missing something, it looks like `Call` does no redaction of the URL. It just calls `toString()` on the `HttpUrl` from the original request.

**Comment by iNoles** [comment]
Looks like Jake is right. https://github.com/square/okhttp/blob/master/okhttp-ws/src/main/java/okhttp3/ws/WebSocketCall.java#L160

**Comment by JakeWharton** [comment]
I was referring to the non-websocket `Call`: https://github.com/square/okhttp/blob/9920c57e7a8c0d49ec2732be899b3e27c215854a/okhttp/src/main/java/okhttp3/RealCall.java#L99

**Comment by boxme** [comment]
I made a simple pull request to add a method to redact the url in Http, which is then used in WebSocketCall to hide the captured tokens

**Comment by JakeWharton** [comment]
Fixed by https://github.com/square/okhttp/pull/2751
