### ISSUE TITLE
how to post json array into service

### ISSUE THREAD

**Issue by ihnuzarx** [square/okhttp#1839]
i want to post parameter likes this
Params:
{
  "email": "",  Email from facebook
  "fbuid": "",  Facebook Id
  "other": {
    "name": "", Facebook name
  },
  "password": "" (Optional this field required when duplicated email)
}
but my issue is "other" variable

**Comment by swankjesse** [comment]
Please try your question on Stackoverflow. This tracker is for bug reports & feature requests only.
