### ISSUE TITLE
Websocket closes afrer 15 minutes

### ISSUE THREAD

**Issue by Ne1c** [square/okhttp#1840]
Websocket closes afrer 15 minutes with code 1000. How to prevent disconnection? And close the websocket  by hand?

**Comment by JakeWharton** [comment]
This sounds like whatever server you are talking to is initiating the close. Without more information there's not much we can do here. It likely closes the connection on inactivity. You can send a ping on the websocket every few minutes to tell it that you are still alive, but it really depends on the server.

Unless you can provide more specific information where OkHttp is at fault here, I don't think there's anything for us to do.
