### ISSUE TITLE
http header values with quoted strings are not validated properly with okhttp 2.5.0

### ISSUE THREAD

**Issue by mwolfe38** [square/okhttp#1841]
According to RFC 2616 section 2.2

http://tools.ietf.org/html/rfc2616#section-2.2

>  Many HTTP/1.1 header field values consist of words separated by LWS
>  or special characters. These special characters MUST be in a quoted
>   string to be used within a parameter value (as defined in section
>   3.6).
>
>       token          = 1*<any CHAR except CTLs or separators>
>       separators     = "(" | ")" | "<" | ">" | "@"
>                      | "," | ";" | ":" | "\" | <">
>                      | "/" | "[" | "]" | "?" | "="
>                      | "{" | "}" | SP | HT

However, with okhttp, even if the header value is surrounded with quotes, the request builder's addHeader method throws IllegalArgumentException.

**Comment by swankjesse** [comment]
Can you provide a test case to demonstrate the problem?

**Comment by mwolfe38** [comment]
Sorry, I was wrong, it was the newline that caused the issue, not the = sign. However this may be an issue but the solution for me was to remove the newline.

**Comment by swankjesse** [comment]
No problem. I typically won't discover problems like that til I try to make a test case!
