### ISSUE TITLE
Threading issue on InputStream close?

### ISSUE THREAD

**Issue by nfuller** [square/okhttp#1842]
I received a report of this against an M build. The code is not _that_ far off of OkHttp head. Please let me know if anything has changed in this area.

```
06-24 12:50:54.425 10001 16298 E AndroidRuntime: java.lang.IllegalStateException: Unbalanced enter/exit
06-24 12:50:54.425 10001 16298 E AndroidRuntime:        at com.android.okhttp.okio.AsyncTimeout.enter(AsyncTimeout.java:62)
06-24 12:50:54.425 10001 16298 E AndroidRuntime:        at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:209)
06-24 12:50:54.425 10001 16298 E AndroidRuntime:        at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:306)
06-24 12:50:54.425 10001 16298 E AndroidRuntime:        at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:300)
06-24 12:50:54.425 10001 16298 E AndroidRuntime:        at com.android.okhttp.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:196)
06-24 12:50:54.425 10001 16298 E AndroidRuntime:        at com.android.okhttp.internal.http.HttpConnection$ChunkedSource.readChunkSize(HttpConnection.java:476)
06-24 12:50:54.425 10001 16298 E AndroidRuntime:        at com.android.okhttp.internal.http.HttpConnection$ChunkedSource.read(HttpConnection.java:460)
06-24 12:50:54.425 10001 16298 E AndroidRuntime:        at com.android.okhttp.internal.Util.skipAll(Util.java:176)
06-24 12:50:54.425 10001 16298 E AndroidRuntime:        at com.android.okhttp.internal.Util.discard(Util.java:158)
06-24 12:50:54.425 10001 16298 E AndroidRuntime:        at com.android.okhttp.internal.http.HttpConnection$ChunkedSource.close(HttpConnection.java:499)
06-24 12:50:54.425 10001 16298 E AndroidRuntime:        at com.android.okhttp.okio.RealBufferedSource.close(RealBufferedSource.java:374)
06-24 12:50:54.425 10001 16298 E AndroidRuntime:        at com.android.okhttp.okio.RealBufferedSource$1.close(RealBufferedSource.java:362)
06-24 12:50:54.425 10001 16298 E AndroidRuntime:        at java.io.FilterInputStream.close(FilterInputStream.java:64)
06-24 12:50:54.425 10001 16298 E AndroidRuntime:        at java.util.zip.InflaterInputStream.close(InflaterInputStream.java:252)
06-24 12:50:54.425 10001 16298 E AndroidRuntime:        at java.util.zip.GZIPInputStream.close(GZIPInputStream.java:125)
06-24 12:50:54.425 10001 16298 E AndroidRuntime:        at okio.Okio$2.close(SourceFile:145)
06-24 12:50:54.425 10001 16298 E AndroidRuntime:        at okio.RealBufferedSource.close(SourceFile:363)
<snip app stack>
```
The way I can think can occur is if another thread is blocked or otherwise inside of AsyncTimeout. Perhaps performing a blocking read. So, it could be another example of the "close from one thread while reading with another" that has been seen with HttpURLConnection before. In this case it is the InputStream. It may not be HttpURLConnection specific: difficult for me to tell.

Note: in this stack trace we have two copies of Okio involved: the one embedded in Android, some layers of GZIPInputStream, and then another app-provided one that wraps the GZIPInputStream. 

The connectivity was apparently "patchy" when this occurred. I do not have a repeatable test case.

**Comment by swankjesse** [comment]
OkHttp sources and sinks are not threadsafe. App code should call `HttpURLConnection.disconnect()` or `Call.cancel()` to interrupt another thread’s ongoing call. Looks like what’s happening here is one thread is calling `close()` on a stream that another thread is using.

Reasonable policy?

**Comment by nfuller** [comment]
The policy seems reasonable to me. From the previous threading issues with disconnect() that caused problems and were fixed I didn't know whether this would be something you'd want to keep working (if it ever did).

I don't think it's particularly reasonable for developers to interact with a stream from multiple threads. 

[To a lesser extent I think the same about HttpURLConnection and disconnect() but I understand the blocking nature of the APIs encourage that and it has become common practice.]

I'll see if I can contact the developers involved and confirm what they are doing.

**Comment by nfuller** [comment]
No further action required.

**Comment by zanxiaofei** [comment]
4.x 不会出现这种情况了，建议您使用推流的4.x版本
