### ISSUE TITLE
OkHttp interprets the http.maxConnections system property differently than Android HttpURLConnection

### ISSUE THREAD

**Issue by xcolwell** [square/okhttp#1843]
Android HttpURLConnection interprets `System.getProperty("http.maxConnections")` as how many idle connections *to each server* will be held [1; Performance Section]. OkHttp interprets the property as how many idle connections across all hosts will be held [2].

HURL's interpretation is easier to interpret and tune in an environment with requests to many hosts. 

1. http://developer.android.com/reference/java/net/HttpURLConnection.html
2. `com.squareup.okhttp.ConnectionPool#performCleanup`

**Comment by swankjesse** [comment]
I think this is a bug in Android’s docs. Both have OkHttp’s behavior.

FYI @nfuller.

**Comment by nfuller** [comment]
For reference, this is broken on Android's default HttpURLConnection: developers don't get to change the values because the class is loaded during device boot.

https://code.google.com/p/android-developer-preview/issues/detail?id=2578

I think it has been broken for a long time so I've been in no rush to deal with it but the docs should definitely be updated.

While on the subject, I was pondering whether we can do something about this to make it functional for Android's default, but the ability to modify the default keep-alive HttpURLConnection behavior would be quite brutal. If somebody wants to have this level of control they should probably embed their own HTTP stack in their app and tweak it on a per server basis. Individual connections can turn off keep alive if it causes problems.

@xcolwell Happy to discuss (probably best on the Android bug) if you have thoughts.

**Comment by xcolwell** [comment]
@nfuller some feedback below.

Would be great to have the Android docs updated, since connection pooling is a key piece of most app performance. I'd be very interested in per-host or even per-request configuration of max connections and timeouts. Aside, it's interesting that OkHttp doesn't set an explicit limit on total concurrent connections, just concurrent connections per host. This is different than Volley which limits total concurrent connections.  

>> because the class is loaded during device boot

I thought each app loads classes into its own process/memory space. I'd appreciate any references here about the loading behavior.

My understanding of the bug is that the class is loaded as part of app initialization, from a dependency in the framework.

>>  embed their own HTTP stack in their app 

The network stack could be shared if it was easier to plug in config per-request. Actually, the HTTP 'Connection` and `Keep-Alive` headers require that each connection gives the latest response the final say in the keep-alive and timeout. Ideally the network would support multiple levels of config, from lowest priority to highest:
- default target
- target applied with app logic (per-request, or per-host)
- response

**Comment by nfuller** [comment]
> I thought each app loads classes into its own process/memory space. I'd appreciate any references 
> here about the loading behavior.

Each app process does get its own process/name space, but it doesn't start out as a blank slate. This is to do with Android's zygote process which is the progenitor of Android's app processes. OTTOMH I don't know of a good reference but there are plenty of people that have written about it if you search for "Android zygote". One of its functions is to initialize the common classes that most apps will use.

https://android.googlesource.com/platform/frameworks/base/+/master/preloaded-classes
(see com.android.okhttp)

> Aside, it's interesting that OkHttp doesn't set an explicit limit on total concurrent connections, just 
> concurrent connections per host. This is different than Volley which limits total concurrent connections.

plus

> The network stack could be shared if it was easier to plug in config per-request. 

On Android's HttpURLConnection we have to work with the API we have. 3rd party stacks like OkHttp get to define their own functionality, expose new behavior (e.g. HTTP/2) and can evolve (and break things if needed) much more quickly.

Pooling configuration / logic outside of what the HttpURLConnection provides is probably best made as a feature request for OkHttp's APIs.

Generally, I suggest that people developing apps who rely on a lot of HTTP comms or more complex usecases embed their own stack. Android's releases have a wide variety of behaviors and bugs on the edges. By using an app-provided stack your exposure to the platform version (and thus behavior) is reduced.

**Comment by xcolwell** [comment]
This is great.

**Comment by swankjesse** [comment]
I don't think there's any action to take here within OkHttp. If I'm wrong, let me know.
