### ISSUE TITLE
Setting a request body doesn't set/update the Content-Length header

### ISSUE THREAD

**Issue by lukaciko** [square/okhttp#1857]
When using `Request.Builder.post()` or any other method with `RequestBody` parameter the `Content-Length` header does not get set. This can be troublesome e.g. when changing the request body using interceptors:

```java
OkHttpClient client = new OkHttpClient();
client.networkInterceptors().add(chain -> {
  Request originalRequest = chain.request();
  Request.Builder builder = originalRequest.newBuilder();

  if (originalRequest.method().equals("POST") && originalRequest.body() != null) {
    byte[] newContent = new byte[4];
    builder.post(RequestBody.create(originalRequest.body().contentType(), newContent));
    // The header has to be set manually!
    builder.header("Content-Length", String.valueOf(newContent.length));
  }
  return chain.proceed(builder.build());
});
```

If the original request already had `Content-Length` set that is not same as the content length of the new request unexpected things will start happening, such as old payloads being written into the new request buffer or server waiting for more data. This can be especially confusing because `RequestBody` has a method called `contentLength()`.

**Comment by swankjesse** [comment]
If you want to transform the request body like this, you're probably better off using an _application_ interceptor. The content-length header doesn't get locked in until after all application interceptors have run.
https://github.com/square/okhttp/wiki/Interceptors
