### ISSUE TITLE
addHeader()

### ISSUE THREAD

**Issue by hdtuan87** [square/okhttp#1866]
I have problems with Request.Builder.addHeader in version 2.5

Unexpected char 0x0a at 66 in header value: 
Basic Qlk1RmVUdzZhTldFOlllZ2RkMlpkUE50cDdNZjdKMVppanZpajd1Um1pUQ==

I downgraded to 2.4 it worked.

**Comment by swankjesse** [comment]
Call `trim()` on your value, it ends with `\ `.
