### ISSUE TITLE
Okhttp, a problem on VIVO Y17T device.

### ISSUE THREAD

**Issue by xueqing325** [square/okhttp#1867]
There is a must have occurred problem on the device. 
important log:

 java.io.IOException: unexpected end of stream on Connection{api.laifeng.com:80, proxy=DIRECT@ hostAddress=106.38.221.245 cipherSuite=none protocol=http/1.1} (recycle count=0)
Caused by: java.io.EOFException: \n not found: size=416.

**Comment by swankjesse** [comment]
That's an I/O problem. Nothing we can do!
