### ISSUE TITLE
4xx & 5xx throw exceptions

### ISSUE THREAD

**Issue by sdhull** [square/okhttp#187]
I don't think I'm the only one connecting to APIs that return non-2xx status codes.

It's frustrating to handle error cases as exception cases for two reasons:
1. These aren't truly "exceptional" (a la PragProg) -- sometimes you request a resource that's not there, or you try to submit params that aren't quite right.  This should be handled in regular application flow, not exception handlers.
2. This makes it impossible to grab the `InputStream` which might contain some useful data about what went wrong (eg, error messages).

Is there some way to turn off this behavior?

**Comment by wsf5918** [comment]
yeap,i had meet this problems ,any did you had solve this problem? can you should me how to solve this problems? thanks

**Comment by wsf5918** [comment]
@sdhull yeap,i had meet this problems ,any did you had solve this problem? can you should me how to solve this problems? thanks

**Comment by wsf5918** [comment]
@JakeWharton 
I don't think I'm the only one connecting to APIs that return non-2xx status codes.

It's frustrating to handle error cases as exception cases for two reasons:

These aren't truly "exceptional" (a la PragProg) -- sometimes you request a resource that's not there, or you try to submit params that aren't quite right. This should be handled in regular application flow, not exception handlers.
This makes it impossible to grab the InputStream which might contain some useful data about what went wrong (eg, error messages).
Is there some way to turn off this behavior?

,i had meet this problems ,any did you had solve this problem? can you should me how to solve this problems? thanks,i had meet this problems ,any did you had solve this problem? can you should me how to solve this problems? thanks

https://github.com/square/okhttp/issues/2952

**Comment by JakeWharton** [comment]
Stop using HttpURLConnection then. This issue is ancient, we have a superior API now.

**Comment by wsf5918** [comment]
@JakeWharton  this is the issues for the testing log
https://github.com/square/okhttp/issues/2952
