### ISSUE TITLE
HttpUrl.uri() not encoding enough to create valid URI instances.

### ISSUE THREAD

**Issue by JakeWharton** [square/okhttp#1872]
```java
HttpUrl url = new Builder() //
    .scheme("http")
    .host("example.com")
    .addPathSegment("data=[out:json];node[\"name\"~\"Karlsruhe\"][\"place\"~\"city|village|town\"];out body;")
    .build();
System.out.println(url);
System.out.println(url.uri());
```
```
http://example.com/data=[out:json];node[%22name%22~%22Karlsruhe%22][%22place%22~%22city%7Cvillage%7Ctown%22];out%20body;
Exception in thread "main" java.lang.IllegalStateException: not valid as a java.net.URI: http://example.com/data=[out:json];node[%22name%22~%22Karlsruhe%22][%22place%22~%22city%7Cvillage%7Ctown%22];out%20body;
```

**Comment by JakeWharton** [comment]
I tried looking into this but gave up. At the very least, adding `[]` to the encode set for URI fixed the issue, but I'm not sure that it's the correct approach to re-encode the entire URL using a global encode set as URI has different encoding sets that it's verifying against for the different parts of the URL. Plus I'm worried (but did not confirm) that this wouldn't play well with IPv6.

We might need a more sophisticated strategy of encoding piecewise before handing to URI either through its `create` method or perhaps one of its constructors.

**Comment by markrietveld** [comment]
This is similar to https://github.com/square/okhttp/issues/1836. According to [this](https://github.com/square/okhttp/issues/1061), doing cookies in OkHttp removes the last dependent on `java.net.URI`, which would avoid this issue

**Comment by iagreen** [comment]
There is a test case matching your case above that is expecting failure on '[' in paths (https://github.com/square/okhttp/blob/master/okhttp-tests/src/test/java/com/squareup/okhttp/HttpUrlTest.java#L933).  The other PR was directed at queries, not paths, but it does seem sketchy to do a global re-encode.  [URI's multi-parameter](http://docs.oracle.com/javase/7/docs/api/java/net/URI.html#URI%28java.lang.String,%20java.lang.String,%20java.lang.String,%20int,%20java.lang.String,%20java.lang.String,%20java.lang.String%29) constructor does piecewise encoding.

**Comment by whyte624** [comment]
When PR will be accepted and released? Thanks!
