### ISSUE TITLE
Issues with SPDY and CloudFlare

### ISSUE THREAD

**Issue by shortstuffsushi** [square/okhttp#1882]
Hi guys, sorry of this is a dupe, having a hard time finding an exact match with all the existing issues.

Similar to [this SO post](http://stackoverflow.com/questions/24190507/what-causes-java-io-ioexception-stream-was-reset-cancel-with-okhttp-and-spdy), I am seeing intermittent request failures (IOException: Canceled) when making requests to a server which has Cloudflare in front of it.

It's not really reproducible reliably, and it doesn't seem to happen when I breakpoint around the failures. Forcing a downgrade to 1.1 works fine, but is obviously not preferable. Any suggestions? I'm using the latest version, I believe -- 2.5.0.

**Comment by swankjesse** [comment]
We've heard a separate issues that our connection pool is interfering with SPDY.  I'll try to dig into this & get out a fix.

**Comment by swankjesse** [comment]
@shortstuffsushi got a URL that triggers this? Feel free to respond to me privately, jesse at swank.ca, if you don't want to post it in the shared tracker.

**Comment by swankjesse** [comment]
My guess is that the call to `closeQuietly(connection.getSocket());` in `HttpEngine.close()` is causing the grief here. Will fix.

**Comment by shortstuffsushi** [comment]
Sent separately; were you able to replicate? I don't know enough about the code base to begin to guess, but I'll definitely test out any patch you put out.

**Comment by swankjesse** [comment]
Appears to be fixed in nginx. See also https://publicobject.com/2015/10/19/okhttp-http2-nginx-1-9-5/

**Comment by shortstuffsushi** [comment]
Interesting, I've been downgrading in the mean time anyway, but will definitely pull that patch into my server when possible. Thanks for looking into this.
