### ISSUE TITLE
ISO-8859-1 charset for response headers

### ISSUE THREAD

**Issue by likebobby** [square/okhttp#1886]
I'm moving away from Apache Http Client (removed in Android SDK 23) to using OkHttp. However I'm getting a problem for a custom response header field which is using special characters (åäö) encoded with `ISO-8859-1`. OkHttp reads them as `UTF-8` in the HttpConnection [here](https://github.com/square/okhttp/blob/832038bdc25e38c7e9cfebff1bc81488fd819056/okhttp/src/main/java/com/squareup/okhttp/internal/http/HttpConnection.java#L220).

I would like to at least configure the charset used when reading response headers. Also as I understand the [spec](http://tools.ietf.org/html/rfc7230#section-3.2.4) says:

> Historically, HTTP has allowed field content with text in the
   ISO-8859-1 charset [ISO-8859-1], supporting other charsets only
   through use of [RFC2047] encoding.  In practice, most HTTP header
   field values use only a subset of the US-ASCII charset [USASCII].
   Newly defined header fields SHOULD limit their field values to
   US-ASCII octets.  A recipient SHOULD treat other octets in field
   content (obs-text) as opaque data.

So why UTF-8 as default an not US-ASCII?

Is the response header field charset configurable or how can it be?

**Comment by swankjesse** [comment]
We use UTF-8 because it's a superset of ASCII, but it's expected to encounter ASCII-only. I don't want to make this configurable, particularly because you have no good mechanism to configure it. Can you ask your server admins to limit themselves to ASCII?

**Comment by likebobby** [comment]
I understand your opinion, too bad there is no good mechanism to configure it. I'll have to make my server admins change their solution in the long term then (IMHO an old bad decision that should be changed anyway). Meanwhile I have to use another solution. Thank you for the quick reply.
