### ISSUE TITLE
WebSocketEcho sample

### ISSUE THREAD

**Issue by nyxee** [square/okhttp#1889]
changing lines 18 and 19 to 
`import static com.squareup.okhttp.ws.WebSocket.PayloadType.BINARY;
import static com.squareup.okhttp.ws.WebSocket.PayloadType.TEXT;`

removed the error mesages on those lines but introduces others on the lines  40, 41 AND 42:
` webSocket.sendMessage(RequestBody.create(TEXT, "Hello..."));
  webSocket.sendMessage(RequestBody.create(TEXT, "...World!"));
 webSocket.sendMessage(RequestBody.create(BINARY, ByteString.decodeHex("deadbeef")));`

**Comment by JakeWharton** [comment]
The code on master does not correspond with the latest released version. If you want the example for the 2.5.0 version you should browse the source code using its release tag: https://github.com/square/okhttp/blob/parent-2.5.0/samples/guide/src/main/java/com/squareup/okhttp/recipes/WebSocketEcho.java
