### ISSUE TITLE
RequestBody.string()

### ISSUE THREAD

**Issue by BugsBunnyBR** [square/okhttp#1891]
Hi, would be possible to have a method RequestBody.string() like in the ResponseBody.string() ?
It would help with the logging of the request being sent.

**Comment by swankjesse** [comment]
You can write your own method to do that like this:

```
  public static String requestBodyToString(RequestBody requestBody) throws IOException {
    Buffer buffer = new Buffer();
    requestBody.writeTo(buffer);
    return buffer.readUtf8();
  }
```

I'm reluctant to include it as it may cause substantial performance problems for some request bodies.

**Comment by swankjesse** [comment]
We’re going to get this for free in OkHttp 4 when we unify the request and response body types.

**Comment by jinal90** [comment]
unable to find string method in RequestBody class.
Using below version of okhttp
implementation 'com.squareup.okhttp3:okhttp:3.10.0'

**Comment by yschimke** [comment]
@jinal90 it doesn't exist in OkHttp 3, use the sample code that Jesse provided above for now.

**Comment by jinal90** [comment]
I tried with the sample code provided by Jesse. Its not working, I am getting null buffer object.

//This is the RequestBody object

RequestBody mRequestBody = new MultipartBody.Builder()
                            .setType(MultipartBody.FORM)
                            .addFormDataPart("name", "content")
                            .addFormDataPart("filename", "sample.pdf",
                                    RequestBody.create(MediaType.parse("*/*"), new File(filePath)))
                            .build();

//This is the requestBodyToString method
//here I get buffer object as null

public String requestBodyToString(RequestBody requestBody) {
       try{
           Buffer buffer = new Buffer();
           requestBody.writeTo(buffer);
           return buffer.readUtf8();
       }catch(Exception e){
           e.printStackTrace();
           return "";
       }
   }

**Comment by yschimke** [comment]
You should ask usage questions like this on stackoverflow.  If you can reproduce a bug then raise an issue here.  But comments on existing closed issues are a very noisy place to debug through usage problems like this.

**Comment by surapuramakhil** [comment]
> You can write your own method to do that like this:
> 
> ```
>   public static String requestBodyToString(RequestBody requestBody) throws IOException {
>     Buffer buffer = new Buffer();
>     requestBody.writeTo(buffer);
>     return buffer.readUtf8();
>   }
> ```
> 
> I'm reluctant to include it as it may cause substantial performance problems for some request bodies.

Buffer class is an Abstract class in Java.nio Package

**Comment by swankjesse** [comment]
Buffer is also a concrete class in the okio package.

**Comment by marufmax** [comment]
Buffer is an abstract class in plain Java. To make this work you need to install Okio library in your grade file

**build.gradle**
`implementation group: 'com.squareup.okio', name: 'okio', version: '3.1.+'` 

Ref: https://github.com/square/okio
