### ISSUE TITLE
Is HTTP/1.1 Request Pipelining supported

### ISSUE THREAD

**Issue by passsy** [square/okhttp#1893]
I have to communicate with very limited hardware which supports only a few concurrent connections. I can work around this limitation with http pipelining which will be fully supported.

There is only one problem: 
**OkHttp doesn't seem to support http pipelining.** Will this be supported in the future?

**Comment by swankjesse** [comment]
No, we aren't planning on supporting HTTP pipelining. It’s not robust.

**Comment by inder123** [comment]
@swankjesse what do you mean HTTP pipelining is not robust? Pipelining should help in poor bandwidth connections in many countries. How would I go about enabling it in OkHttp?

**Comment by inder123** [comment]
https://github.com/jasondevj/hotpotato seems to support pipelining and is under Apache license. May be we can borrow something from there?

**Comment by swankjesse** [comment]
They disabled it from Chrome because it performed poorly.
https://www.chromium.org/developers/design-documents/network-stack/http-pipelining

The workaround is HTTP/2.
