### ISSUE TITLE
Http2 is not always negotiated for Android 5.+ phones connecting to H2/SPDY enabled server

### ISSUE THREAD

**Issue by zhihuawensc** [square/okhttp#1895]
Our server supports both H2 and SPDY, but based on the com.squareup.okhttp.Response.protocol fields, on 20% to 30% of the requests from our test lollipop phones to our servers are using H2, the rest are still using Http/1.1.

Is this a bug or okhttp choose the protocol between h2 and http/1.1 based on some heuristics? Thanks for your clarification.

**Comment by swankjesse** [comment]
Does the device mix give any hints? Do any devices connect with both versions or is it partitioned by device?

**Comment by zhihuawensc** [comment]
It seems any lollipop devices connect with both versions, although of percentage of H2 requests is slightly higher on some devices, e.g., the h2 percentage of Nexus 5 is higher than Galaxy S6.

**Comment by zhihuawensc** [comment]
I used wireshark to check the client hello message sent out from my test phone, and I found the protocols used in ALPN is not always same, sometimes the client broadcast all 3 protocols while sometimes it broadcast only http/1.1. I am using OKHTTP 2.4 right now, is this an known issue and fixed in 2.5?

Client Hello:
ALPN Protocol
  ALPN Next Protocol: http/1.1

Client Hello:
ALPN Protocol
  ALPN Next Protocol: h2
  ALPN Next Protocol: spdy/3.1
  ALPN Next Protocol: http/1.1

**Comment by ppasierbski** [comment]
It happens for you always on the same server? My problem is I'm getting a h2 connection with some test sites and not getting h2 with nginx with h2 enabled. (Nexus 4 with Android 5.1.1)

**Comment by robertoestivill** [comment]
Sounds like this might be related

http://stackoverflow.com/questions/33266886/networkonmainthread-rxjava-retrofit-lollipop

**Comment by swankjesse** [comment]
@zhihuawensc can you reproduce this reliably? I have no idea where the set of protocols would be changed. The only place that happens now is with the `OkHttpClient.setProtocols` API. If you can reproduce this (executable test cases are the best) then we can fix it. Otherwise I don't know what I can do.

**Comment by zhihuawensc** [comment]
Hi, Sorry. Actually I found this is due to some configure error in our
code, please remove this issue then.

On Fri, Oct 30, 2015 at 5:41 PM, Jesse Wilson <notifications@github.com>
wrote:

> @zhihuawensc <https://github.com/zhihuawensc> can you reproduce this
> reliably? I have no idea where the set of protocols would be changed. The
> only place that happens now is with the OkHttpClient.setProtocols API. If
> you can reproduce this (executable test cases are the best) then we can fix
> it. Otherwise I don't know what I can do.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/square/okhttp/issues/1895#issuecomment-152680458>.
>



-- 
Zhihua Wen

**Comment by farmazon3000** [comment]
I had exactly the same problem. It seems to be the server I'm using fault, in my case imgur, see https://stackoverflow.com/questions/61111537/imgur-server-randomly-chooses-h2-over-http-1-1-and-then-it-fails.
