### ISSUE TITLE
Per-request timeout settings (feature request)

### ISSUE THREAD

**Issue by konmik** [square/okhttp#1899]
In example, in some APIs there is a need to sometimes make long lasting requests (like in chats). It is not reasonable to create a new OkHTTP instance and share cookies and stuff just to set a per-request timeouts. Apache HTTP had this possibility, I think OkHTTP can also have it.

**Comment by swankjesse** [comment]
https://github.com/square/okhttp/wiki/Recipes#per-call-configuration
