### ISSUE TITLE
HttpUrl.Builder.fragment() should accept null

### ISSUE THREAD

**Issue by srwilson** [square/okhttp#1905]
The query() method accepts null gracefully but the fragment() method does not and throws an IllegalArgumentException.   Seems like both should be treated the same.  The same should apply to encodedFragment() as well.

It makes something like this hard to do:

```java
HttpUrl url = HttpUrl.parse(urlStr);
String fragment = url.fragment();
fragment = cleanup(fragment)
return url.newBuilder()
                .fragment(fragment)
                .toString();
```
 
More than willing to make the PR if necessary.

**Comment by swankjesse** [comment]
Yep, that's a bug. Fix here: https://github.com/square/okhttp/pull/1956

**Comment by JakeWharton** [comment]
Fix was merged.
