### ISSUE TITLE
HttpUrl.resolve() strips out path segments

### ISSUE THREAD

**Issue by michaeltnguyen** [square/okhttp#1911]
```java
HttpUrl.parse("http://mywebsite.com/segment1/segment2").resolve("/endpoint")
```

I would expect the result to be "http://mywebsite.com/segment1/segment2/endpoint", but what I get is "http://mywebsite.com/endpoint".  Is this intended?

**Comment by JakeWharton** [comment]
Yes. A leading slash indicates an absolute path on the host. It works the same way as an `<a href="">` link would.

**Comment by michaeltnguyen** [comment]
Thanks.  Makes sense.
