### ISSUE TITLE
HttpUrl equals() doesn't decode URL paths

### ISSUE THREAD

**Issue by rfc2822** [square/okhttp#1916]
This simple test fails for me:

```
assertEquals(
                HttpUrl.parse("http://example.com/my@dav/"),
                HttpUrl.parse("http://example.com/my%40dav/")
);
```

Is this behaviour by design (i.e. `equals` must not be used to compare URLs) or is there something wrong

* in the `parse` method (according to its Javadoc, `canonicalize` encodes characters in `encodeSet`, but doesn't decode already encoded characters in `encodeSet`), or
* in the `equals` method
* or somewhere else?

**Comment by swankjesse** [comment]
The two URLs you've provided are not equal. To confirm, try this in your browser’s JavaScript console.
```
new URL("http://example.com/my%40dav/").href
new URL("http://example.com/my@dav/").href
```

**Comment by swankjesse** [comment]
Also fun, run `nc -l 9999` and then `curl 'http://localhost:9999/my%40dav/'`.

**Comment by rfc2822** [comment]
I only have a mobile browser at the moment... Is there a reason why these URLs are not equal? At least, some WebDAV servers send a reply for `/my%40dav/` when queried for info about `/my@dav/`.

**Comment by swankjesse** [comment]
Presumably those WebDAV servers consider the two URLs to be equal. But other servers may serve different content on the encoded and non-encoded form. Similarly, some servers may choose to discard case, treating `index.html` and `INDEX.HTML` as the same resource. Because OkHttp doesn't know the server’s policy, it’s conservative and retains the difference.

**Comment by rfc2822** [comment]
I'll have to look into that... Can you give me a hint why

>other servers may serve different content on the encoded and non-encoded form.

? I've assumed that it's the content of the URL that identifiers it, regardless of which bytes are encoded (for ASCII characters).

**Comment by swankjesse** [comment]
I'm not exactly sure the reason. I'd love to hear it!

It's the encoded form that's canonical. Servers may even serve different resources under `%4A` vs. `%4a`, and so HTTP clients preserve even that.

**Comment by rfc2822** [comment]
Thanks for your patience. As I'm still convinced that there is a problem in the result `equals()`, I will try to explain my views and back them with RFC references.

I'm not "arguing just to argue", but this is a real problem in WebDAV context. Because I love okhttp and value your work, I hope that I can improve it. Of course, if I'm wrong, so be it then, but I think that my arguments are not that bad (and they match with my experience how HTTP servers and clients behave).

I will start with RFC-based arguments, and then reply your other pragmatic arguments.

**RFC-based arguments**

[RFC 1738 (URL) 2.2 URL Character Encoding Issues](https://tools.ietf.org/html/rfc1738#section-2.2) says:

> URLs are sequences of characters, i.e., letters, digits, and special characters. A URLs may be represented in a variety of ways: e.g., ink on paper, or a sequence of octets in a coded character set. _The interpretation of a URL depends only on the identity of the characters used._

As far as I understand this, it means that it doesn't matter whether you write the letter "@" on paper, or use the an octet of a certain character set to represent it. Now let's read the next two paragraphs:

> In most URL schemes, the sequences of characters in different parts of a URL are used to represent sequences of octets used in Internet protocols. […] Within those parts, an octet may be represented by the chararacter (sic!) which has that octet as its code within the US-ASCII [20] coded character set.

In my opinion, this means that the "@" character written on paper may also be represented by the octet with value 0x40 because the "@" character is in the US-ASCII character set and its ASCII code is 0x40. (Usage of this representation may be subject to further limiting rules, for instance in the authority part of HTTP URLs).

> In addition, octets may be encoded by a character triplet consisting of the character "%" followed by the two hexadecimal digits (from "0123456789ABCDEF") which forming the hexadecimal value of the octet. (The characters "abcdef" may also be used in hexadecimal encodings.)

In my opinion, this means that the octet `0x40` (representing the character "@") may also be represented by the character triplet `%40` in a URL.

So my conclusion is:

1. The character `@` may be represented by an octet with value 0x40 in an URL.
2. The octet with value 0x40 may be represented by the triplet `%40` in an URL.
3. The interpretation of the URL only depends on the identity of the `@` character, and not on it's representation.

See also page 3:

>   On the other hand, characters that are not required to be encoded
>   (including alphanumerics) may be encoded within the scheme-specific
>   part of a URL, as long as they are not being used for a reserved
>   purpose.

There are characters that are required to be encoded, and others are not. The ones which are not required to be encoded MAY still be encoded. This only makes sense when both versions, the encoded and not encoded one, have the same interpretation.

I have also found this interpretation in [RFC 3986 URI: When to Encode or Decode](https://tools.ietf.org/html/rfc3986#section-2.4). For instance, it says

> The only exception is for percent-encoded octets corresponding to characters in the unreserved set, which can be decoded at any time.  **For example, the octet corresponding to the tilde ("~") character is often encoded as "%7E" by older URI processing implementations; the "%7E" can be replaced by "~" without changing its interpretation.**

Characters in the unreserved set can be decoded at any time! And `%7e` in an URI has exactly the same meaning (!) as `~` (By the way, `@` is not in the unreserved set, but it may be used in URL paths without encoding nevertheless).


**Replies to pragmatic arguments**

> The two URLs you've provided are not equal. To confirm, try this in your browser’s JavaScript console.
> new URL("http://example.com/my%40dav/").href
> new URL("http://example.com/my@dav/").href

I don't understand this argument. Both `href` values are different, but how does that back that
* both values mean different locations (i.e. the URLs are not "equal"), in contrast to
* both `href`s have different values, but the same interpretation?

> Also fun, run nc -l 9999 and then curl 'http://localhost:9999/my%40dav/'.

It tells me that `curl` sends:

```
GET /my%40dav/ HTTP/1.1
User-Agent: curl/7.40.0
Host: localhost:9999
Accept: */*
```

How can that help to determine whether `/my%40dav/` and `/my@dav/` both represent the same resource?

> Presumably those WebDAV servers consider the two URLs to be equal. But other servers may serve different content on the encoded and non-encoded form. Similarly, some servers may choose to discard case, treating index.html and INDEX.HTML as the same resource.

These are two completely different statements:

1. As far as I understand, you're saying: Servers MAY treat `/` and `/index.html` the same way, i.e. give these two – different – URLs the same meaning. Other servers may not.
2. However, my point of view is that clients and servers MUST treat `/index.html` and `/%69ndex.html` exactly the same way, i.e. they MUST NOT assign different meaning to these two representations of (in my opinion) the same URL.

> It's the encoded form that's canonical. Servers may even serve different resources under %4A vs. %4a, and so HTTP clients preserve even that.

Can you please back this with references? Or did you experience such a behavior from some servers?

**Comment by rfc2822** [comment]
If you find my explanations worth of a thought, I'd be happy if you could re-open this issue so that other people can see it and maybe take part in the discussion.

**Comment by swankjesse** [comment]
I definitely prefer your interpretation - it's simple! But sadly that's not what the browsers do, and OkHttp strives to be consistent with browsers.

Consider the W3C’s web platform tests. They have a test case that requires URL implementations _not_ canonicalize `%51` to `Q`:
https://github.com/w3c/web-platform-tests/blob/master/url/urltestdata.txt#L152

If you'd like, you can write a function that takes an `HttpUrl` and does _aggressive_ canonicalization to that `HttpUrl`. Heck, given the right method name and motivating use cases, we could include it in `HttpUrl`. But I don’t want to do aggressive canonicalization by default because that would make OkHttp inconsistent with browsers. Imagine a web server that redirects `/foo` to `/my%40dav`. That server may very well return 200 on `/my%40dav` and 404 on `/my@dav`.

**Comment by rfc2822** [comment]
> But sadly that's not what the browsers do,

When do browsers have to decide whether two URL representations have the same meaning (i.e. do HttpUrl `equals()`)? The only case I can imagine is when storing things into the cache, and even then they can treat the representations differently and it won't do any harm.

> Consider the W3C’s web platform tests. They have a test case that requires URL implementations not canonicalize %51 to Q:

I see. But that's not related to the question of whether `%51` and `Q` have to be treated as `equal()`.

I don't say that okhttp should do aggressive canonicalization in general, but only for `equals()`. Currently, `equal()` says that `/my%40dav/` is not equal to `/my@dav/`, which is not true as these two representations have the same meaning.

> Imagine a web server that redirects /foo to /my%40dav. That server may very well return 200 on `/my%40dav` and 404 on `/my@dav`.

Would you consider this server to be broken?

**Comment by swankjesse** [comment]
Either two URLs are equal and interchangeable, or they aren’t and they aren’t. In this case the URLs are not interchangeable and so they cannot be equal.

> Would you consider this server to be broken?

This is how most servers work most of the time.
`curl -v  'https://github.com/square/%6fkhttp'`returns 404.
`curl -v  'https://github.com/square/okhttp'` returns 200.

**Comment by rfc2822** [comment]
> Either two URLs are equal and interchangeable, or they aren’t and they aren’t. In this case the URLs are not interchangeable and so they cannot be equal.

I don't understand why and you don't have told me why (except than "some browsers/servers think so"), but I guess we can stop the discussion here. You don't owe me an explanation.

Example 1 (argument from authority):

```
$ curl -v http://google.com/generate_204
> GET /generate_204 HTTP/1.1
> User-Agent: curl/7.40.0
> Host: google.com
> Accept: */*
> 
< HTTP/1.1 204 No Content
< Content-Length: 0
< Date: Sat, 10 Oct 2015 21:36:44 GMT
< Server: GFE/2.0

$ curl -v http://google.com/gen%65rate_204
> GET /gen%65rate_204 HTTP/1.1
> User-Agent: curl/7.40.0
> Host: google.com
> Accept: */*
> 
< HTTP/1.1 204 No Content
< Content-Length: 0
< Date: Sat, 10 Oct 2015 21:36:13 GMT
< Server: GFE/2.0
```

Example 2 (argument from authority): When I enter `http://www.bbc.co.uk/%63ontact` in Firefox, it requests `http://www.bbc.co.uk/%63ontact`. The server responds with 200 OK and returns the same page as when queried for `http://www.bbc.co.uk/contact`. Firefox then even displays the URL in the URL field as "http://www.bbc.co.uk/contact" (!), although there were no redirects.

> curl -v 'https://github.com/square/%6fkhttp' returns 404.
> curl -v 'https://github.com/square/okhttp' returns 200.

Even Github could be broken.

But probably you're right and I just don't get it. I'll do my own URL comparison helper which will be usable for Web servers which behave like what I think to be standards-compliant (e.g. WebDAV servers).

Thanks for your time.

**Comment by jellopuddingstick** [comment]
I came across this issue while evaluating different URL normalizing libraries, and I just wanted to point out that some of the justifications for the current behavior are no longer valid.

In particular, Chrome now decodes percent-encoded unreserved characters:

```js
new URL("https://github.com/square/%6fkhttp").href // returns "https://github.com/square/okhttp"
```

It seems like

> OkHttp strives to be consistent with browsers

and

> In this case the URLs are not interchangeable and so they cannot be equal.

might now be at odds with one another.

**Comment by swankjesse** [comment]
@jellopuddingstic no, those are two distinct URLs and the server can return different content for each. If Chrome thinks they’re equal, that’s a bug in Chrome, not a feature we want to match.

![Screenshot_20210807-083443](https://user-images.githubusercontent.com/133019/128600403-b2cb92ae-0132-407b-b089-2bf8319559ef.png)

Here's a clickable link to test other browsers without using the URL bar:
[https://github.com/square/%6fkhttp](https://github.com/square/%6fkhttp)

**Comment by swankjesse** [comment]
I wrote about this a bit more a few years ago:
https://publicobject.com/2017/08/01/url-encoding-is-material/

What's interesting is Chrome is pretty aggressive about turning `%6f` into `o` but doesn’t do the same for `%3b`. (Is there a spec that describes must canonicalize characters that OkHttp, curl, and Firefox violate?)
