### ISSUE TITLE
HttpUrl && "|"

### ISSUE THREAD

**Issue by KennyGoers** [square/okhttp#1917]
I'm using a search request in the form of http://sample.com/search?this | that using the builder and an HttpUrl. The request fus built also using the HttpUrl and encoded properly with the builder. The resulting url is http://sample.com/search?this%20|%20that but fails within the the Request handling with a URI error as the URI class can't handle the unencoded pipe (|).

I some some buzz about this, but is there a work around? 

The really weird part about this is that it worked just fine, but started failing suddenly in the field more than a month after deployment, which is confusing me.

**Comment by swankjesse** [comment]
There's a fix on master. Or you can fix in your calling code by manually percent-encoding the `|` character. Sorry about this!

**Comment by KennyGoers** [comment]
Any thoughts in a timeline for a release?

**Comment by swankjesse** [comment]
It's overdue. I wanted to do 2.6 in October but it probably won't be ready until some time in November.
