### ISSUE TITLE
URL wih # returns Error 

### ISSUE THREAD

**Issue by hoshomoh** [square/okhttp#1918]
For some reason OkHttp returns an error for this url http://stackoverflow.com/questions/33056658/okhttp-page-source# even when its correct.

If i remove the # at the end everything works fine.

**Comment by swankjesse** [comment]
@hoshomoh  I was unable to reproduce this. Could you please provide an executable test case?

**Comment by hoshomoh** [comment]
Okay @swankjesse Sorry this came late. My case was this; I'm building this app that respond to shared URL. So part of my test was to make sure that all URL are return a success respnse of 200. I used OkHttp to make sure that I got a succes response of 200. For some reason urls with empty fragment or with frahgments seems to return error even though they where valid.

**Comment by swankjesse** [comment]
@hoshomoh I was unable to reproduce this. Could you please provide an executable test case?
