### ISSUE TITLE
Url '+' sign always encoded to %20 or %2B 

### ISSUE THREAD

**Issue by aencica** [square/okhttp#1920]
I am doing some calls on an API that specific requires the '+' sign in the query parameter value. It seems kind of odd that there is no way to specify the request to leave the url as it is, at least for the query parameters value.

For example http://example.org/path?query_param=foo+bar

**Comment by swankjesse** [comment]
Yep, I think we were a little too aggressive in picking the canonical form here.

**Comment by cosminstefanxp** [comment]
:+1:
