### ISSUE TITLE
logging-interceptor

### ISSUE THREAD

**Issue by liqk2014** [square/okhttp#1922]
at this page https://github.com/square/okhttp/tree/master/okhttp-logging-interceptor
the last line : compile 'com.squareup.okhttp:logging-interceptor:(insert latest version)' 
what is  the “lastest version" meaning? ; I've tryed  compile 'com.squareup.okhttp:logging-interceptor:2.5.0',but it didn't work in my andorid studio 。how to solve this problem？thank you!

**Comment by JakeWharton** [comment]
This module is not released yet as it was added very recently after 2.5.0. It will be part of the next release, 2.6.0, whenever that happens. Probably sometime in late October or November.

**Comment by liqk2014** [comment]
yeah.i see,thank you very much.

**Comment by GitHubMurt** [comment]
here you find the number of the lastest version
http://mvnrepository.com/artifact/com.squareup.okhttp/logging-interceptor
