### ISSUE TITLE
ConnectionSpec.isCompatible() and ConnectionSpec.supportedSpec()'s question

### ISSUE THREAD

**Issue by NeoLSN** [square/okhttp#1923]
I think the goal of ConnectionSpec is let a client can manipulate a SSL socket's cipher suites and TLS versions.
But it is not like what I think when I checked the code.
What I think is:
* By comparing  ```sslSocket.getSupportedProtocols()```.
    * if supported then enable protocols like ```sslSocket.setEnabledProtocols(...)```.
* Merge the cipher suites and get intersection.
    * then ```sslSocket.setEnabledCipherSuites(...)```.

Right now, it is comparing ```sslSocket.getEnabledProtocols()``` in ```ConnectionSpec.isCompatible()```
So I can not manipulate the socket as I want.
Perhaps my thought is wrong.
Can you check this?

**Comment by swankjesse** [comment]
I think you'll be better off asking questions like this on StackOverflow.
