### ISSUE TITLE
OkHTTP does not unzip Gzipped content when using Authenticator

### ISSUE THREAD

**Issue by tyvsmith** [square/okhttp#1927]
Using OkHttp 2.5

I'm using an Authenticator to catch 401's and refresh my OAuth token. Upon retrying the requests, GSON fails at parsing a compressed String. Since OkHTTP silently adds the "Accept-encoding: gzip" header after the first try, upon retrying with the Authenticator it sees the existing header for "Accept-encoding" and does not do the unzipping.

```
10-15 16:03:42.900 18864-18889/com.example.dev D/Retrofit: <--- HTTP 200 (775ms)
10-15 16:03:42.900 18864-18889/com.example.dev D/Retrofit: Content-Encoding: gzip
10-15 16:03:42.900 18864-18889/com.example.dev D/Retrofit: Content-Type: application/json; charset=utf-8
10-15 16:03:42.900 18864-18889/com.example.dev D/Retrofit: Date: Thu, 15 Oct 2015 20:03:42 GMT
10-15 16:03:42.900 18864-18889/com.example.dev D/Retrofit: Server: nginx
10-15 16:03:42.900 18864-18889/com.example.dev D/Retrofit: Status: 200 OK
10-15 16:03:42.900 18864-18889/com.example.dev D/Retrofit: X-Runtime: 0.079625
10-15 16:03:42.900 18864-18889/com.example.dev D/Retrofit: X-UA-Compatible: IE=Edge,chrome=1
10-15 16:03:42.900 18864-18889/com.example.dev D/Retrofit: Content-Length: 146
10-15 16:03:42.900 18864-18889/com.example.dev D/Retrofit: Connection: keep-alive
10-15 16:03:42.900 18864-18889/com.example.dev D/Retrofit: OkHttp-Selected-Protocol: http/1.1
10-15 16:03:42.900 18864-18889/com.example.dev D/Retrofit: OkHttp-Sent-Millis: 1444939422732
10-15 16:03:42.900 18864-18889/com.example.dev D/Retrofit: OkHttp-Received-Millis: 1444939422900
10-15 16:03:42.901 18864-18889/com.example.dev D/Retrofit: �������������]�A
10-15 16:03:42.901 18864-18889/com.example.dev D/Retrofit: � D��׶�F+z�D���5�"x�j7-��̛Y�	S�j�n�19JF)�L �
10-15 16:03:42.901 18864-18889/com.example.dev D/Retrofit: �c1m|��'&�]'�N�d���e��?�J��p� ��r�?4�w `�������_�7�3�'�������
10-15 16:03:42.901 18864-18889/com.example.dev D/Retrofit: <--- END HTTP (146-byte body)
```

```java
    private Request refreshAndSign(Response response, AccessToken token) {
        AccessToken freshToken = service.refreshAccessToken(token.refreshToken);
        accessTokenState.setAccessToken(freshToken);

        Request.Builder builder = response.networkResponse().request().newBuilder();
        setAuthHeader(builder, freshToken);
        return builder.build();
    }
```

This is worked around by explicitly removing the header when resigning.

```java
builder.removeHeader("Accept-Encoding");
```

**Comment by swankjesse** [comment]
Eep. I thought we'd fixed all of these.

**Comment by JakeWharton** [comment]
Did you try OkHttp 2.5? OkHttp 2.0 is really, really old.

**Comment by tyvsmith** [comment]
@JakeWharton  I edited it to 2.5 after the first post.

**Comment by alexeimoisseev** [comment]
It seems that response body isn't ungzipped automatically every time you specify "Accept-Encoding: gzip" header manually in a request.

**Comment by JakeWharton** [comment]
By adding that header you are informing OkHttp that you can accept
Gzip-encoded bodies at the application layer.

**Comment by alexeimoisseev** [comment]
@tyvsmith By the way, is it really necessary for you to use raw headers (`networkResponse`)?
Seems like not.
It will work properly if you set auth header this way:

```java
Request.Builder builder = response.request().newBuilder();
setAuthHeader(builder, freshToken);
```

**Comment by tyvsmith** [comment]
@alexeimoisseev At first glance that seems accurate, however, it appears like already existing headers only exist on the networkResponse.request(). Using the builder you recommended would lose other headers set.

**Comment by swankjesse** [comment]
@tyvsmith I think the right fix is to avoid using `networkResponse()` when you're rebuilding the request.

```diff
- Request.Builder builder = response.request().newBuilder();
+ Request.Builder builder = response.networkResponse().request().newBuilder();
```

**Comment by tyvsmith** [comment]
@swankjesse unfortunately, by using response.request(), all headers are stripped, including ones I injected with interceptors. Is this the desired behavior or is there a recommended alternative approach?

![evaluate_expression_and_genymotion_-_google_nexus_5_-_5_1_0_-_api_22_-_1080x1920__1080x1920__480dpi__-_192_168_58_101](https://cloud.githubusercontent.com/assets/309657/11826159/5ea0058e-a338-11e5-9d58-664df3665eb5.jpg)

![evaluate_expression](https://cloud.githubusercontent.com/assets/309657/11826162/6283fe08-a338-11e5-9bc7-8d0cdf4fa2fd.jpg)
