### ISSUE TITLE
Web Socket support?

### ISSUE THREAD

**Issue by ErikHellman** [square/okhttp#193]
Any chance we could se support for Web Sockets?

**Comment by nkzawa** [comment]
+1

I'm thinking to use okhttp for Socket.IO Java Client. https://github.com/nkzawa/socket.io-client.java
I'd like to know the status of the websocket implementation.

**Comment by JakeWharton** [comment]
It's working, but not battle tested in the wild or with an API that we're
sure is good enough for public consumption. The classes are available and
usable in the latest snapshot.

**Comment by JakeWharton** [comment]
See the WebSocketEcho file in the samples for a quick crash course in how
to use it.

**Comment by nkzawa** [comment]
@JakeWharton thx, I will try.

**Comment by JakeWharton** [comment]
okhttp-ws module shipped!
