### ISSUE TITLE
IOException when writing to Websocket sink causes writing to fail forever

### ISSUE THREAD

**Issue by pwerry** [square/okhttp#1931]
This change: [https://github.com/square/okhttp/commit/40a6dc7dd5ff6843b82f904516181182d512d0ca] contains these lines in `public void sendMessage(RequestBody message)`:

```java 
    BufferedSink sink = Okio.buffer(writer.newMessageSink(formatOpcode));
    message.writeTo(sink);
    sink.close();
```

Perhaps rephrase as:
```java
    BufferedSink sink = Okio.buffer(writer.newMessageSink(formatOpcode));
    try {
      message.writeTo(sink);
    } finally {
      sink.close();
    }
```

If an `IOException` is thrown here the sink will never close yet the websocket will remain in a valid state. This causes subsequent executions of `writer.NewMessageSink(formatOpcode)` to fail because the writer is still active.

**Comment by JakeWharton** [comment]
If the `IOException` comes from writing to the underlying socket, the connection isn't in a good state, and calling `close()` will throw another `IOException`. If the `IOException` comes from obtaining the data (like reading from the FS, calling `close()` will finalize the incomplete message.

I think in both cases we try to should send a protocol exception to the server and fail the whole connection.
