### ISSUE TITLE
http code = 408,fiddler do not catch the request url

### ISSUE THREAD

**Issue by chinaczy** [square/okhttp#1937]
Response.body().string()=The client failed to send a complete request on this REUSED connection before the timeout period elapsed; 0 bytes were read from client.

but i can not find this string in okhttp's source .

i used mHttpClient.setReadTimeout(12, TimeUnit.SECONDS);
        mHttpClient.setWriteTimeout(12 , TimeUnit.SECONDS);

**Comment by swankjesse** [comment]
Could you provide a test case to reproduce this? As-is it's unclear what we can do to fix this.

**Comment by chinaczy** [comment]
i don't call ResponseBody.close() ,is this reason ?
