### ISSUE TITLE
OkHttp(version:2.4.0) can't enqueue request !!!

### ISSUE THREAD

**Issue by brycegao** [square/okhttp#1941]
When I  execute multiple  client.newCall(request).enqueue... at the same point,    
     the callback function onResponse(Response response) return  
 "The client failed to send a complete request on this REUSED connection before the timeout period elapsed; 0 bytes were read from client.".

        How do deal with this error?  As my http request can't be execute successfully.

**Comment by swankjesse** [comment]
This sounds like a better question for stackoverflow. This tracker is for feature requests & bug reports (with test cases) only.
