### ISSUE TITLE
Http call for rest APIs

### ISSUE THREAD

**Issue by abhi9wagadre** [square/okhttp#1945]
I am new to programming in android and I am developing an app which needs an rest API call from the app using http post method.
While looking for solutions online I came across Square http ok link.
I am unable to make out how to use this in my existing code for login screen.
I have compiled the gradle dependency.Need to know the further steps.
Any help will be appreciated.
Thanks and Regards.

**Comment by caseykulm** [comment]
For more information see [the website](http://square.github.io/okhttp/) and [the wiki](https://github.com/square/okhttp/wiki).
