### ISSUE TITLE
Method setAlpnProtocols not supported

### ISSUE THREAD

**Issue by luispereira** [square/okhttp#1946]
Hi I'm using the latest okHttp lib 2.5.0, 

When sometimes I'm trying to connect to an https url the following exception appears:

java.lang.AssertionError: Method setAlpnProtocols not supported for object SSL socket over Socket[address=THE_CONNECTED_URL,port=443,localPort=46845]  at 
 com.squareup.okhttp.internal.OptionalMethod.invoke(Unknown Source)  at 
 com.squareup.okhttp.internal.OptionalMethod.invokeWithoutCheckedException(Unknown Source) at 
 com.squareup.okhttp.internal.Platform$Android.configureTlsExtensions(Unknown Source)  at 
 com.squareup.okhttp.Connection.connectTls(Unknown Source) at 
 com.squareup.okhttp.Connection.connectSocket(Unknown Source)  at 
 com.squareup.okhttp.Connection.connect(Unknown Source)  at 
 com.squareup.okhttp.Connection.connectAndSetOwner(Unknown Source) at 
 com.squareup.okhttp.OkHttpClient$1.connectAndSetOwner(Unknown Source) at 
 com.squareup.okhttp.internal.http.HttpEngine.connect(Unknown Source)  at 
 com.squareup.okhttp.internal.http.HttpEngine.sendRequest(Unknown Source)  at 
 com.squareup.okhttp.Call.getResponse(Unknown Source)  at 
 com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Unknown Source)  at 
 com.squareup.okhttp.Call.getResponseWithInterceptorChain(Unknown Source)  at 
 com.squareup.okhttp.Call.execute(Unknown Source)  ...

I'm simply making the okhttp call like this:
`client= new OkHttpClient();
//setting timeouts and readtimeouts
//setting headers and method post for the request variable
client.newCall(request).execute();`

Am I doing something wrong here?
I just want to understand why is an AssertionError being triggered here after an invokeWithoutCheckedException :(

**Comment by swankjesse** [comment]
Two questions:
1. Android or desktop Java? What version?
2. Can you run again retaining debug symbols? Unknown Source is difficult to diagnose.

**Comment by swankjesse** [comment]
No action for us to take on this.
