### ISSUE TITLE
OkHttp Doesn't close socket, it occured TCP ZeroWindow.

### ISSUE THREAD

**Issue by jihunyang** [square/okhttp#1949]
Platform Version: M OS

1. Download file through Downloads(DownloadManager).
2. Cancle the download.

Downloads doesn't close socket. And occurs TCP ZeroWindow.
This issue reproducible only through the DownloadManager.
We guess the reason is OkHttp's AsyncTimeOut demon.
When we cancel the download, It notice to AsyncTimeout demon service and demon service closes socket without uid.

**Comment by JakeWharton** [comment]
This is an Android bug, not an OkHttp bug. Please file on
http://b.android.com.
