### ISSUE TITLE
okhttp does not send headers

### ISSUE THREAD

**Issue by AniketBhadane** [square/okhttp#1950]
I'm using okhttp with picasso, gradle dependencies as follows:
```
compile 'com.squareup.picasso:picasso:2.5.2'
compile 'com.squareup.okhttp:okhttp:2.5.0'
```
Using picasso simply like this:
```
        Picasso.with(context)
                .load(url)
                .placeholder(R.drawable.ic_contact_picture)
                .error(R.drawable.ic_contact_picture)
                .into(imageView);
```
Here url is something like:
```
myserverpath/getImage.php?param=abc
```
In this getImage.php file, I'm setting headers
```
header("Last-Modified: ".gmdate("D, d M Y H:i:s", $lastModified)." GMT");
header("Etag: $etagFile");
header('Cache-Control: max-age=60');
```
And sending image like this:
```
echo file_get_contents("$imagepath");
```

Now on next subsequent calls, okhttp should send these headers to servers to check HTTP_IF_MODIFIED_SINCE and HTTP_IF_NONE_MATCH values. But none are sent.

I captured packets using Wireshark and here's what I'm getting:

![ffsd](https://cloud.githubusercontent.com/assets/15356930/10812644/671de858-7e3e-11e5-81dd-66b76712bf1c.JPG)

**Comment by swankjesse** [comment]
Have you configured a cache?

**Comment by AniketBhadane** [comment]
Did not get you?

**Comment by swankjesse** [comment]
https://github.com/square/okhttp/wiki/Recipes#response-caching

**Comment by AniketBhadane** [comment]
I have not, should it be done if okhttp is used?

**Comment by swankjesse** [comment]
Yep, if you want disk caching you need to tell us how big and where.

**Comment by AniketBhadane** [comment]
Now since picasso first checks memory cache and calls okhttp only if there's a cache miss, then the headers are of NO significance at all ! Am I right?

**Comment by swankjesse** [comment]
It depends if there's a cache miss.

**Comment by AniketBhadane** [comment]
Considering an example of WhatsApp, where such thing is used to show images in listview in chats list and contacts list. When we scroll through the listview, images in cache are loaded first and in the background it checks whether the image has changed as we scroll. Does it mean it is always referring to its http client, irrespective of memory cache miss?

**Comment by swankjesse** [comment]
Let's not do Q&A in our issues tracker. If you want to talk about how stuff works, please use stackoverflow.. Otherwise we'll spend all day teaching you the APIs!

**Comment by AniketBhadane** [comment]
Sorry for that question.

Regarding picasso, if 
Picasso.with(context)
.load(url)
.networkPolicy(NetworkPolicy.NO_CACHE) /*******/
.placeholder(R.drawable.ic_contact_picture)
.error(R.drawable.ic_contact_picture)
.into(imageView);

with networkpolicy set, even then picasso will first look for memory cache? Is networkpolicy for the http client and not for picasso?

**Comment by JakeWharton** [comment]
This is not the place to ask Picasso questions.
