### ISSUE TITLE
okhttp clear disk cache

### ISSUE THREAD

**Issue by AniketBhadane** [square/okhttp#1951]
Just like picasso has Picasso.with(context).invalidate(url) , 
Does okhttp have any mechanism for clearing a disk cache entry given a key?

**Comment by JakeWharton** [comment]
There is no such API, no.

**Comment by AniketBhadane** [comment]
Is there any workaround for this?

**Comment by swankjesse** [comment]
The closest we have is iterating the cache with `urls()` and calling remove on each match. This isn't going to be very fast though!

As a rule, if you need to prune the cache you probably aren't using the right cache headers. Browsers don't have APIs to prune the cache!

**Comment by AniketBhadane** [comment]
Are there right?

header("Last-Modified: ".gmdate("D, d M Y H:i:s", $lastModified)." GMT");
header("Etag: $etagFile");
header('Cache-Control: max-age=60');
