### ISSUE TITLE
Logging Gzip'ed responses in HttpLoggingInterceptor 

### ISSUE THREAD

**Issue by robertoestivill** [square/okhttp#1955]
I noticed that `HttpLoggingInterceptor` does not log Gzip'ed response bodies.
Would you guys be interested in adding this functionality to the mentioned class?

**Comment by JakeWharton** [comment]
What do you mean it doesn't log them? Did you install it as a normal
interceptor or a network interceptor?

**Comment by robertoestivill** [comment]
I was using a network interceptor, but had an old version configured. My bad.

**Comment by drayan85** [comment]
I am using network interceptor I am getting 
D/OkHttp: <-- END HTTP (encoded body omitted)

**Comment by murki** [comment]
@JakeWharton does using the `HttpLoggingInterceptor` as a network interceptor decodes the automatically gzip-ed body? Or that will only work if added as an application interceptor?

**Comment by murki** [comment]
By looking at the source code it seems decoding the body will only work at the application level [1] [2]

[1] https://github.com/square/okhttp/blob/278088c077033b2914d9e033cf52c770c5a1cfac/okhttp/src/main/java/okhttp3/internal/http/BridgeInterceptor.java#L100-L109
[2] https://github.com/square/okhttp/blob/a94f952d4fd612b649f0e1afbbcd06b7b991765b/okhttp/src/main/java/okhttp3/RealCall.java#L175

**Comment by JakeWharton** [comment]
Yes
