### ISSUE TITLE
OutOfMemoryError when using multipart request

### ISSUE THREAD

**Issue by power-alex** [square/okhttp#1964]
Hello.
Encounterend OutOfMemoryError when uploading video using multipart request.

Here's a code snippet:
```java
MultipartBuilder builder = new MultipartBuilder()
		.type(MultipartBuilder.FORM);

for(NameValuePair pair : params) {
	builder.addPart(
			Headers.of("Content-Disposition",
					"form-data; name=\"" + pair.getName() + "\""),
			RequestBody.create(null, pair.getValue()));
}

String extension = FileUtils.getFileExtension(filePath);
String mediaType = FileUtils.getMediaType(extension);

File file = new File(filePath);
builder.addPart(
		Headers.of("Content-Disposition",
				"form-data; name=\"photo\";filename=\"" + FileUtils.getFileNameWithExtension(filePath)),
		RequestBody.create(MediaType.parse(mediaType), new File(filePath)));

RequestBody requestBody = builder.build();

Request request = new Request.Builder()
		.url(getUrl())
		.post(requestBody)
		.build();
OkHttpClient client = App.getClient();
Response response = client.newCall(request).execute();
```

Here's a stack trace:
java.lang.RuntimeException: An error occured while executing doInBackground()
1	at android.os.AsyncTask$3.done(AsyncTask.java:300)
2	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
3	at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
4	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
5	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
6	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
7	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
8	at java.lang.Thread.run(Thread.java:841)
9Caused by: java.lang.OutOfMemoryError
10	at java.lang.AbstractStringBuilder.enlargeBuffer(AbstractStringBuilder.java:94)
11	at java.lang.AbstractStringBuilder.append0(AbstractStringBuilder.java:145)
12	at java.lang.StringBuffer.append(StringBuffer.java:219)
13	at com.splunk.mint.network.io.OutputStreamMonitor.updateBody(OutputStreamMonitor.java:67)
14	at com.splunk.mint.network.io.OutputStreamMonitor.write(OutputStreamMonitor.java:58)
15	at okio.Okio$1.write(Okio.java:78)
16	at okio.AsyncTimeout$1.write(AsyncTimeout.java:155)
17	at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:156)
18	at okio.RealBufferedSink.write(RealBufferedSink.java:46)
19	at com.squareup.okhttp.internal.http.HttpConnection$FixedLengthSink.write(HttpConnection.java:280)
20	at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:156)
21	at okio.RealBufferedSink.writeAll(RealBufferedSink.java:84)
22	at com.squareup.okhttp.RequestBody$2.writeTo(RequestBody.java:100)
23	at com.squareup.okhttp.MultipartBuilder$MultipartRequestBody.writeOrCountBytes(MultipartBuilder.java:277)
24	at com.squareup.okhttp.MultipartBuilder$MultipartRequestBody.writeTo(MultipartBuilder.java:297)
25	at com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:819)
26	at com.squareup.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:684)
27	at com.squareup.okhttp.Call.getResponse(Call.java:272)
28	at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:228)
29	at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:199)
30	at com.squareup.okhttp.Call.execute(Call.java:79)

**Comment by power-alex** [comment]
nvm.
Apparently splunk mint is the culprit here. Disabling network monitoring fixes the issue.

**Comment by JakeWharton** [comment]
Yeah, looks like they buffer the entire body in memory which causes the OOM on such a large file. Glad you figured it out.
