### ISSUE TITLE
HttpLoggingInterceptor what about builder or return this from setLevel

### ISSUE THREAD

**Issue by artem-zinnatullin** [square/okhttp#1966]
Similar to https://github.com/square/retrofit/issues/1240. Would be nice to provide builder or change `setLevel` so it would return `this` and user won't have to store a reference to the `HttpLoggingInterceptor` just to set log level.

Green light for PR?

**Comment by JakeWharton** [comment]
This seems to have nothing in common with the linked issue. This class is not a builder and the method already accepts an argument that you can use conditionally (via ternary) on a boolean.

It sounds like you want a constructor overload that takes the initial level.

**Comment by artem-zinnatullin** [comment]
Sorry for being non-obvious in my words.

I mean, that would be nice to have a builder for `HttpLoggingInterceptor` or at least change `setLevel()` so it could return `this` and we don't have to store a reference to the `HttpLoggingInterceptor` to apply log level.

Today:
```java
HttpLoggingInterceptor loggingInterceptor = new HttpLoggingInterceptor();
loggingInterceptor.setLogLevel(...);
okHttpClient.interceptors().add(loggingIncerceptor);
```

Better tomorrow:
`setLogLevel()` can return `this`
```java
okHttpClient.interceptors().add(new HttpLoggingInterceptor().setLogLevel(...));
```

Or we can add builder for `HttpLoggingInterceptor`:
```java
okHttpClient.interceptors().add(new HttpLoggingInterceptor.Builder()
  .logLevel(...)
  // probably other options of HttpLoggingInterceptor such as Logger impl
  .build()
);
```

**Comment by JakeWharton** [comment]
I don't think a builder is appropriate. As to returning this, nothing
concerns me less, so feel free to send a PR for it. I don't find the first
example particularly offensive, but I suppose the mutable chain precedent
is set widely in this library already.

**Comment by swankjesse** [comment]
PR still welcome on this.

**Comment by artem-zinnatullin** [comment]
Will do today.

On Sun, Nov 22, 2015, 20:41 Jesse Wilson <notifications@github.com> wrote:

> PR still welcome on this.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/square/okhttp/issues/1966#issuecomment-158780567>.
>
-- 

@artem_zin
