### ISSUE TITLE
ResponseBody.create(MediaType, String) constructs an object which can be mutated into an invalid state using ResponseBody.string()

### ISSUE THREAD

**Issue by troinine** [square/okhttp#1968]
Basically we bumped into this when writing unit tests to our component which uses Retrofit and therefore OkHttp. The version of OkHttp is 2.5.0.

When you construct an object using the ```ResponseBody.create(MediaType, String)```, two subsequent calls to ```ResponseBody.string()``` will fail with an ```IOException``` so the getter seems to mutate the object and mutates it to corrupted state. The behaviour is not indicated by the javadoc of ```ResponseBody.string()``` and therefore it was a surprise and we did spend for a while wondering what's the problem here. ```RealResponseBody``` does not seem to be affected by the same issue.

To reproduce the problem:
```
    @Test
    public void testResponseBodyCreate() throws IOException {
        ResponseBody body = ResponseBody.create(MediaType.parse("text/plain"), "test");

        body.string();
        body.string(); // Fails with IOException when using okhttp 2.5.0
    }
```
Which reports 
```
java.io.IOException: Content-Length and stream length disagree
	at com.squareup.okhttp.ResponseBody.bytes(ResponseBody.java:62)
	at com.squareup.okhttp.ResponseBody.string(ResponseBody.java:83)
```

This probably should be documented in the javadocs or the behaviour should be fixed.

**Comment by JakeWharton** [comment]
Every `ResponseBody` instance can only be read once, in practice, as there's no automatic buffering happening. `string()` is effectively an exhaustive read of the input so on a subsequent call the underlying data source is empty (hence the exception message).

**Comment by swankjesse** [comment]
The documentation on this is not necessarily where you'll look first. It's on response which says, “Instances of this class are not immutable: the response body is a one-shot value that may be consumed only once.”

We could_also_ say that on the response body itself.

http://square.github.io/okhttp/2.x/okhttp/com/squareup/okhttp/Response.html

**Comment by troinine** [comment]
Yes, in ```Response``` it clearly says that ```ResponseBody``` retrieved from the response is a one-shot value. As @swankjesse mentions, it makes sense to document the behaviour also directly to ```ResponseBody```that some implementations may be consumed only once. Looks like instances of ```RealResponseBody``` can be consumed more than once.

Anyways, thanks for pointing us to the right direction! And in addition, OkHttp and Retrofit have made the implementation of our reactive RxJava RESTful WS clients a breeze.

**Comment by mkatsoho** [comment]
Just a suggestion. Can refer to the similar function in rest-assured, it is idempotent. I guess it cached the http resp body, and return it in later calls.

**Comment by JakeWharton** [comment]
Application code should cache the response themselves or replace the
RequestBody instance when consuming the stream.
