### ISSUE TITLE
The solution of caching POST request

### ISSUE THREAD

**Issue by rubickcc** [square/okhttp#1969]
Any plan to support POST cache?

I override the `com.squareup.okhttp.Cache.urlToKey()`  (concatenating the URL and the params as the key) method to make it support the POST cache.

Is it possible to merge if I submit a PR?

**Comment by swankjesse** [comment]
Unlikely we'll merge such a PR. Do browsers cache posts under any circumstances? Much better is to do POST-redirect-GET.
https://en.m.wikipedia.org/wiki/Post/Redirect/Get
