### ISSUE TITLE
MockWebServer throttling is possibly broken for slow rates

### ISSUE THREAD

**Issue by nfuller** [square/okhttp#1975]
This is potentially subjective depending on developer expectations. Creating for discussion.

When the MockWebServer opens a socket it wraps the source/sink in BufferedSource / BufferedSink.

```
    BufferedSource source = Okio.buffer(Okio.source(socket));
    BufferedSink sink = Okio.buffer(Okio.sink(socket));
```

The first request body read will read an entire okio segment in one go (e.g. currently 8192 bytes).
If there is a throttling policy the policy is then applied to the reads from the buffer. This has the effect of delaying the body transfer but it's not acting on the network rate as tests _may_ be assuming.

MockResponse docs are slightly at odds with behavior. The documentation suggests it acts on the response body write, but it also acts on the request body read:

```
  /**
   * Throttles the response body writer to sleep for the given period after each
   * series of {@code bytesPerPeriod} bytes are written. Use this to simulate
   * network behavior.
   */
  public MockResponse throttleBody(long bytesPerPeriod, long period, TimeUnit unit) {
```

Response body writes probably have a similar situation: the response body is trickled into a buffer but will be sent en masse to the client in a segment-sized lump when there is enough. I haven't actually checked this, though.

Removing the request buffering and acting directly on the Socket Source is non-trivial due to the reliance on string-based methods (and exhausted()) that exist on BufferedSource (preventing an easy switch to Source) and the inability to set the segment size (preventing the use of a smaller buffer). Switching throttledTransfer() to using Sink looks like it would be easy, though I've not tried removing any buffering.

**Comment by swankjesse** [comment]
We can just call `emit()` or `flush()`.

**Comment by nfuller** [comment]
I assume that works for response body throttling.
Is there an equivalent for request body reading?

**Comment by swankjesse** [comment]
Ahh, only on the sending side.

**Comment by swankjesse** [comment]
@nfuller what would a fix for this look like?

**Comment by swankjesse** [comment]
No obvious action to take on this.
