### ISSUE TITLE
okhttp - Dropbox http API v2

### ISSUE THREAD

**Issue by rchampa** [square/okhttp#1983]
I'm trying to upload a file from android but I'm getting an exception SocketTimeoutException. I have tried use curl and upload the same file and it works.

More details:
http://stackoverflow.com/questions/33598816/okhttp-dropbox-http-api-v2

**Comment by JakeWharton** [comment]
This is a usage question, so StackOverflow was the right place for it.

That said, seems like your timeouts are too low which is causing the exception.
