### ISSUE TITLE
okhttp + retrofit  requset body gzip not working

### ISSUE THREAD

**Issue by chonamdoo** [square/okhttp#1986]
i use  com.squareup.okhttp:okhttp:2.5.0  , com.squareup.retrofit:retrofit:1.9.0      

			// okhttpclient setting

			OkHttpClient statisticsApiClient = new OkHttpClient();
			statisticsApiClient.setReadTimeout(20000, TimeUnit.MILLISECONDS);
			statisticsApiClient.setConnectTimeout(20000, TimeUnit.MILLISECONDS);
			statisticsApiClient.interceptors().add(new GzipRequestInterceptor());

			RestAdapter restStatisticsAdapter = new RestAdapter.Builder().setEndpoint("http://test.couchgram.com").setClient(new OkClient(statisticsApiClient))
					.setLogLevel(RestAdapter.LogLevel.FULL).build();
			statisticsService = restStatisticsAdapter.create(RequestService.class);

			// rest api
			@Headers("Cache-Control: max-age=5000")
			@POST("/api/v1/log")
			@FormUrlEncoded
			Observable<NewBaseData> postStatisticsData(@Field(ServerConst.STATISTICS_DATA) String statistics_data);

			// gzip
			public class GzipRequestInterceptor implements Interceptor {
				@Override public Response intercept(Chain chain) throws IOException {
					Request originalRequest = chain.request();
					if (originalRequest.body() == null || originalRequest.header("Content-Encoding") != null) {
						return chain.proceed(originalRequest);
					}
					Request compressedRequest = originalRequest.newBuilder()
							.header("Content-Encoding", "gzip")
							.method(originalRequest.method(), forceContentLength(gzip(originalRequest.body())))
							.build();
					return chain.proceed(compressedRequest);
				}

				/** https://github.com/square/okhttp/issues/350 */
				private RequestBody forceContentLength(final RequestBody requestBody) throws IOException {
					final Buffer buffer = new Buffer();
					requestBody.writeTo(buffer);
					return new RequestBody() {
						@Override
						public MediaType contentType() {
							return requestBody.contentType();
						}

						@Override
						public long contentLength() {
							return buffer.size();
						}

						@Override
						public void writeTo(BufferedSink sink) throws IOException {
							sink.write(buffer.snapshot());
						}
					};
				}

				private RequestBody gzip(final RequestBody body) {
					return new RequestBody() {
						@Override public MediaType contentType() {
							return body.contentType();
						}

						@Override public long contentLength() {
							return -1; // We don't know the compressed length in advance!
						}

						@Override public void writeTo(BufferedSink sink) throws IOException {
							BufferedSink gzipSink = Okio.buffer(new GzipSink(sink));
							body.writeTo(gzipSink);
							gzipSink.close();
						}
					};
				}
			}

		    HTTP 416 error

**Comment by iNoles** [comment]
416 = Requested Range not satisfiable
the server is looking to right amount of bytes to match. If it is not, you get 416 error.

**Comment by chonamdoo** [comment]
---> HTTP POST http://test.couchgram.com/api/v1/log
 Cache-Control: max-age=5000
 Content-Type: application/x-www-form-urlencoded; charset=UTF-8
 Content-Length: 14012
 statistics_data=%7B%22%5C%2Flog%5C%2Fprivacy.log%22%3A%5B%22%7B%5C%22OSVersion%5C%22%3A%5C%2223%5C%22%2C%5C%22networkType%5C%22%3A%5C%22WIFI%5C%22%2C%5C%22regist_user%5C%22%3A%5C%22Y%5C%22%2C%5C%22modelName%5C%22%3A%5C%22Nexus+5X%5C%22%2C%5C%22device_rid%5C%22%3A%5C%22w93whwjmzino5kbj8bpzwesajh%5C%22%2C%5C%22statType%5C%22%3A%5C%22update%5C%22%2C%5C%22uuid%5C%22%3A%5C%22c9d189065ca83c99%5C%22%2C%5C%22locale%5C%22%3A%5C%22ko_KR%5C%22%2C%5C%22version%5C%22%3A73%2C%5C%22eventTime%5C%22%3A%5C%221447155905759%5C%22%2C%5C%22user_rid%5C%22%3A%5C%22ob87rsp7wfynfc78cftgmahj7h%5C%22%2C%5C%22mcc_mnc%5C%22%3A%5C%2245008%5C%22%7D%22%2C%22%7B%5C%22OSVersion%5C%22%3A%5C%2223%5C%22%2C%5C%22networkType%5C%22%3A%5C%22WIFI%5C%22%2C%5C%22regist_user%5C%22%3A%5C%22Y%5C%22%2C%5C%22modelName%5C%22%3A%5C%22Nexus+5X%5C%22%2C%5C%22device_rid%5C%22%3A%5C%22w93whwjmzino5kbj8bpzwesajh%5C%22%2C%5C%22statType%5C%22%3A%5C%22update%5C%22%2C%5C%22uuid%5C%22%3A%5C%22c9d189065ca83c99%5C%22%2C%5C%22locale%5C%22%3A%5C%22ko_KR%5C%22%2C%5C%22version%5C%22%3A73%2C%5C%22eventTime%5C%22%3A%5C%221447156328610%5C%22%2C%5C%22user_rid%5C%22%3A%5C%22ob87rsp7wfynfc78cftgmahj7h%5C%22%2C%5C%22mcc_mnc%5C%22%3A%5C%2245008%5C%22%7D%22%2C%22%7B%5C%22OSVersion%5C%22%3A%5C%2223%5C%22%2C%5C%22networkType%5C%22%3A%5C%22WIFI%5C%22%2C%5C%22regist_user%5C%22%3A%5C%22Y%5C%22%2C%5C%22modelName%5C%22%3A%5C%22Nexus+5X%5C%22%2C%5C%22device_rid%5C%22%3A%5C%22w93whwjmzino5kbj8bpzwesajh%5C%22%2C%5C%22statType%5C%22%3A%5C%22update%5C%22%2C%5C%22uuid%5C%22%3A%5C%22c9d189065ca83c99%5C%22%2C%5C%22locale%5C%22%3A%5C%22ko_KR%5C%22%2C%5C%22version%5C%22%3A73%2C%5C%22eventTime%5C%22%3A%5C%221447156538917%5C%22%2C%5C%22user_rid%5C%22%3A%5C%22ob87rsp7wfynfc78cftgmahj7h%5C%22%2C%5C%22mcc_mnc%5C%22%3A%5C%2245008%5C%22%7D%22%2C%22%7B%5C%22OSVersion%5C%22%3A%5C%2223%5C%22%2C%5C%22networkType%5C%22%3A%5C%22WIFI%5C%22%2C%5C%22regist_user%5C%22%3A%5C%22Y%5C%22%2C%5C%22modelName%5C%22%3A%5C%22Nexus+5X%5C%22%2C%5C%22device_rid%5C%22%3A%5C%22w93whwjmzino5kbj8bpzwesajh%5C%22%2C%5C%22statType%5C%22%3A%5C%22update%5C%22%2C%5C%22uuid%5C%22%3A%5C%22c9d189065ca83c99%5C%22%2C%5C%22locale%5C%22%3A%5C%22ko_KR%5C%22%2C%5C%22version%5C%22%3A73%2C%5C%22eventTime%5C%22%3A%5C%221447156765466%5C%22%2C%5C%22user_rid%5C%22%3A%5C%22ob87rsp7wfynfc78cftgmahj7h%5C%22%2C%5C%22mcc_mnc%5C%22%3A%5C%2245008%5C%22%7D%22%2C%22%7B%5C%22OSVersion%5C%22%3A%5C%2223%5C%22%2C%5C%22networkType%5C%22%3A%5C%22WIFI%5C%22%2C%5C%22regist_user%5C%22%3A%5C%22Y%5C%22%2C%5C%22modelName%5C%22%3A%5C%22Nexus+5X%5C%22%2C%5C%22device_rid%5C%22%3A%5C%22w93whwjmzino5kbj8bpzwesajh%5C%22%2C%5C%22statType%5C%22%3A%5C%22update%5C%22%2C%5C%22uuid%5C%22%3A%5C%22c9d189065ca83c99%5C%22%2C%5C%22locale%5C%22%3A%5C%22ko_KR%5C%22%2C%5C%22version%5C%22%3A73%2C%5C%22eventTime%5C%22%3A%5C%221447156812578%5C%22%2C%5C%22user_rid%5C%22%3A%5C%22ob87rsp7wfynfc78cftgmahj7h%5C%22%2C%5C%22mcc_mnc%5C%22%3A%5C%2245008%5C%22%7D%22%2C%22%7B%5C%22OSVersion%5C%22%3A%5C%2223%5C%22%2C%5C%22networkType%5C%22%3A%5C%22WIFI%5C%22%2C%5C%22regist_user%5C%22%3A%5C%22Y%5C%22%2C%5C%22modelName%5C%22%3A%5C%22Nexus+5X%5C%22%2C%5C%22device_rid%5C%22%3A%5C%22w93whwjmzino5kbj8bpzwesajh%5C%22%2C%5C%22statType%5C%22%3A%5C%22update%5C%22%2C%5C%22uuid%5C%22%3A%5C%22c9d189065ca83c99%5C%22%2C%5C%22locale%5C%22%3A%5C%22ko_KR%5C%22%2C%5C%22version%5C%22%3A73%2C%5C%22eventTime%5C%22%3A%5C%221447157398981%5C%22%2C%5C%22user_rid%5C%22%3A%5C%22ob87rsp7wfynfc78cftgmahj7h%5C%22%2C%5C%22mcc_mnc%5C%22%3A%5C%2245008%5C%22%7D%22%2C%22%7B%5C%22OSVersion%5C%22%3A%5C%2223%5C%22%2C%5C%22networkType%5C%22%3A%5C%22WIFI%5C%22%2C%5C%22regist_user%5C%22%3A%5C%22Y%5C%22%2C%5C%22modelName%5C%22%3A%5C%22Nexus+5X%5C%22%2C%5C%22device_rid%5C%22%3A%5C%22w93whwjmzino5kbj8bpzwesajh%5C%22%2C%5C%22statType%5C%22%3A%5C%22update%5C%22%2C%5C%22uuid%5C%22%3A%5C%22c9d189065ca83c99%5C%22%2C%5C%22locale%5C%22%3A%5C%22ko_KR%5C%22%2C%5C%22version%5C%22%3A73%2C%5C%22eventTime%5C%22%3A%5C%221447157448672%5C%22%2C%5C%22user_rid%5C%22%3A%5C%22ob87rsp7wfynfc7
 8cftgmahj7h%5C%22%2C%5C%22mcc_mnc%5C%22%3A%5C%2245008%
 ---> END HTTP (14012-byte body)
 <--- HTTP 416 http://test.couchgram.com/api/v1/log (5813ms)
 Server: nginx/1.6.2
 Date: Wed, 11 Nov 2015 00:32:45 GMT
 Content-Type: application/json
 Connection: keep-alive
 Accept: application/json
 OkHttp-Selected-Protocol: http/1.1
 OkHttp-Sent-Millis: 1447201964912
 OkHttp-Received-Millis: 1447201965120
 {"error":"ERROR is not json ... statistics_data=%7B%22%5C%2Flog%5C%2Fprivacy.log%22%3A%5B%22%7B%5C%22OSVersion%5C%22%3A%5C%2223%5C%22%2C%5C%22networkType%5C%22%3A%5C%22WIFI%5C%22%2C%5C%22regist_user%5C%22%3A%5C%22Y%5C%22%2C%5C%22modelName%5C%22%3A%5C%22Nexus+5X%5C%22%2C%5C%22device_rid%5C%22%3A%5C%22w93whwjmzino5kbj8bpzwesajh%5C%22%2C%5C%22statType%5C%22%3A%5C%22update%5C%22%2C%5C%22uuid%5C%22%3A%5C%22c9d189065ca83c99%5C%22%2C%5C%22locale%5C%22%3A%5C%22ko_KR%5C%22%2C%5C%22version%5C%22%3A73%2C%5C%22eventTime%5C%22%3A%5C%221447155905759%5C%22%2C%5C%22user_rid%5C%22%3A%5C%22ob87rsp7wfynfc78cftgmahj7h%5C%22%2C%5C%22mcc_mnc%5C%22%3A%5C%2245008%5C%22%7D%22%2C%22%7B%5C%22OSVersion%5C%22%3A%5C%2223%5C%22%2C%5C%22networkType%5C%22%3A%5C%22WIFI%5C%22%2C%5C%22regist_user%5C%22%3A%5C%22Y%5C%22%2C%5C%22modelName%5C%22%3A%5C%22Nexus+5X%5C%22%2C%5C%22device_rid%5C%22%3A%5C%22w93whwjmzino5kbj8bpzwesajh%5C%22%2C%5C%22statType%5C%22%3A%5C%22update%5C%22%2C%5C%22uuid%5C%22%3A%5C%22c9d189065ca83c99%5C%22%2C%5C%22locale%5C%22%3A%5C%22ko_KR%5C%22%2C%5C%22version%5C%22%3A73%2C%5C%22eventTime%5C%22%3A%5C%221447156328610%5C%22%2C%5C%22user_rid%5C%22%3A%5C%22ob87rsp7wfynfc78cftgmahj7h%5C%22%2C%5C%22mcc_mnc%5C%22%3A%5C%2245008%5C%22%7D%22%2C%22%7B%5C%22OSVersion%5C%22%3A%5C%2223%5C%22%2C%5C%22networkType%5C%22%3A%5C%22WIFI%5C%22%2C%5C%22regist_user%5C%22%3A%5C%22Y%5C%22%2C%5C%22modelName%5C%22%3A%5C%22Nexus+5X%5C%22%2C%5C%22device_rid%5C%22%3A%5C%22w93whwjmzino5kbj8bpzwesajh%5C%22%2C%5C%22statType%5C%22%3A%5C%22update%5C%22%2C%5C%22uuid%5C%22%3A%5C%22c9d189065ca83c99%5C%22%2C%5C%22locale%5C%22%3A%5C%22ko_KR%5C%22%2C%5C%22version%5C%22%3A73%2C%5C%22eventTime%5C%22%3A%5C%221447156538917%5C%22%2C%5C%22user_rid%5C%22%3A%5C%22ob87rsp7wfynfc78cftgmahj7h%5C%22%2C%5C%22mcc_mnc%5C%22%3A%5C%2245008%5C%22%7D%22%2C%22%7B%5C%22OSVersion%5C%22%3A%5C%2223%5C%22%2C%5C%22networkType%5C%22%3A%5C%22WIFI%5C%22%2C%5C%22regist_user%5C%22%3A%5C%22Y%5C%22%2C%5C%22modelName%5C%22%3A%5C%22Nexus+5X%5C%22%2C%5C%22device_rid%5C%22%3A%5C%22w93whwjmzino5kbj8bpzwesajh%5C%22%2C%5C%22statType%5C%22%3A%5C%22update%5C%22%2C%5C%22uuid%5C%22%3A%5C%22c9d189065ca83c99%5C%22%2C%5C%22locale%5C%22%3A%5C%22ko_KR%5C%22%2C%5C%22version%5C%22%3A73%2C%5C%22eventTime%5C%22%3A%5C%221447156765466%5C%22%2C%5C%22user_rid%5C%22%3A%5C%22ob87rsp7wfynfc78cftgmahj7h%5C%22%2C%5C%22mcc_mnc%5C%22%3A%5C%2245008%5C%22%7D%22%2C%22%7B%5C%22OSVersion%5C%22%3A%5C%2223%5C%22%2C%5C%22networkType%5C%22%3A%5C%22WIFI%5C%22%2C%5C%22regist_user%5C%22%3A%5C%22Y%5C%22%2C%5C%22modelName%5C%22%3A%5C%22Nexus+5X%5C%22%2C%5C%22device_rid%5C%22%3A%5C%22w93whwjmzino5kbj8bpzwesajh%5C%22%2C%5C%22statType%5C%22%3A%5C%22update%5C%22%2C%5C%22uuid%5C%22%3A%5C%22c9d189065ca83c99%5C%22%2C%5C%22locale%5C%22%3A%5C%22ko_KR%5C%22%2C%5C%22version%5C%22%3A73%2C%5C%22eventTime%5C%22%3A%5C%221447156812578%5C%22%2C%5C%22user_rid%5C%22%3A%5C%22ob87rsp7wfynfc78cftgmahj7h%5C%22%2C%5C%22mcc_mnc%5C%22%3A%5C%2245008%5C%22%7D%22%2C%22%7B%5C%22OSVersion%5C%22%3A%5C%2223%5C%22%2C%5C%22networkType%5C%22%3A%5C%22WIFI%5C%22%2C%5C%22regist_user%5C%22%3A%5C%22Y%5C%22%2C%5C%22modelName%5C%22%3A%5C%22Nexus+5X%5C%22%2C%5C%22device_rid%5C%22%3A%5C%22w93whwjmzino5kbj8bpzwesajh%5C%22%2C%5C%22statType%5C%22%3A%5C%22update%5C%22%2C%5C%22uuid%5C%22%3A%5C%22c9d189065ca83c99%5C%22%2C%5C%22locale%5C%22%3A%5C%22ko_KR%5C%22%2C%5C%22version%5C%22%3A73%2C%5C%22eventTime%5C%22%3A%5C%221447157398981%5C%22%2C%5C%22user_rid%5C%22%3A%5C%22ob87rsp7wfynfc78cftgmahj7h%5C%22%2C%5C%22mcc_mnc%5C%22%3A%5C%2245008%5C%22%7D%22%2C%22%7B%5C%22OSVersion%5C%22%3A%5C%2223%5C%22%2C%5C%22networkType%5C%22%3A%5C%22WIFI%5C%22%2C%5C%22regist_user%5C%22%3A%5C%22Y%5C%22%2C%5C%22modelName%5C%22%3A%5C%22Nexus+5X%5C%22%2C%5C%22device_rid%5C%22%3A%5C%22w93whwjmzino5kbj8bpzwesajh%5C%22%2C%5C%22statType%5C%22%3A%5C%22update%5C%22%2C%5C%22uuid%5C%22%3A%5C%22c9d189065ca83c99%5C%22%2C%5C%22locale%5C%22%3A%5C%22ko_KR%5C%22%2C%5C%22version%5C%22%3A73%2C%5C%22eventTime%5C%22%3A%5C%221447157448672%5C%22%2C%5C%22user_r
 id%5C%22%3A%5C%22ob87rsp7wfynfc78cftgmahj7h%5C%22%2C%5C%,"request":false,"success":false}
 <--- END HTTP (14077-byte body)


post body not gzip T_T
