### ISSUE TITLE
HttpLoggingInterceptor relative or absolute HttpUrl logging

### ISSUE THREAD

**Issue by austynmahoney** [square/okhttp#2012]
Should the `HttpLoggingInterceptor` log the fully qualified `HttpUrl`?

Currently it [builds the output](https://github.com/square/okhttp/blob/master/okhttp-logging-interceptor/src/main/java/com/squareup/okhttp/logging/HttpLoggingInterceptor.java#L224) using `url.encodedPath()`, which removes the hostname.

### Example
`https://store.google.com/category/phones` => `--> GET /category/phones HTTP/1.1`

**Comment by JakeWharton** [comment]
It mimcs the HTTP request line. Put it as a network interceptor and you
should see a host header.

**Comment by austynmahoney** [comment]
Just tried it as a network interceptor and got the same behavior.

**Comment by austynmahoney** [comment]
Thanks, I see it now. Still trying to get used to the nuances of this logger compared to the old Retrofit one.

**Comment by W-quan** [comment]
It can desige to choose by user?
