### ISSUE TITLE
HttpLoggingInterceptor truncates long response strings

### ISSUE THREAD

**Issue by austynmahoney** [square/okhttp#2018]
The default logger for Android will only log up to 4k of a response body in a single call to `Log.d()` (the default used on Android when `HttpLoggingInterceptor` calls `Platform.get().log(message)`.

This isn't something that is inherently wrong with the class, and can be fixed by providing your own logger, but what is the policy for Android specific code in OkHttp? Could `HttpLoggingInterceptor` provide another `Logger` that chunks the message with respect to the logcat limit of 4k?

**Comment by swankjesse** [comment]
Presumably if the data you want isn't in the first 4K, it isn't going to be in the next 10 MiB that follow?

**Comment by JakeWharton** [comment]
We have code to handle this spread all over ([example][1]). This would be an easy PR for someone to contribute!

 [1]: https://github.com/JakeWharton/timber/blob/362e20b376d9b7d788ac2659e5c92004ab2e0413/timber/src/main/java/timber/log/Timber.java#L459-L473

**Comment by JakeWharton** [comment]
Are you sure this behavior is happening? We have code for this: https://github.com/square/okhttp/blob/33dd69197ed581dc7afdfecad75ac116269953cd/okhttp/src/main/java/com/squareup/okhttp/internal/Platform.java#L257-L269

**Comment by austynmahoney** [comment]
Nice find @JakeWharton. It may have been an issue with some testing I was doing with my own copy-paste class that forwarded to just `Log.d()`. I changed back to the default implementation, but AS may not have picked up the changed injection. When I upgraded to 2.6.0 instead of using SNAPSHOT it fixed the issue (probably because of the clean build).
