### ISSUE TITLE
No message received on long running GET in Android SDK <19

### ISSUE THREAD

**Issue by oliverhausler** [square/okhttp#2023]
Long polling may fail in Android SDK <19. I investigated into this regarding xhr polling, where I could see that GET requests were responded by the server, but not received by the client (or received late): https://github.com/socketio/socket.io-client-java/issues/250

In okhttp-ws I could see the same effect: GET requests were responded, but then suddenly web socket messages were not received anymore. Just as with GET requests, which often failed when crossed over, I could see this with messages:

Server:

engine:ws received "2" +25s
engine:socket packet +0ms
engine:socket got ping +1ms
engine:socket sending packet "pong" (undefined) +0ms
engine:socket flushing buffer to transport +0ms
engine:ws writing "3" +0ms // SENT BUT NOT RECEIVED
engine:ws received "2" +33s
engine:socket packet +1ms
engine:socket got ping +0ms
engine:socket sending packet "pong" (undefined) +0ms
engine:socket flushing buffer to transport +0ms
engine:ws writing "3" +0ms

Client:

11-22 06:49:23.023 7333-7625/cc.closeup.android I/WebSocket: REQ WSK write packet
11-22 06:49:48.033 7333-8004/cc.closeup.android I/WebSocket: REQ WSK write packet
11-22 06:49:55.633 7333-7586/cc.closeup.android I/WebSocket: REQ WSK onMessage

I believe this is a bug in Android.

Not sure if this is the same issue, but I wanted to report it here. I believe both relate to the same problem, because when socket.io fails in xhr polling, also okhttp-ws fails.

**Comment by oliverhausler** [comment]
I just read through wikipedia https://en.wikipedia.org/wiki/WebSocket and maybe web sockets is not compatible with Android SDK <19, but then an exception should be thrown in the library with that information. Otherwise I guess we need a fix for this.

**Comment by oliverhausler** [comment]
As it seems, the whole network is going off in the device. I did the following test: I ran okhttp-ws and waited until messages are not received. Then I switched to the browser and called google.com. Result: Not working. When the network came back, both were back working at the very same moment.

I haven't noticed these outages on the device. Is it possible that okhttp-ws (or let's say long polling) triggers the issue on Android?

**Comment by swankjesse** [comment]
Seems unlikely!

**Comment by oliverhausler** [comment]
Agree, I couldn't believe what I saw. I hope it's just happening on a single device.

**Comment by swankjesse** [comment]
If you could isolate this into a test case, we’ll be able to investigate. As-is, there’s not much to go on here.

**Comment by oliverhausler** [comment]
@swankjesse I received the following report from another user https://github.com/socketio/socket.io-client-java/issues/250#issuecomment-160321946 - so obviously this is a node.js issue and if the request is handled by AWS ELB, it supposedly works fine.

I can reliably reproduce the problem here, but want to play with proxies first.

**Comment by oliverhausler** [comment]
@swankjesse It seems ASUS messed with their network implementation as it is working fine on other 4.2.2 devices so far, see https://github.com/socketio/socket.io-client-java/issues/250#issuecomment-161332850
