### ISSUE TITLE
logging-interceptor:2.6.0-SNAPSHOT breaks on repo. update to 2.7.0-SNAPSHOT

### ISSUE THREAD

**Issue by Ashutosh7** [square/okhttp#2027]
Previous version of the library breaks, since it is removed from the repo.

https://oss.sonatype.org/content/repositories/snapshots/com/squareup/okhttp/logging-interceptor/

**Comment by swankjesse** [comment]
Huh? What's the problem and how do we fix it?

**Comment by JakeWharton** [comment]
When 2.6.0 was released, all of the 2.6.0-SNAPSHOT versions are deleted from the snapshot repo automatically. You don't need to use a snapshot anymore. Just use 2.6.0 as the version.
