### ISSUE TITLE
SocketTimeoutException throw immediately when next request send in keep-alive mode

### ISSUE THREAD

**Issue by asg-mojtaba** [square/okhttp#2028]
Assume that keep-alive time set to 5 minute(default-time for default connection pool) and also i set read-timeout for 60 second. when first request send, a connection created on connection pool, response received and naturally connection keep open for 5 minute.

**but for example after 58 second from first response received (2-3 seconds remain for read-timeout) i send another request, after few seconds (before request received by server) i get SocketTimeoutException immediately !**

i think in keep-alive mode read-timeout interval must reset after send new request on persistent connection to avoid this situation. Or set read-timeout on request not connection.

**Comment by asg-mojtaba** [comment]
With above pull request i can set socket timeout to infinite and readTimeout to 60 second.Now next step is reset timeout of connection before send request to ensure that timeout calculate for any request not for connection.

For that i guess Okio.AsyncTimeout class need a method for reset timeout. after i can call that for both source and sink of my connection in Call.sendRequest() method

My deadline will soon be over, any idea ?! @JakeWharton @swankjesse

**Comment by swankjesse** [comment]
What version of OkHttp are you using? Can  you please provide an executable test case? We already have a similar test case from when we fixed a problem like this a few releases back.

**Comment by asg-mojtaba** [comment]
@swankjesse thanks man!
 i use 2.5.0 but 2.6.0 tested too.
i can do it but how can i simulate "no response until a time" by MockWebServer ?!

**Comment by asg-mojtaba** [comment]
@swankjesse thanks man!
i use 2.5.0 but 2.6.0 tested too.
i can do it but how can i simulate "no response until a time" by MockWebServer ?!

**Comment by swankjesse** [comment]
It was my understanding that the read timeout starts when the new read is attempted (after request 2 send in your diagram) rather than when the previous read completed.

Could you please provide an executable test case?

**Comment by asg-mojtaba** [comment]
@swankjesse Thanks, I write test case and i'm wrong about okHttp.
okHttp work great with this scenario. I must deep looking to my code to find what the hell happened.
