### ISSUE TITLE
Okhttp how to send the non - keepalive request

### ISSUE THREAD

**Issue by jinpu** [square/okhttp#2031]
@swankjesse I want to use okhttp sends a non - keepalive request, my understanding is okhttp default sends a keepalive request, but I am not sure that's the case, how should I set the non - keepalive?

**Comment by asg-mojtaba** [comment]
you can set custom connection pool with zero for maxIdleConnection parameter 

    okHttpClient.setConnectionPool(new ConnectionPool(0, 0));

**note: this is just use case you must declare your connection pool as singleton**

**Comment by swankjesse** [comment]
Use the following header: `Connection: close`.

**Comment by jinpu** [comment]
Yes, according to your method is ok, thank you!

**Comment by jinpu** [comment]
@swankjesse I use the code sends the request, see is non - keepalive from the server end, but the reponse header like this:
{"OkHttp-Selected-Protocol":"http/1.1","content-type":"text/plain","accept-ranges":"bytes","Content-Length":"6","Server":"h2o/1.6.0-alpha1","Connection":"keep-alive"}
I'm not sure that my programe is right? Please give some suggest，thaks!
```java
 client_h1 = new OkHttpClient();
 client_h1.setProtocols(Arrays.asList(Protocol.HTTP_1_1)).setConnectionPool(new ConnectionPool(100,10000));
        for (int i = 0; i < request_times; ++i) {
            request = new Request.Builder().url(Url)
                                .addHeader("Connection","keep-alive")
                                .build(); 
            response = client_h1.newCall(request).execute();
```
