### ISSUE TITLE
Strip OkHttp-Sent-Millis, OkHttp-Sent-Millis

### ISSUE THREAD

**Issue by swankjesse** [square/okhttp#2035]
These are leaked implementation details. They’re useful for the response cache but they shouldn't exist elsewhere in the API.

**Comment by panzerdev** [comment]
Why do you want to remove those headers? I think their useful for tracking the speed of the connections in an Interceptor. 
I use them for this at least.

**Comment by swankjesse** [comment]
You can do the same thing in your interceptor by calling `System.nanoTime()` !

**Comment by panzerdev** [comment]
Sure! By now I was just counting on them beeing there. But I guess the build will break wehen you remove them, because I use the constants for finding them.

**Comment by swankjesse** [comment]
Yeah, they’re a leaked implementation detail. Best to not rely on ’em!
