### ISSUE TITLE
ENETUNREACH Issue

### ISSUE THREAD

**Issue by afrikandroid** [square/okhttp#2041]
Hello,
I am having an issue with Okhttp connecting to one of my servers on digital ocean. I keep getting  the following error:

  java.net.ConnectException: failed to connect to /1.1.1.1  connect failed: ENETUNREACH (Network is unreachable). Note that I changed the ip address for privacy purposes. However, I can open the url in question in the browser with no issue. 
This problem started yesterday. I would appreciate if someone has had a similar issue.
 okio:1.5.0
 okhttp-urlconnection:2.4.0
 okhttp:2.4.0

I am also not setting any default connection time outs.
Here is my okhttp call:
 
         OkHttpClient client = getOkHttpClient();

        Request.Builder requestBuilder = new Request.Builder();
        Request request = requestBuilder.url(url).build();
        Call call = client.newCall(request);
        call.enqueue(new Callback() {
            @Override
            public void onFailure(Request request, IOException e) {
                        Logger.e(TAG,e.getMessage());
            }

            @Override
            public void onResponse(Response response) throws IOException {
                       Logger.d(TAG, response.body().toString());
            }

**Comment by swankjesse** [comment]
Does HttpURLConnection work on the same host?

**Comment by swankjesse** [comment]
(Closing as there's no action for us to take on this.)
