### ISSUE TITLE
Suppressed: javax.net.ssl.SSLHandshakeException: Handshake failed

### ISSUE THREAD

**Issue by matskr90dev** [square/okhttp#2047]
I use your library in my application and with okhttp:2.5.0 everything works fine. But after upgrade to 2.6.0 I get the following errors:

	11-28 16:49:09.714 2237-2237/com.mateusz.myapp W/System.err: retrofit.RetrofitError: Handshake failed
	11-28 16:49:09.714 2237-2237/com.mateusz.myapp W/System.err:     at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:395)
	11-28 16:49:09.714 2237-2237/com.mateusz.myapp W/System.err:     at retrofit.RestAdapter$RestHandler.access$100(RestAdapter.java:220)
	11-28 16:49:09.714 2237-2237/com.mateusz.myapp W/System.err:     at retrofit.RestAdapter$RestHandler$2.obtainResponse(RestAdapter.java:278)
	11-28 16:49:09.714 2237-2237/com.mateusz.myapp W/System.err:     at retrofit.CallbackRunnable.run(CallbackRunnable.java:42)
	11-28 16:49:09.715 2237-2237/com.mateusz.myapp W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	11-28 16:49:09.715 2237-2237/com.mateusz.myapp W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	11-28 16:49:09.715 2237-2237/com.mateusz.myapp W/System.err:     at retrofit.Platform$Android$2$1.run(Platform.java:142)
	11-28 16:49:09.715 2237-2237/com.mateusz.myapp W/System.err:     at java.lang.Thread.run(Thread.java:818)
	11-28 16:49:09.715 2237-2237/com.mateusz.myapp W/System.err: Caused by: javax.net.ssl.SSLHandshakeException: Handshake failed
	11-28 16:49:09.715 2237-2237/com.mateusz.myapp W/System.err:     at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:390)
	11-28 16:49:09.715 2237-2237/com.mateusz.myapp W/System.err:     at com.squareup.okhttp.Connection.connectTls(Connection.java:239)
	11-28 16:49:09.715 2237-2237/com.mateusz.myapp W/System.err:     at com.squareup.okhttp.Connection.connectSocket(Connection.java:201)
	11-28 16:49:09.715 2237-2237/com.mateusz.myapp W/System.err:     at com.squareup.okhttp.Connection.connect(Connection.java:172)
	11-28 16:49:09.715 2237-2237/com.mateusz.myapp W/System.err:     at com.squareup.okhttp.Connection.connectAndSetOwner(Connection.java:358)
	11-28 16:49:09.715 2237-2237/com.mateusz.myapp W/System.err:     at com.squareup.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:117)
	11-28 16:49:09.715 2237-2237/com.mateusz.myapp W/System.err:     at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:329)
	11-28 16:49:09.716 2237-2237/com.mateusz.myapp W/System.err:     at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:246)
	11-28 16:49:09.716 2237-2237/com.mateusz.myapp W/System.err:     at com.squareup.okhttp.Call.getResponse(Call.java:276)
	11-28 16:49:09.716 2237-2237/com.mateusz.myapp W/System.err:     at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:234)
	11-28 16:49:09.716 2237-2237/com.mateusz.myapp W/System.err:     at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:196)
	11-28 16:49:09.716 2237-2237/com.mateusz.myapp W/System.err:     at com.squareup.okhttp.Call.execute(Call.java:79)
	11-28 16:49:09.716 2237-2237/com.mateusz.myapp W/System.err:     at retrofit.client.OkClient.execute(OkClient.java:53)
	11-28 16:49:09.716 2237-2237/com.mateusz.myapp W/System.err:     at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:326)
	11-28 16:49:09.716 2237-2237/com.mateusz.myapp W/System.err: 	... 7 more
	11-28 16:49:09.716 2237-2237/com.mateusz.myapp W/System.err: 	Suppressed: javax.net.ssl.SSLHandshakeException: Handshake failed
	11-28 16:49:09.716 2237-2237/com.mateusz.myapp W/System.err: 		... 21 more
	11-28 16:49:09.716 2237-2237/com.mateusz.myapp W/System.err: 	Caused by: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0xb86f66d8: Failure in SSL library, usually a protocol error
	11-28 16:49:09.717 2237-2237/com.mateusz.myapp W/System.err: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure (external/openssl/ssl/s23_clnt.c:770 0xac52af89:0x00000000)
	11-28 16:49:09.717 2237-2237/com.mateusz.myapp W/System.err:     at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
	11-28 16:49:09.717 2237-2237/com.mateusz.myapp W/System.err:     at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:318)
	11-28 16:49:09.717 2237-2237/com.mateusz.myapp W/System.err: 		... 20 more
	11-28 16:49:09.717 2237-2237/com.mateusz.myapp W/System.err: Caused by: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0xb86f66d8: Failure in SSL library, usually a protocol error
	11-28 16:49:09.717 2237-2237/com.mateusz.myapp W/System.err: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure (external/openssl/ssl/s23_clnt.c:770 0xac52af89:0x00000000)
	11-28 16:49:09.717 2237-2237/com.mateusz.myapp W/System.err:     at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
	11-28 16:49:09.717 2237-2237/com.mateusz.myapp W/System.err:     at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:318)
	11-28 16:49:09.717 2237-2237/com.mateusz.myapp W/System.err: 	... 20 more

Basic info:
	`Androis Studio 1.5`
	`Grandle 1.5.0`
	`compileSdkVersion 23`
	`buildToolsVersion 23.0.2`

What's wrong? If you need more information about the issue let me know.

**Comment by swankjesse** [comment]
Is it possible the server has only obsolete cipher suites? We dropped the DSS suites in 2.6.0.

**Comment by matskr90dev** [comment]
I use Spring 1.3 Boot at the server side. I can't find any information about the default cipher suites used by Spring, but I can set it manually. I tried add sth like this:

`server.ssl.protocol: TLS`
`server.ssl.ciphers:ECDHE_RSA_WITH_AES_256_CBC_SHA384,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA,TLS_RSA_WITH_AES_256_CBC_SHA256,TLS_RSA_WITH_AES_256_CBC_SHA`

But it doesn't help. Maybe I should use another cipher suites?

**Comment by swankjesse** [comment]
Seems related to this:
http://stackoverflow.com/questions/34498023/okhttp-upgrading-from-2-5-to-2-6-breaks-https-tests

**Comment by swankjesse** [comment]
No action to take here.
