### ISSUE TITLE
OutOfMemory with OkHttp-Ws

### ISSUE THREAD

**Issue by BugsBunnyBR** [square/okhttp#2051]
Hi, I am getting some OOM while connected in a websocket with OkHttp-Ws, I know ResponseBody.string() could be the one to blame, but it is happening with my nexus 5 (2GB of ram) and as far as I could track the memory usage the app reaches more than 100 MB before crash. I don't think I have a response so big that would case that allocation. Could you help me to understand this?
I could see the same behavior with 2.6.0 and 2.7.0-SNAPSHOT.

**Comment by swankjesse** [comment]
Could you isolate the problem into a test case? We've got lots of test cases that might be a good starting point.

**Comment by BugsBunnyBR** [comment]
Triyng to write the test made me find the culprit and it is not OkHttp. Sorry for the trouble.
