### ISSUE TITLE
Connection Pool isn't pruning

### ISSUE THREAD

**Issue by swankjesse** [square/okhttp#2053]
This regression was introduced with the new allocations model. It needs to be fixed before shipping the 2.7 final.

**Comment by AndyFrench** [comment]
@swankjesse do you know at what version the regression was introduced? 2.6?

**Comment by JakeWharton** [comment]
It was never released. The new connection pool was added post-2.6 and this
issue was just tracking the regression to ensure 2.7 didn't ship with it.

**Comment by AndyFrench** [comment]
Thanks @JakeWharton. 
FYI I'm getting some really funky SocketTimeoutExceptions using Nexus 5X on 6.0 and I noticed in https://github.com/square/okhttp/issues/1771 that @bdiegel is getting anecdotally similar issues on a Nexus/Marshmallow setup.
