### ISSUE TITLE
Suggestion for usage guide

### ISSUE THREAD

**Issue by chwijaya** [square/okhttp#2056]
Dear OKHTTP developers,

I only would like to give an input regarding the usage guide/wiki of okhttp library.
After checking the code, I understand that in order for connection to be closed immediately,
app developers need to specify explicitly in the header "Connection: close" so that the connection is not reused.
Otherwise, it will open waiting to be reused.

I think many developers out there (especially who are new to okhttp) are not aware of this behavior.
Therefore, the connection is still open although they will not use it anymore, causing
waste of device energy consumption.

In one case I found that in an MMS app, it does not close the connection immediately
after finished retrieving MMS from server. It lingers for about 20 seconds before finally
the server initiate session close by sending FIN packet.

So, I would like to suggest to put this notice in OKHTTP wiki or guide, so that
app developers aware that if they do not want to reuse the connection, they must
add "Connection: close" value in the header.

Thank you.

**Comment by swankjesse** [comment]
The guide [says this](https://github.com/square/okhttp/wiki/Connections#connections):

> Once the response has been received, the connection will be returned to the pool so it can be reused for a future request. Connections are evicted from the pool after a period of inactivity.

**Comment by swankjesse** [comment]
What else should we say?
