### ISSUE TITLE
HttpLoggingInterceptor shows a gzipped response as a raw string

### ISSUE THREAD

**Issue by jbaginski** [square/okhttp#2058]
I use the standard HttpLoggingInterceptor with the log level set to ``Level.BODY``. When the response from a server is gzipped HttpLoggingInterceptor shows it as a raw string (encoded). Is it expected behaviour? It doesn't seem to be very useful unless your server has some issue with gzip :)

pidcat:
```
OkHttp  D  <-- HTTP/1.1 200 OK (146ms)
        D  Date: Wed, 02 Dec 2015 10:53:01 GMT
        D  Server: Apache
        D  X-Frame-Options: SAMEORIGIN
        D  Access-Control-Allow-Origin: *
        D  Cache-Control: no-cache, private
        D  Pragma: no-cache
        D  Content-Encoding: gzip
        D  Vary: Accept-Encoding
        D  Content-Length: 367
        D  Keep-Alive: timeout=15, max=69
        D  Connection: Keep-Alive
        D  Content-Type: application/json;charset=UTF-8
        D  OkHttp-Selected-Protocol: http/1.1
        D  OkHttp-Sent-Millis: 1449053545316
        D  OkHttp-Received-Millis: 1449053545463
        D  ������������Œ�j�0EeЪG�a�rv&-$tQ(�.[���dd%%��{ӗ�d7bĜ;���2%�"�"dU���j����`�u�l�5¦�5
        D  6ݫr�
        D  �Y4�@UW�U��
        D  �� ����c_�����p�n�/�i:@*C5A��{����xt{,�    �RJy6�
                                                                             �9Ic)���t��E0������
                                                                                                '!��JL2�e��Jɇԥ� _�k�x�3�bA36ޔ�'$ft�4���e


-ܸ�*t��<�A�� N#����tf���     ����tU���<���`�w��^���f�'�&��y�|��
      �:���r!�99{ժ�;���;�%�d���{�na�ս��|r�?.2������
        D  <-- END HTTP (367-byte body)
```

**Comment by JakeWharton** [comment]
> Is it expected behaviour?

In the sense that there's no logic to handle non-plain text bodies then yes, it behaves as we expect.

Are you adding this as a network interceptor or a normal interceptor? If you do not set it as a network interceptor you should see the plain-text body.

**Comment by jbaginski** [comment]
by adding it as a regular interceptor I'm getting decoded data :)

thanks @JakeWharton

**Comment by mikhailmelnik** [comment]
Have tried to use HttpLoggingInterceptor as either network or application interceptor but in one case it doesn't show gzipped body. in another - all headers. Is there any default solution to log both? If no how hard is that to write one?

**Comment by swankjesse** [comment]
Best approach is to use Chuck or Charles.

https://github.com/jgilfelt/chuck
https://www.charlesproxy.com/
