### ISSUE TITLE
Interceptor chain should be run before the request is checked for method and body requirements

### ISSUE THREAD

**Issue by todorus** [square/okhttp#2069]
Since I can use Interceptors to completely change the request, it is kind of odd that Builder.method(String method, RequestBody body) is run before the chain of Interceptors. I can quite easily do some processing in an interceptor that either:

* changes an invalid request into a valid one
* changes a valid request into an invalid one

It seems to me that this check should be executed after the Interceptor chain has had its chance to run and fix/break things.

**Comment by swankjesse** [comment]
The request needs to be valid at each step.
