### ISSUE TITLE
connectSocket() timeout is extremely unreliable and can leave dials in zombie state

### ISSUE THREAD

**Issue by diegomontoya** [square/okhttp#2079]
OkHttp v2.6 + Android 4/5/6 + Http 2/TLS + Port 443

We are observing zombie like states on all android versions, but more repeatable with Samsung devices for:

```java
 Platform.get().connectSocket(socket, route.getSocketAddress(), connectTimeout);
```
Where the connectTimeout is absolutely ignored and the execution is just stuck there for eternity. This maybe due to China's GFW as we are doing testing behind this.

We know that GFW plays havoc with tls/ssl connections and randomly drops or leave tcp/tls/ssl conns in zombie states so this may play a part. 

But regardless, android/java side is not also respecting the timeouts as well to detect this broken/zombie dials.

We are currently bypassing this issue with a thread for timer, a thread for actual dialing, and lock for blocking the main execution path until first thread exists.

**Comment by swankjesse** [comment]
Any advice on action we should take on this?

**Comment by swankjesse** [comment]
No action to take on this.
