### ISSUE TITLE
onResponse's response data acting weird

### ISSUE THREAD

**Issue by MyHeartsECO** [square/okhttp#2083]
So when I invoke response.body.string(), it can't be invoked again. When it is, it returns null.

On below code, when i assign 'response.body().string()' to a 'String' object, Log is null; 
or the vice versa situation: when i assign it to 'Log', 'String' object is null. So I can invoke it for only 1 time.
 ```java
Callback callback = new Callback() {
                @Override
                public void onFailure(Request request, IOException e) {
                    Log.i(DataHolder.LOG, "on fail :(");              
                }
                @Override
                public void onResponse(Response response) throws IOException {
                    String responseText = response.body().string();               
                    //Log.i(DataHolder.LOG, response.body().string()); //...
 ```
Does anybody else have this problem?

**Comment by serj-lotutovici** [comment]
When you call `Response#body().string()` you consume the `source`. See the documentation for [okio](https://github.com/square/okio) for more info.
