### ISSUE TITLE
[Feature request] Add a way to cancel all calls

### ISSUE THREAD

**Issue by JonasCz** [square/okhttp#2084]
It would be nice to have a way to cancel all calls, similar to how we can cancel a single call with `OkHttpClient.cancel(...)` method.

It would be very convenient to have a `cancelAll()` method in OkHttpClient, which would cancel all calls in progress, similar to what could be done by adding the same tag object to all calls / requests, and then doing `OkHttpClient.cancel(tag)` with this tag

**Comment by JakeWharton** [comment]
Fixed by https://github.com/square/okhttp/pull/2184

**Comment by JonasCz** [comment]
Awesome, thanks !
