### ISSUE TITLE
Make ResponseBody#source() not throw IOException?

### ISSUE THREAD

**Issue by JakeWharton** [square/okhttp#2093]
I think this can be done as I [explored it before][1]. The underlying data source is already open as we've read the headers, ideally the `source()` (which just imposes something like limit or decorates chunked/framed reading) is eagerly instantiated so that `source()` doesn't need to throw. This also makes `charStream()` and `byteStream()` not need to throw.

This becomes handy for try usage.
```java
Source source = body.source(); // <-- used to throw, needed to be split declaration and assignment
try {
  // Use the source.
} finally {
  source.close(); // Used to need null check.
}
```

 [1]: https://github.com/square/okhttp/pull/1767

**Comment by swankjesse** [comment]
Yes!

**Comment by swankjesse** [comment]
https://github.com/square/okhttp/pull/2105
