### ISSUE TITLE
Overwrite Content-Type

### ISSUE THREAD

**Issue by paul321** [square/okhttp#2099]
We got a server that only accepts Content-Type: application/json and not Content-Type: application/json; charset=utf-8;

OkHttp keeps generating application/json; charset=utf-8; when we do the following json post

MediaType type = MediaType.parse("application/json");
String json = "{\"APIRequests\"}";
            Request request = new Request.Builder()
                    .url(apiURL)
                    .post(RequestBody.create(type, json))
                    .build();
            Response response = client.newCall(request).execute();
            String html = response.body().string();

and returns an error. Is there any posibility to overwrite the content-type and not use the generated one from MediaType.parse?

Server it's a public one and i do have no control over it

**Comment by swankjesse** [comment]
First, fix your server.

Second, work around the problem by manually converting the string to UTF-8 bytes with getBytes() and use the byte[] to create the response body.

**Comment by paul321** [comment]
I said server it's not mine, so i need to send proper content-type

**Comment by swankjesse** [comment]
Got it. Please report a bug against the server.

**Comment by paul321** [comment]
Ok thank you

**Comment by zeluis9** [comment]
> First, fix your server.
> Got it. Please report a bug against the server.

We should have an option to disable/override this behavior. I'm sending custom `Content-Type` and `Accept` headers to the server (in my company) as a way to implement api versioning. This is currently messing with our endpoint calls.
Glad to help if you need.

**Comment by swankjesse** [comment]
The ResponseBody API that accepts a `String` is the one that’s opinionated about charsets on content types. If you want to do your own thing, just convert your string to bytes first and use that API.

**Comment by DefiantCatgirl** [comment]
The issue is old and closed, but I'll just point out that this was really unexpected when I set the Content-Type to the specific value the Layer API expects (a popular chat service for applications) and it got overwritten.

Though thankfully the OkHttp network interceptors exist and can override anything!

**Comment by swankjesse** [comment]
If this is troubling you, you don’t need to have OkHttp pick a charset for you. Just do this:

```
    String requestBody = ...
    Charset charset = ...
    byte[] bytes = requestBody.getBytes(charset);
    return RequestBody.create(contentType, bytes);
```

**Comment by Jotschi** [comment]
I'm faced with a similar issue when using okhttp in combination with Elasticsearch 6.1.2

The type `MediaType.parse("application/x-ndjson");` is rejected by the server due to the included encoding.  Is there an RFC which requires the encoding? The workaround by @swankjesse works fine.

**Comment by ShaimaaSabry** [comment]
I have the following code:
`
String xmlRequest = xmlMapper.writeValueAsString(updateLoginIdRequest);
byte[] bytes = xmlWithNamespace.getBytes(StandardCharsets.UTF_8);
RequestBody requestBody = RequestBody.create(bytes);

Request request = new Request.Builder()
        .url(urlBuilder.toString())
        .header("Content-Type", "application/x-wamupdateuserloginid+xml;version=1")
        .put(requestBody)
        .build();
`

The server is rejecting the request because the custom content type header is not correct. What am I doing wrong?
