### ISSUE TITLE
读取okhttp获取到inputstream,每次最多只能读取2048字节

### ISSUE THREAD

**Issue by huxq17** [square/okhttp#2117]
我在下载文件的时候用okhttp访问并得到了InputStream，在我读取这个inputstream的时候，发现每次最多只能读取2048字节，但是我用HttpURLConnection发现没有这个限制，心想应该是okhttp对返回的InputStream做了限制，所以想来请教解决办法，谢谢！

**Comment by huxq17** [comment]
@Override public int read(byte[] sink, int offset, int byteCount) {
    checkOffsetAndCount(sink.length, offset, byteCount);

    Segment s = head;
    if (s == null) return -1;
    ##// s.limit-s.pos<=2048???
    int toCopy = Math.min(byteCount, s.limit - s.pos);
    System.arraycopy(s.data, s.pos, sink, offset, toCopy);

    s.pos += toCopy;
    size -= toCopy;

    if (s.pos == s.limit) {
      head = s.pop();
      SegmentPool.recycle(s);
    }

    return toCopy;
  }

**Comment by huxq17** [comment]
s.limit-s.pos<=2048???

**Comment by swankjesse** [comment]
Failing Test case?

**Comment by huxq17** [comment]
I got InputStream by okhttp,and read it like this ,
```
 int allocated = freeMemory / 6 / threadNum;//给每个线程分配的内存
byte[] buffer = new byte[allocated];
len = inputStream .read(buffer);
```
allocated is always greater than 2048 or 8192,
and I find the threshold value is define in segment class
```
final class Segment {
  /** The size of all segments in bytes. */
  static final int SIZE = 8192;
...
```
how could I control the SIZE? anyone can help me,please!

**Comment by JakeWharton** [comment]
This value cannot be changed by user code. You need to follow normal InputStream reading practices of checking the return value for the number of characters read and looping until you've filled your buffer or the stream is exhausted.

**Comment by huxq17** [comment]
I'm doing the same as you say,but I want to improve download speed, and 2048 or 8192 limits the download speed.

**Comment by diegomontoya** [comment]
@huxq17 Just download the 2.6 source code + okio 1.6 and put into your app src tree and the modify the code to your liking.

**Comment by huxq17** [comment]
@diegomontoya I did what you said, but I prefer to okhttp Provides a method for developers to change the Size.![pic](http://img.my.csdn.net/uploads/201512/18/1450406851_6856.jpg)

**Comment by huxq17** [comment]
@JakeWharton

**Comment by JakeWharton** [comment]
It does not limit download speed in any meaningful way.

**Comment by huxq17** [comment]
@JakeWharton  Speak with the facts,I have done a related test.
I  download a 7.33 MB file 
My code:
···
 int size = 0;
            try {
                Class segmentClass = Class.forName("okio.Segment");
                Constructor constructor = segmentClass.getDeclaredConstructor();
                constructor.setAccessible(true);
                Segment segment=(Segment)constructor.newInstance();
                Field field = segmentClass.getDeclaredField("SIZE");
                field.setAccessible(true); 
                size = field.getInt(segment);
            } catch (Exception e) {
                e.printStackTrace();
            }
            LogUtils.i("download finshed! " + "size=" + size + " allocated=" + allocated + " and spendTime=" + (System.currentTimeMillis() - starttime));
···

When the SIZE equals 2048
1.
DownLoadTask.onRun(L:130): download finshed! size=2048 allocated=15706 and spendTime=13353
2.
DownLoadTask.onRun(L:130): download finshed! size=2048 allocated=15706 and spendTime=13880
3.
DownLoadTask.onRun(L:130): download finshed! size=2048 allocated=15706 and spendTime=14878

Average time is 14037

When the SIZE equals 8192
1.
DownLoadTask.onRun(L:130): download finshed! size=8192 allocated=15706 and spendTime=8118
2.
DownLoadTask.onRun(L:130): download finshed! size=8192 allocated=15706 and spendTime=9239
3.
DownLoadTask.onRun(L:130): download finshed! size=8192 allocated=15706 and spendTime=6343

Average time is 7900

When the SIZE equals 16384
1.
DownLoadTask.onRun(L:130): download finshed! size=16384 allocated=15706 and spendTime=2909
2.
DownLoadTask.onRun(L:130): download finshed! size=16384 allocated=15706 and spendTime=3302
3.
DownLoadTask.onRun(L:130): download finshed! size=16384 allocated=15706 and spendTime=2015

Average time is 2742

Obviously,increasing SIZE accelerate download speed,
and download speed has a relationship with the SIZE.

**Comment by swankjesse** [comment]
Mind sending a standalone benchmark? Either you’ve uncovered something very broken in Okio, or something is broken in your calling code.

Possibly this: https://github.com/square/okio/issues/171

**Comment by huxq17** [comment]
I resolve it by download the code source

**Comment by ouclbc** [comment]
@huxq17 ,excuse me,how did you resolve it?
