### ISSUE TITLE
how can change the ip of the mockWebServer?

### ISSUE THREAD

**Issue by guttentag** [square/okhttp#2120]
i'm testing an app that use external SDK which have okhttpclient.
i set mockWebServer and than set proxy to httpClient of the SDK using ```okHttpClient.setProxy(mockWebServer.toProxyAddress())```
and i set a dispatcher to simulate the server.
the ip of the mockWebServer is set to localhost (127.0.01), and this is working fine when testing on real device, but when i use emulator (genymotion),  i need to mockWebServer to have a specific ip adress.
i tried, but couldn't find a way to change the IP address, can someone please give me code example?
thanks

**Comment by swankjesse** [comment]
Call `start(InetAddress inetAddress, int port)` with the local IP address you'd like to listen on.

**Comment by emanzanoaxa** [comment]
Someone knows wich IP shoud be set on genymotion to run with mockWebServer?
