### ISSUE TITLE
Problem send redirect 301 with cookies

### ISSUE THREAD

**Issue by moisesvs** [square/okhttp#2125]
Hi! 

I have a service which return 301 (send redirect). This first call sets me 2 cookies that I must send to the second call (redirect) but OkHttp I doesn't put the cookies of the first call in the second call then fail.

My question is: With the framework apache works well but with OkHttp not. What  is I doing bad?

Is there a problem in the library? or I must do something more.

**Comment by swankjesse** [comment]
Are you configuring a cookie handler?

**Comment by moisesvs** [comment]
Hi!

No. I haven't configured a cookie handler. Need a cookie handler for this?

**Comment by swankjesse** [comment]
Yeah. Here's a quick guide.
http://stackoverflow.com/a/24267060/40013

We'll be improving the cookie situation in OkHttp3.
