### ISSUE TITLE
Ok http is setting unwanted headers in the request by default.

### ISSUE THREAD

**Issue by rajendersaini** [square/okhttp#2130]
I am using HttpURLConnection on android platform.which uses Okhttp internally. I am using delete method, typically delete method does not have the entity body. But I am finding that OkHttp is adding following parameter which I do not have intention to add. like

"content-type":"application/x-www-form-urlencoded"
"content-length":"0"
Is this bug in library why it is adding these header when I did not set these headers ?

**Comment by swankjesse** [comment]
These are the defaults specified by HttpURLConnection. No action for us to take on this.
