### ISSUE TITLE
failure : retrofit.RetrofitError: 307 Temporary Redirect

### ISSUE THREAD

**Issue by lotfi10** [square/okhttp#2131]
I have used retrofit for networking in my project in android.I have got this Error when I make a POST request:
failure : retrofit.RetrofitError: 307 Temporary Redirect

I add to line in gradle like that:

compile 'com.squareup.retrofit:retrofit:1.9.0'
compile 'com.squareup.okhttp:okhttp:2.4.0'

How to resolve it ? I need your Help

**Comment by JakeWharton** [comment]
[RFC 2616 states][1]:

> If the 307 status code is received in response to a request other than GET or HEAD, the user agent MUST NOT automatically redirect the request unless it can be confirmed by the user, since this might change the conditions under which the request was issued.

Issue #930 tracks our update to the clarifications of HTTP/1.1 in which [RFC 7231 states][2]:

> The user agent MAY use the Location field value for automatic redirection.

and

> This status code is similar to 302 (Found), except that it does not allow changing the request method from POST to GET.

So for now you need to implement this at the application level (which is hard with Retrofit 1, easier with the forthcoming Retrofit 2) or wait until OkHttp 3.1(ish) when we implement the newest spec.

 [1]: https://tools.ietf.org/html/rfc2616#section-10.3.8
 [2]: https://tools.ietf.org/html/rfc7231#section-6.4.7

**Comment by lotfi10** [comment]
Hi ,
Thank you for your repley.
So, I wait this update.

Regards

**Comment by hb-vijaypalod** [comment]
Hi, any update on how to solve this in retrofit 2.3.

> The user agent MAY use the Location field value for automatic redirection.

I can't get response object so as to get Location header and redirect manually. Can you please guide me on this.

**Comment by d-rahul** [comment]
I got the solution after a lot of efforts. May be this will help you. If you are getting this error **"203 HTTP 307 Temporary Redirect"** then this tricky will help you.

**Comment by LinHuanTanLy** [comment]
Through this method I solved the problem, but I still want to know why it is solved

**Comment by Licarey** [comment]
> I got the solution after a lot of efforts. May be this will help you. If you are getting this error **"203 HTTP 307 Temporary Redirect"** then this trick will help you. Append '/' to your web service at the end and then check this error goes away. I don't know the reason behind this but it works for me.
> For me, my old request web service was: https://mydomain/rest/Search. Using this URL I was getting "203 HTTP 307 Temporary Redirect" where I was able to get a response in POSTMAN and web browser.
> My new request web service with the trick: https://mydomain/rest/Search/. This "/" resolve the issue.

Very Good , Thank you for your answer. I solved the problem!
