### ISSUE TITLE
Consider building a big fancy fake clock infrastructure for OkHttp

### ISSUE THREAD

**Issue by swankjesse** [square/okhttp#2134]
At the moment tests flake because we want to put an upper bound on how long a given task will take, and sometimes the machines we get for free in Travis pause for 7 or 8 seconds.

We have the option of building a fake clock mechanism in OkHttp to make our tests less flaky, but that abstraction has a cost.

​Everything that calls `Object.wait()`, `Thread.sleep()`, `System.nanoTime()` would new operate through the fake clock mechanism:
- mockwebserver throttling
- connection pool sleeping
- discarding the end of a closed stream
- okio async timeouts

The most interesting part of this is definitely Okio . . .  at the moment we use both the socket’s native timeouts, and Okio’s application-layer timeouts. With this change we would need to be a bit clever to make sure native timeouts worked as they’re supposed to. Somehow.

​I think the real challenge is how to expose the fake clock so that it could be accessed by test cases, Okio, & OkHttp. Do application developers want access to such a thing when they’re writing their own code on top of Okio & OkHttp?

**Comment by JakeWharton** [comment]
Retrofit's `MockRetrofit` would want this, if exposed as a public API. And in our consuming Android app we already have this abstraction, and you know about our server one which seems _too_ fancy...

**Comment by swankjesse** [comment]
The TaskRunner being introduced in 4.3 addresses some of this.

**Comment by swankjesse** [comment]
Tracking as #5673.
