### ISSUE TITLE
Multipart should not add "Content-Length"

### ISSUE THREAD

**Issue by TanTan-TT** [square/okhttp#2138]
I found following request will cause server error
**The body of your POST request is not well-formed multipart/form-data**

```
--be1563be-4245-4ac5-8a95-498ba5b57ba8
content-disposition: form-data; name="name"
Content-Length: 22

ic_menu_white_24dp.png
...
--d4653e4a-9a5d-42e5-8a49-fcafbe9c673c
content-disposition: form-data; name="file"; filename="ic_menu_white_24dp.png"
Content-Type: image/png
Content-Length: 92
```

In [okhttp code](https://github.com/square/okhttp/blob/master/okhttp/src/main/java/okhttp3/MultipartBody.java#L160),

``` java
     long contentLength = body.contentLength();
      if (contentLength != -1) {
        sink.writeUtf8("Content-Length: ")
            .writeDecimalLong(contentLength)
            .write(CRLF);
      } else if (countBytes) {
        // We can't measure the body's size without the sizes of its components.
        byteCountBuffer.clear();
        return -1L;
      }
```

And I google the [rfc1867](https://www.ietf.org/rfc/rfc1867.txt), in the document, there is not description for adding "Content-Length", so maybe it is a bug for okhttp.

**Comment by JakeWharton** [comment]
Sounds like a server bug. Any number of headers are allowed in the part bodies so if the length isn't used it should simply be ignored or if it is used the number if accurate so the server is using it incorrectly.

**Comment by TanTan-TT** [comment]
@JakeWharton Are you sure for that? Because I did not found any content that content-length can be included in request in rfc1867

**Comment by JakeWharton** [comment]
It also does not forbid it. That RFC is just adds the 'form-data' subtype to the existing multipart type. The MIME RFC 1341 states:
> The only header fields that have defined meaning for body parts are those the names of which begin with "Content-". All other header fields are generally to be ignored in body parts.

So while it's redundant with the part boundaries, the server software should not crash either.

**Comment by st0rm23** [comment]
some oss provider will request strict format of multipart/form-data while the okhttp will fail to pass.
the temporary solution is copy an own MuiltipartBody from source code and change following code:
            if (contentLength != -1) {
                sink.writeUtf8("Content-Length: ")
                        .writeDecimalLong(contentLength)
                        .write(CRLF);
            } else if (countBytes) {
                // We can't measure the body's size without the sizes of its components.
                byteCountBuffer.clear();
                return -1L;
            }
to 
            if (contentLength != -1) {
            } else if (countBytes) {
                // We can't measure the body's size without the sizes of its components.
                byteCountBuffer.clear();
                return -1L;
            }

**Comment by JakeWharton** [comment]
Strict by whose definition? Per the RFC it's not forbidden and explicitly calls out that headers starting with "Content-" are allowed.

**Comment by st0rm23** [comment]
Sorry, maybe you are right. However, I think if we add something that the RFC not clearly defines, we'd better to create a option to turn it off. For example, it is not comfortable for most of people if we force to add a header named "Content-hello"

**Comment by JakeWharton** [comment]
I would agree, except Content-Length is widely known and used and offers
all kinds of advantages such as the ability to pre-size buffers when
reading individual parts.

**Comment by swankjesse** [comment]
No action for us to take here.

**Comment by bpappin** [comment]
There most definitely is action for the okhttp team to take here.
The content length breaks systems that stream content and don't know the length, because the server see a length of zero.

**Comment by dilroop** [comment]
for my case content-length is being calculated wrong .. ignoring \n character (was 79 but should have been 80 )

**Comment by JakeWharton** [comment]
File a bug with a test case or executable sample that reproduces the problem

**Comment by swankjesse** [comment]
FYI, We're dropping this bad behavior in 5.0.

**Comment by necrox87** [comment]
> Strict by whose definition? Per the RFC it's not forbidden and explicitly calls out that headers starting with "Content-" are allowed.

[4.8](https://datatracker.ietf.org/doc/html/rfc7578#section-4.8).  Other "Content-" Header Fields

   The multipart/form-data media type does not support any MIME header
   fields in parts other than Content-Type, Content-Disposition, and (in
   limited circumstances) Content-Transfer-Encoding.  Other header
   fields MUST NOT be included and MUST be ignored.
