### ISSUE TITLE
okhttp3.internal.Version class object not found

### ISSUE THREAD

**Issue by xiexiaodong** [square/okhttp#2142]
![image](https://cloud.githubusercontent.com/assets/5906306/11957965/d7c95092-a8ff-11e5-961a-bac774624aae.png)
internal package have no this Object

**Comment by swankjesse** [comment]
Try running `mvn package` first?

**Comment by xiexiaodong** [comment]
maven jar have this Object,but the master have no class object.

**Comment by JakeWharton** [comment]
It's generated by the build system automatically.

**Comment by xiexiaodong** [comment]
Got it，Thx

**Comment by ckx-ting** [comment]
@Yaccc How do you solve thid problem?

**Comment by Jawnnypoo** [comment]
@swankjesse Would you consider adding this to the `Building` section of the wiki? https://github.com/square/okhttp/wiki/Building
It may not be an obvious step for someone who is just starting out with Maven. I would make a PR and add it, but I don't think that can be done with wikis

**Comment by Jawnnypoo** [comment]
In case someone else runs into this, I needed to run `mvn compile` instead of `mvn package` to generate the Version class.

**Comment by sodino** [comment]
I run `mvn compile` and `mvn package` both,
but after `rebuild project` (IDEA),   the error `okhttp3.internal.Version class object not found` occured again!

how to fix it?

**Comment by yschimke** [comment]
@swankjesse @JakeWharton is there a reason why Intellij + maven isn't treating this as generated sources and knowing to build automatically?

**Comment by swankjesse** [comment]
Unsure. Reporting the issue to JetBrains can't hurt though!

**Comment by sodino** [comment]
and , if it's not IntelliJ IDEA, what is your IDE??

**Comment by yschimke** [comment]
I've seen it in Intellij on project setup.

**Comment by sodino** [comment]
Which IDE do you use?  @yschimke  thank you.
