### ISSUE TITLE
Body reading should fail with unique exception on cancel

### ISSUE THREAD

**Issue by Wavesonics** [square/okhttp#2145]
It would be great if we could differentiate a network failure IOException from a user canceled IOException.

Maybe we could subclass IOException with something like CanceledException and throw that. So if you are interested in the difference you can catch them separately.

Inside the Callback we don't even have access to the Call object to check and see if that was canceled. 

Is there some other way I'm missing to differentiate the case?

**Comment by JakeWharton** [comment]
You can check `call.isCanceled()` to know whether or not it was the result of cancelation.

**Comment by Wavesonics** [comment]
@JakeWharton so the pattern is to just pass the Call into your Callback object?

**Comment by JakeWharton** [comment]
Usually it's accessible by reaching to the surrounding scope.
```java
Call call = //...
call.enqueue(new Callback() {
  @Override public void onFailure(IOException e) {
    if (call.isCanceled()) return;
    //...
  }
  //...
});
```

**Comment by Wavesonics** [comment]
Ah, yeah I don't have these Callbacks as anonymous classes, that's fine
though, I passed the Call into my Callback and check it in the catch.
Thanks!
