### ISSUE TITLE
Maximum length (in bytes) on response header?

### ISSUE THREAD

**Issue by devflow** [square/okhttp#2152]
a row and whole..

**Comment by swankjesse** [comment]
No limits are enforced. If you want to work with most webservers and load balancers, I personally recommend no more than 1024 bytes per header, and no more than 16 KiB total.

**Comment by swankjesse** [comment]
See also: http://stackoverflow.com/questions/686217/maximum-on-http-header-values

**Comment by yschimke** [comment]
Example Bad Server that causes thread lockup https://github.com/yschimke/okhttp/commit/b29f8e68ce412bca39b63a9aff02f0ecbe6e82c4
