### ISSUE TITLE
Custom SNI value (peer hostname) being overwritten by Platform.configureTlsExtensions

### ISSUE THREAD

**Issue by dustin-graham** [square/okhttp#2153]
We have, I think, a unique requirement that the SNI value sent in the client hello be a custom value not matching the hostname on the request. We find the address through internal means and connect directly with the server and the server needs the SNI value to connect the client to the appropriate service. So the hostname we are using for the request in this case is an invalid SNI value on our server. 

So far I have a custom SSLSocketFactory implementation that internally uses SSLCertificateSocketFactory to create the sockets and set the SNI to the value we need. Once the SSLSocket is created, however, Connection hands it off to Platform.configureTlsExtensions which overrides the SNI value that I set:
```
// Enable SNI and session tickets.
if (hostname != null) {
  setUseSessionTickets.invokeOptionalWithoutCheckedException(sslSocket, true);
  // this overrides the SNI value I set on the SSLSocket
  setHostname.invokeOptionalWithoutCheckedException(sslSocket, hostname);
}
```

I'd like to find out before I start hacking my way to a solution whether there is some configuration or built-in strategy I can employ to get OkHttp to do what I want here. Thanks!

**Comment by swankjesse** [comment]
The closest we can come is using your SNI value in the URL’s hostname, and then customizing `Dns` to resolve that to the actual hostname.

You probably want to fix your design. Whatever your reasons are for cheating SNI, you should probably stop. It is going to be a continued source of pain, and it isn’t HTTP.

**Comment by dustin-graham** [comment]
@swankjesse Thanks for the quick reply. We're definitely aware of the challenges but the design is intentional and born from very unique requirements. It works great in all our cases except for developing Android and iOS clients to work with it! :(  Thanks for the Dns tip. I wasn't aware it could be configured inside OkHttp. 

Cheers!
