### ISSUE TITLE
HttpLoggingInterceptor is not logging response body for some reason

### ISSUE THREAD

**Issue by akobylianskyi** [square/okhttp#2154]
I have OkHttpClient with HttpLoggingInterceptor from Square. I create "GET" request that return json but for some reason the response body is not logged and the result for the response body is only "}". All other stuff as header, content-type, etc is present in the console.

HttpLoggHttpLoggingInterceptor interceptor = new HttpLoggingInterceptor();
interceptor.setLevel(HttpLoggingInterceptor.Level.BODY);
mHttpClient.interceptors().add(interceptor);

The problem should be in that string:
logger.log(buffer.clone().readString(charset));

--> END GET
<-- HTTP/1.1 200 OK (420ms)
Cache-Control: no-cache
Pragma: no-cache
Content-Type: application/json; odata.metadata=minimal; odata.streaming=true
Expires: -1
Server: Microsoft-IIS/8.5
OData-Version: 4.0
X-AspNet-Version: 4.0.30319
X-Powered-By: ASP.NET
Date: Thu, 24 Dec 2015 17:51:42 GMT
Content-Length: 2291
OkHttp-Sent-Millis: 1450979490431
OkHttp-Received-Millis: 1450979490851
}

**Comment by swankjesse** [comment]
Could you provide an executable test case demonstrating the problem? We’ve got examples in HttpLoggingInterceptorTest to get you started.
