### ISSUE TITLE
Twitter Search API's response json parse exception......

### ISSUE THREAD

**Issue by JackyYuanOne** [square/okhttp#2157]
I request this url("https://api.twitter.com/1.1/search/tweets.json?q=android&lang=zh&count=5" this request need twitter's oauth),Twitter's response is a large amount of json's data .When i parse these json not using Gson,it throws exception like this "org.json.JSONException: End of input at character 0 of ....".
But while i use Java's origin HttpURLConnection,it works without no exception.Is that OkHttp can't deal with a large amount data ?

**Comment by swankjesse** [comment]
Have you consumed the response body 2x? You can only read it once.

**Comment by JackyYuanOne** [comment]
I wil try.
