### ISSUE TITLE
com.squareup.okhttp.ConnectionPool pruneAndGetAllocationCount

### ISSUE THREAD

**Issue by leelit** [square/okhttp#2158]
when i ran my unit test, which contains a lot of, may be more than 10, requests, it came out a warning "A connection to http://localhost:8080/ was leaked. Did you forget to close a response body?"

why did this warning come out?
how to solve it?

**Comment by JakeWharton** [comment]
Are you closing the response body of all requests made in the test?

**Comment by leelit** [comment]
the sample [https://github.com/square/okhttp/wiki/Recipes](https://github.com/square/okhttp/wiki/Recipes) doesn't close response body neither.

normally i won't sumit so many requests at the same time, do i need to close response body all the time? just a little confused...

**Comment by JakeWharton** [comment]
Which sample? Most call `body().string()` which closes it for you.

**Comment by leelit** [comment]
you mean if i call `body().string()`, no need to call `body().close()`, other situation it needs ?

after i call close for all response body except `body().string()`, no more warning.

**Comment by JakeWharton** [comment]
Correct. We will document which methods on `ResponseBody` automatically close it.

**Comment by kelmer44** [comment]
If I use `body().byteStream() `do I need to close the connection explicitly as well?

**Comment by dave-r12** [comment]
Yes, per the javadoc, you'll need to close the body. Only bytes() and string() close it automatically. See https://github.com/square/okhttp/blob/master/okhttp/src/main/java/okhttp3/ResponseBody.java#L37

**Comment by kelmer44** [comment]
Just tried it but it seems if I close the stream after calling byteStream() I will then get an exception on processing the stream since it has already been closed.

**Comment by JerryLai8080** [comment]
I was confused ,,I got the warning when i used Retrofit ,,, I didn't have to do anything with the response body,how can I solve this ,,

I do have a custom interceptor ,, is it because of this ?

**Comment by shashidhar34** [comment]
I also have the same problem using Retrofit when there are 2 concurrent http requests are under process. what could go wrong? I do have interceptors.
