### ISSUE TITLE
can not open right image

### ISSUE THREAD

**Issue by LiuDeng** [square/okhttp#2161]
i use fresco and okhttp to load images :+1: 
Request requestWithUserAgent = originalRequest.newBuilder()
                        .header("User-Agent", "Mozilla/5.0 (iPhone; CPU iPhone OS 7_0 like Mac OS X; en-us) AppleWebKit/537.51.1 (KHTML, like Gecko) Version/7.0 Mobile/11A465 Safari/9537.5")
                        .addHeader("Referer",getDomainName(requestUrl)).addHeader("Referer", requestUrl)
                        .header("Host",getDomainName(requestUrl))
                        .header("Connection","keep-alive")
                        .header("Accept","text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8")
                        .header("Accept-Encoding","gzip, deflate, sdch")
                        .header("Accept-Language","zh-CN,zh;q=0.8")
                        .header("Upgrade-Insecure-Requests","1")
                        .header("Cache-Control","max-age=0")
                        .build();

while chrome can open this image "http://inews.gtimg.com/newsapp_bt/0/44453408/1000" but my app can not load it? other image is ok just this one.

Thank you for any help
Best wishes~

**Comment by swankjesse** [comment]
Please try your question on stackoverflow. This tracker is for feature requests & bug reports only.
