### ISSUE TITLE
SocketTimeout exception

### ISSUE THREAD

**Issue by alexey0306** [square/okhttp#2166]
Hi, I have a problem

We're using Evernote Android API, which in turn is using OKHttp client for managing HTTP requests/responses. 

Recently we've faced a problem with uploading big files (> 5-6 Mb). Every time we try to upload the note with attached file we receive SocketTimeoutException:  
java.io.InterruptedIOException: timeout (java.net.SocketException: Socket is closed)

After checking the stacktrace I've found that OKHttp client can be the root cause of this issue. 
In the attach you can find the Exception details

[Exception.txt](https://github.com/square/okhttp/files/73202/Exception.txt)

**Comment by swankjesse** [comment]
Could you provide us with a test case to demonstrate the problem? There are many timeout tests in the test suite to get you started.

**Comment by alexey0306** [comment]
Hi,
Thanks for response

Here is the test case (you need to download Evernote Android SDK from https://github.com/evernote/evernote-sdk-android and authenticate to Evernote to make it work)

1. Initialize the note
Note note = new Note();

2. Set title and notebook GUID
note.setTitle("Some title");
note.setNotebookGuid(notebookGUID);

3. Create Resources (file)
byte[] fileData = <function_that_is_used_to_read_file_data_in_byte_array>
Data data = new Data();
data.setBody(fileData);
data.setBodyHash(MessageDigest.getInstance("MD5").digest(data.getBody()));
data.setSize(fileData.length);

List<Resource> resources = new ArrayList<Resource>();
Resource resource = new Resource();
resource.setData(data);
resource.setMime("application/pdf");
resources.add(resource);

4. Attaching resource to note
note.setResources(resources);
note.setContent("test file");

5. Creating note
EvernoteSession.getInstance().getEvernoteClientFactory().getNoteStoreClient().createNoteAsync(note, new EvernoteCallback<Note>() {
                @Override
                public void onSuccess(Note result) {
                }

                @Override
                public void onException(Exception exception) {
                    // Handle the exception
                }
            });

So, every time I am trying to upload file more thatn 5-6 Mb, i get SocketTimeoutException (stacktrace attached earlier)

Thanks in advance and best regards, 
Alexey

P.S: In Evernote Android SDK git repository you can find the examples, how to authenticate and create notes with files attached

**Comment by swankjesse** [comment]
Could you please isolate this into a standalone test case? See `CallTest.java` for examples. If I fix your bug, I can’t exactly check in the evernote SDK to prevent regressions!
