### ISSUE TITLE
CacheControl.Builder support for define cache as public or private

### ISSUE THREAD

**Issue by tprochazka** [square/okhttp#2170]
Now is not possible to build cache header like this
Cache-Control: public, max-age=...
by the CacheControl.Builder 
Why builder automatically set isPrivate and isPublic to false?

**Comment by swankjesse** [comment]
Although the `Cache-Control` header can be used in requests and responses, OkHttp’s Cache.Control.Builder only offers APIs to build _request_ `Cache-Control` headers. And `public` and `private` aren’t used in Cache-Control request headers.

What’s your use case?
