### ISSUE TITLE
Accessor methods on HttpUrl.Builder

### ISSUE THREAD

**Issue by JakeWharton** [square/okhttp#2171]
Enough to fulfill Retrofit's need of doing path replacement with proper encoding on an instance.

**Comment by swankjesse** [comment]
After further investigation it looks like it’s difficult to get an API that works the way Retrofit wants. In particular a path like `@Get("/{foo}{bar}")` might be problematic if `foo` is encoded already and `bar` is not. That sends us down the ugly road of offering one-off encoding and decoding methods, which I’m not eager to do.

No action to take at this time.
