### ISSUE TITLE
Emoji expression parameters passed by way of exception occurs FormEncodingBuilder

### ISSUE THREAD

**Issue by yushilong** [square/okhttp#2172]
FormEncodingBuilder builder = new FormEncodingBuilder();
                builder.add("frontPic", imgPath);
                builder.add("title", title);
                builder.add("content", text);
Which contain emoji expression title!!!

java.lang.IllegalArgumentException: Unexpected code point: de0a
	at a.e.a(Buffer.java:885)
	at com.squareup.okhttp.HttpUrl.canonicalize(HttpUrl.java:1592)
	at com.squareup.okhttp.FormEncodingBuilder.add(FormEncodingBuilder.java:38)

**Comment by swankjesse** [comment]
Could you provide an executable test case demonstrating the problem? There’s plenty of examples to get started here:
`okhttp-tests/src/test/java/okhttp3/FormBodyTest.java`
