### ISSUE TITLE
Network status changed, okhttp return wrong result

### ISSUE THREAD

**Issue by LyndonDing** [square/okhttp#2175]
When the network is not available(turn off wifi), Using okhttp client request server data, the client callback onFailure().but when the network is available(turn on wifi), Using okhttp client request server data again, the client callback onResponse() immediately, and the "Response.body().string()" is empty.

**Comment by LyndonDing** [comment]
for more info http://stackoverflow.com/questions/34522955/okhttp-return-wrong-result-when-network-status-changed

**Comment by swankjesse** [comment]
Please provide an executable test case. CallTest.java has plenty of examples.
