### ISSUE TITLE
Feature Request: set deadline to okio

### ISSUE THREAD

**Issue by danvinokour** [square/okhttp#2191]
Hi,

There is no elegant way to set timeout to the whole process of the request.
ReadTimeout affects only until data is ready to be read and is passed to okio as timeout which as i understand effects is timeout between each byte being read.
It would be great if i could set a timeout to the whole request process which probably means that okio's deadline is  a good parameter to play with.

**Comment by ericcj** [comment]
this would be great

**Comment by swankjesse** [comment]
Duplicates https://github.com/square/okhttp/issues/2840
