### ISSUE TITLE
HttpLoggingInterceptor reports -1-byte body when set to Level.BASIC and response is chunked

### ISSUE THREAD

**Issue by austynmahoney** [square/okhttp#2194]
The body length of the responses printed by HttpLoggingInterceptor all report `-1-byte body` when set to `Level.BASIC` and the response is `chunked`. They are reported correctly when the logging level is set to `Level.BODY`.

Example:
`HTTP/1.1 200 OK (133ms, -1-byte body)`

**Comment by JakeWharton** [comment]
Can you write a test case? The current ones do not exhibit this behavior: https://github.com/square/okhttp/blob/20653ad0e17b693cad5b0be3d48404fca0a95d88/okhttp-logging-interceptor/src/test/java/okhttp3/logging/HttpLoggingInterceptorTest.java#L109-L161

**Comment by austynmahoney** [comment]
@JakeWharton I noticed the same thing when I ran the tests. The problem occurs when the response is chunked.

Test here, let me know if you want a PR for it.

https://github.com/austynmahoney/okhttp/commit/028f1f01df2caf50325c808576024d1c4350b8dc

**Comment by JakeWharton** [comment]
Got it. Thanks! PR sent.
