### ISSUE TITLE
okHttpClient.interceptors() not returning a modifiable list

### ISSUE THREAD

**Issue by juliomarcos** [square/okhttp#2196]
http://square.github.io/okhttp/3.x/okhttp/okhttp3/OkHttpClient.html#interceptors-- should return a modifiable list according to documentation 

> Returns a modifiable list of interceptors that observe the full span of each call: from before the connection is established (if any) until after the response source is selected (either the origin server, cache, or both).

but it is returning an unmodifiable one.

I'm using version 3.0.0-RC1

**Comment by JakeWharton** [comment]
`OkHttpClient` is now immutable. The mutable list is available on `OkHttpClient.Builder` but not `OkHttpClient`. We'll have to update the documentation. Thanks for pointing it out.

**Comment by juliomarcos** [comment]
I've started using the builder thinking it was just another way to do it. So, that's the case.
Thank you!
