### ISSUE TITLE
Leak in Gson-streaming recipe example

### ISSUE THREAD

**Issue by gborland** [square/okhttp#2199]
It looks like the `Reader` is not closed in the [Gson streaming example](https://github.com/square/okhttp/wiki/Recipes#parse-a-json-response-with-gson).

```java
Gist gist = gson.fromJson(response.body().charStream(), Gist.class);
```

Suggested fix:
```java
try (final Reader json = response.body().charStream()) {
    Gist gist = gson.fromJson(json, Gist.class);
}
```

**Comment by swankjesse** [comment]
Thanks @dave-r12! https://github.com/square/okhttp/pull/2253
