### ISSUE TITLE
`JavaNetCookieJar` parses cookies incorrectly

### ISSUE THREAD

**Issue by floating-cat** [square/okhttp#2202]
After debugged several times I found:
https://github.com/square/okhttp/blob/7f4ce6fdd75d142819d612196dd45aff0795d682/okhttp-urlconnection/src/main/java/okhttp3/JavaNetCookieJar.java#L87
```
/**
 * Convert a request header to OkHttp's cookies via {@link HttpCookie}. That extra step handles
 * multiple cookies in a single request header, which {@link Cookie#parse} doesn't support.
 */
private List<Cookie> decodeHeaderAsJavaNetCookies(HttpUrl url, String header) {
   List<HttpCookie> javaNetCookies;
  try {
    javaNetCookies = HttpCookie.parse(header);
...
```
misuses [`HttpCookie.parse(String)`](http://developer.android.com/reference/java/net/HttpCookie.html#parse(java.lang.String)).
```
public static List<HttpCookie> parse (String header)

Constructs a cookie from a string. The string should comply with set-cookie
or set-cookie2 header format as specified in RFC 2965. Since set-cookies2
syntax allows more than one cookie definitions in one header, the returned
object is a list.
```

Current the header string was composed of several cookies which can't be parse with `HttpCookie.parse(String)`.
`decodeHeaderAsJavaNetCookies(HttpUrl, String)`'s doc comment details the same thing.

Edit: details more about this issue.

**Comment by floating-cat** [comment]
`HttpCookie.parse(String)` only return a `List` with one item if the header is *set-cookie* or a `List` with more items if the header is *set-cookie2*.

**Comment by floating-cat** [comment]
Also see https://android.googlesource.com/platform/libcore/+/f7ab2bc37debba91864bfec6572a3e7bbe994c58/luni/src/main/java/java/net/CookieManager.java#144
```
return Collections.singletonMap("Cookie", Collections.singletonList(result.toString()));
```

**Comment by swankjesse** [comment]
I’ve added a test that tries to reproduce the problem, but doesn’t. Could you send a test that does?
https://github.com/square/okhttp/pull/2207/files
