### ISSUE TITLE
Exception when call com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponseCode()

### ISSUE THREAD

**Issue by LiHanGuang** [square/okhttp#2203]
Hello:

Is a bug?  or Normal? thanks.

https://code.google.com/p/android/issues/detail?id=198285&can=1&q=com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponse&colspec=ID%20Status%20Priority%20Owner%20Summary%20Stars%20Reporter%20Opened

**Comment by JakeWharton** [comment]
That exception is thrown when the timeout is reached and no response has been read. If you think there is a bug with OkHttp specifically please provide a test case or sample code which uses OkHttp's APIs directly. Otherwise the bug is in the right place for Android's API.

**Comment by LiHanGuang** [comment]
@JakeWharton 
Thanks.
