### ISSUE TITLE
Cancelling async request by tag

### ISSUE THREAD

**Issue by AlexLardschneider** [square/okhttp#2205]
Hi,
it seems like there is no way to cancel a async request by using *okHttpClient.cancel(tag)* in okhttp3.
Is this intended behaviour? If yes, is there a replacement method to cancel calls by tag?

**Comment by swankjesse** [comment]
@AlexLardschneider yes, the replacement is that you need to copy&paste this example into your program:

```  
  public void cancel(OkHttpClient client, Object tag) {
    for (Call call : client.dispatcher().queuedCalls()) {
      if (tag.equals(call.request().tag())) call.cancel();
    }
    for (Call call : client.dispatcher().runningCalls()) {
      if (tag.equals(call.request().tag())) call.cancel();
    }
  }
```

**Comment by burntapples** [comment]
client.dispatcher() has private access as well as .queuedCalls() ...
