### ISSUE TITLE
Unexpected connection leak message in 3.0.0-RC1

### ISSUE THREAD

**Issue by omarkilani** [square/okhttp#2217]
I'm using the published 3.0.0-RC1.

I'm seeing this message:

```
WARNING: A connection to https://api.push.apple.com/ was leaked. Did you forget to close a response body?
Jan 08, 2016 8:23:58 PM okhttp3.ConnectionPool pruneAndGetAllocationCount
```

Over and over.

My code looks like this:

```scala
    client.newCall(request).enqueue(new Callback() {
      override def onFailure(request: Request, throwable: IOException) {
      }

      override def onResponse(response: Response) {
        if (!response.isSuccessful()) {
          val body = response.body()
          val charStream = body.charStream()
          val reason = GSON.fromJson(charStream, classOf[APNSError])
          body.close()
        }
      }
    })
```

(Note that the example Gson recipe leaks the body there, but this doesn't.)

Do I need to close the body in the successful case even if I'm not reading it?

Thanks!

**Comment by JakeWharton** [comment]
> Do I need to close the body in the successful case even if I'm not reading it?

Yes!

**Comment by omarkilani** [comment]
Alright -- I think the docs could be clearer here. :)

None of these https://github.com/square/okhttp/wiki/Recipes call close.

**Comment by swankjesse** [comment]
Yeah, we gotta fix that.

**Comment by mtinnes** [comment]
Is body() guaranteed to be not null? Or is it best practice to check before close?

**Comment by swankjesse** [comment]
Body is never null and must always be closed.

**Comment by swankjesse** [comment]
https://github.com/square/okhttp/pull/2572

**Comment by luiszacheu** [comment]
@JakeWharton I'm using Retrofit2 + okhttp3 in a java application fx, but I'm with the sample Which problem? Most call body (). String () Which closes it for you.
In my project I have a ServiceCreator class to create the retrofit coneções and okhttp, but the call I am not able to make a close in the body, following the examples:

`public class ServiceGenerator {

	public static OkHttpClient.Builder httpClient;


    public static Retrofit createRetrofit(String token) {

        if (httpClient == null){
            httpClient = new OkHttpClient.Builder();
            if (token != null){
                httpClient.addInterceptor(new Interceptor() {
                    @Override
                    public okhttp3.Response intercept(Interceptor.Chain chain) throws IOException {
                        Request original = chain.request();

                        Request.Builder requestBuilder = original.newBuilder()
                                .header("Authorization", "Token token=" + token)
                                .method(original.method(), original.body());


                        Request request = requestBuilder.build();

                        return chain.proceed(request);
                    }
                });
            }
            httpClient.connectTimeout(50, TimeUnit.SECONDS);
            httpClient.addInterceptor(addLoggin());
            


        }

        OkHttpClient client = httpClient.build();
        Retrofit retrofit = new Retrofit.Builder().baseUrl(Constant.BASEURL)
                .addConverterFactory(ScalarsConverterFactory.create())
                .addConverterFactory(GsonConverterFactory.create(new GsonBuilder()
                        .excludeFieldsWithModifiers(Modifier.FINAL, Modifier.TRANSIENT, Modifier.STATIC).create())).client(client).build();


        return retrofit;
    }

    public static <S> S createService(String token, Class<S> serviceClass) {
        return createRetrofit(token).create(serviceClass);
    }


    private static HttpLoggingInterceptor addLoggin(){

        HttpLoggingInterceptor logging = new HttpLoggingInterceptor();

        logging.setLevel(HttpLoggingInterceptor.Level.NONE);
        return logging;
    }

}`

Usage into a ScheduleServe to polling:

`CatalogListener catalogListener = ServiceGenerator.createService(token, CatalogListener.class);

		Call<List<Category>> call = catalogListener.syncMerchantId(merchantId);

		call.enqueue(new Callback<List<Category>>() {

			@Override
			public void onResponse(Call<List<Category>> call, retrofit2.Response<List<Category>> response) {
//				System.out.println(response.body());
				cb.onResponse(response.body());
			}
			
			@Override
			public void onFailure(Call<List<Category>> call, Throwable t) {
				System.out.println(t);
				cb.onFailure(t);
			}
		});`

**Comment by VKostenc** [comment]
Hello @luiszacheu. I receive same code structure as you wrote higher. 
And now my task to fix same issue as you got.
Do you found solution?

```
CatalogListener catalogListener = ServiceGenerator.createService(token, CatalogListener.class);
public static <S> S createService(String token, Class<S> serviceClass) {
    return createRetrofit(token).create(serviceClass);
}
````

**Comment by lawloretienne** [comment]
Instead of having a Retrofit Service interface which returns Call<UserDefinedObject> mine returns Observable<UserDefinedObject>.  I am using RxJava and calling observable.subscribe().  Where would be the correct place to close the response body?

**Comment by JakeWharton** [comment]
Retrofit closes it for you
