### ISSUE TITLE
java.lang.UnsupportedOperationException while adding interceptor

### ISSUE THREAD

**Issue by outofdate** [square/okhttp#2219]
3.0.0-RC1
This chunk of code is throwing exception. 
So i found it out when migrating to okhttp3. 

``` java
 client.interceptors().add(new Interceptor() {
            @Override
            public okhttp3.Response intercept(Chain chain) throws IOException {
                Request request = chain.request();
                Request.Builder requestBuilder = request.newBuilder()
                        .addHeader("Authorization", authPrefs.getString(Properties.ApiProperties.TOKEN, "null"))
                        .method(request.method(), request.body());

                request = requestBuilder.build();
                return chain.proceed(request);
            }
        });
```
Version 2.7.0 works fine for me.

**Comment by artem-zinnatullin** [comment]
This part of OkHttp is now immutable, please use OkHttpClient.Builder and
add interceptor when you create OkHttpClient instance.

Something like this:

new OkHttpClient.Builder().addInterceptor(...).build()

On Sat, Jan 9, 2016, 14:19 outofdate <notifications@github.com> wrote:

> 300-RC1
> This chunk of code is throwing exception
> So i found it out when migrating to okhttp3
>
>  clientinterceptors()add(new Interceptor() {
>             @Override
>             public okhttp3Response intercept(Chain chain) throws IOException {
>                 Request request = chainrequest();
>                 RequestBuilder requestBuilder = requestnewBuilder()
>                         addHeader("Authorization", authPrefsgetString(PropertiesApiPropertiesTOKEN, "null"))
>                         method(requestmethod(), requestbody());
>
>                 request = requestBuilderbuild();
>                 return chainproceed(request);
>             }
>         });
>
> Version 270 works fine for me
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/square/okhttp/issues/2219>.
>
-- 

@artem_zin
