### ISSUE TITLE
MockResponse clas doesn't set the right status string when setStatusCode() is called with non 200 status code

### ISSUE THREAD

**Issue by rakeshcusat** [square/okhttp#2222]
MockResponse class doesn't set the right status string when setStatusCode() is called with non 200 status code

example: 
```
responded: HTTP/1.1 401 OK
```
Ideally the status code should be set as following.
expected:
```
responded: HTTP/1.1 401 UNAUTHORIZED
```
Here is the [implementation of the method](https://github.com/square/okhttp/blob/c9080f14f37f8d85d1c6da648e843a70ee474436/mockwebserver/src/main/java/okhttp3/mockwebserver/MockResponse.java#L71) which should change.

```
  public MockResponse setResponseCode(int code) {
    return setStatus("HTTP/1.1 " + code + " OK");
  }
```

**Comment by JakeWharton** [comment]
Why don't we just change it from "OK" to "MockResponse" instead? The reason
phrase has no value except to humans so it's value will have no effect on
consuming clients.

If you need a custom reason you can use setStatusLine().

**Comment by rakeshcusat** [comment]
right, but it is better to put "MockResponse" which can indicate that it is mock and ignore this value completely.
