### ISSUE TITLE
onFailure How to identify different situations

### ISSUE THREAD

**Issue by xushaun** [square/okhttp#2223]
when net is show or server is close ，Call sometimes returns in method onFailure，When i call mOkHttpClient.cancel， Call returns mOkHttpClient.cancel too，so How  can i dentify different situations,Because i will show toast when the call is canceled by user

**Comment by swankjesse** [comment]
Keep a reference to the `Call` and use `isCanceled()`.

**Comment by xushaun** [comment]
I see source of Okhttp,I decide to do like below;
@Override
	public void onFailure(Request request, IOException e) {
		// TODO Auto-generated method stub
		if(e != null && e.getMessage().equals("Canceled"))
			//do something
               ..........
}
