### ISSUE TITLE
Let Cookie.java implement serializable

### ISSUE THREAD

**Issue by mightyhaav** [square/okhttp#2229]
I'd like to create my own cookiejar that should be persistent. Could you please let Cookie.java implement serializable?

**Comment by swankjesse** [comment]
Of all of the ways to marshal days to & from bytes, serializable is among the very worst. Would you consider JSON ?

**Comment by swankjesse** [comment]
Or maybe, just use the toString method and serialize that?

**Comment by mightyhaav** [comment]
I tried toString() but it doesn't work because your implementation omits the domain name if the cookie is host only. I don't see any advantages in converting the cookie to JSON just to store it in the file system. I've got some maps to handle the cookies and I'd like to persist those maps. That would be a single line of code if Cookie would support Serializable.

**Comment by swankjesse** [comment]
You probably want to store additional data, like the cookies created at date, to help with eviction. Imagine a PersistedCookie class.
