### ISSUE TITLE
403 Forbidden, TLS with Amazon, x-amzn-ErrorType: ForbiddenException

### ISSUE THREAD

**Issue by kamilwlf** [square/okhttp#2231]
I use:
'com.squareup.okhttp3:okhttp:3.0.0-RC1'

my code:
okClient.setConnectionSpecs(Collections.singletonList(ConnectionSpec.MODERN_TLS));

Log:
 <-- HTTP/1.1 403 Forbidden (267ms)
 Content-Type: application/json
Content-Length: 23
Connection: keep-alive
x-amzn-ErrorType: ForbiddenException

With HttpURLConnection and from browser works properly

Protocols enabled:
TLS1.2
TLS1.1
TLS1.0
SSLv3
Protocols not enabled:
SSLv2

Cipher suites enabled:
TLS_RSA_WITH_3DES_EDE_CBC_SHA (0x000A)
TLS_RSA_WITH_AES_128_CBC_SHA (0x002F)
TLS_RSA_WITH_AES_256_CBC_SHA (0x0035)
TLS_RSA_WITH_AES_128_CBC_SHA256 (0x003C)
TLS_RSA_WITH_AES_128_GCM_SHA256 (0x009C)
TLS_RSA_WITH_AES_256_GCM_SHA384 (0x009D)
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA (0xC013)
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA (0xC014)
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256 (0xC027)
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384 (0xC028)
TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 (0xC02F)
TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 (0xC030)

**Comment by swankjesse** [comment]
Interesting! It's likely your request is different somehow between the two HTTP clients. Maybe use the logging interceptor & see what's different?

**Comment by swankjesse** [comment]
No clear action for us to take here.

**Comment by kamilwlf** [comment]
I do not remember what I did but it was not the fault of the library
