### ISSUE TITLE
Open file descriptors in cache

### ISSUE THREAD

**Issue by krisskross** [square/okhttp#2232]
We noticed that file descriptors may get exhausted if the ```Response.body().source()``` is never closed for cached requests. Cached as in setting ```OkHttpClient.setCache()```, that is.

Not sure if this is intended or not but it was a bit surprising since the documentation doesn't mention it? Also, the body doesn't seem to require closing in the same way if the response wasn't cached?

**Comment by JakeWharton** [comment]
Not closing an uncached body will leak a connection in the pool and log a warning. Closing is _always_ required when you receive a `Response` object.
