### ISSUE TITLE
Response protocol is not returning HTTP 2 for http 2 endpoint

### ISSUE THREAD

**Issue by lexer** [square/okhttp#2236]
```java
public class Http2Test {

    @Test
    public void isHttp2Transport() throws IOException {
        HttpLoggingInterceptor loggingInterceptor = new HttpLoggingInterceptor();
        loggingInterceptor.setLevel(HttpLoggingInterceptor.Level.BODY);

        OkHttpClient okHttpClient = new OkHttpClient.Builder()
                .addInterceptor(loggingInterceptor)
                .build();

        Request request = new Request.Builder()
                .url("http://twitter.com")
                .build();

        Response response = okHttpClient.newCall(request).execute();

        Protocol protocol = response.protocol();

        assertEquals(Protocol.HTTP_2, protocol);
    }
}
```

junit.framework.AssertionFailedError: 
Expected :h2
Actual   :http/1.1

**Comment by JakeWharton** [comment]
Do you have the ALPN jars added to your classpath? Or are you running the
test on Android 5+?

**Comment by lexer** [comment]
@JakeWharton Im running this as pure junit test. But I run into the issue when I was debugging Android requests on Android+ device.

**Comment by lexer** [comment]
@JakeWharton ok this pure unit test is not correct I guess. I will try to rewrite it Android test and rerun

**Comment by lexer** [comment]
@JakeWharton I was probably wrong. When I run my test as Android Instrumentation it succeeded. Will do more research.

**Comment by lexer** [comment]
Cool I think HTTP 2 protocol is set correctly for response.

I think something is probably wrong with how HttpLoggingInterceptor log things.

In all my tests: https://github.com/square/okhttp/blob/master/okhttp-logging-interceptor/src/main/java/okhttp3/logging/HttpLoggingInterceptor.java#L151

connection is always null.

```
01-14 17:16:06.100 18812-18838/com.github.lexer.http2test D/OkHttp: --> GET https://twitter.com/ HTTP/1.1
01-14 17:16:06.721 18812-18838/com.github.lexer.http2test D/OkHttp: <-- 200  https://twitter.com/ (620ms, -1-byte body)
01-14 17:16:06.722 18812-18838/com.github.lexer.http2test D/OkHttp: --> GET https://twitter.com/download HTTP/1.1
01-14 17:16:06.768 18812-18838/com.github.lexer.http2test D/OkHttp: <-- 200  https://twitter.com/download (45ms, -1-byte body)
```

**Comment by lexer** [comment]
@JakeWharton I will close this story and will open separate ticket for http logger.

**Comment by lexer** [comment]
#2247 Response protocol is correct. This issue is invalid. Protocol is not correctly logged by HttpLoggingInterceptor.
