### ISSUE TITLE
java.util.NoSuchElementException

### ISSUE THREAD

**Issue by EngrZhou** [square/okhttp#2237]
~~**version:2.4.0**~~
**version:2.7.0**

java.util.NoSuchElementException
com.squareup.okhttp.internal.http.RouteSelector.com.squareup.okhttp.Route next()(RouteSelector.java:79)
com.squareup.okhttp.internal.http.StreamAllocation.com.squareup.okhttp.internal.io.RealConnection findConnection(int,int,int,boolean)(StreamAllocation.java:164)
com.squareup.okhttp.internal.http.StreamAllocation.com.squareup.okhttp.internal.io.RealConnection findHealthyConnection(int,int,int,boolean,boolean)(StreamAllocation.java:126)
com.squareup.okhttp.internal.http.StreamAllocation.com.squareup.okhttp.internal.http.HttpStream newStream(int,int,int,boolean,boolean)(StreamAllocation.java:95)
com.squareup.okhttp.internal.http.HttpEngine.com.squareup.okhttp.internal.http.HttpStream connect()(HttpEngine.java:283)
com.squareup.okhttp.internal.http.HttpEngine.void sendRequest()(HttpEngine.java:224)
com.squareup.okhttp.Call.com.squareup.okhttp.Response getResponse(com.squareup.okhttp.Request,boolean)(Call.java:286)
com.squareup.okhttp.Call$ApplicationInterceptorChain.com.squareup.okhttp.Response proceed(com.squareup.okhttp.Request)(Call.java:243)
com.squareup.okhttp.Call.com.squareup.okhttp.Response getResponseWithInterceptorChain(boolean)(Call.java:205)
com.squareup.okhttp.Call.access$100(Call.java:35)
com.squareup.okhttp.Call$AsyncCall.void execute()(Call.java:171)
com.squareup.okhttp.internal.NamedRunnable.void run()(NamedRunnable.java:33)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
java.lang.Thread.run(Thread.java:841)

**Comment by JakeWharton** [comment]
Try 2.7.2?

**Comment by EngrZhou** [comment]
@JakeWharton Sorry，I write the wrong version.

**Comment by swankjesse** [comment]
Definitely try 2.7.2. It should be fixed in the patch release.

**Comment by UmeshAawte** [comment]
I just set my version to **2.7.4** and encountered same error. Is it the case that fix is only in **2.7.2** and not in **2.7.4**

**Comment by swankjesse** [comment]
@UmeshAawte could you provide us with an executable test case?

**Comment by UmeshAawte** [comment]
I am sorry but no I can't. 
One more thing this is not a issue which always reproduce. I am checking with if I can get the exact app state when it happen
