### ISSUE TITLE
cancel network request question

### ISSUE THREAD

**Issue by YangShaoXiong** [square/okhttp#2238]
in okhttp3.0,how to cancel all network request?

**Comment by JakeWharton** [comment]
You can call `cancelAll()` on the dispatcher which can be accessed by calling `dispatcher()` on `OkHttpClient`.

**Comment by YangShaoXiong** [comment]
thanks

**Comment by ahmadrushdie** [comment]
i have an issue about cancel request that do submission data to server ..   when i call okHttpClient.dispatcher().cancelAll();  the request continuing execution but the callback not called
