### ISSUE TITLE
okhttp-ws can send ping/pong on both server and client side

### ISSUE THREAD

**Issue by Dev-Tony** [square/okhttp#2239]
okhttp-ws can only support client send ping and server response pong.

I have a requirment which is server send ping and client send pong.

Hope I can use okhttp-ws....

**Comment by Dev-Tony** [comment]
okHttp-ws actual has implement this feature, but interface is not disclosed. The implementation would be a simple change.

Check this code
```java
  public RealWebSocket(boolean isClient, BufferedSource source, BufferedSink sink, Random random,
      final Executor replyExecutor, final WebSocketListener listener, final String url) {
    this.listener = listener;

    writer = new WebSocketWriter(isClient, sink, random);
    reader = new WebSocketReader(isClient, source, new FrameCallback() {
      @Override public void onMessage(ResponseBody message) throws IOException {
        listener.onMessage(message);
      }

      @Override public void onPing(final Buffer buffer) {
        replyExecutor.execute(new NamedRunnable("OkHttp %s WebSocket Pong Reply", url) {
          @Override protected void execute() {
            try {
              writer.writePong(buffer);
            } catch (IOException ignored) {
            }
          }
        });
      }

      @Override public void onPong(Buffer buffer) {
        listener.onPong(buffer);
      }

      @Override public void onClose(final int code, final String reason) {
        readerSentClose = true;
        replyExecutor.execute(new NamedRunnable("OkHttp %s WebSocket Close Reply", url) {
          @Override protected void execute() {
            peerClose(code, reason);
          }
        });
      }
    });
  }
```

**Comment by swankjesse** [comment]
So the feature request is to notify the application layer when a ping occurs?

**Comment by Dev-Tony** [comment]
Yes, I think so.

**Comment by swankjesse** [comment]
I think that’s an awkward design. What’s the motivation?

**Comment by Dev-Tony** [comment]
I hope application layer can handle the response data of pong depends on the input from ping data, not just simply return pong taking ping data.

for example:
server: ping(A)
client: pong(AB)

**Comment by JakeWharton** [comment]
That would violate [section 5.5.3 of RFC 6455][1] which states:

> A Pong frame sent in response to a Ping frame must have identical "Application data" as found in the message body of the Ping frame being replied to.

 [1]: https://tools.ietf.org/html/rfc6455#section-5.5.3

**Comment by Dev-Tony** [comment]
Yes, you are right.
But I still hope application layer would be notified while receiving ping, so we can handle heartbeat by application.

**Comment by swankjesse** [comment]
It's unlikely that feature will survive the inevitable websockets on HTTP/2 spec.

**Comment by Dev-Tony** [comment]
I agree the example is a mistake.
But the spec does motion application layer should not be noticed on ping.

**Comment by JakeWharton** [comment]
We have decided not to implement this. From a survey of a large group of web socket APIs, pings and pongs are rarely used and pings never have any bearing on the application layer. This is exacerbated by the fact that JavaScript doesn't expose a way to send pings at all.

**Comment by swankjesse** [comment]
We added ping intervals in 3.10.0.
https://github.com/square/okhttp/blob/master/CHANGELOG.md#version-3100
