### ISSUE TITLE
Feature Request: peekBody on Request object

### ISSUE THREAD

**Issue by danvinokour** [square/okhttp#2240]
Hi, There is peekBody on the response body but not on the request one which makes it hard to use the logging interceptor and log the request body.

**Comment by JakeWharton** [comment]
The request body can be written multiple times so it doesn't need a peek
body. You can just write its contents to a Buffer as many times as you need.

**Comment by danvinokour** [comment]
It would be much easier if i could run string() on the request body like on response.
Is it possible to add this possibility?

**Comment by swankjesse** [comment]
This will do it:
```
  String requestBodyToString(RequestBody body) throws IOException {
    Buffer buffer = new Buffer();
    body.writeTo(buffer);
    return buffer.readUtf8();
  }
```
