### ISSUE TITLE
AbstractMethodError

### ISSUE THREAD

**Issue by krishnameena** [square/okhttp#2248]
I have updated OKHTTP from okhttp:3.0.0-RC1 to okhttp:3.0.1, now I am getting following error : 

 java.lang.AbstractMethodError: abstract method "void okhttp3.Callback.onResponse(okhttp3.Call, okhttp3.Response)"
                                                                    at okhttp3.RealCall$AsyncCall.execute(RealCall.java:133)
                                                                    at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:33)
                                                                    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                    at java.lang.Thread.run(Thread.java:818)

**Comment by pawel-marchewka** [comment]
Hi.

I have exactly the same situation.

**Comment by JakeWharton** [comment]
Presumably you are using Retrofit 2.0.0-beta3 and you need to use
2.0.0-SNAPSHOT.

**Comment by pawel-marchewka** [comment]
> Presumably you are using Retrofit 2.0.0-beta3 and you need to use 2.0.0-SNAPSHOT.

You are right, thanks!

**Comment by psyopussy** [comment]
using snapshot does not solve this error me.


    compile 'com.squareup.retrofit2:retrofit:2.0.0-SNAPSHOT'
  //  compile 'com.squareup.retrofit2:retrofit:2.0.0-beta3'
    compile 'com.squareup.retrofit2:converter-gson:2.0.0-beta3'
    compile 'com.squareup.retrofit2:converter-scalars:2.0.0-beta3'
    compile 'com.squareup.okhttp3:logging-interceptor:3.0.1'


        OkHttpClient client = new OkHttpClient();
        //HttpLoggingInterceptor interceptor = new HttpLoggingInterceptor();
        //interceptor.setLevel(HttpLoggingInterceptor.Level.BODY);
       // client.interceptors().add(interceptor);

        Retrofit retrofit = new Retrofit.Builder()
                .baseUrl("http://www.mysite.com")
                .client(client)
                .addConverterFactory(GsonConverterFactory.create())
                .build();
        MyApi myApi = retrofit.create(MyApi.class);
        Call<List<Template>> call = myApi.load();
        call.enqueue(this);

**Comment by JakeWharton** [comment]
You need to use SNAPSHOT for all Retrofit dependencies.

**Comment by mliberato** [comment]
Can't find SNAPSHOT in any repos. Do I need to add a specific repo?

**Comment by JakeWharton** [comment]
The Sonatype snapshot repo. The link is in the README.

**Comment by mliberato** [comment]
Got it, it's working. Didn't notice I had to add sonatype's repo.

**Comment by psyopussy** [comment]
@mliberato 
I'm new to gradle,
how do i add the sonatype repo?
thx!

**Comment by mliberato** [comment]
Include repo address in your repositories field:

    repositories {
        mavenCentral()
        maven { url "https://oss.sonatype.org/content/repositories/snapshots" }
    }

**Comment by psyopussy** [comment]
that simple huh.. ok cool.
cheers!
