### ISSUE TITLE
CookieJar - It doesn't exits method removeAll

### ISSUE THREAD

**Issue by moisesvs** [square/okhttp#2249]
Hi! 

In the new version of the library okHttp 3.0.1 it doesn't exits method removeAll in the new interface CookieJar. In other versiones I had a cookieHandler and I could do a call to method removeAll to remove all cookies of the http client. But now it doesn't existe any similar method. 

How Can I do it?

The old code:
this.cookieManager = new CookieManager();
this.cookieManager.setCookiePolicy(CookiePolicy.ACCEPT_ALL);
this.clientOkHttp.setCookieHandler(cookieManager);

New code:

this.cookieManager = this.clientOkHttp.cookieJar();
this.cookieManager.......

Thanks a lot. Regards

**Comment by swankjesse** [comment]
You can continue to use a `CookieManager` if you use the `okhttp-urlconnection` module and the JavaNetCookieJar class. We don’t yet have a concrete implementation of `CookieJar`.

**Comment by moisesvs** [comment]
Hi, 

Could you say me what is the code to enable CookieManager en OkHttp3? 

Thanks a lot.

**Comment by swankjesse** [comment]
```
    client = client.newBuilder()
        .cookieJar(new JavaNetCookieJar(cookieManager))
        .build();
```

**Comment by GPack1** [comment]
I get 

> Cannot resolve symbol JavaNetCookieJar

isnt it in okhttp3 package?

**Comment by JakeWharton** [comment]
It's in the okhttp3-urlconnection artifact.

**Comment by GPack1** [comment]
thks, it is not very clear for me the migration from okhttp 2 to 3
