### ISSUE TITLE
[Suggestion] Concatenate multiple message-header fields with same field-name

### ISSUE THREAD

**Issue by rfc2822** [square/okhttp#2254]
In both HTTP/1.0 and HTTP/1.1,

>Multiple message-header fields with the same field-name MAY be present in a message if and only if the entire field-value for that header field is defined as a comma-separated list [i.e., #(values)]. **It MUST be possible to combine the multiple header fields into one "field-name: field-value" pair, without changing the semantics of the message, by appending each subsequent field-value to the first, each separated by a comma.**

In my opinion,

1. okhttp should concatenated multiple headers with the same name to one field to allow easy processing without mistakes (the concatenated value should be returned by `response.header()`),
2. so there's no need for `response.headers()` anymore (because multiple message-header fields with same name can always be concatenated to a single list).

okhttp wouldn't need to consider whether the headers actually are allowed to be concatenated by `, `, because only in this case multiple message-header fields with same name may occur.

The reason for this suggestion is a real-world problem where I have (mistakenly) used `response.header("DAV")` to determine the values of the `DAV` header and it worked every time, until a server decided to send two DAV headers, `response.header("DAV")` returned only one of them. It works when processing all `DAV` headers with `response.headers("DAV")`, but I think this should not be required. See this test:

```
mockServer.enqueue(new MockResponse()
    .setResponseCode(200)
    .addHeader("Test", "A, B")
    .addHeader("Test", "C, D")
);
Response response = httpClient.newCall(new Request.Builder()
    .url(mockServer.url("/"))
    .build()).execute();
assertEquals(200, response.code());
assertEquals("A, B, C, D", response.header("Test")); // fails, but shouldn't fail in my opinion
```

I guess that many other applications will use `.header("name-of-header-whose-value-is-a-list")` instead of `.headers()`, too, and those will fail as soon as the first server sends the list in two separate headers.

**Comment by swankjesse** [comment]
We can’t do this generally. The specs call out that certain headers contain `,` characters (specifically `Set-Cookie`) and so combining those is not possible.

I think the best solution here is for webapp authors to combine with `,` in their applications. In this case your app should return a single header line with multiple values separated by commas.

**Comment by rfc2822** [comment]
> We can’t do this generally. The specs call out that certain headers contain , characters (specifically Set-Cookie) and so combining those is not possible.

You're right, RFC 6265 says:

> Origin servers SHOULD NOT fold multiple Set-Cookie header fields into a single header field.  The usual mechanism for folding HTTP headers fields (i.e., as defined in [RFC2616]) might change the semantics of the Set-Cookie header field because the %x2C (",") character is used by Set-Cookie in a way that conflicts with such folding.

Sorry for the noise, caused by believing that HTTP works like described in RFC 2616.

> I think the best solution here is for webapp authors to combine with , in their applications. In this case your app should return a single header line with multiple values separated by commas.

I guess I will make a `headerConcat()` method that concatenates the `headers()` , and always call that one (except when dealing with `Set-Cookie2`).

Don't you think such a method `response.headerConcat()` (or however you'd like to name it), directly available from okhttp's `Response`, would be very useful for others?

**Comment by swankjesse** [comment]
This is one of those awkward situations where we have a disagreement between the semantic and physical layers of the protocol. Ideally, application code doesn’t care whether it’s two headers with one value each, or one header with two values separated by commas.

In practice it usually doesn’t matter. Very few headers are ever repeated, and when they are there’s typically agreement between client & server on how they’re repeated. For example, the `Accept-Encoding` header almost universally uses commas.

I’m reluctant to do anything to transform one form into another. It’d be great if the semantic & physical layers were identical, but they aren’t and it’s weird to play favorites.

**Comment by rfc2822** [comment]
> Very few headers are ever repeated, and when they are there’s typically agreement between client & server on how they’re repeated.

In my case, there was a single server that decided to split the header into two DAV headers. I found it only by occasion. So, yes, very few headers are ever repeated, but when they are, there's a big chance that this will be mistreated.

> I’m reluctant to do anything to transform one form into another.

No problem, I'll do it myself. Thanks for your time.
