### ISSUE TITLE
Can not find MockWebServer class

### ISSUE THREAD

**Issue by yjwfn** [square/okhttp#2258]
I use testCompile add MockWebServer library ,but can not find MockWebServer class.
My AndroidStudio version is 1.5.1.

```
  compile 'com.squareup.okhttp3:okhttp:3.0.1'
  testCompile 'com.squareup.okhttp:mockwebserver:2.7.2'
```

**Comment by JakeWharton** [comment]
What import are you using for it?

**Comment by JakeWharton** [comment]
You should really update MWS to `com.squareup.okhttp3:mockwebserver:3.0.1` if you're using OkHttp 3.0.1...

**Comment by yjwfn** [comment]
I solved this problem by using androidTestCompile .
```
compile 'com.squareup.okhttp3:okhttp:3.0.1'
androidTestCompile 'com.squareup.okhttp:mockwebserver:2.7.2'
```

**Comment by JakeWharton** [comment]
Sounds good.

**Comment by yjwfn** [comment]
I hope you update `README`.

**Comment by JakeWharton** [comment]
Well the README is correct for unit tests for both Java projects and Android projects, just not Android-specific instrumentation tests.

**Comment by yjwfn** [comment]
Got it.

**Comment by superdiazzz** [comment]
it's now available on `testImplementation("com.squareup.okhttp3:mockwebserver:4.0.0")`, i still got same error

**Comment by farruhha** [comment]
> it's not available on `testImplementation("com.squareup.okhttp3:mockwebserver:4.0.0")`, i still got same error

I think latest stable version is 
   ` androidTestImplementation "com.squareup.okhttp3:mockwebserver:3.10.0"`
