### ISSUE TITLE
in the okhttp3.0RC1 listener upload progress

### ISSUE THREAD

**Issue by YangShaoXiong** [square/okhttp#2260]
I according to https://github.com/square/okhttp/pull/1528/files#diff-c6ab42889cbea1ec8ae454018c39977c, but after the success of the upload, can't timely response onResponse method, call onResponse method with a delay.Trouble to help me, thank you in advance.

**Comment by swankjesse** [comment]
Could you provide a test case that demonstrates the problem?

**Comment by longtaoge** [comment]
I think you can   merge  with   https://github.com/hongyangAndroid/okhttp-utils   on Android

**Comment by swankjesse** [comment]
No obvious action for us to take here.
