### ISSUE TITLE
How Okhttp change the rule of the cache key set

### ISSUE THREAD

**Issue by guobao90** [square/okhttp#2261]
okhttp,the cache key is the url.But every time I request the same url I need to put param of "distinctRequestId" to distinguish every request.It lead to my url is different every time.But the content is the same .So I want to set the cache key custom. which i can get the cache is Unique.

**Comment by swankjesse** [comment]
Sorry, different URLs yield different cache values. Your best option is to convince your server team to move the distinctRequestId field from the URL and into a header or the request body.

(You could also hack around this adding the distinctRequestId URL parameter in a network interceptor, but that could be fragile.)

**Comment by swankjesse** [comment]
No action for us to take here.

**Comment by lqtian** [comment]
(You could also hack around this adding the distinctRequestId URL parameter in a network interceptor, but that could be fragile.)

I added my parameter in network interceptor, why it still not work? What should I do else?
