### ISSUE TITLE
HTTP 301 redirect does not respect selected HTTP Method

### ISSUE THREAD

**Issue by pavlospt** [square/okhttp#2262]
Hello.

I have a Django endpoint that ends without a trailing slash. The selected method when I hit the endpoint is POST, but after getting a HTTP 301 Redirect code, the client ends up redirecting the same call, at the same endpoint without respecting the original selected method, by turning the final method to GET.

Is there something that i might have been missing on this or is it in fact a bug?

**Comment by JakeWharton** [comment]
[RFC 7238][1] defines HTTP 308 for that behavior: https://tools.ietf.org/html/rfc7238. For 301 and 302 the client changes the HTTP method to GET.

 [1]:  5 3 4 | 6 7 8 | 9 1 2 
 6 7 2 | 1 9 5 | 3 4 8 
 1 9 8 | 3 4 2 | 5 6 7
-------+-------+------ 
 8 5 9 | 7 6 1 | 4 2 3
 4 2 6 | 8 5 3 | 7 9 1 
 7 1 3 | 9 2 4 | 8 5 6 
-------+-------+------ 
 9 6 1 | 5 3 7 | 2 8 4 
 2 8 7 | 4 1 9 | 6 3 5 
 3 4 5 | 2 8 6 | 1 7 9

**Comment by pavlospt** [comment]
Shouldn't there be an option to turn off the method change behaviour or is 308 widely known for such behaviour? 

What i mean is, do i have to tell the backend team to change the response code as a mistake on their side, or should there be an option in OkHttp to turn this off?

Thanks

**Comment by swankjesse** [comment]
OkHttp tries to act like a web browser. If you want to configure how a redirect is handling, you need to do it server-side.

**Comment by swankjesse** [comment]
(And the upside with that approach is that you get the same behavior everywhere: Android, iOS, web.)

**Comment by pavlospt** [comment]
Tried the same endpoint with Postman, you might know it, but it seemed to work correctly by keeping the same method both on the original call and the redirected one. 

My main question is: Do I have to change the backend's behaviour in this case in order to follow the specific behaviour mentioned by Jake or is there a way to override it from the side of OkHttp?

**Comment by swankjesse** [comment]
What do Chrome & Firefox do?

You could write an interceptor to patch the response code.

**Comment by pavlospt** [comment]
Since Postman is based on Chromium I can only guess that they function the same. 

Maybe i will try with an Interceptor as you suggested. 

Thank you both for the feedback.

**Comment by swankjesse** [comment]
You’d probably want to write an interceptor to rewrite the response code. But that would be a fragile hack.

**Comment by swankjesse** [comment]
No action for us to take here.

**Comment by osrl** [comment]
I have the same issue. Volley, Postman, curl didn't show any track of redirect. Also there is no issue on the server side code, we don't redirect. Is there any possibility that this could be a okHttp issue?

**Comment by swankjesse** [comment]
What’s the request?

**Comment by osrl** [comment]
Just a simple POST request.
`curl -v -H "Content-Type: application/json" -X POST -d '{"email":"abc","password":"abc"}' http://localhost`

Response is 200.

**Comment by swankjesse** [comment]
Hmm . . . I think we do that the exact same. Could you write a quick test case? This gist has the boilerplate to get you started: https://gist.github.com/swankjesse/981fcae102f513eb13ed

**Comment by osrl** [comment]
What do you need me to test?

**Comment by jonasfa** [comment]
Even though many browsers do it (and OkHttp is not a browsers anyways), [RFC 2068](https://tools.ietf.org/html/rfc2068#section-10.3.3) clearly states that changing the request method after a 302 response is an **error**.

**Comment by swankjesse** [comment]
We’re following the more recent [RFC 7231](https://tools.ietf.org/html/rfc7231#section-6.4.2):

> Note: For historical reasons, a user agent MAY change the request method from POST to GET for the subsequent request.  If this behavior is undesired, the 307 (Temporary Redirect) status code can be used instead.

**Comment by jonasfa** [comment]
Let's analyse the context: this note was written to make people aware of a common mistake. It doesn't recommend nor encourage this behaviour.
According to itself - though not explicitly - and with other RFCs - at least 2068 is explicit -, clients still SHOULD **not** change the request method.

**Comment by jonasfa** [comment]
More on the context: the 307 and 308 status codes were created so servers could deal with common but still undesired client implementations - the "historical reasons" you quoted. These status codes sound a lot like workarounds to me.

Should a new, modern client be one of the undesired "historical reasons" which requires workarounds?

**Comment by jonasfa** [comment]
[RFC 2616](https://tools.ietf.org/html/rfc2616#section-10.3.3) (the updated version of 2068) is more clear: clients are not allowed to change the method on 301/302 redirections. It also reinforces that the 307 status code is a workaround to deal with non-compliant clients:

> Note: RFC 1945 and RFC 2068 specify that the client is not allowed
> to change the method on the redirected request.  However, most
> existing user agent implementations treat 302 as if it were a 303
> response, performing a GET on the Location field-value regardless
> of the original request method. The status codes 303 and 307 have
> been added for servers that wish to make unambiguously clear which
> kind of reaction is expected of the client.

**Comment by swankjesse** [comment]
Yep, 307 is perfect because all specs and all user agents agree on what to do. You should use that!

**Comment by ava1ar** [comment]
Having same issue as guys above: REST server is behind F5 BigIP and performs 302 redirect. As a result, none of the POST/PUT methods work, since okhttp performs GET after redirect.
There is nothing we can do internally since this is 3rd-party vendor solution and there is no easy way to change 302 to 307 in this case. Disappointed that okhttp doesn't provide an option to configure this behavior for such situations :(

**Comment by yschimke** [comment]
I think we do have a mechanism to correct for faulty servers like this

```

  val client = OkHttpClient.Builder()
    .eventListenerFactory(LoggingEventListener.Factory())
    .addNetworkInterceptor(object : Interceptor {
      override fun intercept(chain: Chain): Response {
        var response = chain.proceed(chain.request())
        
        if (response.code == 302) {
          response = response.newBuilder().code(307).build()
        }
        
        return response
      }
    })
    .build()
```

But we deliberately don't build in knobs and options that make it easy to workaround these issues.  Hopefully you have raised an issue with the faulty server and are tracking the fix with them.

**Comment by swankjesse** [comment]
@ava1ar use a network interceptor to rewrite the response status code?

**Comment by ava1ar** [comment]
Yes, I looked around for what other people do and did pretty much what you are proposed: network interceptor to re-map 301 to 308 and 302 to 307. Together with recent fixes to handle 307 & 308 in OkHttp this solved the problem.
