### ISSUE TITLE
Path segment documentation is unclear

### ISSUE THREAD

**Issue by marijnvdwerf** [square/okhttp#2263]
> The path identifies a specific resource on the host. Paths have a hierarchical structure like "/square/okhttp/issues/1486". Each path segment is prefixed with "/". This class offers methods to compose and decompose paths by segment. If a path's last segment is the empty string, then the path ends with "/". This class always builds non-empty paths: if the path is omitted it defaults to "/", which is a path whose only segment is the empty string.

This reads contradictory: 'Each path segment is prefixed with "/"', vs ' If a path's last segment is the empty string'. Maybe add some sample input/output?

**Comment by swankjesse** [comment]
Yeah, the wording could be more clear. It intends to mean that when assembling the complete path, we put a '/' before each segment.

**Comment by marijnvdwerf** [comment]
So like this?

Input | PathSegments
------------ | -------------
`https://github.com` | `[]`
`https://github.com/` | `[""]`
`https://github.com/square/okhttp/issues/2263` | `["square", "okhttp", "issues", "2263"]`

**Comment by swankjesse** [comment]
Yep. Though the first case is impossible, every HttpURL has at least one path segment. (ie. we’ll convert the first case into the second case.)

**Comment by marijnvdwerf** [comment]
Is there any reasoning behind this? I've never seen domain name with a trailing slash in an address bar.

**Comment by JakeWharton** [comment]
There is _always_ a path whether it's displayed or not. When you type "
http://google.com" and press enter a "GET / HTTP/1.1" is sent indicating a
path of "/".

**Comment by marijnvdwerf** [comment]
Ah, my bad then!
