### ISSUE TITLE
Error in ConnectionSpecs example on wiki

### ISSUE THREAD

**Issue by mic-** [square/okhttp#2267]
The code example on https://github.com/square/okhttp/wiki/HTTPS for usage of ConnectionSpecs lead me to believe that the `OkHttpClient` instance has a `setConnectionSpecs` method that I was supposed to call. But I don't see any such method in OkHttpClient.java, so I suspect that the intended method is `OkHttpClient.Builder`'s `connectionSpecs`. And in that case the last part of the example ought to read something like:

```
client = new OkHttpClient.Builder()
        ...
        .connectionSpecs(Collections.singletonList(spec))
        .build();
```

**Comment by JakeWharton** [comment]
Fixed! Thanks.

https://github.com/square/okhttp/wiki/HTTPS/_compare/7d143b68037c15cbdb0114aa6654956d65bec9ae...1391049d946f206c9f919e7d53a5d74bc6d7cc46
