### ISSUE TITLE
Provide a finer grained way to disallow cleartext traffic

### ISSUE THREAD

**Issue by chadbrubaker** [square/okhttp#2269]
As a follow up to #1058 we've found in deploying the cleartext traffic opt-out that the all or nothing nature of the current approach is too coarse grained to be enabled in many applications. For example the most common issue we run into is that a developer wants to disallow cleartext traffic to their secure domains while still being able to connect to arbitrary external non-sensitive URLs in cleartext.

It would be great if there was a way to approve cleartext traffic at a hostname level. This could take the form of a callback, perhaps a more generic checkRequestPermitted(Url destination, String method) throws ... which could be used for other types of filtering?

I'm happy to provide a patch if the approach sounds sensible.

**Comment by chadbrubaker** [comment]
Actually it seems that Interceptors would allow exactly what we need, but unfortunately we are stuck with the HttpUrlConnection factory which does not have support them and is deprecated. Would it be worth hooking them up in HttpUrlConnection?

**Comment by JakeWharton** [comment]
Interceptors cannot work with HttpURLConnection because of how it deals
with request bodies (bytes are pushed in rather than pulled).

**Comment by swankjesse** [comment]
@chadbrubaker today is the day to upgrade to OkHttp’s Request/Response API. You won’t regret it!

**Comment by chadbrubaker** [comment]
This is for Android, so I don't think's something we can do.

**Comment by nfuller** [comment]
To be clear, this is for the HttpURLConnection in the Android platform: Chad would like hooks that allow connections to be vetoed/failed based on a per-application policy for host names. Including redirects. So, he was hoping for some callbacks he could use that trigger before a connection is made.

**Comment by swankjesse** [comment]
There is no support for this in the HttpURLConnection APIs.

**Comment by swankjesse** [comment]
(You could try to install a `URLStreamHandlerFactory` that rejects `http:`, but even that won’t be able to handle redirects.)

**Comment by chadbrubaker** [comment]
Correct, there's no API support for this in HttpURLConnection, the goal here is to allow it to respect android's NetworkSecurityPolicy.isCleartextTrafficPermitted, or similar out of band policy. I can go into the why about having such a policy if you'd like.

I've thrown together a couple of quick patches to show what I mean. The simplest can be found in pr #2275.
This isn't as clean as putting into OkHttpClient, but clients of OkHttpClient can already use the Inteceptor functionality to honor the NetworkSecurityPolicy so adding another just seems like cruft. This limits the impact to the deprecated okhttp-urlconnection.

**Comment by swankjesse** [comment]
Just to confirm: is this for a specific app, or for AOSP?

**Comment by chadbrubaker** [comment]
Aosp

**Comment by chadbrubaker** [comment]
For a bit more context, this is about expanding the features provided in https://developer.android.com/reference/android/security/NetworkSecurityPolicy.html and the android:usesCleartextTraffic manifest flag. Common feedback from developers was that they wanted to block cleartext in their app to sensitive domains (ie: login.example.com must always be over https) but that their app still did some cleartext traffic to other non-sensitive hosts that they could not simply force to https (either because the sites did not support it or they supported arbitrary hosts that may or may not have https). This helps to prevent bugs in both the initial implementation as well as avoid regression where a server provides the URL and something on the backend mistakenly changes the URL from https to http.

The general goal is to transparently respect these declarative flags without the developer having to write any code since requiring developers to correctly write security sensitive code often leads to security bugs when they get it wrong. It is better security-wise if the developer can declare simple and easy to understand policy that then 'just works' when using the standard platform connections.
