### ISSUE TITLE
Accept-Encoding: gzip makes response come as gobberish

### ISSUE THREAD

**Issue by danvinokour** [square/okhttp#2277]
I understand that gzipped content extracted automatically but why adding this header causes response to come as gibberish?
Adding this header is the right behaviour even though OkHttp automatically handles it.

**Comment by swankjesse** [comment]
If you add this header yourself, you're disabling OkHttp’s built in support and taking responsibility to decompress on your own.

**Comment by danvinokour** [comment]
So when using OkHttp i should never use this header? in any case?

**Comment by swankjesse** [comment]
Only use it if you want to do gzip yourself. Or use `Accept-Encoding: identity` to disable gzip completely.
