### ISSUE TITLE
okhttp3.ws package does not exist

### ISSUE THREAD

**Issue by TimmySong** [square/okhttp#2279]
Version: okhttp-3.0.1.jar
When I try the WebSocketEcho recipe, I found that the okhttp3.ws package is not found.Then I use the jd-gui to check it out.The result is attached as a part of screenshot.

![okhttp3structure](https://cloud.githubusercontent.com/assets/12878346/12548381/dc45a692-c390-11e5-9cf9-2c282a1b072a.png)

**Comment by swankjesse** [comment]
You'll also need the okhttp-ws jar. This works best if you're using a package manager like Maven or Gradle.

**Comment by TimmySong** [comment]
Get it ,thank you~
