### ISSUE TITLE
okhttp3 OkHttpClient how to set read and write timeouts?

### ISSUE THREAD

**Issue by eugenehusnullin** [square/okhttp#2280]
There is no possibility to set read and write timeouts.

Read and write timeouts can be set to Builder inner class, but if I create custom Builder class object than I can't use it to create OkHttpClient because constructor that take Builder is private.

**Comment by swankjesse** [comment]
`Builder.build()`

**Comment by gzfgeh** [comment]
can you say detail?

**Comment by eugenehusnullin** [comment]
`import okhttp3.OkHttpClient;
import okhttp3.OkHttpClient.Builder;

// .....
Builder b = new Builder();
b.readTimeout(200, TimeUnit.MILLISECONDS);
b.writeTimeout(600, TimeUnit.MILLISECONDS);
// set other properties
		
OkHttpClient client = b.build();
// now you can use client`

**Comment by AppAfzar** [comment]
how can I handle timeout Exception in Okhttp3?
