### ISSUE TITLE
http2 readSettings() throws invalid parameter id when unknown settings encountered

### ISSUE THREAD

**Issue by jk0204** [square/okhttp#2282]
We are using OkHttp2 to talk to a service configured using IIS. It works fine with Android 4.x, but on Android 5.0 and above, the connection is always closed by the client. 

The issue turns out to be that the frame returned back from the service contains a setting  with id 16, which is not defined in https specification, thus OkHttp's http2 readSettings() method throws invalid parameter  exception. 

According to the RFC (https://tools.ietf.org/html/rfc7540#section-6.5.2), unknown parameter should be ignored, so would it be better to ignore and continue in this case instead of throwing the exception?

**Comment by swankjesse** [comment]
Yup, that's our bug. Will fix. If you wanna send a pull request with a test case, please do!
