### ISSUE TITLE
HTTP HEAD requests not cached?

### ISSUE THREAD

**Issue by aoemerson** [square/okhttp#2287]
I have configured a disk cache for my app's instance of OkHttpClient (v3.0.1) and I've noticed that while `GET` requests are cached fine, the equivalent `HEAD` request for the same resource is **not** cached. 

Is this expected behaviour? Perhaps I'm misunderstanding something in the HTTP standard.

For example `GET http://static.bbci.co.uk/news/1.108.0505/apple-touch-icon.png` results in a cache entry as:
```HTTP
http://static.bbci.co.uk/news/1.108.0505/apple-touch-icon.png
GET
0
HTTP/1.1 200 OK
13
Server: Apache/2.2.25 (Unix)
Last-Modified: Thu, 21 Jan 2016 19:22:53 GMT
ETag: "276f-529dd07725d40"
Accept-Ranges: bytes
Content-Length: 10095
Cache-Control: max-age=31536000
Expires: Wed, 25 Jan 2017 10:43:01 GMT
Access-Control-Allow-Origin: *
Content-Type: image/png
Date: Wed, 27 Jan 2016 15:04:20 GMT
Connection: keep-alive
OkHttp-Sent-Millis: 1453907060254
OkHttp-Received-Millis: 1453907060705
```
**but** `HEAD http://static.bbci.co.uk/news/1.108.0505/apple-touch-icon.png` results in nothing being added to the cache. If I clear the cache and try the `HEAD` requests again, still nothing is cached.

The actual `HEAD` response for the resource above is:
```HTTP
Request URL:http://static.bbci.co.uk/news/1.108.0505/apple-touch-icon.png
Request Method:HEAD
Status Code:200 OK
Accept-Ranges:bytes
Access-Control-Allow-Origin:*
Cache-Control:max-age=31536000
Connection:keep-alive
Content-Length:10095
Content-Type:image/png
Date:Wed, 27 Jan 2016 15:22:19 GMT
ETag:"276f-529dd07725d40"
Expires:Wed, 25 Jan 2017 10:42:40 GMT
Last-Modified:Thu, 21 Jan 2016 19:22:53 GMT
OkHttp-Received-Millis:1453908139802
OkHttp-Sent-Millis:1453908139550
Server:Apache/2.2.25 (Unix)
```
### My code
I'm setting up my `OkHttpClient` as follows:

```java
    protected void initOkHttp() {
        File cacheDir = this.getCacheDir();
        OkHttpClient.Builder builder = new OkHttpClient.Builder();

        if (cacheDir != null) {
            final File okCacheDir = new File(cacheDir, "OkHttpCache");
            if (!okCacheDir.exists()) {
                okCacheDir.mkdirs();
            }
            Cache cache = new Cache(okCacheDir, MAX_CACHE_SIZE);
            builder.cache(cache);
        }

        sOkHttpClient = builder.build();
    }
```
and forming the request as follows:
```java
Request request = new Request.Builder()
                    .head()
                    .url(url) // e.g. http://static.bbci.co.uk/news/1.108.0505/apple-touch-icon.png
                    .build();
```

Thanks in advance for any help.

**Comment by aoemerson** [comment]
Sorry, I just read the HEAD [spec](http://tools.ietf.org/html/rfc2616#section-9.4) again and seems that it should only cache if there was a previous *entity* stored in cache:

```
The response to a HEAD request MAY be cacheable in the sense that the
information contained in the response MAY be used to update a
previously cached entity from that resource. If the new field values
indicate that the cached entity differs from the current entity (as
would be indicated by a change in Content-Length, Content-MD5, ETag
or Last-Modified), then the cache MUST treat the cache entry as
stale.
```

Still, I would like to be able to do HEAD requests without necessarily having to hit the network - is that possible? I tried using GET requests without opening the body but that still seems like more of a performance drain than using HEAD.

**Comment by swankjesse** [comment]
Doing a GET without reading the body is fast & easy. Your device doesn’t need to send radio signals to far away cell towers.

**Comment by swankjesse** [comment]
No action for us to take on this.

**Comment by aoemerson** [comment]
Thanks @swankjesse - I'll go with that approach. Thanks again, guys, for a great library :thumbsup:
