### ISSUE TITLE
Support custom HTTP methods with bodies.

### ISSUE THREAD

**Issue by blackdigger** [square/okhttp#229]
PROPFIND was added. Re-purposing this issue for arbitrary methods allowing bodies. These would obviously be forbidden from any cache interaction as no semantics can be known.

— @JakeWharton

~~Is it possible to add support for custom HTTP methods such as PROPFIND?
I realize there is a limitation of sun's implementation of HttpUrlConnection, but maybe you have some idea how to work around that?
we use apache http client in our project at the moment mainly because it allows to define custom http method by extending HttpEntityEnclosingRequestBase.
we tried to switch to OkHttp, both core version with HttpUrlConnection and OkApacheClient version - they both throw ProtocolException (probably because both use HttpUrlConnection inside)~~

**Comment by maevius** [comment]
I think the implementors of HttpURLConnection got it wrong here. Clearly the spec states "extension-method". While this is an optional feature for a Server, it doesn't leave any space for a client side provider to speculate on the server side...

http://www.w3.org/Protocols/rfc2616/rfc2616-sec5.html#sec5.1
The Method token indicates the method to be performed on the resource identified by the Request-URI. The method is case-sensitive.

       Method         = "OPTIONS"                ; Section 9.2
                      | "GET"                    ; Section 9.3
                      | "HEAD"                   ; Section 9.4
                      | "POST"                   ; Section 9.5
                      | "PUT"                    ; Section 9.6
                      | "DELETE"                 ; Section 9.7
                      | "TRACE"                  ; Section 9.8
                      | "CONNECT"                ; Section 9.9
                      | extension-method
       extension-method = token

**Comment by rfc2822** [comment]
Is there currently any way to use PROPFIND with okhttp?

**Comment by rfc2822** [comment]
See also PR #1901. Please tell me if I can do further changes, tests, etc for this modification.

**Comment by alphatan** [comment]
1. How to have:

    1. make user-defined method (supported now, by **Request.method(String, RequestBody)**) 

    2. define the restriction of permitting or not the corresponding body (**NOT** work, **Request.method(String, RequestBody)**, **HttpMethod.permitsRequestBody(method)**).

2. Problem

    As all related classes are marked as '**FINAL**' (terrible pattern), I need to hack inside the source.

    **Hope it can be more open for extension**.

3. Tested version: 

    okhttp-2.5.0


Thanks.

**Comment by dahankzter** [comment]
This would be very neat! Now I have to include Apache Http Components for this isolated little thing. :(

**Comment by zmarkan** [comment]
I just encountered this issue and got around it by using Kotlin and placing an extension method for the Request.Builder in the same package.

I do believe it should be improved upon though.

**Comment by JeroenBer** [comment]
Please allow things like PROPFIND with request body. It seems not correct to be strict about custom http methods.
