### ISSUE TITLE
Caching without headers 

### ISSUE THREAD

**Issue by digitalbuddha** [square/okhttp#2291]
I believe I have a pretty typical use case. I want to use OKHTTP, have data available offline and be able to force network.  I'd like to be able to do this when working with public api's say Reddit.com

Based on various SO questions I was able to make an Interceptor that does just that
https://github.com/digitalbuddha/StoreDemo/blob/master/app%2Fsrc%2Fmain%2Fjava%2Fcom%2Fdigitalbuddha%2Fdaodemo%2Fbase%2FCacheInterceptor.java

Using this interceptor I can pass a header value of whether to force network and add proper Cache Control headers to each request.

I register the interceptor awkwardly by
```
okHttpClient.interceptors().add(interceptor); //needed for force network
okHttpClient.networkInterceptors().add(interceptor); //needed for offline mode
```

I think the community would benefit greatly from OKHTTP having a convenience method that enables the above behavior.

**Comment by swankjesse** [comment]
We're tracking this here:
https://github.com/square/okhttp/issues/1083

The trick is that in general the network state isn't binary. You might have HTTP access to say http://192.168.0.1 without having access to http://google.com.
