### ISSUE TITLE
OkHttp 3.0.1 and Retrofit2-beta3 Error

### ISSUE THREAD

**Issue by vivekkiran** [square/okhttp#2296]
01-29 12:29:22.005: E/AndroidRuntime(18232): FATAL EXCEPTION: OkHttp Dispatcher
01-29 12:29:22.005: E/AndroidRuntime(18232): Process: in.wavelabs.starterapp, PID: 18232
01-29 12:29:22.005: E/AndroidRuntime(18232): java.lang.AbstractMethodError: abstract method not implemented
01-29 12:29:22.005: E/AndroidRuntime(18232): 	at retrofit2.OkHttpCall$1.onFailure(OkHttpCall.java)
01-29 12:29:22.005: E/AndroidRuntime(18232): 	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:140)
01-29 12:29:22.005: E/AndroidRuntime(18232): 	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:33)
01-29 12:29:22.005: E/AndroidRuntime(18232): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
01-29 12:29:22.005: E/AndroidRuntime(18232): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
01-29 12:29:22.005: E/AndroidRuntime(18232): 	at java.lang.Thread.run(Thread.java:841)

**Comment by JakeWharton** [comment]
Duplicate post of https://github.com/square/retrofit/issues/1543, which has a link to another issue which describes the problem and fix.
