### ISSUE TITLE
NetworkOnMainThreadException While converting response to String

### ISSUE THREAD

**Issue by meet2011** [square/okhttp#2298]
Trying to convert API response into string by using following function but sometimes it works and other times it throws error **NetworkOnMainThreadException**

>     public static String convertToString(InputStreamReader isr) throws IOException {
> 
>         StringBuilder sb = new StringBuilder();
>         BufferedReader str = new BufferedReader(sir);
>         String read;
>         while ((read = str.readLine()) != null) {
>             sb.append(read);
>         }
>         return sb.toString();
> 
>     }
> 

using **runOnUiThread** inside onResponse but doesn't work. 
Version : OkHttp 3.0
 
Please help

**Comment by JakeWharton** [comment]
Read the string before calling runOnUiThread.
