### ISSUE TITLE
304 response caching body and prepending to following request header

### ISSUE THREAD

**Issue by harmanjd** [square/okhttp#2310]
Hi,

I am seeing a problem in 2.6.0 of OkHTTP (using it with retrofit 1.9.0). 

We have an endpoint on our server that will return a 304 response when we ask it for new messages and no new messages are available. The problem is that the endpoint also returns a body (this is contrary to the http spec I know - and I am working to get that fixed). 

However what is done with that body is an issue in this library I think. Instead of discarding it - it will be pre-pended to the HEADER of the next response which breaks the next call.

So on the following request I see an error like:

Unexpected status line: {"statusId":304,"subStatusId":0,"message":"No messages found.","path":"http://10.1.248.121/resource/appmessage/?lastMessageId=1","statusTimeStamp":"2016-02-03 09:12:18","allParameters":[{"key":"lastMessageId","value":"1"}]}HTTP/1.1 200 OK

The first part is the body of the 304 response, followed by the HTTP/1.1 200 OK which should be the first thing in the header.

Full stack trace here:

Unexpected status line: {"statusId":304,"subStatusId":0,"message":"No messages found.","path":"http://10.1.248.121/resource/appmessage/?lastMessageId=1","statusTimeStamp":"2016-02-03 09:12:18","allParameters":[{"key":"lastMessageId","value":"1"}]}HTTP/1.1 200 OK
02-03 11:12:17.645 2056-5221/com.servicemagic.consumer.debug E/ConsumerRestLoader:     at com.squareup.okhttp.internal.http.StatusLine.parse(StatusLine.java:54)
02-03 11:12:17.645 2056-5221/com.servicemagic.consumer.debug E/ConsumerRestLoader:     at com.squareup.okhttp.internal.http.HttpConnection.readResponse(HttpConnection.java:191)
02-03 11:12:17.645 2056-5221/com.servicemagic.consumer.debug E/ConsumerRestLoader:     at com.squareup.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:79)
02-03 11:12:17.646 2056-5221/com.servicemagic.consumer.debug E/ConsumerRestLoader:     at com.squareup.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:909)
02-03 11:12:17.646 2056-5221/com.servicemagic.consumer.debug E/ConsumerRestLoader:     at com.squareup.okhttp.internal.http.HttpEngine.access$300(HttpEngine.java:93)
02-03 11:12:17.646 2056-5221/com.servicemagic.consumer.debug E/ConsumerRestLoader:     at com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:894)
02-03 11:12:17.646 2056-5221/com.servicemagic.consumer.debug E/ConsumerRestLoader:     at com.squareup.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:748)
02-03 11:12:17.646 2056-5221/com.servicemagic.consumer.debug E/ConsumerRestLoader:     at com.squareup.okhttp.Call.getResponse(Call.java:277)
02-03 11:12:17.646 2056-5221/com.servicemagic.consumer.debug E/ConsumerRestLoader:     at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:234)
02-03 11:12:17.646 2056-5221/com.servicemagic.consumer.debug E/ConsumerRestLoader:     at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:196)
02-03 11:12:17.646 2056-5221/com.servicemagic.consumer.debug E/ConsumerRestLoader:     at com.squareup.okhttp.Call.execute(Call.java:79)
02-03 11:12:17.646 2056-5221/com.servicemagic.consumer.debug E/ConsumerRestLoader:     at retrofit.client.OkClient.execute(OkClient.java:53)
02-03 11:12:17.646 2056-5221/com.servicemagic.consumer.debug E/ConsumerRestLoader:     at com.servicemagic.consumer.retrofit.InterceptingOkClient.execute(InterceptingOkClient.java:29)
02-03 11:12:17.646 2056-5221/com.servicemagic.consumer.debug E/ConsumerRestLoader:     at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:326)

Looking at the code I don't really understand why the body get's put on the next response.

**Comment by JakeWharton** [comment]
Per [RFC 2616][1]:

> The 304 response MUST NOT contain a message-body, and thus is always terminated by the first empty line after the header fields.

And per its replacement, [RFC 7232][2]:

> A 304 response cannot contain a message-body; it is always terminated by the first empty line after the header fields.

OkHttp stops reading the connection's socket after the first `\r\n\r\n` which indicates termination of the header section. Thus, when the connection is later re-used for subsequent requests, attempting to read the status line of the next response gets the erroneous body of the previous request since those bytes were left sitting on the wire.

If you fix your server to conform to the RFC you'll see OkHttp behave correctly.

 [1]: https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html
 [2]: http://tools.ietf.org/html/rfc7232#section-4.1

**Comment by swankjesse** [comment]
You might be able to work-around this by adding a `Connection: close` header to every request that could suffer this problem. You’ll get worse performance until you remove that.
