### ISSUE TITLE
OkHttp 3.0 

### ISSUE THREAD

**Issue by SurayMdu** [square/okhttp#2312]
Hi Jake,
  I have Problem in implementing okhttp 3.0. I got this issue **java.lang.NoClassDefFoundError: okhttp3.HttpUrl**

**Comment by JakeWharton** [comment]
There is far too little information here to know what the problem is. Please ask your question on StackOverflow with the 'okhttp' tag and a lot more information such as the full trace, the dependencies you're using, etc.
