### ISSUE TITLE
AbstractMethodError for onResponse(...) on all dependency versions

### ISSUE THREAD

**Issue by ciscorucinski** [square/okhttp#2313]
I have tried working with several different versions of the dependencies here with Retrofit and OKHttp; including not declaring the OKHttp dependency since that is included in Retrofit. With all of that, I am still getting the following error message.

As a side note, I cannot seem to get the SNAPSHOT versions working either. They cannot be found.

**Error**

    FATAL EXCEPTION: OkHttp Dispatcher
    Process: io.github.ciscorucinski.nanodegree.android.capstone, PID: 332
    java.lang.AbstractMethodError: abstract method "void okhttp3.Callback.onResponse(okhttp3.Call, okhttp3.Response)"
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:133)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:33)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:818)

**Dependencies**

    compile 'com.android.support:appcompat-v7:23.1.1'
    compile 'com.android.support:design:23.1.1'
    compile 'com.android.support:cardview-v7:23.1.1'
    compile 'com.android.support:recyclerview-v7:23.1.1'
    compile 'com.android.support:support-v4:23.1.1'
    compile 'com.android.support:percent:23.1.1'
    compile 'com.google.android.gms:play-services-auth:8.4.0'
    compile 'com.facebook.stetho:stetho:1.0.0'
    compile 'com.google.code.gson:gson:2.5'
    compile 'com.squareup.retrofit2:retrofit:2.0.0-beta3'
    compile 'com.squareup.retrofit2:converter-gson:2.0.0-beta3'
    compile 'com.squareup.okhttp3:okhttp:3.0.0-RC1'
    compile 'com.facebook.stetho:stetho-okhttp3:1.3.0'

**Comment by JakeWharton** [comment]
stetho-okhttp 1.3.0 brings in OkHttp 3.0.0. You can verify this by running the `dependencies` task.

Update to Retrofit 2.0.0-beta4 and all your problems will magically disappear.
