### ISSUE TITLE
Support ETag and If-None-Match 

### ISSUE THREAD

**Issue by superLY91** [square/okhttp#2314]
I use OkHttpClient (v3.0.1) which is in my application，but ETag and If-None-Match are not working。

For example:
 **First**   GET http://112.4.19.67/task/imags_avatar/20130607165126605.png

In Response, I get ETag and Last-Modified.

Request：
> GET /task/imags_avatar/20130607165126605.png HTTP/1.1
> Host: 112.4.19.67
> Connection: Keep-Alive
> Accept-Encoding: gzip
> User-Agent: okhttp/3.0.1

Response：
> HTTP/1.1 200 OK
> Server: Apache
> **Last-Modified: Mon, 30 Jun 2014 04:44:43 GMT**
> **ETag: "1205-4fd06515d9572"**
> Content-Type: image/png
> Content-Length: 4613
> Accept-Ranges: bytes
> Date: Thu, 04 Feb 2016 13:30:05 GMT
> X-Varnish: 3684240013 3683622711
> Age: 1313
> Via: 1.1 varnish
> Connection: keep-alive

 **Second**   GET the same url : http://112.4.19.67/task/imags_avatar/20130607165126605.png

I think that I could see the If-None-Match in request. but it doesn't exist.

Request：
> GET /task/imags_avatar/20130607165126605.png HTTP/1.1
> Host: 112.4.19.67
> Connection: Keep-Alive
> Accept-Encoding: gzip
> User-Agent: okhttp/3.0.1

Response:
> HTTP/1.1 200 OK
> Server: Apache
> Last-Modified: Mon, 30 Jun 2014 04:44:43 GMT
> ETag: "1205-4fd06515504c0"
> Content-Type: image/png
> Content-Length: 4613
> Accept-Ranges: bytes
> Date: Thu, 04 Feb 2016 13:30:26 GMT
> X-Varnish: 3389168698 3388862573
> Age: 642
> Via: 1.1 varnish
> Connection: keep-alive

**My Code**

        File file = getCacheDir();
        Cache cache = new Cache(file, CACHE_SIZE);

        OkHttpClient.Builder builder = new OkHttpClient.Builder();
        builder.cache(cache);
        OkHttpClient client = builder.build();

        Request request = new Request.Builder()
                .url(url)
                .build();

Thanks in advance for any help.

**Comment by swankjesse** [comment]
I can’t tell if this is a debugging question or a bug report. . .

If it’s a debugging question, please try [stackoverflow](http://stackoverflow.com/questions/tagged/okhttp) instead. You’ll get a better answer, faster there.

If it’s a bug report, please add a failing test case. You could look at our [other test cases](https://github.com/square/okhttp/blob/master/okhttp-tests/src/test/java/okhttp3/CallTest.java) for to get started.

**Comment by msal** [comment]
A test like this, or has it to be with a `MockWebServer`?

```java
   @org.junit.Test
   public void etagTest() throws Exception {
      Cache cache = new Cache(new File("/cache/"), 10 * 1024 * 1024);
      OkHttpClient client = new OkHttpClient.Builder()
            .cache(cache)
            .build();

      String url = "http://112.4.19.67/task/imags_avatar/20130607165126605.png";
      Request request = new Request.Builder()
            .url(url)
            .build();

      Response response1 = client.newCall(request).execute();

      // check that the header has an ETag set, in the response of the first request
      assertNotNull(response1.header("ETag"));
      // check that the http code of the first response is 200
      assertEquals(response1.code(), 200);


      // fire the same request again. now the ETag form the first response should be added
      Response response2 = client.newCall(request).execute();

      // check that the second request has an 'If-None-Match' header element
      assertNotNull(response2.request().header("If-None-Match"));
      // check that the http code of this second response is 304 -
      // because the content didn't change and the ETag has to be set
      assertEquals(response2.code(), 304);
   }
```

**Comment by superLY91** [comment]
Do you run the "etagTest" case success? I fail on "assertNotNull(response2.
request().header("If-None-Match"))", response2.request().header is null.

I debug okhttp3.0 , I find that entry.readable is flase on DisklruCache
Class，so return null.

Thanks in advance for any help.

public synchronized Snapshot get(String key) throws IOException {
  initialize();

  checkNotClosed();
  validateKey(key);
  Entry entry = lruEntries.get(key);
  if (entry == null || !entry.readable) return null;

  Snapshot snapshot = entry.snapshot();
  if (snapshot == null) return null;

  redundantOpCount++;
  journalWriter.writeUtf8(READ).writeByte(' ').writeUtf8(key).writeByte('\n');
  if (journalRebuildRequired()) {
    executor.execute(cleanupRunnable);
  }

  return snapshot;
}
