### ISSUE TITLE
Is it possible to avoid creating several clients?

### ISSUE THREAD

**Issue by danvinokour** [square/okhttp#2316]
I have a need to create several different clients since each one has different interceptors.
I pass those clients to retrofit which mean that each time i use client.build() new client instance is created and memory is wasted.
Is it possible to avoid creating many instances?

**Comment by JakeWharton** [comment]
More info is needed to answer this in any meaningful way. What are the interceptors doing that you need to change them constantly?

Also, this is probably much better served as a question on StackOverflow with the 'okhttp' tag...

**Comment by danvinokour** [comment]
Well, im my case i have one client which needs HeaderInterceptor, SignInterceptor and LoggingInterceptor. the other one needs only the Sign and Logging Interceptor and the third one needs only the Logging Interceptor.

But there easily could be cases in which i would need different header interceptors for different clients...

**Comment by swankjesse** [comment]
Please ask this question on [StackOverflow](stackoverflow.com/questions/tagged/okhttp). This tracker is for bug reports (with executable test cases!) and feature requests only.
