### ISSUE TITLE
Very High CPU time on NimbleDroid

### ISSUE THREAD

**Issue by iNoles** [square/okhttp#2321]
NimbeDroid runs only Cold Startup on Android 4.4. This should be a regression from OkHttp 3.0

1533ms okhttp3.OkHttpClient constructor (okhttp3.OkHttpClient$Builder)
    - 1260ms com.android.conscrypt.TrustManagerImpl.getAcceptedIssuers
    - 120ms okhttp3.internal.tls.CertificateAuthorityCouncil constructor
    - 115ms javax.net.ssl.SSLContext.init
    -  65ms  LinkedHashmap.get
    -  54ms com.android.conscrypt.OpenSSLX509Certificate.getSubjectX500Principal

**Comment by swankjesse** [comment]
Aww, shucks. Thanks for reporting this.

**Comment by swankjesse** [comment]
I think we fix by only doi g this work if a CertificatePinner is in use.

We can possibly also move the work to Platform which might be able to get Android’s own certificate cleaner to do that work.

**Comment by swankjesse** [comment]
Released as 3.1.1 and 2.7.4.
