### ISSUE TITLE
OkHttp not throwing exception when WiFi goes down

### ISSUE THREAD

**Issue by vkislicins** [square/okhttp#2328]
I'm having a really strange problem which I think is related to my app using OkHttp. The problem so far appears only with a remote tester so most likely it's device specific issue. My tester claims he tried on several different WiFi networks and the issue persists on all. I couldn't reproduce the issue on quite a few devices and I don't have that device which makes things much more difficult. The tester is using Samsung,Galaxy S 6 Edge on Android 5.1.1. Essentially when the tester switches off his WiFi during file upload, OkHttp is not throwing any exceptions.

In a nutshell, the app uploads some files to Google Storage. The code that does the uploading is wrapped into try/catch block and on catching an exception, it returns an error to my service that deals with the upload queues etc. This is an example of such an exception:

`javax.net.ssl.SSLException: Write error: ssl=0xb9180118: I/O error during system call, Connection timed out
                        E      at com.android.org.conscrypt.NativeCrypto.SSL_write(Native Method)
                        E      at com.android.org.conscrypt.OpenSSLSocketImpl$SSLOutputStream.write(OpenSSLSocketImpl.java:740)
                        E      at okio.Okio$1.write(Okio.java:80)
                        E      at okio.AsyncTimeout$1.write(AsyncTimeout.java:155)
                        E      at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:176)
                        E      at okio.RealBufferedSink.write(RealBufferedSink.java:46)
                        E      at okhttp3.internal.framed.Http2$Writer.dataFrame(Http2.java:492)
                        E      at okhttp3.internal.framed.Http2$Writer.data(Http2.java:485)
                        E      at okhttp3.internal.framed.FramedConnection.writeData(FramedConnection.java:332)
                        E      at okhttp3.internal.framed.FramedStream$FramedDataSink.emitDataFrame(FramedStream.java:516)
                        E      at okhttp3.internal.framed.FramedStream$FramedDataSink.write(FramedStream.java:489)
                        E      at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:176)
                        E      at okio.RealBufferedSink.write(RealBufferedSink.java:96)
`

However, I can't see this exception in the logs returned from the tester. In fact, I'm currently wrapping my OkHttp request into a catch (Exception e) block to catch any possible exception and nothing is happening.

Is that something that has been noticed before? How can I debug this issue and what can I provide you guys to help looking into this issue?

The issue appeared while using OkHttp 2.4 and OkHttp 3

**Comment by vkislicins** [comment]
My API/OkHttp code for uploading files

` OkHttpClient clonedClient = getClonedClientWithTimeout(EXTENDED_TIMEOUT);
        Response response = null;
        try {
            RequestBody requestBody = new RequestBody() {
                private long uploadedBytes;

                @Override
                public MediaType contentType() {
                    return MediaType.parse(upload.getMimeType());
                }

                @Override
                public void writeTo(BufferedSink sink) throws IOException {
                    if (status.getBytesUploaded() > uploadedBytes) {
                        Log.d(TAG,
                                ".writeTo() - setting uploadedBytes to the value provided in the status");
                        uploadedBytes = status.getBytesUploaded();
                        // Move to the first unsent byte
                        source.skip(uploadedBytes);
                    } else if (uploadedBytes > 0) {
                        Log.d(TAG,
                                ".writeTo() - uploadedBytes are more than 0 but less than set in upload status - stopping");
                        return;
                    }

                    byte[] buffer = new byte[8 * 1024];
                    int count = 0;
                    while ((count = source.read(buffer)) != -1) {
                        sink.write(buffer, 0, count);
                        uploadedBytes += count;

                        // Notify listener at each step
                        if (listener != null) {
                            listener.onTransferredBytesCountChanged(uploadedBytes);
                        }
                    }

                    // Notify listener at the end
                    if (listener != null) {
                        listener.onTransferredBytesCountChanged(uploadedBytes);
                    }
                    source.close();
                }
            };
            final Request request = new Request.Builder()
                    .url(uploadUrl)
                    .put(requestBody)
                    .addHeader("Content-Length",
                            status.getUploadingContentLengthValue()) //upper - lower
                    .addHeader("Content-Range", status.getRangeStringValue())
                    .build();

            response = clonedClient.newCall(request).execute();
        } catch (Exception e) {
**            // the code doesn't get here on that specific Samsung device**
            throw new IOException("Unexpected response from server: " + response);
        }
        if (!response.isSuccessful()) {
**             // not getting here either**
            throw new IOException("Unexpected response from server: " + response);
        }

        int statusCode = response.code();`

**Comment by swankjesse** [comment]
This isn’t a particularly actionable request. Could you open a new issue that includes a failing test case? There’s plenty of examples in CallTest.java if you’re looking for a place to get started.
