### ISSUE TITLE
Unable to cache Post Response using OKHTTPClient

### ISSUE THREAD

**Issue by sbonam** [square/okhttp#2331]
Using OKHttpClient in android app. 

I was able to cache response when using GET(with both Cache-Control and Expires headers but failing when using post. Below is the code. Please let me know if anything missing.

okhttp 2.6.0

Below is the sample code.

    @Override
    public Response intercept(Chain chain) throws IOException {
        Response originalResponse = chain.proceed(chain.request());

        int timeToLive = 8*60*60;

        Response newResponse = originalResponse.newBuilder()
                .header("Cache-Control", String.format("max-age=%d, only-if-cached", timeToLive))
                .build();
        return newResponse;
    }

**Comment by swankjesse** [comment]
Please ask this question on [StackOverflow](https://stackoverflow.com/questions/tagged/okhttp). This tracker is for bug reports (with executable test cases!) and feature requests only.
