### ISSUE TITLE
HttpUrl.Builder.addPathSegments(), addEncodedPathSegments()

### ISSUE THREAD

**Issue by Bradeskojest** [square/okhttp#2333]
for example. A bundled segment that looks like this `API/Method/` gets converted to `API%2FMethod`. This is understandable behaviour for `addPathSegment`, but not `addEncodedPathSegment`, which shouldn't try and encode the string.

This is important when one cannot stack segments, but gets pre-glued segment.

**Comment by JakeWharton** [comment]
It isn't encoding the string. You told HttpUrl that you were adding a
single path segment but lied and added more than one. As such, it has to
correct your incorrectly encoded single segment to ensure that it stays a
single segment in the final URL.

**Comment by Bradeskojest** [comment]
Got that. I wanted to do a shortcut since these segments I get from external source. I don't have any control over them.

This means, that in cases, where the segments are given like that - for example from properties, or some external source. It's only possible to add them by manually splitting them on '/' and then add them one by one?
Alternative could be to have one more method, like addPathSegments, which could handle that in one step?

I am not asking for that, just mentioning as a solution for such cases - if there isn't already something in the API that I missed.

Thanks.

**Comment by swankjesse** [comment]
Yeah, addPathSegments is an option we could implement.

**Comment by Xiadalei** [comment]
Yeah, that should be a option, it's hard to maintain the code that long full of redundancy.

**Comment by NightlyNexus** [comment]
This issue can be closed.
https://github.com/square/okhttp/commit/de0d48866fe25f2d2643b936c9b04d14841c9536 adds these methods.

**Comment by Bradeskojest** [comment]
Thank you guys!
