### ISSUE TITLE
Cannot use HTTP/2

### ISSUE THREAD

**Issue by amrishodiq** [square/okhttp#2336]
Hi,
I tried to use OkHttp 3.0.1 to open https://http2.akamai.com/ which is known to be HTTP/2 enabled.
I found that response.protocol() to always returns "http/1.1" instead of "http/2".
I tried both in my desktop and Android.
Here the code I wrote:

```
        String url = "https://http2.akamai.com/";

        List<Protocol> protocols = new ArrayList<>();
            protocols.add(Protocol.SPDY_3);
            protocols.add(Protocol.HTTP_2);
            protocols.add(Protocol.HTTP_1_1);
            
        OkHttpClient client = new OkHttpClient.Builder()
                .protocols(protocols)
                .build();
        Request request = new Request.Builder()
            .url(url)
            .build();
        
        try {
            Response response = client.newCall(request).execute();
            System.out.println("Protocol: "+response.protocol().toString());
        } catch (IOException ex) {
            Logger.getLogger("Test").log(Level.SEVERE, null, ex);
        }
```

Is it normal?

**Comment by ImGauravC** [comment]
Are you running Android 5.0+? http2 support is enabled via ALPN on android 5.0+ only. 
See: 
https://github.com/square/okhttp/blob/master/okhttp/src/main/java/okhttp3/internal/io/RealConnection.java#L212

https://github.com/square/okhttp/blob/master/okhttp/src/main/java/okhttp3/internal/Platform.java#L154

https://github.com/square/okhttp/blob/master/okhttp/src/main/java/okhttp3/internal/Platform.java#L267

**Comment by swankjesse** [comment]
Try adding ALPN:
https://github.com/square/okhttp/wiki/Building#desktop-testing-without-maven
