### ISSUE TITLE
Certificate pinning of not self-signed certificate does not work in OkHttp 3.1.1

### ISSUE THREAD

**Issue by kruliczek** [square/okhttp#2338]
I am trying to pin not self-signed certificate with OkHttpClient.Builder.setSslSocketFactory using a custom ssl context (https://www.owasp.org/index.php/Certificate_and_Public_Key_Pinning#Android). It used to work in previous OkHttp versions but now its failing because:

https://github.com/square/okhttp/blob/master/okhttp/src/main/java/okhttp3/internal/tls/AndroidTrustRootIndex.java

uses org.conscrypt.TrustManagerImpl's method **findTrustAnchorByIssuerAndSignature** which will only return certificates that are self-signed. On the other hand **findTrustAnchorBySubjectAndPublicKey** method finds my certificate. Is it possible to replace the former with the latter?

**Comment by swankjesse** [comment]
I think you need to configure the trust manager with the CA cert that was used to sign your pinned cert.

**Comment by kruliczek** [comment]
But wouldn't it mean trusting all certificates signed by this global CA? I want to limit it down to only my certificate. Also my custom SSLSocketFactory is fine when I use it with javax.net.ssl.HttpsURLConnection

**Comment by swankjesse** [comment]
You can pin any cert in the chain, but the trust manager probably wants self-signed certificates.

**Comment by kruliczek** [comment]
I've closed the issue but still have doubts that it would be much more convenient if OkHttp worked as in case of standard javax.net.ssl.HttpsURLConnection
