### ISSUE TITLE
Infinite connection when trying to reuse a bad connection in ConnectionPool

### ISSUE THREAD

**Issue by mariotaku** [square/okhttp#2339]
First apologize that I can't give detailed information about this. My app [Twidere](https://travis-ci.org/TwidereProject/Twidere-Android) received some report about this after using OkHttp 3.0.0+, seems there're dead or staled connection in ConnectionPool but OkHttp can't detect them, when tried to connect with these reused connections, connection/read/write timeout limit is also not working.

**Comment by swankjesse** [comment]
We can’t take action without steps to reproduce.

**Comment by mariotaku** [comment]
OK, I'll try write a minimum code to reproduce.

**Comment by mariotaku** [comment]
I'm connecting to https://api.twitter.com and https://quitter.se and https://[id].herokuapp.com , seems error rate reduced after turned retryOnConnectionFailure off.

**Comment by mariotaku** [comment]
After using single instance for ConnectionPool, seems problem solved.

**Comment by mariotaku** [comment]
Sorry and thanks, I can confirm it's not an OkHttp issue.
