### ISSUE TITLE
Remove SPDY support

### ISSUE THREAD

**Issue by JakeWharton** [square/okhttp#2340]
Just a tracking issue. Chrome is [removing on May 15th, 2016][1].

 [1]: http://blog.chromium.org/2016/02/transitioning-from-spdy-to-http2.html

**Comment by yschimke** [comment]
I'd suggest if your aim is to remove in 3.4, could 3.3 be a good release to remove it as a default, but allow clients to opt in?

```
public class OkHttpClient implements Cloneable, Call.Factory {
  private static final List<Protocol> DEFAULT_PROTOCOLS = Util.immutableList(
      Protocol.HTTP_2, Protocol.SPDY_3, Protocol.HTTP_1_1);
```
