### ISSUE TITLE
WebSocketListener.onMessage never called

### ISSUE THREAD

**Issue by hovinen** [square/okhttp#2342]
I am running okhttp 3.0.1 with websocket support on Android 4.3.0 and 4.4.2. My app opens a websocket successfully with the server, which sends messages, but the handler WebSocketListener.onMessage is never invoked on the client side.

The code to set up the webscket is as follows:

    Request request = new Request.Builder().url(getWebsocketUrl()).build();
    WebSocketCall call = WebSocketCall.create(okHttpClient, request);
    call.enqueue(new WebSocketListener() {
        @Override
        public void onOpen(WebSocket webSocket, Response response) {
            log.info("onOpen: Successfully opened websocket: {}", response);
        }

        @Override
        public void onFailure(IOException e, Response response) {
            log.error(String.format("Error opening websocket: %s", response), e);
        }

        @Override
        public void onMessage(ResponseBody message) throws IOException {
            log.info("onMessage: Message {}", message);
            EventDto eventDto = gson.fromJson(message.charStream(), EventDto.class);
            handleEvent(eventDto, subscriber);
            message.close();
        }

        @Override
        public void onPong(Buffer payload) {
            log.info("onPong: Payload {}", payload);
        }

        @Override
        public void onClose(int code, String reason) {
            log.info("Websocket closed ({}): {}", code, reason);
        }
    });

The setup code for okhttp itself is as follows:

    @Provides
    Interceptor getAuthorizationInterceptor(final CredentialsProvider credentialsProvider) {
        return new Interceptor() {
            @Override
            public Response intercept(Chain chain) throws IOException {
                String credentials = credentialsProvider.getUsername() + ":"
                        + credentialsProvider.getPassword();
                String basic =
                        "Basic " + Base64.encodeToString(credentials.getBytes(), Base64.NO_WRAP);
                Request request =
                        chain.request().newBuilder().addHeader("Authorization", basic).build();
                return chain.proceed(request);
            }
        };
    }

    @Provides
    OkHttpClient getHttpClient(
            SSLSocketFactory sslSocketFactory, Interceptor authorizationInterceptor) {
        return new OkHttpClient.Builder()
                .sslSocketFactory(sslSocketFactory)
                .hostnameVerifier(new HostnameVerifier() {
                    @Override
                    public boolean verify(String hostname, SSLSession session) {
                        return Objects.equal(hostname, SERVER_IP);
                    }
                })
                .addInterceptor(authorizationInterceptor)
                .readTimeout(5, TimeUnit.MINUTES)
                .build();
    }

The logs indicate that onOpen is called. There are no further errors. However, onMessage is never called, despite the server having sent messages via the channel.

The client setup does work without problems in my integration tests, which do not run in Android. In that setting the connection to the sever is done without ssl and without the authentication interceptor.

The same OkHttpClient is used to communicate with a REST API on the same server, and this communication works without difficulties. Therefore I do not believe that the problem were a error in the configuration of OkHttpClient.

I'd greatly appreciate any insight you can offer to fix this. Thank you.

**Comment by hovinen** [comment]
One further observation: I have determined that the setup works without problems, also on Android devices, when not using SSL. The SSL setup however works just fine when accessing a REST service on the same server. The problem seems to be the combination of SSL and Websocket.

**Comment by artem-zinnatullin** [comment]
Not sure if it'll help you, but I've faced similar issue: as soon as connection was established client app sent a message via WebSockets and no messages were then received by the client. 

The reason was that backend (Python + Tornado for WebSockets)  was not able to parse the message (little error in client app's serialization) and connection then was not used by the backend anymore, on client app it died after readsocket timeout. 

I'd suggest to: log **all callbacks**, open connection and periodically send pings without sending any messages to the server and check if connection stays alive for a long time and if you receive `pong`s. If that works fine, then try to trigger backend to send you a message without sending messages from client. If that works fine too then try to send message from client and see what happens with the connection. 


Another reason of the problem may be an incorrect implementation of WebSockets on the backend side.

**Comment by swankjesse** [comment]
Could you provide an executable test case to demonstrate the problem? This file will get you started:
okhttp-ws-tests/src/test/java/okhttp3/ws/WebSocketCallTest.java

**Comment by swankjesse** [comment]
No clear action for us to take here.
