### ISSUE TITLE
Update to airline 0.7

### ISSUE THREAD

**Issue by puntogil** [square/okhttp#2346]
Hi
any plan to update to airline 0.7 ?
i wrote a little patch for use the latest airline release:
`--- okhttp-parent-2.2.0/okcurl/src/main/java/com/squareup/okhttp/curl/Main.java	2014-12-31 03:52:33.000000000 +0100
+++ okhttp-parent-2.2.0/okcurl/src/main/java/com/squareup/okhttp/curl/Main.java.airline-0.7	2015-03-11 16:09:49.260083651 +0100
@@ -27,11 +27,11 @@
 import com.squareup.okhttp.internal.http.StatusLine;
 import com.squareup.okhttp.internal.spdy.Http20Draft16;
 
-import io.airlift.command.Arguments;
-import io.airlift.command.Command;
-import io.airlift.command.HelpOption;
-import io.airlift.command.Option;
-import io.airlift.command.SingleCommand;
+import io.airlift.airline.Arguments;
+import io.airlift.airline.Command;
+import io.airlift.airline.HelpOption;
+import io.airlift.airline.Option;
+import io.airlift.airline.SingleCommand;
 import java.io.IOException;
 import java.io.InputStream;
 import java.security.cert.CertificateException;`
Thanks in advance
Regards

**Comment by JakeWharton** [comment]
Thanks. Updated for the next version.

**Comment by puntogil** [comment]
Thanks
I would just like to know who is available https://github.com/rvesse/airline (used by Apache Jena)
but need much work for use this fork
Regards
