### ISSUE TITLE
Certificate Revocation Checks?

### ISSUE THREAD

**Issue by kensykora** [square/okhttp#2348]
I've been googling around and haven't stumbled on any concrete examples of how to do certificate revocation checking when connecting to a TLS endpoint. I've found this blog post:

https://commonsware.com/blog/2014/04/17/psa-webview-chrome-accept-revoked-ssl-certificates.html

and a followup:

https://commonsware.com/blog/2014/04/18/more-android-revoked-ssl-certificates.html

But none of them offer solutions or direction toward how you might implement this. Can you offer any suggestions on how I would do this?

**Comment by swankjesse** [comment]
Nothing concrete. I'd love to support certificate stapling but I'm not sure how much access the Java SSL APIsv give us to do that.

**Comment by ikoz** [comment]
Android disables revocation checks by default:

`
            PKIXParameters params = new PKIXParameters(trustAnchor);
            params.setRevocationEnabled(false);
            params.addCertPathChecker(new ExtendedKeyUsagePKIXCertPathChecker(clientAuth, newChain[0]));
            validator.validate(certPath, params);
`

Google security engineers take a pretty aggressive stance on this.

E.g. read this from Adam Langley: https://www.imperialviolet.org/2014/04/19/revchecking.html

**Comment by swankjesse** [comment]
No obvious action for us to take on this.

**Comment by nick2525** [comment]
What about new Android version?

**Comment by yschimke** [comment]
That's a question for Android or Conscrypt. Start by asking there https://github.com/google/conscrypt, As it's not enabled in the default trust manager, it probably requires you configuring it and passing into OkHttp, so it's not a question we can advise on.
