### ISSUE TITLE
Omit unreadable bodies from logging interceptor

### ISSUE THREAD

**Issue by alexrwegener** [square/okhttp#2351]
It would be nice to only log the bodies of human readable content-types. With image heavy applications also using OkHttp as Picasso's downloader using Level.BODY produces lots of noise. 

Content-Type: image/jpeg
Content-Length: 57634
Accept-Ranges: bytes
Access-Control-Allow-Origin: *
Date: Wed, 17 Feb 2016 15:14:45 GMT
Etag: "5c21b2b-e122-52b7fec4f1540"
Last-Modified: Thu, 11 Feb 2016 15:08:29 GMT
Server: ECS (ord/269B)
X-Cache: HIT
OkHttp-Sent-Millis: 1455722085753
OkHttp-Received-Millis: 1455722085767
������JFIF����H��H��������C��			
����C
... etc x 1000

If this is something you all would be open to fixing I'd love to help :)

**Comment by swankjesse** [comment]
We probably need a simple heuristic to detect plaintext.

Here’s my proposal:
1. Decode the body as UTF-8
2. Count replacement characters (U+FFFD) and other non-printable control characters (U+0000, etc.) in the first 16 codepoints of the decoded body.
3. If the count is ≥ 2, we consider it non-text and don’t print.

Checking 2 of 16 is arbitrary. Ideally it matches well with this:
https://en.wikipedia.org/wiki/List_of_file_signatures

**Comment by swankjesse** [comment]
http://stackoverflow.com/questions/7110750/how-do-popular-source-control-systems-differentiate-binary-files-from-text-files
http://eli.thegreenplace.net/2011/10/19/perls-guess-if-file-is-text-or-binary-implemented-in-python

**Comment by swankjesse** [comment]
Thanks @alexrwegener !
