### ISSUE TITLE
Allow Externalizing MockResponse as Classpath Resource

### ISSUE THREAD

**Issue by rwinch** [square/okhttp#2352]
When writing tests with large responses, the tests can be quite cluttered with creating `MockResponse`s. It would be nice if it were possible to externalize `MockResponse` as classpath resources.

I have put together support for this in a project that I am using. See https://github.com/rwinch/github-cla/commit/3df6a5a605923283e1d50d43609430d9ab20aaed

If this is something would be accepted, I'd be willing to send a Pull Request.

**Comment by swankjesse** [comment]
I think this would take MockWebServer in a direction I’m reluctant to take it in. Shouldn’t be much code to make a factory method that builds your responses with whatever data you like.
