### ISSUE TITLE
Feature request | Default settings for all the clients/intercepting every client

### ISSUE THREAD

**Issue by AlmogBaku** [square/okhttp#2357]
When using `URLConnction` there is a way to "intercept" or change the settings for every url-req the pass through the handler(`setURLStreamHandlerFactory()`).

Adding this ability will allow us to intercept the reqs on an application level(incl. 3rd parties)- i.e. sending the whole app to go through a proxy.

**Comment by swankjesse** [comment]
I’m reluctant to implement something this global. It fights against our natural tendencies to avoid global state & use tools like dependency injection for broad configuration. If you’d like this, I recommend starting by forking the project & seeing how that works out. If it works out well send me a link to the code & I’ll reconsider!
