### ISSUE TITLE
HttpUrl Serializable

### ISSUE THREAD

**Issue by rfc2822** [square/okhttp#2367]
Hello,

Suggestion: Make HttpUrl Serializable (or even Parcelable, but that would be Android-specific).

Use case: Android app which stores some Web service (CalDAV) configuration. Because okhttp is heavily used, most URLs are HttpUrls and not URI/URL/Uri. Now, to pass data between fragments etc., it would be very useful to have an HttpUrl which implements Serializable.

**Comment by swankjesse** [comment]
Is it possible to use toString() ? Serializable is a pretty awful technology. Otherwise we'll take a pull request, but it'll probably need to use readResolve or similar so we don't need to think about it in our implementation.

**Comment by rfc2822** [comment]
I have now replaced HttpURL by URI (which is Serializable) in the data class (a set of URLs and other data describing a service), but it would be nice to be able to serialize data structures with HttpURLs.

Couldn't the serialization just be done by `toString` and `parse`?

**Comment by swankjesse** [comment]
Yeah, that’s exactly what the serialization should do internally.

**Comment by swankjesse** [comment]
I’ve decided to deliberately not fix this because it’s enabling. You should not be using Java Serialization; it’s insecure, inefficient, and has trouble with versioning.

**Comment by wingsum93** [comment]
hi, why not use gson to covert between text and object class, it is easy and fast and simple

**Comment by JakeWharton** [comment]
That would be ridiculous to use here. You can just call toString() /
parse() or write a Parcelable wrapper type which does it for you.

**Comment by alexis-depalle-ma** [comment]
Hi,

Sry for necroposting but i'm facing the same issue : i have an object with many HttpUrl (because this class is so powerfull) and i use it in fragment. 

Problem: when the system automaticaly save state and use 'android.os.Parcel.writeSerializable(Parcel.java:1843)' -> it crash saying HttpUrl isn't serializable

I don't find anyway to override Serialization for HttpUrl object, can you please give me an idea ?

**Comment by JakeWharton** [comment]
Call `toString()` and write it as a string.

**Comment by alexis-depalle-ma** [comment]
> Call `toString()` and write it as a string.

When ? I don't have an override Serializer to do it

**Comment by JakeWharton** [comment]
I'm saying don't call `writeSerializable`, instead, call `writeString` by calling `toString()` on your `HttpUrl`.

**Comment by JakeWharton** [comment]
Fragments do not persist state automatically. So something else is doing this on your behalf and that is the library or tool which you need to pursue for a mechanism to hook in some kind of serializer.
