### ISSUE TITLE
ResponseBody is null when a WebSocket call fails (e.g. http 500)

### ISSUE THREAD

**Issue by iocanel** [square/okhttp#2368]
We are using okhttp in https://github.com/fabric8io/kubernetes-client. 

In some cases the websocket calls we create fail with http 500 + json message that contains a detailed description to the problem.

Unfortunately, the response cannot be read from the Response body or message and we are left in the dark.

Test Case to reproduce the problem: https://gist.github.com/iocanel/b3a9cb6d62e5aabe5426

Thanks

**Comment by JakeWharton** [comment]
Somewhat related to #2264 as well. Will look.

**Comment by iocanel** [comment]
FWIW I forgot to mention that I get this with versions 2.7.2, 2.7.3 and 2.7.4 (haven't tried older ones).

**Comment by dave-r12** [comment]
This should be fixed with OkHttp 3.3.1, see #2374 and #2583.
