### ISSUE TITLE
Timeout Issue in emulator with API Level 16

### ISSUE THREAD

**Issue by elrufoelrufo** [square/okhttp#2370]
Hello,

As you can see in the code below. The timeout sets is not working properly in emulator with api level 16. Find below the code. And Log cat where you can see the execution time and connectTimeoutMillis and readTimeoutMillis. Can you please help me? I'm using  com.squareup.okhttp3:okhttp:3.1.2

**Code :**
`final OkHttpClient client = new OkHttpClient.Builder()
                    .connectTimeout(2000, TimeUnit.MILLISECONDS)
                    .readTimeout(4000, TimeUnit.MILLISECONDS)
                    .build();

            Request request = new Request.Builder()
                    .url(url_all_emisoras)
                    .get()
                    .build();
            //Añadimos la autenticación
            request = addBasicAuthHeaders(request);

            Response response=null ;
            try {
                Log.d(LOG_TAG, "MS connect " + client.connectTimeoutMillis() + " Ms Read " + client.readTimeoutMillis());
                response = client.newCall(request).execute();
            } catch (IOException e) {
                Log.w(LOG_TAG, "IOException try call : " + e.getMessage());
                return false;
            }`
LOG : 
02-25 **03:31:45.498** 5733-5803/com.radiofmapp.radioargentina D/SplashActivity: MS connect 2000 Ms Read 4000
02-25 **03:32:26.429** 5733-5803/com.radiofmapp.radioargentina W/SplashActivity: IOException try call : Unable to resolve host "api.radiofmapp.com": No address associated with hostname

Thanks. Regards.

**Comment by swankjesse** [comment]
Sadly, there’s no timeout for DNS yet.
https://github.com/square/okhttp/issues/95
