### ISSUE TITLE
How to use Request.Builder() with ip address?

### ISSUE THREAD

**Issue by csnu17** [square/okhttp#2380]
I want to make request from Request.Builder() such as
```
new Request.Builder()
                .url(url)
                .post(formBody)
                .build();
```

But when the url is 192.168.1.xxx:xxxx/auth/facebook/token, it found the error 
```
java.lang.IllegalArgumentException: unexpected url: 192.168.1.xxx:xxxx/auth/facebook/token
```

So, how can I make the request from the url that is a ip address? Thank you.

**Comment by swankjesse** [comment]
Please use stackoverflow for questions!
