### ISSUE TITLE
Set-Cookie Secure Flag support

### ISSUE THREAD

**Issue by xeroxnir** [square/okhttp#2389]
Hi, 

I searched all through the documentation and couldn't find if OkHttp supports not sending the cookie in HTTP when the Secure flag is set on a Cookie response. I just found that it is parsed properly. 

Regards,
Joaquín

**Comment by swankjesse** [comment]
It’s an implementation detail of the `CookieJar` that you use. If you use `JavaNetCookieJar`, then it’s an implementation detail of whatever `CookieHandler` that thing is using.

If you use this library, you’re all good:
https://github.com/franmontiel/PersistentCookieJar
