### ISSUE TITLE
addPathSegments does't follow documentation described behavior

### ISSUE THREAD

**Issue by ozodrukh** [square/okhttp#2399]
Documentation says:
`If pathSegments starts with a slash, the resulting URL will have empty path segment` but it is misleading because it doesn't going to clear path.

So for example i have `https://github.com/square/okhttp/issues/` and I need to change it to 
`https://github.com/ozodrukh`

```java
HttpUrl.parse("https://github.com/square/okhttp/issues/")
        .newBuilder()
        .addPathSegment("/ozodrukh")
        .build()
```

and final link will be `https://github.com/square/okhttp/issues//ozodrukh`.

**Comment by swankjesse** [comment]
Yes, the resulting URL has an empty path segment, it’s the segment between `issues` and `ozodrukh`. (Note the double slash.)

The method you’re probably looking for is `resolve()`.

**Comment by ozodrukh** [comment]
@swankjesse Thanks, :cool:  i'm using `newBuilder(link)` (same as resolve but makes Builder instance) 

Is it conceived behavior?

**Comment by swankjesse** [comment]
Double slashing is the bad thing that happens if you call addPathSegments() with a leading slash. Most people probably don't want that, but it is not an error.

newBuilder(link) is perfect.
