### ISSUE TITLE
Use X509TrustManagerExtensions on Android 17+

### ISSUE THREAD

**Issue by swankjesse** [square/okhttp#2407]
We should use this instead of CertificateChainCleaner on Android 17+. It’s more likely to work reliably as Android grows.

It’s possible that our current approach will break on Android N, which [changes the way](https://android-review.googlesource.com/#/c/207611/) that certificate chains are constructed.

We’ll need to keep the current implementation for Android API versions less than 17, and for desktop Java.

**Comment by ikoz** [comment]
@swankjesse great. Every 'chain building' implementation does things in a slightly different way. 
If manually rebuilding the chain after the system did it once, you're bound to end up with different chains in corner cases.
