### ISSUE TITLE
Transparent GZIP decompression only returns single line of document from response.

### ISSUE THREAD

**Issue by drewdiddy611** [square/okhttp#2416]
I'm having an issue with transparent GZIP decompression.  

I'm not sure if this is the webserver returning a weird response, I'm also not sure what kind of information you need from me in this case.

Basically, If I let OkHttp handle decompression transparently, it only returns a single line of the document from the response.  However, when I handle decompression myself using a GZIPInputStream, and read from it using a BufferedReader from `body().byteStream()`, I get the entire document. This way also gives me connection leaked warnings in my Logcat output, even though I'm calling `body().close()` after every request. (Even if I don't use the response body). 

Please let me know if you need any more information, I would be happy to provide.

P.S. I'm working on adding code and a test case to this post instead of using links. Just wanted to get it up to get initial responses on whether I was just crazy or not. :-)

**EDIT**

After building a simple test case, using Eclipse/Java environment (instead of Android libraries). This issue is not present. In both cases, the entire document is fetched correctly.  This issue only appears in the android app and for the specific server I am sending the request to, Response headers will be below...

Dependencies under gradle file.

dependencies {
    ...
    compile 'com.android.support:appcompat-v7:23.2.1'
    compile 'com.android.support:design:23.2.1'
    compile 'com.squareup.okhttp3:okhttp:3.2.0'
    compile 'com.android.support:support-v4:23.2.1'
}

Response headers from the site:

Cache-Control: private
Content-Type: text/html; charset=utf-8
Vary: Accept-Encoding
Server: Microsoft-IIS/7.5
Set-Cookie: ASP.NET_SessionId=<omitted>; path=/; HttpOnly
X-AspNet-Version: 2.0.50727
X-Powered-By: ASP.NET
Date: Sat, 19 Mar 2016 03:17:25 GMT
OkHttp-Sent-Millis: 1458358005672
OkHttp-Received-Millis: 1458358005742

Again, this only happens in the android app, and only when sending the request to this specific website.  If I send the request to google.com or facebook.com, it succeeds. But for some reason, everything works fine when not using the android libraries.

**Comment by drewdiddy611** [comment]
Test case in android system that isn't working.
    // Create the builder.
    Request.Builder getRequestBuilder = new Request.Builder();

    // Set URL.
    getRequestBuilder.url(ALERT_LOGIN_URL);

    // Build the request.
    Request getRequest = getRequestBuilder.build();

    // Fire
    Response getResponse = new OkHttpClient().newCall(getRequest).execute();        
    Log.d("APP_STATUS", "Reading from stream: " + getResponseBodyAsString(getResponse));

    // Create the builder.
    getRequestBuilder = new Request.Builder();

    // Set URL.
    getRequestBuilder.url(ALERT_LOGIN_URL);

    Log.d("APP_STATUS", "SPLIT");

    // Build the request.
    getRequest = getRequestBuilder.build();

    // Fire
    getResponse = new OkHttpClient().newCall(getRequest).execute();
    Log.d("APP_STATUS", "Reading from body().string(): " + getResponse.body().string());

[Check out this picture](http://imgur.com/D7XcT8J), you can clearly see the first request is working, but the second request (after the SPLIT) only gives a tiny portion of the document.

**Comment by swankjesse** [comment]
Is the Android logger truncating?

**Comment by swankjesse** [comment]
Ie. what happens if you log the string’s length, rather than the string itself?

**Comment by drewdiddy611** [comment]
D/APP_STATUS: Reading from stream: 5201
D/APP_STATUS: SPLIT
D/APP_STATUS: Reading from body().string(): 6036

The lengths are different o.O

**Comment by swankjesse** [comment]
And if you don't trim?

**Comment by swankjesse** [comment]
Ie. remove the trim() here, and make sure you don't lose `\r` and `\r\n` characters in the process?
```
    while ((line = br.readLine()) != null) {
      sb.append(line.trim());
    }
```

**Comment by drewdiddy611** [comment]
Good point XD forgot to take that out. They're still different though.
D/APP_STATUS: Reading from stream: 5816
D/APP_STATUS: SPLIT
D/APP_STATUS: Reading from body().string(): 6036

**Comment by swankjesse** [comment]
Looks like a problem with logging. All good.

**Comment by drewdiddy611** [comment]
Nah, I'm still trying to put this together without leaving out carriage returns/newlines... dunno why it's so hard XD im tired.

**Comment by drewdiddy611** [comment]
They're the same length, but it's not a logging problem... my app crashes when I let OkHttp handle it transparently...

**Comment by drewdiddy611** [comment]
Okay, so it was a logging problem XD. Thanks for the help anyway..  It's working fine now.. I dunno what I did. Great product you guys have here, looks like this was user error.

**Comment by swankjesse** [comment]
All good. Truncating logs are annoying. You might be interested in this:
https://github.com/square/okhttp/tree/master/okhttp-logging-interceptor
