### ISSUE TITLE
okhttp dependency okio 1.6.0,but this version of okio  does not have this feature which has fixed "getsockname failed: EBADF (Bad file number)"

### ISSUE THREAD

**Issue by corerzhang** [square/okhttp#2422]
okhttp dependency okio 1.6.0,but this version of okio  does not have the [feature](https://github.com/square/okio/pull/170) that has fixed "getsockname failed: EBADF (Bad file number)"

**Comment by swankjesse** [comment]
Is this a request for us to release an updated version of okio?

**Comment by corerzhang** [comment]
yeah，I hope you release an updated version of okio, and okhttp dependent newest version of okio to avoid crashing beacause of android internal problem "getsockname failed: EBADF (Bad file number)".

**Comment by swankjesse** [comment]
Got it. If you’d like in the interim you can use the unreleased snapshot of Okio.
