### ISSUE TITLE
Creating RequestBody from an InputStream

### ISSUE THREAD

**Issue by jianghaolu** [square/okhttp#2424]
I was looking at RequestBody.java and I can't find an overload for create() like this:
```java
RequestBody.create(MediaType contentType, InputStream stream)'
```
Is there a reason not to implement this? This is pretty useful when piping from one stream into an upload job. The overload accepting a `File` is useful for files but that's not the only scenario where buffering in memory does not work.

Please shed some lights if I'm missing something. Thanks!

**Comment by swankjesse** [comment]
In general we want to be able to replay a request body multiple times. But input streams can only be consumed once.

**Comment by jianghaolu** [comment]
So if I provide a large file it will be read multiple times?

**Comment by swankjesse** [comment]
Yep. For example, if you get a 308 redirect.

**Comment by jianghaolu** [comment]
Or retries. Makes sense! Thanks.

**Comment by MIFind** [comment]
Course of project , i need the overload ,  do you find answers?

**Comment by JakeWharton** [comment]
The `Uri` is what you should create a `RequestBody` from then. As if it needs to be written twice it can have its stream opened twice.

**Comment by bpappin** [comment]
@JakeWharton yes i agree, but there is no `RequestBody.create(MimeType, Uri)` that i can see.

The only way I can see to do it is to override RequetBody and source from the file descriptor.

**Comment by JakeWharton** [comment]
Yep. That's the right way.
