### ISSUE TITLE
NullPointerException in AndroidTrustRootIndex (Okhttp 2.7.5) #2378

### ISSUE THREAD

**Issue by mahdihijazi** [square/okhttp#2425]
Issue is not resolved in 2.7.5

Just doubled checked it again:
1. Device: Nexus 9/ Android 5.1.1
2. Output of System.out.println(okHttpClient.getSslSocketFactory().getClass());
`class android.net.SSLCertificateSocketFactory`
3. making sure I am using the correct version by calling this
`./gradlew -q dependencies AppName:dependencies  | grep com.squareup.okhttp:okhttp`

and this is the result:

+--- com.squareup.okhttp:okhttp:2.7.5
+--- com.squareup.okhttp:okhttp-urlconnection:2.7.5
|    \--- com.squareup.okhttp:okhttp:2.7.5 (*)
|    +--- com.squareup.okhttp:okhttp:2.7.5 (*)
     +--- com.squareup.okhttp:okhttp:2.4.0 -> 2.7.5 (*)
     +--- com.squareup.okhttp:okhttp-urlconnection:2.4.0 -> 2.7.5 (*)
     |    \--- com.squareup.okhttp:okhttp:2.5.0 -> 2.7.5 (*)
          +--- com.squareup.okhttp:okhttp:2.5.0 -> 2.7.5 (*)
+--- com.squareup.okhttp:okhttp:2.7.5
+--- com.squareup.okhttp:okhttp-urlconnection:2.7.5
|    \--- com.squareup.okhttp:okhttp:2.7.5 (*)
|    +--- com.squareup.okhttp:okhttp:2.7.5 (*)
|    +--- com.squareup.okhttp:okhttp:2.4.0 -> 2.7.5 (*)
|    +--- com.squareup.okhttp:okhttp-urlconnection:2.4.0 -> 2.7.5 (*)
|    |    \--- com.squareup.okhttp:okhttp:2.5.0 -> 2.7.5 (*)
|         +--- com.squareup.okhttp:okhttp:2.5.0 -> 2.7.5 (*)
|    +--- com.squareup.okhttp:okhttp:2.5.0 -> 2.7.5
|    |    +--- com.squareup.okhttp:okhttp:2.5.0 -> 2.7.5 (*)
|    |    +--- com.squareup.okhttp:okhttp-ws:2.5.0
|    |    |    \--- com.squareup.okhttp:okhttp:2.5.0 -> 2.7.5 (*)
|         \--- com.squareup.okhttp:okhttp:2.5.0 -> 2.7.5 (*)
+--- com.squareup.okhttp:okhttp:2.7.5 (*)
\--- com.squareup.okhttp:okhttp-urlconnection:2.7.5
     \--- com.squareup.okhttp:okhttp:2.7.5 (*)
|    +--- com.squareup.okhttp:okhttp:2.5.0 -> 2.7.5
|    |    +--- com.squareup.okhttp:okhttp:2.5.0 -> 2.7.5 (*)
|    |    +--- com.squareup.okhttp:okhttp-ws:2.5.0
|    |    |    \--- com.squareup.okhttp:okhttp:2.5.0 -> 2.7.5 (*)
|         \--- com.squareup.okhttp:okhttp:2.5.0 -> 2.7.5 (*)
+--- com.squareup.okhttp:okhttp:2.7.5 (*)
\--- com.squareup.okhttp:okhttp-urlconnection:2.7.5
     \--- com.squareup.okhttp:okhttp:2.7.5 (*)
+--- com.squareup.okhttp:okhttp:2.7.5
+--- com.squareup.okhttp:okhttp-urlconnection:2.7.5
|    \--- com.squareup.okhttp:okhttp:2.7.5 (*)
|    +--- com.squareup.okhttp:okhttp:2.7.5 (*)
|    \--- com.squareup.okhttp:okhttp:2.2.0 -> 2.7.5 (*)
     +--- com.squareup.okhttp:okhttp:2.4.0 -> 2.7.5 (*)
     +--- com.squareup.okhttp:okhttp-urlconnection:2.4.0 -> 2.7.5 (*)
     |    \--- com.squareup.okhttp:okhttp:2.5.0 -> 2.7.5 (*)
          +--- com.squareup.okhttp:okhttp:2.5.0 -> 2.7.5 (*)
+--- com.squareup.okhttp:okhttp:2.7.5
+--- com.squareup.okhttp:okhttp-urlconnection:2.7.5
|    \--- com.squareup.okhttp:okhttp:2.7.5 (*)
|    +--- com.squareup.okhttp:okhttp:2.7.5 (*)
|    \--- com.squareup.okhttp:okhttp:2.2.0 -> 2.7.5 (*)
|    +--- com.squareup.okhttp:okhttp:2.4.0 -> 2.7.5 (*)
|    +--- com.squareup.okhttp:okhttp-urlconnection:2.4.0 -> 2.7.5 (*)
|    |    \--- com.squareup.okhttp:okhttp:2.5.0 -> 2.7.5 (*)
|         +--- com.squareup.okhttp:okhttp:2.5.0 -> 2.7.5 (*)
|    +--- com.squareup.okhttp:okhttp:2.5.0 -> 2.7.5
|    |    +--- com.squareup.okhttp:okhttp:2.5.0 -> 2.7.5 (*)
|    |    +--- com.squareup.okhttp:okhttp-ws:2.5.0
|    |    |    \--- com.squareup.okhttp:okhttp:2.5.0 -> 2.7.5 (*)
|         \--- com.squareup.okhttp:okhttp:2.5.0 -> 2.7.5 (*)
+--- com.squareup.okhttp:okhttp:2.7.5 (*)
\--- com.squareup.okhttp:okhttp-urlconnection:2.7.5
     \--- com.squareup.okhttp:okhttp:2.7.5 (*)
|    +--- com.squareup.okhttp:okhttp:2.5.0 -> 2.7.5
|    |    +--- com.squareup.okhttp:okhttp:2.5.0 -> 2.7.5 (*)
|    |    +--- com.squareup.okhttp:okhttp-ws:2.5.0
|    |    |    \--- com.squareup.okhttp:okhttp:2.5.0 -> 2.7.5 (*)
|         \--- com.squareup.okhttp:okhttp:2.5.0 -> 2.7.5 (*)
+--- com.squareup.okhttp:okhttp:2.7.5 (*)
\--- com.squareup.okhttp:okhttp-urlconnection:2.7.5
     \--- com.squareup.okhttp:okhttp:2.7.5 (*)
+--- com.squareup.okhttp:okhttp:2.7.5
+--- com.squareup.okhttp:okhttp-urlconnection:2.7.5
|    \--- com.squareup.okhttp:okhttp:2.7.5 (*)
|    +--- com.squareup.okhttp:okhttp:2.7.5 (*)
     +--- com.squareup.okhttp:okhttp:2.4.0 -> 2.7.5 (*)
     +--- com.squareup.okhttp:okhttp-urlconnection:2.4.0 -> 2.7.5 (*)
     |    \--- com.squareup.okhttp:okhttp:2.5.0 -> 2.7.5 (*)
          +--- com.squareup.okhttp:okhttp:2.5.0 -> 2.7.5 (*)
+--- com.squareup.okhttp:okhttp:2.7.5
+--- com.squareup.okhttp:okhttp-urlconnection:2.7.5
|    \--- com.squareup.okhttp:okhttp:2.7.5 (*)
|    +--- com.squareup.okhttp:okhttp:2.7.5 (*)
     +--- com.squareup.okhttp:okhttp:2.4.0 -> 2.7.5 (*)
     +--- com.squareup.okhttp:okhttp-urlconnection:2.4.0 -> 2.7.5 (*)
     |    \--- com.squareup.okhttp:okhttp:2.5.0 -> 2.7.5 (*)
          +--- com.squareup.okhttp:okhttp:2.5.0 -> 2.7.5 (*)
|    +--- com.squareup.okhttp:okhttp:2.5.0 -> 2.7.5
|    |    +--- com.squareup.okhttp:okhttp:2.5.0 -> 2.7.5 (*)
|    |    +--- com.squareup.okhttp:okhttp-ws:2.5.0
|    |    |    \--- com.squareup.okhttp:okhttp:2.5.0 -> 2.7.5 (*)
|         \--- com.squareup.okhttp:okhttp:2.5.0 -> 2.7.5 (*)
+--- com.squareup.okhttp:okhttp:2.7.5 (*)
\--- com.squareup.okhttp:okhttp-urlconnection:2.7.5
     \--- com.squareup.okhttp:okhttp:2.7.5 (*)
|    +--- com.squareup.okhttp:okhttp:2.5.0 -> 2.7.5
|    |    +--- com.squareup.okhttp:okhttp:2.5.0 -> 2.7.5 (*)
|    |    +--- com.squareup.okhttp:okhttp-ws:2.5.0
|    |    |    \--- com.squareup.okhttp:okhttp:2.5.0 -> 2.7.5 (*)
|         \--- com.squareup.okhttp:okhttp:2.5.0 -> 2.7.5 (*)
+--- com.squareup.okhttp:okhttp:2.7.5 (*)
\--- com.squareup.okhttp:okhttp-urlconnection:2.7.5
     \--- com.squareup.okhttp:okhttp:2.7.5 (*)
+--- com.squareup.okhttp:okhttp:2.7.5
+--- com.squareup.okhttp:okhttp-urlconnection:2.7.5
|    \--- com.squareup.okhttp:okhttp:2.7.5 (*)
|    +--- com.squareup.okhttp:okhttp:2.7.5 (*)
     +--- com.squareup.okhttp:okhttp:2.4.0 -> 2.5.0
     +--- com.squareup.okhttp:okhttp-urlconnection:2.4.0
     |    \--- com.squareup.okhttp:okhttp:2.4.0 -> 2.5.0 (*)
     |    \--- com.squareup.okhttp:okhttp:2.5.0 (*)
          +--- com.squareup.okhttp:okhttp:2.5.0 (*)
|    \--- com.squareup.okhttp:okhttp:2.2.0 -> 2.7.5
+--- com.squareup.okhttp:okhttp:2.7.5 (*)
+--- com.squareup.okhttp:okhttp-urlconnection:2.7.5
|    \--- com.squareup.okhttp:okhttp:2.7.5 (*)
     +--- com.squareup.okhttp:okhttp:2.4.0 -> 2.7.5 (*)
     +--- com.squareup.okhttp:okhttp-urlconnection:2.4.0 -> 2.7.5 (*)
     |    \--- com.squareup.okhttp:okhttp:2.5.0 -> 2.7.5 (*)
          +--- com.squareup.okhttp:okhttp:2.5.0 -> 2.7.5 (*)
+--- com.squareup.okhttp:okhttp:2.7.5
+--- com.squareup.okhttp:okhttp-urlconnection:2.7.5
|    \--- com.squareup.okhttp:okhttp:2.7.5 (*)
|    +--- com.squareup.okhttp:okhttp:2.7.5 (*)
     +--- com.squareup.okhttp:okhttp:2.4.0 -> 2.5.0
     +--- com.squareup.okhttp:okhttp-urlconnection:2.4.0
     |    \--- com.squareup.okhttp:okhttp:2.4.0 -> 2.5.0 (*)
     |    \--- com.squareup.okhttp:okhttp:2.5.0 (*)
          +--- com.squareup.okhttp:okhttp:2.5.0 (*)
|    +--- com.squareup.okhttp:okhttp:2.5.0 -> 2.7.5
|    |    +--- com.squareup.okhttp:okhttp:2.5.0 -> 2.7.5 (*)
|    |    +--- com.squareup.okhttp:okhttp-ws:2.5.0
|    |    |    \--- com.squareup.okhttp:okhttp:2.5.0 -> 2.7.5 (*)
|         \--- com.squareup.okhttp:okhttp:2.5.0 -> 2.7.5 (*)
+--- com.squareup.okhttp:okhttp:2.7.5 (*)
\--- com.squareup.okhttp:okhttp-urlconnection:2.7.5
     \--- com.squareup.okhttp:okhttp:2.7.5 (*)

**Comment by swankjesse** [comment]
From the other issue, stacktrace is:
```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
                                                              at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:135)
                                                           Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
                                                              at com.squareup.okhttp.internal.tls.AndroidTrustRootIndex.get(AndroidTrustRootIndex.java:57)
                                                              at com.squareup.okhttp.internal.Platform$Android.trustRootIndex(Platform.java:266)
                                                              at com.squareup.okhttp.internal.io.RealConnection.trustRootIndex(RealConnection.java:248)
                                                              at com.squareup.okhttp.internal.io.RealConnection.connectTls(RealConnection.java:206)
                                                              at com.squareup.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:149)
                                                              at com.squareup.okhttp.internal.io.RealConnection.connect(RealConnection.java:112)
                                                              at com.squareup.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:184)
                                                              at com.squareup.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
                                                              at com.squareup.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
                                                              at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:281)
                                                              at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224)
                                                              at com.squareup.okhttp.Call.getResponse(Call.java:286)
```

**Comment by swankjesse** [comment]
It’s attempting and failing to dereference the trust manager.
```
      Method method = trustManager.getClass().getDeclaredMethod(
          "findTrustAnchorByIssuerAndSignature", X509Certificate.class);
```

**Comment by swankjesse** [comment]
If you’re willing to switch to OkHttp 3, there’s a new method coming in 3.3 that lets you control this directly:
`OkHttpClient.Builder.sslSocketFactory(SSLSocketFactory, X509TrustManager)`

Otherwise we need to investigate _why_ the trust manager isn’t being found in your app. My suspicion is that it’s a 3rd party SDK. You can probably find this with this:
```
        SSLContext sslContext = SSLContext.getInstance("TLS");
        sslContext.init(null, null, null);
        System.out.println(sslContext.getSocketFactory().getClass());
```

**Comment by mahdihijazi** [comment]
After we traced the issue, we found the reason that we are using **SSLSessionCache** wich depends on the **SSLCertificateSocketFactory** which makes Android.trustManager inside the Platform class to failed getting the **SSLParametersImpl** because this one doesn't have the **sslParameters** field at all.

So basically the reflecting code failed way before trying to get the trust manager.

**Comment by swankjesse** [comment]
@mahdihijazi thanks for your thorough investigation! In OkHttp 3.3 we’re adding a new API that lets you specify the SSLSocketFactory and X509TrustManager separately. Will this work? Or can we teach our Platform class to detect the SSLSessionCache case?

**Comment by mahdihijazi** [comment]
@swankjesse a quick look in **SSLCertificateSocketFactory** give me the impression that we can use **getDelegate()** that returns the **SSLSocketFactrory**, and from there we can continue looking for the trust manager the same way we have now.

Looks like SSLCertificateSocketFactory compose the expected SSLSocketFactrory.

Unfortunately upgrading to okhttp 3 is not an option short-term.

**Comment by swankjesse** [comment]
We’re not going to do any further releases of OkHttp 2.x.
