### ISSUE TITLE
TCP Fast Open support

### ISSUE THREAD

**Issue by karthikrg** [square/okhttp#2429]
https://en.wikipedia.org/wiki/TCP_Fast_Open
Would be great to get this into OkHttp since it could improve performance in high latency networks.

**Comment by swankjesse** [comment]
Know any webservers that support it? Know if Android supports it?

**Comment by swankjesse** [comment]
Might be better to get this feature in AOSP first.
https://code.google.com/p/android/issues/detail?id=179517

**Comment by karthikrg** [comment]
AOSP does not support it today as far as I know, but chrome on Android does ostensibly because they have their own TCP stack. iOS 9 supports it via connectx.

We plan to support this in our internal webservers soon pending a kernel upgrade to 3.17.

**Comment by swankjesse** [comment]
Closing for now. If AOSP ever gets fast open, we’ll reopen.

**Comment by mufumbo** [comment]
@swankjesse do you know if this got AOSP? it greatly improve user experience.

Nougat should be on kernel 4, so definitely supports at kernel level. Do you think there's anything to be done internally for okhttp?

**Comment by swankjesse** [comment]
Unsure what we’ll need to do.

**Comment by yschimke** [comment]
If Netty hasn't done this, not sure OkHttp should be leading this charge.  particuarly given moves to Https everywhere and Tls 1.3 and Quic in future.

**Comment by UjuiUjuMandan** [comment]
> If Netty hasn't done this,

They implemented this one year later since this was closed. Reopen?

**Comment by yschimke** [comment]
Isn't Netty using native sockets via epoll or iouring?

@UjuiUjuMandan can you send a sample of how to use this with java.net.Socket?
