### ISSUE TITLE
InterruptedException when using takeRequest()

### ISSUE THREAD

**Issue by MRodriguess** [square/okhttp#2431]
Hi Everyone
We started using MockWebServer and it's working like a charme, except for one little thing we haven't yet been able to solve. When asserting the request that was made. using `server.takeRequest()` we got a java.lang.InterruptedException and we are not able to verify the requests.

We call takeRequest after issuing the request with Retrofit . If anybody has faced this kind of problem I would be thankful for any help.

**Comment by swankjesse** [comment]
Are you calling `Thread.interrupt()` ? We haven’t built MockWebServer to work with that, which also impacts certain ways of shutting down Executors

**Comment by MRodriguess** [comment]
Hi thanks swankjess for answering. 
No I not calling thread.interrupt():
I was just trying to assert that the correct request was being made to confirm the endpoint from the api.

**Comment by swankjesse** [comment]
Something is calling Thread.interrupt() and causing this. Not much we can do. If you think otherwise, please send us a test case to demonstrate expected and actual behavior.
