### ISSUE TITLE
Fatal Exception: java.lang.IllegalStateException: Unable to take ownership of connection.

### ISSUE THREAD

**Issue by iceteahh** [square/okhttp#2440]
This happen on version 3.2.0 with 300+ crashes in 30 days. Details:
`Fatal Exception: java.lang.IllegalStateException: Unable to take ownership of connection.
       at com.squareup.okhttp.ws.WebSocketCall.createWebSocket(SourceFile:157)
       at com.squareup.okhttp.ws.WebSocketCall.access$000(SourceFile:42)
       at com.squareup.okhttp.ws.WebSocketCall$1.onResponse(SourceFile:102)
       at com.squareup.okhttp.Call$AsyncCall.execute(SourceFile:168)
       at com.squareup.okhttp.internal.NamedRunnable.run(SourceFile:33)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)`

![image](https://cloud.githubusercontent.com/assets/5756363/14058933/69742c40-f362-11e5-8fa4-b55aeb71035d.png)

Please help me fix it.

**Comment by iceteahh** [comment]
No one care about it :(. I need your support.

**Comment by swankjesse** [comment]
Could you provide a test case to reproduce the problem? That usually makes fixing easy.

**Comment by iceteahh** [comment]
I can't give you a test case. I received that report by fabric.io. I have no idea when it happen.

**Comment by iNoles** [comment]
When I was looking to that error message, I found it on https://android.googlesource.com/platform/external/okhttp/+/refs/heads/master/okhttp-ws/src/main/java/com/squareup/okhttp/ws/WebSocketCall.java#157

**Comment by shobhitpuri** [comment]
+1. I'm getting lot of crashes because of the same exception too. However I'm unable to find the source. I'm using 2.5.0 version though.

**Comment by dave-r12** [comment]
@iceteahh @shobhitpuri are either of you explicitly calling cancel()?

**Comment by rafalniski** [comment]
I also encountered this issue, we are using Socket.io too. Stacktrace: http://crashes.to/s/1798f721c8f

**Comment by shobhitpuri** [comment]
@rafalniski Now I close the socket as soon as the app goes into background. Haven't seen the exception since then.

**Comment by JakeWharton** [comment]
This should have been fixed as a side-effect of the stream allocation model. Please re-open if it's still a problem on version 3.4.0 or newer.
