### ISSUE TITLE
Unable to decompress deflate

### ISSUE THREAD

**Issue by HakuLess** [square/okhttp#2447]
Request requestComment = new Request.Builder()
                //.header("Accept-Encoding", "defalte")
                .removeHeader("Accept-Encoding")
                .url(commentUri)
                .build();
no matter if i set header or not, it still retruns error, just like that , ��Y�]Wv���nՃ��u�L{8R���`�V�]�. I found some answer about gzip, it says don't set header will help, i tested it, but it didn't help in my case. The url is http://comment.bilibili.com/3885454.xml. Thanks for help~

**Comment by JakeWharton** [comment]
OkHttp does not support deflate automatically. If the server returns a deflate body you need to use Okio's `InflaterSource` or `InflateInputStream` to decompress the body.

**Comment by HakuLess** [comment]
Thank you, got it. 
InflaterInputStream inputStream = new InflaterInputStream(
                    responseComment.body().byteStream(), new Inflater(true));

**Comment by suvro24** [comment]
I tried using InflaterSource  and InflateInputStream  but still cant decompress the response. Can anyone help?
