### ISSUE TITLE
Unique request ID with logging interceptor

### ISSUE THREAD

**Issue by ansman** [square/okhttp#2449]
Currently there is no way to pair the start log entry with the end log entry when using the HTTP logging interceptor.

It would be nice if a random ID would be generated for each request that is logged together with the entry so that you can track which requests that complete.

**Comment by jbaginski** [comment]
@ansman you can create a custom logger and pass it to HttpLoggingInterceptor :)

**Comment by ansman** [comment]
@jbaginski How is the logger supposed to know that two log statements are related?

**Comment by jbaginski** [comment]
very good point :) I think you will end up with custom interceptor... I suppose that the id could be the instance id of the request object.

**Comment by ansman** [comment]
Well, this is a feature request for the HTTP logging interceptor. I understand that I have to roll my own if I want this feature today.

**Comment by swankjesse** [comment]
I don't think we’ll implement this. If you’re logging many requests concurrently and manually relating them, you’re going to have a bad time. You’re much better off hooking up Stetho or Charles.
