### ISSUE TITLE
okhttp cache is useless without network

### ISSUE THREAD

**Issue by JuHonggang** [square/okhttp#2450]
- [ ] Feature Request. 
okhttp cache is useless without network under certain circumstances. For example, if the url of request is
"www.example.com?network=wifi&sign=123", but when without network,  your url will be "www.example.com?network=?&sign=345",(sign according to url params to generate). when matching cache data, it is not matched, so get cache data is null. 

Maybe you need to add a function in Cache.java  to solve the issue that developer can customized cache url.

**Comment by teaey** [comment]
guys, how to set read_timeout per request?

**Comment by swankjesse** [comment]
@JuHonggang you’re probably better off storing those responses locally independent of OkHttp’s cache. We won't be able to build a sufficient, performant system to match arbitrary requests to one another.
