### ISSUE TITLE
networkInterceptors().add()  exception

### ISSUE THREAD

**Issue by chongzi** [square/okhttp#2456]
I introduced the library：
 compile 'com.github.bumptech.glide:glide:3.7.0'
 compile 'com.github.bumptech.glide:okhttp3-integration:1.4.0@aar'

When I call this method the times wrong are as follows：
OkHttpClient mOkHttpClient = new OkHttpClient();
        mOkHttpClient.networkInterceptors().add(new Interceptor() {
            @Override
            public Response intercept(Chain chain) throws IOException {
                Response originalResponse = chain.proceed(chain.request());
                return originalResponse.newBuilder()
                        .body(new ProgressResponseBody1(originalResponse.body(), listener))
                        .build();
            }
        });

Exception：
     Caused by: java.lang.UnsupportedOperationException
                                                     at    java.util.Collections$UnmodifiableCollection.add(Collections.java:928)

All my code：

public class MainActivity3 extends Activity {
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        ProgressBar mProgressBar = (ProgressBar) findViewById(R.id.progress_bar);
        final ProgressListener1 listener = new ProgressListener1() {
            @Override
            public void update(long bytesRead, long contentLength, boolean done) {
                Log.e("update : ", bytesRead + " : " + contentLength + " : " + done);

            }
        };
        OkHttpClient mOkHttpClient = new OkHttpClient();
        mOkHttpClient.networkInterceptors().add(new Interceptor() {
            @Override
            public Response intercept(Chain chain) throws IOException {
                Response originalResponse = chain.proceed(chain.request());
                return originalResponse.newBuilder()
                        .body(new ProgressResponseBody1(originalResponse.body(), listener))
                        .build();
            }
        });

        Glide.get(this).register(GlideUrl.class, InputStream.class,
                new OkHttpUrlLoader.Factory(mOkHttpClient));

        ImageView myImageView = (ImageView) findViewById(R.id.myImageView);

        Glide.with(MainActivity3.this)
                .load("http://tupian.enterdesk.com/2013/xll/012/26/3/1.jpg")
                .into(myImageView);

    }

    class ProgressResponseBody1 extends ResponseBody {

        private final ResponseBody responseBody;
        private final ProgressListener1 progressListener;
        private BufferedSource bufferedSource;

        public ProgressResponseBody1(ResponseBody responseBody, ProgressListener1 progressListener) {
            this.responseBody = responseBody;
            this.progressListener = progressListener;
        }

        @Override
        public MediaType contentType() {
            return responseBody.contentType();
        }

        @Override
        public long contentLength() {
            return responseBody.contentLength();
        }

        @Override
        public BufferedSource source() {
            if (bufferedSource == null) {
                bufferedSource = Okio.buffer(source(responseBody.source()));
            }
            return bufferedSource;
        }

        private Source source(Source source) {
            return new ForwardingSource(source) {
                long totalBytesRead = 0L;

                @Override
                public long read(Buffer sink, long byteCount) throws IOException {
                    long bytesRead = super.read(sink, byteCount);
                    // read() returns the number of bytes read, or -1 if this source is exhausted.
                    totalBytesRead += bytesRead != -1 ? bytesRead : 0;
                    progressListener.update(totalBytesRead, responseBody.contentLength(), bytesRead == -1);
                    return bytesRead;
                }
            };
        }
    }

    public interface ProgressListener1 {
        void update(long bytesRead, long contentLength, boolean done);
    }
}

can you help me ? thx.

**Comment by JakeWharton** [comment]
`OkHttpClient` is immutable. Use something like:
```java
OkHttpClient client = new OkHttpClient.Builder()
    .addInterceptor(..)
    .build();
```

**Comment by chongzi** [comment]
@JakeWharton  A few days ago I also tried your above suggestion, but this will cause the content has no effect

 OkHttpClient mOkHttpClient = new OkHttpClient.Builder()
    .addInterceptor(new Interceptor() {
        @Override
        public Response intercept(Chain chain) throws IOException {
            Response originalResponse = chain.proceed(chain.request());
            return originalResponse.newBuilder()
                    .body(new ProgressResponseBody1(originalResponse.body(), listener))
                    .build();
        }
    }).build();


  This method has no response，has no effect。
   public Response intercept(Chain chain) throws IOException {}
