### ISSUE TITLE
response.headers() splits headers by itself

### ISSUE THREAD

**Issue by DavidRamos28** [square/okhttp#2457]
I have an interceptor made for getting headers from response. When i print "response.headers().get(4)" it is supposed to print this: 

> WWW-Authenticate: Bearer realm="Users", error="invalid_token", error_description="Token expired." 

But it only prints this: 

> WWW-Authenticate: Bearer realm="Users"

It is like takes header until the first comma, but it is not supposed to.

The official doc for Headers class says:

> A field with multiple comma- separated values on the same line will be treated as a field with a single value by this class. It is the caller's responsibility to detect and split on commas if their field permits multiple values

As far as I understand, when I use the get() method I obtain all the values for a header, not only until the first comma. 

Here is the code related:

```
import okhttp3.Headers;
import okhttp3.Interceptor;
import okhttp3.Request;
import okhttp3.Response;

public class LoginInterceptor implements Interceptor {

   @Override
   public Response intercept(Chain chain) throws IOException {
       Request originalRequest = chain.request();

       Response response = chain.proceed(originalRequest);

       Headers headers = response.headers();
       String header = headers.get(4);
       Log.i("LoginInterceptor", "Header number 4: "+header);

       return response;
   }
}
```

**Comment by swankjesse** [comment]
Please isolate this into a test case. Start with CallTest.java please.

**Comment by PatrickConceitual** [comment]
Have you tried debug mode? I am having a issue almost like yours.
I'm making a client to consume resources from a server that must response with 3 non-standard headers, using normal run only the standard headers come, in debug mode all the headers came.
I think that HttpEngine its building the response before all the parts of the response arrive.

**Comment by PatrickConceitual** [comment]
I added a "Transfer-Encoding: chunked" header to the request. It did OkHttp read the response properly.

**Comment by swankjesse** [comment]
No action for us to take here.
