### ISSUE TITLE
What's mean "Permitted to short-circuit and not call Chain.proceed()."?

### ISSUE THREAD

**Issue by AlphaHans** [square/okhttp#2460]
In wiki say that Permitted to short-circuit and not call Chain.proceed().

In Application Interceptor,if i don't invoke chain.proceed(request),so i must return a null response,but in souce code, it will crash by a NullPointerException:
if (interceptedResponse == null) {
          throw new NullPointerException("application interceptor " + interceptor
              + " returned null");
 }

Is it my misunderstanding? 

I'm from China,forgive my poor English.

**Comment by JakeWharton** [comment]
You don't have to call chain.proceed(), but you still need to return a
Response instance.

**Comment by AlphaHans** [comment]
Thanks a lot!  it's excited of me to have a chat with you!!!!  But, why? What is intention of this design?

**Comment by AlphaHans** [comment]
Thanks a lot! it's excited of me to have a chat with you!!!! But, why? What is intention of this design?

**Comment by AlphaHans** [comment]
@JakeWharton Thanks a lot! it's excited of me to have a chat with you!!!! But, why? What is intention of this design?

**Comment by JakeWharton** [comment]
This is essentially how the HTTP cache works. It reads from the filesystem
to see if there's a local response and returns it instead of calling
chain.proceed().

**Comment by AlphaHans** [comment]
@JakeWharton  OK！ I will read the source code again and again! Thank you !
