### ISSUE TITLE
[bug] 407 proxy error is not reported when credentials are wrong, instead "Too many follow-up requests"

### ISSUE THREAD

**Issue by smatei** [square/okhttp#2464]
Hello,

When connecting through a proxy with authentication, the first request is done without authentication. 
(I have implemented a preemptive authentication here https://github.com/square/okhttp/pull/2458 in order to send the first request with authentication). 407 response is received, the authenticate method from authenticator is called. If the **user/password credentials are wrong**, we get 407 again, and we make the call again with wrong credentials, and again, and again.

`Exception in thread "main" java.net.ProtocolException: Too many follow-up requests: 21
    at okhttp3.RealCall.getResponse(RealCall.java:289)
    at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:198)
    at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:160)
    at okhttp3.RealCall.execute(RealCall.java:57)
    at testok.run(testok.java:72)
    at testok.main(testok.java:79)
`

If 407 is received and we did send "authentication" header in the request, the request should return 407 without so many useless redirects. 

For the first call (without header) 407 means "try to authenticate". For the second call (with header) 407 should mean "failed to authenticate". **And exit.**

Best Regards,
Stefan Matei

**Comment by swankjesse** [comment]
Our expectation is that your Authenticator will check `Response.priorResponse()`, but we could do a lot to make this more obvious.

**Comment by smatei** [comment]
Hi @swankjesse,

Do you mean like this?


`

        case HTTP_PROXY_AUTH:
        Proxy selectedProxy = route != null
            ? route.proxy()
            : client.proxy();
        if (selectedProxy.type() != Proxy.Type.HTTP) {
          throw new ProtocolException("Received HTTP_PROXY_AUTH (407) code while not using proxy");
        }       

        if (userResponse.priorResponse() == null)
        {
        	return client.proxyAuthenticator().authenticate(route, userResponse);
        }
        else if (userResponse.priorResponse().code() == 407)
        {        	
        	return null;
        }

`

This breaks the retry loop and returns 407 at the second retry.

**Comment by smatei** [comment]
Hi @swankjesse,

I have found a simple solution. Change signature of followUpRequest  so that it contains the request also. If HTTP_PROXY_AUTH and the request already contained 'Proxy-Authorization' header, the authentication is useless and we can return.

`


    private Request followUpRequest(Request request, Response userResponse)
    .....
    switch (responseCode) {
      case HTTP_PROXY_AUTH:
        Proxy selectedProxy = route != null
            ? route.proxy()
            : client.proxy();
        if (selectedProxy.type() != Proxy.Type.HTTP) {
          throw new ProtocolException("Received HTTP_PROXY_AUTH (407) code while not using proxy");
        }
        
        String proxyAuth = request.header("Proxy-Authorization");
        
        if (proxyAuth != null && proxyAuth.length() > 0)
        {
        	return null;
        }
        else
        {
        	return client.proxyAuthenticator().authenticate(route, userResponse);
        }`

I like this better and it works with both my attempt of "preemptive authentication" (https://github.com/square/okhttp/pull/2458) and normal authentication (authenticate after 407). 

What do you say about this? Will you accept this solution for this bug? I don't see any problems.
