### ISSUE TITLE
Fine granted control on Cache

### ISSUE THREAD

**Issue by PaulWoitaschek** [square/okhttp#2466]
I have two api base endpoints I am connecting to. One for public data and one for account related data.
When I change the accounts in my App I want to delete the cache from the accounts endpoint.

However I only find a generic `.evictAll()`. So I ended up in making two separate OkHttpClients with different caches.
I would love to see some finer controls on manipulating the Cache so a shared client can be used. Ideally something like.

``` java
void evict(Predicate<String> shouldEvictUrl);
```

**Comment by JakeWharton** [comment]
Does [`Cache#urls()`][1] fulfill this requirement for you?

 [1]: http://square.github.io/okhttp/3.x/okhttp/okhttp3/Cache.html#urls--

**Comment by PaulWoitaschek** [comment]
Absolutely. Did just skim it and assumed the data behind was immutable. My bad, thanks.
