### ISSUE TITLE
Caching redirected request

### ISSUE THREAD

**Issue by farruxx** [square/okhttp#2472]
When I request to "example.com", server redirects it to some "static-cached-data.example.com", then okhttp follows it, and caches with key "static-cached-data.example.com". The next "example.com" requst is still uncached... This time server may redirect to "another-static-cached-data.example.com"

But Last-Modified date are the same on all responses

**Comment by swankjesse** [comment]
Do web browsers like Chrome and Firefox cache the redirect?

**Comment by farruxx** [comment]
It seems, they also cache by destination url. I understand, thats correct. Because, when user will refresh the site, it will use this cache, otherwise it will never be cached..

**Comment by swankjesse** [comment]
Sorry, I mean specifically do they cache the redirect? HTTP 301s are cacheable by default, but 302s need caching headers.

https://en.wikipedia.org/wiki/URL_redirection#HTTP_status_codes_3xx
https://github.com/square/okhttp/blob/master/okhttp/src/main/java/okhttp3/internal/http/CacheStrategy.java#L66

**Comment by swankjesse** [comment]
No clear action for us to take here.
