### ISSUE TITLE
Require connection preface on HTTP/2 connections

### ISSUE THREAD

**Issue by swankjesse** [square/okhttp#2474]
Currently we aren’t strict on this.

https://github.com/square/okhttp/pull/2473/files/8996934748a48fe04f7dde56069042dfecb64c91#r59138454

**Comment by boxme** [comment]
Wouldn't the following in `RealConnection` already ensure that connection preface is being enforced on HTTP/2 connections?
```
if (protocol == Protocol.HTTP_2) {
      socket.setSoTimeout(0); // Framed connection timeouts are set per-stream.

      Http2Connection http2Connection = new Http2Connection.Builder(true)
          .socket(socket, route.address().url().host(), source, sink)
          .listener(this)
          .build();
      http2Connection.start();
```

Or do you have the idea to enforce it on the `Http2Writer` level?

**Comment by swankjesse** [comment]
There's a few places where we need to fail the connection if the peer doesn't send it. In MockWebServer for one example.
