### ISSUE TITLE
This Symbol ^ crashes okhttp3.Request calls (IllegalStateException: not valid as a java.net.URI)

### ISSUE THREAD

**Issue by ofuwape** [square/okhttp#2475]
**Build Version**
`compile 'com.squareup.okhttp3:okhttp:3.2.0' ` 
`compile('com.squareup.retrofit2:retrofit:2.0.1'){
        exclude module: 'okhttp'
    }`

**Issue**
When I have the symbol ^ in my login requests I get the following error:

`FATAL EXCEPTION: OkHttp Dispatcher 
java.lang.IllegalStateException: not valid as a java.net.URI`

**Comment by swankjesse** [comment]
Yikes. I’ll take a look.

**Comment by ofuwape** [comment]
Found out my requests were using okhttp2 not okhttp3. So this bug does not exist in the okhttp3.
