### ISSUE TITLE
Hook up the built-in ALPN in Java 9

### ISSUE THREAD

**Issue by swankjesse** [square/okhttp#2480]
Cause Platform.java is fun!

**Comment by yschimke** [comment]
If there is no day to day urgency for this (3.4 timeframe), I'm happy to pick this up.  Close to my heart and I'm looking to contribute to the project.

**Comment by swankjesse** [comment]
@yschimke I’m pretty fussy about how these sorts of things are integrated. Usually it’s whatever keeps the behavior most-automatic for the end user, with us eating the complexity in Platform.java. If you’re up for that, sure, please send a PR.

**Comment by yschimke** [comment]
That sounds fair.  Let's see how a PR goes.  Can we say I'm used to your rejections in PRs by now?

Thanks

**Comment by yschimke** [comment]
PR is here https://github.com/square/okhttp/pull/2494

**Comment by yschimke** [comment]
One question, should this be also setting SNIHostName on SSLParameters as well for SNI support?

**Comment by swankjesse** [comment]
Yes, doing SNI also would be great. For a separate follow up PR though please.

**Comment by yschimke** [comment]
I need to confirm this with tests but I believe SNI is already working as is, so the PR will be stating this in the docs and some test evidence that its the case.

**Comment by JakeWharton** [comment]
I think everything in here was resolved, correct?

**Comment by yschimke** [comment]
AFAIK

**Comment by swankjesse** [comment]
Thanks!
