### ISSUE TITLE
AsyncCall in RealCall sets the thread name to the url, exposing sensitive data

### ISSUE THREAD

**Issue by Floens** [square/okhttp#2481]
The AsyncCall runnable inside the RealCall class extends NamedRunnable, and sets the current thread name to the full url of the call.
This can expose sensitive information, for example when API's require a token in the url. I'm having the problem that I log the thread name with log4j2 and it now logs the full url.
I suggest changing it to `toLoggableString()`.

Thanks

**Comment by swankjesse** [comment]
I thought we had all of these but we must have missed one. Can fix.

**Comment by dave-r12** [comment]
Closed with #2499.
