### ISSUE TITLE
Retrofit + OkHTTP causes memory leaks in Tomcat

### ISSUE THREAD

**Issue by CatPlanet** [square/okhttp#2482]
creation of OkHttpClient with ConnectionPool:

	@Scope(ConfigurableBeanFactory.SCOPE_PROTOTYPE)
	@Bean(name = "closeableOKHTTP")
	public OkHttpClient closeableOKHTTP() {
		ConnectionPool pool = new ConnectionPool(5, 1, TimeUnit.SECONDS);
		OkHttpClient client = new OkHttpClient.Builder() //
				.connectTimeout(3, TimeUnit.MINUTES) //
				.followRedirects(true) //
				.readTimeout(3, TimeUnit.MINUTES) //
				.retryOnConnectionFailure(false) //
				.writeTimeout(3, TimeUnit.MINUTES). //
				connectionPool(pool) //
				.build();
		return client;
	}

building service:

	SocialRemoteService getRemote() {
		Gson gson = new GsonBuilder() //
				.setLenient() //
				.create();
		return new Retrofit.Builder() //
				.baseUrl(API) //
				.client(okHttpClient) //
				.addConverterFactory(GsonConverterFactory.create(gson)) //
				.callbackExecutor(daemonExecutor) //
				.build() //
				.create(SocialRemoteService.class);
	}

	@PreDestroy
	public void destroy() {
		okHttpClient.connectionPool().evictAll();
	}

service:

	public interface SocialRemoteService {
	
		@GET("cities")
		public Call<List<SocialCity>> cities(@Query("searchField") String searchField);
	
	}

Tomcat logs on un-deploy: http://pastebin.com/3s091BKh

Is there any way to prevent memory leaks using retrofit and okhttp? `okHttpClient.connectionPool().evictAll()` even with `new ConnectionPool(5, 1, TimeUnit.SECONDS)` does not seem to work.

dependencies:

- okhttp3 - 3.2.0
- retrofit2 - 2.0.1
- retrofit2 converter-gson - 2.0.1
- tomcat8 - Apache Tomcat/8.0.32
- java8 - 1.8.0_74-b02

**Comment by JakeWharton** [comment]
These are the dispatcher threads. You should be able to call
getDispatcher().getExecutor().shutdown() and then await shutdown for
whatever period of time you're comfortable with.

**Comment by CatPlanet** [comment]
changed destroy method to:

			okHttpClient.connectionPool().evictAll();
			ExecutorService executorService = okHttpClient.dispatcher().executorService();
			executorService.shutdown();
			try {
				executorService.awaitTermination(3, TimeUnit.MINUTES);
				log.info("OKHTTP ExecutorService closed.");
			} catch (InterruptedException e) {
				log.warn("InterruptedException on destroy()", e);
			}

tomcat logs: http://pastebin.com/9Vm6rtpH

**Comment by JakeWharton** [comment]
Okio is filed here: https://github.com/square/okio/issues/107

Not sure where the other two come from.

**Comment by CatPlanet** [comment]
I have two services that use two OkHttpClients, each with its own ConnectionPool I'm unable to close manually before Tomcat starts to moan about.

Can I do anything with those? ConnectionPool interface lets me only to evict all unused connections but even after that it still triggers Tomcat's MemoryLeakProtection.

**Comment by swankjesse** [comment]
We haven’t yet implemented Okio watchdog thread shutdowns.

**Comment by CatPlanet** [comment]
And how about ConnectionPool? Is there any way to shutdown it manually?

**Comment by swankjesse** [comment]
`ConnectionPool.evictAll()` should work if you have no requests in flight.

**Comment by CatPlanet** [comment]
I have two Spring @Component (@Service) objects, in each there is @PreDestroy method:

	@PreDestroy
	public void destroy() {
		if (okHttpClient != null) {
			ConnectionPool connectionPool = okHttpClient.connectionPool();
			connectionPool.evictAll();
			log.info("OKHTTP connections iddle: {}, all: {}", connectionPool.idleConnectionCount(), connectionPool.connectionCount());
			ExecutorService executorService = okHttpClient.dispatcher().executorService();
			executorService.shutdown();
			try {
				executorService.awaitTermination(3, TimeUnit.MINUTES);
				log.info("OKHTTP ExecutorService closed.");
			} catch (InterruptedException e) {
				log.warn("InterruptedException on destroy()", e);
			}
		}
	}
	
Tomcat log: http://pastebin.com/QeKb3rwa

After `evictAll` log states `OKHTTP connections iddle: 0, all: 0` and there is still issue with `OkHttp ConnectionPool` threads memory leakage.

**Comment by swankjesse** [comment]
The thread exits asynchronously.

**Comment by CatPlanet** [comment]
So what exactly keeps it in memory? How can I force it to shut down gracefully?

**Comment by CatPlanet** [comment]
I've created a simple repo to show problem [https://github.com/CatPlanet/okhttpMemoryLeak](https://github.com/CatPlanet/okhttpMemoryLeak)

building .war: `clean install`
after deploying app to Tomcat and running `localhost:8080/test` try to undeploy app.

Tomcat logs: http://pastebin.com/x1NAtDs0

**Comment by CatPlanet** [comment]
Can anyone open this issue until it is verified?

**Comment by swankjesse** [comment]
Unloading code is awkward to implement, difficult to test, and yields little benefit in modern app architectures. You're better off using JRebel in development and restarting the JVM on the server.

We may try to make this work, but code unloading is not an advertised feature of this library. Relying on it may cause other problems. For example, our disk cache doesn't support multiple concurrent instances sharing the same cache directory.

Similarly HTTP/2 needs its own threads, and those will also likely harm your ability to do an immediate unload of the OkHttp classes. You could get everything working, then your target webserver upgrades to HTTP/2 and suddenly class unloading breaks.

If you need class unloading as a supported feature, please use another library. But I think you're better off not using class unloading.

**Comment by CatPlanet** [comment]
Restarting JVM as a solution to memory leaks in life-cycle aware application sounds pretty flimsy to me, to be honest. It sounds like I would have to restart my Android every 4-5 apps I started and closed.

>We may try to make this work, but code unloading is not an advertised feature of this library

Direct access to thread pools would do the trick. It might look dirty but in some cases (like using okhttp in server-side apps) it would definitely pay off, especially when pools don't exit asynchronously as fast as they should.

Different http protocols or code unloading doesn't really bother me at this point. It's beacuse I'm unable to manually close those pools *which* leads to keeping class loader in JVM bothers me.

**Comment by supertinou** [comment]
👍 We are having the same issue.

**Comment by swankjesse** [comment]
Unloading code is deliberately something we're not addressing because it's an antipattern.

Testing unloading is very difficult to do well. 

It's difficult to do automatically. Last time I looked into this the popular containers don't offer dependency-free mechanisms to observe when unloading is desired.

The alternative of starting a fresh process has much better industry support. Projects like Kubernetes assume new processes.

**Comment by swankjesse** [comment]
The benefits of unloading code are not worth the costs.

I don't consider inability to unload code to be a memory leak.

**Comment by CatPlanet** [comment]
Inability to unload code is precisely the very reason for this memory leak and thus this issue I've opened almost 3 years ago.

As it is, claiming that executing one method "should work" - and obviously it's doesn't - and then proceeding to close issue (as it's "not worth the costs"), in my eyes serves only one purpose and it's to trim down amount of open issues, consequently neglecting state of your projects further.

**Comment by swankjesse** [comment]
I've spent a lot of time on code unloading and found only [unsatisfying results](https://stackoverflow.com/questions/28403240/exit-a-thread-upon-app-unload). Getting code unloading right is a lot of work and of marginal benefit. I’d rather spend the time on other features!

We close issues that we don't intend to address. This isn't sweeping dirt under the rug; it's being honest about what the scope of this project is.
