### ISSUE TITLE
RealBufferedSource throw  IllegalStateException("closed")

### ISSUE THREAD

**Issue by YLBFDEV** [square/okhttp#2483]
When I use the following method

```java
BufferedSource source = responseBody.source();
source.request(Long.MAX_VALUE); // Buffer the entire body.
Buffer buffer = source.buffer();
```
happened RealBufferedSource throw  IllegalStateException("closed")
![Code Error](http://chuantu.biz/t3/12/1460711284x3340469734.png)

**Comment by swankjesse** [comment]
Are you calling responseBody.string() or any other method to close the response body? I suspect thats the problem here. No action for us to take on this.

**Comment by YLBFDEV** [comment]
I used `inresponseBody.string() `

but in ResponseBody
```java
public final String string() throws IOException {return new String(bytes(), charset().name());}
```

```java
public final byte[] bytes() throws IOException {
   ……
    BufferedSource source = source();
    byte[] bytes;
    try {
      bytes = source.readByteArray();
    } finally {
      Util.closeQuietly(source);
    }
 ……
    return bytes;
  }
```
Here is closed source then I use RxJavaframework So just out of this question 
So here should not be used  `inresponseBody.string() ` method
