### ISSUE TITLE
authenticate interceptor leads to "java.io.IOException: unexpected end of stream on okhttp3.Address" 

### ISSUE THREAD

**Issue by southerton81** [square/okhttp#2486]
If I spend more time in authenticate() interceptor, than the time set as OkHttp timeout (10 seconds default) the followUp request always produces the java.io.IOException: unexpected end of stream on okhttp3.Address
This is OkHttp3. 

```
    @Override
    public Request authenticate(Route route, Response response) throws IOException {
            try {
                Thread.sleep(20_000);
            } catch (InterruptedException e) {
                e.printStackTrace();
            }

            return response.request().newBuilder()
                        .header("Authorization", "newvalidtoken")
                        .build();
        }

```

**Comment by swankjesse** [comment]
Could you convert this into a complete JUnit test case? Those kinds of bugs are way easier to fix.

**Comment by alanlee-gn** [comment]
FYI, I was seeing the same error and resolved it by setting "Connection: close" in the header.

> .header("Connection","close")

It seems "Keep-Alive" is added to the HTTP header by default and was causing an issue for me on subsequent requests.

**Comment by southerton81** [comment]
Thank you for the tip, I'll give it a try. However, I'm afraid that with "Connection: close" flag we would loose some performance, as OkHttp tries to reuse open connections. But I think it would be OK to set this header only in this 401 situation. 
I did a JUnit test case with MockWeb server but was unable to reproduce this, though it always happens on real server.

**Comment by swankjesse** [comment]
No obvious next action for us to take on this.
