### ISSUE TITLE
Exponential Backoff support

### ISSUE THREAD

**Issue by ChronoWaste** [square/okhttp#2489]
The Google's Http Client has an implementation of this algorithm which essentially improves the way retrying a request in case of failures. Is it possible to make yours ?

Additional info:
[https://developers.google.com/api-client-library/java/google-http-java-client/backoff](https://developers.google.com/api-client-library/java/google-http-java-client/backoff)

**Comment by wingsum93** [comment]
-1 ,
if it is user trigger, no data = no retry.
because server may return 500.

if you send data in background, you may retry yourself in own way.

**Comment by swankjesse** [comment]
I’d like to leave this up to the application layer. Backoffs might need to be scheduled in another process if a server is redeployed or an app is relaunched. It’s really awkward to hide the response indefinitely.
