### ISSUE TITLE
Why okhttp dropt NPN support?

### ISSUE THREAD

**Issue by hexucheng** [square/okhttp#2490]
I want to know why okhttp dropt NPN support in version 2.2.0? Were there some bugs in using previous NPN support implementation?

**Comment by hexucheng** [comment]
I want to have SPDY support under android 5.0, action of okhttp makes me confused.

**Comment by swankjesse** [comment]
NPN is obsoleted by ALPN, and SPDY is obsoleted by HTTP/2. Maintaining both ALPN and SPDY is too much code, so we got rid of NPN.

We’ll be dropping SPDY soon too.
