### ISSUE TITLE
X509 certificate public key fingerprint can be different on different Android versions

### ISSUE THREAD

**Issue by artem-zinnatullin** [square/okhttp#2491]
We have pinned hostname agains self-signed root certificate.

Problem is that calculation of `sha fingerprint` for the certificate during the check in `CertificatePinner` gives different results on `Android <= 5` and `Android > 5` -> leads to `SSLPeerUnverifiedException`.

Of course, implementations of `sha256` and `sha1` are correct on both Android versions and both devices receive same certificate chain, but debugging shown that `certificate.getPublicKey().getEncoded()` gives different `byte[]` arrays on mentioned platforms.

As far as I found, during Android 5 development Android team switched from BouncyCastle to own implementation of some security related classes, including [`X509PublicKey`](https://android.googlesource.com/platform/external/conscrypt/+/7d97b2cee4acabea6c8cb795d25fb1fb564f016c%5E%21/src/main/java/org/conscrypt/X509PublicKey.java) and other related classes.

For the app developers I see 2 possible solutions:

1. Pin each host by `sha`s computed on both Android platform versions.
2. Pin by including certificate to the app and computing `sha` at runtime via `CertificatePinner.pin(certificate)`.

Also, worth to mention that in our case we have 3 certificates in the chain and 2 of them produce same `sha`s on both Android versions, but public key of Root CA certificate represented as different `byte[]` arrays on mentioned Android versions.

We decided to go with calculating `sha` at runtime from certificate bundled into the app avoid changes of those classes in Android in future.

Probably there is a way to fix that on OkHttp level, but it looks like copying `Certificate` implementation related code to the library which have both pros and cons.

----

Even if you decide not to fix it on the library side (which is ok from my point of view), I'd like to make a PR and add this info to the javadoc or wiki if you don't mind.

**Comment by swankjesse** [comment]
Could you provide a URL whose cert demonstrates this problem? It might not be a different bytes for the same root CA cert; rather it could be two different certs.

**Comment by artem-zinnatullin** [comment]
Not sure I can post link to the api here (yeah yeah, it's easy to get it from the apk, but yeah, sorry).

Certificates are the same, I get `ourCertificate.toString()` from Android 4.3 and 6.0: public key, serial number and other significant info are the same. **But** `toString()` format is completely different between 4.3 and 6.0, on 4.3 it has more fields that filled with white noise like `ffffff`.

Another thing that guarantees that certificates are the same is that if I compute `CertificatePinner.pin()` from the certificate bundled into the app I get exact same results: on Android 4.3 it's one value, on 6.0 it's another value.

**Comment by swankjesse** [comment]
I couldn't reproduce this.

**Comment by swankjesse** [comment]
After talking with @artem-zinnatullin and doing some investigation I’ve found the root cause. When you have an ECC certificate with a named curve, different versions of Android encode that curve differently.

Android 4.x / BouncyCastle encodes the curve by value.
Android 6.x / OpenSSL encodes the curve by name.

**Comment by swankjesse** [comment]
One reasonable workaround is to pin both encodings. That’s annoying, but it should work.

**Comment by swankjesse** [comment]
https://mailarchive.ietf.org/arch/msg/websec/FNxx6cCUSuFPzIeMFfaXH9tg46E

**Comment by artem-zinnatullin** [comment]
>One reasonable workaround is to pin both encodings. That’s annoying, but it should work.

Well, it's possible, but I was really afraid that on next versions of Android pin may be different again. 

So I decided to read certificate at runtime and compute pin from it so it'll be in the same format as JDK expects.

**Comment by swankjesse** [comment]
Turns out that this is an implementation bug in old versions of Android. [According to Brian Smith](https://mailarchive.ietf.org/arch/msg/websec/ynPkB41qNEtjPwwtfyXf2GahmzQ):

> This is invalid. See https://tools.ietf.org/html/rfc5480#section-2.1.1: "implicitCurve and specifiedCurve MUST NOT be used in PKIX."

Seems like we may be able to work around this somehow.

**Comment by swankjesse** [comment]
Upon further investigation, I believe this only happens if the cert itself is invalid. No action for us to take here.
