### ISSUE TITLE
Multiple requests going in case of request close

### ISSUE THREAD

**Issue by chethann** [square/okhttp#2497]
I am using Fresco with OkHttp 2.7.4. By default the image request from the previous activity won't get canceled when we switch to a new activity. This makes the new activity load slower as previous requests are still running. So I am closing the all the image requests in `onStop()` of my activity based on `tag`.

The request are getting closed, all good...But the requests are fired again to download the images from the previous activity. It is retrying to download the images again. I have `setRetryOnConnectionFailure(false)`. 

Not able to figure out what I am doing wrong. Not sure if Fresco is triggering new requests on cancel. I didn't find any configuration option with Fresco.

Please help. Thank you!

**Comment by JakeWharton** [comment]
This was [posted to StackOverflow][1] (presumably by you) which is the correct place to ask usage questions.

 [1]: http://stackoverflow.com/q/36761432/132047
