### ISSUE TITLE
No request is sent if cached one has date from future.

### ISSUE THREAD

**Issue by mik9** [square/okhttp#2500]
What kind of issue is this?

 - [ ] Question. This issue tracker is not the place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use Stack
       Overflow. https://stackoverflow.com/questions/tagged/okhttp

 - [x] Bug report. If you’ve found a bug, spend the time to write a failing test. Bugs with tests
       get fixed. Here’s an example: https://gist.github.com/swankjesse/981fcae102f513eb13ed

 - [ ] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
       already exists! Don’t send pull requests to implement new features without first getting our
       support. Sometimes we leave features out on purpose to keep the project small.

I'm not really sure this is a bug but:
If there are response in cache with "Date" header with date in future (comparing to system time) than [ageMillis](https://github.com/square/okhttp/blob/master/okhttp/src/main/java/okhttp3/internal/http/CacheStrategy.java#L204) will be negative and no request will be sent.
I think it makes sense to check ageMillis for negative value (in normal case it should not happen) and make request instead of pulling data from cache.

**Comment by swankjesse** [comment]
There's already some mitigation against this in the CacheStrategy class. One challenge is that we don't know whose clock is wrong: the local client or the remote server.

**Comment by mik9** [comment]
Yeah, I understand this.
I'm just thinking that if something goes wrong it's better to send request.
Just my opinion.

Thanks for the reply.

**Comment by swankjesse** [comment]
No action to take on this at this time.
