### ISSUE TITLE
Not comsumimg ResponseBody making X.0.tmp and X.1.tmp files in the cache

### ISSUE THREAD

**Issue by ytinrete** [square/okhttp#2504]
I'm using cache in okhttp3 in my code.
However in some circumstances the cache doesn't work.
Eventually it turn out to be in some occasions I didn't comsume the ResponseBody so the closeQuietly() method will not be call.
Now I'll call response.body().close() if I'll not use it and everything works well.

But I also notice that even if in my wrong using way, the cache folder will still cache some data from the response. They are differnt from normal cache files which end by XXX.0 vs XXX.0.tmp all contain the full specification of the request, and XXX.1 with the real data vs XXX.1.tmp which is just a empty file.

Now my question is:
Is that okhttp3 is designed to have different caching behavior on whether I comsume the responsebody or not, or it is do making the cache but fail to complete it due to I forget to call close() on the body? Or I'm using the wrong api?

Thanks a lot for advance :)

**Comment by swankjesse** [comment]
You have to consume the complete response body for OkHttp to successfully cache it.
