### ISSUE TITLE
Problem in Cookie.parse

### ISSUE THREAD

**Issue by mohuanly** [square/okhttp#2508]
We got a problem while developing a android client with OkHttp 3 and a server with node.js. When the client posted requests to the server, it received responses with cookies, which had a field named  'expires" and followed by the expire time in GMT format. But, when the client  ran into the Cookie.parse method, the "persistent" attribute was surely set to be "true", regardless of the value of "expiresAt" attribute. Just like this:

>       if (attributeName.equalsIgnoreCase("expires")) {
        try {
          expiresAt = parseExpires(attributeValue, 0, attributeValue.length());
          persistent = true;
        } catch (IllegalArgumentException e) {
          // Ignore this attribute, it isn't recognizable as a date.
        }
      }   
>         

So it seemed that, the client would definitely consider the cookie expired whether it really is or not. Did we miss something important? Any advice or help is appreciated! Thanks!

**Comment by swankjesse** [comment]
It's exactly as the spec wants:
https://tools.ietf.org/html/rfc6265#section-5.3

You'll want to read how the spec defines persistent to understand why.
