### ISSUE TITLE
 [Feature Request] MultipartBody.Builder to allow a custom header to be added to a Part

### ISSUE THREAD

**Issue by long-greg-c** [square/okhttp#2509]
Quoting the [multipart recipe](https://github.com/square/okhttp/wiki/Recipes#posting-a-multipart-request) 

> Each part of a multipart request body is itself a request body, and can define its own headers.

If I wanted to add a header to the request body Part, for example a `Content-MD5: ...` checksum header, then I would not be able to use the method `addFormDataPart(String name, String filename, RequestBody body)`, and by using that method take advantage of the provided Content-Disposition header.

I would need to use the method `addPart(Headers headers, RequestBody body)` and supply the Content-Disposition and my custom header.

Feature Request would be to add another overload addFormDataPart as `addFormDataPart(String name, String filename, RequestBody body, Header headers)`. 

Will create a pull request if feature is accepted.

**Comment by swankjesse** [comment]
Interesting. Do web browsers ever provide headers beyond Content-Disposition? I don’t know if it makes sense to support arbitrary headers if that’s an unusual thing to do.
