### ISSUE TITLE
User-Agent Header not used for TLS tunnel

### ISSUE THREAD

**Issue by psniranjan** [square/okhttp#2514]
In case where HTTP tunnel is needed, the "User-Agent" header is reset and the default agent "okhttp/3.x.x" is used. This is causing the request being ignored as its considered to be originating from an unknown client.

Reference code from RealConnection.

```
 /**
   * Returns a request that creates a TLS tunnel via an HTTP proxy, or null if no tunnel is
   * necessary. Everything in the tunnel request is sent unencrypted to the proxy server, so tunnels
   * include only the minimum set of headers. This avoids sending potentially sensitive data like
   * HTTP cookies to the proxy unencrypted.
   */
  private Request createTunnelRequest() throws IOException {
    return new Request.Builder()
        .url(route.address().url())
        .header("Host", Util.hostHeader(route.address().url(), true))
        .header("Proxy-Connection", "Keep-Alive")
        .header("User-Agent", Version.userAgent()) // For HTTP/1.0 proxies like Squid.
        .build();
  }
```

**Comment by yschimke** [comment]
I had a 5 minute look at this and it seems awkward to fix correctly given creating connections is somewhat detached from individual requests currently.  The user agent could be plumbed through, but it seems ugly.  Also a second http request with different user agent would still use the previous user agent from when the RealConnection is first established.

It does make me wonder whether OkHttpClient should support a user agent string which defaults to Version.userAgent(), but can be overridden in the client builder and eventually per request in headers. It seems natural to have as a client property and that could make it easier for RealConnection to use.

**Comment by swankjesse** [comment]
We can fix this with new settings for preemptive authentication.

**Comment by shwalabaka** [comment]
@psniranjan, @yschimke  Hello. Have the same problem (In case where HTTP tunnel is needed, the "User-Agent" header is reset and the default agent "okhttp/3.x.x" is used) in okhttp/3.7.0 . Did you solve this problem? And could you say how.

**Comment by yschimke** [comment]
@shwalabaka - No, it wasn't affecting me.

**Comment by Ashok-Varma** [comment]
@swankjesse 
1) any update on this bug (or) is there any work around for now to set User-Agent ??
2) do you guys have any stats for % of people who use proxy ??

**Comment by JoshSolo** [comment]
Is this issue still on the roadmap? Last update is from 2018.

**Comment by swankjesse** [comment]
@JoshSolo you can hack this in with an `Authenticator` by following the instructions on pre-emptive authentication:
https://square.github.io/okhttp/4.x/okhttp/okhttp3/-authenticator/#preemptive-authentication

**Comment by JoshSolo** [comment]
@swankjesse - Nice! I'm checking it out now.

**Comment by yschimke** [comment]
Won't fix.
