### ISSUE TITLE
EOFException without attempting a connection if the previous connection closed at the end

### ISSUE THREAD

**Issue by ktchernov** [square/okhttp#2516]
What kind of issue is this?

 - [ ] Question. This issue tracker is not the place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use Stack
       Overflow. https://stackoverflow.com/questions/tagged/okhttp

 - [X] Bug report. If you’ve found a bug, spend the time to write a failing test. Bugs with tests
       get fixed. Here’s an example: https://gist.github.com/swankjesse/981fcae102f513eb13ed

 - [ ] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
       already exists! Don’t send pull requests to implement new features without first getting our
       support. Sometimes we leave features out on purpose to keep the project small.

I have created a unit test for this here:
https://gist.github.com/ktchernov/fa5f6e16d128571bf9dfad7e7258512e

The test `whenRetryOnConnectionFailureIsTrue_getAfterDisconnectAtEndShouldSucceed` succeeds, while `whenRetryOnConnectionFailureIsFalse_getAfterDisconnectAtEndShouldSucceed` fails. Both should pass - there should be no need to retry the second connection as it should not fail.

I spotted this in my app when debugging with Charles Proxy. When the socket is closed after the response is sent, the call succeeds but the next call fails with `java.io.EOFException: \n not found: size=0 content=...` without even attempting to make a network request. (In Charles Proxy: this is the "Abort" button on a breakpoint).

I have tried this on 3.2.0 and 3.3.0-SNAPSHOT with the same result.

**Comment by swankjesse** [comment]
Not succeeding here is kind of the entire point of `retryOnConnectionFailure(false)`. We can’t efficiently detect that the socket has been closed (the FIN packet might not have even arrived yet!) and so we attempt and retry.

The warning on that method makes your obligations as the caller clear:

```
     * Set this to false to avoid retrying requests when doing so is destructive. In this case the
     * calling application should do its own recovery of connectivity failures.
```

**Comment by ktchernov** [comment]
It is strange though, the first call (where the socket is closed) succeeds. It is the next call that fails. Is that the correct behaviour?

**Comment by swankjesse** [comment]
Yes. Because we reuse connections. More details here: https://github.com/square/okhttp/wiki/Connections
