### ISSUE TITLE
Cancelling big response.

### ISSUE THREAD

**Issue by farruxx** [square/okhttp#2527]
When server response with stream, I must check headers of response and decide continue or close stream. When I call `call.cancel()`, it doesn't cancel instantly, I use facebook's Stetho, and it takes more time to proccess request, that means, it not cancelling.
Then I try use `responce.body().close()`. It works. But the next requests get a Protocol Exception.
Seems, method `cancel()` not work correctly..

I am using com.squareup.okhttp3:okhttp:3.2.0

**Comment by swankjesse** [comment]
Nit sure what action to take here. Could you provide a test case to show what you're seeing? We request test cases for all bug reports. Our codebase has plenty of examples.

**Comment by swankjesse** [comment]
No action for us to take here. Will re-open on a test case.
