### ISSUE TITLE
Support dynamic table in HPACK of Http/2 when the client working as a request sender

### ISSUE THREAD

**Issue by mostleg** [square/okhttp#2530]
What kind of issue is this?

 - [ ] Question. This issue tracker is not the place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use Stack
       Overflow. https://stackoverflow.com/questions/tagged/okhttp

 - [ ] Bug report. If you’ve found a bug, spend the time to write a failing test. Bugs with tests
       get fixed. Here’s an example: https://gist.github.com/swankjesse/981fcae102f513eb13ed

 - [x] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
       already exists! Don’t send pull requests to implement new features without first getting our
       support. Sometimes we leave features out on purpose to keep the project small.

**Comment by mostleg** [comment]
Hi, I'm the owner of this question on stackoverflow: 

[Does OkHttp support dynamic table in Http/2 when working as a request sender (writer)?](http://stackoverflow.com/questions/36875785/does-okhttp-support-dynamic-table-in-http-2-when-working-as-a-request-sender-wr)

So let's talk about this. How would OkHttp supports it? Automatically add every headers to dynamic table with some mechanism like LRU/FIFO? Or providing some APIs to let the user add headers to it?

If possible I'm interested to add it for OkHttp, is it OK?

**Comment by swankjesse** [comment]
I’d prefer for us to implement something that’s automatic, like LRU. That’s relatively easy to implement and very easy for users of our APIs.

If you’d like to give it a try, please do. But please make small incremental steps if at all possible. It’s quite possible I won’t like your code (due to style, or implementation, or whatever) and with small steps it’s much more likely we’ll be able to merge something.

**Comment by mostleg** [comment]
Thanks Jesse. OK I'll try to make small incremental steps.

Based on HPACK, I think an easy way to make use of the dynamic table automatically is keep adding every entry to it if it's not there and worth to be compressed. This will make it work as a FIFO table. Do you think it's OK as our first step?

A question for the headers whose name is in the static table but value is not: Do we add these headers to dynamic table? Only when the value is long enough?

**Comment by mostleg** [comment]
I saw that current writer will only use the header name in the static table. So maybe we should just add all the headers whose name is not in the static table to the dynamic table as the first step, is it OK?

**Comment by swankjesse** [comment]
I think the simplest might be LRU eviction. There’s a way to subclass LinkedHashMap that makes using it as a LRU pretty easy. I have to be honest that I don’t know too much about HPACK. If we already have a value in the static table, is there a benefit to including it in the dynamic table?

**Comment by mostleg** [comment]
I think because of the protocol, LRU is not easier than FIFO. We could maintain a LinkedHashMap for the  headers in the dynamic table in the writer, but how could we notice the reader when we change the index of entries as LRU mechanism? I don't find an easy method. If I'm wrong please correct me.

For the headers which is in the static table, I didn't describe the question clearly last time. In the static table it restores some name-value pairs, and some ones just names. In the existed code of OkHttp, we ignore the values, so we just compress the names even if the values are in the static table. When adding the dynamic table, we could restore a name-value pair, or just the name. To make the first step relatively easy, I'd like to add the name-value pair of a header into the dynamic table, if and only if its name is not in the static table.

I just made a pull request for a quick review. Thank you very much!

**Comment by swankjesse** [comment]
Anything else to do on this?

**Comment by mostleg** [comment]
We can still go further on the dynamic table. :) What enhancement do you want?

**Comment by swankjesse** [comment]
How does our implementation differ from say, Chrome’s ?

**Comment by mostleg** [comment]
I did some search but didn't find any doc describes the detail info of how does others implement it. Maybe we need to read some source code? I think LRU should be better than FIFO, but I don't find an easy way to implement it. 

BTW, currently OKHttp just ignore the value fields in static table. I think it will be faster in time and the loss in compression rate is limited, so maybe it's by design? We could also change it if you think the compression rate is more important.

**Comment by dave-r12** [comment]
One thing Chome does that we don't: implement 8.1.2.5 Compressing the Cookie Header Field in HTTP/2 spec (https://tools.ietf.org/html/rfc7540#section-8.1.2.5).

We can also be smarter about header fields with names in the static table - they can be indexed in the dynamic table as well. Right now, we treat them as literals without indexing.

**Comment by swankjesse** [comment]
I’m on board with the static table improvements.

For cookies I wonder if clients actually end up sending different combinations of cookies. (I guess I have no good intuition about what people are doing with cookies on OkHttp!)

**Comment by dave-r12** [comment]
I think this one is in a good state. To recap the current implementation:

* All headers are added to the dynamic table by default. The only exception is pseudo headers: we only include the `:authority` header, but exclude all others. This decision was guided by the Chrome HPACK implementation.
* We always prefer an indexed name over a new name when sending a literal header field. This will reduce the bytes sent.
* We support Huffman encoding when sending string literals if the encoded value length is strictly less than the raw data length.
* There's no hard evidence that implementing the cookie compression will benefit OkHttp users, so it's left unimplemented.

**Comment by swankjesse** [comment]
Awesome!
