### ISSUE TITLE
HttpURLConnectionImpl loops forever trying to recover from a RouteException after disconnect() is called

### ISSUE THREAD

**Issue by jdcormie** [square/okhttp#2532]
[Test case that demonstrates the problem.](https://gist.github.com/jdcormie/dc1982436ace9750139777e9fcc6ed46
)

I noticed the bug in branch okhttp_27 but it may affect other versions.

In words: the problem is that HttpEngine.recover(RouteException) returns true, indicating that the request can be recovered, even when the HttpEngine itself is cancelled. Yet a call to HttpEngine.connect() on a cancel()ed instance always throws IOException. This results in an infinite loop of recover()/connect() rooted at HttpURLConnectionImpl.execute(). From the caller's perspective, calls into HttpURLConnection that require the response simply never return.

A possible fix could be to modify StreamAllocation.recover(RouteException) to check for cancellation and decline recovery. Something like:

```
public boolean recover(RouteException e) {
+  if (canceled) {
+   return false;
+  }

  if (connection != null) {
    connectionFailed(e.getLastConnectException());
  }
  ...
```

A possible work around could be to set OkHttpClient.setRetryOnConnectionFailure(false)

**Comment by jdcormie** [comment]
I believe this problem is present in the master branch as well. [The test case is almost the same](https://gist.github.com/jdcormie/f510dc63090b647a5abda61b238c3115) and my proposed fix above appears to work.

**Comment by swankjesse** [comment]
Serious problem. Will fix ASAP.

**Comment by swankjesse** [comment]
Fixed in the next release. We overhauled HttpURLConnectionImpl to use the OkHttp native API behind the scenes.
