### ISSUE TITLE
Allow resizing request cache

### ISSUE THREAD

**Issue by Groxx** [square/okhttp#2545]
Resizing the disk cache currently seems to require one of:
- ending all requests and blocking new ones, then when the queue is empty, dropping the old OkHttp instance and starting a new one with the new desired disk cache size
- kill the app, reload with new configuration
  and then either waiting for a request to come in, or calling `flush()`.

This is rather complex or a poor user experience.  The backing DiskLRUCache has support for resizing, would it be possible to add a call to `setMaxSize(bytes)`?

**Comment by Groxx** [comment]
Actually, now that I read through a few layers again... is the `urls()` iterator in least-recently-used order?  If so, iterating over that and deleting entries until size < desired would work for a size-reducing operation.

Having a `setMaxSize()` method would still be useful though, as it would allow increasing the size, and simplify this process.  It would also be more resilient against changes to the backing cache structure, so `urls()` wouldn't be forced to maintain iteration order compatibility for this.

**Comment by swankjesse** [comment]
Just curious – why are you resizing the response cache? Are you aware of evictAll() ?
https://square.github.io/okhttp/3.x/okhttp/okhttp3/Cache.html#evictAll--

**Comment by Groxx** [comment]
The app I work on is essentially an image browser.  It's not uncommon to end up downloading hundreds or thousands of megabytes of images in a single session.  And as much as possible, I'd like to keep them available offline - everything works offline.

That's a lot of data to store.  I'm doing what I can, but if the user suddenly gets a low-disk-space notification, I'd prefer to let them limit my app as easily as possible - that means runtime trimming.  And kicking everything out with evictAll could mean a ton of offline-availability discarded.
Conversely, if they want to raise the limit, I'd like to take advantage of that immediately, so the following requests don't evict things they may value.  Why would they expect otherwise?

So I want to give them a couple ways to restrict the storage the app can use.  "At most X mb"  or "at most X% of free space", most likely, as other apps have chosen those and they're mostly understandable.  If it's shrunk, I should free up space immediately.  If it's grown, I should use more available space immediately.
Currently this requires killing and restarting the app, evicting all in-memory caches, and at _best_ is a kinda janky experience.  I'd prefer to avoid that.

**Comment by swankjesse** [comment]
Yep, your use case makes sense. It's not something I'm convinced is a common use case, but it makes sense. If you want you can probably hack this in immediately with a little reflection!

**Comment by Groxx** [comment]
Not sure I agree on that, but I am a bit of an edge-case, so I understand why it hasn't been important to people in the past :)   I'm happy to reflect to get this done tho - thanks for the suggestion!  I suspect it'll work fine.

That all said: any chance of converting the cache to an interface, and allowing us to provide a different implementation?  Obviously making a _good_ cache is non-trivial, but having finer-grained control over how things are cached could be useful at times (e.g. "delete sub-folder", save some internal, some external, etc).

**Comment by swankjesse** [comment]
If you’re looking for a lot more control, also take a look here:
https://github.com/square/okhttp/blob/master/okhttp/src/main/java/okhttp3/internal/io/FileSystem.java

This isn’t currently public API, and probably won’t ever be, but you might be able to use it to accomplish what you need.

**Comment by yschimke** [comment]
Won't fix.
