### ISSUE TITLE
okhttp Cookie strips off leading . from domain

### ISSUE THREAD

**Issue by karthikrg** [square/okhttp#2549]
`  private static String parseDomain(String s) {
    if (s.endsWith(".")) {
      throw new IllegalArgumentException();
    }
    if (s.startsWith(".")) {
      s = s.substring(1);
    }
    String canonicalDomain = domainToAscii(s);
    if (canonicalDomain == null) {
      throw new IllegalArgumentException();
    }
    return canonicalDomain;
  }`

Cookie seems to strip off the leading . from the domain; this in turn causes Android's CookiePolicy#ACCEPT_ORIGINAL_SERVER to drop the cookie when used in conjunction with JavaNetCookieStore and a CookieManager. Currently I am getting around this by using a custom interceptor to manually parse the header and directly persist cookies into CookieManager.

Why don't we preserve the domain as is from the header?

**Comment by swankjesse** [comment]
Yup, this is a problem when converting to a format that works with CookieManager. (It isn't a problem with our cookie class itself.)

**Comment by boxme** [comment]
@swankjesse HttpCookie#domainMatches in CookiePolicy#ACCEPT_ORIGINAL_SERVER has a slightly different set of matching rules compared to Cookie#domainMatch. Is there a reason for this?

I'm trying to understand the rationale to stripping off the leading . from the domain.

Thanks!

**Comment by swankjesse** [comment]
It's a bug! Can fix.
