### ISSUE TITLE
At Okhttp2.0,we can okhttpclient.cancel(tag). But at Okhttp3.0,How to cancel a request？

### ISSUE THREAD

**Issue by Larnoo** [square/okhttp#2550]
At Okhttp2.0,we can okhttpclient.cancel(tag). But at Okhttp3.0,How to cancel a request？

**Comment by swankjesse** [comment]
Dupe of https://github.com/square/okhttp/issues/2205

**Comment by GhostInMatrix** [comment]
Well，when using okHttp3, you can set tag in request,like:Request request = new Request.Builder()
                .url(url)
                .tag("sss").build();
so,when you wanna cancel the request with tag "sss",you can do like this:


 for(Call call : mOkHttpClient.dispatcher().queuedCalls()) {
            if(call.request().tag().equals("sss"))
                call.cancel();
        }
        for(Call call : mOkHttpClient.dispatcher().runningCalls()) {
            if(call.request().tag().equals("sss"))
                call.cancel();
        }

**Comment by randomlock** [comment]
How to know if the call was cancelled ?

**Comment by JakeWharton** [comment]
isCanceled()
