### ISSUE TITLE
java.io.IOException: stream was reset: REFUSED_STREAM on okhttp 3.2.0 on POST request

### ISSUE THREAD

**Issue by martinvol** [square/okhttp#2551]
Doing the POST [request example](https://github.com/square/okhttp/blob/master/samples/guide/src/main/java/okhttp3/recipes/PostForm.java)

I got

`05-11 20:11:40.678 13113-13165/com.example.martin.e_fluent W/System.err: java.io.IOException: stream was reset: REFUSED_STREAM
05-11 20:11:40.679 13113-13165/com.example.martin.e_fluent W/System.err:     at okhttp3.internal.framed.FramedStream.checkOutNotClosed(FramedStream.java:574)
05-11 20:11:40.680 13113-13165/com.example.martin.e_fluent W/System.err:     at okhttp3.internal.framed.FramedStream.access$1200(FramedStream.java:34)
05-11 20:11:40.680 13113-13165/com.example.martin.e_fluent W/System.err:     at okhttp3.internal.framed.FramedStream$FramedDataSink.emitDataFrame(FramedStream.java:508)
05-11 20:11:40.680 13113-13165/com.example.martin.e_fluent W/System.err:     at okhttp3.internal.framed.FramedStream$FramedDataSink.close(FramedStream.java:545)
05-11 20:11:40.680 13113-13165/com.example.martin.e_fluent W/System.err:     at okio.RealBufferedSink.close(RealBufferedSink.java:241)
05-11 20:11:40.680 13113-13165/com.example.martin.e_fluent W/System.err:     at okhttp3.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:705)
05-11 20:11:40.680 13113-13165/com.example.martin.e_fluent W/System.err:     at okhttp3.internal.http.HttpEngine.readResponse(HttpEngine.java:563)
05-11 20:11:40.680 13113-13165/com.example.martin.e_fluent W/System.err:     at okhttp3.RealCall.getResponse(RealCall.java:241)
05-11 20:11:40.680 13113-13165/com.example.martin.e_fluent W/System.err:     at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:198)
05-11 20:11:40.680 13113-13165/com.example.martin.e_fluent W/System.err:     at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:160)
05-11 20:11:40.680 13113-13165/com.example.martin.e_fluent W/System.err:     at okhttp3.RealCall.execute(RealCall.java:57)
05-11 20:11:40.680 13113-13165/com.example.martin.e_fluent W/System.err:     at com.example.martin.e_fluent.RetrieveData.doInBackground(RetrieveData.java:103)
05-11 20:11:40.680 13113-13165/com.example.martin.e_fluent W/System.err:     at com.example.martin.e_fluent.RetrieveData.doInBackground(RetrieveData.java:31)
05-11 20:11:40.680 13113-13165/com.example.martin.e_fluent W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:295)
05-11 20:11:40.680 13113-13165/com.example.martin.e_fluent W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
05-11 20:11:40.680 13113-13165/com.example.martin.e_fluent W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
05-11 20:11:40.680 13113-13165/com.example.martin.e_fluent W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
05-11 20:11:40.680 13113-13165/com.example.martin.e_fluent W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
05-11 20:11:40.680 13113-13165/com.example.martin.e_fluent W/System.err:     at java.lang.Thread.run(Thread.java:818)`

The line that fails is

`Response response = client.newCall(request).execute();`

using 

`compile 'com.squareup.okhttp3:okhttp:3.2.0'` on Android Studio 2.1.1

**Comment by swankjesse** [comment]
Will fix with https://github.com/square/okhttp/issues/2543
