### ISSUE TITLE
[feature request] persistent storage similar to Cache

### ISSUE THREAD

**Issue by yschimke** [square/okhttp#2554]
Is there a planned story for persistent storage e.g. Cookies, ~HTTP Public Key Pinning~ or HTTP Strict Transport Security?

These can easily be done externally, but as okhttp is higher level than a toolkit like netty, they seem in scope.  I find it easy to imagine OkHttp as a UserAgent, which probably directs my assumptions.

**Comment by swankjesse** [comment]
Yeah, definitely. I spent quite a while contemplating what this would look like for OkHttp 3. My ideal was to take a directory in your OkHttpClient.Builder and we’d make the rest Just Work.

Unfortunately upon further investigation I decided this was too simple. In particular it means we either need to either forbid multiple processes from sharing a directory (as Cache insists) or coordinating that manually in our own code. Also writing code to recover from interrupted writes, evicting old data, cookie privacy, etc.

Open to ideas on this. I think exposing an interface for all of these persistent parts is a good idea.

**Comment by swankjesse** [comment]
Let’s do this. Will allow us to do smart things like anticipating HTTP/2.
https://github.com/square/okhttp/issues/3083

**Comment by yschimke** [comment]
Watching https://github.com/square/okio/pull/680

**Comment by yschimke** [comment]
It's tempting to use Android SQLite (android.database.sqlite) here if we are in Android.

**Comment by Ethan1983** [comment]
Can this be leveraged for offline use cases? Use the permanent store when not connected with an API for apps to clear specific content as needed.

Current implementation of Cache used with OkHttp doesn't work well in all cases as it is limited with a predefined size.

**Comment by yschimke** [comment]
@Ethan1983 No, this is specifically about remembering things that OkHttp learns during one session, that it should remember across sessions.  Strict HTTPS / permanent redirects are probably the simplest ones.

Not making the Cache unlimited.

**Comment by yschimke** [comment]
Closing as low priority.
