### ISSUE TITLE
libc: Fatal signal 11 (SIGSEGV) at 0x006d6100 (code=1), thread 19252 (OkHttp Dispatch)

### ISSUE THREAD

**Issue by libill** [square/okhttp#2564]
app crash, but the log only :

libc: Fatal signal 11 (SIGSEGV) at 0x006d6100 (code=1), thread 19252 (OkHttp Dispatch)

**Comment by dave-r12** [comment]
@libill can you provide any other information?

**Comment by swankjesse** [comment]
Nothing we can fix with this. It's possible the change isn't related to OkHttp; that's the thread that calls you back.

**Comment by shenjianli** [comment]
W/dalvikvm: Invalid indirect reference 0x43b0a850 in decodeIndirectRef
E/dalvikvm: VM aborting
A/libc: Fatal signal 11 (SIGSEGV) at 0xdeadd00d (code=1), thread 32165 (OkHttp Dispatch)

**Comment by shenjianli** [comment]
app crash in android 4.2.2

**Comment by georgethms10** [comment]
> Nothing we can fix with this. It's possible the change isn't related to OkHttp; that's the thread that calls you back.

@swankjesse  do you mean that that its the thread that is hanging and causing the crash?
