### ISSUE TITLE
java.net.ProtocolException: Too many follow-up requests: 21

### ISSUE THREAD

**Issue by KinaZhen** [square/okhttp#2565]
- [ ] Bug report. 
05-19 15:10:45.502 1029-1029/ W/System.err:     at okhttp3.RealCall.getResponse(RealCall.java:289)
okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:198)
com.zhy.http.okhttp.log.LoggerInterceptor.intercept(LoggerInterceptor.java:46)
okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:187)
okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:160)
okhttp3.RealCall.access$100(RealCall.java:30)
okhttp3.RealCall$AsyncCall.execute(RealCall.java:127)
okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
java.lang.Thread.run(Thread.java:818)

when i use okhttp,this issue happened sometimes.help please!

**Comment by swankjesse** [comment]
Is it redirecting? Are you attempting and failing to do authentication?

**Comment by KinaZhen** [comment]
i'm not add cookies,but i get the Cookie: frontend=tci7q4vmui3j47o20g7djp8sq7; frontend=deleted. why?

**Comment by KinaZhen** [comment]
thank you,i have solved this problem.

**Comment by lakmalz** [comment]
How did you solved this problem?

**Comment by miniFrank** [comment]
@KinaZhen  may i know how to solve

**Comment by hlandim** [comment]
@miniFrank How?
