### ISSUE TITLE
Enhancement request for the Cache class.

### ISSUE THREAD

**Issue by adanecito** [square/okhttp#2566]
What kind of issue is this?

 - [ ] Feature Request. 

Please make public the get method in the Cache class so developers can retrieve the Response for a request.

Thanks.

**Comment by swankjesse** [comment]
Right now you can do this with OkHttpClient. Exposing direct access to the cache makes certain other changes difficult. What's your use case?

**Comment by adanecito** [comment]
When the network is disconnected. When I try to read the response body it is null for when requests are sent and the comment in the java docs that the message body can not be read. I can see the headers but I need the message body. There were comments about this on stackoverflow and my research showed people were getting it from the cache object before okhttp 3.x. I looked at the OkHttpClient source and did not see any way to get this cache response object or any other object that would give me the response body.
Thanks for the prompt reply I appreciate it.

**Comment by swankjesse** [comment]
You can make a regular request using `CacheControl.FORCE_CACHE` as a header.

**Comment by swankjesse** [comment]
(that’ll return HTTP 504 if the cached response cannot be served.)

**Comment by adanecito** [comment]
Thanks, I will take a look at this.
Best Regards,
-Tony
 

    On Saturday, May 21, 2016 9:12 AM, Jesse Wilson <notifications@github.com> wrote:
 

 You can make a regular request using CacheControl.FORCE_CACHE as a header.—
