### ISSUE TITLE
Add possibility to exclude requests from silent retries

### ISSUE THREAD

**Issue by benjaminbauer** [square/okhttp#258]
###### Use-case

I need to make API-Requests via HTTPS from an Android App with reused sockets to avoid overhead for SSL-handshake etc. Though the requests are idempotent, my app relies on the user seeing the result of the request: the first request will give an HTTP 200, while all succeeding will result in an error.
I was using java.net.HttpURLConnection and java.net.URL's openConnection() until I observed the silent retry of POST requests after an IOException which I blame on http://bugs.sun.com/bugdatabase/view_bug.do?bug_id=6382788. But since the proposed fix (setting sun.net.http.retryPost to false) to this does not seem to work on the android-version of URLConnection, and the alternative (disable keep-alive)  is not acceptable for my use-case I gave OkHttp a try just to face the same...
###### Problem

If a request fails with a SocketTimeout (or basically any other problem), I have to be sure it is never sent to the server.
###### Proposed Solutions
1. A global setting where I could define, that OkHttp should never retry POST by itself.
2. It would be nice to have something like an explicit abort for the Connection

``` java
try{
  final HttpURLConnection urlConnection =  mOkHttpClient.open(url);
  //do some I/O
  //...
}
catch (SocketTimeoutException ste){
  urlConnection.abort();
}
```

**Comment by AKASH941** [comment]
Policy of retry , we can customize with
 defaultHttpClient.setHttpRequestRetryHandler(new DefaultHttpRequestRetryHandler
                                             (0, false));
