### ISSUE TITLE
Request that android dependencies be moved to separate package

### ISSUE THREAD

**Issue by zerowaitstate** [square/okhttp#2584]
There is currently a required dependency in the pom.xml to the Google Android API.  When OkHttp is included in non-Android projects, that necessitates including Android code, even when it is not needed for the application (in my case, this quadrupled the size of the deployed app).

From reading the git history, it looks like the Android dependency was created so that a ready-made logging NetworkInterceptor that uses android's Log.d() could be included.  Can this class not be moved to a separate package (i.e., something like okhttp-android), so that non-Android developers don't have to fork the code to remove the dependency?

**Comment by JakeWharton** [comment]
It's marked as `provided` so it is not included as a dependency of the library. However you are packaging your application you should not be bundling `provided` or `optional` dependencies.
