### ISSUE TITLE
 Handling third party logins with okhttp's Authenticator interface

### ISSUE THREAD

**Issue by rakesh1988** [square/okhttp#2585]
Feature Request. 
I am trying to understand the Authenticator interface which helps us to fetch a new token from the API server. In the current implementation, I see that this interface can handle only a single call to the API server with the user credentials (username and password) to fetch the new token. Also this has to be synchronous process.
In a use case where a third party authentication like G+/FB/Twitter is involved, one has to make multiple calls to check if the user has not revoked the permission/get a new token to send to API server to authenticate again. How can we handle such use case in retrofit/okhttp.

**Comment by swankjesse** [comment]
You can do whatever you like in `Authenticator` to prepare credentials for the follow-up request. You can add preemptive authentication by setting the appropriate headers in the application code, or in an interceptor, or wherever.

Here’s a couple examples:
https://github.com/rburgst/okhttp-digest
https://github.com/pakerfeldt/okhttp-signpost

Does that help?

**Comment by swankjesse** [comment]
No action to take here.
