### ISSUE TITLE
 Exception java.lang.OutOfMemoryError: Could not allocate JNI Env

### ISSUE THREAD

**Issue by Vivecstel** [square/okhttp#2598]
Got this exception from a beta tester using samsung galaxy s6 tracked by google's firebase : 

Exception java.lang.OutOfMemoryError: Could not allocate JNI Env
java.lang.Thread.nativeCreate (Thread.java:)
java.lang.Thread.start (Thread.java:1063)
okhttp3.internal.framed.FramedConnection.start (FramedConnection.java:525)
okhttp3.internal.framed.FramedConnection.start (FramedConnection.java:509)
okhttp3.internal.io.RealConnection.establishProtocol (RealConnection.java:210)
okhttp3.internal.io.RealConnection.buildConnection (RealConnection.java:171)
okhttp3.internal.io.RealConnection.connect (RealConnection.java:111)
okhttp3.internal.http.StreamAllocation.findConnection (StreamAllocation.java:187)
okhttp3.internal.http.StreamAllocation.findHealthyConnection (StreamAllocation.java:123)
okhttp3.internal.http.StreamAllocation.newStream (StreamAllocation.java:93)
okhttp3.internal.http.HttpEngine.connect (HttpEngine.java:296)
okhttp3.internal.http.HttpEngine.sendRequest (HttpEngine.java:248)
okhttp3.RealCall.getResponse (RealCall.java:243)
okhttp3.RealCall$ApplicationInterceptorChain.proceed (RealCall.java:201)
okhttp3.RealCall.getResponseWithInterceptorChain (RealCall.java:163)
okhttp3.RealCall.execute (RealCall.java:57)
com.steleot.seriez.utils.HttpClient.executeGetRequest (HttpClient.java:74)
com.steleot.seriez.utils.JobsUtils.getEpisodes (JobsUtils.java:594)
com.steleot.seriez.services.AddBaseIntentService.runEpisodes (AddBaseIntentService.java:95)
com.steleot.seriez.services.AddBaseIntentService.runService (AddBaseIntentService.java:41)
com.steleot.seriez.services.AddSeriesIntentService.onRun (AddSeriesIntentService.java:49)
com.steleot.seriez.services.base.BaseIntentService.onHandleIntent (BaseIntentService.java:47)
android.app.IntentService$ServiceHandler.handleMessage (IntentService.java:66)
android.os.Handler.dispatchMessage (Handler.java:102)
android.os.Looper.loop (Looper.java:158)
android.os.HandlerThread.run (HandlerThread.java:61)

below is method call from HttpClient : 

    public String executeGetRequest(String url, String token) {
        Response response;
        OkHttpClient okHttpClient = new OkHttpClient.Builder()
                .connectTimeout(15, TimeUnit.SECONDS)
                .readTimeout(15, TimeUnit.SECONDS)
                .writeTimeout(15, TimeUnit.SECONDS)
                .build();

        Request request = new Request.Builder()
                .url(url)
                .addHeader(AUTHORIZATION, BEARER + " " + token)
                .addHeader(ACCEPT_LANGUAGE, PreferenceUtils.getString(mContext, mContext.getString(R.string.languageKey),
                        mContext.getString(R.string.englishValue)).toLowerCase())
                .build();

        try {
            response = okHttpClient.newCall(request).execute();
            return response.body().string();
        } catch (IOException e) {
            LogHelper.d(e.getMessage());
        }
        return null;
    }

Thanks

**Comment by Vivecstel** [comment]
I parse the string returned later using gson. Should I use response.body().charStream() instead of response.body().string() ?

**Comment by swankjesse** [comment]
Yes.

**Comment by a1018875550** [comment]
I meet this issues too;But I'm using the retrofit with rxjava;
like this:
`public interface VerifyService {

    @FormUrlEncoded
    @POST("User/Verify")
    Observable<ResponseBody> verify(@Field("EMail") String EMail,
                                    @Field("LoginIP") String LoginIP,
                                    @Field("LoginType") String LoginType,
                                    @Field("Password") String Password);
}
`
and I'm not use Response ;

**Comment by Trolldemorted** [comment]
Could you elaborate what was responsible for the exception?

I am experiencing the same at the moment, and i'd like to understand what is happening. Did replacing string() with charStream() solve this issue?
