### ISSUE TITLE
different uppercase and lowercase

### ISSUE THREAD

**Issue by canran** [square/okhttp#2599]
What kind of issue is this?

 - [ ] Question. when i use OKHTTP,I find a issue(may be not the recent version）
when i use below:
private static final String actionUrl1 = "http://magnifier.tencent.com/v3/mobile/chunksUploadFile";
private static final String actionUrl2 = "http://Magnifier.tencent.com/v3/mobile/chunksUploadFile";

//main code
//URL url = new URL(actionUrl1);
//URL url = new URL(actionUrl2);
hc = (HttpURLConnection) url.openConnection(); 
hc.setRequestProperty("Content-Type", "multipart/form-data; boundary=" + BOUNDARY); 
hc.setRequestProperty("Charsert", "UTF-8"); 
hc.setDoOutput(true); 
hc.setDoInput(true); 
hc.setUseCaches(false); 
hc.setRequestMethod("POST"); 	     
OutputStream dout = hc.getOutputStream(); 

when i use actionUrl1 ,every thing is ok
when i ues actionUrl2 ,it have 10% the responseCode is 501

i don't know why

**Comment by swankjesse** [comment]
Please try the current version and report back if there are still problems.

**Comment by canran** [comment]
the current version is OK!
e~~ i mean that weather it is a optimized-designed point,about decode or anything else

**Comment by swankjesse** [comment]
Yes, the current behavior is deliberate. Anything else is a bug. You might find this interesting:
https://corner.squareup.com/2015/05/okhttp-2-4.html

**Comment by canran** [comment]
ok thanks so nice！！！
