### ISSUE TITLE
Request for addition to works with OkHttp

### ISSUE THREAD

**Issue by amitshekhariitbhu** [square/okhttp#2603]
[Android Networking](https://github.com/amitshekhariitbhu/AndroidNetworking)
Android Networking is a powerful library for doing any type of networking in Android applications

Please add it on wikis of works with OkHttp

**Comment by swankjesse** [comment]
Neat library, but I'm uncomfortable endorsing it at this time. A quick look through the project source code shows some unoriginal code that lacks the original owner’s copyright. If you're going to build on other people's work, you need to honor their original ownership and retain their copyright.

**Comment by amitshekhariitbhu** [comment]
@swankjesse : I am not much aware about licences . but I have added so my times in my readme file that this library use OKHttp and Okio with github links.
Please tell me what to do to give more credits . I will surely add this in my project.

**Comment by swankjesse** [comment]
Please learn about licenses. Retain the original copyright when you take code from other projects (AOSP, Volley).

**Comment by amitshekhariitbhu** [comment]
@swankjesse  : sure I will do the same .

**Comment by amitshekhariitbhu** [comment]
@swankjesse  :  As per suggested by you I have updated licenses . Please review and re-consider it. and tell me if something is wrong I will do the same.

**Comment by amitshekhariitbhu** [comment]
@swankjesse : [Credits](https://github.com/amitshekhariitbhu/AndroidNetworking#credits)
