### ISSUE TITLE
Certificate pinner doesn't work if host name has capital letters

### ISSUE THREAD

**Issue by jkauppin** [square/okhttp#2609]
If certificate pinner is set for host "www.HOST.com" if doesn't apply to the calls that has endpoint "www.host.com".

The CertificatePinner.findMatchingPins() should ignore the case because http doesn't care if the name is in uppercase or not.

Tested with OkHttp 2.7.5.

**Comment by artem-zinnatullin** [comment]
Why not pass lowercased hostname to the CertificatePinner?

**Comment by jkauppin** [comment]
Yes, that was the fix on the app. However that feels unsafe since a small typo in the host will disable the certificate pinning. From http point of view capital letters has no meaning.

**Comment by swankjesse** [comment]
Yeah, we should fix this.
