### ISSUE TITLE
App crashing on Headers Line 320

### ISSUE THREAD

**Issue by paul321** [square/okhttp#2610]
Library is crashing the Android app on the following line in Headers.java

`if (c <= '\u001f' || c >= '\u007f') {
    throw new IllegalArgumentException(Util.format(
    "Unexpected char %#04x at %d in %s value: %s", (int) c, i, name, value));
}`

The app needs to send date in header in the following code:
`
Date date = new Date();
SimpleDateFormat dateformat = new SimpleDateFormat("EEE, d MMM yyyy HH:mm:ss ZZZ");
String strDate = dateformat.format(date);
Request request = new Request.Builder()
    .header("Content-type", "application/json")
    .header("Date", strDate)
    .url(url)
    .build();
`

**Comment by swankjesse** [comment]
What is the content of `strDate`? Presumably this is not a US locale, and the month names require non-ASCII characters.

**Comment by paul321** [comment]
It's something like this
Wed Oct 16 00:00:00 CEST 2013
Will try to force it to use US locale, right now it's phone defaults and maybe in Asia it crashes

**Comment by paul321** [comment]
I think we can close it
