### ISSUE TITLE
[Feature Request] change socket timeouts without creating new instance of OkHttpClient

### ISSUE THREAD

**Issue by bexp** [square/okhttp#2616]
In OkHttp 2.x I could change timeouts whenever I wanted.

Real life example: 
Listen for network type change and apply timeouts accordingly. For example it makes sense to 
have larger timeout for 2G than for LTE.

Now with immutability in OkHttp3 I can't do it anymore.
creating another instance with Builder interface is the only workaround which makes it more awkward for no reason. What is the rationale ? Why do you think that all fields inside OkHttpClient have to be immutable ?

**Comment by swankjesse** [comment]
One consequence of the previous behavior was that you could have bugs if two requests wanted different timeouts. For example a slow call and a fast call that both share the same HTTP client could compete with each other.
