### ISSUE TITLE
How to mock when one cannot change baseUrl?

### ISSUE THREAD

**Issue by prabintim** [square/okhttp#2622]
I am trying to mock response for chat application that uses chat sdk called [layerhq-atlas](https://github.com/layerhq/Atlas-Android). The problem is that I don't know what to set for base url. I can't see any retrofit code in their code. 
From mockwebserver sample,
```
  HttpUrl baseUrl = server.url("/v1/chat/"); // I don't know what string to set here.
  Chat chat = new Chat(baseUrl);
```

I tried server.url("/"), but when I send a message, server.getRequestCount() is still zero.

Is there a way such that when any web request is made, it returns a canned response?

**Comment by swankjesse** [comment]
Please post usage questions to StackOverflow.
