### ISSUE TITLE
addEncodedQueryParameter is not working as expected

### ISSUE THREAD

**Issue by nezen** [square/okhttp#2623]
When I use addEncodedQueryParameter, I want to leave the equal sign as what it is, but it's always encoded as %3D. 
Some other guys seem to have this problem as well [https://github.com/square/retrofit/issues/1199]

**Comment by Alisunov** [comment]
Hi! I've got the same problem and have looked into okhttp source and found the problem.
`addEncodedQueryParameter()` **does encode** keys and values of the url, but **does not re-encode** "%" symbol.

So, one of the solutions is to use `@Query("fieldName") List<String> values`

**Comment by KChernenko** [comment]
I faced with the similar problem: symbols `= `and `&` in the `@QueryMap` which are passed as a part of values are always encoded.

**Comment by JakeWharton** [comment]
That is working as intended. Those are illegal characters in a value since
they are separators. We are canonicalizing the value to work around this.

**Comment by Ginkosama** [comment]
Well, this does work as intended IF you're using a server that does not allow an equal symbol to be something else than a separators... We are obviously working with a different user case scenario...

I'm facing the problem of = being encoded while i don't want it to be...

I can understand the current idea behind encoded=true, not re-encoding already encoded values... but then clearly a second level tag is needed to completely avoid to encode the value passed...

Why do you feel the need to force us to work with the classic HTTP RFC ?

**Comment by Ginkosama** [comment]
@Alisunov could you please develop on how to use a List<String> to work around this issue ? I've tried but it still got the same behavior.

**Comment by swankjesse** [comment]
You can use `Builder.encodedQuery()` when you want to retain `=` characters.
https://square.github.io/okhttp/3.x/okhttp/okhttp3/HttpUrl.Builder.html#encodedQuery-java.lang.String-

**Comment by Ginkosama** [comment]
No you can see [here](https://github.com/square/okhttp/blob/master/okhttp/src/main/java/okhttp3/HttpUrl.java#L1116) that it will encode it anyway, it only does not re-encode what's already encoded.

I ended up having to use an interceptor to force-decode the = characters... which is ugly...

**Comment by swankjesse** [comment]
@Ginkosama false. `Builder.encodedQuery()` will not encode an incoming `=` charager.

**Comment by Ginkosama** [comment]
You're correct, its using QUERY_ENCODE_SET as parameter to canonicalize(), which does not contains the = character !

Thanks, I will try to use it, but will it require to build a different retrofit instance object or there is a way to pass it when calling an API endpoint ?

**Comment by swankjesse** [comment]
Retrofit won’t be able to compose a query for you this way. You’ll need to compose it manually and provide an `HttpUrl` instance to Retrofit.

**Comment by NeLk42** [comment]
A very simple solution is to pass the value encoded and then add the encoded = true flag to retrofit. 

`String item = "MTUwNTIyODgxMDg4Mw==";`

` encodedItem = URLEncoder.encode(item, "utf-8");`

`@Query(value = "item", encoded = true) String item`

This way when the time comes it'll decode it.

**Comment by CodeMason** [comment]
Late to the party, but I ran into this just now, where the query parameters we getting encoded in a way that quite clearly doesn't work!

 This was _a different_ way to solve the problem, also this is in Kotlin.

```
            val url = URI(url).normalize().toASCIIString().let {
                if (queryParameters.isNotEmpty()) {
                    it + "?" + queryParameters.joinToString(separator = "&")
                } else {
                   it
                }
            }

// one would think this is the BETTER way to do add query parameters HOWEVER this encodes them in such a way that it doesn't work!
//            val httpUrlBuilder = url.toHttpUrl().newBuilder()
//                .also { builder ->
//                    queryParameters.forEach {
//                        val (key, value) = it
//                            .split('=', limit = 2)
//                            .also { (it.size == 2).also { hasTwoParts ->
//                                if (!hasTwoParts) throw IllegalStateException("Key with no value: ${it.getOrNull(0)}")
//                            }
//                            }
//                        builder.addQueryParameter(key, value)
//                    }
//                }.build()
```
