### ISSUE TITLE
Robolectric tests fail after switching v3.2.0 -> v3.3.1

### ISSUE THREAD

**Issue by DmitriyZaitsev** [square/okhttp#2625]
I'm facing the issue with Robolectric 3.1.

When I tried to upgrade okhttp3 from 3.2.0 to 3.3.1, all my robolectric tests became red.
The code line that breaks tests:
`final OkHttpClient.Builder builder = new OkHttpClient.Builder();`
 

Below are the parts of stacktraces from two tests:
* `java.lang.NoClassDefFoundError: Could not initialize class okhttp3.OkHttpClient at okhttp3.OkHttpClient$Builder.<init>(OkHttpClient.java:381)`

* `java.lang.ExceptionInInitializerError at okhttp3.OkHttpClient$Builder.<init>(OkHttpClient.java:381)`

**Comment by dave-r12** [comment]
I believe this duplicates #2533. There are a few potential workarounds mentioned on that issue.
