### ISSUE TITLE
Sometimes I am getting the headers in lowercase

### ISSUE THREAD

**Issue by SandroMachado** [square/okhttp#2626]
Hi,

I am not able to reproduce this in a consistent way, but for the same request, usually I get the `Content-Range` header with the first letters capitalised. But sometimes I get it in complete lowercase (`content-range`). There is a reason for that? Am I missing something?

Regards

**Comment by JakeWharton** [comment]
Header names are case-insensitive so you need to handle this. See: https://tools.ietf.org/html/rfc7230#section-3.2

This is probably a result of speaking HTTP/1.1 vs HTTP/2 since the latter favors lowercase.

**Comment by SandroMachado** [comment]
@JakeWharton thanks 👍

**Comment by nmr8acme** [comment]
For people like me it's worth noting that not only are header names case insensitive, but that more importantly (to me) HTTP2 requires that they be lowercase on the wire and the appendix of pre-indexed headers is all in lowercase, so this is not something that is a necessity of HTTP2, and not an implementation detail.
