### ISSUE TITLE
ErrorCode400: Wrong body returned, but not by errorCode 403: response.body.string() returns 

### ISSUE THREAD

**Issue by arberg** [square/okhttp#2627]
On errornous requests I don't get the correct body on statuscode 400.

I have a request that in Postman returns a body with a json-string and status code '400 Bad Request'. In OkHttp v2.7.5 it returns 

> Error 400: SRVE0295E: Error reported: 400

from 

```
Response response = client.newCall(request).execute();
response.body().string();

```
If its a 403 with another json body, I get the json body as expected.

Does this look like a bug?

It is an ssl request with custom trusted certificates and client key authentication, so I cannot post a non-mocked test. I havn't tried reproducing in mock-server test yet.

Best Alex

PS: I'm using OkHttp on a Tomcat server, with java 1.8.0_91, I get same result on a junit test

**Comment by dave-r12** [comment]
My initial reaction is no, this does not look like a bug given the information. If it were me, I'd start by tracing the request on the server to see what's triggering that message.

**Comment by swankjesse** [comment]
No action for us to take here.

**Comment by wsf5918** [comment]
i had the same problems, i do a post request post some datas to the server. the request params a like below.
![image](https://cloud.githubusercontent.com/assets/5617446/19888602/9069b580-a06a-11e6-94bb-7ee077d5868e.png)

i had use the Charles to watch the datas server response to me . the server response to device like below.

![image](https://cloud.githubusercontent.com/assets/5617446/19888620/c4f42ad8-a06a-11e6-8d52-6da79670a92c.png)


this is my code 
![image](https://cloud.githubusercontent.com/assets/5617446/19888643/f76825f0-a06a-11e6-8fbd-41d5555cf6ad.png)


and i get the datas response from the server is below the log you can see 

![image](https://cloud.githubusercontent.com/assets/5617446/19888676/2a3a1056-a06b-11e6-8f79-eef3121d4674.png)

i was confused ,is any problems there .
