### ISSUE TITLE
Subsequent requests fail with java.net.UnknownHostException if the first failed with java.net.SocketTimeoutException

### ISSUE THREAD

**Issue by mikekudzin** [square/okhttp#2631]
I use retrofit2 backed by okhttp3 in my project.
Encountered an issue when OkHttpClient failed to execute requests if **the first executed request** failed with SocketTimeoutException:
> W/System.err: java.net.SocketTimeoutException: timeout
W/System.err:     at okio.Okio$3.newTimeoutException(Okio.java:207)
W/System.err:     at okio.AsyncTimeout.exit(AsyncTimeout.java:250)
W/System.err:     at okio.AsyncTimeout$2.read(AsyncTimeout.java:217)
W/System.err:     at okio.RealBufferedSource.indexOf(RealBufferedSource.java:306)
W/System.err:     at okio.RealBufferedSource.indexOf(RealBufferedSource.java:300)
W/System.err:     at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:196)
W/System.err:     at okhttp3.internal.http.Http1xStream.readResponse(Http1xStream.java:184)

Error log for all subsequent requests:

> W/System.err: java.net.UnknownHostException: Unable to resolve host "my_real_existing_backend.com": No address associated with hostname
W/System.err:     at java.net.InetAddress.lookupHostByName(InetAddress.java:457)
W/System.err:     at java.net.InetAddress.getAllByNameImpl(InetAddress.java:252)
W/System.err:     at java.net.InetAddress.getAllByName(InetAddress.java:215)
W/System.err:     at okhttp3.Dns$1.lookup(Dns.java:39)
W/System.err:     at okhttp3.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:173)
W/System.err:     at okhttp3.internal.http.RouteSelector.nextProxy(RouteSelector.java:139)
W/System.err:     at okhttp3.internal.http.RouteSelector.next(RouteSelector.java:81)
W/System.err:     at okhttp3.internal.http.RouteSelector.next(RouteSelector.java:89)
W/System.err:     at okhttp3.internal.http.StreamAllocation.findConnection(StreamAllocation.java:174)
W/System.err:     at okhttp3.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:127)
W/System.err:     at okhttp3.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
W/System.err:     at okhttp3.internal.http.HttpEngine.connect(HttpEngine.java:289)
W/System.err:     at okhttp3.internal.http.HttpEngine.sendRequest(HttpEngine.java:241)

Test:
```
@Test
    public void testOkClientFailsToExecuteRequestsIfFirstFailedWithSocketTimeoutException() throws Exception {
        OkHttpClient.Builder builder = new OkHttpClient.Builder();
        builder.connectTimeout(2, TimeUnit.SECONDS);
        builder.readTimeout(2, TimeUnit.SECONDS);
        builder.retryOnConnectionFailure(false);
        OkHttpClient client = builder.build();

        // Create a MockWebServer. These are lean enough that you can create a new
        // instance for every unit test.
        MockWebServer server = new MockWebServer();

        //first response will be throttled to cause SocketTimeoutException
        MockResponse response = new MockResponse().addHeader("Content-Type", "application/json; charset=utf-8")
                .addHeader("Cache-Control", "no-cache").setBody("{\"count\":\"1\"}").throttleBody(1, 4, TimeUnit.SECONDS);
        //the second one will be ordinal
        MockResponse response2 = new MockResponse().addHeader("Content-Type", "application/json; charset=utf-8")
                .addHeader("Cache-Control", "no-cache").setBody("{\"count\":\"2\"}");
        server.enqueue(response);
        server.enqueue(response2);
        server.start();

        // Ask the server for its URL. You'll need this to make HTTP requests.
        HttpUrl baseUrl = server.url("/v1/chat/");
        Request.Builder requestBuilder = new Request.Builder();
        requestBuilder.post(RequestBody.create(MediaType.parse("application/json"), "{\"param\":\"val\"}"));
        requestBuilder.url(baseUrl);

        //this call will fail with SocketTimeoutException
        Call call = client.newCall(requestBuilder.build());
        call.enqueue(new Callback() {
            @Override
            public void onFailure(Call call, IOException e) {
                System.out.println("FAILED\n" + e.getCause());
            }

            @Override
            public void onResponse(Call call, Response responseInt) throws IOException {
                //this call should fail
                fail("First call should fall with SocketTimeoutException");
            }
        });
        Thread.sleep(4000);

        final int[] callExecutionResult = {-1}; //0 - success; 1 - failure
        final String[] failReason = {" "};
        //This call should pass
        call = client.newCall(requestBuilder.build());
        call.enqueue(new Callback() {
            @Override
            public void onFailure(Call call, IOException e) {
                System.out.println(e.toString());
                callExecutionResult[0] = 1;
                failReason[0] = e.toString();

            }

            @Override
            public void onResponse(Call call, Response responseInt) throws IOException {
                callExecutionResult[0] = 0;
            }
        });

        Thread.sleep(1000);

        server.shutdown();
        if (callExecutionResult[0] == 1) {
            fail(failReason[0]);
        }
    }
```
If **the first request was successful**, subsequent requests on the same client will be sent even if some of them will fail with timeout.

**P.S. As a workaround new OkHttpClient instance could be created each time a request is send.**

**Comment by dave-r12** [comment]
Is it possible there was an issue with the network? The `java.net.UnknownHostException` is happening during the DNS call, which occurs outside OkHttp. At least for me, that test case fails for a different reason.

**Comment by swankjesse** [comment]
No clear action for us to take on this one.

**Comment by dryware-fr** [comment]
There's a use case for that. Take a client configured for using a socket factory, for example one given by orchid tor library. Since orchid expects only DIRECT connections with unresolved hostnames, that dns call always will fail. Plus, the client forces us to provide a DNS or let it use the SYSTEM default.

Maybe you could remove the null check for the dns and use unresolved InetSocketAddress if it's null and there's a socket factory.

Or just add a flag to let us disabling that particular resolve call and use unresolved address whenever we see fit. Something like that in RouteSelector.resetNextInetSocketAddress : 

```
/** Prepares the socket addresses to attempt for the current proxy or host. */
  private void resetNextInetSocketAddress(Proxy proxy) throws IOException {

/* ... */

    if (proxy.type() == Proxy.Type.SOCKS || proxy.useTor()) { // <== this is the change
      inetSocketAddresses.add(InetSocketAddress.createUnresolved(socketHost, socketPort));
    } else {
      // Try each address for best behavior in mixed IPv4/IPv6 environments.
      List<InetAddress> addresses = address.dns().lookup(socketHost); // <== this is the offending line
      for (int i = 0, size = addresses.size(); i < size; i++) {
        InetAddress inetAddress = addresses.get(i);
        inetSocketAddresses.add(new InetSocketAddress(inetAddress, socketPort));
      }
    }

/* ... */

  }
```
