### ISSUE TITLE
okhttp3 retrofit2  rxandroid  Doing SetTokenInterceptor request or the original address, and the request is invalid!

### ISSUE THREAD

**Issue by zhuyuliang** [square/okhttp#2633]
okHttpClient.addNetworkInterceptor（new Interceptor() {
            @Override
            public Response intercept(Chain chain) throws IOException {
                Request request = chain.request();
                HttpUrl httpUrl = request.url();
                HttpUrl.Builder builder  = httpUrl.newBuilder().addQueryParameter("token",token);
                Request.Builder requestBuilder = request.newBuilder();
                Request request1 = requestBuilder.url(builder.build()).get() .build();
                  return chain.proceed(request1);
                    }
                }
                return chain.proceed(request);
            }）

Want to in the request url behind plus & token = token but add rxandroid observables < the UserBean > getNet intercept () after the original url

**Comment by swankjesse** [comment]
Please ask usage questions on StackOverflow.
