### ISSUE TITLE
Move MockWebServer TestRule implementation

### ISSUE THREAD

**Issue by KenVanHoeylandt** [square/okhttp#2635]
`MockWebServer` currently implements `TestRule`.
It is probably better to have a separate `MockWebServerRule`.
This would allow developers to use `MockWebServer` without the `junit` dependency.

Optionally, `MockWebServerRule` could be moved in to a `mockwebserver-junit` package for all `junit`-related functionality.

**Comment by JakeWharton** [comment]
We can't do this until OkHttp 4 since it's a breaking change.

**Comment by swankjesse** [comment]
It’s tempting to grow MockWebServer in scope and use it for things other than testing. That’d probably end up being a new thing, like an OkHttpServer or something. For now we’re in no hurry to do that work.

If you want a webserver for use beyond testing, you might want something else!

**Comment by KenVanHoeylandt** [comment]
The reasoning was that if you use it for mocking during testing, it might be useful for a demo-mode of an application too.

Either way, it's probably better to have a separate `MockWebServerRule` anyway, because that keeps the `MockWebServer` code cleaner.

**Comment by jodastephen** [comment]
Just to note that we use TestNG, so having `MockWebServer` pull in junit is a pain.

This doesn't have to wait until OkHttp 4 though. A new class `MockWebServerLight` could be added that did not have the dependency, and the pom.xml could be changed to declare the junit dependency as optional. Even if the pom.xml part was considered too risky, at least end users could exclude it in their pom.

**Comment by adriancole** [comment]
I have been a regular offender of making little fake servers using MWS and
a custom dispatcher. These are often used in unit tests, so junit hasn't
been an issue, but also dont feel strongly about it.

Ps MWS has been alive a long time! Here here!

**Comment by Ekt0s** [comment]
That would make it really easy to test business class that are using **Retrofit** as client 👍 
Just like @JakeWharton said I don't think this will be possible on **OkHttp 3.+**

**Comment by detouched** [comment]
[Similarly](https://github.com/square/okhttp/issues/2635#issuecomment-240987326) with JUnit 5: `MockWebServer` pulls in JUnit 4 which is undesirable, so an standalone version would be very useful.

Ugly but functioning workaround for now is to create a fake empty `org.junit.rules.ExternalResource` class.

**Comment by yschimke** [comment]
I'm closing mockwebserver issues like this.  We should probably pull out to a separate library rather than bundling updates with OkHttp.
