### ISSUE TITLE
OkHttp and FIPS compliance.(Feature Request)

### ISSUE THREAD

**Issue by NitzDKoder** [square/okhttp#2641]
Hi Folks,

C HTTP Client:
1)We use PJHTTP  HTTP Client at C level and do HTTP transactions.
http://www.pjsip.org/pjlib-util/docs/html/group__PJ__HTTP__CLIENT.htm

2) We Use wolfSSL for SSL and its FIPS compliant.
https://www.wolfssl.com/wolfSSL/Home.html

Java HTTP Client:
1)Plan is to use OkHttp java level.

2) How to make SSL and FIPS compliant?

https://en.wikipedia.org/wiki/FIPS_140-2

How to make okhttp fips complaint and make it working android device? Use JSafe/Spongy Castle java library JCE?

https://rtyley.github.io/spongycastle/
https://docs.oracle.com/javase/8/docs/technotes/guides/security/jsse/FIPS.html
https://docs.oracle.com/middleware/1213/wls/SECMG/fips.htm#SECMG768

Or use:
C level wolfSSL which is FIPS complaint lib to support both Android/iOS via JNI?

https://www.wolfssl.com/wolfSSL/Products-wolfssl.html

Any other Hints..Pls suggest..

Thanks
Nithin

**Comment by swankjesse** [comment]
It’s unlikely we’re going to pursue this.

**Comment by swankjesse** [comment]
I don’t know what FIPS compliance is. Ask whomever imposed this requirement on you and ask them what the process is. Worst case you end up paying somebody $$$ to read our source code and declare that it’s legit.

**Comment by NitzDKoder** [comment]
@swankjesse 

AFAIK android/Okhttp for SSL uses OpenSSL C library and uses java wrapper javax/net/ssl https://docs.oracle.com/javase/7/docs/api/javax/net/ssl/package-summary.html


Is it possible to repalce okhttp SSL module with wolfssl(C Load Library) which is FIPS complaint..how feasible it is..Pls suggest..

https://github.com/square/okhttp/search?utf8=%E2%9C%93&q=javax.net.ssl&type=Code


Replace Package javax.net.ssl  with com.wolfssl.


https://www.wolfssl.com/documentation/wolfssl-jni-javadocs/com/wolfssl/package-summary.html


Thanks
Nithin

**Comment by NitzDKoder** [comment]
@swankjesse your thoughts on above?

**Comment by swankjesse** [comment]
Sure. Build an SSLSocketFactory that uses FIPS-approved code internally. You can plug that into your OkHttpClient already.
