### ISSUE TITLE
findTrustAnchorByIssuerAndSignature removed in Android N

### ISSUE THREAD

**Issue by ivmai** [square/okhttp#2644]
https://github.com/square/okhttp/blob/master/okhttp/src/main/java/okhttp3/internal/tls/TrustRootIndex.java uses findTrustAnchorByIssuerAndSignature method of Android conscrypt. The method is private and has been deleted recently (https://android-review.googlesource.com/#/c/207611/1/src/platform/java/org/conscrypt/TrustManagerImpl.java, actually replaced with findAllTrustAnchorsByIssuerAndSignature) causing TrustRootIndex.get() to fall-back to the basic implementation, the letter is slower.
(I will provide exact timing of the both implementations.)

**Comment by swankjesse** [comment]
If we’re on the latest & greatest version of Android, I would expect OkHttp to use `X509TrustManagerExtensions` instead, which is a public API and not subject to change between releases.

**Comment by swankjesse** [comment]
Thanks for the heads up on this but I don’t think there’s any action for us to take here.
