### ISSUE TITLE
connect to spdy website failed with expection: stream reset

### ISSUE THREAD

**Issue by pan2636119599** [square/okhttp#2649]
Hi !

I try OKhttp3 client to connect my website with SPDY,but failed,it reports expection that:
okhttp3.internal.framed.StreamResetException: stream was reset: CANCEL

Server: 

nginx 1.6.3  openssl 1.0.2g(alpn supported)
nginx config:
listen 8001 ssl spdy;

client : okhttp-3.3.1.jar
I do not want to use http2 now,so i disable http2 with the code:

OkHttpClient client = new OkHttpClient().newBuilder().protocols(Arrays.asList(Protocol.HTTP_1_1,Protocol.SPDY_3)).build();

**Comment by swankjesse** [comment]
I assume this bug is similar in cause to:
https://github.com/square/okhttp/issues/2506

We might be able to fix it by implementing similar recovery code here.

**Comment by pan2636119599** [comment]
@swankjesse 

Thanks so much !
I did not use http2,my nginx server only support http1.1 and spdy ,and my client has configure Protocol.SPDY_3  too

Is it similar with the cause of 2506?

**Comment by swankjesse** [comment]
Yep, that’s my assumption.

**Comment by dave-r12** [comment]
I set up a host with nginx 1.6.3 with openssl 1.0.2g and haven't been able to reproduce. GET's and POST's appear to be working flawlessly. 

@pan2636119599 can you provide any other information? I've found nginx has good logging. I use this in the conf (you'll need to build --with-debug):

```
error_log  logs/error.log debug;
```

If you can grab a log, that'd be really helpful.

**Comment by pan2636119599** [comment]
I have build nginx --with-debug and conf the nginx.conf.  
[ssl-error.log.txt](https://github.com/square/okhttp/files/334013/ssl-error.log.txt)



ps:

access http url like this   "https://XXXX@XXXX.com/TunnelGateway/auth"

and the nginx.conf

 location /TunnelGateway/auth {
            default_type 'text/plain';
            lua_need_request_body on;
            lua_transform_underscores_in_response_headers off;
            access_by_lua_file login.lua;
        }

login.lua make upstream to 127.0.0.1 8091

**Comment by dave-r12** [comment]
Thanks - it looks like you're doing some sort of scripting. Is there anything going on in the login.lua file? Can you post that? I wonder if that lua module is interfering with the spdy module. The lua module README states, "SPDY Mode Not Fully Supported".

**Comment by swankjesse** [comment]
Now that we’ve dropped SPDY this won’t recur in future versions of OkHttp. No other action I can imagine us taking on this.
