### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by Jalsoncc** [square/okhttp#2662]
java.lang.ArrayIndexOutOfBoundsException
length=13; index=-1
java.util.ArrayList$ArrayListIterator.next(ArrayList.java:579)
java.util.AbstractCollection.removeAll(AbstractCollection.java:277)
com.zhy.http.okhttp.cookie.store.MemoryCookieStore.void add(okhttp3.HttpUrl,java.util.List)(Unknown Source)
                                                   java.util.List get(okhttp3.HttpUrl)
com.zhy.http.okhttp.cookie.CookieJarImpl.void saveFromResponse(okhttp3.HttpUrl,java.util.List)(Unknown Source)
                                         java.util.List loadForRequest(okhttp3.HttpUrl)
okhttp3.internal.http.HttpEngine.void sendRequest()(Unknown Source)
                                 boolean permitsRequestBody(okhttp3.Request)
                                 okhttp3.internal.http.HttpEngine recover(java.io.IOException,okio.Sink)
                                 boolean hasBody(okhttp3.Response)
                                 java.lang.String cookieHeader(java.util.List)
                                 okhttp3.Response cacheWritingResponse(okhttp3.internal.http.CacheRequest,okhttp3.Response)
                                 boolean validate(okhttp3.Response,okhttp3.Response)
                                 okhttp3.Headers combine(okhttp3.Headers,okhttp3.Headers)
                                 void receiveHeaders(okhttp3.Headers)
                                 boolean sameConnection(okhttp3.HttpUrl)
                                 okhttp3.Address createAddress(okhttp3.OkHttpClient,okhttp3.Request)
                                 okhttp3.internal.http.HttpStream access$000(okhttp3.internal.http.HttpEngine)
                                 okhttp3.Request access$102(okhttp3.internal.http.HttpEngine,okhttp3.Request)
okhttp3.internal.http.HttpEngine.void readResponse()(Unknown Source)
okhttp3.RealCall.void enqueue(okhttp3.Callback)(Unknown Source)
                 void enqueue(okhttp3.Callback,boolean)
                 java.lang.String toLoggableString()
                 okhttp3.Response getResponseWithInterceptorChain(boolean)
                 okhttp3.Response getResponse(okhttp3.Request,boolean)
                 okhttp3.Response access$100(okhttp3.RealCall,boolean)
                 java.lang.String access$200(okhttp3.RealCall)
okhttp3.RealCall$ApplicationInterceptorChain.okhttp3.Response proceed(okhttp3.Request)(Unknown Source)
okhttp3.RealCall.void enqueue(okhttp3.Callback)(Unknown Source)
                 void enqueue(okhttp3.Callback,boolean)
                 java.lang.String toLoggableString()
                 okhttp3.Response getResponseWithInterceptorChain(boolean)
                 okhttp3.Response getResponse(okhttp3.Request,boolean)
                 okhttp3.Response access$100(okhttp3.RealCall,boolean)
                 java.lang.String access$200(okhttp3.RealCall)
okhttp3.RealCall.void enqueue(okhttp3.Callback)(Unknown Source)
                 void enqueue(okhttp3.Callback,boolean)
                 java.lang.String toLoggableString()
                 okhttp3.Response getResponseWithInterceptorChain(boolean)
                 okhttp3.Response getResponse(okhttp3.Request,boolean)
                 okhttp3.Response access$100(okhttp3.RealCall,boolean)
                 java.lang.String access$200(okhttp3.RealCall)
okhttp3.RealCall$AsyncCall.void execute()(Unknown Source)
okhttp3.internal.NamedRunnable.void run()(Unknown Source)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
java.lang.Thread.run(Thread.java:818)

**Comment by swankjesse** [comment]
This is a bug in something called com.zhy.http.okhttp.cookie.store.MemoryCookieStore.
