### ISSUE TITLE
Readme doesn't mention if this has been merged into okhttp proper or if it's a separate thing

### ISSUE THREAD

**Issue by jgamedev** [square/okhttp#2670]
For beginners it's unclear what they should use for websockets, as this is a separate repo and marked as experimental. 

Discussions on websockets in oktttp issues page are rather lenghty, so it would be helpful to people lending on the this repo directly if the README could clarify how this repo relates to okhttp discussions in the main repo.

**Comment by jgamedev** [comment]
Ok, I know see that (https://github.com/square/okhttp/tree/master/okhttp-ws)  is maybe not a separate repo but a separate README inside of the main http repo?

This is a bit confusing to me :)

**Comment by swankjesse** [comment]
At the moment OkHttp’s websockets are experimental. What else would you like to know?
