### ISSUE TITLE
why After enabled Proguard my variable changing ?

### ISSUE THREAD

**Issue by derohimat** [square/okhttp#2671]
{"a":"password","b":"rohimatdeni@gmail.com","c":"12341234","d":"187239871","e":"127387918273"}

**Comment by artem-zinnatullin** [comment]
Because proguard by default changes fields names and so on, it's called obfuscation.

Please read proguard documentation before enabling it: 

* https://developer.android.com/studio/build/shrink-code.html
* http://proguard.sourceforge.net

**Comment by derohimat** [comment]
oke thanks @artem-zinnatullin
