### ISSUE TITLE
Call setEndpointIdentificationAlgorithm() once Android API 24 is our minimum

### ISSUE THREAD

**Issue by swankjesse** [square/okhttp#2672]
https://android-review.googlesource.com/#/c/243503/1/android/main/java/com/squareup/okhttp/internal/Platform.java

**Comment by swankjesse** [comment]
I took a look into this. Setting `setEndpointIdentificationAlgorithm("HTTPS")` ends up causing Android’s NativeCrypto to do hostname verification during the TLS handshake. That isn’t supported until API level 24, and I think calling it reflectively could lead to verification to be skipped in some cases.

If/when our minimum requires API level 24 we should call `setEndpointIdentificationAlgorithm("HTTPS")` and delete our own `HostnameVerifier`. Until then it’s simpler and safer to just always do hostname verification in OkHttp.

**Comment by yschimke** [comment]
@swankjesse do you still want this?

**Comment by swankjesse** [comment]
I don't think the tiny benefit is worth the tiny cost.
