### ISSUE TITLE
Recover gracefully instead of throwing IllegalCharsetNameException

### ISSUE THREAD

**Issue by Biswangluo** [square/okhttp#2677]
Wrong data from server 

# 1.
`<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"><head>
<meta content="text/html; charset=utf-8" http-equiv="Content-Type">
<title>系统发生错误</title>
<style type="text/css">`

#2
557 4920-5047/arkui.live W/System.err: java.nio.charset.IllegalCharsetNameException: 'utf-8'
06-29 12:47:49.557 4920-5047/arkui.live W/System.err:     at java.nio.charset.Charset.checkCharsetName(Charset.java:197)
06-29 12:47:49.557 4920-5047/arkui.live W/System.err:     at java.nio.charset.Charset.forName(Charset.java:295)
06-29 12:47:49.557 4920-5047/arkui.live W/System.err:     at okhttp3.MediaType.charset(MediaType.java:103)
06-29 12:47:49.557 4920-5047/arkui.live W/System.err:     at okhttp3.ResponseBody.charset(ResponseBody.java:159)
06-29 12:47:49.557 4920-5047/arkui.live W/System.err:     at okhttp3.ResponseBody.string(ResponseBody.java:154)
06-29 12:47:49.557 4920-5047/arkui.live W/System.err:     at arkui.live.dao.LoadDataUtil$1.onResponse(LoadDataUtil.java:82)
06-29 12:47:49.557 4920-5047/arkui.live W/System.err:     at okhttp3.RealCall$AsyncCall.execute(RealCall.java:133)
06-29 12:47:49.557 4920-5047/arkui.live W/System.err:     at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
06-29 12:47:49.557 4920-5047/arkui.live W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
06-29 12:47:49.557 4920-5047/arkui.live W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
06-29 12:47:49.557 4920-5047/arkui.live W/System.err:     at java.lang.Thread.run(Thread.java:818)

**Comment by swankjesse** [comment]
It looks like your server is returning a header like this:
```
Content-Type: text/html; charset='utf-8'
```
Unfortunately according to RFC 822, use of single quotes isn’t valid in a media type parameter. Instead the content type should be this:
```
Content-Type: text/html; charset="utf-8"
```
Please ask your server team to fix their broken response headers.
https://tools.ietf.org/html/rfc822

I’m unsure what action OkHttp should take here. Probably our best bet is to see how web browsers like Chrome and Firefox handle invalid charsets and do likewise.

**Comment by Biswangluo** [comment]
thank you

**Comment by swankjesse** [comment]
Chrome treats single quotes interchangeably with double quotes. Firefox ignores the charset and detects it from the content.
