### ISSUE TITLE
DiskLruCache2

### ISSUE THREAD

**Issue by swankjesse** [square/okhttp#2682]
### Goals
- Read while writing.
- Avoid I/O in synchronized blocks.
- Only one file per entry.
### API sketch

```
class DiskLruCache2 {
  Entry get(String key);
  Entry put(String key, ByteString metadata, Source upstream);
  // ... plus methods for sizing, trimming, iterating, etc.

  static class Entry {
    ByteString metadata();
    Source newSource();
  }
}
```
### Implementation sketch

Each entry that is being written has these sources and sinks:
- The upstream source passed into `put()`. This has a logical cursor starting at 0, representing the next byte to read.
- The file sink. Data read from upstream is written to the file sink. Its cursor starts at 0 and is incremented when a flush completes successfully. Its cursor represents that last byte that is safe to read from the file.
- The sources created by calls to `newSource()`. On each attempt to read it will read from the file (if its cursor is lower than the file cursor) or from the network otherwise. If it reads from the network it is responsible for writing to the file.

Readers cooperate with synchronization, with only one reading from upstream at a time. We should also add a buffer to contain up to _N_ bytes preceding the upstream source’s cursor. Readers may prefer to read from this buffer instead of from the file for better performance. Also this makes it possible to reduce flushes to the file system.
### Notes
- What happens when a FileInputStream reads the last byte of a file? Does it eagerly EOF? Or does it continue to read bytes if further bytes are later written to the file?
- The current DiskLruCache has `CLEAN` and `DIRTY` entries in its journal. We should do likewise. An entry can be made clean after the upstream source on a put reaches EOF. This requires a last flush to the file.
- We want to be able to `put()` a new entry when an existing entry is already in place. This is necessary when a conditional GET misses.
- We may also want to be able to `put()` new metadata _without_ updating the rest of the cache. This might motivate putting the metadata ByteString at the end of the file.

**Comment by digitalbuddha** [comment]
Since 2 only comes once, I wanted to chime in with  high level  requests that would help a data loading library we are currently working on. 

I'd like to be able to construct a `DataStore<Request,Response>`  The store would have the following interface:
```
Response get(request)//return from memory if present else disk if present else network
Response fresh(request)//return from network
notify()//listen for all responses (not just 1 key)
```

I'm not sure if it makes sense to encapsulate the memory cache inside of OKHTTP since you would want to cache the inflated models for speed of retrieval. This can't be done without passing a parser into the client

Also, ideally the disk cache policy would be configurable the way a Guava Cache is rather than forcing cache control on server (or spoofed in an interceptor):
```
diskLRUCache = CacheBuilder.newBuilder()
                .maximumSize(getCacheSize())
                .expireAfterAccess(getCacheTTL(), TimeUnit.MILLISECONDS)
                .build();
```

Comparing old to new data is something that would be helpful as well.  Say I have a data call that returns ID + timestamps of correction for all articles from today.  I want to be able to fetch that data from network and compare it to the last entry in the cache.  This could be solved by either allowing custom keys or having a way to recreate a cache key from request params.

Finally cache hits when dealing with timestamps is difficult. I had a project where every request sent needed to include current time. Maybe it would make sense to have a a way to mark request params as ignored when it comes to generating a cache key.

Thanks for tracking more flexible cache.

**Comment by swankjesse** [comment]
Here’s a tentative plan on the structure of the new cache’s index. This plan focuses on what happens on the file system; there’s also a model of the index in memory.

As always, I’m open to suggestions & ideas!

#### Cache Sequence ID

The cache is built around a `long` counter that’s incremented on every insert and on every access. This is what’ll power LRU. It’ll be called the sequence ID. It starts at 1.

#### Index

The index is a single file like `index.ok`. Unlike OkHttp’s current cache journal this file is edited in-place. There’s no rebuilding.

The index is:
64 byte header
N × 32 byte entry slots

The header is:
16 byte prefix like `OkHttp index v1\n`.
8 byte created at timestamp
8 byte entry slot count; should equal (file length - header length) / entry length
8 byte next ID to assign (initially 1)
8 byte request count
8 byte hit count
8 byte unused (for 64 byte alignment)

Each entry is:
16 byte SHA-256 hash of URL (truncated from 256 bits to 128 bits)
8 byte length (content + metadata), or the placeholder `0xffffffffffffffff` if unknown
8 byte sequence ID

#### Creates 

To insert an entry named by its hash:

 * Take a sequence number
 * Find an empty entry slot, creating one at the end if necessary
 * Write the entry the slot
 * Flush the index to disk
 * Create a file named by the hash in hex `11112222333344445555666677778888.ok`
 * Later, once the entry is committed, update the entry’s length

#### Reads

To get an entry named by its hash, we:

 * Increment the request count
 * Look for a matching hash. If found and the file is readable:
   * Increment the hit count.
   * Assign the entry’s sequence number to a new sequence number

#### Updates

To update an entry already in the cache:

 * Assign the entry’s sequence number to a new sequence number
 * Assign the entry’s length to the placeholder length
 * Later, once the entry is committed, update the entry’s length

#### Deletes

To remove an entry from the cache:

 * Remove its file from the file system if it exists
 * Zero out its entry

#### Trims

While the cache size is too large, repeatedly remove the entry with the lowest sequence ID.


#### Loading the Cache

The most difficult part of index loading is that the index may be incomplete. We don’t force a flush after every change, and so it’s possible that several changes are missing from the index. This is expected.

As a rule of thumb, the index’s set of files is allowed to be a superset of the file system’s files. We never want a file on the file system that isn’t known by the index. But it’s okay if the index knows about a file that hasn’t been created yet, or a file that has already been deleted.

If the index header is malformed (no prefix or fails to satisfy other invariants) we are on a hostile filesystem. Refuse to cache anything.

Otherwise iterate the entries. Any entry with an placeholder length is a partial entry. Remove that entry.

**Comment by ScottPierce** [comment]
@swankjesse Is there any intention to make an OkHttp Cache that is only in-memory or make the persisted data encrypted so as to better handle using the cache with secure data?

**Comment by swankjesse** [comment]
@ScottPierce it's a feature I’d like to do eventually. Maybe​ just a mechanism to let you transform the stream.

**Comment by ultraon** [comment]
Hello guys, any updates on the issue?

**Comment by roman-tikonov** [comment]
Hi @swankjesse, are there any plans to provide an in-memory OkHttp Cache? That would be really useful for apps that don't want to (or are not allowed to) store any sensitive data on a filesystem.

**Comment by yschimke** [comment]
As of 5.0 (currently Alpha) you can provide your own FileSystem (for example https://github.com/square/okio/blob/master/okio-fakefilesystem/src/commonMain/kotlin/okio/fakefilesystem/FakeFileSystem.kt) and pass it to the public Cache constructor.

https://github.com/square/okhttp/pull/6550/files

**Comment by swankjesse** [comment]
Yep. Our FakeFileSystem is a good in-memory file system for that.

But you may also consider doing an in-memory cache of the parsed response body (a model object) rather than it's encoded bytes. For example Picasso and Coil cache bitmap objects in memory, not their byte arrays. The drawback of this is it’s more work if your models aren't supported by a library like these.

**Comment by ScottPierce** [comment]
What a fantastic benefit of the FakeFileSystem. Thanks for the suggestion!

**Comment by yschimke** [comment]
Closing as low priority. I think tolerance to interrupts might be the main improvement we currently need.

Given Coil has reimplemented a Cache instead of OkHttp, it's likely we should look at a common pattern if we do.

@swankjesse re-open if this is still in scope.
