### ISSUE TITLE
java.lang.IllegalStateException: closed

### ISSUE THREAD

**Issue by guoliuya** [square/okhttp#2683]
java.lang.IllegalStateException: closed
    at okio.RealBufferedSink.writeUtf8(RealBufferedSink.java:56)
    at okhttp3.internal.DiskLruCache.get(DiskLruCache.java:435)
    at okhttp3.Cache.get(Cache.java:193)
    at okhttp3.Cache$1.get(Cache.java:143)
    at okhttp3.internal.http.HttpEngine.sendRequest(HttpEngine.java:198)
    at okhttp3.RealCall.getResponse(RealCall.java:240)
    at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:198)
    at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:160)
    at okhttp3.RealCall.access$100(RealCall.java:30)
    at okhttp3.RealCall.access$200(RealCall.java:30)
    at okhttp3.RealCall$AsyncCall.execute(RealCall.java:127)
    at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
    at java.lang.Thread.run(Thread.java:841)

**Comment by swankjesse** [comment]
Could you please provr

**Comment by swankjesse** [comment]
Could you please provide an executable test case? It looks like you're closing the cache while you're using it.

**Comment by guoliuya** [comment]
this is my util for okhttp to call on network 
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.util.Map;
import java.util.concurrent.TimeUnit;

import android.content.Context;
import android.graphics.Bitmap;
import android.os.Handler;
import android.os.Looper;
import android.text.TextUtils;

import okhttp3.Cache;
import okhttp3.Call;
import okhttp3.Callback;
import okhttp3.FormBody;
import okhttp3.Headers;
import okhttp3.Interceptor;
import okhttp3.MediaType;
import okhttp3.MultipartBody;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.RequestBody;
import okhttp3.Response;
import org.json.JSONObject;

import com.android.volley.DefaultRetryPolicy;

import com.yizhibo.video.app.YZBApplication;
import com.yizhibo.video.db.Preferences;
import com.yizhibo.video.utils.Constants;
import com.yizhibo.video.utils.FileUtil;
import com.yizhibo.video.utils.Logger;
import com.yizhibo.video.utils.SingleToast;
import com.yizhibo.video.utils.StatisticsUtil;

public class OkHttpRequest implements IRequestHelper {
    private static final String TAG = "OkHttpRequest";
    private static final int MY_SOCKET_TIMEOUT_MS = 4000;
    private static final int MY_SOCKET_RETRIES = DefaultRetryPolicy.DEFAULT_MAX_RETRIES;

    private static final MediaType MEDIA_TYPE_JPG = MediaType.parse("image/jpeg");
    private static final String CACHE_FILE = FileUtil.CACHE_DOWNLOAD_DIR + File.separator + "cache.tmp";

    private Handler mHandler;
    private OkHttpClient mClient;

    public OkHttpRequest(Context context) {
        mHandler = new Handler(context.getMainLooper());

        int cacheSize = 10 * 1024 * 1024; // 10 MiB
        Cache cache = new Cache(new File(CACHE_FILE), cacheSize);
        Interceptor mNetworkInterceptor = new Interceptor() {
            @Override
            public Response intercept(Chain chain) throws IOException {
                Request requestOrigin = chain.request();
                Headers headersOrigin = requestOrigin.headers();
                Headers headers = headersOrigin.newBuilder()
                        .set("User-Agent", RequestUtil.getAppUA())
                        .set("Charset", "utf-8").build();
                Request request = requestOrigin.newBuilder().headers(headers).build();
                return chain.proceed(request);
            }
        };
        mClient = new OkHttpClient().newBuilder()
                .connectTimeout(MY_SOCKET_TIMEOUT_MS, TimeUnit.MILLISECONDS)
                .readTimeout(MY_SOCKET_TIMEOUT_MS, TimeUnit.MILLISECONDS)
                .writeTimeout(MY_SOCKET_TIMEOUT_MS, TimeUnit.MILLISECONDS)
                .retryOnConnectionFailure(true)
                .addNetworkInterceptor(mNetworkInterceptor)
                .cache(cache)
                .build();
    }

    @Override
    public void getAsString(String url, final MyRequestCallBack<String> callBack) {
        getAsGson(url, String.class, callBack);
    }

    @Override
    public void getAsGson(String url, final Class clazz, final MyRequestCallBack<?> callBack) {
        requestAsGson(url, null, clazz, callBack, false);
    }

    @Override
    public void postAsString(String url, Map<String, String> params,
            final MyRequestCallBack<String> callBack) {
        postAsGson(url, params, String.class, callBack);
    }

    @Override
    public void postAsGson(String url, Map<String, String> params, final Class clazz,
            final MyRequestCallBack<?> callBack) {
        requestAsGson(url, params, clazz, callBack, true);
    }

    private void requestAsGson(String url, Map<String, String> params, final Class clazz,
            final MyRequestCallBack<?> callBack, boolean isPostMethod) {
        Request.Builder requestBuilder = new Request.Builder().url(url);
        if (isPostMethod) {
            FormBody.Builder builder = new FormBody.Builder();
            if (params != null) {
                for (Map.Entry<String, String> entry : params.entrySet()) {
                    builder.add(entry.getKey(), entry.getValue());
                }
            }
            requestBuilder.post(builder.build());
        } else {
            requestBuilder.get();
        }
        mClient.newCall(requestBuilder.build()).enqueue(new Callback() {
            @Override
            public void onFailure(Call call, IOException e) {
                handlerNetworkError(call, e, callBack);
            }

            @Override
            public void onResponse(Call call, Response response) throws IOException {
                handleResponse(response, callBack, clazz);
            }
        });
    }

    @Override
    public void postAsString(String url, Map<String, String> params, JSONObject jsonObject,
            final MyRequestCallBack<String> callBack) {
        RequestBody body = RequestBody
                .create(MediaType.parse("application/json; charset=utf-8"), jsonObject.toString());
        Request request = new Request.Builder()
                .url(RequestUtil.assembleUrlWithParams(url, params))
                .post(body)
                .build();
        mClient.newCall(request).enqueue(new Callback() {
            @Override
            public void onFailure(Call call, IOException e) {
                handlerNetworkError(call, e, callBack);
            }

            @Override
            public void onResponse(Call call, Response response) throws IOException {
                handleResponse(response, callBack, String.class);
            }
        });
    }

    @Override
    public void postAsGzip(String url, Map<String, String> params, JSONObject jsonObject,
            MyRequestCallBack<String> callBack) {

    }

    @Override
    public void uploadFile(String url, Map<String, String> params, Bitmap bitmap, String fileName,
            final MyRequestCallBack<String> callBack) {
        ByteArrayOutputStream baos = new ByteArrayOutputStream();
        if (bitmap != null) {
            bitmap.compress(Bitmap.CompressFormat.JPEG, 80, baos);
        }
        RequestBody requestBody = new MultipartBody.Builder()
                .setType(MultipartBody.FORM)
                .addFormDataPart("file", fileName, RequestBody.create(MEDIA_TYPE_JPG, baos.toByteArray()))
                .build();
        Request request = new Request.Builder()
                .url(RequestUtil.assembleUrlWithParams(url, params))
                .post(requestBody)
                .build();
        mClient.newCall(request).enqueue(new Callback() {
            @Override
            public void onFailure(Call call, IOException e) {
                handlerNetworkError(call, e, callBack);
            }

            @Override
            public void onResponse(Call call, Response response) throws IOException {
                handleResponse(response, callBack, String.class);
            }
        });
    }

    private void handleResponse(final Response response, final MyRequestCallBack<?> callBack, Class clazz)
            throws IOException {
        if (response.isSuccessful()) {
            handleResponse(response.body().string(), callBack, clazz);
        } else {
            mHandler.post(new Runnable() {
                @Override
                public void run() {
                    callBack.onError(response.message());
                }
            });
        }
    }

    @Override
    public void handleResponse(final String response, final MyRequestCallBack<?> callBack,
            final Class clazz) {
        Logger.d(TAG, "Request success: " + response);
        final JSONObject jsonObject = JsonParserUtil.getJsonObject(response);
        boolean isInMainThread = Looper.getMainLooper().getThread() == Thread.currentThread();
        mHandler.post(new Runnable() {
            @Override
            public void run() {
                if (JsonParserUtil.isResponseOk(jsonObject)) {
                    if (callBack != null) {
                        final String info = JsonParserUtil.getResultInfo(jsonObject);
                        callBack.parseGson(info, clazz);
                    }
                } else {
                    parseErrorInfo(jsonObject, callBack);
                }
            }
        });
    }

    private void parseErrorInfo(JSONObject jsonObject, MyRequestCallBack callBack) {
        StatisticsUtil.statisticApiEvent(Constants.UMENG_EVENT_SERVER_ERROR);
        String errorInfo = JsonParserUtil.getResultValue(jsonObject);
        StatisticsUtil.statisticError("VolleyRequest", Constants.UMENG_EVENT_SERVER_ERROR + ":" + errorInfo);
        String errorTips = JsonParserUtil.getErrorInfo(jsonObject);
        if (callBack != null) {
            callBack.onError(errorInfo);
        }
        if (errorInfo.isEmpty()) {
            return;
        }
        if (ApiConstant.E_SESSION.equals(errorInfo)) {
            boolean isLastUserLogout = Preferences.getInstance(YZBApplication.getApp())
                    .getBoolean(Preferences.KEY_IS_LOGOUT, false);
            if (!isLastUserLogout) {
                YZBApplication.reLogin();
            }
        } else if (!TextUtils.isEmpty(errorTips)) {
            SingleToast.show(YZBApplication.getApp(), errorTips);
        }
    }

    private void handlerNetworkError(Call call, final Exception exception,
            final MyRequestCallBack<?> callBack) {
        if ("Canceled".equalsIgnoreCase(exception.getMessage())) {
            return;
        }
        mHandler.post(new Runnable() {
            @Override
            public void run() {
                if (callBack != null) {
                    callBack.onFailure(exception.getMessage());
                }
            }
        });
    }

    @Override
    public void cancelRequest(String tag) {
        boolean isCancelAll = TextUtils.isEmpty(tag);
        for (Call call : mClient.dispatcher().queuedCalls()) {
            if (isCancelAll) {
                call.cancel();
            } else if (call.request().tag().equals(tag)) {
                call.cancel();
            }
        }
        for (Call call : mClient.dispatcher().runningCalls()) {
            if (isCancelAll) {
                call.cancel();
            } else if (call.request().tag().equals(tag)) {
                call.cancel();
            }
        }
    }
}

**Comment by rfc2822** [comment]
Got the same exception. If the stack trace is useful for you:

```
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.support.v4.content.ModernAsyncTask$3.done(ModernAsyncTask.java:153)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.IllegalStateException: closed
	at okhttp3.internal.http.Http1xStream$FixedLengthSource.read(Http1xStream.java:374)
	at okio.Buffer.writeAll(Buffer.java:993)
	at okio.RealBufferedSource.readByteArray(RealBufferedSource.java:106)
	at okhttp3.ResponseBody.bytes(ResponseBody.java:128)
	at at.bitfire.dav4android.exception.HttpException.<init>(HttpException.java:87)
	at at.bitfire.dav4android.DavResource.checkStatus(DavResource.java:317)
	at at.bitfire.dav4android.DavResource.checkStatus(DavResource.java:290)
	at at.bitfire.dav4android.DavResource.propfind(DavResource.java:275)
	at at.bitfire.davdroid.ui.setup.DavResourceFinder.getCurrentUserPrincipal(DavResourceFinder.java:352)
	at at.bitfire.davdroid.ui.setup.DavResourceFinder.discoverPrincipalUrl(DavResourceFinder.java:334)
	at at.bitfire.davdroid.ui.setup.DavResourceFinder.findInitialConfiguration(DavResourceFinder.java:140)
	at at.bitfire.davdroid.ui.setup.DavResourceFinder.findInitialConfiguration(DavResourceFinder.java:90)
	at at.bitfire.davdroid.ui.setup.DetectConfigurationFragment$ServerConfigurationLoader.loadInBackground(DetectConfigurationFragment.java:142)
	at at.bitfire.davdroid.ui.setup.DetectConfigurationFragment$ServerConfigurationLoader.loadInBackground(DetectConfigurationFragment.java:125)
	at android.support.v4.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:296)
	at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:54)
	at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:42)
	at android.support.v4.content.ModernAsyncTask$2.call(ModernAsyncTask.java:133)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	... 3 more
```

Would it be possible to throw IOExceptions instead of IllegalStateExceptions, which are not easy to handle?

**Comment by JakeWharton** [comment]
ISE is thrown when you have caused the problem, not the network.

**Comment by swankjesse** [comment]
No action to take on this.
