### ISSUE TITLE
Property to proxy non hosts

### ISSUE THREAD

**Issue by ofbizbrazil** [square/okhttp#2693]
Missing a method to inform which hosts should not be sent via proxy.  Actually we could set any route such as Httpclient does or have a property to say proxy non hosts.

**Comment by yschimke** [comment]
Doesn't proxySelector allow this?

**Comment by swankjesse** [comment]
Yep. Please see this StackOverflow question.
https://stackoverflow.com/questions/38154628/non-proxy-hosts-for-okhttp3/38194632#38194632

**Comment by ofbizbrazil** [comment]
But how to do it? Is there any sample?
