### ISSUE TITLE
SSL handshake aborted after upgrading to okhttp 2.3.0

### ISSUE THREAD

**Issue by emilburzo** [square/okhttp#2694]
* Device: Alcatel OT 918
* Android: 2.3.6 / API 10
* Last working okhttp version: 2.2.0
* Failing okhttp version: 2.3.0 and up
* Server SSL config: https://ssllabs.com/ssltest/analyze.html?d=graticule.link&latest
* Possibly related: #1543

I went ahead and [compared](https://www.diffchecker.com/zemy6nwq) the `upgradeToTls` method in 2.2.0 and 2.3.0, but that doesn't seem to be it.

What else could have changed?

I can understand if the device is really old and it doesn't have supported SSL libraries anymore.

But if that's the case, why does 2.2.0 work?

I have the device available, so I can test it on the spot if you find anything.

```
SSL handshake aborted: ssl=0xffe30: Failure in SSL library, usually a protocol error

org.apache.harmony.xnet.provider.jsse.NativeCrypto.SSL_do_handshake(Native Method)
org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:505)
org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:359)
com.squareup.okhttp.Connection.upgradeToTls(Connection.java:242)
com.squareup.okhttp.Connection.connect(Connection.java:159)
com.squareup.okhttp.Connection.connectAndSetOwner(Connection.java:175)
com.squareup.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:120)
com.squareup.okhttp.internal.http.HttpEngine.nextConnection(HttpEngine.java:330)
com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:319)
com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:241)
com.squareup.okhttp.Call.getResponse(Call.java:271)
com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:228)
com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:199)
com.squareup.okhttp.Call.execute(Call.java:79)
```

```
D/NativeCrypto: ssl=0x1a5a50 NativeCrypto_SSL_do_handshake fd=0x40631340 shc=0x4075d6d0 timeout=10000 client_mode=1
D/NativeCrypto: doing handshake ++
D/NativeCrypto: doing handshake -- ret=-1
D/NativeCrypto: ssl=0x1a5a50 NativeCrypto_SSL_do_handshake ret=-1 errno=11 sslError=2 timeout=10000
D/NativeCrypto: sslSelect type=READ fd=49 appData=0x1834c8 timeout=10000
D/NativeCrypto: sslSelect READ fd=49 appData=0x1834c8 timeout=10000 => 1
D/NativeCrypto: doing handshake ++
D/NativeCrypto: doing handshake -- ret=-1
D/NativeCrypto: ssl=0x1a5a50 NativeCrypto_SSL_do_handshake ret=-1 errno=0 sslError=1 timeout=10000
```

What kind of issue is this?

 - [ ] Question. This issue tracker is not the place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use Stack
       Overflow. https://stackoverflow.com/questions/tagged/okhttp

 - [x] Bug report. If you’ve found a bug, spend the time to write a failing test. Bugs with tests
       get fixed. Here’s an example: https://gist.github.com/swankjesse/981fcae102f513eb13ed

 - [ ] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
       already exists! Don’t send pull requests to implement new features without first getting our
       support. Sometimes we leave features out on purpose to keep the project small.

**Comment by swankjesse** [comment]
The changelog says we dropped support for RC4 cipher suites in 2.3. That might be what your server and client negotiated. You can workaround by manually building a ConnectionSpec with the obsolete cipher suites of your choosing.

**Comment by emilburzo** [comment]
Thanks, but my server doesn't have RC4 or other obsolete ciphers enabled.

What else could it be?

**Comment by swankjesse** [comment]
Not sure. If you find something that we can fix, please let me know!
https://github.com/square/okhttp/blob/master/CHANGELOG.md#version-230
