### ISSUE TITLE
Dependency issue when using OkHttp 2.x and 3.x based releases in the same application

### ISSUE THREAD

**Issue by troinine** [square/okhttp#2705]
As far as I have understood based on http://jakewharton.com/java-interoperability-policy-for-major-version-updates/ the goal of OkHttp 3.x release was to provide a less painful way to migrate to major version upgrade of the library.

However, by accident we noticed an issue when using OkHttp 2.3.0 and 3.2.0 in the same application. OkHttp pulls in okio as a dependency and it does not follow the same principle as OkHttp 3.x (and for example Retrofit) in which it uses the Maven groupId for versioning major API changes.

Here's a simple app to reproduce the issue:

pom.xml:

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.test</groupId>
    <artifactId>test-app</artifactId>
    <version>1.0.0-SNAPSHOT</version>

    <properties>
        <okhttp3.version>3.2.0</okhttp3.version>
        <okhttp.version>2.3.0</okhttp.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>com.squareup.okhttp</groupId>
            <artifactId>okhttp</artifactId>
            <version>${okhttp.version}</version>
        </dependency>
        <dependency>
            <groupId>com.squareup.okhttp3</groupId>
            <artifactId>okhttp</artifactId>
            <version>${okhttp3.version}</version>
        </dependency>
        <dependency>
            <groupId>com.squareup.okhttp3</groupId>
            <artifactId>mockwebserver</artifactId>
            <version>${okhttp3.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.12</version>
            <scope>test</scope>
        </dependency>
    </dependencies>
</project>
```

JUnit test

```
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.mockwebserver.MockResponse;
import okhttp3.mockwebserver.MockWebServer;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;

import java.io.IOException;

public class OkHttpDependencyTest {
    private MockWebServer mockWebServer;

    @Before
    public void setup() throws IOException {
        mockWebServer = new MockWebServer();

        mockWebServer.start();
    }

    @After
    public void teardown() throws IOException {
        if (mockWebServer != null) {
            mockWebServer.shutdown();
        }
    }

    @Test
    public void testOkHttp() throws IOException {
        mockWebServer.enqueue(new MockResponse().setBody("Hi!"));

        OkHttpClient okHttpClient = new OkHttpClient.Builder().build();

        Request request = new Request.Builder()
                .get()
                .url(mockWebServer.url("/"))
                .build();

        okHttpClient.newCall(request).execute();
    }
}

```

The test fails with 
```
java.lang.NoClassDefFoundError: okio/ForwardingTimeout

	at okhttp3.internal.http.Http1xStream.newFixedLengthSource(Http1xStream.java:236)
	at okhttp3.internal.http.Http1xStream.getTransferStream(Http1xStream.java:144)
	at okhttp3.internal.http.Http1xStream.openResponseBody(Http1xStream.java:129)
	at okhttp3.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:732)
```

And this happens because OkHttp 2.3.0 pulls in okio version 1.3.0 but okhttp 3.2.0 expects 1.6.0 version of it which seems not to be fully binary backwards compatible.

If your goal is to provide a way to easily to migrate to newer versions of okhttp by being able to rely on both major version branches, that's not possible with this combination of dependencies.

This is not a major issue for us as we migrated to Retrofit 2.0.2 and therefore OkHttp 3.2.0 without eventually not having to depend on both versions but I thought that this might be valuable information for you.

**Comment by swankjesse** [comment]
Please try explicitly configuring your project to use Okio 1.6.0.

**Comment by swankjesse** [comment]
(or even better, 1.9.0!)

**Comment by troinine** [comment]
Of course it works but it shouldn't be the responsibility of the application to resolve transitive dependency versions.

Anyways, looks like you closed the issue already so I guess it is not a big deal.

**Comment by JakeWharton** [comment]
This is a build system configuration problem, not a problem with OkHttp or
Okio. I'm surprised to see Maven behave that way because it should be
resolving the higher version required by OkHttp 3 for use. When I try your
example with Gradle it does pull the higher version of Okio.

**Comment by troinine** [comment]
@JakeWharton, your comment made me double check this. As far as I know, for Maven the order of dependencies matters. And it looks to be the case based on https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html. Therefore the problem in our case realized as okhttp 2.x was declared before the okhttp 3.x dependencies.

Switching the order in the test POM above fixes the issue. Of course here we have to assume that okio 1.6.0 is compatible with okhttp 2.x. I verified the functionality with okhttp 2.x with the following test

```
    @Test
    public void testOkHttp2() throws IOException {
        mockWebServer.enqueue(new MockResponse().setBody("Hi!"));

        com.squareup.okhttp.OkHttpClient okHttpClient =
                new com.squareup.okhttp.OkHttpClient();

        com.squareup.okhttp.Request request = new com.squareup.okhttp.Request.Builder()
                .get()
                .url(mockWebServer.url("/").toString())
                .build();

        okHttpClient.newCall(request).execute();
    }
```

Not sure if the order in Gradle matters similarly than in Maven.

Anyways, this justifies the closing of the issue. Thanks for pointing me to the right direction to find the root cause.

**Comment by JakeWharton** [comment]
Gradle definitely doesn't use declaration order, and I never knew that
about Maven.

Okio does fall under that versioning policy though so if we ever do a
non-compatible release it will be as com.squareup.okio2:okio:2.x.y.
