### ISSUE TITLE
GET with body

### ISSUE THREAD

**Issue by nik9000** [square/okhttp#2706]
- [x] Feature Request. Start by telling us what problem you’re trying to solve.

I'd like to use okhttp to send `GET` requests with a body. So far as I can tell this is permitted by the spec but the server "SHOULD" ignore it. I'd like to you okhttp with a server that does not.

**Comment by swankjesse** [comment]
This breaks too many other assumptions like how caching works. You'll need to fix your server, fork OkHttp, or use another client.

**Comment by nik9000** [comment]
Thanks for responding so quickly. We'll use another client.

**Comment by mmcminn** [comment]
Could someone suggest a client that does allow this? So far all clients seems to assume GET does not allow for a body.

**Comment by pickypg** [comment]
@mmcminn You can configure the Apache Http Async Client to send bodies with `GET` requests. It's not the default behavior, but you can see [a simple example here](https://github.com/elastic/elasticsearch/blob/8c40b2b54eac3e3ab3c41ece5c758be75173191b/client/rest/src/main/java/org/elasticsearch/client/HttpGetWithEntity.java).
