### ISSUE TITLE
Allow to clone a call

### ISSUE THREAD

**Issue by inorichi** [square/okhttp#2709]
I created the following Kotlin extension method on `Call` to use calls with RxJava.

```
fun Call.asObservable(): Observable<Response> {
    return Observable.create { subscriber ->
        subscriber.add(Subscriptions.create { cancel() })

        try {
            val response = execute()
            if (!subscriber.isUnsubscribed) {
                subscriber.onNext(response)
                subscriber.onCompleted()
            }
        } catch (error: IOException) {
            if (!subscriber.isUnsubscribed) {
                subscriber.onError(error)
            }
        }
    }
}
```

It works fine normally, but if a request fails and I use a `.retry()` in the chain, it throws an exception because the call can't be reused. Then I saw Retrofit has a `.clone()` method on its `Call` class for the RxJava's adapter (I guess for a similar scenario).

Though I don't know if it makes sense to include a clone, because the original call would never be executed or canceled.

My current solution is to always create a new call inside the observable, but then I need a reference to the client and the request, and I would like to abstract that.

**Comment by JakeWharton** [comment]
I feel like we've definitely talked about adding it here when it was added to Retrofit, but I'm not sure why it never made it.

**Comment by JakeWharton** [comment]
By the way your custom observable doesn't handle backpressure for the `request(0)` case. It should probably be implemented like this:
```kotlin
fun Call.asObservable(): Observable<Response> {
  return Observable.create { subscriber ->
    subscriber.add(Subscriptions.create { cancel() })
    subscriber.setProducer(object : Producer() {
      private val run = AtomicBoolean()

      override fun request(n: Long) {
        if (!run.compareAndSet(false, true)) return

        // normal try/catch/execute code here
      }
    })
  }
}
```

**Comment by swankjesse** [comment]
I’m in.
