### ISSUE TITLE
[feature request] Is it possible not use strict mode during status line parsing?

### ISSUE THREAD

**Issue by Piasy** [square/okhttp#2719]
Current implementation of `StatusLine.parse` is very strict, any unexpected character would cause a `ProtocolException`. Is it possible to turn off the strict mode and tolerant extra characters? 

The status line from our server has non-ascii characters due to unknown reasons (we have tried many ways to fix it, but we failed), hope there is a flag to use lenient mode.

**Comment by swankjesse** [comment]
If your server is returning non-ASCII from the status line, then it isn’t an HTTP server. We’re unlikely to offer a lenient mode in the project, but it’s open source and you can hack it how you like.

**Comment by Piasy** [comment]
Got it.
