### ISSUE TITLE
When use OkHttp3 in Multithreading program, sometimes "Too many open files" exception occurred

### ISSUE THREAD

**Issue by jiechu** [square/okhttp#2720]
Read the introduction, OkHttp3 has a connection pool built-in. It is better than Spring Rest Template. My application has a ThreadPoolExecutor with 1000 thread size. It works on Linux server. It seems OkHttp3 cannot work well with the ThreadPoolExecutor since sometimes I see "Too many open files" in the log. When I turned back to Spring Rest Template, everything is well.
Is there any thing I missed in the OkHttp3 usage? Or OkHttp3 is preferred to android.
Note: This time OkHttp3 is used in Java program, not Android apk.

**Comment by swankjesse** [comment]
We just posted some advice here. Does that help?
https://square.github.io/okhttp/3.x/okhttp/okhttp3/OkHttpClient.html

**Comment by swankjesse** [comment]
No further action to take on this.

**Comment by erlangp** [comment]
https://github.com/square/okhttp/issues/1943#issuecomment-151024020
