### ISSUE TITLE
cookiejar not post HttpOnly cookie to server ?

### ISSUE THREAD

**Issue by muziling** [square/okhttp#2725]
Implement cookiejar and print log 
```
@Override
public List<Cookie> loadForRequest(HttpUrl url) {
    List<Cookie> cookies = persistentCookieStore.get(url);
    for (Cookie c : cookies)
        Log.d("zzzzzzzzz", c.toString());   //add print log
    return cookies;
    //return persistentCookieStore.get(url);
}
```
open an website

> OkHttp : <-- 200 OK https: //bbs.et8.net/bbs/forumdisplay.php?sort=dateline&order=desc&page=1&f=147 (317ms)
> 
> OkHttp : Server: nginx/1.8.1
> 
> OkHttp : Date: Thu, 14 Jul 2016 13:09:40 GMT
> 
> OkHttp : Content-Type: text/html; charset=UTF-8
> 
> OkHttp : Transfer-Encoding: chunked
> 
> OkHttp : Connection: keep-alive
> 
> OkHttp : Vary: Accept-Encoding
> 
> OkHttp : X-Powered-By: PHP/5.4.41
> 
> OkHttp : Set-Cookie: bbsessionhash=ebaf33d3eed4e3371d6a6b7013d7530e; path=/; domain=.et8.net; HttpOnly
> 
> OkHttp : Set-Cookie: bblastvisit=1468400840; expires=Fri, 14-Jul-2017 13:09:40 GMT; path=/; domain=.et8.net; secure
> 
> OkHttp : Set-Cookie: bblastactivity=0; expires=Fri, 14-Jul-2017 13:09:40 GMT; path=/; domain=.et8.net; secure
> 
> OkHttp : Cache-Control: private
> 
> OkHttp : Pragma: private
> 
> OkHttp : X-UA-Compatible: IE=7
> 
> OkHttp : Strict-Transport-Security: max-age=31536000; includeSubDomains
> 
> OkHttp : X-Frame-Options: SAMEORIGIN
> 
> OkHttp : <-- END HTTP

post data to server:

> OkHttp : --> POST https:// bbs.et8.net/bbs/login.php http/1.1
> 
> OkHttp : Content-Type: application/x-www-form-urlencoded
> 
> OkHttp : Content-Length: 167
> 
> OkHttp : --> END POST
> 
> zzzzzzzzz: bblastactivity=0; expires=Fri, 14 Jul 2017 13:09:40 GMT; domain=et8.net; path=/; secure
> 
> zzzzzzzzz: bblastvisit=1468400840; expires=Fri, 14 Jul 2017 13:09:40 GMT; domain=et8.net; path=/; secure
> 
> zzzzzzzzz: bbsessionhash=ebaf33d3eed4e3371d6a6b7013d7530e; domain=et8.net; path=/; httponly
> 
> OkHttp : <-- 200 OK https://bbs.et8.net/bbs/login.php (76ms)
> 
> OkHttp : Server: nginx/1.8.1
> 
> OkHttp : Date: Thu, 14 Jul 2016 13:09:49 GMT
> 
> OkHttp : Content-Type: text/html; charset=UTF-8
> 
> OkHttp : Transfer-Encoding: chunked
> 
> OkHttp : Connection: keep-alive
> 
> OkHttp : Vary: Accept-Encoding
> 
> OkHttp : X-Powered-By: PHP/5.4.41
> 
> OkHttp : Set-Cookie: bblastvisit=1468400840; expires=Fri, 14-Jul-2017 13:09:49 GMT; path=/; domain=.et8.net; secure
> 
> OkHttp : Set-Cookie: bblastactivity=0; expires=Fri, 14-Jul-2017 13:09:49 GMT; path=/; domain=.et8.net; secure
> 
> OkHttp : Cache-Control: private
> 
> OkHttp : Pragma: private
> 
> OkHttp : X-UA-Compatible: IE=7
> 
> OkHttp : Strict-Transport-Security: max-age=31536000; includeSubDomains
> 
> OkHttp : X-Frame-Options: SAMEORIGIN
> 
> OkHttp : <-- END HTTP

why the post header miss cookie item: set-cookie:bbsessionhash ?

**Comment by muziling** [comment]
HTTPUrlConnection method can auto add bbsessionhash cookie to post headers? How can okhttp auto add too?

**Comment by swankjesse** [comment]
Could you rewrite this as a failing test case?

**Comment by muziling** [comment]
`
import java.util.ArrayList;
import java.util.List;
import okhttp3.Cookie;  
import okhttp3.CookieJar;  
import okhttp3.HttpUrl;

public class CookieManager implements CookieJar {
    private static List<Cookie> mCookies = new ArrayList<>();

    public CookieManager() {
    }

    @Override
    public void saveFromResponse(HttpUrl url, List<Cookie> cookies) {
        System.out.println("saveFromResponse:   "+url.toString());
        for (Cookie c : cookies)
            System.out.println("saveFromResponse:   "+ c.toString());
        mCookies.addAll( cookies);
    }

    @Override
    public List<Cookie> loadForRequest(HttpUrl url) {
        System.out.println("loadForRequest:   "+url.toString());
        for (Cookie c : mCookies)
            System.out.println("loadForRequest:   "+ c.toString());
        return mCookies;
    }
}
`
`
import java.io.IOException;

import okhttp3.*;
import okhttp3.logging.HttpLoggingInterceptor;

public final class GetExample {
    public static final MediaType JSON
            = MediaType.parse("application/json; charset=utf-8");
    OkHttpClient client = new OkHttpClient();

    void init() {
        OkHttpClient.Builder httpClientBuilder = new OkHttpClient.Builder();
        httpClientBuilder.cookieJar(new CookieManager());
        HttpLoggingInterceptor logging = new HttpLoggingInterceptor();
        logging.setLevel(HttpLoggingInterceptor.Level.HEADERS);
        httpClientBuilder.addInterceptor(logging);
        client = httpClientBuilder.build();
    }

    String run(String url) throws IOException {
        Request request = new Request.Builder()
                .url(url)
                .header("User-Agent", "Mozilla/5.0 (Linux; U; Android 2.3.5; zh-cn; HTC_IncredibleS_S710e Build/GRJ90) AppleWebKit/533.1 (KHTML, like Gecko) Version/4.0 Mobile Safari/533.1")
                .build();

        try (Response response = client.newCall(request).execute()) {
            return response.body().string();
        }
    }

    String post(String url, String json) throws IOException {
        RequestBody body = RequestBody.create(JSON, json);
        Request request = new Request.Builder()
                .url(url)
                .header("User-Agent", "Mozilla/5.0 (Linux; U; Android 2.3.5; zh-cn; HTC_IncredibleS_S710e Build/GRJ90) AppleWebKit/533.1 (KHTML, like Gecko) Version/4.0 Mobile Safari/533.1")
                .post(body)
                .build();
        try (Response response = client.newCall(request).execute()) {
            return response.body().string();
        }
    }

    String bowlingJson(String player1, String player2) {
        return "{'winCondition':'HIGH_SCORE',"
                + "'name':'Bowling',"
                + "'round':4,"
                + "'lastSaved':1367702411696,"
                + "'dateStarted':1367702378785,"
                + "'players':["
                + "{'name':'" + player1 + "','history':[10,8,6,7,8],'color':-13388315,'total':39},"
                + "{'name':'" + player2 + "','history':[6,10,5,10,10],'color':-48060,'total':41}"
                + "]}";
    }

    public static void main(String[] args) throws IOException {
        GetExample example = new GetExample();
        example.init();
        String response = example.run("https://bbs.et8.net/bbs/forumdisplay.php?sort=dateline&order=desc&page=1&f=147");
       // System.out.println(response);
        response = example.run("https://bbs.et8.net/bbs/login.php?do=vcode");
        String json = example.bowlingJson("Jesse", "Jake");
        response = example.post("https://bbs.et8.net/bbs/login.php", json);
     //   System.out.println(response);
    }
}
`

Does HttpLoggingInterceptor not logging post headers ?

**Comment by muziling** [comment]
Solve,  okhttp3 defalut user-agent is okhttp/3.4.1,   If I need to visit mobile page, i need to set to android user-agent.
okhttp2 use HttpURLConnection method ,so user-agent is device default user-agent .
