### ISSUE TITLE
Feature Request: Send HTTP requests from Authenticator

### ISSUE THREAD

**Issue by juherr** [square/okhttp#2733]
Hi,

I'd like to have a way to send some HTTP requests from the `Authenticator` because some authentication mechanisms need it in its workflow (for example: OAuth).

As workaround, for the moment, 
* I can create a new instance of `OkHttpClient` but I'm not sure it is a good practice, or 
* I can add a `setHttpClient` method in `Authenticator`:

```java
MyAuthenticator authenticator = new MyAuthenticator();
OkHttpClient client = new OkHttpClient.Builder()
                .authenticator(authenticator)
                .build();
authenticator.setHttpClient(client);
```

But

```java
        OkHttpClient client = new OkHttpClient.Builder()
                .authenticator(new MyAuthenticator(client))
                .build();
```

is not possible.

**Comment by swankjesse** [comment]
Seems like your workaround is sufficient. Not much else we can do about circular references unfortunately.

**Comment by juherr** [comment]
In fact, a built-in solution would be to have the client reference provided in the callback method.

**Comment by swankjesse** [comment]
Yep. That’s a big backwards-incompatible change. We’ll add it to the list of things to consider for okhttp4 in 2021.

**Comment by juherr** [comment]
:+1: I can't wait! :laughing:

**Comment by hosseinaminii** [comment]
It's now 2022 and I still have this issue. Is there any way to fix it in OkHttp5?

**Comment by swankjesse** [comment]
One workaround is to use OkHttpClient.newBuilder():

  1. Create basicClient, an OkHttpClient that's configured exactly as you want it, but with no Authenticator.
  2. Pass the basicClient to your Authenticator constructor
  3. Use basicClient.newBuilder(), add the authenticator, then call build() to create your authenticated client. Use this everywhere.
