### ISSUE TITLE
How to Create a Http Delete Or Put Method With Params?

### ISSUE THREAD

**Issue by wsf5918** [square/okhttp#2734]
What kind of issue is this?

 - [ ] Question. This issue tracker is not the place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use Stack
       Overflow. https://stackoverflow.com/questions/tagged/okhttp

How to Create a Http Delete Or Put Method With Params? Could You Show Me ,I will be grateful

**Comment by JakeWharton** [comment]
Please ask usage questions on StackOverflow with the 'okhttp' tag. There are more people around to answer, it has a reward system for asking and answering quetsions, and it serves as a much more searchable place for existing questions.

**Comment by wsf5918** [comment]
http://stackoverflow.com/questions/38465160/how-to-use-okhttpclient-create-a-http-delete-or-put-method-with-params-android

this is the stack question
