### ISSUE TITLE
Cookie.parse() doesn't strip double quotes around the Path

### ISSUE THREAD

**Issue by venator85** [square/okhttp#2737]
Hi,
we recently migrated our server application container to Tomcat 7.0, but we are having an issue with OkHttp cookie parsing on our Android app: Path's containing slashes are now surrounded with double quotes, as per:

https://tomcat.apache.org/migration-7.html#Cookies

However the Cookie.parse() method in OkHttp doesn't strip the double quotes, and the path of the URL (minus the last segment) is erroneously used instead (https://github.com/square/okhttp/blob/master/okhttp/src/main/java/okhttp3/Cookie.java#L306)

Here is a test that fails on OkHttp 3.4.1:

```java
@Test
public void testQuotedCookiePath() {
	HttpUrl url = HttpUrl.parse("http://a.com/foo/b/c");

	Cookie cookie1 = Cookie.parse(url, "AAA=BBB; Path=/foo; HttpOnly; Version=1");
	assertEquals("/foo", cookie1.path());

	Cookie cookie2 = Cookie.parse(url, "AAA=BBB; Path=\"/foo\"; HttpOnly; Version=1");
	assertEquals("/foo", cookie2.path());   // Actual: /foo/b
}
```

Thanks and keep up the excellent work ;)

**Comment by swankjesse** [comment]
The double quotes aren’t covered in RFC 6265, which attempts to be a complete guide to how Cookies should work on the Internet. That’s too bad.

Next steps:
– Notify the RFC 6265 authors that this interop requirement is missing. Maybe for errata.
– Figure out how quotes should work. For example, if the cookie is `AAA=BBB Path=/6"sub` we don’t want to treat a non-leading `"` as special. But if it’s `AAA=BBB Path="/;HttpOnly"` we want to interpret it as a path containing `/;HttpOnly`. Weird.

**Comment by venator85** [comment]
Quotes are already stripped in OkHttp's JavaNetCookieJar:
https://github.com/square/okhttp/blob/master/okhttp-urlconnection/src/main/java/okhttp3/JavaNetCookieJar.java#L99
however this is performed after the Cookie has been parse()d, so it is too late. I'd simply move that logic in Cookie.parse:
```java
// If the value is "quoted", drop the quotes.
if (value.startsWith("\"") && value.endsWith("\"")) {
    value = value.substring(1, value.length() - 1);
}
```

**Comment by swankjesse** [comment]
See discussion here. https://github.com/square/okhttp/pull/2887
