### ISSUE TITLE
Can't overwrite okhttp3.Cache

### ISSUE THREAD

**Issue by titanseason** [square/okhttp#2740]
Feature Request:
After I  cached a http request with _timestamp_ parameter, such as http://api.example.com/path?user=xxx&timestamp=xxx, the next time I send a request within 2 hours, for the reason of timestamp changed, okhttp will send a second requst to server. But I don't want to send a new request, and I just want okhttp read data from cache directly

Solution:
1. Remove _final_ modifier of class  _okhttp3.Cache_ 
2. Make the method _okhttp3.Cache#urlToKey_  public and none static. 

Can you make this feature?

Poor English, Sorry~

**Comment by swankjesse** [comment]
What problem are you attempting to solve? Can you use Cache-Control instead of the query parameter?

**Comment by titanseason** [comment]
Yes, I am using CacheControl like this:
1. File cacheDirectory = new File(App.getApp().getExternalCacheDir(), "http");
    Cache cache = new Cache(cacheDirectory, 2 * 1024 * 1024); // 2M
    OkHttpClient.Builder builder = new OkHttpClient.Builder().cache(cache);
    OkHttpClient client = builder.build();

2. CacheControl cacheControl = new CacheControl.Builder().maxAge(2, TimeUnit.HOURS).build();

3. Request.Builder builder = new Request.Builder().url(url).cacheControl(cacheControl);
    Request request = builder.build();
    client.newCall(request).enqueue(callback);

But okhttp will send a second request to server within 2 hours, because my http request url contains _timestamp_ paramter which changed every time I build the url.

So, will you make these changes:
1. Remove final modifier of class _okhttp3.Cache_ 
2. Make the method _okhttp3.Cache#urlToKey_ protected and none static.

**Comment by swankjesse** [comment]
Can you just remove the timestamp parameter? Seems likely it’ll interfere with other caches, including a potential reverse proxy on your webserver.

**Comment by titanseason** [comment]
I can simply remove the timestamp parameter, but I'm wondering why you desgin the class _okhttp3.Cache_ as final

**Comment by swankjesse** [comment]
It's final because it’s easier for us to make changes that way. Effective Java has a deeper explanation on this.
