### ISSUE TITLE
i think if the "request" replace "okhttp" to  support  "proxy " and "socket.bind(localAddress)" ,it will be very good.

### ISSUE THREAD

**Issue by scanry** [square/okhttp#2747]
i think if the "request" replace "okhttp" to  support  "proxy " and "socket.bind(localAddress)" ,it will be very good.

**Comment by swankjesse** [comment]
I don’t understand what action to take here.

**Comment by scanry** [comment]
for example：
           Builder build = new Builder().url(url);
           build.localAddress(new InetSocketAddress(tempIp, 0));
           SocketAddress sa = new InetSocketAddress(host,port);
           Proxy proxy = new Proxy(Proxy.Type.HTTP, sa);
           build.proxy(proxy);
           Request request = build.build();

if "request.build" support above, i think the "okhttp" will be flexible.
