### ISSUE TITLE
Multiple Cookies are not sending to the subsequent request 

### ISSUE THREAD

**Issue by nksaroj** [square/okhttp#2752]
Multiple Cookies are not sending to the subsequent request where the previous response has multiple "Set-Cookie".
At the moment the current implementation of JavaNetCookieJar sends only the first cookie to the request and ignores other cookies 

Any robust solution is appreciated 

http://stackoverflow.com/questions/38582530/multiple-cookies-headers-okhttp-javanetcookiejar/38586512#38586512

**Comment by swankjesse** [comment]
Could you provide an executable test case please?

**Comment by nksaroj** [comment]
Hi @swankjesse , I can get a test case ready sometimes . But I can give you quick response payload with bunch of Set-Cookie from which I would like to construct a request payload with the same set of cookies from the earlier given response.
Sample of payload with cookies from which I would like to construct a OKHttp request object as mentioned below.


###  Response Payload
-----------------
```
HTTP/1.1 200 OK
Cache-Control: no-cache, no-store
Content-Type: application/json; charset=utf-8
Expires: -1
Pragma: no-cache
X-AspNet-Version: 4.0.30319
X-Powered-By: AM
Vary: Accept-Encoding
Content-Encoding: gzip
Date: Tue, 26 Jul 2016 12:35:08 GMT
Content-Length: 949
Connection: keep-alive

Set-Cookie: ASP.NET_SessionId=rej2xzwk04qewwkks2j3waec; domain=.psl.com; path=/; secure; HttpOnly
Set-Cookie: kns=cECa%2fzrO%2fz8CSNuuhDBzBQ%3d%3d%2fW7FfxcEJnSyPteckFGo88khlgyNzgBQyb%2fNlIZk%2fj4qTP%2fx%2f%6ogj9; domain=.psl.com; path=/; secure; HttpOnly
Set-Cookie: krl=664; domain=commsec.com.au; path=/; HttpOnly
Set-Cookie: psl=NF5oxEr8GNx2AtHRpOzCoOkGQJqckcA%3d%3d; domain=.psl.com; path=/; secure; HttpOnly
Set-Cookie: gyk=1FQULisVdAgPawwRgLfza3g%3d%3dM8RTbwXdbc62RodKIkw4t2vem5a6Ggb; domain=.psl.com; path=/; secure; HttpOnly

{"message":"Sucess"}

```
###  Request Payload I would like to construct from the above response.

GET /v1/api/getOrders HTTP/1.1
User-Agent: Dalvik/2.1.0 (Linux; U; Android 6.0.1; Nexus 5 Build/MOB30P)
Referer: https://app.psl.com/?OS=android
Origin: https://psl.com
Content-Type: application/json; charset=UTF-8
Host: app.psl.com
Connection: Keep-Alive
Accept-Encoding: gzip
**Cookie: ASP.NET_SessionId=rej2xzwk04qewwkks2j3waec; 
kns=1cECa%2fzrO%2fz8CSNuuhDBzBQ%3d%3d%2fW7FfxcEJnSyPteckFGo88khlgyNzgBQyb%2fNlIZk%2fj4qTP%2fx%2f%6ogj9;
krl=664; 
psl=NF5oxEr8GNx2AtHRpOzCoOkGQJqckcA%3d%3d;
gyk=1FQULisVdAgPawwRgLfza3g%3d%3dM8RTbwXdbc62RodKIkw4t2vem5a6Ggb;**

At the moment when I use JavaNetCookieJar to construct the OkHttp object it's only adding ASP.NET_SessionId and ignoring other cookies to add to it.

I hope it's quite clear.

**Comment by swankjesse** [comment]
I couldn’t reproduce this problem in a test case. Note that my test is using an HTTP proxy to get hostnames that match your examples.

```
  @Test public void receiveAndSendMultipleCookies2() throws Exception {
    MockWebServer server = new MockWebServer();
    server.enqueue(new MockResponse()
        .addHeader("Set-Cookie: ASP.NET_SessionId=rej2xzwk04qewwkks2j3waec; domain=.psl.com; path=/; HttpOnly")
        .addHeader("Set-Cookie: kns=cECa%2fzrO%2fz8CSNuuhDBzBQ%3d%3d%2fW7FfxcEJnSyPteckFGo88khlgyNzgBQyb%2fNlIZk%2fj4qTP%2fx%2f%6ogj9; domain=.psl.com; path=/; HttpOnly")
        .addHeader("Set-Cookie: krl=664; domain=commsec.com.au; path=/; HttpOnly")
        .addHeader("Set-Cookie: psl=NF5oxEr8GNx2AtHRpOzCoOkGQJqckcA%3d%3d; domain=.psl.com; path=/; HttpOnly")
        .addHeader("Set-Cookie: gyk=1FQULisVdAgPawwRgLfza3g%3d%3dM8RTbwXdbc62RodKIkw4t2vem5a6Ggb; domain=.psl.com; path=/; HttpOnly"));
        //.addHeader("Set-Cookie: ASP.NET_SessionId=rej2xzwk04qewwkks2j3waec; domain=.psl.com; path=/; secure; HttpOnly")
        //.addHeader("Set-Cookie: kns=cECa%2fzrO%2fz8CSNuuhDBzBQ%3d%3d%2fW7FfxcEJnSyPteckFGo88khlgyNzgBQyb%2fNlIZk%2fj4qTP%2fx%2f%6ogj9; domain=.psl.com; path=/; secure; HttpOnly")
        //.addHeader("Set-Cookie: krl=664; domain=commsec.com.au; path=/; HttpOnly")
        //.addHeader("Set-Cookie: psl=NF5oxEr8GNx2AtHRpOzCoOkGQJqckcA%3d%3d; domain=.psl.com; path=/; secure; HttpOnly")
        //.addHeader("Set-Cookie: gyk=1FQULisVdAgPawwRgLfza3g%3d%3dM8RTbwXdbc62RodKIkw4t2vem5a6Ggb; domain=.psl.com; path=/; secure; HttpOnly"));
    server.enqueue(new MockResponse());
    server.start();

    CookieManager cookieManager = new CookieManager(null, ACCEPT_ORIGINAL_SERVER);
    client = client.newBuilder()
        .proxy(server.toProxyAddress())
        .cookieJar(new JavaNetCookieJar(cookieManager))
        .build();

    get(HttpUrl.parse("http://app.psl.com/v1/api/getOrders"));
    RecordedRequest request1 = server.takeRequest();
    assertNull(request1.getHeader("Cookie"));

    get(HttpUrl.parse("http://app.psl.com/v1/api/getOrders"));
    RecordedRequest request2 = server.takeRequest();
    System.out.println(request2.getHeader("Cookie"));
  }
```

**Comment by swankjesse** [comment]
... I also removed the `secure; ` attribute from the cookies for the test. Setting up HTTPS with a matching hostname is an exercise for the reader!
