### ISSUE TITLE
setConnectTimeout not resolved by OkHttpClient object ? 

### ISSUE THREAD

**Issue by youcaf** [square/okhttp#2753]
What kind of issue is this?

 - [ ] Question. This issue tracker is not the place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use Stack
       Overflow. https://stackoverflow.com/questions/tagged/okhttp

 - [ ] Bug report. If you’ve found a bug, spend the time to write a failing test. Bugs with tests
       get fixed. Here’s an example: https://gist.github.com/swankjesse/981fcae102f513eb13ed

 - [ ] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
       already exists! Don’t send pull requests to implement new features without first getting our
       support. Sometimes we leave features out on purpose to keep the project small.

**Comment by youcaf** [comment]
I am facing connection time out exception. how can i prolong my connection time using okhttpclient

**Comment by 15characterlimi** [comment]
By setting an appropriate [connectTimeout](http://square.github.io/okhttp/3.x/okhttp/okhttp3/OkHttpClient.Builder.html#connectTimeout-long-java.util.concurrent.TimeUnit-) on your OkHttpClient.Builder, like the documentation suggests? If unset, the default is 10 seconds.
