### ISSUE TITLE
Duplicate entry okhttp3/Address.class

### ISSUE THREAD

**Issue by Paul776** [square/okhttp#2755]
Hello,

I'm facing an issue 

Error:Execution failed for task ':app:transformClassesWithJarMergingForLiteDebug'.
> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: okhttp3/Address.class

and sometimes

Error:Execution failed for task ':app:transformClassesWithJarMergingForLiteDebug'.
> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: okio/AsyncTimeout$1.class

The gradle file
    compile ('com.google.android.gms:play-services-maps:9.2.1')
    compile ('com.google.android.gms:play-services-location:9.2.1')
    compile ('com.android.support:appcompat-v7:23.2.1')
    compile ('com.android.support:design:23.2.1')
    compile ('joda-time:joda-time:2.9.4')
    compile ('com.google.firebase:firebase-ads:9.2.1')
    compile ('com.android.support:multidex:1.0.1')
    compile files('libs/Ajar-lib-usin-http3.jar') // this jar and okhttp 3.4.1
    compile ('com.github.svarzee:gpsoauth-java:v0.2.0') uses okio 1.90 and 3.4.1

I have tried 

compile ('com.github.svarzee:gpsoauth-java:v0.2.0'){
        exclude group: 'com.squareup.okhttp3', module: 'okhttp'
    }
  
But I still get the same error.

Is this a bug with the lib or a something wrong with the way O use the libs ?

Thanks!

**Comment by mhmtk** [comment]
I'm getting the same error. Seeing you've closed this issue yourself, mind sharing what caused it/how you solved it?

**Comment by huaihong1986** [comment]
There must be  more than one place have included the okhttp jar.

**Comment by shihabmi7** [comment]
Did you get any solution @Paul776

**Comment by cinder92** [comment]
any solutions?
