### ISSUE TITLE
Headers duplication

### ISSUE THREAD

**Issue by anormobile** [square/okhttp#2762]
Hi, i found that okhttp can produces duplicates of headers.
I've manually add one, but second appears in the final request:
```
User-Agent:okhttp/current_version
User-Agent:my_header
```
[According to rfc2616](http://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2) it should be comma separated.
It's not a a big issue with the headers added by the user, but the automatically added headers is.
Can it be overriden by the last added header or merged not to produce duplicates? Does it make sense?

**Comment by swankjesse** [comment]
That’s strange. OkHttp only adds its user-agent header if there isn't one already present. Are you using a network interceptor to add the header? If so consider using `header(...)` instead of `addHeader(...)`. That’ll replace what’s already present.

**Comment by anormobile** [comment]
Yes, it's interceptor, so the `User-Agent:okhttp/current_version` already exists, and it's `addHeader(...)`. I've checked it with `header(...)` and it works as expected. So the only one unexpected thing was to have `User-Agent:okhttp/current_version`. Can it be optional instead of default?

**Comment by swankjesse** [comment]
At the moment it’ll only add that header if there’s none already present. Is that sufficient?

**Comment by anormobile** [comment]
That's sufficient for all the cases except interceptor, where user can add more headers and expect the defaults will not be added. Of course it can be easily fixed, but it's not obvious that you need handle it. 
The real problem is that in the most cases you'll never know about this header, before there will be some issues with API. 
Do we really need this default User-Agent header?

**Comment by swankjesse** [comment]
Yes we do.
