### ISSUE TITLE
Bug with cookie parsing.

### ISSUE THREAD

**Issue by MagicDroidX** [square/okhttp#2764]
What kind of issue is this?

 - [ ] Question. This issue tracker is not the place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use Stack
       Overflow. https://stackoverflow.com/questions/tagged/okhttp

 - [x] Bug report. If you’ve found a bug, spend the time to write a failing test. Bugs with tests
       get fixed. Here’s an example: https://gist.github.com/swankjesse/981fcae102f513eb13ed

 - [ ] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
       already exists! Don’t send pull requests to implement new features without first getting our
       support. Sometimes we leave features out on purpose to keep the project small.

I am using `CookieJar` to manage the cookies from server.
And when I get 'Set-Cookie' headers like this: 
`Set-Cookie: hf_skey=1408572.1408572..1470048717.1.5d4ed14e45a8b41edcfdad3df5490c3d; path=/`
It was parsed into only one `Cookie`, and it's value is `1408572.1408572..1470048717.1.5d4ed14e45a8b41edcfdad3df5490c3d`.
So what I want to say is that the `path=/` is somehow ignored.
This is how I implement the `CookieJar`
```
new CookieJar() {
                List<Cookie> cookies = new ArrayList<>();

                @Override
                public void saveFromResponse(HttpUrl url, List<Cookie> cookies) {
                    this.cookies.clear();
                    this.cookies.addAll(cookies);
                    for (Cookie cookie : cookies) {
                        Log.i(cookie.name(), cookie.value());
                    }
                }

                @Override
                public List<Cookie> loadForRequest(HttpUrl url) {
                    return cookies;
                }
            }
```

**Comment by swankjesse** [comment]
Could you provide a complete test case to demonstrate your expected behavior? As is I don’t understand what behavior you disagree with.

**Comment by whichname** [comment]
I also got the same problem.

When I get 'Set-Cookie' headers in response like this:
Set-Cookie: hellou=c4ac2e4d0a61edf5015f08f9586e134b1d4dd6953d4f2a2c4d894599b963b1bf; Max-Age=2592000; Domain=hello.six.cn; Path=/; Expires=Fri, 07 Oct 2016 03:00:42 GMT

I saved this cookie to SharedPreferences and in next time,I get this cookie and send to server.
But I noticed the cookie in request's header becomes like this:
Cookie:nrhyu=c4ac2e4d0a61edf5015f08f9586e134b1d4dd6953d4f2a2c4d894599b963b1bf

The path,domain has been ignored.

Thank u very much.

**Comment by swankjesse** [comment]
@whichname cookie request headers don’t include a path or domain. Or am I misunderstanding?

**Comment by whichname** [comment]
Yes.
The 'Set-Cookie' in response like this:
![image](https://cloud.githubusercontent.com/assets/11702714/18299807/768f3468-74f6-11e6-861c-201681aa3153.png)

But in next request,the cookie becomes like this:
![image](https://cloud.githubusercontent.com/assets/11702714/18299818/8e5d2f14-74f6-11e6-96b8-99ec2a197685.png)

The domain and path disappeared.

But when I use Volly ,the cookie in request like this:
![image](https://cloud.githubusercontent.com/assets/11702714/18299869/05eeea0e-74f7-11e6-9409-5f109c7465d1.png)

Sorry, my English is not so good.
Thank u very much.

**Comment by swankjesse** [comment]
That’s working as designed. You can confirm that the behavior is consistent with web browsers if you like.
