### ISSUE TITLE
CertPathValidatorException only throw in the first time

### ISSUE THREAD

**Issue by chezhong** [square/okhttp#2766]
I implemented the Certificate Pinning by using OKhttp CertificatePinner. But when I test it with Charles SSL Proxying, I see the CertPathValidatorException only throw for the first time and it won't show again in the next calls. If I kill the app and restart it, I can see the CertPathValidatorException again, but still it will only work for the first time.  Could someone guide me on this issue? 

Many thanks!

**Comment by swankjesse** [comment]
When you configure OkHttp to use Charles, you need to do it by calling `OkHttpClient.Builder.proxy()`. Otherwise it’ll pick up the system proxy configuration. When it does that, and the proxy doesn’t work, it automatically retries with a direct connection.

**Comment by b95505017** [comment]
@swankjesse I can't use Interceptor to catch this exception, is there any way to monitor this generally?
