### ISSUE TITLE
Feature request / question: equals() implementation in Request?

### ISSUE THREAD

**Issue by cxzhang2** [square/okhttp#2773]
Not a big deal since toString() is implemented and a toString() comparison works in most cases, just wondering if there was a specific reason to leave out the equals() implementation?

**Comment by swankjesse** [comment]
It implements equals, just by object identity. Other implementations could get awkward because we might need to read the request body.

**Comment by cxzhang2** [comment]
Makes sense.  I ran into this following your cancellation by tag example in #2205 and assumed you had used .equals() instead of == because `Request` had its own implementation.
