### ISSUE TITLE
ResponseBody,charStream(),Reader 

### ISSUE THREAD

**Issue by yubaokang** [square/okhttp#2779]
### class okhttp3.ResponseBody
```java
public final Reader charStream() {
Reader r = reader;
return r != null ? r : (reader = new InputStreamReader(byteStream(), charset()));
}
```
#### why not like this?
```java
public final Reader charStream() {
return new InputStreamReader(byteStream(), charset());
}
```
#### gson.newJsonReader(new StringReader(Html.fromHtml(value.string()).toString()));//Is there a problem?

```java
final class GsonResponseBodyConverter implements Converter {
private final Gson gson;
private final TypeAdapter adapter;
GsonResponseBodyConverter(Gson gson, TypeAdapter<T> adapter) {
    this.gson = gson;
    this.adapter = adapter;
}

@Override
public T convert(ResponseBody value) throws IOException {
   // JsonReader jsonReader1 = gson.newJsonReader(value.charStream());
    JsonReader jsonReader = gson.newJsonReader(new StringReader(Html.fromHtml(value.string()).toString()));//Is there a problem?
    try {
        return adapter.read(jsonReader);
    } finally {
        value.close();
    }
}
```

**Comment by yubaokang** [comment]
I use Retrofit2 and Gson;
final class GsonResponseBodyConverter<T> implements Converter<ResponseBody, T> {
    private final Gson gson;
    private final TypeAdapter<T> adapter;

    GsonResponseBodyConverter(Gson gson, TypeAdapter<T> adapter) {
        this.gson = gson;
        this.adapter = adapter;
    }

    @Override
    public T convert(ResponseBody value) throws IOException {
       // JsonReader jsonReader1 = gson.newJsonReader(value.charStream());
        JsonReader jsonReader = gson.newJsonReader(new StringReader(Html.fromHtml(value.string()).toString()));//Is there a problem?
        try {
            return adapter.read(jsonReader);
        } finally {
            value.close();
        }
    }
}

**Comment by swankjesse** [comment]
Is this a bug report? Please provide an executable test case. If it's a usage question, please use StackOverflow.
