### ISSUE TITLE
Support for WWW-Authenticate headers which does not strictly follow RFC 2617

### ISSUE THREAD

**Issue by alexeyvasilyev** [square/okhttp#2780]
OkHttp expects WWW-Authenticate header to have **realm** parameter going right after **Digest** token in HttpHeaders.parseChallenges(Headers responseHeaders, String challengeHeader) method, e.g.
`WWW-Authenticate: Digest realm="DS-2CD2432F-IW", nonce="4d6a6c4551305a43515449364e6d497a4d6a63314e546b3d", qop="auth", stale="FALSE"`

 However some web servers (e.g. widely used Hikvision IP cameras) can send parameters in different order, e.g.

`WWW-Authenticate: Digest qop="auth", realm="DS-2CD2432F-IW", nonce="4d6a6c4551305a43515449364e6d497a4d6a63314e546b3d", stale="FALSE"`

This situation is not handled properly in OkHttp.

UNIT TEST:

`

    private static void test() {
        // Strict RFC 2617 header
        Headers headers = new Headers.Builder()
                .add("WWW-Authenticate", "Digest realm=\"DS-2CD2432F-IW\", nonce=\"4d6a6c4551305a43515449364e6d497a4d6a63314e546b3d\", qop=\"auth\", stale=\"FALSE\"").build();

        Assert.assertTrue(HttpHeaders.parseChallenges(headers, "WWW-Authenticate").size() == 1);

        // Not strict RFC 2617 header. Generates error in OkHttp 3.4.1.
        headers = new Headers.Builder()
                .add("WWW-Authenticate", "Digest qop=\"auth\", realm=\"DS-2CD2432F-IW\", nonce=\"4d6a6c4551305a43515449364e6d497a4d6a63314e546b3d\", stale=\"FALSE\"").build();
        Assert.assertTrue(HttpHeaders.parseChallenges(headers, "WWW-Authenticate").size() == 1);
    }
`

**Comment by alexeyvasilyev** [comment]
Got the same issue with widely used IP Webcam app version 1.12.4r
https://play.google.com/store/apps/details?id=com.pas.webcam

GET /shot.jpg HTTP/1.1
User-Agent: Android/6.0 (6.0 - 5X) com.alexvas.dvr.pro
Host: 10.0.1.4:8080
Connection: Keep-Alive
Accept-Encoding: gzip

HTTP/1.1 401 Unauthorized
Content-Length: 0
WWW-Authenticate: Digest qop="auth", realm="IP Webcam", nonce="1470841389"

**Comment by rfc2822** [comment]
Please see also #2772, where I have linked working code which parses `WWW-Authenticate` parameters (named as well as anonymous ones).

**Comment by JerryChin** [comment]
```HttpHeaders.parseChallenges``` is _basically_ broken, I come across a ```@TODO``` stub in it, saying:
> This currently only handles schemes with a 'realm' parameter;
  It needs to be fixed to handle any scheme and any parameters
  http://code.google.com/p/android/issues/detail?id=11140

**Comment by alexeyvasilyev** [comment]
https://github.com/rburgst/okhttp-digest uses `response.challenges()` which uses `HttpHeaders.parseChallenges()` to get scheme via `Challenge` instance. If `realm=value` is not the first parameter, `Challenge` is not returned and okhttp-digest does not work.

**Comment by JerryChin** [comment]
> https://github.com/rburgst/okhttp-digest uses response.challenges() which uses HttpHeaders.parseChallenges() to get scheme via Challenge instance.

Are you sure it's **okhttp-digest** bothering you? 

> If realm=value is not the first parameter, Challenge is not returned and okhttp-digest does not work.

The order should be the _very_ least of your worries , since ```Realm``` is the only parameter being parsed,

**Comment by alexeyvasilyev** [comment]
Check this line
https://github.com/rburgst/okhttp-digest/blob/master/src/main/java/com/burgstaller/okhttp/DispatchingAuthenticator.java#L35

What I'm trying to say is that if `realm` cannot be parsed in `HttpHeaders.parseChallenges()`, `scheme` is not returned.

**Comment by JerryChin** [comment]
Okay, I see, seems someone is working on it. Good luck!

**Comment by alexeyvasilyev** [comment]
No, nobody is working. **That is an issue in OkHttp**.
Check unit tests submitted in first post.

**Comment by JerryChin** [comment]
That's sad, there're two ways to solve your problems, either to

- implement #2772 proposal(closed, at this point) to fix ```HttpHeaders.parseChallenges```, but the downside is unnecessary overhead as ``` WWW-Authenticate``` header get parsed two times.
- or create a new issue under okhttp-digest, for ```Response.challenges``` is not usable for parsing Digest scheme.

**Comment by alexeyvasilyev** [comment]
Why it should be okhttp-digest issue? The problem is that `HttpHeaders.parseChallenges()` method in OkHttp does not properly parses `realm` value in `WWW-Authenticate` header.

But yes, implementing #2772 will fix the issue.

**Comment by swankjesse** [comment]
Fixed with https://github.com/square/okhttp/pull/4252
