### ISSUE TITLE
Getting crash issue in on Cache

### ISSUE THREAD

**Issue by rameshkec85** [square/okhttp#2781]
Could you pls check and help me on this ?

08-09 13:00:44.746: I/dalvikvm(15817): "OkHttp http://yoapp-dev.herokuapp.com/..." prio=5 tid=31 RUNNABLE
08-09 13:00:44.746: I/dalvikvm(15817):   | group="main" sCount=0 dsCount=0 obj=0x45ce3400 self=0x62c75130
08-09 13:00:44.746: I/dalvikvm(15817):   | sysTid=19629 nice=0 sched=0/0 cgrp=apps handle=1690652936
08-09 13:00:44.746: I/dalvikvm(15817):   | state=R schedstat=( 978869299 6219494 74 ) utm=97 stm=0 core=2
08-09 13:00:44.746: I/dalvikvm(15817):   at okio.Segment.<init>(Segment.java:~61)
08-09 13:00:44.746: I/dalvikvm(15817):   at okio.SegmentPool.take(SegmentPool.java:46)
08-09 13:00:44.751: I/dalvikvm(15817):   at okio.Buffer.writableSegment(Buffer.java:1151)
08-09 13:00:44.751: I/dalvikvm(15817):   at okio.Okio$2.read(Okio.java:138)
08-09 13:00:44.751: I/dalvikvm(15817):   at okio.RealBufferedSource.indexOf(RealBufferedSource.java:325)
08-09 13:00:44.751: I/dalvikvm(15817):   at okio.RealBufferedSource.indexOf(RealBufferedSource.java:314)
08-09 13:00:44.751: I/dalvikvm(15817):   at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:210)
08-09 13:00:44.751: I/dalvikvm(15817):   at okhttp3.Cache$Entry.<init>(Cache.java:535)
08-09 13:00:44.751: I/dalvikvm(15817):   at okhttp3.Cache.get(Cache.java:203)
08-09 13:00:44.751: I/dalvikvm(15817):   at okhttp3.Cache$1.get(Cache.java:143)
08-09 13:00:44.751: I/dalvikvm(15817):   at okhttp3.internal.http.HttpEngine.sendRequest(HttpEngine.java:203)
08-09 13:00:44.751: I/dalvikvm(15817):   at okhttp3.RealCall.getResponse(RealCall.java:243)
08-09 13:00:44.751: I/dalvikvm(15817):   at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:201)
08-09 13:00:44.751: I/dalvikvm(15817):   at com.yo.android.di.NetWorkModule$OfflineResponseInterceptor.intercept(NetWorkModule.java:177)
08-09 13:00:44.751: I/dalvikvm(15817):   at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:190)
08-09 13:00:44.751: I/dalvikvm(15817):   at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:212)
08-09 13:00:44.751: I/dalvikvm(15817):   at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:190)
08-09 13:00:44.751: I/dalvikvm(15817):   at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:163)
08-09 13:00:44.751: I/dalvikvm(15817):   at okhttp3.RealCall.access$100(RealCall.java:30)
08-09 13:00:44.751: I/dalvikvm(15817):   at okhttp3.RealCall$AsyncCall.execute(RealCall.java:127)
08-09 13:00:44.751: I/dalvikvm(15817):   at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
08-09 13:00:44.751: I/dalvikvm(15817):   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
08-09 13:00:44.751: I/dalvikvm(15817):   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
08-09 13:00:44.751: I/dalvikvm(15817):   at java.lang.Thread.run(Thread.java:841)
08-09 13:00:44.756: W/dalvikvm(15817): threadid=31: thread exiting with uncaught exception (group=0x41d5bc08)
08-09 13:00:44.811:
************************The below code I am using for offline caching
` public class OfflineResponseInterceptor implements Interceptor {
        final ConnectivityHelper mConnectivityHelper;

        public OfflineResponseInterceptor(ConnectivityHelper connectivityHelper) {
            mConnectivityHelper = connectivityHelper;
        }

        @Override
        public Response intercept(Chain chain) throws IOException {
            Request request = chain.request();

            if (!mConnectivityHelper.isConnected()) {
                // tolerate 4-weeks stale
                int maxStale = 60 * 60 * 24 * 28;
                request = request.newBuilder()
                        .header("Cache-Control", "public, only-if-cached, max-stale=" + maxStale)
                        .build();
            }

            return chain.proceed(request);
        }
    }
`

**Comment by swankjesse** [comment]
Is this the full log? I would have expected something about an exception.

**Comment by swankjesse** [comment]
No action for us to take here.
