### ISSUE TITLE
how can I use request param before execute 

### ISSUE THREAD

**Issue by Witype** [square/okhttp#2782]
I want to sign params bafore request,because of the params is different each call,so what can I do!!!
![image](https://cloud.githubusercontent.com/assets/6899329/17511852/7deac138-5e57-11e6-8e83-531c2163149f.png)
thanks!!!

**Comment by Witype** [comment]
![image](https://cloud.githubusercontent.com/assets/6899329/17511993/3970a206-5e58-11e6-9165-1175b9b4db76.png)

**Comment by swankjesse** [comment]
Please use StackOverflow for usage questions.

**Comment by swankjesse** [comment]
Please use StackOverflow for usage questions.
