### ISSUE TITLE
java.lang.NullPointerException: interceptor  

### ISSUE THREAD

**Issue by thiagolenz** [square/okhttp#2784]
It occurs a lot, I can't even catch this NullPointer, and is stopping my app. Can you throws a correct exception please ? 

java.lang.NullPointerException: interceptor com.angel.angelmobile.services.rest.RestClient$2@237f95b6 returned null
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:102)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:170)
	at okhttp3.RealCall.access$100(RealCall.java:33)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:120)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)

**Comment by JakeWharton** [comment]
Your interceptor is returning null which is not allowed. Fix that and don't
worry about catching anything.

**Comment by thiagolenz** [comment]
Here is the code of my interceptor, it never catch on Exception, either on Error 

`OkHttpClient.Builder httpClientBuilder = new OkHttpClient.Builder();
        httpClientBuilder.addInterceptor(new Interceptor() {
            @Override
            public Response intercept(Interceptor.Chain chain) throws IOException {
                try {
                    Request original = chain.request();

                    Request request = original.newBuilder()
                            .header(AngelApplication.PUBLIC_REQUEST_TOKEN_KEY, AngelApplication.PUBLIC_REQUEST_TOKEN_VALUE)
                            .method(original.method(), original.body())
                            .build();

                    return chain.proceed(request);
                } catch (Exception e) {
                    callbackError.onError(e, context);
                } catch (Error e2) {
                    Log.e("", "ROME parse error2: " + e2.toString());
                }
                return null;
            }
        });
        httpClientBuilder.readTimeout(300, TimeUnit.SECONDS);
        httpClientBuilder.connectTimeout(300, TimeUnit.SECONDS);
        httpClientBuilder.retryOnConnectionFailure(true);
        return httpClientBuilder.build();`

**Comment by JakeWharton** [comment]
It does, or you wouldn't get the NullPointerException. Instead of logging,
re-throw from the catch blocks by wrapping the exception in a
RuntimeException. That will surface the actual problem.

**Comment by thiagolenz** [comment]
I'll throw, if the error show again, I'll reopen this issue.

**Comment by GJson** [comment]
the error show again..... 
Your solution is？ @thiagolenz @JakeWharton

**Comment by fantianwen** [comment]
hi,I come up with this question,and it occured a lot. /(ㄒoㄒ)/~~
It bores me that I can NOT even catch this NullPointException.

I think when my result from okhttp is null or blank,OkHttp should NOT do anything (now it throws the exception) cause sometimes return null is JUST what I want...

wish for your response.

**Comment by swankjesse** [comment]
If you could provide us with an executable test case, that’ll help us to fix this quickly.

**Comment by fantianwen** [comment]
@swankjesse 
Problem solved,That is not OkHttp's bug,had found the reason(we return null and `chain.proceed()`).

But maybe Throwing a Exception by wrapping NullPointException instead of directely a NullPointException （could not be catched）,can be some more friendly.

😊

**Comment by zeeshanrasool91** [comment]
> hi,I come up with this question,and it occured a lot. /(ㄒoㄒ)/~~
> 
> I think when my result from okhttp is null or blank,OkHttp should NOT do anything (now it throws NullPointException which can NOT be catched) cause sometimes return null is JUST what I want...
> 
> wish for your response.

how did you solved it ?

**Comment by zhenguo** [comment]
> @swankjesse
> Problem solved,That is not OkHttp's bug,had found the reason(we return null but still `chain.proceed()`).
> 
> But maybe Throwing a Exception by wrapping NullPointException instead of directely a NullPointException （could not be catched）,can be some more friendly.
> 
> 😊

how did you solved it?

**Comment by fantianwen** [comment]
> > @swankjesse
> > Problem solved,That is not OkHttp's bug,had found the reason(we return null but still `chain.proceed()`).
> > But maybe Throwing a Exception by wrapping NullPointException instead of directely a NullPointException （could not be catched）,can be some more friendly.
> > 😊
> 
> how did you solved it?

Oh, 4 years ago!  I have not done Android for some years.
If I have not got a mistake from my remember. I think you can judge whether the return from last chain is NULL or not, and deal with it in your own code.
