### ISSUE TITLE
if "request.build" support below, i think the "okhttp" will be flexible.

### ISSUE THREAD

**Issue by scanry** [square/okhttp#2785]
for example：
Builder build = new Builder().url(url);
build.localAddress(new InetSocketAddress(tempIp, 0));
SocketAddress sa = new InetSocketAddress(host,port);
Proxy proxy = new Proxy(Proxy.Type.HTTP, sa);
build.proxy(proxy);
Request request = build.build();

if "request.build" support above, i think the "okhttp" will be flexible.

**Comment by swankjesse** [comment]
You can configure that on the OkHttpClient. It isn't on the request deliberately because it varies with the network environment.

**Comment by scanry** [comment]
because the OkHttpClient is global and single ,also no need for new any "OkHttpClient"  and the sokect is  based on "request" to create and  choose . so the grain size of configure  may be smaller

**Comment by artem-zinnatullin** [comment]
OkHttp is not global and single!
