### ISSUE TITLE
Platform in pre Lollipop android device with Jetty never getting ALPN supported one 

### ISSUE THREAD

**Issue by saantiaguilera** [square/okhttp#2787]
Im trying to migrate to Http2 (currently testing pro's/cons and alpn) in an Android app. Since it runs on 4.1 onwards, I've added Jetty as a dependency. Im trying to get ALPN support on pre 5.0 devices.

When the findPlatform() method is executed, it first checks if the Android platform is found, and of course this always returns non null (without finding the Network classes added in 5.0. For pre L devices, this is no ALPN). Because of this I can never use Jetty /w alpn (because the method will return the Android platform instance instead of the Jetty one), thus it brings me to http/1.1 (which I dont want to). 

Is there a way to achieve this ? (getting as platform a JdkWithJettyBootPlatform / getting null in the AndroidPlatform.buildIfSupported()). 
Maybe Jetty cant be used on Android ?

Some (maybe) useful data:

Dependency used:
```
//In dependencies of app's gradle
compile group: 'org.mortbay.jetty.alpn', name: 'alpn-boot', version: '7.1.3.v20150130'
```

OkHttp version: 3.3.1

Code
```Java
        OkHttpClient client = new OkHttpClient();

        Request request = new Request.Builder()
                .url(mUrl)
                .header(mKey, mValue)
                .get()
                .build();

        client.newCall(request).enqueue(someCallback);
```

Update: If I change it with reflection :
```
        if (!alreadyTriedToApplyJettyPlatform) {
            Platform jettyPlatform = JdkWithJettyBootPlatform.buildIfSupported();
            if (jettyPlatform != null) {
                try {
                    Field platform = Platform.class.getDeclaredField("PLATFORM");
                    platform.setAccessible(true);
                    platform.set(Platform.get(), jettyPlatform);
                } catch (Exception e) {
                }
            }

            alreadyTriedToApplyJettyPlatform = true;
        }
```
it does work (but it logs me that Jetty isnt in the boot classpath (which is true because I dont know how to do it with gradle). I will check this out, and keep the thread updated if needed

**Comment by swankjesse** [comment]
The jetty-alpn library won’t work on Android. It’s for desktop JVMs only. There’s no HTTP/2 on older Androids.

**Comment by saantiaguilera** [comment]
Oh, thats unfortunate. I guess I will simply have h/1.1 or h/2 depending on the api version then.

Im closing this since its not an issue, thanks for the quick reply !!
