### ISSUE TITLE
removeHeader("Pragma") not working

### ISSUE THREAD

**Issue by jpaseneta** [square/okhttp#2792]
What kind of issue is this?
Bug Report

hi, i've been trying to cache a response from a test rest api from http://jsonplaceholder.typicode.com

D/OkHttp: --> GET http://jsonplaceholder.typicode.com/posts/ http/1.1
D/OkHttp: --> END GET
D/OkHttp: <-- 200 OK http://jsonplaceholder.typicode.com/posts/ (2597ms)
D/OkHttp: Content-Type: application/json; charset=utf-8
D/OkHttp: Transfer-Encoding: chunked
D/OkHttp: Connection: keep-alive
D/OkHttp: Pragma: no-cache
D/OkHttp: Date: Mon, 15 Aug 2016 07:37:59 GMT
D/OkHttp: Set-Cookie: __cfduid=d7a80d31f44b803e5756cb4712926db891471246679; expires=Tue, 15-Aug-17 07:37:59 GMT; path=/; domain=.typicode.com; HttpOnly
D/OkHttp: X-Powered-By: Express
D/OkHttp: Vary: Accept-Encoding
D/OkHttp: Access-Control-Allow-Credentials: true
D/OkHttp: Expires: Mon, 15 Aug 2016 11:37:59 GMT
D/OkHttp: X-Content-Type-Options: nosniff
D/OkHttp: Etag: W/"6b80-uPwhAkDat3Fl5TugzmyYpQ"
D/OkHttp: Via: 1.1 vegur
D/OkHttp: CF-Cache-Status: HIT
D/OkHttp: Server: cloudflare-nginx
D/OkHttp: CF-RAY: 2d2afc05360e22be-LAX
D/OkHttp: Cache-Control: max-age=20
D/OkHttp: <-- END HTTP

i was successfully caching that response, along with also modifying the cache-control, however, all my efforts to remove `Pragma: no-cache` with `response.removeHeader("Pragma")` on my interceptor seems to have failed and i'm not sure why. That pragma prevents me from accessing my saved cache for offline work.

can someone give light to this?

**Comment by FabianTerhorst** [comment]
Can you post the interceptor code?

**Comment by swankjesse** [comment]
You should ask your server maintainers to do it. Caching a thing explicitly marked as no-cache will cause you problems!

**Comment by jpaseneta** [comment]
@FabianTerhorst here's my interceptors, added as Interceptor and networkInterceptor respectively:

```
private static final Interceptor REWRITE_RESPONSE_INTERCEPTOR = chain -> {
        Log.d(TAG,"network interceptor rewriting request");
        Request originalRequest = chain.request();
        Request request = originalRequest.newBuilder().build();
        okhttp3.Response response = chain.proceed(request);

        return response.newBuilder()
                .removeHeader("Pragma")
                .removeHeader("Cache-Control")
                .header("Cache-Control", "public, max-age=" + 60)
                .build();

    };


    static class OfflineInterceptor implements Interceptor{
        Context context;
        public OfflineInterceptor(Context ctx){
            context=ctx;
        }

        @Override
        public okhttp3.Response intercept(Chain chain) throws IOException {
            Request originalRequest = chain.request();
            Request request = originalRequest.newBuilder().build();
            int maxStale=60;
            if (!isNetworkOnline(context)) {
                Log.d(TAG, "offline interceptor rewriting request");

                maxStale = 60 * 60 * 24 * 28; // tolerate 4-weeks stale

            }

            okhttp3.Response response = chain.proceed(request);
            return response.newBuilder()
                    .removeHeader("Pragma")
                    .removeHeader("Cache-Control")
                    .header("Cache-Control", "public, only-if-cached, max-stale=" + maxStale)
                    .build();
        }
    }
```

**Comment by swankjesse** [comment]
Could you provide a complete executable test case? As is it’s unclear where the problem is.

**Comment by jpaseneta** [comment]
@swankjesse just followed your advice instead. since http://www.jsonplaceholder.typicode.com is a free test rest api, it's hard to play around with its server responses. I switched to www.mocky.io instead where i can modify server response codes/headers.

There might be something that's preventing me from removing the "Pragma" header as i'm trying these out.

You can close the issue. Thank you.
