### ISSUE TITLE
Okhttp 3.4.1  Upload Image report code 6003 Exception (java.net.SocketException: sendto failed: EBADF (Bad file descriptor) )

### ISSUE THREAD

**Issue by HarrisonLin** [square/okhttp#2794]
**When my network speed of uplink 18kbps or less** ,  upload pictures must report:

> 

      java.net.SocketException: sendto failed: EBADF (Bad file descriptor) 

But I use tool of catch packet （Charles ）,  upload process is normal，but project debug is report 6003 code , exception above

Paste My code：

`MultipartBody.Builder builder = new MultipartBody.Builder();

        builder.setType(MultipartBody.FORM)
                .addFormDataPart(key, file.getName(), getProgressRequestBody(MultipartBody.FORM, file, callback))
                .addPart(Headers.of("Content-Disposition", "form-data; filename=\"img.png\""), RequestBody.create(MediaType.parse("image/png"), file))
                .build();

        RequestBody requestBody = builder.build();

        Request request = new Request.Builder()
                .url(uploadUrl) //地址
                .post(requestBody)
                .build();

        createOkClient();

        mClient.newCall(request).enqueue(new okhttp3.Callback() {
            @Override
            public void onFailure(Call call, IOException e) {
                MainThreadCallback.onException(callback, ErrorCode.HTTP_CONNECTION_ERROR, e.toString());
            }

            @Override
            public void onResponse(Call call, Response response) throws IOException {
                if (!response.isSuccessful()) {
                    MainThreadCallback.onException(callback, ErrorCode.HTTP_CONNECTION_ERROR, "respone is no success");
                    return;
                }

                try {
                    String result = response.body().string();
                    JSONObject jsonObject = new JSONObject(result);
                    String url = jsonObject.optString("result");

                    if(TextUtils.isEmpty(url)){
                        MainThreadCallback.onException(callback, ErrorCode.DATA_ERROR, "上传文件生成的URL为空");
                        return;
                    }

                    MainThreadCallback.onSuccess(callback, url);

                } catch (Exception e) {
                    MainThreadCallback.onException(callback, ErrorCode.IO_ERROR, e.getMessage());
                }
            }
        });`

**Comment by swankjesse** [comment]
Could you provide a sample exception stacktrace?

**Comment by HarrisonLin** [comment]
![wechatimg4](https://cloud.githubusercontent.com/assets/10679283/17842561/b7902848-6856-11e6-97cc-7679081809d5.jpeg)
![wechatimg5](https://cloud.githubusercontent.com/assets/10679283/17842572/d65f024e-6856-11e6-85e3-9197fc1482d1.jpeg)

**Comment by swankjesse** [comment]
For future reference, the text of the stacktrace is a lot more helpful than a picture of it!

**Comment by HarrisonLin** [comment]
Oh, Sorry～  

08-22 10:49:23.749 13213-22929/com.mogujie.im.sdk.demo W/System.err: java.net.SocketTimeoutException: timeout
08-22 10:49:23.749 13213-22929/com.mogujie.im.sdk.demo W/System.err:     at okio.Okio$3.newTimeoutException(Okio.java:210)
08-22 10:49:23.750 13213-22929/com.mogujie.im.sdk.demo W/System.err:     at okio.AsyncTimeout.exit(AsyncTimeout.java:288)
08-22 10:49:23.750 13213-22929/com.mogujie.im.sdk.demo W/System.err:     at okio.AsyncTimeout$1.write(AsyncTimeout.java:184)
08-22 10:49:23.750 13213-22929/com.mogujie.im.sdk.demo W/System.err:     at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:171)
08-22 10:49:23.750 13213-22929/com.mogujie.im.sdk.demo W/System.err:     at okio.RealBufferedSink.write(RealBufferedSink.java:41)
08-22 10:49:23.750 13213-22929/com.mogujie.im.sdk.demo W/System.err:     at okhttp3.internal.http.Http1xStream$FixedLengthSink.write(Http1xStream.java:282)
08-22 10:49:23.750 13213-22929/com.mogujie.im.sdk.demo W/System.err:     at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:171)
08-22 10:49:23.750 13213-22929/com.mogujie.im.sdk.demo W/System.err:     at okio.RealBufferedSink.write(RealBufferedSink.java:41)
08-22 10:49:23.750 13213-22929/com.mogujie.im.sdk.demo W/System.err:     at com.mogujie.imsdk.core.im.module.file.FileModule$3.writeTo(FileModule.java:386)
08-22 10:49:23.750 13213-22929/com.mogujie.im.sdk.demo W/System.err:     at okhttp3.MultipartBody.writeOrCountBytes(MultipartBody.java:171)
08-22 10:49:23.750 13213-22929/com.mogujie.im.sdk.demo W/System.err:     at okhttp3.MultipartBody.writeTo(MultipartBody.java:113)
08-22 10:49:23.750 13213-22929/com.mogujie.im.sdk.demo W/System.err:     at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:47)
08-22 10:49:23.750 13213-22929/com.mogujie.im.sdk.demo W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
08-22 10:49:23.750 13213-22929/com.mogujie.im.sdk.demo W/System.err:     at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
08-22 10:49:23.750 13213-22929/com.mogujie.im.sdk.demo W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
08-22 10:49:23.750 13213-22929/com.mogujie.im.sdk.demo W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
08-22 10:49:23.750 13213-22929/com.mogujie.im.sdk.demo W/System.err:     at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:109)
08-22 10:49:23.750 13213-22929/com.mogujie.im.sdk.demo W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
08-22 10:49:23.750 13213-22929/com.mogujie.im.sdk.demo W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
08-22 10:49:23.750 13213-22929/com.mogujie.im.sdk.demo W/System.err:     at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
08-22 10:49:23.750 13213-22929/com.mogujie.im.sdk.demo W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
08-22 10:49:23.750 13213-22929/com.mogujie.im.sdk.demo W/System.err:     at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:124)
08-22 10:49:23.750 13213-22929/com.mogujie.im.sdk.demo W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
08-22 10:49:23.750 13213-22929/com.mogujie.im.sdk.demo W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
08-22 10:49:23.750 13213-22929/com.mogujie.im.sdk.demo W/System.err:     at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:170)
08-22 10:49:23.750 13213-22929/com.mogujie.im.sdk.demo W/System.err:     at okhttp3.RealCall.access$100(RealCall.java:33)
08-22 10:49:23.750 13213-22929/com.mogujie.im.sdk.demo W/System.err:     at okhttp3.RealCall$AsyncCall.execute(RealCall.java:120)
08-22 10:49:23.750 13213-22929/com.mogujie.im.sdk.demo W/System.err:     at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
08-22 10:49:23.750 13213-22929/com.mogujie.im.sdk.demo W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
08-22 10:49:23.750 13213-22929/com.mogujie.im.sdk.demo W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
08-22 10:49:23.750 13213-22929/com.mogujie.im.sdk.demo W/System.err:     at java.lang.Thread.run(Thread.java:818)
08-22 10:49:23.750 13213-22929/com.mogujie.im.sdk.demo W/System.err: Caused by: java.net.SocketException: Socket closed
08-22 10:49:23.751 13213-22929/com.mogujie.im.sdk.demo W/System.err:     at libcore.io.Posix.sendtoBytes(Native Method)
08-22 10:49:23.751 13213-22929/com.mogujie.im.sdk.demo W/System.err:     at libcore.io.Posix.sendto(Posix.java:211)
08-22 10:49:23.751 13213-22929/com.mogujie.im.sdk.demo W/System.err:     at libcore.io.BlockGuardOs.sendto(BlockGuardOs.java:278)
08-22 10:49:23.751 13213-22929/com.mogujie.im.sdk.demo W/System.err:     at libcore.io.IoBridge.sendto(IoBridge.java:509)
08-22 10:49:23.751 13213-22929/com.mogujie.im.sdk.demo W/System.err:     at java.net.PlainSocketImpl.write(PlainSocketImpl.java:500)
08-22 10:49:23.751 13213-22929/com.mogujie.im.sdk.demo W/System.err:     at java.net.PlainSocketImpl.-wrap1(PlainSocketImpl.java)
08-22 10:49:23.751 13213-22929/com.mogujie.im.sdk.demo W/System.err:     at java.net.PlainSocketImpl$PlainSocketOutputStream.write(PlainSocketImpl.java:266)
08-22 10:49:23.751 13213-22929/com.mogujie.im.sdk.demo W/System.err:     at okio.Okio$1.write(Okio.java:78)
08-22 10:49:23.751 13213-22929/com.mogujie.im.sdk.demo W/System.err:     at okio.AsyncTimeout$1.write(AsyncTimeout.java:180)
08-22 10:49:23.751 13213-22929/com.mogujie.im.sdk.demo W/System.err: 	... 28 more
08-22 10:49:23.752 13213-22929/com.mogujie.im.sdk.demo W/System.err: java.net.SocketException: sendto failed: EBADF (Bad file descriptor)
08-22 10:49:23.752 13213-22929/com.mogujie.im.sdk.demo W/System.err:     at libcore.io.IoBridge.maybeThrowAfterSendto(IoBridge.java:542)
08-22 10:49:23.752 13213-22929/com.mogujie.im.sdk.demo W/System.err:     at libcore.io.IoBridge.sendto(IoBridge.java:511)
08-22 10:49:23.752 13213-22929/com.mogujie.im.sdk.demo W/System.err:     at java.net.PlainSocketImpl.write(PlainSocketImpl.java:500)
08-22 10:49:23.752 13213-22929/com.mogujie.im.sdk.demo W/System.err:     at java.net.PlainSocketImpl.-wrap1(PlainSocketImpl.java)
08-22 10:49:23.752 13213-22929/com.mogujie.im.sdk.demo W/System.err:     at java.net.PlainSocketImpl$PlainSocketOutputStream.write(PlainSocketImpl.java:266)
08-22 10:49:23.752 13213-22929/com.mogujie.im.sdk.demo W/System.err:     at okio.Okio$1.write(Okio.java:78)
08-22 10:49:23.752 13213-22929/com.mogujie.im.sdk.demo W/System.err:     at okio.AsyncTimeout$1.write(AsyncTimeout.java:180)
08-22 10:49:23.752 13213-22929/com.mogujie.im.sdk.demo W/System.err:     at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:171)
08-22 10:49:23.752 13213-22929/com.mogujie.im.sdk.demo W/System.err:     at okio.RealBufferedSink.write(RealBufferedSink.java:41)
08-22 10:49:23.752 13213-22929/com.mogujie.im.sdk.demo W/System.err:     at okhttp3.internal.http.Http1xStream$FixedLengthSink.write(Http1xStream.java:282)
08-22 10:49:23.752 13213-22929/com.mogujie.im.sdk.demo W/System.err:     at okio.RealBufferedSink.close(RealBufferedSink.java:229)
08-22 10:49:23.752 13213-22929/com.mogujie.im.sdk.demo W/System.err:     at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:48)
08-22 10:49:23.752 13213-22929/com.mogujie.im.sdk.demo W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
08-22 10:49:23.752 13213-22929/com.mogujie.im.sdk.demo W/System.err:     at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
08-22 10:49:23.752 13213-22929/com.mogujie.im.sdk.demo W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
08-22 10:49:23.752 13213-22929/com.mogujie.im.sdk.demo W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
08-22 10:49:23.752 13213-22929/com.mogujie.im.sdk.demo W/System.err:     at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:109)
08-22 10:49:23.752 13213-22929/com.mogujie.im.sdk.demo W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
08-22 10:49:23.752 13213-22929/com.mogujie.im.sdk.demo W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
08-22 10:49:23.752 13213-22929/com.mogujie.im.sdk.demo W/System.err:     at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
08-22 10:49:23.752 13213-22929/com.mogujie.im.sdk.demo W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
08-22 10:49:23.753 13213-22929/com.mogujie.im.sdk.demo W/System.err:     at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:124)
08-22 10:49:23.753 13213-22929/com.mogujie.im.sdk.demo W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
08-22 10:49:23.753 13213-22929/com.mogujie.im.sdk.demo W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
08-22 10:49:23.753 13213-22929/com.mogujie.im.sdk.demo W/System.err:     at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:170)
08-22 10:49:23.753 13213-22929/com.mogujie.im.sdk.demo W/System.err:     at okhttp3.RealCall.access$100(RealCall.java:33)
08-22 10:49:23.753 13213-22929/com.mogujie.im.sdk.demo W/System.err:     at okhttp3.RealCall$AsyncCall.execute(RealCall.java:120)
08-22 10:49:23.753 13213-22929/com.mogujie.im.sdk.demo W/System.err:     at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
08-22 10:49:23.753 13213-22929/com.mogujie.im.sdk.demo W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
08-22 10:49:23.753 13213-22929/com.mogujie.im.sdk.demo W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
08-22 10:49:23.753 13213-22929/com.mogujie.im.sdk.demo W/System.err:     at java.lang.Thread.run(Thread.java:818)
08-22 10:49:23.753 13213-22929/com.mogujie.im.sdk.demo W/System.err: Caused by: android.system.ErrnoException: sendto failed: EBADF (Bad file descriptor)
08-22 10:49:23.753 13213-22929/com.mogujie.im.sdk.demo W/System.err:     at libcore.io.Posix.sendtoBytes(Native Method)
08-22 10:49:23.753 13213-22929/com.mogujie.im.sdk.demo W/System.err:     at libcore.io.Posix.sendto(Posix.java:211)
08-22 10:49:23.753 13213-22929/com.mogujie.im.sdk.demo W/System.err:     at libcore.io.BlockGuardOs.sendto(BlockGuardOs.java:278)
08-22 10:49:23.753 13213-22929/com.mogujie.im.sdk.demo W/System.err:     at libcore.io.IoBridge.sendto(IoBridge.java:509)
08-22 10:49:23.753 13213-22929/com.mogujie.im.sdk.demo W/System.err: 	... 29 more

**Comment by HarrisonLin** [comment]
I try set TimeOut 100 SECONDS ,  300KB below Image upload success. 

I think timeout cause upload faild
