### ISSUE TITLE
Log based on url in okhttp-logging-interceptor

### ISSUE THREAD

**Issue by entertainyou** [square/okhttp#2799]
What kind of issue is this?

 - [ ] Question. This issue tracker is not the place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use Stack
       Overflow. https://stackoverflow.com/questions/tagged/okhttp

 - [ ] Bug report. If you’ve found a bug, spend the time to write a failing test. Bugs with tests
       get fixed. Here’s an example: https://gist.github.com/swankjesse/981fcae102f513eb13ed

 - [X] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
       already exists! Don’t send pull requests to implement new features without first getting our
       support. Sometimes we leave features out on purpose to keep the project small.

I have a project which uses one okhttp client for all the request, I'd like okhttp-logging-interceptor to log only part of the requests(based on url)

**Comment by JakeWharton** [comment]
You can do this with your own interceptor. Use our logging-interceptor code as a starting point and customize it so suit your specific requirements.
