### ISSUE TITLE
SocketTimeoutException should specify if it was a read or a write

### ISSUE THREAD

**Issue by andymacau853** [square/okhttp#2801]
I found that if I set write or read timeout in order to test the exception, the exception string can not know read or write which is, it only shows java.net.SocketTimeoutException: timeout, please see the code here:
https://gist.github.com/andymacau853/80674d77a6e121a5efdfb2fe1d220ea2

Why I am ask the question? because if a connection timed out, it shows "connect timed out" in order to know what exception is...

**Comment by swankjesse** [comment]
Not much I’m eager to do here. Especially with HTTP/2 there’s not much value to the application developer in knowing which kind of timeout it was.

**Comment by andymacau853** [comment]
I think this is eager to do here, because timeout is important!!!
