### ISSUE TITLE
Permission Denied, it happens again. Same is to the question of the #2775.

### ISSUE THREAD

**Issue by maoaixianyu** [square/okhttp#2803]
I do something as your follow, but it happens again in our users and make a bad User Experience. I want to reopen the issue for #2775. But i have no access. So please give me another method for this question. I really need your help. Please. I upload my "AndroidManifest.xml". The permission in my application is still exiting.
![qq20160820-0](https://cloud.githubusercontent.com/assets/17868022/17828473/6420d7da-66c5-11e6-9579-0c994e0e3271.png)

**Comment by swankjesse** [comment]
I don't know what action we can take here. Seems like a hostile device that has revoked permission despite your manifest.

**Comment by carlyonj** [comment]
It would be convenient, as a consumer of OkHTTP, if the library handled the crash for us.

**Comment by swankjesse** [comment]
Handled it how?
