### ISSUE TITLE
unreasonable Thread Usage.

### ISSUE THREAD

**Issue by mojtabye** [square/okhttp#2805]
Hi there ! , 
i am wondering why okhttp create new threads even when i use it Synchronous.
here is my sample code :
```
//Thread.activeCount() return 1

OkHttpClient client = new OkHttpClient();

//this line create 2 new threads but why ? , what's wrong with using current thread ?!
Response response = client.newCall(new Request.Builder().url("https://google.com").get().build()).execute();
```

**Comment by swankjesse** [comment]
It’s explained here. No plans to change that.
https://github.com/square/okhttp/wiki/Concurrency

**Comment by swankjesse** [comment]
I don’t think that design will work. If you’d like to write some code to find an alternative, please do! But I suspect it’s not possible without going fully async like Netty.

**Comment by mojtabye** [comment]
this is what i found in [kevinsawicki/http-request](https://github.com/kevinsawicki/http-request#perform-a-get-request-and-get-the-body-of-the-response)  and just working without creating new thread !
```
String response = HttpRequest.get("http://google.com").body();
System.out.println("Response was: " + response);
```

of course `http-request` author knows about concurrency ([link](https://github.com/kevinsawicki/http-request#are-requests-asynchronous)), but using threads is the responsibility of the user.

we will happy to access okhttp basic methods ;)

**Comment by swankjesse** [comment]
Yeah, but that library doesn’t use HTTP/2. OkHttp only spins up another thread for HTTP/2.
