### ISSUE TITLE
Crashes while using websocket

### ISSUE THREAD

**Issue by sohailbud** [square/okhttp#2807]
Attached is the crash report. Not able to reproduce the crash.

[com.sense.androidclient_issue_64_crash_57b7605203b800013b7a6aef5b38d9eb.1 (1).txt](https://github.com/square/okhttp/files/430441/com.sense.androidclient_issue_64_crash_57b7605203b800013b7a6aef5b38d9eb.1.1.txt)

**Comment by JakeWharton** [comment]
Looks like your server is sending a malformed close payload with a body size that exceeds what the spec allows.

**Comment by sohailbud** [comment]
Thanks for your feedback. Any idea where I would catch this exception so app doesn't crashes? Would like to see what is being send from server but not able to reproduce the error.

**Comment by sohailbud** [comment]
Actually never mind, looks like I was sending a stacktrace as a reason for disconnecting the socket back to server which exceeded the 125 max size. Thank you!

**Comment by gauravsak** [comment]
@JakeWharton Could you please mark this issue as resolved? Thanks
