### ISSUE TITLE
ConnectionPool and enabling WiFi while downloading on 3/4G

### ISSUE THREAD

**Issue by llooz** [square/okhttp#2810]
I have noticed that if i start to read a response body (e.g. a 100MB file) while on a 3g connection and turn on WiFi it keeps downloading without dropping the connection.
I have done some research but everyone says that the connection will drop because the IP changes but i suppose that the device keeps both networks active and use the preferred one only for new tcp connections. I'm on a Nexus 5X with Android 6.0.1.

I'm thinking to restart the download (using Range, Last-Modified and ETag) when i notice this kind of connection change but i'm wondering if i should also ensure to evict all connections from the ConnectionPool.

**Comment by swankjesse** [comment]
Yeah, unfortunately OkHttp isn’t generally aware of user preferences for which networks to use. Doing this might be possible, but might also add substantial complexity – what callback should we report?

I think it might be worthwhile to build a helper thing like a “LargeResourceDownloader” that may make make multiple OkHttp requests to return a response. (And support stateful resumes across app relaunches, etc.)

**Comment by swankjesse** [comment]
No action for us to take on this.
