### ISSUE TITLE
[FR: Logging Interceptor] Add ability to print all request/response data at once

### ISSUE THREAD

**Issue by petromir** [square/okhttp#2813]
I saw that current implemetation of `HttpLoggingInterceptor` prints every line separately, which makes tracing quite difficult when you do many simultaneous requests.

It would be nice if we have the option to print the request/response data at once.

**Comment by JakeWharton** [comment]
If you need logging facilities beyond what the provided one exposes, we recommend you copy its sources and modify it to suit your needs. We can't provide something that works for 100% of uses and requirements because there's so many crazy permutations.

**Comment by petromir** [comment]
What about pull request?

**Comment by JakeWharton** [comment]
Something like this requires exposing options in the API which is what we don't want to add.

**Comment by petromir** [comment]
Or it can be entirely new class...

**Comment by JakeWharton** [comment]
That seems worse than an option. Your best bet is to create your own interceptor.

**Comment by petromir** [comment]
Got it. Contributions are not welcomed.

**Comment by swankjesse** [comment]
GitHub’s closed pull requests page will show you which kinds of contributions are welcomed. This video attempts to explain why:
http://youtu.be/PCxz2LEmuL4

**Comment by petromir** [comment]
Please be more direct!
If you have any special rules for PRs, make them public here https://github.com/square/okhttp/wiki/Contributing or even in your issue template.
Thanks!
