### ISSUE TITLE
[FR: Logging Interceptor] Add ability to hook into specific parts of request/response data

### ISSUE THREAD

**Issue by petromir** [square/okhttp#2814]
Currently if I want to secure some data in the request/response body, the only option is to provide my own implementation of `HttpLoggingInterceptor.Logger` which will receive all request/response data, not only the body.

I would like to have an option to hook some logic only when the body is printed.

**Comment by JakeWharton** [comment]
Similar to [my other response][1], writing your own interceptor gives you access to anything and everything that you need to write customized logging. The logging interceptor that we provide isn't meant to be exhaustive, merely cover 90% of people's needs. You can use it as a good starting point for creating your own.

 [1]: https://github.com/square/okhttp/issues/2813#issuecomment-242827602

**Comment by petromir** [comment]
What about pull request?
