### ISSUE TITLE
GSON error and issue with Async request .enqueue(new Callback())

### ISSUE THREAD

**Issue by neobie** [square/okhttp#2817]
This is totally a disaster.
Just started my first day of OkHttp and found out it is not working as expected.

I tried to call Async request with 

```
client.newCall(request).enqueue(new Callback())
```

To my surprise, the Gson.fromJSON does not work with either charStream() or string():
`ResponseDataRecentFinancialReports responseData = gson.fromJson(response.body().charStream(), ResponseDataRecentFinancialReports.class);`
or
`ResponseDataRecentFinancialReports responseData = gson.fromJson(response.body().string(), ResponseDataRecentFinancialReports.class);`

By using string(), the responseData is null. By using charStream(), it throws JsonSyntaxException.

I try to play around by using Sync Request with:
`Response response = client.newCall(request).execute();`
and now to my surprise, the GSON is working just fine! I wonder what's wrong with the Async .enqueue(new Callback()) which make the GSON not working? I did manually copy and paste the String in 
`public void onResponse(Call call, final Response response) throws IOException {`
and it is working fine. There must be something wrong with the Response / onResponse method?

Below are the two models for references:
```
public class ResponseDataRecentFinancialReports {
		public List<RecentFinancialReportModel> data;
	}

public class RecentFinancialReportModel {

	public String name;
}

```

**Comment by swankjesse** [comment]
You're getting an empty response body. Please ask future questions on StackOverflow Overflow.

**Comment by neobie** [comment]
Sorry, jesse, not an empty response. I manage to Log.i and display the response body. Please  dont make assumptions of your own. Thank you.

**Comment by JakeWharton** [comment]
If you're logging the body then you're also consuming it and it cannot be consumed twice. That's why the second call to `.string()` or the call to `.charStream()` seems empty.
