### ISSUE TITLE
Caching of 301 Responses

### ISSUE THREAD

**Issue by GokhanArik** [square/okhttp#2821]
Hi guys,

I'm using **okhttp3** with **Picasso** and my images are not cached if they are accessed from redirected URIs. 

It looks like **Okhttp** is caching initial call and redirect URI separately. When I turn off wifi and data, `Okhttp` is looking for URL of the first call and comparing it with the request. `get` method of  `Cache` class is where the cached data is being ignored.

```
    Response response = entry.response(snapshot);

    if (!entry.matches(request, response)) {
      Util.closeQuietly(response.body());
      return null;
    }
```

I'm not sure if it is a bug or it is by design. If it is not bug, I would like to hear your advises to solve this problem.

Thanks

**Comment by swankjesse** [comment]
OkHttp caches 301s. Could you provide an executable test case to demonstrate the problem?

**Comment by GokhanArik** [comment]
@swankjesse I created a sample project, I tried to keep it similar to code base I have in my project.
Open the app, hit Download button when you are online. It will show the image. Kill the app, turn off data/wifi and then try it. It won't show the image. The image URL is not the one I'm using, this image is from FB but afaik it also returns 301.

https://github.com/GokhanArik/OkhttpCacheTest

**Comment by swankjesse** [comment]
Yep. For me the Facebook image redirects with a 302. That redirect isn’t cached but the followup image is. You can hack a very dangerous, very bad interceptor to force a 301 and see that that caches completely.

https://gist.github.com/swankjesse/1d3ef753ae38d0fcea910cfa137b60a4

**Comment by GokhanArik** [comment]
When I run your code I see that it is being cached. However, I still can't get it working in my project. I don't see the image when I'm offline. And I saw few people reporting the same issue before. I updated the URL if you want to check it again. This image doesn't prevent caching.

**Comment by GokhanArik** [comment]
And here is the video of the behavior. 

https://www.youtube.com/watch?v=ZMIzu-tuJGk

**Comment by swankjesse** [comment]
No action for us to take on this. You might have to do your own response header rewriting to get caching to work.
