### ISSUE TITLE
Display plain text request data in Multipart/form-data request, instead of byte gibberish with interceptor

### ISSUE THREAD

**Issue by eric-townsquared** [square/okhttp#2824]
With an interceptor one can typically see the plain text information in requests, but in Multipart/form-data post requests, that data is turned into byte data and not displayed in a meaningful or debuggable way, in the case that a server doesn't like the data format in the request

http://stackoverflow.com/questions/38563394/okhttp-loggin-interceptor-in-multipart

**Comment by swankjesse** [comment]
Thanks for asking on StackOverflow. Opening an issue here isn’t necessary.

**Comment by eric-townsquared** [comment]
@swankjesse I didn't ask that question, I found the same issue already posted on stackoverflow in the past.
