### ISSUE TITLE
Enable non-strict Multipart Form types, such as Browser_Compatibility

### ISSUE THREAD

**Issue by eric-townsquared** [square/okhttp#2828]
The bug is that there is no way to enable non-strict Multipart Form types, such as Browser Compatibility that the Apache Http Entity has.

"browser-compatible mode, i.e. only write Content-Disposition; use content charset"

Some browsers send only that header in multipart form parts.

OkHttp currently has a variety of FORM types, and they add multiple headers to separate form parts, which cannot be removed with a Reque (since the interceptor only removes top level request headers)

**Comment by swankjesse** [comment]
What’s a Reque?

**Comment by swankjesse** [comment]
Note that you’re free to build your own `RequestBody` instances that do whatever you want. We offer some built-in ones for common cases, but if you wanna do something fancy you can encode your own bytes however you like. Heck, you can even get Apache’s HTTP entity to help you write your RequestBody.

**Comment by swankjesse** [comment]
We’re trying to follow the standards. You might ask the Reque server to support ’em too!

In the interim my best advice here is to copy-paste our standalone FormBody class into your project and customize it to your liking.
