### ISSUE TITLE
[Request] Add visible proguard rules to Gtihub pages

### ISSUE THREAD

**Issue by jaredsburrows** [square/okhttp#2829]
Similar to [Retrofit's](http://square.github.io/retrofit/) page, can we add [OkHTTP's](http://square.github.io/okhttp/) page as well from here https://github.com/square/okhttp/issues/2230?

**Comment by swankjesse** [comment]
As OkHttp doesn’t really use reflection I think our ProGuard configuration would be trivial. But we could call that out.

**Comment by gengjiawen** [comment]
We can add proguard section saying that proguard won't be neccessary in Readme.
But I don't think extra proguard rules will be needed.

**Comment by swankjesse** [comment]
https://github.com/square/okhttp/commit/87b86a53c4a5c591b8e1c5ec94b4d81edece00a8
