### ISSUE TITLE
ART fails with Method processed more than once: : void okhttp3.ConnectionPool$1.run()

### ISSUE THREAD

**Issue by smedic** [square/okhttp#2836]
I have a problem with OkHttp sync calls.

Structure is the following: 
1. create new thread 
2. in new thread, send a few http get and post calls, and read data from database according to the received parameters. 
3. Send multiple post requests one by one

This sequence fails at random place in 3rd step. I get a big tombstone with information which is not quite useful. 
Only thing I find useful is this: 
**art : Method processed more than once: void okhttp3.ConnectionPool$1.run()**

In the first place, I made just one OkHttpClient, and was making calls on this client. Later I changed this, so every newCall has its own client object.

What is the issue here? I am doing everything on a new thread, calls are synchronized and executed one by one.

I have also tried to check if call isExecuted already, but this method call is always false...

Any ideas?

**Comment by smedic** [comment]
I switched from 3.4.1 to 3.3.0 and errors when sending short requests disappeared.
But, when sending images, for example, it fails again with the error described above... 
Strange. Am I making some architecture mistake?

**Comment by swankjesse** [comment]
It looks like you’re triggering a bug in Art somehow. Are you using ProGuard?

**Comment by swankjesse** [comment]
The “more than once” error might be unrelated. Seems like a benign warning.
https://android.googlesource.com/platform/art/+/master/compiler/dex/verification_results.cc

**Comment by swankjesse** [comment]
... or maybe the error recovery in that method isn’t very good. If that’s the case you’ve somehow found a way to get the Dex verifier in an unexpected state.

**Comment by smedic** [comment]
No, ProGuard has default settings.
I don't know what could cause this, because I am using many libraries and everything works fine.
Maybe I should use older version in order to check further.
What do you suggest?
Obviously, newest lib behaves worse on my device.

**Comment by swankjesse** [comment]
If you could isolate the problem, that’ll help. As is there isn’t anything we can act on here.

**Comment by swankjesse** [comment]
Also, might be worthwhile to confirm that this problem exists on multiple Android versions. If it’s a problem with a specific device, that’s a clue.

**Comment by smedic** [comment]
Problem exists only on my tablet Asus ZenPad and Android 6.0. Target version is 22. 
On 3.3.0, it fails only in a situation when transferring large files. On 3.4.1 it fails in every situation, at random places.
On Galaxy S7, it works good. 
I spent whole day debugging your library, but it seems okay(http). 
Thank you for your fast feedback. 
That is a way to ensure people that you are working good :)

**Comment by steelbytes** [comment]
I'm seeing this on android 6.0.1 with 3.10 - probably an art bug in marshmallow

**Comment by nicai1900** [comment]
> I'm seeing this on android 6.0.1 with 3.10 - probably an art bug in marshmallow

I had the same problem
