### ISSUE TITLE
How to config alpn-boot to support HTTP/2 ?

### ISSUE THREAD

**Issue by KenChoi1992** [square/okhttp#2837]
I'm using OkHttp in my maven project, my server is supports Http/2, however, when I post a request, the console log this info:
```
ALPN callback dropped: SPDY and HTTP/2 are disabled. Is alpn-boot on the boot class path?
```
And the protocol trun out http/1.1 here is my log:
```
16/09/05 15:16:36 DEBUG connection.Http2Client: Response protocol:http/1.1
16/09/05 15:16:36 DEBUG connection.Http2Client: Succeed to get response OK - response body: {"sendno":"1870235218","msg_id":"1561031000"}
```
I tried add this dependency in pom file:
```
<dependency>
			<groupId>org.mortbay.jetty.alpn</groupId>
			<artifactId>alpn-boot</artifactId>
			<version>8.1.9.v20160720</version>
			<scope>runtime</scope>
		</dependency>
```
And the version is completely match my JDK version, but it didn't work. Then I tried run this command:
```
java -Xbootclasspath/p:libs/alpn-boot-8.1.9.v20160720.jar
```
Nothing happened, then I tried to change the path to absolute path , still didn't work. I wonder if anyone encounter this problem like me? I would be very appreciate if someone can offer help.

**Comment by swankjesse** [comment]
This is what I use on Java 8:
```
-Xbootclasspath/p:/Users/jwilson/.m2/repository/org/mortbay/jetty/alpn/alpn-boot/8.1.2.v20141202/alpn-boot-8.1.2.v20141202.jar
```

**Comment by KenChoi1992** [comment]
@swankjesse Do you mean run this command on CMD tool or write this into pom file ? Please tell me in detail. Thanks a lot !

**Comment by swankjesse** [comment]
This is the argument passed to `java`. If you want to see what to do for a `pom.xml` file you can look at OkHttp’s `pom.xml`.

**Comment by KenChoi1992** [comment]
@swankjesse  Thanks a lot. After adding profiles and properties entries, the log didn't show anymore. How ever, the response protocol is still http/1.1.

**Comment by swankjesse** [comment]
@KenChoi1992 does the server you’re hitting support HTTP/2 ?

**Comment by KenChoi1992** [comment]
@swankjesse Yes, my workmate confirms that our server is supports HTTP/2. Is there any method to see what HTTP protocol that request is using ?

**Comment by swankjesse** [comment]
Consider fetching say `https://google.com/` to confirm that your client is working.

**Comment by KenChoi1992** [comment]
@swankjesse  I tried GET method fetch google. Here is my code:
```
Proxy proxy = new Proxy(Proxy.Type.HTTP, new InetSocketAddress("host", "port"));
        OkHttpClient.Builder builder = new OkHttpClient.Builder()
                .proxy(proxy);
        OkHttpClient client = builder.build();
        Request request = new Request.Builder().url("https://google.com/").build();
        try {
            Response response = client.newCall(request).execute();
            LOG.debug("Response protocol:" + response.protocol());
            LOG.debug("Succeed to get response - response body: " + response.body().string());
        } catch (IOException e) {
            e.printStackTrace();
        }
```
And the log is 
```
16/09/06 11:43:55 DEBUG connection.Http2Client: Response protocol:http/1.1
16/09/06 11:43:58 DEBUG connection.Http2Client: Succeed to get response - response body: <!doctype html><html itemscope="" itemtype="http://schema.org/WebPage" lang="ja"><head>...<meta content="noodp" name="robots"><meta content="text/html; charset=UTF-8" http-equiv="Content-Type"><meta content="/images/branding/googleg/1x/googleg_standard_color_128dp.png" itemprop="image"><title>Google</title>...</div></body></html>

Process finished with exit code 0

```

**Comment by KenChoi1992** [comment]
@swankjesse I am using IntelJ IDEA, and before run test, there is a Run/Debug Configurations, it provides VM options:
![](https://cloud.githubusercontent.com/assets/8196928/18265500/a115ef8c-7448-11e6-95d1-7de302d48ba6.png)
Seems my JDK version isn't match the alpn-boot's version, I know [here](https://www.eclipse.org/jetty/documentation/9.3.x/alpn-chapter.html) is a table you can find relationship between OpenJDK's version and alpn-boot's version, but I'm using OracleJDK, which version is 1.8.0_102, I wonder what's your JDK's version? Is JDK's version or alpn-boot's version that cause the problem ?

**Comment by swankjesse** [comment]
They need to match. Thats all I know.

**Comment by KenChoi1992** [comment]
@swankjesse Thanks for reply, I'm not sure whether specific JDK's version and alpn-boot's version that can work or not. I'm closing this issue, because I haven't find a better way to confirm that. Anyway, I admire your attitude, thank you again.
