### ISSUE TITLE
Header whitespace rules don't match RFC 7230 section 3.2 

### ISSUE THREAD

**Issue by 15characterlimi** [square/okhttp#2842]
This is a bug report.

Failing test: https://gist.github.com/15characterlimi/9704ec432a6e95b57611208e5c3ddc11

RFC 7230 3.2 allows ' ' and '\t' in headers, but only inside values and only one consecutive whitespace character.

OkHttp however currently allows any sequence of ' ' not only in values but also in keys. This is too lenient. I don't know if this leniency is deliberate.

OkHttp doesn't currently accept '\t' at all, which is too strict, but PR https://github.com/square/okhttp/pull/2841 proposes to allow '\t' in values.

**Comment by swankjesse** [comment]
I’ve added code to forbid spaces in keys. I don’t think forbidding multiple spaces is worth the effort. Thanks for reporting this!
