### ISSUE TITLE
<-- HTTP FAILED: java.net.SocketException: sendto failed: EBADF (Bad file number)

### ISSUE THREAD

**Issue by yunair** [square/okhttp#2844]
I can not provide a test case that every time can produce it. 
Because in my case, It produces randomly.

**Comment by swankjesse** [comment]
Not much we can do without a failing test unfortunately. Can you please describe which environment you’ve seen this error? Perhaps with a stacktrace? We’ve fixed errors similar to this one before and it’ll be handy to help correlate.

**Comment by yunair** [comment]
In my interceptor code, the stacktrace line is point to chain.process(request).
Is This enough?

![image](https://cloud.githubusercontent.com/assets/4322540/18377023/af010e06-7696-11e6-98d5-72ecc0c56286.png)
![image](https://cloud.githubusercontent.com/assets/4322540/18377029/c8e3938e-7696-11e6-9f3b-b220dab05df4.png)
![image](https://cloud.githubusercontent.com/assets/4322540/18377038/d58123b8-7696-11e6-8ad2-a44863a9604c.png)

**Comment by yunair** [comment]
I want to say what I meet.I use Retrofit to send request, but I need to change request and response. So In interceptor, my code like below

~~~ java

final Request request = chain.request();
final Request newReq = generateRequest(request);

// code below is recursion
Response reponse = chain.process(newReq);
if(response == 200){
  // check response has valid token
  if(checkResponseValid(response)){
     return response;
  }else{
     requestServer to get new Token;
     Request newTokenReq = change request with new Token;
     // recursion this code to check new is valid, next will execute chain.process(newTokenReq)
  }
  
}else{
  return response;
}
