### ISSUE TITLE
cannot deal with request body by Interceptors when upload files & parameters by MultipartBody

### ISSUE THREAD

**Issue by kaikai5545** [square/okhttp#2845]
What kind of issue is this?

 - [ ] Feature Request. 

1. function: upload files & paramters, but need encrypt the request body(just string parameters), so I try to use interceptors to solve it.

2. but I have no idea how to separate the (from)request body(not files) from "public Response intercept(Chain chain)",  it can get the Parts list from request, but cann't get every request body from part.

**Comment by swankjesse** [comment]
Are you asking for a mechanism to parse Multipart request bodies?

**Comment by JakeWharton** [comment]
We expose the parts, so seems like you just need to cast `RequestBody` to `MultipartBody` for access to them.

**Comment by kaikai5545** [comment]
YES, I really did as you said, case RequestBody to MultipartBody, and get Parts from MultipartBody, but look at the Part Class, just has createFormData() methods, no method to get body or header, so I have to get the body & header by reflect the Part Object. that's not a good method I think. so will you add some  get method to get the body directly from part.

**Comment by kaikai5545** [comment]
for (MultipartBody.Part part : ((MultipartBody) requestBody).parts()) {
            Class tmp = part.getClass();
            Field body, headers;
            try {
                body = tmp.getDeclaredField("body");
                body.setAccessible(true);
                body1 = (RequestBody) body.get(part);
                Buffer buffer = new Buffer();
                body1.writeTo(buffer);
                if (HttpLoggingInterceptor.isPlaintext(buffer)) {
                    String msg = buffer.readString(charset);
                    System.out.println("msg = " + msg);
                }

**Comment by JakeWharton** [comment]
Ok. That's just an oversight.
