### ISSUE TITLE
okhttp have a crash ( signal 11 (SIGSEGV), code 1 (SEGV_MAPERR))

### ISSUE THREAD

**Issue by zt000000** [square/okhttp#2847]
we use okhttp in our App.  When we use Monkey test tools on the App, sometimes found crash.
 could you give us reason and solution for this issue? Thanks a lot.

the log is :
// CRASH: cn..debug (pid 5085)

// Short Msg: Native crash

// Long Msg: Native crash: Segmentation fault

// Build Label: Huawei/H60-L03/hwH60:4.4.2/HDH60-L03/CHNC00B613:user/ota-rel-keys,release-keys

// Build Changelist: CHNC00B613

// Build Time: 1416480470000

// *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***

// Build fingerprint: 'Huawei/H60-L03/hwH60:4.4.2/HDH60-L03/CHNC00B613:user/ota-rel-keys,release-keys'

// Revision: '0'

// pid: 5085, tid: 8238, name: OkHttp Dispatch  >>> cn.debug <<<

// signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 00000008

//     r0 00000000  r1 43e4aae0  r2 7bc4fae8  r3 43e4aae0

//     r4 7ab49a18  r5 43e4aae0  r6 7bc4fae8  r7 7acf9c88

//     r8 7bc4fb10  r9 7acf9c78  sl 790cb3d8  fp 7bc4fb24

//     ip 71a46d18  sp 7bc4fac8  lr 40ab78b7  pc 40ab78ce  cpsr 00070030

//     d0  4332424145323746  d1  3134323639353734

//     d2  3942343344323231  d3  3745353338443030

//     d4  0000000000000000  d5  0000002400000000

//     d6  4082040c45e9e258  d7  45e9e2587ab49a88

//     d8  3f8000003f800000  d9  434d46b0443ac000

//     d10 3f03333444618000  d11 4076800000000000

//     d12 bfdc0e45dabe05ca  d13 c068eeaf13e3de25

//     d14 408663abc4f8f789  d15 0000000000000000

//     d16 0000000000000000  d17 0000000000000000

//     d18 0000000000000000  d19 5c5c5c5c5c5c5c5c

//     d20 7f01023a00000002  d21 7f0b01be01000008

//     d22 7f01023b00000002  d23 7f0b01bc01000008

//     d24 000000007ab244c1  d25 0000000000000000

//     d26 0000000000000017  d27 0000000000000001

//     d28 3ff0000000000000  d29 0000000000000001

//     d30 0000000000000001  d31 000000007ab24600

//     scr 68000013

// 

// backtrace:

//     #00  pc 000798ce  /system/lib/libcrypto.so (EVP_DigestFinal_ex+9)

//     #01  pc 000798b3  /system/lib/libcrypto.so (EVP_DigestFinal+6)

//     #02  pc 00008f8b  /system/lib/libjavacrypto.so

//     #03  pc 0001eb8c  /system/lib/libdvm.so (dvmPlatformInvoke+112)

//     #04  pc 0004f253  /system/lib/libdvm.so (dvmCallJNIMethod(unsigned int const*, JValue*, Method const*, Thread*)+398)

//     #05  pc 00027fa0  /system/lib/libdvm.so

//     #06  pc 0002f110  /system/lib/libdvm.so (dvmMterpStd(Thread*)+76)

//     #07  pc 0002c774  /system/lib/libdvm.so (dvmInterpret(Thread*, Method const*, JValue*)+184)

//     #08  pc 00061705  /system/lib/libdvm.so (dvmCallMethodV(Thread*, Method const*, Object*, bool, JValue*, std::__va_list)+336)

//     #09  pc 00061729  /system/lib/libdvm.so (dvmCallMethod(Thread*, Method const*, Object*, JValue*, ...)+20)

//     #10  pc 00056423  /system/lib/libdvm.so

//     #11  pc 0000d408  /system/lib/libc.so (__thread_entry+72)

//     #12  pc 0000d5a0  /system/lib/libc.so (pthread_create+240)

// 

// code around pc:

//     40ab78ac 4830e92d f0004604 4605f807 f0004620  

//     40ab78bc 4628f837 8830e8bd 4604b570 6820460d  

//     40ab78cc 68814616 db0a2941 48134912 44794a13  

//     40ab78dc 440a4408 110ff240 fa18f7e4 69826820  

//     40ab78ec 46294620 46054790 bf1e2e00 68806820  

//     40ab78fc 68206030 b1316a01 47884620 21024620  

//     40ab790c fc38f003 6c416820 68e02200 ef22f7b8  

//     40ab791c bd704628 0006a586 fffda0e8 fffda10d  

//     40ab792c 4604b510 b1f86820 b1406a00 21024620  

//     40ab793c fc2af003 6820b918 46206a01 68204788  

//     40ab794c 6c40b190 bf1c2800 280068e0 4620d00c  

//     40ab795c f0032104 b938fc19 68e06821 f00a6c49  

//     40ab796c 68e0f837 ffdaf009 28006920 f006bf18  

//     40ab797c 6860faff bf182800 ff96f7fa 0050efc0  

//     40ab798c f9442000 f8440a8f 60600f10 bd102001  

//     40ab799c 4800e92d 0050efc0 46032200 0a8ff940  

// 

// code around lr:

//     40ab7894 0006a63c 0006a5ec 0006a696 4800e92d  

//     40ab78a4 47986943 8800e8bd 4830e92d f0004604  

//     40ab78b4 4605f807 f0004620 4628f837 8830e8bd  

//     40ab78c4 4604b570 6820460d 68814616 db0a2941  

//     40ab78d4 48134912 44794a13 440a4408 110ff240  

//     40ab78e4 fa18f7e4 69826820 46294620 46054790  

//     40ab78f4 bf1e2e00 68806820 68206030 b1316a01  

//     40ab7904 47884620 21024620 fc38f003 6c416820  

//     40ab7914 68e02200 ef22f7b8 bd704628 0006a586  

//     40ab7924 fffda0e8 fffda10d 4604b510 b1f86820  

//     40ab7934 b1406a00 21024620 fc2af003 6820b918  

//     40ab7944 46206a01 68204788 6c40b190 bf1c2800  

//     40ab7954 280068e0 4620d00c f0032104 b938fc19  

//     40ab7964 68e06821 f00a6c49 68e0f837 ffdaf009  

//     40ab7974 28006920 f006bf18 6860faff bf182800  

//     40ab7984 ff96f7fa 0050efc0 f9442000 f8440a8f  

// 

** Monkey aborted due to error.

**Comment by zt000000** [comment]
The okttp version is 3.2.0, App is android App. Thanks

**Comment by swankjesse** [comment]
It's likely a bug in your device’s SSL code. OkHttp uses that code but we aren't able to fix bugs in it. Consider reporting this to the device's manufacturer.

Also- if you can reliably reproduce this that'd be helpful to find out if it impacts other devices.

**Comment by swankjesse** [comment]
No action for us to take here.
