### ISSUE TITLE
Weird issue - DELETE calls fail with Akamai H2 (http/2) enabled 

### ISSUE THREAD

**Issue by jkane001** [square/okhttp#2851]
I have 2 Android apps which use Retrofit 2, with the latest version of okhttp. Last week, we enabled http/2 on our API, at the Akamai control panel. That same day, we started getting complaints that users could no longer do certain things in the apps,  and it quickly became apparent that it was only Android apps, and only DELETE calls

**Comment by swankjesse** [comment]
Definitely weird. Can you give us more to go on? Perhaps use Charles to record what OkHttp did and how that differs from what it should do?

**Comment by jkane001** [comment]
Sorry, hit the submit button accidentally.  Finishing my thought :

Only DELETE calls are failing.  We tested turning  off H2 support, and all was well again, and turned it back on,  and is failing again. 

What can I do to help troubleshoot this issue?

**Comment by swankjesse** [comment]
Charles is worth the money and can help you to diagnose HTTP/2 problems.
https://www.charlesproxy.com/

You can also use a tool like WireShark to make DELETE requests in other HTTP/2 clients and show how OkHttp’s requests aren’t as expected.

My guess though is that it’s probably an issue with the server and not the client, and your workaround will be to disable HTTP/2 until they fix their kit.

**Comment by jkane001** [comment]
Calls aren't making it to the server  -  IIS logs allow that. Call never makes it out of Akamai to us. But only deletes. I'll see if I can figure out Wireshark and Charles, but I think there may be a bug in  okhttp causing it.

**Comment by jkane001** [comment]
That should read : IIS logs prove that.

**Comment by jkane001** [comment]
@swankjesse - I've used Charles to compare the request being made by our iOS app (which does work fine making a DELETE call through Akamai) & our Android app (which fails the same call). There were some headers missing, and on a lark, I manually added "content-length: 0" to the DELETE request, and sure enough, it started working. 

I can't fine anything in the http/2 spec that says that a DELETE request MUST have a content-length, so I'm not sure if okhttp is wrong or Akamai is.

Thoughts?

**Comment by swankjesse** [comment]
I’m curious – how are you specifying the `DELETE` method? `DELETE` is special in OkHttp because we permit a request body but don’t require it.

It’s possible we could fix this by changing this line in `Http2Codec.writeRequestHeaders()`:
```
    boolean permitsRequestBody = HttpMethod.permitsRequestBody(request.method());
```
to this:
```
    boolean hasRequestBody = request.body() != null;
```

**Comment by jkane001** [comment]
@DELETE(PATH)
Call<Things> deleteThing(@Query("UserId") String userId, @Query("ThingId") long thingId);

No body, 2 QS params and a couple custom headers ("ApiKey" and "Cache-Control", "public, max-age=9600")

**Comment by jkane001** [comment]
Sorry, I should add that this is using Retrofit2

**Comment by hjudez** [comment]
Same issue here, now that we enabled Akamai with HTTP2.

**Comment by jkane001** [comment]
@hjudez I have fixed it temporarily in my project by adding this to an existing interceptor:

```
if (request.method().equals("DELETE"))
{
    updatedRequestBuilder.header("content-length", "0");
}
```

**Comment by hjudez** [comment]
@jkane001 looks like a good fix. Thanks! We've disabled http2 for now but I guess I'll try you suggestion in case back-end enables http2 again.

**Comment by rfc2822** [comment]
Probably the same problem as #2892?

**Comment by dave-r12** [comment]
Can anyone with this issue confirm whether the latest snapshot fixes the issue (without the interceptor)? Or if you can provide a test URL I'm also happy to test. I'd like to see if #2892 was a possible culprit.

**Comment by swankjesse** [comment]
I’m gonna be optimistic here & assume @dave-r12’s fix fixed!

**Comment by hjudez** [comment]
a little bit late but I can confirm it's been fixed.

**Comment by ericn37** [comment]
in which version it is fixed @hjudez @swankjesse ?

**Comment by JakeWharton** [comment]
The most recent version.

**Comment by ericn37** [comment]
Thanks @JakeWharton , tested and it's working
