### ISSUE TITLE
Implement AutoCloseable in MockWebServer for graceful Shutdown

### ISSUE THREAD

**Issue by marcottedan** [square/okhttp#2854]
Hi,

It would be nice if the MockWebServer could implement Java AutoClosable https://docs.oracle.com/javase/8/docs/api/java/lang/AutoCloseable.html so we can try-with-resource the creation of the MockWebServer and avoid the shutdown method. Also, it would help make the scope of your MockWebServer very clear.

**Comment by JakeWharton** [comment]
No, but we can do `Closable`!

**Comment by marcottedan** [comment]
Hasn't Closeable (Java 1.5) been replaced with AutoCloseable in Java 1.7?

http://stackoverflow.com/questions/13141302/implements-closeable-or-implements-autocloseable/13141382#13141382

**Comment by JakeWharton** [comment]
Yes. We still support 1.6 though.

**Comment by marcottedan** [comment]
I get it, thanks a lot!
