### ISSUE TITLE
Add a reverse proxy option to MockWebServer

### ISSUE THREAD

**Issue by paour** [square/okhttp#2859]
I'd like to include in my tests (which use Robolectric and MockWebServer) an analysis of the staging web server.

For unit tests, I could of course query the back-end server from the tests directly, but for integration-level tests, I would like to have my app generate the request, send it as usual (except I'll have mocked the web server), and for the tests to analyze the server response to the test.

I've built [a crude Dispatcher that does this](https://gist.github.com/paour/bf58afa8969640e36e9bd87f85a6c5df), but a first-party solution would be nice, in particular it would allow the RecordedRequest to also contain the server's response…

**Comment by swankjesse** [comment]
I think it’s unlikely we’ll build this. It’s a lot of work to do well! If you’d like to promote your dispatcher as a standalone gist or project, please do.

**Comment by paour** [comment]
Here's a [gist that implements a basic reverse proxy](https://gist.github.com/paour/f1b72be812621819881f14ece951a59d). Because the MockWebServer makes available only a subset of the Request data, not all data is sent to the upstream server.
