### ISSUE TITLE
Support TLSv1.3

### ISSUE THREAD

**Issue by klyubin** [square/okhttp#2867]
TLSv1.3 is coming. okhttp needs to be adjusted to not disable TLSv1.3 in the underlying TLS stack, or to at least let the user of okhttp enable TLSv1.3 if the underlying TLS stack supports it.

At the moment, okhttp prevents the use of TLSv1.3 even if the underlying TLS stack offers it. My understanding is that all that needs to change in okhttp is: (1) add TLS_1_3 enum to TlsVersion, and (2) add TlsVersion.1_3 to ConnectionSpec.MODERN_TLS.

**Comment by swankjesse** [comment]
Yes!

**Comment by klyubin** [comment]
Would you like me to send a pull request?

**Comment by swankjesse** [comment]
Yes!
