### ISSUE TITLE
How to read response's body without copying buffer

### ISSUE THREAD

**Issue by marcottedan** [square/okhttp#2869]
Hey guys

I had to do something like `response.body().bytes()` in an Interceptor, then had to recreate a full Response with the fetched byte to return a clean Request that can be parsed again, instead of just switching the Reader Index back to it's beginning. That's a lot of temporary objects to garbage-collect.

Do you have a better solution?

**Comment by JakeWharton** [comment]
You can call `.peekBody(Long.MAX_VALUE)` to buffer the entire response in memory and get a lightweight copy of it. It'll be much less wasteful.

**Comment by JakeWharton** [comment]
> That's a lot of temporary objects to garbage-collect.

It's only one temporary object, the `byte[]`. Everything else is pooled automatically.

Switching to `peekBody` saves that allocation but you still copy the underlying data between pooled objects. To eliminate copying you can get the `BufferedSource` of the response, call `request(Long.MAX_VALUE)` to buffer the entire response data, and then call `.snapshot()` to get a read-only copy as a `ByteString` (which is less convenient to read from incrementally but perfectly fine if you just want raw data). This does no storage allocation (aside from the objects wrapping the data) or data copies.

**Comment by marcottedan** [comment]
So basically, it would look like this?

```
final BufferedSource source = response.body().source();
source.request(Integer.MAX_VALUE);
final byte[] bytes = source.buffer().snapshot().toByteArray();
```

Will this solution also work with multipart requests?

**Comment by JakeWharton** [comment]
Yep! Although your `toByteArray()` is going to still allocate a `byte[]` and do a data copy. Can you read what you need directly from `ByteString`?

**Comment by marcottedan** [comment]
I'm using Jackson's ObjectMapper `readValue` that can accepts both a `byte[]` or a `String`.

Should I simply call `snapshot().utf8()` ?

**Comment by marcottedan** [comment]
Ok is misinterpreted `toByteArray()` with `asByteBuffer()`. Am I right using it?

**Comment by marcottedan** [comment]
Awesome, thanks a lot for your support!
