### ISSUE TITLE
Provide RTT interceptor sample / wiki example.

### ISSUE THREAD

**Issue by JakeWharton** [square/okhttp#2870]
This is harder than it looks because you need to wait for the last byte to be read from the source before measuring the time. Mostly people end up erroneously measuring time to _first_ body byte instead of time to read the full request.

From https://twitter.com/jaredculp/status/777963686459834368

**Comment by swankjesse** [comment]
This is better handled by EventListener.
https://github.com/square/okhttp/issues/270
