### ISSUE TITLE
Handling WS connection timeouts when remote server disappears (e.g. crashes, forced off)

### ISSUE THREAD

**Issue by jimmidyson** [square/okhttp#2876]
Now that WS read timeouts default to 0 (see #2863), if the target server disappears ungracefully (not process stop, but perhaps server crashes, firewall starts dropping packets, etc), the connection remains established with no notification as no read timeout. On some platforms, it is enough to tweak the TCP stack, but obviously that is not good enough in the general case.

How can we handle this with okhttp?

**Comment by jimmidyson** [comment]
I wonder if, as @JakeWharton said in https://github.com/square/okhttp/pull/2863#issuecomment-248622798, that okhttp could default to expecting server impls to be spec compliant & send pings transparently in the background. Then could have a sane default ping/read timeout to handle this?

**Comment by JakeWharton** [comment]
We can also use read/write timeouts on individual frames instead of the
whole connection.

**Comment by jimmidyson** [comment]
Implemented via ping-pong & works great. Found a more fundamental issue in the server impl (Kubernetes 1.3) via this too so not wasted time :)

**Comment by swankjesse** [comment]
We’ve got this now. Automatic pings and timeouts that are enabled per-frame.
