### ISSUE TITLE
Response body should be null in a HEAD response

### ISSUE THREAD

**Issue by kenzierocks** [square/okhttp#2879]
Currently, if a server returns a `Content-Length` in the headers of a HEAD request matching the size of the GET entity (as it is supposed to), OkHttp will think that the response has a body to be read. When attempting to read this body, an exception is thrown because only 0 bytes are read instead of whatever the content length is: `Content-Length and stream length disagree`. OkHttp should just report a `null` body, since the `Content-Length` info is still available in the headers.

Here's a test case for what I expect AND what actually happens: https://gist.github.com/kenzierocks/6f061563cbcaafc05fe469a494ab45d6

**Comment by JakeWharton** [comment]
The spec allows a body in a HEAD response. An empty response is much more
appropriate, although if the content length is 0 I agree we should actively
close the underlying source.

**Comment by kenzierocks** [comment]
An empty response would also make sense.

**Comment by swankjesse** [comment]
I added a test. The empty body is working as designed.

**Comment by kenzierocks** [comment]
Fantastic, thanks!
