### ISSUE TITLE
*Feature* Split okhttp enqueue callback success and fail

### ISSUE THREAD

**Issue by lucas34** [square/okhttp#2880]
Hi, 

The current callback interface implements success and fail. If we split into two callback we can use the lambda as follow :

client.newCall(r).enqueue((call, e) -> showSucess(), (call, response) -> showError(response));

On the okhttp side, this callback can be wrapped into the "real" callback that implement both, like Rx when we only implement onNext(). 

Side question
- Do we allow the user to implement only success ?

Lucas.

**Comment by FabianTerhorst** [comment]
Without lambdas two interfaces would look more ugly then the current implementation.

**Comment by swankjesse** [comment]
You can write your own adapter to implement our interface with a pair of lambdas.

**Comment by lucas34** [comment]
Alright
