### ISSUE TITLE
Details about ConnectException

### ISSUE THREAD

**Issue by Tolriq** [square/okhttp#2881]
What kind of issue is this?

 - [X] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
       already exists! Don’t send pull requests to implement new features without first getting our
       support. Sometimes we leave features out on purpose to keep the project small.

I've got a few users that logs ConnectException from okhttp , but the underlying detail is hidden by okhttp implementation.

https://github.com/square/okhttp/blob/master/okhttp/src/main/java/okhttp3/internal/connection/RealConnection.java#L189

Is there a way to get more details like returning underlying error ?
Most of the time I get proper IOException with details like timeout / refused that help to give clue to the user.
But with this one I have no idea what the root cause can be.

**Comment by swankjesse** [comment]
Send a pull request to set the cause?

**Comment by Tolriq** [comment]
@swankjesse #2882
