### ISSUE TITLE
Bug: Response.body() returning null

### ISSUE THREAD

**Issue by JemarJones** [square/okhttp#2883]
According to [this comment](https://github.com/square/okhttp/blob/6014ab9752cff344a0baf57eb7626d98ca1d3401/okhttp/src/main/java/okhttp3/Response.java#L168) the `Response.body()` method may never return null. 

As can be seen in this [gist](https://gist.github.com/JemarJones/fcce225de6a4d59025c4011f4f06395b), there are cases in which this method can return null.

I think this comment either needs to be updated to be more accurate, or the functionality should be updated to match the claim made in the comment.

**Comment by swankjesse** [comment]
It’s an issue with the comment. It should really say “Never null on responses returned from servers”. It is possible to create instances of `Response` without providing a body, and we also use this in the `cacheResponse` and `networkResponse` members of `Response`.

**Comment by JemarJones** [comment]
@swankjesse Agreed, makes sense. Can i submit a PR to make that change to the comment or what is the process with milestones/releases?

**Comment by swankjesse** [comment]
Sure, please send a PR to fix the docs.
