### ISSUE TITLE
Old cache validation code

### ISSUE THREAD

**Issue by SukharevPavel** [square/okhttp#2886]
According to https://tools.ietf.org/html/rfc7234#section-4.3.3:
o  A full response (i.e., one with a payload body) indicates that
      none of the stored responses nominated in the conditional request
      is suitable.  Instead, the cache MUST use the full response to
      satisfy the request and MAY replace the stored response(s).

This statement contradicts to your code in https://github.com/square/okhttp/blob/master/okhttp/src/main/java/okhttp3/internal/cache/CacheInterceptor.java (or okhttp3/internal/http/HttpEngine.java for older versions of library).

```
private static boolean validate(Response cached, Response network) {
if (network.code() == HTTP_NOT_MODIFIED) return true;

// The HTTP spec says that if the network's response is older than our
// cached response, we may return the cache's response. Like Chrome (but
// unlike Firefox), this client prefers to return the newer response.
Date lastModified = cached.headers().getDate("Last-Modified");
if (lastModified != null) {
  Date networkLastModified = network.headers().getDate("Last-Modified");
  if (networkLastModified != null
      && networkLastModified.getTime() < lastModified.getTime()) {
    return true;
  }
}

return false;
  }
```

According to new http spec (https://tools.ietf.org/html/rfc7234 from June 2014) we always should use network response despite its "Last-Modified" header.

**Comment by swankjesse** [comment]
Yep, can fix.
