### ISSUE TITLE
MockWebServer: streaming response (SSE)

### ISSUE THREAD

**Issue by artem-zinnatullin** [square/okhttp#2894]
I might be wrong, but looks like `MockWebServer` does not allow "endless" responses controlled by writing to body `Buffer`.

I'm trying to simulate Server Sent Events with setting `Buffer` as a body of `MockResponse` and keep connection open via not closing the `Buffer`. But whatever I do `MockWebServer` closes connection for me and does not allow me emulate SSE.

Basically, I'd like to keep connection until I explicitly `close()` body `Buffer` and be able to write data to socket via writing to body `Buffer`.

What about adding such API to `MockResponse`? i.e. `MockResponse.setStreamingBody(Buffer body)`.

**Comment by JakeWharton** [comment]
`Buffer` is not safe for use across threads and it's unclear what MWS would be doing during this. Just spinning in a hot loop or waiting for a notification? We don't have a good type to model this and it would probably need something more sophisticated like `RequestBody` which can block on the writer thread or web sockets which have their own API.

**Comment by swankjesse** [comment]
Tracking as https://github.com/square/okhttp/issues/2916

**Comment by artem-zinnatullin** [comment]
Right, `Buffer` requires some wrapper to make it thread safe + add push/pull based API. I'll track #2916 then, thanks.
