### ISSUE TITLE
crash on adding header include some Persian/Arabic letter

### ISSUE THREAD

**Issue by siavashabdoli** [square/okhttp#2896]
I get this Exception on Crashlytics;

`Fatal Exception: java.lang.IllegalArgumentException
Unexpected char 0x641 at ۸۷ in User-Agent value: Android/4.4.2 Sheypoor/2.3.1 VersionCode/558 Manufacturer/Lenovo Model/Lenovo A5500-HV فارسی توسط انجمن پارس جی اس ام
 Raw Text
okhttp3.Headers$Builder.checkNameAndValue (Unknown Source:283)
okhttp3.Headers$Builder.add (Unknown Source:233)
okhttp3.Request$Builder.addHeader (Unknown Source:177)
com.sheypoor.mobile.network.ApiProvider$1.intercept (Unknown Source:57)`

as Fabric report I get this crash on some model of lenovo (and sped!!!) devices. this is my second biggest crash on crashlytics. Why non-english character can cause something like this? I can't Catch this exception and do not add header to it because I want the model in request header.

**Comment by swankjesse** [comment]
HTTP headers cannot have arbitrary characters in them. You should strip non-ASCII characters here.
