### ISSUE TITLE
W/OkHttp: A connection to http://www.xxxx:8082/ was leaked. Did you forget to close a response body?

### ISSUE THREAD

**Issue by wangfuda** [square/okhttp#2910]
- [ ] Question.
 
I have seen the same question as mine,but it's not same case.

when i see the exception, i have try to close the body,  but response is null . i can't close the body by response.

code like this:

`try {
      response = call.execute();

      if (response.isSuccessful()) {

                        
       } 
       } catch (IOException e) {
            e.printStackTrace();
      } finally {
            if (response != null && response.body() != null) {
                  Log.e(TAG, "response.code:" + response.code());
                  response.body().close();
             }
     }`

**Comment by swankjesse** [comment]
Please provide an executable test case!
