### ISSUE TITLE
Allow UTF-8 for Credentials.basic (as defined in RFC 7617)

### ISSUE THREAD

**Issue by rfc2822** [square/okhttp#2911]
Currently, `Credentials.basic` uses ISO-8859-1 encoding for credentials, which seems to be correct as far as I understand it. However, many people say that encoding is not defined that exactly and [expect UTF-8](https://github.com/nextcloud/server/issues/1731), which [causes problems](https://forums.bitfire.at/topic/1230/problem-davdroid-1-3-2-2-on-android-5-0-nextcloud-10-0-1-on-ubuntu-16-04-on-my-own-vserver-is-not-working/7). Other renowned clients like curl also use UTF-8, at least with UTF-8 system locale.

As a solution, RFC 7617 has been published, which allows servers to request a specific character set (and the only one allowed is UTF-8). So, `Credentials.basic` could have a parameter `boolean utf8`, which allows to switch between ISO-8859-1 (default) and UTF-8 (RFC 7617) behaviour.

If you're interested in this, I can try to make a patch.

**Comment by swankjesse** [comment]
Tracking as https://github.com/square/okhttp/issues/1468

If you’d like to prepare a pull request please do, but also please don’t write too much code. We.don’t generally like big PRs.

**Comment by rfc2822** [comment]
I'd even switch to UTF-8 completely. The ISO-8859-1 is a raw guess and not really specified in the standard, so it might work or it might not, according to the server. Every client and server uses another encoding. The only way which will always comply with RFC 7617 is always using UTF-8 (which I have now chosen for dav4android/davdroid). What do you think about it?

**Comment by swankjesse** [comment]
Seems like it could be backwards-incompatible.
