### ISSUE TITLE
OkHttpServer

### ISSUE THREAD

**Issue by swankjesse** [square/okhttp#2916]
We’re exploring building this. We could reuse the same request, response, and interceptor types.

**Comment by artem-zinnatullin** [comment]
1. In WIP PR https://github.com/square/okhttp/pull/2912/files: `<artifactId>okwebserver</artifactId>`, not `okhttpserver`. Can you please clarify naming?
2. Will `OkHttpServer` result in deletion of `MockWebServer` or it'll be used under the hood of `MockWebServer`?

**Comment by swankjesse** [comment]
TBD.

**Comment by artem-zinnatullin** [comment]
Yeah, I understand, those questions were not like "ANSWER THEM NOW OR I'LL UNSTAR OKHTTP ON GITHUB!!" but more "Please think about that and share some thoughts when you'll have some opinion". 

No pressure! 🐱

**Comment by JakeWharton** [comment]
MWS can't test SSE because body is `Buffer`. This should support.

**Comment by yschimke** [comment]
@swankjesse would you build this and https://github.com/cashapp/misk ?

**Comment by swankjesse** [comment]
Misk is a server framework. It currently uses Jetty though if we wanted to make the investment we could swap out Jetty for something we build ourselves.

**Comment by yschimke** [comment]
I'm more wondering whether we can close this?
