### ISSUE TITLE
the wanted request URL is A, but actually request URL is B?

### ISSUE THREAD

**Issue by wangfuda** [square/okhttp#2920]
- [ ] Question. 

why the wanted request URL is http://www.9uplus.com:8082/opt/uplus/apk/1476001608432JJHall.20202.35079.visible.apk
but actually request URL is 
www.9uplus.com/180.168.41.175 (port 8082)?

log as below:

10-21 13:11:03.823 13898-16070/com.airzilla.uplus D/OkHttp: --> GET http://www.9uplus.com:8082/opt/uplus/apk/1476001608432JJHall.20202.35079.visible.apk http/1.1
10-21 13:11:37.126 13898-16070/com.airzilla.uplus D/OkHttp: <-- HTTP FAILED: java.net.SocketTimeoutException: failed to connect to www.9uplus.com/180.168.41.175 (port 8082) after 10000ms
10-21 13:11:37.126 13898-16070/com.airzilla.uplus W/System.err: java.net.SocketTimeoutException: failed to connect to www.9uplus.com/180.168.41.175 (port 8082) after 10000ms

**Comment by swankjesse** [comment]
That error message isn't printing a URL. It’s a hostname and an IP address.
