### ISSUE TITLE
POST requests to HTTPS redirect locations end up as GET requests

### ISSUE THREAD

**Issue by Fibonacci-** [square/okhttp#2928]
## Versions
okhttp 3.4.1
Tested on Android 6.1 & 7.0

## Description
When a POST request is made to a URL that returns a 301 redirection to an HTTPS location, the request will turn into a GET request at the 301 location. This breaks some REST APIs that expect certain request types on specific endpoints.

## Severity
Minor - there is a workaround.

## Steps to Reproduce
1. Create a new OkHttpClient, new RequestBody with JSON mediatype & JSON string body
2. Create a new Request with the URL pointing to a 301 location & post data added
3. Execute the request

## Actual Behavior
The request will fail. On inspection, the final call made to the endpoint is found to be a GET request.

## Expected Behavior 
The request will succeed, with POST being used for all requests to that URL

## Workaround
Find the 301 location with a different library before feeding to OkHttp

**Comment by swankjesse** [comment]
This is working as intended, for compatibility with web browsers. You can use an interceptor to change the response code to 307 if you’d like.

See also https://github.com/square/okhttp/issues/2262#issuecomment-251699960
