### ISSUE TITLE
addEncoded，ignoring the '%'

### ISSUE THREAD

**Issue by galfordliu** [square/okhttp#2930]
public FormBody.Builder addEncoded(String name, String value) {
            this.names.add(HttpUrl.canonicalize(name, " \"\':;<=>@[]^`{}|/\\?#&!$(),~", true, false, true, true));
            this.values.add(HttpUrl.canonicalize(value, " \"\':;<=>@[]^`{}|/\?#&!$(),~", true, false, true, true));
            return this;
        }

A special character encoding, " \"\':;<=>@[]^`{}|/\?#&!$(),~"   ignoring the '%'

**Comment by swankjesse** [comment]
Is this a feature request?

**Comment by galfordliu** [comment]
No to encode %, which leads to the url encoding is not successful

**Comment by galfordliu** [comment]
addEncoded method why not encode '%' and '+' ?
