### ISSUE TITLE
FATAL EXCEPTION: OkHttp Dispatcher java.lang.RuntimeException: Socket closed

### ISSUE THREAD

**Issue by lizhennian** [square/okhttp#2932]
10-21 10:33:58.185 E/AndroidRuntime(22616): FATAL EXCEPTION: OkHttp Dispatcher

**help! help!**

10-21 10:33:58.185 E/AndroidRuntime(22616): java.lang.RuntimeException: Socket closed

10-21 10:33:58.185 E/AndroidRuntime(22616):     at $Proxy15.recvfrom(Native Method)

10-21 10:33:58.185 E/AndroidRuntime(22616):     at libcore.io.BlockGuardOs.recvfrom(BlockGuardOs.java:164)

10-21 10:33:58.185 E/AndroidRuntime(22616):     at libcore.io.IoBridge.recvfrom(IoBridge.java:513)

10-21 10:33:58.185 E/AndroidRuntime(22616):     at java.net.PlainSocketImpl.read(PlainSocketImpl.java:489)

10-21 10:33:58.185 E/AndroidRuntime(22616):     at java.net.PlainSocketImpl.access$000(PlainSocketImpl.java:46)

10-21 10:33:58.185 E/AndroidRuntime(22616):     at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:241)

10-21 10:33:58.185 E/AndroidRuntime(22616):     at okio.Okio$2.read(Okio.java:138)

10-21 10:33:58.185 E/AndroidRuntime(22616):     at okio.AsyncTimeout$2.read(AsyncTimeout.java:238)

10-21 10:33:58.185 E/AndroidRuntime(22616):     at okio.RealBufferedSource.request(RealBufferedSource.java:66)

10-21 10:33:58.185 E/AndroidRuntime(22616):     at okio.RealBufferedSource.require(RealBufferedSource.java:59)

10-21 10:33:58.185 E/AndroidRuntime(22616):     at okio.RealBufferedSource.readHexadecimalUnsignedLong(RealBufferedSource.java:284)

10-21 10:33:58.185 E/AndroidRuntime(22616):     at okhttp3.internal.http.Http1xStream$ChunkedSource.readChunkSize(Http1xStream.java:437)

10-21 10:33:58.185 E/AndroidRuntime(22616):     at okhttp3.internal.http.Http1xStream$ChunkedSource.read(Http1xStream.java:418)

10-21 10:33:58.185 E/AndroidRuntime(22616):     at okhttp3.internal.Util.skipAll(Util.java:176)

10-21 10:33:58.185 E/AndroidRuntime(22616):     at okhttp3.internal.Util.discard(Util.java:158)

10-21 10:33:58.185 E/AndroidRuntime(22616):     at okhttp3.internal.http.Http1xStream$ChunkedSource.close(Http1xStream.java:455)

10-21 10:33:58.185 E/AndroidRuntime(22616):     at okio.RealBufferedSource.close(RealBufferedSource.java:434)

10-21 10:33:58.185 E/AndroidRuntime(22616):     at okhttp3.internal.cache.CacheInterceptor$2.close(CacheInterceptor.java:229)

10-21 10:33:58.185 E/AndroidRuntime(22616):     at okio.RealBufferedSource.close(RealBufferedSource.java:434)

10-21 10:33:58.185 E/AndroidRuntime(22616):     at okio.RealBufferedSource.close(RealBufferedSource.java:434)

10-21 10:33:58.185 E/AndroidRuntime(22616):     at okio.InflaterSource.close(InflaterSource.java:126)

10-21 10:33:58.185 E/AndroidRuntime(22616):     at okio.GzipSource.close(GzipSource.java:182)

10-21 10:33:58.185 E/AndroidRuntime(22616):     at okio.RealBufferedSource.close(RealBufferedSource.java:434)

10-21 10:33:58.185 E/AndroidRuntime(22616):     at okhttp3.internal.Util.closeQuietly(Util.java:88)

10-21 10:33:58.185 E/AndroidRuntime(22616):     at okhttp3.ResponseBody.bytes(ResponseBody.java:130)

10-21 10:33:58.185 E/AndroidRuntime(22616):     at okhttp3.ResponseBody.string(ResponseBody.java:154)

10-21 10:33:58.185 E/AndroidRuntime(22616):     at com.elinkway.tvlive2.epg.OfficialDataSource$3.onResponse(OfficialDataSource.java:252)

10-21 10:33:58.185 E/AndroidRuntime(22616):     at okhttp3.RealCall$AsyncCall.execute(RealCall.java:126)

10-21 10:33:58.185 E/AndroidRuntime(22616):     at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)

10-21 10:33:58.185 E/AndroidRuntime(22616):     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)

10-21 10:33:58.185 E/AndroidRuntime(22616):     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)

10-21 10:33:58.185 E/AndroidRuntime(22616):     at java.lang.Thread.run(Thread.java:856)

10-21 10:33:58.185 E/AndroidRuntime(22616): Caused by: java.net.SocketException: Socket closed

10-21 10:33:58.185 E/AndroidRuntime(22616):     at libcore.io.Posix.recvfromBytes(Native Method)

10-21 10:33:58.185 E/AndroidRuntime(22616):     at libcore.io.Posix.recvfrom(Posix.java:131)

10-21 10:33:58.185 E/AndroidRuntime(22616):     at java.lang.reflect.Method.invokeNative(Native Method)

10-21 10:33:58.185 E/AndroidRuntime(22616):     at java.lang.reflect.Method.invoke(Method.java:511)

10-21 10:33:58.185 E/AndroidRuntime(22616):     at com.morgoo.droidplugin.hook.proxy.ProxyHook.invoke(SourceFile:62)

10-21 10:33:58.185 E/AndroidRuntime(22616):     ... 32 more

**Comment by swankjesse** [comment]
What’s ProxyHook? I don't think OkHttp is to blame here. Can you provide an executable test case?
