### ISSUE TITLE
Removing authorization in redirect should be configurable.

### ISSUE THREAD

**Issue by nhaarman** [square/okhttp#2937]
Line [324 in `RetryAndFollowUpInterceptor`](https://github.com/square/okhttp/blob/master/okhttp/src/main/java/okhttp3/internal/http/RetryAndFollowUpInterceptor.java#L324) says this:

``` java
// When redirecting across hosts, drop all authentication headers. This
// is potentially annoying to the application layer since they have no
// way to retain them.
if (!sameConnection(userResponse, url)) {
    requestBuilder.removeHeader("Authorization");
}
```

Instead of just removing the headers, perhaps create an opt-in to _not_ remove them.
For example, the Nest api sometimes returns a 307 response to redirect to a firebase server. This server really needs the authentication headers. Unfortunately, the `sameConnection` check fails in this case.

```
D: --> GET https://developer-api.nest.com/ http/1.1
D: Authorization: Bearer c.MHcl...
D: --> END GET
D: <-- 307 Temporary Redirect https://developer-api.nest.com/ (473ms)
D: Content-Type: application/json; charset=UTF-8
D: Access-Control-Allow-Origin: *
D: Cache-Control: private, no-cache, no-store, max-age=0
D: Pragma: no-cache
D: Location: https://firebase-apiserver06-tah01-iad01.dapi.production.nest.com:9553/
D: Connection: close
D: Authorization: Bearer c.MHcl...
D: Content-Length: 0
D: <-- END HTTP (0-byte body)
```

For now, setting `followRedirects` to `false` and handling them manually works as a workaround.

**Comment by swankjesse** [comment]
You might be able to accomplish this with a network interceptor.
