### ISSUE TITLE
Do something reasonable about Cookies containing invalid characters

### ISSUE THREAD

**Issue by paul321** [square/okhttp#2939]
I'm trying to access a server on android via okhttp 3.4.1 and i get the following error:

 java.lang.IllegalArgumentException: Unexpected char 0x01 at 325 in Cookie value: incap_ses_151_949833=xNLaFk17+mQdQL4SDnYYAps+D1gAAAAA7IU4sgUQkCsv3rfOJVl9cw==; visid_incap_949833=0P2YodceQOChjdX2SNkD+5s+D1gAAAAAQUIPAAAAAAA3oNf9btXYpqwwNhIkUyPM; js_cookie2=id@879872eaX3683e90/; ___utmvmzFuPmMp=noSqLHjmLPc; ___utmvbzFuPmMp=fZO XwlOQalt: Lts; p_cookie2=cm%3D728443386%26cx%3D10414854; ___utmvazFuPmMp=ViyhtVq

This works fine in any browser, i know there is a problem with value of the cookie ___utmvazFuPmMp, how can we get it working?
Any idea?

Thank you

**Comment by swankjesse** [comment]
Ugh, seems like the webserver is sending a malformed cookie and we’re echoing it back. We can either fix by discarding the bad cookie on the way in, stripping bad characters from it, or by retaining bad characters in it on the way out. I’ll look to see what Chrome & Firefox do and try to do likewise.

**Comment by NikoYuwono** [comment]
In case of Chrome, I think they basically trim the bad characters (in this case \u0001).  
I also tested some other control characters and found out Chrome will strip the backslash only and convert whitespace related control characters into whitespace.

@swankjesse What do you think about this approach?

![screen shot 2016-12-28 at 15 44 27](https://cloud.githubusercontent.com/assets/1751188/21515597/90238eee-cd14-11e6-9236-113e7c0694d5.png)

**Comment by swankjesse** [comment]
#### Chrome:
 * drops cookies containing `\u0001` through `\u0019`
 * except `\u0000` which is stripped

#### Firefox:
 * drops cookies containing `\u0000` through `\u0019`
 * except `\u0000` which terminates the header
 * except `\u0009` (tab) which is retained

#### Safari:
 * truncates cookie at character containing `\u0000` through `\u0019`
 * truncates cookie at character containing `\u007f` through `\u00ff`
 * except `\u0009` (tab) which is retained

**Comment by swankjesse** [comment]
I think I’ll try to get OkHttp to drop cookies in [`\u0000`..`\u0019`] and [`\u007f`..].

**Comment by paul321** [comment]
Was this one released in 3.5.0? I still have the problem.
Thanks

**Comment by swankjesse** [comment]
Nope. Hoping to cut 3.6.0 like today or tomorrow.
