### ISSUE TITLE
okhttp3 多线程下载图片会报这个错误，但用OKhttp2.0不会这样

### ISSUE THREAD

**Issue by akingyin1987** [square/okhttp#2942]
java.net.SocketException: socket failed: EMFILE (Too many open files)
10-27 21:58:42.080 10158-12588/com.md.multipleapp W/System.err:     at libcore.io.IoBridge.socket(IoBridge.java:583)
10-27 21:58:42.080 10158-12588/com.md.multipleapp W/System.err:     at java.net.PlainSocketImpl.create(PlainSocketImpl.java:201)
10-27 21:58:42.080 10158-12588/com.md.multipleapp W/System.err:     at java.net.Socket.checkOpenAndCreate(Socket.java:663)
10-27 21:58:42.080 10158-12588/com.md.multipleapp W/System.err:     at java.net.Socket.setSoTimeout(Socket.java:518)
10-27 21:58:42.080 10158-12588/com.md.multipleapp W/System.err:     at okhttp3.internal.io.RealConnection.connectSocket(RealConnection.java:138)
10-27 21:58:42.080 10158-12588/com.md.multipleapp W/System.err:     at okhttp3.internal.io.RealConnection.connect(RealConnection.java:111)
10-27 21:58:42.080 10158-12588/com.md.multipleapp W/System.err:     at okhttp3.internal.http.StreamAllocation.findConnection(StreamAllocation.java:188)
10-27 21:58:42.080 10158-12588/com.md.multipleapp W/System.err:     at okhttp3.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:127)
10-27 21:58:42.080 10158-12588/com.md.multipleapp W/System.err:     at okhttp3.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
10-27 21:58:42.080 10158-12588/com.md.multipleapp W/System.err:     at okhttp3.internal.http.HttpEngine.connect(HttpEngine.java:289)
10-27 21:58:42.080 10158-12588/com.md.multipleapp W/System.err:     at okhttp3.internal.http.HttpEngine.sendRequest(HttpEngine.java:241)
10-27 21:58:42.080 10158-12588/com.md.multipleapp W/System.err:     at okhttp3.RealCall.getResponse(RealCall.java:240)
10-27 21:58:42.085 10158-12588/com.md.multipleapp W/System.err:     at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:198)
10-27 21:58:42.085 10158-12588/com.md.multipleapp W/System.err:     at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:160)
10-27 21:58:42.085 10158-12588/com.md.multipleapp W/System.err:     at okhttp3.RealCall.execute(RealCall.java:57)

**Comment by erlangp** [comment]
https://github.com/square/okhttp/issues/1943#issuecomment-151024020
