### ISSUE TITLE
Dns Multiple IP filter

### ISSUE THREAD

**Issue by jingtuo** [square/okhttp#2944]
Dns IP

 - [x] Question. I use custom dns，Examples are as follows：
           `OkHttpClient okHttpClient = new OkHttpClient.Builder()
                     .dns(new Dns() {
                              @Override
                               public List<InetAddress> lookup(String hostname) throws
                                        UnknownHostException {
                                        return DnsManager.getInstance().getInetAddresses(hostname);
                                }
                      })...`                              
           The result returned by the method(`DnsManager.getInstance().getInetAddresses(hostname)`) is more than IP,How to let okhttp choose the best network IP.
           My English is very bad，I'm sorry!

**Comment by swankjesse** [comment]
Please use StackOverflow for usage questions.
