### ISSUE TITLE
OkHTTP connection to PayPal gives an SSLHandshakeException

### ISSUE THREAD

**Issue by jeffreyporter** [square/okhttp#2947]
I'm using Java 1.8 and 

```
    <dependency>
        <groupId>com.squareup.okhttp</groupId>
        <artifactId>okhttp</artifactId>
        <version>2.7.5</version>
    </dependency>
```

To connect to Paypal via this code...

```
    String httpUrl = "https://api.sandbox.paypal.com/retail/merchant/v1/invoices/";
    String jsonContent = "{'test':'test'}";

    RequestBody requestBody = RequestBody.create(MediaType.parse("application/json; charset=utf-8"), jsonContent);
    Request request =  new Request.Builder().url(httpUrl).post(requestBody).build();
    Response response = new OkHttpClient().newCall(request).execute();

    System.out.println(response.body());
```

I get the error response of...

> main, READ: TLSv1 Alert, length = 2
>     main, RECV TLSv1 ALERT:  fatal, handshake_failure
>     main, called closeSocket()
>     main, handling exception: javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
>     main, called close()
>     main, called closeInternal(true)
>     Exception in thread "main" javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
>       at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
>       at sun.security.ssl.Alerts.getSSLException(Alerts.java:154)
>       at sun.security.ssl.SSLSocketImpl.recvAlert(SSLSocketImpl.java:1979)
>       at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1086)
>       at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1332)
>       at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1359)
>       at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1343)
>       at com.squareup.okhttp.internal.io.RealConnection.connectTls(RealConnection.java:192)

Can anyone help me out please.

**Comment by hharsunen** [comment]
https://api.sandbox.paypal.com is TLSv1.2 only, see [ssllabs analysis](https://www.ssllabs.com/ssltest/analyze.html?d=api.sandbox.paypal.com) . Seems like you are trying to connect with TLSv1.0

**Comment by jeffreyporter** [comment]
I've not changed the code to be....

```
public static void main(String[] args) throws IOException {

    String httpUrl = "https://api.sandbox.paypal.com/retail/merchant/v1/invoices/";
    String jsonContent = "{'test':'test'}";

    RequestBody requestBody = RequestBody.create(MediaType.parse("application/json; charset=utf-8"), jsonContent);
    Request request =  new Request.Builder().url(httpUrl).post(requestBody).build();
    OkHttpClient okHttpClient = new OkHttpClient();

    okHttpClient.setConnectionSpecs(createConnectionSpecs(okHttpClient));

    Response response = okHttpClient.newCall(request).execute();

    System.out.println(response.body());
}

  private static List<ConnectionSpec> createConnectionSpecs(OkHttpClient okHttpClient) {
    ConnectionSpec spec = new ConnectionSpec.Builder(ConnectionSpec.COMPATIBLE_TLS)  
        .tlsVersions(TlsVersion.TLS_1_2)
        .cipherSuites(
            CipherSuite.TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,
            CipherSuite.TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,
            CipherSuite.TLS_DHE_RSA_WITH_AES_128_GCM_SHA256,
            CipherSuite.TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA,
            CipherSuite.TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA,
            CipherSuite.TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA,
            CipherSuite.TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA,
            CipherSuite.TLS_ECDHE_ECDSA_WITH_RC4_128_SHA,
            CipherSuite.TLS_ECDHE_RSA_WITH_RC4_128_SHA,
            CipherSuite.TLS_DHE_RSA_WITH_AES_128_CBC_SHA,
            CipherSuite.TLS_DHE_DSS_WITH_AES_128_CBC_SHA,
            CipherSuite.TLS_DHE_RSA_WITH_AES_256_CBC_SHA)
        .build();
    return Collections.singletonList(spec);
  }
```

I'm using these option on run of the application...

-Dhttps.protocols=TLSv1.2  -Djavax.net.debug=ssl,handshake

Debug output gives....

        adding as trusted cert:
      Subject: CN=TC TrustCenter Class 2 CA II, OU=TC TrustCenter Class 2 CA, O=TC TrustCenter GmbH, C=DE
      Issuer:  CN=TC TrustCenter Class 2 CA II, OU=TC TrustCenter Class 2 CA, O=TC TrustCenter GmbH, C=DE
      Algorithm: RSA; Serial number: 0x2e6a000100021fd752212c115c3b
      Valid from Thu Jan 12 14:38:43 GMT 2006 until Wed Dec 31 22:59:59 GMT 2025
    
    trigger seeding of SecureRandom
    done seeding SecureRandom
    Ignoring unavailable cipher suite: TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA
    Ignoring unavailable cipher suite: TLS_DHE_RSA_WITH_AES_256_CBC_SHA
    Ignoring unavailable cipher suite: TLS_ECDH_RSA_WITH_AES_256_CBC_SHA
    Ignoring unsupported cipher suite: TLS_DHE_DSS_WITH_AES_128_CBC_SHA256
    Ignoring unsupported cipher suite: TLS_DHE_DSS_WITH_AES_256_CBC_SHA256
    Ignoring unsupported cipher suite: TLS_DHE_RSA_WITH_AES_128_CBC_SHA256
    Ignoring unsupported cipher suite: TLS_ECDH_RSA_WITH_AES_128_CBC_SHA256
    Ignoring unsupported cipher suite: TLS_DHE_RSA_WITH_AES_256_CBC_SHA256
    Ignoring unsupported cipher suite: TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384
    Ignoring unsupported cipher suite: TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA384
    Ignoring unsupported cipher suite: TLS_RSA_WITH_AES_256_CBC_SHA256
    Ignoring unavailable cipher suite: TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA
    Ignoring unsupported cipher suite: TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
    Ignoring unsupported cipher suite: TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384
    Ignoring unavailable cipher suite: TLS_DHE_DSS_WITH_AES_256_CBC_SHA
    Ignoring unsupported cipher suite: TLS_ECDH_RSA_WITH_AES_256_CBC_SHA384
    Ignoring unsupported cipher suite: TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256
    Ignoring unsupported cipher suite: TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA256
    Ignoring unavailable cipher suite: TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA
    Ignoring unavailable cipher suite: TLS_RSA_WITH_AES_256_CBC_SHA
    Ignoring unsupported cipher suite: TLS_RSA_WITH_AES_128_CBC_SHA256
    Allow unsafe renegotiation: false
    Allow legacy hello messages: true
    Is initial handshake: true
    Is secure renegotiation: false
    main, called close()
    main, called closeInternal(true)
    main, called closeSocket(selfInitiated)
    Exception in thread "main" java.net.UnknownServiceException: 
    Unable to find acceptable protocols. isFallback=false, modes=[ConnectionSpec(cipherSuites=[TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256, TLS_DHE_RSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA, TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA, TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA, TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA, TLS_ECDHE_ECDSA_WITH_RC4_128_SHA, TLS_ECDHE_RSA_WITH_RC4_128_SHA, TLS_DHE_RSA_WITH_AES_128_CBC_SHA, TLS_DHE_DSS_WITH_AES_128_CBC_SHA, TLS_DHE_RSA_WITH_AES_256_CBC_SHA], tlsVersions=[TLS_1_2], supportsTlsExtensions=true)], supported protocols=[TLSv1]
        	at com.squareup.okhttp.internal.ConnectionSpecSelector.configureSecureSocket(ConnectionSpecSelector.java:73)

**Comment by hharsunen** [comment]
should this "supported protocols=[TLSv1]" be "supported protocols=[TLSv1.2]", seems like client side is not trying with TLS1.2

**Comment by hharsunen** [comment]
try changing `ConnectionSpec spec = new ConnectionSpec.Builder(ConnectionSpec.COMPATIBLE_TLS)  `  to 
`ConnectionSpec spec = new ConnectionSpec.Builder(ConnectionSpec.MODERN_TLS)`

**Comment by hharsunen** [comment]
And try with TLS_RSA_WITH_AES_128_CBC_SHA cipher

**Comment by hharsunen** [comment]
If you don't wan to limit cipher support, check out the [JDK8 JCE Unlimited Policy Files](http://www.oracle.com/technetwork/java/javase/downloads/jce8-download-2133166.html)

**Comment by jeffreyporter** [comment]
(ConnectionSpec.MODERN_TLS) This works! THANK YOU!
