### ISSUE TITLE
Switching network issue

### ISSUE THREAD

**Issue by haivuhvn** [square/okhttp#2949]
I am using OkHttp 2.4 version and I got the bug like that:

I open my app and then I switch wifi on phone, and come back my app with api call in onResume. The app will load very long time to get the response. It only happen on Android 5.0. 

Anyone can help me resolve this issue. Thanks all.

**Comment by swankjesse** [comment]
If you can reproduce this on a current version of OkHttp, please open a new bug with a test case.
