### ISSUE TITLE
OkHttp may break RFC2616, it will send previous "Date" header from response as "If-Modified-Since" header of next request.

### ISSUE THREAD

**Issue by zhfk930129** [square/okhttp#2951]
I met a problem when I use OkHttp to request api and cache some responses to save data usage.

Let's first see the source code in okhttp3.internal.cache.CacheStrategy class:

```Java
/** The server's time when the cached response was served, if known. */
private Date servedDate;
private String servedDateString;

private CacheStrategy getCandidate() {
      ...
      String conditionName;
      String conditionValue;
      if (etag != null) {
        conditionName = "If-None-Match";
        conditionValue = etag;
      } else if (lastModified != null) {
        conditionName = "If-Modified-Since";
        conditionValue = lastModifiedString;
      } else if (servedDate != null) {
        //Here OkHttp retrieve previous response's "Date" header's value as the next request's "If-Modified-Since" header's value.
        conditionName = "If-Modified-Since";
        conditionValue = servedDateString;
      } else {
        return new CacheStrategy(request, null); // No condition! Make a regular request.
      }

      Headers.Builder conditionalRequestHeaders = request.headers().newBuilder();
      Internal.instance.addLenient(conditionalRequestHeaders, conditionName, conditionValue);

      Request conditionalRequest = request.newBuilder()
          .headers(conditionalRequestHeaders.build())
          .build();
      return new CacheStrategy(conditionalRequest, cacheResponse);
}
```

Let me raise an example to see what will happen (if I am wrong, please correct me). Suppose we make a request first, our server does not return "Last-Modified" but returns "Date" header within response. At the next request, our OkHttp's client will send this "Date" header's value from previous response as "If-Modified-Since" header's value of this request.

That is usually good for our frontend developers since it automatically implements cache mechanism (304 / If-Modified / Last Modified) if our backend also does some support. But recently I met a problem.

What I want to do is to request a menu of restaurant (around 2M of size) from server and cache it to save data consumption. The following is my pseudocode:

```Java
if (No cache) {
    request api without "If-Modified-Since" header {
    //request api with "If-Modified-Since" header of value "Thu Jan 01 1970 00:00:00 GMT {
        if (200) {
            cache response menu into SharedPreference
            return response menu
        } else if (304) {
            return menu from SharedPreference
        }
    }
} else {
    //Cache existing.
    request api with "If-Modified-Since" header {
        if (200) {
            cache response menu into SharedPreference
            return response menu
        } else if (304) {
            return menu from SharedPreference
        }
    }
}
```

It is fine until I need to support multiple languages (I intercepted request and add a "Accept-Language" header):

When user firstly request api (Request A) with "Accept-Language" = "en-uk", no cache exist and we get into the first "if" block, then we got 200 with the menu of English Version. Now the user changes system language to Chinese and makes the request (Request B) again, since no Chinese version of cache existing, again we get into the first "if" block. This time the user wants to make a request without "If-Modified-Since" header, but OkHttp will retrieve "Date" header (suppose its value is T) from Response A and set its value into "If-Modified-Since" header in Request B since OkHttp treats Request A equals to Request B (They differs only on "Accept-Language" header).  So the user will finally send a request with "If-Modified-Since" header, then the server will return 304 since the menu of Chinese version was created (maybe 2 weeks) before timestamp T, which is around the response time of Request A. So our user will not get the menu of Chinese Version until our server changes update_time of the menu.

Although now I fixed my problem as the comments wrote in my pseudocode to prevent OkHttp to amend its cached date value in this api, I checked RFC2616 and have not found it to be a standard.

> RFC2616 Header Field Definitions -> Date 
(https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.18)

So maybe it should be a bug?

**Comment by swankjesse** [comment]
You want to configure your server to use the `Vary` header to differentiate the responses.
