### ISSUE TITLE
Can't get the Content-Length while downloading a gzip-compressed file from nginx

### ISSUE THREAD

**Issue by TreeAndLime** [square/okhttp#2963]
When I download a gzip-compressed file from nginx, I can not use "response.body().contentLength()" to get the file's length. Results will return -1. 
But I use WireShark to capture the data, there is "Content-Length" in the response's headers. 
Bug? @raggi @baldur @mlc @xaviershay @emerose

**Comment by JakeWharton** [comment]
The content length on the wire is the compressed (aka gzipped) length. The unknown content length reported to the application layer is of the uncompressed body. See #259.

Please do not spam random users of our organization.

**Comment by TreeAndLime** [comment]
sorry.
I have used Precompression to compress the file.
using "URLconnection", I can get the content length. why?
