### ISSUE TITLE
Exception NullPointerException

### ISSUE THREAD

**Issue by juvenull** [square/okhttp#2967]
I have error message from log "java.lang.NullPointerException". My android app call webapi. I use packages square.okhttp 2.7.5 and square.okio 1.10.0

This stack:
11-10 09:45:06.038: E/ExceptionHandler(10269): null
11-10 09:45:06.038: E/ExceptionHandler(10269): java.lang.NullPointerException
11-10 09:45:06.038: E/ExceptionHandler(10269): 	at com.forgepond.locksmith.tunnel.HttpTunnel$FPCall.doCall(SourceFile:623)
11-10 09:45:06.038: E/ExceptionHandler(10269): 	at com.forgepond.locksmith.tunnel.HttpTunnel$FPCall.access$000(SourceFile:499)
11-10 09:45:06.038: E/ExceptionHandler(10269): 	at com.forgepond.locksmith.tunnel.HttpTunnel$FPCall$1.intercept(SourceFile:526)
11-10 09:45:06.038: E/ExceptionHandler(10269): 	at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(SourceFile:221)
11-10 09:45:06.038: E/ExceptionHandler(10269): 	at com.squareup.okhttp.Call.getResponseWithInterceptorChain(SourceFile:195)
11-10 09:45:06.038: E/ExceptionHandler(10269): 	at com.squareup.okhttp.Call.access$100(SourceFile:34)
11-10 09:45:06.038: E/ExceptionHandler(10269): 	at com.squareup.okhttp.Call$AsyncCall.execute(SourceFile:162)
11-10 09:45:06.038: E/ExceptionHandler(10269): 	at com.squareup.okhttp.internal.NamedRunnable.run(SourceFile:33)
11-10 09:45:06.038: E/ExceptionHandler(10269): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
11-10 09:45:06.038: E/ExceptionHandler(10269): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
11-10 09:45:06.038: E/ExceptionHandler(10269): 	at java.lang.Thread.run(Thread.java:841)

**Comment by swankjesse** [comment]
The problem is in  com.forgepond.locksmith.tunnel.HttpTunnel and not OkHttp.
