### ISSUE TITLE
Certificate pins not checked after switching network

### ISSUE THREAD

**Issue by freakinruben** [square/okhttp#2968]
I'm running into an issue where the pins are not checked when the initial handshake was successful and then the network changes.

Issue #1780 mentions clearing the connection pool when the network changes for OkHttp2, is this implemented in OkHttp3?

Current version: Okhttp 3.4.1
Device: Nexus 4 with Android 5.1.1

Steps to reproduce:
- Connect to normal network without proxy (LTE for example)
- Run application (pinning is applied successfully)
- API calls work
- Switch to network with proxy (I'm using CharlesProxy)
- API calls are intercepted by charlesproxy and still work while they should fail

When I connect to the network with the proxy before the app launches, certificate pinning is applied correctly and API calls fail.

Currently this makes my app vulnerable for MITM attacks when an attacker sets up a network that impersonates the network you're connected to and makes the phone switch to the rogue network (stronger signal).

Hope you can help me with this

**Comment by swankjesse** [comment]
Could you provide an executable test case? I’ve never seen trust leaks like this before so I’m suspicious it’s a configuration issue on your end.

**Comment by swankjesse** [comment]
If you look in our test suite you’ll see some that use two MockWebServer instances. You’ll wanna do likewise with one configured as a proxy.

**Comment by freakinruben** [comment]
It's based on a report we got back from a pentest. I will try to create a testcase for it this week..
