### ISSUE TITLE
why loss encode for ; in httpurl's QUERY_COMPONENT_ENCODE_SET?

### ISSUE THREAD

**Issue by jiafu1115** [square/okhttp#2975]
http://www.freeformatter.com/url-encoder.html

```
How does URL encoding work?
 
: (Colon) becomes %3A
; (Semi-Colon) becomes %3B
```

can anybody help to explain it?  I use old version's okhttp. it is %3B. but update to newest version, it is still ; with encode. it broken my app.

I doesn't know why to change it?

anybody know it? @swankjesse

**Comment by swankjesse** [comment]
Consistency with Chrome & Firefox.

**Comment by jiafu1115** [comment]
@swankjesse  How to do if we still want to keep encode to %3B.  Or the server should change to support ; instead of %3B?

**Comment by jiafu1115** [comment]
@swankjesse if keeping unencode for ; is standard. This need server to support it instead we change?
