### ISSUE TITLE
Please document File type responses for MockWebServer

### ISSUE THREAD

**Issue by mikelupo** [square/okhttp#2980]
In MockWebServer, it's very easy and robust to respond to API requests. Thank you for a very cool tool.

What about content requests? It would be helpful to the community if you could update the readme.md with an example of a preferred method. There are discussions on SO in regards to this with no answers (Except for what I just posted there) [LINK ](http://stackoverflow.com/questions/37583765/how-can-i-use-okhttpclient-mockwebsever-to-return-an-image-byte)

Just for fodder.
What I'm doing currently, is to Base64 encode the binary (i.e. video/mp4), but the client that is consuming the response does not like it. 

Here's my code. The encodedFile is what is passed back to MockWebServer's response handler for particular request for the video file.
My path is to the file which is resident on the sdcard.

<
//Base64 encode a binary IMAGE file to return with mock.
    String getEncodedPngBinary(String path) {

        Bitmap bm = BitmapFactory.decodeFile(path);
        ByteArrayOutputStream baos = new ByteArrayOutputStream();
        bm.compress(Bitmap.CompressFormat.PNG, 100, baos);

        //bm is the bitmap object
        byte[] b = baos.toByteArray();
        String encodedFile = Base64.encodeToString(b, Base64.NO_WRAP);
        return encodedFile;
    }

    //Base64 encode a binary VIDEO file to return with a mock.
    String getEncodedVideoBinary(String path) throws IOException {
        File file = new File(path);
        byte[] fileData = FileUtils.readFileToByteArray(file);
        String encodedFile = Base64.encodeToString(fileData,Base64.NO_WRAP);
        return encodedFile;
    }

    //Base64 encode a binary IMAGE and compress as JPEG.
    String getEncodedJpgBinary(String path) {
        Bitmap bm = BitmapFactory.decodeFile(path);
        ByteArrayOutputStream baos = new ByteArrayOutputStream();
        bm.compress(Bitmap.CompressFormat.JPEG, 100, baos);

        //bm is the bitmap object
        byte[] b = baos.toByteArray();
        String encodedFile = Base64.encodeToString(b, Base64.NO_WRAP);
        return encodedFile;
    }
>

**Comment by swankjesse** [comment]
In general serving large responses is a bad fit for MockWebServer. It requires all responses be completely loaded into memory.

For your specific case I don’t think base64 encoding is helping you. You should load the file into an `okio.Buffer` and go from there:

```
    Buffer buffer = new Buffer();
    buffer.writeAll(Okio.source(new File("tacos.jpg")));
```

MockResponse will take a Buffer.
