### ISSUE TITLE
Cookies from other domains

### ISSUE THREAD

**Issue by paul321** [square/okhttp#2981]
Our mobile app tries to submit a login form into a website for example www.example.com/login the problem is they are using Incapsula and each request to a website resource generates a security cookie like this one: Cookie: visid_incap_949833=Sz05dkxzQWinC8p4sGN05nDwKlgAAAAAQUIPAAAAAAC9spqh3YNfP4kYN0neX7sU; incap_ses_184_949833=Rrx3W1QP+EOgAI9EYuWNAl8TK1gAAAAAT04R4sWzx6MnpJNuqMsClA==

The login page has a template login.mustache and when is requested generates a cookie like this one which needs to be present in the next request. 
The problem is login.mustache is hosted on a server called cloudfront.net not www.example.com and that page is setting a cookie visid_incap for the domain example.com which okhttp neves saves it and is never passed in the next request because the cookie domain is different from the hosted server.

Any solution to this?

**Comment by swankjesse** [comment]
The domain policy is implemented by your CookieJar. Another cookie jar might be more flexible.
https://github.com/franmontiel/PersistentCookieJar

**Comment by swankjesse** [comment]
No action to take on this.
