### ISSUE TITLE
Can't stream body() directly from network

### ISSUE THREAD

**Issue by mufumbo** [square/okhttp#2982]
We've got inspired reading that the Json parsing should be done over the network latency and tried to implement that with okhttp.

It seems we can't do that with okhttp3, which is very weird, because @JakeWharton is the one commenting about that:
https://www.reddit.com/r/androiddev/comments/3rrplu/flatbuffers_arent_fast_theyre_lazy_jesse_wilson/cwrdcr2/

In any case, we are using chunked gzipped response with HTTP2 (without content-length).

This is the pseudo code:
```           
currentCall = okHttpClient.newCall(getRequest());

final Response response = currentCall.execute();

timeToConnect = System.currentTimeMillis() - start;

// do something with response.body().byteStream();
```

In this code, all the time is spent in currentCall.execute() and zero time spent streaming the byteStream(). 

We tried every search in google and couldn't find anyone with the same problem, which is weird. 
What we're trying to do is to pass the response.body().byteStream() directly to the JsonReader class, so we stream a list of objects, instead of waiting for all of them to be ready.

The same code (JsonReader streaming) works properly with HttpURLConnection. 

Please, advise, as we want to use only one http library.

**Comment by swankjesse** [comment]
It's either a small response (which will be fully buffered) or a measurement error. In either case spending zero time is good news. Your code is very fast.

**Comment by mufumbo** [comment]
@swankjesse, it's a 256kb json request. The code I posted above probably doesn't leave space for measurement error on "timeToConnect" having 99% of the time on a UMTS connection. Also I wouldn't be posting here if haven't tested everything, including implementing the exact same thing on httpurlconnection and volley. We actually had to implement a proxy layer which made very easy to test the three frameworks and the others work properly, including the UX part.

Are you 100% sure okhttp3 streams the network download as well? With these parameters: http2, chunked gzipped stream. 

From what we see, okhttp3 esponse.body().byteStream() has an already consumed stream from the network. Maybe a bug with missing content-length, http2 or gzip.

**Comment by swankjesse** [comment]
Yeah. It's possible that something else is interfering: are you logging the full response body in an interceptor?

**Comment by renatopeterman** [comment]
Yes, we're using the [HttpLoggingInterceptor](https://github.com/square/okhttp/blob/7135628c645892faf1a48a8cff464e0ed4ad88cb/okhttp-logging-interceptor/src/main/java/okhttp3/logging/HttpLoggingInterceptor.java) with logging level `BODY`. Do you think this could interfere?

**Comment by swankjesse** [comment]
Yep. It’ll download the entire body to log it before you get a chance to parse anything. Turn down the logging level and you’ll see what you were expecting to see.

**Comment by mufumbo** [comment]
yes, the log interceptor was the culprit! hope this thread helps other people with the same problem.  thanks!
