### ISSUE TITLE
OkHttp ConnectionPool" prio=5 tid=36 TimedWaiting

### ISSUE THREAD

**Issue by maoaixianyu** [square/okhttp#2983]
This crash  make my app crash, I need help for this.

17:52:38.306 26186-27193/ A/art: art/runtime/runtime.cc:366]   - waiting on <0x00285f3b> (a java.lang.Class<com.android.okhttp.okio.AsyncTimeout>)
11-15 17:52:38.306 26186-27193/ A/art: art/runtime/runtime.cc:366]   at com.android.okhttp.okio.AsyncTimeout.awaitTimeout(AsyncTimeout.java:323)
11-15 17:52:38.306 26186-27193/ A/art: art/runtime/runtime.cc:366]   - locked <0x00285f3b> (a java.lang.Class<com.android.okhttp.okio.AsyncTimeout>)
11-15 17:52:38.306 26186-27193/ A/art: art/runtime/runtime.cc:366]   at com.android.okhttp.okio.AsyncTimeout.access$000(AsyncTimeout.java:40)
11-15 17:52:38.306 26186-27193/ A/art: art/runtime/runtime.cc:366]   at com.android.okhttp.okio.AsyncTimeout$Watchdog.run(AsyncTimeout.java:286)
11-15 17:52:38.306 26186-27193/ A/art: art/runtime/runtime.cc:366] "OkHttp ConnectionPool" prio=5 tid=36 TimedWaiting
11-15 17:52:38.306 26186-27193/ A/art: art/runtime/runtime.cc:366]   - waiting on <0x070aa3b1> (a com.android.okhttp.ConnectionPool)
11-15 17:52:38.306 26186-27193/ A/art: art/runtime/runtime.cc:366]   at com.android.okhttp.ConnectionPool.performCleanup(ConnectionPool.java:319)
11-15 17:52:38.306 26186-27193/ A/art: art/runtime/runtime.cc:366]   - locked <0x070aa3b1> (a com.android.okhttp.ConnectionPool)
11-15 17:52:38.306 26186-27193/ A/art: art/runtime/runtime.cc:366]   at com.android.okhttp.ConnectionPool.runCleanupUntilPoolIsEmpty(ConnectionPool.java:256)
11-15 17:52:38.306 26186-27193/ A/art: art/runtime/runtime.cc:366]   at com.android.okhttp.ConnectionPool.access$000(ConnectionPool.java:59)
11-15 17:52:38.306 26186-27193/ A/art: art/runtime/runtime.cc:366]   at com.android.okhttp.ConnectionPool$1.run(ConnectionPool.java:102)
11-15 17:52:38.306 26186-27193/ A/art: art/runtime/runtime.cc:366] "OkHttp Dispatcher" prio=5 tid=42 TimedWaiting
11-15 17:52:38.306 26186-27193/ A/art: art/runtime/runtime.cc:366] "OkHttp ConnectionPool" prio=5 tid=43 TimedWaiting
11-15 17:52:38.306 26186-27193/ A/art: art/runtime/runtime.cc:366]   - waiting on <0x068e6022> (a okhttp3.ConnectionPool)
11-15 17:52:38.306 26186-27193/ A/art: art/runtime/runtime.cc:366]   at okhttp3.ConnectionPool$1.run(ConnectionPool.java:65)
11-15 17:52:38.306 26186-27193/ A/art: art/runtime/runtime.cc:366]   - locked <0x068e6022> (a okhttp3.ConnectionPool)
11-15 17:52:38.306 26186-27193/ A/art: art/runtime/runtime.cc:366] "OkHttp Dispatcher" prio=5 tid=56 TimedWaiting
11-15 17:52:38.306 26186-27193/ A/art: art/runtime/runtime.cc:366]   at okhttp3.internal.http.Http1xStream$FixedLengthSource.read(Http1xStream.java:381)
11-15 17:52:38.306 26186-27193/ A/art: art/runtime/runtime.cc:366]   at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:225)
11-15 17:52:38.306 26186-27193/ A/art: art/runtime/runtime.cc:366]   at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:187)
11-15 17:52:38.306 26186-27193/ A/art: art/runtime/runtime.cc:366]   at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:160)
11-15 17:52:38.306 26186-27193/ A/art: art/runtime/runtime.cc:366]   at okhttp3.RealCall.execute(RealCall.java:57)
11-15 17:52:38.306 26186-27193/ A/art: art/runtime/runtime.cc:366]   at retrofit2.OkHttpCall.execute(OkHttpCall.java:174)
11-15 17:52:38.306 26186-27193/ A/art: art/runtime/runtime.cc:366] "OkHttp ConnectionPool" prio=5 tid=60 TimedWaiting
11-15 17:52:38.306 26186-27193/ A/art: art/runtime/runtime.cc:366]   - waiting on <0x091276a3> (a okhttp3.ConnectionPool)
11-15 17:52:38.306 26186-27193/ A/art: art/runtime/runtime.cc:366]   at okhttp3.ConnectionPool$1.run(ConnectionPool.java:65)
11-15 17:52:38.306 26186-27193/ A/art: art/runtime/runtime.cc:366]   - locked <0x091276a3> (a okhttp3.ConnectionPool)
11-15 17:52:38.306 26186-27193/ A/art: art/runtime/runtime.cc:366] "OkHttp Dispatcher" prio=5 tid=67 TimedWaiting
11-15 17:52:38.306 26186-27193/ A/art: art/runtime/runtime.cc:366] "OkHttp Dispatcher" prio=5 tid=68 TimedWaiting
11-15 17:52:38.306 26186-27193/ A/art: art/runtime/runtime.cc:366] "OkHttp ConnectionPool" prio=5 tid=78 TimedWaiting
11-15 17:52:38.306 26186-27193/ A/art: art/runtime/runtime.cc:366]   - waiting on <0x093f8d2a> (a okhttp3.ConnectionPool)
11-15 17:52:38.306 26186-27193/ A/art: art/runtime/runtime.cc:366]   at okhttp3.ConnectionPool$1.run(ConnectionPool.java:65)
11-15 17:52:38.306 26186-27193/ A/art: art/runtime/runtime.cc:366]   - locked <0x093f8d2a> (a okhttp3.ConnectionPool)
11-15 17:52:38.306 26186-27193/ A/art: art/runtime/runtime.cc:366] "OkHttp Dispatcher" prio=5 tid=86 TimedWaiting
11-15 17:52:38.316 26186-27193/ A/art: art/runtime/runtime.cc:366]   at com.android.okhttp.okio.Okio$2.read(Okio.java:140)
11-15 17:52:38.316 26186-27193/ A/art: art/runtime/runtime.cc:366]   at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:211)
11-15 17:52:38.316 26186-27193/ A/art: art/runtime/runtime.cc:366]   at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:316)
11-15 17:52:38.316 26186-27193/ A/art: art/runtime/runtime.cc:366]   at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:310)
11-15 17:52:38.316 26186-27193/ A/art: art/runtime/runtime.cc:366]   at com.android.okhttp.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:206)
11-15 17:52:38.316 26186-27193/ A/art: art/runtime/runtime.cc:366]   at com.android.okhttp.internal.http.HttpConnection.readResponse(HttpConnection.java:243)
11-15 17:52:38.316 26186-27193/ A/art: art/runtime/runtime.cc:366]   at com.android.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:104)
11-15 17:52:38.316 26186-27193/ A/art: art/runtime/runtime.cc:366]   at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:1149)
11-15 17:52:38.316 26186-27193/ A/art: art/runtime/runtime.cc:366]   at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:980)
11-15 17:52:38.316 26186-27193/ A/art: art/runtime/runtime.cc:366]   at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:474)
11-15 17:52:38.316 26186-27193/ A/art: art/runtime/runtime.cc:366]   at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:410)
11-15 17:52:38.316 26186-27193/ A/art: art/runtime/runtime.cc:366]   at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:532)
11-15 17:52:38.316 26186-27193/ A/art: art/runtime/runtime.cc:366]   at com.umeng.socialize.net.utils.UClient.httpPostRequest(UClient.java:172)
11-15 17:52:38.316 26186-27193/ A/art: art/runtime/runtime.cc:366] "RefQueueWorker@org.apache.http.impl.conn.tsccm.ConnPoolByRoute@a233c5f" prio=5 tid=118 Waiting
11-15 17:52:38.316 26186-27193/ A/art: art/runtime/runtime.cc:366]   at org.apache.http.impl.conn.tsccm.RefQueueWorker.run(RefQueueWorker.java:107)
11-15 17:52:38.316 26186-27193/ A/art: art/runtime/runtime.cc:366] "RefQueueWorker@org.apache.http.impl.conn.tsccm.ConnPoolByRoute@d21aee3" prio=5 tid=96 Waiting
11-15 17:52:38.316 26186-27193/ A/art: art/runtime/runtime.cc:366]   at org.apache.http.impl.conn.tsccm.RefQueueWorker.run(RefQueueWorker.java:107)
11-15 17:52:38.316 26186-27193/ A/art: art/runtime/runtime.cc:366] "RefQueueWorker@org.apache.http.impl.conn.tsccm.ConnPoolByRoute@68c3210" prio=5 tid=101 Waiting
11-15 17:52:38.316 26186-27193/ A/art: art/runtime/runtime.cc:366]   at org.apache.http.impl.conn.tsccm.RefQueueWorker.run(RefQueueWorker.java:107)
11-15 17:52:38.316 26186-27193/ A/art: art/runtime/runtime.cc:366]   at org.apache.http.impl.io.AbstractSessionInputBuffer.fillBuffer(AbstractSessionInputBuffer.java:108)
11-15 17:52:38.316 26186-27193/ A/art: art/runtime/runtime.cc:366]   at org.apache.http.impl.io.AbstractSessionInputBuffer.read(AbstractSessionInputBuffer.java:139)
11-15 17:52:38.316 26186-27193/ A/art: art/runtime/runtime.cc:366]   at org.apache.http.impl.io.ChunkedInputStream.read(ChunkedInputStream.java:166)
11-15 17:52:38.316 26186-27193/ A/art: art/runtime/runtime.cc:366]   at org.apache.http.conn.EofSensorInputStream.read(EofSensorInputStream.java:164)
11-15 17:52:38.316 26186-27193/ A/art: art/runtime/runtime.cc:366]   - locked <0x0699e532> (a org.apache.http.conn.EofSensorInputStream)
11-15 17:52:38.316 26186-27193/ A/art: art/runtime/runtime.cc:366]   at org.apache.http.util.EntityUtils.toString(EntityUtils.java:140)
11-15 17:52:38.316 26186-27193/ A/art: art/runtime/runtime.cc:366]   at org.apache.http.util.EntityUtils.toString(EntityUtils.java:151)
11-15 17:52:38.316 26186-27193/ A/art: art/runtime/runtime.cc:366] "RefQueueWorker@org.apache.http.impl.conn.tsccm.ConnPoolByRoute@eea5f3c" prio=5 tid=119 Waiting
11-15 17:52:38.316 26186-27193/ A/art: art/runtime/runtime.cc:366]   at org.apache.http.impl.conn.tsccm.RefQueueWorker.run(RefQueueWorker.java:107)

**Comment by swankjesse** [comment]
Could you provide an executable test case? This is just a thread dump without any failure.

**Comment by maoaixianyu** [comment]
sorry, this is not still appearing. If this is appearing, I will told you. Thanks.
