### ISSUE TITLE
Cookie.java Removing a leading dot from cookie domain makes it unable to be used for subdomains

### ISSUE THREAD

**Issue by metalurgus** [square/okhttp#2985]
[https://github.com/square/okhttp/blob/59e70dad8193ad5f8cd79749fc00be7dcf0308d1/okhttp/src/main/java/okhttp3/Cookie.java#L421](url)

On this line the leading dot of the cookie domain is removed permanently, and we are unable to see if the cookie should be used on subdomains. 
Example: 
I perform a request for `www.site.com/login`. In response it returns me `Set-Cookie` with `domain=.site.com`. 
After parsing, cookie is stored with a domain `site.com`, which makes it non-usable even for `www.site.com`
AFAIK, it does not match cookie specification.

**Comment by swankjesse** [comment]
The specs were revised and the leading dot was dropped as a feature. Today cookies whose domain is `example.com` will domain match `foo.example.com` dot or no dot.
https://tools.ietf.org/html/rfc6265#section-4.1.2.3
https://tools.ietf.org/html/rfc6265#section-5.1.3

**Comment by swankjesse** [comment]
BTW, you can use this to check for a domain match. It’s a bit subtle.
https://square.github.io/okhttp/3.x/okhttp/okhttp3/Cookie.html#matches-okhttp3.HttpUrl-

**Comment by metalurgus** [comment]
then it themes like Android SDK bug. 
I've opened this issue because I was trying to use `JavaNetCookieJar`, with a default `CookieManager`. And it will not use cookies for `foo.example.com`, if cookie domain was originally `.example.com`

**Comment by swankjesse** [comment]
Got it. If there's a failing test we can fix, I'm interested.

**Comment by changety** [comment]
@metalurgus ,  I meet the same problem，if the cookie's domain is not hostOnly, the OKHttp will remove the leading dot, but the android's CookieManager do not implement the new RFC specs. So what your work around?
