### ISSUE TITLE
heads up: fragile code around ConnectionPool.cleanup() could break in future such that it might evict active connections

### ISSUE THREAD

**Issue by 15characterlimi** [square/okhttp#2986]
I believe this is not a bug in current code but it is fragile so I wanted to make you aware of it:

For RealConnections that are not idle, the field idleAtNanos currently has the bogus value Long.MAX_VALUE which it is initialized to.

I *think* no code currently reads this bogus value because ConnectionPool.cleanup(long) checks for idle-ness first and only continues to read the value of idleAtNanos if the connection is idle.

However this is fragile because:
 - idleAtNanos is expressed in terms of System.nanoTime(), so Long.MAX_VALUE is not an absolute timestamp; System.nanoTime() is not guaranteed to be positive / negative so Long.MAX_VALUE might be the current time or arbitrarily far in the past or future.
 - idleAtNanos is currently public, so it's easy to introduce buggy code that reads the value of idleAtNanos for a connection that is not actually idle.

I suggest you make the field private and give it an accessor that
 - throws if the connection is not idle, and
 - requires the caller to hold the lock to prevent concurrent changes to idle-ness

Alternatively, you could just initialize the field to some time in the future, such as System.nanoTime() + Long.MAX_VALUE / 2, but that'd be harder to test / avoid regressions for.

While I'm not actively affected by this, I'd be happy to send you a pull request if you let me know your preference.

**Comment by swankjesse** [comment]
Yeah, this stuff is fragile.

We should probably write a doc around stream allocations, the connection pool, and connections to explain what locks we have and what is guarded by what. In this case idleAtNanos is guarded by the connection pool, which is certainly pretty weird.

We’ve got an equivalent doc for HTTP/2 concurrency and I like being able to separate the rules from the implementation. That way we can reason that the rules are consistent and safe, and that the implementation matches the rules. Reasoning about whether the implementation is safe is very difficult!

**Comment by 15characterlimi** [comment]
Cool, as long as you're aware - feel free to close this issue if you don't think it requires any action right now.

I was investigating a separate issue today that was caused by a use of Long.MAX_VALUE under the mistaken assumption that it represented a time in the future, so I wanted to make you aware that RealConnection is still doing this today (although the value is "dead" and never read).

**Comment by swankjesse** [comment]
Cool. I try to be pretty careful to never do anything with nanoTimes other than subtract ’em and compare the difference to an expected duration.
