### ISSUE TITLE
WebSocket automatic pings

### ISSUE THREAD

**Issue by swankjesse** [square/okhttp#2993]
I’d like an API where users set an interval (say 60 seconds) and our websocket automatically pings on that frequency until it is closed or canceled.

**Comment by dlew** [comment]
Would it be set in the `Request`? If so, that'd be a weird setting for any `Request` that's not web sockets-related.

**Comment by swankjesse** [comment]
I was thinking it’d be configuration on the OkHttpClient.

**Comment by dlew** [comment]
That sounds good to me.

**Comment by gengjiawen** [comment]
@swankjesse Hi, I am migrating websocket from 3.4 to 3.5, now we can send ping automatically using okhttp client.But how do i know websocket get pong from server? There is used to be a `onPong` method in WebsocketListener.

**Comment by JakeWharton** [comment]
Automatic pings and pongs are not surfaced to the application layer.

**Comment by gengjiawen** [comment]
Is it still possiable I can send ping and handle pong in `okhttp 3.5`.For now I use keep sending ping mechanism to ensure I the websocket is connected and reconnect when run into network exception or other crash.

**Comment by swankjesse** [comment]
We’ll notify you with an onFailure if that occurs.

**Comment by gengjiawen** [comment]
But I tested on genymotion the onFailure not called when I entre airplane model after 1min or so.But the websocket is actually closed.

**Comment by gengjiawen** [comment]
Here is my okhttp client.Do i need to set connectionTimeout to make `onFailure` reliable?
```java
    private OkHttpClient client = new OkHttpClient.Builder()
            .readTimeout(0, TimeUnit.SECONDS)
            .writeTimeout(0, TimeUnit.SECONDS)
            .build();
```

**Comment by gengjiawen** [comment]
Found another thing ,you get no exception when sending ping even if your network not available.

**Comment by JakeWharton** [comment]
File separate bugs. Preferably with test cases if possible. Commenting here
won't get things done.
