### ISSUE TITLE
 java.lang.SecurityException:Permission denied (missing INTERNET permission?)

### ISSUE THREAD

**Issue by huangyanan** [square/okhttp#3003]
i have use okhttp 3.1.4 in my android app.it happend less than 0.0001,can any one help me? the log is blow:

> 1 java.lang.SecurityException:Permission denied (missing INTERNET permission?)
> 2 java.net.InetAddress.lookupHostByName(InetAddress.java:430)
> 3 ......
> 4 Caused by:
> 5 libcore.io.ErrnoException:getaddrinfo failed: EACCES (Permission denied)
> 6 libcore.io.Posix.getaddrinfo(Native Method)
> 7 libcore.io.ForwardingOs.getaddrinfo(ForwardingOs.java:59)
> 8 java.net.InetAddress.lookupHostByName(InetAddress.java:405)
> 9 java.net.InetAddress.getAllByNameImpl(InetAddress.java:236)
> 10 java.net.InetAddress.getAllByName(InetAddress.java:214)
> 11 okhttp3.o$1.a(Dns.java:39)
> 12 okhttp3.internal.connection.e.a(RouteSelector.java:172)
> 13 okhttp3.internal.connection.e.d(RouteSelector.java:138)
> 14 okhttp3.internal.connection.e.b(RouteSelector.java:80)
> 15 okhttp3.internal.connection.f.a(StreamAllocation.java:178)
> 16 okhttp3.internal.connection.f.a(StreamAllocation.java:129)
> 17 okhttp3.internal.connection.f.a(StreamAllocation.java:98)
> 18 okhttp3.internal.connection.a.intercept(ConnectInterceptor.java:42)
> 19 okhttp3.internal.b.i.a(RealInterceptorChain.java:92)
> 20 okhttp3.internal.b.i.a(RealInterceptorChain.java:67)
> 21 okhttp3.internal.a.a.intercept(CacheInterceptor.java:109)
> 22 okhttp3.internal.b.i.a(RealInterceptorChain.java:92)
> 23 okhttp3.internal.b.i.a(RealInterceptorChain.java:67)
> 24 okhttp3.internal.b.a.intercept(BridgeInterceptor.java:93)
> 25 okhttp3.internal.b.i.a(RealInterceptorChain.java:92)
> 26 okhttp3.internal.b.l.intercept(RetryAndFollowUpInterceptor.java:124)
> 27 okhttp3.internal.b.i.a(RealInterceptorChain.java:92)
> 28 okhttp3.internal.b.i.a(RealInterceptorChain.java:67)
> 29 com.husor.android.net.b.a.intercept(HttpDNSInterceptor.java:47)
> 30 okhttp3.internal.b.i.a(RealInterceptorChain.java:92)
> 31 okhttp3.internal.b.i.a(RealInterceptorChain.java:67)
> 32 com.husor.android.net.b.b.intercept(HttpUrlInterceptor.java:48)
> 33 okhttp3.internal.b.i.a(RealInterceptorChain.java:92)
> 34 okhttp3.internal.b.i.a(RealInterceptorChain.java:67)
> 35 okhttp3.x.g(RealCall.java:170)
> 36 okhttp3.x.a(RealCall.java:33)
> 37 okhttp3.x$a.c(RealCall.java:120)
> 38 okhttp3.internal.b.run(NamedRunnable.java:32)
> 39 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
> 40 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
> 41 java.lang.Thread.run(Thread.java:838)

**Comment by swankjesse** [comment]
Your users have hacked their devices to selectively revoke Internet permission. Nothing we can do to help here.

**Comment by huangyanan** [comment]
thanks

**Comment by tenggangren** [comment]
oh , 我的也报错很多，也是这个crash ， 怎么修复？

**Comment by linyongsheng** [comment]
@swankjesse this crash can catch by okhttp inside?

**Comment by xiangjt** [comment]
i also have this crash

**Comment by iNoles** [comment]
@lalbuquerque why not to have your code catch it?

**Comment by songliao-branch** [comment]
any updates on this?  I am receiving thousands of this crashes on Infinix devices
