### ISSUE TITLE
Caching "isSuccessful() == false" Responses (Response Code 404)

### ISSUE THREAD

**Issue by jkane001** [square/okhttp#3020]
It seems that responses that come back with "isSuccessful() == false" get cached, and I think that shouldn't be the case. The response code that came back in this case was 404.

According to the HTTP spec (https://www.w3.org/Protocols/rfc2616/rfc2616-sec13.html), only the following response codes MAY be cached: 200, 203, 206, 300, 301 or 410

---------------------------

13.4 Response Cacheability

Unless specifically constrained by a cache-control (section 14.9) directive, a caching system MAY always store a successful response (see section 13.8) as a cache entry, MAY return it without validation if it is fresh, and MAY return it after successful validation. If there is neither a cache validator nor an explicit expiration time associated with a response, we do not expect it to be cached, but certain caches MAY violate this expectation (for example, when little or no network connectivity is available). A client can usually detect that such a response was taken from a cache by comparing the Date header to the current time.

Note: some HTTP/1.0 caches are known to violate this expectation without providing any Warning.
However, in some cases it might be inappropriate for a cache to retain an entity, or to return it in response to a subsequent request. This might be because absolute semantic transparency is deemed necessary by the service author, or because of security or privacy considerations. Certain cache-control directives are therefore provided so that the server can indicate that certain resource entities, or portions thereof, are not to be cached regardless of other considerations.

Note that section 14.8 normally prevents a shared cache from saving and returning a response to a previous request if that request included an Authorization header.

A response received with a status code of 200, 203, 206, 300, 301 or 410 MAY be stored by a cache and used in reply to a subsequent request, subject to the expiration mechanism, unless a cache-control directive prohibits caching. However, a cache that does not support the Range and Content-Range headers MUST NOT cache 206 (Partial Content) responses.

A response received with any other status code (e.g. status codes 302 and 307) MUST NOT be returned in a reply to a subsequent request unless there are cache-control directives or another header(s) that explicitly allow it. For example, these include the following: an Expires header (section 14.21); a "max-age", "s-maxage", "must- revalidate", "proxy-revalidate", "public" or "private" cache-control directive (section 14.9).

**Comment by jkane001** [comment]
Wasn't ready to submit yet, but hit Enter and it submitted - sorry, will edit and reopen when ready.

**Comment by jkane001** [comment]
Now it's ready

**Comment by swankjesse** [comment]
The spec you’re citing has been obsoleted by RFC 7234, which states the following:

> “However, it is also possible to cache permanent redirects, negative results (e.g., 404 (Not Found)), incomplete results (e.g., 206 (Partial Content)), and responses to methods other than GET if the method's definition allows such caching and defines something suitable for use as a cache key.”

https://tools.ietf.org/html/rfc7234#section-6.1

**Comment by swankjesse** [comment]
Closing ’cause there’s no action for us to take on this. If you’d like to provide a test case to demonstrate a specific request/response pair we’re doing incorrectly, we can fix.

Here’s a simple-enough test to get you started.
https://github.com/square/okhttp/blob/master/okhttp-tests/src/test/java/okhttp3/CacheTest.java#L943

**Comment by jkane001** [comment]
it's there any way to make that configurable - so a dev could set the client to only cache successful responses?

**Comment by swankjesse** [comment]
You could add a network interceptor to add a `Cache-Control: no-store` header on the response if you don’t like the status code.

https://github.com/square/okhttp/blob/master/okhttp/src/main/java/okhttp3/internal/cache/CacheStrategy.java#L62

**Comment by jkane001** [comment]
perfect, thanks
