### ISSUE TITLE
no-cache="field-name" is not handled

### ISSUE THREAD

**Issue by 1zaman** [square/okhttp#3022]
The no-cache response directive can [specify][1] field names, in which case it should be interpreted as only excluding those specific header fields from being cached. However, this is currently being handled just like the unqualified directive, i.e. by excluding the whole response from being cached.

[1]: https://tools.ietf.org/html/rfc7234#section-5.2.2.2

**Comment by swankjesse** [comment]
Seems reasonable enough. Can do.

**Comment by 1zaman** [comment]
Great! I guess these fields can just be stripped out as the response is being served from the cache, and can still be be stored in cache, to be served in the case of successful revalidation (just like how the unqualified directive is handled). This seems like a simple change overall, and I'll see if I can contribute a pull request in a couple of days when I get some free time.

**Comment by swankjesse** [comment]
Needs some attention.

**Comment by yschimke** [comment]
Closing as low priority, re-open if impacting you.
