### ISSUE TITLE
Error  java.net.ProtocolException: expected 6682 bytes but received 7154

### ISSUE THREAD

**Issue by luigidefrancesco** [square/okhttp#3023]
Hi to all,

when in my java application I try to send a file to PHP server, in logcat I see:

`12-06 16:09:41.050 * W/System.err: java.net.ProtocolException: expected 6682 bytes but received 7154
12-06 16:09:41.070 * W/System.err:     at okhttp3.internal.http1.Http1Codec$FixedLengthSink.write(Http1Codec.java:284)
12-06 16:09:41.070 * W/System.err:     at okio.RealBufferedSink.close(RealBufferedSink.java:229)
12-06 16:09:41.070 * W/System.err:     at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:49)
12-06 16:09:41.070 * W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
12-06 16:09:41.070 * W/System.err:     at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
12-06 16:09:41.070 * W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
12-06 16:09:41.070 * W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
12-06 16:09:41.070 * W/System.err:     at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
12-06 16:09:41.070 * W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
12-06 16:09:41.070 * W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
12-06 16:09:41.070 * W/System.err:     at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
12-06 16:09:41.070 * W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
12-06 16:09:41.070 * W/System.err:     at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
12-06 16:09:41.070 * W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
12-06 16:09:41.070 * W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
12-06 16:09:41.090 * W/System.err:     at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:179)
12-06 16:09:41.090 * W/System.err:     at okhttp3.RealCall.execute(RealCall.java:63)`

But file Is successfully sended to server. 

Another problem is that multiple errors cause app to crash. How can I solve this issue?

**Comment by swankjesse** [comment]
You’re specifying the wrong content-length in your request body. If you continue to have problems please provide an executable test case that demonstrates the problem.

**Comment by gewuxy** [comment]
I record audio and encode it to mp3 using lame in another thread,when reach 60s,I send the file automatically,sometimes I get this error

**Comment by gewuxy** [comment]
How can I know if the file is written completely?

**Comment by MichaelReyes** [comment]
Hello, I'm encountering the same error when uploading video. 
java.net.ProtocolException: expected 660 bytes but received 2048.

here is my code: 
`public static void uploadVideo(Context context, File file) {

        ServiceGenerator serviceGenerator = new ServiceGenerator(context, Constants.SERVER_URL, HttpLoggingInterceptor.Level.BODY);
        CommandAPI commandAPI = serviceGenerator.createService(CommandAPI.class);

        User user = User.getUserFromSharedPreferences(context);

        RequestBody videoBody = RequestBody.create(MediaType.parse("video/*"), file);
        MultipartBody.Part archiveFile = MultipartBody.Part.createFormData("video", file.getName(), videoBody);

        RequestBody accesscode = serviceGenerator.createPartFromString(user.getAccessCode());
        RequestBody accel = serviceGenerator.createPartFromString("");
        RequestBody alert_battery_level = serviceGenerator.createPartFromString("");
        RequestBody alert_gps_files = serviceGenerator.createPartFromString("");
        RequestBody alert_media_files = serviceGenerator.createPartFromString("");
        RequestBody alert_speed = serviceGenerator.createPartFromString("");
        RequestBody course = serviceGenerator.createPartFromString("");
        RequestBody direction = serviceGenerator.createPartFromString("");
        RequestBody elevation = serviceGenerator.createPartFromString("");
        RequestBody event_id = serviceGenerator.createPartFromString("1");
        RequestBody lat = serviceGenerator.createPartFromString(String.valueOf(user.getLat()));
        RequestBody lng = serviceGenerator.createPartFromString(String.valueOf(user.getLon()));
        RequestBody level = serviceGenerator.createPartFromString("");
        RequestBody location_now = serviceGenerator.createPartFromString("");
        RequestBody online_status = serviceGenerator.createPartFromString("");


        HashMap<String, RequestBody> map = new HashMap<>();
        map.put("accesscode", accesscode);
        map.put("accel", accel);
        map.put("alert_battery_level", alert_battery_level);
        map.put("alert_gps_files", alert_gps_files);
        map.put("alert_media_files", alert_media_files);
        map.put("alert_speed", alert_speed);
        map.put("course", course);
        map.put("direction", direction);
        map.put("elevation", elevation);
        map.put("event_id", event_id);
        map.put("lat", lat);
        map.put("lng", lng);
        map.put("level", level);
        map.put("location_now", location_now);
        map.put("online_status", online_status);

        Call<ResponseBody> call = commandAPI.uploadVideo(archiveFile, map);

        try {
            Response<ResponseBody> response = call.execute();
            ResponseBody responseBody = response.body();

            Log.d("MIKE", "responseBody: " + new Gson().toJson(responseBody));

        } catch (Exception e) {
            e.printStackTrace();
        }

    }`

`@Multipart
    @POST("upload/video")
    Call<ResponseBody> uploadVideo(
            @Part MultipartBody.Part video,
            @PartMap() Map<String, RequestBody> partMap
    );`

whats wrong with my code? please help.

**Comment by yefl2064** [comment]
@MichaelReyes i got the same error； check  the video file is modified by other thread when uploading

**Comment by Kevin1ee** [comment]
it did not happen again after move the file to External Storage from Application Cache.

**Comment by dinukapj** [comment]
Occurring when uploading an image captured from the camera

**Comment by filipatbnp** [comment]
same here when uploading file which is an image just captured from the camera and saved to `context.getExternalFilesDir(Environment.DIRECTORY_DOWNLOADS`

**Comment by filipatbnp** [comment]
and this is the answer why (my fault):
https://stackoverflow.com/a/45033270

> After studying for a while the problem I've realized that the content of the file was always changing (as it is the output of a sensor).

It means that the file that is checked for the HEAD and the file for the BODY may not contain the same data (therefore different length), which caused the mismatch.

I solved this [creating a copy](https://stackoverflow.com/questions/9292954/how-to-make-a-copy-of-a-file-in-android) of the file and sending it (the copy) instead of the original file.

**Comment by CCTV-11** [comment]
没有人告诉我有啥解决方案嘛？
