### ISSUE TITLE
Omit Platform class name from HttpLoggingInterceptor

### ISSUE THREAD

**Issue by cachapa** [square/okhttp#3024]
I just upgraded from OkHttp 3.2 to 3.5 and my logs are now barely readable due to every line being prefixed with the internal Platform class name.
This is happening only on my pure Java Unit Tests. On Android the logs look exactly the same.

Where previously I had:
```
INFO: --> POST https://my-url.com/resource http/1.1
INFO: Content-Type: application/json; charset=utf-8
INFO: Content-Length: 97
[...]
```

I now have:
```
Dec 06, 2016 4:44:43 PM okhttp3.internal.platform.Platform log
INFO: --> POST https://my-url.com/resource http/1.1
Dec 06, 2016 4:44:43 PM okhttp3.internal.platform.Platform log
INFO: Content-Type: application/json; charset=utf-8
Dec 06, 2016 4:44:43 PM okhttp3.internal.platform.Platform log
INFO: Content-Length: 97
[...]
```

Furthermore the log text is now red, even for successful operations, which makes it look like my tests failed at first glance. On 3.2 the log text was white.

**Comment by JakeWharton** [comment]
OkHttp doesn't control the log format nor the coloring on the JVM. As you can see we're logging at the INFO level so there's no reason for it to be red. As to the format we just pass information to `java.util.Logger` which you can customize the output of to suit your needs.

**Comment by cachapa** [comment]
I dove into the code and now understand why I was getting a different behaviour in previous versions: 3.2 was logging using a simple [`System.out.println()`](https://github.com/square/okhttp/blob/14eb077351a8f24e83cdac92930eff84d05e8787/okhttp/src/main/java/okhttp3/internal/Platform.java#L129).

I guess it makes no sense to argue for a revert, so I'll just create an alternative `HttpLoggingInterceptor` that produces more readable output for my use case.
Thanks for your feedback.
