### ISSUE TITLE
DNS over TLS

### ISSUE THREAD

**Issue by swankjesse** [square/okhttp#3027]
It’s a thing we could do.

https://tools.ietf.org/html/rfc7858

**Comment by yschimke** [comment]
Curious, what was the objective here? A full DNS implementation? or an implementation of okhttp3.Dns (strictly a subset) for securing OkHttp clients?

If its the latter, would it be worth submitting a dns-over-https implementation (https://tools.ietf.org/html/draft-hoffman-dns-over-http-00)?  This is a working prototype for dns.google.com https://github.com/yschimke/oksocial/blob/master/src/main/java/com/baulsupp/oksocial/network/GoogleDns.java

**Comment by yschimke** [comment]
This appears overtaken by DNS over HTTPS, is there much industry support for this?

**Comment by swankjesse** [comment]
DNS over HTTPS is best.
