### ISSUE TITLE
Android M java.net.PlainSocketImpl$PlainSocketInputStream vs Android N java.net.SocketInputStream?

### ISSUE THREAD

**Issue by NitzDKoder** [square/okhttp#3036]
Hi Folks,

In Android M java.net.Socket.getInputStream() gets the java.net.PlainSocketImpl$PlainSocketInputStream

whereas android N java.net.Socket.getInputStream() gets the  java.net.SocketInputStream

Whats is the implementation changes or behavioral changes of these 2 API's.

Problem:Reading from socket is stuck indefinitly in android N device.

App Design(https://github.com/square/okhttp/issues/2641):
1)Okhtp http library with connectionpool(TCP socket reuse) is used.
2)SSL is handled by WolfSSL by setting the FD.
https://www.wolfssl.com/documentation/wolfssl-jni-javadocs/com/wolfssl/WolfSSLSession.html#setFd-java.net.Socket-

3)Read is stuck in Android N when same socket is used to read data.

https://www.wolfssl.com/documentation/wolfssl-jni-javadocs/com/wolfssl/WolfSSLSession.html#read-byte:A-int-

4)By default, wolfSSL simply gets the internal file descriptor of the socket and does a native recv() call on that descriptor.Guess is that the behavior of PlainSocketInputStream and SocketInputStream differ, where SocketInputStream blocks.
https://github.com/wolfSSL/wolfssl/blob/master/src/io.c#L290

@swankjesse your thoughts on this?

PS: Above works in android < N.
 

Thanks
Nithin

**Comment by swankjesse** [comment]
Sounds like a bug in WolfSSL. Nothing we can fix at our layer.
