### ISSUE TITLE
More capable interceptor chains

### ISSUE THREAD

**Issue by swankjesse** [square/okhttp#3039]
It’d be handy if the interceptor’s chain could do more stuff:

 * [x] Tell if you if the call has been canceled
 * [x] Adjust timeouts

**Comment by realdeadfish** [comment]
Useful would also be to temporarily suppress redirection handling for certain requests, so a caller (or the interceptor implementation) can then actually decide on its own what to do with a 3xx response.

**Comment by swankjesse** [comment]
https://github.com/square/okhttp/pull/3557
