### ISSUE TITLE
Cache control does not respect HTTP headers.

### ISSUE THREAD

**Issue by gpor89** [square/okhttp#3041]
Making request with same url and different accept header returns previous response from okhttp cache.

This means that first request is made for application/json data, the second one requests application/xml. Client therefore returns json data from cache instead of doing xml upstream.

more information: https://www.w3.org/Protocols/rfc2616/rfc2616-sec13.html#sec13.6

here is a simple test https://gist.github.com/gpor89/c69c795b334af5ff63cef6468222a01e which need backend serving xml and json on same url with cache control.

**Comment by swankjesse** [comment]
Typically the server prevents this by including the following header in the response:

```
Vary: Accept
```

Adding a network interceptor that adds this to the response may allow you to work around the problem.

**Comment by gpor89** [comment]
It doesnt work.

Afaik Vary header tells which header fields should be avoided from cache key definition (RFC).
Therefore okhttp cache mechanism should use all header fields which are NOT in Vary header as cache key.

Unless i'm missing smth okhttp cache mechanism implements url only.

`public static String key(HttpUrl url) {
    return ByteString.encodeUtf8(url.toString()).md5().hex();
  }`

**Comment by JakeWharton** [comment]
The key maps a URL to a potential entry. The contents still must be read to
determine caching semantics.
