### ISSUE TITLE
MQTT support

### ISSUE THREAD

**Issue by vanshg** [square/okhttp#3043]
What kind of issue is this?

 - [x] Feature Request

MQTT is a lightweight messaging (pub-sub) protocol. Right now I'm using another dependency for this, but seeing as it is a networking protocol, it'd be a nice-to-have in the OkHttp dependency itself, so that I don't need another one. 

Here is the dependency I currently use:
https://github.com/eclipse/paho.mqtt.android

**Comment by swankjesse** [comment]
Unlikely we’ll do this. We wanna stay focused on HTTP.

**Comment by radityagumay** [comment]
@swankjesse do yo change your mind?

**Comment by swankjesse** [comment]
No. OkHttp is broad enough in scope!

**Comment by yayuntian** [comment]
@swankjesse  we need help, can you give some advice for okhttp + mqtt

**Comment by radityagumay** [comment]
> @swankjesse we need help, can you give some advice for okhttp + mqtt

at @gojek we create an abstraction on top of Paho. which you can see at https://github.com/gojek/courier-android
