### ISSUE TITLE
Extensions 'sni' setting error.

### ISSUE THREAD

**Issue by sandking** [square/okhttp#3049]
I found that okhttp3 will set the 'sni' automatically.

In `RealConnection.java` method `connectTls`

`

       if (connectionSpec.supportsTlsExtensions()) {

            Platform.get().configureTlsExtensions(sslSocket, address.url().host(), address.protocols());

       }
`

It will invoke the `configureTlsExtensions` 

And , it will select the platform by `private static Platform findPlatform()` in `Platform.java`

On Android Platform , `AndroidPlatform.java`

`

       @Override public void configureTlsExtensions(SSLSocket sslSocket, String hostname, List<Protocol> protocols) {

    // Enable SNI and session tickets.

    if (hostname != null) {

      setUseSessionTickets.invokeOptionalWithoutCheckedException(sslSocket, true);

      setHostname.invokeOptionalWithoutCheckedException(sslSocket, hostname);

    }
`

It will set the `SNI` by `url.host()`.

But , when we use 'httpDns' ,request the server by ip and set the request header for 'hos'

And we want to use the `host` which in request headers. instead of `url.host()`

**Comment by swankjesse** [comment]
Make sure the URL host is right. If you want to muck with DNS implement the Dns interface.
