### ISSUE TITLE
How to set the 'sni' myself

### ISSUE THREAD

**Issue by sandking** [square/okhttp#3050]
The issue with : https://github.com/square/okhttp/issues/3049

Sometimes , The url is "https://10.10.10.10" , and then OkHttp will get the host with '10.10.10.10' and now the 'sni' is '10.10.10.10' , But the server can't find the certification by the ip '10.10.10.10'.

My question is , Can i set the sni by myself.

**Comment by swankjesse** [comment]
The SNI must be the host of the URL.

**Comment by sandking** [comment]
hi swankjesse.

In China , We should request the server by IP , but the SNI should be Domain.

Now okhttp will set the sni automatically . when we use the IP request such as 'https://10.10.10.10' but it's domain is 'www.xx.com' . we can just load the correct certificate by setting the Domain sni.

**Comment by sandking** [comment]
@swankjesse

**Comment by maqzi** [comment]
@sandking were you able to set the SNI yourself?

**Comment by sandking** [comment]
@maqzi yes , i changed the source code.
