### ISSUE TITLE
Can't get OkHttp to use http2

### ISSUE THREAD

**Issue by animeshjain** [square/okhttp#3051]
I have tried two devices (both running android 6.0.1) but when I look at the debug logs generated by OkHttp logging interceptor I always see an HTTP/1.1 connection being used, despite my endpoint (say example.com) supporting HTTP2.

I have confirmed that the endpoint is supporting HTTP2 using the following commands

`echo | openssl s_client -alpn h2 -connect example.com:443 | grep ALPN`

returns

```
verify return:1
ALPN protocol: h2
```

`echo | openssl s_client -nextprotoneg h2 -connect example.com:443`

returns

```
Expansion: NONE
Next protocol: (1) h2
No ALPN negotiated
```

When I hit the endpoint using Chrome browser on the desktop, and HTTP2 connection is used.

I'm using retrofit to call my API's at example.com. I am using the default values of OkHttp and here's a snippet of code to show how I am building the OkHttp client

```
HttpLoggingInterceptor interceptor = new HttpLoggingInterceptor();
interceptor.setLevel(HttpLoggingInterceptor.Level.BODY);

OkHttpClient.Builder builder = new OkHttpClient.Builder().cache(cache);
builder.networkInterceptors().add(interceptor);

OkHttpClient client = builder.build();
```

Here's a sample debug log from my logging interceptor output when I call a sample API endpoint (via retrofit)

`D/OkHttp: --> GET https://example.com/sample http/1.1`

I have gone through a number of links on stackoverflow but haven't really seen if there are any specific instructions to getting http2 to work. Most seem to suggest that http2 should work on Android 5 and above.

Let me know what extra information I can provide.

**Comment by animeshjain** [comment]
My bad. I got it to work. It was a silly mistake and I was hitting an API which was not http2.

**Comment by bogdanRada** [comment]
i am trying to make this work also. Can you please tell me how did you fixed it?

**Comment by animeshjain** [comment]
Hi Rada

My issue happened because of an incorrect nginx config as far as I
remember. OkHttp is working as expected.

On May 25, 2017 8:23 PM, "rada bogdan raul" <notifications@github.com>
wrote:

i am trying to make this work also. Can you please tell me how did you
fixed it?

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/square/okhttp/issues/3051#issuecomment-304030429>, or mute
the thread

**Comment by bogdanRada** [comment]
i am using nginx also so i guess i made same mistake there. Thanks for getting back so quickly. Will dig into nginx configuration :) Thanks a lot

**Comment by animeshjain** [comment]
No problem. I'll check mine and see if I remember something about what was
wrong. Can't quite remember.

**Comment by artem-zinnatullin** [comment]
Ngnix has to be 1.9.5+ and you have to explicitly enable http2 by adding
"http2" to "listen" directive.

**Comment by bogdanRada** [comment]
ok. thank you very much :)
