### ISSUE TITLE
java.util.NoSuchElementException,"nulljava.util.AbstractList$SimpleListIterator.next(AbstractList.java:59)

### ISSUE THREAD

**Issue by YongHuiLuo** [square/okhttp#3052]
Excuse me ，I use HttpURLConnection to do network connection operation，The following code：
```
  connection = (HttpURLConnection) postUrl.openConnection();
  setHeaders(connection);
  connection.connect();
```
But appeared the following exception：
```
,java.util.NoSuchElementException,"nulljava.util.AbstractList$SimpleListIterator.next(AbstractList.java:59)
com.android.okhttp.internal.http.RouteSelector.nextProxy(RouteSelector.java:184)
com.android.okhttp.internal.http.RouteSelector.next(RouteSelector.java:121)
com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:292)
com.android.okhttp.internal.http.HttpEngine.sendSocketRequest(HttpEngine.java:255)
com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java206)
com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java：345)
com.android.okhttp.internal.http.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:89)
```
Help me have a look at what causes trouble, is the problem that I use or okhttp original legacy。

Thanks

**Comment by swankjesse** [comment]
My assumption is that your ProxySelector is misbehaving. How’s your HTTP proxy configured?

**Comment by YongHuiLuo** [comment]
First of all, thank you for taking the time to answer my question。
But I did not directly use the OkHttp framework to do network requests, do not need proxy settings。
I was using the `java.net.HttpURLConnection` do network request, the specific code is as follows:
HttpURLConnection connection = null;
URL postUrl = new URL("https://www.google.com");
connection = (HttpURLConnection) postUrl.openConnection();

**Comment by YongHuiLuo** [comment]
First of all, thank you for taking the time to answer my question。
But I did not directly use the OkHttp framework to do network requests, do not need proxy settings。
I was using the `java.net.HttpURLConnection` do network request, the specific code is as follows:

`
HttpURLConnection connection = null;
URL postUrl = new URL("https://www.google.com");
connection = (HttpURLConnection) postUrl.openConnection();
connection.setRequestMethod("POST");
connection.setRequestProperty("Accept-Encoding", "gzip, deflate");
connection.setRequestProperty("User-Agent", USER_AGENT);
connection.setRequestProperty("accept", "*/*");
connection.setRequestProperty("Connection", "Keep-Alive");
connection.setRequestProperty("Content-Type", "application/x-www-form-urlencoded");
onnection.setUseCaches(false);
connection.connect();
...
`
In`connection.connect()` reported the above exception。I think there may be Android source Bug. But do not know whether this is the case, should be resolved?

**Comment by swankjesse** [comment]
Unfortunately I don’t have enough information to fix this. Can you create an executable test case to reproduce the problem? Thanks.
