### ISSUE TITLE
javax.net.ssl.SSLException: Connection closed by peer 

### ISSUE THREAD

**Issue by duke1712** [square/okhttp#3053]
String data=MainActivity.run("https://kolkatatrafficpolice.net");

This is my code and I am getting an exception like this:

javax.net.ssl.SSLHandshakeException: Connection closed by peer
12-22 22:33:05.377 23819-23852/com.pritesh.trafficviolation W/System.err:     at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
12-22 22:33:05.377 23819-23852/com.pritesh.trafficviolation W/System.err:     at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:357)
12-22 22:33:05.377 23819-23852/com.pritesh.trafficviolation W/System.err:     at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:242)
12-22 22:33:05.377 23819-23852/com.pritesh.trafficviolation W/System.err:     at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:200)
12-22 22:33:05.377 23819-23852/com.pritesh.trafficviolation W/System.err:     at okhttp3.internal.connection.RealConnection.buildConnection(RealConnection.java:174)
12-22 22:33:05.377 23819-23852/com.pritesh.trafficviolation W/System.err:     at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:114)
12-22 22:33:05.377 23819-23852/com.pritesh.trafficviolation W/System.err:     at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:196)
12-22 22:33:05.377 23819-23852/com.pritesh.trafficviolation W/System.err:     at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:132)
12-22 22:33:05.377 23819-23852/com.pritesh.trafficviolation W/System.err:     at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:101)
12-22 22:33:05.377 23819-23852/com.pritesh.trafficviolation W/System.err:     at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
12-22 22:33:05.377 23819-23852/com.pritesh.trafficviolation W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
12-22 22:33:05.377 23819-23852/com.pritesh.trafficviolation W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
12-22 22:33:05.377 23819-23852/com.pritesh.trafficviolation W/System.err:     at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
12-22 22:33:05.377 23819-23852/com.pritesh.trafficviolation W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
12-22 22:33:05.377 23819-23852/com.pritesh.trafficviolation W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
12-22 22:33:05.377 23819-23852/com.pritesh.trafficviolation W/System.err:     at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
12-22 22:33:05.378 23819-23852/com.pritesh.trafficviolation W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
12-22 22:33:05.378 23819-23852/com.pritesh.trafficviolation W/System.err:     at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
12-22 22:33:05.378 23819-23852/com.pritesh.trafficviolation W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
12-22 22:33:05.378 23819-23852/com.pritesh.trafficviolation W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
12-22 22:33:05.378 23819-23852/com.pritesh.trafficviolation W/System.err:     at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:179)
12-22 22:33:05.378 23819-23852/com.pritesh.trafficviolation W/System.err:     at okhttp3.RealCall.execute(RealCall.java:63)

**Comment by swankjesse** [comment]
When you connect to this host with another HTTP client which cipher suite + TLS version are used?
