### ISSUE TITLE
How to println http log without HttpLoggingInterceptor?

### ISSUE THREAD

**Issue by fg2q1q3q** [square/okhttp#3054]
Hello, excuse me, I used retrofit2+okhttp in my app, which need to upload files and monitor the progress of the upload, I cannot use HttpLoggingInterceptor or else will upload fail. So how do I print other network requests and response results without HttpLoggingInterceptor

**Comment by swankjesse** [comment]
Try asking on StackOverflow. This tracker is for feature requests and bug reports only.
