### ISSUE TITLE
IllegalArgumentException when requesting file from filesystem

### ISSUE THREAD

**Issue by henrihallik** [square/okhttp#3055]
I need to add custom header to webview requests for files from sdcard. For that only solution i found was to use okhttp. But using the file:///PATH_TO_LOCAL_FILE schema throws exception:

W/System.err: java.lang.IllegalArgumentException: unexpected url: file:///storage/emulated/0/Android/data/eu.ekspressdigital.offlinedemo/files/issue76112603/61b088707d474a703ee408f2d8a1aa22.css
W/System.err:     at okhttp3.Request$Builder.url(Request.java:141)
W/System.err:     at eu.ekspressdigital.offline.OfflineModule.shouldInterceptRequest(OfflineModule.java:111)
12-23 14:18:54.992 11152-11190/? W/System.err:     at eu.ekspressdigital.offlinedemo.MainActivity$5.shouldInterceptRequest(MainActivity.java:117)
W/System.err:     at android.webkit.WebViewClient.shouldInterceptRequest(WebViewClient.java:155)
W/System.err:     at com.android.webview.chromium.WebViewContentsClientAdapter.shouldInterceptRequest(WebViewContentsClientAdapter.java:303)
11152-11190/? W/System.err:     at org.chromium.android_webview.AwContents$IoThreadClientImpl.shouldInterceptRequest(AwContents.java:384)
W/System.err:     at org.chromium.android_webview.AwContentsIoThreadClient.shouldInterceptRequest(AwContentsIoThreadClient.java:68)

The code im using to load the local file is:

  @SuppressLint("NewApi")
  public WebResourceResponse shouldInterceptRequest(final WebView view, String url, Long externalIssueId) {
    //String extension = MimeTypeMap.getFileExtensionFromUrl(url);

String offlineUrl = IssueFileMapper.getInstance(mContext).getOfflineUrl(url);
if(offlineUrl!=null){
  try {
    if(DEBUG) Log.i(TAG, "File:" + url);
    if(DEBUG) Log.i(TAG, "MIME:" + getMimeType(offlineUrl));

    OkHttpClient httpClient = new OkHttpClient();
    okhttp3.Request request = new okhttp3.Request.Builder()
           .url("file://" + offlineUrl)
           .addHeader("Access-Control-Allow-Origin", "*")
           .build();

    okhttp3.Response response = httpClient.newCall(request).execute();

    return new WebResourceResponse(
            response.header("content-type", getMimeType(offlineUrl)), // You can set something other as default content-type
            response.header("content-encoding", "utf-8"),  // Again, you can set another encoding as default
            response.body().byteStream()
    );
    //return new WebResourceResponse(getMimeType(offlineUrl), "UTF-8", new URL("file:///" + offlineUrl).openStream());
  } catch (IOException e) {
    e.printStackTrace();
  }
}
if(OfflineModule.DEBUG) Log.d(TAG, "Failed to retrieve offline content for "+url);
return null;

**Comment by swankjesse** [comment]
OkHttp doesn’t support URLs other than http: and https:.
