### ISSUE TITLE
java.nio.charset.UnsupportedCharsetException in 3.5.0

### ISSUE THREAD

**Issue by huangyanan** [square/okhttp#3061]
log:
`#107902 IntentService[LoadCacheTask]
java.nio.charset.UnsupportedCharsetException
gdk

1 java.nio.charset.Charset.forName(Charset.java:309)
2 okhttp3.t.a(MediaType.java:111)
3 okhttp3.ab.f(ResponseBody.java:182)
4 okhttp3.ab.e(ResponseBody.java:173)
5 com.beibo.yuerbao.hybrid.cache.LoadCacheTask.a(LoadCacheTask.java:76)
6 com.beibo.yuerbao.hybrid.cache.LoadCacheTask.onHandleIntent(LoadCacheTask.java:60)
7 android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
8 android.os.Handler.dispatchMessage(Handler.java:102)
9 android.os.Looper.loop(Looper.java:179)
10 android.os.HandlerThread.run(HandlerThread.java:61)`

this happen when i update okhttp form 3.4.1 to 3.5.0. the version 3.4.1 is ok.

**Comment by swankjesse** [comment]
Do you mind providing a unit test?
