### ISSUE TITLE
[Feature Request] Streamable RequestBody

### ISSUE THREAD

**Issue by VladimirLichonos** [square/okhttp#3064]
Hi,

OkHttp allows to create RequestBody with unknown content length, but it does not seems like it is possible to access a connection (sink?) in order to write RequestBody when parts of the content become available.

The problem is in order to write to the sink it requires to know exact size and full access to a content of the request body at a time when writeTo is called.

Unless I am missing some other way to use OkHttp, I think it is not possible to provide RequestBody  to write a data to the end socket without having full access to content at a time?

e.g. content is generated at a time of the request being processed.

p.s. if I can help anyhow to add the support, please let me know.

**Comment by swankjesse** [comment]
Will this work for you? https://github.com/square/okhttp/wiki/Recipes#post-streaming

**Comment by VladimirLichonos** [comment]
@swankjesse Yes, it may. Correct me if I am wrong, that okhttp would call writeTo method on RequestBody only once when it needs to write the content.

I wonder if let's say I block writeTo with a for-loop that wait on a queue that is fulfilled with a data by other thread. Would this be okay to block writeTo for some time by perspective of okhttp? Would that start streaming data or it would wait until writeTo completed?

I hope I make sense.

**Comment by swankjesse** [comment]
Yep, you’re definitely allowed to block in `writeTo()`. The only constraint is that if you block too long (say, greater than 30 seconds) your server might assume you’ve disappeared and close the connection.

**Comment by swankjesse** [comment]
BTW, this class might be helpful:
http://square.github.io/okio/1.x/okio/okio/Pipe.html

Your writeTo method can just call `sink.writeAll(pipe.source())`.

**Comment by VladimirLichonos** [comment]
Yes, I guess it is non-trivial case. I saw that API, but was not sure how would OkHttp treat a such case.

Pipe sounds something that I may need.

Thank you for help and I think composing RequestBody for post streaming with pipe would solve this problem.

**Comment by pjd0501** [comment]
@VolodymyrLykhonis Hi, I am stuck with the same problem. Did you find a solution with PipeBody? Can you please post a snippet here so that it'd be useful for future visitors. Thnx.

**Comment by VolodymyrLykhonis** [comment]
@pjd0501 I cannot share a snippet, but I basically ended up writing my own pipe class referencing to the okio.Pipe class. Idea is right to use Pipe is right direction, and it works fine for me now.
