### ISSUE TITLE
java.lang.NoClassDefFoundError in 3.5.0

### ISSUE THREAD

**Issue by runyan** [square/okhttp#3065]
When I used the 3.5.0 version of okhttp, I encountered a weird exception
Exception in thread "main" java.lang.NoClassDefFoundError: okio/BufferedSource
	at okhttp3.internal.Util.<clinit>(Util.java:48)
	at okhttp3.OkHttpClient.<clinit>(OkHttpClient.java:121)
	at com.demo.okHttp.Demo.main(Demo.java:8)
Caused by: java.lang.ClassNotFoundException: okio.BufferedSource
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 3 more
however, when I use the 3.2 it works fine. My code is as simple as 
`public static void main(String[] args) {
		    OkHttpClient client = new OkHttpClient();
	}`
and I have okhttp 3.5.0 and okio  1.11.0 imported to my project. Is this a bug in the 3.5.0 version, how can I solve this problem?

**Comment by JakeWharton** [comment]
Your Okio import didn't work or this exception wouldn't occur. Are you sure
you've done it correctly?

**Comment by runyan** [comment]
@JakeWharton I used maven to build my project and my dependencies looks like 
<dependency>
    	<groupId>com.squareup.okio</groupId>
    	<artifactId>okio</artifactId>
    	<version>1.11.0</version>
	</dependency>
  	<dependency>
  		<groupId>com.squareup.okhttp3</groupId>
  		<artifactId>okhttp</artifactId>
  		<version>3.5.0</version>
	</dependency>
    <dependency>

**Comment by runyan** [comment]
@JakeWharton I used maven to build my project, here is my current dependencies
<dependency>
    	<groupId>com.squareup.okio</groupId>
    	<artifactId>okio</artifactId>
    	<version>1.11.0</version>
	</dependency>
  	<dependency>
  		<groupId>com.squareup.okhttp3</groupId>
  		<artifactId>okhttp</artifactId>
  		<version>3.5.0</version>
	</dependency>
    <dependency>

**Comment by runyan** [comment]
<dependency>
    	<groupId>com.squareup.okio</groupId>
    	<artifactId>okio</artifactId>
    	<version>1.11.0</version>
	</dependency>
  	<dependency>
  		<groupId>com.squareup.okhttp3</groupId>
  		<artifactId>okhttp</artifactId>
  		<version>3.5.0</version>
	</dependency>

**Comment by runyan** [comment]
> ``

**Comment by runyan** [comment]
`<dependency>
    	<groupId>com.squareup.okio</groupId>
    	<artifactId>okio</artifactId>
    	<version>1.11.0</version>
	</dependency>
  	<dependency>
  		<groupId>com.squareup.okhttp3</groupId>
  		<artifactId>okhttp</artifactId>
  		<version>3.5.0</version>
	</dependency>`

**Comment by swankjesse** [comment]
Sadly there's nothing we can do here. Something in your tool chain is not pulling in the Okio dependency.

**Comment by kinsleykajiva** [comment]
hey, guys .. well the solution suggested by @JakeWharton  worked for me in Java. I am using the jar as opposed to what @JakeWharton  suggested ,

**Comment by smileboywtu** [comment]
you need also download the okio.jar as your project module

**Comment by Danc2050** [comment]
I had to include these in my `org.apache.maven.plugins`  like so:
```
<plugin>
....
  <configuration>
     <artifactSet>
       <includes>
        <include>com.squareup.okhttp3:okhttp</include>
        <include>com.squareup.okio:okio</include>
       </includes>
     </artifactSet>
  </configuration>
....
</plugin>

**Comment by aniruddhdandotiya** [comment]
@runyan @smileboywtu @kinsleykajiva @Danc2050 I'm creating a java library where I'm using okhttp client and it working fine when tested. The java library will be reused across java applications. But when importing the library as a dependency in other application, I'm getting the same error as above, during the application startup.

Attaching below is dependency added in my library pom.xml. Appreciate your help.
        <dependency>
            <groupId>com.squareup.okhttp3</groupId>
            <artifactId>okhttp</artifactId>
            <version>4.10.0</version>
        </dependency>

        <dependency>
            <groupId>com.squareup.okio</groupId>
            <artifactId>okio-jvm</artifactId>
            <version>3.0.0</version>
            <scope>compile</scope>
        </dependency>

        <dependency>
            <groupId>org.jetbrains.kotlin</groupId>
            <artifactId>kotlin-stdlib</artifactId>
            <version>1.6.20</version>
            <scope>compile</scope>
        </dependency>
