### ISSUE TITLE
Best practice for migrate to new certificates ?

### ISSUE THREAD

**Issue by kuno** [square/okhttp#3074]
Our app using a pinned client to fetch data from backend server, but the certificate for the server hostname will expire soon.

The way how our pinned the certs is following the official doc
```
 CertificatePinner certificatePinner = new CertificatePinner.Builder()
       .add("publicobject.com", "sha256/afwiKY3RxoMmLkuRW1l7QsPZTJPwDS2pdDROQjXw8ig=")
       .add("publicobject.com", "sha256/klO23nT2ehFDXCfx3eHTDRESMz3asj1muO+4aIdjiuY=")
       .add("publicobject.com", "sha256/grX4Ta9HpZx6tSHkmCrvpApTQGo67CYDnvprLg5yRME=")
       .add("publicobject.com", "sha256/lCppFqbkrlJ3EcVFAkeip0+44VaoJUymbnOaEUk7tEU=")
       .build();
 
```

Can someone point me to the best practice to migrate to new certificate.

Is that possible pinned old and new certs at same time ?

**Comment by swankjesse** [comment]
You'll want to add pins for the new certs alongside the old ones. If possible, you can use the same subjects & public keys for your new certs, in which case your new pins and old pins will be the same.

**Comment by yschimke** [comment]
Isn't it better to use a stable pin from your Intermediate CA (with a backup CA?).  That way you can freely rotate your certificates.  I'd suggest that getting your own private keys leaked is a lot more likely that the CA.
