### ISSUE TITLE
Building a local copy of OkHttp for use in Android Studio Project

### ISSUE THREAD

**Issue by John-Keyor** [square/okhttp#3075]
The title says it all. I've downloaded OkHttp and placed it in the same directory as my project's app folder. I've tried compiling in Android Studio (2.2.3) and the error is

`Error:Configuration with name 'default' not found.`

I've looked around SO and the reason seems to be that there's a lack of build.gradle files and Android Studio doesn't know how to make it. ([http://stackoverflow.com/a/20553424](http://stackoverflow.com/a/20553424))

My question is simple: Is there a way to compile a local copy of OkHttp in Android Studio? The purpose is simply to modify some portions of the code for a custom implementation, and seems like this should be a straightforward thing to do.

Any ideas, anyone?

**Comment by JakeWharton** [comment]
OkHttp is built using Maven not Gradle so you'll have to write your own
build.gradle for it.

**Comment by John-Keyor** [comment]
Ah, okay that makes sense. Just not sure how to go about that. Any tips?

**Comment by John-Keyor** [comment]
Okay, so I've generated a build.gradle file using `gradle init`, but when I execute `gradle build` the java class compilation fails. The error is it cannot find symbol for the class Version and variable Version in BridgeInterceptor.java and RealConnection.java. Any idea what could have caused this? And what's required for a successful gradle build of okhttp?

**Comment by JakeWharton** [comment]
That class is generated automatically by the build.

**Comment by John-Keyor** [comment]
Hmm. The errors in gradle build are from executing  :okhttp:compileJava so the compiled java class files aren't being generated. (i.e.
```

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':okhttp:compileJava'.
>Compilation failed; see the compiler error output for details.

*Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```
I've added it to Android Studio and gradle recognizes the module dependency and compiles with no errors. But when actually running the app, it's unable to do so because the java class files weren't compiled. I'm wondering what could be the reason for this..

**Comment by swankjesse** [comment]
Not much action for us to take here. I recommend using Maven to build OkHttp.
