### ISSUE TITLE
HttpLoggingInterceptor causing RequestBody to be instantiated twice

### ISSUE THREAD

**Issue by Schinizer** [square/okhttp#3077]
I am trying to track the progress of my file upload using a `ForwardingSink`

Apparently using `HttpLoggingInterceptor` results `RequestBody` being instantiated twice. The second instantiation is the actual upload. Is this intended behavior?

Here is a sample test case:
https://gist.github.com/Schinizer/22c1877cf1bd9b22ed1dda3962db881f

**Comment by swankjesse** [comment]
This is working as intended, but our intentions might be misguided.

In general requests should be prepared to be sent multiple times; this happens with certain types of redirects and retries. For robustness you probably want to make your code robust to a RequestBody’s `writeTo()` method being called multiple times.
