### ISSUE TITLE
Feature: offer a way to determine if a response was sent gzipped

### ISSUE THREAD

**Issue by markelliot** [square/okhttp#3079]
I'd like to understand if a response was gzipped so that I can verify my servers are behaving correctly in tests, but `BridgeInterceptor` eats the relevant header information. Instead of just stripping headers, it'd be ideal if there were a way to recover 'suppressed headers' or simply determine original encoding of the underlying source, while still getting automatic decoding of the response.

**Comment by swankjesse** [comment]
Try this:
```
Response response = ...
boolean gzip = response.networkResponse().header("Content-Encoding", "").contains("gzip")
```

**Comment by markelliot** [comment]
Perfect, thanks.
