### ISSUE TITLE
Feature: restrict protocols to HTTP/2 only 

### ISSUE THREAD

**Issue by yschimke** [square/okhttp#3083]
If you know a particular server supports HTTP/2 and you would rather fail than downgrade to HTTP/1.1, then you could limit the supported protocols to HTTP/2.  

This would allow you to only connect once, even while waiting for the initial DNS, TLS handshake etc.

Further it also opens up the ability to ask for a preemptive connection, without making the initial request.  This is an annoyance of mine as I am hooking up various APIs and the result of fetching from foursquare, might be to make 20 requests to mapbox each of which currently need to connect separately.

This is tangential to https://github.com/square/okhttp/pull/3080.  Feel free to close this if the payoff is not worth the effort or complexity.

**Comment by swankjesse** [comment]
You can seed the connection pool by making a small request, like `HEAD /robots.txt`. It’s imprecise, but simple.

I’m reluctant to offer an option to opt out of HTTP/1.1 since that has a nasty failure mode if your server changes.

**Comment by yschimke** [comment]
Maybe what is missing is a flag to indicate servers you strongly expect HTTP/2 support.  I think most companies with big mobile apps would generally agree that they are ok with falling back to HTTP/1.1 to keep things working, but at this point I'm not clear why HTTP/2 is considered less reliable than HTTP/1.1?  But still you can workaround that by checking the protocol for new connections and logging it to the server if it falls back.

But cold start up time often has a lot of clients connecting, and this is precisely when you would rather only a single connection.  And perhaps even multiple host coalescing https://daniel.haxx.se/blog/2016/08/18/http2-connection-coalescing/

Anyway, back to the flag, it would be useful *hint* that you expect HTTP/2 so the second connection should wait until you discover that the first is really not HTTP/2.  

I might try this as a library and try to make a simple Android or command line test app to show the difference in cold start times.  This is something I suspect a lot more apps should be doing given the early DNS and TLS handshake times dominate precisely when you want your app to do the minimal amount of work.

**Comment by yschimke** [comment]
BTW I've never actually written against the okhttp API on Android, we use different internal libraries mostly.  Most of my test apps are CLI e.g. https://github.com/yschimke/uberalles/blob/master/commands/ubereta

**Comment by swankjesse** [comment]
Ah, I get the request. If we expect HTTP/2 we should build a single connection rather than jumping through hoops creating one and then tearing it down.

I’d prefer to solve this magically, by remembering past behavior somewhere. Once we have a mechanism for that this becomes easy and automatic.

**Comment by yschimke** [comment]
+1 

That also fits well with HPKP and HSTS

**Comment by cgrushko** [comment]
I'd like to take a stab at implementing this; @yschimke / @swankjesse , do you happen to have the place to start looking at off the top of your head?

In addition to the cold start up time concerns that @yschimke brings up, there's also the issue of reliability, where some of the new connection attempts time out while others succeed (I saw it locally).
