### ISSUE TITLE
OkHttp: <-- HTTP FAILED: java.net.SocketException: sendto failed: EBADF (Bad file number)

### ISSUE THREAD

**Issue by zhaocheng19940105** [square/okhttp#3084]
What kind of issue is this?

 - [x] Question. This issue tracker is not the place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use Stack
       Overflow. https://stackoverflow.com/questions/tagged/okhttp

 - [x] Bug report. If you’ve found a bug, spend the time to write a failing test. Bugs with tests
       get fixed. Here’s an example: https://gist.github.com/swankjesse/981fcae102f513eb13ed

 - [ ] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
       already exists! Don’t send pull requests to implement new features without first getting our
       support. Sometimes we leave features out on purpose to keep the project small.

**Comment by swankjesse** [comment]
Can you provide an executable test case?

**Comment by zhaocheng19940105** [comment]
OkHttpClient client = new OkHttpClient.Builder()
                .cookieJar(cookieJar)
                .cache(new Cache(httpCacheDirectory, 20 * 1024 * 1024))  // 20M SD-Card Cache
                .addInterceptor(logInterceptor)
                .retryOnConnectionFailure(true)
                .connectTimeout(20, TimeUnit.SECONDS)
                .readTimeout(55, TimeUnit.SECONDS)
                .writeTimeout(60, TimeUnit.SECONDS)
                .addNetworkInterceptor(mCommonInfoInterceptor)
                .addNetworkInterceptor(REWRITE_CACHE_CONTROL_INTERCEPTOR)
                .authenticator(mAuthenticator)
                .build();

RequestBody body = RequestBody.create(MediaType.parse("application/otcet-stream"), file);
            FileRequestBody<FileUpLoadUpyResp> fileRequestBody = new FileRequestBody<>(body, callback);
            HashMap<String, RequestBody> mParams = new HashMap<>();//请求参数
            MultipartBody requestBody = new MultipartBody.Builder()
                    .setType(MultipartBody.FORM)
                    .addFormDataPart("uploadfile", "filename", fileRequestBody)
                    .build();
            mParams.put("uploadfile\"; filename=\"" + file.getName() + "", requestBody);
            App.apiService(NodeApiService.class).roomUploadVideo(mParams).enqueue(callback);

**Comment by zhaocheng19940105** [comment]
RequestBody body = RequestBody.create(MediaType.parse("application/otcet-stream"), file);
            FileRequestBody<FileUpLoadUpyResp> fileRequestBody = new FileRequestBody<>(body, callback);
            HashMap<String, RequestBody> mParams = new HashMap<>();
            MultipartBody requestBody = new MultipartBody.Builder()
                    .setType(MultipartBody.FORM)
                    .addFormDataPart("uploadfile", "filename", fileRequestBody)
                    .build();
            mParams.put("uploadfile\"; filename=\"" + file.getName() + "", requestBody);
            App.apiService(NodeApiService.class).roomUploadVideo(mParams).enqueue(callback);

**Comment by zhaocheng19940105** [comment]
Small file no problem But I have a 400M file upload will never fail I do not know if there is a problem or okhttp

**Comment by zhaocheng19940105** [comment]
MultipartBody multipartBody = (MultipartBody) requestBody;
            MultipartBody.Builder multipartBuilder = new MultipartBody.Builder();
            if (multipartBody.size() > 0) {
                for (int idx = 0; idx < multipartBody.size(); idx++) {
                    multipartBuilder.addPart(multipartBody.part(idx));
                }
            }
            if (added != null && added.size() > 0) {
                for (Map.Entry<String, String> entry : added.entrySet()) {
                    multipartBuilder.addFormDataPart(
                            entry.getKey(), null,
                            RequestBody.create(
                                    MediaType.parse("text/plain; charset=UTF-8"), entry.getValue()));
                }
            }
            multipartBody = multipartBuilder.build();
            return request.newBuilder().post(multipartBody)  // need update boundary
                    .header("Content-Type", "multipart/form-data; boundary=" + multipartBody.boundary())
                    .build();
