### ISSUE TITLE
failed to connect <server ip addr>

### ISSUE THREAD

**Issue by yinhaojun** [square/okhttp#3086]
hello, all~

 i developed my app with retrofit + okhttp + rxjava. when net is high speed, there is no problems. but when i close wifi or change net type, there is a issue**(failed to connect ****:****)**.
the okhttp version is 2.7.0;
the retrofit version is 2.1.0;

please forgive my poor english!

**Comment by swankjesse** [comment]
Please ask your question on StackOverflow.
