### ISSUE TITLE
How make MockWebServer to require BasicAuth?

### ISSUE THREAD

**Issue by glebsts** [square/okhttp#3088]
I have my client built with builder.authenticate(new Authenticator(){.. // provide credentials here..})
I want to setup my MockWebServer to actually require basic auth. Sor far seems like authenticator is not invoked. How?

**Comment by swankjesse** [comment]
Return a Response with code `401` if the request isn’t authenticated. You might need to implement MockWebServer’s `Dispatcher` interface.
