### ISSUE TITLE
Http RoutePlanner

### ISSUE THREAD

**Issue by gautamshrm3** [square/okhttp#3099]
Hi Team,

I need to implement route planner through Retrofit. Please help me

Route planner exists in DefaultHttpClient.

**Comment by gautamshrm3** [comment]
How to use 
if possible then please share the code snippet

**Comment by swankjesse** [comment]
You'll implement the `Dns` and `ProxySelector` interfaces.

**Comment by gautamshrm3** [comment]
Can you please provide some sample code
