### ISSUE TITLE
Add support for Java8 CompletableFuture to Call

### ISSUE THREAD

**Issue by jnape** [square/okhttp#3102]
It would be nice to support a niladic form of `Call#enqueue` that returns `CompletableFuture<Response>`. Is it currently reasonable to upgrade support for Android to at least v7.0 (API Level 24, where `CompletableFuture` arrives)?

**Comment by JakeWharton** [comment]
That accounts for 0.7% of active Android devices so it will be at least 3
or 4 years before Java 8 is viable for a project like OkHttp.

**Comment by JakeWharton** [comment]
We could ship a sibling module adding static methods to wrap a Call, but it
seems fairly low-value since it's fairly easy to write your own. Also
Kotlin extension methods work great here since you can add an enqueue-like
method that returns a CompletableFuture.

**Comment by wojtekk** [comment]
I see that Java 8 is required now - will be great to reopen this issue.

**Comment by yschimke** [comment]
Worth a quick discussion. Seems high value for java callers.

**Comment by JakeWharton** [comment]
CF is a pretty poor API to push people towards though. I wouldn't want to evangelize its use implicitly.

**Comment by wojtekk** [comment]
I agree with you @JakeWharton but do we really need something more in simple applications (lambda functions in my case)?
For me CF is better than custom Callback class - I can integrate it with my software in an easier way then.

**Comment by swankjesse** [comment]
I think you can write about 6 lines of code to do this. Maybe paste a sample here for those interested? I don't want this in the library directly.

**Comment by wojtekk** [comment]
@swankjesse could you elaborate a bit? Custom Callback class vs standard JVM solution (CF)?

Btw. I know how to do that in a few lines - to be honest, I've considered contribution ;) because this is simply stupid and probably many people waste time to do that in their projects?

Please keep in mind that I'm not ❤️ in CF - I just don't like to reinvent the wheel.

**Comment by swankjesse** [comment]
Voila: https://gist.github.com/swankjesse/3c11c407f2fc80c1fa9242a94dd0f7e2

**Comment by adrian-skybaker** [comment]
This would be much more convenient to have in the library itself. Taste aside, `java.util.concurrent.CompletableFuture` is the standard JVM class for representing a future.
