### ISSUE TITLE
HTTP/2 ignores user-specified Host header

### ISSUE THREAD

**Issue by moxie0** [square/okhttp#3103]
- [X] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
       already exists! Don’t send pull requests to implement new features without first getting our
       support. Sometimes we leave features out on purpose to keep the project small.

I think the code [here](https://github.com/square/okhttp/blob/90021dcaea583b518fa92cdac58aa757dd6be111/okhttp/src/main/java/okhttp3/internal/http2/Http2Codec.java#L133) ignores the 'Host' header in a `Request` and pulls it straight out of the URI instead:

```
  public static List<Header> http2HeadersList(Request request) {
    Headers headers = request.headers();
    List<Header> result = new ArrayList<>(headers.size() + 4);
    result.add(new Header(TARGET_METHOD, request.method()));
    result.add(new Header(TARGET_PATH, RequestLine.requestPath(request.url())));
    result.add(new Header(TARGET_AUTHORITY, Util.hostHeader(request.url(), false))); // Optional.
    result.add(new Header(TARGET_SCHEME, request.url().scheme()));

    for (int i = 0, size = headers.size(); i < size; i++) {
      // header names must be lowercase.
      ByteString name = ByteString.encodeUtf8(headers.name(i).toLowerCase(Locale.US));
      if (!HTTP_2_SKIPPED_REQUEST_HEADERS.contains(name)) {
        result.add(new Header(name, headers.value(i)));
      }
    }
    return result;
  }
```

I assume this `Request` has gone through `BridgeInterceptor`, in which case it's either guaranteed to have a user-specified 'Host' header, or to have already been populated from the Uri, in which case I think it should be safe to replace:

```
    result.add(new Header(TARGET_AUTHORITY, Util.hostHeader(request.url(), false))); // Optional.
```

with:

```
    result.add(new Header(TARGET_AUTHORITY, request.header("Host"))); // Optional.
```

This might seem silly, but user-specified host headers are essential for those of us who depend on [domain fronting](https://www.bamsoftware.com/papers/fronting/) to circumvent censorship. Happy to submit a PR if this seems acceptable.

**Comment by swankjesse** [comment]
Makes sense. Can do.
