### ISSUE TITLE
How to get the length of the response body before gzip decompress

### ISSUE THREAD

**Issue by MrIceFox** [square/okhttp#3112]
I'm going to count the bytes received by every request, using the codes below,
```java
long length = response.body().bytes().length;
```
but the length is much greater then the actual body size and actually is the uncompressed body size.
I've execute a request and  get the length=4143. 
The overview of this request in Charles,
> Response	1.07 KB (1,095 bytes)
Header	364 bytes
Cookies	44 bytes
Body	731 bytes
Uncompressed Body	4.05 KB (4,143 bytes)
Compression	82.4% (gzip)

Is there any way to get the length of the response body before gzip decompress?

**Comment by swankjesse** [comment]
Two options:

1. Disable gzip with this header: `Accept-Encoding:identity`.
2. Use `response.networkResponse()` and ask its `Content-Length`. Unfortunately this isn’t guaranteed to be present.

**Comment by MrIceFox** [comment]
I've found an solution,
```java
okBuilder.addNetworkInterceptor(new Interceptor() {
            @Override
            public Response intercept(Chain chain) throws IOException {
                Response response = chain.proceed(chain.request());
                ForwardingSource forwardingSource = new ForwardingSource(response.body().source()) {
                    long bodySize;

                    @Override
                    public long read(Buffer sink, long byteCount) throws IOException {
                        long bytesRead = super.read(sink, byteCount);
                        if (bytesRead != -1) {
                            bodySize += bytesRead;
                        }
                        return bytesRead;
                    }
                };
                Response.Builder responseBuilder = response.newBuilder();
                responseBuilder.body(new RealResponseBody(response.headers(), Okio.buffer(forwardingSource)));
                return responseBuilder.build();
            }
        });
```
But the `bodySize` smaller then the data in Charles about 10 bytes. Is it the correct way?
