### ISSUE TITLE
SSLHandshakeException after leaving the app and returning

### ISSUE THREAD

**Issue by laurencedawson** [square/okhttp#3118]
Bug:
- Nexus 6P on latest stock 7.1.1
- okhttp 3.5.0
- A single OkHttpClient is used for submit all network requests

1. Launch the app and then leave it in the background for 20-40 minutes
2. Return to the app and try to execute a request
3. SSLHandshakeExceptions are now thrown for every request until a new OkHttpClient is created

I've started seeing this issue in my app and it seems a few others have been seeing it to:

http://stackoverflow.com/questions/37885391/okhttp-sslprotocolexception-ssl-handshake-terminated

At the moment my solution is to just create a new OkHttpClient when it encounters a SSLHandshakeException but is there a better way to go about this? Maybe emptying the connection pool and retrying the request?

Thanks

**Comment by swankjesse** [comment]
We’ve talked about supporting multiple network interfaces:
https://github.com/square/okhttp/issues/1780

Not sure what other action to take here. We don’t really have visibility into the user’s network state.
