### ISSUE TITLE
unable to get stub builder for org.jetbrains.lang.manifest.ManifestFileType@480c9db7

### ISSUE THREAD

**Issue by boyfox** [square/okhttp#3121]
After changing okhttp3 library with the latest version 3.5.0 began appears following EmptyThrowable on the Android Studio:

11:29:05 AM EmptyThrowable: unable to get stub builder for org.jetbrains.lang.manifest.ManifestFileType@480c9db7, path = /Users/admin/.gradle/caches/modules-2/files-2.1/com.squareup.okhttp3/logging-interceptor/3.5.0/36f80e3705c6123f2d4ca85ab92efe899d81a93c/logging-interceptor-3.5.0-sources.jar!/META-INF/MANIFEST.MF, stubBindingRoot = ManifestFileImpl, languages = [Manifest], filesTypes = [Manifest], files = [ManifestFileImpl], roots = []
11:29:20 AM EmptyThrowable: unable to get stub builder for org.jetbrains.lang.manifest.ManifestFileType@480c9db7, path = /Users/admin/.gradle/caches/modules-2/files-2.1/com.squareup.okhttp3/logging-interceptor/3.5.0/36f80e3705c6123f2d4ca85ab92efe899d81a93c/logging-interceptor-3.5.0-sources.jar!/META-INF/MANIFEST.MF, stubBindingRoot = ManifestFileImpl, languages = [Manifest], filesTypes = [Manifest], files = [ManifestFileImpl], roots = []

How to fix this is?

**Comment by JakeWharton** [comment]
What makes you believe this is a problem with OkHttp? It seems like
something related to your build system.

**Comment by boyfox** [comment]
Hi!
I think this is OkHttp issue because, if I will return back library version 3.4.2 will be works like a charm. If I will change library version with latest then you can see these exceptions.

This is my app build.gradle file:

    buildscript {
        repositories {
            mavenCentral()
            maven { url 'https://maven.fabric.io/public' }
        }

        dependencies {
            classpath 'io.fabric.tools:gradle:1.+'
        }
    }
    apply plugin: 'com.android.application'
    apply plugin: 'io.fabric'

    android {
        compileSdkVersion 25
        buildToolsVersion "25.0.2"

        dataBinding {
            enabled = true
        }

        defaultConfig {
            applicationId "de.fubar.anapp"
            minSdkVersion 15
            targetSdkVersion 25
            versionCode 15
            versionName "1.0.1"
            testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"

            vectorDrawables.useSupportLibrary = true
            resConfigs "en", "de"

            multiDexEnabled true
        }

        aaptOptions {
            cruncherEnabled = false
        }

        lintOptions {
            abortOnError false
        }

        buildTypes {
            release {
                minifyEnabled false
                proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            }
        }

        packagingOptions {
            exclude 'META-INF/LICENSE.txt'
            exclude 'META-INF/NOTICE.txt'
            exclude 'META-INF/LICENSE'
            exclude 'META-INF/license.txt'
        }
    }

    repositories {
        mavenCentral()
        maven { url 'https://maven.fabric.io/public' }
    }

    gradle.taskGraph.useFilter { task ->
        if (task.name.contains("Test") || task.name.contains("mockable")) {
            return false;
        }
        return true;
    }

    dependencies {
        compile fileTree(dir: 'libs', include: ['*.jar'])
        androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
            exclude group: 'com.android.support', module: 'support-annotations'
        })

        compile 'com.android.support:multidex:1.0.1'
        compile 'com.android.support:appcompat-v7:25.1.0'
        compile 'com.android.support:design:25.1.0'
        compile 'com.android.support:support-v4:25.1.0'
        compile 'com.google.firebase:firebase-messaging:10.0.1'
        compile 'com.google.firebase:firebase-crash:10.0.1'
        compile 'com.google.android.gms:play-services-maps:10.0.1'
        compile 'com.google.android.gms:play-services-places:10.0.1'
        compile 'com.google.android.gms:play-services-location:10.0.1'
        compile 'com.jakewharton:butterknife:8.4.0'
    //    compile 'com.squareup.okhttp3:okhttp:3.5.0'
    //    compile 'com.squareup.okhttp3:logging-interceptor:3.5.0'
        compile 'com.squareup.okhttp3:okhttp:3.4.2'
        compile 'com.squareup.okhttp3:logging-interceptor:3.4.2'
        compile 'com.squareup.picasso:picasso:2.5.2'
        compile 'com.mikhaellopez:circularimageview:3.0.2'
        compile 'com.amitshekhar.android:android-networking:0.3.0'
        compile 'com.amitshekhar.android:jackson-android-networking:0.3.0'
        compile 'net.danlew:android.joda:2.9.5.1'
        compile 'com.github.rubensousa:gravitysnaphelper:1.0'
        compile 'com.bartoszlipinski:viewpropertyobjectanimator:1.4.5'
        compile 'com.facebook.android:facebook-android-sdk:4.+'
        testCompile 'junit:junit:4.12'
        annotationProcessor 'com.jakewharton:butterknife-compiler:8.4.0'
        compile('com.twitter.sdk.android:twitter:2.3.1@aar') {
            transitive = true;
        }
    }



    apply plugin: 'com.google.gms.google-services'

**Comment by JakeWharton** [comment]
That doesn't make it a library problem it just means your build system is broken in some way. Did you try a clean build?

**Comment by boyfox** [comment]
Yes, I tried clean, also "Invalid cache/Restart", too. But, did not help

**Comment by swankjesse** [comment]
No action for us to take on this.
