### ISSUE TITLE
Use much more memory with codes than with Jar file.

### ISSUE THREAD

**Issue by minibeep** [square/okhttp#3129]
Not sure if it is a bug.
We are using okhttp 2.3.0 in Androidas our client which has stable connection than 3.5.0. Firstly we use the jar file directly in our project, the memory usage is normal. But we need change some codes and therefore we use source codes. Unfortunately, using source codes makes memory consumption much higher, even outofmemory. Can you give some suggestions on using codes in Android? Needs some configuration to avoid using too much memory?

**Comment by swankjesse** [comment]
Not sure what action to take on this. If you could do further investigation that’d be helpful.
