### ISSUE TITLE
OutOfMemoryError occurs by okhttp3

### ISSUE THREAD

**Issue by cocomikes** [square/okhttp#3130]
What kind of issue is this?
Unfortunately，I found a BUG caused by Okhttp3.

Fatal Exception: java.lang.OutOfMemoryError: pthread_create (1040KB stack) failed: Try again
       at java.lang.Thread.nativeCreate(Thread.java)
       at java.lang.Thread.start(Thread.java:1063)
       at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:920)
       at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1338)
       at okhttp3.Dispatcher.enqueue(Dispatcher.java:112)
       at okhttp3.RealCall.enqueue(RealCall.java:78)
       at okhttp3.RealCall.enqueue(RealCall.java:70)
       at io.library.core.okhttp.OkHttpUtils.execute(OkHttpUtils.java:143)
       at io.library.core.okhttp.request.RequestCall.execute(RequestCall.java:92)
       at io.library.core.http.impl.OkHttpImpl.executeRequest(OkHttpImpl.java:148)
       at io.library.core.http.impl.OkHttpImpl.sendRequest(OkHttpImpl.java:86)

Here is Dispatcher's source code.

  synchronized void enqueue(AsyncCall call) {
    if (runningAsyncCalls.size() < maxRequests && runningCallsForHost(call) < maxRequestsPerHost) {
      runningAsyncCalls.add(call);
      executorService().execute(call);
    } else {
      readyAsyncCalls.add(call);
    }
  }

  public synchronized ExecutorService executorService() {
    if (executorService == null) {
      executorService = new ThreadPoolExecutor(0, Integer.MAX_VALUE, 60, TimeUnit.SECONDS,
          new SynchronousQueue<Runnable>(), Util.threadFactory("OkHttp Dispatcher", false));
    }
    return executorService;
  }

But why the threadPool will occurs OutOfMemoryError. I can not understand.

**Comment by JakeWharton** [comment]
Are you creating one OkHttpClient instance per request?

**Comment by cocomikes** [comment]
no. I use the globally unique OkhttpClient，it is initialize in my own application.
--Here is my applicaion.
        HttpsUtils.SSLParams sslParams = HttpsUtils.getSslSocketFactory(new InputStream[]{new Buffer().writeUtf8(CER_SELF).inputStream()}, null, null);

        CookieJarImpl cookieJar = new CookieJarImpl(new PersistentCookieStore(this));
        OkHttpClient.Builder okHttpClientBuilder = new OkHttpClient.Builder()
                .sslSocketFactory(sslParams.sSLSocketFactory, sslParams.trustManager)
                .cookieJar(cookieJar)
                .cache(createOkhttpCache())
                .connectTimeout(HttpConstants.REQUEST_TIMEOUT_MS, TimeUnit.MILLISECONDS)
                .readTimeout(HttpConstants.REQUEST_TIMEOUT_MS, TimeUnit.MILLISECONDS)
                .retryOnConnectionFailure(true)
                .hostnameVerifier(new HostnameVerifier() {
                    @Override
                    public boolean verify(String hostname, SSLSession session) {
                        return true;
                    }
                })
                .addInterceptor(new AuthTokenInterceptor())
                .addInterceptor(new CacheInterceptor())
                .addNetworkInterceptor(new CacheInterceptor());
        if(AppEnv.DEV_MODE){
            okHttpClientBuilder.addInterceptor(new LogInterceptor());
        }

        HttpFactory.setHttpEngine(HttpEngine.OK_HTTP);
        HttpFactory.setOkHttpClient(okHttpClientBuilder.build());
---Here is my HttpFactory
private static BaseContext mContext = null;
    private static HttpService mHttpService = null;
    public static HttpEngine mHttpEngine = HttpEngine.OK_HTTP;
    private static OkHttpClient okHttpClient;

    public static void setOkHttpClient(OkHttpClient okHttpClient) {
        HttpFactory.okHttpClient = okHttpClient;
    }

**Comment by swankjesse** [comment]
Test case please.

**Comment by cocomikes** [comment]
Sorry,I don't have test case.

**Comment by swankjesse** [comment]
No action to take here.
