### ISSUE TITLE
TrustKit Integration (certificate pinning library)?

### ISSUE THREAD

**Issue by omerlh** [square/okhttp#3131]
Hey there,
[TrustKit](datatheorem/TrustKit-Android) is a library for Certificate Pinning implementation. Pretty similar to what you did here with CertificatePinner, but with reporting capability and Network Security Configuration compatibility. Integrating this library with a regular ok client is pretty easy, but integrating it with the client used by React Native is not easy at all (see this issue: datatheorem/TrustKit-Android#6). The main issue is that TrustKit implements pinning using [TrustManager](https://docs.oracle.com/javase/7/docs/api/javax/net/ssl/TrustManager.html), and the API does not expose the host name. Therefore, when creating TrustKit TrustManager, you need to supply it the host. Now, as React Native using one ok client for all network request, I can create it with TrustKit`s TrustManager and set the host to be our domain. But this will cause all network requests that are not to our domain to fail - because of the pinning.
So my question is pretty simple: How will you advise me to integrate TrustKit? One possible solution, used by another library, is using [interceptor](https://github.com/commonsguy/cwac-netsecurity/blob/master/netsecurity/src/main/java/com/commonsware/cwac/netsecurity/OkHttp3Integrator.java) to update the host name. Another possible solution is using custom CertificatePinner, maybe by inheritance (which is not possible currently as this class is final).
Thanks,
Omer

**Comment by swankjesse** [comment]
Interceptors are usually the best fit for problems like this.

**Comment by swankjesse** [comment]
It’s unfortunate that TrustKit assumes one TrustManager per host, which doesn’t work nicely with OkHttp. Your other option might be to submit code to them to support multiple hosts.

**Comment by omerlh** [comment]
Agree, I am willing to make changes to existing code, just wondering what will be the best place. When you talking about interceptor - do you reference to the solution I linked above? Or to write interceptor that do the validation manually (without using custom sslfactory/trustmanager in the ok client)?
And could you clarify why not enable custom CertificatePinner?
Thanks!

**Comment by omerlh** [comment]
I had in mind something like that for the network interceptor:
````java
new Interceptor() {
                    @Override
                    public Response intercept(Chain chain) throws IOException {
                        Request request = chain.request();
                        SSLSocket socket = (SSLSocket)chain.connection().socket();
                        trustKit.getInstance().getTrustManager(request.url().host()).checkServerTrusted(socket.getSession().getPeerCertificateChain(), "");
                        return chain.proceed(request);
                    }
                }
````
This is just demo, I am still not sure about the parameters needed to be passed to the TrustManager. But beside that, does this a good aproach to this problem?

**Comment by swankjesse** [comment]
Yeah, looks legit.

**Comment by omerlh** [comment]
Thanks. So I will work on the details with TrustKit guys, and I think we can close it for now - unless there are better suggestions.

**Comment by nabla-c0d3** [comment]
@swankjesse Thanks for the quick reply - TrustKit developer here.
I have a quick question: does this interceptor approach mean that the certificate chain will be validated twice in a row?
* First by OkHttp
* Then by the Interceptor itself (with TrustKit)

The downside of this is that TrustKit will not "see" when the server certificate chain is invalid (because OkHttp's validation will fail first). If that's the case, is there a way to have the interceptor validate certificate before OkHttp does its default validation ? 
Supporting multiple hosts would be tricky because older versions of Android don't pass the host to the checkServerTrusted() method.
Thanks!

**Comment by swankjesse** [comment]
@nabla-c0d3 Have you considered implementing `HostnameVerifier.verify()` ?

**Comment by omerlh** [comment]
@swankjesse If I got it correctly, it seems to me that the `HostnameVerifier.verify()` is called after the handshake (by looking in the code). Doesn't that mean it will happen after OkHttp validated the chain?

**Comment by swankjesse** [comment]
It's called after the handshake.

**Comment by omerlh** [comment]
So what the advantage of `HostnameVerifier.verify()` over Interceptor?

**Comment by nabla-c0d3** [comment]
@swankjesse Thanks - that's a really good suggestion and I didn't think of it. @omerlh it solves the problem of not knowing which hostname's identify we are validating (which is why our trustmanager is tied to one specific host). 
I need to try it out tho as it might lead to other issues.

**Comment by omerlh** [comment]
@nabla-c0d3 Agree, but this is true also to `Interceptor`, they have pretty much the same interface.

**Comment by omerlh** [comment]
@swankjesse - why not allow custom CertificatePinner? Currently, the class is sealed, but if that something that can be changed, we can try to integrate it with TrustKit. For example, AlamoFire doing something similar with [ServerTrustPolicy](https://github.com/Alamofire/Alamofire#security) and allow `customEvaluation`.

**Comment by swankjesse** [comment]
I guess I don’t understand why certificate pinners need to be pluggable. If there’s a feature ours is missing we should add it.

**Comment by omerlh** [comment]
I see two missing features that TrustKit add:
 - Android N backward compatibility - meaning, configure the pinning using Network Security Configuration
 - Reporting on pinning violation
If you consider adding those features, this should be enough. But it might be easier just to integrate TrustKit.

**Comment by swankjesse** [comment]
Gotcha. Doing it in an interceptor is probably just as good as a dedicated API. Or perhaps a custom SSL socket factory.

**Comment by omerlh** [comment]
Agreed, but as you can see from this thread, custom SSL socket (which is the current implementation of TrustKit) is not so easy, so interceptor is the preferred option. I just thought that it will be cleaner to use custom `CertificatePinner` as this is actually what I am doing...

**Comment by swankjesse** [comment]
Cool. I think what you're doing is best.
