### ISSUE TITLE
Update recipes to include sample code for closing responses

### ISSUE THREAD

**Issue by edorphy** [square/okhttp#3132]
Documentation/Recipe Update Request

The Response class documentation states that it, or its body, must be closed to avoid leaks. The documentation states this could be explicit via a close() call or implicit via using a try () block.

Is it worth updating the Recipe examples to illustrate this point? Looking solely at the recipes it is not clear that this should be done and may be overlooked by others as it was by me.

**Comment by yschimke** [comment]
I'm updating the docs in the Wiki, there are some out of date code snippets.  Is there any way to include code references instead of copy pasta?

Also a broken link

**Comment by yschimke** [comment]
Samples updated - https://github.com/square/okhttp/wiki/Recipes
