### ISSUE TITLE
Mixed responses when using same OkHttp client from different threads

### ISSUE THREAD

**Issue by angelomastropietro** [square/okhttp#3136]
Hi! First of all, thank you for your cooperation and the amazing work for OkHttp.
As the title says, I've experienced an issue that is randomly happening when using OkHttp.
In my Android application I'm using a shared OkHttp client which executes blocking requests from different threads. For some reason that I would like to discover with you, the responses of those requests are mixed up. 

In order to reproduce the issue [I wrote a test](https://gist.github.com/angelomastropietro/247862dabaac5f0e48215bee1058eeed). I'm using MockWebServer, hoping that the test is well written. If you run it, sometimes passes, sometimes it gives me the "expected wrong" behavior, as seen in the below picture:

<img width="1234" alt="schermata 2017-01-24 alle 16 07 39" src="https://cloud.githubusercontent.com/assets/20488914/22253739/02122616-e253-11e6-8362-6bcb200eac68.png">

Being a random event, I guess it's related to thread concurrency. Does this mean that requests to a web server should run with a minimum timespan between them? It sounds really weird to me though, probably I'm missing something here! Thank you.

**Comment by swankjesse** [comment]
Yeah, your code is racy. Avoid that by subclassing MockWebServer’s `Dispatcher`.

**Comment by angelomastropietro** [comment]
> Yeah, your code is racy.

Do you mean that I can't execute requests sequently in general? I'm experiencing this "mixed response" issue on a real web server. What if I don't use MockWebServer at all?

**Comment by swankjesse** [comment]
The racy part is MockWebServer. It returns the responses in the order they’re requested. Since your requests come through in arbitrary order, the responses are returned in arbitrary order. You workaround this by being more deliberate about matching requests to responses in the dispatcher.
