### ISSUE TITLE
OpenTracing  integration

### ISSUE THREAD

**Issue by pavolloffay** [square/okhttp#3151]
What kind of issue is this?

 - [ ] Question. This issue tracker is not the place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use Stack
       Overflow. https://stackoverflow.com/questions/tagged/okhttp

 - [ ] Bug report. If you’ve found a bug, spend the time to write a failing test. Bugs with tests
       get fixed. Here’s an example: https://gist.github.com/swankjesse/981fcae102f513eb13ed

 - [x] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
       already exists! Don’t send pull requests to implement new features without first getting our
       support. Sometimes we leave features out on purpose to keep the project small.

Hello, 

I'm working on Okhttp OpenTracing integration. OpenTracing standardizes instrumentations for distributed tracing e.g. you can track request between multiple services.

Here is my PR https://github.com/opentracing-contrib/java-okhttp/pull/1 for a `TracingInterceptor`. Could somebody from the team look at it? 

I have a couple of questions:
1. Can I pass an object from user code to the interceptor? Is it fine? I did not find any other way. 
2. `TracingInterceptor` is registered as an application and network interceptor. Is it ok to store a connection in ThreadLocal  (https://github.com/opentracing-contrib/java-okhttp/pull/1/files#diff-ea04702cc44ee71108eb6d612d7f2c0dR106) and access it later after `chain.proceed(request)` in application interceptor? 

[1]: OpenTracing: http://opentracing.io/
[2]: PR with tracing interceptor: https://github.com/opentracing-contrib/java-okhttp/pull/1

**Comment by swankjesse** [comment]
No further action on this.
