### ISSUE TITLE
Disk caching doesn't work when using BitmapFactory.decodeStream() with GIFs

### ISSUE THREAD

**Issue by murki** [square/okhttp#3152]
It looks like when using OkHttp to hit an url that will return a GIF file, and then consuming the returned stream with `BitmapFactory.decodeStream()` the file won't be cached into disk.

If I understand correctly the way `okhttp3.internal.cache.CacheInterceptor` works, it will use a `okio.ForwardingSink` to communicate the stream interactions to the `okhttp3.Cache` class, in order to signal its `DiskLruCache.Editor` to `commit()` to disk the stream that has just been exhausted and closed.

The problem seems to arise when consuming a GIF stream with `BitmapFactory.decodeStream()` which will load a single frame and very likely doesn't bother reading more than header+first frame from the stream, thus never triggering okhttp cache to write all the bytes to disk.

Is there any way to work around this or signal OkHttp to forcefully write its stream to disk cache?

I worked around this issue by writing this hacky Interceptor:

```java
/**
 * This interceptor is helpful if you want to force OkHttp to write the response to disk cache
 * immediately after receiving it (instead of waiting for the response body stream to be consumed).
 * Ideally it should only be used as a network interceptor (since application interceptors also
 * intercept when fetching from cache)
 */
public class DiskCacheEnforcerOkHttpInterceptor implements Interceptor {
    @Override
    public Response intercept(Chain chain) throws IOException {
        Response response = chain.proceed(chain.request());
        Logger.verbose("Flushing OkHttp Response bytes to force disk caching.");
        // by calling response.body().bytes() we force the stream to be consumed and thus cached to disk
        ResponseBody newResponseBody = ResponseBody.create(response.body().contentType(), response.body().bytes());
        return response.newBuilder().body(newResponseBody).build();
    }
}
```

**Comment by JakeWharton** [comment]
When `close()` is called OkHttp will spend 100ms trying to consume the remainder of the stream. You can choose to consume the entirety of the stream (without timeout) in your application layer after calling `decodeStream` if you want.

**Comment by murki** [comment]
Is there any way to change that 100ms value? (kind of a feature request at this point)

Unfortunately the call to `decodeStream` is happening outside of my control (inside [an image loading library](https://github.com/bumptech/glide/blob/master/library/src/main/java/com/bumptech/glide/load/resource/bitmap/Downsampler.java#L423) in this case).

**Comment by swankjesse** [comment]
Oooh, this is a tough case. I think your interceptor is actually a pretty great idea. You can make it even more efficient by using `BufferedSource.request()`:

```
public class DiskCacheEnforcerOkHttpInterceptor implements Interceptor {
    @Override
    public Response intercept(Chain chain) throws IOException {
        Response response = chain.proceed(chain.request());
        response.body().source().request(10 * 1024 * 1024);
        return response;
    }
}
```

That’ll pull the data until it’s loaded either 10 MiB or the end of the file. 

Alternately you could do a [ForwardingSource](https://square.github.io/okio/1.x/okio/okio/ForwardingSource.html) that calls `skip()` on `close()`. That way you only skip the unwanted bytes after you’ve downloaded the image.

**Comment by swankjesse** [comment]
(I don’t want to make the 100ms thing customizable.)

**Comment by murki** [comment]
Thanks @swankjesse I'll give your suggestions a try.

**Comment by KimiChiu** [comment]
So if the response is too big, then the OKHttp won't store it in the cache?
Because I'm facing this issue on my device.
Sometimes it doesn't write the stream into the cache.
So it's making the same network request again and again.
But it sometimes works on the emulator.

The `Cache-Control` header is added in both `Application interceptor` and `Network Interceptor`.

```
response.newBuilder()
    .removeHeader("Pragma")
    .removeHeader("Cache-Control")
    // cache for 3 day, 3600 * 24 * 3
    .header("Cache-Control", CACHE_MAX_AGE)
    .build()
```

**Comment by swankjesse** [comment]
After you read the image, manually exhaust the response body with `responseBody.source.skip(Long.MAX_VALUE)`.

**Comment by swankjesse** [comment]
No action to take here.
