### ISSUE TITLE
OkHttp slow compared to Python's requests library

### ISSUE THREAD

**Issue by shekhargulati** [square/okhttp#3153]
I have written a simple OkHttpClient that downloads HTML of a web page. The below code takes 5 seconds to fetch the HTML. The next calls to the same URL takes less than a second so I am assuming OKHttp caches a connection.

```java
OkHttpClient client = new OkHttpClient();
Request request = new Request.Builder().get().url("https://www.forbes.com/sites/startswithabang/2017/01/24/nobody-knows-where-a-black-holes-information-goes/").build();
long start = System.currentTimeMillis();
Call call = client.newCall(request);
call.execute();
long end = System.currentTimeMillis();
System.out.println(String.format("Total time: %d sec(s)", (end - start) / 1000));
```

If I try the same using Python requests API it takes less than a second.

```python
import time
import requests

start = time.time()
r = requests.get("https://www.forbes.com/sites/startswithabang/2017/01/24/nobody-knows-where-a-black-holes-information-goes/")
print(r.text)
end = time.time()
print(end - start)
```

I am trying to understand why OkHttp take more time to make same request. Can someone help me understand difference? Are there any configuration options I can use?

**Comment by yschimke** [comment]
No definitive answer here but forbes returns ipv4 and ipv6 addresses, so possible it is retrying automatically internally.  It is fast for me.

Dns (www.forbes.com): www.forbes.com/2a02:26f0:64:290:0:0:0:2599, www.forbes.com/2a02:26f0:64:299:0:0:0:2599, www.forbes.com/2.16.31.181
