### ISSUE TITLE
How to build okhttp.jar from https://android.googlesource.com/platform/external/okhttp/

### ISSUE THREAD

**Issue by beaumontk** [square/okhttp#3155]
What kind of issue is this?

 - [x] Question. This issue tracker is not the place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use Stack
       Overflow. https://stackoverflow.com/questions/tagged/okhttp

 - [ ] Bug report. If you’ve found a bug, spend the time to write a failing test. Bugs with tests
       get fixed. Here’s an example: https://gist.github.com/swankjesse/981fcae102f513eb13ed

 - [ ] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
       already exists! Don’t send pull requests to implement new features without first getting our
       support. Sometimes we leave features out on purpose to keep the project small.

**Comment by beaumontk** [comment]
see https://github.com/square/okhttp/issues/2201.

I cloned: https://android.googlesource.com/platform/external/okhttp/
How do I build okhttp.jar for Android? mvn, ndk-build, other?
mvn gives errors. ndk-build looks for jni dir and needs Application.mk
Please explain.
KB

**Comment by JakeWharton** [comment]
We don't control that repository so this isn't the place to ask questions about it. Instructions for building Android are available on http://s.android.com/source/building.html.

**Comment by beaumontk** [comment]
Jake,
I don't want to build Android! Just my version of okhttp.jar.
Maybe you could give me some clues about how to build this from the Google repository?
By the way, I posted the same question on Stack Exchange.
Regards,
Keith
--------------------------------------------
On Mon, 6/2/17, Jake Wharton <notifications@github.com> wrote:

 Subject: Re: [square/okhttp] How to build okhttp.jar from https://android.googlesource.com/platform/external/okhttp/ (#3155)
 To: "square/okhttp" <okhttp@noreply.github.com>
 Cc: "beaumontk" <beaumont_k@yahoo.co.uk>, "Author" <author@noreply.github.com>
 Date: Monday, 6 February, 2017, 13:41
 
 We don't control that
 repository so this isn't the place to ask questions
 about it. Instructions for building Android are available on
 http://s.android.com/source/building.html.
 
 —
 You are receiving this because you authored the thread.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.

**Comment by JakeWharton** [comment]
The version of OkHttp in AOSP builds using AOSP's build system.

**Comment by beaumontk** [comment]
I spent a lot of time yesterday trying to frig the AOSP build system without downloading the whole of it! But this was frustratingly difficult (on x86!). I ONLY want my own version of okhttp.jar, but using thejarjar rules in AOSP.
I just tried to implement this:
https://sonatype.github.io/jarjar-maven-plugin/ in your okhttp3, but it crashed with:
[ERROR] Failed to execute goal org.sonatype.plugins:jarjar-maven-plugin:1.9:jarjar (default) on project my.project: Unable to JarJar: null cause: null: NullPointerException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.sonatype.plugins:jarjar-maven-plugin:1.9:jarjar (default) on project my.project: Unable to JarJar: null cause: null
...
Caused by: java.lang.NullPointerException
        at com.tonicsystems.jarjar.JarJarMojo.execute(JarJarMojo.java:131)

Any ideas?

Also:
1 The AOSP version of okhttp.jar includes okio. How do I modify pom.xml to do this?
2 Can I dex the jar with pom.xml for use on Android?

Hope you can help.
KB

**Comment by beaumontk** [comment]
In pom.xml (from https://sonatype.github.io/jarjar-maven-plugin/):
      <plugin>
        <groupId>org.sonatype.plugins</groupId>
        <artifactId>jarjar-maven-plugin</artifactId>
        <executions>
          <execution>
            <phase>package</phase>
            <goals>
              <goal>jarjar</goal>
            </goals>
            <configuration>
              <includes>
                <include>asm:asm</include>
                <include>org.sonatype.sisu.inject:cglib</include>
              </includes>
              <rules>
                <rule>
                  <pattern>com.squareup.**</pattern>
                  <result>com.android.@1</result>
                </rule>
                <rule>
                  <pattern>okio.**</pattern>
                  <result>com.android.okhttp.okio.@1</result>
                </rule>
              </rules>
            </configuration>
          </execution>
        </executions>
      </plugin>
