### ISSUE TITLE
Websockets: pass event type

### ISSUE THREAD

**Issue by IlyaMyasoedov** [square/okhttp#3158]
Hello! I can't find any solution for the issue. When I use okhttp library for websockets i cannot pass event type. 
For example. when i used socket.io library https://github.com/socketio/socket.io-client-java I sent json object with type field named data_type. 

```
public class ChatMessage {
    private String data_type;
    private Object data;

    public ChatMessage(String data_type, Object data) {
        this.data_type = data_type;
        this.data = data;
    }

    public String getData_type() {
        return this.data_type;
    }

    public void setData_type(String data_type) {
        this.data_type = data_type;
    }

    public Object getData() {
        return this.data;
    }

    public void setData(Object data) {
        this.data = data;
    }
}

```

then i convert this object to json and pass to socket.io. All is Ok:
```
...
ChatMessage chatMessage = new ChatMessage ();

...
SocketIo.send(getConverter().toJson(chatMessage))
```

**Comment by swankjesse** [comment]
OkHttp doesn't implement the Socket.IO API. Only websockets. You might find this explanation helpful in the history of these.
https://medium.com/@ivanderbyl/why-you-don-t-need-socket-io-6848f1c871cd#.sli88v2sm
