### ISSUE TITLE
Unable to close OkHttpClient - ConnectionPool exists forever. 

### ISSUE THREAD

**Issue by HubertWo** [square/okhttp#3160]
Code to reproduce problem:
https://gist.github.com/HubertWo/ad16547fecaca76e14a0016a74f19c33

Evidences.

Before:
![before](https://cloud.githubusercontent.com/assets/2518652/22905039/0409ccd4-f23f-11e6-913e-2586ac355586.png)

After fix presented in example.
![after](https://cloud.githubusercontent.com/assets/2518652/22905040/040b4ab4-f23f-11e6-93ae-dac0fdfa4462.png)

**Comment by swankjesse** [comment]
Not sure what action to take on this. Private connection pools are private, shared ones are shared. We’re pretty explicit about recommending shared connection pools for most applications.
