### ISSUE TITLE
javax.net.ssl.SSLHandshakeException: Connection closed by peer

### ISSUE THREAD

**Issue by HealerKnight** [square/okhttp#3162]
This exception occur when I use HTTPS,My code is as follows:

` @Singleton
    @Provides
    @HttpType("Api")
    OkHttpClient provideOkHttpClient(Context context) {
        OkHttpClient.Builder builder = new OkHttpClient.Builder();
        if (BuildConfig.DEBUG) {
            builder.addInterceptor(new HttpLoggingInterceptor().setLevel(HttpLoggingInterceptor.Level.BODY));
        }
        builder.socketFactory(HttpsUtil.getSSLSocketFactory(context));
        builder.hostnameVerifier(HttpsUtil.getHostnameVerifier(new String[]{}));
        
        builder.connectTimeout(8* 1000, TimeUnit.MILLISECONDS)
                .readTimeout(8* 1000, TimeUnit.MILLISECONDS);
        return builder.build();
    }`

    `private final static String CLIENT_PRI_KEY = "client.bks";
    private final static String TRUSTSTORE_PUB_KEY = "client.bks";
    private final static String CLIENT_BKS_PASSWORD = "123456";
    private final static String TRUSTSTORE_BKS_PASSWORD = "123456";
    private final static String KEYSTORE_TYPE = "BKS";
    private final static String PROTOCOL_TYPE = "TLS";
    private final static String CERTIFICATE_FORMAT_X509 = "X509";

    public static SSLSocketFactory getSSLSocketFactory(Context context) {
        SSLSocketFactory sslSocketFactory = null;
        KeyStore keyStore = null;// 
        KeyStore trustStore = null;//
        InputStream clientKSIn = null;
        InputStream trustStoreIn = null;
        try {
            keyStore = KeyStore.getInstance(KEYSTORE_TYPE);
            trustStore = KeyStore.getInstance(KEYSTORE_TYPE);
            clientKSIn = context.getAssets().open(CLIENT_PRI_KEY);
            trustStoreIn = context.getAssets().open(TRUSTSTORE_PUB_KEY);
            keyStore.load(clientKSIn, CLIENT_BKS_PASSWORD.toCharArray());
            trustStore.load(trustStoreIn, TRUSTSTORE_BKS_PASSWORD.toCharArray());

          
            SSLContext sslContext = SSLContext.getInstance(PROTOCOL_TYPE);
           
            TrustManagerFactory trustManagerFactory = TrustManagerFactory.getInstance(TrustManagerFactory.getDefaultAlgorithm());
            trustManagerFactory.init(trustStore);
          
            KeyManagerFactory keyManagerFactory = KeyManagerFactory.getInstance(TrustManagerFactory.getDefaultAlgorithm());
            keyManagerFactory.init(keyStore, CLIENT_BKS_PASSWORD.toCharArray());
//          sslContext.init(keyManagerFactory.getKeyManagers(), trustManagerFactory.getTrustManagers(), new java.security.SecureRandom());
            sslContext.init(null, trustManagerFactory.getTrustManagers(), new SecureRandom());
            sslSocketFactory = sslContext.getSocketFactory();
//          sslSocketFactory = new NoSSLv3SocketFactory(sslContext.getSocketFactory());//Unconnected sockets not implemented
//          sslSocketFactory = new TLSSocketFactory();
            clientKSIn.close();
            trustStoreIn.close();
        } catch (KeyStoreException e) {
            e.printStackTrace();
        } catch (IOException e) {
            e.printStackTrace();
        } catch (NoSuchAlgorithmException e) {
            e.printStackTrace();
        } catch (CertificateException e) {
            e.printStackTrace();
        } catch (UnrecoverableKeyException e) {
            e.printStackTrace();
        } catch (KeyManagementException e) {
            e.printStackTrace();
        }

        return sslSocketFactory;
    }

    /**
     * set HostnameVerifier
     * {@link HostnameVerifier}
     */
    public static HostnameVerifier getHostnameVerifier(final String[] hostUrls) {

        HostnameVerifier TRUSTED_VERIFIER = new HostnameVerifier() {

            public boolean verify(String hostname, SSLSession session) {
//                boolean ret = false;
//                for (String host : hostUrls) {
//                    if (host.equalsIgnoreCase(hostname)) {
//                        ret = true;
//                    }
//                }
//                return ret;
                return true;
            }
        };

        return TRUSTED_VERIFIER;
    }`

how can i solve this problem?thank you!

**Comment by swankjesse** [comment]
Please use StackOverflow for usage questions.
