### ISSUE TITLE
Some problems with HTTP/2 and timeouts on Android

### ISSUE THREAD

**Issue by ekstro** [square/okhttp#3163]
We have problems with timeout requests on Android.

Please see example below:

OkHttp 3.6
Retrofit 2.1
Android > 5.0.1

2. Create an OkHttp client
3. New GET (or POST) requests (loop, synchronous with 1 s between requests) to HTTP/2 server (we also use Cloudflare)

** server log **
GET test?id=0 200
GET test?id=1 200
GET test?id=2 200

3. Bring the network down (we disconnect the cable from the router but device is still connected to the router)
4. Wait for eg. 30-60 seconds
5. We get timeout for requests

** device log **
GET test?id=3 timeout
GET test?id=4 timeout
GET test?id=5 timeout
GET test?id=6 timeout
GET test?id=7 timeout
GET test?id=8 timeout
GET test?id=9 timeout
GET test?id=10 timeout
GET test?id=11 timeout
GET test?id=12 timeout
GET test?id=13 timeout
GET test?id=14 timeout
GET test?id=15 timeout
GET test?id=16 timeout

6. Bring the network back

** server log **
test?id=7 200	
test?id=16 200
test?id=5 200
test?id=4 200
test?id=6 200
test?id=8 200
test?id=14 200
test?id=10 200
test?id=9 200

Request from 3 to 16 were timeout on device so why all requests run quietly (and in different order) when network was back? We can't get their results from this request becasue there was timeout on the device.

**Comment by swankjesse** [comment]
What behavior would you prefer?

**Comment by ekstro** [comment]
Tell me if I don't get it: if the request is timeout on the device, it shouldn't be passed to server?

**Comment by swankjesse** [comment]
It's already enqueued for transmission and we can't claw it back. Typically the workaround for this is making all requests idempotent.

**Comment by ekstro** [comment]
1. Ok, so if it's already enqueued the thing I don't understand is that if we connect directly to our server (with http/2), NOT by Cloudflare, then this situation doesn't happen. Requests which had timeout don't reach the server. So this queue depends on the server configuration?
2. If we connect by Cloudflare, wait 5 minutes and bring the web back, the requests don't reach the server - I guess this happens because the socket is closed (Keep-Alive: 300), right?

Thanks for your reply.

**Comment by swankjesse** [comment]
No action to take on this.
