### ISSUE TITLE
Different logging level for request and response

### ISSUE THREAD

**Issue by nkuznetsow** [square/okhttp#3165]
It would be helpful to have ability to set different log level for request and response in okhttp-logging-interceptor. For example, I would like to log all requests body but I wouldn't log responses body, because, it may be too large.

**Comment by swankjesse** [comment]
Please copy+paste the log interceptor and customize to your liking? It’s just there for the basic use cases.

Or use a more sophisticated tool like [Chuck](https://github.com/jgilfelt/chuck).

**Comment by swankjesse** [comment]
No action to take on this.
