### ISSUE TITLE
More flexible authenticator - Feature Request

### ISSUE THREAD

**Issue by hrchu** [square/okhttp#3167]
Current authenticator cannot do some kinds of auth scheme, e.g., AWS auth. It is due to:
1. Current authenticator will be triggered only when facing 401 responses. 
2. It also can only construct Auth header by Route, instead of full request information, e.g., URL.

Authenticator  will be more flexible if it can be triggered before challenge and build Auth header by request content, just like  pyhon requests library: http://docs.python-requests.org/en/master/user/authentication/

**Comment by swankjesse** [comment]
Would you consider using an interceptor?
https://github.com/square/okhttp/wiki/Interceptors

**Comment by swankjesse** [comment]
No action to take on this.
