### ISSUE TITLE
Cannot get out of while(true) - RealConnection#347 - squid3 - 407

### ISSUE THREAD

**Issue by dzmitrykashlach** [square/okhttp#3168]
I have a problem with OkHttp-3.4.1 when using it with squid3 as proxy. When I test my client with incorrect proxy credentials(proxy returns 407), I get into [while(true){} loop](https://github.com/square/okhttp/blob/158692870d5a5cf1fdf42bd62a18ffa699d7e0b3/okhttp/src/main/java/okhttp3/internal/connection/RealConnection.java#L347) which I cannot get out from.

So client is hanging forever. How can I solve this? Please, advice. Thanks.

**Comment by swankjesse** [comment]
Does this help?
https://github.com/square/okhttp/blob/master/samples/guide/src/main/java/okhttp3/recipes/Authenticate.java

**Comment by dzmitrykashlach** [comment]
Yes, using "Proxy-Authorization" header did the trick.
