### ISSUE TITLE
Call.cancel() works, forward to onFailure callback but Call.isCancelled() always returns false

### ISSUE THREAD

**Issue by cs-leonardo-aramaki** [square/okhttp#3169]
I'm cancelling calls by their tags it's working fine, forwarding the cancellation to onFailure callback with an IOException containing the message "Cancelled". 
When I execute call.isCancelled() from the onFailure method though it's always returning false.

I'm using OkHttp 3.6.0. Is it a bug?

**Comment by swankjesse** [comment]
Yeah, sounds like a bug. Can you confirm with a test case?

**Comment by cs-leonardo-aramaki** [comment]
@swankjesse I did further experimentations here and it seems like a Retrofit issue, not an OkHttp one. 
I'm cancelling the requests through the okhttp client. By doing that, the call is canceled but the status is no propagated to Retrofit's own Call object.

**Comment by JakeWharton** [comment]
I believe this will be fixed in the forthcoming 2.2.0 release of Retrofit.

**Comment by NightlyNexus** [comment]
Yes. https://github.com/square/retrofit/commit/2074732da81f1079cccf8a6bf7cc2e37d2666bc8
