### ISSUE TITLE
Unify SocketTimeoutException message

### ISSUE THREAD

**Issue by dave-r12** [square/okhttp#3172]
I've seen this test fail locally and during PR's:

```
readTimeoutAppliesToHttpRequest(okhttp3.internal.ws.WebSocketHttpTest)  Time elapsed: 0.52 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:<[time]out> but was:<[Read timed ]out>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at okhttp3.internal.ws.WebSocketRecorder.assertFailure(WebSocketRecorder.java:194)
	at okhttp3.internal.ws.WebSocketHttpTest.readTimeoutAppliesToHttpRequest(WebSocketHttpTest.java:468)
```

Studying it, it appears there is a small race when Java's timeout mechanism triggers before Okio's AsyncTimeout. In the end, the same exception is thrown but with a different message. I don't think this is really an issue except for test cases.

Ideas that come to mind:
* In Okio, if the IOException is a SocketTimeoutException, wrap and re-throw with message "timeout".
* Change tests to use `contains` rather than `equals`.

**Comment by swankjesse** [comment]
Fixed the tests here:
https://github.com/square/okhttp/pull/3284
