### ISSUE TITLE
Attempt to invoke interface method 'okio.BufferedSink okio.BufferedSink.writeUtf8(java.lang.String)' on a null object reference

### ISSUE THREAD

**Issue by devinhu** [square/okhttp#3176]
Caused by: java.lang.NullPointerException:Attempt to invoke interface method 'okio.BufferedSink okio.BufferedSink.writeUtf8(java.lang.String)' on a null object reference
1	at okhttp3.internal.http.Http1xStream.writeRequest(Http1xStream.java:167)
2	at okhttp3.internal.http.Http1xStream.writeRequestHeaders(Http1xStream.java:123)
3	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:42)
4	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
5	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
6	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
7	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
8	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:109)
9	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
10	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
11	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
12	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
13	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:124)
14	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
15	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
16	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:170)
17	at okhttp3.RealCall.access$100(RealCall.java:33)
18	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:120)
19	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
20	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
21	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
22	at java.lang.Thread.run(Thread.java:818)

**tips:  okhttp version is 3.3.1**

**Comment by swankjesse** [comment]
Could you provide an executable test case to demonstrate this problem? As-is this isn’t actionable.
