### ISSUE TITLE
Attempt to read from field 'int okio.Segment.limit' on a null object reference

### ISSUE THREAD

**Issue by devinhu** [square/okhttp#3177]
Caused by: java.lang.NullPointerException:Attempt to read from field 'int okio.Segment.limit' on a null object reference
1	at okio.Okio$1.write(Okio.java:77)
2	at okio.AsyncTimeout$1.write(AsyncTimeout.java:180)
3	at okio.RealBufferedSink.flush(RealBufferedSink.java:216)
4	at okhttp3.internal.http.Http1xStream.finishRequest(Http1xStream.java:161)
5	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:51)
6	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
7	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
8	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
9	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
10	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:109)
11	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
12	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
13	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
14	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
15	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:124)
16	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
17	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
18	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:170)
19	at okhttp3.RealCall.access$100(RealCall.java:33)
20	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:120)
21	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
22	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
23	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
24	at java.lang.Thread.run(Thread.java:818)

tips: the okhttp version 3.3.1

**Comment by swankjesse** [comment]
Could you provide an executable test case? As-is this isn’t actionable.
