### ISSUE TITLE
Monitor WebSocket upload progress with okHttp 3.5+

### ISSUE THREAD

**Issue by mpost** [square/okhttp#3178]
Up until okHttp 3.5 the preliminary WebSocket API used a `RequestBody` to send data over a `WebSocket` connection. This allowed to monitor the upload progress in the `writeTo(BufferedSink sink)` method of the `RequestBody`.

With the the introduction of the "stable" websocket API in okHttp 3.5 you have to provide either a `String` (for TEXT data) or a `ByteString` (for BINARY data). Both of these classes do not allow to monitor its reading progress.

Is there any replacement for monitoring the upload progress during a `WebSocket` send operation in okHttp 3.5+?

**Comment by swankjesse** [comment]
There's no such mechanism. Your best bet is to probably use regular HTTP for such uploads.

**Comment by mpost** [comment]
We are implementing the behavior of the the `bufferedAmount` as specified by the WebSocket definition on [mdn](https://developer.mozilla.org/en-US/docs/Web/API/WebSocket#Attributes). The amount of bytes decreases while bytes are being send.

While the `bufferedAmount` is not part of the [rfc](https://tools.ietf.org/html/rfc6455) it would great to be able to provide the same functionality than the mdn definition.

**Comment by swankjesse** [comment]
Does this work? http://square.github.io/okhttp/3.x/okhttp/okhttp3/WebSocket.html#queueSize--

**Comment by mpost** [comment]
@swankjesse Ah i missed that. Looks good. Thanks. Closing this issue for now.
