### ISSUE TITLE
javax.net.ssl.SSLHandshakeException: Chain validation failed

### ISSUE THREAD

**Issue by cnsilvan** [square/okhttp#3180]
This error occurs only in Android Nougat and above when use self-signed certificate。

**Comment by cnsilvan** [comment]
targetSdkVersion 22 
compileSdkVersion 25

**Comment by unext-wendong** [comment]
Can someone explain the reason why this issue was closed? Was it fixed? Or it's not a valid issue (why)?

**Comment by unext-wendong** [comment]
We see this issue on Android 7.0 with the latest version 3.8.1.

It happens only in the first time when we try to make a https post request after device bootups.
After that, it just works fine.

**Comment by gitcarlosandrade** [comment]
I have the same issue on android emulator with API 26

OkHttp version: 3.8.0
targetSdkVersion: 25
compileSdkVersion: 25

**Comment by unext-wendong** [comment]
Is anyone monitoring this? It'll be nice if someone makes a comment.

**Comment by swankjesse** [comment]
Creating an executable test case is the best way to get something fixed.

**Comment by unext-wendong** [comment]
When trying to implement a test case, I found out the possible cause for my issue.

The device I'm using always resets its system time to a fixed time in the past when booting up, and updates the time to the current time shortly after. The certificate verification fails if the https request is made before the system time is updated.

Not related to okhttp. Should have found this before coming to here. Sorry for the trouble.

**Comment by cnsilvan** [comment]
Not related to okhttp.

**Comment by vivchar** [comment]
I have the same problem when I am trying to load a image from the github:

Code:
`
final String url = "https://avatars0.githubusercontent.com/u/6949942?v=4";
Glide.with(getContext()).load(url).into(imageView);
`

Exception:

> W/Glide: Load failed for https://avatars0.githubusercontent.com/u/6949942?v=4 with size [317x317]
>                                                                     class com.bumptech.glide.load.engine.GlideException: Failed to load resource
>                                                                       Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Fetching data failed, class java.io.InputStream, REMOTE
>                                                                         Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Fetch failed
>                                                                           Cause (1 of 1): class javax.net.ssl.SSLHandshakeException: Chain validation failed
> E/Glide: class com.bumptech.glide.load.engine.GlideException: Failed to load resource
> I/Glide: Root cause (1 of 1)
>                                                                     javax.net.ssl.SSLHandshakeException: Chain validation failed
>                                                                         at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:355)
>                                                                         at com.android.okhttp.internal.io.RealConnection.connectTls(RealConnection.java:192)
>                                                                         at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:149)
>                                                                         at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:112)
>                                                                         at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:184)
>                                                                         at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
>                                                                         at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
>                                                                         at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:281)
>                                                                         at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224)
>                                                                         at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:461)
>                                                                         at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:127)
>                                                                         at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:89)
>                                                                         at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(Unknown Source:0)
>                                                                         at com.bumptech.glide.load.data.HttpUrlFetcher.loadDataWithRedirects(HttpUrlFetcher.java:101)
>                                                                         at com.bumptech.glide.load.data.HttpUrlFetcher.loadData(HttpUrlFetcher.java:53)
>                                                                         at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.loadData(MultiModelLoader.java:95)
>                                                                         at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.startNextOrFail(MultiModelLoader.java:144)
>                                                                         at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.onLoadFailed(MultiModelLoader.java:138)
>                                                                         at com.bumptech.glide.load.data.HttpUrlFetcher.loadData(HttpUrlFetcher.java:59)
>                                                                         at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.loadData(MultiModelLoader.java:95)
>                                                                         at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:61)
>                                                                         at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:282)
>                                                                         at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:252)
>                                                                         at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:222)
>                                                                         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
>                                                                         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
>                                                                         at java.lang.Thread.run(Thread.java:764)
>                                                                         at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:347)
>

**Comment by maoqis** [comment]
get it

**Comment by FabianTerhorst** [comment]
I can reproduce it 100% with an xiaomi mi a1. On nexus 9, 10, 6p, pixel, essential ph1 works.

**Comment by scottkruse** [comment]
I can reproduce anytime i set my system clock into the future (testing 1 month ahead of the current time)

**Comment by yschimke** [comment]
@scottkruse so SSL and faking time don't mix well.  e.g. let's encrypt use certificates for 90 days, so many popular sites will issue certificates that have expired in the next month.

**Comment by leizGit** [comment]
> When trying to implement a test case, I found out the possible cause for my issue.
> 
> The device I'm using always resets its system time to a fixed time in the past when booting up, and updates the time to the current time shortly after. The certificate verification fails if the https request is made before the system time is updated.
> 
> Not related to okhttp. Should have found this before coming to here. Sorry for the trouble.

Did it not work at the wrong time? How to fix it?

**Comment by unext-wendong** [comment]
> Did it not work at the wrong time? How to fix it?

If the system time is set to time point at which the server certificate is not valid, https will fail.

We fixed it by waiting for system time to be updated before making any https requests.

**Comment by Minhalatgit** [comment]
I fixed it by just changing the api's base url from "https" to "http"

**Comment by LetsHandOutOurMastery** [comment]
I tried the above solutions but still its not working for me. Whenever Im trying to save data in aws amplify datastore, im receiving this exception.

DataStoreException{message=Failure during mutation., cause=ApiException{message=OkHttp client request failed., cause=javax.net.ssl.SSLHandshakeException: Chain validation failed, recoverySuggestion=See attached exception for more details.}, recoverySuggestion=Check details.}
W/amplify:aws-datastore(31591): 	at com.amplifyframework.datastore.appsync.AppSyncClient.lambda$mutation$5(AppSyncClient.java:359)
W/amplify:aws-datastore(31591): 	at com.amplifyframework.datastore.appsync.-$$Lambda$AppSyncClient$FfgHx1XvivjmTcZhtf9BjbrAq_M.accept(Unknown Source:4)
W/amplify:aws-datastore(31591): 	at com.amplifyframework.api.aws.AppSyncGraphQLOperation$OkHttpCallback.onFailure(AppSyncGraphQLOperation.java:157)
W/amplify:aws-datastore(31591): 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:525)
W/amplify:aws-datastore(31591): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/amplify:aws-datastore(31591): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/amplify:aws-datastore(31591): 	at java.lang.Thread.run(Thread.java:920)
W/amplify:aws-datastore(31591): Caused by: ApiException{message=OkHttp client request failed., cause=javax.net.ssl.SSLHandshakeException: Chain validation failed, recoverySuggestion=See attached exception for more details.}
W/amplify:aws-datastore(31591): 	... 5 more
W/amplify:aws-datastore(31591): Caused by: javax.net.ssl.SSLHandshakeException: Chain validation failed

**Comment by k9ne257** [comment]
> I fixed it by just changing the api's base url from "https" to "http"

Trying this gave me the following error:
com.android.volley.NoConnectionError: java.io.IOException: Cleartext HTTP traffic to ***.***.***.*** not permitted

where ***.***.***.*** is the ip of my backend server

**Comment by yosefyudha** [comment]
> We see this issue on Android 7.0 with the latest version 3.8.1.
> 
> It happens only in the first time when we try to make a https post request after device bootups. After that, it just works fine.

I have the same issue, even though I'm on Android 14. I've tried so many solution, but still solve the problem.
