### ISSUE TITLE
Android okhttp CertificatePinner  not working

### ISSUE THREAD

**Issue by mohamedchouat** [square/okhttp#3181]
# the problem here is # the web service works fine if i enter a invalid sha pins

  CertificatePinner certificatePinner = new CertificatePinner.Builder()
                    .add(HOSTNAME, "sha256/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA")
                    .build();

            OkHttpClient client;
            client = new OkHttpClient.Builder()
                    .certificatePinner(certificatePinner)
                    .connectTimeout(timeOut, TimeUnit.MILLISECONDS)
                    .readTimeout(timeOut, TimeUnit.MILLISECONDS)

                    .authenticator(new Authenticator() {
                        @Override
                        public Request authenticate(Route route, Response response) throws IOException {
                            String credential = Credentials.basic("aaaaaaaaaa", "aaaaaaaaaaaaa");
                            return response.request().newBuilder()
                                    .header("Authorization", credential)
                                    .build();
                        }
                    })
                    .build();
 Request request;

        Response response = null;
       if (method == GET) {

            if (paramsGet != null) {
                String paramString = URLEncodedUtils
                        .format(paramsGet, "utf-8");
                url += "?" + paramString;
            }

            String deviceID = Utility.DEVICE_ID;
            String carrier = Utility.CARRIER;

            request = new Request.Builder()
                    .url(url)

                    .addHeader("Device", deviceID)
                    .addHeader("carrier", carrier)
                    .build();

            response = client.newCall(request).execute();

        }

**Comment by swankjesse** [comment]
Please provide an executable test case. As is this isn’t actionable.
