### ISSUE TITLE
Reading a response body via GzipSource within a network interceptor results in a truncated response further down the chain

### ISSUE THREAD

**Issue by jgilfelt** [square/okhttp#3182]
I want to read and decompress the contents of gzip encoded responses in the network interceptor chain. I can do this using code like:

```java
String contentEncoding = response.header("Content-Encoding");
if (contentEncoding != null && contentEncoding.equalsIgnoreCase("gzip")) {
    GzipSource source = new GzipSource(response.body().source());
    String body = Okio.buffer(source).readUtf8();
    // do something with body ...
}
return response;

```

This works for the purposes of my interceptor. However, when the response is passed back to the application code (or another interceptor further down the chain), I receive a `java.io.EOFException` like the one below when the response body is read again.

```java
java.io.EOFException
	at okio.RealBufferedSource.require(RealBufferedSource.java:59)
	at okio.GzipSource.consumeHeader(GzipSource.java:114)
	at okio.GzipSource.read(GzipSource.java:73)
	at okio.RealBufferedSource.request(RealBufferedSource.java:66)
	at okio.RealBufferedSource.rangeEquals(RealBufferedSource.java:387)
	at okio.RealBufferedSource.rangeEquals(RealBufferedSource.java:371)
	at okhttp3.internal.Util.bomAwareCharset(Util.java:412)
	at okhttp3.ResponseBody.string(ResponseBody.java:173)
	at org.okhttptest.BreakingGzipInterceptorTest.test(BreakingGzipInterceptorTest.java:44)
	...

```

Any ideas what I am doing wrong? The server responses are perfectly valid, and I'm not doing any other response rewriting as far as I know. 

Here is a simple test using the mock web server that reproduces the issue: https://gist.github.com/jgilfelt/223978009329d8158d86ee4ea82a3514

I'm using OkHttp 3.6.0

**Comment by swankjesse** [comment]
Tragically, the response body may only be consumed 1x. But you can cheat with Response.peekBody.

**Comment by jgilfelt** [comment]
Aha! Thanks. I guess this was fine with plain text because I could read directly from the buffered source.

**Comment by JakeWharton** [comment]
The logging-interceptor also provides a good example for how to read the
body without affecting the normal pipeline. It works as both a network
interceptor and application interceptor.
