### ISSUE TITLE
SSLHandshakeException: Connection closed by peer

### ISSUE THREAD

**Issue by Pitel** [square/okhttp#3188]
I have some API server (not under my management).

And according to `nmap --script ssl-enum-ciphers`, it has the following cipers:
```
| ssl-enum-ciphers: 
|   TLSv1.0: 
|     ciphers: 
|       TLS_RSA_WITH_RC4_128_MD5 (rsa 2048) - A
|       TLS_RSA_WITH_RC4_128_SHA (rsa 2048) - A
|       TLS_RSA_WITH_3DES_EDE_CBC_SHA (rsa 2048) - C
|       TLS_RSA_WITH_DES_CBC_SHA (rsa 2048) - C
|       TLS_RSA_EXPORT1024_WITH_RC4_56_SHA - D
|       TLS_RSA_EXPORT1024_WITH_DES_CBC_SHA - D
|       TLS_RSA_EXPORT_WITH_RC4_40_MD5 - E
|       TLS_RSA_EXPORT_WITH_RC2_CBC_40_MD5 - E
|     compressors: 
|       NULL
|     cipher preference: server
|     warnings: 
|       Ciphersuite uses MD5 for message integrity
|_  least strength: E
```

Not very secure, I know, but I can't do much with it.

when using `curl`, I ends with following:
```
* SSL connection using TLS1.0 / RSA_3DES_EDE_CBC_SHA1
```

And when I try to connect to it with OkHttp on Android, I get this exception.

I tried this in my code:
```java
final OkHttpClient okhttp = new OkHttpClient.Builder()
		.connectionSpecs(Collections.singletonList(ConnectionSpec.COMPATIBLE_TLS))
		.build();
```

According to source code of `ConnectionSpec.COMPATIBLE_TLS`, it should support `TLS1.0` and `RSA_3DES_EDE_CBC_SHA`, so why it doesn't work?

Tested on Android 5 and 7.

**Comment by Pitel** [comment]
And when I try to write it to fit the server:
```java
new ConnectionSpec.Builder(ConnectionSpec.COMPATIBLE_TLS)
		.tlsVersions(TlsVersion.TLS_1_0)
		.cipherSuites(CipherSuite.TLS_RSA_WITH_3DES_EDE_CBC_SHA)
		.supportsTlsExtensions(false)
		.build()
```

I get this exception:
```
java.net.UnknownServiceException: Unable to find acceptable protocols. isFallback=false, modes=[ConnectionSpec(cipherSuites=[SSL_RSA_WITH_3DES_EDE_CBC_SHA], tlsVersions=[TLS_1_0], supportsTlsExtensions=true)], supported protocols=[TLSv1, TLSv1.1, TLSv1.2]
```

**Comment by swankjesse** [comment]
Sadly you need to enable these old bad cipher suites in the SSLSocketFactory layer as well. Here’s an ugly example to get you started:

https://github.com/square/okhttp/blob/master/samples/guide/src/main/java/okhttp3/recipes/CustomCipherSuites.java

**Comment by Pitel** [comment]
Tanks. Luckily, I was able to convince the API providers to update their sipher suites. :)
