### ISSUE TITLE
ArrayIndexOutOfBoundsExceptionsrc.length=8192 srcPos=25 dst.length=9 dstPos=0 length=-16

### ISSUE THREAD

**Issue by loumzy** [square/okhttp#3194]
ArrayIndexOutOfBoundsException

src.length=8192 srcPos=25 dst.length=9 dstPos=0 length=-16
com.zxinsight.common.http.z in run at line 59
com.zxinsight.common.http.z in a at line 100
com.zxinsight.common.http.ai in e at line 665
com.zxinsight.common.http.ai in a at line 676
com.zxinsight.common.http.ai in a at line 688
com.zxinsight.common.http.ai in l at line 731
com.android.okhttp.internal.huc.HttpsURLConnectionImpl in getOutputStream
com.android.okhttp.internal.huc.DelegatingHttpsURLConnection in getOutputStream at line 218
com.android.okhttp.internal.huc.HttpURLConnectionImpl in getOutputStream at line 257
com.android.okhttp.internal.huc.HttpURLConnectionImpl in connect at line 126
com.android.okhttp.internal.huc.HttpURLConnectionImpl in execute at line 457
com.android.okhttp.internal.http.HttpEngine in sendRequest at line 246
com.android.okhttp.internal.http.HttpEngine in connect at line 329
com.android.okhttp.OkHttpClient$1 in connectAndSetOwner at line 130
com.android.okhttp.Connection in connectAndSetOwner at line 367
com.android.okhttp.Connection in connect at line 172
com.android.okhttp.Connection in connectSocket at line 199
com.android.okhttp.Connection in connectTls at line 230
com.android.okhttp.internal.Platform in configureTlsExtensions at line 84
com.android.okhttp.internal.Platform in concatLengthPrefixed at line 133
com.android.okhttp.okio.Buffer in readByteArray at line 707
com.android.okhttp.okio.Buffer in readByteArray at line 720
com.android.okhttp.okio.Buffer in readFully at line 731
com.android.okhttp.okio.Buffer in read at line 743
java.lang.System in arraycopy at line 514

**Comment by JakeWharton** [comment]
This is a problem in whatever the obfuscated com.zxinsight code is doing.
And even if it weren't, com.android.okhttp is not the same as this library.
It's a standalone packaging of an older version inside of Android and it's
bugs should be reported to http://b.android.com.

**Comment by JakeWharton** [comment]
Actually it looks like your stacktrace is upside down. I would recommend trying normal OkHttp instead of the older version packaged in Android. If you can reproduce with the latest version with a failing test case or example then we can take a look.

**Comment by naturalwarren** [comment]
Neat! I didn't know OkHttp was packaged into android at some point.

**Comment by swankjesse** [comment]
No action to take on this.
