### ISSUE TITLE
socket timeout

### ISSUE THREAD

**Issue by dinuscxj** [square/okhttp#3195]
02-28 21:38:42.349 31577-1880/com.kwai.mercury W/System.err: java.net.SocketTimeoutException: timeout
02-28 21:38:42.349 31577-1880/com.kwai.mercury W/System.err:     at okio.Okio$3.newTimeoutException(Okio.java:207)
02-28 21:38:42.349 31577-1880/com.kwai.mercury W/System.err:     at okio.AsyncTimeout.exit(AsyncTimeout.java:261)
02-28 21:38:42.349 31577-1880/com.kwai.mercury W/System.err:     at okio.AsyncTimeout$1.write(AsyncTimeout.java:158)
02-28 21:38:42.349 31577-1880/com.kwai.mercury W/System.err:     at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:176)
02-28 21:38:42.349 31577-1880/com.kwai.mercury W/System.err:     at okio.RealBufferedSink.write(RealBufferedSink.java:46)
02-28 21:38:42.349 31577-1880/com.kwai.mercury W/System.err:     at com.squareup.okhttp.internal.http.RetryableSink.writeToSocket(RetryableSink.java:78)
02-28 21:38:42.349 31577-1880/com.kwai.mercury W/System.err:     at com.squareup.okhttp.internal.http.HttpConnection.writeRequestBody(HttpConnection.java:240)
02-28 21:38:42.349 31577-1880/com.kwai.mercury W/System.err:     at com.squareup.okhttp.internal.http.HttpTransport.writeRequestBody(HttpTransport.java:56)
02-28 21:38:42.350 31577-1880/com.kwai.mercury W/System.err:     at com.squareup.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:777)

**Comment by JakeWharton** [comment]
Socket timeouts are normal occurrences. What leads you to believe that this
is a bug?

**Comment by liuxj** [comment]
How to catch Socket timeout exception?

**Comment by liuxj** [comment]
I use `getInstance(context).client.newCall(request).enqueue(`, how to catch the SocketTimeoutExceptions?

**Comment by JakeWharton** [comment]
You don't need to catch it. It will be passed to onFailure.

**Comment by liuxj** [comment]
Oh, thanks

**Comment by swankjesse** [comment]
No action to take on this.
