### ISSUE TITLE
WebSocket ping logic is not customizable

### ISSUE THREAD

**Issue by dryganets** [square/okhttp#3197]
**Problem**
On Android, web sockets are unable to detect connectivity loss reliably.
I could have a dangling connection for 20 minutes (which is obviously closed on the server-side).
I need to be able to switch to the RestProtocol in my app in case WebSockets are not working reliably in current conditions.

**Setup**
1. Server side has an automatic disconnect on connection loss
2. Client loses connection. To simulate you could pull out the cable out of your local wifi router.
3. OkHttp is configured to have 10s write timeout and ping interval is 5 seconds

As a result, we have a dangling socket which is unable to recover after server-side disconnect.

Our server-side WebSocket implementation drops the connection in case there is no response on the ping.

**Workaround**
Socket send buffer size in the range 256-1024 allow to detect the connection drop in this configuration reliably in 20-30 seconds

**Forensics**
It turns out this is common android sockets problem so I have a limited setup to reproduce it.
1. Install this simple server to some cloud service https://github.com/dryganets/hello-socket
2. you could use any java socket application/android application which connects with socket API and writes to the socket some data.
https://github.com/dryganets/AndroidSocketTest
https://github.com/dryganets/JavaSocketTest

In the case of java application write is blocking and as soon you pull the cable out of router you don't see write confirmations anymore.

In the case of android application, write is non-blocking until the send buffer is exhausted, once it's it blocks. In case I'm plug in cable back it tries to re-connect automatically.

**Proposed solution**

Provide a way to implement and manually handle ping/pong logic.
We need to have a way to send the ping command and close the connection manually in case there is no response from the server.

**Comment by dryganets** [comment]
I would like to see it customizable. We are using the Lib as a part of react-native and it would be easier to have it integrated correctly. SocketRoket for ios has ping method and callback. Ws package of okhttp had it as well.

**Comment by swankjesse** [comment]
It's unlikely we'll expose a ping method to the application layer. We’re following browsers’ websocket APIs which also don’t do pings.

This gives us options if ever we do websockets on HTTP/2.

**Comment by gengjiawen** [comment]
For anyone still try use ping pong for reconnect implementation or other thing, you can just copy the related file in your project.It's only six file, not much work.
```
add onPong method on WebsocketListener
call it in RealWebsocket
create websocket instance (see newWebSocket method in OkhttpClient)
```
In migrating, use static import * for constants in WebSocketProtocol, it will save you a lot of time.

For me, i still use the pingInterval in OkhttpClient for ping method, because I only need pingpong to implement reconnect.

**Comment by dmedov** [comment]
what is the best strategy for reconnect to ws server if some error happens?
is current implementation trying to send ping or reinit connection? or user of the library should handle reinit of connection manually?

**Comment by swankjesse** [comment]
Recovering from failure is something you need to handle. Doing an exponential backoff is a good idea if you want to avoid inadvertently DoSing your server when it’s suffering performance problems.

**Comment by swankjesse** [comment]
No plans to implement user-visible pings. But #3227 will fail connections if pongs aren’t received.

**Comment by h0jeZvgoxFepBQ2C** [comment]
I don't understand why you are not opening a user configurable ping timeout. 

Some usecases have clearly a reasonable requirement to have higher ping times (like for us, doing realtime replication over websockets and to ensure low battery consumption our ping times are around 60 seconds). 

Not opening at least the ping timeout setter is really not helpful.
