### ISSUE TITLE
Attempt to invoke virtual method 'okio.Timeout okio.Timeout.clearDeadline()' on a null object reference

### ISSUE THREAD

**Issue by lizhw123** [square/okhttp#3200]
I use OKhttp 3.5.0, often crashes.

![1](https://cloud.githubusercontent.com/assets/17741114/23495767/82bc5916-ff55-11e6-8816-3ae2e7351d73.jpeg)

The above is the error log！

**Comment by devinhu** [comment]
I have the same error.

**Comment by swankjesse** [comment]
Could you help us to reproduce with an executable test case?

**Comment by lizhw123** [comment]
This is the third party statistics, I'm trying to reproduce

**Comment by swankjesse** [comment]
Any particular combination of devices? I’m curious if this is a problem with a specific device. From the code I can’t see what would be triggering this.

**Comment by devinhu** [comment]
I test many times, I found the reason why the third party application
reinforcement。Now solved， thanks。

2017-03-19 0:35 GMT+08:00 Jesse Wilson <notifications@github.com>:

**Comment by lizhw123** [comment]
hi devinhu，Can you tell me the details? What caused it? How to solve?

**Comment by devinhu** [comment]
Can you speak Chinese？
I user the third lib  in my project.

the third lib is bangcle (https://www.bangcle.com).
I change the third lib solve the case.

2017-03-20 10:15 GMT+08:00 lizhw123 <notifications@github.com>:
