### ISSUE TITLE
PUT that results in 204 No Content doesn't invalidate the cache for subsequent GETs

### ISSUE THREAD

**Issue by awenger** [square/okhttp#3203]
It looks like the cache invalidation via `PUT` is not working if the server responds with `204 no content`. However if the response for the `PUT` is `200 OK` + body the cache for the affected resource is invalidated. This leads to a state were the client gets an old representation for a resource he just updated on the server.

I think i found the relevant parts while debugging this behavior:
- cache is only written for responses that have a body:
  - https://github.com/square/okhttp/blob/89621df62dda5cf73726ce2d5410c82c6f760f00/okhttp/src/main/java/okhttp3/internal/cache/CacheInterceptor.java#L128-L131
- the `cache.put(Response)` also seems to be indirectly responsible to invalidate other cached responses
  - https://github.com/square/okhttp/blob/89621df62dda5cf73726ce2d5410c82c6f760f00/okhttp/src/main/java/okhttp3/Cache.java#L220-L230

**Comment by swankjesse** [comment]
Can fix.
