### ISSUE TITLE
Empty exception on DNS resolution error

### ISSUE THREAD

**Issue by redochka** [square/okhttp#3204]
I am using okhttp 3.5.0

While my app was trying to do a HTTP request, it faced an intermittent network error (maybe my internet connexion had a micro issue at this time..).

Here is the logcat output:

	I System.out: [CDS][DNS]Unable to resolve host "www.example.com": No address associated with hostname

	W MyTAG: ✘ 

Here is my code:

    try {
    	//...
        client.newCall(request).execute();
    } catch (Exception e) {
        Log.w("MyTAG", "✘ ", e);
    }

Why when logging the exception there is no message?

**Comment by swankjesse** [comment]
Not sure what action to take on this. Did you end up figuring out what the problem was?

**Comment by redochka** [comment]
can you let okhttp throw the exception instead of swallowing it?

**Comment by iNoles** [comment]
if it is in Android, I believe Android's Log class is swallowing it.

**Comment by JakeWharton** [comment]
Correct. This is evidenced by the fact that the catch block obviously runs
to produce the log "X".
