### ISSUE TITLE
unexpected end of stream on Connection{IP:PORT, proxy=DIRECT@ hostAddress=IP cipherSuite=none protocol=http/1.1} (recycle count=0)

### ISSUE THREAD

**Issue by rachanamamillapalli** [square/okhttp#3205]
What kind of issue is this?

 - [ ] Question. This issue tracker is not the place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use Stack
       Overflow. https://stackoverflow.com/questions/tagged/okhttp

 - [ ] Bug report. If you’ve found a bug, spend the time to write a failing test. Bugs with tests
       get fixed. Here’s an example: https://gist.github.com/swankjesse/981fcae102f513eb13ed

 - [ ] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
       already exists! Don’t send pull requests to implement new features without first getting our
       support. Sometimes we leave features out on purpose to keep the project small.

**Comment by skill20** [comment]
I got the same bug，but i't know how to  solve it。

**Comment by swankjesse** [comment]
Typically this indicates a connectivity problem to the server. If you can make an executable test case to demonstrate something that we can fix please do.

**Comment by mohit-sharma-87** [comment]
@swankjesse : how about if a share my actual code with you, will this help you to fix this issue

**Comment by guillaume-tgl** [comment]
I have the same error when trying to connect to a local WebDAV server I set up with https://itunes.apple.com/us/app/webdavnav-server/id747482894?mt=12.
I set up "Use HTTPS" and create a self-signed certificate.

**Comment by mhm9002** [comment]
I have "Failed to send request: "+this error, when two or more users try to send requests to my API on the same time. Will this be related to server capacity.. (as the API hosted on shared hosting server)? I've tried so hard to catch which part of code causing this error, but with no luck!

![screenshot_20180501-193245](https://user-images.githubusercontent.com/23471472/39488407-d9429d16-4d8a-11e8-8954-4d71f886831c.png)

**Comment by linguokun1** [comment]
I got the same bug，but i't know how to solve it。
