### ISSUE TITLE
upload image ,content-size 0

### ISSUE THREAD

**Issue by JokerHYC** [square/okhttp#3209]
the image file is approximately 17mb. 
i used multipartbody to build a request.

here is the raw http request info

--04e8b019-ae62-4044-97ff-d8c13c8ae5f6
Content-Disposition: form-data; name="uploadFile"; filename="upload.jpg"
Content-Type: image/jpeg
Content-Length: 0

--04e8b019-ae62-4044-97ff-d8c13c8ae5f6--

the content-length is 0; how can i fix this?

**Comment by swankjesse** [comment]
Test case please.

**Comment by JokerHYC** [comment]
sorry,it's my fault.
