### ISSUE TITLE
CallTest is locale dependent

### ISSUE THREAD

**Issue by aahlenst** [square/okhttp#3211]
Two tests in `CallTest` break when they are executed on a JVM that does not use an English locale: `leakedResponseBodyLogsStackTrace()` and `asyncLeakedResponseBodyLogsStackTrace()`. The problem is the line:

    assertTrue(message.contains("WARNING: A connection to " + server.url("/") + " was leaked."
        + " Did you forget to close a response body?"));

`WARNING` is for example `WARNUNG` (German for "WARNING") on a JVM with a German locale. If you tell me how I should fix it (JUnit `@Rule`, `Locale.setDefault(...)`, just removing "WARNING" from the assertion) I'll do it.

**Comment by JakeWharton** [comment]
Drop the text which we didn't explicitly log from the assertion?
