### ISSUE TITLE
NullPointerException - Cannot evaluate okio.Buffer.toString()

### ISSUE THREAD

**Issue by rashidtab** [square/okhttp#3215]
I am Using OKHttp version 3.6.0  (JAR File)  & OKIO 1.11.0 (Jar File)

Buld.gradle

-minSdkVersion 8
-targetSdkVersion 23

See the error shown in the screen shot.

Method threw `'java.lang.NullPointerException' exception. Cannot evaluate okio.Buffer.toString()`

![Error shown in Android Studio Debugging](https://cloud.githubusercontent.com/assets/6448293/23697595/65aa4e7a-03f9-11e7-90f9-69ef2d90d339.png)

Issue is happening when i Use

`MyResponse.body().string()`

**Comment by swankjesse** [comment]
Executable test case? Typically this kind of failure indicates unsafe concurrent access to a buffer.

**Comment by rashidtab** [comment]
But when I hard code JSON string in the code, it works fine. I mean the issue happens only when I read from Network. 

The Json Response contains the XML data also.

https://gist.github.com/rashidtab/22a2c697c4c28cd2624ea2364d02b4e1

**Comment by swankjesse** [comment]
I don’t have enough information to take action on this. If you could provide an executable test case to reproduce the problem, that’d help substantially. Also a full stack trace would be handy.

**Comment by rashidtab** [comment]
It is easily reproduceable if you try to read the content of this Gist (Like above)

https://gist.githubusercontent.com/rashidtab/22a2c697c4c28cd2624ea2364d02b4e1/raw/60fd39fb2b3269d4674d77702544f808a19fdf1d/gistfile1.txt

**Comment by swankjesse** [comment]
Closing for now. If it’s still causing you pain, please provide an executable test case.
