### ISSUE TITLE
okhttp3.6.0 looks slower than okhttp3.4.2 on low end devices

### ISSUE THREAD

**Issue by tomsang** [square/okhttp#3216]
I tested okhttp on the following two devices in 4Mbitps bandwidth networking environment.

Device A: CPU: 8 x Intel(R) Core(TM) i7-4710MQ CPU @ 2.50GHz;       MEM: 8G
Device B: CPU: 4 x Maxim, BogoMIPS    24.00;                                       MEM: 2G

3.6.0 is as fast as 3.4.2 on Device A
But 3.6.0 is slower than 3.4.3 on Device B

I use the following function to get response
mHttpClient.newCall(req).execute()

On Device A:  Either 3.6.0 or 3.4.2 can get the response in 100ms, and get response body(200KByte) in 500ms. 

On Device B:
3.6.0  can get the response in 300ms, and get response body(200KByte) in 5000ms. Sometimes it even cost much longer time (for example, 20000ms) to get the body.
3.4.2  can get the response in 150ms, and get response body(200KByte) in 600ms.   

What makes 3.6.0 so slow on low end device B?   I use the same source code and APIs to carry out the tests.

**Comment by swankjesse** [comment]
Hook up a profiler and see what it’s doing over that time?

**Comment by tomsang** [comment]
Could you possibly give a link of recommended profiler ?

**Comment by swankjesse** [comment]
Can you tell if the slowness is in OkHttp, or is it in the InputStream that OkHttp calls into?

**Comment by DerrickBrayanClayton** [comment]
look at OKHTTP calls into

2017-03-09 20:55 GMT-06:00 Jesse Wilson <notifications@github.com>:

**Comment by ErChenZhang** [comment]
Will be cause of the device?

**Comment by tomsang** [comment]
The cause  seems to be GZip decompression.

Is there difference between 3.6.0 and 3.4.2 regarding GZip decompression?

**Comment by swankjesse** [comment]
Does this particular device have gzip problems when you're not using OkHttp?

**Comment by tomsang** [comment]
The device have no gzip problems.
We can use the following method to work around  the issue.

1.In apk, add "Accept-Encoding" = "gzip" into http request header;
2.Then get the gzipped data through response body;
3. Unzip the data in our apk.

This way the overall time is shorter than that through okhttp built-in gzip processing module.

**Comment by tomsang** [comment]
It seems 3.6.0 has some enhanced protection  logics to solve those issues exposed in the earlier version(such as 3.4.2).

Could you possibly tell which codes to deal with the enhanced protection  logics?

**Comment by swankjesse** [comment]
Ahhh, interesting. Trying to get precise on range headers will be difficult. Would you consider stripping out the `Range: bytes=0-` header yourself in an interceptor?

**Comment by swankjesse** [comment]
No action to take on this.
