### ISSUE TITLE
Unexpected url in Request.Builder.url

### ISSUE THREAD

**Issue by djih** [square/okhttp#3217]
We've been using Okhttp 3.0.1 for a while now in Amplitude's Android SDK with no issues, although recently a customer reported a crash stemming from Okhttp3:

```
Fatal Exception: java.lang.IllegalArgumentException: unexpected url: https://api.amplitude.com/ 
at okhttp3.Request$Builder.url(Request.java:143) 
...
```

We haven't changed this code in a long time, and our api endpoint URL hasn't changed either. The customer did report that 100% of these crashes are coming from Lenovo Android devices.

Have you guys seen something like this before? Is there something about Lenovo's Android OS that interferes with the url parsing?

**Comment by swankjesse** [comment]
We’ve seen problems before where certain devices have VM bugs that execute the wrong code. One of which was a particular Lenovo.
https://github.com/square/okio/pull/164

Know which device this is?

**Comment by ErChenZhang** [comment]
Yeah,Chinese Lenovo.What type of Lenovo device?

-------- 原始邮件 --------
发件人：Jesse Wilson <notifications@github.com>
时间：周六 3月11日 20:33
收件人：square/okhttp <okhttp@noreply.github.com>
抄送：Subscribed <subscribed@noreply.github.com>
主题：Re: [square/okhttp] Unexpected url in Request.Builder.url (#3217)

**Comment by djih** [comment]
@swankjesse thanks for the info. The device is a Lenovo A328 running Android 4.4.2 (unrooted) if that helps. In the meantime we will just catch the IllegalArgumentExceptions when building the request.

**Comment by fozzarelo** [comment]
I don't think this is isolated to Lenovo. I'm having the same problems on an Alcatel running Android 6.0.1. 
I'll catch it for now, but that's just a hack.
