### ISSUE TITLE
duplicate connection created when send multiple request to one server

### ISSUE THREAD

**Issue by chchgb** [square/okhttp#3220]
when sending multiple request(the same host), duplicate connection may be created due to the synchronized method in function findConnection().

That there were several synchronized (connectionPool) blocks, and 2 request may entry the code of findConnection() method, and create 2 connections.

the deduplicate() method could remove the duplicated connection, but actually it was done after the connection operator, so it will waste server resource and client resource.

so anyone can provide some suggestion to optimize it?

**Comment by chchgb** [comment]
to avoid duplicated connection creating, one way is to use one synchronized (connectionPool) in findConnection() method or use synchronized block to call the method.

another way is to use named lock for each server, specified by the address(host and port).

**Comment by swankjesse** [comment]
One problem is that we don't know whether the connection will support HTTP/2 until after we’re connected. Locking would slow down requests that don't have it.

**Comment by chchgb** [comment]
@swankjesse thanks. 

We are porting okhttp3 to support our customized protocol (connections reusing over tcp). so we are trying to use named lock (for each server) to avoid create duplicated connection and reduce the server pressure, since the server need to handle hundreds of thousands connection.

**Comment by swankjesse** [comment]
Sounds good. No action for us to take here.
