### ISSUE TITLE
Implementing custom okhttp3 callback

### ISSUE THREAD

**Issue by lolsheeplol** [square/okhttp#3222]
Hi,  

While using Okhttp3, I have many callbacks that end up doing ui work on the main thread, so often in the response I have to create a new Handler or `runOnUIThread`.  To get around this, I made a new implementation of the default callback where the response is always handled on the main thread and is further separated by http success or failure.  Is this a correct way to go about doing this? http://stackoverflow.com/questions/42773534/implementing-custom-okhttp3-callback  I wasn't able to get a definitive response on SO so I thought you guys might know better.

**Comment by swankjesse** [comment]
This makes sense. Popular alternatives are Retrofit and RxJava, which solve this problem with more abstraction.

**Comment by NightlyNexus** [comment]
oooh, i wonder if you could also do this with a custom Call.Factory to avoid wrapping every single Callback.
maybe something like this.
```java
final class MyClient implements Call.Factory {
  private final Call.Factory delegate;
  private final Executor callbackExecutor;

  @Override public okhttp3.Call newCall(Request request) {
    return new ExecutorCall(delegate.newCall(request), callbackExecutor);
  }

  private static final class ExecutorCall implements Call {
    private final Call delegate;
    final Executor callbackExecutor;

    @Override public Response execute() throws IOException {
      return delegate.execute();
    }

    @Override public void enqueue(final Callback callback) {
      delegate.enqueue(new Callback() {
        @Override public void onFailure(final Call call, final IOException e) {
          callbackExecutor.execute(...);
        }
        @Override public void onResponse(final Call call, final Response response)
            throws IOException {
          callbackExecutor.execute(...);
        }
      });
    }
  }
}
```
