### ISSUE TITLE
Feature request: Parse only querystring

### ISSUE THREAD

**Issue by wulfsberg** [square/okhttp#3223]
What kind of issue is this?
Feature Request

HttpUrl contains a robust handling of query parameters (decoding, handling of duplicate keys etc).
Sometimes, it is convenient to do such parsing and/or building in other situations, without the need to handle a full URL, and I would like to reuse OkHttp's existing logic for this rather than pull in another utility library or code my own.

This is currently not possible, since the querystring logic is only exposed through HttpUrl, which requires a full, valid URL.

This could be exposed as an option for an even more lenient parsing in the HttpUrl class, or - preferably - as a stand-alone builder/parser.

**Comment by swankjesse** [comment]
You can just use a placeholder like "host" for the host. Much simpler than a specialized API for partial URLs.

**Comment by wulfsberg** [comment]
That is my current plan :-)
I am just not overly fond of dedicated "I don't actually use this" in my code, and it seems a little brittle to have to send correct-but-unused parts. Case in point, "host" is _not_ enough; that will result in the parser returning null. It needs to scheme and host.
I guess the spec is stable enough and the overhead minimal enough that it's arguably a valid trade-off against an additional API surface, but it does seem a little too dirty and brittle for my taste.

**Comment by swankjesse** [comment]
One more option: write your own Query class that hides the "host" shortcut. That way HttpUrl does the annoying encoding and decoding but your callers don't see the "host" shortcut.

**Comment by swankjesse** [comment]
One more option: write your own Query class that hides the "host" shortcut. That way HttpUrl does the annoying encoding and decoding but your callers see only what they need.

**Comment by swankjesse** [comment]
No action to take on this.
