### ISSUE TITLE
Problem on set different dispatchers

### ISSUE THREAD

**Issue by lupsyn** [square/okhttp#3224]
Hi,
 i had several issues try to use different dispatchers. If i setup a dispatcher for a test and after the tearDown() i try to re-set a local one, the following mock response will be fetched always from the previous dispatcher. Maybe there is something i miss. You can check the code i'm using [here](https://github.com/lupsyn/music-mvp-rx/blob/master/app/src/androidTest/java/com/music/androidtest/BaseLogicTest.java) 
I had to divide some normal espresso tests using the LocalDispatcher (you can find it in my code) from tests in which i need to setup a MockResponse inside the testAndroid package.

**Comment by swankjesse** [comment]
You’ll likely have a lot more success using a new instance of MockWebServer for every test.

**Comment by lupsyn** [comment]
@swankjesse it make no sense for me to create a new instance for every test. MockWebServer is injected extending my api module, and i think it should work also in these manner...

**Comment by swankjesse** [comment]
Got it. Can you isolate this into a test case for MockWebServer? As-is I know there are some places where MockWebServer makes assumptions about its dispatcher not changing, but I’m surprised that it’s impacting you.
