### ISSUE TITLE
Bug of HttpUrl.Builder addQueryParameter

### ISSUE THREAD

**Issue by marti1125** [square/okhttp#3225]
What kind of issue is this?

 - [x] Bug report. If you’ve found a bug, spend the time to write a failing test. Bugs with tests
       get fixed. Here’s an example: https://gist.github.com/marti1125/b15eec84d87ccfe1d6e89baf511be6da

the problem is with the final result of  urlquery.url().getQuery()
%22bin%22=%22411111%22 you can check in https://ostermiller.org/calc/encode.html
but I need bin="411111"

my solution was 
`String queryParams = (urlquery.url().getQuery() != null) ? "?"+urlquery.url().getQuery().replace("%22","") : "";`

**Comment by JakeWharton** [comment]
Can you express this in a test case? It's not really clear where you think the problem is.

**Comment by marti1125** [comment]
hello @JakeWharton https://gist.github.com/marti1125/dcb458f71b5eb1d229747cc58177b6e8
the output is:
%22limit%22=10
?limit=10
Response{protocol=http/1.1, code=200, message=OK, url=https://api.culqi.com/v2/charges?limit=10}
Process finished with exit code 0

%22 is not necessary I have to replace("%22","")

**Comment by swankjesse** [comment]
You’re including a `"` character in your parameter name. Don’t.

**Comment by marti1125** [comment]
hello @swankjesse but this part I added builder.addQueryParameter(pair.getKey().toString(), pair.getValue().toString()); "param" is a String.
Could you explain  me what is wrong with my code? please

**Comment by marti1125** [comment]
ups I fixed map.put(keyValue[0].replace("\"",""), keyValue[1].replace("\"",""));
Thanks!!!
