### ISSUE TITLE
HTTP/2 without ALPN boot jar

### ISSUE THREAD

**Issue by stevehu** [square/okhttp#3233]
What kind of issue is this?

 - [ ] Question. This issue tracker is not the place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use Stack
       Overflow. https://stackoverflow.com/questions/tagged/okhttp

 - [ ] Bug report. If you’ve found a bug, spend the time to write a failing test. Bugs with tests
       get fixed. Here’s an example: https://gist.github.com/swankjesse/981fcae102f513eb13ed

 - [X] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
       already exists! Don’t send pull requests to implement new features without first getting our
       support. Sometimes we leave features out on purpose to keep the project small.

I am working on a [microservices framework](https://github.com/networknt/light-java) and all my services are in HTTP/2. While looking for a decent HTTP/2 client library, I found okhttp. I like the API but it is very annoying to put alpn jar in boot classpath. The HTTP/2 server Undertow has a [hack](https://github.com/undertow-io/undertow/blob/master/core/src/main/java/io/undertow/protocols/ssl/ALPNHackSSLEngine.java) of JDK8 internal classes to resolve this issue. I am wondering if someone want to port it to this wonderful library.

**Comment by swankjesse** [comment]
Another option is to just use Java 9, which requires neither.

**Comment by stevehu** [comment]
I know:) but Java 9 won't be available until July and it will take some time to be production ready.

**Comment by aahlenst** [comment]
[netty-tcnative](http://netty.io/wiki/forked-tomcat-native.html) is nice. You just have to add another [Platform.java](https://github.com/square/okhttp/blob/master/okhttp/src/main/java/okhttp3/internal/platform/Platform.java) or to hook it into an existing one.

**Comment by yschimke** [comment]
I looked at using Conscrypt https://github.com/google/conscrypt for this.  It looked feasible to me, but would require either implementing inside OkHttp or allowing external Platforms to be used.

**Comment by yschimke** [comment]
I had a play around with conscrypt here https://github.com/square/okhttp/pull/3262

**Comment by swankjesse** [comment]
With Concrypt and Java 9 there’s nothing left to do here.
