### ISSUE TITLE
HttpUrl.Builder.addQueryParameter is not escaping curly braces which causes Tomcat 8 to reject request

### ISSUE THREAD

**Issue by arakelian** [square/okhttp#3235]
OkHttp does not properly escape URL query parameters that contain curly braces.

Tomcat 7.0.73+, 8.0.39+, and 8.5.7+ will reject these requests with the following error:
```
Mar 20, 2017 2:47:59 PM org.apache.coyote.http11.Http11Processor service
INFO: Error parsing HTTP request header
 Note: further occurrences of HTTP header parsing errors will be logged at DEBUG level.
java.lang.IllegalArgumentException: Invalid character found in the request target. The valid characters are defined in RFC 7230 and RFC 3986
        at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:471)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:667)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:798)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1434)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:745)
```

These are the characters that Tomcat will now reject as part of the URI request line (see org.apache.tomcat.util.http.parser.HttpParser):
```
            if (IS_CONTROL[i] || i > 127 ||
                    i == ' ' || i == '\"' || i == '#' || i == '<' || i == '>' || i == '\\' ||
                    i == '^' || i == '`'  || i == '{' || i == '|' || i == '}') {
                IS_NOT_REQUEST_TARGET[i] = true;  // reject the character!
```

To solve issue, the characters included in HttpUrl.QUERY_COMPONENT_ENCODE_SET may need to be changed.  Here is current definition:
```
static final String QUERY_COMPONENT_ENCODE_SET = " \"'<>#&=";
```

These

**Comment by swankjesse** [comment]
Can you ask the Tomcat authors to fix their server? Seems like they’re shutting out a lot of popular browsers with that check.

curl:
```
GET /?a={} HTTP/1.1
User-Agent: curl/7.51.0
```

Firefox:
```
GET /?a={} HTTP/1.1
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:52.0) Gecko/20100101 Firefox/52.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
```

Chrome:
```
GET /?a={} HTTP/1.1
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36
```

Safari:
```
GET /?a={} HTTP/1.1
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/602.4.8 (KHTML, like 
```

Wget does conform though, for what that’s worth.
```
~/Development/java jwilson.0320.conversation_movements * nc -l  8000
GET /?a=%7B%7D HTTP/1.1
User-Agent: Wget/1.16.1 (darwin13.4.0)
```

**Comment by swankjesse** [comment]
WhatWG recommends escaping `"#<>` only. https://url.spec.whatwg.org/#query-state

**Comment by garakelian** [comment]
I sympathize, believe me.  See the ticket referenced above for how I discovered the problem.

In attempting to craft a workaround, I've discovered that HttpClient (4.5.2) appears to be aligned with Tomcat in terms of what is valid URL:

```
    String original = "http://mycompany.com:80/path/query.html?json={}";

    // parse with OkHttp3 works
    String url = HttpUrl.parse(original).toString();
		
    // parse with HttpClient fails
    // Illegal character in query at index 45: http://mycompany.com:80/path/query.html?json={}
    String url2 = new URIBuilder(original).toString();
```

**Comment by swankjesse** [comment]
Oh man, having to discover that through an extra layer of indirection is tricky. 

Looks like it has been since fixed in Tomcat.
https://bz.apache.org/bugzilla/show_bug.cgi?id=60594

**Comment by garakelian** [comment]
Thanks for the link.  I hadn't seen that yet.

I wouldn't say that they 'fixed it', as the issue I experienced would continue to occur unless System property `tomcat.util.http.parser.HttpParser.requestTargetAllow` is set.

Not that HttpClient's URLBuilder is the gold-standard (or I wouldn't be using OkHttp3), but I'd respectfully suggest that modify HttpUrl builder to escape {, }, and | would be a good thing to do :-)

**Comment by swankjesse** [comment]
Yep.

One frustrating thing is that servlets & other frameworks don’t unescape automatically. So if you write a web app that’s expecting `{` and OkHttp provides `%7B`, your program might reply with a 400. This means that we can’t change OkHttp’s escaping rules without breaking applications.

I don’t think changing which URL characters are legal was a wise move for Tomcat. Particularly since the characters they’ve chosen to forbid aren’t part of any spec. The CVE they’re trying to address is bogus and they overreacted, and applications like ours are broken as a side-effect.

**Comment by garakelian** [comment]
So, I wrote a little unit test to see how all of the ASCII chars were encoded by OkHttp and HttpClient.   

I got some interesting results, which I'd like to confirm with you.  In no particular order, let's start with ASCII character 3F, or the ?.

According to my test, OkHttp is willing to parse the following URL:
```
http://host/path/subpath?arg=?
```

It returns a single query parameter, with a value of ?.  

What's more, when the unit test re-builds the URL, passing a query parameter named "arg" with a value of "?", I get back the same URL.

I'm pretty sure that I'm using the HttpUrl builder correctly.  If I am, the unit tests produces a set of results where HttpUrl builder is different than HttpClient. 

**Code:**
```
import java.net.URISyntaxException;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

import org.apache.http.client.utils.URIBuilder;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.junit.runners.Parameterized;
import org.junit.runners.Parameterized.Parameters;

import com.google.common.base.Joiner;

import okhttp3.HttpUrl;
import okhttp3.HttpUrl.Builder;

@RunWith(Parameterized.class)
public class HttpUrlEscapingTest {
	@Parameters(name = "{2}")
	public static Collection<Object[]> data() {
		List<Object[]> list = new ArrayList<>();
		for (int i = 0; i < 256; i++) {
			Character ch = Character.valueOf((char) i);

			String hex = Integer.toHexString(i).toUpperCase();
			if (hex.length() < 2) {
				hex = "0" + hex;
			}

			final String name;
			if (i >= 32 && i <= 127) {
				// including printable version
				name = hex + " \"" + ch + "\"";
			} else {
				name = hex;
			}

			list.add(new Object[] { ch, hex, name });
		}
		return list;
	}

	private final char ch;
	private final String hex;
	private final String name;

	public HttpUrlEscapingTest(char ch, String escapedChar, String name) {
		this.ch = ch;
		this.hex = escapedChar;
		this.name = name;
	}

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("HttpUrlEscapingTest [ch=");
		builder.append(ch);
		builder.append(", ");
		if (hex != null) {
			builder.append("hex=");
			builder.append(hex);
			builder.append(", ");
		}
		if (name != null) {
			builder.append("name=");
			builder.append(name);
		}
		builder.append("]");
		return builder.toString();
	}

	/**
	 * Returns a Tomcat-friendly URL with strict URL escaping
	 *
	 * @param url
	 *            OkHttp3 URL
	 * @return Tomcat-friendly URL with strict URL escaping
	 */
	public static String buildUrl(HttpUrl url) {
		URIBuilder builder = new URIBuilder();
		String scheme = url.scheme();
		builder.setScheme(scheme);

		StringBuilder userInfo = new StringBuilder();
		String username = url.username();
		String password = url.password();
		if (!username.isEmpty() || !password.isEmpty()) {
			userInfo.append(username);
			if (!password.isEmpty()) {
				userInfo.append(':');
				userInfo.append(password);
			}
		}

		if (userInfo.length() != 0) {
			builder.setUserInfo(userInfo.toString());
		}

		builder.setHost(url.host());
		int port = url.port();
		if (port != HttpUrl.defaultPort(scheme)) {
			builder.setPort(port);
		}

		builder.setPath(Joiner.on('/').join(url.pathSegments()));
		for (String name : url.queryParameterNames()) {
			for (String value : url.queryParameterValues(name)) {
				builder.addParameter(name, value);
			}
		}

		builder.setFragment(url.fragment());

		return builder.toString();
	}

	@Test
	public void testEscapingAsciiChars() throws URISyntaxException {
		// okhttp is forgiving when parsing
		String url = "http://host/path/subpath?arg=%" + hex;
		HttpUrl original = HttpUrl.parse(url);

		// encode using httpclient
		String httpClientUrl = buildUrl(original);

		// encode using okhttp
		Builder builder = original.newBuilder();
		for (String name : original.queryParameterNames()) {
			builder.removeAllQueryParameters(name);
		}
		for (String name : original.queryParameterNames()) {
			for (String value : original.queryParameterValues(name)) {
				builder.addQueryParameter(name, value);
			}
		}

		String okHttpUrl = builder.build().toString();
		Assert.assertEquals("HttpClient encoded as \"" + httpClientUrl + "\" but OkHttp encoded as \"" + okHttpUrl + "\"", httpClientUrl,
				okHttpUrl);

		// make sure HttpClient can parse
		Assert.assertNotNull(new URIBuilder(httpClientUrl).toString());
	}
}
```

**Comment by garakelian** [comment]
Okay, just read this:
http://stackoverflow.com/questions/2924160/is-it-valid-to-have-more-than-one-question-mark-in-a-url

*wow*

**Comment by swankjesse** [comment]
Yep. Here’s my research.
https://docs.google.com/spreadsheets/d/1BgGAhJ5WE3JBsATeudamiBzxmgEhwkfcFqQmPx8qrkc/edit?usp=sharing

**Comment by garakelian** [comment]
Thanks for sharing!

I'm writing some code to output how different libraries handle this on the server side.  I'll share tomorrow.  Thanks again.

**Comment by swankjesse** [comment]
@arakelian did your research on how libraries handle this find anything interesting?

**Comment by arakelian** [comment]
@swankjesse Work has been busy since I found the work around, so I haven't experimented beyond what I had the last day that I commented. We have a production release this week, but I intend to revisit this again, as I'm eager to understand how the different Java-side libraries handle this. Give me two weeks... Thanks.

**Comment by swankjesse** [comment]
Sounds good.

**Comment by swankjesse** [comment]
@arakelian I’m gonna close this out ’cause it’s not actionable in OkHttp. If you find out anything interesting about different libraries, I’m curious.

**Comment by Hronom** [comment]
Guys, I'm f*cked hard by this issue...
I'm using spring boot based backend and okhttp as tool for sending test requests.
And I'm got
```
java.lang.IllegalArgumentException: Invalid character found in the request target. The valid characters are defined in RFC 7230 and RFC 3986
```
Spring boot uses Tomcat 8.5.16

What the status/plans about this stuff?

**Comment by swankjesse** [comment]
@Hronom you might be able to work-around with [this](https://github.com/spring-cloud/spring-cloud-netflix/issues/1800#issuecomment-288129648):
`tomcat.util.http.parser.HttpParser.requestTargetAllow`

I don’t think OkHttp is to blame here. And I also think it’s not safe to change OkHttp’s behavior; I wrote about this [here](https://publicobject.com/2017/08/01/url-encoding-is-material/).

**Comment by swankjesse** [comment]
I did some more research on this. As above, none of the major browsers replace `{` with `%7B` when a URL is entered into the address bar. But it _is_ escaped when submitted as a GET parameter in an HTML form like the following:

```
<form method="get" action="http://localhost:8000/">
  <input type="text" name="foo">
  <input type="submit">
</form>
```

I think it’s my mistake that I interpreted browser behavior as “does it re-encode this character in a URL” and not “does it encode this character in a form” and for that I’m sorry! I have convinced myself that `addQueryParameter()` should escape `{` etc., but `parse()` should continue to preserve the passed-in encoding.

@arakelian, @Hronom thanks for pushing me on this and I’m sorry it took me so long to come around on it.

**Comment by yschimke** [comment]
@swankjesse it would be good to have some of these principles documented somewhere.  It matches my thinking for how I expect OkHttp to work, generally acting like a user agent instead of a networking toolkit like Netty.

**Comment by dineshmaske** [comment]
@arakelian : This solved my problem. Thanks so much. :+1:

**Comment by cketti** [comment]
In a `<form>` Chrome seems to percent-encode everything but numbers, letters, and `*-._`. Should `addQueryParameter()` do the same? What about `addEncodedQueryParameter()`?

**Comment by arakelian** [comment]
@swankjesse Thank you for the changes.
