### ISSUE TITLE
Exception when accessing the content of a redirected URL 

### ISSUE THREAD

**Issue by jnioche** [square/okhttp#3238]
Am getting 

```
Exception in thread "main" java.io.IOException: ID1ID2: actual 0x00003c68 != expected 0x00001f8b
	at okio.GzipSource.checkEqual(GzipSource.java:205)
	at okio.GzipSource.consumeHeader(GzipSource.java:120)
	at okio.GzipSource.read(GzipSource.java:73)
	at okio.Buffer.writeAll(Buffer.java:996)
	at okio.RealBufferedSource.readByteArray(RealBufferedSource.java:106)
	at okhttp3.ResponseBody.bytes(ResponseBody.java:135)
```
when fetching https://sgs.taleo.net/careersection/qam/jobdetail.ftl?job=026018

Here is some code to reproduce the issue

```
        String url = args[0];
        
        OkHttpClient client = new OkHttpClient.Builder().followRedirects(false)
                .build();
        
        Request request = new Request.Builder().url(url).build();
        Response response = client.newCall(request).execute();
        
        System.out.println("body length "+response.body().bytes().length);
        System.out.println("code "+response.code());
```

I tried with Apache's HTTPClient and it complains about  java.util.zip.ZipException: Not in GZIP format

curl deals with it fine

**Comment by swankjesse** [comment]
I wasn’t able to reproduce this. If you want to disable transparent gzip do this:

```
    Request request = new Request.Builder()
        .addHeader("Accept-Encoding", "identity")
        .url(url)
        .build();
```

**Comment by jnioche** [comment]
That's strange. Here are the versions for okhttp and java

```
okhttp 3.6.0

java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)
```

I tried again using a minimalistic Maven project with no other dependency but okhttp and got the same error. In addition I got the following warning

```
[WARNING] thread Thread[OkHttp ConnectionPool,5,com.dipe.http.Test] was interrupted but is still alive after waiting at least 15000msecs
[WARNING] thread Thread[OkHttp ConnectionPool,5,com.dipe.http.Test] will linger despite being asked to die via interruption
[WARNING] thread Thread[Okio Watchdog,5,com.dipe.http.Test] will linger despite being asked to die via interruption
[WARNING] NOTE: 2 thread(s) did not finish despite being asked to  via interruption. This is not a problem with exec:java, it is a problem with the running code. Although not serious, it should be remedied.
[WARNING] Couldn't destroy threadgroup org.codehaus.mojo.exec.ExecJavaMojo$IsolatedThreadGroup[name=com.dipe.http.Test,maxpri=10]
```

**Comment by swankjesse** [comment]
Whatever code is printing those warnings shouldn’t be doing that. How are you running OkHttp?

**Comment by swankjesse** [comment]
My guess is that IsolatedThreadGroup is trying to do something it shouldn’t be. Are you running tests in process with your build?

**Comment by jnioche** [comment]
Thanks @swankjesse 

The warnings above are anecdotal and probably a side effect of running the test code I posted earlier in a minimalistic Maven project.

`mvn exec:java -Dexec.mainClass="com.dipe.http.Test" -Dexec.args="https://sgs.taleo.net/careersection/qam/jobdetail.ftl?job=026018" `

That's probably due to close() not being called on the response object after catching the exception or something like that.

Back to the main point and the exception you can't reproduce: I get the same issue when running the test code from Eclipse. Did you specify `followRedirects(false)` when testing?

**Comment by swankjesse** [comment]
Yep, I ran it both with and without redirects and both times it completed normally.

**Comment by jnioche** [comment]
Weird. I wonder where that difference come from. Something in the java system defaults?

**Comment by jnioche** [comment]
in the meantime, I could simply return an empty byte[] content in case of redirections but it would have been good to get to the bottom of the issue. 

See https://github.com/DigitalPebble/storm-crawler/issues/443 for some background

**Comment by swankjesse** [comment]
No obvious action for us to take on this.

**Comment by su1216** [comment]
reproduced in picasso 2.5.2

> 05-11 19:06:13.549 27680-27680/? D/Picasso: Main        created      [R87] Request{https://static.huli.com/wap/images/app/android/myaccount/myassets.png resize(64,64) RGB_565}
05-11 19:06:13.550 27680-27680/? D/Picasso: Main        created      [R88] Request{https://static.huli.com/wap/images/app/android/myaccount/calender.png resize(64,64) RGB_565}
05-11 19:06:13.554 27680-27710/? D/Picasso: Dispatcher  canceled     [R77]+621s from replaying
05-11 19:06:13.555 27680-27710/? D/Picasso: Dispatcher  enqueued     [R87]+5ms 
05-11 19:06:13.555 27680-27710/? D/Picasso: Dispatcher  canceled     [R78]+621s from replaying
05-11 19:06:13.555 27680-27710/? D/Picasso: Dispatcher  enqueued     [R88]+5ms 
05-11 19:06:13.557 27680-27981/? D/Picasso: Hunter      executing    [R87]+7ms 
05-11 19:06:13.560 27680-27986/? D/Picasso: Hunter      executing    [R88]+9ms 
05-11 19:06:13.563 27680-27680/? D/Picasso: Main        created      [R89] Request{https://static.huli.com/wap/images/app/android/myaccount/mybuy.png resize(64,64) RGB_565}
05-11 19:06:13.564 27680-27710/? D/Picasso: Dispatcher  canceled     [R79]+621s from replaying
05-11 19:06:13.564 27680-27680/? D/Picasso: Main        created      [R90] Request{https://static.huli.com/wap/images/app/android/myaccount/xjg.png resize(64,64) RGB_565}
05-11 19:06:13.565 27680-27710/? D/Picasso: Dispatcher  enqueued     [R89]+2ms 
05-11 19:06:13.565 27680-27680/? D/Picasso: Main        completed    [R90] from MEMORY
05-11 19:06:13.565 27680-27710/? D/Picasso: Dispatcher  canceled     [R80]+621s from replaying
05-11 19:06:13.565 27680-27981/? D/Picasso: Hunter      executing    [R89]+2ms 
05-11 19:06:13.566 27680-27680/? D/Picasso: Main        created      [R91] Request{https://static.huli.com/wap/images/app/android/myaccount/myinvest.png resize(64,64) RGB_565}
05-11 19:06:13.567 27680-27710/? D/Picasso: Dispatcher  canceled     [R81]+621s from replaying
05-11 19:06:13.567 27680-27710/? D/Picasso: Dispatcher  enqueued     [R91]+0ms 
05-11 19:06:13.567 27680-27754/? D/Picasso: Hunter      executing    [R91]+1ms 
05-11 19:06:13.599 27680-27680/? D/Picasso: Main        created      [R92] Request{https://static.huli.com/wap/images/app/android/myaccount/dqb.png resize(64,64) RGB_565}
05-11 19:06:13.599 27680-27680/? D/Picasso: Main        created      [R93] Request{https://static.huli.com/wap/images/app/android/myaccount/coupon.png resize(64,64) RGB_565}
05-11 19:06:13.599 27680-27680/? D/Picasso: Main        created      [R94] Request{https://static.huli.com/wap/images/app/android/myaccount/raise.png resize(64,64) RGB_565}
05-11 19:06:13.599 27680-27710/? D/Picasso: Dispatcher  enqueued     [R92]+0ms 
05-11 19:06:13.599 27680-27680/? D/Picasso: Main        created      [R95] Request{https://static.huli.com/wap/images/app/android/myaccount/score.png resize(64,64) RGB_565}
05-11 19:06:13.599 27680-27710/? D/Picasso: Dispatcher  enqueued     [R93]+0ms 
05-11 19:06:13.599 27680-27680/? D/Picasso: Main        created      [R96] Request{https://static.huli.com/wap/images/app/android/myaccount/safecenter.png resize(64,64) RGB_565}
05-11 19:06:13.600 27680-27986/? D/Picasso: Hunter      executing    [R92]+0ms 
05-11 19:06:13.600 27680-27990/? D/Picasso: Hunter      executing    [R93]+1ms 
05-11 19:06:13.600 27680-27710/? D/Picasso: Dispatcher  enqueued     [R94]+1ms 
05-11 19:06:13.601 27680-27710/? D/Picasso: Dispatcher  enqueued     [R95]+1ms 
05-11 19:06:13.601 27680-27710/? D/Picasso: Dispatcher  enqueued     [R96]+1ms 
05-11 19:06:13.601 27680-27981/? D/Picasso: Hunter      executing    [R94]+1ms 
05-11 19:06:13.604 27680-27990/? D/Picasso: Hunter      executing    [R95]+4ms 
05-11 19:06:13.604 27680-27981/? D/Picasso: Hunter      executing    [R96]+4ms 
05-11 19:06:14.100 27680-27710/? D/Picasso: Dispatcher  retrying     [R88]+550ms 
05-11 19:06:14.101 27680-27986/? D/Picasso: Hunter      executing    [R88]+550ms 
05-11 19:06:14.101 27680-27710/? D/Picasso: Dispatcher  retrying     [R87]+551ms 
05-11 19:06:14.101 27680-27754/? D/Picasso: Hunter      executing    [R87]+552ms 
05-11 19:06:14.108 27680-27710/? D/Picasso: Dispatcher  retrying     [R89]+545ms 
05-11 19:06:14.111 27680-27986/? D/Picasso: Hunter      executing    [R89]+548ms 
05-11 19:06:14.115 27680-27710/? D/Picasso: Dispatcher  retrying     [R91]+548ms 
05-11 19:06:14.118 27680-27981/? D/Picasso: Hunter      executing    [R91]+552ms 
05-11 19:06:14.123 27680-27710/? D/Picasso: Dispatcher  retrying     [R93]+523ms 
05-11 19:06:14.123 27680-27986/? D/Picasso: Hunter      executing    [R93]+524ms 
05-11 19:06:14.126 27680-27710/? D/Picasso: Dispatcher  retrying     [R94]+526ms 
05-11 19:06:14.127 27680-27990/? D/Picasso: Hunter      executing    [R94]+527ms 
05-11 19:06:14.130 27680-27710/? D/Picasso: Dispatcher  retrying     [R92]+530ms 
05-11 19:06:14.131 27680-27754/? D/Picasso: Hunter      executing    [R92]+532ms 
05-11 19:06:14.135 27680-27710/? D/Picasso: Dispatcher  retrying     [R95]+536ms 
05-11 19:06:14.136 27680-27754/? D/Picasso: Hunter      executing    [R95]+536ms 
05-11 19:06:14.138 27680-27710/? D/Picasso: Dispatcher  retrying     [R96]+538ms 
05-11 19:06:14.140 345-438/? I/ThermalEngine: Sensor:batt_temp:333 mC
05-11 19:06:14.140 27680-27754/? D/Picasso: Hunter      executing    [R96]+540ms 
05-11 19:06:14.603 2984-2984/? D/wpa_supplicant: wlan0: Control interface command 'SIGNAL_POLL'
05-11 19:06:14.641 27680-27710/? D/Picasso: Dispatcher  retrying     [R87]+1092ms 
05-11 19:06:14.644 27680-27981/? D/Picasso: Hunter      executing    [R87]+1093ms 
05-11 19:06:14.644 27680-27710/? D/Picasso: Dispatcher  retrying     [R88]+1093ms 
05-11 19:06:14.647 27680-27990/? D/Picasso: Hunter      executing    [R88]+1096ms 
05-11 19:06:14.650 27680-27710/? D/Picasso: Dispatcher  retrying     [R89]+1087ms 
05-11 19:06:14.656 27680-27986/? D/Picasso: Hunter      executing    [R89]+1093ms 
05-11 19:06:14.662 27680-27710/? D/Picasso: Dispatcher  retrying     [R91]+1096ms 
05-11 19:06:14.663 27680-27754/? D/Picasso: Hunter      executing    [R91]+1096ms 
05-11 19:06:14.665 27680-27710/? D/Picasso: Dispatcher  retrying     [R94]+1066ms 
05-11 19:06:14.666 27680-27990/? D/Picasso: Hunter      executing    [R94]+1067ms 
05-11 19:06:14.677 27680-27710/? D/Picasso: Dispatcher  retrying     [R92]+1078ms 
05-11 19:06:14.678 27680-27981/? D/Picasso: Hunter      executing    [R92]+1078ms 
05-11 19:06:14.680 27680-27710/? D/Picasso: Dispatcher  retrying     [R95]+1079ms 
05-11 19:06:14.682 27680-27754/? D/Picasso: Hunter      executing    [R95]+1082ms 
05-11 19:06:14.684 27680-27710/? D/Picasso: Dispatcher  retrying     [R93]+1085ms 
05-11 19:06:14.689 27680-27990/? D/Picasso: Hunter      executing    [R93]+1089ms 
05-11 19:06:14.692 27680-27710/? D/Picasso: Dispatcher  retrying     [R96]+1092ms 
05-11 19:06:14.694 27680-27981/? D/Picasso: Hunter      executing    [R96]+1094ms 
05-11 19:06:15.141 345-438/? I/ThermalEngine: Sensor:batt_temp:333 mC
05-11 19:06:15.200 27680-27710/? D/Picasso: Dispatcher  batched      [R88]+1650ms for error (will replay)
05-11 19:06:15.201 27680-27710/? D/Picasso: Dispatcher  batched      [R87]+1651ms for error (will replay)
05-11 19:06:15.202 27680-27710/? D/Picasso: Dispatcher  batched      [R91]+1635ms for error (will replay)
05-11 19:06:15.203 27680-27710/? D/Picasso: Dispatcher  batched      [R92]+1604ms for error (will replay)
05-11 19:06:15.207 27680-27710/? D/Picasso: Dispatcher  batched      [R94]+1605ms for error (will replay)
05-11 19:06:15.208 27680-27710/? D/Picasso: Dispatcher  batched      [R89]+1645ms for error (will replay)
05-11 19:06:15.212 27680-27710/? D/Picasso: Dispatcher  batched      [R95]+1612ms for error (will replay)
05-11 19:06:15.212 27680-27710/? D/Picasso: Dispatcher  batched      [R93]+1613ms for error (will replay)
05-11 19:06:15.214 27680-27710/? D/Picasso: Dispatcher  batched      [R96]+1614ms for error (will replay)
05-11 19:06:15.441 27680-27710/? D/Picasso: Dispatcher  delivered    [R88]+1890ms, [R87]+1891ms, [R91]+1874ms, [R92]+1841ms, [R94]+1841ms, [R89]+1878ms, [R95]+1841ms, [R93]+1841ms, [R96]+1841ms 
05-11 19:06:15.449 27680-27680/? D/Picasso: Main        errored      [R88]+1899ms 
05-11 19:06:15.449 27680-27680/? W/System.err: java.io.IOException: ID1ID2: actual 0xffff8950 != expected 0x00001f8b
05-11 19:06:15.450 27680-27680/? W/System.err:     at com.android.okhttp.okio.GzipSource.checkEqual(GzipSource.java:205)
05-11 19:06:15.450 27680-27680/? W/System.err:     at com.android.okhttp.okio.GzipSource.consumeHeader(GzipSource.java:120)
05-11 19:06:15.450 27680-27680/? W/System.err:     at com.android.okhttp.okio.GzipSource.read(GzipSource.java:73)
05-11 19:06:15.450 27680-27680/? W/System.err:     at com.android.okhttp.okio.RealBufferedSource$1.read(RealBufferedSource.java:349)
05-11 19:06:15.450 27680-27680/? W/System.err:     at java.io.BufferedInputStream.fillbuf(BufferedInputStream.java:175)
05-11 19:06:15.450 27680-27680/? W/System.err:     at java.io.BufferedInputStream.read(BufferedInputStream.java:295)
05-11 19:06:15.451 27680-27680/? W/System.err:     at com.squareup.picasso.MarkableInputStream.read(MarkableInputStream.java:138)
05-11 19:06:15.451 27680-27680/? W/System.err:     at com.squareup.picasso.Utils.isWebPFile(Utils.java:324)
05-11 19:06:15.451 27680-27680/? W/System.err:     at com.squareup.picasso.BitmapHunter.decodeStream(BitmapHunter.java:122)
05-11 19:06:15.451 27680-27680/? W/System.err:     at com.squareup.picasso.BitmapHunter.hunt(BitmapHunter.java:217)
05-11 19:06:15.451 27680-27680/? W/System.err:     at com.squareup.picasso.BitmapHunter.run(BitmapHunter.java:159)
05-11 19:06:15.451 27680-27680/? W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
05-11 19:06:15.451 27680-27680/? W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
05-11 19:06:15.451 27680-27680/? W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
05-11 19:06:15.451 27680-27680/? W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
05-11 19:06:15.451 27680-27680/? W/System.err:     at java.lang.Thread.run(Thread.java:818)
05-11 19:06:15.451 27680-27680/? W/System.err:     at com.squareup.picasso.Utils$PicassoThread.run(Utils.java:411)
05-11 19:06:15.452 27680-27680/? D/Picasso: Main        errored      [R87]+1902ms 
05-11 19:06:15.452 27680-27680/? W/System.err: java.io.IOException: ID1ID2: actual 0xffff8950 != expected 0x00001f8b
05-11 19:06:15.452 27680-27680/? W/System.err:     at com.android.okhttp.okio.GzipSource.checkEqual(GzipSource.java:205)
05-11 19:06:15.452 27680-27680/? W/System.err:     at com.android.okhttp.okio.GzipSource.consumeHeader(GzipSource.java:120)
05-11 19:06:15.452 27680-27680/? W/System.err:     at com.android.okhttp.okio.GzipSource.read(GzipSource.java:73)
05-11 19:06:15.452 27680-27680/? W/System.err:     at com.android.okhttp.okio.RealBufferedSource$1.read(RealBufferedSource.java:349)
05-11 19:06:15.452 27680-27680/? W/System.err:     at java.io.BufferedInputStream.fillbuf(BufferedInputStream.java:175)
05-11 19:06:15.452 27680-27680/? W/System.err:     at java.io.BufferedInputStream.read(BufferedInputStream.java:295)
05-11 19:06:15.452 27680-27680/? W/System.err:     at com.squareup.picasso.MarkableInputStream.read(MarkableInputStream.java:138)
05-11 19:06:15.452 27680-27680/? W/System.err:     at com.squareup.picasso.Utils.isWebPFile(Utils.java:324)
05-11 19:06:15.453 27680-27680/? W/System.err:     at com.squareup.picasso.BitmapHunter.decodeStream(BitmapHunter.java:122)
05-11 19:06:15.453 27680-27680/? W/System.err:     at com.squareup.picasso.BitmapHunter.hunt(BitmapHunter.java:217)
05-11 19:06:15.454 27680-27680/? W/System.err:     at com.squareup.picasso.BitmapHunter.run(BitmapHunter.java:159)
05-11 19:06:15.455 27680-27680/? W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
05-11 19:06:15.455 27680-27680/? W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
05-11 19:06:15.456 27680-27680/? W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
05-11 19:06:15.456 27680-27680/? W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
05-11 19:06:15.456 27680-27680/? W/System.err:     at java.lang.Thread.run(Thread.java:818)
05-11 19:06:15.456 27680-27680/? W/System.err:     at com.squareup.picasso.Utils$PicassoThread.run(Utils.java:411)
......

**Comment by su1216** [comment]
when this happen, picasso will never show the pictures again, unless uninstall and install again the app.

**Comment by swankjesse** [comment]
I couldn’t reproduce this. Could you provide a sample URL that’s breaking? My guess is that there’s something in gzip + caching that’s causing problems.

**Comment by swankjesse** [comment]
Hang on – can you switch your Picasso to use OkHttp 3.7 rather than the OS’ built in copy of OkHttp? That might fix everything.

**Comment by JakeWharton** [comment]
Which is done using
https://github.com/JakeWharton/picasso2-okhttp3-downloader/

**Comment by su1216** [comment]
@swankjesse OkHttp 3.7 doesn't work...

**Comment by su1216** [comment]
@JakeWharton picasso2-okhttp3-downloader works fine. It fix my bug.

**Comment by su1216** [comment]
@JakeWharton but why this happened? Will picasso 2.5.3 fix this?

**Comment by jnioche** [comment]
Tried the snippet below with 3.8.0 and still getting 

Exception in thread "main" java.io.IOException: ID1ID2: actual 0x00003c68 != expected 0x00001f8b
	at okio.GzipSource.checkEqual(GzipSource.java:205)
	at okio.GzipSource.consumeHeader(GzipSource.java:120)
	at okio.GzipSource.read(GzipSource.java:73)
	at okio.Buffer.writeAll(Buffer.java:1005)
	at okio.RealBufferedSource.readByteArray(RealBufferedSource.java:107)
	at okhttp3.ResponseBody.bytes(ResponseBody.java:136)
	at Test.main(Test.java:18)

with `https://sgs.taleo.net/careersection/qam/jobdetail.ftl?job=026018`

Here is the code

```java
import java.io.IOException;

import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.Response;

public class Test {

    public static void main(String[] args) throws IOException {
 String url = args[0];
        
        OkHttpClient client = new OkHttpClient.Builder().followRedirects(false)
                .build();
        
        Request request = new Request.Builder().url(url).build();
        Response response = client.newCall(request).execute();
        
        System.out.println("body length "+response.body().bytes().length);
        System.out.println("code "+response.code());

    }

}
```
