### ISSUE TITLE
Expose public suffix info via an API

### ISSUE THREAD

**Issue by swankjesse** [square/okhttp#3243]
We have the public suffix DB. Should we expose it with an API somewhere?

Perhaps something like this?

```
HttpUrl url = HttpUrl.parse("https://adwords.google.co.uk");
assertEquals("google.co.uk", url.topPrivateDomain());
```

(I’m borrowing the method name from Guava here.)

**Comment by dave-r12** [comment]
That might be handy. I haven't gotten this far yet, but I was going to experiment with using the _top private domain_ to bucket cookies in the cookie jar. Pulling it directly off the HttpUrl would be nice.

**Comment by dave-r12** [comment]
@swankjesse was going to look at this one, please let me know if you have something in progress.

**Comment by swankjesse** [comment]
Please go ahead!
