### ISSUE TITLE
Multipart POST upload fails when upgrading to okHttp 3..6.0

### ISSUE THREAD

**Issue by rhadary** [square/okhttp#3244]
Our Android team has recently attempted an upgrade to okHttp 3.6.0 from 3.4.1.  However, while testing multi-part POST uploads over a network with poor connectivity, we noticed that these uploads seem to fail much more frequently.  The culprit seems to be a change made in the following commit:
https://github.com/square/okhttp/commit/5d70f5f7a7cf85e0f4c528452aa89bbdf7f7f2d5

Below is the code for the multi-part post.  Help in resolving this problem is greatly appreciated. 

 public  String sendPOSTMultiPartRequest(final ImageContainer container,                          
                                            File f,
                                            Object progressListener)  throws IOException  {
        RequestBodyWithUploadProgress.ProgressListener progress;
        try {
            progress = (RequestBodyWithUploadProgress.ProgressListener) progressListener;
        } catch (ClassCastException e) {
            throw new ClassCastException("listener must implement RequestBodyWithUploadProgress.ProgressListener!");
        }

        final String mimeType = container.getMimeType();
        RequestBody formData = new RequestBodyWithUploadProgress( f,
                                                                mimeType,
                                                                progress);
        RequestBody requestBody = new MultipartBody.Builder().setType(MultipartBody.FORM)
                                                        .addFormDataPart("ImageData", f.getName(), formData)
                                                        .build();
        CustomRequestBuilder builder = new CustomRequestBuilder(preferredLanguage);

        builder.url(container.links.getLink(LinkEnum.UPLOAD_PUSH))
               .post(requestBody)
               .addHeader("MimeType", mimeType);

        Response response = client.newCall(builder.build()).execute();
        return response.body().string();
    }

public  class CustomRequestBuilder extends Request.Builder {
    private static final String PREFERRED_LANGUAGE = "Accept-Language";
    private final String CONTENT_TYPE = "application/json";

   public CustomRequestBuilder(String preferredLanguage) {
        super();
        this.header("Content-Type", contentType);
        if (!isNullOrEmpty(preferredLanguage)) {
            addHeader(PREFERRED_LANGUAGE, preferredLanguage);
        }
    }
}

public class RequestBodyWithUploadProgress extends RequestBody {

    private static final int SEGMENT_SIZE = 2048; //= okio.Segment.SIZE;
    private static final String DISPOSITION_LENGTH = "Content-Disposition: form-data; name=ImageData ; filename=";
    public interface ProgressListener {
        void transferred(long num);
    }
    private final File file;
    private final ProgressListener listener;
    private final String contentType;

    public RequestBodyWithUploadProgress(File file, String contentType, ProgressListener listener {
        this.file = file;
        this.contentType = contentType;
        this.listener = listener;
    }

    @Override
    public long contentLength() {
        return file.length(); 
    }

    @Override
    public MediaType contentType() {
        return MediaType.parse(contentType);
    }

    @Override
    public void writeTo(BufferedSink sink) throws IOException {
        Source source = null;
        try {
            source = Okio.source(file);
            long total = 0;
            long read;

            while ((read = source.read(sink.buffer(), SEGMENT_SIZE)) != -1) {
                total += read;
                sink.flush();
                this.listener.transferred(total);
            }
        } finally {
            Util.closeQuietly(source);
        }
    }
}

**Comment by swankjesse** [comment]
Any chance you could write a small, executable test case to demonstrate the regression? Something that fails on 3.6.0 that passed on 3.4.2?

**Comment by swankjesse** [comment]
Here's an example to get started:
https://gist.github.com/swankjesse/981fcae102f513eb13ed

**Comment by rhadary** [comment]
?Let me see if  I can isolate the problem.  In the meantime, maybe you can review the code snippet I provided and see if anything stands out.  Thank you!

________________________________

**Comment by rhadary** [comment]
I was able to repro this problem in a standalone testbed starting with okHttp 3.5.0.  I previously stated that this was a 3.4.2 issue but the problem seems to have been introduced in 3.5.0.   I provided the network settings under which this problem occurred.  The code snippet below excludes  some authentication details which allowed us to upload the images to our own image servers.   Hopefully, you can modify the code to point to your own upload destination.   Thank-you!

Network Settings:
Bandwidth: Download 256k  and Upload 128k
Round-Trip latency ( ms ) 30
MTU 1000
Reliability: 95%
Stability: 95%
Unstable quality range 75-100

import org.junit.Assert;
import org.junit.Rule;
import org.junit.Test;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;

import okhttp3.MediaType;
import okhttp3.MultipartBody;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.RequestBody;
import okhttp3.Response;
import okhttp3.internal.Util;
import okhttp3.mockwebserver.MockWebServer;
import okio.BufferedSink;
import okio.Okio;
import okio.Source;

public class OkHttpTest {
    private final String UPLOAD_URL = "YOUR_UPLOAD_URL";
    private final String CONTENT_TYPE = "application/json";
    private final String IMAGE_URL = "YOUR_LOCAL_IMAGE_URL";
    private final String MIME_TYPE ="image/*";
    private final OkHttpClient httpClient = new OkHttpClient.Builder().build();
    private final int UPLOAD_COUNT = 20;

    @Rule
    public final MockWebServer server = new MockWebServer();

    @Test
    public void test() throws Exception {
        uploadImages();
    }

    public void uploadImages() {
        for (int i=0; i<UPLOAD_COUNT; i++) {
            uploadImage();
        }
    }

    private void uploadImage() {
        File f = getImageFile(IMAGE_URL);
        int responseCode = -1;

        if (!f.exists()) {
            onUploadFail();
            return;
        }

        try {
            Response response = sendPOSTMultiPartRequest(UPLOAD_URL, f);
            responseCode = response.code();
        }
        catch (IOException e) {
            onUploadFail(e.getMessage());
        }

        Assert.assertEquals(responseCode, 200);
    }

    private File getImageFile(String path) {
        return new File(java.net.URI.create(encodeUrl(path)).getPath());
    }

    private static String encodeUrl(String url) {
        return url.replace(" ", "%20").replace("^", "%5E");
    }

    public Response sendPOSTMultiPartRequest(String uploadUrl, File f) throws IOException {
        RequestBody formData = new RequestBodyWithUploadProgress(f, MIME_TYPE);
        RequestBody requestBody = new MultipartBody.Builder().setType(MultipartBody.FORM)
                .addFormDataPart("ImageData", f.getName(), formData)
                .build();

        Request.Builder builder = new Request.Builder();

        builder.url(uploadUrl)
                .post(requestBody)
                .addHeader("Content-Type", CONTENT_TYPE)
                .addHeader("MimeType", MIME_TYPE);

        Response response = httpClient.newCall(builder.build()).execute();
        return response;
    }

    public class RequestBodyWithUploadProgress extends RequestBody {
        private static final int SEGMENT_SIZE = 2048;

        private final File file;
        private final String contentType;

        public RequestBodyWithUploadProgress(File file, String contentType) {
            this.file = file;
            this.contentType = contentType;
        }

        @Override
        public long contentLength() {
            return file.length(); // + file.getName().length() + DISPOSITION_LENGTH.length() + contentType.length();
        }

        @Override
        public MediaType contentType() {
            return MediaType.parse(contentType);
        }


        @Override
        public void writeTo(BufferedSink sink) throws IOException {
            Source source = null;
            try {
                source = Okio.source(file);
                long total = 0;
                long read;

                while ((read = source.read(sink.buffer(), SEGMENT_SIZE)) != -1) {
                    total += read;
                    sink.flush();
                }
            }
            catch (FileNotFoundException e) {
            }
            finally {
                Util.closeQuietly(source);
            }
        }
    }

    private void onUploadFail() {
        onUploadFail(null);
    }

    private void onUploadFail(String message) {
        // TODO: log upload failure
    }
}

**Comment by swankjesse** [comment]
Your test case worked for me. I needed to give MockWebServer some responses to respond with.

```
    for (int i = 0; i < UPLOAD_COUNT; i++) {
      server.enqueue(new MockResponse());
    }
```

**Comment by rhadary** [comment]
Hello Jesse,
Did you try this using the specified network settings and on running on a device?
________________________________

**Comment by swankjesse** [comment]
I haven’t. If you could isolate what’s causing this, that’d be handy.
