### ISSUE TITLE
cacheResponse and networkResponse both non-null for non-conditional GET

### ISSUE THREAD

**Issue by unparalleled** [square/okhttp#3248]
`OKHTTP_VERSION=3.6.0`

According to the documentation, there's a contract where both `cacheResponse` and `networkResponse` may be non-null only for conditional GETs.

```
  /**
   * Returns the raw response received from the network. Will be null if this response didn't use
   * the network, such as when the response is fully cached. The body of the returned response
   * should not be read.
   */
  public Response networkResponse() {
    return networkResponse;
  }

  /**
   * Returns the raw response received from the cache. Will be null if this response didn't use the
   * cache. For conditional get requests the cache response and network response may both be
   * non-null. The body of the returned response should not be read.
   */
  public Response cacheResponse() {
    return cacheResponse;
  }
```

My GET is non-conditional, and only has the following two headers: `Authorization` and a custom one `X-Api-Start`.

The `Response` object then contains both `cacheResponse` and `networkResponse`, the networkResponse obviously having a more recent `Date` header. Both responses even have the following `Cache-Control` header: `max-age=0, private, must-revalidate`.

Please let me know what other information may be helpful.

**Comment by swankjesse** [comment]
OkHttp automatically makes your GET request conditional if there’s a cached response that needs to be validated. If you don’t want a conditional GET, you should specify network only (with`CacheControl.FORCE_NETWORK`) or cache only (with `CacheControl.FORCE_CACHE`).
