### ISSUE TITLE
Feature request: Support for dynamic level in HttpLoggingInterceptor

### ISSUE THREAD

**Issue by jakubvimn** [square/okhttp#3250]
I have `HttpLoggingInterceptor` configured with Timber in the following way
```
val logging = HttpLoggingInterceptor { message ->
    Timber.tag(HTTP_LOGGING_TAG).d(message)
}

logging.level = HttpLoggingInterceptor.Level.BODY
```

It works nice if I have Timber initialized to print something on the debug level. But what if my release application has debug logging disabled? The `HttpLoggingInterceptor` still builds the whole message (with the `BODY` level it's quite heavy) and the message is ignored at the very end.
I'd like to optimize it.
My first idea was overriding the `getLevel` method, but first of all `HttpLoggingInterceptor` is final and secondly, this method is not used in the `intercept` method. So it looks it can't be done with the current interceptor.

What do you think about replacing the field `level` with a lambda, so that the level can be calculated dynamically (in my example the result would be `BODY` if the logging is enabled or `NONE` if it's disabled)?

EDIT
My current work-around is:
```
class DynamicHttpLoggingInterceptor(logger: HttpLoggingInterceptor.Logger) : Interceptor {

    var levelProvider: () -> HttpLoggingInterceptor.Level = { HttpLoggingInterceptor.Level.NONE }

    private val wrappedInterceptor = HttpLoggingInterceptor(logger)

    override fun intercept(chain: Interceptor.Chain): Response {
        wrappedInterceptor.level = levelProvider()
        return wrappedInterceptor.intercept(chain)
    }
}
```

**Comment by swankjesse** [comment]
You should consider the logging interceptor to be a code sample. If you'd like to customize it for your own needs, copy it into your project.

Also consider using Chuck if you want something for development time only.

https://github.com/jgilfelt/chuck

**Comment by JakeWharton** [comment]
> But what if my release application has debug logging disabled?

Why are you setting the value to `BODY` in this case then? If the application doesn't want logs then set the logging level to NONE or don't even add the interceptor.

**Comment by jakubvimn** [comment]
I'm developing a library (for internal use inside the company) that uses Timber and OkHttp. I want to make the library setup as simple as possible. I can add a flag to the library configuration, e.g. `logHttpRequest`, but I thought that it may be good to configure this behaviour automatically.

**Comment by swankjesse** [comment]
No action to take on this.
