### ISSUE TITLE
Have more fine grained control over client on runtime

### ISSUE THREAD

**Issue by yoavgray** [square/okhttp#3259]
What kind of issue is this?

Feature Request:
If I use Dagger & Retrofit and I want that one of my API requests will have different timeouts set, for example, I need to either inject another `OkHttpClient` -> `Retrofit` -> `Service` or build them on runtime when I make the request, which then is less performant (because I have to keep building it every time). That's a little annoying but fine for 2 different requests. If I want to be very careful with how my users are seeing errors and how I deal with timeouts, I could eventually need 4-5-6 different requests with different settings for the client.

Is there a way to set the timeout on runtime without having multiple `OkHttpClient` instances?

Thank you very much for this amazing library.

**Comment by kurisu** [comment]
This would be very helpful for user experiences with variable response times, such as a bidding process where we would want to show quick responses for initial bids, then progressively longer timeouts to get responses from other bidders who might take longer to respond.

**Comment by swankjesse** [comment]
Planning on doing this here:
https://github.com/square/okhttp/issues/3039

**Comment by yoavgray** [comment]
So there's no documentation for what one is suppose to do when there's a need to change a call's timeout on flight.

This doesn't seem to work:
```
Request original = chain.request();
if (original.headers().get(TIMEOUT_HEADER) != null) {
    original = chain
        .withReadTimeout(Integer.valueOf(original.headers().get(TIMEOUT_HEADER)), TimeUnit.MILLISECONDS)
        .request();
}
```

Any suggestion?

**Comment by JakeWharton** [comment]
You need to use the new chain to invoke the request. You're basically
thowing it away and using the original.

**Comment by swankjesse** [comment]
Call proceed() on the returned chain.

**Comment by yoavgray** [comment]
I'll try that. Thanks for the prompt response.

**Comment by yoavgray** [comment]
Yeah, you guys were right. I wasn't using the new chain. Thanks so much for your help!
