### ISSUE TITLE
Glide with Instant Run enabled

### ISSUE THREAD

**Issue by ghiyats-olx** [square/okhttp#3264]
I am getting an unusual NoClassDefFound Exception when running my app with InstantRun enabled on Android Studio 2.3 which resulting the images not appeared on the screen, but somehow when I disable the instantRun everything works just fine.

`java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/newrelic/agent/android/instrumentation/BitmapFactoryInstrumentation;`

**Comment by JakeWharton** [comment]
Seems like you should file this on http://b.android.com? I'm not sure how OkHttp is involved here or what you think could be changed in OkHttp to mitigate. It seems strictly between New Relic's tool and Instant Run.
