### ISSUE TITLE
Handling Content-Type in 304 responses

### ISSUE THREAD

**Issue by steelbytes** [square/okhttp#3265]
This is sort of a bug report, sort of a feature request ...

A certain popular CDN is occasionally returning `Content-Type` in it's `304` responses (I'm pretty sure it's them and not the upstream actual server).  Even worse it's the wrong `Content-Type` - `text/plain` instead of `application/json` 

I dropped a conditional breakpoint in `CacheInterceptor.intercept()` in it's handling of a `304` that would only trigger when `networkResponse.header("Content-Type")!=null`.  After playing with my app heavily and continuously for about an hour this breakpoint eventually triggers.  So I'm confident this is happening.

So where does okhttp (i'm using 3.6.0 on android) come in to this?  Why the report/request?  Because this `Content-Type` is returned to my app instead of the correct value from the cache.  I feel okhttp should ignore the headers that should not be in a 304 response - call it a bug, call it a feature (defend against bad servers).

**Comment by swankjesse** [comment]
Section 13.5.3 and 13.5.1 is what we implemented.
https://www.ietf.org/rfc/rfc2616.txt

Have you reported the problem to the server's administrator? Presumably a link to that RFC should be compelling.

In the interim you can strip unwanted headers with a network interceptor.

**Comment by steelbytes** [comment]
I have reported the issue to the service provider (waiting for reply).

I have also changed my app to sniff the content when I receive plain/text to see if it's really a json, this works just fine.

since this took me over a week to catch it in a debugger to prove the issue, I feel it would be nice if you added defence into okhttp for this.  it's bound to trip up many other devs ...

**Comment by swankjesse** [comment]
What would that defense look like?

**Comment by steelbytes** [comment]
I would have thought simply removing all headers from the network response that related to the body when a 304 is received. ie, Content-Type, Content-Encoding, Content-Language, etc.  basically Content-*

the simplest would to be do this in the 304 handler in CacheInterceptor, but really it could be performed a lot earlier (probably should be?)

this probably should be for a few other http codes as well (100-199, 204, see http://stackoverflow.com/questions/8628725/comprehensive-list-of-http-status-codes-that-dont-include-a-response-body)

**Comment by swankjesse** [comment]
Seems like it’d be convenient for you, but it contradicts the HTTP spec.

> In other words, the set of end-to-end headers received in the incoming response overrides all corresponding end-to-end headers stored with the cache entry (except for stored Warning headers with warn-code 1xx, which are deleted even if not overridden).

Another question – what would have helped you to diagnose this earlier? Were you using a tool like Charles or Stetho?

**Comment by steelbytes** [comment]
no, I wasn't using any proxies when debugging.  the slowness in debugging was the rareness of the problem and that nothing spat a warning anywhere (eg, nothing in logcat, no exceptions ...).  it took a while before I thought of logging mime as I didn't know what the problem was.  then when I saw it I didn't really believe it so then tried to work out was there a bug in okhttp's cache or was the server really doing the wrong thing.  like if it was repeatable or at least frequent then I would have nailed it in no time.

/me shakes fist in the air at the bl**dy CDN provider (still no response from them)

**Comment by steelbytes** [comment]
hmm ... another thought: maybe if a 304 is received with header values that it shouldn't have then maybe just reject/fail the response instead of processing it?

**Comment by swankjesse** [comment]
That would break caching completely.

**Comment by swankjesse** [comment]
Consider stripping the content-type from the response in a network interceptor. It’ll workaround the bad behavior of your server until they fix their stuff.
