### ISSUE TITLE
FormBody + encoding

### ISSUE THREAD

**Issue by gazz94** [square/okhttp#3266]
Hello, I am currently using the FormBody class to make a POST call.

This is how I am handling the request:

```
String password = URLEncoder.encode(params.get("password").toString(), "UTF-8");
String username = URLEncoder.encode(params.get("username").toString(), "UTF-8");

RequestBody formBody = new FormBody.Builder()
    .addEncoded("username", username)
    .addEncoded("password", password)
    .build();
                                     
request = new Request.Builder()
    .url(getHostName()+endpoint)
    .post(formBody)
    .build();
```

In case the `password` field has a plus `+` in it, the request gets trimmed of that character, and becomes the field with a space instead of the plus. I tried to call `.addEncoded` with an encoded String, as well as `.add` with a non encoded string, but the result is the same. 

In the end, if a user has a `+` in its password, the authentication field, the authentication fails.

Am I doing something wrong or performing some misconfiguration or is this a bug?

Thanks

**Comment by swankjesse** [comment]
Does this work?
```

RequestBody formBody = new FormBody.Builder()
    .add("username", params.get("username").toString())
    .add("password", params.get("password").toString())
    .build();
```

**Comment by gazz94** [comment]
No I've got the same result

**Comment by swankjesse** [comment]
Not sure what action to take on this. I don’t know about `URLEncoder` but that might be problematic.

**Comment by rchibukhchyan** [comment]
why did this get closed without resolution?
`new FormBody.Builder().addEncoded("name", value).build()`
doesn't encode the `+` sign. Whenever value has `+` sign authentication fails because it stays as is, while it should be converted to `%2B`
