### ISSUE TITLE
Bug: HttpLoggingInterceptor.Level.BODY breaks a streaming request

### ISSUE THREAD

**Issue by sammefford** [square/okhttp#3269]
I'd like to report what I believe is a bug in HttpLoggingInterceptor.

The following fails to send the request body because of `setLevel(HttpLogginInterceptor.Level.BODY)`.  I'm guessing the HttpLoggingInterceptor reads from the stream which prevents the stream from making it to the request body.  Rather than throw an error, the request silently proceeds with an empty request body.  I could only validate this by using wireshark to inspect the network traffic.  Without the `setLevel` call the request body had the expected chunk size and binary data in the request body.  With the `setLevel` call the request body had just a chunk size of 0 and no request body.

```
import java.io.InputStream;
import java.io.IOException;
import java.io.OutputStream;

import okhttp3.HttpUrl;
import okhttp3.MediaType;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.RequestBody;
import okhttp3.Response;
import okhttp3.logging.HttpLoggingInterceptor;

import okio.Buffer;
import okio.BufferedSink;

public class OkHttpMinimalPut {

  public static void main(String[] args) throws IOException {
    OkHttpClient client = new OkHttpClient.Builder()
      .addNetworkInterceptor(
        new HttpLoggingInterceptor()
          .setLevel(HttpLoggingInterceptor.Level.BODY))
      .build();

    Request request = new Request.Builder()
      .url(
        new HttpUrl.Builder()
          .scheme("http")
          .host(args[0])
          .port(Integer.parseInt(args[1]))
          .addPathSegments("my/endpoint")
          .addQueryParameter("fileName", "OkHttpMinimalPut.class")
          .build()
      )
      .put(getJavaClass())
      .build();
    try ( Response response = client.newCall(request).execute() ) {
      System.out.println("response=" + response.toString());
    }
  }

  private static RequestBody getJavaClass() {
    InputStream thisClass = OkHttpMinimalPut.class.getResourceAsStream("OkHttpMinimalPut.class");
    return new RequestBody() {
      @Override public MediaType contentType() {
        return MediaType.parse("application/octet-stream");
      }

      @Override public void writeTo(BufferedSink sink) throws IOException {
        byte[] data = new byte[1024];
        int bytesRead;
        while ( (bytesRead = thisClass.read(data)) > 0 ) {
          sink.write(data, 0, bytesRead);
        }
      }
    };
  }
}
```

**Comment by swankjesse** [comment]
Try changing your `writeTo()` method to write the full body on each call:

```
      @Override public void writeTo(BufferedSink sink) throws IOException {
        InputStream thisClass = OkHttpMinimalPut.class.getResourceAsStream("OkHttpMinimalPut.class");
        byte[] data = new byte[1024];
        int bytesRead;
        while ( (bytesRead = thisClass.read(data)) > 0 ) {
          sink.write(data, 0, bytesRead);
        }
      }
```

We expect `RequestBody.writeTo()` to be called multiple times. This is useful for the logging interceptor, and also for retries on unexpected network failures.

**Comment by swankjesse** [comment]
Admittedly, our docs should call this out.

**Comment by sammefford** [comment]
That's a good work-around for my example.  Unfortunately, I'm not just trying to solve that scenario--that's just an example.  The scenarios I'm trying to address are when a user of my library gave me a large stream and I need to send it.  So I'll need to make sure I can deal with logging, auth, gzip, etc. without losing my one shot at that stream.  I can't assume I can buffer it--I need to assume it might sometimes be too large to reasonably buffer.  There are scenarios where a payload is only available once.  I presume this is why you have [UnrepeatableRequestBody](https://github.com/square/okhttp/blob/master/okhttp/src/main/java/okhttp3/internal/http/UnrepeatableRequestBody.java).  

By the way, thanks for an awesome HTTP library!  Jersey 2.x left us stranded with unresolved bugs, and Java 9 and Apache HttpClient are just getting started on async and HTTP2.  So we're very excited to see the traction behind OkHttp.  From what I can see, you've dealt with the extreme requirements like we have--I just need to learn how to put all the pieces together.

**Comment by sammefford** [comment]
I think this is a better example.  Presume there's a library that has utility methods `sendNonRetryablePut` and `streamRequestBody` that don't own the InputStream and can't recreate it.

```
import java.io.InputStream;
import java.io.IOException;
import java.io.OutputStream;

import okhttp3.HttpUrl;
import okhttp3.MediaType;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.RequestBody;
import okhttp3.Response;
import okhttp3.logging.HttpLoggingInterceptor;

import okio.Buffer;
import okio.BufferedSink;

public class OkHttpMinimalPut {

  public static void main(String[] args) throws IOException {
    OkHttpClient client = new OkHttpClient.Builder()
      .addNetworkInterceptor(
        new HttpLoggingInterceptor()
          .setLevel(HttpLoggingInterceptor.Level.BODY))
      .build();

    InputStream thisClass = OkHttpMinimalPut.class.getResourceAsStream("OkHttpMinimalPut.class");
    HttpUrl url = new HttpUrl.Builder()
      .scheme("http")
      .host(args[0])
      .port(Integer.parseInt(args[1]))
      .addPathSegments("my/endpoint")
      .addQueryParameter("fileName", "OkHttpMinimalPut.class")
      .build();
    sendNonRetryablePut(client, url, thisClass);
  }

  public static void sendNonRetryablePut(OkHttpClient client, HttpUrl url, InputStream stream) throws IOException {
    Request request = new Request.Builder()
      .url(url)
      .put(streamRequestBody(stream))
      .build();
    try ( Response response = client.newCall(request).execute() ) {
      System.out.println("response=" + response.toString());
    }
  }

  private static RequestBody streamRequestBody(InputStream stream) {
    return new RequestBody() {
      @Override public MediaType contentType() {
        return MediaType.parse("application/octet-stream");
      }

      @Override public void writeTo(BufferedSink sink) throws IOException {
        byte[] data = new byte[1024];
        int bytesRead;
        while ( (bytesRead = stream.read(data)) > 0 ) {
          sink.write(data, 0, bytesRead);
        }
      }
    };
  }
}
```

**Comment by swankjesse** [comment]
We designed `Level.BODY` for debug logging. Making it support streaming requests has some weird bad consequences – in particular we’d probably need to fragment the request body into separate log messages and that’d look weird.

I recommend using [Charles](https://www.charlesproxy.com/) or [Chuck](https://github.com/jgilfelt/chuck) if you’re looking for better ways to inspect your request body.

**Comment by sammefford** [comment]
I'm not looking for a work-around.  As I said in my original post, I used wireshark to validate this issue.  So I can monitor/debug fine without Level.BODY.  

I just logged this issue as a courtesy to your project.  It would be unfortunate if others experienced what I did as I was getting started with OkHttp.  It just made sense to me to use Level.BODY as I was learning so I could see that requests and responses were through properly.  But that put me in the uncomfortable situation of my code not working as the examples said it should.  It took an unfortunate amount of effort to discover that it was HttpLoggingInterceptor that was breaking my code.

I guess it's up to you whether that's an issue you want to address so others don't encounter the same thing.

**Comment by lDuffy** [comment]
Hi. To Add to this post. Ive noticed the same issue occurring when adding a Chunk interceptor and adding a Stetho as well as the httpLoggingInterceptor. In my case I'm reading audio from the microphone and writing to sink. 
            @Override
            public void writeTo(BufferedSink sink) throws IOException {

                while (isRecording() && (totalBytes < MAXIMUM_RECORDING_SIZE)) {
                        byte[] bytes = recorder.consumeRecording();
                        totalBytes += bytes.length;
                        sink.write(bytes);
                        Timber.d(String.valueOf(bytes.length));
                    }
                    try {
                        Thread.sleep(100);
                    } catch (InterruptedException e) {
                        Timber.e(TAG, "writeTo: ", e);
                    }
                }
            }

**Comment by sammefford** [comment]
Someone else reported the same issue: #3157
