### ISSUE TITLE
Do You guys think, that know better than me, what I want?

### ISSUE THREAD

**Issue by dnovikov-pro** [square/okhttp#3273]
Do You guys think, that know better than me, what I want? Why did You do all this f*king "security" checks without ability to make "unsafe" HTTP opertaions? 

Here what I mean:

REF: https://github.com/square/okhttp/blob/master/okhttp/src/main/java/okhttp3/HttpUrl.java

1. "By canonicalizing the input paths, they are complicit in directory traversal attacks."

It's a client, not a server! Why cannot I send a path-traversal request for a testing purpose?

2. "Each component must be encoded before it is embedded in the complete URL."

Some security tests should be send in an unencoded URL form. But You  guys say: "No, people doesn't need it, we know". How do You know this?

And Google decides, why don't we use OkHttp as underlying level of HttpURLConnection. Nor You nor google give developer an alternative. It's pretty sad, when you have to look for an alternative for a such common component.

**Comment by JakeWharton** [comment]
Here's an alternative: https://hc.apache.org/httpcomponents-client-ga/

**Comment by cesards** [comment]
@JakeWharton I would have respond with:

![dancing happy cuac](https://cloud.githubusercontent.com/assets/1536079/24811956/7e49c096-1bc8-11e7-837d-b597b194944d.gif)
