### ISSUE TITLE
addQueryParameter() not escapes `;` (semicolon)

### ISSUE THREAD

**Issue by iglaweb** [square/okhttp#3274]
I use HttpUrl.Builder#addQueryParameter, but String ';&' is translated into ";%26". Why semicolon is not escaped?

If user passes the value containing ';' as a get parameter, it can be treated as the delimiter by server and hence the part of the query string can be broken. How can I force to escape the whole user string? Using retrofit 2.1 + okhttp 3.6

**Comment by JakeWharton** [comment]
The escaping behavior is because an ampersand is a separator between key/value pairs whereas a semicolon is not. If your server treats it as a separate you'll need to escape it yourself.

**Comment by swankjesse** [comment]
No action for us to take on this.

**Comment by fuyun** [comment]
I am using retrofit, for an API like

postAPI(@Query("param") String val)

If val (user passed) contains semicolon, the generated URL does not escape the semicolon. I feel it is not the right behavior. For example, if I use Django as server, Django truncates parameter val at the semicolon. I cannot handle it at all. I have to treat semicolon specially on client side.

**Comment by JakeWharton** [comment]
That sounds like Django specific behavior or a Django bug.

**Comment by fuyun** [comment]
This is determined by python urlparse I guess

https://docs.python.org/2/library/urlparse.html#urlparse.parse_qs

>>> urlparse.parse_qs("name1=val1;val2&name2=val3")
{'name2': ['val3'], 'name1': ['val1']}

**Comment by JakeWharton** [comment]
That is quite broken!

**Comment by fuyun** [comment]
For Django users, if you want to patch this issue on server side, you can fix it this way

orig_query = request.META['QUERY_STRING']
if orig_query is not None:
       request.GET = QueryDict(orig_query.replace(";", "%3B"))

**Comment by swankjesse** [comment]
What’s completely absurd about that Python API is that it expects both `;` and `%3B` to be used and puts the burden on the caller to decide which to use. How you escape the URL has behavior consequences!

OkHttp has no idea how you intent to interpret `;` and can’t escape on your behalf.
