### ISSUE TITLE
3.6.0 version with socketIO?

### ISSUE THREAD

**Issue by gewuxy** [square/okhttp#3275]
in 3.4.1，the code is:
compile 'com.squareup.okhttp3:okhttp:3.4.1'
    compile 'com.squareup.okhttp3:okhttp-ws:3.4.1'

in 3.6.0 how?

**Comment by artem-zinnatullin** [comment]
WebSockets are now part of OkHttp itself, you don't need separate
dependency.

**Comment by gewuxy** [comment]
any demo to study?

**Comment by JakeWharton** [comment]
You'll have to ask the SocketIO people. We have nothing to do with that project so there aren't any demos using it.

**Comment by arvi** [comment]
@gewuxy I had a similar issue and posted my answer in SO http://stackoverflow.com/questions/42209251/okhttp3-java-lang-nosuchmethoderror-no-virtual-method-setcallwebsocket/43714998#43714998
