### ISSUE TITLE
sometimes upload audio file broken

### ISSUE THREAD

**Issue by gewuxy** [square/okhttp#3279]
I use this code to upload audio file (about 500K) ,but it sometimes upload failed caused by file broken:
`

        AudioAttachment attachment = (AudioAttachment)msg.getAttachment();
        String path = attachment.getPath();
        MultipartBody.Part body = null;
        if(TextUtils.isEmpty(path)){
            ToastUtil.showToast(getActivity(),getString(R.string.audio_file_not_exist));
            return false;
        }
        File file = new File(path);
        RequestBody requestFile = RequestBody.create(MediaType.parse("audio/*"), file);
        body = MultipartBody.Part.createFormData("audio_file", file.getName(), requestFile);

        HashMap<String,RequestBody> params = new HashMap<>();
        params.put("lecture_id",RequestBody.create(MediaType.parse("multipart/form-data"), mId + ""));
        params.put("need_encode",RequestBody.create(MediaType.parse("multipart/form-data"), String.valueOf(false)));
        params.put("duration",RequestBody.create(MediaType.parse("multipart/form-data"),attachment.getDuration() + ""));
        params.put("reply_message_id",RequestBody.create(MediaType.parse("multipart/form-data"),msg.getReplyMsgId() + ""));
        params.put("uuid",RequestBody.create(MediaType.parse("multipart/form-data"),msg.getUuid()));
        params.put("ts",RequestBody.create(MediaType.parse("multipart/form-data")
                ,String.valueOf(System.currentTimeMillis())));

        Subscription subscription = ApiService.getInstance().sendAudioMessage(body,params).subscribe(new HttpObserver<IMMessage>() {
            @Override
            protected void onError(ApiException ex) {
                ex.printStackTrace();
                ToastUtil.showToast(getActivity(),ex.getMsg());
                onSendMessageFail(msg);
            }

            @Override
            public void onNext(IMMessage imMessage) {
                onSendMessageSuccess(msg);
            }
        });
        mCompositeSubscription.add(subscription);`

**Comment by gewuxy** [comment]
`

    compile ('com.squareup.retrofit2:retrofit:2.1.0'){
        // 排除依赖okhttp
        exclude module: 'okhttp'
    }

    compile 'com.squareup.retrofit2:adapter-rxjava:2.1.0'
    compile 'com.squareup.retrofit2:converter-gson:2.1.0'
    compile 'io.reactivex:rxjava:1.0.14'
    compile 'io.reactivex:rxandroid:1.0.1'`

**Comment by swankjesse** [comment]
I’m sorry, this isn’t enough for us to take any action. Please isolate the problem and send a small test case that demonstrates where OkHttp is incorrect!
