### ISSUE TITLE
com.squareup.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress (RouteSelector.java:187)

### ISSUE THREAD

**Issue by yangguozhong** [square/okhttp#3290]
- [ ] Bug report.
com.squareup.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress (RouteSelector.java:187)
	
com.squareup.okhttp.internal.http.RouteSelector.nextProxy (RouteSelector.java:156)
	
com.squareup.okhttp.internal.http.RouteSelector.next (RouteSelector.java:98)
	
com.squareup.okhttp.internal.http.HttpEngine.createNextConnection (HttpEngine.java:344)
	
com.squareup.okhttp.internal.http.HttpEngine.connect (HttpEngine.java:327)
	
com.squareup.okhttp.internal.http.HttpEngine.sendRequest (HttpEngine.java:245)
	
com.squareup.okhttp.Call.getResponse (Call.java:267)
	
com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed (Call.java:224)
	
com.squareup.okhttp.Call.getResponseWithInterceptorChain (Call.java:195)
	
com.squareup.okhttp.Call.access$100 (Call.java:34)
	
com.squareup.okhttp.Call$AsyncCall.execute (Call.java:162)
	
com.squareup.okhttp.internal.NamedRunnable.run (NamedRunnable.java:33)
	
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1133)
	
java.lang.Thread.run (Thread.java:776)
 - [ ] Feature Request.
I want master to solve this problem a little faster, or tell me how to deal with it
I use okhttp 2.5.0 or 2.7.5 jar have this problem

**Comment by swankjesse** [comment]
Get with the times. Use 3.7.0.

**Comment by yangguozhong** [comment]
I use the okhttp version is 2x+, not okhttp3.
Okhttp 2 has stopped maintenance?

**Comment by swankjesse** [comment]
Yep.
