### ISSUE TITLE
MockWebserver : Firebase java.net.ConnectException: Failed to connect to localhost/127.0.0.1:3000

### ISSUE THREAD

**Issue by meethdjain** [square/okhttp#3296]
Hi, 

I'd like to report an issue that I'm facing with mockwebserver, while running Instrumentation Tests on Firebase Test Lab.

I'm using the mockwebserver to intercept & return mock responses for requests being sent from my app. The mock responses are stored locally in the assets folder.

I have multiple instrumentation tests & after few tests are run, I get the following error due to which the instrumentation flow breaks

**04-19 05:38:31.514: D/OkHttp(8347): --> GET http://localhost:3000/sample/url http/1.1
04-19 05:38:31.515: D/OkHttp(8347): <-- HTTP FAILED: java.net.ConnectException: Failed to connect to localhost/127.0.0.1:3000**

Note : I'm not facing this issue when I run the some Instrumentation Tests on a Local Emulator

**Sample Code**

`class ScreenTest {

  @Rule
  public MockWebServer mMockWebServer = new MockWebServer();

  ScreenTest() throws Exception {
    startServer();
  }

  private void startServer() throws Exception {
    int port = 3000;
    mMockWebServer.start(port);
    //Change the base url for all requests
    BuildConfig.changeUrl(mMockWebServer.url("/").toString());
    mMockWebServer.setDispatcher(new Dispatcher() {
      @Override
      public MockResponse dispatch(RecordedRequest request) throws InterruptedException {
        MockResponse mockResponse = new MockResponse();
        mockResponse.setResponseCode(200);
        mockResponse.setBody(MockHelper.getStringFromFilePath(request));
        return mockResponse;
      }
    });
  }

  @Test
  public void runTest1() {
    //Test Code Here
  }

  @Test
  public void runTest2() {
    //Test Code Here
  }  

  @After
  public void stop() throws Exception {
    shutdown();
  }

  private void shutdown() throws Exception {
    mMockWebServer.shutdown();
    mMockWebServer = null;
  }
}`

**Comment by swankjesse** [comment]
Consider omitting the port argument when setting up the server. That'll cause an available port to be assigned automatically. You can look it up after the server has started.

**Comment by meethdjain** [comment]
@swankjesse : I've tried omitting the port as well, still doesn't solve the issue.

As a workaround, instead of starting the server as @Rule for each test, I'm not starting the server onCreate of my app, which seems to solve the issue.

**Comment by darthcow** [comment]
@meethdjain Could you please explain how does your workaround work? You're not starting the server onCreate so where are you starting it? and by server you mean mockWebServer right?

**Comment by radityagumay** [comment]
@meethdjain how do you solve this issue?

I found a weird behavior on MockWebserver. in local machine percentage tests passed are high, but when running on Firebase Test Labs, its drastically failed due to ConnectionException.
