### ISSUE TITLE
Continues throw SocketTimeoutException after a long time run

### ISSUE THREAD

**Issue by VictorSnow** [square/okhttp#3298]
What kind of issue is this?

 - [ ] Question. This issue tracker is not the place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use Stack
       Overflow. https://stackoverflow.com/questions/tagged/okhttp

 - [x] Bug report. If you’ve found a bug, spend the time to write a failing test. Bugs with tests
       get fixed. Here’s an example: https://gist.github.com/swankjesse/981fcae102f513eb13ed

 - [ ] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
       already exists! Don’t send pull requests to implement new features without first getting our
       support. Sometimes we leave features out on purpose to keep the project small.

Bug info and Request code blow:
[Gist Code](https://gist.github.com/VictorSnow/b680736af2faab7333a7e1e71d55baeb)

Bug: Continues throw SocketTimeoutException after a long time run
Device: nexus5 (with Supersu Xposed)
Android Version: 6.0.1

i also wrote anonther app(same code), do the same request, successed to perform request, but the origin app keep throw SocketTimeoutException, so it's not a network problem

so far as i tried, when i open the origin app,  network start being ok, SocketTimeoutException disappeared!

**Comment by JakeWharton** [comment]
This exception, quite clearly, comes from the platform and not from the
library. Unless you somehow think this is a bug in the library, there's no
action to take here.

**Comment by VictorSnow** [comment]
more likely  android wifi network restrict or bug

i will need to look into it

**Comment by VictorSnow** [comment]
finally found that it's about nexus5 rom limit, just change and keep the screen on
