### ISSUE TITLE
URL Parsing: Strip whitespace after newline?

### ISSUE THREAD

**Issue by EricEdens** [square/okhttp#3300]
I've been looking at whitespace removal when parsing URLs. Based off [this discussion](https://tools.ietf.org/html/rfc3986#appendix-C), I think the motivation is to remove whitespace that was added by an eager line breaker. Consistent with [your research](https://docs.google.com/spreadsheets/d/1BgGAhJ5WE3JBsATeudamiBzxmgEhwkfcFqQmPx8qrkc/edit#gid=0), both Chrome and FF fail to open this link successfully:

```html
<html>
<body>
  <a href="http://www.google
  .com/maps">Google Maps</a>
</body>
</html>
```

Proposed change: During URL parsing, if `\n` or `\r` is seen, drop that *and all following codepoints* until a non-whitespace codepoint is seen.

Future test cases:

```java
    // Currently fails with http://host.com/%20%20info.
    assertEquals("http://host.com/info", HttpUrl.parse("http://host.com/\n  info").toString());

    // Currently fails due to HttpUrl.parse returning null since spaces aren't allowed in DNS hostnames.
    assertEquals("http://host.com/info", HttpUrl.parse("http://host.\n  com/info").toString());
```

To avoid regression, these test cases should still pass:

```java
    assertEquals("http://host.com/info", HttpUrl.parse("http://host.com/\tinfo").toString());
    assertEquals("http://host.com/info", HttpUrl.parse("http://host.com/\rinfo").toString());
    assertEquals("http://host.com/info", HttpUrl.parse("http://host.com/\ninfo").toString());
    assertEquals("http://host.com/info", HttpUrl.parse("http://host.com/\finfo").toString());
```

Open questions:
1. Which codepoints are whitespace? The [unicode.org](http://unicode.org/cldr/utility/list-unicodeset.jsp?a=%5Cp%7Bwhitespace%7D) definition is used by Guava.

If you guys are interested in this, I'm happy to help out and write a pull request.

**Comment by EricEdens** [comment]
Second open question: What definition of line break to use? Some additional looking, and Unicode defines its own set, eg:

https://en.wikipedia.org/wiki/Newline#Unicode
[\R in Pattern](https://docs.oracle.com/javase/7/docs/api/java/util/regex/Pattern.html)

**Comment by swankjesse** [comment]
Is this a real problem in practice? I assume anything that's accepting line-wrapped URLs will preprocess them before offering them to OkHttp.

**Comment by EricEdens** [comment]
Maybe not! I ran into it while processing URLs taken from HTML documents, so I'll just clean the whitespace before passing it to OkHttp.
