### ISSUE TITLE
Add utility method inside Header to return a concatenated value for duplicate response header names

### ISSUE THREAD

**Issue by akiwarheit** [square/okhttp#3302]
Considering that duplicate response headers are actually a thing https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2

It would be nice if we could suplement Headers.get() https://square.github.io/okhttp/3.x/okhttp/okhttp3/Headers.html#get-java.lang.String-

With a utility method that returns a concatenated value for duplicate response headers e.g.
`String concat(String name)`

Currently I would have to do the ff.

```java
String cookie = "";
for (String cookieCandidate : Splitter.on("\n").split(objectResponse.headers().toString())) {
  if (cookieCandidate.startsWith("Set-Cookie")) {
    cookie += cookieCandidate.replace("Set-Cookie:", "").trim() + ";";
  }
}
```

What do you guys think? And what should the method name be?

**Comment by swankjesse** [comment]
Does `Headers.values("Set-Cookie")` work?
