### ISSUE TITLE
Content-Length and stream length disagree when cache was edited

### ISSUE THREAD

**Issue by JackLauu** [square/okhttp#3303]
When the local cache file was edited manually, OkHttp will give a IOException with message:"Content-Length and stream length disagree". It can't be fixed, OkHttp will continue to give this exception. If OkHttp 
automatically delete the invalid cache or give a option to neglect check content-length?

**Comment by swankjesse** [comment]
It’s unlikely we will try to recover from a cache that's been corrupted in this way. This should never happen.
