### ISSUE TITLE
will ArrayDeque used in Dispatcher cause concurrent issue in multi-thread environment

### ISSUE THREAD

**Issue by chchgb** [square/okhttp#3310]
In Dispatcher implement, ArrayDeque were used for readyAsyncCalls, runningAsyncCalls, runningSyncCalls. But in multi-thread environment, there were only synchronized method in code, which did not protect ConcurrentModificationException case, like one request was enqueuing, another request was finished and removing from the queue.

in finished(), synchronized (this) only can avoid concurrently remove().

**Comment by swankjesse** [comment]
Send a PR? I think we’re already synchronizing where we need to be.

```
  private <T> void finished(Deque<T> calls, T call, boolean promoteCalls) {
    int runningCallsCount;
    Runnable idleCallback;
    synchronized (this) {
      if (!calls.remove(call)) throw new AssertionError("Call wasn't in-flight!");
      if (promoteCalls) promoteCalls();
      runningCallsCount = runningCallsCount();
      idleCallback = this.idleCallback;
    }

    if (runningCallsCount == 0 && idleCallback != null) {
      idleCallback.run();
    }
  }
```

**Comment by chchgb** [comment]
@swankjesse only remove() was in synchronizing. does it need to synchronize both add() and remove() for ArrayDeque

**Comment by swankjesse** [comment]
When applied to a non-static method, the `synchronized` keyword is the same as `synchronized (this) { }`.

**Comment by chchgb** [comment]
got it, thanks.
