### ISSUE TITLE
[Question]:Why the default number of connections is 5

### ISSUE THREAD

**Issue by jasonzhang1986** [square/okhttp#3313]
`/**
   * Create a new connection pool with tuning parameters appropriate for a single-user application.
   * The tuning parameters in this pool are subject to change in future OkHttp releases. Currently
   * this pool holds up to 5 idle connections which will be evicted after 5 minutes of inactivity.
   */
  public ConnectionPool() {
    this(5, 5, TimeUnit.MINUTES);
  }
`
why the default number of  connection is 5?

**Comment by swankjesse** [comment]
Historical accident. What should it be?

**Comment by swankjesse** [comment]
No action to take on this.
