### ISSUE TITLE
Dispatcher is hard to customize

### ISSUE THREAD

**Issue by SethFeng** [square/okhttp#3314]
I want to customize `Dispatcher ` to implement a priority ready async calls. I enqueue many download requests, I want to promote a special call (like login request) to execute after one completed in running async calls queue.
```java
Comparator comparator = new Comparator<RealCall.AsyncCall>() {
    @Override
    public int compare(RealCall.AsyncCall o1, RealCall.AsyncCall o2) {
        String host1 = o1.request().url().toString();
        String host2 = o2.request().url().toString();
        if (host1.contains("download") && !host2.contains("download")) {
            return 1;
        } else if (!host1.contains("download") && host2.contains("download")) {
            return -1;
        }
        return 0;
    }
};

private final PriorityQueue<RealCall.AsyncCall> readyAsyncCalls = new PriorityQueue<>(11, comparator);

...

private void promoteCalls() {
    if (runningAsyncCalls.size() >= maxRequests) return; // Already running max capacity.
    if (readyAsyncCalls.isEmpty()) return; // No ready calls to promote.
    Object[] array = readyAsyncCalls.toArray();
    Arrays.sort(array, comparator);
    for(Object i : array) {
        RealCall.AsyncCall call = (RealCall.AsyncCall) i;
        if (runningCallsForHost(call) < maxRequestsPerHost) {
            readyAsyncCalls.remove(i);
            runningAsyncCalls.add(call);
            executorService().execute(call);
        }
        if (runningAsyncCalls.size() >= maxRequests) return; // Reached max capacity.
    }
}
```
`Dispatcher` is defined as a final class. It's hard to extend, or as a interface to implement. What `OkHttpClient.Builder.dispatcher(Dispatcher)` can customize is limited.

**Comment by swankjesse** [comment]
Tracking here:
https://github.com/square/okhttp/issues/1361

Doing priority naively is easy; handling the corner cases might be very difficult. If you need this urgently, I’d love it if you could help to figure out what the gotchas are. Could you fork the project, customize Dispatcher to your liking, and report back how that went? Were there unexpected problems or benefits?

I’m going to close this for now; please comment on #1361 if you get something that works!
