### ISSUE TITLE
NetworkOnMainThreadException when calling evictAll() method

### ISSUE THREAD

**Issue by jkangzhang** [square/okhttp#3322]
This is what I've done for releasing resources of OKHttp

 `if (okHttpClient != null) {
            if (okHttpClient.dispatcher() != null && okHttpClient.dispatcher().executorService() != null) {
                okHttpClient.dispatcher().executorService().shutdown();  
            }
            if (okHttpClient.connectionPool() != null) {
                okHttpClient.connectionPool().evictAll();               
            }
            try {
                if (okHttpClient.cache() != null) {
                    okHttpClient.cache().close(); 
                }
            } catch (IOException e) {
                LOG.info("Close okhttp error" + e.toString());
            }
        }`

and this is the log info:

` android.os.NetworkOnMainThreadException:
 android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1148)
com.android.org.conscrypt.OpenSSLSocketImpl.close(OpenSSLSocketImpl.java:1010)
okhttp3.internal.Util.void closeQuietly(java.net.Socket)(Now:103)
okhttp3.ConnectionPool.void evictAll()(Now:170)
com.danikula.videocache.HttpUrlSource.void clearConnection()(Now:218) `

**Comment by JakeWharton** [comment]
Looks like this should use `cancel()` instead of `closeQuietly(socket())`. Or maybe we can get away with changing `socket()` to return `rawSocket` instead of `socket`...

**Comment by JakeWharton** [comment]
Related: https://github.com/square/okhttp/pull/2048

**Comment by swankjesse** [comment]
I think this was closed here: https://github.com/square/okhttp/issues/1592

**Comment by swankjesse** [comment]
Nope, that issue is about canceling, not `evictAll()`. 

I don’t think there’s a better solution here. We need to do network stuff to tear down sockets. You should call this method on a background thread!
