### ISSUE TITLE
Whether okhttp can use gradle building?

### ISSUE THREAD

**Issue by gdky005** [square/okhttp#3333]
I want to use the gradle build the project and look at it.Late but can't see now, could you please tell me whether can consider to use gradle build?After all gradle is now the mainstream。Don't need to use all gradle, can be part of the first part of the transfer.

**Comment by gdky005** [comment]
I found with Android Studio is not open properly and use the idea, what tools do you usually using?

**Comment by swankjesse** [comment]
I use Maven with IntelliJ. We won’t be adding a Gradle build.

**Comment by gdky005** [comment]
You win.  Perhaps the historical reasons。I can understand, I am very sad.

**Comment by autonomousapps** [comment]
@gdky005 you can download the IntelliJ IDE [here](https://www.jetbrains.com/idea/#chooseYourEdition). It will import Maven builds and offer a GUI for building.
