### ISSUE TITLE
Upload large files, appear OOM

### ISSUE THREAD

**Issue by 550609334** [square/okhttp#3337]
hi

I used OkHttp upload large files when there OOM, is very common through Multipart upload files, small files no problem. OOM out of this document is 84MB, is there any way to solve?

Thank you！

05-09 18:01:56.190 2196-2196/com.example.testfile D/NetworkSecurityConfig: No Network Security Config specified, using platform default
05-09 18:01:56.270 2196-2795/com.example.testfile D/OkHttp: --> POST http://172.25.121.132:8080/upload.do http/1.1
05-09 18:01:56.270 2196-2795/com.example.testfile D/OkHttp: Content-Type: multipart/form-data; boundary=c8eb70eb-5fc2-4516-a675-e4ff9aa38d5c
05-09 18:01:56.273 2196-2795/com.example.testfile D/OkHttp: Content-Length: 89063108
05-09 18:01:56.273 2196-2795/com.example.testfile D/OkHttp: isHeader: done
05-09 18:01:56.299 2196-2233/com.example.testfile I/Adreno: QUALCOMM build                   : a5b4970, If5818605d9
                                                            Build Date                       : 10/12/16
                                                            OpenGL ES Shader Compiler Version: XE031.09.00.04
                                                            Local Branch                     : N24D
                                                            Remote Branch                    : 
                                                            Remote Branch                    : 
                                                            Reconstruct Branch               : 
05-09 18:01:56.340 2196-2233/com.example.testfile I/OpenGLRenderer: Initialized EGL, version 1.4
05-09 18:01:56.340 2196-2233/com.example.testfile D/OpenGLRenderer: Swap behavior 1
05-09 18:01:56.346 2196-2206/com.example.testfile W/art: Suspending all threads took: 5.061ms
05-09 18:01:56.575 2196-2210/com.example.testfile W/art: Suspending all threads took: 10.133ms
05-09 18:01:56.579 2196-2210/com.example.testfile I/art: Background sticky concurrent mark sweep GC freed 2247(1358KB) AllocSpace objects, 0(0B) LOS objects, 16% free, 8MB/10MB, paused 10.971ms total 34.882ms
05-09 18:01:56.589 2196-2210/com.example.testfile W/art: Suspending all threads took: 9.618ms
05-09 18:02:04.872 2196-2206/com.example.testfile W/art: Suspending all threads took: 5.835ms
05-09 18:02:05.872 2196-2206/com.example.testfile W/art: Suspending all threads took: 6.606ms
05-09 18:02:07.001 2196-2795/com.example.testfile I/art: Starting a blocking GC Alloc
05-09 18:02:07.001 2196-2795/com.example.testfile I/art: Starting a blocking GC Alloc
05-09 18:02:07.026 2196-2795/com.example.testfile I/art: Alloc sticky concurrent mark sweep GC freed 71724(2MB) AllocSpace objects, 0(0B) LOS objects, 2% free, 136MB/139MB, paused 784us total 24.299ms
05-09 18:02:07.030 2196-2795/com.example.testfile I/art: Starting a blocking GC Alloc
05-09 18:02:07.064 2196-2795/com.example.testfile I/art: Alloc partial concurrent mark sweep GC freed 550(29KB) AllocSpace objects, 0(0B) LOS objects, 10% free, 136MB/152MB, paused 1.007ms total 33.380ms
05-09 18:02:07.068 2196-2795/com.example.testfile I/art: Starting a blocking GC Alloc
05-09 18:02:07.118 2196-2795/com.example.testfile I/art: Alloc concurrent mark sweep GC freed 104(3KB) AllocSpace objects, 0(0B) LOS objects, 10% free, 136MB/152MB, paused 869us total 50.353ms
05-09 18:02:07.121 2196-2795/com.example.testfile I/art: Forcing collection of SoftReferences for 84MB allocation
05-09 18:02:07.122 2196-2795/com.example.testfile I/art: Starting a blocking GC Alloc
05-09 18:02:07.168 2196-2795/com.example.testfile I/art: Alloc concurrent mark sweep GC freed 3(72B) AllocSpace objects, 0(0B) LOS objects, 10% free, 136MB/152MB, paused 840us total 46.072ms
05-09 18:02:07.172 2196-2795/com.example.testfile W/art: Throwing OutOfMemoryError "Failed to allocate a 89063120 byte allocation with 16771688 free bytes and 55MB until OOM"
05-09 18:02:07.172 2196-2795/com.example.testfile I/art: Starting a blocking GC Alloc
05-09 18:02:07.172 2196-2795/com.example.testfile I/art: Starting a blocking GC Alloc
05-09 18:02:07.180 2196-2795/com.example.testfile I/art: Alloc sticky concurrent mark sweep GC freed 4(512B) AllocSpace objects, 0(0B) LOS objects, 10% free, 136MB/152MB, paused 814us total 7.525ms
05-09 18:02:07.184 2196-2795/com.example.testfile I/art: Starting a blocking GC Alloc
05-09 18:02:07.216 2196-2795/com.example.testfile I/art: Alloc partial concurrent mark sweep GC freed 6(144B) AllocSpace objects, 0(0B) LOS objects, 10% free, 136MB/152MB, paused 767us total 32.489ms
05-09 18:02:07.220 2196-2795/com.example.testfile I/art: Starting a blocking GC Alloc
05-09 18:02:07.262 2196-2795/com.example.testfile I/art: Alloc concurrent mark sweep GC freed 3(72B) AllocSpace objects, 0(0B) LOS objects, 10% free, 136MB/152MB, paused 780us total 42.577ms
05-09 18:02:07.266 2196-2795/com.example.testfile I/art: Forcing collection of SoftReferences for 84MB allocation
05-09 18:02:07.266 2196-2795/com.example.testfile I/art: Starting a blocking GC Alloc
05-09 18:02:07.310 2196-2795/com.example.testfile I/art: Alloc concurrent mark sweep GC freed 3(72B) AllocSpace objects, 0(0B) LOS objects, 10% free, 136MB/152MB, paused 801us total 43.431ms
05-09 18:02:07.310 2196-2210/com.example.testfile I/art: WaitForGcToComplete blocked for 43.123ms for cause HeapTrim
05-09 18:02:07.314 2196-2795/com.example.testfile I/art: Waiting for a blocking GC HomogeneousSpaceCompact
05-09 18:02:07.315 2196-2795/com.example.testfile I/art: Starting a blocking GC HomogeneousSpaceCompact
05-09 18:02:07.614 2196-2795/com.example.testfile I/art: HomogeneousSpaceCompact marksweep + semispace GC freed 3(72B) AllocSpace objects, 0(0B) LOS objects, 10% free, 136MB/152MB, paused 298.968ms total 298.968ms
05-09 18:02:07.616 2196-2795/com.example.testfile W/art: Throwing OutOfMemoryError "Failed to allocate a 89063120 byte allocation with 16769248 free bytes and 55MB until OOM"
05-09 18:02:07.618 2196-2795/com.example.testfile E/AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
                                                                    Process: com.example.testfile, PID: 2196
                                                                    java.lang.OutOfMemoryError: Failed to allocate a 89063120 byte allocation with 16769248 free bytes and 55MB until OOM
                                                                        at okio.Buffer.readByteArray(Buffer.java:759)
                                                                        at okio.Buffer.readString(Buffer.java:619)
                                                                        at okio.Buffer.readString(Buffer.java:602)
                                                                        at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:199)
                                                                        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                                        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:179)
                                                                        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:129)
                                                                        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
                                                                        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                        at java.lang.Thread.run(Thread.java:761)

**Comment by swankjesse** [comment]
Please use StackOverflow for usage questions.
http://stackoverflow.com/questions/24279563/uploading-a-large-file-in-multipart-using-okhttp
