### ISSUE TITLE
java.nio.charset.IllegalCharsetNameException: %s 

### ISSUE THREAD

**Issue by gdky005** [square/okhttp#3340]
I met a very strange problem, appear on okhttp version 3.4: under Caused by: Java nio. Charset. IllegalCharsetNameException: %s.I was very confused, why so strange questions.Arguably the server returns the Charset inside is never to appear %s. This is the collapse of the specific log:

```
   Caused by: java.nio.charset.IllegalCharsetNameException: %s
    at java.nio.charset.Charset.checkCharsetName(Charset.java:197)
    at java.nio.charset.Charset.forName(Charset.java:295)
    at okhttp3.MediaType.charset(SourceFile:103)
    at okhttp3.ResponseBody.charset(SourceFile:159)
    at okhttp3.ResponseBody.string(SourceFile:154)
    at com.bb.h5.container.service.DownloadService$3.onResponse(SourceFile:806)
    at okhttp3.RealCall$AsyncCall.execute(SourceFile:141)
    at okhttp3.internal.NamedRunnable.run(SourceFile:32)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
    at java.lang.Thread.run(Thread.java:833)
```

**Comment by gdky005** [comment]
Currently only found in many devices at a time.

**Comment by swankjesse** [comment]
Could you provide a sample URL that has the problem? Typically this indicates that your server is sending down something like this:
```
Content-Type: application/json; charset=%s
```

**Comment by gdky005** [comment]
At present, this is the collapse of the background statistics information.And in a lot of equipment is only one device appeared again.I doubt whether information has been hijacked, or error in transmission.

**Comment by swankjesse** [comment]
Got it. In that case I recommend you decode the charset manually:

```
String bodyString = new String(responseBody.bytes(), "YOUR_CHARSET");
```

Where instead of `YOUR_CHARSET` you’ll probably put `UTF-8`, but you could use whatever charset you think the response is encoded with.

**Comment by swankjesse** [comment]
No further action for us to take on this! If you think there’s something we can do further, please add an executable test case!

**Comment by gdky005** [comment]
3Q

**Comment by gdky005** [comment]
I just looked at the relevant part of the code, feel so to modify.

MediaType.java
```
   /**
   * Returns the charset of this media type, or {@code defaultValue} if either this media type
   * doesn't specify a charset, of it its charset is unsupported by the current runtime.
   */
  public Charset charset(Charset defaultValue) {
    try {
      return charset != null ? Charset.forName(charset) : defaultValue;
    } catch (IllegalArgumentException e) {
      return defaultValue; // This charset is invalid or unsupported. Give up.
    } catch(IllegalCharsetNameException e) {
      return defaultValue; //
    }
  }
```


I saw you before in other issues mentioned, you can refer to the processing of Chrome and Safari.For unknown character, or the wrong, can catch up And return the default utf-8.
