### ISSUE TITLE
IllegalArgumentException: sockaddrToInetAddress unsupported ss_family: 0

### ISSUE THREAD

**Issue by vanshg** [square/okhttp#3345]
I've been seeing this exception in a couple of my users' crash logs. I haven't really been able to replicate it either. The crash occurred on OkHttp 3.7.0, on Android 7.0, on a Samsung Galaxy S8+. Unfortunately, I don't have much other information that I can provide, since I haven't been able to personally recreate this crash.

```
Exception java.lang.IllegalArgumentException: sockaddrToInetAddress unsupported ss_family: 0
libcore.io.Posix.android_getaddrinfo (Posix.java)
libcore.io.ForwardingOs.android_getaddrinfo (ForwardingOs.java:55)
java.net.Inet6AddressImpl.lookupHostByName (Inet6AddressImpl.java:106)
java.net.Inet6AddressImpl.lookupAllHostAddr (Inet6AddressImpl.java:74)
java.net.InetAddress.getAllByName (InetAddress.java:752)
okhttp3.Dns$1.lookup (Dns.java:39)
okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress (RouteSelector.java:170)
okhttp3.internal.connection.RouteSelector.nextProxy (RouteSelector.java:136)
okhttp3.internal.connection.RouteSelector.next (RouteSelector.java:81)
okhttp3.internal.connection.StreamAllocation.findConnection (StreamAllocation.java:171)
okhttp3.internal.connection.StreamAllocation.findHealthyConnection (StreamAllocation.java:121)
okhttp3.internal.connection.StreamAllocation.newStream (StreamAllocation.java:100)
okhttp3.internal.connection.ConnectInterceptor.intercept (ConnectInterceptor.java:42)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:92)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:67)
okhttp3.internal.cache.CacheInterceptor.intercept (CacheInterceptor.java:93)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:92)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:67)
okhttp3.internal.http.BridgeInterceptor.intercept (BridgeInterceptor.java:93)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:92)
okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept (RetryAndFollowUpInterceptor.java:120)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:92)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:67)
okhttp3.RealCall.getResponseWithInterceptorChain (RealCall.java:179)
okhttp3.RealCall$AsyncCall.execute (RealCall.java:129)
okhttp3.internal.NamedRunnable.run (NamedRunnable.java:32)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1133)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:607)
java.lang.Thread.run (Thread.java:762)
```

**Comment by swankjesse** [comment]
This is an internal crash [in Android](https://android.googlesource.com/platform/libcore/+/android-4.3_r3/luni/src/main/native/NetworkUtilities.cpp) that we can’t recover from.

        // We can't throw SocketException. We aren't meant to see bad addresses, so seeing one
        // really does imply an internal error.
        jniThrowExceptionFmt(env, "java/lang/IllegalArgumentException",
                             "sockaddrToInetAddress unsupported ss_family: %i", ss.ss_family);

There isn’t much we can do here unfortunately. Please report it to the device’s manufacturer.

**Comment by vanshg** [comment]
Any possible insight as to what might be causing the issue on those devices or what kind of address might be causing it? As far as I'm concerned, I'm never trying to access an address that's not either `AF_INET` or `AF_INET6`

**Comment by swankjesse** [comment]
Its a device bug. Not much you can do to cause or avoid this. If you report it to Google or Samsung, they might be able to fix it in the next update.

**Comment by daztop** [comment]
Given that I can't catch this crash (other than through an uncaughtExceptionHandler - yuk), can you offer any tips on what could cause it? I only use okhttp to load images (via Fresco), so I'd rather just fail that specific image than crash the whole app.

You say device bug - I'm seeing some reports of this from some devices (so far all Samsung models of varous ages running Android 6), but I'm not seeing it from all devices all of the time, so there must be something specific about the address being requested.

**Comment by swankjesse** [comment]
Another option – create your own implementation of `Dns`:

```
  Dns SAMSUNG_SAFE_DNS = new Dns() {
    @Override public List<InetAddress> lookup(String hostname) throws UnknownHostException {
      try {
        return Dns.SYSTEM.lookup(hostname);
      } catch (IllegalArgumentException e) {
        // Hack. See https://github.com/square/okhttp/issues/3345
        throw new UnknownHostException(e.getMessage());
      }
    }
  };
```

This works around the problem. If you get more information about how to reproduce, we might be able to figure out a workaround in OkHttp.

**Comment by ivokc** [comment]
huawei also has the question

**Comment by xckevin** [comment]
Xiaomi device get same error. Android 9, Redmi 8A Dual
