### ISSUE TITLE
okhttp3Version(3.7.0) SSL handshake aborted

### ISSUE THREAD

**Issue by Pluckypan** [square/okhttp#3348]
Caused by: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0x923d3d40: Failure in SSL library, usually a protocol error
error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER (external/boringssl/src/ssl/tls_record.c:192 0xa3025872:0x00000000) at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method) at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:357)

**Comment by Pluckypan** [comment]
if we set default port as 80 when visit https server will produce this error

**Comment by alexxgarci** [comment]
@Pluckypan I've got the same issue, how i change the default port?
