### ISSUE TITLE
how to add array of integer into RequestBody

### ISSUE THREAD

**Issue by BakhtiyarKBTU** [square/okhttp#3356]
`case 1:
                documentsList.clear();
                listAdapter.notifyDataSetChanged();
                direction = "out";
                doc_category.setText(Constant.DOCUMENT_CATEGORY.get(direction));
                formBody = DocumentUtils.generateParameters(Document_Constants.DocTitleTypes.OUTBOUND, Constant.TIMESTAMP_MAX);
                new getActs(getActivity()).execute(Urls.ACTS_FEED);
                break;`
`formBody = new FormBody.Builder()
                        .add(Constant.DIRECTION, Constant.OUT)
                        .add(Constant.LIMIT, Constant.docs_limit)
                        .add(Constant.IMPORTED, Constant.FALSE)
                        .add(Constant.STATUSES, Arrays.toString(new int[]{Document_Constants.DocumentStatus.Send.getStatus(),
                        Document_Constants.DocumentStatus.Success.getStatus(),
                        Document_Constants.DocumentStatus.Canceled.getStatus(),
                        Document_Constants.DocumentStatus.Revoked.getStatus()}))
                        .add(Constant.TIMESTAMP_START, String.valueOf(timestamp_start))
                        .build();`

I want to send post request where I need send array of integer, but by Requestbody i can only send string when i convert array of integer to String, it send bad request like picture below:
![image](https://cloud.githubusercontent.com/assets/9846332/26038052/76b8822e-3921-11e7-90ed-ef1a47da42da.png)

**Comment by JakeWharton** [comment]
Please ask usage questions on StackOverflow with the 'okhttp' tag
