### ISSUE TITLE
null pointer crash

### ISSUE THREAD

**Issue by steelbytes** [square/okhttp#3358]
just got the following crash in okhttp 3.8.0(*) on nexus 6p / 7.1.2

(*) pretty sure it's 3.8 and not 3.7.  any way to check in a compiled apk?

05-16 13:34:21.370 21469 11806 E AndroidRuntime: java.lang.NullPointerException: Attempt to write to field 'io.intercom.okio.Segment io.intercom.okio.Segment.next' on a null object reference
05-16 13:34:21.370 21469 11806 E AndroidRuntime:        at io.intercom.okio.Segment.pop(Segment.java:85)
05-16 13:34:21.370 21469 11806 E AndroidRuntime:        at io.intercom.okio.Buffer.skip(Buffer.java:820)
05-16 13:34:21.370 21469 11806 E AndroidRuntime:        at io.intercom.okio.RealBufferedSource.skip(RealBufferedSource.java:308)
05-16 13:34:21.370 21469 11806 E AndroidRuntime:        at io.intercom.okhttp3.internal.ws.WebSocketReader$FramedMessageSource.close(WebSocketReader.java:309)
05-16 13:34:21.370 21469 11806 E AndroidRuntime:        at io.intercom.okio.RealBufferedSource.close(RealBufferedSource.java:434)
05-16 13:34:21.370 21469 11806 E AndroidRuntime:        at io.intercom.okhttp3.internal.Util.closeQuietly(Util.java:88)
05-16 13:34:21.370 21469 11806 E AndroidRuntime:        at io.intercom.okhttp3.ResponseBody.bytes(ResponseBody.java:130)
05-16 13:34:21.370 21469 11806 E AndroidRuntime:        at io.intercom.okhttp3.ResponseBody.string(ResponseBody.java:154)
05-16 13:34:21.370 21469 11806 E AndroidRuntime:        at io.intercom.android.sdk.nexus.NexusSocket.onMessage(NexusSocket.java:191)
05-16 13:34:21.370 21469 11806 E AndroidRuntime:        at io.intercom.okhttp3.internal.ws.RealWebSocket$1.onMessage(RealWebSocket.java:62)
05-16 13:34:21.370 21469 11806 E AndroidRuntime:        at io.intercom.okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.java:242)
05-16 13:34:21.370 21469 11806 E AndroidRuntime:        at io.intercom.okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:108)
05-16 13:34:21.370 21469 11806 E AndroidRuntime:        at io.intercom.okhttp3.internal.ws.RealWebSocket.readMessage(RealWebSocket.java:97)
05-16 13:34:21.370 21469 11806 E AndroidRuntime:        at io.intercom.okhttp3.ws.WebSocketCall.createWebSocket(WebSocketCall.java:152)
05-16 13:34:21.370 21469 11806 E AndroidRuntime:        at io.intercom.okhttp3.ws.WebSocketCall.access$000(WebSocketCall.java:41)
05-16 13:34:21.370 21469 11806 E AndroidRuntime:        at io.intercom.okhttp3.ws.WebSocketCall$1.onResponse(WebSocketCall.java:97)
05-16 13:34:21.370 21469 11806 E AndroidRuntime:        at io.intercom.okhttp3.RealCall$AsyncCall.execute(RealCall.java:126)
05-16 13:34:21.370 21469 11806 E AndroidRuntime:        at io.intercom.okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
05-16 13:34:21.370 21469 11806 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
05-16 13:34:21.370 21469 11806 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
05-16 13:34:21.370 21469 11806 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:761)

**Comment by swankjesse** [comment]
Typically this occurs when you’re concurrently operating on a buffer from multiple threads.

**Comment by steelbytes** [comment]
I pretty sure I am not doing that.  I don't pass buffers between threads.  all my http code is using blocking calls to okhttp that build a request, execute it, read and process the whole body, then close all in a single method in in an asynctask

**Comment by steelbytes** [comment]
ah whoops - just noticed the io.intercom part of the class names in the callstack - yeah it's a 3rd party lib :-/
