### ISSUE TITLE
[Feature Request] add method to create RequestBody from InputStream

### ISSUE THREAD

**Issue by xanscale** [square/okhttp#3362]
android intents picker-capture doesn't not return file or path but an Uri (is not same thing)
actually to create a RequestBody we can start from file
`public static RequestBody create(MediaType contentType, File file)`

i think that will be usefull to have something like
`public static RequestBody create(MediaType contentType, InputString is)`
or
`public static RequestBody create(MediaType contentType, Uri uri)`

to make File from Uri the only sicure way is to copy all data in chace dir.

	public File getTempFile(Uri uri) throws IOException {
		File file = File.createTempFile("media", null);
		InputStream inputStream = context.getContentResolver().openInputStream(uri);
		OutputStream outputStream = new BufferedOutputStream(new FileOutputStream(file));
		byte[] buffer = new byte[1024];
		int len;
		while ((len = inputStream.read(buffer)) != -1)
			outputStream.write(buffer, 0, len);
		inputStream.close();
		outputStream.close();
		return file;
	}

**Comment by swankjesse** [comment]
We don’t support this because there are rare cases where we need to transmit the request body multiple times, and input streams have no such capability.

You should instead subclass `RequestBody` and do the work there.

**Comment by xanscale** [comment]
i say to add this possibility, not to replace

**Comment by swankjesse** [comment]
Agreed. The problem is that an InputStream isn’t capable of solving the problem we have because we might need to read it twice.

**Comment by xanscale** [comment]
"we" as "library developer" not as "third-party app developer"

re-made question: which the best way to send to server data behind Uri ?
copy in temp folder is the best way?

**Comment by PaulWoitaschek** [comment]
@xanscale 
Yes, copy it to a `File.createTempFile` and use that.
