### ISSUE TITLE
Revisit Call.cancel() code path that closes connection directly.

### ISSUE THREAD

**Issue by artem-zinnatullin** [square/okhttp#3363]
#### Intro

We're investigating 2 issues with HTTP/2 in our application that uses OkHttp and found few cases when OkHttp creates more TCP connections than practically required which reduces performance of our app, especially on mobile network.

#### Problem

Currently (OkHttp 3.8.0) [can close underlying TCP connection directly](https://github.com/square/okhttp/blob/fad89a786a6a19c78197b417f76bb0087fc95c71/okhttp/src/main/java/okhttp3/internal/connection/StreamAllocation.java#L303) in case of early `Call.cancel()` invocation when connection `codec` is not determined yet which unfortunately does not leave chance to reuse this connection for future requests which is especially sad for HTTP/2 and pretty bad for HTTP/1.1 with keepalive.

In our case we're indirectly calling `Call.cancel()` by unsubscribing (switchMap) from RxJava Observable provided by Retrofit which we need to do because of business specification and thought that it'll be completely fine with HTTP/2 since it should have only close virtual stream inside of real TCP connection.

#### Proposal

Change behavior of `Call.cancel()` or add new version of `Call.cancel()` that won't close underlying TCP socket *directly*. Probably only call `HttpCodec.cancel()` if `codec` is determined otherwise let connection live in `ConnectionPool` which will allow OkHttp to reuse it for future requests or will be closed later.

**Comment by swankjesse** [comment]
Two challenges that make this really difficult:
 * It’ll cause us to put connections in the pool _before_ they’ve made any requests. This might work but it‘s weird.
 * We’ll need to find a way to make the thread asking for the connection interruptible without breaking the connection being created. We could do this with more threads (futures or something) but it’s more code and more mechanism.

I’m going to icebox this for now only to be completely honest about how I prioritize this work!
https://github.com/square/okhttp/pull/3080

**Comment by artem-zinnatullin** [comment]
Both of the outlined challenges sound like good design goals to pursue haha

iceboxing is fair, thanks for being open about it 👍

**Comment by yschimke** [comment]
Won't fix.  I think we should have a different feature for mobile clients, e.g. keeping known warm connections while the app is foregrounded for purely performance critical apps.  But not opening that issue now, but no plans here either.
