### ISSUE TITLE
bug AndroidStudio3.0Preview

### ISSUE THREAD

**Issue by mcxinyu** [square/okhttp#3368]
When I open AndroidStudio3.0Preview in the New Android Profiler function when there is a failure,
Closed to resume.
Probably a preview version of the bug.

![05fd8a70-b368-429c-8a7c-ecccf754888c](https://cloud.githubusercontent.com/assets/9566116/26242243/49faa202-3cba-11e7-8c66-542df4935be9.png)

 - [ ] 05-19 17:20:53.777 15693-15693/com.about.zhiye W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
05-19 17:20:53.778 15693-15693/com.about.zhiye W/System.err:     at com.android.tools.profiler.support.network.OkHttpInterceptorHandler.wrapResponseBody(OkHttpInterceptorHandler.java:108)
05-19 17:20:53.778 15693-15693/com.about.zhiye W/System.err:     at com.android.tools.profiler.support.network.OkHttpInterceptorHandler.wrapResponse(OkHttpInterceptorHandler.java:74)
05-19 17:20:53.778 15693-15693/com.about.zhiye W/System.err:     at com.android.tools.profiler.support.network.OkHttpInterceptorHandler.invoke(OkHttpInterceptorHandler.java:39)
05-19 17:20:53.778 15693-15693/com.about.zhiye W/System.err:     at java.lang.reflect.Proxy.invoke(Proxy.java:393)
05-19 17:20:53.778 15693-15693/com.about.zhiye W/System.err:     at $Proxy0.intercept(Unknown Source)
05-19 17:20:53.778 15693-15693/com.about.zhiye W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
05-19 17:20:53.778 15693-15693/com.about.zhiye W/System.err:     at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
05-19 17:20:53.778 15693-15693/com.about.zhiye W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
05-19 17:20:53.778 15693-15693/com.about.zhiye W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
05-19 17:20:53.778 15693-15693/com.about.zhiye W/System.err:     at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
05-19 17:20:53.778 15693-15693/com.about.zhiye W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
05-19 17:20:53.778 15693-15693/com.about.zhiye W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
05-19 17:20:53.778 15693-15693/com.about.zhiye W/System.err:     at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
05-19 17:20:53.778 15693-15693/com.about.zhiye W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
05-19 17:20:53.778 15693-15693/com.about.zhiye W/System.err:     at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
05-19 17:20:53.778 15693-15693/com.about.zhiye W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
05-19 17:20:53.778 15693-15693/com.about.zhiye W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
05-19 17:20:53.778 15693-15693/com.about.zhiye W/System.err:     at com.about.zhiye.api.ApiRetrofit$1.intercept(ApiRetrofit.java:94)
05-19 17:20:53.778 15693-15693/com.about.zhiye W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
05-19 17:20:53.778 15693-15693/com.about.zhiye W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
05-19 17:20:53.778 15693-15693/com.about.zhiye W/System.err:     at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185)
05-19 17:20:53.778 15693-15693/com.about.zhiye W/System.err:     at okhttp3.RealCall.execute(RealCall.java:69)
05-19 17:20:53.778 15693-15693/com.about.zhiye W/System.err:     at retrofit2.OkHttpCall.execute(OkHttpCall.java:174)
05-19 17:20:53.778 15693-15693/com.about.zhiye W/System.err:     at retrofit2.adapter.rxjava.CallExecuteOnSubscribe.call(CallExecuteOnSubscribe.java:40)
05-19 17:20:53.778 15693-15693/com.about.zhiye W/System.err:     at retrofit2.adapter.rxjava.CallExecuteOnSubscribe.call(CallExecuteOnSubscribe.java:24)
05-19 17:20:53.778 15693-15693/com.about.zhiye W/System.err:     at retrofit2.adapter.rxjava.BodyOnSubscribe.call(BodyOnSubscribe.java:33)
05-19 17:20:53.778 15693-15693/com.about.zhiye W/System.err:     at retrofit2.adapter.rxjava.BodyOnSubscribe.call(BodyOnSubscribe.java:25)
05-19 17:20:53.778 15693-15693/com.about.zhiye W/System.err:     at rx.Observable.unsafeSubscribe(Observable.java:10346)
05-19 17:20:53.779 15693-15693/com.about.zhiye W/System.err:     at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
05-19 17:20:53.779 15693-15693/com.about.zhiye W/System.err:     at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
05-19 17:20:53.779 15693-15693/com.about.zhiye W/System.err:     at rx.Observable.unsafeSubscribe(Observable.java:10346)
05-19 17:20:53.779 15693-15693/com.about.zhiye W/System.err:     at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
05-19 17:20:53.779 15693-15693/com.about.zhiye W/System.err:     at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
05-19 17:20:53.779 15693-15693/com.about.zhiye W/System.err:     at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
05-19 17:20:53.779 15693-15693/com.about.zhiye W/System.err:     at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
05-19 17:20:53.779 15693-15693/com.about.zhiye W/System.err:     at rx.Observable.unsafeSubscribe(Observable.java:10346)
05-19 17:20:53.779 15693-15693/com.about.zhiye W/System.err:     at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.call(OperatorSubscribeOn.java:100)
05-19 17:20:53.779 15693-15693/com.about.zhiye W/System.err:     at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:230)
05-19 17:20:53.779 15693-15693/com.about.zhiye W/System.err:     at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
05-19 17:20:53.779 15693-15693/com.about.zhiye W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
05-19 17:20:53.779 15693-15693/com.about.zhiye W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
05-19 17:20:53.779 15693-15693/com.about.zhiye W/System.err:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
05-19 17:20:53.779 15693-15693/com.about.zhiye W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
05-19 17:20:53.779 15693-15693/com.about.zhiye W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
05-19 17:20:53.779 15693-15693/com.about.zhiye W/System.err:     at java.lang.Thread.run(Thread.java:818)

**Comment by JakeWharton** [comment]
What makes you think this is an OkHttp but vs a tools bug?

**Comment by lidemin** [comment]
I believe this is an Android Studio's bug. It happened to me when app supposed to receive an empty response.

**Comment by JakeWharton** [comment]
Please file on b.android.com

**Comment by daliyan** [comment]
It happened to me when app supposed to receive an empty response.

**Comment by magneticflux-** [comment]
This still occurs on the official 3.0 release. Was this bug ever reported? If so, what is its ID?
