### ISSUE TITLE
Charles breakpoints cause EOFException

### ISSUE THREAD

**Issue by JanithaR** [square/okhttp#3379]
I'm in middle of a Web API migration in my app and I'm using OkHttp. For testing purposes I'm intercepting API results so that I can manipulate them and test if the server responses are handled correctly. This was working fine but suddenly all requests that I intercept using breakpoints are now throwing java.io.EOFException.

```
05-30 12:19:24.240 W/System.err: java.io.EOFException
05-30 12:19:24.241 W/System.err:     at okio.RealBufferedSource.require(RealBufferedSource.java:59)
05-30 12:19:24.241 W/System.err:     at okio.RealBufferedSource.readHexadecimalUnsignedLong(RealBufferedSource.java:284)
05-30 12:19:24.241 W/System.err:     at okhttp3.internal.http1.Http1Codec$ChunkedSource.readChunkSize(Http1Codec.java:444)
05-30 12:19:24.241 W/System.err:     at okhttp3.internal.http1.Http1Codec$ChunkedSource.read(Http1Codec.java:425)
05-30 12:19:24.241 W/System.err:     at okio.RealBufferedSource.request(RealBufferedSource.java:66)
05-30 12:19:24.241 W/System.err:     at okio.RealBufferedSource.rangeEquals(RealBufferedSource.java:387)
05-30 12:19:24.241 W/System.err:     at okio.RealBufferedSource.rangeEquals(RealBufferedSource.java:371)
05-30 12:19:24.242 W/System.err:     at okhttp3.internal.Util.bomAwareCharset(Util.java:412)
05-30 12:19:24.242 W/System.err:     at okhttp3.ResponseBody.string(ResponseBody.java:173)
05-30 12:19:24.242 W/System.err:     at facilit.net.core.webapi.WebApi.workOrderGetList(WebApi.java:200)

```

The above error is thrown from the code but here's what it looks like in [Charles](http://imgur.com/a/tC88N). This happens just by intercepting the response from the server, but it seems fine. I'm not manipulating anything.

I have added most info here. https://stackoverflow.com/questions/44243403/charles-breakpoints-cause-eofexception-and-malformedchunkcodingexception?noredirect=1#comment75517830_44243403

**Comment by JanithaR** [comment]
After some digging around I found these differences in the response header.

This is the header shown in Charles.
```
HTTP/1.1 200 OK
Cache-Control	no-cache
Pragma	no-cache
Content-Type	application/json; charset=utf-8
Expires	-1
Server	Microsoft-IIS/8.5
X-AspNet-Version	4.0.30319
X-Powered-By	ASP.NET
Date	Wed, 31 May 2017 03:42:34 GMT
Content-Length	23461
```

I have used an interceptor and this is the header shown by OkHttp.


                             ```
Cache-Control: no-cache
                             Pragma: no-cache
                             Content-Type: application/json; charset=utf-8
                             Expires: -1
                             Server: Microsoft-IIS/8.5
                             X-AspNet-Version: 4.0.30319
                             X-Powered-By: ASP.NET
                             Date: Wed, 31 May 2017 03:35:13 GMT
                             Transfer-Encoding: chunked
                             Proxy-Connection: Keep-alive
```

Content-Length has been stripped out and Transfer-Encoding is there which is not the actual response from the server.

**Comment by swankjesse** [comment]
Is this a Charles bug? Not sure what action to take in OkHttp.

**Comment by JanithaR** [comment]
Hey, it seems so. I started using ZAP and works as expected. It took quite an effort to figure out Charles was the culprit. If someone else also run into this problem, I'm not quite sure what started causing the misbehaving header edits by Charles.

**Comment by swankjesse** [comment]
No action for us to take on this.
