### ISSUE TITLE
Feature Request : Configurable Connection Pool Thread Setting

### ISSUE THREAD

**Issue by khannedy** [square/okhttp#3380]
We have a problem with okhttp, currently we want to implement 1 okhttpclient per service, there are so many services in our system, for example my app want to connect to 5 services, and we create 5 okhttpclient object. we want to use different configuration for each okhttpclient, for example timeout and threadpool size.

we can see in this code  

https://github.com/square/okhttp/blob/master/okhttp/src/main/java/okhttp3/ConnectionPool.java#L50

because threadpool setting hardcoded, so we can not change the threadpool configuration.

configurable threadpool setting is needed for backpressure, so if the service too slow, we can reject the request automatically in okhttpclient.

**Comment by crystalfan** [comment]
you can compile source code and modified any parameter for your project

**Comment by khannedy** [comment]
@crystalfan that's not a solution

**Comment by swankjesse** [comment]
That thread pool size is not a tuning parameter; it’s just how many threads OkHttp spends garbage collecting old connections. There’s no utility to changing that configuration.

**Comment by menih** [comment]
Problem becomes more relevant when reusing third party which uses OkHttp and cannot even expose that level of control to whomever uses them. For those users, modifying the original code is not an option.
