### ISSUE TITLE
Feature request: First class support for authority in httpurl

### ISSUE THREAD

**Issue by ayush-veem** [square/okhttp#3381]
What kind of issue is this?
    Feature Request

Have a project with config values in the form of host:port and just host (based on env) and it would be convenient to be able to do something like builder.scheme("http").authority(<string>).build()

**Comment by swankjesse** [comment]
There’s a few unsatisfying options here. The closest we could come would be accepting an `InetSocketAddress` to set both the hostname and port in one go. But that class sometimes has both a hostname and an IP address, and we aren’t going to pick the option most people will like.

If we pick the IP address we’re broken for SNI. If we pick the hostname we waste a DNS call resolving the IP address later.

My preference is to make this the caller’s responsibility, and they know whether they want the string hostname or the IP address, or whatever.

**Comment by swankjesse** [comment]
For your usecase I recommend just doing something like this:
```
 HttpUrl.parse("http://" + authority)
```
That doesn’t require much code and it does the right thing.

**Comment by ayush-veem** [comment]
Why not a simple wrapper class given that authority is just defined as user + password + host + port? Seems like the builder .authority would accept either the wrapper or a string (and both will have to be parsed/validated anyway).

**Comment by yschimke** [comment]
Won't fix.
