### ISSUE TITLE
Response.close() nullability issue.

### ISSUE THREAD

**Issue by Tolriq** [square/okhttp#3383]
Not a big deal, but since OkHttp now returns much more nullable / not nullable things I found that I missed some cases handling in my code.

And this lead to seeing that Response.close() directly calls body.close() with body that can be null and not tested.

The function should maybe either be marked as possible NPE throw or test for null body for completeness.

**Comment by swankjesse** [comment]
We could throw an IllegalStateException instead. Applications shouldn't ever attempt to close the response returned from a `cacheResponse()` or `networkResponse()`.

**Comment by Tolriq** [comment]
Not sure to understand

From code https://github.com/square/okhttp/blob/c70e35802e984e8b9bf3fbf1479deb37c0bdfa43/okhttp/src/main/java/okhttp3/Response.java#L274

Response.close() correctly only deals with body (ResponseBody) and does not touch the others.

Finally maybe I'm wrong but in the end just adding a body != null check sound like the proper handling as there's no real error to manage in fact, a Closeable should not NPE on close.

**Comment by swankjesse** [comment]
It's an error to attempt to close a response that doesn't have a body.

**Comment by gilday** [comment]
> It's an error to attempt to close a response that doesn't have a body.

@swankjesse how strongly do you hold this opinion? If this were not an error condition, then users could use `Response` in a try-with-resources statement in scenarios where the body is not considered. Take this example which checks for a successful status code and ignores the body

```java
Response response = null;
try {
  response = client.newCall(request).execute();
  if (!response.isSuccessful()) {
    throw new IllegalStateException("HTTP server returned error code " + response.code());
  }
} finally {
  if (response != null && response.body() != null) {
    response.close();
  }
}
```

If this code didn't need to first check `response.body != null` to avoid an error condition, then we could get rid of boilerplate with a try-with-resources statement.

```java
try(Response response = client.newCall(request).execute()) {
  if (!response.isSuccessful()) {
    throw new IllegalStateException("HTTP server returned error code " + response.code());
  }
}
```

**Comment by swankjesse** [comment]
Your example above is safe. You have to try hard to get a response without a body – it’s the response used by `Response.networkResponse()` or `Response.cacheResponse()`.

**Comment by gilday** [comment]
Cool, that helps. I was running into trouble in a unit test where I was building a `Response` myself and I omitted the body e.g.

```java
    final Response response =
        new Response.Builder()
            .request(success.request())
            .protocol(Protocol.HTTP_1_1)
            .message("OK")
            .code(204)
            .build();
```

but I can fix this by adding an empty body to the builder chain and remain confident that for my use case responses should always have a non-null body.

```java
.body(EMPTY_RESPONSE)
```

thanks!
