### ISSUE TITLE
Request - Allow content type to be different from request type

### ISSUE THREAD

**Issue by roarapps** [square/okhttp#3385]
Hello,

At the moment I do a multipart.FORM request which allows me to send an image to the server. I require the response to be interpreted as JSON.

I've tried to create a request body by passing in the JSON content type but that seems to have no effect.

In iOS for AFNetworking, this can be achieved by the following - manager.responseSerializer = [AFJSONResponseSerializer serializer];

is it possible to get something similar in okhttp?

**Comment by swankjesse** [comment]
It's already supported. If you'd like more support, please ask on StackOverflow.
