### ISSUE TITLE
After building an OkHttpClent, how to modify its setting

### ISSUE THREAD

**Issue by Leaking** [square/okhttp#3388]
For example, i use builder to create a OkHttpClient as the below codes, but how can i modify its property such as 'readTimeout'. Maybe some requests set 'readTimeout' as 10 seconds and some requests set 'readTimeout' as 20 seconds.
 
```
OkHttpClient eagerClient = client.newBuilder()
       .readTimeout(500, TimeUnit.MILLISECONDS)
       .build();
```

**Comment by NightlyNexus** [comment]
Consider subscribing to https://github.com/square/okhttp/issues/3039.
