### ISSUE TITLE
Feature Request: Multipart Response

### ISSUE THREAD

**Issue by sammefford** [square/okhttp#3394]
I'm currently using JavaMail to parse multipart responses since I can't see a way to do that with OkHttp.  However, it appears that JavaMail parses the response as a single payload rather than allowing streaming.  I say this because javax.mail.internet.Multipart only offers getCount() and getBodyPart(int index) to walk through the parts, rather than an iterator or async API.  I'd like a way to work on parts as they come in, to support streaming response processing.  That would allow processing very large responses without requiring outrageous amounts of JVM memory.  Ideally, each part would of course be available once its headers are available, so we could also stream each part as it comes in (in case one part is too large to fit in memory).  So my feature request is that OkHttp support Multipart Responses, and do it in a way to support streaming (processing each part as it arrives).

**Comment by swankjesse** [comment]
Yep, being able to decode a multipart body would be really nice.

We’ve got this plan for a thing “OkHttp 4” which would have a single type for RequestBody and ResponseBody. If we do that, it would be handy for our `MultipartBody` class to be able to decode its content. That’s also useful for testing clients!

**Comment by swankjesse** [comment]
Its been almost 3 years but it’s done!

**Comment by sayan-chaliha** [comment]
Hello @swankjesse! Took me a lot of digging to find this thread :) ... do you have any code samples on how to parse multipart responses (basically I’m using HTTP range requests with OkHttp3 and I get multiple ranges in one response)?

**Comment by swankjesse** [comment]
@sayan-chaliha try this: https://square.github.io/okhttp/4.x/okhttp/okhttp3/-multipart-reader/

**Comment by HPSudip** [comment]
Hi @swankjesse is it possible to create http responses of Content-Type: Multipart/Related;, by using OkHttp ?
