### ISSUE TITLE
I wan to 

### ISSUE THREAD

**Issue by qq690712575** [square/okhttp#3396]
What kind of issue is this?

I want to get a cookie is ASP.NET_SessionId ,but there is a problem[header]
Server: Tengine/2.1.1
Date: Sat, 10 Jun 2017 19:00:09 GMT
Content-Type: text/html; charset=gb2312
Transfer-Encoding: chunked
Connection: keep-alive
X-Powered-By: ASP.NET
X-AspNet-Version: 1.1.4322
Set-Cookie: ASP.NET_SessionId=y1j5ob45vowusoqgwuh0qliq; path=/
Cache-Control: private
Set-Cookie: route=1e20206b82f84f04622e1280ba6c03d3;Path=/

[code]
  System.out.println("header="+response.header("Set-Cookie"));
[Output result]:
header=route=1e20206b82f84f04622e1280ba6c03d3;Path=/

**Comment by swankjesse** [comment]
Please use StackOverflow for usage questions.
