### ISSUE TITLE
OkUrlFactory is deprecated, so should I continue using OkHttpURLConnection?

### ISSUE THREAD

**Issue by Leaking** [square/okhttp#3397]
As Jesse Wilson mentioned here, OkUrlFactory is deprecated. Does it means that the whole library [okhttp-urlconnection](https://github.com/square/okhttp/tree/master/okhttp-urlconnection) will be deprecated..

Should I continue using OkHttpURLConnection. For example, I want to open a connection based on okhttp implement like the following codes

```java
public static HttpURLConnection open(@NonNull URL url) {
        OkHttpClient commonOkHttpClient = new OkHttpClient().newBuilder().build();
        return new OkHttpURLConnection(url, commonOkHttpClient);
}
```

**Comment by swankjesse** [comment]
Nothing in the `internal` package is intended for use by application developers. That entire package does not promise a stable API, even between minor releases.

Upgrade to the Request/Response API.
