### ISSUE TITLE
when I proguard in android app , crash issues , connect closed!

### ISSUE THREAD

**Issue by JackLiaoJH** [square/okhttp#3407]
06-15 00:03:14.893 3503-3930/? W/System.err: java.lang.IllegalStateException: closed
06-15 00:03:14.894 3503-3930/? W/System.err:     at okio.RealBufferedSource.read(Unknown Source)
06-15 00:03:14.894 3503-3930/? W/System.err:     at okio.ForwardingSource.read(Unknown Source)
06-15 00:03:14.894 3503-3930/? W/System.err:     at retrofit2.aw.read(Unknown Source)
06-15 00:03:14.894 3503-3930/? W/System.err:     at okio.RealBufferedSource.request(Unknown Source)
06-15 00:03:14.894 3503-3930/? W/System.err:     at okio.RealBufferedSource.rangeEquals(Unknown Source)
06-15 00:03:14.894 3503-3930/? W/System.err:     at okio.RealBufferedSource.rangeEquals(Unknown Source)
06-15 00:03:14.894 3503-3930/? W/System.err:     at okhttp3.internal.Util.bomAwareCharset(Unknown Source)
06-15 00:03:14.894 3503-3930/? W/System.err:     at okhttp3.ResponseBody$BomAwareReader.read(Unknown Source)
06-15 00:03:14.894 3503-3930/? W/System.err:     at com.google.gson.stream.JsonReader.fillBuffer(Unknown Source)
06-15 00:03:14.894 3503-3930/? W/System.err:     at com.google.gson.stream.JsonReader.nextNonWhitespace(Unknown Source)
06-15 00:03:14.894 3503-3930/? W/System.err:     at com.google.gson.stream.JsonReader.doPeek(Unknown Source)
06-15 00:03:14.894 3503-3930/? W/System.err:     at com.google.gson.stream.JsonReader.peek(Unknown Source)
06-15 00:03:14.894 3503-3930/? W/System.err:     at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(Unknown Source)
06-15 00:03:14.894 3503-3930/? W/System.err:     at com.shop7.net.gson.GsonResponseBodyConverter.convert(Unknown Source)
06-15 00:03:14.894 3503-3930/? W/System.err:     at com.shop7.net.gson.GsonResponseBodyConverter.convert(Unknown Source)
06-15 00:03:14.894 3503-3930/? W/System.err:     at retrofit2.g.c(Unknown Source)
06-15 00:03:14.894 3503-3930/? W/System.err:     at retrofit2.ax.a(Unknown Source)
06-15 00:03:14.894 3503-3930/? W/System.err:     at retrofit2.ax.a(Unknown Source)
06-15 00:03:14.894 3503-3930/? W/System.err:     at com.jakewharton.retrofit2.adapter.rxjava2.b.a(Unknown Source)
06-15 00:03:14.894 3503-3930/? W/System.err:     at io.reactivex.a.b(Unknown Source)
06-15 00:03:14.894 3503-3930/? W/System.err:     at com.jakewharton.retrofit2.adapter.rxjava2.d.a(Unknown Source)
06-15 00:03:14.894 3503-3930/? W/System.err:     at io.reactivex.a.b(Unknown Source)
06-15 00:03:14.894 3503-3930/? W/System.err:     at io.reactivex.internal.operators.observable.f.run(Unknown Source)
06-15 00:03:14.894 3503-3930/? W/System.err:     at io.reactivex.j.run(Unknown Source)
06-15 00:03:14.894 3503-3930/? W/System.err:     at io.reactivex.internal.schedulers.ScheduledRunnable.run(Unknown Source)
06-15 00:03:14.894 3503-3930/? W/System.err:     at io.reactivex.internal.schedulers.ScheduledRunnable.call(Unknown Source)
06-15 00:03:14.894 3503-3930/? W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
06-15 00:03:14.894 3503-3930/? W/System.err:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
06-15 00:03:14.894 3503-3930/? W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
06-15 00:03:14.894 3503-3930/? W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
06-15 00:03:14.894 3503-3930/? W/System.err:     at java.lang.Thread.run(Thread.java:761)

**Comment by swankjesse** [comment]
This issue isn’t actionable. Please provide an executable test case.
