### ISSUE TITLE
Unable to release OkHttp ConnectionPool thread.

### ISSUE THREAD

**Issue by sewak2610** [square/okhttp#3409]
Release Unused Resources.

  evictAll from connectionPool and cancelAll from dispatchers dosen't release the OkHttpConnectionPool thread. The OkHttp ConnectionPool are stacking up for me. want to release this.
Is this any kind of bug.?

Here is the stackflow link as you said tag with okhttp.
https://stackoverflow.com/questions/44551090/how-can-release-unused-resource-thread-okhttp-connectionpool-in-okhttp

**Comment by swankjesse** [comment]
Thanks for posting on StackOverflow.

**Comment by Jiayi-Liao** [comment]
@sewak2610 @swankjesse  Hi, I've encountered the same problem recently. Do you have any updates here? I didn't find the answer on the above StackOverflow link.
