### ISSUE TITLE
Implement Request.equals

### ISSUE THREAD

**Issue by alokmenghrajani** [square/okhttp#3416]
What kind of issue is this?

 - [X] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
       already exists! Don’t send pull requests to implement new features without first getting our
       support. Sometimes we leave features out on purpose to keep the project small.

I'm trying to write a test using Mockito, and my test looks something like:
`when(mock.newCall(some_request).execute()).thenReturn(some_response);`.

This however does not work. Adding an `equals` method to Request (and its members, e.g. RequestBody) would enable mocking. My understanding is that Request could fit the "value class" model.

**Comment by JakeWharton** [comment]
See #2773

**Comment by alokmenghrajani** [comment]
❤️  for quick response. 😢 for not being able to mock.
