### ISSUE TITLE
Use UTF-8 as Charset for Credentials, ISO-8859-1 is failing with umlauts (e.g ö)

### ISSUE THREAD

**Issue by androideo** [square/okhttp#3417]
I switched my HTTPClient from okhttp-urlconnection okhttp-client. After some days after the release a customer could not make any valid requests anymore. After a long time i realized that Credentials of okhttp 3 is not using UTF-8 for BasicAuth. The problem arised through having an 'ö' in the password. 

After having a look in "java.nio.charset" i realized that all android libraries are using UTF-8

> Android note: The Android platform default is always UTF-8.

Not sure if switching is the best way, but i took me a lot of time.

**Comment by feichngr** [comment]
I also was not aware of thie until now.
From a quick Google search I figure that utf-8 support and encoding in basic auth is not very well supported or standardized.
Maybe adding hints in JavaDoc would be helpful, to `Credentials.basic(String, String)`'s for its default charset and to `Credentials.basic(String, String, Charset)`'s that it won't go out of its way to encode other charsets in an RFC 2047 or whatever standard way.

**Comment by swankjesse** [comment]
We’ve been sitting on a PR for this. Needs attention. 
https://github.com/square/okhttp/pull/3144

**Comment by swankjesse** [comment]
Duplicate of https://github.com/square/okhttp/issues/1468
