### ISSUE TITLE
Default Cookie Policy

### ISSUE THREAD

**Issue by okarakose** [square/okhttp#3418]
OkHttp does not handling cookies with default implementation. We need to integrate with okhttp-urlconnection to add cookie policy.

    compile "com.squareup.okhttp3:okhttp-urlconnection:3.8.1"

and then setCookieManager

    OkHttpClient.Builder clientBuilder = new OkHttpClient.Builder();

    CookieManager cookieManager = new CookieManager(null, 
    CookiePolicy.ACCEPT_ORIGINAL_SERVER);
    clientBuilder.cookieJar(new JavaNetCookieJar(cookieManager));

When server sent Set-Cookie parameter in response header, I think it should be automatically added for next requests by OkHttp. 

What is the reason of OkHttp does not accept cookies automatically ?

**Comment by swankjesse** [comment]
Persistence is hard and we haven’t implemented anything yet.
