### ISSUE TITLE
[bug] If proxy authentication user or password are wrong, on HTTPS, current thread blocks in an infinite loop.

### ISSUE THREAD

**Issue by smatei** [square/okhttp#3423]
If one tries to navigate to a HTTPS page using a proxy authentication, and the user or password for the proxy are wrong, infinite loop occurs. The code to duplicate this is simple:

`	package testOKHTTP;
	
	import java.io.IOException;
	import java.net.InetSocketAddress;
	import java.net.Proxy;
	import java.util.Arrays;
	import java.util.concurrent.TimeUnit;
	
	import okhttp3.Authenticator;
	import okhttp3.Call;
	import okhttp3.Credentials;
	import okhttp3.OkHttpClient;
	import okhttp3.Protocol;
	import okhttp3.Request;
	import okhttp3.Response;
	import okhttp3.Route;
	
	public class testok
	{
	  void run(String url) throws IOException {
	    String proxy = "137.74.248.8";
	    int port = 3128;
	    final String user = "blabla";
	    final String password = "titimimi";
	
	    Authenticator proxyAuthenticator = new Authenticator() {
	      public Request authenticate(Route route, Response response) throws IOException {
	           String credential = Credentials.basic(user, password);
	           return response.request().newBuilder()
	               .header("Proxy-Authorization", credential)
	               .header("User-Agent", "Mozilla/5.0 (Windows NT 6.2; WOW64; rv:44.0) Gecko/20100101 Firefox/44.0")
	               .build();
	      }
	    };
	    
	    OkHttpClient client = new OkHttpClient.Builder()
	        .protocols(Arrays.asList(Protocol.HTTP_2, Protocol.HTTP_1_1, Protocol.SPDY_3))
	        .connectTimeout(20, TimeUnit.SECONDS)
	        .writeTimeout(20, TimeUnit.SECONDS)
	        .readTimeout(20, TimeUnit.SECONDS)
	        .proxy(new Proxy(Proxy.Type.HTTP, new InetSocketAddress(proxy, port)))
	        .proxyAuthenticator(proxyAuthenticator)
	        .build();
	    
	    Request request = new Request.Builder()
	        .url(url)
	        .header("User-Agent", "Mozilla/5.0 (Windows NT 6.2; WOW64; rv:44.0) Gecko/20100101 Firefox/44.0")
	        .header("Accept", "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8")
	        .header("Accept-Language", "en-US,en;q=0.5")
	        .header("Accept-Encoding", "gzip, deflate")
	        .header("Cookie", "NID=77=tJ2mqhkopJG8tterOLf9RoQT5wIXF76XgEsmUgc4UnRbEktrsG4UOPKIeWhu58nkQPaQDoRNucdJAhCeTQoBmsaUJusiPrSlN5mwPltG7iM01tb2__RITDwGrBK1wC5BGsF8ibXa_r7zhg;")        
	        .header("Connection", "keep-alive")
	        .build();
	
	    final Call call = client.newCall(request);
	    
	    Response response = call.execute();
	        
	    System.out.println("XXXXXXXXXXXXXXXXXXXX response: " + response.code());
	  }
	
	  public static void main(String[] args) throws IOException {
	    System.out.println(System.getProperty("java.runtime.version"));
	    System.out.println(System.getProperty("java.endorsed.dirs"));
	
	    testok example = new testok();
	    
	    example.run(
	        //"http://localhost/phpinfo.php"
	        //"https://www.google.com/"
	        "https://www.advancedwebranking.com/"
	        /*"https://whatsmyuseragent.com/"*/);    
	  }
	  
	}
	

`

This fills the proxy server log with 407

1498207186.367      0 82.79.222.141 TCP_DENIED/407 4275 CONNECT www.advancedwebranking.com:443 blabla HIER_NONE/- text/html
	1498207186.416      0 82.79.222.141 TCP_DENIED/407 4275 CONNECT www.advancedwebranking.com:443 blabla HIER_NONE/- text/html
	1498207186.465      0 82.79.222.141 TCP_DENIED/407 4275 CONNECT www.advancedwebranking.com:443 blabla HIER_NONE/- text/html

And the thread is blocked forever in a loop reading from socket (see profiler attached picture)
![loop](https://user-images.githubusercontent.com/17740806/27474247-6f1f1002-580a-11e7-96ff-414ca34670bd.jpg)

I will take a look at the code, maybe I can break the loop and get the 407 response.

**Comment by Tolriq** [comment]
https://github.com/square/okhttp/wiki/Recipes#handling-authentication explains how to avoid infinite retries no?

**Comment by smatei** [comment]
@Tolriq Thank you! I have fixed it like this. 

`	   
        Authenticator proxyAuthenticator = new Authenticator() {
               public Request authenticate(Route route, Response response) throws IOException {
                 if (response != null && response.code() == 407)
	    	     {
                   return null;
                 }
	    	  
	           String credential = Credentials.basic(user, password);
	           return response.request().newBuilder()
	               .header("Proxy-Authorization", credential)
	               .header("User-Agent", "Mozilla/5.0 (Windows NT 6.2; WOW64; rv:44.0) Gecko/20100101 Firefox/44.0")
	               .build();
	      }
	    };

`

This throws java.io.IOException: Failed to authenticate with proxy.
