### ISSUE TITLE
Thoughts on EventListener

### ISSUE THREAD

**Issue by yschimke** [square/okhttp#3427]
I tried implementing a simple logging EventListener and had some thoughts about it

https://github.com/yschimke/oksocial/pull/244/files

1.  Since I needed to store start times e.g. dns, connect, it was a lot more natural to have a EventListener.Factory and a request scoped EventListener instance
2. This made the call parameter on each invocation redundant
3. Should protocol be a Protocol enum value instead of a string?
4. Should connectEnd get given a InetSocketAddress instead of InetAddress + port
5. Not receiving the Response seems a bit asymmetric, same for Headers.

**Comment by yschimke** [comment]
Expanding on 1&2

Either your listener is stateless - in which case each redundant copy is as cheap as a new Object(), e.g. noise in overall request execution.

or

listener is stateful and the API suggests you should have internal Map<Call, State> which is actually not the best pattern.

**Comment by yschimke** [comment]
Also connectStart vs secureConnectStart threw me as I thought it was plaintext vs TLS.  I now realise connectStart is socket connect, and secureConnectStart is TLS handshake. 

Like reusing a TLS session, we might need something to indicate that an existing socket to this host/port was used.

**Comment by yschimke** [comment]
cc @dave-r12

**Comment by dave-r12** [comment]
I'm looking at the connect start/end and have a few similar reactions.

**Comment by yschimke** [comment]
I implemented a few more events at test quality, feel free to steal these diffs as a starting point but I was only concerned about obvious cases, not websocket continues etc.

https://github.com/square/okhttp/compare/master...yschimke:events?expand=1

Anyway, let me to a few more questions

1. What is the expected treatment of a client slow reading a response?  Does the call finish for the listener API when the caller has a response, or when they close the response body?
2. What is fetchStart, fetchEnd meant to represent? For an enqueued job that might be delayed waiting for a thread, is there an event for the job being enqueued? I'm currently assuming these are equivalent to the outer most application interceptors being called.
3. Should there be a networkRequestStart/End that are synonyms for requestHeadersStart and responseBodyEnd.  Essentially equivalent to the inner most network interceptor.
4. How to access response code e.g. 404?
5. It's awkward to cleanly link together a start and end call currently, except for (trivially) accounting for start, end, start, end.   It's slightly more awkward with connectionFound also, although I think that relates to the bug I mentioned on the PR.

cc @dave-r12

**Comment by swankjesse** [comment]
Maybe rename `connectionFound` to `connectionAcquired` and add `connectionReleased` ? Only challenge there is that with Happy Eyeballs we might hold multiple connections concurrently. Theey won’t necessarily nest right.

**Comment by yschimke** [comment]
https://github.com/square/okhttp/pull/3475
