### ISSUE TITLE
Use linux system proxy

### ISSUE THREAD

**Issue by devnewton** [square/okhttp#3439]
It would be great if okhttp automatically use linux system proxy environnement variables usually found in /etc/environnement:

http_proxy="http://user:password@myproxy:3128"
https_proxy="http://user:password@mysecureproxy:3128"
 auto_proxy="http://myproxyconfserver/myconf.pac"

**Comment by yschimke** [comment]
Especially for the last one with a PAC file I think you want to use an existing library e.g. https://github.com/MarkusBernhardt/proxy-vole/

n.b. I haven't tested this

```
import com.github.markusbernhardt.proxy.ProxySearch;
import java.net.ProxySelector;

public class XDF {
  public static void main(String[] args) {
    ProxySearch x = ProxySearch.getDefaultProxySearch();
    ProxySelector.setDefault(x.getProxySelector());
  }
}
```

**Comment by swankjesse** [comment]
No action for us to take on this.
