### ISSUE TITLE
SSL Certificate Pinning with different port

### ISSUE THREAD

**Issue by kumar-cherry** [square/okhttp#3440]
I did certificate pinning with my android application , i try to connect with our production server i got expected result with man-in-the-middle not possible. production api look like _https://one.host.com/api_ , we try to connect with test server same certificate api look like _https://one.host.com:9443/api_ this requets is allow man-in-the-middle attack.

**Comment by swankjesse** [comment]
Don’t run untrusted applications on your own domains. Certificate pinning does not defend against this.
