### ISSUE TITLE
concurrent http2 request performance bad

### ISSUE THREAD

**Issue by NormanOu** [square/okhttp#3442]
I'm testing the multithread performance of okhttp. The strategy is to request for 180 images at the same time, just like what is doing in this website. https://http2.golang.org/gophertiles?latency=0
The performance result with okhttp of http2 is almost the same as the performance of http1.1, which is much slower than the performance of the browser on my phone.

I tcpdump the requests of these two test(okhttp with http2 and browser(chrome) with http2), found out something interesting.
1. first, both okhttp and chrome use one tcp channel to finish requesting all the 180 images. (which is correct with my understanding of http2)
2. but the difference is that, chrome would have most of the request sent in the early seconds, while okhttp send the requests evenly. The traffic diagram is shown as follows. Notice that chrome takes 3.2s to finish while okhttp takes 14s to finish.

chrome up
![chrome_up](https://user-images.githubusercontent.com/1645891/27759746-c50ad8dc-5e6a-11e7-87db-ba91c0f71ace.jpg)
chrome down
![chrome_down](https://user-images.githubusercontent.com/1645891/27759747-d128c318-5e6a-11e7-8a0d-ce7a37e79159.jpg)
okhttp up
![okhttp_up](https://user-images.githubusercontent.com/1645891/27759748-d2ef0810-5e6a-11e7-8378-53d4cf826459.jpg)
okhttp down
![okhttp_down](https://user-images.githubusercontent.com/1645891/27759749-d43d9e2a-5e6a-11e7-94c1-2a836009e210.jpg)

**Comment by swankjesse** [comment]
What does the calling code look like?

**Comment by NormanOu** [comment]
OkHttpClient client = builder.build();
        for (int i = 0; i < count; i++) {
            int x = i / 12;
            int y = i % 12;
            String thisUrl = urlReal;
            thisUrl = thisUrl.replace("x=5", "x=" + x);
            thisUrl = thisUrl.replace("y=5", "y=" + y);
            runTestwithEnqueue(thisUrl, client, latch);
        }

    private void runTestwithEnqueue(String url, OkHttpClient client, final CountDownLatch latch) {
        Request request = new Request.Builder()
                .url(url)
                .build();
        final long startMillies = SystemClock.elapsedRealtime();
        final AtomicBoolean done = new AtomicBoolean(false);

        client.newCall(request).enqueue(new Callback() {
            @Override
            public void onFailure(Call call, IOException e) {
                if (!done.getAndSet(true)) {
                    latch.countDown();
                }
            }

            @Override
            public void onResponse(Call call, Response response) throws IOException {
                if (!done.getAndSet(true)) {
                    latch.countDown();
                }
                String result = response.body().string();
                response.close();
            }
        });
    }

**Comment by NormanOu** [comment]
I read some of the source code and found something.
1. In Dispatcher there's a maxRequestsPerHost limiting 5 Call of same host at the same time.
2. In RealCall AsyncCall.excute, I see call is mark finished only when response is got. So the 6th request can only be send out after the first response is back... and so on.
3. I use "client.dispatcher().setMaxRequestsPerHost(250);" then the speed is boost up, but the down side is much more(about 50-60) tcp channel is created. (and besides, without setting 250, the tcp channel created is 5. and I noticed chrome will only create one or two tcp channel)

any suggestions?

**Comment by yschimke** [comment]
Can you send a single warmup request first?  

OkHttp will allow all concurrent requests to proceed as it doesn't know if server support http/2.  The 5 concurrent initial requests all have a tcp connection.  However when they establish a connection, 4 of them are immediately closed and all requests go over a single h2 connection.

**Comment by NormanOu** [comment]
@yschimke yes, I tried setMaxRequestsPerHost(1), and then after i got the first response back, i setMaxRequestsPerHost(50) to a larger value. now there's only one tcp channel. 
But I still worry about the 50 threads running at the same time. would it be a little to much?

**Comment by swankjesse** [comment]
We should make sure connection coalescing is working in these cases. That should put all HTTP/2 traffic on the same socket, though multiple sockets will still be created.

50 threads shouldn't be a problem. Maybe try 100. I suspect beyond that you'll see diminishing returns.

**Comment by NormanOu** [comment]
I think connection coalescing is working fine. But I don't understand "diminishing returns" means. 
Now what I'm using is "warmup request" first, and then setMaxRequestsPerHost() to a larger value to boost the speed up. Is this the suggested way?

**Comment by yschimke** [comment]
I think he meant that assuming there is a maximum practical limit, e.g. 100kb/s network.  Then as you increase max requests per host you might get close to that maximum.  At some point you are near the maximum and increasing further gives almost no benefit and may actually start to hurt performance.

fake example:
1 concurrent request = 10kb/s
2 concurrent request = 20kb/s
5 concurrent request = 40kb/s
10 concurrent request = 80kb/s
50 concurrent request = 90kb/s
100 concurrent request = 80kb/s

**Comment by swankjesse** [comment]
No further action to take on this. Hooray for our connection coalescing!

**Comment by markzhai** [comment]
@NormanOu Have you got any conclusion? We met the same problem that when we use okhttp to load all images in https://http2.akamai.com/demo, it is very slow, while we use network embeded in android chrome, it is 5-7 times faster

**Comment by NormanOu** [comment]
@markzhai I think it's an architecture issues. the walk around is to use the setMaxRequestsPerHost trick.

**Comment by markzhai** [comment]
@NormanOu Yes, I found this as well. Did you meet any other problems after set that ? I sometimes blocked in the last several requests when using http/1.1 after setMaxRequestsPerHost to 100

**Comment by jafesch** [comment]
Has this issue been resolved? I'm builiding a map app, which downloads many images, and okhttp still seems to be much slower than when i send the same requests in a web browser.

I tried the setMaxRequestsPerHost trick. Didn't work for me though.

Am I doing something wrong?
`OkHttpClient client = new OkHttpClient.Builder()
                .retryOnConnectionFailure(true)
                .build();

for (final DownloadTask task : allTasks) {
    OkHttpRequestBuilderAdapter requestBuilder = new OkHttpRequestBuilderAdapter();
    task.buildRequest(requestBuilder);

    client.newCall(requestBuilder.build())
            .enqueue(new RequestCallback(client, task));
}`

**Comment by icespring** [comment]
okhttp4.x still has this issue

**Comment by tiwariashish86** [comment]
is there any update on this? I am sending warm up request and setting setMaxRequestsPerHost to 50. then when tried downloading images, Http/2 seems to be much slower than Http1.1

**Comment by wisdomtl** [comment]
> is there any update on this? I am sending warm up request and setting setMaxRequestsPerHost to 50. then when tried downloading images, Http/2 seems to be much slower than Http1.1

Maybe the head-of-line blocking of Http/2 is the reson why single tcp connection is slower than Http/1.1 with multiple tcp connections

**Comment by wisdomtl** [comment]
http/2 is not a good choice for the concurrent image loading.
I make a test, loading 20 image with Glide (replace HttpUrlConnection with OkHttp). OkHttp with http/2 is 3 times slower than HttpUrlConnection. then i change the protocol with OkHttp to http/1.1, the speed is the same with HttpUrlConnection.

**Comment by yschimke** [comment]
There are a lot of factors here, including load balancing https://github.com/square/okhttp/issues/4530

Without that you are likely hitting a single origin server, (depends on how the host is setup with reverse proxy etc).  So it's quite possible that it's limited to some number of concurrent requests.  In addition to limitations on the client.

Is this from a benchmark, or affecting common usage of a mobile app? I mean are you regularly loading 50 images concurrently without caching or other mechanisms to speed things up.  Just wondering whether it's worth implementing some workarounds, or it's more flagging one of the downsides of HTTP/2 without load balancing.

**Comment by wisdomtl** [comment]
> There are a lot of factors here, including load balancing #4530
> 
> Without that you are likely hitting a single origin server, (depends on how the host is setup with reverse proxy etc). So it's quite possible that it's limited to some number of concurrent requests. In addition to limitations on the client.
> 
> Is this from a benchmark, or affecting common usage of a mobile app? I mean are you regularly loading 50 images concurrently without caching or other mechanisms to speed things up. Just wondering whether it's worth implementing some workarounds, or it's more flagging one of the downsides of HTTP/2 without load balancing.

The test i made is a benchmark. 

The test is loading 20 images concurrently. The host of image url is the same, i did it purposely, in order for only one connection in OkHttp. I want to figure out which one is faster, HttpUrlConnection or OkHttp.

I will share the testing code as following:

```kotlin
class GlideActivity3 : AppCompatActivity() {
    private lateinit var lf: LineFeedLayout
    // 20 images
    private val images = listOf(
        "https://gimg2.baidu.com/image_search/src=http%3A%2F%2Fppt.chnlib.com%2FFileUpload%2F2018-11%2F7-Cai_Se_Re_1i_1iu_Gao-110740_129.png&refer=http%3A%2F%2Fppt.chnlib.com&app=2002&size=f9999,10000&q=a80&n=0&g=0n&fmt=auto?sec=1654343732&t=06d9d1091d3bf3ff9211e0cb27e0afe0",
        "https://gimg2.baidu.com/image_search/src=http%3A%2F%2Fimg.51miz.com%2FElement%2F00%2F84%2F05%2F33%2Fb07322b0_E840533_bf6a953e.png%21%2Fquality%2F90%2Funsharp%2Ftrue%2Fcompress%2Ftrue%2Fformat%2Fpng&refer=http%3A%2F%2Fimg.51miz.com&app=2002&size=f9999,10000&q=a80&n=0&g=0n&fmt=auto?sec=1654343749&t=cacd1263d9232c376e3b59f5eb4b3254",
        "https://gimg2.baidu.com/image_search/src=http%3A%2F%2Fimage101.360doc.com%2FDownloadImg%2F2016%2F11%2F0111%2F83510768_1.png&refer=http%3A%2F%2Fimage101.360doc.com&app=2002&size=f9999,10000&q=a80&n=0&g=0n&fmt=auto?sec=1654343763&t=a106fc9fea3c3b62cf271947a6ade37f",
        "https://gimg2.baidu.com/image_search/src=http%3A%2F%2Fbbsfiles.vivo.com.cn%2Fvivobbs%2Fattachment%2Fforum%2F201611%2F06%2F211252asasxdc78psgaflg.png&refer=http%3A%2F%2Fbbsfiles.vivo.com.cn&app=2002&size=f9999,10000&q=a80&n=0&g=0n&fmt=auto?sec=1654343803&t=eb1a25e7ed7cdefc4e387cf2ec2f4afe",
        "https://gimg2.baidu.com/image_search/src=http%3A%2F%2Fc-ssl.duitang.com%2Fuploads%2Fitem%2F201803%2F25%2F20180325210912_vcfXH.jpeg&refer=http%3A%2F%2Fc-ssl.duitang.com&app=2002&size=f9999,10000&q=a80&n=0&g=0n&fmt=auto?sec=1654343860&t=377ddbacd2710b3c4505d5adb481ec36",
        "https://gimg2.baidu.com/image_search/src=http%3A%2F%2Fi0.hdslb.com%2Fbfs%2Farticle%2F853126203de1cf032deadd4d783b8ba881a1ce8a.jpg&refer=http%3A%2F%2Fi0.hdslb.com&app=2002&size=f9999,10000&q=a80&n=0&g=0n&fmt=auto?sec=1654343873&t=94c3b2ec979fa69f481a2b675b91aad1",
        "https://gimg2.baidu.com/image_search/src=http%3A%2F%2Fc-ssl.duitang.com%2Fuploads%2Fitem%2F202005%2F04%2F20200504150124_t3iQA.jpeg&refer=http%3A%2F%2Fc-ssl.duitang.com&app=2002&size=f9999,10000&q=a80&n=0&g=0n&fmt=auto?sec=1654343884&t=da1e0bad45c8bbe4da2789f65b7093d2",
        "https://gimg2.baidu.com/image_search/src=http%3A%2F%2Fb-ssl.duitang.com%2Fuploads%2Fitem%2F201811%2F17%2F20181117005612_AVJvw.jpeg&refer=http%3A%2F%2Fb-ssl.duitang.com&app=2002&size=f9999,10000&q=a80&n=0&g=0n&fmt=auto?sec=1654343926&t=d8dce9688923ed4fc5b5a08bdc8302fe",
        "https://gimg2.baidu.com/image_search/src=http%3A%2F%2Fb-ssl.duitang.com%2Fuploads%2Fitem%2F20181%2F30%2F2018130185920_HQ82m.jpeg&refer=http%3A%2F%2Fb-ssl.duitang.com&app=2002&size=f9999,10000&q=a80&n=0&g=0n&fmt=auto?sec=1654343954&t=cae923ee08bbc79ec78eb19afa5d9f54",
        "https://gimg2.baidu.com/image_search/src=http%3A%2F%2Fn.sinaimg.cn%2Fsinakd20110%2F96%2Fw2048h2048%2F20210627%2Fc8ed-6d1cd3485e8b83f3e9e8fb9c5c85bede.jpg&refer=http%3A%2F%2Fn.sinaimg.cn&app=2002&size=f9999,10000&q=a80&n=0&g=0n&fmt=auto?sec=1654343964&t=48dc3ca5734d78bfe40bd92201f3b6fc",
        "https://gimg2.baidu.com/image_search/src=http%3A%2F%2Fn.sinaimg.cn%2Fsinakd20114%2F96%2Fw2048h2048%2F20210915%2Fc5c6-4c0a8d0d5ed782f4c61fcc6143cc8500.jpg&refer=http%3A%2F%2Fn.sinaimg.cn&app=2002&size=f9999,10000&q=a80&n=0&g=0n&fmt=auto?sec=1654343977&t=e4104e3e6225b5f871734b9003e216b4",
        "https://gimg2.baidu.com/image_search/src=http%3A%2F%2Fc-ssl.duitang.com%2Fuploads%2Fitem%2F202006%2F23%2F20200623184344_oscsd.jpg&refer=http%3A%2F%2Fc-ssl.duitang.com&app=2002&size=f9999,10000&q=a80&n=0&g=0n&fmt=auto?sec=1654344000&t=696365df5abffba9170a7802ad013157",
        "https://gimg2.baidu.com/image_search/src=http%3A%2F%2Fimg.nga.178.com%2Fattachments%2Fmon_202002%2F02%2FbiQ5-3ydxXuZ8eT3cS1yg-140.png&refer=http%3A%2F%2Fimg.nga.178.com&app=2002&size=f9999,10000&q=a80&n=0&g=0n&fmt=auto?sec=1654344029&t=481858dd07437105b055629188ca4fd6",
        "https://gimg2.baidu.com/image_search/src=http%3A%2F%2Fi0.hdslb.com%2Fbfs%2Farticle%2Fbc2764753cc88f2f14abfcc448e386677394ea40.jpg&refer=http%3A%2F%2Fi0.hdslb.com&app=2002&size=f9999,10000&q=a80&n=0&g=0n&fmt=auto?sec=1654359412&t=bae9d0a04c0d7fac18587c50c788a713",
        "https://gimg2.baidu.com/image_search/src=http%3A%2F%2Fimg31.51tietu.net%2Fpic%2F2016-120805%2F20161208051934ibognezuubc112650.jpg&refer=http%3A%2F%2Fimg31.51tietu.net&app=2002&size=f9999,10000&q=a80&n=0&g=0n&fmt=auto?sec=1654359483&t=43e460285b89ed1feccd58b66d7f550f",
        "https://gimg2.baidu.com/image_search/src=http%3A%2F%2Fi0.hdslb.com%2Fbfs%2Farticle%2F9b6de70095b0a623992462e27b2cc435b1e39158.jpg&refer=http%3A%2F%2Fi0.hdslb.com&app=2002&size=f9999,10000&q=a80&n=0&g=0n&fmt=auto?sec=1654359531&t=51b5e96b1a750f01c3207cab69871a2c",
        "https://gimg2.baidu.com/image_search/src=http%3A%2F%2Fhbimg.b0.upaiyun.com%2F68c7e4ec9a8b3804d387012c8f2c2c69f9db95a42b695-Rxfr9z_fw658&refer=http%3A%2F%2Fhbimg.b0.upaiyun.com&app=2002&size=f9999,10000&q=a80&n=0&g=0n&fmt=auto?sec=1653817842&t=9fa35989a42b23f39f692e03aebe4672",
        "https://gimg2.baidu.com/image_search/src=http%3A%2F%2Fimg.ivsky.com%2Fimg%2Ftupian%2Fpic%2F202002%2F27%2Fkatong_yingtao_png_sucai.png%3Fdownload&refer=http%3A%2F%2Fimg.ivsky.com&app=2002&size=f9999,10000&q=a80&n=0&g=0n&fmt=auto?sec=1654343700&t=cc961b89a23fa161c143ca2b93629a9b",
        "https://gimg2.baidu.com/image_search/src=http%3A%2F%2Fpic.90sjimg.com%2Fdesign%2F01%2F84%2F14%2F63%2F5a2e2b3b888ae.png&refer=http%3A%2F%2Fpic.90sjimg.com&app=2002&size=f9999,10000&q=a80&n=0&g=0n&fmt=auto?sec=1654343721&t=36f54ccbfa53efc1fc91dfb74b80b89f",
    )

    private val countdownLatch = CountDownLatch(images.size)
    private val contentView by lazy {
        ConstraintLayout {
            layout_width = match_parent
            layout_height = match_parent

            lf = LineFeedLayout {
                layout_width = match_parent
                layout_height = match_parent
                verticalGap = 10
                horizontalGap = 15
            }
        }
    }

    private var start = System.currentTimeMillis()
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(contentView)
        // print time consumed after all images loaded
        MainScope().launch(Dispatchers.IO) {
            countdownLatch.await()
            Log.d(
                "test",
                "[glide-performance] glide-time-consume=${System.currentTimeMillis() - start}"
            )
        }

        lf.apply {
            images.forEach { img ->
                ImageView {
                    layout_width = 100
                    layout_height = 100
                    scaleType = scale_fit_xy
                    // loading images (I will replace HttpUrlConnection by OkHttp)
                    Glide
                        .with(this@GlideActivity3)
                        .load(img)
                        .diskCacheStrategy(DiskCacheStrategy.NONE)
                        .skipMemoryCache(true)
                        .listener(object : RequestListener<Drawable> {
                            override fun onLoadFailed(
                                e: GlideException?,
                                model: Any?,
                                target: Target<Drawable>?,
                                isFirstResource: Boolean
                            ): Boolean {
                                countdownLatch.countDown()
                                return false
                            }

                            override fun onResourceReady(
                                resource: Drawable?,
                                model: Any?,
                                target: Target<Drawable>?,
                                dataSource: DataSource?,
                                isFirstResource: Boolean
                            ): Boolean {
                                countdownLatch.countDown()
                                return false
                            }
                        })
                        .into(this)
                }.also { addView(it) }
            }
        }
    }
}
```
The [#4530](https://github.com/square/okhttp/issues/4530) is in open state.

Is there anything i can do to make loading faster by OkHttp, or say making http/2 faster in cocurrency request.

Is it possible to make more than one http/2 connection to the same host in OkHttp for now? 

Thanks!

**Comment by yschimke** [comment]
@wisdomtl no clean way. You can implement your own client side load balancing if you implement Call.Factory, and having that use a root OkHttpClient, and then fork other instances (with a new ConnectionPool) above a certain limit.

It's an awkward workaround, but we don't have clean support for this yet.

Even if you raise per host limits, because it's a shared socket you still get head of line blocking and are likely* hitting a single server.

**Comment by wisdomtl** [comment]
> @wisdomtl no clean way. You can implement your own client side load balancing if you implement Call.Factory, and having that use a root OkHttpClient, and then fork other instances (with a new ConnectionPool) above a certain limit.
> 
> It's an awkward workaround, but we don't have clean support for this yet.
> 
> Even if you raise per host limits, because it's a shared socket you still get head of line blocking and are likely* hitting a single server.

Thanks for the prompt reply!

Maybe QUIC will come to the rescue, will it be supported in OkHttp in the near future?

**Comment by yschimke** [comment]
Not directly any time soon see https://github.com/square/okhttp/issues/907

Options if you care about this

Cronet/OkHttp https://github.com/google/cronet-transport-for-okhttp/blob/master/README.md

But if I prototype the Call.Factory load balancer, would it be worth benchmarking with that?

Generally I'm not in a rush to tackle this in OkHttp for two reasons

1) It's complex to do right, potentially negative results if done badly or for edge cases.  And we have a lot on our plate already for 5.0.
2) In most typical apps, I think there are other solutions to avoid this problem before hitting the network.  Say caching, or proactively fetching content. I'm not sure there are many apps where this is the bottleneck to showing the user a page full of content.

**Comment by yschimke** [comment]
@wisdomtl a sample load balancing Call.Factory https://github.com/square/okhttp/pull/7280/files

**Comment by techwnn** [comment]
> Generally I'm not in a rush to tackle this in OkHttp for two reasons
> 
> 1. It's complex to do right, potentially negative results if done badly or for edge cases.  And we have a lot on our plate already for 5.0.
> 2. In most typical apps, I think there are other solutions to avoid this problem before hitting the network.  Say caching, or proactively fetching content. I'm not sure there are many apps where this is the bottleneck to showing the user a page full of content.

I agree with this, but I think it's better to start spike of http3 support in a seprated branch. 
Just like what nginx do in https://quic.nginx.org.
Netty on the other hand, they start incubator project in https://netty.io/news/2021/03/04/http3-0-0-1-Final.html
So I think a project like incubator for OkHttp on http/3 should start, at least we can start spike of the [RFC-914](https://quicwg.org/) and related RFCs, since they are complex and especially need to start from scratch for KMM target.

**Comment by yschimke** [comment]
@techwnn there are no current plans for OkHttp support for http3 in built. No one is working on it, and a lot of discussion would need to happen before someone contributed it and it landed in main, such as who would maintain it going forward.

You can always build the functionality yourself and leave it as a fork, or put up a PR for contribution.  But it's a lot of work.
