### ISSUE TITLE
HttpUrl string value would contain encoded hash-bang path segment even after adding it as encoded segment path to HttpUrl.Builder

### ISSUE THREAD

**Issue by novachevskyi** [square/okhttp#3446]
I'm trying to create URL using `HttpUrl.Builder` but after adding hash-bang path segment it gets encoded in any case even after using `HttpUrl.Builder::addEncodedPathSegment` method. Test case: https://gist.github.com/novachevskyi/71529d8fdecf120e626af227193a9e0f

**Comment by JakeWharton** [comment]
That is not a path segment. That is a fragment.

**Comment by novachevskyi** [comment]
@JakeWharton could you please post a short snippet of how is it possible to build `HttpUrl` with a hash-bang where it wouldn't be encoded to `%23!`? Now I'm trying different ways but can't get it working as expected. 

I'm also trying this solution: https://gist.github.com/novachevskyi/12b59e53d6162fb1cd4e6236b03fb504

But the result is still not what I'm expecting to get:
```
Expected :https://www.google.com/mobile/#!/id?platform=android
Actual   :https://www.google.com/mobile/?platform=android#!/id
```

**Comment by JakeWharton** [comment]
Everything after the # is part of the fragment and not the path or query
parameters.

Since this is a usage question, you should ask on StackOverflow and we can
assist you there.
