### ISSUE TITLE
RouteDatabase shall never contains a  'new Route()'

### ISSUE THREAD

**Issue by changety** [square/okhttp#3463]
in `RouteSelector` next() method：
```
    Route route = new Route(address, lastProxy, lastInetSocketAddress);
    if (routeDatabase.shouldPostpone(route)) {
      postponedRoutes.add(route);
      // We will only recurse in order to skip previously failed routes. They will be tried last.
      return next();
    }
```
and in `RouteDatabase` shouldPostpone() method：
```
    return failedRoutes.contains(route);
```
how can this return true?

in  my case:
everytime a new route with the same Address will pass shouldPostpone() method, but I think this route is a failed route which should be postpone.

![popo_2017-07-18 13-49-50](https://user-images.githubusercontent.com/1650376/28302488-2ed3954e-6bc0-11e7-87e7-dd81cfd673a8.jpg)

and in a very bad case, it will leak the memory:
think about a custom `DNS` implement"

```
public class CustomDns implements Dns {
    @Override
    public List<InetAddress> lookup(String hostname) throws UnknownHostException {
        List<String> ips = new ArrayList<>();
        ips.add("10.126.21.106");
        ips.add("10.126.21.107"); // may be from the HttpDns server
        List<InetAddress> addrs = new ArrayList<>();
        for (String ip : ips) {
            InetAddress address = InetAddress.getByName(ip);
            addrs.add(address);
        }
        return addrs;
    }
}
```
 the first two ips are bad one,  the `RouteDatabase` always record them as the failedroute, and never postpone them, and the good one will be delay ,because the bad one will try first...
 so the 
```
  private final Set<Route> failedRoutes = new LinkedHashSet<>();
```
will become bigger and bigger, actually it leaks the memory

**Comment by JakeWharton** [comment]
It would return `true` with a proper `equals` method comparing by value, for what it's worth.

**Comment by changety** [comment]
@JakeWharton Would new okhttp version fix this problem?

**Comment by changety** [comment]
I

**Comment by changety** [comment]
orz This is a mistake... in my case my every request has a dns implement in my request, so the equal() return false.
