### ISSUE TITLE
HttpLoggingInterceptor cause download progress problem

### ISSUE THREAD

**Issue by cd-butterfly** [square/okhttp#3464]
Bug report.
i used #1568 for downloading a file that more than 20M. it calls update method Within 2 seconds of the end of the download. i removed the HttpLoggingInterceptor Interceptor, it goes ok.
in HttpLoggingInterceptor.java i find the following code 
`source.request(9223372036854775807L);`
how can i solve this bug.
thanks

**Comment by JakeWharton** [comment]
There is no bug. The logging interceptor buffers the entire response in memory which will affect things like observing progress (assuming the progress indicator is prior to the logging interceptor in the chain). This is by design as there's no other way to log the body unless we load it into memory. If you want to ensure that progress works use a logging level lower than `BODY`. It will also prevent OOMs on very large files.

**Comment by cd-butterfly** [comment]
thanks for your advice. i used `Level.NONE` in released apk.
i find another way to solve this. is to call `addInterceptor(loggingInterceptor)` before `addInterceptor(new FileDownloadInterceptor())`, the progress Interceptor will be prior to the logging interceptor in the chain.
thanks so much

**Comment by jollyjoker992** [comment]
@cd-butterfly @JakeWharton I run into the similar problem when I try to implement the `ProgressInterceptor` for listening on download progress update. When I remove `HttpLoggingInterceptor` (in release build), the progress will not be updated. It works well when i re-add the `HttpLoggingInterceptor`. Could you guys help to give some advices?

**Comment by jollyjoker992** [comment]
> @cd-butterfly @JakeWharton I run into the similar problem when I try to implement the `ProgressInterceptor` for listening on download progress update. When I remove `HttpLoggingInterceptor` (in release build), the progress will not be updated. It works well when i re-add the `HttpLoggingInterceptor`. Could you guys help to give some advices?
> 
> Here is my code:
> 
> * [Interceptor](https://github.com/bitmark-inc/bitmark-mobile-android/blob/master/app/src/main/java/com/bitmark/registry/data/source/remote/api/middleware/ProgressInterceptor.kt)
> * [ProgressResponseBody](https://github.com/bitmark-inc/bitmark-mobile-android/blob/master/app/src/main/java/com/bitmark/registry/data/source/remote/api/response/ProgressResponseBody.kt)

It's my mistake when i use a `PublishSubject` to emit the progress but i already disposed the `Subscription` it when receive the `Response`. That why i cannot receive any progress update. Thank you.
