### ISSUE TITLE
Uncaught IllegalArgumentException causing fatal crash

### ISSUE THREAD

**Issue by JohnSolstice** [square/okhttp#3465]
I'm seeing a rare crash in my app's crash reporting.  It stems from the Okio library.  I'm not sure exactly what the root cause is, but for some reason, the sink or source methods will get called with a null input or output stream, causing an IllegalArgumentException to be thrown.  These methods do not have a `throws IllegalArgumentException` declaration in method declaration, so they cause a crash if not caught.  This isn't an issue when making a synchronous RealCall, because I can just catch the exception myself.  However, when using AsyncCall, the exception will crash the app.  Here is the stack trace:

```
Exception java.lang.IllegalArgumentException: in == null
okio.Okio.source (Okio.java:127)
okio.Okio.source (Okio.java:220)
okhttp3.internal.connection.RealConnection.connectSocket (RealConnection.java:226)
okhttp3.internal.connection.RealConnection.connect (RealConnection.java:146)
okhttp3.internal.connection.StreamAllocation.findConnection (StreamAllocation.java:186)
okhttp3.internal.connection.StreamAllocation.findHealthyConnection (StreamAllocation.java:121)
okhttp3.internal.connection.StreamAllocation.newStream (StreamAllocation.java:100)
okhttp3.internal.connection.ConnectInterceptor.intercept (ConnectInterceptor.java:42)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:92)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:67)
okhttp3.internal.cache.CacheInterceptor.intercept (CacheInterceptor.java:93)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:92)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:67)
okhttp3.internal.http.BridgeInterceptor.intercept (BridgeInterceptor.java:93)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:92)
okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept (RetryAndFollowUpInterceptor.java:120)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:92)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:67)
okhttp3.RealCall.getResponseWithInterceptorChain (RealCall.java:179)
okhttp3.RealCall$AsyncCall.execute (RealCall.java:129)
okhttp3.internal.NamedRunnable.run (NamedRunnable.java:32)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1113)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:588)
java.lang.Thread.run (Thread.java:818)
```

A quick fix would be to catch both an `IOException | IllegalArgumentException e` in RealCall.java line 143.  You would have to  deal with the fact that onFailure currently takes an IOException of course.  I was doing it like this: 

``` 
catch (Exception e) {
        if (signalledCallback) {    
          // Do not signal the callback twice!    
          Platform.get().log(INFO, "Callback failure for " + toLoggableString(), e);    
        } else {     
          if (e instanceof IOException) {     
            responseCallback.onFailure(RealCall.this, (IOException) e);     
          } else {     
            responseCallback.onFailure(RealCall.this, new IOException(e.getMessage(), e));     
          }     
        }     
      }
```

But there is probably a better way...

If you don't fix this, is there a way around it?

**Comment by briananderson1222** [comment]
I am seeing the exact same thing in my crash reporting. We've moved to using the synchronous `execute` method in our repository layer and manually handling the threading of the API call itself. We have seen this come up with OKHTTP's integration in other libraries we use though, such as MapBox. Not entirely sure what the root cause is either.. It does seem strange to throw an Exception without declaring that that exception can be thrown. Definitely curious in the solution here..

**Comment by wujingchao** [comment]
see #3477

**Comment by swankjesse** [comment]
Looks like you’ve got a misbehaving implementation of `java.net.Socket`. In particular, `Socket.getInputStream()` is supposed to either return a non-null `InputStream` or throw an `IOException`. But in your code it looks like it’s returning null.

If you can find which implementation of `Socket` or `SocketFactory` is being used, that’s who you should report this bug to. There’s nothing we can do in OkHttp to workaround broken socket implementations.

**Comment by briananderson1222** [comment]
To provide more details, as suggested by @swankjesse it seems that this was most likely cause by not setting the Source/Target Compatibility when using JDK 8 using Gradle 3.5. After setting:

```
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_7
        targetCompatibility JavaVersion.VERSION_1_7
    }
```

I am fairly certain this has fixed the problem for our project.

**Comment by JacobCooley** [comment]
This is plaguing my application too
I've gotten my app to 99.9% crash free rating, but this is still getting the most crashes.  I think the only thing I'm using that uses okhttp is Picasso.  I'm not getting any references to what's happening when the crash happens though. 

Fatal Exception: java.lang.IllegalStateException
stream != null
com.squareup.okhttp.internal.http.StreamAllocation.findConnection (StreamAllocation.java:143)
com.squareup.okhttp.internal.http.StreamAllocation.findHealthyConnection (StreamAllocation.java:126)
com.squareup.okhttp.internal.http.StreamAllocation.newStream (StreamAllocation.java:95)
com.squareup.okhttp.internal.http.HttpEngine.connect (HttpEngine.java:283)
com.squareup.okhttp.internal.http.HttpEngine.sendRequest (HttpEngine.java:224)

**Comment by swankjesse** [comment]
@JacobCooley upgrading to OkHttp3 should fix that.

**Comment by JohnSolstice** [comment]
@JacobCooley if upgrading okhttp3 doesn't work... Are you by chance using Splunk?  Or any other library that would set your SocketImpl?  If you're not sure, set a breakpoint at that line in the okio library and check what type of object the Socket is.  If it's not a PlainSocketImpl I would figure out where the class comes from...
