### ISSUE TITLE
add additional CRLF for multipart body

### ISSUE THREAD

**Issue by aegis123** [square/okhttp#3467]
Add additional CRLF for body parts where the content ends with a line break. As per [RFC1341](https://www.w3.org/Protocols/rfc1341/7_2_Multipart.html#z0) an additional CRLF is needed when the content ends in a line break.

```
From: Nathaniel Borenstein <nsb@bellcore.com> 
To:  Ned Freed <ned@innosoft.com> 
Subject: Sample message 
MIME-Version: 1.0 
Content-type: multipart/mixed; boundary="simple 
boundary" 

This is the preamble.  It is to be ignored, though it 
is a handy place for mail composers to include an 
explanatory note to non-MIME compliant readers. 
--simple boundary 

This is implicitly typed plain ASCII text. 
It does NOT end with a linebreak. 
--simple boundary 
Content-type: text/plain; charset=us-ascii 

This is explicitly typed plain ASCII text. 
It DOES end with a linebreak. 

--simple boundary-- 
This is the epilogue.  It is also to be ignored.
```

**Comment by JakeWharton** [comment]
Are you saying we don't do this already? I don't really see the difference between the two cases. If there's no trailing newline then we add a newline and write the boundary. If there is a trailing newline then we add a newline and write the boundary.

**Comment by swankjesse** [comment]
No action to take on this.
