### ISSUE TITLE
 java.net.SocketTimeoutException: timeout

### ISSUE THREAD

**Issue by heshun25** [square/okhttp#3482]
I had call the same address and the second time found this exception,also the following request all failed with the same question too! may it is a bug !  anybody can help me ?
I had try to evealAll connection when the catch block and solve this problem , but i still think it is a bug! 
version:okhttp-3.8.1 with android6.0

System.err: java.net.SocketTimeoutException: timeout
07-27 08:25:09.112  4868  4957 W System.err: 	at okhttp3.internal.http2.Http2Stream$StreamTimeout.newTimeoutException(Http2Stream.java:593)
07-27 08:25:09.112  4868  4957 W System.err: 	at okhttp3.internal.http2.Http2Stream$StreamTimeout.exitAndThrowIfTimedOut(Http2Stream.java:601)
07-27 08:25:09.113  4868  4957 W System.err: 	at okhttp3.internal.http2.Http2Stream$FramingSink.emitFrame(Http2Stream.java:498)
07-27 08:25:09.113  4868  4957 W System.err: 	at okhttp3.internal.http2.Http2Stream$FramingSink.close(Http2Stream.java:538)
07-27 08:25:09.113  4868  4957 W System.err: 	at okio.RealBufferedSink.close(RealBufferedSink.java:236)
07-27 08:25:09.116  4868  4957 W System.err: 	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:63)
07-27 08:25:09.116  4868  4957 W System.err: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
07-27 08:25:09.116  4868  4957 W System.err: 	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
07-27 08:25:09.116  4868  4957 W System.err: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
07-27 08:25:09.116  4868  4957 W System.err: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
07-27 08:25:09.116  4868  4957 W System.err: 	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
07-27 08:25:09.117  4868  4957 W System.err: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
07-27 08:25:09.117  4868  4957 W System.err: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
07-27 08:25:09.117  4868  4957 W System.err: 	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
07-27 08:25:09.117  4868  4957 W System.err: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
07-27 08:25:09.117  4868  4957 W System.err: 	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
07-27 08:25:09.117  4868  4957 W System.err: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
07-27 08:25:09.117  4868  4957 W System.err: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
07-27 08:25:09.118  4868  4957 W System.err: 	at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:211)
07-27 08:25:09.118  4868  4957 W System.err: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
07-27 08:25:09.118  4868  4957 W System.err: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
07-27 08:25:09.118  4868  4957 W System.err: 	at com.facebook.stetho.okhttp3.StethoInterceptor.intercept(StethoInterceptor.java:59)
07-27 08:25:09.118  4868  4957 W System.err: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
07-27 08:25:09.118  4868  4957 W System.err: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
07-27 08:25:09.118  4868  4957 W System.err: 	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185)
07-27 08:25:09.119  4868  4957 W System.err: 	at okhttp3.RealCall.execute(RealCall.java:69)
07-27 08:25:09.122  4868  4957 W System.err: 	at com.x.base.net.HttpRequest.execute(HttpRequest.java:62)
07-27 08:25:09.122  4868  4957 W System.err: 	at com.x.base.net.request.RequestCall.execute(RequestCall.java:45)
07-27 08:25:09.122  4868  4957 W System.err: 	at com.x.base.net.request.RequestCall.execute(RequestCall.java:49)
07-27 08:25:09.123  4868  4957 W System.err: 	at com.x.account.AccountManager.loginRokid(AccountManager.java:127)
07-27 08:25:09.123  4868  4957 W System.err: 	at com.x.account.AccountService$AccountProxy.login(AccountService.java:60)
07-27 08:25:09.123  4868  4957 W System.err: 	at com.x.base.IAccountManager$Stub.onTransact(IAccountManager.java:54)
07-27 08:25:09.123  4868  4957 W System.err: 	at android.os.Binder.transact(Binder.java:387)
07-27 08:25:09.123  4868  4957 W System.err: 	at com.x.base.IAccountManager$Stub$Proxy.login(IAccountManager.java:157)
07-27 08:25:09.123  4868  4957 W System.err: 	at com.x.netprovider.Provider.login(Provider.java:44)
07-27 08:25:09.123  4868  4957 W System.err: 	at com.x.network.ReconnectThread.login(ReconnectThread.java:462)
07-27 08:25:09.124  4868  4957 W System.err: 	at com.x.network.ReconnectThread.connectSsid(ReconnectThread.java:289)
07-27 08:25:09.124  4868  4957 W System.err: 	at com.x.network.ReconnectThread.handleMessage(ReconnectThread.java:214)
07-27 08:25:09.127  4868  4957 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:98)
07-27 08:25:09.127  4868  4957 W System.err: 	at android.os.Looper.loop(Looper.java:148)
07-27 08:25:09.127  4868  4957 W System.err: 	at com.x.network.ReconnectThread.run(ReconnectThread.java:181)

**Comment by JakeWharton** [comment]
This looks like a normal timeout due to connectivity issues. What makes you
think it's a bug instead?

**Comment by heshun25** [comment]
because this exception throws every time and i use httpurlconnection instead it and it's ok! also postman help me test address is working,this exception only i use okhttp ,every time i found this exception , 

 public <T> T execute(RequestCall requestCall, Type typeOfT) {
        Response response = null;
        ResponseBody responseBody = null;
        try {
            response = requestCall.getCall().execute();
            responseBody = response.body();
            if (TextUtils.isEmpty(responseBody.toString())) {
                return null;
            }

            String adapterKey = requestCall.getAdapterKey();
            if (TextUtils.isEmpty(adapterKey) || !httpRequestAdapterMap.containsKey(adapterKey)) {
                if (null == typeOfT) {
                    return (T) responseBody.toString();
                } else {
                    return new Gson().fromJson(responseBody.toString(), typeOfT);
                }
            } else {
                return (T) httpRequestAdapterMap.get(adapterKey).parseResponseBodySync(response.body(), typeOfT);
            }


        } catch (IOException e) {
            e.printStackTrace();
            mOkHttpClient.connectionPool().evictAll();
        } finally {
            if (null != responseBody) {
                responseBody.close();
            }
        }

        return null;
    }

**Comment by swankjesse** [comment]
Likely the difference between OkHttp and HttpURLConnection is that OkHttp uses HTTP/2, whereas HttpURLConnection does not.

That said, there’s insufficient information here for us to take action. If you can give us a specific HTTP request that we can make that triggers this problem, that’d be a start.

**Comment by devfoFikiCar** [comment]
> same problem.Is there any conclusion to this question?

Me too

**Comment by arifardians-gibeon** [comment]
> @heshun25 hello, I may have had the same problem.Is there any conclusion to this question?

me too

**Comment by devfoFikiCar** [comment]
> > @heshun25 hello, I may have had the same problem.Is there any conclusion to this question?
> 
> me too

I did it by moving to async task and putting timeout length longer or shorter depending on user internet speed

**Comment by jianming221** [comment]
Me too
