### ISSUE TITLE
Proposal: Google Dynamic Security Provider Support

### ISSUE THREAD

**Issue by naturalwarren** [square/okhttp#3485]
Currently we have a small fork of OkHttp that checks to see if [DSP](https://developer.android.com/training/articles/security-gms-provider.html) is present on Android devices. The implementation looks to see if the GMS `java.security.Provider` is installed when `AndroidPlatform.buildIfSupported()` is called:

```java
// Attempt to find Google Play Services Dynamic Security Provider.
Provider provider = Security.getProvider("GmsCore_OpenSSL");
if (provider != null) {
  getAlpnSelectedProtocol = GET_ALPN_SELECTED_PROTOCOL;
  setAlpnProtocols = SET_ALPN_PROTOCOLS;
} else {
  // Attempt to find Android 5.0+ APIs.
  ...
}
```

This would be pretty easy to add directly in a PR and would allow OkHttp to provide ALPN support for pre 5.x devices and facilitate HTTP/2 use on older devices. 

Thoughts?

**Comment by swankjesse** [comment]
Send a pull request?

**Comment by naturalwarren** [comment]
Will do, thanks Jesse.

**Comment by naturalwarren** [comment]
Fixed in #3490.

**Comment by yschimke** [comment]
Did we break this recently?

**Comment by yschimke** [comment]
Supported cleanly via https://github.com/square/okhttp/pull/5243

Supports default Android, BYO Conscrypt and GMS
