### ISSUE TITLE
Dynamically choose the connectivity channel to perform 

### ISSUE THREAD

**Issue by ashwinqb** [square/okhttp#3495]
Feature Request

In customized version of Android OS if the Device is connected to wifi and it has no internet connectivity it will not try to perform the HTTP call using the cellular data. if this is handled in the library itself it will be helpful. ie. when an HTTP call is triggered the Okhttp choose through wifi channel or cellular data the call must perform. In early Android versions they supported ConnetivityManager.setPerference(). But now this is deprecated. If this feature is implemented. it will be very helpful.
I mean to loop through the NetworkInterfaces and check the destination address is reachable or not and then if reachable the call must perform through that interface.

**Comment by swankjesse** [comment]
I recommend you use an interceptor for this. It's not reasonable for OkHttp to do this because there’s no simple policy that would work for most apps.
