### ISSUE TITLE
MockWebServer hangs for 5 seconds upon shutdown

### ISSUE THREAD

**Issue by Alexander--** [square/okhttp#3497]
MockWebServer does not shutdown it's own executor when closed, instead it calls `awaitTermination` and waits for things to magically work out themselves. When doing "long" operations (such as testing read timeouts), that behaviour may result in longer-than-necessary waiting and potentially resource leaks (if the Dispatcher allocates any resources, that must be released).

Expected behaviour: MockWebServer must call `shutdownNow` on it's executor when closed. All internal mechanisms of MockWebServer (such as `throttleBody`) must be properly interruptible.

The testcase below demonstrates that behaviour using native `URLConnection`. The connection itself times out nicely, but MockWebServer will hang for additional 5 seconds because it's executor is never shut down, threads are never interrupted and throttleBody timeouts are not cancelled:

    @Test(timeout = 1000)
    public void terribleTimeoutShowcase() throws Exception {
        try (MockWebServer server = new MockWebServer()) {
            URLConnection conn = server.url("/").url().openConnection();

            server.enqueue(new MockResponse()
                    .throttleBody(1, 10000, TimeUnit.SECONDS)
                    .setBody("xxxxxxxxxxxxxxxxxxxxxxxxxx"));

            conn.setReadTimeout(200);

            convertStreamToString(conn.getInputStream());
        }
    }

    private static String convertStreamToString(InputStream is) throws IOException {
        try (Scanner scanner = new Scanner(is, "UTF-8")) {
            String result = null;

            try {
                result = scanner.useDelimiter("\\A").next();
            } catch (java.util.NoSuchElementException e) {
                e.printStackTrace();
            }

            final IOException trueError = scanner.ioException();
            if (trueError != null) {
                throw trueError;
            }

            return result;
        }
    }

**Comment by swankjesse** [comment]
Thread interruption is very difficult to do right. Unlikely we’ll get to this any time soon, but it’s definitely an improvement we could make.

**Comment by Alexander--** [comment]
@swankjesse

In my experience, both task cancellation and thread interruption are relatively easy to get right (that is, compared to other aspects of multi-threaded programming). It seems, that checking for ThreadPoolExecutor#isShutdown inside MockWebServer runnables as well as correctly handling InterruptionException (for example, by converting it to IOException) should do the trick. Or is there anything I overlooked?

> Unlikely we’ll get to this any time soon, but it’s definitely an improvement we could make.

In that case, could you please remove call to `awaitTermination` from `shutdown`? If MockWebServer does not properly support response termination, why does `shutdown` ever wait for it?

**Comment by yschimke** [comment]
This should be fixed by TaskRunner changes

**Comment by MitroshinDmitry** [comment]
@yschimke in which version were these changes added? 
And how to resolve okhttpClient version conflict with retrofit, which uses com.squareup.okhttp3:okhttp:3.14.9 , but actual version on mockwebServer  com.squareup.okhttp3:okhttp:4.9.3 ? Is there a way for them to work together? 

I understand that retrofit uses to old version, but i decided to ask you for help first.
