### ISSUE TITLE
charset property in application/json mimetype is invalid

### ISSUE THREAD

**Issue by theikkila** [square/okhttp#3499]
I'm investigating for weird problem related to Content-Type and properties of that.

Currently I'm using Apollo GraphQL-client in React Native-application that transports GraphQL-queries through HTTP to GraphQL-server.

Content-Type of those requests should be `application/json` (https://github.com/apollographql/apollo-client/blob/master/src/transport/networkInterface.ts#L194) but actually when using react native in Android (and so okhttp) the header is `application/json; charset=utf-8` instead of just plain `application/json` which is against RFC and so the server I'm using will disallow the requests.

From tcpdump you can clearly see that the header is actually that. I couldn't find anything related to that from whatwg-fetch project, theyre using just plain mime-type without properties.

The only place I could find that was in Okhttp's frontpage there is an example (1?) request with content-type `application/json; charset=utf-8` However according to http://www.ietf.org/rfc/rfc4627.txt `charset` property with `application/json` is invalid and so strictly implemented servers will decline that those requests.
From the example that faulty manner propagates through open source software and so server implementations have to handle this kind of input if they want to support more clients.

Here is also tcpdumped headers of the request coming from the phone:

```
POST /graphql HTTP/1.1
accept: */*
Content-Type: application/json; charset=utf-8
Content-Length: 431
Host: 192.168.100.163:8888
Connection: Keep-Alive
Accept-Encoding: gzip
User-Agent: okhttp/3.6.0

...
```
[1]
https://github.com/square/okhttp/blob/7135628c645892faf1a48a8cff464e0ed4ad88cb/samples/guide/src/main/java/okhttp3/guide/PostExample.java#L12

**Comment by JakeWharton** [comment]
What makes you think the 'charset' is explicitly invalid from that document?

The current RFC for JSON is https://tools.ietf.org/html/rfc7159, which states:

>   Note:  No "charset" parameter is defined for this registration.
>   Adding one really has no effect on compliant recipients.

So I'd actually argue an implementation that fails when a charset is specified is actually not correct.

**Comment by swankjesse** [comment]
BTW, if you’d like to create a response body without a charset, you can! Just use the method that takes a `byte[]` and do whatever character encoding you want.
https://square.github.io/okhttp/3.x/okhttp/okhttp3/ResponseBody.html#create-okhttp3.MediaType-byte:A-
