### ISSUE TITLE
Add GZip Request Compression

### ISSUE THREAD

**Issue by johnlcox** [square/okhttp#350]
The way I'm using retrofit/okhttp most of the requests are POSTs with JSON bodies that aren't huge (2KB - 30KB), but happen fairly frequently.  The server APIs support gzip compressed requests and so I spent some time trying to find a quick way to use gzip compression with retrofit/okhttp and it looks like it wouldn't be possible without modifications to okhttp itself.

Is there any possibility of this being added or accepted as a pull request?

**Comment by Gerlot** [comment]
Hi!

I tried to use the GzipRequestInterceptor Jake linked in the last comment, but the webserver I'm trying to reach returns the response "411 Length Required".
I noticed that the GzipRequestInterceptor sets the compressed RequestBody's contentLength to -1. This must be the problem, and I can't find a way to determine the length of the compressed body. How can I do that?

**Comment by JakeWharton** [comment]
You need to buffer the entire body by writing it to a Buffer. Then you can
get its size to use when writing.

**Comment by Gerlot** [comment]
Yeah, I've just figured it out with the help of a partly related conversation:
https://github.com/square/okhttp/issues/1349

Maybe you should add this solution to the linked page about interceptors. It took me 1.5 hour to figure it out.
Btw I did it like this (maybe it will be useful for others):
```java
private RequestBody requestBodyWithContentLength(final RequestBody requestBody) throws IOException {
        final Buffer buffer = new Buffer();
        try {
            requestBody.writeTo(buffer);
        } catch (IOException e) {
            throw new IOException("Unable to copy RequestBody");
        }
        return new RequestBody() {
            @Override
            public MediaType contentType() {
                return requestBody.contentType();
            }

            @Override
            public long contentLength() {
                return buffer.size();
            }

            @Override
            public void writeTo(BufferedSink sink) throws IOException {
                sink.write(ByteString.read(buffer.inputStream(), (int) buffer.size()));
            }
        };
    }
```
And I pass the whole thing to the Request like this:

```java
Request compressedRequest = originalRequest.newBuilder()
                .header("Content-Encoding", "gzip")
                .method(originalRequest.method(), requestBodyWithContentLength(gzip(originalRequest.body())))
                .build();
```

**Comment by JakeWharton** [comment]
```java
sink.write(ByteString.read(buffer.inputStream(), (int) buffer.size()));
```
This is _wildly_ inefficient.

At the very least do:
```java
sink.writeAll(buffer);
```

Or a bit more correctly:
```java
ByteString body = buffer.snapshot();

// .. RequestBody code
sink.write(body);
```

**Comment by Gerlot** [comment]
Ok, thanks for the correction!

**Comment by felipecsl** [comment]
Here's the full gzip interceptor with content length, for whom it may concern:

```java
class GzipRequestInterceptor implements Interceptor {
  @Override public Response intercept(Chain chain) throws IOException {
    Request originalRequest = chain.request();
    if (originalRequest.body() == null || originalRequest.header("Content-Encoding") != null) {
      return chain.proceed(originalRequest);
    }

    Request compressedRequest = originalRequest.newBuilder()
        .header("Content-Encoding", "gzip")
        .method(originalRequest.method(), forceContentLength(gzip(originalRequest.body())))
        .build();
    return chain.proceed(compressedRequest);
  }

  /** https://github.com/square/okhttp/issues/350 */
  private RequestBody forceContentLength(final RequestBody requestBody) throws IOException {
    final Buffer buffer = new Buffer();
    requestBody.writeTo(buffer);
    return new RequestBody() {
      @Override
      public MediaType contentType() {
        return requestBody.contentType();
      }

      @Override
      public long contentLength() {
        return buffer.size();
      }

      @Override
      public void writeTo(BufferedSink sink) throws IOException {
        sink.write(buffer.snapshot());
      }
    };
  }

  private RequestBody gzip(final RequestBody body) {
    return new RequestBody() {
      @Override public MediaType contentType() {
        return body.contentType();
      }

      @Override public long contentLength() {
        return -1; // We don't know the compressed length in advance!
      }

      @Override public void writeTo(BufferedSink sink) throws IOException {
        BufferedSink gzipSink = Okio.buffer(new GzipSink(sink));
        body.writeTo(gzipSink);
        gzipSink.close();
      }
    };
  }
}
```

**Comment by kamoljan** [comment]
If this issue is still open, +1

**Comment by galex** [comment]
Looking for this as well. 

@felipecsl 's solution does not work on Okhttp 2.5.0 (last one), as I get a TimeoutException. I think the content Length and the size of the gzipped body do not match, so the server is waiting for more.

**Comment by felipecsl** [comment]
when you gzip you dont know the contentLength in advance (see it returns -1) above

**Comment by minliang1219** [comment]
so，we should not be using gzip?

**Comment by swankjesse** [comment]
This is implemented by a straightforward interceptor. I can’t see a reasonable safe way to turn it on by default otherwise! No other action to take here.

**Comment by balazsgerlei** [comment]
Is the interceptor that @felipecsl wrote still works with Retrofit2 and OkHttp3?

**Comment by felipecsl** [comment]
@balazsgerlei it does

**Comment by laoxiao79** [comment]
Here is my method,
   public class GzipRequestInterceptor implements Interceptor {
        @Override
        public Response intercept(Chain chain) throws IOException {
            Request originalRequest = chain.request();
           
            **if(originalRequest.body() == null){
                Request newRequest = originalRequest.newBuilder()
                        .header("Content-Encoding", "gzip")
                        .build();
                return chain.proceed(newRequest);
            }**

            if (originalRequest.header("Content-Encoding") != null) {
                return chain.proceed(originalRequest);
            }
            Request compressedRequest = originalRequest.newBuilder()
                    .header("Content-Encoding", "gzip")
                    .method(originalRequest.method(), forceContentLength(gzip(originalRequest.body())))
                    .build();
            return chain.proceed(compressedRequest);
        }

        /**
         * https://github.com/square/okhttp/issues/350
         */
        private RequestBody forceContentLength(final RequestBody requestBody) throws IOException {
            final Buffer buffer = new Buffer();
            requestBody.writeTo(buffer);
            return new RequestBody() {
                @Override
                public MediaType contentType() {
                    return requestBody.contentType();
                }

                @Override
                public long contentLength() {
                    return buffer.size();
                }

                @Override
                public void writeTo(BufferedSink sink) throws IOException {
                    sink.write(buffer.snapshot());
                }
            };
        }

        private RequestBody gzip(final RequestBody body) {
            return new RequestBody() {
                @Override
                public MediaType contentType() {
                    return body.contentType();
                }

                @Override
                public long contentLength() {
                    return -1; // We don't know the compressed length in advance!
                }

                @Override
                public void writeTo(BufferedSink sink) throws IOException {
                    BufferedSink gzipSink = Okio.buffer(new GzipSink(sink));
                    body.writeTo(gzipSink);
                    gzipSink.close();
                }
            };
        }
    }

**Comment by laoxiao79** [comment]
Here is my method:
    public class GzipRequestInterceptor implements Interceptor {
        @Override
        public Response intercept(Chain chain) throws IOException {
            Request originalRequest = chain.request();
            if(originalRequest.body() == null){
                Request newRequest = originalRequest.newBuilder()
                        .header("Content-Encoding", "gzip")
                        .build();
                Log.i(TAG, "GzipRequestInterceptor　newRequest.toString():" + newRequest.toString());
                return chain.proceed(newRequest);
            }

            if (originalRequest.header("Content-Encoding") != null) {
                return chain.proceed(originalRequest);
            }
            Request compressedRequest = originalRequest.newBuilder()
                    .header("Content-Encoding", "gzip")
                    .method(originalRequest.method(), forceContentLength(gzip(originalRequest.body())))
                    .build();
            return chain.proceed(compressedRequest);
        }

        /**
         * https://github.com/square/okhttp/issues/350
         */
        private RequestBody forceContentLength(final RequestBody requestBody) throws IOException {
            final Buffer buffer = new Buffer();
            requestBody.writeTo(buffer);
            return new RequestBody() {
                @Override
                public MediaType contentType() {
                    return requestBody.contentType();
                }

                @Override
                public long contentLength() {
                    return buffer.size();
                }

                @Override
                public void writeTo(BufferedSink sink) throws IOException {
                    sink.write(buffer.snapshot());
                }
            };
        }

        private RequestBody gzip(final RequestBody body) {
            return new RequestBody() {
                @Override
                public MediaType contentType() {
                    return body.contentType();
                }

                @Override
                public long contentLength() {
                    return -1; // We don't know the compressed length in advance!
                }

                @Override
                public void writeTo(BufferedSink sink) throws IOException {
                    BufferedSink gzipSink = Okio.buffer(new GzipSink(sink));
                    body.writeTo(gzipSink);
                    gzipSink.close();
                }
            };
        }
    }

**Comment by laoxiao79** [comment]
or:

```
 builder.addInterceptor(new Interceptor() {
            @Override
            public Response intercept(Chain chain) throws IOException {
                Log.i(TAG,"GzipRequestInterceptor　chain.request().toString():"+chain.request().toString());
                Request request = chain.request()
                        .newBuilder()
                        .header("Content-Encoding", "gzip")
                        .build();
                Log.i(TAG,"GzipRequestInterceptor　request.toString():"+request.toString());
                return chain.proceed(request);
            }
        });
```

**Comment by karussell** [comment]
> This is implemented by a straightforward interceptor. I can’t see a reasonable safe way to turn it on by default otherwise! No other action to take here.

@swankjesse would it make sense to put the GzipRequestInterceptor in okhttp? I've copied this now to 3 applications already ;) ... or is this already available somewhere and I overlooked it?

**Comment by swankjesse** [comment]
@karussell how do you decide which requests to gzip?

**Comment by karussell** [comment]
Good question :). If I add this interceptor I would probably assume all requests are gzipped. Or one could configure the interceptor to gzip only under special conditions like "too big".

**Comment by swankjesse** [comment]
Gotcha. And you know your webservers will accept Gzip. The problem with making it on-by-default is that not all servers do unfortunately.

**Comment by karussell** [comment]
Yes, the webserver has to support this. If not, it will likely respond with an explicit error of the unsupported Content-Encoding.

If the GzipInterceptor has the code as above we can do requests without gzipping even with the GzipInterceptor added by setting the `Content-Encoding` header to `identity` I think.

**Comment by ashraf-atef** [comment]
@felipecsl  I tried your solution but unfortunately the response body is omitted from the log of http logging interceptor but I tried to log the request body by myself but the compression text was so weird.

Original request body: {"data":{"lng":"-122.0840926","lat":"37.4219524"},"device_id":"XXXXX"}
Compressed request body: ���������������9
    � ���ڈ�h\.\� �$�x���L�0�Dx�����=���ኤӤ�r�Z*w�{D�A�J�ՒNX?��r�Q������
    
So why do you think this is happening?

**Comment by sermah** [comment]
If someone is still on okhttp 4 these days, here's Kotlin version:

```kotlin
public class GzipRequestInterceptor : Interceptor {
    @Throws(IOException::class)
    override fun intercept(chain: Chain): Response {
        val originalRequest = chain.request()
        val requestBody = originalRequest.body
        // Ignore if no body or it's already compressed
        if (requestBody == null || originalRequest.header(ENCODING_HEADER) != null) {
            return chain.proceed(originalRequest)
        }

        val compressedRequest = originalRequest.newBuilder()
            .header(ENCODING_HEADER, GZIP_ENCODING)
            .method(originalRequest.method, gzip(requestBody))
            .build()
        return chain.proceed(compressedRequest)
    }

    private fun gzip(body: RequestBody): RequestBody {
        val buffer = Buffer()
        GzipSink(buffer).buffer().use {
            body.writeTo(it)
        }

        return object : RequestBody() {
            override fun contentType(): MediaType? {
                return body.contentType()
            }

            override fun contentLength(): Long {
                return buffer.size
            }

            override fun writeTo(sink: BufferedSink) {
                sink.write(buffer.snapshot())
            }
        }
    }

    private companion object {
        // https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Headers/Content-Encoding
        const val ENCODING_HEADER = "Content-Encoding"
        const val GZIP_ENCODING = "gzip"
    }
}
```
