### ISSUE TITLE
Make bouncycastle a provided dependency for mockwebserver

### ISSUE THREAD

**Issue by scompt** [square/okhttp#351]
I'm getting the following exception when running tests that use **mockwebserver** on 2.3.x devices:

```
11-15 13:40:55.565 W/ClassPathPackageInfoSource(25066): Cannot load class. Make sure it is in your apk. Class name: 'org.bouncycastle.asn1.x500.X500Name'. Message: org.bouncycastle.asn1.x500.X500Name
11-15 13:40:55.565 W/ClassPathPackageInfoSource(25066): java.lang.ClassNotFoundException: org.bouncycastle.asn1.x500.X500Name
```

On devices with Android 4.x installed, I don't get the exception and the tests pass.

If I change the `org.bouncycastle:bcprov-jdk15on` dependency on **mockwebserver** to `provided`, the tests pass on 2.3.x as well. I'm assuming that the bundled version of bouncy castle on older devices is simply incompatible with the dependency. Does this sound like a reasonable fix for this problem? If so, I'll make a pull request.

**Comment by yschimke** [comment]
No longer relevant, given dependency structure and support android versions
