### ISSUE TITLE
Add shutdown hook to OkHttpClient

### ISSUE THREAD

**Issue by JackyWoo** [square/okhttp#3513]
I used okhttpclient and when I wanted to shut down my program, I did not find a convenient way to release connections.
When process terminates, OS will released resources, but I think some kind of resource like sockets should be released manually.
So I think adding shutdown hook to okhttpclient  maybe a good way.

What kind of issue is this?

 - [x] Question. This issue tracker is not the place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use Stack
       Overflow. https://stackoverflow.com/questions/tagged/okhttp

 - [ ] Bug report. If you’ve found a bug, spend the time to write a failing test. Bugs with tests
       get fixed. Here’s an example: https://gist.github.com/swankjesse/981fcae102f513eb13ed

 - [ ] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
       already exists! Don’t send pull requests to implement new features without first getting our
       support. Sometimes we leave features out on purpose to keep the project small.

**Comment by swankjesse** [comment]
Resources are released when the process exits.

**Comment by JackyWoo** [comment]
Thanks for reply.  I know that  when the process exits resources are released. 
But  some kind of resource like sockets be released manually maybe better.

**Comment by JackyWoo** [comment]
In additional, I use okhttpclient in server not android.

**Comment by swankjesse** [comment]
If it helps, OkHttpClient has docs on what you need to shut down if you want to shut it down.

**Comment by JackyWoo** [comment]
I did not mean to release resources in run time, but release resources when process exist more gracefully.
Maybe  adding shutdown hook does matter much more.

**Comment by JakeWharton** [comment]
OkHttp can't know the context in which it's being used. If you want a
graceful shutdown then I think you should be adding the Runtime shutdown
hook and then stepping OkHttp through its shutdown lifecycle as documented.

**Comment by JackyWoo** [comment]
ok  I have done like this. I just think it is not a convenient way so I post the issue

**Comment by JakeWharton** [comment]
I think it would scary if we side-effected anytime you created an instance
by adding a shutdown hook. Not to mention what we'd have to do when you
called newBuilder()/build() to create shallow clones of the original
instance.

**Comment by JackyWoo** [comment]
As I understand,  okhttpclient should be singleton in most cases, so there is only one shutdown hook.
But also users can create many instances which will cause too much shutdown hooks and this is really bad.
