### ISSUE TITLE
Attempt to invoke interface method intercept on a null object reference

### ISSUE THREAD

**Issue by stitch9108** [square/okhttp#3514]
Hi,

We are having a large number of crashes reported by Crashlytics with the following error. 
We have this issue with okhttp 3.5 and 3.8.
Maybe there is something wrong in our code.

Can anyone help us?

Thanks a lot

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'okhttp3.Response okhttp3.Interceptor.intercept(okhttp3.Interceptor$Chain)' on a null object reference
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
       at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:179)
       at okhttp3.RealCall$AsyncCall.execute(RealCall.java:129)
       at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run(Thread.java:762)
```

**Comment by swankjesse** [comment]
Looks like you’re adding null to your interceptor chain.

**Comment by stitch9108** [comment]
Thanks for your answer @swankjesse 
However, I don't know where we could ne doing that.

Sorry but this is a large project and we are two new guys continuing the work of another company so we're still trying to understand everything.

From what I see, the addInterceptor method is only called using non null objects because it is created during the call as you can see bellow
``okHttpClientBuilder.addInterceptor(new Interceptor() {
                    @Override
                    public Response intercept(Interceptor.Chain chain) throws IOException {

                        HttpUrl url = chain.request().url().newBuilder()
                                .addQueryParameter(Constants.TOKEN_PARAMETER, TokenManager.getInstance().getCurrentToken()).build();

                        Request request = chain.request().newBuilder().url(url).build();

                        return chain.proceed(request);
                    }
                });``

Maybe there is something else that's done wrong. 

Thanks for the help!

**Comment by Genleon** [comment]
@swankjesse, i have this problem too, how to fix it? thanks.
 `
        Interceptor addCookiesInterceptor = chain -> {
            Request.Builder builder = chain.request().newBuilder();
            String cookies = UserInfoMrg.getInstance().getString("token", "");
            if (!TextUtils.isEmpty(cookies)) {
                builder.addHeader("Cookie", "user_token=" + cookies);
            }
            return chain.proceed(builder.build());
        };
`

**Comment by Genleon** [comment]
@swankjesse, i have this problem too, how to fix it? thanks.

        Interceptor addCookiesInterceptor = chain -> {
            Request.Builder builder1 = chain.request().newBuilder();
            String cookies = UserInfoMrg.getInstance().getString("token", "");
            if (!TextUtils.isEmpty(cookies)) {
                builder1.addHeader("Cookie", "user_token=" + cookies);
                Log.d(TAG, "添加token:" + "user_token=" + cookies);
            }
            return chain.proceed(builder1.build());
        };

**Comment by Genleon** [comment]
@swankjesse, i have this problem too, how to fix it? thanks.

        Interceptor addCookiesInterceptor = chain -> {
            Request.Builder builder = chain.request().newBuilder();
            String cookies = UserInfoMrg.getInstance().getString("token", "");
            if (!TextUtils.isEmpty(cookies)) {
                builder.addHeader("Cookie", "user_token=" + cookies);
            }
            return chain.proceed(builder.build());
        };

**Comment by Genleon** [comment]
this is my error message.

![image](https://user-images.githubusercontent.com/20266526/35266382-23e29d46-005e-11e8-805a-f67c729c58eb.png)
