### ISSUE TITLE
Add Max Connection Age

### ISSUE THREAD

**Issue by pdavidson** [square/okhttp#3520]
What kind of issue is this?
 - [ X ] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
       already exists! Don’t send pull requests to implement new features without first getting our
       support. Sometimes we leave features out on purpose to keep the project small.

In our server environment, we use DNS for Blue-Green deployment routing.  Since extremely active connections never go idle, they are never torn down and they never re-resolve DNS.  Thus the server never changes the environment it is calling.  Can a Max Connection Age be added to the Connection/Connection Pool?   

We have a potential work around using a Network Interceptor.  It feels hacky since we're messing with connections, casting objects and closing sockets.

```java
new Interceptor() {
    final ConcurrentHashMap<Integer, Long> CONNECTION_LIFETIME_MAP = new ConcurrentHashMap<>();
    final Long maxAge = TimeUnit.SECONDS.toMillis(2);

    @Override
    public Response intercept(Chain chain) throws IOException {

        Response response = chain.proceed(chain.request());

        Connection connection = chain.connection();
        if (connection != null && connection instanceof RealConnection) {
            RealConnection realConnection = (RealConnection) connection;
            int hashCode = realConnection.hashCode();
            Long current = System.currentTimeMillis();

            Long connectionStartTime = CONNECTION_LIFETIME_MAP.putIfAbsent(hashCode, current);
            if (connectionStartTime != null && current - connectionStartTime > maxAge) {
                realConnection.noNewStreams = true;
                if (realConnection.allocations.size() <= 1) {
                    CONNECTION_LIFETIME_MAP.remove(hashCode);
                    Socket socket = connection.socket();
                    Util.closeQuietly(socket);
                } 
            } 
        }
        return response;
    }
}
```

Thanks
Peter

**Comment by swankjesse** [comment]
I don’t think this is a thing. What do you do for browser user-agents?

Instead, servers should send `Connection: close` when they’re going out of rotation.

**Comment by pdavidson** [comment]
When we do a blue/green deploy we change the CName from pointing to ELB A (Elastic Load Balancer) to point to ELB B.  Since the connection using okhttp is coming from a very active service, the load balancer idle timeout is not hit to close the connection, nor is the okhttp idle timeout hit to close the connection.  Thus, traffic is sent to ELB A until we restart the very active service.  We typically do not tear down the inactive load balancer and leave it in an idle state.  We always run the risk of an external consumer hitting the old ELB A, but most traffic switches over within minutes.

**Comment by pdavidson** [comment]
This is topology is based on the amazon whitepaper https://d0.awsstatic.com/whitepapers/AWS_Blue_Green_Deployments.pdf

**Comment by swankjesse** [comment]
What do browsers do?

**Comment by pdavidson** [comment]
Browsers and other clients with keep alive eventually go idle and hit an idle timeout either in the client or on the ELB.  Our servers making multiple req's/sec never go idle, thus never hit the idle timeout.

**Comment by swankjesse** [comment]
I think this is best implemented as a custom interceptor.
