### ISSUE TITLE
Remove unnecessary branches

### ISSUE THREAD

**Issue by PromanSEW** [square/okhttp#3524]
There are 74 branches, most of active branches are merged PRs.
What about removing them?

**Comment by yschimke** [comment]
@JakeWharton Low priority but I'm OCD.  Are you for keeping any of the jw/ branches, if not I'll prune the non version branches.

![image](https://user-images.githubusercontent.com/231923/29601652-7ebadc2c-87d4-11e7-90f2-faf12cc19078.png)

**Comment by JakeWharton** [comment]
Feel free
