### ISSUE TITLE
Certificate Pinning not working for Android versions below 6

### ISSUE THREAD

**Issue by pKoerfer** [square/okhttp#3526]
Hello Square Team,

we are using certificate Pinning for securing the communication with our backend systems. We now have the problem that the Pinning is no longer working, meaning a 'Man in the middle' attack is possible.

This occurs with various okhttp versions in combination with retrofit. We are using the correct public keys from the backend systems.

Our pinning is implemented as follows:

`public CertificatePinner provideCertificatePinner() {
        Log.d(LOG_TAG, "Creating CertificatePinner");
        final CertificatePinner.Builder builder = new CertificatePinner.Builder();
        builder.add("www.url.com", "sha256Key");
        return builder.build();
    }`

`public OkHttpClient provideOkHttpClient(CertificatePinner pinner) {
        Log.d(LOG_TAG, "Creating OkHttpClient");
        final OkHttpClient.Builder clientBuilder = new OkHttpClient().newBuilder();
        clientBuilder.certificatePinner(provideCertificatePinner);
        clientBuilder.connectTimeout(BuildConfig.CONNECTION_TIMEOUT, TimeUnit.MILLISECONDS);
        clientBuilder.writeTimeout(BuildConfig.WRITE_TIMEOUT, TimeUnit.MILLISECONDS);
        clientBuilder.readTimeout(BuildConfig.CONNECTION_TIMEOUT, TimeUnit.MILLISECONDS);
        return clientBuilder.build();
    }`

We have tried the following things:
forcing the usage of TLS v1.2
`ConnectionSpec spec = new ConnectionSpec.Builder(ConnectionSpec.MODERN_TLS)  
    .tlsVersions(TlsVersion.TLS_1_2)
    .cipherSuites(
          CipherSuite.TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,
          CipherSuite.TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,
          CipherSuite.TLS_DHE_RSA_WITH_AES_128_GCM_SHA256)
    .build();`

And implementing a custom SSLSocketFactory forcing the usage of TLS v1.2 in Version under AN 4.1 according to: [https://github.com/square/okhttp/issues/2372](url)

We also tried to use different okhttp versions (3.4.0 => 3.8.1)

So we are not sure what causes this issue.

Best regards
Pascal

**Comment by swankjesse** [comment]
Could you provide a full executable example? It works for us!

**Comment by pKoerfer** [comment]
We found out that the 'not working' certificate pinning wasn´t caused by OKHTTP, it was primarily caused by misconfigurations on client side. 
I am very sorry to have bothered you falsely

best regards

Pascal

**Comment by eltonjhony** [comment]
> We found out that the 'not working' certificate pinning wasn´t caused by OKHTTP, it was primarily caused by misconfigurations on client side.
> I am very sorry to have bothered you falsely
> 
> best regards
> 
> Pascal

Do you have more details about the issues that was happening in client side? I'm facing the same issue described by you.

**Comment by pKoerfer** [comment]
It was really embarrassing to be honest. The problem was that we've configured everything but through refactoring we've forgot to actually set the certificate pinning.
Regards Pascal
