### ISSUE TITLE
RealWebSocket.close() throws IllegalArgumentException when code is 0

### ISSUE THREAD

**Issue by Egorand** [square/okhttp#3531]
In the Javadoc for `WebSocket.close()`:

```
@param code Status code as defined by <a href="...">Section 7.4 of RFC 6455</a> or {@code 0}.
```

When doing the following:

```java
WebSocket webSocket = okHttpClient.newWebSocket(request, wsListener);
webSocket.close(0, "Bye!");
```

It throws:

```java
java.lang.IllegalArgumentException: Code must be in range [1000,5000): 0

	at okhttp3.internal.ws.WebSocketProtocol.validateCloseCode(WebSocketProtocol.java:120)
	at okhttp3.internal.ws.RealWebSocket.close(RealWebSocket.java:399)
	at okhttp3.internal.ws.RealWebSocket.close(RealWebSocket.java:395)
```

It's not clear what `0` would mean anyway, the [RFC](https://tools.ietf.org/html/rfc6455#section-7.4.2) states that this code is not used. Does it make sense to just fix the Javadoc?

**Comment by JakeWharton** [comment]
It may have been changed after running the autobahn test suite. Doss the
commit history offer any answers? I can look later otherwise.

**Comment by Egorand** [comment]
I found c8dbcce that adds `validateCloseCode(code)` to `close()`

**Comment by yschimke** [comment]
WebSocketWriter handles this and tests expect it

```
if (code != 0) {
        validateCloseCode(code);
}
```

e.g. https://github.com/square/okhttp/blob/802c029b82672ea90534e8da1bd42100c194aca9/okhttp-tests/src/test/java/okhttp3/internal/ws/WebSocketWriterTest.java#L271

```
  @Test public void clientEmptyClose() throws IOException {
    clientWriter.writeClose(0, null);
    assertData("888060b420bb");
  }
```

**Comment by yschimke** [comment]
I think we agreed to just change the docs https://github.com/square/okhttp/pull/3540
