### ISSUE TITLE
Feature Request - IOException in MockResponse

### ISSUE THREAD

**Issue by mrcosta** [square/okhttp#3533]
**Problem**: try to unit test the scenario where 
```java
client.newCall(request).execute()
```
would throw an IOException

I wonder if is possible to have some possibility to create a MockResponse that would do this. Ok, if I got right the call under the test is done to a pseudo server, so that wouldn't be possible and I think there is no way to put something in the response body or the headers that would force the exception, right?

![coverage](https://user-images.githubusercontent.com/4819516/29501826-c587539e-8601-11e7-951e-782ba8795c37.png)

**Comment by JakeWharton** [comment]
Use a socket policy to close the socket after the headers and you'll get an
IOException

**Comment by mrcosta** [comment]
Thank you @JakeWharton. Much better now:

![coverage](https://user-images.githubusercontent.com/4819516/29528818-c32da5a4-8673-11e7-9362-4cb7345f324c.png)
