### ISSUE TITLE
onPing/onPong event

### ISSUE THREAD

**Issue by miladrasooli** [square/okhttp#3538]
Hi,
I was wondering If there is a way to receive onPing/onPong events in websocket to handle disconnect and reconnects?
Thanks

**Comment by yschimke** [comment]
Beyond OkHttpClient.pingInterval are you wanting these surfaced as events that you control, or just be notified of?

Hopefully the existing ping code inside websockets is detecting disconnects and sending your listener an event via WebSocketListener.onFailure

**Comment by miladrasooli** [comment]
Currently I'm using another websocket library which notifies the user of  Pings which the client receives from the server (onPingFrame = Called when a ping frame was received. ) , I want to switch to OKHttp3 instead of that one. I just need to be notified if the server is sending Ping frame and the client is receiving it. 

This is the library I'm using now:
https://github.com/TakahikoKawasaki/nv-websocket-client

**Comment by JakeWharton** [comment]
But why do you need to be notified? As Yuri said, we detect timeouts
automatically.

**Comment by miladrasooli** [comment]
In the mentioned Library which I'm using the lib can not detect disconnects immediately so I have to save last ping time on ping event to disconnect the socket manually if it doesn't receive ping frame for 2 minutes. I noticed OKHttp client is doing much better but I need to be sure of that

**Comment by yschimke** [comment]
That doesn't seem like a compelling reason to make a change to public API.  Can you test with a locally modified build of OkHttp until you are satisfied that it does what it says on the tin?

**Comment by JakeWharton** [comment]
And if it doesn't, that's a bug we can fix! But I agree this isn't a
compelling reason to expose it.

**Comment by yschimke** [comment]
@miladrasooli - closing, please reopen if you want to continue the discussion of the value, but it's very unlikely to change.

**Comment by nlovrencic** [comment]
@JakeWharton as https://tools.ietf.org/html/rfc6455#page-37 says " A Ping frame MAY include "Application data" - how do you get this data from okhttp if you are not notified when ping/pong frame is received?

**Comment by swankjesse** [comment]
Pings are not available in OkHttp’s web sockets APIs. If you need em, we can't help you.

**Comment by fabioyy** [comment]
I have a good reason for that, I want to measure latency. 
as IOS libraries support this. we will have a long time ( as always in android ) to workaround this.

**Comment by yschimke** [comment]
You can always write these events as First class Websocket messages.
