### ISSUE TITLE
Run CI tests in JDK 8 without ALPN support

### ISSUE THREAD

**Issue by yschimke** [square/okhttp#3542]
Since this is a common situation when using OkHttp as a desktop/server library, it is useful to run tests without ALPN support.

Strategies for HTTP/2 specific tests

1) Make tests handle the different code paths.
2) Use Junit assumptions to shortcircuit if Platform does not support HTTP/2.  Should this be part of the public Platform API?

I'd suggest the latter.

**Comment by swankjesse** [comment]
Reviewing this, I think our best strategy now is to encourage our users to get either Java 11 or Conscrypt, both of which have ALPN.

**Comment by yschimke** [comment]
Java 8 is a supported LTS for quite a long time.  So maybe this approach should replace and flush out issues https://github.com/square/okhttp/issues/4358

**Comment by yschimke** [comment]
supported now
