### ISSUE TITLE
aapt uncompress the publicsuffixes.gz that makes my app crash

### ISSUE THREAD

**Issue by shanghuibo** [square/okhttp#3568]
I used aapt to repack my apk and I found that the publicsuffixeds.gz in apk was uncompressed by aapt. My app crashed as java.lang.IllegalStateException: Unable to load publicsuffixes.gz resource from the classpath. Any idea for this problem?

aapt commands:
unzip ./origin.apk -d ./repack_package/unzip
aapt p -F ./repack_package/repacked.apk ./repack_package/unzip

**Comment by dave-r12** [comment]
OkHttp includes a resource called `publicsuffixes.gz` that is used for [public suffixes](https://publicsuffix.org/). Please make sure to include that resource.

**Comment by shanghuibo** [comment]
the origin apk has the resource called publicsuffixes.gz. When I unzip the origin apk and repackage it with aapt, the resource was uncompressed.

**Comment by swankjesse** [comment]
Could you report a bug against the aapt maintainers? They’re the ones who will be able to fix this.
