### ISSUE TITLE
[Feature Request] - RequestBody supports InputStream 

### ISSUE THREAD

**Issue by jaredsburrows** [square/okhttp#3585]
I would like to submit a PR to add support for `InputStream`s in the `RequestBody` class. As of now, `RequestBody` supports the following:

 - `create(MediaType contentType, String content) `
 - `create(MediaType contentType, ByteString content)`
 - `create(MediaType contentType, byte[] content)`
 - `create(MediaType contentType, byte[] content,
      final int offset, final int byteCount)`
 - `create(MediaType contentType, File file)`

I would like to go one step further and add support for `InputStream`:
 - `create(MediaType contentType, Inputream inputStream)`

Similar to https://stackoverflow.com/a/25384793: 
```
  public static RequestBody create(final @Nullable MediaType contentType, final InputStream inputStream) {
    if (inputStream == null) throw new NullPointerException("inputStream == null");

    return new RequestBody() {
      @Override public @Nullable MediaType contentType() {
        return contentType;
      }

      @Override public long contentLength() {
        return inputStream.available() == 0 ? -1 : inputStream.available();
      }

      @Override public void writeTo(BufferedSink sink) throws IOException {
        Source source = null;
        try {
          source = Okio.source(inputStream);
          sink.writeAll(source);
        } finally {
          Util.closeQuietly(source);
        }
      }
    };
  }
```

This would be nice to have since `Okio.source` support both `File` and `InputStream`.

**Comment by JakeWharton** [comment]
A RequestBody occasionally needs to be written multiple times, which this
would not allow. The current overloads all create instances which support
this, and I think we intentionally want to make it hard to create one that
does not support this.

**Comment by jaredsburrows** [comment]
Are `RequestBody`s written multiple times on retries? 

What would you suggest for `contentResolver.openInputStream(uri)`? Save it to a file first then use `create(MediaType contentType, File file)`?  Even that uses `Okio.source` when uses a `FileInputStream`.

**Comment by JakeWharton** [comment]
Inside of writeTo call that method and then call
sink.writeAll(Okio.source(steam)).

**Comment by swankjesse** [comment]
Also, request bodies may be written zero times, in which case this would leak the input stream.

**Comment by jaredsburrows** [comment]
@swankjesse Maybe I could pass a `Uri` instead of `InputStream` in the class to prevent leaking using.

@JakeWharton If I call `contentResolver.openInputStream(uri)` inside of `writeTo`, how do I update the `long contentLength()` before the request is made?

**Comment by JakeWharton** [comment]
OkHttp isn't an Android library and can't reference Uri. Use -1 for length.

**Comment by jaredsburrows** [comment]
@JakeWharton I know it is not an Android library. I figured after the first comment, I would have to keep this code locally and not be able to make a PR. Something like this: 
```
public class InputStreamRequestBody extends RequestBody {
    private final InputStream inputStream;
    private final MediaType contentType;

    public InputStreamRequestBody(MediaType contentType, InputStream inputStream) {
        if (inputStream == null) throw new NullPointerException("inputStream == null");
        this.contentType = contentType;
        this.inputStream = inputStream;
    }

    @Nullable
    @Override
    public MediaType contentType() {
        return contentType;
    }

    @Override
    public long contentLength() throws IOException {
        return inputStream.available() == 0 ? -1 : inputStream.available();
    }

    @Override
    public void writeTo(@NonNull BufferedSink sink) throws IOException {
        Source source = null;
        try {
            source = Okio.source(inputStream);
            sink.writeAll(source);
        } finally {
            Util.closeQuietly(source);
        }
    }
}
```

Based on your changes, @JakeWharton, to be changed to handle `Uri`:
```
public class InputStreamRequestBody extends RequestBody {
    private final MediaType contentType;
    private final ContentResolver contentResolver;
    private final Uri uri;

    public InputStreamRequestBody(MediaType contentType, ContentResolver contentResolver, Uri uri) {
        if (uri == null) throw new NullPointerException("uri == null");
        this.contentType = contentType;
        this.contentResolver = contentResolver;
        this.uri = uri;
    }

    @Nullable
    @Override
    public MediaType contentType() {
        return contentType;
    }

    @Override
    public long contentLength() throws IOException {
        return -1;
    }

    @Override
    public void writeTo(@NonNull BufferedSink sink) throws IOException {
        sink.writeAll(Okio.source(contentResolver.openInputStream(uri)));
    }
}
```

**Comment by JakeWharton** [comment]
Ah, yes. Definitely do that to make it reusable in your own code. Don't
forget try-with-resources:

try (Source source = Okio.source(contentResolver.openInputStream(uri))) {
  sink.writeAll(source);
}

**Comment by jaredsburrows** [comment]
@JakeWharton Based on your first comment, I guess I will close this because using `TypeInputStream` directly does not work very well with the current implementation of `RequestionBody`.

**Comment by neiljaywarner** [comment]
@JakeWharton @jaredsburrows 3 years later. what's the best way to go from a android uri to okhttp "put"?

**Comment by jemshit** [comment]
[My take](https://stackoverflow.com/a/67252049/3736955) on this.

**Comment by yschimke** [comment]
@jemshit Thanks, we can possibly make this some samples for documentation inside the project.

@swankjesse had the most conniving argument for why we don't support this inbuilt

> Also, request bodies may be written zero times, in which case this would leak the input stream.
