### ISSUE TITLE
Intermittent Call Failure With BLE on Kindle Fire 7

### ISSUE THREAD

**Issue by djlitvak** [square/okhttp#3587]
I have been working through an issue for the last few days and believe that I have figured out what is going on. To be honest, I'm not really sure it falls on okhttp or not, but I figured I would post something here regardless.

I have an app that has intermittent call failure (`SocketTimeOut`) that only exists on Kindle Fire 7. The calls all work on Kindle Fire 8 and all other Android phones/tablets that we have tested. We have also found that the calls only fail (`SocketTimeOut`) when BLE is in use. So if BLE is not in use, then the calls do not fail - even on the Fire 7.

I have a [post on StackOverflow](https://stackoverflow.com/questions/46079666/okhttp3-sockettimeout-only-on-specific-call) searching for workarounds.

The reason I am posting here is that once one call fails, the remaining calls are much much more likely to fail. I have attempted to reinitialize our `OkHttpClient` but the calls still fail. The only solution seems to be to close the app and then re-open it.

I guess my thoughts are that adding some feature to okhttp that releases all sockets and recreates them all. Some built in reinitialization to "ungunk" our "gunked" connection.

**Comment by yschimke** [comment]
From your stackoverflow post - this is with 3.8.1.

There is at least one fix for similar problems in 3.9.0, so trying to reproduce with 3.9.0 would be helpful.

https://github.com/square/okhttp/commit/d3d4a1e6332cb9fa49d4aad2eca93a650ce39cc2

**Comment by djlitvak** [comment]
I will carve out a few minutes later today to test on 3.9.0 . Thanks for bringing that to my attention.

**Comment by yschimke** [comment]
please reopen if its still an issue with 3.9.0
