### ISSUE TITLE
OkHttp - ProtocolException

### ISSUE THREAD

**Issue by roktoshl** [square/okhttp#3589]
Im trying to fetch data from my server with Android 8 (26 Oreo) and I get the following error:

```
java.net.ProtocolException: unexpected end of stream 
at okhttp3.internal.http1.Http1Codec$FixedLengthSource.read(Http1Codec.java:398)
at okio.RealBufferedSource.readAll(RealBufferedSource.java:163)
at retrofit2.Utils.buffer(Utils.java:304)
at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:204)
at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:112)
at okhttp3.RealCall$AsyncCall.execute(RealCall.java:153)
at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
at java.lang.Thread.run(Thread.java:764)
```

Im using Retrofit 2.3.0 and OkHttp 3.9.0. The strange thing is that this error only happens on API 26 Oreo and not on any previous APIs, I get this error randomly, sometimes yes, sometimes not.

The call that I make is very standard:

```
TestInterface api = retrofit.create(TestInterface.class);
Call<List<Post>> call = api.getFeed(0, 0, "9");
call.enqueue(new Callback<List<Post>>() {
	@Override
	public void onResponse(Call<List<Post>> call, Response<List<Post>> response) {
		Log.i(TAG, "[app] onResponse");
	}
	@Override
	public void onFailure(Call<List<Post>> call, Throwable t) {
		Log.i(TAG, "[app] onFailure: ", t);
	}
});
```

**Comment by yschimke** [comment]
There is not much to go on here.  The most obvious reason is that the server is lying about the Content-Length.

As for why it triggers on Android 8, I'm not sure, there is not enough to go on from your report.  

My suggestion would be to reproduce with OkHttp only on Android 8 and print out the headers and the body bytes and see why you are not getting enough bytes in the response.

**Comment by roktoshl** [comment]
@yschimke That was my initial thought also, about Content-Length header. I will try to come back with more input.

**Comment by roktoshl** [comment]
This is an example from of my headers, content length seems to be ok...btw im using Django Rest Framework for my server side.

Allow →GET, HEAD, OPTIONS
Connection →close
Content-Language →en
Content-Length →3277
Content-Type →application/json
Date →Sat, 09 Sep 2017 14:58:38 GMT
Server →gunicorn/19.7.0
Vary →Accept, Accept-Language, Cookie
X-Frame-Options →SAMEORIGIN`

**Comment by yschimke** [comment]
What about the body length, does it match (3277 bytes)?

**Comment by roktoshl** [comment]
@yschimke Yes, it does match 3277 bytes (or 3277 octets - 8 bit).

**Comment by roktoshl** [comment]
@yschimke Any news on this? Content-length works completely fine.

**Comment by yschimke** [comment]
I don't have much to go on from this report at the moment.  At reproducing test case would be great.  Failing that an actual example request I can test with (privately DM me if needed) would also make it a lot clearer.

**Comment by roktoshl** [comment]
@yschimke Hey I have sent you an email (the one in your github profile) containing the API url :) hope it helps.

**Comment by roktoshl** [comment]
@yschimke I should also mention that im testing Android 8 on an emulator and not on an actual device.

**Comment by yschimke** [comment]
As we discussed over email. everything looked ok from a desktop test. i don't have any quick options. but am going to think about how to make it easier to reproduce this sort of problem.

**Comment by yschimke** [comment]
I tried the request you supplied (via email) in an Android 8 emulator.  Still couldn't reproduce.

Is it ok if I close until you can provide a reproduction?
