### ISSUE TITLE
javax.net.ssl.SSLException: Read error: ssl=0x8ad9c2c0: I/O error during system call, Connection reset by peer

### ISSUE THREAD

**Issue by hasretsariyer** [square/okhttp#3594]
SSLException

I try to make a http post request. Okhttp throws an sslexception. So I add some codes to trust all certificates.

`ResponseBody body = response.body();
int statusCode = response.code();
byte[] bodyBytes = body.bytes(); // **The exception occurs on this line**`

Okhttp version is here 

> compile 'com.squareup.okhttp3:okhttp:3.8.1'

Trace is here:
`javax.net.ssl.SSLException: Read error: ssl=0x8797a780: I/O error during system call, Connection reset by peer
09-11 11:56:44.811 25238-29849/ D/OkHttp:     at com.android.org.conscrypt.NativeCrypto.SSL_read(Native Method)
09-11 11:56:44.811 25238-29849/ D/OkHttp:     at com.android.org.conscrypt.OpenSSLSocketImpl$SSLInputStream.read(OpenSSLSocketImpl.java:758)
09-11 11:56:44.811 25238-29849/ D/OkHttp:     at okio.Okio$2.read(Okio.java:139)
09-11 11:56:44.811 25238-29849/ D/OkHttp:     at okio.AsyncTimeout$2.read(AsyncTimeout.java:237)
09-11 11:56:44.811 25238-29849/ D/OkHttp:     at okio.RealBufferedSource.read(RealBufferedSource.java:46)
09-11 11:56:44.811 25238-29849/ D/OkHttp:     at okhttp3.internal.http1.Http1Codec$FixedLengthSource.read(Http1Codec.java:384)
09-11 11:56:44.812 25238-29849/ D/OkHttp:     at okio.Buffer.writeAll(Buffer.java:1005)
09-11 11:56:44.812 25238-29849/ D/OkHttp:     at okio.RealBufferedSource.readByteArray(RealBufferedSource.java:107)
09-11 11:56:44.812 25238-29849/ D/OkHttp:     at okhttp3.ResponseBody.bytes(ResponseBody.java:136)`

 ```
X509TrustManager trustManager = new X509TrustManager() {
    @Override
    public void checkClientTrusted(java.security.cert.X509Certificate[] chain, String authType) throws CertificateException {
    }

    @Override
    public void checkServerTrusted(java.security.cert.X509Certificate[] chain, String authType) throws CertificateException {
    }

    @Override
    public java.security.cert.X509Certificate[] getAcceptedIssuers() {
        return new X509Certificate[]{};
    }
};

final SSLContext sslContext = SSLContext.getInstance("SSL");
sslContext.init(null, trustAllCerts, new java.security.SecureRandom());
sslSocketFactory = sslContext.getSocketFactory();
clientBuilder.sslSocketFactory(sslSocketFactory, trustManager);

clientBuilder.hostnameVerifier(new HostnameVerifier() {
    @Override
    public boolean verify(String hostname, SSLSession session) {
        return true;
    }
});
client = clientBuilder.build();
client.retryOnConnectionFailure();
```

I think this is not a server side problem. I just tried, volley works for same request.

**Comment by hemanthkaipaa** [comment]
I'm also getting the same error, since 5 days. I figured out but didn't solved my problem.

Are you sending header encrypted data to server.?
try not passing header data.

**Comment by hasretsariyer** [comment]
I don't send any header data. My request is here:

`Request request = new Request.Builder().url(Url)
                .post(RequestBody.create(MediaType.parse("application/json; charset=utf-8"), text)).build();`

**Comment by yschimke** [comment]
This looks like a SSL handshake failure before the trustmanager or hostname verifier get involved.  I suggest posting on stackoverflow with a reproducible example, but it doesn't look like it is a bug in OkHttp

**Comment by NayaneshGupte** [comment]
@yschimke How does this work with Volley then ?
@hasretsariyer  have you found the solution ?
I have put it on SO but still not able to find solution -
https://stackoverflow.com/questions/58803642/okhttp3-hostnameverifier-caused-by-javax-net-ssl-sslexception-read-error-ssl
