### ISSUE TITLE
NullPointerException in HttpUrl.class

### ISSUE THREAD

**Issue by MS893** [square/okhttp#3597]
IT IS NOT REALLY A BUG, BUT...

There is no check if a value is null whille buiding a body for a POST
`            RequestBody formBody = new FormBody.Builder()
                    .add("value", value)
                    .build();
`
if value is null, there is a :
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference at okhttp3.HttpUrl.canonicalize(HttpUrl.java:1751)

My app doesn't stop after this crash and remains in a loop.

Would it be possible to throw a NullPointerException ?

**Comment by swankjesse** [comment]
Yeah, definitely. Wanna send a pull request?

**Comment by MS893** [comment]
Yes I do

**Comment by yschimke** [comment]
Was this PR related to this? https://github.com/square/okhttp/pull/3598

**Comment by swankjesse** [comment]
This was fixed.

**Comment by MS893** [comment]
++++++++++ !

**Comment by MarkRaoAndroid** [comment]
Okhttp request parameters can not be empty, check your parameters
