### ISSUE TITLE
recvfrom failed: ECONNRESET (Connection reset by peer)

### ISSUE THREAD

**Issue by yangxuqiang9** [square/okhttp#3604]
What kind of issue is this?

 - [ ] Question. This issue tracker is not the place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use Stack
       Overflow. https://stackoverflow.com/questions/tagged/okhttp

 - [ ] Bug report. If you’ve found a bug, spend the time to write a failing test. Bugs with tests
       get fixed. Here’s an example: https://gist.github.com/swankjesse/981fcae102f513eb13ed

 - [ ] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
       already exists! Don’t send pull requests to implement new features without first getting our
       support. Sometimes we leave features out on purpose to keep the project small.

**Comment by yschimke** [comment]
Is this a bug report? It seems like you got an IO exception in an app using the network.  Is there something more to it?

**Comment by yangxuqiang9** [comment]
What is the reason for this unusual occurrence?I use okhttp to send requests。But the return result is only the wrong line

**Comment by yschimke** [comment]
Please reopen if you can provide a reproduction or a lot more detail e.g. stacktrace and which specific devices and hosts cause it.  n.b. I can send you a sample app to test with if it helps.
