### ISSUE TITLE
Caused by: java.net.ProtocolException: Unexpected status line: HTTP/0.0 503 Service Unavailable

### ISSUE THREAD

**Issue by glassxx** [square/okhttp#3608]
Bug report. 

it  perhaps a bug.  I dont know how to write a bug test,  forgive me.

the error log :

`at rx.Observable$2.call(Observable.java:233)
09-14 08:25:02.704 16946-16946/com.glassx.demo W/System.err:     at rx.Observable$2.call(Observable.java:225)
09-14 08:25:02.704 16946-16946/com.glassx.demo W/System.err:     at rx.Observable$2.call(Observable.java:233)
09-14 08:25:02.704 16946-16946/com.glassx.demo W/System.err:     at rx.Observable$2.call(Observable.java:225)
09-14 08:25:02.704 16946-16946/com.glassx.demo W/System.err:     at rx.Observable.unsafeSubscribe(Observable.java:8741)
09-14 08:25:02.704 16946-16946/com.glassx.demo W/System.err:     at rx.internal.operators.OperatorSubscribeOn$1.call(OperatorSubscribeOn.java:94)
09-14 08:25:02.704 16946-16946/com.glassx.demo W/System.err:     at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
09-14 08:25:02.704 16946-16946/com.glassx.demo W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
09-14 08:25:02.705 16946-16946/com.glassx.demo W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
09-14 08:25:02.705 16946-16946/com.glassx.demo W/System.err:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
09-14 08:25:02.705 16946-16946/com.glassx.demo W/System.err:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
09-14 08:25:02.705 16946-16946/com.glassx.demo W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
09-14 08:25:02.705 16946-16946/com.glassx.demo W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
09-14 08:25:02.705 16946-16946/com.glassx.demo W/System.err:     at java.lang.Thread.run(Thread.java:818)
09-14 08:25:02.705 16946-16946/com.glassx.demo W/System.err: Caused by: java.net.ProtocolException: Unexpected status line: HTTP/0.0 503 Service Unavailable
09-14 08:25:02.706 16946-16946/com.glassx.demo W/System.err:     at okhttp3.internal.http.StatusLine.parse(StatusLine.java:69)
09-14 08:25:02.706 16946-16946/com.glassx.demo W/System.err:     at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:189)
09-14 08:25:02.706 16946-16946/com.glassx.demo W/System.err:     at okhttp3.internal.connection.RealConnection.createTunnel(RealConnection.java:322)
09-14 08:25:02.706 16946-16946/com.glassx.demo W/System.err:     at okhttp3.internal.connection.RealConnection.connectTunnel(RealConnection.java:196)
09-14 08:25:02.706 16946-16946/com.glassx.demo W/System.err:     at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:144)
09-14 08:25:02.706 16946-16946/com.glassx.demo W/System.err:     at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:186)
09-14 08:25:02.706 16946-16946/com.glassx.demo W/System.err:     at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:121)
09-14 08:25:02.706 16946-16946/com.glassx.demo W/System.err:     at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:100)
09-14 08:25:02.706 16946-16946/com.glassx.demo W/System.err:     at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
09-14 08:25:02.706 16946-16946/com.glassx.demo W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
09-14 08:25:02.706 16946-16946/com.glassx.demo W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
09-14 08:25:02.706 16946-16946/com.glassx.demo W/System.err:     at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
09-14 08:25:02.706 16946-16946/com.glassx.demo W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
09-14 08:25:02.706 16946-16946/com.glassx.demo W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
09-14 08:25:02.706 16946-16946/com.glassx.demo W/System.err:     at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
09-14 08:25:02.706 16946-16946/com.glassx.demo W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
09-14 08:25:02.707 16946-16946/com.glassx.demo W/System.err:     at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
09-14 08:25:02.707 16946-16946/com.glassx.demo W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
09-14 08:25:02.707 16946-16946/com.glassx.demo W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
09-14 08:25:02.707 16946-16946/com.glassx.demo W/System.err:     at com.glassx.net.interceptor.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:50)
09-14 08:25:02.707 16946-16946/com.glassx.demo W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
09-14 08:25:02.707 16946-16946/com.glassx.demo W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
09-14 08:25:02.707 16946-16946/com.glassx.demo W/System.err:     at com.glassx.net.interceptor.ParamsInterceptor.intercept(ParamsInterceptor.java:55)
09-14 08:25:02.707 16946-16946/com.glassx.demo W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
09-14 08:25:02.707 16946-16946/com.glassx.demo W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
09-14 08:25:02.707 16946-16946/com.glassx.demo W/System.err:     at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:179)
09-14 08:25:02.707 16946-16946/com.glassx.demo W/System.err:     at okhttp3.RealCall.execute(RealCall.java:63)
09-14 08:25:02.707 16946-16946/com.glassx.demo W/System.err:     at com.glassx.net.GlassxNetClient$CallOnSubscribe.call(GlassxNetClient.java:278)
09-14 08:25:02.707 16946-16946/com.glassx.demo W/System.err: 	... 15 more`

thanks and forgive my poor  English !

**Comment by swankjesse** [comment]
This is working as intended. OkHttp works with HTTP/1.0, HTTP/1.1, and HTTP/2. There’s no support for HTTP/0.0.

**Comment by glassxx** [comment]
so, the reason is server reply me an  illegal  data ?  thanks  for your reply

**Comment by swankjesse** [comment]
Exactly.
