### ISSUE TITLE
Websocket connection blocks write to okio sink.

### ISSUE THREAD

**Issue by lDuffy** [square/okhttp#3609]
I'm writing an audio streaming websocket. It requires a bit of ceremony before the user can actually start streaming bytes so Ive been trying to use the okio Pipe class to buffer recorded audio while the connection is being made made. Im using the [PostStreamingWithPipe PipeBody](https://github.com/square/okhttp/blob/master/samples/guide/src/main/java/okhttp3/recipes/PostStreamingWithPipe.java)  example to store the Pipe's sink and source. I write to the Bufferedsink and when the connection is made, continue writing but also read from the BufferedSource 
    
    `static final class PipeBody extends RequestBody {
          private final Pipe pipe = new Pipe(8192);
          private final BufferedSink sink = Okio.buffer(pipe.sink());
          private final BufferedSource source = Okio.buffer(pipe.source());
    
         public BufferedSink sink() {
              return sink;
         }
         public int read(byte[] buffer) throws IOException {
            return source.read(buffer);
         }
     }`
  I have an audio manager class that kicks off recording to the sink with the user clicks record 

     ` public void startRecording() {
            record = getAudioRecorder();
            record.startRecording();
            byte[] buffer = getBuffer();
            body = new PipeBody();
            BufferedSink sink = body.getBuffer();

            new Thread(() -> {
                int bytesRead;
                while ((bytesRead = record.read(buffer, 0, buffer.length)) > -1) {
                    sink.write(buffer, 0, bytesRead);
                    sink.flush()
                    Log.d(TAG, "write: ");
                }
                try {
                    sink.close();
                } catch (IOException e) {
                    Log.e(TAG, "error: ", e);
                }
            }).start();
        }`

The webSocket is setup is as per the example using the webSocketListener, done on a separate thread. What Ive noticed is that when I initialize the webSocket and send my setup request, The audio manager thread block on sink.write() method. This corrupts the first second of audio from when the connection is being made as the audio record class is still recording to its buffer but the sink isn't capturing the audio. 

To fix this Ive gone with a different  approach of using a blockingQueue<ByteString> to store and stream the audio. I am curious to know though if you guys have any idea as to why BufferedSink was blocking in the first place?

**Comment by swankjesse** [comment]
Which version are you using? There’s no streaming in our websockets since we finalized the API in 3.5.0.

**Comment by lDuffy** [comment]
Thanks for the quick response. I'm using the version of okhttp in com.squareup.retrofit2:retrofit:2.3.0. I'm probably not using the term streaming correctly. This is a pared down version of my webSocket implementation

      `public class WebSocketListenerImpl extends WebSocketListener {

        private final OkHttpClient client;
        private final Request request;
        private WebSocket webSocket;

        public WebSocketListenerImpl(OkHttpClient client, Request request, SocketEventParser 
socketEventParser) {
            this.socketEventParser = socketEventParser;
            this.request = request;
            this.client = client;
        }

        @Override
        public void onMessage(WebSocket webSocket, String stringResponse) {
            Log.d(TAG, "onMessage: " + stringResponse);
            callback.onResponse(“”));
        }

        public <T extends ApiRequest> void send(String request) {
            init();
            Log.d(TAG, "send: " + request);
            webSocket.send(request);
        }

        private void init() {
            if (webSocket == null) {
                Log.d(TAG, "init: " + Thread.currentThread().getName());
                webSocket = client.newWebSocket(request, this);
            }
        }

        public void sendBytes(StreamRequestBody body) {
             new Thread(() -> {
                while (body.isRecording()) {
                    try {
                        webSocket.send(body.read());
                    } catch (InterruptedException e) {
                        Log.e(TAG, "sendBytes: ", e);
                    }
                   Log.d(TAG, "write: ");
                }
                webSocket.send(ByteString.of(new byte[] { 4 }));
            }).start();
        }

    }`

the api that uses this socket will call send(String request) two times and wait for responses to setup the connection. when the 'handshake'  is made call the sendBytes(StreamRequestBody body) method and continuously send bytesString's to the server while the audioRecord class is recording audio

**Comment by swankjesse** [comment]
Gotcha. I think you just need to size your pipe to be larger. It blocks when it's full.

**Comment by lDuffy** [comment]
yep. looks like thats what the issue was. Thanks!

**Comment by ksperling** [comment]
@swankjesse Was the removal of streaming sends an intentional decision, or is this a feature tha might come back? We're currently still on 3.4.x and using a custom `RequestBody` implementation that serializes protobufs containing large amounts of binary data on the fly, to avoid that binary data having to be copied.

**Comment by swankjesse** [comment]
Streaming websocket messages aren’t coming back.

**Comment by swankjesse** [comment]
... that said, if you write to an Okio buffer and call `snapshot()` data copying will be minimal.

**Comment by sanginovs** [comment]
@swankjesse I'm considering to contribute to this project. I was wondering whether you guys have any means of communication like Slack, IRC or smth? Thanks.

**Comment by crossle** [comment]
plz support websocket send byte[] not ByteString

**Comment by swankjesse** [comment]
@sanginovs – if you'd like to contribute please create a GitHub issue with the proposed bug or feature. Please don't start coding yet; most large contributions are rejected.

**Comment by sanginovs** [comment]
@swankjesse will do. thanks

**Comment by yschimke** [comment]
Doesn't seem like there is anything (active from us) to do here.
