### ISSUE TITLE
Parsing response headers with pagination links

### ISSUE THREAD

**Issue by rafaltrzcinski** [square/okhttp#3615]
Pagination could be handled by Links Headers in response, so header in response looks like:
`<https://api.my.com/v1/users?page=3>; rel="next", <https://api.my.com/v1/users?page=1>; rel="prev"`
Is there a way to handle this header to get values of links for specifeid `rel` value? `Headers` is array of Strings so i have to parse String...

**Comment by rafaltrzcinski** [comment]
Nice to have something similar to this:
https://github.com/whiskeysierra/elf/tree/master/limil -> handling links as separate objects
`Link self = HttpLink.parse("</alice>; rel=\"self\"; title=\"Alice\"")`

**Comment by JakeWharton** [comment]
Are these covered by one of the HTTP RFCs? My gut reaction is that this is out of scope for an HTTP client and should be handled by a higher layer of abstraction which also deals with the requested URLs and manages initiating requests for the next page. But if it's part of a spec then at least there's precedent to support it.

**Comment by rafaltrzcinski** [comment]
It's part of RFC:
https://tools.ietf.org/html/rfc5988

**Comment by JakeWharton** [comment]
So it's its own but not part of the HTTP ones.

My opinion is that this seems like it could be implemented in a nicely
scoped standalone library.

**Comment by swankjesse** [comment]
Agreed. Seems like something that'd be difficult to do well at our layer.
