### ISSUE TITLE
Fatal error with okhttp and Android 4.2.2

### ISSUE THREAD

**Issue by iHombre** [square/okhttp#3618]
This code leads to a fatal error at Android 4.2.2:
```
Request request = new Request.Builder()
                                        .url(URL)
                                        .build();
```
**signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr deadd00d**

**Comment by naturalwarren** [comment]
That's a pretty nasty native crash. Are you seeing this on a variety of manufactures or just one in particular?

**Comment by iHombre** [comment]
Emulator and real device.

**Comment by naturalwarren** [comment]
Which emulator and which device? Running the code you've provided doesn't `SEGSEV` on devices and emulators I use.

**Comment by yschimke** [comment]
reopen if you can provide a reproduction or more concrete information.

**Comment by arpitsingh21** [comment]
i am using api 19 on android emulator ,it returns illegalStateException but only devices below api 21 above that it is working .

 Interceptor REWRITE_CACHE_CONTROL_INTERCEPTOR = new Interceptor() {
            @Override
            public Response intercept(@NonNull Chain chain) throws IOException {


                Response originalResponse = chain.proceed(chain.request());  ****Getting Error Here****
                if (isNetworkAvailable(context)) {
                    int maxAge = 120; // read from cache for 120 seconds
                    return originalResponse.newBuilder()
                            .header("Cache-Control", "public, max-age=" + maxAge)
                            .build();
                } else {
                    int maxStale = 60 * 60 * 24 * 7; // tolerate 1-week stale
                    return originalResponse.newBuilder()
                            .header("Cache-Control", "public, only-if-cached, max-stale=" + maxStale)
                            .build();
                }
            }

        };
