### ISSUE TITLE
Please help me

### ISSUE THREAD

**Issue by wangguifa** [square/okhttp#3622]
.Can you help me see a question? I put the https certificate on the assets package. When the certificate expires，I would like to ignore the verification certificate.So i do this：

```
private void overLockCard() {
final TrustManager[] trustAllCerts = new TrustManager[]{new X509TrustManager() {
@override
public void checkClientTrusted(X509Certificate[] chain, String authType) throws CertificateException {

        }

        @Override
        public void checkServerTrusted(X509Certificate[] chain, String authType) throws CertificateException {

        }

        @Override
        public X509Certificate[] getAcceptedIssuers() {
            return new X509Certificate[0];
        }
    }};
    try {
        SSLContext sslContext = SSLContext.getInstance("TLS");
        sslContext.init(null, trustAllCerts, new SecureRandom());
        HostnameVerifier hostnameVerifier = new HostnameVerifier() {
            @Override
            public boolean verify(String hostname, SSLSession session) {
                return true;
            }
        };
        OkHttpClient.Builder builder = mOkHttpClient.newBuilder();
        builder.sslSocketFactory(sslContext.getSocketFactory());
        builder.hostnameVerifier(hostnameVerifier);
        builder.build();
    } catch (Exception e) {
        e.printStackTrace();
    }
}
```

But when I put the phone system time to change the time after the expiration of the certificate，The network request will appear as follows：
.bouncycastle.jce.exception.ExtCertPathValidatorException: Could not validate certificate: Certificate expired at Fri Feb 09 09:54:32 GMT+08:00 2018 (compared to Sat Sep 14 15:13:55 GMT+08:00 2019)
what should I do? Thank you very much.

If i use native httpsUrlConnection request，He can ignore the certificate,what should I do?

**Comment by yschimke** [comment]
Can I ask why you are doing this instead of failing the untrusted request, or just writing it such that you can renew your certificates as a regular quarterly or yearly process?

**Comment by wangguifa** [comment]
We have such a need：There is a certificate in my app,If the certificate is valid on the certificate,Then go to verify the certificate.If the certificate expires, the certificate is ignored.This is to prevent future certificate expired, but the user did not upgrade the new app when he can also use the app.If i use native httpsUrlConnection request，He can ignore the certificate.But when i use okhttp,He can not ignore the certificate.I do not know what to do to make okhttp ignore certificate validation.Can you help me ?thank you

**Comment by wangguifa** [comment]
”OkHttpClient.Builder builder = mOkHttpClient.newBuilder()” should be replacedmOkHttpClient = new OkHttpClient.Builder()
                ...
                .build();
Because i used the default,So it has failed,Thank you

**Comment by yschimke** [comment]
So I'm not clear why this will be a problem when that time actually comes?  I suspect you are trying to connect to the server which still sending the now (theoretically) expired certificate.  What certificate is the client sending?  I think everything is working as it should be if this is the case.

If you really want this, why not just use plaintext http?

In reality, surely you will have upgraded your server to use a different certificate by then. That new certificate will be accepted automatically as long as it can find an accepted certificate in the chain. 

Take a look at a random site greatist.com using a letsencrypt issued certificate, their certificate is only valid for 3 months, and a client should continue to accept it as long as it accepts either the Let's Encrypt certificate or the DST root CA.

https://www.ssllabs.com/ssltest/analyze.html?d=greatist.com&s=23.185.0.3&latest

I believe everything is working as it should and the SSL handshake *should* fail before the certificate chain is checked.

**Comment by wangguifa** [comment]
OK Thank you
