### ISSUE TITLE
Vulnerable Dependencies

### ISSUE THREAD

**Issue by TommyJ1994** [square/okhttp#3633]
**What kind of issue is this?**
Vulnerable Dependencies

Snyk Test Report:
https://snyk.io/test/github/square/okhttp/master%2Fokhttp

**Comment by JakeWharton** [comment]
The Apache HTTP code is a legacy bridge. I don't think there's any action
to take here, and I'd be surprised if anyone really uses it anymore.

**Comment by swankjesse** [comment]
I think of Apache HTTP client as both an _API_ and an _implementation_.

OkHttp doesn’t use the vulnerable implementation. Anyone who is using that implementation could avoid their vulnerabilities by using Apache’s API with OkHttp instead.
