### ISSUE TITLE
[Question] - Can I use okhttp client with endpoints with self-signed SSL certificates?

### ISSUE THREAD

**Issue by smadurange** [square/okhttp#3636]
I have a Java REST API that posts emails to a another web service using a url like http://18.67.890.00/email/sendsimple/ which works fine. However, once I try https://18.67.890.00/email/sendsimple/, the email doesn't get sent out, but I do not see any error from my Java API. The SSL certificate of the email API server is a self-signed one.

**Comment by yschimke** [comment]
Can you either provide reproducing code showing what you believe is a bug in behaviour, or consider posting on stackoverflow (again with sample code).  There are a lot of posts on stackoverflow showing how to use self signed certificates, but you should get a failure from okhttp anyway.

https://stackoverflow.com/questions/23103174/does-okhttp-support-accepting-self-signed-ssl-certs

https://stackoverflow.com/questions/tagged/okhttp3

Please reopen if you can provide a test case showing a bug.
