### ISSUE TITLE
MockWebServer request URL is wrong for proxy requests

### ISSUE THREAD

**Issue by swankjesse** [square/okhttp#3638]
For example, the request line might be

```
GET http://example.com/ HTTP/1.1.
```

**Comment by yschimke** [comment]
Won't fix. MockWebserver is not a priority for bugs in here.

**Comment by swankjesse** [comment]
Though I agree about most of the MockWebServer things, this is a real correctness issue. Should be an easy fix.

**Comment by zsp322** [comment]
Hi, team. I am willing to make a contribution here. It would be nice if I can have a little bit more detailed description of the ask.

**Comment by yschimke** [comment]
@zsp322 Thanks, but @swankjesse fixed this incidentally in https://github.com/square/okhttp/pull/6919
