### ISSUE TITLE
Method threw 'java.lang.NullPointerException' exception. Cannot evaluate okhttp3.HttpUrl$Builder.toString()

### ISSUE THREAD

**Issue by juntity** [square/okhttp#3639]
Method threw 'java.lang.NullPointerException' exception. Cannot evaluate okhttp3.HttpUrl$Builder.toString()
why？  I used in Retorfit

**Comment by JakeWharton** [comment]
Include the entire stacktrace or a failing test please.

**Comment by juntity** [comment]
`Retrofit ret = new Retrofit.Builder()
                .baseUrl("http://api.igootoo.com/")
                .addConverterFactory(GsonConverterFactory.create())
                .build();`
it's just wrong in baseUrl
@JakeWharton

**Comment by JakeWharton** [comment]
That is not enough information to reproduce or identify the problem.

**Comment by juntity** [comment]
I get this error where I used baseUrl(...) @JakeWharton 
can i talk to you in some chat tools

**Comment by JakeWharton** [comment]
No. Provide the full stacktrace or a sample which reproduces the problem.
