### ISSUE TITLE
maven 3.2.3 jdk 1.6 complie is error

### ISSUE THREAD

**Issue by beyondsmz** [square/okhttp#3644]
I want to compile okhttp in the environment of maven3.2.3 and jdk1.6, but I have been wrong. How can I solve this compilation problem ,plase

**Comment by JakeWharton** [comment]
We do not support JDK 6 which is old and has been marked as end of life. Our builds require JDK 8 or newer.

**Comment by beyondsmz** [comment]
OK   thanks!

**Comment by beyondsmz** [comment]
OK   thanks
