### ISSUE TITLE
W/System.err: remove failed: ENOENT (No such file or directory)

### ISSUE THREAD

**Issue by Qamar4P** [square/okhttp#3645]
W/System.err: remove failed: ENOENT (No such file or directory) : /data/user/0/com.abc.xyz/cache/picasso-cache/c1d640c64d6dfaba7ef9a9702c2e5ada.0

This issue doesn't allow to cache image using `Picasso` with `OkHttp3Downloader` so Picasso failed to load image using `.networkPolicy(NetworkPolicy.OFFLINE)` but load in normal online mode. What's the solution?

This is what @JakeWharton said [ref](https://github.com/square/picasso/issues/1486)
> Despite Picasso's name being included in the path, Picasso has nothing to do with this. These are coming from the underlying HTTP client which is managing the disk cache and Picasso has no control over it. It looks like the cache dir might have been cleared out from underneath the HTTP client which won't hurt anything.

**Comment by yschimke** [comment]
Could you provide sample code of the client setup and any code relevant to the cache instance or cache directory?

Ideally an example app that reproduces the problem.

Is there any chance you are modifying the files in the cache via some other mechanism? e.g. deleting manually?

**Comment by yschimke** [comment]
@swankjesse @JakeWharton is this normal anyway, https://developer.android.com/guide/topics/data/data-storage.html seems to suggest that Android will cleanup these cache files if it needs space.

**Comment by Qamar4P** [comment]
Simply doesn't cache some image at first try. I prefetch 50 images, two at a time to make user experience better. It works on second try. Don't know why, I didn't found it in emulator cache.

Application.onCreate
```
Picasso picasso = new Picasso.Builder(context)
                .downloader(new OkHttp3Downloader(context,Integer.MAX_VALUE))
                .build();
        Picasso.setSingletonInstance(picasso);
```
Gradle
    ```
compile 'com.squareup.picasso:picasso:2.5.2'
    compile 'com.squareup.okhttp3:okhttp:3.9.0'
    compile 'com.jakewharton.picasso:picasso2-okhttp3-downloader:1.1.0'
```
    
code
Picasso.with(context).load(imageUrl)
                    .memoryPolicy(MemoryPolicy.NO_CACHE).fetch(new Callback() {}

**Comment by JakeWharton** [comment]
They can be cleaned up from outside your app, yes. I'm not sure as to
whether they can be removed while the app is running or not.

**Comment by Qamar4P** [comment]
@JakeWharton System shouldn't be cleaning if there are a lot of storage free space available.
User can clear cache, system and some apps can clean this cache. 
So this mean, cache folder is not reliable place for long term usage. 

Is `Context.getFilesDir()` more reliable for caching images (downloading) once use forever per install.

**Comment by yschimke** [comment]
@JakeWharton I might dig into this.  This could be as simple as checking the file exists before attempting to delete.  But also confirming that our cache behaves nicely when the cache is deleted underneath us.

https://android.googlesource.com/platform/libcore/+/jb-mr2-release/luni/src/main/native/libcore_io_Posix.cpp#1075

Seems like it comes from there.

**Comment by canciloglu** [comment]
Any progress on this? We're having the same issue.

**Comment by yschimke** [comment]
I tried to reproduce the problem, but I couldn't get it to show broken behaviour with a OkHttp test client.  n.b. I wasn't including picasso in my test.  The OkHttp Cache behaved correctly and repaired itself as documented even if I trashed the cache files in the background.  But obviously my testing can't be exhaustive.

**Comment by Qamar4P** [comment]
```https://s3.abc.amazonaws.com/folder/1487229668.9226.-Ip_Qo.png
11-10 16:32:22.092 9684-9710/com.xxx.bbb D/Picasso: Dispatcher  enqueued     [R16]+2ms 
11-10 16:32:22.093 9684-9939/com.xxx.bbb D/Picasso: Hunter      executing    [R16]+3ms 
11-10 16:32:22.105 9684-9710/com.xxx.bbb D/Picasso: Dispatcher  batched      [R16]+15ms for error
11-10 16:32:22.308 9684-9684/com.xxx.bbb D/Picasso: Main        errored      [R16]+218ms 
11-10 16:32:22.308 9684-9710/com.xxx.bbb D/Picasso: Dispatcher  delivered    [R16]+218ms 
11-10 16:32:22.378 9684-9710/com.xxx.bbb D/Picasso: Dispatcher  batched      [R15]+523ms for error (will replay)
11-10 16:32:22.582 9684-9710/com.xxx.bbb D/Picasso: Dispatcher  delivered    [R15]+729ms 
11-10 16:32:22.582 9684-9684/com.xxx.bbb D/Picasso: Main        errored      [R15]+729ms
R21]+15ms for error https:://s3.abc.amazonaws.com//1487229634.6965.KDou3U.png ```

**Comment by swankjesse** [comment]
Unclear what action to take here.
