### ISSUE TITLE
javax.net.ssl.SSLException: Read error: ssl=0xd00ba180: I/O error during system call, Software caused connection abort

### ISSUE THREAD

**Issue by sduslum** [square/okhttp#3650]
System.err: javax.net.ssl.SSLException: Read error: ssl=0xd00ba180: I/O error during system call, Software caused connection abort
System.err:     at com.android.org.conscrypt.NativeCrypto.SSL_read(Native Method)
System.err:     at com.android.org.conscrypt.OpenSSLSocketImpl$SSLInputStream.read(OpenSSLSocketImpl.java:758)
System.err:     at okio.Okio$2.read(Okio.java:139)
System.err:     at okio.AsyncTimeout$2.read(AsyncTimeout.java:237)
System.err:     at okio.RealBufferedSource.request(RealBufferedSource.java:67)
System.err:     at okio.RealBufferedSource.require(RealBufferedSource.java:60)
System.err:     at okio.RealBufferedSource.readByte(RealBufferedSource.java:73)
System.err:     at okhttp3.internal.ws.WebSocketReader.readHeader(WebSocketReader.java:113)
System.err:     at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:97)
System.err:     at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:265)
System.err:     at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:204)
System.err:     at okhttp3.RealCall$AsyncCall.execute(RealCall.java:153)
System.err:     at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
System.err:     at java.lang.Thread.run(Thread.java:761)

**Comment by yschimke** [comment]
Can you provide more information? Does it happen everytime, only after a network change, only on certain devices?  Network calls fail so you should handle occasional network failures in your app.
