### ISSUE TITLE
can i get response head when request is error,like response code is 403

### ISSUE THREAD

**Issue by duzechao** [square/okhttp#3651]
@JakeWharton the service return 403 and response message in response head,but okhttp just throw IOException

**Comment by duzechao** [comment]
em,i change the source code,in RealConnection.java,the method createTunnel,`switch (response.code()) {
        case HTTP_OK:
          // Assume the server won't send a TLS ServerHello until we send a TLS ClientHello. If
          // that happens, then we will have buffered bytes that are needed by the SSLSocket!
          // This check is imperfect: it doesn't tell us whether a handshake will succeed, just
          // that it will almost certainly fail because the proxy has sent unexpected data.
          if (!source.buffer().exhausted() || !sink.buffer().exhausted()) {
            throw new IOException("TLS tunnel buffered too many bytes!");
          }
          return null;

        case HTTP_PROXY_AUTH:
          tunnelRequest = route.address().proxyAuthenticator().authenticate(route, response);
          if (tunnelRequest == null) throw new IOException("Failed to authenticate with proxy");

          if ("close".equalsIgnoreCase(response.header("Connection"))) {
            return tunnelRequest;
          }
          break;
        default:
          Headers headers = response.headers();
          throw new CustomIOException(response.message(),response.code(),response.request().url().toString(),headers);
      }`

**Comment by yschimke** [comment]
If this is important to you, I suggest submitting a proper PR with tests.  I can't see any reason to object to exposing additional data in a ProxyIOException or similar.

**Comment by bobsmith30332** [comment]
+1

In case it isn't obvious to you, integrators have to hardcode the "Failed to auth" string in our code and do a string comparison to test against this IOException.  The other big fail in this area is that we don't have access to the response code in the request either so looking for the 403 code is not an option either.

**Comment by swankjesse** [comment]
I'm curious: what does the code do when it detects a connectivity problem caused by the proxy? My working theory has been that there isn't much you can do about this that you haven't already done in the authenticator.

**Comment by swankjesse** [comment]
No action to take here.
