### ISSUE TITLE
Badly formatted POST request (3.8.0)

### ISSUE THREAD

**Issue by Malachiasz** [square/okhttp#3652]
OkHttp has sent such request*:

```
:method: POST
:path: /token
:authority: sample.domain.net
:scheme: https
authorization: Basic Z214SAMPLEzQzakE0UzFGM1l6VDJQUG9hU01k
user-agent: sample.useragent/5.13 Dalvik/2.1.0 (Linux; U; Android 6.0; Android SDK built for x86 Build/MASTER)
x-ui-app: sample.header/5.13
content-type: application/x-www-form-urlencoded; charset=utf-8
accept-encoding: gzip

grant_type=password&username=sampleusername&password=samplepassword&device_name=unknown+Android+SDK+built+for+x86
```
 Reinstalling application helped solving issue. Take a look at ":method: POST". A proper request starts like that: "POST /token HTTP/1.1". It seems that OkHttp printed on stream an array or a list. I don't know how to reproduce it.

*I have replaced some date with words "sample". This is log from Charles proxy.

**Comment by JakeWharton** [comment]
It's HTTP/2
