### ISSUE TITLE
Caret charater encoding problem of Query Parameter

### ISSUE THREAD

**Issue by leotu** [square/okhttp#3653]
- Test code:
```java
HttpUrl url = new HttpUrl.Builder()//
				.scheme("http") //
				.host("127.0.0.1")//
				.port(7029)//
				.encodedPath("/be/echo") //
				.addQueryParameter("input", "Ab^12") //
				.addQueryParameter("others", "<ok>") //
				.build();
		log.debug("url={}", url);
                log.debug("caret charater encoded={}", URLEncoder.encode("Ab^12", "UTF-8"));

OkHttpClient client = new OkHttpClient.Builder().build();
		Request request = new Request.Builder().url(url).build();

		log.debug("request={}", request);
		try (Response response = client.newCall(request).execute()) {
			log.debug("successful={}, response={}", response.isSuccessful(), response);
			ResponseBody body = response.body();
			log.debug("body.string={}", body.string());
		}
```
logger show:
 > url=http://127.0.0.1:7029/be/echo?input=Ab^12&others=%3Cok%3E
 > caret charater encoded=Ab%5E12

- but Tomcat Server show error when received this request:
```java
java.lang.IllegalArgumentException: Invalid character found in the request target. The valid characters are defined in RFC 7230 and RFC 3986
	at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:472)
```

- Trace the Tomcat (ver. 8.5.15) source code:
org.apache.tomcat.util.http.parser.HttpParser.java

```java
public class HttpParser {
 ...
    private static final boolean[] IS_NOT_REQUEST_TARGET = new boolean[ARRAY_SIZE];
    private static final boolean[] IS_HTTP_PROTOCOL = new boolean[ARRAY_SIZE];
    private static final boolean[] REQUEST_TARGET_ALLOW = new boolean[ARRAY_SIZE];
 ...
 static {
        String prop = System.getProperty("tomcat.util.http.parser.HttpParser.requestTargetAllow");
        if (prop != null) {
            for (int i = 0; i < prop.length(); i++) {
                char c = prop.charAt(i);
                if (c == '{' || c == '}' || c == '|') {
                    REQUEST_TARGET_ALLOW[c] = true;
                } else {
                    log.warn(sm.getString("httpparser.invalidRequestTargetCharacter",
                            Character.valueOf(c)));
                }
            }
        }
 ...
           // Not valid for request target.
            // Combination of multiple rules from RFC7230 and RFC 3986. Must be
            // ASCII, no controls plus a few additional characters excluded
            if (IS_CONTROL[i] || i > 127 ||
                    i == ' ' || i == '\"' || i == '#' || i == '<' || i == '>' || i == '\\' ||
                    i == '^' || i == '`'  || i == '{' || i == '|' || i == '}') {
                if (!REQUEST_TARGET_ALLOW[i]) {
                    IS_NOT_REQUEST_TARGET[i] = true;
                }
            }
...
```
find '^' is illegal character
and change to using Apache HttpClient, the ^ character be encoded %5E
> http://127.0.0.1:7029/be/echo?input=Ab%5E12&others=%3Cok%3E

P.S,
I am using Netflix's Zuul as API-Gateway,  the problem causing turn to using httpclient.

## Successful config.
feign.httpclient.enabled=true
feign.okhttp.enabled=false

ribbon.httpclient.enabled=true
ribbon.okhttp.enabled=false

## Failed config.
feign.httpclient.enabled=false
feign.okhttp.enabled=true

ribbon.httpclient.enabled=false
ribbon.okhttp.enabled=true

**Comment by rigolepe** [comment]
I have the same issue with square and curly brackets: []{} They don't get encoded when they are passed as query parameter.

What should happen is: 
```
[ encodes to %5B%0A
] encodes to %5D%0A
{ encodes to %7B 
} encodes to %7D
```
But none of this happens.

**Comment by yschimke** [comment]
I believe this is deliberate based on the most up to date RFCs.

n.b. this also matches chrome

https://requestb.in/1jie36h1?inspect

![image](https://user-images.githubusercontent.com/231923/34413873-0768f172-ebde-11e7-9fa9-bd67240461cd.png)

**Comment by DPanger13** [comment]
@yschimke Can you quote the RFCs? It seems like the characters mentioned fall under "unreserved characters", which need to be percent encoded. [This](https://meta.stackexchange.com/a/69371) seems to describe this situation, unless that post is outdated.

**Comment by DPanger13** [comment]
@swankjesse 3.10 works with the characters mentioned in this post
