### ISSUE TITLE
Add module-info.java

### ISSUE THREAD

**Issue by hrchu** [square/okhttp#3655]
So that projects depend on this can be published to a public artifact repository.
Note that this is not breaking backward compatibility. All codes except this file can be still compiled in Java 6.

**Comment by JakeWharton** [comment]
I don't see how publishing to a public artifact repository and becoming a
module jar are correlated.

**Comment by yschimke** [comment]
Does seem like something we should do.

http://blog.joda.org/2017/05/java-se-9-jpms-automatic-modules.html

Along with additionally building against released JDK 9 in https://github.com/square/okhttp/blob/master/.travis.yml

**Comment by JakeWharton** [comment]
Oh I'm all for an automatic module name. But I see no reason to add a
module-info.class entry.

**Comment by hrchu** [comment]
@JakeWharton the problem is that projects depends on filename-based automodules should not be published to a public artifact repository. 

At least we need add Automatic-Module-Name entry to JAR's manifest.
https://github.com/google/guava/commit/f2be0be06ef49dee7c5dfcb3a0231c5ecaf5b621#diff-e407b6f223ee6c04116a91ead9f5e100R42

Refer: https://github.com/grpc/grpc-java/issues/3523

**Comment by JakeWharton** [comment]
That's what I said, yeah. But why are you recommending a module-info.class
entry?

**Comment by hrchu** [comment]
I change my mind.  Automatic-Module-Name is good enough currently.

**Comment by yschimke** [comment]
https://github.com/square/okhttp/pull/3743

**Comment by yschimke** [comment]
Per https://github.com/square/okhttp/pull/3743#issuecomment-363851149

We should (ideally) clean up package names to not overlap when doing this.

cc @jodastephen

**Comment by swankjesse** [comment]
Done.

**Comment by CodFront** [comment]
Newbie here. Can't create a custom JRE using jlink without module-info.java. I use OkHTTP in almost all my projects. Would be great if I didn't have to manually unpack and recompile everything with module-info.java.
