### ISSUE TITLE
Is there a way to read status code in onFailure ? If API response body is empty and  i have to check API success failure by only status code then what to do?

### ISSUE THREAD

**Issue by rashel007** [square/okhttp#3657]
What kind of issue is this?

 - [ ] Question. This issue tracker is not the place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use Stack
       Overflow. https://stackoverflow.com/questions/tagged/okhttp

 - [ ] Bug report. If you’ve found a bug, spend the time to write a failing test. Bugs with tests
       get fixed. Here’s an example: https://gist.github.com/swankjesse/981fcae102f513eb13ed

 - [x] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
       already exists! Don’t send pull requests to implement new features without first getting our
       support. Sometimes we leave features out on purpose to keep the project small.

**Comment by JakeWharton** [comment]
Empty bodies are delivered to onResponse not onFailure.

**Comment by rashel007** [comment]
I am getting API response in onFailure for empty body. And when i print the error message, it is saying "body is empty". One of my API have post method. And to find out post is successful or failed, I have to  check status code 204. But this API response delivered to onFailure. And currently in okhttp you cannot check status code in onFailure. @JakeWharton

**Comment by JakeWharton** [comment]
Can you provide a failing test case or executable sample?

**Comment by rashel007** [comment]
Sure,  But i can provide sample tomorrow . As i am away from my workplace now. @JakeWharton

**Comment by rashel007** [comment]
This is my code. 
`
Request request = new Request.Builder()
                .url(URL)
                .header(HEADER_ONE)
                .addHeader(HEADER_TWO)
                .delete()
                .build();

        MvpApp.okhttp.newCall(request).enqueue(new Callback() {
            @Override
            public void onFailure(Call call, IOException e) {
               
                Log.d("onFailure", "failed1 " + e.getMessage());
                e.printStackTrace();
            }

            @Override
            public void onResponse(Call call, Response response) throws IOException {
                try {
                       Log.d("onResponse", "onResponse");
               		// Need to check status code
                    call.cancel();
                } catch (Exception e) {
                    e.printStackTrace();
                    call.cancel();
                } finally {
                    response.body().close();
                    call.cancel();
                }
            }
        });`

Getting error response in onFailure:  " failed1 HTTP 204 had non-zero Content-Length: 20 "

**Comment by yschimke** [comment]
This is acting as specified, can you make a fix on the server side, or report to the API/website owner?

https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html

`The 204 response MUST NOT include a message-body`
