### ISSUE TITLE
Should the Response.close() method be thread-safe?

### ISSUE THREAD

**Issue by enric-sinh** [square/okhttp#3659]
Sorry if this is a duplicate, I found a couple of similar issues that don't exactly match mine.

I am implementing a reader for a Response using RxJava2, and subscribing to the reader on a Scheduler.io() thread, but I can't cancel the response because the scheduler thread is blocked on source.readLine() and if I call close() from another thread it throws an exception but doesn't close it.

Here is the code:

```
fun linesOf(response: Response): Observable<String> =
            Observable.create { emitter ->
                emitter.setCancellable {
                    try {
                        response.close() // <-- throws but doesn't close it
                    } catch (t: Throwable) {
                    }
                }
                try {
                    val body = response.body()
                    if (body == null)
                        emitter.onComplete()
                    else {
                        val source = body.source()
                        while (!emitter.isDisposed) {
                            val line = source.readUtf8LineStrict() // <-- thread blocked
                            emitter.onNext(line)
                        }
                    }
                } catch (ioe: IOException) {
                    emitter.tryOnError(ioe)
                }
            }
```
My problem is that cancelling this is not possible, because the "owner" thread is blocked and calling close() from another thread does nothing but throwing an exception.

My expectation was that it would behave like a BufferedInputStream or similar, where the close() method can be called from another thread, and this causes the readLine() method to immediately throw and exit.

Should Response.close() be thread-safe? is there another solution I may be missing?

Thanks!

**Comment by swankjesse** [comment]
You can use `Call.cancel()` to asynchronously cancel an unwanted response. Calling `close()` from another thread is going to cause you pain.

If we supported it we’d need to synchronize all I/O in OkHttp and Okio; this gets complicated and slow.

**Comment by enric-sinh** [comment]
Hey @swankjesse thank you for your answer, calling `Call.cancel()` did immediately stop the `readLine()`, solving the thread block. I thought that the only was was through `Response.close()`.
