### ISSUE TITLE
Fatal signal 11 (SIGSEGV), code 1, from libssl.so (SSL_shutdown+158)

### ISSUE THREAD

**Issue by diousk** [square/okhttp#3660]
Hi,

I found that our production app sometimes crashed from native library libssl.so (SSL_shutdown+158)
Can you help check this?

Device: Google Pixel
OS: Android 8.0.0
OkHttp version: 3.8.1
Retrofit version: 2.3.0

crash log:
10-20 21:32:08.462 2238-2238/? A/DEBUG: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x56
10-20 21:32:08.462 2238-2238/? A/DEBUG: Cause: null pointer dereference
10-20 21:32:08.462 2238-2238/? A/DEBUG:     r0 00000003  r1 00000000  r2 00000000  r3 0000000c
10-20 21:32:08.462 2238-2238/? A/DEBUG:     r4 00000000  r5 00000005  r6 00000000  r7 c4224100
10-20 21:32:08.462 2238-2238/? A/DEBUG:     r8 bfb5ece6  r9 00000032  sl bfb5ece7  fp bfb5ece0
10-20 21:32:08.462 2238-2238/? A/DEBUG:     ip ec5280f4  sp bfb5ecb8  lr ec4b0a2f  pc e2460ace  cpsr 000b0030
10-20 21:32:08.553 2238-2238/? A/DEBUG: backtrace:
10-20 21:32:08.553 2238-2238/? A/DEBUG:     #00 pc 00014ace  /system/lib/libssl.so (ssl_read_buffer_extend_to+257)
10-20 21:32:08.553 2238-2238/? A/DEBUG:     #01 pc 0001303d  /system/lib/libssl.so (ssl3_get_record+132)
10-20 21:32:08.553 2238-2238/? A/DEBUG:     #02 pc 0001325b  /system/lib/libssl.so (ssl3_read_close_notify+6)
10-20 21:32:08.553 2238-2238/? A/DEBUG:     #03 pc 00018603  /system/lib/libssl.so (SSL_shutdown+158)

Thanks.

**Comment by swankjesse** [comment]
@kruton ideas?

**Comment by yschimke** [comment]
@diousk is this still reproducible? And have you seen it on other devices?

**Comment by yschimke** [comment]
Closing as we aren't seeing other reports, and it's potentially just a bug in 8.0 that could be fixed in later android versions.
