### ISSUE TITLE
Provide the ability to delete an entry in the cache without forcing a request

### ISSUE THREAD

**Issue by emezias** [square/okhttp#3661]
Feature Request

In this case, the app has a default to force-cache and a follow-up. ETags are set on the pages to set logic for updated content to reload if the user wants it. All good.

Some authentication is done using Custom Tabs to share cookies and the app returns from a Chrome login to the Activity that started it. Once login finishes this custom tab activity also finishes and starts a new "main activity".  The main activity should not load a cached page so I want to clear that page from the cache before I leave the login activity since the busy, overloaded main activity has some complexity onCreate/NewIntent logic.

The app also has fragment paths for authentication where the page leading to the login fragment needs to be removed from the cache. The login fragment knows the page that opened it, but the login process may not immediately reload that page after the login fragment changes the app state. 

The kluge I use to solve the problem is to make an extra request with a force network cache-control and an empty callback. This leads me to open a feature request with two pieces. 

1 - It would be nice, at different points in my app, to look and see if there is an entry in the cache for any given page. 
2 - The real request is to be able to remove/overwrite a cache entry without forcing a network call since we do not know when the user might return to the page they were viewing before login. 

I hope this makes sense. I saw a closed request from 2015. This feature request is about the same with an added requirement -
 need to be able to clear a cache entry without forcing a network call.

**Comment by JakeWharton** [comment]
The cache has an iterator which supports remove() so that should handle 1.

**Comment by emezias** [comment]
Wait, what? Ok - Cache.urls(), got it. That's a good answer.
Is that the way I can get the logic I need? Sounds like changing the iterator won't result in an empty cache result and force network overwrite on the next call.

**Comment by swankjesse** [comment]
Removing from the iterator removes from the cache too.

**Comment by emezias** [comment]
Unfortunately the fragment's webview might be showing the cached response
when the entry is removed via Iterator and so the results are unexpected.
I'll keep at it.

**Comment by JakeWharton** [comment]
That's fine. If the users refreshes it'll re-fetch.

**Comment by yschimke** [comment]
@emezias if you post and answer yourself on stackoverflow, I'll upvote so next time someone finds it sooner there.

**Comment by emezias** [comment]
Yuri,

I finally posted my issue <https://github.com/square/okhttp/issues/3661> to
stackoverflow.

https://stackoverflow.com/questions/47542506/how-to-drop-an-entry-from-the-okhttp3-cache/47542507#47542507

Thanks to you and Jake for the help.

Best regards,
Beth
