### ISSUE TITLE
ReadLine() not working for content-part of message, on Server side

### ISSUE THREAD

**Issue by chjan** [square/okhttp#3673]
Strange problem in a rest based client-server project. I am at loss as to source of this problem, but I try here:

On the server side: While inputstream.readLine() works fine for header lines of received http message via websocket, we had to use inputstream.read() char by char for the content part. Seemingly, there was no end of line included on the content line. 

Result: Socket timeout for the response on client side.

Setup on the client side: rxJava2, retrofit2, working fine (when the problem was corrected).

Any ideas?

**Comment by swankjesse** [comment]
I don’t think you can rely on newline characters to delimit websocket messaes.
