### ISSUE TITLE
Invalid http2 settings id may cause app crash.

### ISSUE THREAD

**Issue by MegatronKing** [square/okhttp#3675]
There is a crash report, http2 settings value has some problem from server, but I think client must do some guard judgment agains this.
```
java.lang.ArrayIndexOutOfBoundsException
length=10; index=-27591
okhttp3.internal.http2.Settings.set(Settings.java:65)
okhttp3.internal.http2.Http2Reader.readSettings(Http2Reader.java:304)
okhttp3.internal.http2.Http2Reader.nextFrame(Http2Reader.java:149)
okhttp3.internal.http2.Http2Reader.readConnectionPreface(Http2Reader.java:83)
okhttp3.internal.http2.Http2Connection$ReaderRunnable.execute(Http2Connection.java:571)
okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
java.lang.Thread.run(Thread.java:818)

```

**Comment by yschimke** [comment]
It would be good to reproduce this in a standalone test first, otherwise it's hard to know we have completely fixed this.  But as reported it does look like a bug as OkHttp shouldn't get into an undefined state or crash the app based on invalid responses from a single server.

**Comment by yschimke** [comment]
Fixed already https://github.com/square/okhttp/commit/3819ed03996f1497512bffb445f81398a0bbaa17#diff-537e6894951189ccea5a38e6201e2161
