### ISSUE TITLE
toMultimap method from class Headers  make key to lower case

### ISSUE THREAD

**Issue by suxianbaozi** [square/okhttp#3679]
toMultimap method from class Headers  make key to lower case

I think it should not make it lower case

**Comment by yschimke** [comment]
I believe this is by design in the API.  In the case of two headers differing only by case they need to be joined into the same entry anyway.

Some discussion on https://github.com/square/okhttp/issues/2701

**Comment by swankjesse** [comment]
For what it’s worth, lowercase is best for HTTP headers. It’s what HTTP/2 requires!

**Comment by suxianbaozi** [comment]
sorry , does the method should return what the server has returned ?

**Comment by yschimke** [comment]
Semantically yes.  Which means no guarantee to preserve case.
