### ISSUE TITLE
Calling cancel() does not close the connection/stream

### ISSUE THREAD

**Issue by anikravesh** [square/okhttp#3680]
I am trying to cancel a HTTP/2.0 stream (by calling its cancel() function) after downloading/reading first half of the file, but when I look at the pcap trace, I see that it keeps downloading the whole file.
```
Call call=client.newCall(request);
Response response = call.execute();
byte[] readBuffer = new byte[1024];
if(response.isSuccessful()){
                InputStream inputStream = response.body().byteStream();
                int totalLen=0;
                ...
                //reading the first half of the file 
                ...
                call.cancel();
                inputStream.close();
                response.close();
}
```
after calling cancel(), both call.isCanceled() and call.isExecuted() return true.
Okhttp 3.9.0, Android 6, Nexus 5, server: nginx with http2.0 enabled

**Comment by anikravesh** [comment]
I changed the web server from nginx to apache2 and the problem still exist. 
I also added debugging code to the okhttp source code and here is the function call trace when I call cancel():
RealCall.java->cancel()
RetryAndFollowUpInterceptor.java->cancel()
StreamAllocation.java->cancel()
Http2Codec.java->cancel()
Http2Stream.java->closeLater()
Http2Connection.java->writeSynResetLater() with Error code: CANCEL
Http2Writer.java->rstStream() with Error code CANCEL
and then several:
Http2Writer.java->rstStream() with error code: PROTOCOL_ERROR

Any idea how I can fix this problem?

**Comment by yschimke** [comment]
It would help a lot if you made a reproducible test case for this.  Specifically if we test against different URLs, negotiate a different protocol then results may differ.

**Comment by jiangbodev** [comment]
I got very similar problem.

My case is even simple.
1. Set connect/read/write timeout to a large number, like 30 seconds.
2. I was with emulator with wifi settings on, but my pc's network is off.
3. When I create a new thread to start a http call.
4. And then wait 1-2 seconds to cancel the call.
5. The thread will still run for many seconds, it seems, it would not stop the thread until the 30s connection timeout happen.

**Comment by anikravesh** [comment]
@yschimke I realized that the problem is not caused by okhttp implementation. In fact, okhttp can not fix this problem. Please take a look at this [paper](https://dl.acm.org/citation.cfm?id=2999583) for more info, if you are interested.
