### ISSUE TITLE
Adding QUIC entry to Protocol enum

### ISSUE THREAD

**Issue by ypyu2000** [square/okhttp#3683]
We are adding QUIC (https://www.chromium.org/quic) support to the OKHttp by adding a QUIC interceptor. The QUIC interceptor can transmit request packets and response packets over QUIC between the OKHttp client and a QUIC proxy or a QUIC server. To integrate QUIC into existing okhttp codes, we plan to add QUIC(“quic”) to the Protocol enum in Protocol.java to be used in the QUIC interceptor. We can contribute back the QUIC interceptor to the OKHttp git if this addition can be approved. Can the committee approve this addition? Thanks.

**Comment by swankjesse** [comment]
Sure. Who is “we” ?

**Comment by naturalwarren** [comment]
The networking team at Uber developed the QUIC interceptor. It's pretty nifty! Not sure whether this kind of thing would live inside or outside of OkHttp. Instead of having the interceptor live inside OkHttp we could just add an API to support custom protocols. 

Once we have the Interceptor hosted on Git we'll ping this thread.

**Comment by vinothchandar** [comment]
+ 1 for support for custom protocol api :) That would be awesome..

**Comment by cfsbhawkins** [comment]
Where could one find this QUIC interceptor?

**Comment by vinothchandar** [comment]
@cfsbhawkins Not open sourced as of now.

**Comment by swankjesse** [comment]
Done!

**Comment by esafirm-tiket** [comment]
Is the QUIC interceptor open sourced yet? Or can anyone help me find some resource to build one? Thanks

**Comment by yschimke** [comment]
See Cronet example which should support Quic https://medium.com/the-react-native-log/using-cronet-in-your-mobile-app-7dda3a89c132
