### ISSUE TITLE
OkHttp strict mode

### ISSUE THREAD

**Issue by yschimke** [square/okhttp#3685]
what are your thoughts about having a strict mode that would detect common issues like multithreaded use of a Response.  Was thinking it could be useful to ask people to flip it on if they are getting issues with cancellation, or unexpected end of stream etc.  To that matter, what are the exact rules?  a response body must be consumed by any single thread, cancellation must be done by the same thread?

**Comment by swankjesse** [comment]
I think it's very interesting! Particularly for checking things like unsafe concurrent use of Okio buffers.

Figuring the right way to enable this is awkward. I really liked the way we did the leaked connection stack trace. Maybe something like that?

**Comment by yschimke** [comment]
This page is awesomely helpful https://github.com/square/okhttp/wiki/Concurrency

**Comment by yschimke** [comment]
Bit vague requirement from me, closing.
