### ISSUE TITLE
http works, https has no post data and is slower

### ISSUE THREAD

**Issue by Sturaccou57** [square/okhttp#3686]
Hello,

We use cloudflare for a https connection.

When i send data to the server over http, i get te post data and it is fast but when i change the http into https it takes longer (half a min) and the server has no post data.

Is this a bug?

**Comment by yschimke** [comment]
Can you implement an event listener and log the output? it is interesting whether its time to connect or speed of transferring the results.

https://github.com/square/okhttp/wiki/Events

Alternatively - Can you provide a test URL and more information e.g. is it a large file.

**Comment by ParkerK** [comment]
I may have the same issue. https://lainchan.org/%CE%94/src/1492678838479-0.jpg does not load for me, but it does on older versions of OkHTTP. I get an HTTPS auth error that the handshake failed. It seems like the supported TLS encodings changed at some point, as HTTPS works for most sites still, just doesn't work for this server.

**Comment by swankjesse** [comment]
@ParkerK hmm, it gets TLS checkmarks from Chrome and Firefox. And it works when I run OkHttp on my desktop JVM. Maybe it’s a problem with the cipher suites or TLS versions on your Android or JVM?

**Comment by yschimke** [comment]
I haven't really dug in yet, but one relevant factor may be two candidates from DNS. One ipv4, ipv6, make sure you are clear in your testing which you are using.

I am guessing there is currently some handshake failure on one and the other isn't responding.

lainchan.org/107.161.19.243, lainchan.org/2604:180:1:c59::2c97

**Comment by hrj** [comment]
I am running into a similar problem, trying to access this URL: https://w3c-test.org

The SSL Labs report shows that the ipv4 server is reachable but ipv6 isn't:
https://www.ssllabs.com/ssltest/analyze.html?d=w3c-test.org

OkHttp using url-connection is trying to connect to the ipv6 address and failing.

But direclty using OkHttp seems to work.

I understand that the url connection library is deprecated. However, if there is a quick workaround for this, please let me know. Thanks!
