### ISSUE TITLE
Parse and expose mediatypes parameters

### ISSUE THREAD

**Issue by bric3** [square/okhttp#3702]
- [X] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
       already exists! Don’t send pull requests to implement new features without first getting our
       support. Sometimes we leave features out on purpose to keep the project small.

Currently `MediaType` class doesn't handle media-type parameters. This would be useful to be able to parse the parameters of received media-types, as per [RFC 6838 §4.3](https://tools.ietf.org/html/rfc6838#section-4.3).

This is could be handy client side when defining constants. Of course one can use strings for those constants. But this could avoid typing errors. I'm exploring the idea of media-type parameters to express API versions.

**Comment by swankjesse** [comment]
To do this right we’d probably also want range matching.
https://github.com/square/okhttp/issues/3702

**Comment by bric3** [comment]
I agree but this is a separate concern / issue. Expressing special values like the quality factor `q` is one of them.

**Comment by swankjesse** [comment]
I wanna do this.

**Comment by yschimke** [comment]
https://github.com/square/okhttp/pull/5994/files

**Comment by bric3** [comment]
Thanks @swankjesse and @yschimke (and others I don't know about) !

**Comment by yschimke** [comment]
Nothing to me, this was all @swankjesse
