### ISSUE TITLE
空指针：java.net.SocketImpl java.net.SocketImplFactory.createSocketImpl()' on a null object reference

### ISSUE THREAD

**Issue by wu1178279937** [square/okhttp#3704]
Attempt to invoke interface method 'java.net.SocketImpl java.net.SocketImplFactory.createSocketImpl()' on a null object reference
java.net.Socket.setImpl(Socket.java:501)
--
2 java.net.Socket.<init>(Socket.java:87)
3 javax.net.ssl.SSLSocket.<init>(SSLSocket.java:880)
4 com.android.org.conscrypt.OpenSSLSocketImpl.<init>(OpenSSLSocketImpl.java:237)
5 com.android.org.conscrypt.OpenSSLSocketImplWrapper.<init>(OpenSSLSocketImplWrapper.java:35)
6 com.networkbench.agent.impl.socket.g.<init>(SourceFile:29)
7 com.networkbench.agent.impl.socket.CustomSSLSocketFactory.createSocket(SourceFile:69)
8 okhttp3.internal.connection.RealConnection.connectTls(SourceFile:288)
9 okhttp3.internal.connection.RealConnection.establishProtocol(SourceFile:268)
10 okhttp3.internal.connection.RealConnection.connect(SourceFile:160)
11 okhttp3.internal.connection.StreamAllocation.findConnection(SourceFile:256)
12 okhttp3.internal.connection.StreamAllocation.findHealthyConnection(SourceFile:134)
13 okhttp3.internal.connection.StreamAllocation.newStream(SourceFile:113)
14 okhttp3.internal.connection.ConnectInterceptor.intercept(SourceFile:42)
15 okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:147)
16 okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:121)
17 okhttp3.internal.cache.CacheInterceptor.intercept(SourceFile:93)
18 okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:147)
19 okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:121)
20 okhttp3.internal.http.BridgeInterceptor.intercept(SourceFile:93)
21 okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:147)
22 okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(SourceFile:125)
23 okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:147)
24 okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:121)
25 com.networkbench.agent.impl.i.a.intercept(SourceFile:83)
26 okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:147)
27 okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:121)
28 okhttp3.RealCall.getResponseWithInterceptorChain(SourceFile:200)
29 okhttp3.RealCall$AsyncCall.execute(SourceFile:147)
30 okhttp3.internal.NamedRunnable.run(SourceFile:32)
31 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
32 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)

**Comment by yschimke** [comment]
It looks like it is happening in a custom socket factory com.networkbench.agent.impl.socket.CustomSSLSocketFactory

Could you add debugging to it?  I don't think there is anything for OkHttp to fix here.
