### ISSUE TITLE
After closing web socket connection not all OkHttp's threads are terminated

### ISSUE THREAD

**Issue by aplut** [square/okhttp#3708]
Hi,

I just wrote simple app like this:

```
final OkHttpClient httpClient = new OkHttpClient();

final WebSocket webSocket = httpClient.newWebSocket(new Request.Builder().url("ws://demos.kaazing.com/echo").build(), new WebSocketListener() {
    @Override
    public void onOpen(WebSocket webSocket, Response response) {
        System.out.println("STARTED!");
    }

    @Override
    public void onClosed(WebSocket webSocket, int code, String reason) {
        System.out.println("CLOSED!");
    }
});

Thread.sleep(1000);

webSocket.close(1000, "Closed.");

Thread.sleep(1000);

Thread.getAllStackTraces().keySet().stream()
        .filter(Thread::isAlive)
        .forEach(System.out::println);
```

System output:

```
STARTED!
CLOSED!
Thread[Signal Dispatcher,9,system]
Thread[Okio Watchdog,5,main]
Thread[OkHttp ConnectionPool,5,main]
Thread[main,5,main]
Thread[Finalizer,8,system]
Thread[OkHttp Dispatcher,5,main]
Thread[Reference Handler,10,system]
Thread[Monitor Ctrl-Break,5,main]
```

It looks like the OkHttp Dispatcher is waiting for something.

After calling:

`httpClient.dispatcher().executorService().shutdown();`

All OkHttp's threads are terminated and java process is finally down.

Is it expected behaviour?

I don't have similar problems when I call http request, the problem occurs only with web sockets.

Best,
Adrian

**Comment by swankjesse** [comment]
This is expected behavior. The OkHttpClient javadoc explains resources consumed by each client and how to release them.

**Comment by yay** [comment]
I'm calling
```kotlin
client.dispatcher().executorService().shutdown()
client.connectionPool().evictAll()
```
on all OkHttpClient instances, yet the application does not exit until after the `Okio Watchdog` thread is done, around 30 seconds after the shutdown has been initiated.

Is there a way to manually shutdown that thread too?

**Comment by yschimke** [comment]
It should be a daemon thread.

https://publicobject.com/2015/01/02/okio-watchdog/
https://github.com/square/okio/blob/master/okio/src/main/java/okio/AsyncTimeout.java

Can you provide a stack trace showing it not running as a Daemon?

**Comment by yay** [comment]
@yschimke It does run as a daemon:

```
"Okio Watchdog" #24 daemon prio=5 os_prio=31 tid=0x00007fe71b7f2000 nid=0x1079b in Object.wait() [0x0000700002935000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at okio.AsyncTimeout.awaitTimeout(AsyncTimeout.java:347)
	at okio.AsyncTimeout$Watchdog.run(AsyncTimeout.java:312)
	- locked <0x00000006c0711710> (a java.lang.Class for okio.AsyncTimeout)

   Locked ownable synchronizers:
	- None
```

Full output is here: 
[dump.txt](https://github.com/square/okhttp/files/1892221/dump.txt)

**Comment by kevin4dhd** [comment]
Alguna solución?
