### ISSUE TITLE
feature: allow use of default port for HttpUrl.Builder

### ISSUE THREAD

**Issue by clshortfuse** [square/okhttp#3711]
This is rather small request, but there's no way to tell `HttpUrl.Builder` to use the default port explicitly.

For example, if I chain the functions like so:

```
  HttpUrl url = new HttpUrl.Builder()
        .scheme(SCHEME)
        .host(HOSTNAME)
        .port(PORT)
        .encodedPath(path)
        .build();
```

There's no way to pass an option for default port based on scheme. Instead, the code has to be be built like this:

```
  HttpUrl url;
  if (PORT != null && PORT != -1) {
    url = new HttpUrl.Builder()
          .scheme(SCHEME)
          .host(HOSTNAME)
          .port(PORT)
          .encodedPath(path)
          .build();
  } else {
    url = new HttpUrl.Builder()
          .scheme(SCHEME)
          .host(HOSTNAME)
          .encodedPath(path)
          .build();
  }
```

As you can see, it can get rather verbose. The two considerations are using `Integer` instead of `int` and allowing `null` values, or allowing `-1` to be used to specify `HttpUrl.Builder` to use the default port.

**Comment by swankjesse** [comment]
I think you're just working too much about method chaining.

```
  HttpUrl.Builder builder = new HttpUrl.Builder()
    .scheme(SCHEME)
    .host(HOSTNAME)
    .encodedPath(path);
  if (PORT != -1) builder.port(PORT);
  HttpUrl url = builder.build();
```

**Comment by clshortfuse** [comment]
Ah, that is a lot simpler. Thought I think the feature would be nice to have. Changing to `Integer` and checking for null seems like it wouldn't break any existing code.

**Comment by JakeWharton** [comment]
That is a binary incompatible change.
