### ISSUE TITLE
Provide IssueLogEventListener

### ISSUE THREAD

**Issue by yschimke** [square/okhttp#3717]
OkHttp could ship with an event listener that can be added with one line code change and logs device information, request details and call events for failing requests.  This could make it easier to ask for enough information on bug reports without asking issue reporters to write 100 lines of code to collect all possibly relevant data.

**Comment by swankjesse** [comment]
I like this. Especially since EventListener makes it easy to progressively gather information like DNS and TLS results.

**Comment by yschimke** [comment]
Probably a worthwhile external library.  Won't fix as part of OkHttp.
