### ISSUE TITLE
HttpLoggingInterceptor with exceptions

### ISSUE THREAD

**Issue by mgohin** [square/okhttp#3727]
- [x] Feature Request

I'm using your `HttpLoggingInterceptor` which do a pretty good job to log http requests into a file in my android app.
I'd like to add some urls that must not be logged (all logging calls for example).

Did I miss that kind of feature or it doesn't exists ?

**Comment by mgohin** [comment]
I can make a PR if you like the idea, I had to dev my own custom logging interceptor on top of your to do it

**Comment by JakeWharton** [comment]
This sounds like a good task for composition and not something we want to
bake in.

.addInterceptor(new PredicateInterceptor(loggingerInterceptor, request ->
!blacklisted.contains(request.url()))

**Comment by mgohin** [comment]
Do you add it to your todo list or do I make a PR ?

**Comment by JakeWharton** [comment]
I don't think we need to ship a PredicateInterceptor since it's only like 6
lines of code. Perhaps ask a StackOverflow question for this and we can add
it as an answer.

**Comment by mgohin** [comment]
I was not aware of interceptor's power, came to this :

    .addInterceptor(new Interceptor() {
                    @Override
                    public Response intercept(Chain chain) throws IOException {
                        Request request = chain.request();
                        boolean logBody = needToLogBody();
                        logging.setLevel(logBody ? HttpLoggingInterceptor.Level.BODY : HttpLoggingInterceptor.Level.HEADERS);
                        return chain.proceed(request);
                    }
                })
    .addInterceptor(logging)
