### ISSUE TITLE
Multi HTTP/2 Connections connecting to a single domain

### ISSUE THREAD

**Issue by lingmingyb** [square/okhttp#373]
Hi, 

Under a multi thread frame we may send several requests synchronously to a single domain. In OkHttp(SPDY) according to the codes I found that multi SPDY connections maybe set up to the same remote (I`m keeping tracking version 1.1.0, so not sure if the newest version has fixed it, seems not from the codes.) 

I do not think it's a correct behavior for clients so just wanna open the topic here. I've got a patch for it and will make a pull request if you guys confirm this issue.

Thanks

**Comment by yschimke** [comment]
I wonder whether client protocol (h2 vs http1) could be specific per domain as well as a default per client.  This could allow high volume apps to configure h2 only for their api and then the blocking could be done predictably.  I don't think any of the major sites are going to turn off h2 now.

I think we saw this in production and were scratching our heads why we had more connections than we predicted.
