### ISSUE TITLE
how can it use with VPN？

### ISSUE THREAD

**Issue by wangtl** [square/okhttp#3732]
What kind of issue is this?

 - [x] Question. This issue tracker is not the place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use Stack
       Overflow. https://stackoverflow.com/questions/tagged/okhttp

 - [x] Bug report. If you’ve found a bug, spend the time to write a failing test. Bugs with tests
       get fixed. Here’s an example: https://gist.github.com/swankjesse/981fcae102f513eb13ed

 - [x] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
       already exists! Don’t send pull requests to implement new features without first getting our
       support. Sometimes we leave features out on purpose to keep the project small.

**Comment by yschimke** [comment]
The defaults should work, picking up any VPN settings automatically and blissfully unaware of your general network setup.  There isn't really any special code you should be making to your app work with a vpn.  If there was it would be difficult to ship adds to end users who may or may not have VPNs.

Can I suggest moving this question to stackoverflow? Unless you have a bug, stackoverflow is the right forum to ask general usage questions like this.
