### ISSUE TITLE
为什么使用https   Android 7.0 不能加载 图片 抛异常，然而Android 6.0就不会抛异常

### ISSUE THREAD

**Issue by liqiang2199** [square/okhttp#3733]
W/System.err: javax.net.ssl.SSLHandshakeException: Connection closed by peer
W/System.err:     at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
W/System.err:     at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:357)
W/System.err:     at com.android.okhttp.Connection.connectTls(Connection.java:235)
W/System.err:     at com.android.okhttp.Connection.connectSocket(Connection.java:199)
W/System.err:     at com.android.okhttp.Connection.connect(Connection.java:172)
W/System.err:     at com.android.okhttp.Connection.connectAndSetOwner(Connection.java:367)
W/System.err:     at com.android.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:130)
W/System.err:     at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:329)
W/System.err:     at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:246)
W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:457)
W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:405)
W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:521)
W/System.err:     at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:105)
W/System.err:     at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java)
W/System.err:     at com.imageloader.test.MainActivity.URLConnection(MainActivity.java:114)
W/System.err:     at com.imageloader.test.MainActivity$1.run(MainActivity.java:50)
W/System.err: 	Suppressed: javax.net.ssl.SSLHandshakeException: Connection closed by peer
W/System.err: 		... 16 more
W/System.err: 		Suppressed: javax.net.ssl.SSLHandshakeException: Connection closed by peer
W/System.err: 			... 16 more

图片地址
https://www.kexindai.com/UploadFiles/Sys/Adv/c0f5fbd843b744bd9bfe942351ec3da2.jpg

**Comment by samwencn** [comment]
check android7 cipherSuite and tls version??

you image urls https is
The connection to this site uses TLS 1.0 (an obsolete protocol), RSA (an obsolete key exchange), and 3DES_EDE_CBC with HMAC-SHA1 (an obsolete cipher).

**Comment by yschimke** [comment]
This sort of question is best asked on stackoverflow, please ask there and feel free to post the stackoverflow link here.  As samwencn points out the server you are using, is using some old obsolete options.  I don't think this is a OkHttp specific problem.
