### ISSUE TITLE
okhttp3 with Retrofit where is the cached file on the phone? Unable to see it inside the Application directory

### ISSUE THREAD

**Issue by FahdSaif** [square/okhttp#3735]
okhttp3 with Retrofit where is the cached file on the phone? Unable to see it inside the Application directory here is my code:
I am sending the request in Android and the results are also comming out fine but where is it being cached??

```
 OkHttpClient.Builder builder = new OkHttpClient().newBuilder();
    builder.cache(new Cache(getApplicationContext().getCacheDir(),CACHE_SIZE_BYTES));
    OkHttpClient client = builder.build().client(client);
    final Retrofit retrofitlogin=new Retrofit.Builder()
    .baseUrl(GlobalROOT_URL)
    .addConverterFactory(GsonConverterFactory.create())
    .build();
    ..rest of the code.
```

**Comment by yschimke** [comment]
The cache isn't meant to be accessed by other applications, the format isn't documented and public API, and concurrent access could cause problems.

But if you log the cache directory it will tell you anyway

    Log.w("WARN", getApplicationContext().getCacheDir().toString())

12-22 08:11:22.071 16936-16936/? W/WARN: /data/user/0/com.squareup.okhttptestapp/cache

**Comment by yschimke** [comment]
https://stackoverflow.com/questions/47936603/okhttp3-with-retrofit-where-is-the-cached-file-on-the-phone-unable-to-see-it-in
