### ISSUE TITLE
OkHttp route traffic throw wifi and SocketFactory

### ISSUE THREAD

**Issue by rooton** [square/okhttp#3736]
I need to route specific requests throw wifi, even wifi "Connected, no internet" and "Mobile Data" is turned On.

Below example works fine with HttpURLConnection, but not works with OkHttp3 (3.8.1) which is primary network library for app:

Works with Okhttp version: 3.4.2
Broken since Okhttp version: 3.5.0

Current Okhttp version used in project: 3.8.1

```
OkHttpClient.Builder builder = new OkHttpClient.Builder();

if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
        final Network[] networks = connectivityManager.getAllNetworks();

        for (final Network network : networks) {
            final NetworkInfo netInfo = connectivityManager.getNetworkInfo(network);
            if (netInfo.getType() == ConnectivityManager.TYPE_WIFI && netInfo.getState() == NetworkInfo.State.CONNECTED) {

             // works as expected and route traffic throw wifi
             connection = (HttpURLConnection) network.openConnection(url);

             // not works, route traffic in same way
             builder.socketFactory(network.getSocketFactory());

            }
        }
    }

OkHttpClient client = builder.build();
final Response response = client.newCall(initialRequest).execute();
```
client.newCall not works as expected as I understand, or I simple missing something.

**Comment by yschimke** [comment]
Please ask on stackoverflow, if you post and put a link here to the question then you should get an answer from both OkHttp maintainers and OkHttp users who might have hit a similar case as yours.

**Comment by rooton** [comment]
Finally, I found.

https://github.com/square/okhttp/compare/parent-3.4.2...parent-3.5.0#diff-ec23bee7240c28053b0ca4fbc6029529L114 (find and navigate to RouteSelector.java) `resetNextProxy` method. 

So in my case, described above, i  need to manually disable proxy:

```
builder.proxy(Proxy.NO_PROXY);
builder.socketFactory(socketFactory);
```

**Comment by yschimke** [comment]
Nice, and thanks for looking into it.  Much appreciated.

It's a deliberate change - https://github.com/square/okhttp/commit/2a5fb08b39195d4238c7117e851e9221f94de62a#diff-ec23bee7240c28053b0ca4fbc6029529

If you want to get the old behaviour back you can take java.net.ProxySelector.getDefault() and wrap it with one that also tries NO_PROXY.  But if you know that proxies are not needed, then looks like you are all set.
