### ISSUE TITLE
OkHttp Android, network off again, unable to send request

### ISSUE THREAD

**Issue by alicemmm** [square/okhttp#3737]
OkHttp networking framework, off the network, it is easy to request no network
I find some answer 
add <uses-permission android:name="android.permission.NETWORK_PROVIDER"/> solved?
and other else answer.

I think It is cache problem.

**Comment by JunWeiAndroid** [comment]
？

**Comment by JunWeiAndroid** [comment]
how to solve this problem

**Comment by yschimke** [comment]
Sounds possibly similar to https://github.com/square/okhttp/issues/3278.  Thanks for closing, this is also a better question for stackoverflow than reporting a bug.
