### ISSUE TITLE
WebSocket WebRTC 403 FORBIDDEN

### ISSUE THREAD

**Issue by thaihuynhxyz** [square/okhttp#3738]
What kind of issue is this?

 - [ ] Question. This issue tracker is not the place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use Stack
       Overflow. https://stackoverflow.com/questions/tagged/okhttp

 - [ ] Bug report. If you’ve found a bug, spend the time to write a failing test. Bugs with tests
       get fixed. Here’s an example: https://gist.github.com/swankjesse/981fcae102f513eb13ed

 - [x] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
       already exists! Don’t send pull requests to implement new features without first getting our
       support. Sometimes we leave features out on purpose to keep the project small.

By default autobahn work well in [WebRTC's android demo](https://webrtc.googlesource.com/src/+/master/examples/androidapp/src/org/appspot/apprtc/WebSocketChannelClient.java) without extra config. I like square's okhttp so I want to replace autobahn by okhttp's websocket:

`
WebSocket mWebSocket = mClient.newWebSocket(Request.Builder().url(wsUrl).build(), WebSocketListener())
`

and get 403 FORBIDDEN, After research I add:

`
mWebSocket = mClient.newWebSocket(Request.Builder()
                .url(wsUrl)
                .header("Origin", wsUrl)
                .build(), WebSocketListener())
`

then it work well. We can test by curl:

curl --include \
       --no-buffer \
       --header "Connection: Upgrade" \
       --header "Upgrade: websocket" \
       --header "Host: apprtc-ws.webrtc.org:443" \
       --header "Origin: wss://apprtc-ws.webrtc.org:443/ws" \
       --header "Sec-WebSocket-Key: SGVsbG8sIHdvcmxkIQ==" \
       --header "Sec-WebSocket-Version: 13" \
       https://apprtc-ws.webrtc.org:443/ws

note:
wsUrl = "wss://apprtc-ws.webrtc.org:443/ws"

I don't know how `header("Origin",...)` work, but hope it useful

**Comment by yschimke** [comment]
The spec is clear that OkHttp is doing the right thing

https://tools.ietf.org/html/rfc6455

>    The |Origin| header field [RFC6454] is used to protect against
>    unauthorized cross-origin use of a WebSocket server by scripts using
>    the WebSocket API in a web browser.  The server is informed of the
>    script origin generating the WebSocket connection request.  If the
>    server does not wish to accept connections from this origin, it can
>    choose to reject the connection by sending an appropriate HTTP error
>    code.  This header field is sent by browser clients; for non-browser
>    clients, this header field may be sent if it makes sense in the
>    context of those clients.

It's focus is clearly around CORS requests, where the browser is trusted and will accurately report the Origin (the website making the websocket request).  Setting it automatically seems surprising, particularly as it's trivial (once discovered) to send with OkHttp.

On the other side https://en.wikipedia.org/wiki/WebSocket

> It is important (from a security perspective) to validate the "Origin" header during the connection establishment process on the server side (against the expected origins) to avoid Cross-Site WebSocket Hijacking attacks, which might be possible when the connection is authenticated with Cookies or HTTP authentication. It is better to use tokens or similar protection mechanisms to authenticate the WebSocket connection when sensitive (private) data is being transferred over the WebSocket.[33]

Possibilities are

1) Don't send by default (current status)
2) Send an Origin by default, but that might send one that causes other servers to start rejecting traffic that is currently accepted.  Other WebSocket servers might now assume the new requests are browser based.
3) Include in WebSocket API to force clients to provide a valid Origin, as an assumption that websocket servers will generally want to validate this accurately.

I'd argue against changing anything here as it risky and makes OkHttp look like a browser user agent.

**Comment by thaihuynhxyz** [comment]
Thanks for your explanation.
