### ISSUE TITLE
How to get download progress on okhttp 3.9.1 ?

### ISSUE THREAD

**Issue by tateisu** [square/okhttp#3740]
ResponseBody#source() must returns BufferedSource in recent okhttp.
The example on https://github.com/square/okhttp/issues/1568 uses ForwardingSource that is not BufferedSource. 
How to get download progress on okhttp 3.9.1 ?

 - [ x] Question. This issue tracker is not the place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use Stack
       Overflow. https://stackoverflow.com/questions/tagged/okhttp

 - [ ] Bug report. If you’ve found a bug, spend the time to write a failing test. Bugs with tests
       get fixed. Here’s an example: https://gist.github.com/swankjesse/981fcae102f513eb13ed

 - [ ] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
       already exists! Don’t send pull requests to implement new features without first getting our
       support. Sometimes we leave features out on purpose to keep the project small.

**Comment by yschimke** [comment]
The code still compiles and runs in Intellij, n.b. it doesn't appear to work uniformly against other urls.  At a minimum we should include an example that doesn't complete immediately.  And probably make the example worked for chunked examples of unknown size also.

https://github.com/square/okhttp/blob/master/samples/guide/src/main/java/okhttp3/recipes/Progress.java

https://publicobject.com/helloworld.txt

1759
1759
false
100% done
1759
1759
true
100% done

https://httpbin.org/stream-bytes/102400?chunk_size=10 (Chunked)

10
-1
false
-1000% done
20
-1
false
-2000% done

https://fsmedia.imgix.net/ca/0b/22/49/d82a/4144/b15e/cce9eb835dc9/the-boss-great-wall-weighs-10000-times-as-much-as-our-measly-milky-way-pictured-above.jpeg

2397
29574010
false
0% done
5156
29574010
false
0% done
7915
29574010

**Comment by tateisu** [comment]
Finally I wrote another version.
https://gist.github.com/tateisu/70a74bb6415d98909a6381b8786844e3
This code does not double buffering.
But only bytes() method is progressed.

**Comment by yschimke** [comment]
Can you unwrap the BufferedSource with the source() method instead?

```
public interface BufferedSource extends Source {
  /** Returns this source's internal buffer. */
  Buffer buffer();
```

**Comment by yschimke** [comment]
@tateisu do you have an example URL that is broken for the existing sample code, but works without the double buffering?
