### ISSUE TITLE
HttpHostConnectException  without any response and no timeout

### ISSUE THREAD

**Issue by liukewill** [square/okhttp#3745]
When I request an unkonwnhost that didnot exit  like this   http://10.11.73.166:8888 （you can reqeust it by your browser ，it just loading all the times）
it without any response  even  I set  connectTimeout（10，TimeUnit.SECONDS）
it will be failure by several minutes but not 10 seconds and throw HttpHostConnectException like this

```
Connection to http://10.11.73.166:8888 refused
12-28 19:40:25.412 4813-5174/? E/beacon: execute error:org.apache.http.conn.HttpHostConnectException: Connection to http://10.11.73.166:8888 refused
```
I realize  `HttpHostConnectException` that  not belong to  `connecttimeout` or `readtimeout `
But I want to konw ， if there no response by 10 seconds ，how can it return a callback anyway。

**Comment by yschimke** [comment]
Can you provide a reproducing test case.  The connect timeout is firing correctly for me on both desktop and an Android emulator.  

If you call call.execute it should throw an exception you can catch, and if you call enqueue it should call Callback.onFailure

**Comment by yschimke** [comment]
It's also strange you have an apache http exception (org.apache.http.conn.HttpHostConnectException)
