### ISSUE TITLE
Should android platform install the GMS provider if present already?

### ISSUE THREAD

**Issue by yschimke** [square/okhttp#3749]
https://developer.android.com/training/articles/security-gms-provider.html

> Rather than using this class, we encourage app developers to use high-level methods for interacting with cryptography. Most apps can use APIs like HttpsURLConnection without needing to set a custom TrustManager or create an SSLCertificateSocketFactory.

n.b. I know OkHttp does the hostname verification they are actually talking about above, but I think the comment applies generally.

Question
1) why not use the best security available automatically if it is present
2) why require extra steps over other APIs like HttpsURLConnection that it's possible to forget
3) Why not warn via debug logging when older clients are not using the updated provider 
4) Can this cause differences in reported issues like "this works in Volley"

**Comment by yschimke** [comment]
For instance

http://square.github.io/retrofit/

```
Retrofit retrofit = new Retrofit.Builder()
    .baseUrl("https://api.github.com/")
    .build();

GitHubService service = retrofit.create(GitHubService.class);
```

It isn't clear at what point in the above sample code the developer should be introduced to SSL providers.

**Comment by swankjesse** [comment]
Great idea. I'm unsure whether we can do this seamlessly, but if we can it's another opportunity for the framework to make the app developer's job easier.

**Comment by aahlenst** [comment]
The Play Services Dynamic Security Provider is a JCP Cryptographic Security Provider. Therefore it should automatically be picked up by OkHttp when it is installed. It was at least when I tested it the last time (~2 years ago). Insofar as a user it does not make a difference whether you use `HttpUrlConnection` or OkHttp.

The only thing you have to do is to install the security provider before opening any network connections by running `ProviderInstaller.installIfNeeded(getContext())`. It would be nice if OkHttp could do it for me, but getting hold of the `Context` might get awkward and require the addition of an user-facing API. Would that be worth it?

**Comment by yschimke** [comment]
I've used the API, but yeah the context could be tough to resolve nicely.  The other option would be to warn if this has not been installed.

I'd like to make sure we encourage the best security practices possible, and also minimise support load due to apps on phones with old versions of SSL providers.  Put this out there for discussion,  happy to consider all options and not rush anything.

**Comment by aahlenst** [comment]
In my experience the biggest pain is to ensure that the DSP is installed before any network connection is opened. This is also the hardest part to get right. Would an interceptor be called early enough? In that case I would create a separate artifact (like the logging interceptor) and encourage its use.

**Comment by yschimke** [comment]
That sounds like a good option. It's potentially a good home for any Android specific code e.g. checking network availability, network changes or proxy changes etc.

**Comment by aahlenst** [comment]
I've looked into it. Using an interceptor does not seem to be an option, at least for the DSP. The `SSLSocketFactory` is set in `OkHttpClients`'s constructor. So if the interceptor installs the DSP it's already too late even though no connection has been opened yet. It's even worse with ALPN in `AndroidPlatform`: You have to install the DSP before `findPlatform()` is ran (= before first `new OkHttpClient.Builder()`), otherwise you cannot use ALPN at all.

Looks as if we had to resort to a wiki page that explains how to do it properly.

**Comment by yschimke** [comment]
Documentation doesn't hurt, so let's add that.

Separately, I've got an Android test client that I'm using to test this, and generally network change detection https://github.com/yschimke/okhttp-testapp.   I hope to root cause some existing other problems on Android when networks become unavailable.

![image](https://user-images.githubusercontent.com/231923/34913228-4f5be49e-f8ef-11e7-9c92-4039a95968dc.png)

**Comment by ming13** [comment]
@swankjesse, sorry to bother you with this, but what it the best timing to call `ProviderInstaller.installIfNeeded`?

From its documentation it seems like this call blocks the thread it was called on. At the same, if `OkHttpClient` is provided somewhere from DI it is tricky to call the method on a background thread and build `OkHttpClient` as an execution result.

Can we utilize some `OkHttpClient` hook for that or something? Seems like I’m trying to connect async action (`installIfNeeded` on a background thread) and sync one (create `OkHttpClient`) and of course it leads to some headache.

**Comment by yschimke** [comment]
There is an async form ProviderInstaller.installIfNeededAsync.  It is suggested to call this in Activity. onCreate().  

https://developer.android.com/training/articles/security-gms-provider.html

I think you are right, it is awkward, you should defer any DI tasks until it succeeds or fails before creating and using the OkHttpClient instance.  So perhaps defer any startup work until after it returns.

Not a solution, basically agreeing with you.

**Comment by ming13** [comment]
Well, `installIfNeededAsync` is basically the same. We are calling this in `Application` and still it is a wild guess if it is going to succeed in time. Well, until the DI layer becomes async itself, that would solve the issue.

**Comment by JakeWharton** [comment]
You can use Dagger's producers to async inject inject OkHttpClient such that it synchronously installs the security provider on the background thread. The problem is that will transitively infect all downstream providers in the graph that need to inject the reference (or its transitives).

**Comment by swankjesse** [comment]
I’m sadly gonna drop this. I think it’s too magical for OkHttp to do itself, especially since it is potentially slow and has system-wide consequences.
