### ISSUE TITLE
java.net.SocketTimeoutException: failed to connect to /10.0.0.172 (port 80) after 10000ms

### ISSUE THREAD

**Issue by hallowsman** [square/okhttp#3757]
when i use wifi it is ok for connecting to the internet ，but i used 4g then it show me error like this：

01-02 18:23:11.560 23733-23733/com.yunzong.spacebridge E/maneki: ║ java.net.SocketTimeoutException: failed to connect to /10.0.0.172 (port 80) after 10000ms : java.net.SocketTimeoutException: failed to connect to /10.0.0.172 (port 80) after 10000ms
01-02 18:23:11.560 23733-23733/com.yunzong.spacebridge E/maneki: ║ 	at libcore.io.IoBridge.connectErrno(IoBridge.java:169)
01-02 18:23:11.560 23733-23733/com.yunzong.spacebridge E/maneki: ║ 	at libcore.io.IoBridge.connect(IoBridge.java:122)
01-02 18:23:11.560 23733-23733/com.yunzong.spacebridge E/maneki: ║ 	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:183)
01-02 18:23:11.560 23733-23733/com.yunzong.spacebridge E/maneki: ║ 	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:456)
01-02 18:23:11.560 23733-23733/com.yunzong.spacebridge E/maneki: ║ 	at com.hello2mao.xlogging.internal.tcp.tcpv1.MonitoredSocketImplV1.connect(MonitoredSocketImplV1.java:107)
01-02 18:23:11.560 23733-23733/com.yunzong.spacebridge E/maneki: ║ 	at java.net.Socket.connect(Socket.java:882)
01-02 18:23:11.560 23733-23733/com.yunzong.spacebridge E/maneki: ║ 	at okhttp3.internal.platform.AndroidPlatform.connectSocket(AndroidPlatform.java:69)
01-02 18:23:11.560 23733-23733/com.yunzong.spacebridge E/maneki: ║ 	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:238)
01-02 18:23:11.560 23733-23733/com.yunzong.spacebridge E/maneki: ║ 	at okhttp3.internal.connection.RealConnection.connectTunnel(RealConnection.java:210)
01-02 18:23:11.560 23733-23733/com.yunzong.spacebridge E/maneki: ║ 	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:152)
01-02 18:23:11.560 23733-23733/com.yunzong.spacebridge E/maneki: ║ 	at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:256)
01-02 18:23:11.560 23733-23733/com.yunzong.spacebridge E/maneki: ║ 	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:134)
01-02 18:23:11.560 23733-23733/com.yunzong.spacebridge E/maneki: ║ 	at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:113)
01-02 18:23:11.560 23733-23733/com.yunzong.spacebridge E/maneki: ║ 	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
01-02 18:23:11.560 23733-23733/com.yunzong.spacebridge E/maneki: ║ 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
01-02 18:23:11.560 23733-23733/com.yunzong.spacebridge E/maneki: ║ 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
01-02 18:23:11.560 23733-23733/com.yunzong.spacebridge E/maneki: ║ 	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
01-02 18:23:11.560 23733-23733/com.yunzong.spacebridge E/maneki: ║ 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
01-02 18:23:11.560 23733-23733/com.yunzong.spacebridge E/maneki: ║ 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
01-02 18:23:11.560 23733-23733/com.yunzong.spacebridge E/maneki: ║ 	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
01-02 18:23:11.560 23733-23733/com.yunzong.spacebridge E/maneki: ║ 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
01-02 18:23:11.560 23733-23733/com.yunzong.spacebridge E/maneki: ║ 	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:125)
01-02 18:23:11.560 23733-23733/com.yunzong.spacebridge E/maneki: ║ 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
01-02 18:23:11.560 23733-23733/com.yunzong.spacebridge E/maneki: ║ 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
01-02 18:23:11.560 23733-23733/com.yunzong.spacebridge E/maneki: ║ 	at com.yunzong.spacebridge.network.RetrofitUtils$LogInterceptor.intercept(RetrofitUtils.java:127)
01-02 18:23:11.560 23733-23733/com.yunzong.spacebridge E/maneki: ║ 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
01-02 18:23:11.560 23733-23733/com.yunzong.spacebridge E/maneki: ║ 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
01-02 18:23:11.561 23733-23733/com.yunzong.spacebridge E/maneki: ║ 	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
01-02 18:23:11.561 23733-23733/com.yunzong.spacebridge E/maneki: ║ 	at okhttp3.RealCall.execute(RealCall.java:77)
01-02 18:23:11.561 23733-23733/com.yunzong.spacebridge E/maneki: ║ 	at retrofit2.OkHttpCall.execute(OkHttpCall.java:174)
01-02 18:23:11.561 23733-23733/com.yunzong.spacebridge E/maneki: ║ 	at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$RequestArbiter.request(RxJavaCallAdapterFactory.java:171)
01-02 18:23:11.561 23733-23733/com.yunzong.spacebridge E/maneki: ║ 	at rx.internal.operators.OperatorSubscribeOn$1$1$1.request(OperatorSubscribeOn.java:80)
01-02 18:23:11.561 23733-23733/com.yunzong.spacebridge E/maneki: ║ 	at rx.Subscriber.setProducer(Subscriber.java:211)
01-02 18:23:11.561 23733-23733/com.yunzong.spacebridge E/maneki: ║ 	at rx.internal.operators.OperatorSubscribeOn$1$1.setProducer(OperatorSubscribeOn.java:76)
01-02 18:23:11.561 23733-23733/com.yunzong.spacebridge E/maneki: ║ 	at rx.Subscriber.setProducer(Subscriber.java:205)
01-02 18:23:11.561 23733-23733/com.yunzong.spacebridge E/maneki: ║ 	at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:152)
01-02 18:23:11.561 23733-23733/com.yunzong.spacebridge E/maneki: ║ 	at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:138)
01-02 18:23:11.561 23733-23733/com.yunzong.spacebridge E/maneki: ║ 	at rx.Observable$2.call(Observable.java:162)
01-02 18:23:11.561 23733-23733/com.yunzong.spacebridge E/maneki: ║ 	at rx.Observable$2.call(Observable.java:154)
01-02 18:23:11.561 23733-23733/com.yunzong.spacebridge E/maneki: ║ 	at rx.Observable.unsafeSubscribe(Observable.java:8314)
01-02 18:23:11.561 23733-23733/com.yunzong.spacebridge E/maneki: ║ 	at rx.internal.operators.OperatorSubscribeOn$1.call(OperatorSubscribeOn.java:94)
01-02 18:23:11.561 23733-23733/com.yunzong.spacebridge E/maneki: ║ 	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
01-02 18:23:11.561 23733-23733/com.yunzong.spacebridge E/maneki: ║ 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
01-02 18:23:11.561 23733-23733/com.yunzong.spacebridge E/maneki: ║ 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
01-02 18:23:11.561 23733-23733/com.yunzong.spacebridge E/maneki: ║ 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
01-02 18:23:11.561 23733-23733/com.yunzong.spacebridge E/maneki: ║ 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
01-02 18:23:11.561 23733-23733/com.yunzong.spacebridge E/maneki: ║ 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
01-02 18:23:11.561 23733-23733/com.yunzong.spacebridge E/maneki: ║ 	at java.util.concurrent.ThreadPoolExecutor$Work
01-02 18:23:11.561 23733-23733/com.yunzong.spacebridge E/maneki: ║ er.run(ThreadPoolExecutor.java:587)
01-02 18:23:11.561 23733-23733/com.yunzong.spacebridge E/maneki: ║ 	at java.lang.Thread.run(Thread.java:818)

**Comment by yschimke** [comment]
10.0.0.172 is a private IP range.

https://www.arin.net/knowledge/address_filters.html

If you want to continue the discussion please post on stackoverflow for usage questions like this, once you have done, feel fee to add a link as a comment here.
