### ISSUE TITLE
ava.io.IOException: unexpected end of stream on Connection{sjkh.stocke.com.cn:443, proxy=DIRECT hostAddress=sjkh.stocke.com.cn/115.236.66.22:443 cipherSuite=TLS_RSA_WITH_AES_128_GCM_SHA256 protocol=http/1.1}

### ISSUE THREAD

**Issue by lphgithub** [square/okhttp#3758]
java.io.IOException: unexpected end of stream on Connection{sjkh.stocke.com.cn:443, proxy=DIRECT hostAddress=sjkh.stocke.com.cn/115.236.66.22:443 cipherSuite=TLS_RSA_WITH_AES_128_GCM_SHA256 protocol=http/1.1}
01-03 13:10:42.886 27691-29071/xx.xx.xx W/System.err:     at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:203)
01-03 13:10:42.886 27691-29071/xx.xx.xx W/System.err:     at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:88)
01-03 13:10:42.886 27691-29071/xx.xx.xx W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
01-03 13:10:42.886 27691-29071/xx.xx.xx W/System.err:     at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
01-03 13:10:42.887 27691-29071/xx.xx.xx W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
01-03 13:10:42.887 27691-29071/xx.xx.xx W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
01-03 13:10:42.887 27691-29071/xx.xx.xx W/System.err:     at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
01-03 13:10:42.887 27691-29071/xx.xx.xx W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
01-03 13:10:42.887 27691-29071/xx.xx.xx W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
01-03 13:10:42.887 27691-29071/xx.xx.xx W/System.err:     at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
01-03 13:10:42.887 27691-29071/xx.xx.xx W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
01-03 13:10:42.887 27691-29071/xx.xx.xx W/System.err:     at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:125)
01-03 13:10:42.887 27691-29071/xx.xx.xx W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
01-03 13:10:42.887 27691-29071/xx.xx.xx W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
01-03 13:10:42.887 27691-29071/xx.xx.xx W/System.err:     at com.cairh.app.sjkh.common.LogInterceptor.intercept(LogInterceptor.java:23)
01-03 13:10:42.887 27691-29071/xx.xx.xx W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
01-03 13:10:42.887 27691-29071/xx.xx.xx W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
01-03 13:10:42.887 27691-29071/xx.xx.xx W/System.err:     at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
01-03 13:10:42.887 27691-29071/xx.xx.xx W/System.err:     at okhttp3.RealCall$AsyncCall.execute(RealCall.java:147)
01-03 13:10:42.887 27691-29071/xx.xx.xx W/System.err:     at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
01-03 13:10:42.887 27691-29071/xx.xx.xx W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
01-03 13:10:42.887 27691-29071/xx.xx.xx W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
01-03 13:10:42.887 27691-29071/xx.xx.xx W/System.err:     at java.lang.Thread.run(Thread.java:776)
01-03 13:10:42.887 27691-29071/xx.xx.xx W/System.err: Caused by: java.io.EOFException: \n not found: limit=0 content=…
01-03 13:10:42.888 27691-29071/xx.xx.xx W/System.err:     at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:227)
01-03 13:10:42.888 27691-29071/xx.xx.xx W/System.err:     at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:211)
01-03 13:10:42.888 27691-29071/xx.xx.xx W/System.err:     at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:187)
01-03 13:10:42.888 27691-29071/xx.xx.xx W/System.err: 	... 22 more

this is occasionally, about fifteen percent,how can i do?

**Comment by yschimke** [comment]
Ideally post a reproducible test program on stackoverflow.  This looks like the server is sending malformed responses in some cases, but just the stacktrace is not enough to do anything with.

These sorts of usage questions are best handled in stackoverflow, not by reporting issues.
