### ISSUE TITLE
Warmup connection pool

### ISSUE THREAD

**Issue by mattinger** [square/okhttp#3763]
- Feature Request

I'd like to be able to pre-initialize any resources required for the OkHttpClient object.  Currently, i create the OkHttpClient.  When i first use it, i'm noticing that according to the response, the call takes around 50 - 150ms in total.  However, in real time, it's taking somewhere between 600-800ms.  It's even longer on older, slower handsets, upwards of a few seconds.

The second time i make the call, the gap is much smaller (around 100ms gap, I assume for parsing).  I've verified all this timing using an Interceptor, so that I know rxjava is not the culprit.

I suspect this is due to having to warm up the client and the underlying connection pool.

I'd like a way to do this up front, as this  extra time is causing slower handsets to timeout the call (i'm using rxjava's .timeout() function)

**Comment by swankjesse** [comment]
Typically you’ll issue a short-fast request on the hosts you want to reach later. Maybe a `GET` or a `HEAD` request for `/robots.txt`.
