### ISSUE TITLE
Add consumer application to builders

### ISSUE THREAD

**Issue by electrum** [square/okhttp#3765]
Consider the following code:

```java
OkHttpClient.Builder builder = new OkHttpClient.Builder();
setupSocksProxy(builder, socksProxy);
this.okHttpClient = builder.build();
```

We'd like to use the nice builder chaining, but the code using the builder is abstracted in a helper method. A simple addition to the builder would allow this:
```java
this.okHttpClient = new OkHttpClient.Builder()
    .apply(builder -> setupSocksProxy(builder, socksProxy))
    .build();
```

The new `apply()` method would take a `Consumer<Builder>`:
```java
public interface Consumer<T> {
  void accept(T t);
}
```

**Comment by swankjesse** [comment]
If you'd like to build your own interface like this, please do. It's not something we need in OkHttp itself.
