### ISSUE TITLE
Silent "error" when a 302 redirect url is malformed

### ISSUE THREAD

**Issue by jpearl** [square/okhttp#3767]
I'm seeing a case in handling redirects where it _appears_ that okhttp isn't following a redirect. After digging through okhttp with the failing url, okhttp is functioning "correctly" - the redirect url is invalid. Therefore, okhttp doesn't follow the redirect, and returns a response with response code 302.

A test illustrating this:
```
Request request = new Request.Builder().url(originalUrl).build();
Response response = okhttp.newCall(request).execute();

log(response.code());
log(response.isSuccessful());
```
results in:
```
302
false
```

Example for `originalUrl`:
```
<originalUrl>, <host>, and <paths> have been used as substitutes for real urls, hosts, and paths

<-- 302 Found <originalUrl>
Date: Sun, 07 Jan 2018 17:04:43 GMT
Server: Apache/2.4.10 (Debian) PHP/5.6.24-0+deb8u1 OpenSSL/1.0.1t
X-Powered-By: PHP/5.6.24-0+deb8u1
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Location: http://.<host>/<path>
Access-Control-Allow-Origin: *
Connection: close
Content-Type: text/html; charset=UTF-8
<-- END HTTP
```

And yes, `followRedirects` and `followSslRedirects` are enabled

What's going on here is that the 302 redirect location is an illegally formatted URL - in my case, something like `http://.<somehost>/<path>` (note the leading `.` to the hostname). OkHttp's `RetryAndFollowUpInterceptor` reads this Location, and tries to parse it with `HttpUrl`. That, correctly, fails. At this point, the retry interceptor just returns and allows the 302 to propagate up:
https://github.com/square/okhttp/blob/cd84d79c3574de81f23802f832f2ead6ad38a735/okhttp/src/main/java/okhttp3/internal/http/RetryAndFollowUpInterceptor.java#L307-L312

Now, any sane client should be able to detect that the end response is not successful and handle it gracefully. But through reading through app logs, there's no indication as to what the actual failure was. The failed url parsing on the redirect location is simply swallowed here deep in OkHttp, without any mechanism to inform the client that the error occurred.

Should a failed HttpUrl parse be bubbled up as an exception?

**Comment by JakeWharton** [comment]
We've been talking about throwing-variants of parse and resolve for quite
some time.

**Comment by swankjesse** [comment]
I think this is asking a slightly different question – given a redirect that we can’t follow should the call throw?

**Comment by JakeWharton** [comment]
What's the alternative? I definitely think delivering a 302 that can't be
followed it weird.

What do browsers do?

**Comment by jpearl** [comment]
@swankjesse is right in that I think the first question is what is the expected behavior? I could see a reasonable argument going something along the lines of "well, we already provide an API for `Response.isSuccessful()`, so the precedent already exists for a failure condition that isn't bubbled up through an exception". Obviously the flip side of that argument is why are there different classifications of errors - those that throw and those that don't, and are those classifications clearly defined as to what type of error falls in each bucket? 

Then of course I see a few arguments for the throws, including my original confusion that spurred this, which is that I thought OkHttp was broken and that it wasn't following the redirect, because it gave me no indication at all that it tried, nor that it was the redirect that was the root cause of the overall call failure.

Of course to @JakeWharton's point, a throws on `parse` and `resolve` would seem to be one sane option to raising the exception, especially if that's already been a desire.

My one request though on any new exception is to avoid putting URLs into the exception message. URLs, especially for content, can be considered customer sensitive data that we won't log. For example, that's why we use [parse](https://github.com/square/okhttp/blob/cd84d79c3574de81f23802f832f2ead6ad38a735/okhttp/src/main/java/okhttp3/HttpUrl.java#L899) and not [Request.Builder.url(String)](https://github.com/square/okhttp/blob/cd84d79c3574de81f23802f832f2ead6ad38a735/okhttp/src/main/java/okhttp3/Request.java#L142-L144)

**Comment by JakeWharton** [comment]
To clarify, I don't mean changing the behavior of the existing methods, but
rather to have some other version like parseOrThrow or safeParse or
something...

**Comment by swankjesse** [comment]
<img width="1670" alt="screen shot 2018-01-07 at 10 59 13 pm" src="https://user-images.githubusercontent.com/133019/34658624-8ee6603a-f3fe-11e7-9122-0cc0b8924eb8.png">

**Comment by swankjesse** [comment]
That’s an attempt to redirect to a `file:` URL. I didn’t get anything satisfying attempting to get Chrome and Firefox to redirect to broken URLs; they appear to just hang.

I don’t think OkHttp should throw when it has a response to return, even if that response is weak. Throwing prevents the application layer from inspecting the HTTP response body, and that might have some clues around what went wrong.

**Comment by Mezner** [comment]
Will changing this to not throw break consumers? Should we introduce new methods for safely parsing, and then consider changing this implementation in a larger revision?

**Comment by JakeWharton** [comment]
Existing HttpUrl methods would not be charged in behavior

**Comment by swankjesse** [comment]
I think returning the 302 is our best option here.
