### ISSUE TITLE
Response leaked according to Coverity

### ISSUE THREAD

**Issue by aaronjwood** [square/okhttp#3769]
Version `com.squareup.okhttp3:okhttp:3.9.1`

This is somewhat related to #2311 except I'm not seeing any kind of log from the library and it looks like `Response` is the problem, not `ResponseBody`.

Coverity sees my code as leaking a `Response` even though I believe I have it all covered: https://github.com/aaronjwood/PortAuthority/blob/development/app/src/main/java/com/aaronjwood/portauthority/async/WanIpAsyncTask.java#L42

![leak](https://user-images.githubusercontent.com/446283/34789059-c19a98bc-f60a-11e7-93a7-0037fac4c68f.png)

It sounds like calling `string()` is supposed to close everything for me https://github.com/square/okhttp/issues/2311#issuecomment-179524978. Am I wrong about that? Do I need some extra handling for the `Response` as well as the `ResponseBody`?

**Comment by JakeWharton** [comment]
Yeah it looks like the tool can't tell that Response and ResponseBody
represent the same resource.

**Comment by aaronjwood** [comment]
Bummer, but it's good to know that it's a false positive. Just wanted to make sure I'm not actually leaking anything :)

**Comment by swankjesse** [comment]
Try this?
```
        try (Response response = httpClient.newCall(request).execute()) {
            ResponseBody body = response.body();
            if (!response.isSuccessful()) {
                return error;
            }

            return response.body().string().trim();
        } catch (IOException e) {
            return error;
        }
```

**Comment by aaronjwood** [comment]
@swankjesse thanks for the idea but unfortunately I can't use the try-with-resources construct since my `minSdkVersion` would need to be 19 or higher (quite a pain actually). Just so I understand correctly, is doing
```
        try {
            Response response = httpClient.newCall(request).execute();
            ResponseBody body = response.body();
            if (!response.isSuccessful()) {
                body.close();
                return error;
            }

            return response.body().string().trim(); // string() closes the resource automatically.
        } catch (IOException e) {
            return error;
        }
```
the same as doing something like
```
        try {
            Response response = httpClient.newCall(request).execute();
            ResponseBody body = response.body();
            if (!response.isSuccessful()) {
                response.close();
                body.close(); // Does closing the response implicitly close the body?
                return error;
            }

            response.close(); // Does closing the response implicitly close the body?
            return response.body().string().trim(); // string() closes the resource automatically.
        } catch (IOException e) {
            return error;
        }
```
?

**Comment by JakeWharton** [comment]
If you use the Android Gradle plugin 3.1 alphas you can use
try-with-resources on pre API 19. If you use 3.0, you can set android.
enableD8=true in your gradle.properties to get it. If that doesn't work (on
3.0), you can set your Java source and target compatibility to 1.8 which
will enable it, although that will slow down your builds a tiny bit.

**Comment by swankjesse** [comment]
@aaronjwood closing the response just closes the body for you. You can do either. Don’t close it before you read it!

Probably the best way to do this without try-with-resources is this:

```
        try {
          Response response = httpClient.newCall(request).execute();
          try {
            if (!response.isSuccessful()) {
                return error;
            }

            return response.body().string().trim();
          } finally {
            response.close();
          }
        } catch (IOException e) {
            return error;
        }
```

**Comment by aaronjwood** [comment]
@JakeWharton thanks I'll give that a try when I'm back at my computer.

@swankjesse is doing that just to work around the failure in Coverity to see the resources as the same or do you believe that there is a real leak by not closing the response?

**Comment by swankjesse** [comment]
They're both correct. It's nicer to close in a finally clause.

**Comment by aaronjwood** [comment]
Thanks guys, it's good to finally be able to use try-with-resources! https://github.com/aaronjwood/PortAuthority/commit/15400ced63e84e42186ebdf78f14771efd9f3127

**Comment by aaronjwood** [comment]
The only thing that sucks about this is https://github.com/travis-ci/travis-ci/issues/8111 which one of the guys from Coverity responded to a while back. I can't target 1.8 without Jack when using the older versions of Gradle. It seems that as long as I use Android Studio 3.x.x and apply `@SuppressLint("NewApi")` try-with-resources works, even without targeting 1.8.
