### ISSUE TITLE
Feature Request: Configuration parameter `followSslRedirects` is misleading its real purpose and should be renamed

### ISSUE THREAD

**Issue by MarcoLied** [square/okhttp#3773]
The configuration parameter `followSslRedirects` is misleading from its name to its real purpose and it would be better to rename it. We have already stumbled upon over it.
A better name for it would be `followProtocolRedirects` like the method parameter is already called, because its used inside the `RetryFollowUpInterceptor` to check if a scheme has changed between a call and a redirect.

```
boolean sameScheme = url.scheme().equals(userResponse.request().url().scheme());
if(!sameScheme && !this.client.followSslRedirects()) {
    return null;
}
```

A rename should be done because of the following reasons:
- `followSslRedirects` indicates that if you set it to true and `followRedirects` to false, that okHttp will only follow SSL redirects but redirects are disabled completely
- Setting `followSslRedirects` to false, indicates that redirects from `https` to `http` should be valid, but are dropped internally
- Even the parameter of `followSslRedirects` is already `followProtocolRedirects` which indicates the real purpose

**Comment by swankjesse** [comment]
Yes, good point!

**Comment by swankjesse** [comment]
I think we fix this with documentation rather than with API changes. 

And we should consider getting close to turning plaintext off by default!
