### ISSUE TITLE
okhttp3's urlencode operation doesn't match the server side

### ISSUE THREAD

**Issue by icourt-android** [square/okhttp#3775]
there is a file named "我的workflow\t.doc",  i encode the filename by HttpUrl.Builder#addEncodedQueryParameter(key, fileName), but the \t wasn't been encoded, then it causes a strange behavior, the server sends back a 400 response

**Comment by swankjesse** [comment]
addEncodedQueryParameter accepts a string that has already been encoded. Try addQueryParameter instead.
