### ISSUE TITLE
okhttp-hpacktests references invalid okhttp version

### ISSUE THREAD

**Issue by haikoschol** [square/okhttp#3779]
In the next release, can you please make sure that [this line in the pom file for okhttp-hpacktests](https://github.com/square/okhttp/blob/8318fadb32d6967c40bea66bd6cd56e31f6d38e5/okhttp-hpacktests/pom.xml#L11) contains the correct version number?

This causes problems when trying to automatically find the source code of all dependencies in the okhttp repository. For example, when running the analyzer in [oss-review-toolkit](https://github.com/heremaps/oss-review-toolkit), it currently fails with the message:
```
[FATAL] Non-resolvable parent POM for com.squareup.okhttp3:okhttp-hpacktests:[unknown-version]: Could not find artifact com.squareup.okhttp3:parent:pom:3.5.0-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 8, column 11
```

**Comment by JakeWharton** [comment]
The module is not listed in the [root pom][1] so you should file a bug on oss-review-toolkit that it shouldn't attempt to build it.

 [1]: https://github.com/square/okhttp/blob/8318fadb32d6967c40bea66bd6cd56e31f6d38e5/pom.xml#L21-L40

**Comment by haikoschol** [comment]
alright
