### ISSUE TITLE
FAILURE: Build failed with an exception.

### ISSUE THREAD

**Issue by ashikazeez** [square/okhttp#3783]
What went wrong:
Execution failed for task ':app:transformClassesWithInstantRunForDebug'.
> Unexpected inputs: ImmutableJarInput{name=com.squareup.okhttp3:okhttp:3.8.0, file=/mnt/.../app/build/intermediates/transforms/desugar/debug/29.jar, contentTypes=CLASSES, scopes=EXTERNAL_LIBRARIES, status=REMOVED}

**Comment by JakeWharton** [comment]
This is not a problem with OkHttp but a problem with your build system. You should report the bug to them at http://b.android.com/new.

**Comment by Protino** [comment]
@ashikazeez Yea, the problem is with "Instant run". Just disable it.
