### ISSUE TITLE
How to cancel Call without SocketException

### ISSUE THREAD

**Issue by alizarei95** [square/okhttp#3791]
hi , is there any way to cancel a call without socket exception?

**Comment by swankjesse** [comment]
What problem are you trying to solve?

**Comment by alizarei95** [comment]
this my code schema :

```
public String call(params ...){
   try {
     // okhttp codes ...
    } catch (Exception e) {
     // handle exception and show error dialog to user
    }
 }

 public void cancel(String tag) {
  // cancel call
 }

```
after cancel i don't want to get SocketException because of error dialog, so i need a way to quietly cancel call, any idea?

**Comment by swankjesse** [comment]
Use Call.isCanceled() to check for a cancellation before showing a dialog.

**Comment by alizarei95** [comment]
Thanks guy , you can close this issue
