### ISSUE TITLE
Provide non-default, unique thread names

### ISSUE THREAD

**Issue by ash211** [square/okhttp#3795]
This library creates threads with either no name, or in some cases the same name repeatedly.  It's very useful for threads to have unique names for debugging purposes, and this is one of the inspections YourKit provides for recorded snapshots.

Currently no name is provided for the thread created at [Http2Connection.java#L483](https://github.com/square/okhttp/blob/parent-3.9.1/okhttp/src/main/java/okhttp3/internal/http2/Http2Connection.java#L483) and the same name is used between multiple threads [Util.java#L203](https://github.com/square/okhttp/blob/parent-3.9.1/okhttp/src/main/java/okhttp3/internal/Util.java#L203).

A pattern I've seen elsewhere for generating unique thread names is a name pattern (e.g. `okhttp-pool-%d` which is then templated with an incrementing integer as new threads are created.  An example of this pattern is in Guava at [ThreadFactoryBuilder.java](https://github.com/google/guava/blob/v23.6/guava/src/com/google/common/util/concurrent/ThreadFactoryBuilder.java#L58)

Screenshot from YourKit:
<img width="1392" alt="screen shot 2018-01-23 at 10 24 33 pm" src="https://user-images.githubusercontent.com/357170/35317577-4a6b0128-008c-11e8-8560-c0ba08181968.png">

**Comment by yschimke** [comment]
+1 want to submit a PR?

**Comment by swankjesse** [comment]
The thread in Http2Connection does have name that gets set when the thread executes.
https://github.com/square/okhttp/blob/parent-3.9.1/okhttp/src/main/java/okhttp3/internal/http2/Http2Connection.java#L557
Looks like YourKit isn’t tracking the name update.

As for the ConnectionPool, you usually don’t want multiple connection pools in your application. So the warning is appropriate. Probably the best way to do this is to follow the advice here:
https://square.github.io/okhttp/3.x/okhttp/okhttp3/OkHttpClient.html

That said, giving them numbers might help with tracing.

**Comment by swankjesse** [comment]
For the ReaderRunnable it’ll be simpler to just use a regular Runnable (not a NamedRunnable) and set the thread name at construction.

**Comment by wobondar** [comment]
Is there any chance to get it? Thanks.

**Comment by yschimke** [comment]
I think this is supported now.
