### ISSUE TITLE
Bug? LogInterceptor Question

### ISSUE THREAD

**Issue by GhostInMatrix** [square/okhttp#3798]
The chain.connection() . in LoggingInterceptor from the example is always null.
I am so confused.
In the CallServerInterceptor, the chain.connection() is not null.But, after that,in LogginInterceptor,it becomes null.
DId I miss something?  How can I resolve this problem?

**Comment by swankjesse** [comment]
It's non-null if you install it as a network interceptor.
https://github.com/square/okhttp/wiki/Interceptors

**Comment by GhostInMatrix** [comment]
Thanks mate, your answer is so important for me!
