### ISSUE TITLE
[Feature Request] Authenticator supports only http code 401, add posibility to change the code

### ISSUE THREAD

**Issue by Kolyall** [square/okhttp#3800]
Authenticator supports only http code 401, 
https://square.github.io/okhttp/3.x/okhttp/okhttp3/Authenticator.html

> When authentication is requested by an origin server, the response code is 401 and the implementation should respond with a new request that sets the "Authorization" header. 

Add posibility to change the code to any other. Thanks.

**Comment by yschimke** [comment]
A few questions/points

1) You can implement preemptive authentication using an Interceptor, and probably should, if you have prior knowledge about the behaviours of particular servers.  
2) There is some discussion about enhancing the support for authentication e.g. https://github.com/square/okhttp/issues/2435
3) Can you give an example where you want other response codes and how it should be handled?

**Comment by Kolyall** [comment]
@yschimke 
3. Server return to me not 401 error code, but 423(own created)
1. Does Interceptor work like Authenticator?
What if I have two simultaneously request , and each will catch 423 error, and then each will send request to refreshToken?

**Comment by yschimke** [comment]
A normal (not network) interceptor should be able to retry the request synchronously (execute, not enqueue) in your own interceptor, or you can retry once the entire request fails.  If you implement your own interceptor you can do anything you need in respect to concurrency etc.

**Comment by swankjesse** [comment]
No action to take on this.
