### ISSUE TITLE
Multiple websocket connections

### ISSUE THREAD

**Issue by njovy** [square/okhttp#3801]
```
    OkHttpClient client =
        new OkHttpClient.Builder().connectionPool(new ConnectionPool(10, 5, TimeUnit.MINUTES))
            .build();
    for (int i = 0; i < 10; i++) {
      client.newWebSocket(new Request.Builder().url("wss://echo.websocket.org").build(),
          new WebSocketListener() {
            @Override public void onOpen(WebSocket webSocket, Response response) {
              super.onOpen(webSocket, response);
              System.out.println("response=" + response);
            }
          });
    }
```
Above is the code to create 10 multiple websocket clients concurrently. However, it only opens 5 websocket connections.

**Comment by JakeWharton** [comment]
Ooooo this is a side effect of Dispatcher policy. Good catch.

You can set a custom max connections per host yourself for now on the
Dispatcher.

**Comment by JakeWharton** [comment]
I'm tempted to simply exempt WS connections from the policy.

**Comment by njovy** [comment]
Wow! Thank you for a rapid response.
I set a custom max connections per host as you advised and it works like a charm.

**Comment by swankjesse** [comment]
Yeah, let's exempt then. Though I also think it's strange to have more than one!
