### ISSUE TITLE
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256 support

### ISSUE THREAD

**Issue by DanielCharczynski** [square/okhttp#3807]
Hello

ConnectionSpec.APPROVED_CIPHER_SUITES contains TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA but there is no TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256 

As SHA1 has been deprecated due to its security vulnerabilities, it is important to ensure you are no longer using an SSL certificate which is signed using SHA1. All major SSL certificate issuers now use SHA256 which is more secure and trustworthy.

Could you add TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256 to APPROVED_CIPHER_SUITES?

Because of that we have handshake_failure in java7

**Comment by swankjesse** [comment]
I should confirm the latest versions of Chrome and Firefox. Last time we checked that cipher suites wasn't enabled in either of those browsers.

It is also disabled by default on Android.

It is, however, available on both Android and Java if you’d like to enable it in your own programs.

http://tinyurl.com/okhttp-cipher-suites

**Comment by DanielCharczynski** [comment]
In java it is enabled by default and it works in pure java but when I'm using OkHttp it doesn't work because APPROVED_CIPHER_SUITES restrict default behavior/chipers.

My problem is that third party library is using okhttp and with default configuration but default configuration in okhttp doesn't match default java ciphers.

Is there any problem to add this cipher?

**Comment by swankjesse** [comment]
Yeah, I’d prefer we only add widely-used cipher suites, such as those enabled-by-default in Chrome and Firefox. If there’s a problem with them, we’re in good company. I’m worried about performance or security problems with cipher suites that we use but that aren’t used by other user-agents.

**Comment by yschimke** [comment]
Closing as this can be easily fixed in client without change to OkHttp
