### ISSUE TITLE
Spnego/Kerberos authentication

### ISSUE THREAD

**Issue by KevCel** [square/okhttp#3808]
Hi,
Is any solutions for spnego or kerberos authentication?

**Comment by yschimke** [comment]
I haven't tried, but a google search produced this https://github.com/marklogic/java-client-api/commit/9cc65f86ab23c166ebb0f5aeb2721684d2f07de4

This seems like something that ideally a well documented open source library would provide.  But I haven't seen anything like that.

**Comment by swankjesse** [comment]
Nothing actionable here.
