### ISSUE TITLE
after a network change, throw javax.net.ssl.SSLException 

### ISSUE THREAD

**Issue by dabutaizha** [square/okhttp#3814]
Close the network Click Send Request enter Reconnection interface, and then open the network click Try reconnect 

throw javax.net.ssl.SSLException
<pre><code>javax.net.ssl.SSLException: Write error: ssl=0x7f7e95c400: I/O error during system call, Software caused connection abort
02-02 15:23:07.256 6958-6958/com.cf.xinmanhua W/System.err:     at com.android.org.conscrypt.NativeCrypto.SSL_write(Native Method)
02-02 15:23:07.256 6958-6958/com.cf.xinmanhua W/System.err:     at com.android.org.conscrypt.OpenSSLSocketImpl$SSLOutputStream.write(OpenSSLSocketImpl.java:824)
02-02 15:23:07.256 6958-6958/com.cf.xinmanhua W/System.err:     at okio.Okio$1.write(Okio.java:79)
02-02 15:23:07.256 6958-6958/com.cf.xinmanhua W/System.err:     at okio.AsyncTimeout$1.write(AsyncTimeout.java:180)
02-02 15:23:07.257 6958-6958/com.cf.xinmanhua W/System.err:     at okio.RealBufferedSink.flush(RealBufferedSink.java:216)
02-02 15:23:07.257 6958-6958/com.cf.xinmanhua W/System.err:     at okhttp3.internal.http1.Http1Codec.finishRequest(Http1Codec.java:166)
02-02 15:23:07.257 6958-6958/com.cf.xinmanhua W/System.err:     at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:72)
02-02 15:23:07.257 6958-6958/com.cf.xinmanhua W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
02-02 15:23:07.257 6958-6958/com.cf.xinmanhua W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
02-02 15:23:07.257 6958-6958/com.cf.xinmanhua W/System.err:     at com.facebook.stetho.okhttp3.StethoInterceptor.intercept(StethoInterceptor.java:59)
02-02 15:23:07.257 6958-6958/com.cf.xinmanhua W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
02-02 15:23:07.257 6958-6958/com.cf.xinmanhua W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
02-02 15:23:07.257 6958-6958/com.cf.xinmanhua W/System.err:     at com.ulab.newcomics.api.NewComicClient$1.intercept(NewComicClient.java:68)
02-02 15:23:07.257 6958-6958/com.cf.xinmanhua W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
02-02 15:23:07.257 6958-6958/com.cf.xinmanhua W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
02-02 15:23:07.257 6958-6958/com.cf.xinmanhua W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
02-02 15:23:07.257 6958-6958/com.cf.xinmanhua W/System.err:     at com.android.tools.profiler.support.network.okhttp.reflection.okhttp3.Interceptor$$Chain$.proceed(Interceptor$.java:52)
02-02 15:23:07.257 6958-6958/com.cf.xinmanhua W/System.err:     at com.android.tools.profiler.support.network.okhttp.OkHttp3Interceptor.invoke(OkHttp3Interceptor.java:53)
02-02 15:23:07.257 6958-6958/com.cf.xinmanhua W/System.err:     at java.lang.reflect.Proxy.invoke(Proxy.java:813)
02-02 15:23:07.257 6958-6958/com.cf.xinmanhua W/System.err:     at $Proxy1.intercept(Unknown Source)
02-02 15:23:07.257 6958-6958/com.cf.xinmanhua W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
02-02 15:23:07.257 6958-6958/com.cf.xinmanhua W/System.err:     at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
02-02 15:23:07.257 6958-6958/com.cf.xinmanhua W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
02-02 15:23:07.257 6958-6958/com.cf.xinmanhua W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
02-02 15:23:07.257 6958-6958/com.cf.xinmanhua W/System.err:     at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
02-02 15:23:07.257 6958-6958/com.cf.xinmanhua W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
02-02 15:23:07.257 6958-6958/com.cf.xinmanhua W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
02-02 15:23:07.257 6958-6958/com.cf.xinmanhua W/System.err:     at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
02-02 15:23:07.258 6958-6958/com.cf.xinmanhua W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
02-02 15:23:07.258 6958-6958/com.cf.xinmanhua W/System.err:     at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
02-02 15:23:07.258 6958-6958/com.cf.xinmanhua W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
02-02 15:23:07.258 6958-6958/com.cf.xinmanhua W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
02-02 15:23:07.258 6958-6958/com.cf.xinmanhua W/System.err:     at com.ulab.newcomics.api.NewComicClient$1.intercept(NewComicClient.java:68)
02-02 15:23:07.258 6958-6958/com.cf.xinmanhua W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
02-02 15:23:07.258 6958-6958/com.cf.xinmanhua W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
02-02 15:23:07.258 6958-6958/com.cf.xinmanhua W/System.err:     at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185)
02-02 15:23:07.258 6958-6958/com.cf.xinmanhua W/System.err:     at okhttp3.RealCall$AsyncCall.execute(RealCall.java:135)
02-02 15:23:07.258 6958-6958/com.cf.xinmanhua W/System.err:     at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
02-02 15:23:07.258 6958-6958/com.cf.xinmanhua W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
02-02 15:23:07.258 6958-6958/com.cf.xinmanhua W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
02-02 15:23:07.258 6958-6958/com.cf.xinmanhua W/System.err:     at java.lang.Thread.run(Thread.java:761)</code></pre>

**Comment by swankjesse** [comment]
This is working as intended. When the network disappears OkHttp notifies you with an exception. If you need to retry your request, you should. OkHttp can't do that automatically because it doesn't know whether retrying will be useful.
