### ISSUE TITLE
Chunked Transfer Encoding Response

### ISSUE THREAD

**Issue by judemanutd** [square/okhttp#3818]
The app is making a request to an endpoint which is sending back a json string containing data fetched from the database. This data could sometimes get pretty huge, as big as 4mb, the default Transfer-Encoding for the server is chunked so when the data is big enough it splits it into chunks and sends it to the app. The problem is Retrofit doesn't seem to be handling that out of the box and crashes with an EOF error. How can this i let Retrofit or rather OkHttp know that the response could be chunked?

**Comment by yschimke** [comment]
The server sending "Transfer-encoding: chunked" as a header should be enough.  If you find it is not, please include more information like example headers from the server, or a test server we can submit requests against.
