### ISSUE TITLE
HttpLoggingInterceptor leaks Authorization Header

### ISSUE THREAD

**Issue by mnembrini** [square/okhttp#3826]
Feature Request/Bug:

When using Level.HEADERS or Level.BODY all HTTP headers of request and response are printed. 
If someone is using these for e.g. tests running on a CI server, the logs will leak authorization tokens. 

There is a warning in the README about not using this in production, but I think it would be very easy to redact values of sensitive headers (I think "Authorization" and "Proxy-Authorization" are the only ones?)

I have already working code for this, but I wanted to know if this is something you would like to see upstreamed and how it should be configured: e.g. by adding more levels or adding a boolean *redactSensitiveHeaders* to the constructor.

**Comment by JakeWharton** [comment]
A boolean isn't a very future-proof solution. We could accept a list. Or
add a builder where you could add individual headers.
