### ISSUE TITLE
Thread safety for cancel in RetryAndFollowUpInterceptor

### ISSUE THREAD

**Issue by electrum** [square/okhttp#3834]
The `streamAllocation` field is written by the `intercept()` method and then read by the `cancel()` method, which per the Javadoc is safe to call from any thread. However, there is no *happens-before relationship* between the write and read, so it's possible that the reader will always see null, see an old value, see a partially constructed object, etc.

**Comment by swankjesse** [comment]
Yeah, I think you’re right. Should be `volatile` like `canceled`.

**Comment by electrum** [comment]
I thought it might be taking advantage of volatile piggybacking of the `canceled` field, but the relationship is backwards, since the writer of `streamAllocation` is reading from `canceled`.

**Comment by swankjesse** [comment]
Yeah, reasoning about this hurts my head. In either case, `volatile` here is an easy fix.
