### ISSUE TITLE
List of encryption algorithms used in library

### ISSUE THREAD

**Issue by jmkyo** [square/okhttp#3847]
Can you please share a list of encryption algorithms (+ bit strengths) that are part of okhttp?

We're using the library and need to know it for export control purposes (paper work).
e.g., AES, 3DES, RSA, RC4, etc

**Comment by yschimke** [comment]
So technically, I think this just comes from the JVM plus any additional providers.  OkHttp doesn't implement any encryption algorithms.  OkHttp can default which to use, but they can be overridden and missing default ones will just be skipped.

**Comment by yschimke** [comment]
I guess use this list if you just need *an* answer

https://github.com/square/okhttp/blob/c70e35802e984e8b9bf3fbf1479deb37c0bdfa43/okhttp/src/main/java/okhttp3/ConnectionSpec.java#L46-L65

**Comment by jmkyo** [comment]
Thanks!
