### ISSUE TITLE
[Feature Request] introduce "Message Written" callback for Websocket

### ISSUE THREAD

**Issue by mostroverkhov** [square/okhttp#3848]
**Problem**

Pending messages queue is capped, and connection gets closed if new message hits queue limit. 
I have 2 issues there:

* Its hard to efficiently send big payloads (e.g. big file sliced into chunks) without resorting to polling `WebSocket.queueSize`
* If new message exceeds queue size (16 MiB currently, not exposed ), I would like to signal that to client  without closing connection.

**Possible solution**
  
* Enhance `WebsocketListener` with `onMessageWritten(WebSocket)`
* Enhance `Websocket` with `maxQueueSize` (it has `queueSize` already)

**Comment by swankjesse** [comment]
If your application is approaching a full queue it's quite likely that websockets are an awkward fit for your data.

Websockets work best for small, latency-sensitive messages like chat. When your queue is full, you aren't low-latency.

In such cases, consider just using HTTP. It's better suited for big payloads.

That said, exposing the max queue size isn't unreasonable. In the interim you can assume it's 16 MiB.

**Comment by mostroverkhov** [comment]
OkHttp Websockets is used as transport for [RSocket-android](https://github.com/rsocket/rsocket-android) protocol implementation, which makes no distinction regarding use-cases (everything in `Publisher<Payload>`). Proposed `WebsocketListener` changes would allow updating said transport in a way that upstream Publisher does not overwhelm OkHttp on low quality connection or network hiccup. 

Http is not an option as It is request-response only and is wasteful for binary protocol. 

Can you explain your concerns regarding `onMessageWritten`? (except breaking change one)

**Comment by swankjesse** [comment]
Got it. This explanation is helpful.

The biggest challenge to doing onMessageWritten is we’d need to invoke it on a different thread from the one doing the writing.

The other giant problem is that onMessageWritten doesn't confirm anything about whether the message has been received. That needs to happen at the application layer.

I think the right solution for RSocket is to do something similar to the flow control in HTTP/2. Add back pressure to the application protocol and manage it there.

**Comment by mostroverkhov** [comment]
@swankjesse Ah, with `onMessageWritten` I meant something similar to Netty `OutboundHandler.write()`, which signals when message is removed from outbound buffer. But I see Okhttp is designed in a way that `written` callback is redundant - thanks for explanation.

Also, for valuable insights into http2 flow control - will do!
