### ISSUE TITLE
Consider making HttpUrl.getChecked() public

### ISSUE THREAD

**Issue by grodin** [square/okhttp#3850]
Using `HttpUrl.parse()` in Kotlin to parse constant urls that you know will parse is slightly annoying because of the nullable return. 

I've worked around it by writing a static method `parseHttpUrlOrThrow()` but this essentially duplicates the existing `HttpUrl.getChecked()`, which is unfortunately package private. It would be useful if this method was public.

**Comment by JakeWharton** [comment]
We've talked about this for a long time. It's caused at least one bug in Retrofit and OkHttp thus far.

**Comment by swankjesse** [comment]
Isn't it just `parse(url)!!` ?

**Comment by JakeWharton** [comment]
Assuming you remember that, yes. In Java you don't. And in Kotlin it's a platform type so you sometimes are forced to.

**Comment by JakeWharton** [comment]
Another advantage of a throwing version is that it's able to communicate useful information about the reason why it failed.

**Comment by shaburov** [comment]
+1

**Comment by yschimke** [comment]
oops PR hasn't landed yet
