### ISSUE TITLE
EventListener fires responseHeadersStart too early

### ISSUE THREAD

**Issue by yschimke** [square/okhttp#3861]
Low priority

We currently fire immediately after completing the request.

![image](https://user-images.githubusercontent.com/231923/36351711-e0345182-14a5-11e8-9a7f-91a0dc74e78b.png)

Realistically it looks more like this

![image](https://user-images.githubusercontent.com/231923/36351720-ed8c5cee-14a5-11e8-99e2-01f38c586688.png)

The second is by logging requestHeadersEnd which is only true when request headers are in a single frame.

**Comment by toncid** [comment]
This is a bug, rather than an enhancement. Please check #5578.

**Comment by yschimke** [comment]
Now a dupe
