### ISSUE TITLE
Review a couple of ConscryptPlatform issues before 3.10 release

### ISSUE THREAD

**Issue by yschimke** [square/okhttp#3862]
1) Is it safe to use "Conscrypt" in

https://github.com/square/okhttp/blob/19726969aabbd0791d315994384a0cc46bf41648/okhttp/src/main/java/okhttp3/internal/platform/Platform.java#L194

Based on this diff https://github.com/google/conscrypt/pull/426

2) Should we avoid setting and then assuming any Conscrypt platform defaults e.g.

https://github.com/square/okhttp/blob/19726969aabbd0791d315994384a0cc46bf41648/okhttp/src/main/java/okhttp3/internal/platform/ConscryptPlatform.java#L106

May be able to move to using per connection settings.

**Comment by yschimke** [comment]
cc @nmittler

**Comment by yschimke** [comment]
If we want to land the second change

https://github.com/square/okhttp/pull/3868/

**Comment by yschimke** [comment]
For the first one

https://github.com/square/okhttp/pull/3869

**Comment by nmittler** [comment]
@yschimke 

You should test the provider using [Conscrypt.isConscrypt()](https://github.com/google/conscrypt/blob/master/common/src/main/java/org/conscrypt/Conscrypt.java#L64).

`ConscryptPlatform` looks good to me.

@flooey, want to take a look as well?

**Comment by yschimke** [comment]
@nmittler We don't want to rely on having Conscrypt loaded at this point.  Ideally you could ship OkHttp without having to have Conscrypt also.

**Comment by nmittler** [comment]
@yschimke ok, that makes sense. In that case, you'll need to check for `Conscrypt` or `AndroidOpenSSL`.

See https://github.com/google/conscrypt/search?utf8=%E2%9C%93&q=getDefaultProviderName&type=

**Comment by flooey** [comment]
@yschimke There are actually three names and three packages that you're likely to encounter in the wild:

- `"Conscrypt"` + `org.conscrypt.OpenSSLProvider` - Public builds of the library, though users can customize the provider name via OpenSSLProvider's constructor.
- `"AndroidOpenSSL"` + `com.android.org.conscrypt.OpenSSLProvider` - The platform-included copy on Android.
- `"GmsCore_OpenSSL"` + `com.google.android.gms.org.conscrypt.OpenSSLProvider` - The copy of Conscrypt installed by Google Play Services via ProviderInstaller.

The latter two will of course only appear on Android.

You could probably get by with checking `provider.getClass().getName().endsWith("org.conscrypt.OpenSSLProvider")`, which should cover all the cases.

**Comment by yschimke** [comment]
@nmittler @flooey thanks for the explanation, given this check are all post "Are we in Android" which uses the Android Platform, I think checking "Conscrypt"/OpenSSLProvider works.
