### ISSUE TITLE
Let's encrypt certificate support for Android API < 20

### ISSUE THREAD

**Issue by perrosnk** [square/okhttp#3880]
What kind of issue is this?

Bug report

Description:
I have a node server which uses Let's Encrypt CA and it's hosted on zeit.now. The client is developed using react-native. I try to connect to it using websockets.

On iOS and newer Android versions (API > 20) it connects successfully.

When running on older Android versions (both on simulator and actual devices) it never connects.

I have tried to connect using older Android version to a server that's not using Let's encrypt CA (but IS using ssl from other provider - hosted on heroku), and it also connects successfully.

So I believe there is something wrong with older Android versions and Let's encrypt certificate.

Could someone help? I have lost 5 days researching this problem and I don't know a lot about JAVA.

**Comment by swankjesse** [comment]
You’re going to need to set up a custom trust store that trusts LetsEncrypt. We have a full example here:

https://github.com/square/okhttp/blob/master/samples/guide/src/main/java/okhttp3/recipes/CustomTrust.java

I don’t know how you hook that up to React Native.
