### ISSUE TITLE
Expected ':status' header not present

### ISSUE THREAD

**Issue by xiaozuozi** [square/okhttp#3882]
when i use get request,it cause this exception,the version is 3.3.1

**Comment by yschimke** [comment]
This seems like a bad server, could you provide either a test case, or reproduction steps against a public server?

**Comment by xiaozuozi** [comment]
the url is https://fir.im/apps/latest/59f6f318959d695680000a5c?api_token=519257864d9d2fc7f4f38132c3827416,the method i use is OkHttpUtils.get().url(url).build().connTimeOut(6000).execute(callback);

**Comment by yschimke** [comment]
I get a clean 401.  So can't do much with this at the moment.

HTTP/1.1 401
{
  "errors": {
    "exception": [
      "Authentication failed"
    ]
  },
  "code": 100020
}

**Comment by xiaozuozi** [comment]
i update the the okhttp and then solve the question

**Comment by xiaozuozi** [comment]
when i upload 5 pictures one time,i hava got --> END POST (2024087-byte body)
                                                                        <-- HTTP FAILED: java.net.SocketTimeoutException
how can i solve this question?

**Comment by yschimke** [comment]
Can you ask these types of typical use and error handling questions on stackoverflow.  This is for reporting confirmed reproducible bugs.
