### ISSUE TITLE
When use OkHttpClient,Java Mission Control Thread Blocking Count NUM column display a big Num?

### ISSUE THREAD

**Issue by ex34toway** [square/okhttp#3891]
What kind of issue is this?

When use OkHttpClient,Java Mission Control Thread Blocking Count NUM column display a big Num?
      OkHttp ConnectionPool thread blocking num is very big,even more than Finalizer?
![qq 20180226142925](https://user-images.githubusercontent.com/17397753/36656164-ee89ea78-1b01-11e8-9a0b-8dae8ad93103.jpg)

**Comment by yschimke** [comment]
Most likely you are *not* reusing a single OkHttp instance? 

n.b. Please ask this sort of question on stackoverflow in future, and use the issue tracker for reproducible issues (logs or a failing test).

**Comment by ex34toway** [comment]
@yschimke Thank you!Yeah.aam. My code like this:
globalOkHttpClient.newBuilder().connectTimeout(10,TimeUnit.SECONDS).build() 
to new a Instance,that still can't avoid slove this problem,must keep in mind,Only a OkHttp instance? Because business logic have vary HTTP rest invoke,timeout paramter must set in different OkHttpClient instance.So,how to do that?

**Comment by yschimke** [comment]
Can you post your question on stackoverflow and I'll answer there.

**Comment by ex34toway** [comment]
Ok,i posted the question.https://stackoverflow.com/questions/36009889/okhttp-connection-timeout

**Comment by ex34toway** [comment]
@yschimke Hi,please answer it.I'm waiting for you.
