### ISSUE TITLE
When Content-Encoding: gzip is used, and the content-length header is removed, and the underlying socket connection is not broken, the client is blocked when the body data is read

### ISSUE THREAD

**Issue by twoeggs** [square/okhttp#3892]
When Content-Encoding: gzip is used, and the content-length header is removed, and the underlying socket connection is not broken, the client is blocked when the body data is read, until the connection is disconnected or the request timed out. The same scenario, using httpclient request is not blocked, through my debugging blocking problems found in okio class okio. GzipSource in the read method, my feel this time should be returned -1, since the gzip data has been finished, now is no longer able to call the read method，Because there is no data to read in the current stream.

**Comment by twoeggs** [comment]
Normally, the standard httpresponse has a head "content-length/chunked", but for some unknown reason, the content-length head may be removed by the gateway, so it is still necessary to adapt.

**Comment by twoeggs** [comment]
Even if it is not supported, the average user can accept interrupts or exceptions at this time, but cannot accept that the program is blocked.

**Comment by twoeggs** [comment]
![1519642060152](https://user-images.githubusercontent.com/15973584/36666421-900efc44-1b25-11e8-92ee-6ccc9989b652.jpg)

**Comment by swankjesse** [comment]
Same bug?
https://github.com/square/okhttp/issues/3759

**Comment by twoeggs** [comment]
Thank you for your reply.I looked at it #3759 ，The question he's discussing is very similar to what I'm saying, but it's actually different, and I pointed out that the problem is okhttp client is blocked due to no content-length problem, I here is a test server code : 
[MockHttpserver.java.zip](https://github.com/square/okhttp/files/1761165/MockHttpserver.java.zip)

client code:
<img width="819" alt="wx20180227-115923 2x" src="https://user-images.githubusercontent.com/15973584/36709939-b1548b22-1bb5-11e8-9d89-a575547d531d.png">

**Comment by twoeggs** [comment]
When the call response.body().string() is blocked, the timeout exception occurs when the timeout occurs in 30 seconds. The root cause is that the socket on the server side is not closed immediately (the long connection is simulated).
<img width="252" alt="wx20180227-120216" src="https://user-images.githubusercontent.com/15973584/36710033-5829fbd0-1bb6-11e8-8b7f-167c1a67153b.png">

**Comment by twoeggs** [comment]
There is no data to read in the buffer at this point, so when you try to read when it is blocked, in fact gzip is fully transmitted when the data is complete, and the entire request process should end normally.

**Comment by yschimke** [comment]
My reading of what is described is that it's almost the same bug as #3759.  In 3759, we receive a full content length header with multiple streams and fail because we don't expect multiple streams.  Here we receive a single stream without termination(?) and if we assumed a single gzip stream and self terminated we would work in this case.

Seems awkward to fix 3759 without keeping this failing.  And it does sound like there is a problem with the server behaviour on this issue that is the root cause and should be the highest priority fix.

What clients does this server work correctly with?

**Comment by twoeggs** [comment]
Yes！ Here we receive a single stream without termination。
It seems that there is a problem with server behavior. In this scene in fact the problem is not on the server, but in the middle gateway node.
The HTTP response that the server sends out is the "content-length" header, which is removed by the gateway of some router in the middle. This is not something we can solve, but it should be compatible.

**Comment by swankjesse** [comment]
I think it would be bad if we changed OkHttp to not exhaust the stream. That breaks connection reuse and caching.

The right fix here is to not do wacky things on the server.
