### ISSUE TITLE
Update to 3.10 => Android 4.4 SLL Handcheck Error

### ISSUE THREAD

**Issue by thelittlefireman** [square/okhttp#3894]
Hi,
just to warn that i've got an SLL error on Android 4.4 version when i update from 3.9.1 to 3.10.

`error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure (external/openssl/ssl/s23_clnt.c:741 0x5c528d38:0x00000000) ---> Java.IO.IOException: SSL handshake aborted: ssl=0x59a0feb8: Failure in SSL library, usually a protocol error`

I try many things like : [https://github.com/square/okhttp/issues/2372](https://github.com/square/okhttp/issues/2372) or this : 

```
ConnectionSpec spec = new ConnectionSpec.Builder(ConnectionSpec.MODERN_TLS)  
    .tlsVersions(TlsVersion.TLS_1_2)
    .cipherSuites(
          CipherSuite.TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,
          CipherSuite.TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,
          CipherSuite.TLS_DHE_RSA_WITH_AES_128_GCM_SHA256)
    .build();

OkHttpClient client = new OkHttpClient.Builder() 
    .connectionSpecs(Collections.singletonList(spec))
    .build();
```

or this : 
` ProviderInstaller.installIfNeededAsync(this.getApplicationContext())`

But nothing works and i've got unsuportedSLLEncryption or unknow

**Comment by plastiv** [comment]
Can you share hostname you are connecting to? 
Also try https://www.ssllabs.com/ssltest/analyze.html to get better understanding of what your server supports.

**Comment by thelittlefireman** [comment]
it's https://rappel_produits.berlioz.me

**Comment by plastiv** [comment]
Yup, it looks like removed from okhttp 3.10 ciphers are your server only supported 

https://www.ssllabs.com/ssltest/analyze.html?d=berlioz.me&s=2400%3acb00%3a2048%3a1%3a0%3a0%3a6818%3a69ee
![image](https://user-images.githubusercontent.com/179550/36725483-bbf632e6-1bb6-11e8-85a1-e0046b40289a.png)

https://github.com/square/okhttp/blob/master/CHANGELOG.md#version-3100
![image](https://user-images.githubusercontent.com/179550/36725535-e0b3c634-1bb6-11e8-81c3-5468f3913e00.png)

**Comment by thelittlefireman** [comment]
how should i fix the issue ? I'm on a synology behind cloudflare

**Comment by Radwa13** [comment]
thanks @thelittlefireman thelittlefireman it works for me :)

**Comment by shekh-akther** [comment]
To know which TLS versions and Cipher suites are supported by your server, first analyse by any SSL Analyzer (i.e. sslanalyzer.comodoca.com) then update your ConnectionSpec code accordingly.
