### ISSUE TITLE
ConscryptPlatform platform should not globally configure Conscrypt.setUseEngineSocketByDefault

### ISSUE THREAD

**Issue by cakofony** [square/okhttp#3895]
What kind of issue is this?

 - [x] Bug report.

`ConscryptPlatform.buildIfSupported()` globally sets `Conscrypt.setUseEngineSocketByDefault(true)`, which causes HttpUrlConnections used across the jvm to behave differently (connections external to okhttp, okhttp itself works fine). In my case I'm seeing socket timeouts causing tests to fail where there aren't problems with `setUseEngineSocketByDefault` disabled.

Proposed Fix:
We can invoke `Conscrypt.setUseEngineSocket(SSLSocketFactory, true)` on the `SSLSocketFactory` instance rather than setting global configuration.

**Comment by yschimke** [comment]
Just saw this issue. It might be also worth reporting to the conscrypt project.

**Comment by nmittler** [comment]
cc @flooey

@yschimke the FD and engine-based sockets do differ WRT detection of the underlying socket closure. when wrapping another socket.  The FD socket cheats by obtaining the underlying FD for the wrapped socket and detecting when it is closed.  The engine-based socket relies on operations of the wrapped Java socket to fail, which can take a while depending on the configuration.
