### ISSUE TITLE
Majority of rest call time spent in "readResponseHeaders()"

### ISSUE THREAD

**Issue by bjoernw** [square/okhttp#3897]
I'm really sorry to be asking a question here but I'm not having any luck on stackoverflow. I'm trying to figure out what the root cause would be of my code spending 90% of its time in Http1xStream.readResponseHeaders() while the actual external call just takes 167ms. Any guidance would be hugely appreciated.

<img width="915" alt="vo7hp" src="https://user-images.githubusercontent.com/1467156/36751066-f1ec45b4-1bb3-11e8-9189-3132955b7398.png">

Feel free to delete this issue and respond on https://stackoverflow.com/questions/47373602/time-spent-in-okhttp3-internal-http-http1xstream-readresponseheaders

thanks!

**Comment by JakeWharton** [comment]
It's blocked waiting for the first byte of the response after sending the request.

**Comment by bjoernw** [comment]
@JakeWharton great, thanks for the quick response. I guess NewRelic doesn't count it into the time spent making the external http call.
