### ISSUE TITLE
ConnectionSpec.RESTRICTED_TLS

### ISSUE THREAD

**Issue by swankjesse** [square/okhttp#3903]
Currently we do MODERN_TLS and COMPATIBLE_TLS. We should add RESTRICTED_TLS with only the most secure configuration.

Inspired by this:
https://cloudplatform.googleblog.com/2018/02/announcing-SSL-policies-for-HTTPS-and-SSL-proxy-load-balancers.html?m=1

**Comment by yschimke** [comment]
https://github.com/square/okhttp/pull/3908

**Comment by yschimke** [comment]
Yep, just not released yet.
