### ISSUE TITLE
Use FormBody.Builder add picture Base64 string cost hundreds of millisecond,how can I optimize it？

### ISSUE THREAD

**Issue by gitgzw** [square/okhttp#3906]

**Comment by yschimke** [comment]
Please ask questions like this on stackoverflow preferably with code showing how you are using the APIs.  This issue tracker is for reporting reproducible bugs, and posting to stackoverflow will help others in future.

**Comment by gitgzw** [comment]
Okay,I will ask this question on stackoverflow quickly!
