### ISSUE TITLE
Peril of using Date as the value of If-Modified-Since

### ISSUE THREAD

**Issue by AlexBonel** [square/okhttp#3911]
I would like to elaborate a bit on #2951. 

We've encountered with situation when you may get inconsistency between requests while the server side undergoes it's state change. Let me illustrate the problem in sequence of 3 requests:

The server provides `Date` header in all responses to the client replicating current time on the server (it's provided by nginx).

1) You make first request and get `Last-Modified` and `Date` headers in response.
2) You make the second request with `Last-Modified` as `If-Modified-Since` value and get 4xx response without `Last-Modified` header but with `Date` header in it. At this moment the server undergoes state change which implies presence of requested data by the time of next request. And the _update time_ is equal to server's `Date`value.
3) You make 3d request but instead of sending `If-Modified-Since` with `Last-Modified` you send `Date` value in it. And get 304 as _update time_ equals to `If-Modified-Since` (`Date` from 2nd response) value.

So I was interested of what rfc suggests on this issues and the only thing I've found is:

> Note: If a client uses an arbitrary date in the If-Modified-Since
      header instead of a date taken from the Last-Modified header for
      the same request, the client should be aware of the fact that this
      date is interpreted in the server's understanding of time. The
      client should consider unsynchronized clocks and rounding problems
      due to the different encodings of time between the client and
      server. This includes the possibility of race conditions if the
      document has changed between the time it was first requested and
      the If-Modified-Since date of a subsequent request, and the
      possibility of clock-skew-related problems if the If-Modified-
      Since date is derived from the client's clock without correction
      to the server's clock. Corrections for different time bases
      between client and server are at best approximate due to network
      latency. ([origin](https://tools.ietf.org/html/rfc2616#page-130))

So I would like to know what was the motivation behind the decision to use `Date` value as potential value of `If-Modified-Since` ?

**Comment by swankjesse** [comment]
Some information on using a response’s `Date` in a request’s `If-Modified-Since` parameter is here:
https://tools.ietf.org/html/rfc7232#section-2.2.2

I think the underlying problem is that the client is keeping a cacheable 4xx response (404, 405, 410 or 414) but the server doesn’t expect such responses to be cached. For such cases maybe the server should provide a header to prevent caching? `Cache-Control: no-store` ?

**Comment by AlexBonel** [comment]
Jesse, thanks for suggestion! We'll definitely consider using of `Cache-Control` in such situations.
