### ISSUE TITLE
SocketTimeoutException in background service only

### ISSUE THREAD

**Issue by Riningan** [square/okhttp#3914]
Hello!
I have background service.
He periodically send data to server.
When activity is dead (no in app list)? I catch always exception:
java.net.SocketTimeoutException: failed to connect to m2mtest.nis-glonass.ru/213.87.44.109 (port 443) after 35000ms: isConnected failed: ETIMEDOUT (Connection timed out)
But when I start activity, exception gone and service works fine.
Is any constraints to work in background?

**Comment by JakeWharton** [comment]
Dupe of https://github.com/square/retrofit/issues/2684
