### ISSUE TITLE
Add easy way to set date header.

### ISSUE THREAD

**Issue by NightlyNexus** [square/okhttp#3921]
I want to put the date header (https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Date) on all my requests.

```java
static final ThreadLocal<DateFormat> DATE_HEADER_FORMAT =
      new ThreadLocal<DateFormat>() {
        @Override protected DateFormat initialValue() {
          DateFormat format = new SimpleDateFormat("EEE, dd MMM yyyy HH:mm:ss 'GMT'", Locale.US);
          format.setTimeZone(TimeZone.getTimeZone("GMT"));
          return format;
        }
      };
...
requestBuilder.addHeader("Date", DATE_HEADER_FORMAT.get().format(new Date())
```

I'd like to remove this code in favor of perhaps `okhttp3.Headers.setDate(Date)`.

The downside is that it opens up discussion about other general headers that _could_ be added to the Headers API. Is this general-purpose enough?

**Comment by swankjesse** [comment]
You'd also want overloads for the Request.Builder.

**Comment by NightlyNexus** [comment]
Headers.Builder could be fine.
```java
Headers headers = request.headers();
request = request.newBuilder()
    .headers(headers.newBuilder().setDate(new Date()).build())
    .build();
```
or maybe that's too hidden, then?
Agree that it opens up a lot of questions about conveniences.

**Comment by yschimke** [comment]
+1 I think OkHttp could usefully provide constants and formatters for more headers.  Would it be worth a sweep through https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers?

Date is also pretty common in responses.

**Comment by JakeWharton** [comment]
So long as we provide a java.time overload to anything we add. Date is bad, bad news.

**Comment by yschimke** [comment]
I thought java.time was Android O?

**Comment by JakeWharton** [comment]
It was, yes.

**Comment by jjshanks** [comment]
I did a pull request for this but left out the java.time stuff since that is newer and didn't want to break backward compatibility.
