### ISSUE TITLE
switching from network with no proxy to network with proxy breaks http/2

### ISSUE THREAD

**Issue by steelbytes** [square/okhttp#3924]
What kind of issue is this?
 - [x] Bug report. If you’ve found a bug, spend the time to write a failing test. Bugs with tests
       get fixed. Here’s an example: https://gist.github.com/swankjesse/981fcae102f513eb13ed

steps:
* start app (android app using okhttp 3.10.0) and connect to http/2 server via network that doesn't use proxy, eg on mobile data
* move to a wifi with proxy (squid 3.5.12) without restarting the app
* okhttp gernerates lots of socket closed errors (and never seems to recover)
* close & restart app
* app now works

note: the wifi proxy uses a proxy pac file - not sure if this matters

edit: note sure about squid not/supporting h2 ...

**Comment by swankjesse** [comment]
Could you share the socket closed errors? Typically a socket close should be enough to trigger OkHttp to reconnect on a fresh socket.

Also: could you use an `EventListener` to print the routes selected? Maybe override `connectionAcquired()` and `connectFailed()` and print the parameters? I’m curious if we’re getting stale DNS results or something else.

**Comment by steelbytes** [comment]
EventListener added - will monitor (might take a day or two to catch it)

**Comment by steelbytes** [comment]
some logs
`
//////////
// before failing - had been on mobile data with hotspot enabled

03-15 12:09:36.718 D/MyApp    (17305): 03/15 12:09:36 okHttp.connectionAcquired  route=Route{myapp.com/valid.public.ip:443}  protocol=h2

//////////
// when failing - had just returned to home wifi

03-15 12:10:18.211 W/System.err(17305): 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
03-15 12:10:18.211 W/System.err(17305): 	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
03-15 12:10:18.211 W/System.err(17305): 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
03-15 12:10:18.211 W/System.err(17305): 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
03-15 12:10:18.211 W/System.err(17305): 	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
03-15 12:10:18.212 W/System.err(17305): 	at okhttp3.RealCall.execute(RealCall.java:77)
03-15 12:10:18.212 W/System.err(17305): 	at com.myapp
03-15 12:10:18.214 W/System.err(17305): Caused by: java.net.SocketException: Socket closed
03-15 12:10:18.214 W/System.err(17305): 	at java.net.SocketInputStream.read(SocketInputStream.java:203)
03-15 12:10:18.214 W/System.err(17305): 	at java.net.SocketInputStream.read(SocketInputStream.java:139)
03-15 12:10:18.214 W/System.err(17305): 	at okio.Okio$2.read(Okio.java:140)
03-15 12:10:18.214 W/System.err(17305): 	at okio.AsyncTimeout$2.read(AsyncTimeout.java:237)
03-15 12:10:18.214 W/System.err(17305): 	... 32 more

03-15 12:10:28.558 D/MyApp    (17305): 03/15 12:10:28 okHttp.connectFailed  inetSocketAddress=localhost/127.0.0.1:44590  proxy=HTTP @ localhost:44590  protocol=<null>  ioe=timeout

03-15 12:10:28.559 W/System.err(17305): java.net.SocketTimeoutException: timeout
03-15 12:10:28.560 W/System.err(17305): 	at okio.Okio$4.newTimeoutException(Okio.java:232)
03-15 12:10:28.560 W/System.err(17305): 	at okio.AsyncTimeout.exit(AsyncTimeout.java:285)
03-15 12:10:28.560 W/System.err(17305): 	at okio.AsyncTimeout$2.read(AsyncTimeout.java:241)
03-15 12:10:28.560 W/System.err(17305): 	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:355)
03-15 12:10:28.560 W/System.err(17305): 	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:227)
03-15 12:10:28.561 W/System.err(17305): 	at okhttp3.internal.http1.Http1Codec.readHeaderLine(Http1Codec.java:215)
03-15 12:10:28.561 W/System.err(17305): 	at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:189)
03-15 12:10:28.561 W/System.err(17305): 	at okhttp3.internal.connection.RealConnection.createTunnel(RealConnection.java:368)
03-15 12:10:28.561 W/System.err(17305): 	at okhttp3.internal.connection.RealConnection.connectTunnel(RealConnection.java:213)
03-15 12:10:28.561 W/System.err(17305): 	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:154)
03-15 12:10:28.562 W/System.err(17305): 	at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:257)
03-15 12:10:28.563 W/System.err(17305): 	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
03-15 12:10:28.563 W/System.err(17305): 	at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
03-15 12:10:28.563 W/System.err(17305): 	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
03-15 12:10:28.563 W/System.err(17305): 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
03-15 12:10:28.563 W/System.err(17305): 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
03-15 12:10:28.564 W/System.err(17305): 	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
03-15 12:10:28.564 W/System.err(17305): 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
03-15 12:10:28.565 W/System.err(17305): 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
03-15 12:10:28.566 W/System.err(17305): 	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
03-15 12:10:28.566 W/System.err(17305): 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
03-15 12:10:28.566 W/System.err(17305): 	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
03-15 12:10:28.566 W/System.err(17305): 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
03-15 12:10:28.567 W/System.err(17305): 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
03-15 12:10:28.567 W/System.err(17305): 	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
03-15 12:10:28.567 W/System.err(17305): 	at okhttp3.RealCall.execute(RealCall.java:77)
03-15 12:10:18.212 W/System.err(17305): 	at com.myapp
03-15 12:10:28.571 W/System.err(17305): Caused by: java.net.SocketException: Socket closed
03-15 12:10:28.571 W/System.err(17305): 	at java.net.SocketInputStream.read(SocketInputStream.java:203)
03-15 12:10:28.571 W/System.err(17305): 	at java.net.SocketInputStream.read(SocketInputStream.java:139)
03-15 12:10:28.572 W/System.err(17305): 	at okio.Okio$2.read(Okio.java:140)
03-15 12:10:28.572 W/System.err(17305): 	at okio.AsyncTimeout$2.read(AsyncTimeout.java:237)
03-15 12:10:28.572 W/System.err(17305): 	... 32 more

//////////
// after restart app - still on same wifi

03-15 12:12:40.778 D/MyApp    (6395): 03/15 12:12:40 okHttp.connectionAcquired  route=Route{/192.168.wifi.proxy:8080}  protocol=h2
`

**Comment by swankjesse** [comment]
@steelbytes this is the line that looks off to me:
```
03-15 12:10:28.558 D/MyApp    (17305): 03/15 12:10:28 okHttp.connectFailed  inetSocketAddress=localhost/127.0.0.1:44590  proxy=HTTP @ localhost:44590  protocol=<null>  ioe=timeout
```

When you join your home wifi it’s attempting to connect via a proxy running on localhost. That’s super weird; you shouldn’t usually be running a proxy on your device.

**Comment by steelbytes** [comment]
yeah, I saw that localhost - weird.  I don't have anything like that installed on my phone (Nexus 6P with 8.1.0)

I have a hunch (not yet explored) that the localhost shown may be android os doing processing of the proxy.pac file - sort of a proxy for the proxy (so the app doesn't have to understand the proxy.pac file)

**Comment by swankjesse** [comment]
Gotcha. OkHttp uses its RouteSelector to keep track of which proxies & IP addresses to attempt to connect to. The RouteSelector “remembers” the proxy settings as long as it’s used.

But it isn’t used across multiple calls. If you make a new call, we do another round of selecting a route which should mean fresh proxy information.

**Comment by steelbytes** [comment]
weird stuff ... I can't make it happen by just sitting here and twiddling the wifi and hotspot on my phone, but it seems consistent if I leave the home office for a couple of hours and then return home.  Maybe it's todo with stale connections and timeouts or something (note the actual exception is a timeout)

**Comment by yschimke** [comment]
At the lowest level, the Android APIs are pretty explicit about which proxy to use for which network. But proxy selection and network interface are both done independently but treated as if there is a single network for your phone.

Separately from this specific issue - I'm going to try to reproduce this in a personal test app and see if I can solve this in that scope first, I think aircraft mode and/or moving between corporate networks and public cell networks is a big unsolved problem at the moment.  Curious if we can do a much better job.

**Comment by steelbytes** [comment]
further investigation suggests this only happens when using a proxy.pac.  if using 'manual' mode (just entering the actual proxy ip:port into wifi settings) then doesn't seem to happeb

**Comment by swankjesse** [comment]
No action to take on this.
