### ISSUE TITLE
Chain interface missing fields?

### ISSUE THREAD

**Issue by ravuthlong** [square/okhttp#3926]
I am trying to access connectTimeoutMillis(), readTimeoutMillis() and writeTimeoutMillis() in my okHttp interceptor, but i am unable to do so because they are somehow missing from the interface. What is the problem?

Attached in image of Chain interface
[https://i.imgur.com/H2jN5J1.png](url)

Thank you!

**Comment by JakeWharton** [comment]
Your version of OkHttp is too old. Upgrade to 3.10.0.
