### ISSUE TITLE
Okhttp makes network request even with Cache-Control max-age directive

### ISSUE THREAD

**Issue by tiago7s** [square/okhttp#3927]
The request:

`Connection: Keep-Alive
Accept-Encoding: gzip
User-Agent: okhttp/3.9.0
If-None-Match: "7936b8fb7585d9491f62ac9ed08a5b51"`

And response:

`Content-Type: application/json; charset=utf-8
Vary: Accept-Encoding
Cache-Control: private, max-age=60
ETag: "7936b8fb7585d9491f62ac9ed08a5b51"`

Using the ETag works fine, it returns 304 not modified when the data is still valid. But okhttp always forces network even though there is the directive max-age. Why is this? I have tested with forcing the cache using network interceptor and the cache is hit, so the cache is stored correctly. But how can I make okhttp not make the request when the cache is still valid per the Cache-Control directives?

I have posted a question in stackoverflow, but no one answered: https://stackoverflow.com/questions/49224207/okhttp-and-retrofit-not-using-cached-data-even-with-cache-control-directive-max

**Comment by powysm** [comment]
I am having the same issue, basically max-age is ignored when etags are in use, and okhttp always goes to the network. Can you post as to what the resolution or outcome was for this issue to have been closed, please? The SO link is not found. thanks

**Comment by yschimke** [comment]
Can you post this question on stackoverflow, it is a better way to get user support like this.  I'll answer there.  The most likely reason the question doesn't exist is that it was deemed to be a duplicate.

FWIW there is some code in okhttp-dnsoverhttp that does similar with two passes

https://github.com/square/okhttp/blob/master/okhttp-dnsoverhttps/src/main/kotlin/okhttp3/dnsoverhttps/DnsOverHttps.kt#L186-L208

But continue discussion on stackoverflow, please.
