### ISSUE TITLE
why Okhttp3 custom Interceptor just be called one time?

### ISSUE THREAD

**Issue by ha1265387134** [square/okhttp#3930]
I intercept image when without wifi , the custom interceptor will be called, but when network state changed,  I pull RecyclerView back, the interceptor won't be called, so the image that’s haven't be loaded can't be loaded, just show placeholder

**Comment by yschimke** [comment]
Please ask these sorts of usage questions on stackoverflow with example code.

Alternatively, please write a test case reproducing the bug you are reporting and link to it here
