### ISSUE TITLE
ResponseBody.string() return a strange string

### ISSUE THREAD

**Issue by Unoken** [square/okhttp#3935]
When i use mobile internet (4G), it's ok. But sometimes with my wifi ResponseBody.string() give me a string like that "��������������{ɲ�H��_�V���MI�I�J�3��$A���1��(@��<��^y�pxa��.........."
Run app with Redmi note 4, galaxy core,... same isssue.
I use: OkHttp 3.6.0

**Comment by yschimke** [comment]
If you can't provide a reproduction or more headers then there is not much we can help with.  This isn't an actionable bug report e.g. its possible this is the server response. Or a proxy in the middle compressing content etc.

I suggest asking in stackoverflow, possibly someone has seen similar.
