### ISSUE TITLE
IPv6 Hostname Verification

### ISSUE THREAD

**Issue by OnlyInAmerica** [square/okhttp#3937]
`OkHostnameVerifier` does not verify IPv6 hostnames in `[square brackets]` as IP addresses. Hostnames derived from URLs per [RFC 2732](https://www.ietf.org/rfc/rfc2732.txt) are in this form. e.g: `Uri#getHost()` will return a `[square bracket]` address.

If this is something you'd like to change let me know and I'll happily submit a PR.

### Example Failing Test
```
import android.support.test.runner.AndroidJUnit4;

import org.junit.Test;
import org.junit.runner.RunWith;

import static com.squareup.okhttp.internal.tls.OkHostnameVerifier.verifyAsIpAddress;
import static junit.framework.Assert.assertTrue;

@RunWith(AndroidJUnit4.class)
public class OkHttpTest {

    @Test
    public void testIpv6Verify() {
        assertTrue(verifyAsIpAddress("[FE80::FABB:BFFF:FE01:3A52]"));
    }
}
```

**Comment by swankjesse** [comment]
The square braces are not part of the hostname. They're only used to disambiguate IPv6 addresses in URLs. This is similar to how the `?` character in a URL delimits the query but isn't part of it.

**Comment by swankjesse** [comment]
And if ya don't want to scrub the `[` and `]` characters from an IPv6 name, just use HttpUrl which gets this right.
https://square.github.io/okhttp/3.x/okhttp/okhttp3/HttpUrl.html#host--

**Comment by OnlyInAmerica** [comment]
👍 Thanks for the quick reply.
For future readers of this thread: One gotcha (and how I got here) is that `URI#getHost()` returns IPv6 hostnames within `[square brackets]`. Libraries that rely on this behavior when setting a hostname for validation (e.g: possibly [grpc-java](https://github.com/grpc/grpc-java/issues/4278)) might cause issue.
