### ISSUE TITLE
Why are cancel events in HTTP2 causing the connection to be closed?

### ISSUE THREAD

**Issue by oliveroneill** [square/okhttp#3940]
https://github.com/square/okhttp/blob/878bde8fd6939b508adeb21e2911e390cfe27326/okhttp/src/main/java/okhttp3/internal/connection/StreamAllocation.java#L436

Only `REFUSED_STREAM` errors allow the reuse of a connection. I believe it should be acceptable for a cancelled stream to be able to reuse the connection. Am I misunderstanding what `ErrorCode.CANCEL` means?

**Comment by swankjesse** [comment]
Looks like a bug!

**Comment by yschimke** [comment]
Pull Requests are always welcome, we are happy to review as long as you sign the Contributor Agreement when you submit it.  n.b. If it's high enough priority and the PR doesn't look like it's coming, then someone else may fix instead.  These issues are not actively assigned to anyone.

And Thanks!

**Comment by oliveroneill** [comment]
There is a test that uses `ErrorCode.CANCEL` to kill the connection. The test is `recoverFromConnectionNoNewStreamsOnFollowUp` in `HttpOverHttp2Test`. This makes me wonder if it's intended behaviour?

**Comment by yschimke** [comment]
Completed PR - this appears closed already
