### ISSUE TITLE
Feature Request: Response header bytes?

### ISSUE THREAD

**Issue by giantsol** [square/okhttp#3943]
Hi.
I have a case where I want to get raw byte stream of response header, to correctly decode the filename parameter in "Content-Disposition" header, but I guess okhttp doesn't support this feature..
Since you support response body streaming, could you also support header streaming? Or something like a way to peek into resp header bytes?
Thanks in advance.

**Comment by swankjesse** [comment]
We're not going to support this. Please don't use anything but ASCII for headers.

**Comment by swankjesse** [comment]
Hang on, you might be talking about a multipart part’s headers, which _is_ allowed to have UTF-8 characters in it.

https://github.com/square/okhttp/issues/3876

We’re gonna fix that.

**Comment by giantsol** [comment]
Hooray~~ thanks!!

**Comment by yschimke** [comment]
is this a dupe or subtlety different?

**Comment by giantsol** [comment]
Oh, hold on.. I think I misunderstood your "We're gonna fix that."
You mean you're just gonna support UTF-8 characters in headers, and not that you're gonna support response header bytes streaming?
Cause some websites do encode resp headers with something like euc-kr.. and if you decode that with utf-8 it's still gonna break :(

**Comment by swankjesse** [comment]
I’d like to support non-ASCII characters in headers for MultipartBody requests. But I think you’re looking at filenames in _response_ headers, which are different.

No plans to support non-ASCII characters in regular HTTP headers. If you need that, we aren’t gonna be able to help.

**Comment by giantsol** [comment]
Ok.
Thanks for response!
