### ISSUE TITLE
Reverse HTTP

### ISSUE THREAD

**Issue by ingsaurabh** [square/okhttp#3944]
- [ ] Feature Request. I am not sure if it has been asked earlier. Does Okhttp supports Reverse HTTP as stated in following [link](https://tools.ietf.org/id/draft-lentczner-rhttp-00.txt)

**Comment by swankjesse** [comment]
Not supported. If you need this, you might be able to build something using a custom SocketFactory.

**Comment by ingsaurabh** [comment]
Ok I thought since Okhttp is strictly following HTTP protocol, so any future plans, 
I am currently using custom SocketFactory but not happy with performance as my implementation is simply hacks.

**Comment by swankjesse** [comment]
Yeah, I don’t think you’re going to find anything that’s particularly satisfying. You might want to do something in a different layer. Perhaps using SSH port forwarding or something.

No action for us to take on this.
