### ISSUE TITLE
Okhttp clears the Thread interrupt status

### ISSUE THREAD

**Issue by DrMetallius** [square/okhttp#3945]
We have a problem in our project due to Okhttp consuming the interrupted flag of the thread. #3107 describes the problem perfectly. The reply suggests that the thrown `InterruptedIOException` should be enough handle the case. It isn't because it is rethrown in two cases: when a timeout is reached and when the thread was actually interrupted. We have no way to actually find out whether my thread got interrupted while it was doing work in Okhttp or it is just a network problem. The only solution is to parse the error message, which is obviously very wonky. This applies to both `waitUntilNotified` and `throwIfReached` in `Timeout`.

**There should be a way to tell thread interruption apart from network problems**. I suggest changing `InterruptedIOException` to `InterruptedException` when the thread is interrupted, as this will actually make the code conform to the **interruption handling conventions which are currently violated as `InterruptedIOException` is not an `InterruptedException`**, it is an `IOException`. In the case if this is considered a breaking change, I suggest creating a subclass of the `InterruptedIOException` and throwing that instead on thread interruption.

**Comment by swankjesse** [comment]
We should probably just mark the thread as interrupted before throwing the `InterruptedIOException`.
