### ISSUE TITLE
how can i overwrite host by code

### ISSUE THREAD

**Issue by fantasysea** [square/okhttp#3946]
What kind of issue is this?

 - [ ] Question. how can i overwrite host by code,because sometime chinese's dns service have some problem,can connect to my  server,when i find i can server by domain,i need to change headers host to my domain,but i will request a new url by ip address like : http://192.168.0.1:88/getsomething. my question is how can i do it?

**Comment by yschimke** [comment]
If you set a specific Host header on the request it will use it instead of the host from the URL

e.g. https://github.com/square/okhttp/pull/3108/files

**Comment by fantasysea** [comment]
thank you, i get it

**Comment by yschimke** [comment]
n.b. If you care to submit this on Stackoverflow and self answer, post the link here and I'll up vote.
