### ISSUE TITLE
SSLHandshakeException

### ISSUE THREAD

**Issue by Caij** [square/okhttp#3950]
version:3.9.0 (3.10.0)
device: Android 5.0 low(Android 4.4)

javax.net.ssl.SSLHandshakeException: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0x79cd4088: Failure in SSL library, usually a protocol error
    error:1407743E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert inappropriate fallback (external/openssl/ssl/s23_clnt.c:744 0x719f5cf8:0x00000000)

url:https://pic-cdn.vert.tv/verttv/uploads/file/180319/192300371838.jpg

**Comment by dentex** [comment]
Same error, since I updated the lib to v3.10.0

**Comment by swankjesse** [comment]
@dentex it’s possible that you’re facing this issue: https://github.com/square/okhttp/issues/4053

**Comment by swankjesse** [comment]
@Caij There isn’t enough information here for us to take action on. When I executed a request for the sample URL it returned a 504 gateway timeout once I configured a  90 second timeout. I didn’t have handshake problems.
