### ISSUE TITLE
Does okhttp 2.4.0 support HTTP/2.0 protocol?

### ISSUE THREAD

**Issue by Bajranghudda** [square/okhttp#3954]
I am using Retrofit 1.9 with okhttp 2.4.0. So far we have SPDY protocol disabled on server side (I checked it by this ). And enabled protocol on server side is HTTP/2 (I checked it by this).

So I was thinking that okhttp will try to make an api call using HTTP/2 (latest one protocol) but it's using HTTP/1.1 on android device 4.2.2 samsung S4 - 

  D/Retrofit : OkHttp-Selected-Protocol: http/1.1

And when i am trying to make an api call with 5.0 > above device I am getting exception - 
java.net.ProtocolException: Expected ':status' header not present https://stackoverflow.com/q/49643383/3448003 

Is Okhttp 2.4.0 doesn't support http/2.0 well or what's the real problem ?

**Comment by swankjesse** [comment]
OkHttp 2.x is obsolete. Please upgrade to 3.10.

**Comment by Bajranghudda** [comment]
Upgrading to okhttp to latest 3.10 is okay and I will, but why a live app stop working suddenly IS A MYSTERIOUS for our both team (mobile & back end). 

If you can provide any clue, will be much more helpful to explain to our client.
Thanks.

**Comment by swankjesse** [comment]
There was a bug in HTTP/2 support in 2.4.0 that caused this exception. Nobody noticed at the time because there weren't many HTTP/2 servers and those that existed didn't trigger this bug.

But today there's more HTTP/2 servers and some trigger this bug. I'm guessing one of your webervers was upgraded.

**Comment by Bajranghudda** [comment]
But webserver's people saying they didn't make any changes/ upgradation happend from their side.

**Comment by Bajranghudda** [comment]
What can be the possible upgradation on server side, because server side people saying we didn't make any changes or is it a kind of automatic upgradation?
