### ISSUE TITLE
OkHttp causes connection leaks when deduplicating

### ISSUE THREAD

**Issue by oliveroneill** [square/okhttp#3962]
https://github.com/square/okhttp/blob/878bde8fd6939b508adeb21e2911e390cfe27326/okhttp/src/main/java/okhttp3/internal/connection/StreamAllocation.java#L501

I believe the line above should be replaced with:
` Reference<StreamAllocation> onlyAllocation = connection.allocations.remove(0); `
If I understand correctly, deduplication will leave allocation references on the old connection that will cause the prune step in ConnectionPool to trigger a connection leak. I believe the allocations are meant to be moved across instead of copied when doing `releaseAndAcquire`. Is this a bug?

**Comment by dave-r12** [comment]
Can you create an executable test case? The allocation will be removed on the call to `deallocate` which happens on the next line.

**Comment by oliveroneill** [comment]
I'll see if I can create a simple test case. The allocations don't get removed unless `release` is called in `deallocate`, which depends on this condition:
https://github.com/square/okhttp/blob/878bde8fd6939b508adeb21e2911e390cfe27326/okhttp/src/main/java/okhttp3/internal/connection/StreamAllocation.java#L394
Doesn't that mean there is a case where they aren't removed?

**Comment by oliveroneill** [comment]
Sorry, this is my mistake, I must have misread the call. The allocation will be removed in the `deallocate` call, there's no bug here
