### ISSUE TITLE
A small suggest.

### ISSUE THREAD

**Issue by SuperBeagleDog** [square/okhttp#3963]
I saw that There are two same code in enqueue and execute method of RealCall class.
These two code snips may should be merged as one.
Thank you.

Here is the code:
synchronized (this) {
      if (executed) throw new IllegalStateException("Already Executed");
      executed = true;
    }
    captureCallStackTrace();
    eventListener.callStart(this);

**Comment by yschimke** [comment]
I'm not convinced this would make things more readable, it doesn't seem like an issue that needs addressing.

**Comment by swankjesse** [comment]
No action to take here.
