### ISSUE TITLE
Publish a list of expected Lint suppressions

### ISSUE THREAD

**Issue by gsboylan** [square/okhttp#3966]
Lint fails on our project after upleveling from OkHttp 3.5.0 to 3.10.0 due to an InvalidPackage error on an OkHttp3 dependency:
```
GoogleConscrypt/1.0.1/conscrypt-openjdk-uber-1.0.1.jar: Invalid package reference in library; not included in Android: java.nio.file.attribute. Referenced from org.conscrypt.Java7PlatformUtil.
This check scans through libraries looking for calls to APIs that are not included in Android.
```

I was able to resolve this by adding this to our gradle lint.xml file: 
```
  <issue id="InvalidPackage">
    <ignore path="**/conscrypt-openjdk-uber-1.*.jar"/>
  </issue>
```

A published list of lint suppressions for verification would be helpful.

**Comment by JakeWharton** [comment]
That is an optional dependency which isn't included in Android APKs. You should report a bug to the scanner.

**Comment by gsboylan** [comment]
Okay, I'll look into this more on our end and check that out. Thanks

**Comment by JakeWharton** [comment]
If you are just including the library with a dependency manager like Gradle
this should not be on the classpath that lint looks at.
