### ISSUE TITLE
Call.cancel fails to close socket

### ISSUE THREAD

**Issue by RaisedByTheInternet** [square/okhttp#3968]
**OkHttp version: 3.10.0**
**OS: Android 7.0**

The following code should produce a "Socket is closed" exception, since it cancels a Call and then tries to read from the underlying socket.  However, no exception is thrown.

```java
    OkHttpClient client = new OkHttpClient();
    Request request = new Request.Builder().url("https://i.imgur.com/FQpOdrE.jpg").build();
    final Call call = client.newCall(request);

    new Thread(new Runnable() {
        @Override
        public void run() {
            try {
                Response response = call.execute();
                try (ResponseBody body = response.body()) {
                    Thread.sleep(5000);
                    call.cancel(); // CANCEL!
                    InputStream stream = body.byteStream();
                    byte[] buffer = new byte[4 * 1024];
                    for (int n = stream.read(buffer); n != -1; n = stream.read(buffer)) {
                        // do nothing -- we're just reading from the stream
                    }
                }
            } catch (Throwable t) {
                Log.e("Test", Log.getStackTraceString(e));
            }
        }
    }).start();
```

The image is read fully, even though we said `call.cancel();` before trying to read from the InputStream.

In **OkHttp 2.2.0** (the version I just upgraded from), however, the same code *does* produce an exception:

> java.net.SocketException: Socket is closed
        at com.android.org.conscrypt.OpenSSLSocketImpl.checkOpen(OpenSSLSocketImpl.java:270)
        at com.android.org.conscrypt.OpenSSLSocketImpl.-wrap0(OpenSSLSocketImpl.java)
        at com.android.org.conscrypt.OpenSSLSocketImpl$SSLInputStream.read(OpenSSLSocketImpl.java:743)
        at okio.Okio$2.read(Okio.java:136)
        at okio.AsyncTimeout$2.read(AsyncTimeout.java:211)
        at okio.RealBufferedSource.read(RealBufferedSource.java:50)
        at com.squareup.okhttp.internal.http.HttpConnection$FixedLengthSource.read(HttpConnection.java:408)
        at okio.RealBufferedSource$1.read(RealBufferedSource.java:298)
        at java.io.InputStream.read(InputStream.java:101)
        at com.example.MainActivity$1.run(MainActivity.java:96)
        at java.lang.Thread.run(Thread.java:761)

**Comment by yschimke** [comment]
I haven't debugged, I suggest putting an EventListener in place and seeing when reads are happening.

https://github.com/square/okhttp/wiki/Events

But I don't think it's part of the contract of call.cancel, that an existing ResponseBody should fail to read from the socket.  e.g. if the connection is http/2 then you can expect that the input must be consumed during the 5 second window to avoid head of line blocking other potential requests.

**Comment by swankjesse** [comment]
My guess is the difference is go HTTP/2.

**Comment by RaisedByTheInternet** [comment]
I did some testing, and I can confirm that the entire image is downloaded as soon as Call.execute has completed.  I triple-checked this by disconnecting from the Internet immediately after running Call.execute, and I was still able to read the response body using an InputStream.

Although this behaviour is different from that of OkHttp 2.2.0, your responses suggest that this is intended behaviour because of HTTP/2, so I will close this issue.

Sorry about the false report, and thank you for your speedy responses!
