### ISSUE TITLE
DNS over Https

### ISSUE THREAD

**Issue by yschimke** [square/okhttp#3969]
It’s a thing we could do. :)

https://tools.ietf.org/html/draft-ietf-doh-dns-over-https-07

Prototype

https://github.com/yschimke/oksocial/blob/master/src/main/kotlin/com/baulsupp/oksocial/network/doh/OkHttpDnsOverHttps.kt
https://github.com/yschimke/oksocial/blob/master/src/main/kotlin/com/baulsupp/oksocial/network/doh/DnsOverHttpsRequestBuilder.kt

This reuses Netty encoders and decoders, but could be re-implemented for just querying A (ipv4) and AAAA (ipv6) records.

**Comment by yschimke** [comment]
@swankjesse Would we ship this when the spec goes final if I get it ready?

**Comment by swankjesse** [comment]
```
OkHttpClient client = new OkHttpClient.Builder()
    .dns(new TlsDns("1.1.1.1"))
    .build();
```
?

**Comment by yschimke** [comment]
It's different from Dns over TLS.  So DnsOverHTTPS("https://dns.google.com/experimental?ct")?

**Comment by swankjesse** [comment]
👍🏻

**Comment by yschimke** [comment]
If it's an optional module, then Kotlin could be an option.  I'll start with Java for now, but worth asking the question. Could be a useful toe in the water.

**Comment by swankjesse** [comment]
Next steps?

**Comment by yschimke** [comment]
Experimental in 3.11, get API usage as an optional module in experimental state.  Iterate and see how adoption goes before we bake it solid? But it should be a working (buggy?) implementation of the spec.

**Comment by yschimke** [comment]
@swankjesse Should we make this API non experimental, or review and adjust based on new information?
