### ISSUE TITLE
Unexpected TLS version: NONE

### ISSUE THREAD

**Issue by lizhangqu** [square/okhttp#3973]
These days so many crashes happened in our app. About 200+ Android devices has happened. And it's always happend on Andorid 8.1.0. The OkHttp's version I used is 3.10.0.

This is the crash's stack information
```
0 java.lang.IllegalArgumentException: Unexpected TLS version: NONE
1 okhttp3.TlsVersion.forJavaName(TlsVersion.java:46)
2 okhttp3.Handshake.get(Handshake.java:55)
3 okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:242)
4 okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:198)
5 okhttp3.internal.connection.RealConnection.buildConnection(RealConnection.java:174)
6 okhttp3.internal.connection.RealConnection.connect(RealConnection.java:114)
7 okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:193)
8 okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:129)
9 okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:98)
10 okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
11 okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
12 okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
13 okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:109)
14 okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
15 okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
16 okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
17 okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
18 okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:124)
19 okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
20 okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
21 com.weidian.lib.imagehunter.glidehunter.okhttp3.OkHttpUrlLoader$Factory$1.intercept(OkHttpUrlLoader.java:63)
22 okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
23 okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
24 okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:170)
25 okhttp3.RealCall.access$100(RealCall.java:33)
26 okhttp3.RealCall$AsyncCall.execute(RealCall.java:120)
27 okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
28 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
29 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
30 java.lang.Thread.run(Thread.java:764)
```

I found that OkHttp will not callback when java.lang.IllegalArgumentException happend.
This exception is thrown by **TlsVersion.forJavaName** method

```
public static TlsVersion forJavaName(String javaName) {
  switch (javaName) {
    case "TLSv1.3":
      return TLS_1_3;
    case "TLSv1.2":
      return TLS_1_2;
    case "TLSv1.1":
      return TLS_1_1;
    case "TLSv1":
      return TLS_1_0;
    case "SSLv3":
      return SSL_3_0;
  }
  throw new IllegalArgumentException("Unexpected TLS version: " + javaName);
}
```

When invoke call's enqueue method to get result async, if this exception happened, it will not callback onFailure method. And also I can't catch it.

```
client.newCall(request).enqueue(new Callback() {
    @Override
    public void onFailure(Call call, IOException e) {

    }

    @Override
    public void onResponse(Call call, Response response) throws IOException {

    }
});
```

```
final class AsyncCall extends NamedRunnable {
  private final Callback responseCallback;

  @Override protected void execute() {
    boolean signalledCallback = false;
    try {
      Response response = getResponseWithInterceptorChain();
      if (retryAndFollowUpInterceptor.isCanceled()) {
        signalledCallback = true;
        responseCallback.onFailure(RealCall.this, new IOException("Canceled"));
      } else {
        signalledCallback = true;
        responseCallback.onResponse(RealCall.this, response);
      }
    } catch (IOException e) {
      //only IOException will catch and callback onFailure method
      if (signalledCallback) {
        // Do not signal the callback twice!
        Platform.get().log(INFO, "Callback failure for " + toLoggableString(), e);
      } else {
        responseCallback.onFailure(RealCall.this, e);
      }
    } finally {
      client.dispatcher().finished(this);
    }
  }
}
```

Is there any solution? Thank you.

**Comment by Belka1000867** [comment]
Any update?

**Comment by yschimke** [comment]
This isn't happening with 3.10.0, this was fixed quite a while ago.

https://github.com/square/okhttp/pull/3721

**Comment by lizhangqu** [comment]
yes, it really happened in 3.10.0

**Comment by yschimke** [comment]
Can you provide a new stacktrace then, I think the current one you provided is from before 3.10.0, based on line numbers

**Comment by lizhangqu** [comment]
@yschimke 

java.lang.IllegalArgumentException: Unexpected TLS version: NONE
	at okhttp3.TlsVersion.forJavaName(TlsVersion.java:53)
	at okhttp3.Handshake.get(Handshake.java:56)
	at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:319)
	at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:277)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:162)
	at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:257)
	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
	at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:147)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by yschimke** [comment]
Your original stack trace looks like it is from 3.4.0 

3.4.0
https://github.com/square/okhttp/blob/parent-3.4.0/okhttp/src/main/java/okhttp3/internal/connection/RealConnection.java#L242

This new stacktrace is happening after the fix (https://github.com/square/okhttp/pull/3721/files), but also seems to be a build from okhttp master slightly after 3.10.0.

3.10.0:
https://github.com/square/okhttp/blob/parent-3.10.0/okhttp/src/main/java/okhttp3/internal/connection/RealConnection.java#L319

9a6f88dc34cb68d341ec1a7e4c79546fa1c18c96:
https://github.com/square/okhttp/blob/9a6f88dc34cb68d341ec1a7e4c79546fa1c18c96/okhttp/src/main/java/okhttp3/internal/connection/RealConnection.java#L319  

So it looks like two subsequent calls to sslSocketSession.getProtocol() are returning something normal, and then "NONE" for the second call.

**Comment by lizhangqu** [comment]
@yschimke yes , it's built after 3.10.0 on master branch

**Comment by yschimke** [comment]
@lizhangqu can you build against the PR branch from yesterday, see if it fixes things?

**Comment by gdky005** [comment]
I had the same problem. The probability of this problem crashing is not very high, but it does exist in some devices.

> String tlsVersionString = session.getProtocol();
> if (tlsVersionString == null) throw new IllegalStateException("tlsVersion == null");
> TlsVersion tlsVersion = TlsVersion.forJavaName(tlsVersionString);

tlsVersionString in other devices get "NONE".

**Comment by lizhangqu** [comment]
@yschimke maybe it will fix one scene which call trigger the crash, if the stack not call **public static Handshake get(SSLSession session)**, it will crash too. Maybe this will work fine.

```
  public static TlsVersion forJavaName(String javaName) {
    switch (javaName) {
      case "TLSv1.3":
        return TLS_1_3;
      case "TLSv1.2":
        return TLS_1_2;
      case "TLSv1.1":
        return TLS_1_1;
      case "TLSv1":
        return TLS_1_0;
      case "SSLv3":
        return SSL_3_0;
    }
    throw new IOException("Unexpected TLS version: " + javaName);
  }

```

All tlsVersion will call TlsVersion.forJavaName and we can check it in this method. Throwing IOException instead of IllegalArgumentException

**Comment by gdky005** [comment]
@yschimke 

The source code:
>    public static TlsVersion forJavaName(String javaName) {
    switch (javaName) {
      case "TLSv1.3":
        return TLS_1_3;
      case "TLSv1.2":
        return TLS_1_2;
      case "TLSv1.1":
        return TLS_1_1;
      case "TLSv1":
        return TLS_1_0;
      case "SSLv3":
        return SSL_3_0;
    }
    throw new IllegalArgumentException("Unexpected TLS version: " + javaName);
  }

The modified：

>   public static TlsVersion forJavaName(String javaName) {
    switch (javaName) {
      case "TLSv1.3":
        return TLS_1_3;
      case "TLSv1.2":
        return TLS_1_2;
      case "TLSv1.1":
        return TLS_1_1;
      case "TLSv1":
        return TLS_1_0;
      case "SSLv3":
      default:
        return SSL_3_0;
    }
  }




If the system access to the TLS version is NONE, I can assume that the user must use the Android system, but because of the system for less than the corresponding TLS version, can try to return to the oldest SSL_3_0, so mobile phone can compatible with the model, some security handshake rules can not only use, but can ensure the request is successful, and does not collapse.

**Comment by yschimke** [comment]
NONE isn't unknown or old.  It's that there is no SSL session anymore, or it failed initially.  So changing TlsVersion lookup doesn't seem right to me.

**Comment by gdky005** [comment]
3Q

**Comment by lizhangqu** [comment]
@yschimke also with 3.4.1 and 3.9.1, but I now the stacktrace is missing so I can't provid it.

**Comment by yschimke** [comment]
@lizhangqu is the frequency that you see this per device (Android 8.1.0) the same with 3.10 and also with all earlier OkHttp versions?  I didn't follow you previous answer.

**Comment by a1018875550** [comment]
@yschimke it's also happened in v3.9.1

**Comment by yschimke** [comment]
@a1018875550 understood, but 3.10.0 includes a fix that should substantially reduce the frequency of this error.  But likely not eliminate it completely as its still a timing issue with an async cause (sslsocket closing).

**Comment by a1018875550** [comment]
yeah, but he said it's also happened in v3.10.0 for this issues first commit. And I'm not update this for my users. 
so I'm not sure v3.10.0 it's ok.

**Comment by yschimke** [comment]
@a1018875550 the original stack trace wasn't from 3.10.0, but a later one was. I suspect the main change here is Android 8.1.0, rather than OkHttp 3.4.0 vs 3.9.1.  As I said, I believe it should happen *less* frequently with 3.10.0.

**Comment by lizhangqu** [comment]
I fix this problem by modifing async call to sync call and try catch it. The versions I used are 3.4.1, 3.9.1 and 3.10.0. All these versions have happened this problem. But it seems that 3.2.1 is ok. I am sorry that I have not focus on the crash number with different okhttp version.

**Comment by lizhangqu** [comment]
@yschimke  We have two android apps, the first one uses 3.4.2, there are about 400+ crashes. And the other one uses 3.10.0, there are about 250+ crashes. I'm not sure whether 3.10.0 reduce crashes or not

**Comment by lizhangqu** [comment]
@yschimke but all happened on Android 8.1.0

**Comment by lizhangqu** [comment]
@a1018875550 

before fix

```
OkHttpClient client = new OkHttpClient();
RequestBody body = RequestBody.create(MediaType.parse("application/json; charset=utf-8"), json);
Request request = new Request.Builder()
    .url(url)
    .post(body)
    .build();
client.newCall(request).enqueue(new Callback() {
  @Override
  public void onFailure(Call call, IOException e) {
    //java.lang.IllegalArgumentException: Unexpected TLS version: NONE 
    //will not callback on this function and then crash
  }

  @Override
  public void onResponse(Call call, Response response) throws IOException {

  }
});
```

after fix
```
final OkHttpClient client = new OkHttpClient();
final RequestBody body = RequestBody.create(MediaType.parse("application/json; charset=utf-8"), json);
final Request request = new Request.Builder()
        .url(url)
        .post(body)
        .build();
client.dispatcher().executorService().execute(new Runnable() {
    @Override
    public void run() {
        try {
            client.newCall(request).execute();
        } catch (IllegalArgumentException e) {
            //Unexpected TLS version: NONE will be catch
            //and will not crash
            //but in essence, I have not solved this problem. Just only ignore it
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
}); 
```

**Comment by a1018875550** [comment]
@lizhangqu I think it not a good way to slove this. you should try/catch every request. And I'm using rxjava for request.

**Comment by yschimke** [comment]
This should be fixed in 3.11 https://github.com/square/okhttp/pull/4055

**Comment by a1018875550** [comment]
@yschimke nice, when is update 3.11?

**Comment by yschimke** [comment]
Not sure, but I suspect soon, it's overdue, and there are enough meaningful bug fixes and some experimental features already in master.

**Comment by swankjesse** [comment]
I’m getting ready to cut 3.11.
