### ISSUE TITLE
Please link mockwebserver docs in Wiki sidebar

### ISSUE THREAD

**Issue by fastily** [square/okhttp#3975]
What kind of issue is this?

 - [ ] Question. This issue tracker is not the place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use Stack
       Overflow. https://stackoverflow.com/questions/tagged/okhttp

 - [ ] Bug report. If you’ve found a bug, spend the time to write a failing test. Bugs with tests
       get fixed. Here’s an example: https://gist.github.com/swankjesse/981fcae102f513eb13ed

 - [x] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
       already exists! Don’t send pull requests to implement new features without first getting our
       support. Sometimes we leave features out on purpose to keep the project small.

----
Could the [mockwebserver docs](http://square.github.io/okhttp/3.x/mockwebserver/) be linked under the Javadoc section in the the sidebar of the [Wiki](https://github.com/square/okhttp/wiki)?

I didn't even realize these docs existed (until I looked through the gh-pages branch) and I'm sure others may have been similarly befuddled.

Thanks!

**Comment by yschimke** [comment]
Good suggestion - https://github.com/square/okhttp/wiki

cc @swankjesse revert if by design
