### ISSUE TITLE
err

### ISSUE THREAD

**Issue by ruanbaojun1105** [square/okhttp#3979]
What kind of issue is this?

 - [ ] Question. This issue tracker is not the place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use Stack
       Overflow. https://stackoverflow.com/questions/tagged/okhttp

 - [x] Bug report. If you’ve found a bug, spend the time to write a failing test. Bugs with tests
       get fixed. Here’s an example: https://gist.github.com/swankjesse/981fcae102f513eb13ed

 - [ ] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
       already exists! Don’t send pull requests to implement new features without first getting our
       support. Sometimes we leave features out on purpose to keep the project small.
![image](https://user-images.githubusercontent.com/7459297/39281038-31c99386-4935-11e8-9a3c-7b3a6cc29780.png)

**Comment by swankjesse** [comment]
Not actionable. Please submit nice bug reports with unobfuscated stack traces impacted versions, etc.
