### ISSUE TITLE
Request/Response details are not showing in logcat in Nokia 1 device (Oreao 8.1)

### ISSUE THREAD

**Issue by msayanece** [square/okhttp#3985]
Logcat is not showing the request and response details in Nokia 1 with OS Oreao 8.1.

**Comment by yschimke** [comment]
What is normally logging your requests to logcat?  Are you using HttpLoggingInterceptor?

There isn't much to go on with this report, short of us building an app and buying the phone and testing ourselves.  If you have a test app and we can reproduce in a simulator it may help.  I have an android app in github you could test with (https://github.com/yschimke/okhttp-testapp).

**Comment by msayanece** [comment]
@yschimke Thanks for a reply mate.


> Are you using HttpLoggingInterceptor?

Yes.


> What is normally logging your requests to logcat?


 In Nokia 1 with OS Oreao 8.1, the logcat is showing only this...

`I/System.out: [OkHttp] sendRequest>>`

 `I/System.out: [OkHttp] sendRequest<<`


Whereas in other devices...

`D/OkHttp: --> GET https://www.fikarrnot.com/apps_response/loginWithDeviceId.php`
`D/OpenGLRenderer: prepareDirty (0.00, 0.00, 600.00, 976.00) opaque 0 <0x607921b8>`
`D/OkHttp: deviceId: fikarrnotbf1d2ba7-233e-4b90-a757-5b41dcd63071`
`D/OkHttp: deviceIdPhysical: c8083d4d598d7dec`
`D/OpenGLRenderer: clear (0.00, 976 - 976.00 = 0.00, 600.00 - 0.00 = 600.00, 976.00 - 0.00 = 976.00) opaque 0 <0x607921b8>`
`D/OkHttp: fcmId: d17xff1bAB8:APA91bFK663j1ButscuwIzcdOGG3Sho6D0rT6cF829HhK-YL81pU5YgBvAnzgifMXg4QDCSn58vewv_RUFwGMQvlYQWAOA6m6w8I1YlS8OFZBIM7IlQ87R8FE_YR9o9eMxfVVw4QNpxa`
`D/OpenGLRenderer: finish <0x607921b8>`
`D/OkHttp: deviceType: android`
`D/OkHttp: --> END GET`

Here is my interceptor method I am using...

`public static void createInterceptorHTTPClient(final Context context){`
            `HttpLoggingInterceptor interceptor = new HttpLoggingInterceptor();`
            `interceptor.setLevel(HttpLoggingInterceptor.Level.BODY);`
            `defaultHttpClient = new OkHttpClient.Builder()`
                   ` .addInterceptor(`
                           ` new Interceptor() {`
                              `  @Override`
                              `  public Response intercept(Chain chain) throws IOException {`
                                `    Request request = chain.request().newBuilder()`
                                       `     .addHeader("deviceId", ("fikarrnot" + getUniqueId(context)))`
                                           ` .addHeader("deviceIdPhysical", Settings.Secure.getString(context.getContentResolver(), Settings.Secure.ANDROID_ID))`
                                           ` .addHeader("fcmId", FirebaseInstanceId.getInstance().getToken())`
                                          `  .addHeader("deviceType","android")`
                                           ` .build();request.headers().toString());`
                                   ` return chain.proceed(request);`
                              `  }`
                           ` })`
                   ` .readTimeout(2, TimeUnit.MINUTES)`
                    `.addInterceptor(interceptor)`
                   ` .build();`
  `  }`

**Comment by yschimke** [comment]
There isn't enough for me to go on here, have you tested that your own interceptor can log also?

        Log.println(Log.DEBUG, "MyClient", "XXX");

**Comment by msayanece** [comment]
Actually log.println() is not working when it is set to Log.DEBUG mode, in other mode it is working fine. Kindly guide me through.

**Comment by yschimke** [comment]
You should post to stackoverflow for help

**Comment by Rolf-Smit** [comment]
I want to add some more info since I tried this on a Nokia 1 device:

By default this device (even with developer options on) does not log verbose and debug messages.

Small test I did:
```
I/Logcat Test: Log.i()
W/Logcat Test: Log.w()
E/Logcat Test: Log.e()
E/Logcat Test: Log.wtf()
A/Logcat Test: Log.println(ASSERT)
I/System.out: Logcat Test System.out.println()
```

Notice that it does not contain `Log.v()` and `Log.d()`.

Checking the build properties of the Nokia 1 gives the following result:
```
> adb shell getprop log.tag
> I
```

After changing `I` to `V` (or just `VERBOSE`) using `adb shell setprop log.tag VERBOSE`:

```
V/Logcat Test: Log.v()
D/Logcat Test: Log.d()
I/Logcat Test: Log.i()
W/Logcat Test: Log.w()
E/Logcat Test: Log.e()
E/Logcat Test: Log.wtf()
A/Logcat Test: Log.println(ASSERT)
I/System.out: Logcat Test System.out.println()
```
_Note: This setting might not persist when rebooting the phone!_


So this is not a OkHttp issue, but a system setting on the Nokia 1.

**Comment by msayanece** [comment]
> I want to add some more info since I tried this on a Nokia 1 device:
> 
> By default this device (even with developer options on) does not log verbose and debug messages.
> 
> Small test I did:
> 
> ```
> I/Logcat Test: Log.i()
> W/Logcat Test: Log.w()
> E/Logcat Test: Log.e()
> E/Logcat Test: Log.wtf()
> A/Logcat Test: Log.println(ASSERT)
> I/System.out: Logcat Test System.out.println()
> ```
> Notice that it does not contain `Log.v()` and `Log.d()`.
> 
> Checking the build properties of the Nokia 1 gives the following result:
> 
> ```
> > adb shell getprop log.tag
> > I
> ```
> After changing `I` to `V` (or just `VERBOSE`) using `adb shell setprop log.tag VERBOSE`:
> 
> ```
> V/Logcat Test: Log.v()
> D/Logcat Test: Log.d()
> I/Logcat Test: Log.i()
> W/Logcat Test: Log.w()
> E/Logcat Test: Log.e()
> E/Logcat Test: Log.wtf()
> A/Logcat Test: Log.println(ASSERT)
> I/System.out: Logcat Test System.out.println()
> ```
> _Note: This setting might not persist when rebooting the phone!_
> 
> So this is not a OkHttp issue, but a system setting on the Nokia 1.

Thanks mate, that works! Thank you so much!

**Comment by MujahidKhan07** [comment]
I have faced these problem on Nokia only , i don't know why , i think i have trigger api calling so many time  but when i use `android:usesCleartextTraffic="true"` in my manifest file then its works
