### ISSUE TITLE
SSL connection not maintained

### ISSUE THREAD

**Issue by Hemant0601** [square/okhttp#3986]
SSL connection with OKHTTP is not maintained getting following error

java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
Version used : implementation 'com.squareup.okhttp3:okhttp:3.10.0'

my code 

 Function used to create client as follows

```
public static OkHttpClient getOkHttpClient() {
        if(okHttpClient==null){

            try{
                CertificateFactory cf ;
                InputStream cert ;
                Certificate ca ;
                SSLContext sslContext ;

                cf = CertificateFactory.getInstance("X.509");

                cert = AppController.getInstance().getResources().openRawResource(R.raw.my_cert); // Place your 'my_cert.crt' file in `res/raw`

                try {
                    ca = cf.generateCertificate(cert);
                    Log.v(TAG,"ca=" + ((X509Certificate) ca).getSubjectDN());
                } finally {
                    cert.close();
                }

                String keyStoreType = KeyStore.getDefaultType();
                KeyStore keyStore = null;
                try {
                    keyStore = KeyStore.getInstance(keyStoreType);
                } catch (KeyStoreException e) {
                    e.printStackTrace();
                }
                keyStore.load(null, null);
                keyStore.setCertificateEntry("ca", ca);

                String tmfAlgorithm = TrustManagerFactory.getDefaultAlgorithm();
                TrustManagerFactory tmf = null;
                tmf = TrustManagerFactory.getInstance(tmfAlgorithm);

                tmf.init(keyStore);

                sslContext = SSLContext.getInstance("TLS");
                sslContext.init(null, tmf.getTrustManagers(), null);


                okHttpClient = new OkHttpClient.Builder()
                        .sslSocketFactory(sslContext.getSocketFactory())
                        .connectTimeout(CONNECTION_TIME_OUT, TimeUnit.SECONDS)
                        .readTimeout(CONNECTION_TIME_OUT, TimeUnit.SECONDS)
                        .writeTimeout(CONNECTION_TIME_OUT, TimeUnit.SECONDS)
                        .retryOnConnectionFailure(true)
                        .build();

            } catch (KeyManagementException | NoSuchAlgorithmException | java.security.cert.CertificateException | IOException | KeyStoreException e) {
                e.printStackTrace();
            }


        }


        return okHttpClient;
    }
```

**Comment by swankjesse** [comment]
Your trust managers don't trust the server you're connecting to.

**Comment by Hemant0601** [comment]
@swankjesse Thats what I need to understand what Im doing wrong here, I tried a similar thing using Volley and it worked completely fine.

**Comment by swankjesse** [comment]
I'm not sure. It looks reasonable. Any way you can express this problem as a standalone test case?

**Comment by swankjesse** [comment]
This example works. Maybe see where your code and the example disagree?
https://github.com/square/okhttp/blob/master/samples/guide/src/main/java/okhttp3/recipes/CustomTrust.java

**Comment by Hemant0601** [comment]
@swankjesse Did exactly what mentioned above, getting same error.

**Comment by swankjesse** [comment]
Could you provide an executable test case? Presumably this is a bug in OkHttp but I don’t have enough information to reproduce it.

**Comment by msayanece** [comment]
Having same issue in my Tablet (Micromax P480) Android version 4.4.2, but in other devices it works fine. I don't have an idea of how to solve this.

**Comment by yschimke** [comment]
please reopen with more information e.g. a fully reproducible test case or URL to test against.

**Comment by Hemant0601** [comment]
I guess the above code is all the details needed.
URL?? we are using app side for this.
share little brief what exactly required for this.

**Comment by yschimke** [comment]
@Hemant0601 I can't paste that code into Intellij and run it and reproduce the failure.  The results could vary depending on Android version, server and URL, certificates used.  Similar examples are known to work, so there isn't much we can do.

If you are able to debug the issue and make it a reproducible bug report we can help.  But as is, it isn't something we can help with.  Try stackoverflow as you will get a wider response.

**Comment by Hemant0601** [comment]
@yschimke sure, will add if i get any running code or could not find any solution soon.
Thanks
