### ISSUE TITLE
java.net.SocketTimeoutException

### ISSUE THREAD

**Issue by ccbfm** [square/okhttp#3987]
https://github.com/square/okhttp/blob/fa994f54e41ab67dc407d37a72f4faa4a5245d1f/okhttp/src/main/java/okhttp3/RealCall.java#L152

'com.squareup.okhttp3:okhttp:3.9.0'

response.body().string(); 
When an exception occurs, the failed interface will not be called back

04-26 16:20:14.374 D/OkHttp  ( 5390): java.net.SocketTimeoutException
04-26 16:20:14.374 D/OkHttp  ( 5390):   at java.net.PlainSocketImpl.read(PlainSocketImpl.java:484)
04-26 16:20:14.374 D/OkHttp  ( 5390):   at java.net.PlainSocketImpl.-wrap0(PlainSocketImpl.java)
04-26 16:20:14.374 D/OkHttp  ( 5390):   at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:237)
04-26 16:20:14.374 D/OkHttp  ( 5390):   at okio.k$2.read(Okio.java:139)
04-26 16:20:14.374 D/OkHttp  ( 5390):   at okio.a$2.read(AsyncTimeout.java:237)
04-26 16:20:14.374 D/OkHttp  ( 5390):   at okio.m.read(RealBufferedSource.java:46)
04-26 16:20:14.374 D/OkHttp  ( 5390):   at okhttp3.internal.c.a$a.read(Http1Codec.java:352)
04-26 16:20:14.374 D/OkHttp  ( 5390):   at okhttp3.internal.c.a$c.read(Http1Codec.java:442)
04-26 16:20:14.374 D/OkHttp  ( 5390):   at okio.m.read(RealBufferedSource.java:46)
04-26 16:20:14.374 D/OkHttp  ( 5390):   at okhttp3.internal.a.a$1.read(CacheInterceptor.java:174)
04-26 16:20:14.374 D/OkHttp  ( 5390):   at okio.m.read(RealBufferedSource.java:46)
04-26 16:20:14.374 D/OkHttp  ( 5390):   at okio.m.exhausted(RealBufferedSource.java:56)
04-26 16:20:14.374 D/OkHttp  ( 5390):   at okio.j.a(InflaterSource.java:101)
04-26 16:20:14.374 D/OkHttp  ( 5390):   at okio.j.read(InflaterSource.java:62)
04-26 16:20:14.374 D/OkHttp  ( 5390):   at okio.i.read(GzipSource.java:80)
04-26 16:20:14.374 D/OkHttp  ( 5390):   at okio.c.a(Buffer.java:1005)
04-26 16:20:14.374 D/OkHttp  ( 5390):   at okio.m.readString(RealBufferedSource.java:190)
04-26 16:20:14.374 D/OkHttp  ( 5390):   at okhttp3.ab.string(ResponseBody.java:175)
04-26 16:20:14.374 D/OkHttp  ( 5390):   at com.pptv.tvsports.sender.c$1.onResponse(HttpSenderProxy.java:309)
04-26 16:20:14.374 D/OkHttp  ( 5390):   at okhttp3.x$a.b(RealCall.java:153)
04-26 16:20:14.374 D/OkHttp  ( 5390):   at okhttp3.internal.b.run(NamedRunnable.java:32)
04-26 16:20:14.374 D/OkHttp  ( 5390):   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
04-26 16:20:14.374 D/OkHttp  ( 5390):   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
04-26 16:20:14.374 D/OkHttp  ( 5390):   at java.lang.Thread.run(Thread.java:818)

**Comment by swankjesse** [comment]
That's working as intended. You can handle this with a try/catch in onResponse().

**Comment by ccbfm** [comment]
Thank you for your answer.
