### ISSUE TITLE
CacheInterceptor get/put with different key

### ISSUE THREAD

**Issue by veonua** [square/okhttp#3988]
I need to do redirect in my network interceptor in order to some query params

as soon as CacheInterceptor is on the top of the interceptor list (index 3), and my interceptor is #6 
so change of url breaks cache interceptor's keys

it always gets original url and puts modified key to the storage

**Comment by swankjesse** [comment]
Change the URL in an app interceptor?

**Comment by veonua** [comment]
unfortunately I need it after retryAndFollowUpInterceptor or ability to control it.
as far as I can see it is final

**Comment by yschimke** [comment]
Is there anything to do here?
