### ISSUE TITLE
Tune ConnectionPool pruning

### ISSUE THREAD

**Issue by swankjesse** [square/okhttp#3997]
It's been problematic in crawlers.
https://github.com/apache/nutch/pull/328

**Comment by swankjesse** [comment]
Yeah, I prefer small vs. scalable when the two are in conflict. For example, we don’t do any native code!

We can go toe-to-toe with Netty in all but the most extreme cases. We are very GC-friendly and small. And I also think OkHttp server is something we cad competitively if we get coroutines right.

**Comment by yschimke** [comment]
I’m using kotlin coroutines extensively in my client so that’s awesome to hear even for client only use

**Comment by yschimke** [comment]
Closing as a dupe of https://github.com/square/okhttp/issues/4530, a lot of overlap here.
