### ISSUE TITLE
cache:how to get cache data first then get network data in network connetting?

### ISSUE THREAD

**Issue by scsfwgy** [square/okhttp#4003]
What kind of issue is this?

 - [ ] Question. cache:how to get cache data first then get network data in network connetting?

**Comment by yschimke** [comment]
Execute two requests, and handle the 504 from the first cache request by sending a network request:

https://github.com/square/okhttp/wiki/Recipes

> To prevent it from using the network, use CacheControl.FORCE_CACHE. Be warned: if you use FORCE_CACHE and the response requires the network, OkHttp will return a 504 Unsatisfiable Request response.

Please follow up in stackoverflow question to benefit others.

**Comment by nuisanceless** [comment]
https://square.github.io/okhttp/recipes/

**Comment by nuisanceless** [comment]
https://square.github.io/okhttp/recipes/   not   https://github.com/square/okhttp/wiki/Recipes
