### ISSUE TITLE
websocket did not callback onFailure or onClosed

### ISSUE THREAD

**Issue by huangliqiang** [square/okhttp#4004]
`mOkHttpClient = new OkHttpClient.Builder()
                        .connectTimeout(20, TimeUnit.SECONDS)
                        .build();
        Request request = new Request.Builder()
                .url(config.getCurrentUrl())
                .addHeader("Connection", "close")
                .build();`

When I changed the network state (wifi -> 4G or wifi -> wifi),websocket did not immediately callback onFailure or onclosed，if i send message, user webSocket.send() will return true,  then I couldn't immediately know if websocket was disconnected. This is the only thing that happens to some mobile phones。 

How can I instantly know that websocket has been disconnected when the mobile network changes?

**Comment by swankjesse** [comment]
Might be an OS bug. OkHttp is actively reading from the web socket and will notify you when it sees it close.

**Comment by huangliqiang** [comment]
@swankjesse if i set pingInterval(long interval, TimeUnit unit),  will be useable ?

**Comment by swankjesse** [comment]
Yes, do that!

**Comment by yschimke** [comment]
Make sure you are using 3.10 which improves ping behaviour.
