### ISSUE TITLE
Http2 Multiplexing not working

### ISSUE THREAD

**Issue by mohrezaei** [square/okhttp#4007]
I'm not getting any multiplexing at all with Http2 and there are contradictory answers on Stackoverflow ([here](https://stackoverflow.com/questions/32625035/when-using-http2-in-okhttp-why-multi-requests-to-the-same-host-didnt-use-just) vs [here](https://stackoverflow.com/questions/49925071/how-do-i-do-multiplexing-on-okhttp)).

Environment: Okhttp 3.10.0, JDK 10
Run the following main method, using a console to monitor open sockets (e.g. with ```netstat -a -n | grep 104.101```, or whatever IP address http2.akamai.com resolves to from your location).

Test code:
```java
import okhttp3.*;

import java.io.IOException;

public class Http2Main
{
    public static void main(String[] args) throws Exception
    {
        Thread[] threads = new Thread[10];
        for(int i=0;i<threads.length;i++)
        {
            threads[i] = new PingThread();
        }
        for(int i=0;i<threads.length;i++)
        {
            threads[i].start();
        }
        Thread.sleep(10000);
        System.exit(0);
    }

    private static class PingThread extends Thread
    {
        @Override
        public void run()
        {
            while(true)
            {
                try
                {
                    OkHttpClient client = new OkHttpClient();
                    Request request = new Request.Builder().url("https://http2.akamai.com/demo").build();
                    Response response = client.newCall(request).execute();
                    System.out.println("Protocol: " + response.protocol());
                }
                catch (IOException e)
                {
                    e.printStackTrace();
                }
            }
        }
    }
}
```
I see hundreds of connections being made to akamai.

**Comment by JakeWharton** [comment]
You need to share the OkHttpClient instance.

**Comment by mohrezaei** [comment]
Thanks for the advice. New code, still doesn't work, but it seems to create fewer connections.

```java
import okhttp3.*;

import java.io.IOException;

public class Http2Main
{
    public static void main(String[] args) throws Exception
    {
        OkHttpClient client = new OkHttpClient();
        Thread[] threads = new Thread[10];
        for(int i=0;i<threads.length;i++)
        {
            threads[i] = new PingThread(client);
        }
        for(int i=0;i<threads.length;i++)
        {
            threads[i].start();
        }
        Thread.sleep(10000);
        System.exit(0);
    }

    private static class PingThread extends Thread
    {
        private OkHttpClient client;

        public PingThread(OkHttpClient client)
        {
            this.client = client;
        }

        @Override
        public void run()
        {
            while(true)
            {
                try
                {
                    Request request = new Request.Builder().url("https://http2.akamai.com/demo").build();
                    Response response = client.newCall(request).execute();
                    System.out.println("Protocol: " + response.protocol());

                }
                catch (IOException e)
                {
                    e.printStackTrace();
                }
            }
        }
    }
}
```
Console output while test is running:
$ netstat -a -n | grep 104.101
  TCP    192.168.1.4:49613      104.101.201.41:443     ESTABLISHED
  TCP    192.168.1.4:49617      104.101.201.41:443     ESTABLISHED
  TCP    192.168.1.4:49627      104.101.201.41:443     ESTABLISHED
  TCP    192.168.1.4:49637      104.101.201.41:443     ESTABLISHED
  TCP    192.168.1.4:49649      104.101.201.41:443     ESTABLISHED
  TCP    192.168.1.4:49657      104.101.201.41:443     ESTABLISHED
  TCP    192.168.1.4:49661      104.101.201.41:443     ESTABLISHED
  TCP    192.168.1.4:49678      104.101.201.41:443     ESTABLISHED
  TCP    192.168.1.4:49687      104.101.201.41:443     ESTABLISHED
  TCP    192.168.1.4:49697      104.101.201.41:443     ESTABLISHED
  TCP    192.168.1.4:49707      104.101.201.41:443     ESTABLISHED
  TCP    192.168.1.4:49717      104.101.201.41:443     ESTABLISHED
  TCP    192.168.1.4:49727      104.101.201.41:443     ESTABLISHED
  TCP    192.168.1.4:49738      104.101.201.41:443     ESTABLISHED

**Comment by mohrezaei** [comment]
Solved: I had to add ```response.close()```
