### ISSUE TITLE
The header of response has Chinese , and crash by IllegalArgumentException

### ISSUE THREAD

**Issue by KingPeng** [square/okhttp#4008]
I'm download file , but the header of response has Chinese, and crash by IllegalArgumentException;
The detail like this:
05-16 16:42:15.406 E/AndroidRuntime(  861): FATAL EXCEPTION: OkHttp Dispatcher

05-16 16:42:15.406 E/AndroidRuntime(  861): Process: com.linkin.launchery, PID: 861

05-16 16:42:15.406 E/AndroidRuntime(  861): java.lang.IllegalArgumentException: Unexpected char 0x6c99 at 22 in header value: attachment; filename="沙发管家_v4.8.5_xunma01.apk"

05-16 16:42:15.406 E/AndroidRuntime(  861): 	at com.squareup.okhttp.Headers$Builder.checkNameAndValue(Headers.java:295)

05-16 16:42:15.406 E/AndroidRuntime(  861): 	at com.squareup.okhttp.Headers$Builder.add(Headers.java:245)

05-16 16:42:15.406 E/AndroidRuntime(  861): 	at com.squareup.okhttp.internal.http.Http2xStream.readHttp2HeadersList(Http2xStream.java:264)

05-16 16:42:15.406 E/AndroidRuntime(  861): 	at com.squareup.okhttp.internal.http.Http2xStream.readResponseHeaders(Http2xStream.java:150)

05-16 16:42:15.406 E/AndroidRuntime(  861): 	at com.squareup.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:737)

05-16 16:42:15.406 E/AndroidRuntime(  861): 	at com.squareup.okhttp.internal.http.HttpEngine.access$200(HttpEngine.java:87)

05-16 16:42:15.406 E/AndroidRuntime(  861): 	at com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:722)

05-16 16:42:15.406 E/AndroidRuntime(  861): 	at com.squareup.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:576)

05-16 16:42:15.406 E/AndroidRuntime(  861): 	at com.squareup.okhttp.Call.getResponse(Call.java:287)

05-16 16:42:15.406 E/AndroidRuntime(  861): 	at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:243)

05-16 16:42:15.406 E/AndroidRuntime(  861): 	at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:205)

05-16 16:42:15.406 E/AndroidRuntime(  861): 	at com.squareup.okhttp.Call.access$100(Call.java:35)

05-16 16:42:15.406 E/AndroidRuntime(  861): 	at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:171)

05-16 16:42:15.406 E/AndroidRuntime(  861): 	at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)

05-16 16:42:15.406 E/AndroidRuntime(  861): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)

05-16 16:42:15.406 E/AndroidRuntime(  861): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)

05-16 16:42:15.406 E/AndroidRuntime(  861): 	at java.lang.Thread.run(Thread.java:818)

How can I handle ?

**Comment by swankjesse** [comment]
This is a bug in OkHttp. We should never crash on unexpected data from the server.

**Comment by BeckZero** [comment]
+1 same here....

**Comment by pidoubleyou** [comment]
The same problem occurs if the request header contains Chinese or German characters like 'ä'

**Comment by amirlivneh** [comment]
This has been probably fixed by 3ec5227d2693262db5467abcc36641a405808166.

`Http2xStream.readHttp2HeadersList()` was changed to call `Headers.Builder.addLenient()` and not `Headers.Builder.add()`, as seen in the stack trace.
