### ISSUE TITLE
Websocket closes connection with EOF exception on "Switching Protocols" code 101

### ISSUE THREAD

**Issue by dinzdale** [square/okhttp#4012]
OKHttp3 version 3.10. Android application
After a successful connection and a short period of inactivity, the OKHttp3 websocket throws a EOFException in response to a code 101, "Switching Protocols" response. This then disconnects the socket and our application is forced to re-connect again.
Is there anyway to control this so the socket does not close ? 
Is this expected behavior?
Our iOS and server side tests against the same server did not show this behaivor and remained connected until the applications disconnected them explicitely.

RealWebsocket class:

public void connect(OkHttpClient client) { ...

               try {
                    RealWebSocket.this.listener.onOpen(RealWebSocket.this, response);
                    String name = "OkHttp WebSocket " + request.url().redact();
                    RealWebSocket.this.initReaderAndWriter(name, streams);
                    streamAllocation.connection().socket().setSoTimeout(0);
                    RealWebSocket.this.loopReader();
                } catch (Exception var6) {
                    RealWebSocket.this.failWebSocket(var6, (Response)null);
                }
(Response return code 101)

**Comment by swankjesse** [comment]
Could you provide an executable test case? Nothing actionable here.

**Comment by dinzdale** [comment]
Issue Resolved:
Apologies, I should have specified that I am also using the wonderful STOMP client on top of the OKHttp3Client websockets:
https://github.com/NaikSoftware/StompProtocolAndroid by Nickolay Savchenko (Nickolay Savchenko
NaikSoftware). This library does an exceptional job of implementing the STOMP protocol integrated with OKHtttp3 websockets. 
This is where I fell short by using the wrong StompClient.over method to provide my Url, which will create a default websocket instance that has a default socket read timeout (30 seconds ?). The  for me was to use the alternative StompClient.over method, allowing for a reference to an application instance of the OKHttp3Client. This allows the application set it's desired timeouts beyond any defaults.
