### ISSUE TITLE
How do i solve, Android Picasso symbol error "with".?

### ISSUE THREAD

**Issue by Streamfloatiningplayer** [square/okhttp#4013]
I upgraded implementation `'com.squareup.picasso:picasso:2.5.2' to  implementation 'com.squareup.picasso:picasso:2.71828'`

also added this in App.grade:
`implementation 'com.squareup.okhttp3:okhttp:3.10.0'`

In My API client.java, I added this:
```
import okhttp3.OkHttpClient;
import okhttp3.Request;
```
But I still find this error message:
error: cannot find symbol `Picasso.with(context).load(url).placeholder(R.drawable.placeholder).into(thumbnail);
`
It also shows: cannot resolve method with(android.content.context)
`Picasso.with(context).load(url).placeholder(R.drawable.placeholder).into(thumbnail);`

Above written (With) Shows in red error mark. How can I solve this error?. Thanks.

**Comment by yschimke** [comment]
This seems like a Picasso question.  But also, please use the OkHttp for reproducible bugs instead of usage questions.  Stackoverflow might be the best way to get help for these types of issues.

**Comment by Streamfloatiningplayer** [comment]
Ok. Thanks.
