### ISSUE TITLE
Bug: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.

### ISSUE THREAD

**Issue by gybin02** [square/okhttp#4015]
Bug report.
   OKHttp3 version 3.8.1. Android application. 

   when I  set ' clientBuilder.sslSocketFactory'， request HTTPS will fail  In Android 5.X 
   
  here is my code which can  request https success.

        OkHttpClient.Builder clientBuilder = new OkHttpClient.Builder();
        OkHttpClient client = clientBuilder.build();

        String URL = "https://news.seeyouyima.com";
        Request request = new Request.Builder()
                .url(URL)
                .build();
       Call call = client.newCall(request);

this code which  request  https fail。

        clientBuilder.socketFactory(SocketFactory.getDefault());        
        SSLSocketFactory socketFactory = SSLContext.getDefault()
                                                      .getSocketFactory();
        clientBuilder.sslSocketFactory(socketFactory);
        OkHttpClient client = clientBuilder.build();

        String URL = "https://news.seeyouyima.com";
        Request request = new Request.Builder()
                .url(URL)
                .build();
       Call call = client.newCall(request);

Exception Message is: 
`
javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
`

**Comment by yschimke** [comment]
That method sslSocketFactory is deprecated, and the alternative is documented with an explanation and workaround code.

https://square.github.io/okhttp/3.x/okhttp/okhttp3/OkHttpClient.Builder.html#sslSocketFactory-javax.net.ssl.SSLSocketFactory-javax.net.ssl.X509TrustManager-

**Comment by imtianx** [comment]
I also have the same question only when I set up the phone to proxy with Charles ,how can I solve it?

**Comment by liuao2010** [comment]
it's not work for me
