### ISSUE TITLE
This is a very serious problem，com.squareup.okhttp3:okhttp-urlconnection:3.10.0  have socket File handle  leak ,when pass 1000 handle,the app while quit.

### ISSUE THREAD

**Issue by xihuan22d** [square/okhttp#4020]
com.squareup.okhttp3:okhttp-urlconnection:3.10.0  have File handle  leak ,when pass 1000 handle,the app while quit.

but the httpURLConnection don't  have this probelm ， is socket something  don't close？

**Comment by xihuan22d** [comment]
I write a demo to Reproduce the bug

https://github.com/xihuan22d/OKHttpBugTest

**Comment by JakeWharton** [comment]
Dupe of #4019.
