### ISSUE TITLE
the request in EventListener's  call Parameter not change during

### ISSUE THREAD

**Issue by changety** [square/okhttp#4021]
I use EventListener's callback to record some logs, like method callStart(Call call), callEnd(Call);  And I get call parameter to get the Request;

![ec7cecc578b2436a9bd341b95896dbe0_3d5dd4329b415636baf94e248c34f0f2](https://user-images.githubusercontent.com/1650376/40418922-3da0c4d6-5eb6-11e8-9ec1-0857c8c44736.jpg)
But there's some problems, if I newBuilder a Request to replace a new host for a call in some interceptors, for example, the originalRequest in Call not change at all; 
![1f77f6ae0b9943589bfada6329a57232_6017ec5104d727776047cd4b53ee3402](https://user-images.githubusercontent.com/1650376/40418961-5ca1bdf4-5eb6-11e8-9733-1a654d4de969.jpg)

So, how can I get the real host in the method callStart(); is there some elegance way?  
The key is that we should get the real Request after interceptor in EventListener's callback

I know this maybe not a issue, but the Requst in call parameter maybe change.

**Comment by swankjesse** [comment]
At the time callStart() has been called the interceptor hasn’t run yet.
