### ISSUE TITLE
When the request is cancelled frequently, it will cause SocketTimeoutException

### ISSUE THREAD

**Issue by Caij** [square/okhttp#4025]
version 3.10.0

demo: https://github.com/Caij/OkHttpDownDemo

**Comment by yschimke** [comment]
Hopefully this is fixed by https://github.com/square/okhttp/pull/4052

**Comment by Caij** [comment]
Thanks .  When is it released?

**Comment by yschimke** [comment]
I'm not sure at the moment, can you test with a snapshot build? https://oss.jfrog.org/artifactory/libs-snapshot/com/squareup/okhttp3/okhttp/3.11.0-SNAPSHOT/

**Comment by Caij** [comment]
I test with a snapshot build, The problem has been solved.
