### ISSUE TITLE
HttpUrl.Builder does not support ws and wss schemes

### ISSUE THREAD

**Issue by gastaldi** [square/okhttp#4035]
What kind of issue is this?

 - [x] Bug report

From https://en.wikipedia.org/wiki/WebSocket
>The WebSocket protocol specification defines **ws** (WebSocket) and **wss** (WebSocket Secure) as two new uniform resource identifier (URI) schemes that are used for unencrypted and encrypted connections, respectively. Apart from the scheme name and fragment (# is not supported), the rest of the URI components are defined to use URI generic syntax.

Test case: 

```java
import okhttp3.HttpUrl;
import org.junit.Test;

import static org.assertj.core.api.Assertions.assertThatCode;

/**
 * @author <a href="mailto:ggastald@redhat.com">George Gastaldi</a>
 */
public class HttpUrlTest {

    @Test
    public void should_support_ws() {
        assertThatCode(() -> new HttpUrl.Builder().scheme("ws").host("localhost").build())
                .doesNotThrowAnyException();
    }

    @Test
    public void should_support_wss() {
        assertThatCode(() -> new HttpUrl.Builder().scheme("wss").host("localhost").build())
                .doesNotThrowAnyException();
    }
}
```

**Comment by yschimke** [comment]
This feels like a pure judgement call.  To me, I would have expected ws and wss to be supported.  However, this was a deliberate design decision.  Will close unless OS (@swankjesse and @JakeWharton) want to revisit.

**Comment by swankjesse** [comment]
Yep, this is deliberate. If you want a class to model ws:// URLs, it's pretty straightforward to build if you delegate to HttpUrl. I'm not seeking contributions of such a class at this time.
