### ISSUE TITLE
head protocol Question

### ISSUE THREAD

**Issue by moumoudodoo** [square/okhttp#4036]
Code
Request request = new Request.Builder().url(url).head().build();
Response response = okHttpClient.newCall(request).execute();
response.body().contentLength();
on 3.4.2 is success
on 3.10.0 response.body() is {}

**Comment by yschimke** [comment]
Hey, can you provide any more context? Android? JVM? versions? HTTP/2?

**Comment by moumoudodoo** [comment]
Thank you。This is in Android，I solved the problem！
Code
response.body().contentLength();  -> Integer.valueOf(response.header("Content-Length"))
