### ISSUE TITLE
Suggestion: Request context information

### ISSUE THREAD

**Issue by yschimke** [square/okhttp#4039]
I'd like to add the ability of a Request or maybe Call to carry some additional contextual information.  I'm curious if this has been considered before.  Or any thoughts for how to approach this, e.g. an immutable Map on Request.

I'm bastardising request.tag in my own project to carry an optional auth token or "pointer".

https://github.com/yschimke/oksocial/blob/6b8025dc3a53623e3b49d041ef36037961ae0c23/src/main/kotlin/com/baulsupp/oksocial/credentials/TokenSet.kt

```
sealed class Token {
  open fun name(): String? = null
}

val DefaultToken = TokenSet("default")

data class TokenSet(val name: String) : Token() {
  override fun name(): String? = name
}

data class TokenValue(val token: Any) : Token()

object NoToken : Token()
```

Used to override the auth token that a preregistered authenticator should use e.g. None, Default, "Work", "Accounts", "Personal", or even a programmatically provided one.

e.g.

```
    val response = client.query<Oauth2TokenResponse>(request("https://connect.squareup.com/oauth2/token", NoToken) {
      postJsonBody(AuthDetails(clientId, clientSecret, code, s.redirectUri))
    })
```

This works, but I'm fighting the OkHttp library to do it.  It is terrible example code I can't show anybody.

**Comment by swankjesse** [comment]
That’s what the tag is for! It’s only job is to be a place for you to stash something. And if you find you need to stash a few things, you can do that too:

```
class SocialTag {
  var token: Token
  var stacktrace: Throwable
  var callback: SocialCallback
}
```

**Comment by yschimke** [comment]
Ok great.  This isn't very clear to me then

```
    /**
     * Attaches {@code tag} to the request. It can be used later to cancel the request. If the tag
     * is unspecified or null, the request is canceled by using the request itself as the tag.
     */
    public Builder tag(Object tag) {
      this.tag = tag;
      return this;
    }
```

**Comment by swankjesse** [comment]
Yeah, that's a mistake. One of the original motivations was so you could tag a request with the current screen in an Android app, then cancel them all when you leave that screen.

We should update to say it's a free-for-all.

**Comment by yschimke** [comment]
That sounds cool.  Can you do that via the API somehow?

**Comment by swankjesse** [comment]
We dropped it! https://github.com/square/okhttp/issues/2205

**Comment by yschimke** [comment]
I'll update the comments.
