### ISSUE TITLE
version-3.10.0 Whether there is a bug to SSL

### ISSUE THREAD

**Issue by rooChick** [square/okhttp#4042]
Set sslSocketFactory and hostnameVerifier in 3.10.0 to solve SSL exceptions, but network requests are SSL exceptions.
Later, turning the library into 3.9.1 does not require sslSocketFactory and hostnameVerifier network requests to be normal, so there is bug in the 3.10.0 version.

**Comment by yschimke** [comment]
Please post a reproducible code sample e.g. hitting https://httpbin.org/get.

**Comment by swankjesse** [comment]
My guess is that it’s cause we took some obsolete ciphers (`TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA` and `TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA`) away:
https://github.com/square/okhttp/blob/master/CHANGELOG.md#version-3100

Is your server reachable with Chromium?

**Comment by rooChick** [comment]
It can be accessed in browsers and cannot be accessed on the okhttp3.10.0 version. The example web address is https://api.yuncloudapp.com/? Opact=ticket/index

**Comment by rooChick** [comment]
It can be accessed in browsers and cannot be accessed on the okhttp3.10.0 version. The example web address is https://api.yuncloudapp.com/? Opact=ticket/index

**Comment by yschimke** [comment]
Closing - no response.  Please provide reproducible sample code, and chrome test results and reopen.
