### ISSUE TITLE
Log not work?

### ISSUE THREAD

**Issue by SerBad** [square/okhttp#4044]
why this log is not work?
Platform.get().log(Level.INFO.intValue(), "This is a test log ", null)

**Comment by yschimke** [comment]
Could you please provide a reproducible test case, otherwise please ask on stackoverflow.  I'm assuming this is on Android, so please sanity check that logging works first before posting to stackoverflow.

Log.println(Log.DEBUG, "ME", "******");

**Comment by SerBad** [comment]
yeah，it's Android，
Log.println(Log.DEBUG, "ME", "******");
work well，
so , when I try use HttpLoggingInterceptor on Retrofit ,can't log anything.I don't why?
there's my code .
`    @Singleton
    @Provides
    fun provideHttpLoggingInterceptor(): HttpLoggingInterceptor {
        return HttpLoggingInterceptor().apply {
            if (BuildConfig.DEBUG) {
                level = HttpLoggingInterceptor.Level.BODY
            }
        }
    }

    @Provides
    @Singleton
    fun provideOkHttpClient(): OkHttpClient {
        return OkHttpClient.Builder()
                .connectTimeout(5, TimeUnit.SECONDS)
                .readTimeout(5, TimeUnit.SECONDS)
                .addInterceptor(provideHttpLoggingInterceptor())
                .addInterceptor(CosHttpInterceptor()).build()
    }

    @Provides
    @Singleton
    fun provideGson(): Gson = Gson()

    @Provides
    @Singleton
    fun provideApiService(retrofit: Retrofit): ApiService {
        return retrofit.create(ApiService::class.java)
    }

    @Provides
    @Singleton
    fun provideRetrofit(): Retrofit {
        return Retrofit.Builder()
                .baseUrl(ApiService.BASE_URL)
                .addConverterFactory(CosGsonConverterFactory.create(provideGson(), provideNoticeManager()))
                .addCallAdapterFactory(RxJava2CallAdapterFactory.create())
                .client(provideOkHttpClient())
                .build()
    }`

**Comment by yschimke** [comment]
Please post to stackoverflow with an executable test case, the sample code provided is not executable without extensive project setup.
