### ISSUE TITLE
 Exception! message:closed

### ISSUE THREAD

**Issue by gelbertgel** [square/okhttp#4047]
- My okhttp version:  3.10.0

           @Override
            public void onResponse(@NonNull Call call, @NonNull Response response) {
                if (response.isSuccessful()) {

                    try {

                        final String url = response.request().url().toString();
                        Log.i(TAG, " url: " + url);

                        Thread diffThread = new Thread(new Runnable() {
                        @Override
                         public void run() {

                                try {

                                    System.setProperty("http.keepAlive", "false");

                                    ResponseBody responseBody = response.body();

                                    if (responseBody == null) {
                                        return;
                                    }

                                   BufferedSource source = responseBody.source();

                                    } catch(Exception e){
                                      ---> Exception! message:closed
                                    }
      }

        

How can I do that? It gives an error if it is in a different thread? Please help me

**Comment by yschimke** [comment]
This example doesn't look complete. It's unclear what exactly is going on and doesn't look executable.  There is no stacktrace either.

Consider posting an example to stackoverflow for usage problems like this.  But this isn't really a reproducible bug report as is.
