### ISSUE TITLE
Expose public APIs for CertificatePinner pins

### ISSUE THREAD

**Issue by pooyanmajd** [square/okhttp#4049]
Hey guys,

CertificatePinner.Builder class has add method, Is it possible to add a get method as well? I need to know if there are any pins already added in the class

**Comment by yschimke** [comment]
@pooyanmajd care to submit a PR?

**Comment by swankjesse** [comment]
This is tough ’cause we don’t currently expose a `Pin` type, and would need to do that, or something similar, to make this API make sense.

**Comment by pooyanmajd** [comment]
Yeah I wanted to create a PR but I figured out we need to expose `Pin` object as well or we can just return a Pair object since Pin is <String, String>

**Comment by pooyanmajd** [comment]
So we should make `Pin` class a public separate class not a nested static one, and return the list of Pins from builder
