### ISSUE TITLE
How can this happen, throw an exception after CallEnd

### ISSUE THREAD

**Issue by changety** [square/okhttp#4051]
I got a stacktrace that show a request has callEnd,  and receive an exception.  Why not call callFail, but call callEnd and then throw this exception. 

FYI, this request factly not success because the response body not receive completely.

![popo_2018-06-08 15-26-28](https://user-images.githubusercontent.com/1650376/41144701-5bd256be-6b30-11e8-8009-f46d542d8861.jpg)

**Comment by yschimke** [comment]
I can't reproduce with https://github.com/square/okhttp/pull/4069

**Comment by changety** [comment]
👍,nice job for ：
Fix: Don't drop a call to EventListener.callEnd() when the response body is consumed inside an interceptor.
