### ISSUE TITLE
OkHttp slower than Unirest?

### ISSUE THREAD

**Issue by xttam** [square/okhttp#4056]
Check the two examples below. I've found OkHttp is way slower (~110ms) than Unirest (~0.001ms), so much so that I'm certainly missing something.

Where is the request really executed, is it in [1] or [2]? Why does it take so much time to run [2]?

```java
String endpoint = "https://gist.githubusercontent.com/xttam/193913ed1e1fa3ea2b360c08b39eb84e/raw/0cae0280bda7332c6bd2a40ff25566efcbf0aad1/gistfile1.txt";
{
    System.out.println("OkHttp");
    OkHttpClient client = new OkHttpClient();
    Request request = new Request.Builder().url(endpoint).build();
    for (int i=0; i<10; i++) {
        Response response = client.newCall(request).execute(); // [1]
        if (response.isSuccessful()) {
            long start = System.nanoTime();
            String body = response.body().string(); // [2]
            long end = System.nanoTime();
            System.out.println(" "+(end - start)/1000000.0 + "ms");
        }
    }
}
System.out.println();
{
    System.out.println("Unirest");
    GetRequest request = Unirest.get(endpoint);
    for (int i=0; i<10; i++) {
        HttpResponse<String> response = request.asString(); // [1]
        if (response.getStatus() == 200) {
            long start = System.nanoTime();
            String body = response.getBody(); // [2]
            long end = System.nanoTime();
            System.out.println(" "+(end - start)/10000000.0 + "ms");
        }
    }
}
```

Output

```
OkHttp
 129.337261ms
 112.919293ms
 112.809315ms
 112.228543ms
 114.533677ms
 112.522991ms
 111.165509ms
 111.931617ms
 112.203989ms
 111.456409ms

Unirest
 7.753E-4ms
 1.023E-4ms
 1.356E-4ms
 1.244E-4ms
 7.59E-5ms
 1.137E-4ms
 5.08E-5ms
 1.26E-4ms
 1.285E-4ms
 7.47E-5ms
```

**Comment by JakeWharton** [comment]
Those Unirest times are impossible for HTTP. It presumably buffers the entire response and you're merely measuring how long it takes to return a reference. Measure the whole thing and the times will be equal.

**Comment by yschimke** [comment]
From a command line client, so not an optimised as a persistent server.  

![image](https://user-images.githubusercontent.com/231923/41296135-23c12896-6e54-11e8-9e84-b4996fd85ea8.png)

**Comment by xttam** [comment]
Here are the results when measuring the whole thing, I still see OkHttp being about 10x slower.

```java
String endpoint = "https://gist.githubusercontent.com/xttam/193913ed1e1fa3ea2b360c08b39eb84e/raw/0cae0280bda7332c6bd2a40ff25566efcbf0aad1/gistfile1.txt";
{
    System.out.println("OkHttp");
    OkHttpClient client = new OkHttpClient();
    Request request = new Request.Builder().url(endpoint).build();
    for (int i=0; i<10; i++) {
        long start = System.nanoTime();
        Response response = client.newCall(request).execute(); // [1]
        if (response.isSuccessful()) {
            String body = response.body().string(); // [2]
        }
        long end = System.nanoTime();
        System.out.println(" "+(end - start)/1000000.0 + "ms");
    }
}
System.out.println();
{
    System.out.println("Unirest");
    GetRequest request = Unirest.get(endpoint);
    for (int i=0; i<10; i++) {
        long start = System.nanoTime();
        HttpResponse<String> response = request.asString(); // [1]
        if (response.getStatus() == 200) {
            String body = response.getBody(); // [2]
        }
        long end = System.nanoTime();
        System.out.println(" "+(end - start)/10000000.0 + "ms");
    }
}
```

```
OkHttp
 1087.883824ms
 184.502116ms
 185.824719ms
 184.254003ms
 184.359506ms
 247.390385ms
 271.082414ms
 229.310894ms
 223.316986ms
 208.466311ms

Unirest
 56.7184372ms
 18.5351475ms
 18.5024981ms
 18.4437487ms
 18.7865435ms
 18.5818931ms
 18.4320346ms
 18.5278975ms
 18.491005ms
 19.0403392ms
```

**Comment by xttam** [comment]
Can you explain further why those times are impossible for HTTP? At the beginning I wasn't measuring the time it takes to get the response from the server, only the time it takes to convert it to a String. I was expecting it to be bellow 1ms.

**Comment by yschimke** [comment]
@xttam if you are on mac "brew install oksocial" it's a very small subset of curl like features on OkHttp. Otherwise checkout the project from github and run locally.  But has a flag to publish zipkin trace results also.

**Comment by yschimke** [comment]
@xttam you are dividing by 1,000,000.0 vs 10,000,000.0

**Comment by yschimke** [comment]
Some good guides to tell you if things seem off

https://gist.github.com/hellerbarde/2843375

And a guide to the typical roundtrips you see in HTTPS requests 

https://blog.cloudflare.com/introducing-0-rtt/

**Comment by JakeWharton** [comment]
OkHttp streams responses and it's clear that the other library does not. When you get a `Response` only the headers have been read. Calling `.string()` forces the library to block until all bytes have been consumed. Both libraries will be 100x faster than the speed of the network so you aren't going to get any kind of reasonable measurement or difference in measurement.

**Comment by xttam** [comment]
Oh, my bad! That explains it. Now I'm getting about the same numbers for both libs. However, I feel I'm not completely understanding what those calls are doing internally for OkHttp.

`new Request.Builder().url(endpoint+"?t="+System.nanoTime()).build()` creates the request but doesn't send anything.

`client.newCall(request).execute()` sends the request and waits for the response, but doesn't download the response, only its headers so you can check things like `response.isSuccessful()` immediately.

`response.body().string()` downloads the body of the response and returns a string.

Can you confirm this is correct?

Thanks for the links you added to your message above.

**Comment by JakeWharton** [comment]
Yep! That's about it. You can also stream the body (since the code will be
orders of magnitude faster than the network) by using source(),
byteStream(), or charStream().

**Comment by xttam** [comment]
That's great. And for the sake of completeness before closing this issue...

Any advice on improving the performance further when sending multiple requests to the same server as fast as possible, other than using async calls (ie, `client.newCall(request).enqueue(callback)`) and making sure HTTP2 is used so the socket is reused?

**Comment by xttam** [comment]
I'm closing this issue and asking my other question on StackOverflow, I think that'll be more appropriate.

**Comment by yschimke** [comment]
That server (https://gist.github.com/robots.txt) is HTTP/1.1 - but yeah, HTTP/2 should help when possible. Enqueue vs Execute as you mention.  Streaming the body as Jake mentioned i.e. processing the response when first byte is received, which can be well in advance of server sending the last byte.  Enabling caching.

You could also test conscrypt/jdk SSL on the JVM.  On Android, test the latest Google Play Provider vs the default.

I'd also suggest tracing, you might find that your biggest time is waiting for the server to generate and send the response so you can only get a small win.

**Comment by xttam** [comment]
Thank you @yschimke. I'll take those tips.
