### ISSUE TITLE
bug : Accept-Encoding:gzip

### ISSUE THREAD

**Issue by feiyangtianyao** [square/okhttp#4061]
BridgeInterceptor: 78-82 
if (userRequest.header("Accept-Encoding") == null && userRequest.header("Range") == null) {
      transparentGzip = true;
      requestBuilder.header("Accept-Encoding", "gzip");
    }

If I set the "Accept-Encoding:gzip"，"transparentGzip" is false. then the ChunkedSource can not turn to GzipSource. This will cause unrecognizable characters.

**Comment by swankjesse** [comment]
Don't do that then?

OkHttp will only decompress your response if you aren't already managing the accept-encoding header. As soon as you provide that header yourself, you're signaling to OkHttp that you're going to handle things.
