### ISSUE TITLE
Is there any way to set the local port in okttp?

### ISSUE THREAD

**Issue by YunlongYang** [square/okhttp#4062]
- [ ] Question:  Is there any way to set the local port in okttp?

**Comment by JakeWharton** [comment]
OkHttp is a client, not a server. Any port is part of the request URL.

**Comment by yschimke** [comment]
You can implement a SocketFactory and set it on OkHttpClient e.g. https://github.com/yschimke/oksocial/blob/e484fa1548b7e34b95972826f40dce0b5fe32f35/src/main/kotlin/com/baulsupp/oksocial/network/InterfaceSocketFactory.kt
