### ISSUE TITLE
okhttp3:okhttp:3.8.1 Error reporting using websocket

### ISSUE THREAD

**Issue by hrdgr** [square/okhttp#4063]
Hello, please ask for your help

The onFailure method is used when the regular heartbeat is executed for a period of time

**Comment by yschimke** [comment]
It's not clear from this, whether you think the current behaviour is a bug.  I think you are asking whether you will get onFailure when heartbeats are not received within some amount of time.  

A Stackoverflow post with example code is likely to get a better answer.  But note that websocket heartbeats have been enforced in 3.10.0, so upgrading might be worthwhile.

**Comment by hrdgr** [comment]
It should be the heartbeat for a while, will take the wrong way.
My current version of androidstud is 2.3.3, so I can't use 3.10.0 version of okhttp。
