### ISSUE TITLE
Upload file with DHCP v6 SLA isn't working on Android

### ISSUE THREAD

**Issue by simplythomasjay** [square/okhttp#4064]
I am developing inside a company network with several VLANs.

The distribution method of ipv6 addresses is with DHCP v6 SLA.

I have an internet server in the outside world with dual stack ipv6 and ipv4.

I want to upload a small zip-file from the android-device (which is inside the company-wlan) to the server with a https-connection.

I tried several combinations from older Android-devices to newer Android-devices and older and newer Okhttp-library-versions (but this isn't changing anything).

I tried several combinations of ipv4 ipv6 stacks. And this is what i discovered:

ipv4 only (in company) -> works
ipv6 only with VLAN and DHCP v6 SLA -> it don't work
ipv4 and ipv6 in my home network -> works
ipv4 and ipv6 with VLAN and DHCP v6 SLA -> it don't work.

What really bugs me:
If I go with Google Chrome on the Android Device onto this website it is just loading fast - so no problem.
If i want to upload with Okhttp it hangs at  " Response response = client.newCall(request).execute();  "
I have a log entry at the server-side so it is not an issue with dns-resolving.
(Error number 500)

I am doing the same upload with Win10, .net and https and it works just out of the box. 

I hope this is specific enough and it is possible to rebuild this scenario.

Best regards,
Thomas

**Comment by jhillmannco** [comment]
We have the same issue problem seems ipv4 and ipv6

**Comment by yschimke** [comment]
It isn't enough to go on.  Can you running with the PrintEventListener but use Android log instead of System.out.  Then provide that output.

https://github.com/square/okhttp/wiki/Events 

Also provide your client code.  If we can't see something obvious in the output, and you can't reproduce in a test we can verify against, then you might get more eyes on the problem by posting to stackoverflow.  This isn't an actionable bug report as is.

**Comment by simplythomasjay** [comment]
I have some further info.
https://www.techrepublic.com/article/androids-lack-of-dhcpv6-support-poses-security-and-ipv6-deployment-issues/  
In Android version 6, 7 and 8 there is still DHCPv6 not implemented.

I downloaded the APP "Network Info 2" and read out the assigned ipv6 addresse.

A Nexus 5x with Android 8.1 is selfassigning an ipv6 address which is a combination from an advertised prefix and the link local address.
 
In the company network we are not enforcing a blacklist or whitelist. So there seems to be room for the Chrome browser to somehow communicate with the router and get ipv6 network traffic back and forth over ipv6. (I think because Chrome browser is a native implementation).
But in the app-world with the standardized APIs there is no room for this.

With okhttp it is possible to send some packets to the server (this is the reason why i have em in the server log), but there is no packet coming back (the router is sending this packets into a wrong direction somehow).

Here is the feature request for DHCPv6
https://issuetracker.google.com/issues/36949085  
But it is still not implemented.
