### ISSUE TITLE
HTTP 1.1 Pipelining Workaround?

### ISSUE THREAD

**Issue by xttam** [square/okhttp#4066]
I need to send multiple requests to a rest server one after the other, those requests must execute in FIFO order, otherwise some would fail.

The easiest would be to wait for the response of one to send the next and so on, but that is way too slow for this application, so I sending them with no delay in between.

OkHttp doesn't support HTTP 1.1 pipelining, right? That would be perfect for me. I'm aware of HTTP2 multiplexing and I tried it, but it usually crashes as the server tries to process all requests in parallel rather than in FIFO order.

I'm guessing you have no plans to add pipelining to OkHttp, so the question is if there's any workaround to be able to send requests using HTTP2 without waiting for their responses, but also force the server to process them in order.

**Comment by JakeWharton** [comment]
And if you don't want this to apply to all connections, use newBuilder() to create a new instance from a shared instance with the restrictive configuration and then only use that new instance for calls to that host.

**Comment by xttam** [comment]
So let me see if I got it right. Currently if I send two async requests with OkHttp (assuming HTTP2 is not supported) it would actually create two sockets and send each requests on a different socket?

Now, if I set the max per-host connection to 1 there is only one connection, so both requests will be sent through the same socket. Would OkHttp wait for the response of A before sending B? If not, what's the difference between this approach and pipelining? I'm confused.

**Comment by JakeWharton** [comment]
I believe it's going to wait. So not pipelining, but at least serial.

**Comment by xttam** [comment]
I see, that wouldn't work for me.

**Comment by xttam** [comment]
I'm not sure if there's an HTTP2 header to ask the server to process in FIFO order (ie, to simulate pipelining with multiplexing).

If you know this is possible or any other workaround on OkHttp3 that would be really useful.

**Comment by xttam** [comment]
On a second thought, I'm actually not getting what kind of support is needed on the client.

What I'm asking for is really simple. I would like to send the requests in async mode with OkHttp, and I don't need it to do anything special apart from keeping the connection alive, which is something it already support. How is that pipelining is not done out of the box? Looks like it should be doing some checks to avoid it, which I may be able to disable. Don't know, it's just an idea.

**Comment by swankjesse** [comment]
Pipelining is a great idea but not reliable in practice. You should probably just make your calls in serial and ask your server team to fix their stuff.
