### ISSUE TITLE
Unreleased Resource while using  OkHttpClient.socketFactory()

### ISSUE THREAD

**Issue by selmanon** [square/okhttp#4075]
Among the suggested solution for Untagged socket detected [issue](https://github.com/square/okhttp/issues/3537) , we find the use `SocketFactory` you coud check the implementation [here](https://github.com/hidroh/materialistic/pull/1101/commits/74c6f4fab5855d8b08570855e2ce77e9cd4f9121).
The problem that I faced now is that the created socket didn't seem's to be released by `OkHttpClient`.
Do this issue create a Security Vulnerabilities ?

**Comment by yschimke** [comment]
The socket won't be released until the connection or client is closed.  See docs on closing a client here http://square.github.io/okhttp/3.x/okhttp/

IF you want further answers please post a question on stackoverflow

**Comment by selmanon** [comment]
@yschimke thanks.
The posted link is just the Okhttp doc home page could you please fix it to point to the right page :].
