### ISSUE TITLE
Move RealCall to okhttp3.internal.http package

### ISSUE THREAD

**Issue by PromanSEW** [square/okhttp#4080]
This class is package-private, all other classes and interfaces in the root package are public, as public API, except `RealCall`. Why it lives in the root package since all other implementations are located in `okhttp3.internal`?

**Comment by JakeWharton** [comment]
A quick look shows 4 or 5 usages of package private methods on other types.
Those could be exposed through the Internal class hack, but I'm not sure
there's motivation for the move.

**Comment by yschimke** [comment]
reopen to continue the discussion
