### ISSUE TITLE
Limit Payload on HTTP/2 Support

### ISSUE THREAD

**Issue by darkfrog26** [square/okhttp#4081]
This is both a feature request and bug report.  There does not appear to be any mechanism to limit the maximum payload of requests, but when doing asynchronous HTTP/2 requests to the same server, the payload can get rather large and some RESTful APIs throw 413s if you send too large of a payload.

This results in an uncontrollable situation where OkHttp is overflowing the server and getting errors back.  The only solution is to reduce the rate of calling, but that decreases the performance of my application substantially.  It would be far better if OkHttp had a configuration option to limit the maximum payload size so multiple HTTP requests via HTTP/2 didn't stack to overflow.

**Comment by darkfrog26** [comment]
This seems like a pretty huge bug in OkHttp. Why can't I get any response to it?

**Comment by darkfrog26** [comment]
@swankjesse and @JakeWharton I apologize for roping you in, but I'm afraid this issue isn't getting the visibility it needs.

**Comment by dave-r12** [comment]
I don't follow. HTTP/2 has built-in flow control that the server can use. If the client is sending too much data, why doesn't the server alter the HTTP/2 settings? Those settings are honored by the client.

**Comment by darkfrog26** [comment]
Well, I'm not sure.  It is for this API: https://smartystreets.com/docs/cloud/us-street-api that I'm having trouble.

As the documentation states: `413 | Request Entity Too Large: The maximum size for a request body to this API is 32K (32,768 bytes).`

This occurs only when the asynchronous communication gets saturated.  Is this a bug in their system you think then?

**Comment by JakeWharton** [comment]
And just to be clear, this is an open source project worked on by volunteers when they choose. We do not offer any kind of SLA on issue response or guarantee of fix.

**Comment by darkfrog26** [comment]
@JakeWharton, of course, I never intended to suggest otherwise.  It's a great project and just was concerned that you'd want to know of an issue like this.

**Comment by dave-r12** [comment]
@darkfrog26 that's strange. You should be able to enforce this constraint in your own app specific code when transmitting the request body. At first glance, I'd say it just a coincidence (the async requests.) I bet we could violate that constraint with synchronous requests as well.

**Comment by yschimke** [comment]
So it doesn't look to me like that server even supports HTTP/2.  I'm getting http/1.1 responses and ssllabs agrees.

```
$ ./oksocial --debug 'https://us-street.api.smartystreets.com/street-address?street=1600+amphitheatre+pkwy&city=mountain+view&state=CA&candidates=10'
18:03:08.548	url https://us-street.api.smartystreets.com/street-address?street=1600+amphitheatre+pkwy&city=mountain+view&state=CA&candidates=10
18:03:08.553	Request Request{method=GET, url=https://us-street.api.smartystreets.com/street-address?street=1600+amphitheatre+pkwy&city=mountain+view&state=CA&candidates=10, tag=TokenSet(name=default)}
18:03:08.571	Dns (us-street.api.smartystreets.com): us-street.api.smartystreets.com/45.33.22.104, us-street.api.smartystreets.com/147.75.68.23, us-street.api.smartystreets.com/8.9.37.241, us-street.api.smartystreets.com/45.77.157.49, us-street.api.smartystreets.com/45.56.78.239, us-street.api.smartystreets.com/45.33.26.94, us-street.api.smartystreets.com/140.82.6.112, us-street.api.smartystreets.com/147.75.68.17, us-street.api.smartystreets.com/140.82.40.87, us-street.api.smartystreets.com/104.237.130.234
18:03:09.061	--> GET https://us-street.api.smartystreets.com/street-address?street=1600+amphitheatre+pkwy&city=mountain+view&state=CA&candidates=10 http/1.1
18:03:09.061	User-Agent: oksocial/dev
18:03:09.061	Host: us-street.api.smartystreets.com
18:03:09.062	Connection: Keep-Alive
18:03:09.062	Accept-Encoding: gzip
18:03:09.062	Accept-Encoding: br
18:03:09.062	--> END GET
18:03:09.227	<-- 200 OK https://us-street.api.smartystreets.com/street-address?street=1600+amphitheatre+pkwy&city=mountain+view&state=CA&candidates=10&auth-id=XXX&auth-token=XXX (164ms)
18:03:09.227	Content-Type: application/json; charset=utf-8
18:03:09.227	Date: Sat, 23 Jun 2018 17:03:09 GMT
18:03:09.227	Content-Length: 829
18:03:09.227	Strict-Transport-Security: max-age=31536000; includeSubDomains
18:03:09.227	<-- END HTTP
18:03:09.230	OkHttp Platform: ConscryptPlatform
18:03:09.231	TLS Version: TLS_1_2
18:03:09.231	Protocol: http/1.1
18:03:09.231	Cipher: TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
18:03:09.231	Peer Principal: CN=smartystreets.com, OU=PositiveSSL Multi-Domain, OU=Domain Control Validated
[
  {
    "input_index": 0,
    "candidate_index": 0,
    "delivery_line_1": "1600 Amphitheatre Pkwy",
    "last_line": "Mountain View CA 94043-1351",
    "delivery_point_barcode": "940431351000",
```

**Comment by yschimke** [comment]
Can you enable logging e.g. HttpLoggingInterceptor with HEADERS and print out the request and response headers for a failing request?

**Comment by darkfrog26** [comment]
Strange, I think you might be right.  They claim they support HTTP/2 but it doesn't appear they actually are.  I'm sorry, I might be leading you guys on a wild goose chase here.  Let me do some more research and I'll create a new ticket if it points back to OkHttp.

Again, sorry for the inconvenience.
