### ISSUE TITLE
Guide to domain fronting

### ISSUE THREAD

**Issue by yschimke** [square/okhttp#4083]
https://en.wikipedia.org/wiki/Domain_fronting#cite_note-1
https://www.bamsoftware.com/papers/fronting/

Wondering where we stand on Domain Fronting with OkHttp.  Amazon and Google cut this off.  Some other providers require disabling SNI.  Should we document a working example to support this initiative?

**Comment by swankjesse** [comment]
I'd love that. I’m disappointed in Amazon & Google for breaking this. I wonder if Azure does it?

**Comment by swankjesse** [comment]
It looks like domain fronting is no longer a viable technique. Ugh.
https://signal.org/blog/looking-back-on-the-front/

No action for us to take here.

Ugh.
