### ISSUE TITLE
Analytics events are not emited when a response payload has no payload

### ISSUE THREAD

**Issue by bric3** [square/okhttp#4085]
I have identified an issue in the code of the event listener, I described the faulty behavior in this
https://github.com/square/okhttp/issues/270#issuecomment-371464079, since it is not related to the API introduced via #270, I'm creating a new issue as suggested by this comment https://github.com/square/okhttp/issues/270#issuecomment-397993363

Here's a verbatim of the mentioned comment :

> I was playing around this class to expose some metrics for prometheus, and I noticed that `callEnd` event was not sent for `DELETE` calls. In subsequent tests I found out this problem is occurring only when the response has no body e.g. for 204 statuses. I looked at the code and found out some commented tests, like this one 
> 
> https://github.com/square/okhttp/blob/d0418379a7c7a0c92781e4f5f75260d28a0b0145/okhttp-tests/src/test/java/okhttp3/EventListenerTest.java#L881-L899
> 
> I'm sure this is gonna be fixed in the next release(s) of okhttp. As a workaround, I think my only option at this is to place the metrics reporting in the `connectionReleased` event at this time. I don't think there's anything else, isn't it ?
> 
> _In my case I know there won't be multiple connections_

**Comment by swankjesse** [comment]
Can fix.

**Comment by amirlivneh** [comment]
This may have been fixed in https://github.com/square/okhttp/commit/30e72340e0c5a74feb347a79621b93d640ded576.
