### ISSUE TITLE
Deluxe Tags

### ISSUE THREAD

**Issue by bric3** [square/okhttp#4087]
As suggested by @yschimke in this https://github.com/square/okhttp/issues/270#issuecomment-399324485, I'm opening a new issue, regarding the analytics API to be able to handle _call_ contextual data. 

The idea of this issue is to have a way to give and access context per call / request. This is interesting for monitoring typically when the request is parameterized (via path params, etc.). Or to monitor certain kind of payload, e.g. separate metrics for the various grant type of an oauth endpoint.

----

Here's a verbatim of the comments in #270

* https://github.com/square/okhttp/issues/270#issuecomment-381157742

  > @swankjesse I would like to monitor request by their route as defined in Retrofit. However this appear to be difficult to capture this information in Retrofit, see square/retrofit#2732. For bootstrapping the idea I talked about using Request.tag to pass along this contextual route data, but I don't think this is wise regarding the tag usage documentation.
  > 
  > Do you think OkHttp could introduce another concept in that regard ?

* https://github.com/square/okhttp/issues/270#issuecomment-381291303

  > how are you planning to do the monitoring? For example, is it a timer? One thing you could do is add a synthetic request header that your "start" timer removes. There are probably other ways, too.

* https://github.com/square/okhttp/issues/270#issuecomment-381597941

  > @adriancole Actually I implemented an eventlistener that feeds prometheus collectors (gauge, summary, counters). Summary are the closest thing to timers if compared to micrometer. (But for reasons outside of this scope I'm using summary instead of histograms).
  > 
  > I considered this approach as well in retrofit, but since I cannot modify the request at the right moment / stage in retrofit I cannot capture the path of the retrofit annotation.

**Comment by adriancole** [comment]
interesting things here are that call is delay started.. so for example, lifecycle would be more foreground with a feature like this.. for example, can you add to the context before the call is executed, or can you only add before it is executed? Is the state immutable after a certain point? If a call is created and enqueued, but doesn't actually end in a network request, does that monkey wrench any assumptions?

Also, sometimes folks want property propagation (explicit context), and other times they want implicit context (like MDC hooks). Properties are much easier.

Just things for teasing out the design.

**Comment by bric3** [comment]
By the way I hacked thing on friday night. While this work I'm not satisfied by the overall design of my hack as it involves to tweak things at several places.

Regarding immutability in my hacky design, the object (`RequestMetadata`) set in the `tag` field is _mutable until read_.

As both retrofit and okhttp are tied in this here's a verbatim of the https://github.com/square/retrofit/issues/2732#issuecomment-399894314 I just posted.

----

@adriancole I took the time to play a bit with the call adapter factory and ok event listener. I have a solution that can capture annotations and store them in the request _tag_, these annotations can be read in the `EventListener`.

=> https://github.com/bric3/retrofit-okhttp-accounting/

What I don't like with this solution is that, this a quite hacky one

1. The Call wrapper is relying on the fact that calling `.request()` on the actual `call` before executing or enqueuing the call will return the request that will be used in this operations, it could be a copy for example, since the object is _almost immutable this is probably unlikely but given that _tag_ can be a mutable object I don't know if that is a lasting approach. 

2. The `tag` type is `Object` and has _self_ (the request itself) value by default; so the Call wrapper has to cast the `tag` to the needed type, and the value has to be set at the request creation time because a `Request` is immutable. Currently this is done in the `CallFactory`, where the request is modified with a builder then passed to ok http client. Design wise that's wrong, that's splitting concerns in different places. What if the `tag` has to be used for something else.

3. OkHttp `Request` builder documents the `tag` as way to cancel the request. I'm not sure how this is used, but using `tag` to achieve accounting or monitoring feels like a misappropriate use of the `tag`.

   > Attaches {@code tag} to the request. It can be used later to cancel the request. If the tag is unspecified or null, the request is canceled by using the request itself as the tag.

I think this would be very welcome improvement in both retrofit and okhttp to have this kind of feature.
I would like a simpler approach without having to rely on a `CallAdapterFactory` and a custom `CalFactory`

1. OkHttp' request could benefit from a field dedicated to contextual information.
2. Retrofit should have a request factory, or some kind of _request customizer_, or _request context customizer_, that could be leveraged with interface methods annotations like `@DELETE`.

**Comment by yschimke** [comment]
Tag javadocs lie: https://github.com/square/okhttp/issues/4039

**Comment by bric3** [comment]
@yschimke oh interesting. But still I find the `tag` api a bit awkward to use. And one concern is that it is not possible to have different concerns in the tag. Once the tag is set you cannot add a different _set_ of contextual data (symply because the actual type set in the tag maybe another type, set by something else). 

Retrofit call adapters could be leveraged to add various aspects like authentication, accounting, monitoring, etc.

**Comment by swankjesse** [comment]
Idea:
Promote the tag from an `Object` to a `Map<Class<T>, T>`.
```
ZipkinTag zipkinTag = request.tag(ZipkinTag.class);
Call<?> retrofitCall = request.tag(retrofit2.Call.class);
...
```

We’d be backwards-compatible by storing the current tag under `Object.class`. We could enhance Retrofit to attach its Call to the requests it creates, and possibly also to make Call expose more stuff.

Thoughts?

**Comment by bric3** [comment]
I think that's reasonable on the OkHttp side and quite easy to implement. 

Regarding retrofit, I would definitely like a way to access more stuff, especially methods annotation, maybe method name.

**Comment by swankjesse** [comment]
Yeah, we have that information but haven’t really had anywhere to expose it. Putting it on the Call is pretty straightforward.

Lets proceed to have typed tags in OkHttp. If anyone is picking this up I’d prefer to _not_ allocate a `LinkedHashMap` until we have multiple tags, since that case should be quite rare. Perhaps something like this:
```
class Request {
  ...
  private Class<?> onlyTagType; // Object.class, etc.
  private Object onlyTag;
  private Map<Class<?>, Object> tags; // null unless we have multiple tags
}
```
