### ISSUE TITLE
http request normal,but change https request is frequent occur SocketTimeoutException

### ISSUE THREAD

**Issue by richaelguitar** [square/okhttp#4093]
Hello, I was recently trying to change http to https, but the result wasn't so happier because of the frequent request timeouts after changing to https, which made me have a very bad user experience; my current solution is Use a thread pool to perform okhttp synchronization requests, which are normal for http requests. I want a solution, thank you!

###First step 

         Runable   task =  new Runable(){
           @Override
	     public void run() {
                   okhttp.execute()
               }
          };

###Second step

        ThreadPool.getInstance().exe(task);

###Final results
![v s f l meqa 3o5t_0rmy](https://user-images.githubusercontent.com/15651265/41842983-dd120f3c-789e-11e8-822a-7a606f42a040.png)

###After that

        I tried to repackage an okhttp tool. It's normal to use https requests in an asynchronous way, but I haven't found any SocketTimeoutException in the thread pool.

**Comment by yschimke** [comment]
Could you ask usage questions like this on stackoverflow please?

The issue tracker is for confirmed or suspected bugs/feature requests not for general usage questions.
