### ISSUE TITLE
Event "callEnd" not called if an Interceptor is added

### ISSUE THREAD

**Issue by dechanaud** [square/okhttp#4094]
Given the "Events" isn't finalized on version 3.10.0, I hesitated to report that issue as a bug.

Issue : Event "callEnd" isn't called if an Interceptor (Network or not) is added.

Steps to reproduce
- Instantiate an HttpClient with an EventListenerFactory (logging all events)
- Perform a dummy but successful GET request
- Check that all events are triggered, especially "callEnd"

- Instantiate an HttpClient with an EventListenerFactory (logging all events) & an interceptor such as HttpLoggingInterceptor
- Perform a dummy but successful GET request
- Check that all events except "callEnd" are triggered (not verified for callFailed)

**Comment by yschimke** [comment]
It's not any interceptor, seems like something that HttpLoggingInterceptor is doing

**Comment by yschimke** [comment]
I haven't dug in, just confirmed the bug with a test we can commit with a fix.

**Comment by dechanaud** [comment]
No problem ;) I went a bit further on my side.

If I disable the response logging, "callEnd" event is well triggered. It looks to be linked with the request.body() called within the intercept. I hope it helps you

**Comment by dechanaud** [comment]
I think I got it.

HttpLoggingInterceptor : line 241 : source.request(Long.MAX_VALUE) is the guilty point.
I don't get exactly the purpose of this operation...

**Comment by yschimke** [comment]
@dechanaud I think it tries to read until the end of the stream, so the clone is a full copy.

**Comment by dechanaud** [comment]
Indeed. Without this call, "chunked" response aren't logged as we didn't get the end of the stream

**Comment by dechanaud** [comment]
I just verified and it works fine with 3.11.0. Thanks guys ;)
