### ISSUE TITLE
possible verb tampering vulnerability in okhttp.

### ISSUE THREAD

**Issue by SonOfMa1ice** [square/okhttp#4098]
What kind of issue is this?
 - [x] Bug report. 
i was able to gain unauthorized access to a webcam powered by okhttp with verb tampering technique. screenshots kinda speak for themselves.
please just make sure the problem is not on your side.
![tamper1](https://user-images.githubusercontent.com/40563002/42061926-850a633c-7b34-11e8-9ff1-d46dc74a2e38.png)
![tamper2](https://user-images.githubusercontent.com/40563002/42061927-852d24e4-7b34-11e8-88b6-b271fb6f3ec9.png)

**Comment by JakeWharton** [comment]
It's not clear why you think this is a problem with OkHttp or why the webcam is "powered by" OkHttp. OkHttp is an HTTP client, not a server.

**Comment by SonOfMa1ice** [comment]
you're right, i'm not sure the problem is with okhttp, seems more like server misconfiguration. by the way, i just want to make sure that okhttp, which is used in this webcam is clear.
