### ISSUE TITLE
Kotlin module

### ISSUE THREAD

**Issue by yschimke** [square/okhttp#4102]
Would we provide a supported kotlin module in 3.11? Or wait for bigger changes down the road?

Useful methods

```
fun request(init: Request.Builder.() -> Unit = {}) = new Request.Builder().apply(init).build()
fun Request.edit(init: Request.Builder.() -> Unit = {}) = newBuilder().apply(init).build()
fun client(init: OkHttpClient.Builder.() -> Unit = {}) = new OkHttpClient.Builder().apply(init).build()
fun OkHttpClient.edit(init: OkHttpClient.Builder.() -> Unit = {}) = newBuilder().apply(init).build()
fun HttpUrl.edit(init: HttpUrl.Builder.() -> Unit = {}) = newBuilder().apply(init).build()
```

With Continuations support

```
suspend fun OkHttpClient.execute(request: Request): Response {
  val call = this.newCall(request)
  return call.await()
}

suspend fun Call.await(): Response {
  return kotlinx.coroutines.experimental.suspendCancellableCoroutine { c ->
    enqueue(object : Callback {
      override fun onFailure(call: Call, e: IOException) {
        c.resumeWithException(e)
      }

      override fun onResponse(call: Call, response: Response) {
        c.resume(response)
      }
    })
  }
}
```

Raising here even though I suspect the answer is no, but discussion and roadmap is useful and a closed issue might still be a useful pastebin.

**Comment by swankjesse** [comment]
Neat! edit is a nice idiom.

**Comment by swankjesse** [comment]
Lets do this in 3.12.

**Comment by rybalkinsd** [comment]
I'm working on providing kotlin dsl for both sync and async calls, @swankjesse

**Comment by yschimke** [comment]
@rybalkinsd awesome, be great to see your approach.

FWIW I extracted some of my existing code in this PR https://github.com/square/okhttp/pull/4129, but no imminent plans to land it.

**Comment by rybalkinsd** [comment]
@yschimke welcome [kohttp on github](https://github.com/rybalkinsd/kohttp)

**Comment by swankjesse** [comment]
Lets do this here:
https://github.com/square/okhttp/issues/4723
