### ISSUE TITLE
When default Proxy is set via ProxySelector.setDefault(), and if the proxy requires authentication, the default Authenticator is not used.

### ISSUE THREAD

**Issue by bsia** [square/okhttp#4108]
What kind of issue is this?

 - [X] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
       already exists! Don’t send pull requests to implement new features without first getting our
       support. Sometimes we leave features out on purpose to keep the project small.

I have an android app with multiple 3rd party library dependencies some of which use okhttp internally.  In my environment, I require an Http Proxy with Basic Auth to retrieve web resources.   However, some of the 3rd party libs don't allow configuration of a custom okhttp client.  And so, I try to setup a jvm-default proxy by using ProxySelector and Authenticator (java.net):

    public void setGlobalProxyAndAuthenticator() {
        ProxySelector proxySelector = new ProxySelector() {
            @Override
            public void connectFailed(URI uri, SocketAddress addr, IOException error) {
            }

            @Override
            public List<Proxy> select(URI uri) {
                List<Proxy> list = new ArrayList<Proxy>();
                Proxy proxy = new Proxy(Proxy.Type.HTTP, new InetSocketAddress("<proxy ip>",3128));
                list.add(proxy);
                return list;
            }
        };

        ProxySelector.setDefault(proxySelector);

        java.net.Authenticator authenticator = new java.net.Authenticator() {
            @Override
            public PasswordAuthentication getPasswordAuthentication() {
                return new PasswordAuthentication("user", "password".toCharArray());
            }
        };

        java.net.Authenticator.setDefault(authenticator);
    }

When I use an okhttp client, like so:

    public InputStream getData(final String url) throws IOException {
        Request request = new Request.Builder()
                .url(url)
                .build();

        OkHttpClient client = new OkHttpClient.Builder()
                .build();

        Response response = client.newCall(request).execute();
        return response.body().byteStream();
    }

I expect that the ProxySelector default will provide the proper proxy settings and that if proxy auth is required, the default authenticator will be used.

However, I only see the ProxySelector default being used.  Digging a little bit into [OkHttpClient Builder code](https://github.com/square/okhttp/blob/master/okhttp/src/main/java/okhttp3/OkHttpClient.java#L484), I can see that indeed the ProxySelector default is being retrieved and used to initialize the proxy:

        public Builder() {
            dispatcher = new Dispatcher();
            ...
            proxySelector = ProxySelector.getDefault();
            ...
            proxyAuthenticator = Authenticator.NONE;
            authenticator = Authenticator.NONE;
            ...

However, the proxyAuthenticator is just set to the no-op Authenticator (NONE).  (Incidentally, the standard http Authenticator is also set to NONE.  But this feature request is only for the proxy.).

It would be nice if OkHttpClient would be able to also pick up and use the JVM-default Authenticator.  (This likely requires adding an okhttp.Authenticator adapter that calls PasswordAuthentication.requestAuthentication() which will, in turn, call the registered java.net.Authenticator.) This will allow default proxy config for third-party libraries that also use okhttp within the app even for libs that do not have explicit interfaces for setting their internal okhttp client objects.

FYI, I also created a unit test for this:  https://gist.github.com/bsia/78d96c8aa06c9bb2bf0fe097b6a132a8

Thanks.

**Comment by swankjesse** [comment]
We used to do this and abandoned it because it's a static singleton, and these cannot be properly encapsulated for testing or modularity.

If you need this, you can create an Authenticator that delegates to the static singleton.

**Comment by bsia** [comment]
How about adding a custom OkHttp method to set a default okhttp3.Authenticator?

Below are the reasons why I want this:
  * It's tricky to configure the okhttp3.Authenticator for 3rd-party library dependencies in an app.  And in some cases, it's even impossible because some libraries don't even expose an api for configuring their internal okhttp clients.
  * In some network environments, where an end-user is required to use a proxy with auth, apps that use okhttp including all the 3rd party libs dependent on okhttp, will not work out of the box.

**Comment by sschuberth** [comment]
> We used to do this and abandoned it because it's a static singleton, and these cannot be properly encapsulated for testing or modularity.

But so is `ProxySelector.getDefault()`; what's the rationale for honoring the `ProxySelector.getDefault()` singleton but not the `Authenticator.getDefault()` singleton?

> If you need this, you can create an Authenticator that delegates to the static singleton.

Could we at least get a built-in method for that, similar to `Builder.proxySelector()`?

**Comment by swankjesse** [comment]
@sschuberth like so?
```
  OkHttpClient.Builder()
      .authenticator(Authenticator.JAVA_NET_AUTHENTICATOR)
      .build()
```

I think we could do that. Mind opening a new issue?

**Comment by sschuberth** [comment]
> Mind opening a new issue?

Done: https://github.com/square/okhttp/issues/5967.

**Comment by lyl-94** [comment]
> But so is ProxySelector.getDefault(); what's the rationale for honoring the ProxySelector.getDefault() singleton but not the Authenticator.getDefault() singleton?
That's what I want to say. When I develop a plugin in JetBrains IntelliJ IDE, the IDE supports proxy settings along with proxy credentials. The okhttp library reads the ProxySelector.getDefault() configured by the IDE itself but cannot read the Authenticator.getDefault(), which is also configured by the IDE. This causes the plugin to be unable to use the user proxy settings. It's weird too.

And why do I need a static configuration? Because different modules in the plugin use different OkHttpClient instances (with different settings), why not provide a static configuration?
