### ISSUE TITLE
Image downloads partially but the response and write to sink is successful

### ISSUE THREAD

**Issue by gopi1410** [square/okhttp#4111]
I use okhttp (android) to downloads images in my app. But sometimes the image downloads finishes with partial image but okhttp returns successful response, and successful write to sink using okio/buffered sink. The below image illustrates what I mean
![whatsapp image 2018-07-04 at 7 59 53 am](https://user-images.githubusercontent.com/831274/42256266-e471fbf4-7f6d-11e8-9e3a-d96774feae5b.jpeg)

I use the following piece of code to download an image and save to device:

```
Request request = new Request.Builder().url(url).tag(fileName).build();
final Call downloadCall = new OkHttpClient().newCall(request);
downloadCall.enqueue(new Callback() {
	public void onResponse(Call call, Response response) {
		if (downloadCall.isCanceled() || call.isCanceled())
			return;

		if (!response.isSuccessful()) {
			requestCallback.onFailure();
			return;
		}
		try {
			if (response.body() != null) {
				BufferedSink sink = Okio.buffer(Okio.sink(tempFile));
				sink.writeAll(response.body().source());
				sink.close();
				response.body().close();
				if (FileUtils.moveFile(tempFile, downloadedFile))
					requestCallback.onSuccess();
				else
					requestCallback.onFailure();
			} else {
				FileUtils.deleteFile(tempFile);
				requestCallback.onFailure();
			}
		} catch (Exception e) {
			FileUtils.deleteFile(tempFile);
			requestCallback.onFailure();
		}
	}

	public void onFailure(Call call, IOException e) {
		if (downloadCall.isCanceled() || call.isCanceled())
			return;
		FileUtils.deleteFile(downloadedFile);
		requestCallback.onFailure();
	}

});
```

(PS.: when I check the file in the local storage its the same as above, its not a rendering issue)
Am I doing something wrong? Or is it a HTTP client issue?

**Comment by yschimke** [comment]
This isn't a form that we can easily reproduce and fix as a bug.  I'd suggest posting to stackoverflow, including problematic image urls, and also logging header values (content-length) and the number of bytes written to the file etc.

**Comment by gopi1410** [comment]
@yschimke okay, will log content-length and number of bytes next time I face this (have faced this like once in ~50-60 downloads). Is there any specific header that I need to send from server?

**Comment by yschimke** [comment]
Please continue on stackoverflow, the issue tracker isn't a viable support forum for potential usage issues.
