### ISSUE TITLE
Request cancellation requires consuming remaining bytes for HTTP/2 connections

### ISSUE THREAD

**Issue by yschimke** [square/okhttp#4126]
To be filled in next week

> We're not reading the full response body in the test app (i'm just using exoplayer and the OKHttp extension for it).
> 
> I modified the test in question to stop discarding the bytes on cancel and it fails with the exact error we're seeing in our application:

Split off https://github.com/square/okhttp/issues/3915

cc @natez0r @dave-r12

**Comment by yschimke** [comment]
related test PR - https://github.com/square/okhttp/pull/4127

**Comment by veang544** [comment]
Support

**Comment by swankjesse** [comment]
I believe the fix shipped with 3.11.
