### ISSUE TITLE
Response response = interceptor.intercept(next) null crash

### ISSUE THREAD

**Issue by Andylove1314** [square/okhttp#4143]
// Confirm that the intercepted response isn't null.
    if (response == null) {
      throw new NullPointerException("interceptor " + interceptor + " returned null");
    }
if resonse is null，throw this.

How to do it？ thanks

**Comment by swankjesse** [comment]
Executable test case?

**Comment by Andylove1314** [comment]
@Override
    public Response intercept(Chain chain) throws IOException {
        Request request = chain.request();
        LLog.e("加速url", request.url().toString());
        Response rsp = null;
        try {
            rsp = chain.proceed(request);
        } catch (Exception e) {
        }
        int reqCount = 1;
        while (!(rsp != null && rsp.isSuccessful()) && reqCount > 0) {
            Request newRequest = request.newBuilder().url(getBackUpUrl()).build();
            LLog.e("备用url", newRequest.url().toString());
            try {
                rsp = chain.proceed(newRequest);
            } catch (Exception e) {
            }
            --reqCount;
        }
        return rsp;
    }

this is my code，when rsp is null crash，what is exactness，help me please！

**Comment by yschimke** [comment]
Please ask this sort of usage question on stackoverflow.  Without an executable test case, as compared to a code snippet you have provided, it's hard for us to know if we are fixing your problem.

FWIW I don't think you can call proceed on the chain multiple times.

**Comment by Andylove1314** [comment]
I‘m sorry，my business requirements change other host url when requestion is fail，so what mean current requestion is error？ thanks

**Comment by yschimke** [comment]
Please ask on stackoverflow, and post a link here.  This issue tracker is for reproducible errors or feature requests e.g. bugs.

**Comment by Andylove1314** [comment]
thank you ，brother
