### ISSUE TITLE
Okhttp2: response.body() can return null or response.body().string() can return null?

### ISSUE THREAD

**Issue by tuanbaros** [square/okhttp#4159]
I'm using Okhttp2 (ver 2.7.5). In ver 3.x, body() never return null, but in ver 2.x (2.7.5) the method can return null? I don't find document for method?

**Comment by yschimke** [comment]
Javadoc https://square.github.io/okhttp/2.x/okhttp/index.html?com/squareup/okhttp/RequestBody.html

Source code: 
https://github.com/square/okhttp/blob/okhttp_27/okhttp/src/main/java/com/squareup/okhttp/Response.java
https://github.com/square/okhttp/blob/okhttp_27/okhttp/src/main/java/com/squareup/okhttp/ResponseBody.java

response.body() can be null
response.body().string() cannot be null
