### ISSUE TITLE
NullPointerException   I try version 9,10,11

### ISSUE THREAD

**Issue by rizwanahmedtest** [square/okhttp#4163]
java.lang.NullPointerException: 
  at okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:157)
  at okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:121)
  at okhttp3.logging.HttpLoggingInterceptor.intercept (HttpLoggingInterceptor.java:144)
  at okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:147)
  at okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:121)
  at okhttp3.RealCall.getResponseWithInterceptorChain (RealCall.java:200)
  at okhttp3.RealCall$AsyncCall.execute (RealCall.java:147)
  at okhttp3.internal.NamedRunnable.run (NamedRunnable.java:32)
  at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1113)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:588)
  at java.lang.Thread.run (Thread.java:818)

**Comment by yschimke** [comment]
You have an interceptor returning null. Please continue any discussion in stackoverflow, or if you can provide a runnable reproducible test case showing the problem then post it here.

**Comment by rizwanahmedtest** [comment]
Yes cause is returning null. But why it not catchable? or how i can catch this null exception .Following try catch i am using right now

   Request request = requestBuilder.build();
                    ApplicationData.isTrue = false;
                    Response response = null;
                    try {
                        if (request != null)
                            response = chain.proceed(request);
                        Log.v("ROME parse error2 ", "unknown: 1");
                    } catch (NullPointerException exception) {
                        // Output unexpected IOExceptions.
                        Log.v("ROME parse error2 ", "unknown: 2" + exception.toString());
                    } catch (UnknownHostException exception) {
                        // Output expected UnknownHostExceptions.
                        Log.v("ROME parse error2 ", "unknown: 3" + exception.toString());
                    } catch (Error e2) {
                        Log.v("ROME parse error2 ", "unknown: 4" + e2.toString());
                    } catch (IOException e) {
                        e.printStackTrace();
                        Log.v("ROME parse error2 ", "unknown: 5" + e.toString());
                    }

                    return response;

**Comment by yschimke** [comment]
This isn't a reproducible issue, please post to stackoverflow for advice.

**Comment by rizwanahmedtest** [comment]
OK Thanks

**Comment by rizwanahmedtest** [comment]
07-22 13:31:16.508 17327-17608/ W/System.err: java.net.SocketTimeoutException: timeout
07-22 13:31:16.509 17327-17608/ W/System.err:     at okio.Okio$4.newTimeoutException(Okio.java:232)
            07-22 13:31:16.509 17327-17608/ W/System.err:     at okio.AsyncTimeout.exit(AsyncTimeout.java:275)
            07-22 13:31:16.509 17327-17608/ W/System.err:     at okio.AsyncTimeout$2.read(AsyncTimeout.java:243)
            07-22 13:31:16.510 17327-17608/ W/System.err:     at okio.RealBufferedSource.indexOf(RealBufferedSource.java:355)
            07-22 13:31:16.510 17327-17608/ W/System.err:     at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:227)
            07-22 13:31:16.510 17327-17608/ W/System.err:     at okhttp3.internal.http1.Http1Codec.readHeaderLine(Http1Codec.java:215)
            07-22 13:31:16.510 17327-17608/ W/System.err:     at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:189)
            07-22 13:31:16.510 17327-17608/ W/System.err:     at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:88)
            07-22 13:31:16.510 17327-17608/ W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
            07-22 13:31:16.510 17327-17608/ W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
            07-22 13:31:16.511 17327-17608/ W/System.err:     at .retrofit.RestClient$1.intercept(RestClient.java:74)
            07-22 13:31:16.511 17327-17608/ W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
            07-22 13:31:16.511 17327-17608/ W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
            07-22 13:31:16.511 17327-17608/ W/System.err:     at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:213)
            07-22 13:31:16.511 17327-17608/ W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
            07-22 13:31:16.511 17327-17608/ W/System.err:     at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
            07-22 13:31:16.511 17327-17608/ W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
            07-22 13:31:16.512 17327-17608/ W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
            07-22 13:31:16.512 17327-17608/ W/System.err:     at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
            07-22 13:31:16.512 17327-17608/ W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
            07-22 13:31:16.512 17327-17608/ W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
            07-22 13:31:16.512 17327-17608/ W/System.err:     at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
            07-22 13:31:16.512 17327-17608/ W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
            07-22 13:31:16.512 17327-17608/ W/System.err:     at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
            07-22 13:31:16.512 17327-17608/ W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
            07-22 13:31:16.513 17327-17608/ W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
            07-22 13:31:16.513 17327-17608/ W/System.err:     at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
            07-22 13:31:16.513 17327-17608/ W/System.err:     at okhttp3.RealCall$AsyncCall.execute(RealCall.java:147)
            07-22 13:31:16.514 17327-17608/ W/System.err:     at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
            07-22 13:31:16.514 17327-17608/ W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
            07-22 13:31:16.514 17327-17608/ W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
            07-22 13:31:16.514 17327-17608/ W/System.err:     at java.lang.Thread.run(Thread.java:764)

**Comment by rizwanahmedtest** [comment]
Fatal Exception: java.lang.NullPointerException: interceptor com.myapp.RestClient$1@56be3fa returned null
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:157)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
       at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:254)
       at okhttp3.RealCall$AsyncCall.execute(RealCall.java:200)
       at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)


here is my rest client class code
httpClient.addInterceptor(new Interceptor() {
                @Override
                @NonNull
                public okhttp3.Response intercept(@NonNull Chain chain) throws NullPointerException, IOException {
                    Request original = chain.request();
                    Request.Builder requestBuilder = original.newBuilder();

                    if (isheaderneedtoadd) {
                        String token ;
                        String bearer ;

                        if (isheader) {
                            token = "hide";
                            bearer = "hide";
                        }
                        requestBuilder.addHeader("Authorization", bearer + " " + token);
                    }
                    requestBuilder.addHeader("key", "123123123");
                    Request request = requestBuilder.build();
                    Response response = null;
                    try {
                        response = chain.proceed(request);
                    } catch (Error | IOException | NullPointerException e2) {
                        Log.v("ROME parse error2 ", "unknown: 2" + e2.toString());
                    }
                    return response;
                }
            });
