### ISSUE TITLE
same function on "com.squareup.okhttp: okhttp: 2.7.0"

### ISSUE THREAD

**Issue by fajaranugrah** [square/okhttp#4166]
is it the same function using "com.squareup.okhttp: okhttp: 2.7.0" with the current version? if different can give me the tutorial for update using the current version
thank you

**Comment by yschimke** [comment]
Please ask usage questions like this on stackoverflow.  The APIs are familiar enough that starting with existing code and changing imports will get you some way along.  Also if you use libraries like retrofit, then it's mostly changing a dependency.
