### ISSUE TITLE
FR/Proposal: Means to check if a connection is reused from a pool

### ISSUE THREAD

**Issue by hzsweers** [square/okhttp#4170]
In our fork, one of the things we added is an `isPooled()` API to `Connection` so that we could read if it was reused from the connectionpool (set in `StreamAllocation` right after `foundPooledConnection`, we read it for metrics in an interceptor).

We could do a PR with our implementation, but I'm not sure if `Connection` is intended to be a read-only API or if it'd be a breaking change to add this.

**Comment by yschimke** [comment]
You can derive this from events sent to an EventListener. Not sure if that suits your case.

**Comment by hzsweers** [comment]
Possibly! Could you share an example?

**Comment by yschimke** [comment]
Yeah - take a look at EventListenerTest.noDnsLookupOnPooledConnection.  I'm not suggesting it is perfect, but currently available in released versions.  

You might want to compare the dnsStart results with whether this is the first call to connectionAcquired with a particular connection.  As early on in startup simultaneous calls may all create http/2 connections before they are coalesced and duplicates closed.

I'm doubt adding this flag you suggested to Connection is likely to be accepted for a public API, so trying to give you some other options.

**Comment by yschimke** [comment]
assuming we wont make this public API, so workarounds are probably the best option for now
