### ISSUE TITLE
java.lang.NoClassDefFoundError: okhttp3.OkHttpClient$Builder

### ISSUE THREAD

**Issue by MrTaoGe** [square/okhttp#4171]
What kind of issue is this?

 - [x] Question. This issue tracker is not the place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use Stack
       Overflow. https://stackoverflow.com/questions/tagged/okhttp

 - [ ] Bug report. If you’ve found a bug, spend the time to write a failing test. Bugs with tests
       get fixed. Here’s an example: https://gist.github.com/swankjesse/981fcae102f513eb13ed

 - [ ] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
       already exists! Don’t send pull requests to implement new features without first getting our
       support. Sometimes we leave features out on purpose to keep the project small.

dear sir,
      i had suffered from the problem as above when i attampted to build a jar file that had included okhttp library in my gradle. The jar i wanted to  create was built successfully but the problem "java.lang.NoClassDefFoundError: okhttp3.OkHttpClient$Builder" was occured while i used my jar that had integrated the okhttp in a apk,so what was wrong in my whole process？

**Comment by yschimke** [comment]
Please post usage questions on sites like stackoverflow, as stated this is probably a general Android build problem and I don't think there is enough to go on to suggest this is a bug in OkHttp.
