### ISSUE TITLE
Add @Nullable annotation to Route parameter of Authenticator's authenticate() method for better Kotlin interop

### ISSUE THREAD

**Issue by mpeng3** [square/okhttp#4173]
I've run into an issue when implementing the Authenticator interface in Kotlin.  The `authenticate()` method takes two parameters, `Route` and `Response`, but does not provide any nullability information about these.

Implementing this method by default in Kotlin sets both Route and Response to be non-null.  However, at runtime, I have found it is possible for the `Route` parameter to be null.  This causes a NPE by the Kotlin Intrinsics checks at the entry point of the method.

Despite the note in the changelog for v3.10.0 which says "Fix: Never pass a null Route to Authenticator. There was a bug where routes were omitted for eagerly-closed connections.", the following line shows that it's still possible to end up with a null Route inside the Authenticate method:
https://github.com/square/okhttp/blob/80bb3b175b860890d29e33d90010bf727d16ccde/okhttp/src/main/java/okhttp3/internal/http/RetryAndFollowUpInterceptor.java#L285

I believe that some developer headaches can easily be resolved by including a @Nullable annotation on the `Route` parameter to the `authenticate()` method.

**Comment by swankjesse** [comment]
@mpeng3 could you write an executable test case to demonstrate the null route?

**Comment by jeffmaury** [comment]
I'm facing the same issue while migration openshift-restclient-java (https://github.com/openshift/openshift-restclient-java) from okhttp 3.3.9 to 3.11.0

**Comment by yschimke** [comment]
Fixed in master https://github.com/square/okhttp/pull/4257
