### ISSUE TITLE
Easier access to Response and in particular to ResponseBody.string()

### ISSUE THREAD

**Issue by aartiPl** [square/okhttp#4177]
We are using okHttps for microservices implementation. We send requests and get back simple responses from other services. In 100% of our use-cases and probably in the whole company in 95% of all use-cases, we receive short response bodies, which can be stored without any problems in memory.
From that perspective, currently, access to Response and in particular to ResponseBody is really uncomfortable. A response has to be closed and released, so I have to pass response in a lambda to some component which can handle automatically closing Response to avoid doing it in every function where a response is collected. Also, I found the behavior of ResponseBody.string() to be very strange. It returns value only first time, but then just empty string. But if the first time response body is loaded, then why not to cache it and return every time it is requested?

I think that it will be better to not require to close the whole response. It should be enough to close ResponseBody and moreover it can be done internally in the Response object. Getting the string() from ResponseBody should only throw a runtime exception, during unsuccessful dereference of the stream. In all other cases, it should just return the cached value of the response body. Handling of closing the stream should be done internally in Response object depending on usage scenario.

I would like to add that overall I really like the design: request (query) object --> processing --> response object. IMHO that's the correct way of doing that and that's why we are using okHttp instead of standard Spring functionality. The only missing point for me is what I have explained above.

**Comment by swankjesse** [comment]
We've modeled responses to be one-shot. We expect you to stream the response, decode it from JSON or another format, and use the result as a model object. Keeping the response body around looks like a memory leak to applications that don't use it.

I think what you probably want instead of a friendlier Response API is an entire abstraction on top of OkHttp like Retrofit. OkHttp wants to do the low level HTTP stuff only and generally favors efficiency over ergonomics when the two are in conflict.

**Comment by aartiPl** [comment]
I really appreciate the overall design. The only point which needs attention is the response object. Because of that, I don't want to go for anything more complex, especially not for high-level frameworks. 

Few important points supporting this view:
* immutability of most fields in Response doesn't matter if you have a single field which is not immutable. You can not consider Response as an immutable object
* you cannot pass Response up the stack e.g. in Exception
* probably about 95% of usages of Response in microservices is just reading the whole body to the memory
* handling of exceptions when reading the body of the response complicates significantly logic behind the processing of the response.

I think it is reasonable for a client to decide which response it wants to get as a result: value-based or stream based. So one possible way to go is to create different modes to get a response and allow the client to decide which one is desirable.

In our microservice, we have to wrap okHttp response into our own response object, which has already resolved stringBody. That way we can pass Response to many functions which can process a body without worrying that in some point it is null. 

But this solution is still far from good:
* we are using okHttp.Request as it is, but we are returning our own Response object. Not very nice
* I would like to keep the structure of the okHttp.Response in the most part - it has nice builders. But reimplementing it in our own object is a significant effort.

I hope I explained my use-case at least a bit. If you need more information, do not hesitate to ask.

**Comment by swankjesse** [comment]
If you want, create a class like InMemoryResponseBody that can be constructed from another ResponseBody.

Then use an application interceptor to replace the streaming one with the in-memory one.

**Comment by swankjesse** [comment]
No action to take here.
