### ISSUE TITLE
TLS-PSK Support

### ISSUE THREAD

**Issue by mateusz-** [square/okhttp#4178]
I would like to use TLS-PSK with okhttp.

The sslSocketFactory method of OkHttpClient takes an instance of X509TrustManager. In this case, there is no certificate, so the X509TrustManager is not necessary.

If a dummy X509TrustManager implementation is created, connectTls method of RealConnection throws an exception when trying to obtain a peer certificate from the handshake.

**Comment by swankjesse** [comment]
Yeah that's something we can't handle. Can fix though.

If you want to help us along, could you provide an executable test case that does pre-shared keys? We'll need to set that up in MockWebServer & haven't done so before.

**Comment by swankjesse** [comment]
Also – should test both TLSv1.3 and TLSv1.2 ’cause things changed in 1.3.

**Comment by yschimke** [comment]
This is working now

**Comment by satur9nine** [comment]
Are there any examples/docs that explain setting up TLS PSK with OkHttp?
What versions of OkHttp won't work and which version was this fixed in?

**Comment by satur9nine** [comment]
Looks like this was  broken in 3.13.0 and then fixed in 3.13.1 by this particular commit: https://github.com/square/okhttp/commit/ad8d8099a5e475475ddce44cde1b5e1d360990c4
