### ISSUE TITLE
Fatal Exception: java.lang.StackOverflowError

### ISSUE THREAD

**Issue by jnrahul** [square/okhttp#4179]
Getting this issue in AuthenticationIntercepter

okhttp3.CipherSuite$1.compare (CipherSuite.java:43)
okhttp3.internal.Util.intersect (Util.java:220)
okhttp3.ConnectionSpec.supportedSpec (ConnectionSpec.java:136)
okhttp3.ConnectionSpec.apply (ConnectionSpec.java:120)
okhttp3.OkHttpClient$1.apply (OkHttpClient.java:181)
okhttp3.internal.connection.ConnectionSpecSelector.configureSecureSocket (ConnectionSpecSelector.java:78)
okhttp3.internal.connection.RealConnection.connectTls (RealConnection.java:295)
okhttp3.internal.connection.RealConnection.establishProtocol (RealConnection.java:270)
okhttp3.internal.connection.RealConnection.connect (RealConnection.java:162)
okhttp3.internal.connection.StreamAllocation.findConnection (StreamAllocation.java:257)
okhttp3.internal.connection.StreamAllocation.findHealthyConnection (StreamAllocation.java:135)
okhttp3.internal.connection.StreamAllocation.newStream (StreamAllocation.java:114)
okhttp3.internal.connection.ConnectInterceptor.intercept (ConnectInterceptor.java:42)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:147)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:121)
okhttp3.internal.cache.CacheInterceptor.intercept (CacheInterceptor.java:93)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:147)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:121)
okhttp3.internal.http.BridgeInterceptor.intercept (BridgeInterceptor.java:93)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:147)
okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept (RetryAndFollowUpInterceptor.java:126)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:147)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:121)
com.practicemock.practicemock.domain.AuthenticationInterceptor.intercept (AuthenticationInterceptor.java:25)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:147)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:121)
com.practicemock.practicemock.domain.AuthenticationInterceptor.intercept (AuthenticationInterceptor.java:25)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:147)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:121)
com.practicemock.practicemock.domain.AuthenticationInterceptor.intercept (AuthenticationInterceptor.java:25)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:147)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:121)
com.practicemock.practicemock.domain.AuthenticationInterceptor.intercept (AuthenticationInterceptor.java:25)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:147)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:121)
com.practicemock.practicemock.domain.AuthenticationInterceptor.intercept (AuthenticationInterceptor.java:25)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:147)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:121)
com.practicemock.practicemock.domain.AuthenticationInterceptor.intercept (AuthenticationInterceptor.java:25)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:147)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:121)
com.practicemock.practicemock.domain.AuthenticationInterceptor.intercept (AuthenticationInterceptor.java:25)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:147)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:121)

**Comment by swankjesse** [comment]
Typically this happens when you add an interceptor many many times. Looks like you're doing that with `com.practicemock.practicemock.domain.AuthenticationInterceptor`.
