### ISSUE TITLE
setconnectTimeout will influence realwebsocket open time

### ISSUE THREAD

**Issue by huangliqiang** [square/okhttp#4186]
i use compile 'com.squareup.okhttp3:okhttp:3.9.0'

i use okhttp's newWebSocket, when i set OkHttpClient.connectTimeout(8, TimeUnit.SECONDS), this websocket openSuccess time will be affected. if i set connecttimeout 8 seconds, the websocket need use 8 seconds to opensuccess. also if i set 15 seconds, need use 15 seconds to open websocket.  This problem appears in the 4G network。

**Comment by swankjesse** [comment]
Is it timing out and retrying? Do all of the IP addresses for this host work?

**Comment by huangliqiang** [comment]
@swankjesse Each time the client is created then connet this wss, not timingout and retrying. all ip addresses has problem. if my phone use wifi , It's going to work well

**Comment by swankjesse** [comment]
Executable test case?

**Comment by swankjesse** [comment]
Unclear what action to take on this.
