### ISSUE TITLE
Multiple 1xx responses not handled properly

### ISSUE THREAD

**Issue by guillerodriguez** [square/okhttp#4188]
Hi,

Issue #1337 fixed the cases where OkHttp receives an unexpected 1xx response from the server. However this only works if the server sends a single 1xx unexpected response. Any additional unexpected 1xx responses are not handled properly. According to [RFC 7231](https://tools.ietf.org/html/rfc7231#section-6.2), clients should be able to cope with this:

> A client MUST be able to parse one or more 1xx responses received
prior to a final response, even if the client does not expect one. A
user agent MAY ignore unexpected 1xx responses.

**Comment by yschimke** [comment]
Should be fixed in https://github.com/square/okhttp/pull/7629/files
