### ISSUE TITLE
java.lang.NullPointerException(RetryAndFollowUpInterceptor.java:282)

### ISSUE THREAD

**Issue by easytome** [square/okhttp#4191]
java.lang.NullPointerException

Attempt to invoke virtual method 'java.net.Proxy$Type java.net.Proxy.type()' on a null object reference

1 okhttp3.internal.http.RetryAndFollowUpInterceptor.followUpRequest(RetryAndFollowUpInterceptor.java:282)
2 okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:158)
3 okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
4 okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
5 okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
6 okhttp3.RealCall$AsyncCall.execute(RealCall.java:147)
7 okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
8 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
9 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
10 java.lang.Thread.run(Thread.java:764)

**Comment by sjwoodard** [comment]
I'm seeing this error too when registering a ProxySelector (e.g. `builder.proxySelector(myProxySelector);`). Registering a single proxy works fine.

**Comment by yschimke** [comment]
dupe

**Comment by easytome** [comment]
I'm not with you. Tell me what you mean.

**Comment by sjwoodard** [comment]
@easytome there's another issue already opened for this, see #3995
