### ISSUE TITLE
Interceptor access to WebSocket Connection

### ISSUE THREAD

**Issue by sduslum** [square/okhttp#4192]
Feature Request :
when use web socket, I want to get dns ip result which tcp connect success

**Comment by swankjesse** [comment]
This kind of thing is available on the connection in an interceptor for regular calls, but not for web sockets.

**Comment by flocsy** [comment]
+1

Or at least make it possible to set http headers on the request that opens the socket

**Comment by amitav13** [comment]
Would love this as well - trying to make a `HttpLoggingInterceptor` equivalent seems impossible at this point.

**Comment by widarlein** [comment]
Yes, pleaaase. I would love this for logging

**Comment by apkelly** [comment]
Did this ever get released, I'm looking to log my websocket traffic in a similar fashion to my http traffic.

**Comment by yschimke** [comment]
BTW Interceptor and Logger are probably two different features.  I suspect we should implement Logger first.

**Comment by Nokuap** [comment]
Yeah, would be nice to have some kind of logging

**Comment by yschimke** [comment]
Related issue https://github.com/square/okhttp/issues/5833

**Comment by testifyqa** [comment]
This would be great to have +1

**Comment by tao1** [comment]
+1

**Comment by Freshman111** [comment]
+1

**Comment by yschimke** [comment]
Closing as low priority. Not implemented after almost 5 years.
