### ISSUE TITLE
about SocketTimeoutException

### ISSUE THREAD

**Issue by Caij** [square/okhttp#4193]
version : 3.11.0

protocol: http 2.0

occasionally hava SocketTimeoutException, I can be sure that the network and server and glide are ok. When this abnormal problem occurs, retrying the resource requesting the same domain name will definitely cause a SocketTimeoutException, and it will take a while to disappear. But I don't know the triggering steps.  
i use glide with okhttp, and image down with okhttp.  Is it a problem caused by cancel? 

sorry ，I'm not good at English

okhttp3.internal.http2.Http2Stream$StreamTimeout.newTimeoutException(Http2Stream.java:616)
okhttp3.internal.http2.Http2Stream$StreamTimeout.exitAndThrowIfTimedOut(Http2Stream.java:624)
okhttp3.internal.http2.Http2Stream.takeResponseHeaders(Http2Stream.java:146)
okhttp3.internal.http2.Http2Codec.readResponseHeaders(Http2Codec.java:127)
okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:88)
okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
com.caij.emore.Singletons$1.intercept(Singletons.java:94)
okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
okhttp3.RealCall.execute(RealCall.java:77)

**Comment by ahulyk** [comment]
look like duplicate  [#3146](https://github.com/square/okhttp/issues/3146)

**Comment by Caij** [comment]
@ahulyk  thanks 
now, I solve this problem by using only http 1.1

**Comment by yschimke** [comment]
Closing as duplicate
