### ISSUE TITLE
why IOException occurs in server point when client stops?

### ISSUE THREAD

**Issue by xiongshiyan** [square/okhttp#4194]
IOException occurs in server point when client stops. the Exception is IOException （**The remote host forced the closure of an existing connection**）[远程主机强迫关闭了一个现有的连接], and I use the normal testing code. the code is undering:
```
OkHttpClient client = new OkHttpClient();

  String post(String url, String json) throws IOException {
    RequestBody body = RequestBody.create(JSON, json);
    Request request = new Request.Builder()
        .url(url)
        .post(body)
        .build();
    try (Response response = client.newCall(request).execute()) {
      return response.body().string();
    }
  }

**Comment by xiongshiyan** [comment]
![image](https://user-images.githubusercontent.com/39974039/43765451-8cb4be78-9a62-11e8-9bff-5a8b53d7894b.png)

**Comment by swankjesse** [comment]
Unclear what action we should take on this. Could you provide an executable test case that demonstrates the problem?
