### ISSUE TITLE
Server close fails

### ISSUE THREAD

**Issue by DanielYWoo** [square/okhttp#4195]
If you set the server HTTP keepalive to 10 seconds or so, when the server closes the connection with a FIN ACK, the client often *forgets* the TCP connection has been closed and try to close the connection again from the client side.

Below is an example
![untitled](https://user-images.githubusercontent.com/514417/43818464-6b96259c-9b11-11e8-8c5c-0dd043765bbb.png)

Version: 3.6.0

**Comment by dalu9527** [comment]
I have the same problem, the closed is not callback

**Comment by noear** [comment]
我也有这个问题。。。服务器的tcp数特别高。。。如何解决啊？

**Comment by DanielYWoo** [comment]
only in 3.6.x, seems fixed.

**Comment by swankjesse** [comment]
No actino to take here.
