### ISSUE TITLE
SSLProtocolException and unexpected end of stream on Connection

### ISSUE THREAD

**Issue by linguokun1** [square/okhttp#4196]
There is very low probability to produce "HTTP FAILED: javax.net.ssl.SSLProtocolException: Read error: ssl=0xdfa6e140: Failure in SSL library, usually a protocol error
error:100000d7:SSL routines:OPENSSL_internal:SSL_HANDSHAKE_FAILURE (external/boringssl/src/ssl/ssl_lib.c:710 0xe57a3144:0x00000000)" and "unexpected end of stream on Connection{xmart.xiaopeng.com:443, proxy=DIRECT hostAddress=xmart.xiaopeng.com/118.31.212.217:443 cipherSuite=TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256 protocol=http/1.1}".

**Comment by linguokun1** [comment]
this two exception will happen in the same time

**Comment by linguokun1** [comment]
[D][2018-08-08 +8.0 14:28:12.569][25178, 1486][OKHttp][, , 0][[ threadId=1633,RxCachedThreadScheduler-5,at TbsSdkJava:47]--> POST https://xmart.xiaopeng.com/biz/v4/message/category http/1.1
[D][2018-08-08 +8.0 14:28:12.570][25178, 1486][OKHttp][, , 0][[ threadId=1633,RxCachedThreadScheduler-5,at TbsSdkJava:47]
[D][2018-08-08 +8.0 14:28:12.570][25178, 1486][OKHttp][, , 0][[ threadId=1633,RxCachedThreadScheduler-5,at TbsSdkJava:47]--> END POST (2-byte body)
[D][2018-08-08 +8.0 14:28:12.574][25178, 1486][OKHttp][, , 0][[ threadId=1484,RxCachedThreadScheduler-1,at TbsSdkJava:47]--> POST https://appdata.xiaopeng.com/app/reportData?di=88ebcab9c99b60f336e9c376aa3c5675&pn=com.xiaopeng.mycarinfo&ve=1.6.0&br=VTR&mo=VTR-AL00&st=1&sv=8.0.0&nt=4G&t=1533709689673&gp= http/1.1
[D][2018-08-08 +8.0 14:28:12.577][25178, 1486][OKHttp][, , 0][[ threadId=1536,RxCachedThreadScheduler-3,at TbsSdkJava:47]--> POST https://xmart.xiaopeng.com/resource/app/v1/userinfo http/1.1
[D][2018-08-08 +8.0 14:28:12.577][25178, 1486][OKHttp][, , 0][[ threadId=1484,RxCachedThreadScheduler-1,at TbsSdkJava:47]
[D][2018-08-08 +8.0 14:28:12.578][25178, 1486][OKHttp][, , 0][[ threadId=1536,RxCachedThreadScheduler-3,at TbsSdkJava:47]
[D][2018-08-08 +8.0 14:28:12.579][25178, 1486][OKHttp][, , 0][[ threadId=1484,RxCachedThreadScheduler-1,at TbsSdkJava:47]--> END POST (368-byte body)
[D][2018-08-08 +8.0 14:28:12.579][25178, 1486][OKHttp][, , 0][[ threadId=1536,RxCachedThreadScheduler-3,at TbsSdkJava:47]--> END POST (2-byte body)
[D][2018-08-08 +8.0 14:28:12.586][25178, 1486][OKHttp][, , 0][[ threadId=1537,RxCachedThreadScheduler-4,at TbsSdkJava:47]--> GET https://xmart.xiaopeng.com/config/v2/config http/1.1
[D][2018-08-08 +8.0 14:28:12.587][25178, 1486][OKHttp][, , 0][[ threadId=1537,RxCachedThreadScheduler-4,at TbsSdkJava:47]--> END GET
[D][2018-08-08 +8.0 14:28:12.707][25178, 1486][OKHttp][, , 0][[ threadId=1651,RxCachedThreadScheduler-6,at TbsSdkJava:47]--> POST https://xmart.xiaopeng.com/biz/v4/vehicle/myVehicles http/1.1
[D][2018-08-08 +8.0 14:28:12.707][25178, 1486][OKHttp][, , 0][[ threadId=1651,RxCachedThreadScheduler-6,at TbsSdkJava:47]
[D][2018-08-08 +8.0 14:28:12.707][25178, 1486][OKHttp][, , 0][[ threadId=1651,RxCachedThreadScheduler-6,at TbsSdkJava:47]--> END POST (2-byte body)
[D][2018-08-08 +8.0 14:28:16.277][25178, 1486][OKHttp][, , 0][[ threadId=1484,RxCachedThreadScheduler-1,at TbsSdkJava:47]<-- HTTP FAILED: javax.net.ssl.SSLProtocolException: Read error: ssl=0xdfa6e140: Failure in SSL library, usually a protocol error
error:100000d7:SSL routines:OPENSSL_internal:SSL_HANDSHAKE_FAILURE (external/boringssl/src/ssl/ssl_lib.c:710 0xe57a3144:0x00000000)
[D][2018-08-08 +8.0 14:28:16.278][25178, 1486][OKHttp][, , 0][[ threadId=1633,RxCachedThreadScheduler-5,at TbsSdkJava:47]<-- HTTP FAILED: javax.net.ssl.SSLProtocolException: Read error: ssl=0xc4835c40: Failure in SSL library, usually a protocol error
error:100000d7:SSL routines:OPENSSL_internal:SSL_HANDSHAKE_FAILURE (external/boringssl/src/ssl/ssl_lib.c:710 0xe57a3144:0x00000000)
[D][2018-08-08 +8.0 14:28:16.286][25178, 1486][ApiHelper][, , 0][[ threadId=1633,RxCachedThreadScheduler-5,at TbsSdkJava:78]throwable Exception == SSLProtocolException
[D][2018-08-08 +8.0 14:28:16.289][25178, 1486][okhttp][, , 0][[ threadId=1,main,at TbsSdkJava:152]e.getMessage() == Read error: ssl=0xc4835c40: Failure in SSL library, usually a protocol error
error:100000d7:SSL routines:OPENSSL_internal:SSL_HANDSHAKE_FAILURE (external/boringssl/src/ssl/ssl_lib.c:710 0xe57a3144:0x00000000)
[D][2018-08-08 +8.0 14:28:16.291][25178, 1486][OKHttp][, , 0][[ threadId=1536,RxCachedThreadScheduler-3,at TbsSdkJava:47]<-- HTTP FAILED: javax.net.ssl.SSLProtocolException: Read error: ssl=0xce17af00: Failure in SSL library, usually a protocol error
error:100000d7:SSL routines:OPENSSL_internal:SSL_HANDSHAKE_FAILURE (external/boringssl/src/ssl/ssl_lib.c:710 0xe57a3144:0x00000000)
[D][2018-08-08 +8.0 14:28:16.291][25178, 1486][okhttp][, , 0][[ threadId=1,main,at TbsSdkJava:153]e.getMessage() != TokenInvalidException
[D][2018-08-08 +8.0 14:28:16.296][25178, 1486][ApiHelper][, , 0][[ threadId=1536,RxCachedThreadScheduler-3,at TbsSdkJava:78]throwable Exception == SSLProtocolException
[D][2018-08-08 +8.0 14:28:16.303][25178, 1486][okhttp][, , 0][[ threadId=1,main,at TbsSdkJava:152]e.getMessage() == Read error: ssl=0xce17af00: Failure in SSL library, usually a protocol error
error:100000d7:SSL routines:OPENSSL_internal:SSL_HANDSHAKE_FAILURE (external/boringssl/src/ssl/ssl_lib.c:710 0xe57a3144:0x00000000)
[D][2018-08-08 +8.0 14:28:16.305][25178, 1486][okhttp][, , 0][[ threadId=1,main,at TbsSdkJava:153]e.getMessage() != TokenInvalidException
[D][2018-08-08 +8.0 14:28:16.309][25178, 1486][OKHttp][, , 0][[ threadId=1537,RxCachedThreadScheduler-4,at TbsSdkJava:47]<-- HTTP FAILED: javax.net.ssl.SSLProtocolException: Read error: ssl=0xdd232300: Failure in SSL library, usually a protocol error
error:100000d7:SSL routines:OPENSSL_internal:SSL_HANDSHAKE_FAILURE (external/boringssl/src/ssl/ssl_lib.c:710 0xe57a3144:0x00000000)
[D][2018-08-08 +8.0 14:28:16.311][25178, 1486][xiaopeng][, , 0][[ threadId=1,main,at TbsSdkJava:59]okhttp   code === -1
[D][2018-08-08 +8.0 14:28:16.336][25178, 1486][OKHttp][, , 0][[ threadId=1651,RxCachedThreadScheduler-6,at TbsSdkJava:47]<-- HTTP FAILED: java.io.IOException: unexpected end of stream on Connection{xmart.xiaopeng.com:443, proxy=DIRECT hostAddress=xmart.xiaopeng.com/118.31.212.217:443 cipherSuite=TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256 protocol=http/1.1}
[D][2018-08-08 +8.0 14:28:16.339][25178, 1486][ApiHelper][, , 0][[ threadId=1651,RxCachedThreadScheduler-6,at TbsSdkJava:78]throwable Exception == IOException
[D][2018-08-08 +8.0 14:28:16.436][25178, 1486][okhttp][, , 0][[ threadId=1,main,at TbsSdkJava:152]e.getMessage() == unexpected end of stream on Connection{xmart.xiaopeng.com:443, proxy=DIRECT hostAddress=xmart.xiaopeng.com/118.31.212.217:443 cipherSuite=TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256 protocol=http/1.1}
[D][2018-08-08 +8.0 14:28:16.437][25178, 1486][okhttp][, , 0][[ threadId=1,main,at TbsSdkJava:153]e.getMessage() != TokenInvalidException
[D][2018-08-08 +8.0 14:28:16.438][25178, 1486][CarId][, , 0][[ threadId=1,main,at TbsSdkJava:61]_onError
[D][2018-08-08 +8.0 14:28:16.439][25178, 1486][xiaopeng][, , 0][[ threadId=1,main,at TbsSdkJava:59]okhttp   code === -1
[D][2018-08-08 +8.0 14:28:16.956][25178, 1486][ApiHelper][, , 0][[ threadId=1535,RxCachedThreadScheduler-2,at TbsSdkJava:78]throwable Exception == SSLHandshakeException
[D][2018-08-08 +8.0 14:28:16.970][25178, 1486][okhttp][, , 0][[ threadId=1,main,at TbsSdkJava:152]e.getMessage() == Connection closed by peer

**Comment by linguokun1** [comment]
I see the source code.
I find ConnectionSpecSelector class in the OKHttp.

// On Android, SSLProtocolExceptions can be caused by TLS_FALLBACK_SCSV failures, which means we retry those when we probably should not.
    
return (e instanceof SSLHandshakeException || e instanceof SSLProtocolException);"

**Comment by linguokun1** [comment]
So I remember that I add the code for compatible the 4.4 as below:
public static List<ConnectionSpec> getConnectionSpecs() {
//        LogUtils.d("ServerUtil","getConnectionSpecs 1");
        ConnectionSpec cs = new ConnectionSpec.Builder(ConnectionSpec.MODERN_TLS)
                .tlsVersions(TlsVersion.TLS_1_2)
                .cipherSuites(
                        CipherSuite.TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,
                        CipherSuite.TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,
                        CipherSuite.TLS_DHE_RSA_WITH_AES_128_GCM_SHA256,
                        CipherSuite.TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA,
                        CipherSuite.TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA,
                        CipherSuite.TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA,
                        CipherSuite.TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA,
                        CipherSuite.TLS_ECDHE_ECDSA_WITH_RC4_128_SHA,
                        CipherSuite.TLS_ECDHE_RSA_WITH_RC4_128_SHA,
                        CipherSuite.TLS_DHE_RSA_WITH_AES_128_CBC_SHA,
                        CipherSuite.TLS_DHE_DSS_WITH_AES_128_CBC_SHA,
                        CipherSuite.TLS_DHE_RSA_WITH_AES_256_CBC_SHA
                .build();

        List<ConnectionSpec> specs = Lists.newArrayList();//new ArrayList<>();
        specs.add(cs);
        specs.add(ConnectionSpec.COMPATIBLE_TLS);
        specs.add(ConnectionSpec.CLEARTEXT);

        return specs;
    }

**Comment by linguokun1** [comment]
Now I add "CipherSuite.TLS_FALLBACK_SCSV".
As below, I don't know if it can work. share previously.

OkHttpClient.Builder builder = new OkHttpClient.Builder()
                .retryOnConnectionFailure(true)
                .connectTimeout(20, TimeUnit.SECONDS)
                .readTimeout(20, TimeUnit.SECONDS)
                .connectionSpecs(ServerUtil.getConnectionSpecs())
                .hostnameVerifier(new XpHostnameVerifier(adapter.getTrustHosts()))
                .addNetworkInterceptor(new XpSignRequestInterceptor(adapter, secret));

public static List<ConnectionSpec> getConnectionSpecs() {
//        LogUtils.d("ServerUtil","getConnectionSpecs 1");
        ConnectionSpec cs = new ConnectionSpec.Builder(ConnectionSpec.MODERN_TLS)
                .tlsVersions(TlsVersion.TLS_1_2)
                .cipherSuites(
                        CipherSuite.TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,
                        CipherSuite.TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,
                        CipherSuite.TLS_DHE_RSA_WITH_AES_128_GCM_SHA256,
                        CipherSuite.TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA,
                        CipherSuite.TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA,
                        CipherSuite.TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA,
                        CipherSuite.TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA,
                        CipherSuite.TLS_ECDHE_ECDSA_WITH_RC4_128_SHA,
                        CipherSuite.TLS_ECDHE_RSA_WITH_RC4_128_SHA,
                        CipherSuite.TLS_DHE_RSA_WITH_AES_128_CBC_SHA,
                        CipherSuite.TLS_DHE_DSS_WITH_AES_128_CBC_SHA,
                        CipherSuite.TLS_DHE_RSA_WITH_AES_256_CBC_SHA,
                        CipherSuite.TLS_FALLBACK_SCSV)
                .build();

        List<ConnectionSpec> specs = Lists.newArrayList();//new ArrayList<>();
        specs.add(cs);
        specs.add(ConnectionSpec.COMPATIBLE_TLS);
        specs.add(ConnectionSpec.CLEARTEXT);

        return specs;
    }

**Comment by linguokun1** [comment]
Android will throw this error  but ios not

**Comment by yschimke** [comment]
Do you expect https://xmart.xiaopeng.com to work without additional certificates? it fails for me with curl and JDK okhttp requests with similar errors.

**Comment by linguokun1** [comment]
Hello @yschimke 
Our company certificate is at the android assets folder and will validate by this certificate with server's.
So How can I avoid this similar exception? These SSLProtocolException will happen at  very low probability.(not 100% happen)

**Comment by linguokun1** [comment]
Hi @yschimke 
Do you know what cause this problem?

**Comment by yschimke** [comment]
My own testing gives a handshake failure as I don't have valid certificates for the server.  But using insecure mode it works ok.  So I suggest asking on stackoverflow instead.

**Comment by linguokun1** [comment]
@yschimke 
yes I know using insecure mode it works ok. When I using insecure mode , it's ok too.
I will put this question on stackoverflow, but I hope okhttp team should add the secure mode testing program. beacuse it seems to not only one people encounter ssl exception

**Comment by yschimke** [comment]
@linguokun1 you can just run a simple main program with -Djavax.net.debug=ssl,handshake if you want that.  But it isn't a OkHttp specific problem, it fails with Chrome and vanilla JDK should report the same.

FWIW I have a test client, but that's all it is showing also

```
$ okurl --ssldebug https://xmart.xiaopeng.com
```

**Comment by linguokun1** [comment]
@yschimke I found sometimes also get sslexception connection close by peer

**Comment by linguokun1** [comment]
@yschimke  and the title exception will high possible occur when i erupt simultaneously

**Comment by veang544** [comment]
Support

**Comment by swankjesse** [comment]
No clear action to take here.
