### ISSUE TITLE
How to add error body to MockResponse?

### ISSUE THREAD

**Issue by jushlwest** [square/okhttp#4197]
`      MockResponse mockedResponse = new MockResponse();
        mockedResponse.setResponseCode(404);
        mockedResponse.setBody(JsonHelper.getJson(JsonHelper.ERROR_404_NOT_FOUND_BODY));`
But 404 is ignored and body json parsed as normal response. I need check error response body not normal body. How to do this?

**Comment by JakeWharton** [comment]
There is only one body in an HTTP response. Whether it's a "normal" body or an "error" body relies on the client's interpretation of the HTTP status code. Can you show more code that indicates more of the problem?

**Comment by jushlwest** [comment]
I have specific error body(json) on the server. So I would like simulate that response with MockWebServer.

My code:

```
 public void testErrorReponse() throws Exception {

        MockResponse mockedResponse = new MockResponse();
        mockedResponse.setResponseCode(404);
        mockedResponse.setBody(<json file>);
        mockServer.enqueue(mockedResponse);

        TestSubscriber<List<EntityResponse>> subscriber = new TestSubscriber<>();

        apiManager
                .getMyDataFromRest()
                .subscribe(subscriber);
        subscriber.awaitTerminalEvent(2, TimeUnit.SECONDS);

        subscriber.assertError(new Predicate<Throwable>() {
            @Override
            public boolean test(Throwable throwable) throws Exception {

                if(throwable instanceof AppError) {
                    AppError appError = (AppError) throwable;

                    if(appError.getType() == AppErrorType.SERVER_NORMAL_ERROR
                            && appError.getMessageForUser() != null
                            && !appError.getMessageForUser().isEmpty()){
                        return true;
                    }
                }

                return false;
            }
        });
    }
```

apiManager it is wrapper for retrofit api cotract, and here I have onErrorResumeNext() to parse error response and wrap it to my own throwable - AppError.

But I received `java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING` and it looks like status 404 is ignored by MockWebServer when I add body

**Comment by JakeWharton** [comment]
Retrofit itself has a test which is very similar to that: https://github.com/square/retrofit/blob/4a048cc03f5a851b64d9726098df49b5fa4130c6/retrofit/src/test/java/retrofit2/CallTest.java#L106-L119. What's the stacktrace of the exception? Is the parsing coming from inside of Retrofit's `OkHttpCall` or from inside your error-handling code?

**Comment by swankjesse** [comment]
No clear action to take here.
