### ISSUE TITLE
[Security] Fragile cipher suites supported, would you like to remove them?

### ISSUE THREAD

**Issue by jackyvictory** [square/okhttp#4199]
What kind of issue is this?

 - [ ] Bug report. If you’ve found a bug, spend the time to write a failing test. Bugs with tests
       get fixed. Here’s an example: https://gist.github.com/swankjesse/981fcae102f513eb13ed

Our apk with OKHttp is under the security inspection of IBM AppScan, and get the issue that `Android: Weak SSL Cipher Suites are Supported`. Here is the details of this issue: 

Title | Description
-- | --
Severity | High 
Status | New
Classification | Definitive
Location | (okhttp3\internal\connection\RealConnection.java:241)
Calling Line | (okhttp3\internal\connection\RealConnection.java:241)
Calling Method | okhttp3.internal.connection.RealConnection.connectTls(int, int, okhttp3.internal.connection.Conn ectionSpecSelector):void
Class | com.xxx.xxx
Package | com.xxx.xxx
Availability Impact | Partial
Confidentiality Impact | Partial
Integrity Impact | Partial
Date Created | Wednesday, July 11, 2018
Last Updated | Wednesday, July 11, 2018
Risk | It is possible to steal or manipulate customer session and cookies, which might be used to impersonate a legitimate user, allowing the hacker to view or alter user records, and to perform  								transactions as that user.
Causes | The web server or application server are configured insecurely.
Payload |
Intent Package | com.xxx.xxx
Intent Class | com.xxx.xxx
Method Signature | javax.net.ssl.SSLParameters.setCipherSuites(java.lang.String[]):void
Issue Validation Parameters - Name | ciph￼￼￼￼￼￼￼erSuites
Issue Validation Parameters - Value | TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA25, **_TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA_**,**_TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA_**,**_TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA_**,**_TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA_**,TLS_RSA_WITH_AES_128_GCM_SHA256,**_TLS_RSA_WITH_AES_128_CBC_SHA_**,**_TLS_RSA_WITH_AES_256_CBC_SHA_**

The above with **_bold and italic_** are reported as the cause of this issue.  As far as I'm concerned, it is **_SHA_** that considered fragile by IBM AppScan. In fact it is an outdated algorithm and many security standards such as PCI consider it fragile. 

So, would you like to upgrade OKHttp, deprecate **_SHA_** to make it complies with these security standards? Or else some apk with high security requirements may face the same problem.

**Comment by swankjesse** [comment]
Configure your OkHttpClient to use ConnectionSpec.RESTRICTED_TLS instead of it's default connection specs. This may limit which servers you can complete a TLS handshake with.

**Comment by yschimke** [comment]
Doesn't appear to be anything to do here

**Comment by mobDevKz** [comment]
@jackyvictory Hello! How did you resolved this problem?
