### ISSUE TITLE
[Feature Request] get RealConnection rawsocket localport

### ISSUE THREAD

**Issue by lxxgreat** [square/okhttp#4200]
we use okhttp to implementing websocket, and want to get RealConnection rawsocket localport, but the connection pool's member variable is private. so can it be public or hava a public method ?

**Comment by yschimke** [comment]
As mentioned on the PR, we should not expose private types.  But it would be useful to have some visibility into the ConnectionPool.  So I personally hope there is something we can do here.

This sort of change probably takes a number of review iterations and will need to prove it's value before getting accepted as it commits to a new public API.  i.e. it could be a frustrating experience.

**Comment by swankjesse** [comment]
If you're looking for a workaround, you can provide a custom SocketFactory that remembers the sockets returned.

**Comment by yschimke** [comment]
@swankjesse I want a similar feature to snapshot, and listen for connection pool additions and removals (facebook flipper and stetho type monitoring).  Have we considered public API here?

**Comment by swankjesse** [comment]
I'm not sure. Our EventListener API is intended to help developers understand how their clients & servers interact. This would be strictly about OkHttp itself, which is a much narrower audience.

**Comment by yschimke** [comment]
Won't fix.
