### ISSUE TITLE
Repeated requests

### ISSUE THREAD

**Issue by hekaidaqaz** [square/okhttp#4202]
What kind of issue is this?

 - [ ] When the request to play no response back, will send the second post request repeat immediately
Cause background request twice, but will have a response for the second time

The following is the response of the two requests, the first response without any value

`Request URL:https://www.uto360.com/utoo/client/2dcode/reservation
Provisional headers are shown
Accept-Encoding:gzip
Connection:Keep-Alive
Content-Length:610
Content-Type:application/x-www-form-urlencoded
deviceId:90:b6:86:83:94:f1
Host:www.uto360.com
identify:90:b6:86:83:94:f1
imei:99000479681500
imsi:
lat:4.9E-324
lon:4.9E-324
platform:android
type:0
User-Agent:okhttp/3.11.0
user-token:cbfef89e88e0c4f65f0c19f0a662727e
version:3.5.1
param:{"address":"成都四川锦江宾馆","departure":"1533947400000","dstLatitude":39.73280452097715,"contact":"13518105627","departureBegin":"1533945600000","dstAddress":"测试北京大兴区政府","orderId":"3000030","latitude":30.65431584414922,"passengerCount":1,"longtitude":104.07113670211325,"mileage":1775.976,"dstLongtitude":116.34808946282484,"passengers":[]}`
``
`Request URL:https://www.uto360.com/utoo/client/2dcode/reservation
Request Method:POST
Status Code:200 
Provisional headers are shown
Accept-Encoding:gzip
Connection:Keep-Alive
Content-Length:610
Content-Type:application/x-www-form-urlencoded
deviceId:90:b6:86:83:94:f1
Host:www.uto360.com
identify:90:b6:86:83:94:f1
imei:99000479681500
imsi:
lat:4.9E-324
lon:4.9E-324
platform:android
type:0
User-Agent:okhttp/3.11.0
user-token:cbfef89e88e0c4f65f0c19f0a662727e
version:3.5.1
param:{"address":"成都四川锦江宾馆","departure":"1533947400000","dstLatitude":39.73280452097715,"contact":"13518105627","departureBegin":"1533945600000","dstAddress":"测试北京大兴区政府","orderId":"3000030","latitude":30.65431584414922,"passengerCount":1,"longtitude":104.07113670211325,"mileage":1775.976,"dstLongtitude":116.34808946282484,"passengers":[]}
access-control-allow-headers:X-Requested-With, user-token, Content-Type, Accept, version, type, platform
access-control-allow-methods:POST, GET, OPTIONS, DELETE, HEADER
access-control-allow-origin:*
access-control-max-age:3600
cache-control:no-cache, no-store, max-age=0, must-revalidate
content-type:application/json;charset=UTF-8
date:Thu, 09 Aug 2018 17:39:18 GMT
expires:0
pragma:no-cache
server:Tengine
x-application-context:service-entry:prod:8090
x-content-type-options:nosniff
x-frame-options:DENY
x-xss-protection:1; mode=block`

**Comment by yschimke** [comment]
Can you make a reproduction? It shouldn't do this unless the connection fails and the request couldn't possibly have started on the server.

**Comment by swankjesse** [comment]
No clear action to take here.
