### ISSUE TITLE
Is the okhttp3 use ssl default? how can i disable it

### ISSUE THREAD

**Issue by wangzl8128** [square/okhttp#4207]
I send the http request, the server response the 302 and https location, but I use browser requet the http address is ok. also I try to the postman,is ok too. so I at a loss.

**Comment by Obeyed** [comment]
Sounds like you're calling http, but the service wants you to follow the https protocal instead.
Allow following redirects to https or simply start by calling the url with https?

**Comment by yschimke** [comment]
Do you have an example URL that you can share? Also try with curl and -v options.

**Comment by wangzl8128** [comment]
Sorry，I found the problem. The server redirection to Https when the add header value 'HOST'.
