### ISSUE TITLE
The Content-Type of FormBody with charset

### ISSUE THREAD

**Issue by lfz757077613** [square/okhttp#4210]
I set the content-type with charset as shown below, but it will be covered by BridgeInterceptor with application/x-www-form-urlencoded.
Thus, the server analyze the request with its default charset. 
I create a interceptor to set the right Content-Type
```
FormBody formBody = new FormBody.Builder(Charset.forName("utf8"))
        .add("param", "xx")
        .build();
Request request = new Request.Builder()
        .url("xx")
        .header("Content-Type", "application/x-www-form-urlencoded; charset=UTF-8")
        .post(formBody)
        .build();
```
I think that if user has set Content-Type, OKHTTP would not cover it in BridgeInterceptor.intercept().
changes as below :
```
from:
      if (contentType != null) {
        requestBuilder.header("Content-Type", contentType.toString());
      }
to:
      if (contentType != null && userRequest.header("Content-Type") == null) {
        requestBuilder.header("Content-Type", contentType.toString());
      }
```

**Comment by lfz757077613** [comment]
sadly, I find The interceptor created by user will execute before the BridgeInterceptor because of getResponseWithInterceptorChain(), so I can't set the right content-type by creating a interceptor.

**Comment by yschimke** [comment]
Is charset valid for application/x-www-form-urlencoded?  Regardless, this primarily seems like a bug with the server.  It shouldn't be using it's default charset when evaluating client requests.

Anyway, You can probably set a network interceptor which executes after the bridge interceptor.

**Comment by lfz757077613** [comment]
@yschimke finally, I guess the real reason is  not the Content-Type. 
It works well when I send  the parameter by FormBody.addEncoded() instead of FormBody.add().
By reading source code, I find that FormBody.addEncoded() do something else for special charaters such as '+' and '%'.
Thanks for your help, I understand how the interceptor woks better and I will figure out the difference between add() and addEncoded()
: D
