### ISSUE TITLE
HTTPS Wiki page is out-of-date

### ISSUE THREAD

**Issue by amirlivneh** [square/okhttp#4214]
https://github.com/square/okhttp/wiki/HTTPS lists the built-in connection specs but doesn't mention RESTRICTED_TLS:
https://github.com/square/okhttp/blob/911a625cd5c2a98d721daa5c0f3945674b707500/okhttp/src/main/java/okhttp3/ConnectionSpec.java#L97-L101

Also, the Wiki mentions falling back to COMPATIBLE_TLS, but I could not find evidence of this in the code.

**Comment by swankjesse** [comment]
Yeah, wow that’s quite out of date. Can fix.

**Comment by yschimke** [comment]
I've fixed https://github.com/square/okhttp/wiki/HTTPS, but no offense taken if you edit further.  I'll update this page when either JDK 11 or Conscrypt is released with TLS 1.3 support.
