### ISSUE TITLE
EventListener can't access wire-level request in case of failure

### ISSUE THREAD

**Issue by amirlivneh** [square/okhttp#4218]
I'm trying to log the URI of failed requests using an `EventListener`. The URI may be rewritten by Interceptors and I'm interested in the URI of the wire-level request.

In case of a successful request, the URI of the wire-level request can be obtained by by calling `Response.request()`. But if the request fails and there is no `Response` object, there seems to be no way to get this information; Only the original is accessible through `Call.request()`.

**Comment by amirlivneh** [comment]
2 possible solutions are:
- Add a `Call.wireLevelRequest()` method. This is not strictly backward compatible, but may be acceptable.
- Change `EventListener.requestHeadersStart()`'s signature to `EventListener.requestHeadersStart(Call call, Request wireLevelRequest)`. This is not backward compatible, but there is a disclaimer in https://github.com/square/okhttp/wiki/Events#availability stating that this interface is subject to change.

If any of the above works, or if you can suggest a better solution, I can send a PR.

**Comment by swankjesse** [comment]
If you need a quick & dirty fix you can use Call tags and interceptors to hack around this. Here’s a sketch:

```
public void callOkHttp() {
  Request request = new Request.Builder()
      .url(...)
      .tag(HackWireLevelRequestHolder.class, new HackWireLevelRequestHolder())
      .build();
  ...
}


class HackWireLevelRequestHolder {
  public static final Interceptor INTERCEPTOR = new Interceptor() {
    public Response intercept(Chain chain) throws IOException {
      Request request = chain.request();
      request.tag(HackWireLevelRequestHolder.class).wireLevelRequest = request;
      return chain.proceed(request);
    }
  }

  Request wireLevelRequest = null;
}
```

**Comment by swankjesse** [comment]
Will this help?
https://github.com/square/okhttp/issues/4638

**Comment by amirlivneh** [comment]
Yes, it can help, assuming that the wire-level request will be reachable from the parameters of the new methods.

**Comment by yschimke** [comment]
Closing in favour of the request events.

**Comment by yschimke** [comment]
Just hit this but without the ability to control the creation of the request.  Just realised I'm saved by the Call.Factory which I can trivially decorate to set the tag I need.

I don't actually need to check it, just use Call.Factory wrapper instead of an interceptor.
