### ISSUE TITLE
retrofit.RetrofitError: method POST must have a request body.

### ISSUE THREAD

**Issue by KMKnation** [square/okhttp#4219]
I am using Retrofit API v-1.9.0  with the Okhttp v-2.2.0.
During gradle sync Okhttp's com.squareup.okhttp.internal.http.HttpEngine class's _proceed(Request request)_method's defination get changed like following...

HttpEngine using com.squareup.okhttp.internal.http.Transport interface
```

   transport.writeRequestHeaders(request);

      if (permitsRequestBody() && request.body() != null) {
        Sink requestBodyOut = transport.createRequestBody(request, request.body().contentLength());
        BufferedSink bufferedRequestBody = Okio.buffer(requestBodyOut);
        request.body().writeTo(bufferedRequestBody);
        bufferedRequestBody.close();
      }
```
HttpEngine using com.squareup.okhttp.internal.http.HttpStream interface

```

      httpStream.writeRequestHeaders(request);

      //Update the networkRequest with the possibly updated interceptor request.
      networkRequest = request;

      if (permitsRequestBody(request) && request.body() != null) {
        Sink requestBodyOut = httpStream.createRequestBody(request, request.body().contentLength());
        BufferedSink bufferedRequestBody = Okio.buffer(requestBodyOut);
        request.body().writeTo(bufferedRequestBody);
        bufferedRequestBody.close();
      }
```

which results in throwing  following issue.

> retrofit.RetrofitError: method POST must have a request body.

 - [ ] Question. How this class file changes during build process ?

 - [ ] Bug report. One Okhttp library v-2.2.0 throwing **retrofit.RetrofitError: method POST must have a request body.** and same library in last versioned project not throwing this exception.

**Comment by swankjesse** [comment]
This is an open source project. Please upgrade to a recent release before reporting bugs.
