### ISSUE TITLE
javax.net.ssl.SSLHandshakeException: SSL handshake aborted: ssl=0xd71fb080: I/O error during system call, Connection reset by peer

### ISSUE THREAD

**Issue by Loren-Wang** [square/okhttp#4221]
An exception that occurs using "implementation 'com.squareup.okhttp3:okhttp:3.11.0'",But It was solved by "implementation 'com.squareup.okhttp3:okhttp-urlconnection:3.11.0'".

I want to know why???

**Comment by swankjesse** [comment]
Unsure. No action to take here regardless.
