### ISSUE TITLE
Update MockWebServer to support long-polling line-delimited JSON responses

### ISSUE THREAD

**Issue by tir38** [square/okhttp#4222]
I have a long polling GET request that responds with line-delimited JSON. I'd like to mock this in my tests.  https://en.wikipedia.org/wiki/JSON_streaming#Line-delimited_JSON I realize this is a big change to how MockWebServer works.

Currently MockWebServer let's me specify the entire mock response which will be returned all at once, and then the request will complete. I figure there are two main parts:

1. let me decide when to complete/close a response
2. allow me to enqueue only part of a response

**Comment by swankjesse** [comment]
FYI, this is actually pretty awkward to do given OkHttp’s design. The closest we get is MockResponse#throttleBody.

**Comment by JakeWharton** [comment]
There was another issue about this. I searched but couldn't find it. WebSockets are also similar.

**Comment by tir38** [comment]
What is the reason that `MockResponse.setBody(Buffer buffer)` performs a clone of the buffer?

https://github.com/square/okhttp/blob/master/mockwebserver/src/main/java/okhttp3/mockwebserver/MockResponse.java#L163

IIUC if this did *not* clone, then I could write to the buffer after creating a MockResponse and essentially insert individual lines of json throughout a test.

**Comment by swankjesse** [comment]
Might come with the server part of this change:
https://github.com/square/okhttp/issues/4267

**Comment by tir38** [comment]
To anybody who has this issue. I solved my problem with some other means:

1. isolate the long polling GET into its own retrofit service
2. wrap that service in a helper class that makes the web request, handles buffer reading, and returns an observable of lines of json
3. mock that wrapper in tests to supply my own lines of json as needed

```
interface LongPollingGetRetrofitService {
    @Streaming
    @GET("api/example/events")
    Observable<ResponseBody> getEvents(...);
}

class Wrapper {

    private LongPollingGetRetrofitService longPollingGetRetrofitService;

    public Observable<String> observeEventChannelJson(...) {
        return longPollingGetRetrofitService.getEvents(....)
        // emit each line of input buffer separately
        // Following example in https://www.nurkiewicz.com/2017/08/loading-files-with-backpressure-rxjava.html
        // except we don't handle backpressure so we don't need Flowable or generate()
            .flatMap(responseBody ->
                Observable.create(emitter -> {
                    BufferedReader bufferedReader = new BufferedReader(responseBody.charStream());
                    String line;
                    try {
                        while ((line = bufferedReader.readLine()) != null) {
                            if (!line.isEmpty()) {
                                emitter.onNext(line);
                            }
                        }
                    } catch (...) {
                        ...
                    } finally {
                        emitter.onComplete();
                        responseBody.close();
                    }
                }));
    }
}
```

This was probably the right thing to do all along. "Don't mock what you don't own."

**Comment by yschimke** [comment]
Won't fix.
