### ISSUE TITLE
[doh] re-enable buildChantra

### ISSUE THREAD

**Issue by chantra** [square/okhttp#4223]
It should be possible to re-enable buildChantra in https://github.com/square/okhttp/blob/master/okhttp-dnsoverhttps/src/test/java/okhttp3/dnsoverhttps/DohProviders.java#L109

It now support draft-13 (only). Also it should be accessible over IPv6 and IPv4.

Now, mind this is not an enterprise grade setup :) it may be just easier to spin up a local proxy by `pip install`ing doh-proxy and forwarding DNS requests to a well know open resolver provider (or whatever may be locally available).

**Comment by chantra** [comment]
oh, and if things are still failing, I like to know more to dig and see what the issue is :) Feel free to open an issue against https://github.com/facebookexperimental/doh-proxy

**Comment by yschimke** [comment]
With IPv4 only

```
uncached
********

Testing https://dns.dnsoverhttps.net/dns-query
google.com: [/216.58.194.174]
graph.facebook.com: [/157.240.22.19]
sdflkhfsdlkjdf.ee: java.net.UnknownHostException: sdflkhfsdlkjdf.ee: NXDOMAIN

Time: 1.964 seconds

cached first run
****************

Testing https://dns.dnsoverhttps.net/dns-query
google.com: [/216.58.194.174]
graph.facebook.com: [/157.240.22.19]

Time: 0.337 seconds

cached second run
*****************

Testing https://dns.dnsoverhttps.net/dns-query
google.com: [/216.58.194.174]
graph.facebook.com: [/157.240.22.19]

Time: 0.015 seconds
```

With IPv4 and IPv6

```
uncached
********

Testing https://dns.dnsoverhttps.net/dns-query
google.com: []
graph.facebook.com: []
sdflkhfsdlkjdf.ee: []

Time: 2.132 seconds

cached first run
****************

Testing https://dns.dnsoverhttps.net/dns-query
google.com: []
graph.facebook.com: []

Time: 0.379 seconds

cached second run
*****************

Testing https://dns.dnsoverhttps.net/dns-query
google.com: []
graph.facebook.com: []

Time: 0.016 seconds
```

**Comment by chantra** [comment]
@yschimke so IPv6 is not working for you? I am not sure why though. From testing myself on a v6 enabled host: 

```
./dohproxy/client.py  --domain dns.dnsoverhttps.net --remote-address 2604:a880:1:20::51:f001 --qname graph.facebook.com --qtype a
2018-08-23 10:29:36,688:    DEBUG: Opening connection to dns.dnsoverhttps.net
2018-08-23 10:29:36,841:    DEBUG: Query parameters: {'dns': 'AAABAAABAAAAAAAABWdyYXBoCGZhY2Vib29rA2NvbQAAAQAB'}
2018-08-23 10:29:36,843:    DEBUG: Stream ID: 1 / Total streams: 0
2018-08-23 10:29:36,914:    DEBUG: Response headers: [(':status', '200'), ('server', 'nginx/1.12.2'), ('date', 'Thu, 23 Aug 2018 17:29:36 GMT'), ('content-type', 'application/dns-message'), ('content-length', '94'), ('cache-control', 'max-age=60')]
id 0
opcode QUERY
rcode NOERROR
flags QR RD RA
;QUESTION
graph.facebook.com. IN A
;ANSWER
graph.facebook.com. 3590 IN CNAME api.facebook.com.
api.facebook.com. 3590 IN CNAME star.c10r.facebook.com.
star.c10r.facebook.com. 60 IN A 157.240.22.19
;AUTHORITY
;ADDITIONAL
2018-08-23 10:29:36,920:    DEBUG: Response trailers: {}
```

**Comment by yschimke** [comment]
Shouldn’t that be a AAAA query?

**Comment by chantra** [comment]
@yschimke well you can query either A/AAAA over IPv4/IPv6. I am not sure what the `includeIPv6()` is used for. I thought it meant to test over v4 and v6.

**Comment by chantra** [comment]
> This is valid AFAICT

very few implementations (if any) do support multiple questions...

**Comment by yschimke** [comment]
Yep, this appears to be spec valid (A & AAAA queries) in both DNS generally and DOH, but avoided due to confusion when combining results.  I'll avoid doing this.  Thanks.

**Comment by yschimke** [comment]
@chantra PR https://github.com/square/okhttp/pull/4234
