### ISSUE TITLE
Closing the body of Response{protocol=http/1.1, code=302, message=Found, url=http://weixin.qh.chinamobile.com/imss/app?service=page/GreenPaymentChannel&listener=initPage&oriurl=http://dapis.mting.info/yyting/gateway/entityPath.action?entityId=29284&entityType=3&opType=1&sections=%5B661%5D&type=0&token=2Jdt4wLs} didn't close its backing stream. Bad interceptor?  okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:178)

### ISSUE THREAD

**Issue by barryyanggoing** [square/okhttp#4224]
# OkHttp Dispatcher(673)

java.lang.IllegalStateException

Closing the body of Response{protocol=http/1.1, code=302, message=Found, url=http://weixin.qh.chinamobile.com/imss/app?service=page/GreenPaymentChannel&listener=initPage&oriurl=http://dapis.mting.info/yyting/gateway/entityPath.action?entityId=29284&entityType=3&opType=1&sections=%5B661%5D&type=0&token=2Jdt4wLs} didn't close its backing stream. Bad interceptor?

**Comment by barryyanggoing** [comment]
okhttp3.6.0

**Comment by barryyanggoing** [comment]
RetryAndFollowUpInterceptor

**Comment by swankjesse** [comment]
Executable test case?

**Comment by barryyanggoing** [comment]
sorry,i have no test case and cause of the problem seem is the public wifi.
