### ISSUE TITLE
MockWebServer recordedRequest.getRequestUrl() is null on ipv6 host

### ISSUE THREAD

**Issue by thevery** [square/okhttp#4225]
1) On my linux build machine localhost is resolved to ipv6 address (`0:0:0:0:0:0:0:1`)
2) `okhttp3.mockwebserver.RecordedRequest#RecordedRequest` does not handle ipv6 properly because it  uses `HttpUrl.parse(String.format("%s://%s:%s%s", scheme, hostname, port, path));` - brackets are missing for ipv6. Easy fix is `HttpUrl.Builder` usage.
3) Unfortunately I cannot create a reliable test class, but I use `server.start(Inet4Address.getLocalHost(), 0);` as a workaround.

**Comment by swankjesse** [comment]
That was pretty sloppy! Can fix.
