### ISSUE TITLE
I did an experiment and the result is http1.1 better than http2...

### ISSUE THREAD

**Issue by Kyson** [square/okhttp#4226]
Hi,

I did an experiment: 

1. Download “Network Link Conditioner” for mac. In this software, choose network to "Very bad" which is 10% loss package and 500ms delay.
2. Android Device connect mac's wifi.
3. In my app code:

![image](https://user-images.githubusercontent.com/3901140/44458404-b29fda00-a638-11e8-9272-4854cbdbfc09.png)

enable http2 then send 100 same requests, and it fail 20+ times

4. disable http2 then send 100 same requests, and it fail about 5 times

This result is no accident, because i tried for many times.

Before I thought http2 is better than http1.1 ,especially when network is bad. But the truth is not.

So why is this happening? Is there some bug with okhttp's http2? 

Thank u very much.

**Comment by swankjesse** [comment]
Related: https://www.twilio.com/blog/2017/10/http2-issues.html

**Comment by Kyson** [comment]
@swankjesse Thank you very much , i will read this post.

**Comment by yschimke** [comment]
The takeaway here could be to make concurrency of a single stream tunable or controllable.  Also maybe applies to sharing Video and critical API calls over the same connection, especially with coalescing.
