### ISSUE TITLE
Shutdown webserver after N-th request

### ISSUE THREAD

**Issue by fred84** [square/okhttp#4227]
Our application make several sequential http calls. We treat connection error differently for first and subsequent calls, e.g.
- when first request failed mark operation as failed
- when second request failed - schedule retry request later

We can test read timeouts with `MockResponse.setHeadersDelay` or `MockResponse.setSocketPolicy`. But I didn't find similar option for testing connection timeouts.

IMHO it will be handy to have `SocketPolicy.SHUTDOWN_SERVER_AFTER_REQUEST` for such cases.

**Comment by swankjesse** [comment]
You might be able to use a custom Dispatcher to do this.

**Comment by fred84** [comment]
Thanks for suggestion with `Dispatcher`. Current solution looks like:
```java
    @Test
    void shutdownAfterFirstRequest() {
        RestTemplate template = new RestTemplate();

        server.setDispatcher(new Dispatcher() {
            @Override
            public MockResponse dispatch(RecordedRequest request) {
                CompletableFuture.runAsync(() -> {
                    try {
                        server.shutdown();
                    } catch (IOException e) {
                        // ignoring for now
                    }
                });

                return new MockResponse().setBody("hello world");
            }
        });


        assertThat(
                template.getForObject(server.url("/").toString(), String.class),
                equalTo("hello world")
        );

        ResourceAccessException e = assertThrows(
                ResourceAccessException.class,
                () -> template.getForObject(server.url("/").toString(), String.class)
        );
        assertThat(
                e,
                hasCause(instanceOf(ConnectException.class))
        );
    }
```
Other option with SocketPolicy seems much easier (no additional threads created) and at first sight requires only small modification of `MockWebServer`. I've just added 
```java
        if (response.getSocketPolicy() == SHUTDOWN_SERVER) {
          shutdown();
        }
```
after writing http response in `MockWebServer::processOneRequest` and it worked fine.

I'll test it more and prepare PR if you think it worth adding such `SocketPolicy`.

**Comment by swankjesse** [comment]
Please do. Maybe call it `SHUTDOWN_SERVER_AFTER_RESPONSE` ?
