### ISSUE TITLE
http/1.1, code=307, message=Temporary Redirect

### ISSUE THREAD

**Issue by vinaykrish505** [square/okhttp#4229]
Response{protocol=http/1.1, code=307, message=Temporary Redirect, url=https://xxxxxxxxx/xxxxxx/}

Android studio with 
retrofit2 and okhttp3 llibrary latest versions 2.4.0 & 3.11.0 respectively. Getting the issue that redirecting. Previously Httpclient it is working but here in retrofit we dont have solution for it. 
please provide update as early as possible.

**Comment by swankjesse** [comment]
Executable test case? Just want to be clear where OkHttp’s behavior is incorrect.

**Comment by vinaykrish505** [comment]
Hello Team,

In one of my android projects, I used to work with the retrofit library and
Okhhtp client. In post request I'm getting response code 307 temporary url
redirection. But the same request in iOS is normally getting the
response from the server. So I digged for the solution and in the process,
I found that Okhttp is not allowing the 307(301 & 302 also) response to
load directly.

I'm requesting you guys that please enable the 307 response code to
redirect directly.




*Thanks & Regards*
 M. Vinay Krishna
 Mob : +91-9440170923

**Comment by swankjesse** [comment]
Does calling OkHttpClient.Builder.followRedirects(false) help?

**Comment by vinaykrish505** [comment]
Yeah, @Jesse I tried with followRedirects(true) but it is not worked for
me.




*Thanks & Regards*
 M. Vinay Krishna
 Mob : +91-9440170923

**Comment by yschimke** [comment]
This works for my test client

```
$ okurl 'https://httpbin.org/redirect-to?status_code=307&url=https://api.twitter.com/robots.txt'
# Used for Google app indexing. See https://developers.google.com/app-indexing/webmasters/server
User-agent: Googlebot
Disallow:

User-agent: *
Disallow: /
```

**Comment by swankjesse** [comment]
Unclear what action to take here.
