### ISSUE TITLE
HttpLoggingInterceptor - configuration options

### ISSUE THREAD

**Issue by oliverlockwood** [square/okhttp#4244]
What kind of issue is this?

 - [x] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
       already exists! Don’t send pull requests to implement new features without first getting our
       support. Sometimes we leave features out on purpose to keep the project small.

I'd like to use the `HttpLoggingInterceptor` in my project, but to be able to customise how I use it - e.g. to hide an API key query parameter, or log the request body but not the response body, etc.

I can't see a way to do this at the moment.  Would you consider a PR to add this kind of functionality?  I thought I would offer to do this rather than just creating my own local implementation.

**Comment by swankjesse** [comment]
You can just create your own logging interceptor. It isn’t much code, especially if you start with the one in the Interceptors doc on the wiki.

**Comment by oliverlockwood** [comment]
Sure, no problem.
