### ISSUE TITLE
Exhausting stream IDs causes an application-visible failure

### ISSUE THREAD

**Issue by swankjesse** [square/okhttp#4245]
Would be neater to just set RealConnection.noNewStreams when we approach the limit.

**Comment by omkarnix** [comment]
Can I take pick up issue if no one else is working?

**Comment by yschimke** [comment]
Yep, if you are happy to sign the CLA https://github.com/square/okhttp/wiki/Contributing

Please include tests for the changes, and expect a thorough review including stylistic comments.

**Comment by swankjesse** [comment]
Duplicate of https://github.com/square/okhttp/issues/3670
