### ISSUE TITLE
java.net.Authenticator support

### ISSUE THREAD

**Issue by Vampire** [square/okhttp#4248]
There is a standard way to authenticate against servers and proxies, which is the `java.net.Authenticator`.
While you provide a way to set a `Proxy` or a `ProxySelector` directly, as default fallback you use the system default proxy selector.

It would be very nice if you could also use the "System default `Authenticator`" if none is set explicitly and also support setting a `java.net.Authenticator` explicitly instead of your own `okhttp3.Authenticator`.

**Comment by JakeWharton** [comment]
See https://github.com/square/okhttp/blob/master/okhttp-urlconnection/src/main/java/okhttp3/JavaNetAuthenticator.java from the `okhttp-urlconnection` artifact.

**Comment by yschimke** [comment]
I think the missing part is the bridge to your own existing (non system default) java.net.Authenticator.  

n.b. I am playing around with https://github.com/rburgst/okhttp-digest for this functionality for my own purposes. It is obviously okhttp focused, but mentioning it to avoid duplication.

**Comment by Vampire** [comment]
Ah, nice that this bridge exists already.

What is missing is the non-default authenticator bridge as Yuri said, because this bridge only works with the default authenticator. 

But what is missing additionally is, that it is used automatically if nothing else is set explicitly. The system default `ProxySelector` is used automatically, this authenticator is not. I'd say this is inconsistent and inconvenient. Why not automatically using this for both authenticators if nothing is set explicitly?

What would also be missing from my request, but that would only be a convenience function, are `HttpClient.Builder.authenticator(java.net.Authenticator)` and `HttpClient.Builder.proxyAuthenticator(java.net.Authenticator)` methods that apply the missing wrapper to the argument.

**Comment by yschimke** [comment]
@Vampire I think changing the default now could be awkward and break more people than it fixes.  Others have probably worked around by now.  But adding support your own java.net.Authenticator seems like a clear cut net positive PR.

**Comment by Vampire** [comment]
How should that break people?

Current Default:
- They have a proxy that needs authentication
- The default authenticator is set
- It does not work

Current with "work-around":
- They have a proxy that needs authentication
- The default authenticator is set
- It does not work
- They set the OkHttp authenticator
- It works by using the OkHttp set one

With the change Default:
- They have a proxy that needs authentication
- The default authenticator is set
- It works using the default one

With the change with old "work-around":
- They have a proxy that needs authentication
- The default authenticator is set
- They set the OkHttp authenticator as it didn't work in the past
- It works by using the OkHttp set one

So if someone work-arounded the problem, which means they wrote an OkHttp authenticator and set it, it will not change that this is used and works like before.

The only "breaking" change I see, is that before connecting to a site or proxy that needs authentication just did fail when no OkHttp specific code was written and will work now if the default authenticator is set and suitable.

**Comment by Vampire** [comment]
And btw. the `JavaNetAuthenticator` does not follow the advice of `okhttp3.Authenticator` JavaDoc to check whether there is already an authorization header in the original request and thus ends in an endless-loop if invalid credentials are provided and the `java.net.Authenticator` has no chance to do this check.

**Comment by yschimke** [comment]
Maybe I'm jaded :) https://xkcd.com/1172/

**Comment by Vampire** [comment]
While as usual xkcd is very funny and unfortunately all too true, I'm not sure how to interpret that comment.
Does it mean you still are against changing the default or does it mean you now support changing the default?
If the former, I'm sad, because I still cannot imagine a situation where this will break peoples stuff, except if they relied on the "bug" / "absence of the feature" which imho should be ignored as this should be a fairly small amount of users if at all and the gain for the average user would be more important, as this is the standard way to define authentication, especially if you also use the default proxy selector or the standard proxy selection properties the default default proxy selector is looking at.

If you e. g. use some software or library that uses OkHttp under the hood that does not do anything proxy-specific, you can still set a proxy via standard system properties or setting the default proxy selector, but you have no chance to define authentication unless the software or library you use adds explicit support for it.

**Comment by yschimke** [comment]
@Vampire It means I'm probably overly cautious by default, and trying to fix it going forward is worthwhile.

I think the biggest risk could be a badly implemented java.net Authenticator which now starts leaking private credentials to any site that prompts for basic auth.  But could be mitigated by a strong warning.

**Comment by swankjesse** [comment]
**Proxy selection and authentication belongs with the host operating system.** The OS knows which proxy it wants for which host, and how to authenticate against each. I agree with @Vampire that it’s a bug that OkHttp makes proxy _selection_ automatic but not proxy _authentication_.

**Endpoint authentication belongs with the application layer.** Only the application layer knows how it’s supposed to authenticate (cookies, OAuth, basic, digest, etc.) and can implement this.

Unfortunately Java’s built-in Authenticator API is a mess. Among its various usability issues it conflates endpoint authentication (which is relatively common) with proxy authentication (which is relatively rare). We abandoned this API in OkHttp 3.0 in favor of our own. But that means we don’t get the host OS to provide proxy configuration.

We have an open issue for pre-emptive proxy authentication (https://github.com/square/okhttp/issues/2435). Perhaps we could call `java.net.Authenticator` _before_ connecting in order to do pre-emptive BASIC auth. Unfortunately such authentication is insecure and will always send unencrypted credentials over the wire.

@Vampire do the proxy servers you’re looking at use BASIC auth? Or are they sending some other header? We don’t have anything here partly because we haven’t had much demand, and partly because there aren’t many good options.

**Comment by Vampire** [comment]
Well, I'd say that is up to the user and operators to care about. (the security)
The standardized way is like that and it would be nice if OkHttp would conveniently support it. :-)

Actually I'm not looking at real proxies.
I "just" add proxy support and tests to Javacord which uses OkHttp for the REST API it talks to.
I use http://mock-server.com/ as test-backend and there just emulate the authentication round-trip.

**Comment by yschimke** [comment]
@swankjesse I'm trying to get internal http clients e.g. scripts working against various intranet and internet services without user intervention.  Finding I can end up dealing with any and all of

1) kerberos/basic auth
2) pac/manual config for proxies
3) proxies or authenticated services
4) a limited set of hosts (*.company.com) I want to possibly send my basic auth credentials (windows login details)

**Comment by swankjesse** [comment]
I'd love to talk to users & operators before adding new behavior. We want to be secure-by-default and that might mean not supporting BASIC auth over a plaintext channel, even if that was common once upon a time.

**Comment by Vampire** [comment]
Oh man, forget about the support to set an explicit non-default `java.net.Authenticator`.
I looked into doing it in our code at least intermediary.
But that class is really written to not be used.
To use it without having set it as system default you would need to use reflection heavily as all fields are private, all methods are protected and almost all methods are final, so you also could not circumvent by using subclassing.

So the only left open point is whether to use the system default authenticator by default as is used the system default proxy selector by default.

**Comment by Vampire** [comment]
And maybe moving the `JavaNetAuthenticator` out of `okhttp-urlconnection` into `okhttp` as it is not `URLConnection` specific and hopefully should not be removed once `okhttp-urlconnection` gets removed due to being deprecated. (And maybe `JavaNetCookieJar` alongside)

**Comment by swankjesse** [comment]
Trying to figure out what next steps are for this bug. Changing the defaults is possible but we might want to sit on that until we do a major version bump.

**Comment by yschimke** [comment]
> And maybe moving the `JavaNetAuthenticator` out of `okhttp-urlconnection` into `okhttp` as it is not `URLConnection` specific and hopefully should not be removed once `okhttp-urlconnection` gets removed due to being deprecated. (And maybe `JavaNetCookieJar` alongside)

Done in https://github.com/square/okhttp/pull/5978
