### ISSUE TITLE
is it possible to make a request to HTTPS resource through proxy with basic authorization?

### ISSUE THREAD

**Issue by mihmig** [square/okhttp#4254]
Hi!
I am using this library with my pet-project on Java.
There was a problem - i can't get HTTPS resource through my HTTP (not HTTPS!) proxy with basic authorization.
When i send http-request, everything is OK:
```

Request request = new Request.Builder().url("http://httpbin.org/get").build();
		Authenticator proxyAuthenticator = new Authenticator() {
		  @Override public Request authenticate(Route route, Response response) throws IOException {
		       String credential = Credentials.basic("user", "myVery$trongPa$$word");
		       return response.request().newBuilder()
		           .header("Proxy-Authorization", credential)
		           .build();
		  }
		};
		OkHttpClient.Builder okHttpClientBuilder = new OkHttpClient().newBuilder();
		okHttpClientBuilder.proxy(new Proxy(Proxy.Type.HTTP, new InetSocketAddress("proxy.mycompany.com",8080)));
		okHttpClientBuilder.proxyAuthenticator(proxyAuthenticator);
		OkHttpClient client = okHttpClientBuilder.build();
		Response response = client.newCall(request).execute();
		System.out.println(response.body().string());

```
we see that proxy is working.

But when I change url for http**s**://httpbin.org/get
i get error 407 Proxy Authentication Required

is it possible to make a request to HTTP**S** resource through proxy with basic authorization?

**Comment by swankjesse** [comment]
That's surprising; the authenticator should be called in both cases.

**Comment by yschimke** [comment]
@mihmig can you send the request and response headers for all calls (mask out tokens obviously)?  You can get these with a EventListener or HttpLoggingInterceptor

**Comment by swankjesse** [comment]
No obvious action to take here.
