### ISSUE TITLE
HTTP/2 nonblocking backend

### ISSUE THREAD

**Issue by swankjesse** [square/okhttp#426]
The async API is currently backed by blocking transports for SPDY. We should change the SPDY and HTTP/2 transport to offer a non-blocking / callback driven API. The async API would enqueue jobs and recover from failures without holding a thread during I/O.

**Comment by dain** [comment]
Any guess on when this is going to land?

**Comment by swankjesse** [comment]
It isn't high-priority, but mostly 'cause it's a disruptive change to implement. We would gain concurrency, but we'd need to create more objects and use more memory to make async work.

What are you looking for?

**Comment by dain** [comment]
I am looking at OkHttp for server to server communication in large clusters.  In this environment, the client would need to talk to 1000s of servers with 100s of concurrent request per server.  A thread per request is not possible, but with request multiplexing, a thread connection might work, but would be annoying.

**Comment by swankjesse** [comment]
@dain gotcha. Are your servers using HTTP/2 ? I'd love to do async on HTTP/2 only!

**Comment by dain** [comment]
Yes, this is for HTTP/2 servers.

**Comment by swankjesse** [comment]
Unlikely to be how we implement this. Instead I’m thinking coroutines in Okio.
