### ISSUE TITLE
3.11.0 breaks on RoboVM

### ISSUE THREAD

**Issue by guillerodriguez** [square/okhttp#4266]
OkHttp 3.11.0 breaks on [RoboVM](http://robovm.mobidevelop.com/).

RoboVM is an AOT compiler for iOS. It uses a runtime class library that is "derived from Android" (i.e. based on Apache Harmony), but without any Android specific packages.

Because RoboVM's runtime class library is based on Apache Harmony, all the checks in AndroidPlatform.buildIfSupported() (which basically check for classes that are present in Android, but which are not actually Android-specific) pass, so OkHttp decides it is running on Android.

However, there are problems later when AndroidPlatform.getSSLContext() uses the Android-specific android.os.Build.VERSION class to decide whether TLS 1.2 is available.

This problem is only present in 3.11.0, as it was introduced by [this commit]( https://github.com/square/okhttp/commit/bdbe2dad8806a77bf018b87f4518df250fa67f89).

Here's the relevant RoboVM issue: https://github.com/MobiVM/robovm/issues/325

**Comment by swankjesse** [comment]
At the moment I feel we’re unprepared to build & test correct behavior on RoboVM. It’s awesome that it has ever worked, and I don’t want to do anything that’ll harm it.

But we don’t have the capacity to anticipate or address problems on that platform. Heck, supporting both Android and Java is a headache.

If RoboVM users would like to submit small patches or workarounds, I’m receptive. I’m closing this because it isn’t actionable by the OkHttp project team. If there’s another place to track it (RoboVM’s project? A RoboVM form?) that works for me.

**Comment by guillerodriguez** [comment]
Fair enough. However this should be very easy to fix. Since you say you are receptive to small patches / workarounds, I'll prepare a PR and submit it for review.

**Comment by yschimke** [comment]
@guillerodriguez How does RoboVM run?  Do you want to run as close to Android mode as possible? Or do you want to run using JDK code as much as possible behind the Android APIs?

I guess I'm asking whether you ideally want to run AndroidPlatform or Java9Platform?

I'm assuming the former, and a minor fix will get past this issue.

**Comment by almilli** [comment]
This is also a problem on Multi-Engine OS when running on iOS and I run into the same problem with the android.os.Build.VERSION class not being found.

**Comment by guillerodriguez** [comment]
@yschimke 

> How does RoboVM run? Do you want to run as close to Android mode as possible? Or do you want to run using JDK code as much as possible behind the Android APIs?

I believe as close to Android mode as possible. The runtime is based on Android 4.something, it supports conscrypt, and has setUseSessionTickets, setHostname, etc.

**Comment by angelix** [comment]
Is it possible to backport the check from #4269 to v4?

**Comment by guillerodriguez** [comment]
> @guillerodriguez Is it possible to backport the check from #4269 to v4?

(Sorry, didn't get a notification for this)

Backporting the check is not straightforward for several reasons:

 1. OkHttp now [checks the java.vm.name system property](https://github.com/dkimitsa/okhttp/blob/93b5a1af7548b2dd6eb163528a20d5211c9e51c1/okhttp/src/main/kotlin/okhttp3/internal/platform/Platform.kt#L190) to decide if it is running on Android. This returns "Dalvik" on Android but "RoboVM" in RoboVM. So RoboVM would not be identified as an Android based target. If you want to support RoboVM (as a "pseudo-Android target") this check would need to be updated.
 2. OkHttp now requires Android 5 minimum I think. RoboVM is based on an Android4 runtime. Not sure about the real implications of this (would need to check).
 3. The [AndroidPlatform class](https://github.com/dkimitsa/okhttp/blob/93b5a1af7548b2dd6eb163528a20d5211c9e51c1/okhttp/src/main/kotlin/okhttp3/internal/platform/AndroidPlatform.kt) now has `Build.VERSION.SDK_INT` checks all over the place, so this would need to be extracted to a separate helper function to catch the NoClassDefFound exceptions, or perhaps the check could simply be skipped for the RoboVM case.

Some other approaches that you may want to try:

 * Patch `Platform.kt` so that it also considers RoboVM as an Android platform (java.vm.name == "RoboVM"), then add an android.os.Build class to your application (as shown [here](https://github.com/MobiVM/robovm/issues/325#issuecomment-420311698)) with appropriate SDK_INT version.
 * Have a look at PR #6133 from dkmitsa (this adds a specific RoboVM platform implementation)
