### ISSUE TITLE
Duplex Calls

### ISSUE THREAD

**Issue by swankjesse** [square/okhttp#4267]
# Motivation

I’d like to build make it possible for gRPC clients to be built with OkHttp’s public API. The gRPC project already has an [OkHttp backend](https://github.com/grpc/grpc-java/tree/master/okhttp/src/main/java/io/grpc/okhttp), but it needs to rely on internal features.

There’s two things gRPC needs that OkHttp doesn’t offer:

 * Sending data on the request stream _after_ having received the response status and headers. This isn’t like HTTP because it isn’t request/response. It’s a bit more like WebSockets. It’s possible to do a two-way chat session with a single gRPC call.
 * Sending and receiving trailers. This is how gRPC cleanly signals a clean termination of a stream.

I’d like to build APIs on OkHttp to support these. At the moment gRPC would be the only use case for these APIs, but we wouldn’t label them as “gRPC”. The name I like best is “duplex” but I’d love to find something better.

# API

Here’s a sketch of how duplex calls would work.

### Caller Creates a Duplex Request

When you do this you can’t also specify a request body.

```
Request request = new Request.Builder()
    .url("https://api.github.com/markdown/raw")
    .duplexPost(...)
    .build();
```

The returned request has a null body, and returns `true` from a new `isDuplex()` method.

### Response Has An Outbound Stream

This class is structured like a `ResponseBody` that does blocking writes instead of blocking reads.

```
interface HttpSink extends Closeable {
  BufferedSink sink();
  void headers(Headers headers);
}
```

It’s exposed on the `ResponseBody` and you can access it after you `execute()` or in the callback to `enqueue()`.

```
try (Response response = client.newCall(request).execute()) {
  HttpSink sink = response.duplexSink();
  ...
}
```

I’m using the word `HttpSink` here instead of `DuplexRequestBody` because I think it might be possible to use the same type in MockWebServer when sending these things.

### Response Has Trailer Callbacks

There’s an interface to get callbacks when trailers arrive and a mechanism to register it on the response body.

```
interface HeadersListener {
  void onHeaders(Headers headers);
}
```

```
response.body().headersListener(new HeadersListener() {
  @Override public void onHeaders(Headers headers) {
    System.out.println(headers);
  }
});
```

I’d like to avoid having the word “trailers” in the API because the HTTP/2 wire protocol allows ’em to come anywhere in the stream. Also it would be bad to have a variable called `trailers` with a type of `Headers`.

### onHeaders Arrives On The User’s Thread

I’d like to keep response reading single-threaded, but response readers get both bytes (via the `BufferedSource`) and headers. Rather than calling back with headers on another thread, we call back with headers while doing a blocking read of the response body.

Given this code:

```
response.body().headersListener(new HeadersListener() {
  @Override public void onHeaders(Headers headers) {
    System.out.println(Thread.currentThread() + "/headers: " + headers);
  }
});
System.out.println(Thread.currentThread() + "/body: " + response.body().readUtf8Line());
System.out.println(Thread.currentThread() + "/body: " + response.body().readUtf8Line());
```

It could print something like this:

```
main/body: hello
main/headers: grpc-status: 0
main/body: world
```

With this design you’ll not be notified of trailers unless you make a blocking call into the stream! Most of our code reads streams to the end so I don’t think this will be a problem.

# Etc.

### Interceptors Mostly Work

Interceptors will need to know to look for the response’s duplex sink instead of the request body. But if they do, they’ll be able to do interesting things like log or encrypt or compress that data. They need to just build a `HttpSink` decorator.

### Need a Solution For ‘Early’ Data

This design doesn’t have a place for the client to send messages to the server until it’s received the response headers. I’m tempted to allow these to keep their request body, and to use it as a prefix to the duplex stream. The biggest drawback of this is that it makes things more complex. For example, that early data’s content length is irrelevant, but still present and confusing. It would miserably fail on things like client-side gzip interceptors, for example.

That might be worthwhile regardless; the performance consequences are pretty huge.

### Blocking Still Sucks

This API presumes a lot of threads blocking on reads. Would be nice to have a mechanism in Okio. I reach for coroutines but actually wiring that up is nontrivial.

### Retrofit

It’s [madness](https://github.com/square/misk/blob/master/misk/src/main/kotlin/misk/grpc/GrpcClient.kt) to set gRPC headers and encode gRPC messages directly via OkHttp. Instead we need a nice Retrofit layer on top. Retrofit can accept the complexity of mapping a bytestream of framed gRPC messages into an `Observable<Taco>` or the framework du jour.

**Comment by yschimke** [comment]
FWIW I've used other http libraries in the past because of the lack of support for the bidirectional streams support.  It's a useful feature but does make it more complicated than the request/response model.

e.g. https://github.com/rsocket/rsocket-cli/blob/master/src/main/kotlin/io/rsocket/cli/http2/Http2DuplexConnection.kt

**Comment by swankjesse** [comment]
Yeah. That rsocket class has both Jetty and Netty. Yipes, I hope we can do smaller.

**Comment by MONIKA-KUMAR-JETHANI** [comment]
@yschimke Can I work on this?

**Comment by swankjesse** [comment]
@MONIKA-KUMAR-JETHANI nope, this is not appropriate for new contributors.

**Comment by yschimke** [comment]
@swankjesse I hope you can also, I'll happily cleanup and switch to OkHttp if you write this.  

Maybe consider how the approach would fit with https://github.com/square/okhttp/pull/4014, the RFC is now at version 7 and I'd consider very likely to pass since websockets should be capable of going over HTTP/2.  The RFC overall is not WebSockets specific though.

**Comment by swankjesse** [comment]
I’ve been working with @oldergod on implementing gRPC on OkHttp. We’ve learned that although the HTTP/2 transport layer permits multiple headers + data frames to be interleaved, the HTTP+HTTP/2 layering permits headers only before the data (headers) and after the data (trailers).

For HTTP requests there are no trailers after the request body.

Because duplex exists for gRPC and no other reason, we’re going to change our APIs to support that use case only. In particular, we need to:

1. Add an API for MockWebServer to enqueue the end-of-stream trailers. If trailers are to be provided they must be provided before the call to ResponseBody.close().
2. Add an API for OkHttp to collect the end-of-stream trailers. These may only be collected after the response body stream has been exhausted.

We may also want to consider an API for OkHttp to write the request body without our `RequestBody` callback. That API is inconvenient when streaming an arbitrarily-large request.

**Comment by swankjesse** [comment]
# 🎉

**Comment by oldergod** [comment]
yooooooooooooo

**Comment by lucianojoublanc-da** [comment]
Hi, I can't find a support channel so this seemed the best place to post this: Is there any documentation/examples for using okhttp as a grpc client? From the above it seems this is possible. How/what options would I need to pass to the client builder?

In my specific case I'm looking to do a cleartext h2c connection i.e. avoid the HTTP 1.1 to 2 'upgrade' handshake altogether.
