### ISSUE TITLE
Cancel request not working

### ISSUE THREAD

**Issue by Slake07** [square/okhttp#4268]
Before network call, I am checking if any request is running or in queue. If it founds then cancel it. but every time it returns 0 in runningCallsCount and queuedCallsCount even there is running network call. Below is code for cancelling request.

      fun cancelCallWithTag(client: OkHttpClient, tag: String) {

        Log.e("OKHTTPUTILS", "running: "+client.dispatcher().runningCallsCount())
        Log.e("OKHTTPUTILS", "queued: "+client.dispatcher().queuedCallsCount())

        for (call in client.dispatcher().queuedCalls()) {
            Log.e("OKHTTPUTILS", "queuedCalls cancelCallWithTag "+call.request().tag())
            if (call.request().tag() == tag)
                Log.e("OKHTTPUTILS", "call cancel: "+tag)
                call.cancel()
        }
        for (call in client.dispatcher().runningCalls()) {
            Log.e("OKHTTPUTILS", "runningCalls cancelCallWithTag "+call.request().tag())
            if (call.request().tag() == tag)
                Log.e("OKHTTPUTILS", "call cancel: "+tag)
                call.cancel()
        }
    }

The URL which i am calling is currently return timeout. So is it possible that in this case, request can't cancel.? Or there is any other bug.?

**Comment by shanyuliang** [comment]
@Slake07 , maybe that is because you are comparing tag by "==". Try use "equals()" method.

**Comment by Slake07** [comment]
> Executable test case?

What should i provide you?

**Comment by Slake07** [comment]
> @Slake07 , maybe that is because you are comparing tag by "==". Try use "equals()" method.

Then at least it should return runningCallsCount valid.

**Comment by swankjesse** [comment]
@Slake07 can you provide a self-contained executable test case that demonstrates the problem? You can start here: https://gist.github.com/swankjesse/981fcae102f513eb13ed

**Comment by Slake07** [comment]
@swankjesse https://gist.github.com/Slake07/d0c261cde3f2b6a9063d00c8d4be5940
Here it is.

**Comment by shanyuliang** [comment]
A @Synchronized function can not be executed concurrently. Even though you can call the `getRequest ` function multiple times in a short time but it always wait for the other `getRequest ` to finish. That is why the cancelling in `getRequest ` doesn't work, because by that time there is nothing to be cancelled.

**Comment by swankjesse** [comment]
@Slake07 you're cancelling the call before you enqueue or execute it, so the dispatcher doesn't know about it yet.

**Comment by Slake07** [comment]
@swankjesse Sorry i forgot to mention that i am cancelling previously called API. So when cancel method call that time already previous API will be running.

One more point i want to add here. That APIs which i am calling is right now return connection timeout. and I can only test when timeout occur otherwise it return fast response and i can't check if any API is running or not.

**Comment by swankjesse** [comment]
Could you provide an executable test case that fails in the same way as this bug report?

**Comment by Slake07** [comment]
I am just calling get API when screen opens. After that, user will go back and again open that screen and again that API will call. and at that time previous API was running.

**Comment by swankjesse** [comment]
Is this a bug report? If so, I need an executable test case so I know what to fix.

Otherwise I assume this is just a usage question and you should use StackOverflow for that.

**Comment by liupeng1991** [comment]
Hello, I have the same problem, have you solved it?If you have solved it, please reply to me. Thank you
