### ISSUE TITLE
A  bug

### ISSUE THREAD

**Issue by saefbadwan** [square/okhttp#4275]
if you called 
response.body().string()
twice you will get  weird error like this

> java.lang.IllegalStateException: closed

https://github.com/square/okhttp/issues/4172

**Comment by JakeWharton** [comment]
This is working as intended. A Response and its ResponseBody represent an active resource that is streamed from the server for performance. Once consumed, it cannot be reused.

This is documented here: http://square.github.io/okhttp/3.x/okhttp/okhttp3/ResponseBody.html
