### ISSUE TITLE
An explicitly set Cookie header is overwritten when using a CookieJar

### ISSUE THREAD

**Issue by nicktrav** [square/okhttp#4282]
If a `Request` contains a `Cookie` header, it is overridden by the values returned by the `CookieJar` (if one has been installed).

This issue is half "bug report" in the sense that the principle of least surprise would have me reason that a cookie header set _explicitly_ on a request would be honored when using a `CookieJar`, and half "question" in the sense that maybe this is actually intended behavior?

Here's a test case to reproduce what I'm noticing: https://github.com/nicktrav/okhttp/commit/1cc51f7c33e0d110e85e97cc51528685a6c1a565

The following is a naive patch I'd be happy to offer up, though this change in behavior might break existing clients, so I'm open to thoughts / ideas.

```diff
--- a/okhttp/src/main/java/okhttp3/internal/http/BridgeInterceptor.java
+++ b/okhttp/src/main/java/okhttp3/internal/http/BridgeInterceptor.java
@@ -82,7 +82,7 @@ public final class BridgeInterceptor implements Interceptor {
     }

     List<Cookie> cookies = cookieJar.loadForRequest(userRequest.url());
-    if (!cookies.isEmpty()) {
+    if (!cookies.isEmpty() && userRequest.header("Cookie") == null) {
       requestBuilder.header("Cookie", cookieHeader(cookies));
     }
```

Thanks!

**Comment by swankjesse** [comment]
We could union ’em. You’re allowed to have multiple `Cookie` headers. Want to submit a pull request?!

**Comment by nicktrav** [comment]
My understanding is that you can have multiple values in a single `Cookie` header (i.e. you can't have multiple `Cookie` headers, as per [RFC 6265][0]):

> When the user agent generates an HTTP request, the user agent MUST
> NOT attach more than one Cookie header

A union of the cookie values sounds reasonable! There's still the question of which cookie value is authoritative if the cookie value is in the `CookieJar` as well as set on the `Request`. Taking the value set on the `Request` would solve the issue in our case.

@yschimke - feel free to assign this one to me. I'll submit a patch in the next couple days.

[0]: https://tools.ietf.org/html/rfc6265#section-5.4

**Comment by yschimke** [comment]
I think @swankjesse is against "licking the cookie", If you are worried, then I suggest putting up a PR even if it's still WIP.  Not sure if there is some other process for square employees :)

**Comment by swankjesse** [comment]
As mentioned on PR #4490 I think it’s simpler to say “cookie jar _or_ user cookies, not both”.

@nicktrav if you’ve got insight we’re missing, please let me know!
