### ISSUE TITLE
Android Retrofit/OkHtp Use `8.8.8.8` programatically for DNS lookup?

### ISSUE THREAD

**Issue by sudhanshugaur4** [square/okhttp#4284]
I am trying to add Google DNS lookup which is '8.8.8.8.' in my android app, I am using Retrofit with OkHttp.

Is it possible programmatically?

I saw this post but wasn't able to add it https://garage.easytaxi.com/tag/dns-android-okhttp/

**Comment by swankjesse** [comment]
https://stackoverflow.com/questions/52458671/android-retrofit-okhtp-use-8-8-8-8-programatically-for-dns-lookup
