### ISSUE TITLE
Cleanup all threads (e.g. AsyncTimeout.Watchdog) on explicit shutdown

### ISSUE THREAD

**Issue by OlegYch** [square/okhttp#4293]
Currently i use this
```
    OkHttpClient client0 = ???
    client0.dispatcher.executorService.shutdown
    client0.connectionPool.evictAll
    client0.cache.close
```
but this is not enough since okhttp3.ConnectionPool#executor remains running
this is an issue because it prevents garbage collection of classloader which loaded okhttp
it would be nice to have a single close method which closes all connections and stops all threads started by okhttp
tested on 3.11.0

**Comment by Saladoc** [comment]
:+1: My application keeps on running for several minutes even after I have shut down the `ExecutorService` and evicted everything from the `ConnectionPool`. If I explicitly state that the connections are no longer necessary they should be cleaned up immediatly.

**Comment by yschimke** [comment]
@swankjesse I know we closed https://github.com/square/okhttp/issues/3372 because of sharing, but what about a shutdown method that is only valid on the original client?

**Comment by yschimke** [comment]
This should be fixed/improved with TaskRunner using more daemon threads.  And we deliberately don't have a simple close method given it's awkward with our current model of sharing involving client.newBuilder() etc.

**Comment by OlegYch** [comment]
the issue with collecting garbage is not fixed though

**Comment by yschimke** [comment]
Can you test against 4.3 and identify what's still running or holding onto things after the steps listed in the original report are run?

**Comment by yschimke** [comment]
@OlegYch I think the task runner cleanup should fix this. Specifically before the TaskRunner changes, I think some threads persisted. Can you reopen if it's still a problem.  

My conjecture is that if you shutdown the dispatcher, and you let the client be garbage collected.  You shouldn't retain running threads or objects.

**Comment by OlegYch** [comment]
@yschimke there is a okio.AsyncTimeout.Watchdog thread still running after shutting down the dispatcher
it takes a while for it to shutdown, but after that the classloader can be collected
would be nice to be able to interrupt it immediately

**Comment by yschimke** [comment]
@OlegYch fair point. 

BTW this it isn't a high priority at the moment, but if you follow the steps above, we should try to shutdown threads etc so we are good citizens in containers (build systems or web servers etc)

**Comment by yschimke** [comment]
We now use daemon threads for clients.

**Comment by OlegYch** [comment]
@yschimke i'm not sure how daemon threads are relevant
afaik they are only useful if you want jvm to shutdown, the issue was about releasing resources without shutting down the vm

**Comment by yschimke** [comment]
@swankjesse just refactored the TaskRunner API.  That final AsyncTimeout.Watchdog thread is probably one to raise with okio.

If you read above, all other cases should be handled.

To be honest, I don't think we have further plans for changes here in near term. So I'm mostly being honest.

**Comment by OlegYch** [comment]
fair enough
