### ISSUE TITLE
[Feature Request] Reduce connection pool threads

### ISSUE THREAD

**Issue by r16turbo** [square/okhttp#4308]
I'm trying to create a test tool that will run many **OkHttpClient**'s.

Since the number of **Connection Pool** threads is proportional to the number of clients, the debugger is heavy as the number of clients increases. I would like to reduce the number of threads and operate many clients.

The following is a patch:
https://github.com/r16turbo/okhttp/commit/c634726e6fa2d99ea5b0ffbcb330ad0b9daf8b8a

Example:
```java
package test;

import java.io.IOException;
import java.util.stream.IntStream;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.Response;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

public class Test {

  private static final Logger logger = LogManager.getLogger(Test.class);

  public static void main(String[] args) throws Exception {
    final Request request = new Request.Builder()
        .url("http://localhost").get()
        .build();

    IntStream.range(0, 10000).parallel()
        .mapToObj(i -> new OkHttpClient.Builder().build())
        .forEach(client -> {
          try (Response response = client.newCall(request).execute()) {
            logger.trace("{}", response);
          } catch (IOException e) {
            logger.catching(e);
          }
        });
    // here: 10,000 Connection Pool threads!
  }
}
```

**Comment by swankjesse** [comment]
This doc might help:
https://square.github.io/okhttp/3.x/okhttp/okhttp3/OkHttpClient.html

**Comment by r16turbo** [comment]
Thanks for your support.

I understood as follows:
Since OkHttpClient needs to be shared, it can not be used for a test tool that runs many clients.

**Comment by swankjesse** [comment]
You just need to make a singleton OkHttpClient somewhere in your test infrastructure.

**Comment by r16turbo** [comment]
The test tool wanted to have a separate **Connection Pool** for each client. Therefore, it was necessary to have multiple (**non singleton**) client instances.

Since the above patch worked well, I submitted this request.

but, I understand that it is a usage not in **OkHttpClient**'s requirement (_**OkHttpClients should be shared**_), so I will cancel this proposal.
