### ISSUE TITLE
[FR] Asterisk-Form OPTIONS Requests

### ISSUE THREAD

**Issue by cbrockington** [square/okhttp#4310]
What kind of issue is this?
 - [X] Feature Request.

Support for the asterisk-form of a request-target.

As specified in https://tools.ietf.org/html/rfc7230#section-5.3 the request-target can take an asterisk-form (`*`), this is particularly useful when sending `OPTIONS` requests in order to query the server as a whole, rather than a specific resource.  Currently a url with a path must either be provided (and start with a `/`) or if none is given a path of `/` is used, providing no mechanism to query the `*` resource uri.

**Comment by swankjesse** [comment]
Really tough to think through how we’d express this.

**Comment by swankjesse** [comment]
We've completely painted ourselves in a corner making this very difficult to support. I regret that this won't be ready any time soon.

**Comment by yschimke** [comment]
Won't fix.
