### ISSUE TITLE
Incomplete ResponseBody documentation: what to do when body is not fully consumed?

### ISSUE THREAD

**Issue by ivanr** [square/okhttp#4311]
I am trying to understand what to do when I don't want to read the entire response body, and the ResponseBody documentation doesn't provide any guidance. If the entire response body hasn't been read, I don't want the connection to go back to the pool, because whoever reads from the same TCP connection next might not get what they expect. I would also prefer okhttp not to read the entire response body, but in that case it's best to close the faulty connection.

**Comment by swankjesse** [comment]
You're thinking too much about the implementation of HTTP/1.1 connection pooling. You can just close the response body and OkHttp will do the right thing.

**Comment by ivanr** [comment]
That's great, but may I suggest that you add at least a sentence to document what's going to happen. Otherwise, it's my job to assume the worst. If OkHttp does indeed do the right thing, having it documented would have saved me some work looking for an answer and then handling the situation in my code. :)

(Yes, I am thinking about HTTP/1.1 connection pooling, because I expect that's what we'll be chiefly connecting to for a few more years.)

**Comment by swankjesse** [comment]
Pull request?

**Comment by ivanr** [comment]
Sorry, in this particular instance I can only pay it forward. If a pull request were within my current OkHttp knowledge, you would have had it already. But I've written only about 10 lines of code so far; to add to the docs would require a deep dive into the internals, which requires time I don't have.

**Comment by yschimke** [comment]
No PR, hasn't come up elsewhere and we do the default sensible thing for both HTTP/1.1 and HTTP/2.
