### ISSUE TITLE
LoggingEventListener

### ISSUE THREAD

**Issue by swankjesse** [square/okhttp#4315]
We should make one and make it very easy to install.

**Comment by amirlivneh** [comment]
This can be useful for us too. I can send a PR for a basic implementation. Initially, it can have output similar to that of `HttpLoggingInterceptor`. It can then be incrementally improved to leverage all `EventListener`'s callbacks. The API can be something like:

```
import okhttp3.logging.LoggingEventListener.Factory;

LoggingEventListener.Factory loggingEventListenerFactory =
    new LoggingEventListener.Factory()
        .setLevel(LoggingEventListener.Level.HEADERS);

OkHttpClient client = new OkHttpClient.Builder()
      .eventListenerFactory(loggingEventListenerFactory)
      .build();
```

Alternatively, the API can be more concise and emphasize the feature's functionality over the implementation detail of using `EventListener`:

```
import okhttp3.logging.CallLogger;

CallLogger callLogger =
     new CallLogger().setLevel(CallLogger.Level.HEADERS);

OkHttpClient client = new OkHttpClient.Builder()
      .eventListenerFactory(callLogger.eventListenerFactory())
      .build();
```

To make it easier to install, we can have:
```
    OkHttpClient.Builder builder = new OkHttpClient.Builder();
    callLogger.install(builder);
```
But this may be redundant.

Let me know if one of these work.

**Comment by yschimke** [comment]
A basic one would be really useful.  No objection if we stop there.

If we start thinking about anything more a few features I'd love to see included in this

1) Making it useful for us in getting bug reports e.g. output device details, handshake details.
2) Dynamically Filterable e.g. log requests to a set of site (Function<Request, Boolean>)
3) After the fact logging e.g. for long running requests, failed requests.

**Comment by amirlivneh** [comment]
Any thoughts on the API options?

**Comment by swankjesse** [comment]
Love it. Thanks @amirlivneh !
