### ISSUE TITLE
"Transfer-Encoding" silently removed from POST requests

### ISSUE THREAD

**Issue by birukoff** [square/okhttp#4318]
"Transfer-Encoding" is silently removed from POST requests when they are executed. Possibly, a bug in OkHttp.
See gist with test:
https://gist.github.com/birukoff/70c35b3ea754bff5cfaff242e63d6c66
Versions tested: 3.9.1, 3.11.0

**Comment by swankjesse** [comment]
This is working as designed. I think the header you want is `Content-Encoding`, not `Transfer-Encoding`.
