### ISSUE TITLE
Feature Request: option to disable sni

### ISSUE THREAD

**Issue by updatede** [square/okhttp#4324]
Since dns query is encrypted, tls 1.3 encrypt certificates, sni is the only info that leak server name, and sni encryption is under way of being rfc standard, before that universally implemented, please add a option to not send sni extension, there is no need of sni for non virtual web server.

**Comment by swankjesse** [comment]
If it's a non virtual web server you can make the request by IP address?

**Comment by updatede** [comment]
Yes of course. But maybe should ask dns inventor why we use name not ip address to visit server. I think at least include that name friendly than ip address, and there's no need to tell all your visitor the new ip address and issue a new certificate for that new ip address everytime it changes. I think we can keep server name unknown to intermediate party at the same time benefit from server name. That's why we create dns over https and yet encrypted sni.

**Comment by updatede** [comment]
Maybe should abandon dns , just use ip address ? I think most people won't want it.

**Comment by updatede** [comment]
@swankjesse still don’t know what do you mean.  l need okhttpclient not send sni extension, how anything to do with rewriting request url ? I have no ip certificate, only domain name certificate. okhttpclient can make request using ip address but verify certificate using domain name ? how to do it ?  i don’t know.

**Comment by swankjesse** [comment]
@yschimke thoughts?

**Comment by yschimke** [comment]
Trying to remember how SNI works on all platforms

 * <h3>Server name indication (SNI)</h3>
 * Supported on Android 2.3+.
 * Supported on OpenJDK 7+

IIRC

For JVM 7+, it's implicit via https://github.com/square/okhttp/blob/de4acc58bbe8d20853502b67c5d1dc8ea26c0fef/okhttp/src/main/java/okhttp3/internal/connection/RealConnection.java#L307

For Android and Conscrypt it's done via the Platform hook
https://github.com/square/okhttp/blob/5b37cda9e00626f43acf354df145fd452c3031f1/okhttp/src/main/java/okhttp3/internal/platform/AndroidPlatform.java#L121
https://github.com/square/okhttp/blob/de4acc58bbe8d20853502b67c5d1dc8ea26c0fef/okhttp/src/main/java/okhttp3/internal/platform/ConscryptPlatform.java#L69

Changing the code to support this as a flag, doesn't sound great to me.

**Comment by yschimke** [comment]
n.b. I think you can achieve something similar via the domain fronting style, but will require testing.  I think it should work.

https://github.com/square/okhttp/pull/3108/files

**Comment by yschimke** [comment]
SNI is now implicit on all platforms.  Domain fronting works if you have a willing host.  Dns over Https is supported.

Closing this.

Next jump would probably activate ESNI when Conscrypt supports.

**Comment by panthony** [comment]
I stumbled upon this issue, I was also looking at a way to disable SNI due to this website that fails the SSL handshake if the host is provided:

https://www.juwelier-boeckelmann.de

Using OkHttpClient, it fails with the same error I had with Apache HttpClient (until I omit the "host" when opening the SSL socket).

```
Suppressed: javax.net.ssl.SSLHandshakeException: Received fatal alert: illegal_parameter
		at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
		at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:117)
		at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:340)
		at java.base/sun.security.ssl.Alert$AlertConsumer.consume(Alert.java:293)
```

It works with `okurl` though I'm not sure why.

**Comment by tishma** [comment]
@panthony I know it's almost a year, but in case you're still wondering, this may be the solution to this: #7873

**Comment by yschimke** [comment]
How does your JVM disable it by default? Is it set as a system property in your launcher?

**Comment by tishma** [comment]
No idea... My work is pretty much higher level than dealing with launcher,
so I can't tell where it was turned off, but I also doubt it was off - on
purpose. Again IntelliJ bundled JDK 11 and production Ubuntu one had it
both disabled, so to me - it's normally disabled :)

**Comment by tishma** [comment]
Is it possible that most of the popular Java frameworks (neither of which
I'm using) are just silently turning SNI extension on under the hood?
