### ISSUE TITLE
Slow creating new instance of OkHttpClient()

### ISSUE THREAD

**Issue by tprochazka** [square/okhttp#4337]
Creating a new instance of OkHttpClient is very slow because initializing HTTPS support probably. It spends more than 500ms in CipherSuite class. I understand that it is probably important, but why it happens directly when a new instance is created and not during first HTTP request which happens every time on a background thread. It is very unusual, to do such time complex operation directly after the instance is created.

**Comment by tprochazka** [comment]
Here is trace file https://www.dropbox.com/s/50eupuup8bplks8/okhttp.zip?dl=1

**Comment by yschimke** [comment]
https://aflame.rhye.org/trace/8D0D69D9EB476C425549B8B815477FA8

![image](https://user-images.githubusercontent.com/231923/47542468-76f1ec80-d8d5-11e8-84dc-123db067c98e.png)

**Comment by yschimke** [comment]
I think there is an easy win here.  Stop using a TreeMap, change the static fields from a normal lookup to an (assumed to be unique) insert.  Then on lookup, check the happy path first, and on failure, do a secondary lookup s/TLS_/SSL_/ or s/SSL_/TLS_/. 

@swankjesse thoughts?

**Comment by yschimke** [comment]
On a desktop mac, roughly representation numbers

Before: Init Took 2.373407ms
After: Init Took 0.453405ms

**Comment by yschimke** [comment]
@tprochazka What device did you profile on?

**Comment by yschimke** [comment]
This is still a tiny amount of time relative to the first actual use of the native TLS library, which is roughly 100x more expensive and happens on first request.

**Comment by tprochazka** [comment]
The Trace is from Samsung S8+

**Comment by swankjesse** [comment]
@yschimke thumbs up on making things faster!
