### ISSUE TITLE
Unnecessary call to KeyManagerFactory.init in CustomTrust recipe

### ISSUE THREAD

**Issue by uce** [square/okhttp#4370]
I think that lines 193–195 in the `CustomTrust` recipe are unnecessary, because they are not relevant for initializing the trust managers:

https://github.com/square/okhttp/blob/9f9903e7a36a6b2d7944dc12bac4344b68643d8f/samples/guide/src/main/java/okhttp3/recipes/CustomTrust.java#L195

I've verified that running the recipe works as expected without these lines. I'm not too familiar with the Java security APIs. Therefore, feel free to close this ticket in case I'm mistaken.

**Comment by yschimke** [comment]
Yep, I think as an example however it should probably be fixed to pass in the key manager in line 48 requiring some refactoring of the methods.

**Comment by swankjesse** [comment]
Send a pull request?

**Comment by yschimke** [comment]
Working on a samples cleanup https://github.com/square/okhttp/pull/5699
