### ISSUE TITLE
Check for unused enqueued responses on mockwebserver after test

### ISSUE THREAD

**Issue by rowanseymour** [square/okhttp#4383]
Maybe I'm missing something but I'm not seeing any way to check at the end of a test that there aren't any unused responses. I don't always want to have to check the details of each recorded request, and it would be useful to just assert that the responses we're all used and won't leak into the next test if I'm re-using the same mock server.

**Comment by swankjesse** [comment]
Write a custom dispatcher? Or use the QueueDispatcher and confirm that peek() returns null?

**Comment by rowanseymour** [comment]
Doesn't seem like there's any way to access the dispatcher. I get that I can do this with custom queue dispatcher, it just seems like it should be standard practice to check all enqueued responses were used as expected, so I was wondering if there wasn't a simpler way to do it.
