### ISSUE TITLE
Question:  Is there documentation on the usage pattern for OkHttpClient?

### ISSUE THREAD

**Issue by memebag** [square/okhttp#4389]
I'm using OkHttpClient because RingCentral uses that inside their API.  I'm just trying to send and receive FAXes inside a Java enterprise application.

I'm able to use OkHttpClient, but it spawns threads that never die.  I read [this issue](https://github.com/square/okhttp/issues/3372) and see that OkHttpClient spawns its own connection pool and other things.  I tried shutting it down using 

     client.dispatcher().executorService().shutdown();
     client.connectionPool().evictAll();
     client.cache().close();

but that last call throws a NullPointerException.

Is there someplace that documents the expected usage pattern for OkHttpClient used inside an enterprise app?  Am I supposed to reuse one instance?  Is there a way to configure and manage the connection pool?

**Comment by swankjesse** [comment]
See this?
https://square.github.io/okhttp/3.x/okhttp/okhttp3/OkHttpClient.html

**Comment by memebag** [comment]
Yes, I saw that, but it doesn't address thread safety, connection management or now to avoid starting new threads.  In an enterprise app, there should be one instance of the connection pool and multiple, thread safe clients.  EJBs should not start new threads.  I don't see anything in the documentation about how to make that work.  Am I missing something?

**Comment by swankjesse** [comment]
Creating an OkHttpClient will create threads. Trying to think through how I can better document this without overwhelming.

**Comment by memebag** [comment]
I understand that creating an OkHttpClient starts threads.  EJBs are not supposed to start threads.

If OkHttpClient can't be used from EJBs, that's OK.  We can write our own REST code using the Apache HTTP client.  OkHttp is just what RingCentral uses in the JAR they provide to developers.

**Comment by swankjesse** [comment]
You can probably also find a way to create threads with your EJBs.

**Comment by memebag** [comment]
The [Java Platform Enterprise Edition docs](https://docs.oracle.com/javaee/7/tutorial/concurrency-utilities001.htm) say not to create Thread objects from EJBs.  Managing concurrency inside an enterprise app is more complicated that starting a thread that never dies.

**Comment by swankjesse** [comment]
Yeah, those docs are advocating for patterns that make little sense in 2018. The motivation to avoid creating threads was so that an app container could unload an app. Today we solve such problems with load balancers and/or kubernetes.

**Comment by memebag** [comment]
So, to sum up:

1.  OkHttpClient shouldn't be used in EJBs.  Neither should RingCentral's Java library, since it depends on OkHttpClient.
2.  JPEE products should be abandoned/rewritten because 2018.

Gotcha.

**Comment by swankjesse** [comment]
Actually I think you should probably just start threads in your J2EE container and discover that . . . . it just works?

**Comment by memebag** [comment]
We will use an Apache HTTP client with a connection pool we can configure.  It doesn't start any threads, so there's no risk of threads accumulating as we redeploy apps or their plugin modules.  All the RingCentral library does is hide some REST interaction with their server.

**Comment by swankjesse** [comment]
Gotcha. OkHttp also creates threads for async calls, for write timeouts, and for HTTP/2. I assume Apache HTTP either doesn't have these features or somehow implements them without threads.

Doing fancy stuff requires threads; refusing them seems to me like an unnecessary constraint that may make your project worse.

**Comment by memebag** [comment]
Apache uses the java.util.concurrent package.  If you read the Oracle doc I linked, it explains why it's safe to use java,util.concurrent with JPEE.
