### ISSUE TITLE
Tunnel with proxy required for WS (HTTP) WebSocket

### ISSUE THREAD

**Issue by pasin** [square/okhttp#4390]
Currently OKHTTPhttp sends `CONNECT` request to the proxy to create a tunnel only when SSL is used. However when using WebSocket that is required the protocol to be upgraded, a tunnel is required by some proxies (e.g. Squid), otherwise the`Upgrade` headers will not be forwarded to the remote server correctly. Can OKHTTP create a tunnel with the proxy regardless of SSL being used?

**Comment by swankjesse** [comment]
It’s 2018. Please use SSL.

**Comment by pasin** [comment]
Yeah, I knew. But HTTP is still around and commonly used in development so I guessed there is still a reason to support HTTP.

**Comment by swankjesse** [comment]
Hang on – are you using Squid in development?

**Comment by swankjesse** [comment]
I don’t think we’re going to take further action on this. Tunnels for plaintext add more complexity than they’re worth. HTTPS is great!
