### ISSUE TITLE
[bug]FormBody charset

### ISSUE THREAD

**Issue by gMan1990** [square/okhttp#4393]
https://github.com/square/okhttp/blob/c273b3be385383842e44d25d6b7ca137ff6b1076/okhttp/src/main/java/okhttp3/FormBody.java#L50
https://github.com/square/okhttp/blob/c273b3be385383842e44d25d6b7ca137ff6b1076/okhttp/src/main/java/okhttp3/FormBody.java#L58

code
```java
FormBody.Builder utf8FormBodyBuilder = new FormBody.Builder(StandardCharsets.UTF_8).add("name", "中");
FormBody utf8FormBody = utf8FormBodyBuilder.build();
System.out.println(utf8FormBody.value(0));
FormBody.Builder gbkFormBodyBuilder = new FormBody.Builder(Charset.forName("GBK")).add("name", "中");
FormBody gbkFormBody = gbkFormBodyBuilder.build();
System.out.println(gbkFormBody.value(0));
```

output
```text
中      // right
��   // error, should be 中
```

**Comment by swankjesse** [comment]
Yep. Unfortunately the charset is used for encoding only. We don’t retain it in the FormBody object. We should figure out if `application/x-www-form-urlencoded` accepts a charset.

Also – you should consider switching to UTF-8. It’s the only charset anyone should use.

**Comment by andrew-qiu** [comment]
> Yep. Unfortunately the charset is used for encoding only. We don’t retain it in the FormBody object. We should figure out if `application/x-www-form-urlencoded` accepts a charset.
> 
> Also – you should consider switching to UTF-8. It’s the only charset anyone should use.

Has this bug been fixed? I really need the framework support:
Content-Type: application/x-www-form-urlencoded; charset=UTF-8

**Comment by gMan1990** [comment]
@andrew-qiu default is "UTF-8",( if you use other charset, that will be bug...

**Comment by andrew-qiu** [comment]
> @andrew-qiu default is "UTF-8",( if you use other charset, that will be bug...

Could you give me an alternative solution? I found almost all of web servers working in my corp only support the explicit format:
Content-Type: application/x-www-form-urlencoded; charset=UTF-8

'Content-Type: application/x-www-form-urlencoded' would lead to apparently unreadable Chinese code.

**Comment by gMan1990** [comment]
@swankjesse https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Type

**Comment by andrew-qiu** [comment]
> @swankjesse https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Type

It's Ok. I think I had just used an inappropriate framework.

**Comment by yschimke** [comment]
Closing, no plans to change and we have closed other related issues https://github.com/square/okhttp/issues?q=is%3Aissue+charset+formbody
