### ISSUE TITLE
why okhttp maxRequests is 64 and maxRequestsPerHost is 5? 

### ISSUE THREAD

**Issue by youuupeng** [square/okhttp#4404]
why okhttp maxRequests is 64 and maxRequestsPerHost is 5? Is there any foundation why the value is 64 and 5?

**Comment by swankjesse** [comment]
Historical decision plus inertia. I'm hoping to adjust these in an upcoming release, but I want to do some benchmarking so I can provide opinionated recommendations to users.

Tracking here:
https://github.com/square/okhttp/issues/4354
