### ISSUE TITLE
Use github issue templates

### ISSUE THREAD

**Issue by yschimke** [square/okhttp#4412]
Compare https://github.com/Homebrew/brew/issues/new/choose

to

https://github.com/square/okhttp/issues/new

**Comment by yschimke** [comment]
Config from Homebrew https://github.com/Homebrew/brew/blob/master/.github/ISSUE_TEMPLATE/Reproducible-Bug-Report.md

**Comment by yschimke** [comment]
Docs are here https://help.github.com/articles/creating-issue-templates-for-your-repository/

and https://blog.github.com/2016-02-17-issue-and-pull-request-templates/

**Comment by yschimke** [comment]
n.b. I don't have rights, but the flow involves a PR, so I'm happy to review.

**Comment by swankjesse** [comment]
Done! https://gist.github.com/swankjesse/981fcae102f513eb13ed

**Comment by swankjesse** [comment]
Done! https://github.com/square/okhttp/issues/new/choose

**Comment by yschimke** [comment]
Nice.

FWIW while I agree with the sentiment "Bug reports must include a failing test!", it is strong wording.  But I'll defer to your judgement, I could go either way on whether to require.

**Comment by swankjesse** [comment]
https://github.com/square/okhttp/pull/4505/files
