### ISSUE TITLE
MockWebServer + HTTP/2 + UNIX sockets

### ISSUE THREAD

**Issue by swankjesse** [square/okhttp#4419]
I don’t think this works. We should add a test to confirm that it does.

**Comment by swankjesse** [comment]
Looks like we might crash trying to figure out what the remote hostname is. We only need this to name threads; we could fall back to something else.
```
java.lang.ClassCastException: jnr.unixsocket.UnixSocketAddress cannot be cast to java.net.InetSocketAddress
    at okhttp3.internal.http2.Http2Connection$Builder.socket(Http2Connection.java:559)
    at okhttp3.mockwebserver.MockWebServer$3.processConnection(MockWebServer.java:501)
```

**Comment by kikin81** [comment]
We are facing numerous crashes related to your comment
`java.lang.ClassCastException: jnr.unixsocket.UnixSocketAddress cannot be cast to java.net.InetSocketAddress`

We are using version 3.9.0 of the library.

**Comment by swankjesse** [comment]
@kikin81 please report the bug to the device makers?

@amirlivneh no. We won't need a dependency from MockWebServer to fix this bug.

**Comment by amirlivneh** [comment]
@swankjesse, ignore the mention of MockWebServer. But in whatever module this new test will be added, it will need to use `UnixDomainSocketFactory` and `UnixDomainServerSocketFactory` to reproduce the issue, right?

**Comment by swankjesse** [comment]
I don't want to test all possible Socket implementations; the UNIX socket sample is just intended to show where OkHttp’s extension points are.

**Comment by amirlivneh** [comment]
> We should add a test to confirm that it does.

OK, my understanding of your statement in the issue description was that you’re suggesting to add a unit test that confirms that MockWebServer + HTTP/2 + UNIX socket works.
