### ISSUE TITLE
ProGuard can’t find IgnoreJRERequirement (Misconfigured?)

### ISSUE THREAD

**Issue by amalive** [square/okhttp#4424]
What kind of issue is this?

 - [ ] Question. This issue tracker is not the place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use Stack
       Overflow. https://stackoverflow.com/questions/tagged/okhttp

 - [x] Bug report. If you’ve found a bug, spend the time to write a failing test. Bugs with tests
       get fixed. Here’s an example: https://gist.github.com/swankjesse/981fcae102f513eb13ed

 - [ ] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
       already exists! Don’t send pull requests to implement new features without first getting our
       support. Sometimes we leave features out on purpose to keep the project small.

I just update the latest version, but then I got this error when try to build my project

**okhttp3.OkHttpClient$Builder: can't find referenced class org.codehaus.mojo.animal_sniffer.IgnoreJRERequirement**

**Comment by swankjesse** [comment]
Ahh, it's a ProGuard problem! That's what I was missing.

**Comment by yschimke** [comment]
Won't fix.
