### ISSUE TITLE
EventListener callStart should only fire if we go to network 

### ISSUE THREAD

**Issue by ZacSweers** [square/okhttp#4441]
Per @swankjesse 

> we might need to move the callStart callback to only occur if you actually use the network

**Comment by yschimke** [comment]
Would it be more useful to keep callStart, callEnd marking the start and end for clients, but expose an event for a cache hit instead?

**Comment by swankjesse** [comment]
The issue here is we don't even get that far. One of the user’s interceptors short-circuits before a connection is opened.

**Comment by swankjesse** [comment]
No, cache hits will work too. Only thing is broken is if an application interceptor doesn't call proceed().

**Comment by swankjesse** [comment]
Fixed!
https://github.com/square/okhttp/pull/4630/files#diff-1bace3b10780b6d78dca6b26ce001321R1171
