### ISSUE TITLE
Backsplash is not encoded when used as a path segment

### ISSUE THREAD

**Issue by dmitrikudrenko** [square/okhttp#4446]
Backsplash is recognized as delimeter and the path `/<>.,\|*/1.jpg` is converted in `/%3C%3E.,/%7C*/1.jpg` that's not correct

**Comment by swankjesse** [comment]
Executable test case please.

**Comment by dmitrikudrenko** [comment]
https://github.com/dmitrikudrenko/Okhttpsample-4446/blob/master/app/src/test/java/io/github/dmitrikudrenko/okhttp_sample/HttpUrlTest.java

**Comment by swankjesse** [comment]
Did you want addPathSegment() not addPathSegments() ?

**Comment by dmitrikudrenko** [comment]
No, I didn't. addPathSegment makes `http://example.com/%3C%3E.,%5C%7C*%2F1.jpg`, without `/` before filename `1.jpg`
