### ISSUE TITLE
ResponseBody charStream() and string() don't behave as described

### ISSUE THREAD

**Issue by schildbach** [square/okhttp#4456]
https://github.com/square/okhttp/blob/307e619ebea5ff9eb297a013315716ce15e43545/okhttp/src/main/java/okhttp3/ResponseBody.java#L151

https://github.com/square/okhttp/blob/307e619ebea5ff9eb297a013315716ce15e43545/okhttp/src/main/java/okhttp3/ResponseBody.java#L162

These Javadocs do not describe the actual behavior. In fact, a BOM takes precendence over a defined charset in the Content-Type header. This is an obvious result of the implementation of `Utils.bomAwareCharset()`.

To fix this, I would suggest fixing the implementation (rather than fixing the Javadocs), as the described behaviour is more useful than the actual implementation.

**Comment by swankjesse** [comment]
Is this a problem in practice? What’s the BOM and the reported charset?

**Comment by swankjesse** [comment]
Could you create an executable test case?

**Comment by schildbach** [comment]
I was writing an Interceptor that takes an XML encoding from its pragma and puts it into the Content-Type header. Turns out okhttp is ignoring my Content-Type because the body has a BOM.

**Comment by schildbach** [comment]
Indeed, that's my advice too.

**Comment by swankjesse** [comment]
We should fix the documentation to mention how BOMs are used.
