### ISSUE TITLE
logger buffer if requestBody.contentLength()>0

### ISSUE THREAD

**Issue by gMan1990** [square/okhttp#4495]
https://github.com/square/okhttp/blob/ab605ab8c537c403eb9368485cc5b47864ef87bd/okhttp-logging-interceptor/src/main/java/okhttp3/logging/HttpLoggingInterceptor.java#L212
to(maybe)
```java
if(requestBody.contentLength()>0){
    logger.log(buffer.readString(charset));
}
```
ignore logger output empty line.

**Comment by swankjesse** [comment]
To clarify: the request is to not emit an empty line?

**Comment by gMan1990** [comment]
code like this with retrofit:
```
public interface DemoService {
  @POST("https://httpbin.org/post")
  Call<Object> post(@Query("a") String a);
}
```

**Comment by gMan1990** [comment]
@swankjesse no, not empty line, test code like this with retrofit:
```java
public interface DemoService {
  @POST("https://httpbin.org/post")
  Call<Object> post(@Query("a") String a);
}
```

**Comment by yschimke** [comment]
I think any changes to HttpLoggingInterceptor should probably come via copying and changing to your desired behaviour.  Leaving the current implementation simpler as a demo is the current plan.
