### ISSUE TITLE
SOCKS cannot be used below android7.0,  More than 7.0 is successful.

### ISSUE THREAD

**Issue by alless1** [square/okhttp#4496]
These codes are working normally greater than or equal to android7.0, but exceptions are reported on systems below 7.0, " java.net.UnknownHostException: Host is unresolved: 106.**.**.**"
I really don't know what the problem is. I hope I can get help. Thank you very much.

        java.net.Authenticator.setDefault(new java.net.Authenticator() {
            private PasswordAuthentication authentication = new PasswordAuthentication(mSocksInfo.getUser(), mSocksInfo.getPassword().toCharArray());

            @Override
            protected PasswordAuthentication getPasswordAuthentication() {
                return authentication;
            }
        });
        OkHttpClient client = new OkHttpClient.Builder()
                .proxy(new Proxy(Proxy.Type.SOCKS, new InetSocketAddress(mSocksInfo.getAddress(), mSocksInfo.getPort())))
                .build();
        Request request = new Request.Builder().url(mUrl).get().build();
        client.newCall(request).enqueue(new Callback() {
            @Override
            public void onFailure(Call call, IOException e) {
                //java.net.UnknownHostException: Host is unresolved: 106.**.**.**
            }

            @Override
            public void onResponse(Call call, Response response) throws IOException {

            }
        });

**Comment by swankjesse** [comment]
Arg, our old friend unresolved SOCKS addresses. What are you using SOCKS for? And what version?
See also https://github.com/square/okhttp/issues/1359

**Comment by alless1** [comment]
@swankjesse 
Thank you for your reply. I don't know. Under Android 7.0, socks V4 will be used by default? If you use socket directly, you can specify the version of the protocol as v5, os. write (new byte []{0x05, 0x01, 0x02}); it also works well. But with OKhttp, how do you specify socks v5?

**Comment by alless1** [comment]
@swankjesse 
I looked at the previous content, as if to say that only jdk9 or above can support socks4? But Android platform can only use jdk8, I see the use of custom socketfactory, but still not.
    @Override
    public Socket createSocket() {
        Socket socket = null;
        try {
            socket = new Socket();
            SocksInfo socks = getSocks();
            SocketAddress socketAddress = new InetSocketAddress(socks.getAddress(), socks.getPort());
            socket.connect(socketAddress);
            //socks5 authentication
            chooseAuthentication(socket.getInputStream(), socket.getOutputStream(), socks.getUser(), socks.getPassword());
        } catch (IOException e) {
            e.printStackTrace();
        }

        return socket;
    }

Report wrong：Already connected
I don't know if there are any good ways and suggestions on Android 7.0 below. Thank you

**Comment by alless1** [comment]
@swankjesse
I know how to implement the socks protocol, but how to pass the authenticated socket to okhttp?

**Comment by yschimke** [comment]
@alless1 We are building with JDK11 now, if you are careful about not putting this on a normal codepath, do you think you can get this working?

e.g. https://github.com/square/okhttp/blob/master/okhttp/src/main/java/okhttp3/internal/platform/Jdk9Platform.kt

**Comment by yschimke** [comment]
Closing this out, I don't think we have any plans to extend our Socks support on legacy Android versions.

OkHttpClient supports both proxy (Proxy.SOCKS) and socketFactory (custom socket factory) that can help here.
