### ISSUE TITLE
FATAL EXCEPTION when using okhttpclient with conscrypt

### ISSUE THREAD

**Issue by updatede** [square/okhttp#4510]
I want tls 1.3 so I use conscrypt, according to TestTls13Request.java I use : 
`Security.insertProviderAt(Conscrypt.newProviderBuilder().provideTrustManager().build(), 1)`
but it crashed, here is log 
```
AndroidRuntime: java.lang.NoClassDefFoundError: org.conscrypt.TrustManagerImpl
AndroidRuntime: 	at org.conscrypt.TrustManagerFactoryImpl.engineGetTrustManagers(TrustManagerFactoryImpl.java:87)
AndroidRuntime: 	at javax.net.ssl.TrustManagerFactory.getTrustManagers(TrustManagerFactory.java:219)
AndroidRuntime: 	at okhttp3.internal.Util.platformTrustManager(Util.java:667)
AndroidRuntime: 	at okhttp3.OkHttpClient.<init>(OkHttpClient.java:257)
AndroidRuntime: 	at okhttp3.OkHttpClient$Builder.build(OkHttpClient.java:1040)
```
There is no excepiton if I use this instead: 
`Security.insertProviderAt(new org.conscrypt.OpenSSLProvider(), 1);`
but okhttpclient use tls 1.2 to handshake not 1.3

**Comment by swankjesse** [comment]
I don't think we test or support user-provided Conscrypt on Android. Instead we only test Conscrypt on desktop Java.

It's worth considering and might be easy. But today you’re doing something OkHttp isn’t expecting.

**Comment by swankjesse** [comment]
Unclear what action to take here.

**Comment by schildbach** [comment]
@swankjesse I think it's up to you (OkHttp) to explain the steps needed to get TLSv1.3 working on Android 8/9. I'm using OkHttp 3.12.2, `ConnectionSpec.RESTRICTED_TLS` and an TLSv1.3-capable nginx on the other side, but still OkHttp always negotiates TLSv1.2.

**Comment by yschimke** [comment]
I’ve done most of the integration of conscript but on JVM. If you just want TLS 1.3 on Android it should just work with modern android versions or the optional play provider. 

For conscrypt on Android support you should try getting that working first with a socket and use stackoverflow or the conscrypt mailing list for support. And once that is working we can help with any bugs in okhttp + conscrypt on Android. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by schildbach** [comment]
@yschimke Well, it doesn't work. At least not out of the box. I'll post to StackOverflow.

I'd rather not use proprietary close source components like Google Play Services; I'm fine for now if TLSv1.3 only works on Android 8 and 9.

**Comment by schildbach** [comment]
fwiw: https://stackoverflow.com/questions/55539513/how-to-enable-tlsv1-3-for-okhttp-3-12-x-on-android-8-9
