### ISSUE TITLE
[Feature request] Better android Proguard support

### ISSUE THREAD

**Issue by gengjiawen** [square/okhttp#4533]
Android community heavily rely on okhttp. It basically everywhere. But there is no android related test in this repo. I am thinking introduce an android sample and do proguard or other android related thing.

So any ideas ?

**Comment by JakeWharton** [comment]
What Android support is missing? OkHttp is not an Android-specific library so it's built on the behavior of the `java.*` APIs. Android ships those APIs so any behavior difference is an OS bug. What specifically are you asking for?

**Comment by gengjiawen** [comment]
Like ensure R8/Proguard rules are correct. From this https://github.com/facebook/react-native/pull/22877, it looks like something is broken.

**Comment by JakeWharton** [comment]
Those warnings comes from bouncy castle. I didn't see any OkHttp ones.
Which ones did you see?

**Comment by gengjiawen** [comment]
I see. But with test for R8/Proguard rules is good to have.

**Comment by gengjiawen** [comment]
Also okhttp-tls depend on `org.bouncycastle:bcprov-jdk15on` https://github.com/square/okhttp/blob/16372fa6f49012bd25caf2eb732667eadab304b5/okhttp-tls/pom.xml#L27

**Comment by JakeWharton** [comment]
That's not part of the client by default. And even if it were why would we provide rules for that dependency? Should it be the one providing the rules instead of every library that depends on it?

**Comment by gengjiawen** [comment]
Good point. 

But for this moment, if android developer use `okhttp-tls`, they will run into the issue.

Clarify this in `README` or just leave it be for now?

**Comment by swankjesse** [comment]
What's the ProGuard issue? What would we do to prevent it?

**Comment by gengjiawen** [comment]
Problem: Integrate with android app with TLS 1.3 support will result in buid issue.

Solution: Add android sample to this repo and using ci to prevent similiar problem.

**Comment by yschimke** [comment]
@swankjesse @JakeWharton it might be a good way to provide a base http://www.sscce.org/ Android example for people to reproduce Android related issues with.  When people go the extra mile to provide a reproducible Android bug report, it does usually involve a new repo, and a lot of generated Android Studio code.

**Comment by yschimke** [comment]
We now have a manually runnable android test
