### ISSUE TITLE
EventListener behavior when response body is closed without reading all data

### ISSUE THREAD

**Issue by amirlivneh** [square/okhttp#4536]
`EventListenerTest` has this ignored test: https://github.com/square/okhttp/blob/e3c9e9a4399bdd720f6292abd9e8aed187113b10/okhttp-tests/src/test/java/okhttp3/EventListenerTest.java#L950-L968

1. This read throws a socket timeout exception after 100 ms, possibly because the test doesn't read the response body:
https://github.com/square/okhttp/blob/ded5e1fd264c68de31901dd3f2596bc35c5dd7cb/okhttp/src/main/java/okhttp3/internal/http1/Http1Codec.java#L365
Once this is fixed, reading the response body will throw a `java.net.ProtocolException: unexpected end of stream`. Do we actually want to ignore this exception and treat this scenario as a successful call?

2. What is the purpose of delaying the body in the test:
https://github.com/square/okhttp/blob/e3c9e9a4399bdd720f6292abd9e8aed187113b10/okhttp-tests/src/test/java/okhttp3/EventListenerTest.java#L954

**Comment by swankjesse** [comment]
Fixed!
