### ISSUE TITLE
Request help, upload images with probabilistic distortion

### ISSUE THREAD

**Issue by laymanZ** [square/okhttp#4537]
🛑 𝙎𝙏𝙊𝙋

hello , when I upload file by okhttp use the following way 

>     
        OkHttpClient.Builder clientBuilder = new OkHttpClient.Builder();
       OkHttpClient okHttpClient = clientBuilder.build();
        MultipartBody.Builder builder = new MultipartBody
                .Builder()
                .setType(MultipartBody.FORM);
        for (int i = 0; i < fileList.size(); i++) {
                File file = new File(fileList.get(i));
                builder.addFormDataPart(path, path, 
                RequestBody.create(MediaType.parse("application/octet-stream"), file));
        }
        RequestBody body = builder.build();
        final Request request = new Request.Builder()
                .url(upLoadUrl)
                .post(body)
                .build();
        okHttpClient.newCall(request).enqueue(new Callback() {})

and  I  get  response  in  method  **onResponse()** 

The background server does not do any processing on the image, just returns a link 。

Sometimes the pictures you get are complete and sometimes distorted.

like  these ：

![img_1546569488740_341782c2-99d7-40f4-9aa6-707b5dccdad9](https://user-images.githubusercontent.com/17823177/50751991-227ccd00-1287-11e9-8d12-0482858d4f4a.jpg)
![76317c21ab106096b40df6f015f8d9a55352335](https://user-images.githubusercontent.com/17823177/50752006-36283380-1287-11e9-9a8b-788b66618074.jpg)

they are from the same  file.

I don't know if my method of use is wrong, please also give comments.  Thank you !

**Comment by yschimke** [comment]
OkHttp won't create different representations of your file.  Most likely you have either some concurrency issue in the client before uploading, or in the server while storing or other processing, and  possibly a timing issue (race condition).

You should verify by checking something like a checksum of the file before submitting and then compare to what the server sees and vice versa.  You might be reading from the server while the request.

This sort of question is best asked in stackoverflow, it isn't an actionable bug report for the OkHttp developers.
