### ISSUE TITLE
cache response is stale

### ISSUE THREAD

**Issue by drorsun** [square/okhttp#4539]
Hi, it seems like the cache response contains the old response while the network response is new and modified.

We're on android using  'com.squareup.okhttp3:okhttp:3.11.0'

See example below of the headers we get this in the same Response, notice the network response has 200 status code and a newer LastModified, different ETag etc.

The expected result would be that the cache response would contain the same (new) data as the network response in cases where the network response is fresher.

**network response**
Response{protocol=http/1.1, code=200, message=OK, url=http://xxx.yyy.zzz/test} 
headers: Content-Type: application/octet-stream
    Content-Length: 3093384
    Connection: keep-alive
    Date: Mon, 07 Jan 2019 09:11:45 GMT
    Last-Modified: Mon, 07 Jan 2019 09:11:15 GMT
    ETag: "18905c1f58feca0c6df495f7cc2e6846"
    x-amz-version-id: 6J9k_vF2g.lPoELovv9G.rUPpfnk2h4r
    Accept-Ranges: bytes
    Server: AmazonS3
    Age: 10
    X-Cache: Hit from cloudfront
    Via: 1.1 32c8da10203574baccb74b8f771a7ffb.cloudfront.net (CloudFront)
    X-Amz-Cf-Id: FVvnNF3QD5I0vELy78FoVxYgvJeqRsCACGdbbh5W8MGtARkg0lH9CQ==

**cache response** 
Response{protocol=http/1.1, code=200, message=OK, url=http://http://xxx.yyy.zzz/test} 
headers: Content-Type: application/octet-stream
    Content-Length: 3093323
    Connection: keep-alive
    Last-Modified: Sun, 06 Jan 2019 15:03:31 GMT
    Accept-Ranges: bytes
    Date: Mon, 07 Jan 2019 09:09:11 GMT
    ETag: "9725f2a6b04151c54f8a420be6fa7690"
    x-amz-version-id: vKJV3auEiruTggNKvciHJoy1LWscENFM
    Server: AmazonS3
    Age: 65063
    X-Cache: Hit from cloudfront
    Via: 1.1 e64eb476d8f76c461d21278e018e194f.cloudfront.net (CloudFront)
    X-Amz-Cf-Id: R53ZU9rO1_ZWlueMU3Xo1ZOeDX5ibAv9TFDgp2uchC6rfg9fBCtk-A==

**Comment by swankjesse** [comment]
Does this explain it?
https://publicobject.com/2015/03/26/how-do-http-caching-heuristics-work/

Your server needs to include a cache-control header in the response.

**Comment by romanbsd** [comment]
Actually, in this case I think that the cacheResponse should be null, since this response shouldn't have been served from the cache.

**Comment by swankjesse** [comment]
Was it? Ie. is there a networkResponse present with a code other than 304?

**Comment by drorsun** [comment]
yes, both networkResponse and cacheResponse I copied below are form the same response. The networkResponse is with code 200.

**Comment by swankjesse** [comment]
What's the issue?

**Comment by romanbsd** [comment]
I believe that in case of a newer network response, the cacheResponse should be null, since it's stale (and the request cannot be served from cache for that matter). The common approach ( https://stackoverflow.com/questions/41727750/detect-if-okhttp-response-comes-from-cache-with-retrofit ) to see whether the asset didn't change is checking for the presence of the cacheResponse.

**Comment by swankjesse** [comment]
Gotcha. This was a conditional cache miss. You know that because the networkResponse is not a 304. If you’d like to update Stackoverflow, please do!

**Comment by romanbsd** [comment]
Since it's a common concern, I think that maybe it's worth adding in the wiki. A helper method would also be nice :)

**Comment by swankjesse** [comment]
Good idea!
https://github.com/square/okhttp/issues/4637
