### ISSUE TITLE
 Response header Hpack compression is not correct

### ISSUE THREAD

**Issue by MegatronKing** [square/okhttp#4541]
Hi guys,

I tried to use Hpack to compression response header block, I found the compressed data is not correct. For example:

Header list to encode:
:status: 302

According to [rfc7541#page-45](https://tools.ietf.org/html/rfc7541#page-45), the first byte should be 0x48, but now it is 0x08.

The response code should use 'Literal Header Field with Incremental Indexing', but now uses 'Literal Header Field without Indexing'.  It goes this line: https://github.com/square/okhttp/blob/bb4a067e06791ce48b5b65aa138599c69a87dc21/okhttp/src/main/java/okhttp3/internal/http2/Hpack.java#L519 , it is not correct.

**Comment by swankjesse** [comment]
There’s multiple correct ways to encode a list of headers.

**Comment by MegatronKing** [comment]
Sorry for my stupid mistake.
