### ISSUE TITLE
Not possible to remove header based on name and value from Request.Builder.

### ISSUE THREAD

**Issue by JanAndersson** [square/okhttp#4545]
I have a case where I would like to remove header(s) based on name and value in a network interceptor. It would then be really useful to be able to do something like:

```
public Response intercept(Chain chain) throws IOException {
  Request originalRequest = chain.request();
  ...
  Request.Builder requestBuilder = new Request.Builder(originalRequest);
  requestBuilder.removeHeader("X-Header, "Tag-To-Be-Removed");
  ...
}
```

Now I manually have to add each header that I do not want to copy. Works just fine, but  since header can be multiply-valued this sounds like a reasonable requirement to me?

**Comment by JakeWharton** [comment]
How about
```java
Request request = chain.request();
if ("Tag-To-Be-Removed".equals(request.header("X-Header")) {
  request = request.newBuilder()
      .headers(request.headers().newBuilder()
           .remove("X-Header")
           .build())
      .build();
}
return chain.proceed(request);
```
?

**Comment by JanAndersson** [comment]
If "X-Header" has multiple values removeHeader("X-Header") will remove all "X-Header" values.
I want to remove a specific header/value. For example if we have:

X-Header: value1
X-Header: value2

Say that I want to remove only "X-Header: value2". This isn't possible today?

**Comment by JakeWharton** [comment]
I see. Seems like no!

**Comment by swankjesse** [comment]
Would remove-by-index work for you?

**Comment by JanAndersson** [comment]
I guess so. But what I really vould like to see is something like:

```
/** Remove named header/value pair if found. */
public Builder remove(String name, String value) {
   for (int i = 0; i < namesAndValues.size(); i += 2) {
      if (name.equalsIgnoreCase(namesAndValues.get(i))) {
         if (value.equals(namesAndValues.get(i))) {
            namesAndValues.remove(i); // name
            namesAndValues.remove(i); // value
         }
      }
   }
   return this;
}
```

Not tested and only based on a quick glance at the current code.

Headers.java could be rewritten to store the headers using a map: Map<String, List<String>>? 
But I'm not sure it's worth it.

**Comment by swankjesse** [comment]
I think we should implement remove-by-index. That way you can use whatever logic you want to decide which of your X-Header instances you want to remove.

**Comment by JanAndersson** [comment]
Ok by me.
Sorry about the delay answering this...

**Comment by yschimke** [comment]
won't fix.
