### ISSUE TITLE
OkHttp will not cache video, but can cache other files

### ISSUE THREAD

**Issue by tanpuer** [square/okhttp#4557]
I am using OkHttp with my VideoPlayer to cache videos and preload videos. But unfortunately, I find that OkHttp will not cache video. I have set cache and NetWorkInterceptor in OkHttpClient. Can anyone help me?

public class VideoCacheInterceptor imlements Interceptor {

    @Override
    public Response intercept(Chain chain) throws IOException{
        Response originResponse = chain.proceed(chain.request());
        return originResponse.newBuilder()
              .removeHeader("Pragma")
              .removeHeader("No-Cache")
              .removeHeader("Cache-Control")
              .header(Cache-Control", "public, max-age=" + INVPlayer.maxAge)
              .build();
    }

}

OkHttpClient okHttpClient = new OkHttpClient.Builder() .cache(VideoOkHttpUtil.getInstance(MyApplication.mContext).getCache()) .addNetworkInterceptor(new VideoCacheInterceptor()) .build();

**Comment by swankjesse** [comment]
Please use StackOverflow for questions.
