### ISSUE TITLE
Disabling SSL Pinning

### ISSUE THREAD

**Issue by yunusmete** [square/okhttp#4558]
Hello everyone!
We are using OkHttp 3.11.0 in our Android project and recently implemented certificate pinning feature thanks to CertificatePinner in OkHttp for security requirements.

We just noticed that [Objection](https://github.com/sensepost/objection) toolkit can disable certificate pinning after applying the patch to the generated APK. As a result, patched apk can be installed to the device and bypassing SSL pinning.

Is there any way to get rid of this issue?
Thanks in advance.

**Comment by swankjesse** [comment]
Certificate pinning defends against a network attacker. It does not attempt to defend against an attacker whose code is present in-process.
