### ISSUE TITLE
The Dispatcher runningAsyncCalls > 64

### ISSUE THREAD

**Issue by Chumfuchiu** [square/okhttp#4559]
I mimic your Dispatcher.java to implement a ThreadPoolUtil,but I found the runningAsyncCalls> 64.

import java.util.*;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.SynchronousQueue;
import java.util.concurrent.ThreadPoolExecutor;
import java.util.concurrent.TimeUnit;

public final class Dispatcher {
    private int maxRequests = 64;
    private ExecutorService executorService;
    private final Deque<LightTask> readyAsyncCalls = new ArrayDeque<>();
    private final Deque<LightTask> runningAsyncCalls = new ArrayDeque<>();

    private Dispatcher() {
    }

    public static Dispatcher getInstance(){
        return InstanceHolder.INSTANCE;
    }

    private static  class InstanceHolder {
        static Dispatcher INSTANCE = new Dispatcher();
    }

    public synchronized ExecutorService executorService() {
        if (executorService == null) {
            executorService = new ThreadPoolExecutor(0, Integer.MAX_VALUE, 60, TimeUnit.SECONDS,
                    new SynchronousQueue<>());
        }
        return executorService;
    }

    void enqueue(LightTask call) {
        synchronized (this) {
            readyAsyncCalls.add(call);
        }
        promoteAndExecute();
    }

    private void promoteAndExecute() {
        List<LightTask> executableCalls = new ArrayList<>();
        synchronized (this) {
            for (Iterator<LightTask> i = readyAsyncCalls.iterator(); i.hasNext(); ) {
                LightTask asyncCall = i.next();
                if (runningAsyncCalls.size() >= maxRequests) break; // Max capacity.
                i.remove();
                asyncCall.ready2runing = true;
                executableCalls.add(asyncCall);
                runningAsyncCalls.add(asyncCall);
            }
        }

        for (int i = 0, size = executableCalls.size(); i < size; i++) {
            LightTask asyncCall = executableCalls.get(i);
            executorService().execute(asyncCall);
        }
    }

    private void finished(LightTask call) {
        synchronized (this) {
            if (!runningAsyncCalls.remove(call)) throw new AssertionError("Call wasn't in-flight!");
        }
        promoteAndExecute();
    }

    public synchronized int queuedCallsCount() {
        return readyAsyncCalls.size();
    }

    public synchronized int runningCallsCount() {
        return runningAsyncCalls.size();
    }

    public static class LightTask implements Runnable {
        private Runnable realTask;
        private String name;
        public boolean ready2runing;

        public LightTask(Runnable realTask, String name) {
            this.realTask = realTask;
            this.name = name;
        }

        @Override
        public final void run() {
            String oldName = Thread.currentThread().getName();
            if (name != null && name.length() != 0) {
                Thread.currentThread().setName(name);
            }
            try {
                realTask.run();
                int count = ((ThreadPoolExecutor) Dispatcher.getInstance().executorService()).getActiveCount();
                System.out.println("queuedCallsCount：" + Dispatcher.getInstance().queuedCallsCount() +
                        " runningCallsCount：" + Dispatcher.getInstance().runningCallsCount() +
                        " activeCallCount：" + (count > 64 ? "**" + count : count) + ready2runing
                );
            } finally {
                getInstance().finished(this);
                Thread.currentThread().setName(oldName);
            }
        }
    }
}

===============Test=================
    private static final int MAX = 1_000;
    public static void main(String[] args) {
        for (int i = 0; i <= MAX; i++) {
            Dispatcher.getInstance().enqueue(new Dispatcher.LightTask(new Runnable() {
                @Override
                public void run() {
                    
                }
            },""));
        }
    }
================Result================
queuedCallsCount：293 runningCallsCount：64 activeCallCount：64true
queuedCallsCount：277 runningCallsCount：64 activeCallCount：**65true
queuedCallsCount：293 runningCallsCount：64 activeCallCount：64true
queuedCallsCount：294 runningCallsCount：64 activeCallCount：64true
queuedCallsCount：300 runningCallsCount：64 activeCallCount：64true

**Comment by swankjesse** [comment]
That’s allowed! Dispatcher limits number of outbound network requests, not the number of locally-consumed threads. Also, the thread counts are approximate!

**Comment by swankjesse** [comment]
<img width="585" alt="screen shot 2019-01-16 at 3 34 25 pm" src="https://user-images.githubusercontent.com/133019/51277367-6bc6ce00-19a5-11e9-8da2-672e5540403a.png">
