### ISSUE TITLE
OkHttp websocket bug without running Activity in Android

### ISSUE THREAD

**Issue by loader77** [square/okhttp#4562]
I receive a standard notification about closing  a websocket connection due to a pong  was not received in time when Activity is destroyed.
Websocket connection is launched in  Service, which is launched through  startForeground.
  Ping interval is 30 seconds.
It seems that  client websocket has  problems when activity is destroyed.
What is it :  problems with Android system or  with OkHTTP module?

**Comment by swankjesse** [comment]
Executable test case?

**Comment by loader77** [comment]
Sorry, problem solved.
It was probably connected to the server.

**Comment by loader77** [comment]
This was due to the screen lock and the processor falling asleep.
