### ISSUE TITLE
java.net.ProtocolException: unexpected end of stream

### ISSUE THREAD

**Issue by zhouhui520w** [square/okhttp#4567]
![1](https://user-images.githubusercontent.com/8720881/51364706-f7f90280-1b17-11e9-9400-60bec7ea3727.jpg)

at okhttp3.internal.d.a$e.read(SourceFile:409)

**Comment by swankjesse** [comment]
This is not actionable. Provide steps to reproduce please.

**Comment by zhouhui520w** [comment]
`implementation 'com.squareup.okhttp3:okhttp:3.11.0'
    implementation 'com.squareup.okhttp3:logging-interceptor:3.11.0'`

`OkHttpClient client = new OkHttpClient.Builder()
                .retryOnConnectionFailure(true)
                .addInterceptor(new HttpLoggingInterceptor().setLevel(HttpLoggingInterceptor.Level.NONE))
                .connectTimeout(30, TimeUnit.SECONDS)
                .readTimeout(30, TimeUnit.SECONDS)
                .writeTimeout(30, TimeUnit.SECONDS)
                .build();
        Request request = new Request.Builder().url(mVersionUrl).build();
        mCall = client.newCall(request);
        mCall.enqueue(new Callback() {
            @Override
            public void onFailure(Call call, IOException e) {
                e.printStackTrace();
                LogUtil.e("TEST", "MainActivity", "onFailure", "e.getMessage()---" + e.getMessage());
            }

            @Override
            public void onResponse(Call call, Response response) {
                BufferedSource source = null;
                BufferedSink sink = null;
                try {
                    String apkDownLoadDir = FileManager.getApkDownLoadDir();
                    File apkFile = new File(apkDownLoadDir, "TEST.apk");
                    apkFile.getParentFile().mkdirs();
                    apkFile.createNewFile();

                    source = responseBody.source();
                    sink = Okio.buffer(Okio.sink(apkFile));

                    source.readAll(sink);
                    sink.flush();
                } catch (IOException e) {
                    e.printStackTrace();
                    LogUtil.e("TEST", "MainActivity", "onResponse", "e.getMessage()---" + e.getMessage());
                } finally {
                    try {
                        if (source != null) {
                            source.close();
                        }
                        if (sink != null) {
                            sink.close();
                        }
                    } catch (IOException e) {
                        e.printStackTrace();
                    }
                }

            }
        });`

**Comment by zhouhui520w** [comment]
> 这不可行。提供重现的步骤。

> implementation 'com.squareup.okhttp3:okhttp:3.11.0'

> implementation 'com.squareup.okhttp3:logging-interceptor:3.11.0'



`OkHttpClient client = new OkHttpClient.Builder()
            .retryOnConnectionFailure(true)
            .connectTimeout(30, TimeUnit.SECONDS)
            .readTimeout(30, TimeUnit.SECONDS)
            .writeTimeout(30, TimeUnit.SECONDS)
            .build();`

`Request request = new Request.Builder().url(mVersionUrl).build();`
`Call call = client.newCall(request);`

` call.enqueue(new Callback() {
        @override
        public void onFailure (Call call, IOException e){
            e.printStackTrace();
            LogUtil.e("TEST", "MainActivity", "onFailure", "e.getMessage()---" + e.getMessage());
        }

        @Override
        public void onResponse (Call call, Response response){
            BufferedSource source = null;
            BufferedSink sink = null;
            try {
                String apkDownLoadDir = FileManager.getApkDownLoadDir();
                File apkFile = new File(apkDownLoadDir, "TEST.apk");
                apkFile.getParentFile().mkdirs();
                apkFile.createNewFile();

                source = responseBody.source();
                sink = Okio.buffer(Okio.sink(apkFile));

                source.readAll(sink);
                sink.flush();
            } catch (IOException e) {
                e.printStackTrace();
                LogUtil.e("TEST", "MainActivity", "onResponse", "e.getMessage()---" + e.getMessage());
            } finally {
                try {
                    if (source != null) {
                        source.close();
                    }
                    if (sink != null) {
                        sink.close();
                    }
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
        }
    });`

**Comment by swankjesse** [comment]
Bugs with executable test cases get fixed!
