### ISSUE TITLE
Reopen of #4253 : retry indefinitely during a file upload

### ISSUE THREAD

**Issue by yuit** [square/okhttp#4570]
We observed similar behavior as this [comment](https://github.com/square/okhttp/issues/4253#issuecomment-444690032) We have audit our app extensively. We have narrowed down to similar area in RetryAndFollowUpInterceptor and that IOException or RouteException short circuit. 

here is the stacktrace of the issue
<img width="1251" alt="screen shot 2019-01-09 at 10 05 28 am" src="https://user-images.githubusercontent.com/489742/50918885-3e52b100-13f6-11e9-957d-9db33c93755b.png">

Couple questions:

- is there a mitigate we can use? 
- Is there a fix of the issue  ? We saw this PR#4523. We can try to take up the fix of the issue but would love to have a guideline on how to best approach the problem

**Comment by swankjesse** [comment]
Fixed in OkHttp 3.14.
