### ISSUE TITLE
Response-Building creates crashes

### ISSUE THREAD

**Issue by NothShow** [square/okhttp#4571]
okhttp3.3 checks the message when we build the Response  which causes the Exception without notify developer; Can u fix to the issue?
eg.  add default value
public Response build() {
      if (request == null) throw new IllegalStateException("request == null");
      if (protocol == null) throw new IllegalStateException("protocol == null");
      if (code < 0) throw new IllegalStateException("code < 0: " + code);
      if (message == null) throw new IllegalStateException("message == null");
      return new Response(this);
    }

**Comment by swankjesse** [comment]
Just provide "OK" ?
