### ISSUE TITLE
Content type of FormBody should include charset

### ISSUE THREAD

**Issue by BoxResin** [square/okhttp#4574]
I builded a `FormBody` like this:
```kotlin
val requestBody = FormBody.Builder(Charset.forName("UTF-8"))
    .add("...", "...")
    .add("...", "...")
    .add("...", "...")
    .build()
```

The next code should return `application/x-www-form-urlencoded; charset=UTF-8`.
```kotlin
requestBody.contentType()
```
However, it only returns `application/x-www-form-urlencoded`.

**Comment by monkey-mas** [comment]
It seems that it's not correct to add `charset` according to [Stackoverflow: application/x-www-form-urlencoded and charset=“utf-8”?](https://stackoverflow.com/questions/16819502/application-x-www-form-urlencoded-and-charset-utf-8/16829056#16829056). So I think OkHttp correctly handles the request body.

Also, according to https://www.w3.org/TR/html401/interact/forms.html#h-17.13.4.1, I counldn't find a description that you can append `charset` to `application/x-www-form-urlencoded` unlike `multipart/form-data`.

#### multipart/form-data
> As with all multipart MIME types, each part has an optional "Content-Type" header that defaults to "text/plain". User agents should supply the "Content-Type" header, accompanied by a "charset" parameter.

**Comment by BoxResin** [comment]
@monkey-mas 
Some web servers don't accept a request of which `charset` isn't specified. May not they follow HTTP spec?

**Comment by monkey-mas** [comment]
Yeah, there could be servers rejecting an `application/x-www-form-urlencode` request without `charset`. IIUC, that happens as they don't follow some specification like I posted before. Also, I've seen a bug report in another GitHub project that some servers don't accept an `application/x-www-form-urlencode` with `charset`, e.g., `Content-Type: application/x-www-form-urlencoded; charset=UTF-8`.

**Comment by BoxResin** [comment]
I think you're right. This is not problem.
