### ISSUE TITLE
skip some bytes of file in Multipart form-data

### ISSUE THREAD

**Issue by alifarahmandnejad** [square/okhttp#4587]
is this possible to skip some bytes of file in Multipart form-data?

for example:

I want to upload 1Gb file to server. The server receives 700Mb of file and store it. Next time server tell me ok! send me next 300Mb. and i want to skip the first 700Mb of the file and send next 300Mb of the file to a server.

**Comment by swankjesse** [comment]
You can send whichever data you like. There's no built in feature for this, and none planned.
