### ISSUE TITLE
Tomcat unloading 

### ISSUE THREAD

**Issue by costinarsene** [square/okhttp#4596]
The field 
`
private static final Executor executor = new ThreadPoolExecutor(0 /* corePoolSize */,
      Integer.MAX_VALUE /* maximumPoolSize */, 60L /* keepAliveTime */, TimeUnit.SECONDS,
      new SynchronousQueue<Runnable>(), Util.threadFactory("OkHttp ConnectionPool", true));
`

in the class **ConnectionPool** does not get unloaded in a JEE server and upon war reloading this will be unloaded.

I have the following options:

1. I believe if you **remove the static modifier** and **shutdown executor** on a custom method  or on an existing one such as "evictAll" the whole issue will be avoided.

2. Create a **constructor** with that will provide  **custom Executor instance** and the shutting down this executor will be carried out of who provided it in consturctor.

Thank you in advance

**Comment by swankjesse** [comment]
I’ve decided to not fix this issue because I don’t think the cost of code unloading is worth the benefit.

Discussion here:
https://github.com/square/okhttp/issues/2482
