### ISSUE TITLE
Unable to instantiate the client

### ISSUE THREAD

**Issue by desokroshan** [square/okhttp#4597]
While trying to instantiate OkHttpClient as follows inside the MainActivity of android:

```OkHttpClient client = new OkHttpClient();```

Stacktrace : 

    java.lang.BootstrapMethodError: Exception from call site #5 bootstrap method
        at okhttp3.internal.Util.<clinit>(Util.java:87)
        at okhttp3.internal.Util.immutableList(Util.java:234)
        at okhttp3.OkHttpClient.<clinit>(OkHttpClient.java:127)
        at com.amazonaws.transcribestreaminghttpclient.MainActivity.<init>(MainActivity.java:28)
        at java.lang.Class.newInstance(Native Method)
        at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:69)
        at android.support.v4.app.CoreComponentFactory.instantiateActivity(CoreComponentFactory.java:43)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1215)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2831)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)

Happens only on 3.13.1. Works well on 3.12.1.
Any insights?

**Comment by JakeWharton** [comment]
Per [the release notes](https://github.com/square/okhttp/blob/master/CHANGELOG.md#version-3130), OkHttp requires that you enable Java 8 in your builds to function as of 3.13 and newer. You can learn more about how to enable this at https://developer.android.com/studio/write/java8-support.

You need to add something like
```groovy
android {
    compileOptions {
        targetCompatibility = "8"
        sourceCompatibility = "8"
    }
}
```
to your application `build.gradle`.

**Comment by CHENGCHANGHU** [comment]
hello, i enabled JAVA 8 but it still did not work
`OkHttpClient client = new OkHttpClient();
                Request request = new Request.Builder()
                        .url("https://www.baidu.com")
                        .build();
                try {

                    Response response = client.newCall(request).execute();
                    String responseData = response.body().string();
                    showResponse(responseData);
                } catch (IOException e) {
                    e.printStackTrace();
                }`
`compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }`

**Comment by eddex** [comment]
@CHENGCHANGHU make sure to do a _Clean Project_ (`Build > Clean Project`) after you change the `build.gradle` file.

**Comment by mckasap** [comment]
After adding compileOption...  cleaning and Building the project solved my problem  thanks guys

**Comment by leetyk** [comment]
> @CHENGCHANGHU make sure to do a _Clean Project_ (`Build > Clean Project`) after you change the `build.gradle` file.


I have the same problem. Thank you for sharing.

**Comment by phamthelong** [comment]
> Per [the release notes](https://github.com/square/okhttp/blob/master/CHANGELOG.md#version-3130), OkHttp requires that you enable Java 8 in your builds to function as of 3.13 and newer. You can learn more about how to enable this at https://developer.android.com/studio/write/java8-support.
> 
> You need to add something like
> 
> ```groovy
> android {
>     compileOptions {
>         targetCompatibility = "8"
>         sourceCompatibility = "8"
>     }
> }
> ```
> 
> to your application `build.gradle`.

thanks you

**Comment by michalharakal** [comment]
Just a hint for somebody wanting to add the compile options into `build.gradle.kts`

```kotlin
compileOptions {
        targetCompatibility = JavaVersion.VERSION_1_8
        sourceCompatibility = JavaVersion.VERSION_1_8
}
```
