### ISSUE TITLE
JDK 11 test failures

### ISSUE THREAD

**Issue by yschimke** [square/okhttp#4598]
- No appropriate protocol (protocol is disabled or cipher suites are inappropriate)
- NoSuchElementException in BasicCertificateChainCleaner.clean
- StreamReset stream was reset: PROT...

**Comment by yschimke** [comment]
marked with TODO in the code

**Comment by yschimke** [comment]
FWIW I split these out as there is value in having the tests in place even while existing bugs with JDK 11 remain.

**Comment by yschimke** [comment]
@swankjesse Hey, just wanted to flag these.  They probably deserve some attention, but I may not get to them in next couple of weeks.  They pre-existed but were surfaced by the Jenkins matrix build.

**Comment by galderz** [comment]
I've just tried to run the testsuite with Java 11 (`jdk-11.0.2.jdk`) and got this failure:

```
[ERROR] Tests run: 32, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 77.672 s <<< FAILURE! - in okhttp3.InterceptorTest
[ERROR] connectTimeout(okhttp3.InterceptorTest)  Time elapsed: 75.613 s  <<< ERROR!
java.net.ConnectException: Operation timed out (Connection timed out)
	at okhttp3.InterceptorTest.connectTimeout(InterceptorTest.java:693)
```

Shall I create a separate issue for it, or shall we track failures in this issue? p.s. I can look into it.

**Comment by yschimke** [comment]
I think fine here. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by galderz** [comment]
Apologies, issue was also happening with Java 8. Turns out the error only appears when wifi is disabled on my laptop (but ethernet on...). Shall I create a separate issue?

**Comment by galderz** [comment]
Went ahead and created #4682

**Comment by swankjesse** [comment]
Isolated one of ’em to a regression in OpenJDK caused by the pre_shared_key extension. https://github.com/square/okhttp/issues/4703
