### ISSUE TITLE
Adopt AssertJ in tests

### ISSUE THREAD

**Issue by swankjesse** [square/okhttp#4599]
We've resisted it to date to make it easier for AOSP people to keep OkHttp up-to-date inside Android. That isn't happening anyway so we shouldn't be constrained by it.

FYI: @nfuller @narayank @15characterlimi

**Comment by 15characterlimi** [comment]
Thanks for the heads-up!

I'm not personally familiar with AssertJ (seems like there is a version for Android?) but in any case, it seems fair for you to not feel too constrained by Android. Based on some ongoing work internally, my personal hope is that we *may* be in a better position to take behaviour changing OkHttp updates in a couple of years, but it's hard to predict.

**Comment by swankjesse** [comment]
Strategy: inline this:
https://gist.github.com/swankjesse/252e5bd3f1cb987a95f49a469bb4c8ea

**Comment by swankjesse** [comment]
https://github.com/square/okhttp/pull/4713
