### ISSUE TITLE
MultipartBody not working with PUT 

### ISSUE THREAD

**Issue by neobie** [square/okhttp#4601]
```
MultipartBody formBody = new MultipartBody.Builder()
				.setType(MultipartBody.FORM)
				.addFormDataPart("message", message.trim())
				.build(); //not working
		RequestBody formBody = new FormBody.Builder()
				.add("message", message.trim())
				.build(); //working

		Request request = new Request.Builder()
				.url(url)
				.put(formBody) // here I use PUT request
				.build();
```

If I sent MultipartBody with PUT request, empty data is sent. It works fine if MultiPartBody is sent with POST request.

**Comment by swankjesse** [comment]
Executable test case please.

**Comment by claudivanmoreira** [comment]
Hi @neobie , i could not simulate your scenario.

However, I did two scenarios, using POST and PUT to inspect the sent request. At first, in both cases everything is ok.

I created a servlet to simulate the data receiver, and it was able to read the data that was sent using OkHttp.

What may be happening is that in the destination of your data, the header "multipart / form-data" is being read manually and compared to a fixed value.

For example, the logs below indicate that for both POST and PUT methods, the content type of the request is "multipart / form-data; boundary = xxxxxxxx" and not just the fixed "multipart / form-data" String.

`{
  "method" : "PUT",
  "path" : "/upload/put",
  "body" : "--08fe80aa-36f7-4033-bf40-37d34f3a8d7c\r\nContent-Disposition: form-data; name=\"message\"\r\nContent-Length: 5\r\n\r\ndados\r\n--08fe80aa-36f7-4033-bf40-37d34f3a8d7c--\r\n",
  "headers" : {
    "Connection" : [ "Keep-Alive" ],
    "User-Agent" : [ "okhttp/3.13.1" ],
    "Host" : [ "localhost:3000" ],
    "Accept-Encoding" : [ "gzip" ],
    "Content-Length" : [ "158" ],
    "Content-Type" : [ "multipart/form-data; boundary=08fe80aa-36f7-4033-bf40-37d34f3a8d7c" ]
  },
  "keepAlive" : true,
  "secure" : false
}

{
  "method" : "POST",
  "path" : "/upload/put",
  "body" : "--3d931c15-3fe7-4d7c-bdda-e667315bf3c7\r\nContent-Disposition: form-data; name=\"message\"\r\nContent-Length: 5\r\n\r\ndados\r\n--3d931c15-3fe7-4d7c-bdda-e667315bf3c7--\r\n",
  "headers" : {
    "Connection" : [ "Keep-Alive" ],
    "User-Agent" : [ "okhttp/3.13.1" ],
    "Host" : [ "localhost:3000" ],
    "Accept-Encoding" : [ "gzip" ],
    "Content-Length" : [ "158" ],
    "Content-Type" : [ "multipart/form-data; boundary=3d931c15-3fe7-4d7c-bdda-e667315bf3c7" ]
  },
  "keepAlive" : true,
  "secure" : false
}`

It is the same scenario when a json request is sent and the Content Type header is sent with "application / json; charset = UTF-8" and not just "application / json". Make sure this is your case.

You can see my test [here](https://github.com/claudivanmoreira/okhttp-multipart-studing).
