### ISSUE TITLE
Rewrite StreamAllocation + Events

### ISSUE THREAD

**Issue by swankjesse** [square/okhttp#4603]
I’m unhappy with the way events are sent. It feels pretty haphazard, and we’re not reliably publishing all of the events we should be. For example, with 100-continue we don’t publish an endHeaders event.

I’m also unhappy with the way StreamAllocation interacts with duplex requests. It seems we’re likely to inadvertently leak when the request stream outlives the response stream.

I’d like to rewrite the StreamAllocation code as a new `Transmitter` class. It’s the bridge between OkHttp’s application layer stuff (built-in interceptors) and its network layer stuff (route planning, connection pooling, etc.). The transmitter should look kind of like a state machine and it should publish events on state transitions.

**Comment by yschimke** [comment]
The test coverage pre-events and events specific is pretty good, so if you can run that gauntlet, you should be pretty safe.  :)

**Comment by swankjesse** [comment]
Happy with where this landed. Thanks @yschimke, @oldergod, and @amirlivneh for quick code reviews!
