### ISSUE TITLE
the picture of introducing Follow-UP new connection is not correct

### ISSUE THREAD

**Issue by chwnFlyPig** [square/okhttp#4610]
this url is redirect：http://push.gd165.com:8080/?psbs_sid=b1-s-gd020012047010164eab65258895&psbs_pid=a6115a002ba6e46c
we can get from its log:
once time callStart; two times callEnd
this is not same with your wiki.
the log detail is:
02-14 14:04:56.413 : callStart  url:http://push.gd165.com:8080/?psbs_sid=b1-s-gd020012047010164eab65258895&psbs_pid=a6115a002ba6e46c
02-14 14:04:56.422 : dnsStart  url:http://push.gd165.com:8080/?psbs_sid=b1-s-gd020012047010164eab65258895&psbs_pid=a6115a002ba6e46c;domainName:push.gd165.com
02-14 14:04:57.028 : dnsEnd  url:http://push.gd165.com:8080/?psbs_sid=b1-s-gd020012047010164eab65258895&psbs_pid=a6115a002ba6e46c;domainName:push.gd165.com
02-14 14:04:57.029 : connectStart  url:http://push.gd165.com:8080/?psbs_sid=b1-s-gd020012047010164eab65258895&psbs_pid=a6115a002ba6e46c;hostString:push.gd165.com;proxy:DIRECT
02-14 14:04:57.164 : connectEnd  url:http://push.gd165.com:8080/?psbs_sid=b1-s-gd020012047010164eab65258895&psbs_pid=a6115a002ba6e46c;hostString:push.gd165.com;proxy:DIRECT;protocol:http/1.1
02-14 14:04:57.168 : connectionAcquired  url:http://push.gd165.com:8080/?psbs_sid=b1-s-gd020012047010164eab65258895&psbs_pid=a6115a002ba6e46c
02-14 14:04:57.170 : requestHeadersStart  url:http://push.gd165.com:8080/?psbs_sid=b1-s-gd020012047010164eab65258895&psbs_pid=a6115a002ba6e46c
02-14 14:04:57.172 : requestHeadersEnd  url:http://push.gd165.com:8080/?psbs_sid=b1-s-gd020012047010164eab65258895&psbs_pid=a6115a002ba6e46c
02-14 14:04:57.176 : responseHeadersStart  url:http://push.gd165.com:8080/?psbs_sid=b1-s-gd020012047010164eab65258895&psbs_pid=a6115a002ba6e46c
02-14 14:04:57.260 : responseHeadersEnd  url:http://push.gd165.com:8080/?psbs_sid=b1-s-gd020012047010164eab65258895&psbs_pid=a6115a002ba6e46c
02-14 14:04:57.260 : responseBodyStart  url:http://push.gd165.com:8080/?psbs_sid=b1-s-gd020012047010164eab65258895&psbs_pid=a6115a002ba6e46c
02-14 14:04:57.291 : responseBodyEnd  url:http://push.gd165.com:8080/?psbs_sid=b1-s-gd020012047010164eab65258895&psbs_pid=a6115a002ba6e46c
02-14 14:04:57.292 : connectionReleased  url:http://push.gd165.com:8080/?psbs_sid=b1-s-gd020012047010164eab65258895&psbs_pid=a6115a002ba6e46c
02-14 14:04:57.293 : callEnd  url:http://push.gd165.com:8080/?psbs_sid=b1-s-gd020012047010164eab65258895&psbs_pid=a6115a002ba6e46c
02-14 14:04:57.306 : dnsStart  url:http://push.gd165.com:8080/?psbs_sid=b1-s-gd020012047010164eab65258895&psbs_pid=a6115a002ba6e46c;domainName:push.gd165.com
02-14 14:04:57.309 : dnsEnd  url:http://push.gd165.com:8080/?psbs_sid=b1-s-gd020012047010164eab65258895&psbs_pid=a6115a002ba6e46c;domainName:push.gd165.com
02-14 14:04:57.310 : connectStart  url:http://push.gd165.com:8080/?psbs_sid=b1-s-gd020012047010164eab65258895&psbs_pid=a6115a002ba6e46c;hostString:push.gd165.com;proxy:DIRECT
02-14 14:04:57.350 : connectEnd  url:http://push.gd165.com:8080/?psbs_sid=b1-s-gd020012047010164eab65258895&psbs_pid=a6115a002ba6e46c;hostString:push.gd165.com;proxy:DIRECT;protocol:http/1.1
02-14 14:04:57.351 : connectionAcquired  url:http://push.gd165.com:8080/?psbs_sid=b1-s-gd020012047010164eab65258895&psbs_pid=a6115a002ba6e46c
02-14 14:04:57.351 : requestHeadersStart  url:http://push.gd165.com:8080/?psbs_sid=b1-s-gd020012047010164eab65258895&psbs_pid=a6115a002ba6e46c
02-14 14:04:57.353 : requestHeadersEnd  url:http://push.gd165.com:8080/?psbs_sid=b1-s-gd020012047010164eab65258895&psbs_pid=a6115a002ba6e46c
02-14 14:04:57.354 : responseHeadersStart  url:http://push.gd165.com:8080/?psbs_sid=b1-s-gd020012047010164eab65258895&psbs_pid=a6115a002ba6e46c
02-14 14:04:57.392 : responseHeadersEnd  url:http://push.gd165.com:8080/?psbs_sid=b1-s-gd020012047010164eab65258895&psbs_pid=a6115a002ba6e46c
02-14 14:04:57.392 : responseBodyStart  url:http://push.gd165.com:8080/?psbs_sid=b1-s-gd020012047010164eab65258895&psbs_pid=a6115a002ba6e46c
02-14 14:04:57.394 : responseBodyEnd  url:http://push.gd165.com:8080/?psbs_sid=b1-s-gd020012047010164eab65258895&psbs_pid=a6115a002ba6e46c
02-14 14:04:57.395 : connectionReleased  url:http://push.gd165.com:8080/?psbs_sid=b1-s-gd020012047010164eab65258895&psbs_pid=a6115a002ba6e46c
02-14 14:04:57.395 : callEnd  url:http://push.gd165.com:8080/?psbs_sid=b1-s-gd020012047010164eab65258895&psbs_pid=a6115a002ba6e46c

**Comment by swankjesse** [comment]
Fixed!
