### ISSUE TITLE
Okhttp breaks jetty on Java 8 with ALPN enabled *dynamically*

### ISSUE THREAD

**Issue by dansanduleac** [square/okhttp#4615]
Specifically, if this line is executed:

https://github.com/square/okhttp/blob/5ecd590c8c0cd7833ed378c8702d3a228817b4e8/okhttp/src/main/java/okhttp3/internal/platform/Jdk8WithJettyBootPlatform.java#L85

and that ALPN class is on the normal classpath, in addition to the boot classpath, then the class will be initialized from the class' ClassLoader, _not_ from the 'null' (system / bootstrap) classloader.

Then, Jetty will fail to initialize its `OpenJDK8ServerALPNProcessor` because the following check will fail:

https://github.com/eclipse/jetty.project/blob/f88f856673f2e8768042c973481ad78d41910e22/jetty-alpn/jetty-alpn-openjdk8-server/src/main/java/org/eclipse/jetty/alpn/openjdk8/server/OpenJDK8ServerALPNProcessor.java#L44-L45

We've usually hit this failure case when initializing okhttp clients in tests first (simply due to an unfortunate class load ordering), and only later loading the [jetty ALPN agent](https://github.com/jetty-project/jetty-alpn-agent) dynamically by calling a method [Http2Agent.install](https://github.com/palantir/conjure-java-runtime/blob/4f7e9c6428b356394771ef136f22bb4ad825877e/jetty-http2-agent/src/main/java/com/palantir/conjure/java/http2/Http2Agent.java#L33-L50) in a static initializer.

TODO:

- [x] test: https://github.com/square/okhttp/pull/4617

**Comment by swankjesse** [comment]
Weird. Why is it on both class paths? Wanna send a PR to force the boot class loader?

**Comment by dansanduleac** [comment]
Because if you want to support java 9+ too, then you need to depend on `org.eclipse.jetty:jetty-alpn-java-server`, which brings `org.eclipse.jetty.alpn:alpn-api` as a dependency, which contains that same class 😉
