### ISSUE TITLE
Tests hanging in HttpOverHttp2Test

### ISSUE THREAD

**Issue by swankjesse** [square/okhttp#4633]
I’ve seen this twice, both times on JDK11. This is alarming.
```
01:53:45:383 [INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.005 s - in okhttp3.internal.http2.HuffmanTest
01:53:45:384 [INFO] Running okhttp3.internal.http2.HttpOverHttp2Test


No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received

The build has been terminated
```

**Comment by galderz** [comment]
Just [happened](https://travis-ci.org/square/okhttp/jobs/503531285) in one my PRs with openjdk8.

**Comment by yschimke** [comment]
If we looked at circleci, we could use the test metadata collection to spot these sorts of problems sooner.

https://circleci.com/docs/api/v1-reference/#test-metadata
https://circleci.com/docs/2.0/insights/

On Travis, I think we probably need to rely on junit timeout rules.  I'll put up a PR see if we can pin it down.

**Comment by yschimke** [comment]
Going to hit restart on this a few times

https://travis-ci.org/square/okhttp/builds/503816334?utm_source=github_status&utm_medium=notification

**Comment by amirlivneh** [comment]
It may be faster to do **More options -> Trigger Build** multiple times until you hit the limit.

**Comment by yschimke** [comment]
Or land as is, and see when it fails in master, and on which tests.

**Comment by amirlivneh** [comment]
The new timeout was triggered for HttpOverHttp2Test.recoverFromCancelReusesConnection() in https://travis-ci.org/square/okhttp/jobs/504609207.

**Comment by yschimke** [comment]
```
okhttp3.internal.http2.HttpOverHttp2Test
10:12:15:907 [ERROR] recoverFromCancelReusesConnection[h2](okhttp3.internal.http2.HttpOverHttp2Test)  Time elapsed: 5.006 s  <<< ERROR!
org.junit.runners.model.TestTimedOutException: test timed out after 5 seconds
	at okhttp3.internal.http2.HttpOverHttp2Test.callAndCancel(HttpOverHttp2Test.java:909)
	at okhttp3.internal.http2.HttpOverHttp2Test.recoverFromCancelReusesConnection(HttpOverHttp2Test.java:856)
10:12:15:908 [ERROR] concurrentHttp2ConnectionsDeduplicated[h2](okhttp3.internal.http2.HttpOverHttp2Test)  Time elapsed: 0.215 s  <<< FAILURE!
java.lang.AssertionError: expected:<1> but was:<2>
	at okhttp3.internal.http2.HttpOverHttp2Test.concurrentHttp2ConnectionsDeduplicated(HttpOverHttp2Test.java:1415)
10:12:15:908 [ERROR] cancelWithStreamNotCompleted[h2](okhttp3.internal.http2.HttpOverHttp2Test)  Time elapsed: 0.167 s  <<< FAILURE!
java.lang.AssertionError: expected:<1> but was:<2>
	at okhttp3.internal.http2.HttpOverHttp2Test.cancelWithStreamNotCompleted(HttpOverHttp2Test.java:770)

```

**Comment by amirlivneh** [comment]
A possible scenario is that https://github.com/square/okhttp/blob/12bc2b7bde7cbf70be932729045120dc021e25e7/okhttp-tests/src/test/java/okhttp3/internal/http2/HttpOverHttp2Test.java#L909 waits forever, possibly when we cancel the call in some very specific timing where cancellation doesn't take effect.

**Comment by amirlivneh** [comment]
There may be multiple failure modes here. This is one of them: While in most runs, the first request is canceled before the client starts to read the response body, in some runs, it's canceled after the client starts to read the response body and the first call doesn't fail as expected.

**Comment by amirlivneh** [comment]
In another failure mode, the first request is cancelled before the server dispatches the first mocked response from the queue. The first mocked response, which is set to send a body after a 10 second delay, is then used to respond to the second request, which triggers the 5 second test timeout.

**Comment by yschimke** [comment]
Haven't seen this hang recently, closing.
