### ISSUE TITLE
Handling comma in cookie values

### ISSUE THREAD

**Issue by jaruyot** [square/okhttp#4636]
Hello,

I'm developing a mobile application using React Native which is using OkHttp as HTTP client in the Android version. My issue is how OkHttp handles commas in cookie values. When the client receives "set-cookie" header which contains a comma in the cookie value, OkHttp parses the value until the comma and ignores the rest of the value. I know that [RFC6265](https://tools.ietf.org/html/rfc6265#section-4.1) doesn't allow comma, but it seems to be widely supported in browsers such as Google Chrome and Safari.

I have located this line in the cookie parser in [JavaNetCookieJar.java](https://github.com/square/okhttp/blob/ded5e1fd264c68de31901dd3f2596bc35c5dd7cb/okhttp-urlconnection/src/main/java/okhttp3/JavaNetCookieJar.java#L91):

`pairEnd = delimiterOffset(header, pos, limit, ";,");`

This code seems to expect that cookie name-value pairs can be separated by either a semicolon _or_ comma, but I'm not certain whether a comma is valid cookie separator (I have only seen semicolons used).

Hence my suggestion/question: Can we remove comma as cookie separator in the line above or is there any potential issue that I might have missed?

cc @swankjesse

**Comment by swankjesse** [comment]
We’re trying to satisfy a different discouraged case where the server folds multiple set-cookie headers into a single line, like this:

```
Set-Cookie: c1=first, c2=second
```

This is discouraged per the spec:

> Origin servers SHOULD NOT fold multiple Set-Cookie header fields into a single header field.  The usual mechanism for folding HTTP headers fields (i.e., as defined in [RFC2616]) might change the semantics of the Set-Cookie header field because the %x2C (",") character is used by Set-Cookie in a way that conflicts with such folding.

My preference is to retain our current behavior, only because changing it risks breaking existing users.

**Comment by swankjesse** [comment]
Studying our code some more, you won’t get this behavior if you don’t use JavaNetCookieJar. The regular CookieJar has more modern behavior.

**Comment by swankjesse** [comment]
No action to take on this.
