### ISSUE TITLE
Wiki page all about caching

### ISSUE THREAD

**Issue by swankjesse** [square/okhttp#4637]
Stuff like:
 * HTTP caching heuristics [source?](https://publicobject.com/2015/03/26/how-do-http-caching-heuristics-work/)
 * what it means if cacheResponse() and networkResponse() are both non-null (issue #4539)
 * why you need to read the entire response before an entry is stored
 * the cache must not compete with other processes for the same directory
 * pruning the cache manually

**Comment by MetalDent** [comment]
Hi, anyone working on this issue?

**Comment by eduardoflorendo** [comment]
#5525

**Comment by eduardoflorendo** [comment]
#5528

**Comment by eduardoflorendo** [comment]
#

**Comment by eduardoflorendo** [comment]
#

**Comment by yschimke** [comment]
Also how to avoid network when there is a viable cache entry.

```
        // Use the cache without hitting the network first
        // 504 code indicates that the Cache is stale
        val preferCache = CacheControl.Builder()
            .onlyIfCached()
            .build()
```

**Comment by yschimke** [comment]
Working on this in a draft PR.

https://github.com/square/okhttp/pull/6009/files
