### ISSUE TITLE
EventListener.requestFailed(), responseFailed()

### ISSUE THREAD

**Issue by swankjesse** [square/okhttp#4638]
We don’t have a mechanism to signal that a request or response has failed. This can happen even if the call ultimately succeeds due to our retry mechanisms. I’d like new events for these.

**Comment by yschimke** [comment]
https://github.com/square/okhttp/blob/19771365f25d986d125478a75c15d24d6e285e12/okhttp/src/main/kotlin/okhttp3/EventListener.kt#L291

https://github.com/square/okhttp/blob/19771365f25d986d125478a75c15d24d6e285e12/okhttp/src/main/kotlin/okhttp3/EventListener.kt#L376
