### ISSUE TITLE
Connection leaks if WebSocket handshake fails

### ISSUE THREAD

**Issue by amirlivneh** [square/okhttp#4658]
This is a recent regression bisected to dd70407455f09f3eda7288f0bb9610f8943af03e.

It may be the cause for the recent increase in test flakiness.

To reproduce, run this modified test:
```
  @Test public void missingConnectionHeader() throws IOException {
    webServer.enqueue(new MockResponse()
        .setResponseCode(101)
        .setHeader("Upgrade", "websocket")
        .setHeader("Sec-WebSocket-Accept", "ujmZX4KXZqjwy6vi1aQFH5p4Ygk="));
    newWebSocket();

    clientListener.assertFailure(101, null, ProtocolException.class,
        "Expected 'Connection' header value 'Upgrade' but was 'null'");

    client.connectionPool().evictAll();
    assertEquals(0, client.connectionPool().connectionCount());
  }
```

**Comment by swankjesse** [comment]
Nice find. Can fix.

**Comment by swankjesse** [comment]
I was playing with this and experimented running websockets calls over our new duplex mechanisms. Seems doable though there are some drawbacks. We’d need `GET` upgrade requests to have a duplex body! But the upside is you’d be able to optimistically send request frames before the response was received.

**Comment by galderz** [comment]
Not sure if strictly related, but I've just seen `WebSocketHttpTest .missingConnectionHeader` fail (see #4695)
