### ISSUE TITLE
Multipart upload has no Content-Length in header if return -1 in RequestBody.contentLength

### ISSUE THREAD

**Issue by ethanlee27** [square/okhttp#4664]
Hi,
I'm trying to upload a file to our server, I have tried compose header and body by HttpClient like below and it's work:

[My Header]:
Content-Length:	215
Content-Type:	multipart/form-data;boundary=*****
Content-Encoding:	UTF-8
Host:	192.168.82.107:8080
Connection:	Keep-Alive

[My Body]:
--*****
Content-Disposition: form-data; name="Filename"

\okhttp.txt
--*****
Content-Disposition: form-data; name="Filedata"; filename="okhttp.txt"
Content-Type: application/octet-stream

okhttp
--*****--

Now we prefer to use okHttp because it's more popular and support Http 2.0.
So I try to upload the same file again, but it's failed by the two cases I've tried:
1. If I return -1 in RequestBody.contentLength(), then header will not add Content-Length.
2. If I return the right length in RequestBody.contentLength(), the header will add the right Content-Length, but server will return like size not match error to me.

By upload successfully with HttpClient case, I guess I need no RequestBody.contentLength() and need Content-Length in header, so how can I achieve this case by okHttp?

I've searched and found this issue: https://github.com/square/okhttp/issues/2050
I know its' some reason by your designed.
Or you can add some option to let user more flexible to decide add content-length in body or in header individually?

**Comment by JakeWharton** [comment]
One way to know the length is to write the body to a `Buffer()` and then create a new body with its contents and the now-known length. Otherwise this seems working as designed.

**Comment by swankjesse** [comment]
No action to take here.
