### ISSUE TITLE
Static interface methods are only supported starting with Android N in Kotlin 1.3.20 

### ISSUE THREAD

**Issue by adrian09h** [square/okhttp#4668]
When I've added the library in gradle and build, I got an error.

> implementation 'com.squareup.okhttp3:logging-interceptor:3.13.1'

*Static interface methods are only supported starting with Android N*

**Comment by JakeWharton** [comment]
Per [the release notes](https://github.com/square/okhttp/blob/master/CHANGELOG.md#version-3130), OkHttp requires that you enable Java 8 in your builds to function as of 3.13 and newer. You can learn more about how to enable this at https://developer.android.com/studio/write/java8-support.

You need to add something like
```groovy
android {
    compileOptions {
        targetCompatibility = "8"
        sourceCompatibility = "8"
    }
}
```
to your application `build.gradle`.

**Comment by adrian09h** [comment]
Thank you.
Now it's working fine.
