### ISSUE TITLE
CookieJar not working on Android Pie

### ISSUE THREAD

**Issue by bantheban** [square/okhttp#4673]
Anyone encountered problem where your app network calls work perfectly on devices which are not on Android Pie, but fails on Android Pie? I use cookie authorization for my Android app, and it works perfectly with OkHttp client which is setup like this: 

```
CookieManager cookieManager = new CookieManager();
cookieManager.setCookiePolicy(CookiePolicy.ACCEPT_ALL);
JavaNetCookieJar cookieJar = new JavaNetCookieJar(cookieManager);

OkHttpClient client = new OkHttpClient.Builder().cookieJar(cookieJar).build();
```

Problem appears on Android 9 (Pie) devices, where my server fails to fetch cookies from request I call on my device.

**Comment by bantheban** [comment]
It seems that the problem was in CertificateFactory.getInstance("X.509", "BC"), X.509 is not found for Android 9. CertificateFactory.getInstance("X509") is the fix.

**Comment by swankjesse** [comment]
No further action to take here.
