### ISSUE TITLE
Upgrade to JUnit 4.13

### ISSUE THREAD

**Issue by amirlivneh** [square/okhttp#4683]
I'm specifically interested in the fix for https://github.com/junit-team/junit4/pull/1517, which affects OkHttp tests that use a Timeout rule.

**Comment by JakeWharton** [comment]
Yes please! I think we'd all be comfortable using beta 2 since it's only test APIs. I wouldn't force it onto our consumers in MockWebServer until stable, though.

**Comment by swankjesse** [comment]
Fixed with https://github.com/square/okhttp/pull/5718/files
