### ISSUE TITLE
failedRoutes in RouteDatabase causes Full GC

### ISSUE THREAD

**Issue by lfz757077613** [square/okhttp#4689]
1. In my project, I used Okhttp with a large of proxies. Most of the proxies were used only once, so failedRoutes saved too many routes and cause full gc all the time
2. I think that failedRoutes use a time-bound cache instead of a simple set is better

**Comment by swankjesse** [comment]
Wow!

**Comment by parker89** [comment]
I encountered this issue as well, and filed a PR to fix it: https://github.com/square/okhttp/pull/5746

**Comment by lfz757077613** [comment]
> I encountered this issue as well. This PR should fix it: #5746

cool~I hava used [ahc](https://github.com/AsyncHttpClient/async-http-client) for a long time, very good performance. I think you can also try it

**Comment by yschimke** [comment]
Comment by @swankjesse https://github.com/square/okhttp/pull/5746#issuecomment-578387225

Inverts the problem from RouteSelector -> 1xRouteDatabase -> X*Y*Address

to

RouteSelector -> X*RouteDatabase -> Y*Address

X is client settings like SSL Socket Factory
Y is address like host, port etc

**Comment by swankjesse** [comment]
Yes! You explained it much better.

**Comment by yschimke** [comment]
Should we scope the connection pool instead of route database here?
