### ISSUE TITLE
ssl handshake time 

### ISSUE THREAD

**Issue by ankitjain10** [square/okhttp#4692]
Good bug reports include a failing test! Writing a test helps you to isolate and describe the problem, and it helps us to fix it fast. Bug reports without a failing test or reproduction steps are likely to be closed.

Here’s an example test to get you started.
https://gist.github.com/swankjesse/981fcae102f513eb13ed

HttpLoggingInterceptor logging = new HttpLoggingInterceptor();
      // set your desired log level
      logging.setLevel(HttpLoggingInterceptor.Level.BODY);
      OkHttpClient okHttpClient = new OkHttpClient().newBuilder()
          .connectTimeout(TIMEOUT, TimeUnit.SECONDS)
          .readTimeout(TIMEOUT, TimeUnit.SECONDS)
          .writeTimeout(TIMEOUT, TimeUnit.SECONDS)
          .addNetworkInterceptor(new Interceptor() {
            @Override public Response intercept(Chain chain) throws IOException {
              okhttp3.Request request = chain.request()
                  .newBuilder()
                  .build();
              return chain.proceed(request);
            }
          })
          .addInterceptor(logging)
          .build();

      mRetrofit4 = new Retrofit.Builder().baseUrl("https://enquiry.indianrail.gov.in/crisntes/")
          .client(okHttpClient)
          .addConverterFactory(new NullOnEmptyConverterFactory())
          .addConverterFactory(new ToStringConverterFactory())
          .addConverterFactory(ScalarsConverterFactory.create())
          .addConverterFactory(GsonConverterFactory.create())
          .build();
      mApiHelper4 = mRetrofit4.create(ApiHelper.class);

getting SSL handshake exception
It is working when making network call using HttpUrlConnection

**Comment by swankjesse** [comment]
Try with the COMPATIBLE_TLS ConnectionSpec?

https://github.com/square/okhttp/wiki/HTTPS

**Comment by ankitjain10** [comment]
Thanks. It is working now, 
It was previously working without ConnectionSpec but it stopped recently. 
Anyways thanks for saving my a55.

**Comment by ankitjain10** [comment]
Now a new problem have occurred.
It is working but if app goes idle/background for say 5-6 minutes then again if I am hitting it is giving
Error:-
javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0x7aeaf80080: Failure in SSL library, usually a protocol error
error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER (external/boringssl/src/ssl/tls_record.cc:239 0x7aeccb50bf:0x00000000)
I am recreating retrofit instance every time,I have to kill the App and open again to hit API.

**Comment by swankjesse** [comment]
https://github.com/grpc/grpc/issues/9538#issuecomment-366402388
