### ISSUE TITLE
Android 6.0.1 Use OkHhttp  with Retrofit  cause:  java.lang.InternalError:  Invoking getAttribute with bad arg 0

### ISSUE THREAD

**Issue by nicai1900** [square/okhttp#4697]
Use OkHttp with Retrofit   Crash only on  Android 6.0.1 Devices， Maybe an ART Bug?

##  Versions:
Okhttp:   3.10.0
Retrofit:  2.4.0
Rxjava:  2.0.8
Android Gradle Plugin: 3.2.1

## Crash log：
```
 java.lang.InternalError:Invoking getAttribute with bad arg 0, type 'Lcom/example/user/model/RegisterModel;' not instance of 'Ljava/lang/String;'

2  at com.example.user.UserHelper$Companion.io.reactivex.Observable register(com.example.user.model.RegisterModel)(SourceFile:77)
3  at com.example.user.login.LoginPresenter.io.reactivex.Observable 

```
## My Code：
 
```kotlin

interface ApiService {

    @POST(AppConfig.API_PATH + "/register")
    fun register(@Body registerModel: RegisterModel): Observable<LoginRespResult>

}

@Keep
class RegisterModel {
    @SerializedName("email")
    @JvmField
    var emailAddress: String? = null
    @SerializedName("password")
    @JvmField
    var password: String? = null

}

@Keep
class LoginRespResult {
    @SerializedName("auth")
    @JvmField
    var userAuth: UserAuth? = null
}

// call api

fun test() {
       HttpClient.API.register(registerModel)
                .subscribeOn(Schedulers.io())
                .observeOn(AndroidSchedulers.mainThread())
                .subscribe()                
}

```

##   Someone other  asked：
[Redmi note 3 ,Android 6.0.1 crash](https://cloud.tencent.com/developer/ask/196354)

`
java.lang.InternalError: Invoking with bad arg 0, type 'Lokhttp3/RequestBody$2;' not instance of '[Ljava/lang/Object;'
2    at com.sfpush.pushsdk.PushManager.getRegistrationId(PushManager.java:152)
3    at com.sfpush.pushsdk.PushManager.start(PushManager.java:63)
4    at com.sferp.employe.ui.MainActivity.onCreate(MainActivity.java:174)
5    at android.app.Activity.performCreate(Activity.java:6278)
6    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
7    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2396)
8    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2503)
9    at android.app.ActivityThread.-wrap11(ActivityThread.java)
10    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1353)
11    at android.os.Handler.dispatchMessage(Handler.java:102)
12    at android.os.Looper.loop(Looper.java:148)
13    at android.app.ActivityThread.main(ActivityThread.java:5529)
14    at java.lang.reflect.Method.invoke(Native Method)
15    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:745)
16    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:635)
`

## Related stackoverflow question:
[Why does Facebook and Messenger set the vmSafeMode option as false to the manifest file?
](https://stackoverflow.com/questions/54439914/why-does-facebook-and-messenger-set-the-vmsafemode-option-as-false-to-the-manife?newreg=73e576d3be374379a22241849dd184ab)

**Comment by nicai1900** [comment]
Related issue  #2836

**Comment by swankjesse** [comment]
Executable test case? As is this is not actionable.

**Comment by nicai1900** [comment]
> Executable test case? As is this is not actionable.

It's sample code

**Comment by drakeet** [comment]
Got the same error:
Fatal Exception: java.lang.InternalError: Invoking get with bad arg 0, type 'Ljava/lang/String;' not instance of 'Lcom/****;'

okhttp version: 4.3.1

**Comment by xiaomingmuzi** [comment]
> Got the same error:
> Fatal Exception: java.lang.InternalError: Invoking get with bad arg 0, type 'Ljava/lang/String;' not instance of 'Lcom/****;'
> 
> okhttp version: 4.3.1
> 
> Device:
> 
> ![image](https://user-images.githubusercontent.com/5214214/74163262-10751700-4c5d-11ea-89eb-55cb19008b93.png)

hello ，got the same error，so how to solve it

**Comment by zhihuangcao** [comment]
got the same error，so how to solve it

**Comment by xialonghua** [comment]
got the same error，so how to solve it

**Comment by yschimke** [comment]
Provide steps to reliably reproduce. A sample app or project to build. Does it happen with emulator?

**Comment by xialonghua** [comment]
> Provide steps to reliably reproduce. A sample app or project to build. Does it happen with emulator?

The crash happened online，we can not reproduce.the code is correct,use apktool to check smali

**Comment by yschimke** [comment]
We can't help.  Consider raising with the device manufacturers, although if the devices are rooted like above then it's a wild west and unlikely they will support. These types of issues are somewhat common with the huge variety of older devices and we can't fix or debug for you.

**Comment by xialonghua** [comment]
> We can't help. Consider raising with the device manufacturers, although if the devices are rooted like above then it's a wild west and unlikely they will support. These types of issues are somewhat common with the huge variety of older devices and we can't fix or debug for you.

thanks,we will follow up this issue.

**Comment by xiaobailong24** [comment]
Got same error. Maybe art 6.0 bug.

**Comment by xiaobailong24** [comment]
@nicai1900 how to sovle it finally?

**Comment by hzy00** [comment]
still get the same error, how to solve it?
