### ISSUE TITLE
File Descriptors exhausted by Cache

### ISSUE THREAD

**Issue by awenger** [square/okhttp#4699]
We are observing crashes in a Android app that are caused by the exhaustion of the available File Descriptors.
This seems to happen if many requests are `Call.enqueue`ed. We already made sure that we only have a single OkHttp instance.
While debugging it on a rooted emulator it seems to only happen if `OkHttpClient.Builder.cache()` is used.
### `Call.enqueue`ing a few thousand calls, with a Cache set, leads to:
- number of open File Descriptors goes up quite fast (well beyond 1k) and decreases slowly as the requests are being processed. If it does not crash because of missing File Descriptors it will go back to a normal number again once requests are finishing. 
```
...
/proc/<pid>/fd # ls -al | wc -l                                                                                        
967
/proc/<pid>/fd # ls -al | wc -l                                                                                        
1327
/proc/<pid>/fd # ls -al | wc -l                                                                                        
1617
/proc/<pid>/fd # ls -al | wc -l                                                                                        
1963
/proc/<pid>/fd # ls -al | wc -l                                                                                        
1547
/proc/<pid>/fd # ls -al | wc -l                                                                                        
1040
/proc/<pid>/fd # ls -al | wc -l                                                                                        
536
/proc/<pid>/fd # ls -al | wc -l                                                                                        
149
```
and there are thousand of open File Descriptors like:
```
/proc/<pid>/fd # ls -al

/<path-to-the-http-cache>/c5c99e84ce2ff13078cb523c95d74dff.1.tmp
/<path-to-the-http-cache>/e4e886e180225e2e05a2e1cf94537ef9.1.tmp
/<path-to-the-http-cache>/80de10600cb6c424fe994169e1135620.1.tmp
/<path-to-the-http-cache>/043d5411a5b6f8930d8c34397b983e74.1.tmp
```

### `Call.enqueue`ing a few thousand calls, with**out** a Cache set, leads to:
- steady number of open File Descriptors that stays around that number while the requests are being fetched
```
/proc/<pid>/fd # ls -al | wc -l                                                                                        
150
```

For both runs (with and without cache) the app storage was cleared (nothing cached yet), so I think it is caused by OkHttp Cache writing all the responses to the File System.

**Comment by swankjesse** [comment]
Do you close the HTTP response when you’re done reading it?

**Comment by awenger** [comment]
I'm quite sure we are closing the response properly, otherwise the file descriptors should also skyrocket during the run that has no cache in place, right?
However to make sure that my understanding of kotlins [`use`](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.io/use.html) and suspend functions ([`suspendCancellableCoroutine`](https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/suspend-cancellable-coroutine.html)) is not failing me, here is how the requests are triggered:
```kt
@Throws(IOException::class)
suspend fun get(params): Data {
    val req = Request.Builder().....build()
    httpClient.newCall(req).await().use { response ->
        return when (response.code()) {
            // just extracting some data from the response
            200  -> Data(response.header("content-type"), response.body()?.bytes() ?: throw IOException("body missing"))
            else -> throw IOException("${response.code()} - Unexpected Response during resource get")
        }
    }
}
```

The response is `await`ed with this (very similar to how it is done in [gildor/kotlin-coroutines-okhttp](https://github.com/gildor/kotlin-coroutines-okhttp/blob/257ad2e0c3784a363876096d1bb5c201a366ded1/src/main/kotlin/ru/gildor/coroutines/okhttp/CallAwait.kt#L36-L57)):
```kt
suspend fun Call.await(): Response {
    return suspendCancellableCoroutine { continuation ->
        enqueue(object : Callback {
            override fun onResponse(call: Call, response: Response) {
                continuation.resume(response)
            }
            override fun onFailure(call: Call, e: IOException) {
                continuation.resumeWithException(e)
            }
        })
        continuation.invokeOnCancellation { cancel() }
    }
}
```

**Comment by JakeWharton** [comment]
That is not safe. You'll need to use
https://github.com/Kotlin/kotlinx.coroutines/pull/1084 and pass
`response::close` for the cancelation lambda. If there's a race between
`resume` and `cancel`, currently, the object will leak.

**Comment by awenger** [comment]
Thanks for the hint. I just tried it with the new kotlin/coroutines version and changed the `await()` function to:
```kt
suspend fun Call.await(): Response {
    return suspendCancellableCoroutine { continuation ->
        enqueue(object : Callback {
            override fun onResponse(call: Call, response: Response) {
                continuation.resume(response) { response.close() }
            }
            override fun onFailure(call: Call, e: IOException) {
                continuation.resumeWithException(e)
            }
        })
        continuation.invokeOnCancellation { cancel() }
    }
}
```
Nevertheless, if I use okhttp with the `Cache` the open file descriptors skyrocket and the app crashes after some time. Without the `Cache` it processes all requests with a maximum of ~300 open file descriptors.

**Comment by farrukhnajmi** [comment]
We are facing the same issue on Android 4.3 (but not on on Android 6) when using okhttp cache. The following issue may be relevant on Android 4.3:

https://stackoverflow.com/questions/20367647/android-httpurlconnection-is-not-closing-eventually-results-to-socketexceptio/20417556#20417556

The solution proposed (Connection/Close header prop) is not good because we want to keep connection open to servers the android device talks to.

**Comment by awenger** [comment]
@yschimke I was not aware that this needed input from my side. I thought the "needs info" was related to 
> Do you close the HTTP response when you’re done reading it?

What do you need in terms of reproducible test case. Exhausting file descriptors and a crashing app are hard to write tests for. So I guess a sample app that has the described behavior?

**Comment by yschimke** [comment]
@awenger Yep - something like that.  If you can hack a failing test case in 

https://github.com/square/okhttp/blob/master/android-test/src/androidTest/java/okhttp/android/test/OkHttpTest.kt

it would really help.  Reopen if possible.
