### ISSUE TITLE
java.lang.NoClassDefFoundError: java.util.Objects

### ISSUE THREAD

**Issue by APLK** [square/okhttp#4716]
Genymotion Samsung Galaxy S2 4.1.1 API16 480*800

![TIM截图20190314145058](https://user-images.githubusercontent.com/24518328/54337169-0ae80900-4669-11e9-9f73-a814ee6028b8.jpg)
![TIM截图20190314145509](https://user-images.githubusercontent.com/24518328/54337208-2f43e580-4669-11e9-88ec-512dd5b1bc0e.jpg)

**Comment by APLK** [comment]
reduce the version to 3.8.0,solved the problem

**Comment by swankjesse** [comment]
https://medium.com/square-corner-blog/okhttp-3-13-requires-android-5-818bb78d07ce

**Comment by APLK** [comment]
thanks!

**Comment by APLK** [comment]
There is still a problem. After the network is disconnected, the request is sent.Send request again when connected to the network,it gives the timeout error twice and works fine third time
