### ISSUE TITLE
自定义的Interceptor中怎么取消当前所有正在进行的网络请求

### ISSUE THREAD

**Issue by chenxi0203** [square/okhttp#4742]
自定义的Interceptor中怎么取消当前所有正在进行的网络请求。

**Comment by swankjesse** [comment]
Executable test case?!

**Comment by chenxi0203** [comment]
就是我在自定义拦截器中如果拦截到某中状态时要结束当前所有并发的请求，使用OkHttpClient.dispatcher().cancelAll()试了没用效果。

**Comment by yschimke** [comment]
How to cancel all current online requests in the custom Interceptor.
