### ISSUE TITLE
Building wiki page out of date

### ISSUE THREAD

**Issue by yschimke** [square/okhttp#4766]
https://github.com/square/okhttp/wiki/Building

refers to java 6 and 7

**Comment by MonikaJethani** [comment]
@swankjesse @JakeWharton Can I work on this?

**Comment by swankjesse** [comment]
Sure, please send a PR!

**Comment by monkey-mas** [comment]
Did we remove Building page? It's now redirected to [Contributing.md](https://github.com/square/okhttp/blob/master/CONTRIBUTING.md).

**Comment by swankjesse** [comment]
Yep, this is fixed.
