### ISSUE TITLE
Getting hit by submodule issues

### ISSUE THREAD

**Issue by yschimke** [square/okhttp#4767]
Not sure why I have seen this 3 times recently, but getting hit by submodule issues for clone.  I think this used to be automatic?

```
$ git submodule init
Submodule 'okhttp-hpacktests/src/test/resources/hpack-test-case' (git://github.com/http2jp/hpack-test-case.git) registered for path 'okhttp-hpacktests/src/test/resources/hpack-test-case'
$ git submodule update
```

**Comment by swankjesse** [comment]
It isn't automatic. I think it might be better to just exclude hpacktests by excluding ’em from settings.gradle.

**Comment by yschimke** [comment]
OK, so that was the change?  gradle including that module?

**Comment by swankjesse** [comment]
You got it.

**Comment by swankjesse** [comment]
And please comment it out or remove it!

**Comment by yschimke** [comment]
Added

```
    Assume.assumeFalse("Test stories missing, checkout git submodule", getStory() == Story.MISSING);
```
