### ISSUE TITLE
Apply ktlintFormat gradle plugin

### ISSUE THREAD

**Issue by yschimke** [square/okhttp#4776]
Implement the square style for Kotlin with ktlint and run against the code base

**Comment by yschimke** [comment]
Plugins

https://github.com/jlleitschuh/ktlint-gradle
https://github.com/jeremymailen/kotlinter-gradle

I've used the first one

**Comment by ZacSweers** [comment]
Spotless is another good option, and what I've seen used on some popular projects like https://github.com/nickbutcher/plaid or https://github.com/chrisbanes/tivi

https://github.com/diffplug/spotless

**Comment by swankjesse** [comment]
https://github.com/square/okhttp/pull/4925
