### ISSUE TITLE
CacheControl exposes two getters for Java consumers

### ISSUE THREAD

**Issue by shaishavgandhi05** [square/okhttp#4782]
With #4762, `CacheControl` has two getters for Java consumers. 
```java
CacheControl cacheControl = new CacheControl.Builder().build();
cacheControl.immutable();
cacheControl.getImmutable();
```

This might be confusing for consumers. Should we be adding `@get:JvmName("immutable")` to the `immutable` property?

**Comment by JakeWharton** [comment]
The properties should be private for now. Eventually they'll be public with `JvmName` and the functions will be marked with `Deprecation` and `JvmName` to provide migration support for Kotlin users.

**Comment by shaishavgandhi05** [comment]
Leave it as it is for now or should we move to private properties?

**Comment by swankjesse** [comment]
If you wanna send a PR, please do! Otherwise we'll clean it up before we release.
