### ISSUE TITLE
addNetworkInterceptor   Post method data is missing

### ISSUE THREAD

**Issue by MyWdq** [square/okhttp#4808]
OkHttpClient.Builder builder = new OkHttpClient.Builder()
                .retryOnConnectionFailure(true)
                .connectTimeout(60, TimeUnit.SECONDS)
                .writeTimeout(60, TimeUnit.SECONDS)
                .readTimeout(60, TimeUnit.SECONDS)
                .addNetworkInterceptor(mTokenInterceptor)
                .addInterceptor(interceptor);

Interceptor mTokenInterceptor = new Interceptor() {
        @Override
        public Response intercept(Chain chain) throws IOException {
        Request request = chain.request();

       String  tests = "f150bdcae8578d4f1db3646ead4ef002c282a6ebde6e3b9bf464e94cdae68b34b73e0b7697140d303465de824754ed8aafac388787be325f687f6c0b918c8044c6813c35314735a59bd225aa59aeb99f97942e3fe9ab0846056101c09cc3e72a52bb91eadf503752c48b8b54cda3e368a99246c97f1297a1771865869ad108dc5088355489ac0e5b63cc355c0f0facbfb713228ec062ed927cdb517bab0ac79d5cb6ccd36b5048a38ab16137a99bee80c94bc2f3d98d7843ce0e16b350b5f4a1e11e37bd72c366f1e22af8bcc359a0117f3ed3914bfe55228f1be9b43e1d1fbc93da7743a7c33613fc00305ee194b85010b8a014f871533e60890a576ff31ea46906d9fe85b3ddc2c4ffca549fde9e5de829ef05d5636733c2a87a0d7c74791f6006ccace21220f0";    （Encrypt the data）
              （or  application/json）                  
            RequestBody requestBody = RequestBody.create(MediaType.parse("text/plain"), tests);
            request = request.newBuilder().post(requestBody).build();

            return chain.proceed(request);

        }

retrofit2：
@POST("{url}")
Observable<Response> getTestLogin(@Path(value = "url", encoded = true) String url, @Body Map<String, String> maps);

server  results：
f150bdcae8578d4f1db3646ead4ef002c282a6ebde6e3b9bf464e94cdae68b34b73e0b7697140d303465de824754ed8aafac388787be325f687f6c0b918c8044c6813c35314735a59bd225aa59aeb99f97942e3fe9ab0846056101c09cc3e72a52bb91eadf503752c48b8b54cda3e368a99246c97f1297a1771865869ad108dc5088355489ac0e5b63cc355c0f0facbfb71

Loss of data：
3228ec062ed927cdb517bab0ac79d5cb6ccd36b5048a38ab16137a99bee80c94bc2f3d98d7843ce0e16b350b5f4a1e11e37bd72c366f1e22af8bcc359a0117f3ed3914bfe55228f1be9b43e1d1fbc93da7743a7c33613fc00305ee194b85010b8a014f871533e60890a576ff31ea46906d9fe85b3ddc2c4ffca549fde9e5de829ef05d5636733c2a87a0d7c74791f6006ccace21220f0

No Interceptor   data is normal  （Cannot handle encryption uniformly  Body）
Why set Content-Length ???

**Comment by swankjesse** [comment]
Executable test case?

**Comment by MyWdq** [comment]
> 
> 
> Executable test case?

for android 

implementation 'com.squareup.okhttp3:okhttp:3.9.1'
implementation 'com.squareup.okhttp3:logging-interceptor:3.4.1'
implementation 'com.squareup.retrofit2:retrofit:2.3.0'
implementation 'com.squareup.retrofit2:converter-gson:2.3.0'
implementation 'com.squareup.retrofit2:adapter-rxjava2:2.3.0'
implementation 'io.reactivex.rxjava2:rxandroid:2.1.0'
implementation "io.reactivex.rxjava2:rxjava:2.x.y"

**Comment by swankjesse** [comment]
Unclear what action to take. Consider asking a question on StackOverflow.
