### ISSUE TITLE
After http2, connectPool prevent program from exit.

### ISSUE THREAD

**Issue by moonfruit** [square/okhttp#4815]
After complete a http2 connection, the connectPool prevent program from exit.

Code like this:
https://gist.github.com/moonfruit/2abfa558e9506b389cbef856817635a2

This program never exit, even the main thread terminate.
This happens on Java 11 (openjdk) and Java 12 (openjdk), but the program can exit normally on Java 8 (oracle jdk).

When I add `client.connectionPool().evictAll();` to the end of the main method, everything is ok.

And this only happens on http2 connection. (https://search.maven.org/ supports http2).

Now I must manually evict the connectionPool to make my program to run normally on java 11 or 12.

By the way, I didn't test this on Java 9 or 10.

**Comment by swankjesse** [comment]
That's working as intended.

**Comment by moonfruit** [comment]
After doing some research, I found that there are 3 threads on Java 11 or 12 that not exists on Java 8.

They are Thread[OkHttp Http2Connection,5,main], Thread[OkHttp search.maven.org,5,main] and Thread[OkHttp search.maven.org Writer,5,main].
Among them, Thread[OkHttp search.maven.org Writer,5,main] is not a daemon. I think he is the one which prevent program from exit.

1. Should Thread[OkHttp search.maven.org Writer,5,main] be created as a daemon?
2. Why are these 3 threads present on Java 11 or Java 12, or why are these 3 threads not present on java 8?

**Comment by moonfruit** [comment]
@swankjesse 

Why is this designed?
Why is it designed to be different between Java 8 and Java 11 or 12?

**Comment by swankjesse** [comment]
Java 8 can't do HTTP/2 without the alpn-boot library.

If we were to make it a daemon thread, async requests would occasionally not return because the program would exit.

**Comment by moonfruit** [comment]
When the program exit, shouldn't it stop everything? Even there is something being handled.

**Comment by moonfruit** [comment]
When other threads (not daemon) terminated, the program should exits.
Or OkHttp provide some destroy function.

**Comment by swankjesse** [comment]
Tracking here: https://github.com/square/okhttp/issues/4029
