### ISSUE TITLE
Handshake failed after updated to okhttp 3.14.0

### ISSUE THREAD

**Issue by MS893** [square/okhttp#4823]
When I use okhttp 3.12.2, I can make a GET request on https web site.

After upgrading to okhttp 3.14.0, I have an IO exception on execute when I perform the same GET request. The interceptor message indicates "handshake failed".

`request = new Request.Builder().url("https://anhttpswebsite").build();
response = client.newCall(request).execute();
`

**Comment by yschimke** [comment]
Can you run a report for the site with https://www.ssllabs.com/ssltest/

**Comment by MS893** [comment]
Hi,

here is the result.
Christian


Le sam. 30 mars 2019 à 13:33, Yuri Schimke <notifications@github.com> a
écrit :

**Comment by MS893** [comment]
Hi Yuri, I sent the report via email (using reply button)

**Comment by yschimke** [comment]
Hi,

my email isn't notifications@github.com

I suggest asking this sort of question on stackoverflow, most likely it's related to the server using insecure ciphers etc.

**Comment by MS893** [comment]
Ok, I understand the server makes the  problem, but why using okhttp 3.12.2 there is no handshake failed and using 3.14.0 there is a handshake failed ?

I' not sure I can get help on stackoverflow !

**Comment by yschimke** [comment]
In between those versions we dropped support for older unsupported versions of TLS

https://github.com/square/okhttp/blob/master/CHANGELOG.md

"TLSv1 and TLSv1.1 are no longer enabled by default"

But we are not setup to provide 1:1 support when often the fix is to upgrade your server etc, so you should use stackoverflow and make sure all relevant information is in the question you ask on stackoverflow.  There are a lot more people seeing your question there, than a bug tracker here.

**Comment by MS893** [comment]
Good to remove TLS 1 and TLS 1.1

But the server I try to connect uses 1.1 and 1.2
I also use Chrome 73 and I can access the website (since Chrome 72, TLS 1 and 1.1 are not supported anymore), so it shows that the server is accessible via TLS 1.2

I don't request a 1.1 support, and I can't upgrade the server (which is not mine !), anyway the server is TLS 1.1 and 1.2 so Chrome is working fine, okhttp 3.12.2 is working fine, okhttp 3.14.0 is not working...

I don't request any support, I just want to report my problem, that's all !

If there is no bug, OK... the end, but I don't need stackoverflow or something else !

**Comment by yschimke** [comment]
Yep. I appreciate that. But there are millions of ssl handshake failures happening every day between various servers and clients. This isn’t a reproducible bug report and it’s quite a lot of effort to investigate each one. So stackoverflow is a better forum for support. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by MS893** [comment]
I see, thanks Yuri
