### ISSUE TITLE
java.io.IOException: CRC: actual 0x648b6135 != expected 0x29d115fe

### ISSUE THREAD

**Issue by dingyong666** [square/okhttp#4850]
java.io.IOException: CRC: actual 0x648b6135 != expected 0x29d115fe
at okio.GzipSource.checkEqual(GzipSource.java:205)
at okio.GzipSource.consumeTrailer(GzipSource.java:173)
at okio.GzipSource.read(GzipSource.java:92)
at okio.RealBufferedSource$1.read(RealBufferedSource.java:430)
at java.io.InputStream.read(InputStream.java:101)

---------------------------------------------------------------------------------------

Test Url  https://www.toptoon.net/comic/contents_list?comic_id=80029 

---------------------------------------------------------------------------------------
Successful HTML

```
//..........
//gtag('send', 'pageview', 'comic/contents_list?comic_id=80029/comic/contents_list?comic_id=80029');

	}
	catch (e)
	{
	}

</script><img height="1" width="1" style="display:none"  src="https://www.facebook.com/tr?id=2099949253593107&amp;ev=CustomEvent&amp;cd[episode_idx]=&amp;cd[comic_id]=80029&amp;cd[user_idx]=0&amp;cd[pay_cnt]="/>
```

Read until this location sends an exception~

```
		//gtag('send', 'pageview', '/comic/contents_list?comic_id=80029');

	}
	catch (e)
	{
	}

//There's an anomaly here.
```

my code 
```
String url = "https://www.toptoon.net/comic/contents_list?comic_id=80029&tmp=undefined_undefined_pc";
        OkHttpClient okHttpClient = new OkHttpClient();
        Request request = new Request.Builder()
                .url(url).header("accept-encoding","gzip, deflate, br")
                .get()
                .build();
        Call call = okHttpClient.newCall(request);
        call.enqueue(new Callback() {
            @Override
            public void onFailure(Call call, IOException e) {
            }
            @Override
            public void onResponse(Call call, okhttp3.Response response) throws IOException {
                InputStream is = response.body().byteStream();
                GZIPInputStream gzin = new GZIPInputStream(is);
                InputStreamReader isr = new InputStreamReader(gzin, StandardCharsets.UTF_8);
                java.io.BufferedReader br = new java.io.BufferedReader(isr);
                StringBuffer sb = new StringBuffer();
                String tempbf;
                try {
                    while ((tempbf = br.readLine()) != null) {
                        sb.append(tempbf);
                        sb.append("\r\n");
                    }
                } catch (IOException e) {
                    e.printStackTrace();
                }
                isr.close();
                gzin.close();
                Log.i("body", "" + sb.toString());
            }
```

**Comment by swankjesse** [comment]
Remove the gzip accept header & decompression?

**Comment by dingyong666** [comment]
@swankjesse Yes, because the default gzip is the same error

**Comment by swankjesse** [comment]
Are you sure it's good data on the server?

**Comment by dingyong666** [comment]
@awankjesse  Using curl and browsers is successful

**Comment by dingyong666** [comment]
![](http://ww1.sinaimg.cn/large/006zDHY5gy1g1n8jndwypj30jp01dmx5.jpg)
![](http://ww1.sinaimg.cn/large/006zDHY5gy1g1n8k6nhw9j313t04aq38.jpg)

**Comment by dingyong666** [comment]
Using curl and browsers is perfect data

**Comment by swankjesse** [comment]
Can you curl with this flag: `-h "Accept-Encoding: gzip` and pipe the result to foo.txt.gz, then use gunzip on that file?

**Comment by dingyong666** [comment]
@swankjesse  

Excuse me, I executed the command 
```
curl 'https://www.toptoon.net/comic/contents_list?comic_id=80029&tmp=undefined_cn_pc' -H 'accept-encoding: gzip, deflate, br' -o t.gz --progress
```
Then unzip the file~  Gunzip decompression error, prompting file end error, but using online web panel (similar to cpanel) can decompress

**Comment by swankjesse** [comment]
Is it possible that the file is corrupt?

**Comment by dingyong666** [comment]
@swankjesse The document is undamaged，HTTP tools tests written in C # are normal

**Comment by dingyong666** [comment]
use local http debug tools
![](http://ww1.sinaimg.cn/large/006zDHY5gy1g1och7zl5dj30k70e70td.jpg)

**Comment by dingyong666** [comment]
you can open chrome url: view-source:https://www.toptoon.net/comic/contents_list?comic_id=80029

**Comment by swankjesse** [comment]
I recommend turning off OkHttp’s gzip support like so:
```
requestBuilder.addHeader("Accept-Encoding": "identity");
```
