### ISSUE TITLE
为什么弃用了streamAllocation  在3.14版本

### ISSUE THREAD

**Issue by lihua45678910** [square/okhttp#4857]
![image](https://user-images.githubusercontent.com/29397850/55389472-e7c5c080-5567-11e9-8312-bdf2a0682835.png)
![image](https://user-images.githubusercontent.com/29397850/55389488-f1e7bf00-5567-11e9-84c9-80a5664a002b.png)

**Comment by lihua45678910** [comment]
请问为什么直接弃用了 streamAllocation

**Comment by Egorand** [comment]
What's the type of `realChain`? If it's `okhttp3.Interceptor.Chain` then I'm not able to find the `streamAllocation()` method in previous versions of OkHttp. Is it an extension function defined somewhere else?

Also, please prefer using English when filing issues on this project, as this is the language the majority of maintainers and contributors use. Thanks!

**Comment by swankjesse** [comment]
That was not public API and we moved it in 3.14.

**Comment by lihua45678910** [comment]
thanks for  your reply ，
