### ISSUE TITLE
OkHttp failed future request when the previous request encountered this error java.net.SocketTimeOutException:timeout

### ISSUE THREAD

**Issue by jomarierafa** [square/okhttp#4869]
val logging = HttpLoggingInterceptor().apply { level = HttpLoggingInterceptor.Level.BODY }
        val internet = ConnectivityInterceptor(context)
        val chuck = ChuckInterceptor(context)
        val builder = OkHttpClient.Builder()
            .addInterceptor(internet)
            .connectTimeout(30, TimeUnit.SECONDS)
            .writeTimeout(30, TimeUnit.SECONDS)
            .readTimeout(30, TimeUnit.SECONDS)
        if (BuildConfig.DEBUG) {
            builder
                .addInterceptor(chuck)
                .addInterceptor(logging)
        }
        return builder.build()

i'm using 3.12.2
my application encountered the problem when the previous request is timeout ,, the app cant request to the server anymore , request always return timeout exception, it's need to relaunch the app or reconnect in the internet to make it works

**Comment by jomarierafa** [comment]
https://github.com/square/okhttp/issues/3974#issuecomment-396998924

look like this

**Comment by dagguh** [comment]
I have the same symptoms. Why is it closed?

**Comment by jomarierafa** [comment]
try to add this on your okhttpClient builder
.connectionPool(ConnectionPool(0, 1, TimeUnit.NANOSECONDS))
