### ISSUE TITLE
Support sha512 digest in CertificatePinner

### ISSUE THREAD

**Issue by hkhc** [square/okhttp#4870]
We have requirement to use sha512 digest for certificate pinning, and we have that in legacy code based on good old TrustManager. We planned to migrate it to okhttp. However the `CertificatePinner` in okhttp supports sha1 and sha256 only. 

On the other hand, `CertificatePinner` does not have extensibility in mind, so I cannot extend the class for additional type of digest. The simplest way to get out of the situation seems to be enhancing the `CertificatePinner` directly. If there is no fundamental cause to avoid sha512 digest, i am happy to contribute enhancement to the class.

**Comment by yschimke** [comment]
Curious, does this come from an RFC? or a decision made within your org.  Generally https://tools.ietf.org/html/rfc7469 seems to assume sha256 is the way forward for now.

**Comment by swankjesse** [comment]
Yeah, unless there's a security benefit it's just more complexity. I'd prefer to stick with what we have.

**Comment by hkhc** [comment]
@yschimke sadly it is corporate requirement of my project.

**Comment by yschimke** [comment]
@hkhc I suggest you implement a HostnameVerifier, that delegates to OkHostnameVerifier for the main checks, and then checks particular hosts also match your corporate requirements.

See https://github.com/square/okhttp/blob/5b37cda9e00626f43acf354df145fd452c3031f1/okhttp/src/main/java/okhttp3/internal/tls/OkHostnameVerifier.java#L48 for getting the certificates

**Comment by swankjesse** [comment]
@hkhc Where do you work? That’s a bad policy and your infosec people should feel bad.
