### ISSUE TITLE
Option to log cURL

### ISSUE THREAD

**Issue by muddassiroyo** [square/okhttp#4879]
Hi,

As a developer we sometimes need to verify the cURL that we are hitting and the cURL the server is expecting are same or different. Currently it is not available as an in-build functionality in the library. Everyone has to write their own interceptors.

Moreover the logs that print, if we enable logging, are verbose and contains all the information of the request but a well formed cURL is missing. 

We would appreciate if this could be a part of the library itself.

Thanks

**Comment by yschimke** [comment]
I've had great experience with this library https://github.com/mrmike/Ok2Curl

It won't be a core part of the okhttp library
