### ISSUE TITLE
java.lang.IllegalStateException: Unable to extract the trust manager on AndroidPlatform, sslSocketFactory is class org.conscrypt.OpenSSLSocketFactoryImpl at okhttp3.internal.platform.Platform.buildCertificateChainCleaner(Platform.java:183)

### ISSUE THREAD

**Issue by raviteja74** [square/okhttp#4880]
In my Android application i have two libraries one is chat and one is video calling when i opened first time video calling its working fine but when open after chat library open next time video calling not connected and crash was generated and get below exception like this java.lang.IllegalStateException: Unable to extract the trust manager on AndroidPlatform, sslSocketFactory is class org.conscrypt.OpenSSLSocketFactoryImpl
at okhttp3.internal.platform.Platform.buildCertificateChainCleaner(Platform.java:183)....(both side created sockets for different servers)

**Comment by swankjesse** [comment]
OkHttp does not support application-bundled Conscrypt on Android.
