### ISSUE TITLE
Okhttp multiple response handling for single http/2 request android

### ISSUE THREAD

**Issue by dsrisandhiya** [square/okhttp#4885]
I have an android application and I am trying to make an http/2 call with okHttp version 3.13.1, in my case for one request I will be receiving two responses sequentially separated by a time interval of 4 seconds from the server, but with the okHttp client integrated in my android application, I am getting only one response and if I try to send the same request using curl command I am able to receive two responses sequentially from the server.

Is there a way to handle multiple responses for a single http/2 request with OKHttp in android?

I tried various ways, but no luck:( Would be more than happy, if anyone could provide your inputs.

Thanks for your help and time in advance!!!

**Comment by swankjesse** [comment]
HTTP/2 cache push?

**Comment by dsrisandhiya** [comment]
> HTTP/2 cache push?

@swankjesse I am basically sending a get request from my android application to a server which supports  http/2, so expecting to receive 2 different response for that single request in a timely manner.i.e the second response will be sent from the server after 5 seconds gap of receiving the first response. 

Below is my response : 

First response 
event:initialize
data:{"session_id":"df313001-6461-431c-bcc1-7cb931bda4f5","deviceId":"YL0012345678"}

Second response
event:voice_response
data:{"intents":[{"version":0,"intent":"telstra_intent_voice","params":{"voiceResponse":{"displayText":"Launching now","vuiFileName":"E03.01.P2.V01.E.wav"},"action":{"ecp":"/launch-install/71361"}}}],"deviceId":"YL0012345678","channelId":"269671"}

But, in my case once I receive the first response the client is no longer listing to the server. When I receive the first response, in my log I see :
com.example.okhttp3 D/OkHttp: <-- END HTTP (166-byte body), 
so not receiving the second response.

Appreciate your help!

**Comment by swankjesse** [comment]
Ask on StackOverflow?

**Comment by dsrisandhiya** [comment]
yes asked, no response yet:(

When I try to send the request using curl command, it works as expected, only when I try to send via OkHttp I am facing this issue.

Do I need to specify anything in the HttpClient Builder?

**Comment by dsrisandhiya** [comment]
> Ask on StackOverflow?

yes asked, no response yet:(

When I try to send the request using curl command, it works as expected, only when I try to send via OkHttp I am facing this issue.

Do I need to specify anything in the HttpClient Builder?

**Comment by dsrisandhiya** [comment]
@swankjesse Is server push supported by okhttp now??

**Comment by swankjesse** [comment]
You got it. OkHttp doesn’t support server push. Tracking that here:
https://github.com/square/okhttp/issues/4156
