### ISSUE TITLE
EventListener method's are not called

### ISSUE THREAD

**Issue by rkuzner** [square/okhttp#4917]
We created an EventListener implementation to collect metrics data for insights.
We collect the data and thru a helper class we push it fire-and-forget to a dedicated api on our back-end.

On dev environments (debug run) and unit tests (mocked apps) we are able to successfully collect insights data (all EventListener methods get called).
On staging and prod environments, we have cases where:
a- `callStart()`, `dnsStart()`, `dnsEnd()`, `connectStart()` were called, **but** `secureConnectStart()` nor `secureConnectEnd()` nor `connectEnd()` nor `connectFailed()` nor `connectionAcquired()` were called
b- `callStart()` to `responseHeadersEnd()` were called, **but** `responseBodyStart()` nor `responseBodyEnd()` nor `connectionReleased()` nor `callEnd()` were called

For all the cases:
- okHttp v3.11.0 on dev, staging & prod
- okHttp v3.12.x was also tested (dev and staging) with the same behavior
- we call secured endpoints (https with valid TLS certificates) 
- the app has no weird functioning (no missed responses from backend nor missing payload from responses) 
- presence of `HttpLoggingInterceptor` in the interceptor chain (enabled or not) makes no difference (at least not worse)

Here you can take a look at the two classes that handle the collect and push the metrics:
https://gist.github.com/rkuzner/1b2e2224c4586fc7d0eb390f5f59632f

**Comment by swankjesse** [comment]
Can you make this into an executable test case? I suspect it’s more likely to be an issue with your environments (prod vs. staging vs. test) than with OkHttp.

**Comment by rkuzner** [comment]
Hi! 

We're working on making this into an reproducible test case, keeping the minimum needed for it to work and also checking if there is no other component that might interfere.

In the meantime, there is some additional info/clarifications:
- what I named as _staging_ are experimental versions that we run _internally_ with _live_ accounts
- on a few debug runs (on emulators) had also missing calls to Listener methods, sadly i'm not able to reproduce the case. I suspect this has something to do with cleaning the build and/or rebuilding the project.
- i need to confirm if our implementation of `connectionAcquired()` has some `null reference` issues with `connection.socket()`

I'll keep you updated!
