### ISSUE TITLE
Broken kotlin source compatibility

### ISSUE THREAD

**Issue by yschimke** [square/okhttp#4937]
I think this is hidden because KotlinSourceCompatibilityTest is in the same package 

Was: import okhttp3.CipherSuite.forJavaName
Now import okhttp3.CipherSuite.Companion.forJavaName

**Comment by yschimke** [comment]
Fixes a proven by KotlinSourceModernTest

**Comment by swankjesse** [comment]
Documented! https://github.com/square/okhttp/pull/5176
