### ISSUE TITLE
Square Org account for CircleCI?

### ISSUE THREAD

**Issue by yschimke** [square/okhttp#4941]
CircleCI seems like a win to me.  Now have builds for each platform (8 ALPN, 11, conscrypt etc) and it's quick signal on PRs with checks and tests reporting separately.

Maybe worth considering buying a beefy Square org account and making it even faster?

How about hitting Jack up for it?  It's basically one retreat he skips for the year and would improve PR experience even more.

BTW I don't have current plans to touch or get involved on the release side, so probably worth someone taking a look at some point so not to maintain both.

**Comment by swankjesse** [comment]
Already looking into it!
