### ISSUE TITLE
About UrlEncode

### ISSUE THREAD

**Issue by AliveDevs** [square/okhttp#4944]
![image](https://user-images.githubusercontent.com/39820743/56089699-77089780-5ec9-11e9-923a-1029efb4be98.png)

%e6%b2%89%e9%bb%98%e8%b5%8c%e5%8d%9a%ef%bc%8c%e4%b8%8d%e5%8f%af%e8%87%aa%e6%8b%94

is an encoded string  . i use it as part of url path
but in the end . it was encoded again. 
how i solve this problem ?

**Comment by yschimke** [comment]
Please ask on https://stackoverflow.com/questions/tagged/okhttp so that it builds the knowledgebase.  The issue tracker is for bug reports or feature requests.
