### ISSUE TITLE
HEAD requests break if the response contains the content-length header over HTTP2

### ISSUE THREAD

**Issue by danielflower** [square/okhttp#4948]
This is similar to #2998 except it only happens on HTTP2 requests. The following example with okhttp `3.14.1` shows the issue:

````java
@Test
public void headOverHttp2() throws IOException {
    try (Response resp = client.newCall(
        new Request.Builder()
            .head()
            .url("https://http2.akamai.com/demo")
            .build()
    ).execute()) {
        System.out.println("resp.protocol() = " + resp.protocol().toString());
        System.out.println("resp.header(\"content-length\") = " + resp.header("content-length"));
        System.out.println("resp.body().contentLength() = " + resp.body().contentLength());
        System.out.println("resp.body().bytes().length = " + resp.body().bytes().length);
    }
}
````

I get this output:

	resp.protocol() = h2
	resp.header("content-length") = 2421
	resp.body().contentLength() = 2421

	java.io.IOException: Content-Length (2421) and stream length (0) disagree
		at okhttp3.ResponseBody.bytes(ResponseBody.java:139)

It is `resp.body().bytes().length` that throws the exception. When not using HTTP2, the `resp.body().contentLength()` correctly returns 0, as does `resp.body().bytes().length`.

**Comment by swankjesse** [comment]
Can fix!

**Comment by danielflower** [comment]
Thanks. Also I just noticed something that may be related. The body content length returns 0 on a 204 (with no content length header) over http1 which seems correct, however it returns -1 over http2.
