### ISSUE TITLE
Add function for URL encoding header values

### ISSUE THREAD

**Issue by dlew** [square/okhttp#4957]
I am proposing that we support [RFC 8187](https://tools.ietf.org/html/rfc8187) in OkHttp.

# Context

Header values should generally be restricted to the ASCII charset only.

OkHttp already enforces this restriction: Most values provided to `Headers` gets run through `Headers.checkValue()`, which throws an exception for any non-ASCII characters. (The only exception to this is if you explicitly use `Headers.Builder.addUnsafeNonAscii()`.

However, OkHttp provides no tools for actually encoding values, either manually or automatically.

It's not as simple as just calling `URLEncoder` to encode these values; you also have to change the way the name is written, and the value adds encoding/language info as well. For example, `title="US-$ rates"` when properly encoded becomes `title*=utf-8'en'%C2%A3%20rates`.

# Solutions

I would like to see something along the lines of this API, which would allow us to satisfy RFC 8187:

```
public Builder addEncoded(String name, String value, @Nullable String language)
```

I am unsure of whether we should let people define a character set besides UTF-8 for headers. I feel like defaulting to UTF-8 is probably good enough.

We could also consider making this conversion automatic (instead of blowing up if you use a value with non-ASCII characters).

**Comment by swankjesse** [comment]
Unfortunately your proposed API doesn’t work because the header it produces has a single header name, and multiple parameter names. Here’s a single `foo` header with a `title` parameter that has been encoded in two different ways.

```
foo: bar; title="EURO exchange rates";
               title*=utf-8''%e2%82%ac%20exchange%20rates
```

**Comment by dlew** [comment]
Hmm, I underestimated RFC 8187. So we have to account for:

1. Multiple parameters (e.g., `Content-Disposition: form-data; name="file"; filename="thing.txt"`)
2. The same parameter with multiple encodings (as in your example).

Is that correct?

**Comment by swankjesse** [comment]
You got it.

**Comment by swankjesse** [comment]
Oh, and the same parameter with multiple languages also.

**Comment by dlew** [comment]
I had opened this thinking I had time to work on it, but really I don't at the moment. If there's future desire from anyone besides me I'd be happy to jump back on this and figure out the right API, but as it stands I don't *need* it so I'm closing for now.
