### ISSUE TITLE
Issues with retry on connection failure

### ISSUE THREAD

**Issue by androideveloper** [square/okhttp#4963]
Most of our clients are receiving this kind of exceptions per our logs.

![1](https://user-images.githubusercontent.com/1249919/56342297-a882ab00-61c8-11e9-8b31-86638e68005b.PNG)
![2](https://user-images.githubusercontent.com/1249919/56342298-a882ab00-61c8-11e9-9731-778f83885fff.PNG)

What they complain about is that data is uploaded to the server but mobile still shows as not uploaded. I have researched a bit and found that okHttp is retrying requests on connection failure and guess it is related to this topic. I can't create a case while debugging the app. I have tried to connect to 10.10.10.1, it is getting socket timeout, but it seems that okhttp doesn't retry this request. It just returns on this line `if (!streamAllocation.hasMoreRoutes()) return false;` (**okhttp v3.12.1**). I can't see any logs on retrying in logcat or stetho. How to reproduce this case? Should okHttp retry in this case? Will disabling retry help in this case?

**Comment by swankjesse** [comment]
Is this a bug report? I think you wanna ask on StackOverflow.

**Comment by swankjesse** [comment]
OkHttp retries when a client attempts to reuse a TCP connection that a server has unexpectedly closed.

**Comment by androideveloper** [comment]
How to test this case if we don't have access to the server?

**Comment by swankjesse** [comment]
Here’s an example test to get you started.
https://gist.github.com/swankjesse/981fcae102f513eb13ed

**Comment by androideveloper** [comment]
Thanks, will try out!

**Comment by androideveloper** [comment]
I managed to replicate the case based on your test `silentRetryWhenIdempotentRequestFailsOnReusedConnection`. Here is the test. It retries silently 2 times.  (Logging interceptor doesn't log anything about retries). Uncommenting the line causes java.io.IOException: unexpected end of stream on http://licensing.ultraedit.com:52524/... Shouldn't it retry more than 2 times? I can see followup count is 20.

```
import okhttp3.OkHttpClient
import okhttp3.Request
import okhttp3.logging.HttpLoggingInterceptor
import okhttp3.mockwebserver.MockResponse
import okhttp3.mockwebserver.MockWebServer
import okhttp3.mockwebserver.SocketPolicy
import org.junit.Assert.assertThat
import kotlin.test.assertEquals

fun main() {
    val server = MockWebServer()
    server.start()

    server.enqueue(MockResponse().setBody("a"))
    server.enqueue(MockResponse().setBody("aa"))
    server.enqueue(MockResponse().setSocketPolicy(SocketPolicy.DISCONNECT_AFTER_REQUEST))
    server.enqueue(MockResponse().setSocketPolicy(SocketPolicy.DISCONNECT_AFTER_REQUEST))
//    server.enqueue(MockResponse().setSocketPolicy(SocketPolicy.DISCONNECT_AFTER_REQUEST))
    server.enqueue(MockResponse().setBody("b"))

    val request = Request.Builder()
            .url(server.url("/"))
            .build()

    val client = OkHttpClient.Builder()
            .build()

    val responseA = client.newCall(request).execute()
    assertEquals("a", responseA.body()!!.string())
    assertEquals(0, server.takeRequest().getSequenceNumber())

    val responseAA = client.newCall(request).execute()
    assertEquals("aa", responseAA.body()!!.string())
    assertEquals(1, server.takeRequest().getSequenceNumber())

    val responseB = client.newCall(request).execute()
    assertEquals("b", responseB.body()!!.string())
    assertEquals(2, server.takeRequest().getSequenceNumber())
    assertEquals(0, server.takeRequest().getSequenceNumber())
    assertEquals(0, server.takeRequest().getSequenceNumber())
}
```

**Comment by androideveloper** [comment]
The second test is similar. Uncommenting `.setBody("a"))` leads to the same error but I expect it to retry. Does it matter if if has body? It seems weird. Bot tests use **okhttp 3.14.1**

```
import okhttp3.mockwebserver.MockResponse
import okhttp3.mockwebserver.MockWebServer
import okhttp3.OkHttpClient
import okhttp3.Request
import okhttp3.mockwebserver.SocketPolicy
import kotlin.test.assertEquals


fun main() {
    val server = MockWebServer()
    server.start()

    server.enqueue(MockResponse())//.setBody("a"))
    server.enqueue(MockResponse().setSocketPolicy(SocketPolicy.DISCONNECT_AFTER_REQUEST))
    server.enqueue(MockResponse().setBody("b"))

    val request = Request.Builder()
            .url(server.url("/"))
            .build()

    val client = OkHttpClient.Builder()
            .build()

    val responseA = client.newCall(request).execute()
    val responseB = client.newCall(request).execute()
}
```

**Comment by swankjesse** [comment]
OkHttp retries when a client attempts to **reuse** a TCP connection that a server has unexpectedly closed. It does not retry otherwise.

**Comment by androideveloper** [comment]
So my question is how it decides when to reuse when not? And how many times will it retry?

**Comment by swankjesse** [comment]
Does this help?
https://github.com/square/okhttp/wiki/Connections

**Comment by androideveloper** [comment]
To better understand connections, yes. But I have tried to debug my second case and still can't figure out why body presence in response matters for connection reuse. Should it work this way?

**Comment by androideveloper** [comment]
And shouldn't logging interceptor log anything in case of retries?

**Comment by swankjesse** [comment]
If you install your logging interceptor as a network interceptor, you'll see more.
