### ISSUE TITLE
OkHostnameVerifier does not check common-name of certificates

### ISSUE THREAD

**Issue by kalexmills** [square/okhttp#4966]
The current implementation of the OkHostnameVerifier does not appear to conform to [RFC 2818, Section 3.1](https://tools.ietf.org/html/rfc2818#section-3.1)

From that document:

>   If a subjectAltName extension of type dNSName is present, that MUST
>   be used as the identity. Otherwise, the (most specific) Common Name
>   field in the Subject field of the certificate MUST be used. Although
>   the use of the Common Name is existing practice, it is deprecated and
>   Certification Authorities are encouraged to use the dNSName instead.

As of 3.14.0, in the implementation of OkHostnameVerifier, only the subject alternate names are being used.

**Comment by yschimke** [comment]
This is by design and follows the lead of browsers such as Firefox and Chrome

https://textslashplain.com/2017/03/10/chrome-deprecates-subject-cn-matching/

**Comment by yschimke** [comment]
This change was specifically made in 3.10.0, i.e. it's not a bug or an oversight.

https://github.com/square/okhttp/blob/master/CHANGELOG.md

> New: Don't fall back to common name (CN) verification for hostnames. This behavior was deprecated with RFC 2818 in May 2000 and was recently dropped from major web browsers.
