### ISSUE TITLE
Use SecureRandom instead of Random

### ISSUE THREAD

**Issue by haidershah** [square/okhttp#4974]
OkHttpClient.kt uses java.util.Random in the newWebSocket() method. java.util.Random is considered cryptically insecure due to the predictability of Linear Congruential Generators (LCGs). An attacker may be able to calculate the seed the number was generated by the use of Brute Force attacks as the class does generate enough entropy to truly be random.

Java includes a class named SecureRandom or java.util.SecureRandom to address this vulnerability and should be used in all instances where Random is used. The Random Number Generator (RNG) used for SecureRandom is considered stronger as it compiles based on a truly random pattern.

**Comment by JakeWharton** [comment]
I vaguely remember talking about this at the time it was implemented. The use of the random data isn't for cryptography. The value is transmitted as part of the request and serves as an ongoing checksum of sorts. It's super useless, but the spec mandates we do it.

**Comment by mbaluda** [comment]
> It's super useless, but the spec mandates we do it.
How does the spec mandate that you use java.util.Random? java.security.SecureRandom extends Random and can be used as drop-in replacement.
Even though this is not a security issue, the finding is reported by static analysis tools and might prevent the adoption of okhttp in enterprise projects.
