### ISSUE TITLE
Some OkHttp versions don't call EventListener.callEnd if interceptor short-circuits

### ISSUE THREAD

**Issue by hey99xx** [square/okhttp#4980]
In older OkHttp versions, when using EventListener, if an interceptor short circuits the request and does not go to network, the only event received is `callStart`.

In new OkHttp versions, having the same code, both `callStart` and `callEvent` events are received.

I don't know which one is the intended version. I certainly prefer the new one. But I would like if this can be clarified in the docs so we can rely on the intended behavior.

Difference happened somewhere between 3.13.0 and 3.14.1. I will post code example shortly.

**Comment by hey99xx** [comment]
Sample code to reproduce: https://gist.github.com/hey99xx/a522682af1cacaf52ccc787f50cf6566

When run with 3.13.0 result is:

```
REQUEST 3 (short circuit)
BBB  0.000 callStart
AAA  0.000 callStart
AAA  0.006 dnsStart
AAA  0.008 dnsEnd
AAA  0.013 connectStart
AAA  0.033 secureConnectStart
AAA  0.168 secureConnectEnd
AAA  0.168 connectEnd
AAA  0.169 connectionAcquired
AAA  0.170 requestHeadersStart
AAA  0.171 requestHeadersEnd
AAA  0.173 responseHeadersStart
AAA  0.187 responseHeadersEnd
AAA  0.187 responseBodyStart
AAA  0.189 responseBodyEnd
AAA  0.190 connectionReleased
AAA  0.190 callEnd
```

When run with 3.14.1 result is:

```
REQUEST 3 (short circuit)
BBB  0.000 callStart
AAA  0.000 callStart
AAA  0.004 dnsStart
AAA  0.007 dnsEnd
AAA  0.012 connectStart
AAA  0.036 secureConnectStart
AAA  0.172 secureConnectEnd
AAA  0.172 connectEnd
AAA  0.173 connectionAcquired
AAA  0.175 requestHeadersStart
AAA  0.175 requestHeadersEnd
AAA  0.177 responseHeadersStart
AAA  0.192 responseHeadersEnd
AAA  0.193 responseBodyStart
BBB  0.201 callEnd                        <-- Notice this line
AAA  0.196 responseBodyEnd
AAA  0.196 connectionReleased
AAA  0.196 callEnd
```

I would have also preferred `BBB  0.201 callEnd` to be the final line too btw.

**Comment by swankjesse** [comment]
From the 3.14 [changelog](https://github.com/square/okhttp/blob/master/CHANGELOG.md): 

> New: We've added requestFailed() and responseFailed() methods to EventListener. These are called instead of requestBodyEnd() and responseBodyEnd() in some failure situations. They may also be fired in cases where no event was published previously. In this release we did an internal rewrite of our event code to fix problems where events were lost or unbalanced.

The fixes have accompanying test cases to defend against potential regressions.

**Comment by hey99xx** [comment]
Thanks. Hard to tell which commit is the fix but [`applicationInterceptorShortCircuit`](https://github.com/square/okhttp/blob/parent-3.14.1/okhttp-tests/src/test/java/okhttp3/EventListenerTest.java#L1216-L1233) test case should cover my sample code.
