### ISSUE TITLE
Malformed response on string() 

### ISSUE THREAD

**Issue by hoangpham95** [square/okhttp#4995]
Hello,

I am using okhttp to send a POST request to our own backend service to receive a JSON string. However, on receive, I noticed that the string is in wrong format, with something like this: �][OI��+�gG)�zciz���E6Ӛ�� instead of UTF-8 string. This is the sample code:

```
OkHttpClient client = new OkHttpClient();
Request r = new Request.Builder()
                        .method("POST", RequestBody.create(null , new byte[]{}))
                        .url(myUrl)
                        .addHeader("x-ms-request-method", "GET")
                        .addHeader("Authorization",  someAuthToken)
                        .addHeader("Accept", "*/*")
                        .addHeader("Accept-language", "en-US")
                        .addHeader("x-client-request-id",reqId)
                        .addHeader("x-session-id", session)
                        .addHeader("Cache-control", "no-cache, no-store")
                        .build();
Response responses;
responses = client.newCall(r).execute();

// this is causing the malformed response
responses.body().string() ---> returned malformed string 
```
Is this a known issue and how could I work around this?

**Comment by JakeWharton** [comment]
What's the response? What charset does it declare? Is it actually binary?

**Comment by hoangpham95** [comment]
The response has Content-Type header as "application/json". Even when I specified the charset as utf-8, this is still replying this malformed string.

**Comment by JakeWharton** [comment]
Can you write a test case with an example payload and charset that
demonstrates the problem? The issue template had a link to an example.

**Comment by hoangpham95** [comment]
I have trouble running the sample test. Android studio replies with
```
java.lang.VerifyError: Cannot inherit from final class

	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.example.myapplication.ExampleUnitTest.test(ExampleUnitTest.java:19)
```
The issue is with initializing the `MockWebServer` object.

**Comment by JakeWharton** [comment]
It should work in IntelliJ, or you can just open OkHttp in IntelliJ and
write the test inside its tests.

**Comment by hoangpham95** [comment]
Hi Jake, I just updated the comment. I was able to write the test but couldn't reproduce the issue.

**Comment by hoangpham95** [comment]
UPDATE: Able to pinpoint the issue (#2447). We're sending `Content-Encoding: deflate` and okhttp can't decompress. We'll figure out from here.
