### ISSUE TITLE
Failed to allocate a 205151760 byte allocation with 16773216 free bytes and 193MB until OOM

### ISSUE THREAD

**Issue by gelbertgel** [square/okhttp#5002]
When I have downloaded 100MB video, it has crashed. I don't know how to destroy this error.
Please help me. 

```
 requestCall.enqueue(new Callback() {

            @Override
            public void onFailure(@NonNull Call call, @NonNull IOException e) {
                transferIsFail(attachmentId, messageTypeStr);
            }

            @Override
            public void onResponse(@NonNull Call call, @NonNull Response response) {
                if (!response.isSuccessful()) {
                    transferIsFail(attachmentId, messageTypeStr);
                } else {

                        final String url = response.request().url().toString();
                        ResponseBody responseBody = response.body();

                        if (responseBody == null) {
                            transferIsFail(attachmentId, messageTypeStr);
                            return;
                        }

                        BufferedSource source = responseBody.source();

                        if (source == null) {
                            transferIsFail(attachmentId, messageTypeStr);
                            return;
                        }

                        String encryptedBase64Data = source.readUtf8(); --> it is crashed this line (316)
                     
                 response.close();
            }
        });

```

my crash log:
```

2019-05-03 16:43:57.740 19837-21316/com.android.android.test E/AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
    Process: com.android.android.test, PID: 19837
    java.lang.OutOfMemoryError: Failed to allocate a 205151760 byte allocation with 16773216 free bytes and 193MB until OOM
        at java.lang.StringFactory.newStringFromChars(StringFactory.java:218)
        at java.lang.StringFactory.newStringFromBytes(StringFactory.java:203)
        at java.lang.StringFactory.newStringFromBytes(StringFactory.java:207)
        at okio.Buffer.readString(Buffer.java:631)
        at okio.Buffer.readUtf8(Buffer.java:602)
        at okio.RealBufferedSource.readUtf8(RealBufferedSource.java:189)
        at com.android.android.conversation.operation.message.receive.ReceiveMessageOperations$3.onResponse(ReceiveMessageOperations.java:316)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:153)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:762)
```

**Comment by JakeWharton** [comment]
The error message is pretty clear here. You don't have sufficient memory to allocate such a massive string. You'll want to stream the data to the file system or to the video player instead of buffering it as a string or byte array. If you need help in doing this, please ask on StackOverflow with the 'okhttp' tag.

**Comment by joseflaviojesus27-oss** [comment]
requestCall.enqueue(new Callback() {

            @Override
            public void onFailure(@NonNull Call call, @NonNull IOException e) {
                transferIsFail(attachmentId, messageTypeStr);
            }

            @Override
            public void onResponse(@NonNull Call call, @NonNull Response response) {
                if (!response.isSuccessful()) {
                    transferIsFail(attachmentId, messageTypeStr);
                } else {

                        final String url = response.request().url().toString();
                        ResponseBody responseBody = response.body();

                        if (responseBody == null) {
                            transferIsFail(attachmentId, messageTypeStr);
                            return;
                        }

                        BufferedSource source = responseBody.source();

                        if (source == null) {
                            transferIsFail(attachmentId, messageTypeStr);
                            return;
                        }

                        String encryptedBase64Data = source.readUtf8(); --> it is crashed this line (316)
                     
                 response.close();
            }
        });

**Comment by joseflaviojesus27-oss** [comment]
requestCall.enqueue(new Callback() {

            @Override
            public void onFailure(@NonNull Call call, @NonNull IOException e) {
                transferIsFail(attachmentId, messageTypeStr);
            }

            @Override
            public void onResponse(@NonNull Call call, @NonNull Response response) {
                if (!response.isSuccessful()) {
                    transferIsFail(attachmentId, messageTypeStr);
                } else {

                        final String url = response.request().url().toString();
                        ResponseBody responseBody = response.body();

                        if (responseBody == null) {
                            transferIsFail(attachmentId, messageTypeStr);
                            return;
                        }

                        BufferedSource source = responseBody.source();

                        if (source == null) {
                            transferIsFail(attachmentId, messageTypeStr);
                            return;
                        }

                        String encryptedBase64Data = source.readUtf8(); --> it is crashed this line (316)
                     
                 response.close();
            }
        });
