### ISSUE TITLE
Custom algorithm of CertificatePinner

### ISSUE THREAD

**Issue by ittianyu** [square/okhttp#5025]
Hi, I feel awkward to pin Certificate.
What I have now is a hex string which equals to `sha256(x509Certificate.getEncoded())`.
While I found it is `sha256(x509Certificate.getPublicKey().getEncoded())` in `CertificatePinner`.

```
if (pin.hashAlgorithm.equals("sha256/")) {
    if (sha256 == null) sha256 = sha256(x509Certificate);
    if (pin.hash.equals(sha256)) return; // Success!
}

static ByteString sha256(X509Certificate x509Certificate) {
    return ByteString.of(x509Certificate.getPublicKey().getEncoded()).sha256();
}
```

Do you have plan to support custom algorithm ?

**Comment by swankjesse** [comment]
No plans. Don’t pin the whole certificate; that won’t work if you issue a new certificate with the same keys and a new expiration date.
