### ISSUE TITLE
OkHttp future and Java 11 java.net.http

### ISSUE THREAD

**Issue by nicolabeghin** [square/okhttp#5031]
Hi everyone 
I would to gather ideas about the topic, specifically if there's any plan for okhttp to be built on top of the [new Java 11 `java.net.http` jdk-inbuilt](https://dzone.com/articles/java-11-standardized-http-client-api) network library or if it doesn't make sense at all! 

Really looking forward to your opinions on this, after several lousy battles I had to fight against jlink and Java 11/12 😁

**Comment by swankjesse** [comment]
The java.net.http has a limited API and an inefficient implementation. We won’t be integrating it.
