### ISSUE TITLE
Dns Async API

### ISSUE THREAD

**Issue by yschimke** [square/okhttp#5042]
I'm using DnsOverHttps externally, and would like to start taking advantage of Kotlin coroutines here.  Ahead of a Kotlin first coroutines experience, I'm curious whether making DnsOverHttps support both coroutines and the sync Dns interface.

Two options

1) Internally the implementation would be coroutines throughout, and Dns lookup could call runBlocking
2) Two implementations reusing the same building blocks

**Comment by swankjesse** [comment]
I’d like to ship 4.0 without any coroutines dependencies, and follow up with APIs that use coroutines where they fit. Possibly even a new interface like `AsyncDns` that just adds the `suspend` modifier.

**Comment by yschimke** [comment]
@swankjesse Whats your thinking now that coroutines are stable?

AsyncDns sub-interface using suspend?
AsyncDns sub-interface using callbacks?

When is appropriate time to dip a toe into optimized async code paths?

This is relevant for DoH and potentially relevant for Happy eyeballs (https://github.com/square/okhttp/issues/506)

**Comment by yschimke** [comment]
Won't fix, we should just make this part of a general kotlin coroutines story?

**Comment by yschimke** [comment]
It's probably also useful for a happy eyeballs impl, but not a feature on it's own.
