### ISSUE TITLE
Kotlin Documentation leaks some weird public APIs 

### ISSUE THREAD

**Issue by yschimke** [square/okhttp#5043]
http://square.github.io/okhttp/4.x/okhttp/okhttp/okhttp3/-dns/index.html

<img width="659" alt="image" src="https://user-images.githubusercontent.com/231923/57583963-ef18ac00-74cd-11e9-8234-bf0cdf61f6d2.png">

**Comment by monkey-mas** [comment]
Seems like we removed them? We might still have weird public APIs though.
PR: https://github.com/square/okhttp/pull/5158
