### ISSUE TITLE
MockWebServer responds successful even with SocketPolicy.DISCONNECT_AT_START

### ISSUE THREAD

**Issue by ceronman** [square/okhttp#5054]
If I enqueue a `MockResponse` with `SocketPolicy.DISCONNECT_AT_START` after another `MockResponse` both requests succeed.

Here is a small example of how to reproduce the issue:

```java
MockWebServer server = new MockWebServer();

server.enqueue(new MockResponse());
server.enqueue(new MockResponse().setSocketPolicy(SocketPolicy.DISCONNECT_AT_START));

OkHttpClient client = new OkHttpClient.Builder().build();
Request request = new Request.Builder().url(server.url("/")).build();

try (Response response = client.newCall(request).execute()) {
    System.out.println("SUCCESS");
} catch (Exception e) {
    System.out.println("ERROR");
}

try (Response response = client.newCall(request).execute()) {
    System.out.println("SUCCESS");
} catch (Exception e) {
    System.out.println("ERROR");
}
```

I expect this to print:

```
SUCCESS
ERROR
```

However it prints

```
SUCCESS
SUCCESS
```
Note that if I change the enqueueing order and I enqueue the `MockResponse` that throws errors first, and the successful one second, this works as expected.

I'm using version 3.14.1

**Comment by amirlivneh** [comment]
I believe this works as designed. The second request reuses the connection of the first one. No new socket is created for the second request and therefore the socket policy is not applied.
