### ISSUE TITLE
Allow configuration to use different TCP socket connection for URLs that share the same address (URL)

### ISSUE THREAD

**Issue by hlms** [square/okhttp#5098]
[The documentation](https://github.com/square/okhttp/wiki/Connections#addresses) states the following:

> URLs that share the same address may also share the same underlying TCP socket connection. 

Problem:
* When multiple threads (different users) are calling the same endpoint (same URL since it's a SOAP call), OkHttp client reuses the same TCP connections for all calls even across different threads.
* And load balancer does load balancing on the TCP level, not HTTP level, so different threads are issued overlapping values of sticky cookies. 

So, okhttp client should be able to configure to pick different TCP socket connection for the same URLs.

**Comment by swankjesse** [comment]
Tracking here: https://github.com/square/okhttp/issues/4530
