### ISSUE TITLE
Mandatory: compliance as a function of version. 

### ISSUE THREAD

**Issue by chjan** [square/okhttp#5122]
PLEASE DISREGARD. THE ERROR WAS SOMETHING ELSE. SEE NEW COMMENT. 
Using Gradle, updating to latest okhttp given by readme, the following error is reported, opposing your statement in readme that okhttp is in compliance with Android 21+ 

Error: Static interface methods are only supported starting with Android N (--min-api 24): void okhttp3.logging.HttpLoggingInterceptor$Logger.lambda$static$0(java.lang.String)

The library was updated due to nodefined class exception concerning the logging interceptor. Both okhttp and okhttp-loggin-interceptor, thus non-working, was 3.10.0. This error is therefore equal to a push on the "wild guess button". We are not the only ones at loss for proper explanantion. What is causing it? Should you include a section in your readme on this common issue? Please understand that we want to avoid library integration becoming a recurring timethief each time an update is mandatory for this or that reason.

SUGGESTED REMEDY:
At the very minimum, please update your readme with a compliance table, including Android, Java, retrofit, or other libraries of relevance. Do have in mind that when developing apps for Android, it is of very high interest to be backward compliant to the extent possible, so as to cover as large a market segment as possible. I would suggest that your code, if at all possible, should be that; backward compliant to for example Android 19. There are still many models of this version in use. Put version control if then else into your code!

Beyond this lack of professional configuration control on versions, okhttp is brilliant!

Thankyou.

**Comment by digitalbuddha** [comment]
Tldr: okhttp needs you to use Java 8

compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

**Comment by digitalbuddha** [comment]
The readme has a suggestion of what version to use if you need java 7+ support (under requirements)

The OkHttp 3.12.x branch supports Android 2.3+ (API level 9+) and Java 7+. These platforms lack support for TLS 1.2 and should not be used. But because upgrading is difficult we will backport critical fixes to the 3.12.x branch through December 31, 2020.

**Comment by chjan** [comment]
Sorry for being too hasty. okhttp was not the problem. The problem was the building of "fat" jars in android studio, instead it was building "thin" jar. Don't know why, but this happens often, and has to do with library changes. One should think this is commodity, but the jar command of the Gradle Java plugin is vulnerable to changes. And it does not report it when libraries were not included in the jar. 

Someone should  close this thread.
