### ISSUE TITLE
Add callback for connection leak

### ISSUE THREAD

**Issue by gatesn** [square/okhttp#5136]
I'm trying to adding monitoring to my application that will alert me if I've introduced a bug that causes okhttp connection leaks. Currently the only way to do that is to listen for the log line produced in the Platform#logCloseableLeak method.

It would be nice if there was a way to register a callback for connection leaks such that I can alert on this more gracefully.

**Comment by swankjesse** [comment]
I think the logger is the best mechanism we’re likely to offer for this. You might want to monitor logged warnings in general!
