### ISSUE TITLE
Handshake certificates are unclean

### ISSUE THREAD

**Issue by swankjesse** [square/okhttp#5138]
We’re cleaning them for the certificate Pinner but not otherwise. We should put cleaned certificates into the handshake always.

Only need to be careful of the performance consequences of this.

https://github.com/Babylonpartners/certificate-transparency-android/issues/4#issuecomment-496485839

**Comment by yschimke** [comment]
This is a good candidate for 4.1

**Comment by yschimke** [comment]
Draft PR, will add tests, feel free to comment on approach.

https://github.com/square/okhttp/pull/5311/files

**Comment by swankjesse** [comment]
Shipped in 4.2!
