### ISSUE TITLE
okhttp3.Headers bug

### ISSUE THREAD

**Issue by xiaomingzhong** [square/okhttp#5146]
**no spaces allowed in header**

![image](https://user-images.githubusercontent.com/13159188/58681651-ed8d2600-839f-11e9-824f-0c74a61077cd.png)

![image](https://user-images.githubusercontent.com/13159188/58681666-00075f80-83a0-11e9-8be0-bdfb703e7d0c.png)

**Comment by swankjesse** [comment]
Unclear what the problem is.

**Comment by xiaomingzhong** [comment]
＠swankjesse  header no spaces allowed
