### ISSUE TITLE
Facing Security issue

### ISSUE THREAD

**Issue by vigneshthillaichithambaram** [square/okhttp#5148]
We got the security issue in the okhttp.
With the IBM Application Security, we got the following trace. Please check

javax.net.ssl.SSLParameters.setCipherSuites(java.lang.String[]):void | SSLParameters | (javax\net\ssl\SSLParameters.java:140)
-- | -- | --
[Framework Code, 8 lines removed] | ... | (...)
com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake():void | OpenSSLSocketImpl | (com\android\org\conscrypt\OpenSSLSocketImpl.java:351)
okhttp3.internal.connection.RealConnection.connectTls(okhttp3.internal.connection.ConnectionSpecSelector):void | RealConnection | (okhttp3\internal\connection\RealConnection.java:318)
okhttp3.internal.connection.RealConnection.establishProtocol(okhttp3.internal.connection.ConnectionSpecSelector, int, okhttp3.Call, okhttp3.EventListener):void | RealConnection | (okhttp3\internal\connection\RealConnection.java:282)
okhttp3.internal.connection.RealConnection.connect(int, int, int, int, boolean, okhttp3.Call, okhttp3.EventListener):void | RealConnection | (okhttp3\internal\connection\RealConnection.java:167)
okhttp3.internal.connection.StreamAllocation.findConnection(int, int, int, int, boolean):okhttp3.internal.connection.RealConnection | StreamAllocation | (okhttp3\internal\connection\StreamAllocation.java:257)
okhttp3.internal.connection.StreamAllocation.findHealthyConnection(int, int, int, int, boolean, boolean):okhttp3.internal.connection.RealConnection | StreamAllocation | (okhttp3\internal\connection\StreamAllocation.java:135)
okhttp3.internal.connection.StreamAllocation.newStream(okhttp3.OkHttpClient, okhttp3.Interceptor.Chain, boolean):okhttp3.internal.http.HttpCodec | StreamAllocation | (okhttp3\internal\connection\StreamAllocation.java:114)
okhttp3.internal.connection.ConnectInterceptor.intercept(okhttp3.Interceptor.Chain):okhttp3.Response | ConnectInterceptor | (okhttp3\internal\connection\ConnectInterceptor.java:42)
okhttp3.internal.http.RealInterceptorChain.proceed(okhttp3.Request, okhttp3.internal.connection.StreamAllocation, okhttp3.internal.http.HttpCodec, okhttp3.internal.connection.RealConnection):okhttp3.Response | RealInterceptorChain | (okhttp3\internal\http\RealInterceptorChain.java:147)
okhttp3.internal.http.RealInterceptorChain.proceed(okhttp3.Request):okhttp3.Response | RealInterceptorChain | (okhttp3\internal\http\RealInterceptorChain.java:121)
okhttp3.internal.cache.CacheInterceptor.intercept(okhttp3.Interceptor.Chain):okhttp3.Response | CacheInterceptor | (okhttp3\internal\cache\CacheInterceptor.java:93)
okhttp3.internal.http.RealInterceptorChain.proceed(okhttp3.Request, okhttp3.internal.connection.StreamAllocation, okhttp3.internal.http.HttpCodec, okhttp3.internal.connection.RealConnection):okhttp3.Response | RealInterceptorChain | (okhttp3\internal\http\RealInterceptorChain.java:147)
okhttp3.internal.http.RealInterceptorChain.proceed(okhttp3.Request):okhttp3.Response | RealInterceptorChain | (okhttp3\internal\http\RealInterceptorChain.java:121)
okhttp3.internal.http.BridgeInterceptor.intercept(okhttp3.Interceptor.Chain):okhttp3.Response | BridgeInterceptor | (okhttp3\internal\http\BridgeInterceptor.java:93)
okhttp3.internal.http.RealInterceptorChain.proceed(okhttp3.Request, okhttp3.internal.connection.StreamAllocation, okhttp3.internal.http.HttpCodec, okhttp3.internal.connection.RealConnection):okhttp3.Response | RealInterceptorChain | (okhttp3\internal\http\RealInterceptorChain.java:147)
okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(okhttp3.Interceptor.Chain):okhttp3.Response | RetryAndFollowUpInterceptor | (okhttp3\internal\http\RetryAndFollowUpInterceptor.java:126)
okhttp3.internal.http.RealInterceptorChain.proceed(okhttp3.Request, okhttp3.internal.connection.StreamAllocation, okhttp3.internal.http.HttpCodec, okhttp3.internal.connection.RealConnection):okhttp3.Response | RealInterceptorChain | (okhttp3\internal\http\RealInterceptorChain.java:147)
okhttp3.internal.http.RealInterceptorChain.proceed(okhttp3.Request):okhttp3.Response | RealInterceptorChain | (okhttp3\internal\http\RealInterceptorChain.java:121)
okhttp3.internal.http.RealInterceptorChain.proceed(okhttp3.Request, okhttp3.internal.connection.StreamAllocation, okhttp3.internal.http.HttpCodec, okhttp3.internal.connection.RealConnection):okhttp3.Response | RealInterceptorChain | (okhttp3\internal\http\RealInterceptorChain.java:147)
okhttp3.internal.http.RealInterceptorChain.proceed(okhttp3.Request):okhttp3.Response | RealInterceptorChain | (okhttp3\internal\http\RealInterceptorChain.java:121)
okhttp3.logging.HttpLoggingInterceptor.intercept(okhttp3.Interceptor.Chain):okhttp3.Response | HttpLoggingInterceptor | (okhttp3\logging\HttpLoggingInterceptor.java:212)
okhttp3.internal.http.RealInterceptorChain.proceed(okhttp3.Request, okhttp3.internal.connection.StreamAllocation, okhttp3.internal.http.HttpCodec, okhttp3.internal.connection.RealConnection):okhttp3.Response | RealInterceptorChain | (okhttp3\internal\http\RealInterceptorChain.java:147)
okhttp3.internal.http.RealInterceptorChain.proceed(okhttp3.Request):okhttp3.Response | RealInterceptorChain | (okhttp3\internal\http\RealInterceptorChain.java:121)
okhttp3.RealCall.getResponseWithInterceptorChain():okhttp3.Response | RealCall | (okhttp3\RealCall.java:200)
okhttp3.RealCall.AsyncCall.execute():void | RealCall$AsyncCall | (okhttp3\RealCall.java:147)
okhttp3.internal.NamedRunnable.run():void | NamedRunnable | (okhttp3\internal\NamedRunnable.java:32)
java.util.concurrent.ThreadPoolExecutor.runWorker(java.util.concurrent.ThreadPoolExecutor.Worker):void | ThreadPoolExecutor | (java\util\concurrent\ThreadPoolExecutor.java:1162)
java.util.concurrent.ThreadPoolExecutor.Worker.run():void | ThreadPoolExecutor$Worker | (java\util\concurrent\ThreadPoolExecutor.java:636)
java.lang.Thread.run():void | Thread | (java\lang\Thread.java:764)

Please check this and let us know. We are using, 
implementation 'com.squareup.retrofit2:retrofit:2.1.0'
implementation 'com.squareup.okhttp3:logging-interceptor:3.4.1'

**Comment by swankjesse** [comment]
Please upgrade to the latest OkHttp before reporting bugs.

**Comment by vigneshthillaichithambaram** [comment]
Hello Swankjesse!
I have updated to the latest version and still facing the above issue. Could you please check and let us know for us..?

**Comment by swankjesse** [comment]
What's the headline on the exception?

**Comment by swankjesse** [comment]
And can you provide an exception for the updated OkHttp version?

**Comment by shivavandana** [comment]
Hi Vignesh, could you resolve the above issue? I used HCL Application Security, and it shows the same issue, seems like it is pointing to internal files of okhttp

here is the security issue it shows:
Location
(okhttp3\internal\connection\RealConnection.java:281)
Calling Line
(okhttp3\internal\connection\RealConnection.java:281)
Calling Method
okhttp3.internal.connection.RealConnection.connectTls(okhttp3.internal.connection.ConnectionSpecSelector):void

the full description is:

javax.net.ssl.SSLParameters.setProtocols(java.lang.String[]):void | SSLParameters | (javax\net\ssl\SSLParameters.java:160)
-- | -- | --
[Framework Code, 8 lines removed] | ... | (...)
com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake():void | OpenSSLSocketImpl | (com\android\org\conscrypt\OpenSSLSocketImpl.java:351)
okhttp3.internal.connection.RealConnection.connectTls(okhttp3.internal.connection.ConnectionSpecSelector):void | RealConnection | (okhttp3\internal\connection\RealConnection.java:281)
okhttp3.internal.connection.RealConnection.establishProtocol(okhttp3.internal.connection.ConnectionSpecSelector):void | RealConnection | (okhttp3\internal\connection\RealConnection.java:251)
okhttp3.internal.connection.RealConnection.connect(int, int, int, boolean):void | RealConnection | (okhttp3\internal\connection\RealConnection.java:151)
okhttp3.internal.connection.StreamAllocation.findConnection(int, int, int, boolean):okhttp3.internal.connection.RealConnection | StreamAllocation | (okhttp3\internal\connection\StreamAllocation.java:192)
okhttp3.internal.connection.StreamAllocation.findHealthyConnection(int, int, int, boolean, boolean):okhttp3.internal.connection.RealConnection | StreamAllocation | (okhttp3\internal\connection\StreamAllocation.java:121)
okhttp3.internal.connection.StreamAllocation.newStream(okhttp3.OkHttpClient, boolean):okhttp3.internal.http.HttpCodec | StreamAllocation | (okhttp3\internal\connection\StreamAllocation.java:100)
okhttp3.internal.connection.ConnectInterceptor.intercept(okhttp3.Interceptor.Chain):okhttp3.Response | ConnectInterceptor | (okhttp3\internal\connection\ConnectInterceptor.java:42)
okhttp3.internal.http.RealInterceptorChain.proceed(okhttp3.Request, okhttp3.internal.connection.StreamAllocation, okhttp3.internal.http.HttpCodec, okhttp3.internal.connection.RealConnection):okhttp3.Response | RealInterceptorChain | (okhttp3\internal\http\RealInterceptorChain.java:92)
okhttp3.internal.http.RealInterceptorChain.proceed(okhttp3.Request):okhttp3.Response | RealInterceptorChain | (okhttp3\internal\http\RealInterceptorChain.java:67)
okhttp3.internal.cache.CacheInterceptor.intercept(okhttp3.Interceptor.Chain):okhttp3.Response | CacheInterceptor | (okhttp3\internal\cache\CacheInterceptor.java:93)
okhttp3.internal.http.RealInterceptorChain.proceed(okhttp3.Request, okhttp3.internal.connection.StreamAllocation, okhttp3.internal.http.HttpCodec, okhttp3.internal.connection.RealConnection):okhttp3.Response | RealInterceptorChain | (okhttp3\internal\http\RealInterceptorChain.java:92)
okhttp3.internal.http.RealInterceptorChain.proceed(okhttp3.Request):okhttp3.Response | RealInterceptorChain | (okhttp3\internal\http\RealInterceptorChain.java:67)
okhttp3.internal.http.BridgeInterceptor.intercept(okhttp3.Interceptor.Chain):okhttp3.Response | BridgeInterceptor | (okhttp3\internal\http\BridgeInterceptor.java:93)
okhttp3.internal.http.RealInterceptorChain.proceed(okhttp3.Request, okhttp3.internal.connection.StreamAllocation, okhttp3.internal.http.HttpCodec, okhttp3.internal.connection.RealConnection):okhttp3.Response | RealInterceptorChain | (okhttp3\internal\http\RealInterceptorChain.java:92)
okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(okhttp3.Interceptor.Chain):okhttp3.Response | RetryAndFollowUpInterceptor | (okhttp3\internal\http\RetryAndFollowUpInterceptor.java:120)
okhttp3.internal.http.RealInterceptorChain.proceed(okhttp3.Request, okhttp3.internal.connection.StreamAllocation, okhttp3.internal.http.HttpCodec, okhttp3.internal.connection.RealConnection):okhttp3.Response | RealInterceptorChain | (okhttp3\internal\http\RealInterceptorChain.java:92)
okhttp3.internal.http.RealInterceptorChain.proceed(okhttp3.Request):okhttp3.Response | RealInterceptorChain | (okhttp3\internal\http\RealInterceptorChain.java:67)
okhttp3.RealCall.getResponseWithInterceptorChain():okhttp3.Response | RealCall | (okhttp3\RealCall.java:185)
okhttp3.RealCall.execute():okhttp3.Response | RealCall | (okhttp3\RealCall.java:69)
com.ta.covance.application.AsyncHttpRequest.doInBackground(com.ta.covance.model.MWCContainer[]):com.ta.covance.model.MWCContainer | AsyncHttpRequest | (com\ta\covance\application\AsyncHttpRequest.java:57)
com.ta.covance.application.AsyncHttpRequest.doInBackground(java.lang.Object[]):java.lang.Object | AsyncHttpRequest | (com\ta\covance\application\AsyncHttpRequest.java:20)
android.os.AsyncTask.2.call():java.lang.Object | AsyncTask$2 | (android\os\AsyncTask.java:333)
