### ISSUE TITLE
image issue when using com.squareup.okhttp3:okhttp

### ISSUE THREAD

**Issue by foxalone** [square/okhttp#5165]
When i use this library i have an issue  - every image taken from firebase got some DogEar , when the phone is offline, but also when the phone is connected by wi fi:

![image](https://user-images.githubusercontent.com/19224066/58803304-c80a5180-8617-11e9-9a5b-4acbabdeb338.png)

**Comment by JakeWharton** [comment]
That is from Picasso and its debug indicator feature. Set [this](https://square.github.io/picasso/2.x/picasso/com/squareup/picasso/Picasso.html#setIndicatorsEnabled-boolean-) to `false`.

**Comment by foxalone** [comment]
> That is from Picasso and its debug indicator feature. Set [this](https://square.github.io/picasso/2.x/picasso/com/squareup/picasso/Picasso.html#setIndicatorsEnabled-boolean-) to `false`.

Tnx men!!!!!
