### ISSUE TITLE
Kotlin Type-Safe Builders

### ISSUE THREAD

**Issue by stachu540** [square/okhttp#5166]
I was checking you renewing code which are be provided to fresh new OkHttp4. I guess those title is good point to presenting new feature. You can use a Type-Safe Builders to create a builder invoked inside to constructor.

This is a example:
```kotlin
val http = OkHttp {
  addInterceptor(HttpLoggingInterceptor(LOG::debug))
} // it is return OkHttp aswell
```
Other examples is on `Request`:
```kotlin
val response = http.newCall { 
  // here is a Request.Builder.() -> Unit
}.execute()
// or
val response2 = http.newCall(Request { 
  // same like a first one: Request.Builder.() -> Unit
}).execute()
```

Not all classes have builders inside the constructor (eg. `constructor(builder: Builder -> Unit) : this(Builder().apply(builder))`) so on `companion object {}` (inside on class of course) we can add: 
```kotlin
operator fun invoke(builder: Builder.() -> Unit) = Builder().apply(builder).build()
```
Will works same way like above examples.

Those changes will solve a many solutions, to use it instead of long-term builders. All references are be in the [Kotlin Documentation](https://kotlinlang.org/docs/reference/type-safe-builders.html)

If do you wish a more explanation I can describe this solutions more precisely.

**Comment by swankjesse** [comment]
If you want a Kotlin DSL for OkHttp please share a gist here? I don’t want to add this to the library.

Also, if you find yourself tuning your OkHttp syntax, check out [Retrofit](https://github.com/square/retrofit)!
