### ISSUE TITLE
4.0.0 upgrade testing - CipherSuite.forName

### ISSUE THREAD

**Issue by yschimke** [square/okhttp#5169]
Needed the following after a cleanup in Intellij of existing Kotlin code

```
-import okhttp3.CipherSuite.forJavaName
+import okhttp3.CipherSuite.Companion.forJavaName
```

The upgrade for MockWebServer.setProtocols is also really ugly with the run method.

**Comment by swankjesse** [comment]
Documented: https://github.com/square/okhttp/pull/5176
