### ISSUE TITLE
okhttp cellular and wifi problem

### ISSUE THREAD

**Issue by LHeczko** [square/okhttp#5170]
Hi,

I've got problem OkHttpClient. 
Cellular data on, WIFI connected. Application reqests HTTPS and everything works perfect. When WIFI lose connection (still on) app link through cellular and works ok. The problem is when phone connect back to this WIFI
{java.net.UnknownHostException: Unable to resolve host: No address associated with hostname}

The only solution is to restart app, but I try to do this using JobScheduler and it have to work in backgroud.

```
    var vProtokoly : java.Util.List<Protocol> := new java.util.ArrayList<Protocol>;
    var vUprawnienia : RemObjects.Elements.RTL.String;
    var Wywolanie : Request;
    var Odpowiedz : Response;

    vProtokoly.add(Protocol.HTTP_1_1);
    vUprawnienia := okhttp3.Credentials.basic('some', 'credentials');

    Http := new OkHttpClient.Builder()
		.connectTimeout(15,java.util.concurrent.TimeUnit.SECONDS)
		.writeTimeout(20,java.util.concurrent.TimeUnit.SECONDS)
		.readTimeout(20,java.util.concurrent.TimeUnit.SECONDS)
		.retryOnConnectionFailure(false)
		.protocols(vProtokoly)
		.proxy(Proxy.NO_PROXY)
		//.socketFactory(android.net.Network.getSocketFactory())
		.build();
    Http.ConnectionPool.evictAll;

           Wywolanie :=  new okhttp3.Request.Builder().url(Parametry.Uri).header('Authorization',vUprawnienia).build();
        Odpowiedz := Http.newCall(Wywolanie).execute;

```

**Comment by sd1998** [comment]
@LHeczko I am new to this project and Can I start with this as my first issue?

**Comment by LHeczko** [comment]
I need solution - no matter which issue :)

**Comment by LHeczko** [comment]
The best scenario is to connect to cellular and wifi, turn off wifi on router, wait phone to disconnect, turn wifi on routern, wait phone to connect and then send request

**Comment by LHeczko** [comment]
After some investigation found the problem

I had 

android.net.ConnectivityManager.setProcessDefaultNetwork(currentConnection);

in on lostConnection of registerNetworkCallback. After removing this everything works perfect. Sorry and thank you

**Comment by JohnBueno** [comment]
@LHeczko I am running into something similar using OKHttp and Retrofit. It also seems to be specific to a certain kind of device.  I don't know that we have any specific code set up in `lostConnection` or `registerNetworkCallbac`k though.  Where would I look for this?
