### ISSUE TITLE
String.toRequestBody() vs. String.asRequestBody()

### ISSUE THREAD

**Issue by swankjesse** [square/okhttp#5177]
We’ve implemented it as `String.toRequestBody()` but I think we might be mistaken here. `to` feels like a conversion; `as` feels like a cast. I’d like to confirm what the precedents are and follow them.

**Comment by JakeWharton** [comment]
The distinction for string is mostly irrelevant because it's immutable. I think file is far more interesting and makes the argument for 'as'. The key difference being that changes to the file contents are reflected in the request body even after it's been created.

**Comment by swankjesse** [comment]
Lemme confirm I follow:

A.toB: returns a B getting the value from A. String.toInt(), Int.toString(), MutableList.toList().

A.asB: returns a B that is a view of A. Arrays.asList(), MutableList as List.

**Comment by JakeWharton** [comment]
That is my understanding, yep!

**Comment by swankjesse** [comment]
I wanna change `File.toRequestBody()` to `File.asRequestBody()` because we don’t snapshot the file at the time of the call. I should go through the other `toXxx()` methods to confirm they’re not views.
