### ISSUE TITLE
 java.net.SocketException:Socket closed

### ISSUE THREAD

**Issue by supermavericks** [square/okhttp#5179]
java.lang.IllegalStateException:Fata Exceptio throw o Scheduler.Worke thread.
 rx.android.schedulers.LooperScheduler$ScheduledAction.run(LooperScheduler.java:114)
 ......
 Cause by:
 java.net.SocketException:Socke closed
 java.net.SocketInputStream.read(SocketInputStream.java:203)
 java.net.SocketInputStream.read(SocketInputStream.java:139)
 okio.Okio$2.read(Okio.java:140)
 okio.AsyncTimeout$2.read(AsyncTimeout.java:237)
 okio.RealBufferedSource.indexOf(RealBufferedSource.java:355)
 okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:227)
 okhttp3.internal.http1.Http1Codec.readHeaderLine(Http1Codec.java:215)
 okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:189)
 okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:88)
 okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
 okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
 okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
 okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
 okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
 okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
 okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
 okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
 okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
 okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
 okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
 okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
 com.fr_cloud.common.thirdparty.RetrofitModule$2.intercept(RetrofitModule.java:103)
 okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
 okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
 okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
 okhttp3.RealCall.execute(RealCall.java:77)
 retrofit2.OkHttpCall.execute(OkHttpCall.java:174)
 retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$RequestArbiter.request(RxJavaCallAdapterFactory.java:171)
 rx.internal.operators.OperatorSubscribeOn$1$1$1.request(OperatorSubscribeOn.java:80)
 rx.Subscriber.setProducer(Subscriber.java:211)
 rx.internal.operators.OperatorSubscribeOn$1$1.setProducer(OperatorSubscribeOn.java:76)
 rx.internal.operators.OperatorMap$MapSubscriber.setProducer(OperatorMap.java:99)
 rx.Subscriber.setProducer(Subscriber.java:205)
 retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:152)
 retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:138)
 rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
 rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
 rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
 rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
 rx.Observable.unsafeSubscribe(Observable.java:8460)
 rx.internal.operators.OperatorSubscribeOn$1.call(OperatorSubscribeOn.java:94)
 rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
 java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
 java.util.concurrent.FutureTask.run(FutureTask.java:266)
 java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
 java.lang.Thread.run(Thread.java:764)

**Comment by swankjesse** [comment]
Unclear what action we’d take on this. Open a new bug if you can reproduce with an executable test case.
