### ISSUE TITLE
Docker container missing SNAT on massive request

### ISSUE THREAD

**Issue by msartor92** [square/okhttp#5183]
Hi all,

I've introduced retrofit2 into a java application that made massive (bulk of 250k) http request to some (3) endpoint and run into a Docker container.

Dockerfile example:
`FROM openjdk:8-jre-alpine

COPY "./FlinkHTTPTest.jar" "/tmp/FlinkHTTPTest.jar"

ENV jar_file=FlinkHTTPTest.jar
ENTRYPOINT exec java $JAVA_OPTS -jar /tmp/$jar_file
`
Initially apps work well but after few second I see on the host TCP packet exiting with container source IP.
The expected behavior is that host NAT source IP of each packet coming from Docker container with host IP so the other host that recive request could respond through it.

Instead with this bug other host receive request and respond to docker ip that is not exposed to all VM so that packet generate an alert in the firewall.

Ping and telnet command works fine so I think host ARP table is correct.

I've used Retrofit with okHttp implementation.

Anyone with same problem?
I've run mi code also with plain java (HttpURLConnection) implementation and this work fine.

**Comment by swankjesse** [comment]
Executable test case?
