### ISSUE TITLE
Error while dexing with okhttp 4.0.0 releases

### ISSUE THREAD

**Issue by bohsen** [square/okhttp#5185]
Preparing a migration to okhttp 4.0.0 (using 4.0.0-RC1) we are seeing an issue when trying to  install the app.

A gist of the stacktrace can be found [here](https://gist.github.com/bohsen/3b0b30168d723e15a6a46e209d1a8e42).

Build output looks like this:
![Skærmbillede 2019-06-12 kl  14 46 04](https://user-images.githubusercontent.com/355452/59352542-37bbc300-8d21-11e9-81ae-eba2d004ccbb.png)

Happens every time we try to run the app.

Reverting to version 3.14.2 fixes it.

**Comment by JakeWharton** [comment]
Please file an issue on R8 at https://issuetracker.google.com/issues/new?component=326788 and link it here. It's unlikely that OkHttp is actually the cause of this beyond having a shape of code that somehow breaks R8.

**Comment by JakeWharton** [comment]
Also, make sure you're on the latest Android Gradle plugin. I don't have any problems on 3.4.1 or 3.5 betas with the RC1.

**Comment by bohsen** [comment]
If others come across this - issue can be found [here](https://issuetracker.google.com/issues/135141615).

**Comment by namkazt** [comment]
still have this problem on rc1 with lastest gradle 3.4.1. I need to revert to use 3.14.2

**Comment by bohsen** [comment]
@namkazt Just disable advanced profiling in your run configuration and the problem will be gone.

<img width="768" alt="Skærmbillede 2019-06-15 kl  23 51 37" src="https://user-images.githubusercontent.com/355452/59556797-56dc7e00-8fc9-11e9-9b3a-a41ea2975102.png">

**Comment by namkazt** [comment]
@bohsen ohhh right, I wonder why it just happens from nowhere when just run normally. Thanks
