### ISSUE TITLE
Improve Connection Pool logic and defaults

### ISSUE THREAD

**Issue by yschimke** [square/okhttp#5191]
5 idle connections seems small for an app that might hit 2 APIs, a few CDNs etc and some external sites.

Specifically closing a bunch of HTTP/2 connections to retain the last 5 HTTP/1.1 connections to a single site seems odd.

<img width="352" alt="image" src="https://user-images.githubusercontent.com/231923/59565690-5e923600-904e-11e9-870f-e3a7fb7df387.png">

**Comment by yschimke** [comment]
FYI I know the defaults are tunable, but the logic isn't.

**Comment by swankjesse** [comment]
I wanna build a small, high leverage API to let users control both connection pooling and client side load balancing.

**Comment by yschimke** [comment]
This is a good space for mid sized companies to improve their app performance.  And therefore a high value space above basic submit a HTTP request for me, for OkHttp to provide value. 

It's pretty obvious from java.net.http and Android cronet, that they want to hide any details like that because they can do a good job optimising the default with an API with minimal surface API. But not the best for any infra team at a tech company trying to improve app performance.

I'm still plugging along on https://github.com/yschimke/OkHttpAndroidApp/
