### ISSUE TITLE
Public API to monitor and manage connections 

### ISSUE THREAD

**Issue by yschimke** [square/okhttp#5194]
https://github.com/yschimke/OkHttpAndroidApp/blob/master/android/app/src/main/java/ee/schimke/okhttp/android/factory/Accessors.kt

Shows the internal APIs and reflection I've needed to monitor and actively manage connections e.g. soft/hard close them on network events.

Raising this to track a 4.1 API for this sort of functionality.

Want to be able to:
- enumerate the connections with some form of identity (id? or reference?), 
- Actively close or soft close a connection
- Understand network (socket? local ip?)

**Comment by yschimke** [comment]
Relates to https://github.com/square/okhttp/issues/4530

**Comment by yschimke** [comment]
Also relates to https://github.com/square/okhttp/pull/3855

**Comment by yschimke** [comment]
@swankjesse how against this are you? I could really use this on Wear, where controlling which connections between (low bandwidth) BT, Wifi and expensive LTE is critical for apps.

I'm looking to accurately report the number of each type of connections, since there can me multiple at the same time.  We might have started a bluetooth connection for fetching artwork images, then temporarily open up LTE to download an 80mb podcast.

**Comment by swankjesse** [comment]
I'm not opposed! Doing a multiplatform release with Android-specific code also gives us the opportunity to do this in a way that gives users good defaults.

My top line goal here is that if we offer a tuning API, we should also do the work to make use of it ourselves.

**Comment by yschimke** [comment]
A draft for discussion here https://github.com/square/okhttp/pull/7456
