### ISSUE TITLE
Fatal Exception: java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by MajaTrzebiatowska** [square/okhttp#5196]
Retrofit version: 2.3.0
okHttp version: 3.14.1
Brand: samsung
Model: Galaxy S7 edge
RAM free: 1.17 GB
Disk free: 898.03 MB
Operating System Version: 8.0.0
Rooted: No

Stacktrace: Fatal Exception: java.lang.ArrayIndexOutOfBoundsException
size=13 offset=0 byteCount=4827

okio.Util.checkOffsetAndCount (Util.java:30)
okio.AsyncTimeout$1.write (AsyncTimeout.java:162)
okio.RealBufferedSink.emitCompleteSegments (RealBufferedSink.java:179)
okio.RealBufferedSink.writeByte (RealBufferedSink.java:125)
okhttp3.internal.http2.Http2Writer.writeMedium (Http2Writer.java:265)
okhttp3.internal.http2.Http2Writer.frameHeader (Http2Writer.java:253)
okhttp3.internal.http2.Http2Writer.goAway (Http2Writer.java:220)
okhttp3.internal.http2.Http2Connection.shutdown (Http2Connection.java:428)
okhttp3.internal.http2.Http2Connection.close (Http2Connection.java:443)
okhttp3.internal.http2.Http2Connection$ReaderRunnable.execute (Http2Connection.java:609)
okhttp3.internal.NamedRunnable.run (NamedRunnable.java:32)
java.lang.Thread.run (Thread.java:764)

As it only happened once, we weren't able to reproduce yet or provide a test case atm. Will update when happens again though.

**Comment by swankjesse** [comment]
Typically indicates unsafe concurrent access to buffers.
