### ISSUE TITLE
Conditional GET is issued even though cache is fresh (max-age ignored?)

### ISSUE THREAD

**Issue by TommyN** [square/okhttp#5197]
Given the following response to a GET request
```
cache-control: public, max-age=1800
content-encoding: gzip
content-type: application/json
date: Tue, 18 Jun 2019 08:33:16 GMT
```

I would expect a subsequent GET for the same resource to use the cached response.
Instead a conditional GET is issued
```
Request Method: GET
Accept-Encoding: gzip
Connection: Keep-Alive
If-Modified-Since: Tue, 18 Jun 2019 08:33:16 GMT
```

The clock on the phone was around 08:40:00 GMT at the time of testing, so the `max-age` (30 min) should have prevented the network call.

Also note that the response doesn't include a `Last-Modified` header, but still a `If-Modified-Since` is added in the request based on the previous `Date` header.

From: https://tools.ietf.org/html/rfc7232#section-3.3
>    However, caches occasionally generate the field
>    value based on other data, such as the Date header field of the
>    cached message or the local clock time that the message was received,
>    particularly when the cached message does not contain a Last-Modified
>    field.
> 

Btw, is it possible to turn off this behavior so a conditional GET is only performed if a `Last-Modified` header or `Etag` header is present in the response?

I might be missing something that "Wiki page all about caching #4637" would answer.

Environment: Android
Version: 'com.squareup.okhttp3:okhttp:3.11.0'

**Comment by swankjesse** [comment]
Agreed we could use better docs here. This might help:

https://github.com/square/okhttp/blob/master/okhttp/src/main/java/okhttp3/internal/cache/CacheStrategy.kt

**Comment by TommyN** [comment]
My bad! Couldn't find anything from the linked code, but found that we'd installed a custom interceptor and had also used the overrideServerCachePolicy. Removing the code made everything work as expected.
