### ISSUE TITLE
MockResponse socketPolicy awkwardness in 4.0

### ISSUE THREAD

**Issue by yschimke** [square/okhttp#5199]
One is deprecated, the other doesn't compile...

<img width="609" alt="image" src="https://user-images.githubusercontent.com/231923/59740359-c8cdf500-925f-11e9-91bc-103f753bed65.png">

**Comment by swankjesse** [comment]
Ugh. Kotlin doesn't like mutators to return things.

**Comment by swankjesse** [comment]
I assume Good Kotlin Style is `.apply` ?

**Comment by yschimke** [comment]
@swankjesse that doesn't help for Java callers.

**Comment by yschimke** [comment]
apply doesn't really help, see https://github.com/square/okhttp/issues/5470
