### ISSUE TITLE
🙉response.header("OkHttp-Sent-Millis“)/(”OkHttp-Received-Millis“) 

### ISSUE THREAD

**Issue by NeverGiveUp-Max** [square/okhttp#5200]
What do these two parameters mean？
Can I subtract these two parameters to calculate the request time？

**Comment by swankjesse** [comment]
These are no longer headers Upgrade to a more recent OkHttp and use the methods instead.

http://square.github.io/okhttp/3.x/okhttp/okhttp3/Response.html#sentRequestAtMillis--
