### ISSUE TITLE
IndexOutOfBoundsException

### ISSUE THREAD

**Issue by wangshuibo** [square/okhttp#5204]
1 java.util.Collections$EmptyList.get(Collections.java:4514)
--
2 okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:326)
3 okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:283)
4 okhttp3.internal.connection.RealConnection.connect(RealConnection.java:168)
5 okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:257)
6 okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
7 okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
8 okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
9 okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
10 okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
11 okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
12 okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
13 okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
14 okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
15 okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
16 okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
17 okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
18 okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
19 okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:254)
20 okhttp3.RealCall$AsyncCall.execute(RealCall.java:200)
21 okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
22 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
23 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
24 java.lang.Thread.run(Thread.java:784)

**Comment by monkey-mas** [comment]
Which version are you using? Please paste test case or your branch URL that can reproduce the error.

**Comment by monkey-mas** [comment]
Let me close the issue. Please reopen it when executable test case is available! :)
