### ISSUE TITLE
Stackoverflow link in docs points at okhttp not okhttp3

### ISSUE THREAD

**Issue by yschimke** [square/okhttp#5206]
https://square.github.io/okhttp/

1.9k https://stackoverflow.com/questions/tagged/okhttp?sort=active
1.3k https://stackoverflow.com/questions/tagged/okhttp3?sort=active

Might be worth suggesting these as synonyms now

**Comment by swankjesse** [comment]
Lets encourage `okhttp` only. Now that we’re on the package okhttp3 with version 4.0 the version numbers work against us.

**Comment by yschimke** [comment]
If you have enough karma could you suggest on stackoverflow?

**Comment by yschimke** [comment]
<img width="505" alt="image" src="https://user-images.githubusercontent.com/231923/63082509-1361aa00-bf4f-11e9-9d51-1199940e0613.png">

**Comment by swankjesse** [comment]
Nah, moderator is a very special role that you can’t achieve through reputation alone. Not sure how to request this, but these are the people.
https://stackoverflow.com/users?tab=moderators

**Comment by yschimke** [comment]
Synonym added https://stackoverflow.com/tags/okhttp/synonyms
