### ISSUE TITLE
MockWebServer takeRequest with timeout should be nullable

### ISSUE THREAD

**Issue by laalto** [square/okhttp#5208]
OkHttp 4.0.0-RC1

`MockWebServer` `takeRequest()` with timeout function signature is NotNull:

```
fun takeRequest(timeout: Long, unit: TimeUnit): RecordedRequest = requestQueue.poll(timeout, unit)
```

However the underlying `LinkedBlockingQueue` `poll()` returns nulls on timeout, causing an `IllegalStateException` when a NotNull kotlin function tries to return null.

I believe the return type should be Nullable instead, e.g. 

```
fun takeRequest(timeout: Long, unit: TimeUnit): RecordedRequest? = requestQueue.poll(timeout, unit)
```

I discovered this when trying out 4.0.0-RC1 migration on a codebase that has some unit test cases testing caching functionality using `takeRequest()` with (short) timeout to make sure the feature being tested does not hit the network.

**Comment by swankjesse** [comment]
Good catch. Can fix.
