### ISSUE TITLE
JDK 13 Testing

### ISSUE THREAD

**Issue by yschimke** [square/okhttp#5213]
Gradle support still missing

https://github.com/gradle/gradle/issues/8681

https://jdk.java.net/13/release-notes

Reimplement the Legacy Socket API (JDK-8221481)
Update the default enabled cipher suites preference (JDK-8163326)
Use server cipher suites preference by default (JDK-8168261)
Deprecated javax.security.cert APIs with forRemoval=true (JDK-8160247)

okhttp-testing-support/src/main/java/okhttp3/FakeSSLSession.java:import javax.security.cert.X509Certificate;

**Comment by swankjesse** [comment]
Yikes, that’s a lot of risky changes.

**Comment by yschimke** [comment]
So far, no observed issues in an Intellij build with an EA of 13. But still blocked on CircleCI integration as above.

**Comment by yschimke** [comment]
The only test with a problem

https://github.com/square/okhttp/issues/5221
 
> Seems like a deadlock problem? Probably related issue was resolved and fixed in JDK 13.
> JDK-8219658 Deadlock in sun.security.ssl.SSLSocketImpl

**Comment by yschimke** [comment]
https://twitter.com/seanjmullan/status/1158348427027259392?s=21

**Comment by yschimke** [comment]
Testing here with Gradle 6 snapshot https://github.com/square/okhttp/pull/5385

**Comment by yschimke** [comment]
Only test failing is previously identified https://github.com/square/okhttp/issues/5221 which is fixed in JDK 13, so I think we are good.

**Comment by yschimke** [comment]
Gradle 6 fails with a spotless bug reported here https://github.com/diffplug/spotless/issues/440
