### ISSUE TITLE
Is is possible to intercept incoming self-signed certificate?

### ISSUE THREAD

**Issue by ursusursus** [square/okhttp#5219]
Hi, upon SSLHandshake exception of self-signed SSL cert, is it possible to intercept this certificate? I.e. to get its contents so I can save it to he keystore, to be used normally as hardcoded self-signed certificate would from assets via sslSocketFactory etc?

TLDR; "This certificate is not trusted bla bla. Accept?", however I am not sure how to grab the certificate so I can add it to the keystore

**Comment by yschimke** [comment]
Could you ask questions like this on stackoverflow, it's a better place to have the discussion and more community answers etc. I'll answer there.

**Comment by ursusursus** [comment]
If I knew I'd get a response there..

But okay:
https://stackoverflow.com/questions/56711560/how-to-accept-incoming-self-signed-ssl-certificate-in-okhttp

please chime in if you can
