### ISSUE TITLE
EventListener proxy events

### ISSUE THREAD

**Issue by yschimke** [square/okhttp#5230]
http://square.github.io/okhttp/events/

<img width="379" alt="image" src="https://user-images.githubusercontent.com/231923/59973218-6d1fa680-9594-11e9-8c13-97ff18f12b0a.png">

Between callStart and dns event there is likely a thread context switch.  Awkwardly there are API interactions, e.g. the Proxy selection which is essentially implicit here.  This event is hidden from event listeners.

I'd like to be able to make decisions in a ProxySelector based on the active call, but it's not easy to track either through direct API parameters or implicitly via the associated call/thread etc.

```
        at ee.schimke.okhttp.android.factory.AndroidProxySelector.select(AndroidProxySelector.kt:12)
        at okhttp3.internal.connection.RouteSelector.resetNextProxy(RouteSelector.java:115)
        at okhttp3.internal.connection.RouteSelector.<init>(RouteSelector.java:63)
        at okhttp3.internal.connection.ExchangeFinder.<init>(ExchangeFinder.java:75)
        at okhttp3.internal.connection.Transmitter.prepareToConnect(Transmitter.java:138)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:79)
``` 

Options

1) a OkHttp Proxy API with this information
2) add events around Proxy selection to EventListener

Why should we care?

1) At least on Android multiple networks might have different proxies e.g. Cellular is direct, Wifi has a corporate proxy.
2) Proxy selection is an "interesting" event we aren't tracking.

**Comment by swankjesse** [comment]
Cool. Maybe this?

```
/**
 * Invoked prior to a proxy selection.
 *
 * This will be invoked for route selection regardless of whether the client
 * is configured with a single proxy, a proxy selector, or neither.
 * 
 * @param url a URL with only the scheme, hostname, and port specified.
 */
open fun proxySelectStart(call: Call, url: HttpUrl)

/**
 * Invoked after proxy selection.
 * 
 * Note that the list of proxies is never null, but it may be a list containing
 * only [Proxy.NO_PROXY]. This comes up in several situations:
 * 
 * * If neither a proxy nor proxy selector is configured.
 * * If the proxy is configured explicitly as [Proxy.NO_PROXY].
 * * If the proxy selector returns only [Proxy.NO_PROXY].
 * * If the proxy selector returns an empty list or null.
 *
 * Otherwise it lists the proxies in the order they will be attempted.
 * 
 * @param url a URL with only the scheme, hostname, and port specified.
 */
open fun proxySelectEnd(call: Call, url: HttpUrl, proxies: List<Proxy>)
```

**Comment by swankjesse** [comment]
Only other gotcha is to make sure we don’t call these while holding any locks.

**Comment by yschimke** [comment]
I'll check the locks, but if we were holding locks we were potentially executing javascript of Proxy PAC files, so that's a more serious problem.

**Comment by swankjesse** [comment]
Done!
