### ISSUE TITLE
Conscrypt use in Android forces HTTP/1.1

### ISSUE THREAD

**Issue by yschimke** [square/okhttp#5231]
Trying to use Conscrypt + OkHttp in Android seems to force HTTP/1.1. I suspect this is rare, since most common options are

 1. AndroidPlatform *just* works (by a big majority)
 2. Use Google Play provider to upgrade Android without breaking AndroidPlatform (haven't seen this in the wild)

Conscrypt provider + AndroidPlatform seems to result in ALPN not working?  You can't easily opt into ConscryptPlatform for a couple of reasons

 1. The ordering picks up AndroidPlatform first
 2. It's a final field after initialization and a lot of frameworks e.g. reactnative would trigger the platform earlier.

**Comment by yschimke** [comment]
It's working fine on a desktop, just on Android having issues testing.

**Comment by yschimke** [comment]
<img width="1242" alt="image" src="https://user-images.githubusercontent.com/231923/59979614-0a54fc00-95e2-11e9-922b-f169595134fd.png">

Runtime socket with Conscrypt = org.conscrypt.Java8FileDescriptorSocket 
AndroidPlatform uses com.android.org.conscrypt.OpenSSLSocketImpl

**Comment by yschimke** [comment]
Also failing with GMS - com.google.android.gms.org.conscrypt.Java8FileDescriptorSocket

**Comment by yschimke** [comment]
cc @swankjesse curious if this is surprising to you?  Should we warn against using Gms provider until we fix this?  Everything works, but Http/1.1 certainly isn't optimal.

**Comment by yschimke** [comment]
I'll put a PR up for conscrypt support and Android to bump it to the top.

**Comment by swankjesse** [comment]
I’m surprised GMS doesn’t work. I don’t think Conscrypt on Android is common.

**Comment by yschimke** [comment]
With GMS

sslSocketClass = com.android.org.conscrypt.OpenSSLSocketImpl

sslSocket is com.google.android.gms.org.conscrypt.Java8FileDescriptorSocket
com.google.android.gms.org.conscrypt.ConscryptFileDescriptorSocket
com.google.android.gms.org.conscrypt.OpenSSLSocketImpl
com.google.android.gms.org.conscrypt.AbstractConscryptSocket
javax.net.ssl.SSLSocket

**Comment by yschimke** [comment]
I don't think this is urgent, since it's opt-in per app.  The default just works. But probably worth fixing in 3.12.x, 3.14.x and 4.1?  Choosing high security here, means giving up on HTTP/2 currently :(

**Comment by yschimke** [comment]
Package names from here https://android.googlesource.com/platform/external/conscrypt/+/b578b39/src/main/java/org/conscrypt/NativeCrypto.java#53

cc @flooey

**Comment by yschimke** [comment]
Testing a fix on https://github.com/square/okhttp/pull/5243

**Comment by colinrtwhite** [comment]
Worth noting that I believe Google's Firestore SDK installs Conscrypt asynchronously [behind the scenes](https://github.com/firebase/firebase-android-sdk/blob/d9ed980c39c58ddf55ab945baa120c2e0a9fa8cb/firebase-firestore/src/main/java/com/google/firebase/firestore/remote/GrpcCallProvider.java#L92). This can create a race condition when setting up new sockets.

**Comment by yschimke** [comment]
My intended fix should handle the socket type changing
