### ISSUE TITLE
HTTP FAILED: javax.net.ssl.SSLHandshakeException: Handshake failed

### ISSUE THREAD

**Issue by lbx2015** [square/okhttp#5232]
I am using  implementation 'com.squareup.okhttp3:okhttp:3.11.0' 
and after I upgrade to 3.14.2 I got the following issue. all the api is not work with the following issue. How can I do with this to jump this issue. 
I am using android studio 3.4.1 and I am in Shanghai of China.
HTTP FAILED: javax.net.ssl.SSLHandshakeException: Handshake failed.

Hope hear soon from u. 

following is my script:
    implementation 'com.google.code.gson:gson:2.8.2'
        implementation('com.squareup.retrofit2:retrofit:2.6.0') {
        // exclude Retrofit’s OkHttp peer-dependency module and define your own module import
        exclude module: 'okhttp'
    }
    implementation 'com.squareup.okhttp3:okhttp:3.14.2'

**Comment by lbx2015** [comment]
I tried to solve this : and not the same issue
   ConnectionSpec.Builder obsoleteSpecBuilder = new ConnectionSpec.Builder(ConnectionSpec.COMPATIBLE_TLS);
        obsoleteSpecBuilder = obsoleteSpecBuilder.cipherSuites("TLS_DHE_DSS_WITH_AES_128_CBC_SHA");
        ConnectionSpec obsoleteSpec = obsoleteSpecBuilder.build();

        HttpLoggingInterceptor interceptor = new HttpLoggingInterceptor();
        interceptor.setLevel(HttpLoggingInterceptor.Level.BODY);
        OkHttpClient client = new OkHttpClient.Builder()
                .addInterceptor(new HeaderInterceptor())
                .readTimeout(120, TimeUnit.SECONDS)
                .connectTimeout(120, TimeUnit.SECONDS)
                .writeTimeout(120, TimeUnit.SECONDS)
                .connectionSpecs(Arrays.asList(obsoleteSpec))
                .addInterceptor(interceptor).build();

**Comment by yschimke** [comment]
Can you raise this on stackoverflow with a working example? It's often environmental e.g. phone, server, tls version/cipher related.

If you can make a reproduction as a test case for OkHttp then reopen here.

**Comment by lbx2015** [comment]
solved, thanks guys. ! Today I upgrade to 2.6.1 and okhttp loging intrcepter 4.1.0, and got shake hand issue for my test server, This is an issue which can be solved in server configuration. But It's can also be solved in android side.  You can adding following configuration for the compatible tls.  
   List<ConnectionSpec> lists = Arrays.asList(ConnectionSpec.COMPATIBLE_TLS, ConnectionSpec.CLEARTEXT);
        HttpLoggingInterceptor interceptor = new HttpLoggingInterceptor();
        interceptor.setLevel(HttpLoggingInterceptor.Level.BODY);
        OkHttpClient.Builder build = new OkHttpClient.Builder()
           
                .connectionSpecs(lists)

**Comment by zhaobinsir** [comment]
here: https://devtak0623.medium.com/android-en-sslhandshakeexception-handshake-failed-aa27b278b82a
Solved my problem;
step1：implementation 'org.conscrypt:conscrypt-android:2.5.2'
step2：class App : Application() {
   
    override fun onCreate() {
        super.onCreate()
        Security.insertProviderAt(Conscrypt.newProvider(), 1)
    }
}

it's work！0.0！
