### ISSUE TITLE
Add Dollar sign to be replaced when creating a new URI

### ISSUE THREAD

**Issue by joaobbaptista** [square/okhttp#5236]
Is it possible to add the "$"  to the replaceAll when creating a new URI in the code below?

```
public URI uri() {
        String uri = newBuilder().reencodeForUri().toString();
        try {
            return new URI(uri);
        } catch (URISyntaxException e) {
            try {
                return URI.create(uri.replaceAll("[\\u0000-\\u001F\\u007F-\\u009F\\p{javaWhitespace}]", FRAGMENT_ENCODE_SET));
            } catch (Exception e2) {
                throw new RuntimeException(e);
            }
        }
    }
```

We have a library, that uses OkHttp crashing our android app because one of their customers is providing the following buggy URL: " https://${imp_tracker_1}/".

We have debugged the code and it's throwing an exception at the second Catch of the function above. Since $ is a reserved character for URI and does nothing I think it would be a good idea to have it treated when trying to create a new URI.

**Comment by swankjesse** [comment]
Yeah, I think we can handle this. Or you can call `newBuilder()` to replace it yourself.

**Comment by joaobbaptista** [comment]
Hey Jesse, thanks for the quick response!
Actually, I can't make any change to fix that issue on our app because is a tracking call that the library we consume does internally and is throwing the crash back at us. 

We don't have any interaction with the tracking call nor with the URL that is being called. We notified them and had it disabled on our app for now but I think it may be something that could be handled by OkHTTP as well since the crash is actually happening at the code I shared above and "$" is a URL reserved sign.

Thanks!

**Comment by yschimke** [comment]
@swankjesse Do we want to make HttpUrl stricter for the host?  Or just send through an incomplete but passing host?  What about http://$/?

```
  @Test public void hostContainsIllegalCharacter() throws Exception {
    assertInvalid("http://\n/", "Invalid URL host: \"\n\"");
    assertInvalid("http:// /", "Invalid URL host: \" \"");
    assertInvalid("http://%20/", "Invalid URL host: \"%20\"");
    // added here
    assertInvalid("http://$/", "Invalid URL host: \"%20\"");
  }
```
Or is there some sensible encoding to pass to URI constructor?

Specifically that catch block is documented as handling the fragment, which I accept for stripping.  But this case involves a $ in the host.

**Comment by swankjesse** [comment]
I don't think we'll be able to resolve a host with a `$` character in it.

What do the specs say?

**Comment by yschimke** [comment]
https://tools.ietf.org/html/rfc3986#section-3.2.2

https://tools.ietf.org/html/rfc1034#section-3.5

Pretty sure it's invalid so we should arguably fail parsing before allowing an invalid HttpUrl.

**Comment by swankjesse** [comment]
Our validation of hostnames is pretty limited. We lean on Java’s IDN class for most of it.
