### ISSUE TITLE
Allow overriding/redaction of host in RealWebSocket thread names

### ISSUE THREAD

**Issue by nathklei** [square/okhttp#5237]
To allow sharing stack traces where host names are considered sensitive, the behavior of thread name provided by RealWebSocket should be overridable:
https://github.com/square/okhttp/blob/master/okhttp/src/main/java/okhttp3/internal/ws/RealWebSocket.kt#L178

I'm happy to contribute a fix here if someone can point me to the best way to override something like this, or if this is feasible.

Thanks!

**Comment by swankjesse** [comment]
The hostname is sensitive? Yikes. We aren’t really prepared for this, especially as we also use the hostname in exceptions.

I don’t want to add this flexibility to the core library, just because it’s such a one-off case. Would you consider finding a way to avoid needing these sensitive hostnames?

**Comment by nathklei** [comment]
Thanks for the reply @swankjesse! While in our specific case exception messages are not a concern - only thread names which end up in shared thread stacks (e.g. via jstack) - I understand the hesitance to make this change.  I'll do a bit more thinking on if there are any alternatives for us.

**Comment by yschimke** [comment]
Won't fix.
