### ISSUE TITLE
Tag critical Java tests with @JavaApiTest

### ISSUE THREAD

**Issue by yschimke** [square/okhttp#5244]
I assume new tests we will increasingly write with Kotlin, particularly with some kotlin specific surface area.  So tagging the tests that should remain in Java would be useful, and migrating some to cleaner Kotlin APIs e.g. CallTest?

**Comment by swankjesse** [comment]
Yikes, yeah this gets complicated.

Should we create a JavaSourceCompatibilityTest? Or a set of them? Then we don’t have to rely on the tests to have that side responsibility?

**Comment by yschimke** [comment]
Yep. Sounds good. Just wanted to have discussion and noted plan.
