### ISSUE TITLE
Add jvm static to companion object to improve backward compatibility

### ISSUE THREAD

**Issue by ahmadmuhsink** [square/okhttp#5245]
Apollo client is not compatible because of this:

https://github.com/apollographql/apollo-android/issues/1394

**Comment by yschimke** [comment]
We have made some concessions, e.g. https://github.com/square/okhttp/commit/ab72e81808533957e4d669d8ae1a817056e4bce2

Not sure where this sits...

**Comment by yschimke** [comment]
We have made some concessions, e.g. https://github.com/square/okhttp/commit/ab72e81808533957e4d669d8ae1a817056e4bce2

Not sure where this sits...

**Comment by JakeWharton** [comment]
They seem to be using the cache as if it were a library type. Don't see much reason to fix this. They should be copy/pasting and embeding instead.

**Comment by digitalbuddha** [comment]
https://github.com/apollographql/apollo-android/pull/1357 Zac fixed it already

**Comment by ahmadmuhsink** [comment]
Thanks. Closing this.
