### ISSUE TITLE
HttpHeaders.hasBody removed

### ISSUE THREAD

**Issue by PaulWoitaschek** [square/okhttp#5246]
There is no replacement for the old function `HttpHeaders.hasBody`

Therefore it's not binary compatible and crashes using chuck:

https://github.com/jgilfelt/chuck/blob/152f9a79f94ea23e9f0542137765961918909a76/library/src/main/java/com/readystatesoftware/chuck/ChuckInterceptor.java#L196

Feel free to close as it's in the internal package.

**Comment by yschimke** [comment]
It's generally inline with https://github.com/square/okhttp/commit/ab72e81808533957e4d669d8ae1a817056e4bce2

**Comment by koral--** [comment]
There is a `Response.promisesBody()` extension function which looks like possible replacement.

https://github.com/square/okhttp/blob/eee838aebe8d3524d7e0e2dbf8f9bf357512f038/okhttp/src/main/java/okhttp3/internal/http/HttpHeaders.kt#L213

**Comment by swankjesse** [comment]
Do not use APIs in `internal`. We will move them in a future release without warning.

If you need this functionality, copy-paste it into your app.
