### ISSUE TITLE
Update wording on library deps

### ISSUE THREAD

**Issue by yschimke** [square/okhttp#5247]
> OkHttp has one library dependency on Okio, a small library for high-performance I/O.

api deps.okio
api deps.kotlinStdlib

Should we have a statement on the policy for upgrading kotlin?

**Comment by JakeWharton** [comment]
Still might be worth talking about this as a single library dependency, but then also mentioning that it's written in Kotlin and incurs the Kotlin stdlib dependency as a result of that.

**Comment by yschimke** [comment]
related PR https://github.com/square/okhttp/pull/5273
