### ISSUE TITLE
Make canonicalize public API

### ISSUE THREAD

**Issue by Tolriq** [square/okhttp#5248]
Already asked about that a long time ago and was refused :)

But before we could package cheat and use the code, now there's no more possible cheat.

That piece of code is highly optimized and very useful, it's sad to have to copy paste a bunch of things to reproduce it.

What would be missing to have that as a public API?

**Comment by swankjesse** [comment]
What’s the use case?

**Comment by Tolriq** [comment]
1) 
I receive data from a backend that I need to encode with specific set before appending them to an url later when actually loading it.
Since it's on a performance critical path and dealing with many thousands, I do the encoding before saving to database. OkHTTP code fit that needs of specific sets and is way faster and allocation efficient than OS versions (Specially since I then need to do some replace in the generated string to fix the applied set)

2)
Less important as less critical path, but I do need to generate simple static string urls with encoded login/password and place holders with manual encoding allocate a lot less than create a full blown httpurl and convert to string. (For that one I could use provided httpurl api)

**Comment by swankjesse** [comment]
Got it. In both of these cases I think your best option is to copy this method into your project. Or maybe use one of the ones from Guava.
https://guava.dev/releases/snapshot-jre/api/docs/com/google/common/net/PercentEscaper.html

Our canonicalize method is an implementation detail. It doesn’t stand alone as a public API.
