### ISSUE TITLE
RealWebsocket boolean value no set to false after reconnecting

### ISSUE THREAD

**Issue by Edydaoud** [square/okhttp#5249]
After checking why the onFailure is called once and never get called again after calling `RealWebSocket.connect(client: OkHttpClient)` when the session is disconnected, I found that this boolean value 
` /** True if this web socket failed and the listener has been notified. */
  private boolean failed;`

is set to `true` in the `RealWebSocket.failWebSocket(e: Exception, response: Response)` and never set to false in the `RealWebSocket.connect(client: OkHttpClient)`

My question is: should I create a RealWebSocket instance every time the session disconnected to reconnect to the server or this is a bug and should I create a pull request?

**Comment by swankjesse** [comment]
You should never use the RealWebSocket type directly. It is in our `internal` package and off limits for you!

**Comment by Edydaoud** [comment]
> You should never use the RealWebSocket type directly. It is in our `internal` package and off limits for you!

I'm not using the RealWebSocket type directly, I'm pointing on the `boolean` in it.

> is set to true in the RealWebSocket.failWebSocket(e: Exception, response: Response) and never set to false in the RealWebSocket.connect(client: OkHttpClient)

These method calls are made inside the class, while the connect method is called after the client is disconnected due to an internet problem for example. `boolean failed` is always true after the first failure and the `RealWebSocket.failWebSocket(e: Exception, response: Response)` is never called again 

check line number 4

`public void failWebSocket(Exception e, @Nullable Response response) {
    Streams streamsToClose;
    synchronized (this) {
      if (failed) return; // Already failed.     
      failed = true;
      streamsToClose = this.streams;
      this.streams = null;
      if (cancelFuture != null) cancelFuture.cancel(false);
      if (executor != null) executor.shutdown();
    }

    try {
      listener.onFailure(this, e, response);
    } finally {
      closeQuietly(streamsToClose);
    }
  }`

**Comment by swankjesse** [comment]
Yes, once a web socket fails it’s failed forever. You'll need to create a new instance to retry.
