### ISSUE TITLE
🙉When can support Android Q with API that create ReuqestBody by Uri

### ISSUE THREAD

**Issue by 24KWYL** [square/okhttp#5250]
RequestBody requestFile =
                                RequestBody.create(MediaType.parse("multipart/form-data"), uri);

**Comment by yschimke** [comment]
is uri a location that should be downloaded automatically and inserted into the request? or a data uri of an image etc?

**Comment by 24KWYL** [comment]
i want to upload file by uri and local imge or audio

**Comment by yschimke** [comment]
This won’t be supported. You will need to create your own RequestBody subclass

**Comment by jp1017** [comment]
> This won’t be supported. You will need to create your own RequestBody subclass

@yschimke So, how to make it, can't upload file on Android 10 now.

**Comment by yschimke** [comment]
If you want to reopen, can you provide a reproducible test case?  I think I'm missing exactly what you are asking.

Stackoverflow is a better place for general usage questions.

**Comment by SjAndy88** [comment]
in Android Q, app can't read the file which in the external file by File api, only support Uri.

**Comment by liujingxing** [comment]
@yschimke In Android Q, we can only get the Uri object, but we can't read the length of the Uri, so we can't create a subclass of RequestBody.
