### ISSUE TITLE
EventListener responseBodyEnd callEnd not execute when method is post

### ISSUE THREAD

**Issue by sakurajiang** [square/okhttp#5252]
I use OkHttp version is 3.14.2，when I debug，I find it will enter else block in CallServerInterceptor：
```
if (requestBody.isDuplex()) {
          // Prepare a duplex body so that the application can send a request body later.
          exchange.flushRequest()
          val bufferedRequestBody = exchange.createRequestBody(request, true).buffer()
          requestBody.writeTo(bufferedRequestBody)
        } else {
          // Write the request body if the "Expect: 100-continue" expectation was met.
          val bufferedRequestBody = exchange.createRequestBody(request, false).buffer()
          requestBody.writeTo(bufferedRequestBody)
          bufferedRequestBody.close()
        }
```
and then it will enter `Exchange.close()`,then `bodyComplete(bytesReceived, false, true, e)`

**Comment by swankjesse** [comment]
Do you consume the entire response body? Please provide an executable test case! Here's one to get you started:
https://github.com/square/okhttp/blob/master/okhttp/src/test/java/okhttp3/EventListenerTest.java#L1247

**Comment by sakurajiang** [comment]
thank you for your reply
I find reason after I report this Bug, and I comment it on my Bug page, but now I can not find it 
the cause of the bug is i am not consume the entire response body
in my origin code , i do not consume the entire response body, here is my origin code: 
```
if (response.isSuccessful) {
                internal?.deleteLogFile(file.absolutePath)
            }
```
here is my new code:
```
if (response.isSuccessful) {
                response.body()?.string()
                internal?.deleteLogFile(file.absolutePath)
            }
```
my new code is work.
but I think some times people do not consume entire response body, so I think the better way is can Implicit invoked by okhttp framework

**Comment by swankjesse** [comment]
No clear action to take here.
