### ISSUE TITLE
SSLException when trying to send multipart/form-data to AWS S3

### ISSUE THREAD

**Issue by AZOM** [square/okhttp#5254]
Hi folks

I am stuck when trying to upload bigger files (up to 100Mb) from Android to AWS S3 bucket using okhttp. 

The error I am getting is:

> OkHttp: <-- HTTP FAILED: javax.net.ssl.SSLException: Write error: ssl=0x96644e00: I/O error during system call, Connection reset by peer

Detailed information here in my thread on StackOverflow:
https://stackoverflow.com/questions/56739407/uploading-multipart-form-data-to-s3-bucket-throws-sslexception

I'd really appreciate your help :-)

**Comment by yschimke** [comment]
Thanks, taking a look in stackoverflow
