### ISSUE TITLE
Misuses of cryptographic APIs

### ISSUE THREAD

**Issue by mhp0rtal** [square/okhttp#5261]
Hi
The following lines have cryptographic API misuses. <br> File name => okhttp-tls/src/main/java/okhttp3/tls/HeldCertificate.java: Line number => 425: API name => KeyPairGenerator:First parameter (with value "ECDSA") should be any of {RSA, DSA, Diffie-Hellman}<BR> File name => okhttp-tls/src/main/java/okhttp3/tls/HeldCertificate.java: Line number => 427: API name => KeyPairGenerator:<BR> File name => samples/static-server/src/main/java/okhttp3/sample/SampleServer.java: Line number => 121: API name => KeyStore:Second parameter should never be of type java.lang.String.<BR> File name => samples/guide/src/main/java/okhttp3/recipes/CustomTrust.java: Line number => 209: API name => KeyStore:Second parameter should never be of type java.lang.String.<BR>

**Comment by swankjesse** [comment]
Spam.
https://github.com/mob41/broadlink-java-api/issues/22
