### ISSUE TITLE
[OKHTTP] HTTP2 use too many Connections

### ISSUE THREAD

**Issue by authorfu** [square/okhttp#5269]
I use okhttp version 3.14.2 to send Http2 request with alpn-boot-8.1.13.jar

By setting       `client.dispatcher().setMaxRequestsPerHost(250)` to send about 500 requests , I watched in Wireshark that about 20+ TCP connection established. But finally , I found only one TCP connection really transfered HTTP2 data. That means other 20 connections are useless and time wasted.

I review in code that in the source code, and find that:
In `ExchangeFinder.java   findConnection()`, there are 2  ` synchronized (connectionPool)`  methods. If I try to merge the two blocks into one, only one or two `RealConnection ` are created, the problems seems resolved.

**Comment by swankjesse** [comment]
This is working as designed. We pessimistically create multiple connections in case the server isn't HTTP/2, and consolidate them if they are.

Merging the synchronized blocks would dramatically harm throughput of HTTP/1 connections because we couldn't create them in parallel.
