### ISSUE TITLE
conflict logging-interceptor:version 4.0.0 had dependency okhttp3:version 3.8.1

### ISSUE THREAD

**Issue by brucewuu520** [square/okhttp#5277]
<dependency>
            <groupId>com.squareup.okhttp3</groupId>
            <artifactId>logging-interceptor</artifactId>
            <version>4.0.0</version>
</dependency>

has conflicts : 
dependency okhttp3 version 3.8.1

**Comment by JakeWharton** [comment]
All artifacts in the `com.squareup.okhttp3` groupId must use the same version. There are no source or binary compatibility guarantees between artifacts across different versions.
