### ISSUE TITLE
Avoid using non-null assertion in OkHttp4.0.x to prevent NPE

### ISSUE THREAD

**Issue by monkey-mas** [square/okhttp#5285]
To be compatible with OkHttp3, OkHttp4.0 doesn't use non-null assertion(`!!`) to avoid NPE.

Here's the list of classes where we use `!!`.
To find classes: `git grep "\!\!." | cut -f 1 -d ":" | uniq -d`

- [ ] `mockwebserver/src/main/java/okhttp3/mockwebserver/MockWebServer.kt`
- [ ] `okcurl/src/main/java/okhttp3/curl/Main.kt`
- [ ] `okhttp-dnsoverhttps/src/main/java/okhttp3/dnsoverhttps/DnsOverHttps.kt`
- [ ] `okhttp-tls/src/main/java/okhttp3/tls/HeldCertificate.kt`
- [ ] `okhttp-urlconnection/src/main/java/okhttp3/JavaNetCookieJar.kt`
- [ ] `okhttp/src/main/java/okhttp3/Cache.kt`
- [x] `okhttp/src/main/java/okhttp3/ConnectionSpec.kt`
- [ ] `okhttp/src/main/java/okhttp3/HttpUrl.kt`
- [ ] `okhttp/src/main/java/okhttp3/MultipartBody.kt`
- [ ] `okhttp/src/main/java/okhttp3/internal/cache/CacheInterceptor.kt`
- [ ] `okhttp/src/main/java/okhttp3/internal/cache/CacheStrategy.kt`
- [ ] `okhttp/src/main/java/okhttp3/internal/cache/DiskLruCache.kt`
- [ ] `okhttp/src/main/java/okhttp3/internal/cache2/Relay.kt`
- [ ] `okhttp/src/main/java/okhttp3/internal/connection/Exchange.kt`
- [ ] `okhttp/src/main/java/okhttp3/internal/connection/ExchangeFinder.kt`
- [ ] `okhttp/src/main/java/okhttp3/internal/connection/RealConnection.kt`
- [ ] `okhttp/src/main/java/okhttp3/internal/connection/Transmitter.kt`
- [ ] `okhttp/src/main/java/okhttp3/internal/http/CallServerInterceptor.kt`
- [ ] `okhttp/src/main/java/okhttp3/internal/http1/Http1ExchangeCodec.kt`
- [ ] `okhttp/src/main/java/okhttp3/internal/http2/Hpack.kt`
- [ ] `okhttp/src/main/java/okhttp3/internal/http2/Http2Connection.kt`
- [ ] `okhttp/src/main/java/okhttp3/internal/http2/Http2ExchangeCodec.kt`
- [ ] `okhttp/src/main/java/okhttp3/internal/http2/Http2Stream.kt`
- [ ] `okhttp/src/main/java/okhttp3/internal/http2/Huffman.kt`
- [ ] `okhttp/src/main/java/okhttp3/internal/platform/AndroidPlatform.kt`
- [ ] `okhttp/src/main/java/okhttp3/internal/ws/RealWebSocket.kt`
- [ ] `okhttp/src/main/java/okhttp3/internal/ws/WebSocketReader.kt`
- [ ] `okhttp/src/main/java/okhttp3/internal/ws/WebSocketWriter.kt`
- [ ] `okhttp/src/test/java/okhttp3/CallKotlinTest.kt`
- [ ] `okhttp/src/test/java/okhttp3/ConscryptTest.kt`
- [ ] `okhttp/src/test/java/okhttp3/internal/http/HttpDateTest.kt`

**Comment by swankjesse** [comment]
I don't think this approach works for us. The `!!` operator is necessary whenever the static type system lacks dynamic information.

**Comment by JakeWharton** [comment]
Moreover, these operations existed in the Java code already but were entirely implicit. Kotlin just forced you to make them explicit.

**Comment by monkey-mas** [comment]
Ah, sorry I didn't mean to (automatically) replace all the `!!`s from the files listed but I just wanted to figure out problematic Kotlin files where we use `!!` like we had an issue in #5280 .

Probably I'm missing something here. Please point me to the right direction! I'm happy to modify the similar issues :)
