### ISSUE TITLE
OpenSSLSocketImpl.startHandshake crash

### ISSUE THREAD

**Issue by treasure-lau** [square/okhttp#5286]
on some devices i get the crash below:

// the crash info

SIGABRT

#00 pc 00042364 /system/lib/libc.so (tgkill+12) [armeabi-v7a]
#01 pc 0004019d /system/lib/libc.so (pthread_kill+32) [armeabi-v7a]
#02 pc 0001c893 /system/lib/libc.so (raise+10) [armeabi-v7a]
#03 pc 00019af1 /system/lib/libc.so (__libc_android_abort+34) [armeabi-v7a]
#04 pc 000176b8 /system/lib/libc.so (abort+4) [armeabi-v7a]
#05 pc 0001b553 /system/lib/libc.so (__libc_fatal+16) [armeabi-v7a]
#06 pc 0001b56b /system/lib/libc.so (__fortify_chk_fail+18) [armeabi-v7a]
#07 pc 000462f5 /system/lib/libc.so (__FD_SET_chk+24) [armeabi-v7a]
#08 pc 000092eb /system/lib/libjavacrypto.so [armeabi-v7a]
java:
com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:324)
com.android.okhttp.internal.http.SocketConnector.connectTls(SocketConnector.java:103)
com.android.okhttp.Connection.connect(Connection.java:143)
com.android.okhttp.Connection.connectAndSetOwner(Connection.java:185)
com.android.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:128)
com.android.okhttp.internal.http.HttpEngine.nextConnection(HttpEngine.java:341)
com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:330)
com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:248)
com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:433)
com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:114)
com.android.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:245)
com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:218)
com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:25)
c.t.m.li.tsa.b.a(Unknown Source)
c.t.m.li.tsa.h.run(Unknown Source)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
java.lang.Thread.run(Thread.java:833)

**Comment by swankjesse** [comment]
Please report this to AOSP. Google includes an old version of OkHttp in Android, and that version is impacted.

**Comment by treasure-lau** [comment]
Thanks.

**Comment by zewenwang** [comment]
So, does anyone know if the problem has been solved? Or how to avoid the crash?

**Comment by yschimke** [comment]
Look for the AOSP bug, this isn't for this project.

**Comment by zewenwang** [comment]
OK，Thanks
