### ISSUE TITLE
use one client in many threads, cause much time_wait

### ISSUE THREAD

**Issue by noosc** [square/okhttp#5292]
Good bug reports include a failing test! Writing a test helps you to isolate and describe the problem, and it helps us to fix it fast. Bug reports without a failing test or reproduction steps are likely to be closed.

Here’s an example test to get you started.
https://gist.github.com/swankjesse/981fcae102f513eb13ed

create client like this.
```
OkHttpClient.Builder builder = new OkHttpClient.Builder()
                .readTimeout(config.getReadTimeout(), TimeUnit.MILLISECONDS)
                .writeTimeout(config.getReadTimeout(), TimeUnit.MILLISECONDS)
                .connectTimeout(config.getConnTimeout(), TimeUnit.MILLISECONDS)
                .sslSocketFactory(sslSocketFactory(), x509TrustManager())
                .addInterceptor(wrapper.getResponse());
return builder.build();
```

use the default connectionPool, then use the client to send request in 300 threads.

netstat -anp | grep ip | wc -l

found 1000+ time_wait connection

**Comment by noosc** [comment]
https://github.com/square/okhttp/blob/ed25f41e4823ade5f1017f07f729b0448dad10f4/okhttp/src/main/java/okhttp3/internal/connection/RealConnectionPool.kt#L143

that says, the connection that has been idle the longest if either it has exceeded the keep alive limit or the idle connections limit.

but I need a param to limit connection numbers. how could I achieve this goal? any suggestion is appreciated

**Comment by noosc** [comment]
![image](https://user-images.githubusercontent.com/12183250/61463059-40e62280-a9a6-11e9-87c1-27f8e580125e.png)
a connection is idle for 165170 ns is eligible to evict.

**Comment by swankjesse** [comment]
Please use StackOverflow for questions.
