### ISSUE TITLE
/system/lib/libssl.so (SSL_is_init_finished+7)

### ISSUE THREAD

**Issue by longxf** [square/okhttp#5303]
1 #00 pc 000194f4 /system/lib/libssl.so (SSL_is_init_finished+7) [armeabi-v7a]
--
2 #01 pc 000147cb /system/lib/libjavacrypto.so [armeabi-v7a]
3 #02 pc 0000f745 /system/lib/libjavacrypto.so [armeabi-v7a]
4 #03 pc 0003535f /system/framework/arm/boot-conscrypt.oat (oatexec+99167) [armeabi]
5 java:
6 com.android.org.conscrypt.SslWrapper.read(SslWrapper.java:384)
7 com.android.org.conscrypt.ConscryptFileDescriptorSocket$SSLInputStream.read(ConscryptFileDescriptorSocket.java:541)
8 okio.Okio$2.read(Okio.java:140)
9 okio.AsyncTimeout$2.read(AsyncTimeout.java:236)
10 okio.RealBufferedSource.request(RealBufferedSource.java:67)
11 okio.RealBufferedSource.require(RealBufferedSource.java:59)
12 okio.RealBufferedSource.readHexadecimalUnsignedLong(RealBufferedSource.java:297)
13 okhttp3.internal.http1.Http1Codec$ChunkedSource.readChunkSize(Http1Codec.java:466)
14 okhttp3.internal.http1.Http1Codec$ChunkedSource.read(Http1Codec.java:446)
15 okio.RealBufferedSource.read(RealBufferedSource.java:45)
16 okio.RealBufferedSource.exhausted(RealBufferedSource.java:55)
17 okio.InflaterSource.refill(InflaterSource.java:101)
18 okio.InflaterSource.read(InflaterSource.java:62)
19 okio.GzipSource.read(GzipSource.java:80)
20 okio.RealBufferedSource$1.read(RealBufferedSource.java:433)
21 java.io.InputStream.read(InputStream.java:101)
22 com.android.volley.toolbox.ResponseUtil.stream2Bytes(ResponseUtil.java:36)
23 com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:159)
24 com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:129)

most of crash in os 8.1.0

**Comment by yschimke** [comment]
This is a better question for stackoverflow, it's likely not reproducible for us outside of a specific hardware/os combo.  It looks like a problem with the underlying OS, not OkHttp.
