### ISSUE TITLE
OkHttp 4.0.1 javax.net.ssl.SSLHandshakeException: Handshake failed

### ISSUE THREAD

**Issue by Sergioct** [square/okhttp#5307]
Hello, I have updated to last version of OkHttp and is not working any api call. I am getting the following error from okhttp log: 

> HTTP FAILED: javax.net.ssl.SSLHandshakeException: Handshake failed

The next code is how i create OkHttpClient object:

https://gist.github.com/Sergioct/3996d91559caa69d02a9908d40660599

Thanks.

**Comment by Sergioct** [comment]
> 
> 
> Hello, I have updated to last version of OkHttp and is not working any api call. I am getting the following error from okhttp log:
> 
> > HTTP FAILED: javax.net.ssl.SSLHandshakeException: Handshake failed
> 
> The next code is how i create OkHttpClient object:
> 
> `fun getOkHttpClient(context: Context): OkHttpClient {
> val trustAllCerts = arrayOf(object : X509TrustManager {
> override fun checkClientTrusted(chain: Array, authType: String) {}
> 
> ```
>     override fun checkServerTrusted(chain: Array<X509Certificate>, authType: String) {}
> 
>     override fun getAcceptedIssuers(): Array<X509Certificate> =
>         arrayOf() // arrayOf(X509Certificate()[0])
> })
> 
> val trustManagerFactory = TrustManagerFactory.getInstance(TrustManagerFactory.getDefaultAlgorithm())
> trustManagerFactory.init(null as KeyStore?)
> val trustManagers = trustManagerFactory.trustManagers
> val trustManager = trustManagers[0] as X509TrustManager
> val sslContext = SSLContext.getInstance("SSL")
> sslContext.init(null, trustAllCerts, null)
> val sslSocketFactory = sslContext.socketFactory
> val hostnameVerifier = HostnameVerifier { hostname, _ -> hostname in BaseService.trustedHosts }
> 
> val builder = OkHttpClient.Builder()
> if (BuildConfig.DEBUG) {
>     val interceptor = HttpLoggingInterceptor()
>     interceptor.level = HttpLoggingInterceptor.Level.BODY
>     builder.addInterceptor(interceptor)
> }
> builder.addInterceptor(TokenInterceptor(context, DefaultLogManager(context)))
> builder.sslSocketFactory(sslSocketFactory, trustManager)
> builder.hostnameVerifier(hostnameVerifier)
> 
> return builder
>     .readTimeout(20, TimeUnit.SECONDS)
>     .writeTimeout(20, TimeUnit.SECONDS)
>     .connectTimeout(20, TimeUnit.SECONDS)
>     .build()
> ```
> 
> }`
> 
> Thanks.

**Comment by yschimke** [comment]
Please ask usage questions on stackoverflow. Search for similar questions there also. Sorry, but this is for reproducible bug reports.
