### ISSUE TITLE
NoSuchMethodError copyInto in TlsUtil

### ISSUE THREAD

**Issue by tir38** [square/okhttp#5308]
Running instrumentation tests with RESTMock we are getting this error

```
java.lang.NoSuchMethodError: No static method copyInto$default([Ljava/lang/Object;[Ljava/lang/Object;IIIILjava/lang/Object;)[Ljava/lang/Object; in class Lkotlin/collections/ArraysKt; or its super classes (declaration of 'kotlin.collections.ArraysKt' appears in /data/app/com.example.debug-1/base.apk)
FATAL EXCEPTION: pool-6-thread-1
Process: com.example.debug, PID: 6606
java.lang.NoSuchMethodError: No static method copyInto$default([Ljava/lang/Object;[Ljava/lang/Object;IIIILjava/lang/Object;)[Ljava/lang/Object; in class Lkotlin/collections/ArraysKt; or its super classes (declaration of 'kotlin.collections.ArraysKt' appears in /data/app/com.example.debug-1/base.apk)
	at okhttp3.tls.internal.TlsUtil.newKeyManager(TlsUtil.kt:84)
	at okhttp3.tls.HandshakeCertificates$Builder.build(HandshakeCertificates.kt:144)
	at io.appflate.restmock.SslUtils.localhost(SslUtils.java:49)
	at io.appflate.restmock.RESTMockServer.setUpHttps(RESTMockServer.java:91)
	at io.appflate.restmock.RESTMockServer.init(RESTMockServer.java:74)
	at io.appflate.restmock.RESTMockServerStarter$1.run(RESTMockServerStarter.java:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
```

This is the line in question https://github.com/square/okhttp/blob/master/okhttp-tls/src/main/java/okhttp3/tls/internal/TlsUtil.kt#L84

IIUC, Kotlin can treat a `varargs` as a Kotlin Array and then call extensions functions like [copyInto](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/copy-into.html)

We're on OkHttp 4.0.1, Kotlin 1.3.40, R8 1.5.41

Our test apk correctly contains `copyInto` method so I don't think it's a proguard/R8 issue:

<img width="713" alt="Screen Shot 2019-07-26 at 4 02 10 PM" src="https://user-images.githubusercontent.com/1980553/61978292-e1e46700-afbe-11e9-835d-96beb22f7457.png">

**Comment by yschimke** [comment]
This might be a better question for stackoverflow, can you post there and link back to this ticket?

**Comment by tir38** [comment]
done: https://stackoverflow.com/q/57330923/1650674
