### ISSUE TITLE
okhttp4.0    Cannot inline bytecode built with JVM target 1.8 into bytecode that is being built with JVM target 1.6

### ISSUE THREAD

**Issue by akingyin1987** [square/okhttp#5315]
okhttp4.0.1

**Comment by JakeWharton** [comment]
OkHttp builds with and targets Java 8 bytecode, and you will need to do the same.

See https://kotlinlang.org/docs/reference/using-gradle.html#compiler-options for configuring the compiler. You'll want to set `jvmTarget` to "1.8".
