### ISSUE TITLE
Build fails with RuntimeException when building from command line: 'Error injecting constructor'

### ISSUE THREAD

**Issue by criblecrable** [square/okhttp#5316]
Branch: master or latest release (parent-4.0.1)

Command: ./gradlew clean build

Error: 
> Task :mockwebserver:dokka FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':mockwebserver:dokka'.
> Guice provision errors:
  1) Error injecting constructor, java.lang.RuntimeException: Exception while loading package-list from ExternalDocumentationLinkImpl(url=https://square.github.io/okio/2.x/okio/jvm/index.html, packageListUrl=https://square.github.io/okio/2.x/okio/jvm/package-list)
    at org.jetbrains.dokka.ExternalDocumentationLinkResolver.<init>(ExternalDocumentationLinkResolver.kt:32)

Cause: Referencing a non-existing (404) page https://square.github.io/okio/2.x/okio/jvm/package-list

**Comment by swankjesse** [comment]
Might be caused by us doing multiplatform for Okio.

**Comment by yschimke** [comment]
I probably disabled this step in travis, so getting it back via CircleCI is more relevant.

**Comment by yschimke** [comment]
I believe this is already fixed.
