### ISSUE TITLE
Small read timeouts result in non-deterministic SocketTimeoutException messages

### ISSUE THREAD

**Issue by rain-on** [square/okhttp#5317]
Setup:
* Client using Okhttp to send delete request to a http server
* Server accepts TCP connection, but does not respond
* Client is configured with a small (~2ms) read timeout

The call to HttpRequest::newCall will throw a SocketTimeoutException (expected).
The message in the exception maybe either:
1. "timeout"
2. "Read timed out" 

The stack traces for these instances are different:
1. Stems from AsyncTimeout::newTimeoutException
2. Stems from the raw socket read operation.

It appears that when "2" occurs the AsyncTimer thinks it as already exited (though cannot say this with confidence), and thus does not wrap the exception in one generated by okhttp - and re-throws the original exception.

Replicated in 3.12.1, 3.13.1, and 4.0.1

**Comment by yschimke** [comment]
This is possibly more of an improvement.  I don't think we strictly consider the exception (class, message, cause, suppressions etc) to be public API you can depend on.  In both cases you should be getting an IOException.

**Comment by rain-on** [comment]
That is probably a fair statement - I was concerned that perhaps there was a race condition occurring somewhere between the timeout thread and the socket reading. Determinism can become hard when time is involved...

**Comment by swankjesse** [comment]
Yeah, the timeouts fire from wherever the execution is when the time elapses.

Any action to take here?
