### ISSUE TITLE
多个请求同时执行execute有时会多个请求都编程一个请求！

### ISSUE THREAD

**Issue by yuanfen7650** [square/okhttp#5320]
多个请求同时执行execute有时会多个请求都编程一个请求！
使用版本:3.11.0
不知道新版有没有修复！

**Comment by yuanfen7650** [comment]
测试后发现4.0.1还是有同样的问题！自己使用多线程，然后多个client.newCall(request).execute()同时执行，client是单列，就会出现多个请求最终请求同一个！

**Comment by yschimke** [comment]
Google Translation:

> 
After testing, I found that 4.0.1 still has the same problem! Use multi-threading yourself, then multiple client.newCall(request).execute() are executed at the same time, client is a single column, and multiple requests will appear and the same request will be the same!

You should probably ask this sort of question on a site like stackoverflow or equivelant.  If you want to report a bug, please make a reproducible test case before re-opening.
