### ISSUE TITLE
connection health check take 1 ms, make request slow

### ISSUE THREAD

**Issue by noosc** [square/okhttp#5321]
I 've asked a question on [stackoverflow](https://stackoverflow.com/q/57308220/11265297)

The connection check takes 1 ms, but my request only takes 5ms. So speed down 1/5.
Is it possible to add a config to disable the check?

**Comment by yschimke** [comment]
Thanks for raising in both places, it's useful on stackoverflow, but also a valid enhancement request.

We should probably consider this for https://github.com/square/okhttp/issues/4530

**Comment by yschimke** [comment]
No further action on this, if you are concerned about performance, adopting HTTP/2 is a good starting point.  But we don't want more tuning knobs.
