### ISSUE TITLE
OkHttpClient.Builder overrides with kotlin.time.Duration

### ISSUE THREAD

**Issue by JakeWharton** [square/okhttp#5322]
Once they're stable, or we could propagate their experimental nature with their experimental annotation.

**Comment by yschimke** [comment]
+1, but I think we should generally wait until they are stable.  I assume we hide from java?  

I think API usage by a common library like OkHttp, will result in user pain and in general experimental features probably don't compose well through transient libraries. Once they are broadly adopted but experimental, it's going to be an awkward upgrade no matter what.

**Comment by JakeWharton** [comment]
They're automatically hidden from Java since `Duration` is an `inline class`.

**Comment by yschimke** [comment]
Is this useful as an extension? Or does it mainly make sense when internal representation uses this and the legacy API is the converter?

We could stick useful extensions in okhttp-coroutines ( make it modern kotlin).

**Comment by JakeWharton** [comment]
An extension is okay, but putting it in a separate artifact doesn't really make sense.

**Comment by yschimke** [comment]
Does it still work with apiVersion if we land https://github.com/square/okhttp/pull/7267

Or do you prefer shading it like okio like your suggestion in https://github.com/square/okio/pull/960
