### ISSUE TITLE
Connecttimeout not honored

### ISSUE THREAD

**Issue by peterdk** [square/okhttp#5328]
We are experiencing issues with the OkHTTP connect timeout not being honored on a Pixel 3 device on Android 9.
We set it to 10 seconds in the builder, and when using that OkHTTP client and enabling AirPlane Mode, the request we issue will just hang forever.

```
private static OkHttpClient client = new OkHttpClient.Builder().connectTimeout(10, TimeUnit.SECONDS).build();
[..]
Response response = client.newCall(request).execute();
//Should continue here after 10s, but keeps hanging at this point.
if (response.body() != null) {
//do something
}
```

The weird thing is, it works ok with other devices, also on Android 9, and the emulator. 
The issue happens when in AirPlane mode, but also when just having no mobile network in a building. 

I tried testing the app with OkHTTP 4.0.1, 3.14.2, 3.12.1 and 3.4.1, all exhibit the same issue.

**Comment by peterdk** [comment]
It might be related to a VPN service we use, we discovered. But still, it's weird that the connection timeout is not enforced always somehow.

**Comment by yschimke** [comment]
So it's likely that we can connect to a VPN if it's exposed as a proxy on the localhost.  You can use the call, read and write timeouts to fix this.

**Comment by peterdk** [comment]
Ok, but the issue is, that when the VPN is enabled on Android, the call timeout does not get enforced. It's likely a issue with the VPN app itself, but I would expect OkHTTP to always enforce the call timeout even when it's internally waiting for some internal call to finish.

**Comment by yschimke** [comment]
@peterdk your example doesn't appear to set a call timeout, so that defaults to infinite.

**Comment by peterdk** [comment]
@yschimke Ok, sorry, I thought you were referring to the connect timeout. 
If I am not mistaken, the call timeout is for the whole call, including reading and writing? 
I only want to abort if the connection cannot be made in 10 seconds. When a connection is possible, I want to be able to load the data in max 2 minutes or so.

**Comment by yschimke** [comment]
Assuming we can connect a socket to the VPN, it isn't clear that OkHttp is doing something wrong here.

You could reproduce by adding a test to 

https://github.com/square/okhttp/blob/master/android-test/src/androidTest/java/okhttp/android/test/OkHttpTest.kt

**Comment by peterdk** [comment]
Ah ok, I understand now. OkHTTP connects to the VPN socket, to the connect timeout is not triggered. But the VPN internally just doesn't give a proper error, until after 5 minutes or so. That's indeed then not a OkHTTP issue.
