### ISSUE TITLE
Examples don't work in Kotlin with version 4

### ISSUE THREAD

**Issue by TidyIQ** [square/okhttp#5330]
I'm trying to follow the examples in the documentation to send a basic form POST request, however the documentation is outdated and doesn't work with Kotlin (after copy-pasting the example code into Android Studio and letting it auto-convert to Kotlin).

Please update the documentation to provide examples for how to use OkHttp version 4 with Kotlin. Here's the code I'm attempting that's failing:

```
    fun run() {
        val formBody = FormBody.Builder()
            .add("to", "+123456")
            .add("message", "Message content)
            .build()
        val request = Request.Builder()
            .url("https://myurl.com/post_route")
            .post(formBody)
            .build()

        client.newCall(request).execute().use { response ->
            if (!response.isSuccessful) throw IOException("Unexpected code $response")
            val body = response.body?.string();
            println(body)
            println("Success")
        }
    }
```

**Comment by yschimke** [comment]
Which example are you using?  https://square.github.io/okhttp/recipes/#posting-form-parameters ?

It looks like you left a " off this line

```
.add("message", "Message content)
```

**Comment by yschimke** [comment]
Separately, providing kotlin examples is probably inevitable.  But just secondary at the moment.

**Comment by yschimke** [comment]
reopen if it's not just the typo in quotes
