### ISSUE TITLE
Native Crash in okhttp 3.12.2

### ISSUE THREAD

**Issue by sandking** [square/okhttp#5331]
I got the crash on some devices

okhttp3.12.2

SIGABRT

1 #00 pc 0003d4e8 /system/lib/libc.so (tgkill+12) [armeabi-v8]
2 #01 pc 000164eb /system/lib/libc.so (pthread_kill+66) [armeabi-v8]
3 #02 pc 000170b7 /system/lib/libc.so (raise+10) [armeabi-v8]
4 #03 pc 000139a7 /system/lib/libc.so (__libc_android_abort+34) [armeabi-v8]
5 #04 pc 000120d8 /system/lib/libc.so (abort+4) [armeabi-v8]
6 #05 pc 00014ba3 /system/lib/libc.so (__libc_fatal+16) [armeabi-v8]
7 #06 pc 00014bbb /system/lib/libc.so (__fortify_chk_fail+18) [armeabi-v8]
8 #07 pc 00040f29 /system/lib/libc.so (__FD_SET_chk+24) [armeabi-v8]
9 #08 pc 0000ae15 /system/lib/libjavacrypto.so [armeabi-v8]
10 #09 pc 0000f845 /system/lib/libjavacrypto.so [armeabi-v8]
11 #10 pc 002f063f /data/dalvik-cache/arm/system@framework@boot.oat [armeabi]
12 java:
13 com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:307)
14 okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:320)
15 okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:284)
16 okhttp3.internal.connection.RealConnection.connect(RealConnection.java:169)
17 okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:257)
18 okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
19 okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
20 okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
21 okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
22 okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
23 okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
24 okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
25 okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
26 okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
27 okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
28 okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
29 okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
30 okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
31 okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:250)
32 okhttp3.RealCall.execute(RealCall.java:93)

**Comment by swankjesse** [comment]
There's not enough here to reproduce this issue. If you can help identify which devices are impacted, and perhaps provide a self contained test case, please open a new issue!

**Comment by fengqingxiuyi** [comment]
![image](https://user-images.githubusercontent.com/20492527/70605682-e8a20c80-1c35-11ea-86b0-54b62ad0598f.png)
how to solve this problem

**Comment by fengqingxiuyi** [comment]
version: okhttp3.12.0
