### ISSUE TITLE
Configure different Log Types for different Response Statuses in Okhttp-Logging-Interceptor

### ISSUE THREAD

**Issue by christophschnabl** [square/okhttp#5333]
Currently  4 log levels exist in OkhttpLogginginterceptor.Level. 
In an application with lots of request this could lead to very noisy log output. e.g. it would totally make sense to have just a Level.BASIC logging for all successful Requests and Responses and to log the whole Body for unsuccessful ones. Also it could be considered to have the possibility to log erroneous Requests on a Debug or Error LogLevel

**Comment by yschimke** [comment]
This comes up frequently, we generally advise people to copy and modify the OkhttpLogginginterceptor or the event listener and implement the functionality you need.  We are not intending an all purpose logging facility, and we don't want changes to surprise existing users.

**Comment by christophschnabl** [comment]
Okay thank you for the insight
