### ISSUE TITLE
Accessor for X509TrustManager

### ISSUE THREAD

**Issue by swankjesse** [square/okhttp#5336]
Would be handy to get one out of the OkHttpClient.

**Comment by yschimke** [comment]
Fixed here https://github.com/square/okhttp/pull/5339

**Comment by yschimke** [comment]
@swankjesse what do you think about exposing the SSLSessionContext at the same time? It's not a common API by any means, but for advanced usage (session management/invalidation, session values) it seems relevant to understand whether you are getting the benefits of session reuse etc.

```
@get:JvmName("x509TrustManager") val x509TrustManager: X509TrustManager?

@get:JvmName("sslSessionContext") val sslSessionContext: SSLSessionContext?
```

One counter point, if OkHttpClient is ever MPP, do you want X509TrustManager and SSLSessionContext as part of that API.

**Comment by yschimke** [comment]
A benefit of exposing TrustManager and SSLSessionContext for Conscrypt is that you can enable features like a persistent session cache.

    public static ConscryptHostnameVerifier getHostnameVerifier(TrustManager trustManager) {

    public static void setClientSessionCache(SSLContext context, SSLClientSessionCache cache) {

**Comment by JakeWharton** [comment]
MPP can still expose platform-specific APIs only on that platform. We do this for Okio and java.io stream types.

**Comment by swankjesse** [comment]
I’m closing this for the original issue which was blocking something internally at Square.

As for exposing SSLSessionContext and SSLContext, I’m on board. But all that stuff should be very easy if we want people to use it.

**Comment by swankjesse** [comment]
https://github.com/square/okhttp/issues/5352
