### ISSUE TITLE
Be more container friendly

### ISSUE THREAD

**Issue by yschimke** [square/okhttp#5341]
When shutting down OkHttpClient cleanly we should end up in a clean state within a reasonable time (< 1s?), e.g. no open sockets, files, backround threads (including daemon).

**Comment by yschimke** [comment]
See https://github.com/square/okhttp/pull/5334#issuecomment-520147914

**Comment by swankjesse** [comment]
And we should be able to attribute runaway threads to the tests that created em!

**Comment by yschimke** [comment]
https://github.com/square/okhttp/issues/5296#issuecomment-520165999

**Comment by yschimke** [comment]
I think this is covered by the TaskQueue changes.
