### ISSUE TITLE
Add test specifically for Session Resumption

### ISSUE THREAD

**Issue by yschimke** [square/okhttp#5342]
We should have a test designed to prove that session resumption works in JDK11+

re: https://github.com/square/okhttp/pull/5325#issuecomment-517806509

**Comment by yschimke** [comment]
Interesting page with nowhere else to post :) https://java.com/en/jre-jdk-cryptoroadmap.html

**Comment by yschimke** [comment]
Android is now tested.  But we should have some tests for desktop VMs.

**Comment by yschimke** [comment]
@swankjesse Any suggestions how to make a live status page? If it's an output of CI, I think we need it to combine results from multiple builds.

Going to close this as an open task, but I might try to make something that actually tells us what differences we have between platforms etc.  It seems really patchy on different JDKs.  Conscrypt just worked but only defaults to 10 sessions.  It also has a persistent cache API which we don't use or expose.

**Comment by swankjesse** [comment]
I’d actually prefer a static page with what we have test coverage for and encourage our users to use.
