### ISSUE TITLE
Compilation fails

### ISSUE THREAD

**Issue by tianshaokai** [square/okhttp#5350]
* What went wrong:
Execution failed for task ':mockwebserver:dokka'.
> Guice provision errors:
  
  1) Error injecting constructor, java.lang.RuntimeException: Exception while loading package-list from ExternalDocumentationLinkImpl(url=https://square.github.io/okio/2.x/okio/jvm/index.html, packageListUrl=https://square.github.io/okio/2.x/okio/jvm/package-list)
    at org.jetbrains.dokka.ExternalDocumentationLinkResolver.<init>(ExternalDocumentationLinkResolver.kt:32)
    at org.jetbrains.dokka.ExternalDocumentationLinkResolver.class(ExternalDocumentationLinkResolver.kt:32)
    while locating org.jetbrains.dokka.ExternalDocumentationLinkResolver
      for parameter 4 at org.jetbrains.dokka.DeclarationLinkResolver.<init>(DeclarationLinkResolver.kt:10)
    while locating org.jetbrains.dokka.DeclarationLinkResolver
      for parameter 0 at org.jetbrains.dokka.PackageDocs.<init>(PackageDocs.kt:20)
    at org.jetbrains.dokka.PackageDocs.class(PackageDocs.kt:19)
    while locating org.jetbrains.dokka.PackageDocs
  
  1 error

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

**Comment by TangHuaiZhe** [comment]
It seems that because we get a 404 response while access the resource  from url=https://square.github.io/okio/2.x/okio/jvm/index.html
But access https://square.github.io/okio/2.x/okio is ok.
Perhaps there is a problem in [square.github.io](https://square.github.io)

**Comment by yschimke** [comment]
Fixed in

```
commit 4739b278066c25de7d1fcada943e0aaddda7e7a7 (tag: parent-4.1.0)
Author: Jesse Wilson <jwilson@squareup.com>
Date:   Mon Aug 12 13:00:00 2019 -0400

    Prepare for release 4.1.0.
```
