### ISSUE TITLE
jdk8 with alpn broken tests

### ISSUE THREAD

**Issue by yschimke** [square/okhttp#5353]
https://circleci.com/gh/square/okhttp/4677#tests/containers/0
https://circleci.com/gh/square/okhttp/4689#tests/containers/0
https://circleci.com/gh/square/okhttp/4698#tests/containers/0
https://circleci.com/gh/square/okhttp/4723#tests/containers/0

```
Your job ran 140 tests with 2 failures

    duplexRequestsAreNotLogged - okhttp3.logging.HttpLoggingInterceptorTest

java.net.ProtocolException: Duplex connections are not supported for HTTP/1

secureGet - okhttp3.logging.LoggingEventListenerTest

java.lang.AssertionError: 
```

**Comment by yschimke** [comment]
Seems to be an issue with ALPN boot?

https://4677-5152285-gh.circle-artifacts.com/0/home/circleci/reports/okhttp-logging-interceptor/build/reports/tests/test/classes/okhttp3.logging.HttpLoggingInterceptorTest.html#duplexRequestsAreNotLogged

Warning: ALPN Boot not enabled
Aug 10, 2019 2:32:44 PM okhttp3.mockwebserver.MockWebServer$start$$inlined$execute$1 run

**Comment by yschimke** [comment]
Here's a 2 day old log from when we were definitely using alpn-boot

https://4673-5152285-gh.circle-artifacts.com/0/home/circleci/reports/okhttp-logging-interceptor/build/reports/tests/test/classes/okhttp3.logging.HttpLoggingInterceptorTest.html

**Comment by swankjesse** [comment]
OpenJDK vs. OracleJDK?

**Comment by yschimke** [comment]
AFAICT we run in circleci with OpenJDK 

```
testjdk8alpn:
    docker:
      - image: circleci/openjdk:8u171-jdk
```

The version map is specified against OpenJDK

https://github.com/jetty-project/jetty-alpn

> OpenJDK 8 version to ALPN version mapping

Is there an obvious fix?

**Comment by yschimke** [comment]
I'm reproducing locally, so something seems broken.  Hopefully just the gradle build, rather than code? 

With both

```
$ java -version
java version "1.8.0_65"
Java(TM) SE Runtime Environment (build 1.8.0_65-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.65-b01, mixed mode)
```

```
$ java -version
openjdk version "1.8.0_222"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_222-b10)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.222-b10, mixed mode)
```

**Comment by yschimke** [comment]
def alpnBootJar = configurations.testCompile.find { it.name.startsWith("alpn-boot-") }
      test {
        jvmArgs += "-Xbootclasspath/p:${alpnBootJar}"
      }

At this point alpnBootJar is null

**Comment by yschimke** [comment]
@swankjesse OK Tests are passing if I hardcode it, so don't let it block you.
