### ISSUE TITLE
Please provide a official jx-rs adapter :3

### ISSUE THREAD

**Issue by martyglaubitz** [square/okhttp#5360]
There is a Gist out there: https://gist.github.com/tbroyer/509aeae1e0738bcdd28a. But it would surely be nice to be able to pull it from Maven. Even better if the Adapter comes from the Makers of OkHttp :3

**Comment by yschimke** [comment]
This is better handled in either the higher level libraries (above http or websockets) that have dependencies on OkHttp, or in combination libraries.  There are simply too many combinations of libraries you could make.  So this is out of scope for OkHttp by default.

It would also tie us to release cycles of both projects.

Sorry.
