### ISSUE TITLE
Message received in onMessage(WebSocket webscoket, String message) callback is truncated in Android

### ISSUE THREAD

**Issue by NikhilKumarM** [square/okhttp#5361]
I am using okhttp3 library for creating a web socket client in my **android application**. Okhttp version is **4.0.1*.*
I have a web socket listener where I am receiving a message sent by the server using onMessage callback. When a large message is sent by the server, I see that the message received is truncated.

Client is receiving the message in **onMessage(WebSocket websocket, String messsage)** callback of web socket listener.

Is there any limit on the size of the message that is received by okhttp web socket connection. Is there a way to configure the message size?

I have noticed that the message is truncated on the client-side when the message sent by the server is greater than **4 kb**.
I thought that the message might be split if the message is large, but I don't see two callbacks being fired either. I only see one call back that has a truncated message.

**Comment by NikhilKumarM** [comment]
Android Log has a limit on buffer size. So when I am logging the message more than 4 kb, Android Log is truncating the message.

**Comment by yschimke** [comment]
Thanks for the update
