### ISSUE TITLE
🙉Attempt to read from field 'int com.android.okhttp.okio.Segment.limit' on a null object reference

### ISSUE THREAD

**Issue by JackLiaoJH** [square/okhttp#5367]
fabric receive :
`
com.android.okhttp.okio.Buffer.write + 1182 (Buffer.java:1182)
--
  | com.android.okhttp.okio.Buffer.read + 1221 (Buffer.java:1221)
  | com.android.okhttp.okio.RealBufferedSource.read + 65 (RealBufferedSource.java:65)
  | com.android.okhttp.internal.http.Http1xStream$FixedLengthSource.read + 602 (Http1xStream.java:602)
  | com.android.okhttp.internal.Util.skipAll + 172 (Util.java:172)
  | com.android.okhttp.internal.Util.discard + 154 (Util.java:154)
  | com.android.okhttp.internal.http.Http1xStream$FixedLengthSource.close + 619 (Http1xStream.java:619)
  | com.android.okhttp.okio.RealBufferedSource.close + 421 (RealBufferedSource.java:421)
  | com.android.okhttp.okio.RealBufferedSource$1.close + 409 (RealBufferedSource.java:409)
  | com.google.android.gms.internal.firebase_messaging.zzk.zza + 4 (zzk.java:4)
  | com.google.firebase.messaging.zzi.close + 37 (zzi.java:37)
  | com.google.firebase.messaging.zzb.zza + 51 (zzb.java:51)
  | com.google.firebase.messaging.FirebaseMessagingService.zzc + 59 (FirebaseMessagingService.java:59)
  | com.google.firebase.messaging.zzg.run + 2 (zzg.java:2)
  | java.util.concurrent.ThreadPoolExecutor.runWorker + 1167 (ThreadPoolExecutor.java:1167)
  | java.util.concurrent.ThreadPoolExecutor$Worker.run + 641 (ThreadPoolExecutor.java:641)
  | com.google.android.gms.common.util.concurrent.zza.run + 6 (zza.java:6)
  | java.lang.Thread.run + 764 (Thread.java:764)
`

Is firebase sdk  user okhttp?

**Comment by swankjesse** [comment]
That's an old Android version. Please report to the Android bug tracker.

**Comment by AlexeyGorovoy** [comment]
@swankjesse Can you elaborate please what you meant by the old Android version? I'm struggling with a similar issue and it's reported by Crashlytics for many devices on different Android versions starting from Marshmallow to up to Pie.

**Comment by yschimke** [comment]
"com.android.okhttp.okio.Buffer.read" indicates it is the fork of the code in AOSP.  Not a direct library use of okhttp that we can fix here.
