### ISSUE TITLE
Warning about Android private APIs

### ISSUE THREAD

**Issue by yschimke** [square/okhttp#5370]
Should we suppress? Or is there work to do here?

<img width="790" alt="image" src="https://user-images.githubusercontent.com/231923/63025454-eca16600-beb1-11e9-9956-39391d47aa0c.png">

**Comment by swankjesse** [comment]
Suppressing it or letting it warn are both okay with me. I think suppressing warnings to get a clean build is self-deception.

**Comment by yschimke** [comment]
If you enable warnings in the build, presumably you should fix or disable that warning.  Not choose linters that always spam or make you jump through hoops.  

BTW Intellij noticeably slows down when it decides you have hundreds of warnings in a single kotlin file.

**Comment by swankjesse** [comment]
I know which Kotlin file you’re referring to!
