### ISSUE TITLE
OkHttp Fails to set TLS V1.1 and v1.2 on IBM JDK 8

### ISSUE THREAD

**Issue by hijakebye** [square/okhttp#5372]
Extremely similar to https://github.com/square/okhttp/issues/4086 but applicable IBM JDK8

java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 8.0.5.20 - pxa6480sr5fp20ifix-20180809_01(SR5 FP20+IJ08001))
IBM J9 VM (build 2.9, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20180809_394103 (JIT enabled, AOT enabled)
OpenJ9   - cce432b
OMR      - 7ce4228
IBM      - 98805ca)
JCL - 20180719_01 based on Oracle jdk8u181-b12

We compile in 7 because half of our environments are in 7 and the other half are in 8 so we use the 3.12.3 library but noticed the issues is there in the latest 4.1 as well, just doesn't seem to work in IBM JDK8 given what's happening in the internal/platform package 
There's some logic in there that handles the JDK7 route but still leaves IBM JDK broken because the response differs from openjdk when calling SSLContext.getInstance("TLS")

```
  public SSLContext getSSLContext() {
    String jvmVersion = System.getProperty("java.specification.version");
    if ("1.7".equals(jvmVersion)) {
      try {
        // JDK 1.7 (public version) only support > TLSv1 with named protocols
        return SSLContext.getInstance("TLSv1.2");
      } catch (NoSuchAlgorithmException e) {
        // fallback to TLS
      }
    }

    try {
      return SSLContext.getInstance("TLS");
    } catch (NoSuchAlgorithmException e) {
      throw new IllegalStateException("No TLS provider", e);
    }
  }
```

After some remote debugging/troubleshooting discovered when it's establishing the connections is where the issue begins to arise the supported protocols is set to TLSv1 because of the above query to the JRE for supported/preferred TLS Setting 

Unable to find acceptable protocols. isFallback=false, modes=[ConnectionSpec(cipherSuites=[TLS_AES_128_GCM_SHA256, TLS_AES_256_GCM_SHA384, TLS_CHACHA20_POLY1305_SHA256, TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384, TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384, TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256, TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256, TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA, TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA, TLS_RSA_WITH_AES_128_GCM_SHA256, TLS_RSA_WITH_AES_256_GCM_SHA384, TLS_RSA_WITH_AES_128_CBC_SHA, TLS_RSA_WITH_AES_256_CBC_SHA, SSL_RSA_WITH_3DES_EDE_CBC_SHA], tlsVersions=[TLS_1_3, TLS_1_2], supportsTlsExtensions=true), ConnectionSpec()], supported protocols=[TLSv1]

**Comment by yschimke** [comment]
Can you use this workaround https://www.ibm.com/support/knowledgecenter/en/SSYKE2_8.0.0/com.ibm.java.security.component.80.doc/security-component/jsse2Docs/matchsslcontext_tls.html

```
com.ibm.jsse2.overrideDefaultTLS =[true|false]
```

What would you expect the logic on IBM JDKs to be?

**Comment by yschimke** [comment]
https://www.ibm.com/support/knowledgecenter/SSYKE2_8.0.0/com.ibm.java.security.component.80.doc/security-component/jsse2Docs/protocols.html

We can special case "SSL" on IBM JDKs or just require users set the system property.  Going to assume we ask users to set the system property for now.
