### ISSUE TITLE
expected http2 -> got http1.1 -> why? ( alvn correctly installed )

### ISSUE THREAD

**Issue by ogolovanov** [square/okhttp#5374]
Hi.

okhttp 3.14.2.
alvn "installed".

Problem: 
if i request yandex.ru -> it uses http1.1, not http2 as expected ( that host supports http2 and real browser uses it ).
if i request, for example, google.ru -> it uses http2 as expected.

How can that be possible?

Code is very simple:
```
httpClient.newCall(new Request.Builder().url("https://yandex.ru/").build()).execute(); // --> GET https://yandex.ru/ http/1.1
httpClient.newCall(new Request.Builder().url("https://www.google.ru/").build()).execute(); // --> GET https://www.google.ru/ h2
```

Debugger shows:

> ALPN | http/1.1
> Client Supported | [http/1.1, h2]
> Server Chosen | http/1.1

Thanks.

**Comment by swankjesse** [comment]
I got `h2` when I tried. Unclear what next action to take here.

**Comment by ogolovanov** [comment]
Hi.

Could you say whats your exact version of java + okhttp + alvn?

**Comment by ogolovanov** [comment]
My bad.

>> .protocols(Lists.newArrayList(Protocol.HTTP_2, Protocol.HTTP_1_1))
solves the problem -> ordering matters

sorry for disturbing you.

**Comment by ogolovanov** [comment]
Just FYI.

There is a bug, somewhere - okhttp, java, or alpn.

More info here: https://github.com/jetty-project/jetty-alpn/issues/28

Java <= 8u162 always gives expected response from https://www.yandex.ru/ ( code = 200 ).
Java >= 8u172 always gives unexpected response from https://www.yandex.ru/ ( code = 403 ).

Both requests are via http2, of course.
