### ISSUE TITLE
Rolling upgrade to okhttp 4.1.0 breaks due to backward in-compatible change

### ISSUE THREAD

**Issue by SElab2019** [square/okhttp#5376]
Hi,

The following code snippets throw an incompatible issue when I try to upgrade okhttp from 3.11.0 to 4.1.0.

```
@Test
public void test(){
	String userAgent = Version.userAgent();
}
```

Thanks.

**Comment by JakeWharton** [comment]
This class is in the internal package and is not subject to API compatibility. From Java I believe it's now exposed as a field.

**Comment by SElab2019** [comment]
Thank you. I just found internal package had been deleted.
