### ISSUE TITLE
add logging for arabic language

### ISSUE THREAD

**Issue by kldMohammed** [square/okhttp#5383]
i used latest version of Okhttp Logging interceptor
when i received JSON that represent Arabic language it looks like this

`"name":"\u0641\u0646\u062f\u0642 \u062a\u062c\u0631\u064a\u0628"`

please add support for encoding Arabic language

**Comment by swankjesse** [comment]
This isn’t OkHttp’s doing. Might be your JSON encoder to blame?

**Comment by kldMohammed** [comment]
When dealing with it in an android app it works fine , but in logcat appears like that
