### ISSUE TITLE
BrotliInterceptor V4.1.0

### ISSUE THREAD

**Issue by krishnameena** [square/okhttp#5384]
cannot resolve symbol BrotliInterceptor .

Please help how to get it working

**Comment by PascalSchumacher** [comment]
Did you add the okhttp-brotli dependency (https://search.maven.org/artifact/com.squareup.okhttp3/okhttp-brotli/4.1.0/jar)?

**Comment by krishnameena** [comment]
Yes but still not able to implement in java :

 ```
OkHttpClient client = new OkHttpClient.Builder()
                .addInterceptor(new BrotliInterceptor())
                .build();
```

It gives error that BrotliInterceptor() has private access

Please help how I can implement in java

**Comment by yschimke** [comment]
I’ll add an example. There is a singleton instance of it so use the static field.

**Comment by krishnameena** [comment]
Waiting for your reply

**Comment by yschimke** [comment]
@krishnameena Can you try following these instructions https://github.com/square/okhttp/pull/5391/files

**Comment by krishnameena** [comment]
Thanks it is working now
