### ISSUE TITLE
MockWebServer: Enqueue many

### ISSUE THREAD

**Issue by AOrobator** [square/okhttp#5392]
For instrumented tests on Android that go through multiple screens to test a user flow, I find myself enqueueing multiple requests so I get the following code:

```kotlin
server.enqueue(request1)
server.enqueue(request2)
server.enqueue(request3)
```

For convenience, I propose a method for syntactic sugar:

```kotlin
fun MockWebServer.enqueueMany(vararg responses: MockResponse) =
  responses.forEach { enqueue(it) }
```

Usage:

```kotlin
server.enqueueMany(request1, request2, request3)
```

Start by telling us what problem you’re trying to solve. Often a solution already exists!

Don’t send pull requests to implement new features without first getting our support. Sometimes we leave features out on purpose to keep the project small.

**Comment by swankjesse** [comment]
I think your utility method is fine. I don't want to add it to the library.
