### ISSUE TITLE
Okhttp overrides user-agent header

### ISSUE THREAD

**Issue by rodrigocasillas** [square/okhttp#5399]
Hello, we use "user-agent" header to add additional information to all requests going to our server. The issue is that Okhttp overrides user-agent header. In server logs we get this header <user-agent: okhttp/4.1.0>and not the original header, which is a problem for our implementation, is there a way to tell okhttp to avoid overriding this header?

*Note: This behavior is only with https requests.

Thanks in advance.

**Comment by kustraslawomir** [comment]
@rodrigocasillas I fixed it by removing default User-Agent header:

       fun getBuilder(chain: Interceptor.Chain, userAgent: String): Request.Builder {
        val originalRequest = chain.request()
   
        return originalRequest.newBuilder()
                .removeHeader("User-Agent")
                .addHeader("User-Agent", userAgent)
    }

**Comment by yschimke** [comment]
Could you please provide a reproducible test case.

```
fun main() {
  val client = OkHttpClient()

  val request = Request.Builder().url("https://httpbin.org/get").header("User-Agent", "XXX").build()
  val response = client.newCall(request).execute()
  
  println(response.body?.string())
}
```

```
{
  "args": {}, 
  "headers": {
    "Accept-Encoding": "gzip", 
    "Host": "httpbin.org", 
    "User-Agent": "XXX"
  }, 
  "origin": "80.7.252.32, 80.7.252.32", 
  "url": "https://httpbin.org/get"
}
```

**Comment by rodrigocasillas** [comment]
Thanks @kustraslawomir :)
