### ISSUE TITLE
UndeliverableException after update from 3.14.2 to 4.0.0

### ISSUE THREAD

**Issue by pawthunder** [square/okhttp#5401]
After updating okhttp to version 4.0.0 - 4.1.0 application crashes with UndeliverableException on devices running Android 10

Crash log:
![NoSuchMethod](https://user-images.githubusercontent.com/36672705/64016398-31bace80-cb27-11e9-95d4-26257fef0ece.png)

**Comment by yschimke** [comment]
com.apalon.android.network.OkHttpUtil is using private APIs from the internal package, these are not guaranteed to be stable across version upgrades.
