### ISSUE TITLE
 java.net.ProtocolException Expected leading 

### ISSUE THREAD

**Issue by liruibao** [square/okhttp#5411]
We are binary font file, the vera.ttf format file is encrypted, then at the time of network transmission through okhttp, broke the java.net.ProtocolException Expected leading [0-9 a - fA - f] character but  was 0x48 
![image](https://user-images.githubusercontent.com/29444771/64251951-3ed32580-cf4c-11e9-9c6b-7cc2d0e29e74.png)

![image](https://user-images.githubusercontent.com/29444771/64251770-d71cda80-cf4b-11e9-891f-f91ab6cac79d.png)

The same encryption is fine on iOS, so how do you fix it

**Comment by swankjesse** [comment]
Executable test case? 

Here’s an example test to get you started.
https://gist.github.com/swankjesse/981fcae102f513eb13ed
