### ISSUE TITLE
HttpLoggingInterceptor: faulty binary request/response detection 

### ISSUE THREAD

**Issue by DavidJRobertson** [square/okhttp#5412]
HttpLoggingInterceptor sometimes omits request/response bodies from logs if it thinks that it contains binary data. However, the `Buffer.isProbablyUtf8()` method doesn't reliably detect binary data, especially when the file format begins with a textual header.

This results in the logs being completely overwhelmed with useless binary data. For instance, this occurs frequently for me when uploading (10MB chunks of) mp4 video:
<img width="1969" alt="Screenshot 2019-09-04 at 15 01 28" src="https://user-images.githubusercontent.com/357772/64261780-f6ecd800-cf24-11e9-9ad8-05382e6e7f54.png">

Perhaps it would be better to examine the Content-Type and/or Content-Length headers first to see if we have a binary type or very large body, before falling back to `isProbablyUtf8()` if these headers are not present.

Alternatively, it might be worth making `isProbablyUtf8()` examine more than just the first 64 bytes / 16 UTF-8 code points before making a decision.

**Comment by yschimke** [comment]
Won't fix, this should probably be a separate project.  It's interesting enough on it's own, but a distraction for OkHttp.
