### ISSUE TITLE
Cached header combination dropping headers when repeated name present

### ISSUE THREAD

**Issue by thierryd** [square/okhttp#5413]
I have upgraded my project to Retrofit 2.6.1 and OkHttp 4.0.1
Everything seem to work, except when the server returns a 304. Retrofit can't seem to parse the response from the cache (it tries to parse an empty response).

Rolling back to Retrofit 2.5.0 and OkHttp 3.14.0 fix the issue.

**Comment by swankjesse** [comment]
@thierryd fantastic investigation. We’ll fix this ASAP and cut a patch release.
