### ISSUE TITLE
Release notes for 3.14.3 and 3.14.4

### ISSUE THREAD

**Issue by johnjohndoe** [square/okhttp#5435]
Can you please add the release notes for [`3.14.3`](https://github.com/square/okhttp/tree/parent-3.12.3) and [`3.14.4`](https://github.com/square/okhttp/tree/parent-3.12.4) in the [Changelog 3x](https://square.github.io/okhttp/changelog_3x/)?

**Comment by swankjesse** [comment]
Here you go!
https://square.github.io/okhttp/changelog_3x/#version-3124
https://square.github.io/okhttp/changelog_3x/#version-3123

**Comment by johnjohndoe** [comment]
Thank you. OMG :see_no_evil:
