### ISSUE TITLE
head after failed put breaks on upgrade from 3.10.0 to 3.14.2

### ISSUE THREAD

**Issue by ehennum** [square/okhttp#5447]
We have a test that executes the following sequence of actions

1. a PUT with a RequestBody that throws an IO exception during writeTo
2. a HEAD for the same URI

On 3.10.0, the HEAD request is sent over the wire as a HEAD request.

On 3.14.2 with no changes other than upgrading OkHttp in the build.gradle, 
the HEAD request is sent over the wire as a PUT request as detected both
by our HTTP server and by WireShark running on the client.

Could some state from the failed request be leaking into the subsequent request?

I tried to create a test to reproduce this issue but ran into a separate bug 
with MockWebServer. In the same situation, MockWebServer throws:

SEVERE: MockWebServer[32987] connection from localhost/127.0.0.1 crashed
java.lang.NumberFormatException: For input string: "HEAD /endpoint HTTP/1.1"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.base/java.lang.Integer.parseInt(Integer.java:652)
	at okhttp3.mockwebserver.MockWebServer.readRequest(MockWebServer.java:624)

The attached test reproduces the MockWebServer issue. If the MockWebServer issue is fixed, 
I hope the attached test will then reproduce the actual issue of interest.
  
[OkPutHeadTest.zip](https://github.com/square/okhttp/files/3602643/OkPutHeadTest.zip)

**Comment by swankjesse** [comment]
Looks like we’re incorrectly recycling a failed outbound HTTP/1 connection when the request body hasn’t been completely transmitted.

**Comment by yschimke** [comment]
Not sure this fix is in the right place, so putting it up as a strawman

https://github.com/square/okhttp/pull/5472

**Comment by yschimke** [comment]
@ehennum Thanks for the thorough test case, not ready to land a fix, but the test shows the problem well.
