### ISSUE TITLE
OkHttpClient reuse problems on Android Studio emulator and airplane mode.

### ISSUE THREAD

**Issue by Coderdreams** [square/okhttp#5448]
Steps to reproduce:

Emulators used: Nexus 5 with Android 6 or 9 (in 6 it's more consistent)

1) in online mode make a complete request (click "synchronous get")
      it will show "the provided value is invalid..." but it's a valid response
2) set airplane mode
3) attempt request again
     it will show "timeout" after some time instead of failing immediately

Expected result: since airplane mode is enabled I should receive the java.net.UnknownHostException immediately instead of a java.net.SocketTimeoutException

This only happens when reusing the OkHttpClient instance, if I create it with new everytime this problem doesn't happen, and so far I only observed it on the emulator, I don't have a real device around to reproduce it.

I can't avoid reusing the OkHttpClient instance since in the real project this is used there are a lot of configurations done to it and it's injected. 
Having a timeout though makes for a very bad user experience since we have the data cached and we could respond faster than waiting for the timeout if the user is in airplane mode.

[okhttptimeout.zip](https://github.com/square/okhttp/files/3602838/okhttptimeout.zip)

**Comment by swankjesse** [comment]
This is a bug in the Android emulator.

**Comment by Coderdreams** [comment]
Is this a known issue or just based on my report?

**Comment by swankjesse** [comment]
I've seen it before. Need to dig up the original bug report.

**Comment by Coderdreams** [comment]
Thank you, I wanted confirmation of this behavior since I don't have many real devices around to check for it. I see now that there always were problems with airplane mode in emulators not related to okhttp.
