### ISSUE TITLE
connect timeout set not work.

### ISSUE THREAD

**Issue by Clearlove9** [square/okhttp#5451]
Hi，i set connection timeout to 2 sec，use a fake address that can not connect，finally after 20 sec , i got the exception throwed. 

can someone explain it? thanks

**Comment by yschimke** [comment]
Please provide a reproduction that we can investigate.  It sounds like this is possible Dns timeout rather than connecting to the socket.

Alternatively could you attach output from a test using LoggingEventListener?

**Comment by Clearlove9** [comment]
![1](https://user-images.githubusercontent.com/26438979/64764072-e5827c00-d573-11e9-9f2d-cafd1ecb63de.png)

okhttp version：compile "com.squareup.okhttp3:okhttp:3.10.0"

**Comment by yschimke** [comment]
Please reopen if you can provide extra information showing it is definitely a bug (LoggingEventListener output) or a test reproduction.
