### ISSUE TITLE
ConnectionTimeout in android REST request

### ISSUE THREAD

**Issue by AndresHades** [square/okhttp#5454]
Im getting a timeout in android app, with the timeout set to 300 s. 
With an external REST tool, the same request take 10 millis.
The request returns a JSON, with one field including a Base64 encoded image.

Here is the code:

String urlFinal = restServiceHost+":"+restServicePort+"/"+table+filter;

        OkHttpClient client = null;

        OkHttpClient.Builder builder = new OkHttpClient.Builder();
        builder.connectTimeout(300, TimeUnit.SECONDS);
        builder.readTimeout(300, TimeUnit.SECONDS);
        builder.writeTimeout(300, TimeUnit.SECONDS);
        client = builder.build();

        Request request = new Request.Builder()
                .url(urlFinal)
                .build();

        try {
            Response response = client.newCall(request).execute();
            result = response.body().string();
        }catch (Exception ex) {
            ex.printStackTrace();
        }
        return result;

I can give you the real URL in private.

This code is executing in a async thread in android app, with the following library import:

implementation 'com.squareup.okhttp3:okhttp:4.2.0'

**Comment by yschimke** [comment]
I suggest asking for assistance on stackoverflow.  And look at using LoggingEventListener to see where delay is.

But this is not actionable, or scalable for us to help debug connections issues and similar without a confirmed bug reproduction.
