### ISSUE TITLE
missing files?

### ISSUE THREAD

**Issue by johannkaiser** [square/okhttp#5455]
While attempting to load OkHttp3, I continually got errors and decided to find source code and attempt to work out what was causing problems.

The file okhttp3.internal.toImmutableList is completely missing. It's only mentioned in imports and no where else. JvmName is also missing, but that may just be a dependency I missed.

Any help would be appreciated.

**Comment by yschimke** [comment]
Can you run the build locally and include the build failure. This is likely an issue with your setup, not the project. 

$ ./gradlew test

Please reopen once confirmed. But this is not a reproducible report. We run CI etc.
