### ISSUE TITLE
Improve/Fix visibility of sample recipes e.g. Certificate Pinning

### ISSUE THREAD

**Issue by z0rti** [square/okhttp#5458]
The docs on https://square.github.io/okhttp/https/#certificate-pinning
say:
```
public SSLContext sslContextForTrustedCertificates(InputStream in) {
    ... // Full source omitted. See sample.
  }

```
but there is no such sample.

https://github.com/square/okhttp/tree/master/samples/guide/src/main/java/okhttp3/recipes

**Comment by swankjesse** [comment]
https://github.com/square/okhttp/blob/master/samples/guide/src/main/java/okhttp3/recipes/CustomTrust.java

**Comment by swankjesse** [comment]
We could make the link more obvious? It’s the title.

**Comment by yschimke** [comment]
I’d also suggest also some (healthy) stackoverflow SEO. Post the specific permalinks to relevant existing or else new questions on stackoverflow etc.

**Comment by z0rti** [comment]
Sorry, i was just grepping for 'sslContextForTrustedCertificates' , after reading/trying out lots of outdated examples and it was late ;-)

Were there direct links to the samples yesterday?
'Certificate Pinning'
'Customizing Trusted Certificates'
I didn't notice them either (see lame excuses above)

Thanks anyways!
