### ISSUE TITLE
i have some problems about response.body().close()

### ISSUE THREAD

**Issue by yanyan20769** [square/okhttp#5463]
i write like this, but still got the error "A connection to XXX was leaked. Did you forget to close a response body? "

`
        
    @Retry
    public String getPageFromServer(String activityKey) throws Exception {
        String address = pageServerHolder.getServerAddressRandom();

        String url = MessageFormat.format(URL, address, activityKey);
        log.debug("=============== url [{}] ================", url);

        OkHttpClient client = new OkHttpClient().newBuilder().connectTimeout(60, TimeUnit.SECONDS).callTimeout(1, TimeUnit.SECONDS).build();
        final Request request = new Request.Builder().url(url).get().build();

        Response response = client.newCall(request).execute();

        try (ResponseBody body = response.body()) {
            if (response.isSuccessful() && null != body) {
                String bodyString = body.string();
                if (StringUtils.isNotBlank(bodyString)) {
                    body.close();
                    return bodyString;
                }
            }
        }
        throw new RuntimeException(MessageFormat.format("获取活动页信息异常，url [{0}], response.code [{1}]，response.message [{2}] ", url, response.code(), response.message()));
    }
`

**Comment by yschimke** [comment]
Please raise usage questions like this on stackoverflow, otherwise please provide a reproduction in the form of a runnable test so we can confirm and fix the bug report.
