### ISSUE TITLE
Parallel requests are not cached at once.

### ISSUE THREAD

**Issue by mansurrrr** [square/okhttp#5467]
When load three fragments from the viewpager and request http connection from each fragment simultaneously, Not all responses are cached at once.
After 4~5 requests, It cached and works.
Do I have to make all requests serialized?

**Comment by yschimke** [comment]
Usage questions like this should go to a site like stackoverflow.  If you can reproduce what you think is a bug, please provide a test that we can use to confirm the problem and the fix.

Unfortunately, our time doesn't scale to handling one of usage issues.

**Comment by swankjesse** [comment]
Also this: https://github.com/square/okhttp/issues/607
