### ISSUE TITLE
Auto reconnect sse like browser does

### ISSUE THREAD

**Issue by erlangparasu** [square/okhttp#5471]

**Comment by yschimke** [comment]
Seems like a sensible feature to add

See discussion including Last-Event-Id here

https://kaazing.com/kaazing.io/doc/understanding-server-sent-events/
https://www.html5rocks.com/en/tutorials/eventsource/basics/

**Comment by erlangp** [comment]
thanks sir @yschimke :+1:

**Comment by yschimke** [comment]
We should also cleanup 

```
  /**
   * TODO description.
   *
   * No further calls to this listener will be made.
   */
  open fun onClosed(eventSource: EventSource) {
  }
```

**Comment by erlangp** [comment]
```kotlin
open fun onClosed(eventSource: EventSource): Boolean {
    return true // To retry ?
}
```

**Comment by erlangp** [comment]
https://github.com/square/okhttp/blob/aad8a1420d8f22a35138b92d7ecc14efc96155fe/okhttp-sse/src/main/java/okhttp3/internal/sse/RealEventSource.kt#L105

**Comment by erlangp** [comment]
hello sir.. other lib that provide auto retry: https://github.com/heremaps/oksse

**Comment by yschimke** [comment]
It's not currently in development, or confirmed on the near term roadmap. Sorry.
