### ISSUE TITLE
Get paid CI account

### ISSUE THREAD

**Issue by yschimke** [square/okhttp#5476]
CircleCI is great, but github actions is getting great feedback.  Seems roughly similar in complexity.

https://github.com/bodil/im-rs/commit/1aeec1b7f78ea958c21581fe5a660e69eebc4d08

It would be good to make a deliberate call on which is the right long term platform.  Square org members should probably drive that. Is this being discussed across the projects?

**Comment by yschimke** [comment]
For context, two changes I may work on would be affected

- JDK9 build and JDK8 test run 
- run headless android emulator and run android tests

**Comment by yschimke** [comment]
Build output https://github.com/bodil/im-rs/runs/228998957

**Comment by yschimke** [comment]
@swankjesse Overall, this feels like it should follow whatever Square folk decide.

Can you speak to long term direction?

- TravisCI vs CircleCI vs Github Actions?
- Publishing snapshots and tagged releases

Or example projects that are further along?

**Comment by swankjesse** [comment]
Internally we have our own CI system that works quite well. This means that for open source I need to do my own research here, and potentially get our other OSS projects on the same plan.

My personal preference is CircleCI. But I’ll need to make the case and possibly get a paid account expensed.

**Comment by yschimke** [comment]
@swankjesse That's great to know.  Is it fair to say you think you would pick up any obvious "clangers" for Android support on snapshots prior to public release?  I've been working towards better public CI coverage and general testing for Android, because for me at least it was always a lot of work to test e.g. fixing Android socket support.  Hence the instrumentation unit tests, which are quick to run manually with a local emulator.

**Comment by yschimke** [comment]
Douche move assigning to @swankjesse but honestly noone else can do it and it may not be CircleCI anyway.  To be determined which way Square as an org go.
