### ISSUE TITLE
HttpUrl host validation could be more strict

### ISSUE THREAD

**Issue by swankjesse** [square/okhttp#5488]
It permits the following invalid domains:

```
abc.12c
foo-.com
_bar.quux
foo+bar.com
foo!bar.com
a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.com
aaaaa.aaaaa.aaaaa.aaaaa.aaaaa.aaaaa.aaaaa.aaaaa.aaaaa.aaaaa.aaaaa.aaaaa.aaaaa.aaaaa.aaaaa.aaaaa.aaaaa.aaaaa.aaaaa.aaaaa.aaaaa.aaaaa.aaaaa.aaaaa.aaaaa.aaaaa.aaaaa.aaaaa.aaaaa.aaaaa.aaaaa.aaaaa.aaaaa.aaaaa.aaaaa.aaaaa.aaaaa.aaaaa.aaaaa.aaaaa.1234567890.c.c
```

**Comment by swankjesse** [comment]
Found via:
https://github.com/google/guava/blob/master/guava-tests/test/com/google/common/net/InternetDomainNameTest.java

**Comment by JoelLau** [comment]
@swankjesse would applying [the InetAddressValidator from Apache Commons](http://commons.apache.org/proper/commons-validator/apidocs/org/apache/commons/validator/routines/InetAddressValidator.html) help ?

**Comment by yschimke** [comment]
Also related https://github.com/square/okhttp/issues/5840

**Comment by yschimke** [comment]
These are awkward, any impedence with JDK or Android handling is likely to be an issue.  Generally it's asking for trouble to be the strictest out of 

a) general practice (chrome, firefox, domain registrars)
b) Android
c) JDK

Suggesting we close.
