### ISSUE TITLE
Top private domain matches unexpected TLDs

### ISSUE THREAD

**Issue by swankjesse** [square/okhttp#5489]
Guava’s implementation says that if a domain is not registered it cannot have a top private domain. OkHttp treats any unknown suffix as a top private domain.

```
    assertNull(HttpUrl.parse("https://foo.www/").topPrivateDomain());
```

**Comment by swankjesse** [comment]
Found via
https://github.com/google/guava/blob/master/guava-tests/test/com/google/common/net/InternetDomainNameTest.java

**Comment by MartinDevi** [comment]
Could it be worth including in the library the [IANA TLD list](https://www.iana.org/domains/root/db) ([raw](https://data.iana.org/TLD/tlds-alpha-by-domain.txt)) to match against?

I'm not 100% sure whether this fixes the issue that you're reporting, but I think it could be useful to check whether the top level domain is registered, and therefore whether the top private domain is "credible".

**Comment by swankjesse** [comment]
I don’t really want to ship more data that gets stale over time. It creates mysterious reasons for things to not work, especially long in the future when OkHttp is a distant implementation detail of something.

**Comment by MartinDevi** [comment]
That's fair, but I figured that since Mozilla's Public Suffix List is already included, it might make sense to have this as well, since I get the impression that its data is less volatile.

**Comment by swankjesse** [comment]
I think it’s mostly just how the failure modes work.

If we’re strict about TLDs for top-private domains, then when a new TLD is introduced you can’t set cookies on it without an OkHttp update. I don’t like that.

**Comment by swankjesse** [comment]
Closing, no action planned here.
