### ISSUE TITLE
H2_PRIOR_KNOWLEDGE is not working

### ISSUE THREAD

**Issue by mohamedanees6** [square/okhttp#5498]
I am using OkHttp-4.2

```
return new OkHttpClient.Builder()
				.connectionPool(new ConnectionPool(maxIdleConnections, keepAliveDurationInMillis, TimeUnit.MILLISECONDS))
				.readTimeout(socketTimeout, TimeUnit.SECONDS).connectTimeout(connectTimeout, TimeUnit.SECONDS).build();
```

Is working fine, but the protocol used is HTTP1.1 (I checked `Protocol` in the `Response`).

But, I know the server supports h2c. Here is the curl response,

> curl -v --http2 <http://xxx.com:9080>

> Connection: Upgrade, HTTP2-Settings
> Upgrade: h2c

If I change my `Protocol` to `Protocol.H2_PRIOR_KNOWLEDGE`, it is not working.

Here is how I am building
```
return new OkHttpClient.Builder()
				.connectionPool(new ConnectionPool(maxIdleConnections, keepAliveDurationInMillis, TimeUnit.MILLISECONDS))
				.readTimeout(socketTimeout, TimeUnit.SECONDS).connectTimeout(connectTimeout, TimeUnit.SECONDS).protocols(Arrays.asList(Protocol.H2_PRIOR_KNOWLEDGE)).build();

```

The exception reads as

> okhttp3.internal.http2.ConnectionShutdownException 
> at okhttp3.internal.http2.Http2Connection.newStream(Http2Connection.java:248)
> at okhttp3.internal.http2.Http2Connection.newStream(Http2Connection.java:231)
> at okhttp3.internal.http2.Http2Codec.writeRequestHeaders(Http2Codec.java:117)

Any reasons why this might be happening?

**Comment by swankjesse** [comment]
These are different mechanisms.

Prior knowledge requires the server accept HTTP/2 frames immediately with no HTTP/1 back and forth beforehand.

This server supports HTTP/2 upgrade negotiation over plaintext. OkHttp does not support HTTP/2 without HTTPS or prior knowledge.

Does Chrome or Firefox negotiate HTTP/2?

**Comment by mohamedanees6** [comment]
Can you suggest some alternates in Java where I can make HTTP/2 Requests for h2c?

**Comment by swankjesse** [comment]
Let's finish here.
https://stackoverflow.com/questions/58115718/enabling-http-2-on-the-plain-text-connector
