### ISSUE TITLE
Upgrading to OkHttp 4.20 from 3.11.0 (cannot access url it is public/*package*/ in Request)

### ISSUE THREAD

**Issue by RoudyK** [square/okhttp#5505]
This is my build.gradle

```
apply plugin: 'kotlin'

dependencies {
    def dependencies = rootProject.ext.repositoryDependencies
    def testDependencies = rootProject.ext.repositoryTestDependencies

    implementation project(":domain")

    implementation dependencies.kotlin
    implementation dependencies.moshi
    implementation dependencies.rxJavaAdapter
    implementation dependencies.okHttp3
    implementation dependencies.jodaTime
    testImplementation testDependencies.okHttpMock
    testImplementation testDependencies.okHttp3
}

sourceCompatibility = "1.8"
targetCompatibility = "1.8"

compileKotlin {
    kotlinOptions {
        jvmTarget = "1.8"
    }
}
compileTestKotlin {
    kotlinOptions {
        jvmTarget = "1.8"
    }
}

compileJava {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}
```

Kotlin version:
`  kotlin              : "org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.3.50,`

Okhttp3 version:
`okHttp3                 : "com.squareup.okhttp3:okhttp:4.2.0,`

Failing method:
```
fun OkHttpClient.Builder.addQueryParameterInterceptor(name: String, value: String): OkHttpClient.Builder {
    addInterceptor {
        var request = it.request()
        val url = request.url.newBuilder().addQueryParameter(name, value).build()
        request = request.newBuilder().url(url).build()
        it.proceed(request)
    }
    return this
}
```

Using `url()` is deprecated in `Request` and suggests using the val `url`.

However building with `request.url.etc` I get `cannot access url it is public/*package*/ in Request`

I looked at the migration guide and changed the java compatibility to 1.8.

Thank you for the help.

**Comment by swankjesse** [comment]
Do you have two copies of OkHttp on your classpath?

**Comment by RoudyK** [comment]
Hello, @swankjesse, no only one copy of OkHttp3, if you mean this line: `testImplementation testDependencies.okHttp3` I removed it and tried and still get the error. One is `implementation` while the other is `testImplementation`. However, other than those, there isn't any other copy of okhttp, I also removed the `testImplementation` one so there is only one implementation is the build.gradle. 

Here's a screenshot of the error I am getting:

![url](https://user-images.githubusercontent.com/22520376/65778547-774fd300-e189-11e9-9760-ae68412eeba3.png)

**Comment by swankjesse** [comment]
Strange. You’re absolutely sure you don’t have another OkHttp version on your classpath somewhere? I can’t think of any other explanations.

**Comment by RoudyK** [comment]
Hello, @swankjesse, I just figured out the problem. It seems one of the libraries I was using (Our own library) was using a different version of okhttp3 and even though I'm explicitly specifying 4.2.0 in this module's build.gralde, it was using the library's version of okhttp3. I upgraded both to 4.2.0 and now everything works fine.

Thank you for the help, did direct me in the right direction.
