### ISSUE TITLE
Protocol Upgrade Mechanism in okHttp Interceptors

### ISSUE THREAD

**Issue by mohamedanees6** [square/okhttp#5514]
I need to upgrade my request from being served by HTTP1.1 to HTTP/2. This is so far what I have tried.

```
public class H2cUpgradeRequestInterceptor implements Interceptor {
    private static final Log logger = LogFactory.getLog(H2cUpgradeRequestInterceptor.class);
    @Override
    public Response intercept(Chain chain) throws IOException {
        Request request = chain.request();
        Request upgradeRequest = request.newBuilder().addHeader("Connection", "Upgrade, HTTP2-Settings")
                .addHeader("Upgrade", "h2c").addHeader("HTTP2-Settings", "AAMAAABkAARAAAAAAAIAAAAA").build();
        Response upgradeResponse = chain.proceed(upgradeRequest);
        if (upgradeResponse != null && upgradeResponse.code() == HttpStatus.SC_SWITCHING_PROTOCOLS) {
            logger.debug("Switching Protocols success"); // Success. Got 101 in reply.
        }
        Response response = chain.proceed(request);
        if (response.protocol() == Protocol.HTTP_2) { // This is returning HTTP1.1 as protocol
            logger.debug("Used upgraded h2c protocol");
        }
        return response;
    }
    }
```
My server has h2c enabled. I am also receiving 101 Switching Protocols in my first chain.proceed() call. But the next proceed() always gives me HTTP1.1 as protocol even if switching protocols is successful. Is it right right way of achieving protocol upgrade through okhttp? Or a kind of bug?

**Comment by swankjesse** [comment]
Tracking here:
https://stackoverflow.com/questions/58066881/java-net-protocolexception-unexpected-end-of-stream-implementation-com-square

**Comment by swankjesse** [comment]
Tracking here:
https://stackoverflow.com/questions/58163115/protocol-upgrade-mechanism-in-okhttp-interceptors

**Comment by swankjesse** [comment]
Please use StackOverflow for usage questions.

**Comment by mohamedanees6** [comment]
I wasn't sure if it is a bug/ I was using it unwittingly! :disappointed:
