### ISSUE TITLE
callEnd and responseBodyEnd methods are not called for EventListener

### ISSUE THREAD

**Issue by bantyK** [square/okhttp#5516]
When using the asynchronous call with ResponseCallback, the callEnd and responseBodyEnd callbacks are not triggered. But Callback's onResponse is getting triggered
    
    val client = OkHttpClient.Builder()
    .eventListenerFactory(HttpEventListenerFactory.FACTORY)
     .build()

    val request = Request.Builder()
        .url("http://jsonplaceholder.typicode.com/comments?postId=1")
        .build()

     with(client) {
         newCall(request).enqueue(object : Callback {
            override fun onFailure(call: Call, e: IOException) {
                Log.d("OkHttp##", "Request failed")
            }

            override fun onResponse(call: Call, response: Response) {
                //this is getting triggered
                Log.d("OkHttp##", "Response received")
            }
        })
      }

**EventListener class**
    
       public class HttpEventListenerFactory extends EventListener {

    public static final Factory FACTORY = new Factory() {
        final AtomicLong nextCallId = new AtomicLong(1L);

        @Override
        public EventListener create(Call call) {
            long callId = nextCallId.getAndIncrement();
            Log.d("OkHttp##", "next call id : " + nextCallId);
            String message = String.format(Locale.US, "%04d %s%n", callId, call.request().url());
            Log.d("OkHttp##", message);
            return new HttpEventListenerFactory(callId, System.nanoTime());
        }
    };

    @Override
    public void responseBodyEnd(Call call, long byteCount) {
        // this method never gets called
        printEvent("Response body end", callId);
    }

**Comment by yschimke** [comment]
It doesn't look like you are consuming the response body and then closing it.  This is likely the problem.

**Comment by bantyK** [comment]
What do you suggest I should do in my code to get the responseBodyEnd callback ?

**Comment by yschimke** [comment]
> What do you suggest I should do in my code to get the responseBodyEnd callback ?

Read the body and then close the response?

**Comment by bantyK** [comment]
Thank you @yschimke. It worked.
