### ISSUE TITLE
Too many NullProxySelector instances break connection pooling

### ISSUE THREAD

**Issue by swankjesse** [square/okhttp#5519]
We observed clients not pooling connections because although they shared a connection pool, they had different instances of NullProxySelector.

**Comment by yschimke** [comment]
Which version did this start?  :(

**Comment by swankjesse** [comment]
The SecurityManager managed to cause this! It's the worst.
https://github.com/square/okhttp/pull/5332

**Comment by yschimke** [comment]
My bug.  ultimately NullProxySelector could have been a singleton, it is now.  Or had equality defined, it essentially does not via ==.  

Thanks!

**Comment by yschimke** [comment]
The meta comment is we should be able to detect these regressions through stats, so hopefully with load balancing changes we would notice.
