### ISSUE TITLE
Forcing to use Java 7

### ISSUE THREAD

**Issue by shailendrarao** [square/okhttp#5523]
Facing issue to use this in dependency in Android Studio. If we have Java 8 then this dependency is a dead lock for any developer. I struggled for two days to use this but failed. What i observed is that build is successful but when we try to run the Application using this dependency then its failing to convert byecode to dex, which is must for android also dex cannot parse 52 byte code.  Due to this we are getting Runtime error while we run the application.

**Comment by yschimke** [comment]
which version are you running?  Can you provide a reproduction we can test against? e.g. a sample github android project?

I'm using Android Studio without issue with both released version and snapshots, so I'd like to understand whats wrong.

Without a reproducible issue, you might need to ask advice on stackoverflow, we may not be able to help.  And with the reproduction it could ultimately be either OkHttp bug, a build issue with your code or an Android Studio bug.
