### ISSUE TITLE
Race condition causes retry loop?

### ISSUE THREAD

**Issue by swankjesse** [square/okhttp#5547]
https://github.com/square/okhttp/pull/2179#issuecomment-539877107

> I found this patch may cause endless loop:
> 
> 1. on a mobile phone, user sends one request, in function StreamAllocation::findHealthyConnection(), it returns a candidate
> 2. if this candidate successCount is 0, it is returned without health check (candidate.isHealthy())
> 3. switch the phone's netowrk from 4G to wifi, so the socket is broken, the candidate is unhealthy.
> 4. to send request, SocketException(socket is closed) is thrown to RetryAndFollowUpInterceptor, and will have one more retry.
> 5. StreamAllocation::findHealthyConnection() returns the same candidate.
     ...
     so it causes endless loop.

**Comment by yschimke** [comment]
My main interest is whether we would detect this with anyone using the LoggingEventListener?  Bugs happen, do we make it easy to report and diagnose after the fact?

BTW in practice, switching phone network from 4G to Wifi doesn't break the existing 4G connections on standard Android phones.  It's perfectly valid to choose between a 4G and Wifi network using interface binding on the socket. See [OkHttpAndroidApp/.../AndroidNetworkManager.kt](https://github.com/yschimke/OkHttpAndroidApp/blob/master/android/app/src/main/java/ee/schimke/okhttp/android/factory/AndroidNetworkManager.kt#L212)

**Comment by tankjj** [comment]
> My main interest is whether we would detect this with anyone using the LoggingEventListener? Bugs happen, do we make it easy to report and diagnose after the fact?
> 
> BTW in practice, switching phone network from 4G to Wifi doesn't break the existing 4G connections on standard Android phones. It's perfectly valid to choose between a 4G and Wifi network using interface binding on the socket. See [OkHttpAndroidApp/.../AndroidNetworkManager.kt](https://github.com/yschimke/OkHttpAndroidApp/blob/master/android/app/src/main/java/ee/schimke/okhttp/android/factory/AndroidNetworkManager.kt#L212)

On my android phone(xiaomi MIX 2, OS is android 8.0), switch 4G to Wifi, it will break the connection, I checked the rawSocket of the connection, it is closed. If you do the health check, it'll also return false.

**Comment by yschimke** [comment]
@tankjj thanks. I wonder if it’s Android 9 (Nokia 7.1) or it depends on whether you explicitly bind to a network?

**Comment by tankjj** [comment]
@yschimke I don't test on Android 9. My device is xiaomi MIX2, android 8.0. And it doesn't depend on binding to a network.

**Comment by yschimke** [comment]
@tankjj Yep, I am testing with Android 9.  And when I switch to Wifi, existing connections over 4G are not lost.  Particularly if they have traffic or pings.
