### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by brendanw** [square/okhttp#5548]
Reproduction steps:

1. Make the below Activity
```
class MainActivity : AppCompatActivity() {

  @SuppressLint("CheckResult")
  override fun onCreate(savedInstanceState: Bundle?) {
    super.onCreate(savedInstanceState)
    setContentView(R.layout.activity_main)
    val cache = Cache(File(cacheDir, "okhttp-cache"), 10 * 1024 * 1024)
    val client = getUnsafeOkHttpClientBuilder()
        .cache(cache)
        .addInterceptor(HttpLoggingInterceptor().setLevel(HttpLoggingInterceptor.Level.BODY))
        .build()
    Completable.fromCallable {
      var i = 0
      while (i < 50) {
        Log.d("MainActivity", "requesting video")
        val request = Request.Builder().url("https://d1e3r4xclxgbvg.cloudfront.net/united-states-paria-canyon-0.webm")
            .build()
        val file = File("${applicationContext.filesDir}/$i.webm")
        client.newCall(request).execute().use { resp ->

        }
        Log.d("MainActivity", "loop iteration")
        i++
      }
    }.subscribeOn(Schedulers.io()).observeOn(AndroidSchedulers.mainThread()).subscribeBy(onError = {

    })
  }

  private fun getUnsafeOkHttpClientBuilder(): OkHttpClient.Builder {
    // Create a trust manager that does not validate certificate chains
    val trustAllCerts = arrayOf<TrustManager>(object : X509TrustManager {
      override fun checkClientTrusted(chain: Array<out X509Certificate>?, authType: String?) {
      }

      override fun checkServerTrusted(chain: Array<out X509Certificate>?, authType: String?) {
      }

      override fun getAcceptedIssuers() = arrayOf<X509Certificate>()
    })

    // Install the all-trusting trust manager
    val sslContext = SSLContext.getInstance("SSL")
    sslContext.init(null, trustAllCerts, java.security.SecureRandom())
    // Create an ssl socket factory with our all-trusting manager
    val sslSocketFactory = sslContext.socketFactory

    return OkHttpClient.Builder()
        .sslSocketFactory(sslSocketFactory, trustAllCerts[0] as X509TrustManager)
        .hostnameVerifier(HostnameVerifier { _, _ -> true })
  }
}
```

2. Launch the activity

Observed: We see the below log repeated for each loop iteration
```
D/MainActivity: loop iteration
D/MainActivity: requesting video
W/System: A resource failed to call close. 
```
Expected: We should not see the log "A resource failed to call close".

As a user I can fix this by using an OkHttpClient without the custom ssl configuration.

**Comment by yschimke** [comment]
It's not clear why the custom SSL would cause it to leak.  It looks more likely that the custom insecure SSL config is allowing the request to succeed, and you are just not seeing the errors because of your deliberately empty error handler.

For a reproducible bug report, you could either make a junit test outside of Android, or looks at tests in the android-test directory for OkHttp.

Please raise this sort of request on stackoverflow.

**Comment by brendanw** [comment]
@yschimke No error is getting propagated from OkHttp. You can clone and run the test from this repository. Is it possible to write a junit test that checks logcat logs?

https://github.com/brendanw/memleak/blob/master/app/src/main/java/com/basebeta/okhttpleak/MainActivity.kt

![image](https://user-images.githubusercontent.com/585321/66719256-4fc05380-eda2-11e9-9fcf-cf8abbe702fe.png)

**Comment by swankjesse** [comment]
You must close the response returned by 

client.newCall(request).execute()

**Comment by brendanw** [comment]
Sorry! I removed the `use { }` call while looking through this morning. I added it back in, ran the test again, and still see `A resource failed to call close` only with the insecure ssl configuration. Pushed the update to https://github.com/brendanw/memleak

![image](https://user-images.githubusercontent.com/585321/66722674-907d9400-edc5-11e9-943c-de99305201be.png)
