### ISSUE TITLE
Okhttp blocks all requests while big request is pending

### ISSUE THREAD

**Issue by bolds07** [square/okhttp#5556]
I know this isn't the best place to ask it, but since i couldn't get any support on starckoverflow and i'm struggling with this problem over a week i'm going to ask here, maybe is something very simple that a person with more experience handle fast.

I'm using OkHttp + Retrofit2 to build an api to a third party system.
I've noticed that even using a ConnectionPool and multiple threads, Retrofit is never making simultaneous calls.

This is how i create the service:

```
OkHttpClient.Builder httpClientBuilder = new OkHttpClient.Builder();
httpClientBuilder.connectionPool(new ConnectionPool(7, 1, TimeUnit.MINUTES););
Dispatcher dispatcher = new Dispatcher();
dispatcher.setMaxRequests(10);
dispatcher.setMaxRequestsPerHost(10);
httpClientBuilder.dispatcher(dispatcher);
OkHttpClient okhttp = httpClientBuilder.build();
this.service = new Retrofit.Builder().baseUrl(API_URL).addConverterFactory(GsonConverterFactory.create(getGson())).client(okhttp).build().create(IService.class);
```
In order to simplify the IService.class lets supose it has only 2 methods:

```
@GET
Call<JsonElement> get(@Url String url, @HeaderMap Map<String, Object> headers, @QueryMap Map<String, Object> query);

@POST
Call<ResponseBody> complexPost(@Url String url, @HeaderMap Map<String, Object> headers, @QueryMap Map<String, Object> query, @Body RequestBody body);
```
now this is how i'm trying to make parallel requests:

```
public static void main(String[] args) {

final Map<String,Object> empty = new HashMap<String, Object>();
	new Thread(new Runnable() {

		@Override
		public void run() {
				while(true) {
					System.out.println("sending short request");
					this.service.get(bar,empty,empty).execute();
					System.out.println("short request sent");
				}
		}
	}).start();


	new Thread(new Runnable() {

		@Override
		public void run() {
			byte[] buffer  = new byte[1024*1024];
			
				while(true) {
					RequestBody requestFile = RequestBody.create(MediaType.parse("application/octet-stream"), buffer, 0, buffer.length);
					System.out.println("sending long request").execute();
					this.service.complexPost(foo, empty, empty, requestFile);
					System.out.println("long request sent");
				}
		}
	}).start();
```

}
Simple explanation: two threads, thread A sends a small GET request - thread B sends 1MB data request [1024*1024 zeros just]

So, nothing is synchronized, I've a connection pool with enough idle connections to make it run in parallel, IN MY MIND sine request B is bigger is natural it takes long to complete, but as there is no synchronization there should be LOTS of "short request sent" for every "long request sent".

but what is printed is something like:

```
sending short request
short request sent  
sending long request
long request sent
sending short request
short request sent
sending long request
long request sent
sending short request
short request sent
```

no thread is interrupting the other request. WHY???? how to make multiple requests in parallel?

I did a deep debuging and i found the snippet of code where the synchronization locks:

```
private Http2Stream newStream(
      int associatedStreamId, List<Header> requestHeaders, boolean out) throws IOException {
    boolean outFinished = !out;
    boolean inFinished = false;
    boolean flushHeaders;
    Http2Stream stream;
    int streamId;

    synchronized (writer) {
      synchronized (this) {
        if (nextStreamId > Integer.MAX_VALUE / 2) {
          shutdown(REFUSED_STREAM);
        }
        if (shutdown) {
          throw new ConnectionShutdownException();
        }
        streamId = nextStreamId;
        nextStreamId += 2;
        stream = new Http2Stream(streamId, this, outFinished, inFinished, null);
        flushHeaders = !out || bytesLeftInWriteWindow == 0L || stream.bytesLeftInWriteWindow == 0L;
        if (stream.isOpen()) {
          streams.put(streamId, stream);
        }
      }
      if (associatedStreamId == 0) {
        writer.synStream(outFinished, streamId, associatedStreamId, requestHeaders);
      } else if (client) {
        throw new IllegalArgumentException("client streams shouldn't have associated stream IDs");
      } else { // HTTP/2 has a PUSH_PROMISE frame.
        writer.pushPromise(associatedStreamId, streamId, requestHeaders);
      }
    }

    if (flushHeaders) {
      writer.flush();
    }

    return stream;
  }
```
this is the synchronization block that locks boths threads. my question is WHY, and how to fix it?

**Comment by swankjesse** [comment]
Post a link to your StackOverflow question?

**Comment by yschimke** [comment]
@swankjesse Do we have tests covering the expected emitted frames of large (fixed size ready) requests?  I assume a slow request body will be handled by Okio buffering.

**Comment by bolds07** [comment]
> Post a link to your StackOverflow question?

https://stackoverflow.com/questions/58385954/retrofit2-parallel-requests?noredirect=1#comment103119476_58385954

As I've been looking it seams to be a project decision to "lock all client output while any thread is writing" doesn't matter how do I configure connection pool or dispatcher it will always lock to that point.

Is there any reason for this approach? I searched and sockets and the basic java api that okhttp is built on top of have not such limitation to explain that. so why?

**Comment by swankjesse** [comment]
I think there's something wrong with your measurement technique. OkHttp isn't involved when your "sending request" message is logged and so those two calls should be interleaved regardless of what OkHttp is doing.

**Comment by yschimke** [comment]
@swankjesse if we have a http/2 large fixed size body, won't we complete sending the 1MB body before the next request can start?

**Comment by swankjesse** [comment]
Tracking stream prioritization here: https://github.com/square/okhttp/issues/404

**Comment by ericYc** [comment]
@bolds07 hey brother，does you issue fixed，we face the same issue，i found that request to same endpoint is hunged for the thread is bloced state，i think this is a fetal problem；
by the way，my big request is also about 1MB

**Comment by ericYc** [comment]
@swankjesse hey brother，is this a issue，we have jstack file，okhttp version，how can we fix this， waiting on your response，thanks 
        <dependency>
            <groupId>com.squareup.okhttp3</groupId>
            <artifactId>okhttp</artifactId>
            <version>3.12.3</version>
        </dependency>
