### ISSUE TITLE
Cannot Segregate request and Response logs

### ISSUE THREAD

**Issue by surapuramakhil** [square/okhttp#5557]
Start by telling us what problem you’re trying to solve. Often a solution already exists!

If the case is of I am logging information in a table with different columns as request and response. it's not possible currently. if we can have differntly loggers for logging requests and response Strings it will solve. Currently Library is designed only for logging to the same place both request and response at the same place. (scenarios like logging into the log file and for console output)

Don’t send pull requests to implement new features without first getting our support. Sometimes we leave features out on purpose to keep the project small.

**Comment by swankjesse** [comment]
Please write your own logging interceptor. There's guidance on the interceptors wiki page.
