### ISSUE TITLE
MockWebServer not works on suite test in android

### ISSUE THREAD

**Issue by fpitpit** [square/okhttp#5566]
When I use MockWebServer in a suite test into android studio. it works when i launch a test manually but not works when I launch all tests.

The socket is closed
Failed to connect to localhost/127.0.0.1:60033
   
I use the latest version 4.2.2
@Before
setUp() {
mockWebServer = MockWebServer()
mockWebServer.start() 
       
....
}

and into 
@After
fun tearDown() {
 mockWebServer.shutdown()
}

and same thing into another

**Comment by yschimke** [comment]
You should ask this sort of question on stackoverflow. At a complete guess, make sure mockWebServer isn't a static field.

**Comment by fpitpit** [comment]
Yes I'm sure is not static

Téléchargez Outlook pour Android<https://aka.ms/ghei36>

________________________________
