### ISSUE TITLE
Socket timeout exception

### ISSUE THREAD

**Issue by Gvex95** [square/okhttp#5567]
Hi, i am having weird issue, and not sure where to look and debug anymore.
So i have some test android app, which should print some data from server after i get  server response.
Before i send request to server, i check for network availability by downloading some json file from network.
Also i have two physical devices, one is running on android 7.1.2, and another on android 6.0.1. 
The issue can be reproduced like this. When i turn device off, and pull Ethernet cable out, than turn device back on, there will be message that network is not availble. But also i have some network checker in background which checks for network every second by trying to download some json. That file downloader is based on retrofit and okHttp. What is happening, is that as soon i plug ethernet back i try to download file, got socket timeout exception, try again after a second, and it will succeed to download after couple of attempts, after that i use retrofit to send request to server which will  SOME TIME produce socket timeout exception, but not always. What is strange here, is that if u don't pull out etherent cable when turning device off, than everything works just fine. Even stranger is that this same code works on another board which runs on android 7.1.2. 
Also i created another flavor off app, one which use HttpUrl connection to download json file, and to send request to server, and it works even on board that runs on android 6.0.1, every single time( both file download, and talking to server part) 
So i don't have clue what is happening. I am using latest  version ( 4.2.2). I tried to use trusted agent to eliminate ssl errors, but it did not helped at all.
So please if  anyone had similar problem, it would be great if someone could provide me a solution for this, or at least point me in direction where to look.

Edit:
If this helps, from logs i can see:

10-22 14:28:06.829  5663  5767 I System.out: 0.000 callStart
10-22 14:28:06.866  5663  5829 I System.out 0.037 proxySelectStart
10-22 14:28:06.866  5663  5829 I System.out : 0.038 proxySelectEnd
10-22 14:28:06.868  5663  5829 I System.out : 0.040 connectionAcquired
10-22 14:28:06.879  5663  5829 I System.out : 0.051 requestHeadersStart
10-22 14:28:06.880  5663  5829 I System.out : 0.052 requestHeadersEnd
10-22 14:28:06.880  5663  5829 I System.out : 0.052 requestBodyStart
10-22 14:28:06.881  5663  5829 I System.out : 0.052 requestBodyEnd
10-22 14:28:06.881  5663  5829 I System.out : 0.053 responseHeadersStart
10-22 14:28:36.885  5663  5829 I System.out : 30.056 responseFailed
10-22 14:28:36.888  5663  5829 I System.out : 30.059 connectionReleased
10-22 14:28:36.889  5663  5829 I System.out : 30.060 callFailed1

So i don't see responseHeadersEnd in logs, so there is the place where it is stucked. Hope this helps

Edit2:
I found out one more board which also runs on android 6.0.1. And it has same behaviour, but i found out that it does not work randomly, but every second time. So it works, than socket timeout, than works again, than timeout, etc. Still have no idea why :(

**Comment by swankjesse** [comment]
Unclear what action to take on this.
