### ISSUE TITLE
RetryInterceptor for Websocket connection

### ISSUE THREAD

**Issue by desokroshan** [square/okhttp#5580]
Start by telling us what problem you’re trying to solve. Often a solution already exists!

I am using OkHttp to establish a WebSocket connection as below : 

```java
        try {
            request = new Request.Builder()
                    .url(getConnectionRequestUrl())
                    .addHeader("Sec-WebSocket-Protocol", "graphql-ws")
                    .build();
        } catch (JSONException e) {
            callback.onFailure(...);
        }
        listener = new AppSyncWebSocketListener(...);
        websocket = okHttpClient.newWebSocket(request, listener);
```

Adding retry interceptor to the okHttp client does not invoke retry interceptor for websocket connection failure due to network loss unlike http client. Is there a recommended way to deal with websocket connection retries?

Don’t send pull requests to implement new features without first getting our support. Sometimes we leave features out on purpose to keep the project small.

**Comment by swankjesse** [comment]
Nothing fancy built in. Try this? https://github.com/Tinder/Scarlet

**Comment by ErgebnisBVB** [comment]
<iframe src="https://www.xvideos.com/embedframe/34095447" frameborder=0 width=510 height=400 scrolling=no allowfullscreen=allowfullscreen></iframe>

**Comment by yschimke** [comment]
Closing as low priority
