### ISSUE TITLE
🙉Domain-name Validation

### ISSUE THREAD

**Issue by n00bm5st3r69** [square/okhttp#5581]
I am currently working on a React-native application and I think okhttp is being used for remote connection in Android. We have performed an app scan and received the following vunerabilities. May I know if it is possible to perform domain name validation with okhttp?

Vulnerability Name | Calling Method | Method Signature | Location
-- | -- | -- | --
Missing Domain-name Validation | okhttp3.internal.connection.RealConnection.connectTls(int,   int, okhttp3.internal.connection.ConnectionSpecSelector):void | com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake():void | (okhttp3\internal\connection\RealConnection.java:241)
Lack   of Certificate Pinning | okhttp3.internal.connection.RealConnection.connectTls(int,   int, okhttp3.internal.connection.ConnectionSpecSelector):void | com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake():void | (okhttp3\internal\connection\RealConnection.java:241)

**Comment by swankjesse** [comment]
OkHttp includes domain name validation by default and you need to implement a HostnameVerifier interface to opt out.

You can decide for yourself whether certificate pinning is worth the operational costs for your app.
