### ISSUE TITLE
Interceptor to see EventListener values?

### ISSUE THREAD

**Issue by ursusursus** [square/okhttp#5585]
Hi, Im trying to do simple time synchronization with server, where server responds with its time, and I want to substract response time from this.

I do have EventListener and measure between responseHeadersStart and callEnd, however it's difficult to attach this to a call, since they're immutable.

So I'm trying write an interceptor but I dont see a way to get these values here, or rather, if I manually measure around chain.proceed(), it includes all, not just response time so, am I out of luck?

**Comment by yschimke** [comment]
With an Interceptor you can surround the chain.proceed call.  But it's tricky with streaming responses.

With an EventListener https://square.github.io/okhttp/events/ you can have a different listener instance created per call, and so store the start as a field and then the call end is invoked after the reading of the body completes.

**Comment by yschimke** [comment]
Please consider posting this to stackoverflow.  This isn't a bug or feature request you have raised.

**Comment by ursusursus** [comment]
No no, what I'm getting at is that there's no way I can see that result from EventListener at response callsite. As its designed only to sideffect, to a logger for example. I want to use that time as a value with a response

**Comment by swankjesse** [comment]
```
  static class MyEventListenerFactory implements EventListener.Factory {
    @Override public EventListener create(Call call) {
      MyEventListener eventListener = call.request().tag(MyEventListener.class);
      if (eventListener == null) throw new IllegalStateException();
      return eventListener;
    }
  }

  static class MyEventListener extends EventListener {
    long startNanos = -1L;

    @Override public void callStart(@NotNull Call call) {
      startNanos = System.nanoTime();
    }
  }

  static class MyInterceptor implements Interceptor {
    @Override public Response intercept(Chain chain) throws IOException {
      MyEventListener eventListener = chain.request().tag(MyEventListener.class);
      if (eventListener == null) throw new IllegalStateException();

      Response response = chain.proceed(chain.request());
      return response.newBuilder()
          .addHeader("start-nanos", Long.toString(eventListener.startNanos))
          .build();
    }
  }

  @Test public void eventListenerAndInterceptorCollaborate() throws IOException {
    server.enqueue(new MockResponse()
        .setBody("abc"));

    client = new OkHttpClient.Builder()
        .addInterceptor(new MyInterceptor())
        .eventListenerFactory(new MyEventListenerFactory())
        .build();

    Call call = client.newCall(new Request.Builder()
        .url(server.url("/"))
        .tag(MyEventListener.class, new MyEventListener())
        .build());

    Response response = call.execute();
    System.out.println(response.header("start-nanos"));
    response.body().close();
  }
```

**Comment by ursusursus** [comment]
oh tags, excellent, thanks!
