### ISSUE TITLE
Thread.holdsLock calls result in excessive overhead w/o ability to turn it off

### ISSUE THREAD

**Issue by astral303** [square/okhttp#5586]
When profiling OkHttp3 4.2.1 under a high load (a microservice/RPC scenario), the profiler constantly shows `Thread.holdsLock(this)` as a non-trivial percentage of wall time spent servicing sending a request.

Here's an example hot spot in `Dispatcher.kt`:

```
  private fun promoteAndExecute(): Boolean {
    assert(!Thread.holdsLock(this))
```

The generated Java source makes the call to `Thread.holdsLock(this)` even if assertions are *off*:

```
  private final boolean promoteAndExecute() {
      boolean var1 = !Thread.holdsLock(this);
      boolean isRunning = false;
      boolean var3 = false;
      boolean var4;
      if (_Assertions.ENABLED && !var1) {
```

However, `Thread.holdsLock` is a native call:

```   
public static native boolean holdsLock(Object obj);
```

The JIT optimizer is unable to optimize across native call boundaries. This cause a hard unable-to-optimize situation, which, for example, inhibits inlining across virtual calls. In my profiling for my target use case, this placed a ceiling on performance that I was not able to work around (save for building a patched OkHttp version).

**Comment by JakeWharton** [comment]
Relevant: https://youtrack.jetbrains.com/issue/KT-22292

**Comment by JakeWharton** [comment]
We can mitigate by duplicating https://github.com/Kotlin/kotlinx.coroutines/commit/583d39dd4fe1d8f488df3e384901aa19f95166e2

**Comment by yschimke** [comment]
@JakeWharton this looks worrying i.e. we can't reproduce exactly

```
// Need InlineOnly for efficient bytecode on Android
@file:Suppress("INVISIBLE_REFERENCE", "INVISIBLE_MEMBER")
```
