### ISSUE TITLE
Support trailing lambda syntax in HttpLoggingInterceptor

### ISSUE THREAD

**Issue by jbluntz** [square/okhttp#5589]
Now that okhttp is written in kotlin, it would be nice to be able to construct an HttpLoggingInterceptor with a trailing lambda, instead of having to pass an anonymous Logger object (like in the readme example):

`val loggingInterceptor = HttpLoggingInterceptor { Timber.tag("OkHttp").d(message) }`

This could be as simple as a top-level factory function: 
```
fun HttpLoggingInterceptor(logger: ((String) -> Unit)): HttpLoggingInterceptor {
    return HttpLoggingInterceptor(object: HttpLoggingInterceptor.Logger {
        override fun log(message: String) {
            logger(message)
        }
    })
}
```

I'd love to try and contribute this, if you're amenable to the idea.

**Comment by swankjesse** [comment]
We're waiting for Kotlin to launch language support for SAM conversion that can do this for us.

**Comment by jbluntz** [comment]
That's a really good point; SAM conversion for kotlin functions is [enabled by default in the new inference engine](https://youtrack.jetbrains.com/issue/KT-11129), but it seems that SAM conversion for kotlin classes is [still in debate](https://youtrack.jetbrains.com/issue/KT-7770#focus=streamItem-27-2919336.0-0) (and potentially a long way off?)

You don't think it's worth it as a stopgap?

**Comment by swankjesse** [comment]
I do not.
