### ISSUE TITLE
IllegalArgumentException: reason.size() > 123

### ISSUE THREAD

**Issue by flocsy** [square/okhttp#5594]
There's this relatively new code in: okhttp/src/main/java/okhttp3/internal/ws/RealWebSocket.kt:

```
    if (reason != null) {
      reasonBytes = reason.encodeUtf8()
      require(reasonBytes.size <= CLOSE_MESSAGE_MAX) {
        "reason.size() > $CLOSE_MESSAGE_MAX: $reason"
      }
    }
```

The problem is that this causes "IllegalArgumentException: reason.size() > 123" and there's no "nice" way to fix it.

Of course I can do:

```
   int code = 1000;
   String reason = ("disconnected: " + url).substring(0,123);
   webSocket.close(code, reason);
```

but this is not ideal, because that 123 can change. So I would rather do:

```
   String reason = ("disconnected: " + url).substring(0,(int) WebSocketProtocol.CLOSE_MESSAGE_MAX);
```

but this doesn't work because it's internal.

So at least change it to public, but even better solution maybe would be to do this (the substring) in okhttp, and instead of an exception just log a warning.

**Comment by swankjesse** [comment]
123 won't change.

**Comment by pau101** [comment]
It should be acknowledged that it would be erroneous to truncate arbitrary reason strings by 123, as that max length refers to bytes of UTF-8 text, not characters, nor String chars (UTF-16 code units). The error message OkHttp is providing is a bit misleading in that regard.

**Comment by yschimke** [comment]
Yep, agreed.  We shouldn't arbitrarily truncate, it's awkward with partial unicode strings etc.  So clients should do this, reporting the error is the best we can do as an API.  If you feel strongly, submit a PR to improve the message to include encoded bytes or similar. But unlikely we fix this internally if it hasn't gotten attention so far.

Won't fix without a PR.
