### ISSUE TITLE
Onhttp3 thread pool

### ISSUE THREAD

**Issue by xh520md** [square/okhttp#5608]
When I used okhttp3, every per request will  create a thread. Look at the source code. There is a “ConnectionPool” class with a  static method: static {
Executor = new ThreadPoolExecutor(0, 2147483647, 60L, timeunit.seconds, new SynchronousQueue(), Util. ThreadFactory ("OkHttp ConnectionPool", true);
}. I have two questions. The first one is that after executing the request, the thread is idle, and it has to wait 60 seconds for recycling. When the concurrency is high, Can we use this idle threads instead of creating threads all the time? The second problem is naming. Currently all thread pool thread names are "OkHttp ConnectionPool". It is recommended to add the thread number "OkHttp ConnectionPool-%d" ,Easy to find problems

**Comment by swankjesse** [comment]
Duplicate of https://github.com/square/okhttp/issues/5607

**Comment by xh520md** [comment]
How can I ask questions on GitHub？




---Original---
