### ISSUE TITLE
Okhttp3 Thread pool problem

### ISSUE THREAD

**Issue by xh520md** [square/okhttp#5609]
Excuse me.I used okhttp as the network forwarding. The peak time of TPS is about 10000. I simulated the network and sent it 10,000 times. 
Test case :
for(int i = 0; i < 10000; i++)}{
/ / okhttp3 forward
}
 I then looked at the number of threads using Java visualvm and found that the number of threads was increasing and approaching the number of requests. As an android network request, this may not be a problem, but as a Java application making a request, the number of sending threads will be high at some point.Too many threads cause the application to process slowly.
Okhttp3 version is 3.11.0
Jdk version is 1.7

**Comment by swankjesse** [comment]
Please use StackOverflow for usage questions.
