### ISSUE TITLE
Become complaint with WHATWG url standard

### ISSUE THREAD

**Issue by RicoGit** [square/okhttp#5611]
Does httpOk support [WHATWG spec](https://url.spec.whatwg.org/) for parsing URLs?
If yes, could you add this information in docs and add these test cases from [web-platform-tests](https://github.com/web-platform-tests/wpt/tree/master/url). If not, do you have any plans to follow this spec?

**Comment by swankjesse** [comment]
Yep! https://github.com/square/okhttp/blob/master/okhttp/src/test/java/okhttp3/WebPlatformUrlTest.java

**Comment by RicoGit** [comment]
That's great. Sorry for wasting your time, but could you add that somewhere into the documentation. It's a great selling point! And thanks for what you're doing.
