### ISSUE TITLE
java.lang.NoClassDefFoundError: okhttp3/internal/platform/Platform

### ISSUE THREAD

**Issue by 10045125** [square/okhttp#5613]
The version of OkHttp I am using is 3.14.4. Some exceptions occur on some Android 4.4 models.

    java.lang.NoClassDefFoundError: okhttp3/internal/platform/Platform
        at okhttp3.internal.tls.CertificateChainCleaner.get(CertificateChainCleaner.java:41)
        at okhttp3.OkHttpClient$Builder.sslSocketFactory(OkHttpClient.java:782)

**Comment by yschimke** [comment]
You will need to use 3.12 branch for these devices.

**Comment by 10045125** [comment]
I want to know what is the root cause of this problem. Thank you！

**Comment by swankjesse** [comment]
https://cashapp.github.io/2019-02-05/okhttp-3-13-requires-android-5
