### ISSUE TITLE
Add an option to parse non standard HTTP status codes

### ISSUE THREAD

**Issue by Dkhusainov** [square/okhttp#5615]
Currently if the HTTP response code falls outside of 3 digits, the request fails with "Unexpected status line:".

There is currently **NO WAY**(standard or hacky) to bypass that, since header parsing happens deep inside OkHttp internals and you can't access it...

**Comment by JakeWharton** [comment]
For what purpose?

**Comment by Dkhusainov** [comment]
Working with a server that communicates errors through custom HTTP codes like 10001, 10002...

I understand this is extremely narrow case - I'd be fine with just any solution that doesn't require forking the library to modify one line of code.

**Comment by swankjesse** [comment]
I suspect it hurts to be on the other side of this, but one of our goals with OkHttp is to use our limited influence to discourage special cases in the wild. Our implementation leans on existing precedents (what does Firefox do?) and standards (what do the RFCs require?)

And so when developers ask for a special case I push back. I want you to further push back to whatever service returns 10001 and to get its maintainers to conform to standards.

If they’re unwilling, you should find an alternative HTTP client whose maintainers carry no such beliefs. Or fork it! It’s open source, 7,000 people forked it already and you can be next.

Though I recommend that if you do fork, please try to track upstream as much as possible. We occasionally fix security bugs and being stuck in 2019 hurts you.

**Comment by Dkhusainov** [comment]
We ended up just extracting invalid HTTP code from OkHttp internal exception message and rethrowing our own - If anyone has the same problem.
