### ISSUE TITLE
Cannot iterate on Headers in Java 11 + JPMS

### ISSUE THREAD

**Issue by sbordet** [square/okhttp#5617]
Trying to iterate over a `Headers` instance does not work when using plain Java 11 and JPMS.

The reason is that `Headers implements Iterator<kotlin.Pair>` and `kotlin.Pair` is not available to JPMS.

This works fine in Java 8 (as the Kotlin stdlib ends up in the classpath), but does not work when using Java 11 and proper JPMS modules, because the application class that iterates over the `Headers` would need to JPMS-_read_ `kotlin.Pair`, which would require a directive in the application `module-info.java`.
Unfortunately the Kotlin stdlib does not support JPMS (no `Automatic-Module-Name` in the manifest, no `module-info.class` in the jar), so that leaves the application relying on automatic modules with unstable module names.

This can be worked around iterating using `Headers.names()` and `Headers.values(name)`.

FTR, I encountered this problem in [CometD 6](https://github.com/cometd/cometd/tree/6.0.x) which is based on Java 11 and JPMS.

**Comment by JakeWharton** [comment]
Is there a Kotlin bug filed for this? What action are you proposing OkHttp take here?

**Comment by sbordet** [comment]
I know OkHttp 4 has been rewritten in Kotlin, so not sure what to suggest here.

Personally, I would like OkHttp classes that are APIs, such as `Headers`, to explicitly not have Kotlin classes in method signatures, class inheritance, type parameters, etc.
That would ensure maximum usability from Java 11 + JPMS, as the only dependencies an application would need to require in `module-info.java` would be Java-only ones.

I don't think it's a Kotlin issue as they need to remain Java 6 compatible and such, so for Kotlin JPMS modules are far far away.

However, removing `implements Iterable<kotlin.Pair>` may be an incompatible change, so I raised this issue just as a heads-up, as there is an easy workaround to iterate over `Headers`.

Trying to iterate over `Headers` using `Iterable` would not even compile with Java 11 + JPMS, so it's a hard error, but as I said easily workaroundable with a small code change.
I only found this example in my usage of OkHttp, but it may be possible that there are other cases where there is no work around.

**Comment by JakeWharton** [comment]
Supplying an Automatic-Module-Name can be done regardless of what version they support though. Not to mention they could use the `META-INF/versions/9/module-info.class` trick, or provide a `kotlin-stdlib-jdk9` variant of the standard library (like they already do for 7 and 8).

Let me search through for an issue about this on their tracker. I know it has come up in the past, but I don't know what the state of it is.

**Comment by swankjesse** [comment]
Thanks for reporting!

Kotlin folks should fix this for Kotlin 1.4.
https://youtrack.jetbrains.com/issue/KT-21266

No further action for us to take on this.
