### ISSUE TITLE
Hello All , I got an strange issue related to okhttp3 while requesting the network call in webservices . I am stuck here and  I am not able to make the network request , Below is the log of error .

### ISSUE THREAD

**Issue by Kedar-jirel** [square/okhttp#5620]
11-29 11:32:16.082 30319-31012/cashpay.com.np V/NativeCrypto: SSL handshake aborted: ssl=0x55bce8b658: Failure in SSL library, usually a protocol error
    error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER (third_party/openssl/boringssl/src/ssl/tls_record.cc:242 0x7f5d0eb1bb:0x00000000)
11-29 11:32:16.095 30319-31012/cashpay.com.np W/System.err: javax.net.ssl.SSLHandshakeException: Handshake failed
11-29 11:32:16.096 30319-31012/cashpay.com.np W/System.err:     at com.google.android.gms.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(:com.google.android.gms@19629021@19.6.29 (040408-278422107):38)
11-29 11:32:16.096 30319-31012/cashpay.com.np W/System.err:     at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:320)
11-29 11:32:16.096 30319-31012/cashpay.com.np W/System.err:     at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:284)
11-29 11:32:16.096 30319-31012/cashpay.com.np W/System.err:     at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:169)
11-29 11:32:16.096 30319-31012/cashpay.com.np W/System.err:     at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:257)
11-29 11:32:16.096 30319-31012/cashpay.com.np W/System.err:     at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
11-29 11:32:16.096 30319-31012/cashpay.com.np W/System.err:     at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
11-29 11:32:16.096 30319-31012/cashpay.com.np W/System.err:     at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
11-29 11:32:16.097 30319-31012/cashpay.com.np W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
11-29 11:32:16.097 30319-31012/cashpay.com.np W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
11-29 11:32:16.097 30319-31012/cashpay.com.np W/System.err:     at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
11-29 11:32:16.097 30319-31012/cashpay.com.np W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
11-29 11:32:16.097 30319-31012/cashpay.com.np W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
11-29 11:32:16.097 30319-31012/cashpay.com.np W/System.err:     at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
11-29 11:32:16.097 30319-31012/cashpay.com.np W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
11-29 11:32:16.097 30319-31012/cashpay.com.np W/System.err:     at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:125)
11-29 11:32:16.097 30319-31012/cashpay.com.np W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
11-29 11:32:16.097 30319-31012/cashpay.com.np W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
11-29 11:32:16.097 30319-31012/cashpay.com.np W/System.err:     at cashpay.com.np.di.UnsafeOkHttpClient.lambda$getUnsafeOkHttpClient$0(UnsafeOkHttpClient.java:110)
11-29 11:32:16.097 30319-31012/cashpay.com.np W/System.err:     at cashpay.com.np.di.-$$Lambda$UnsafeOkHttpClient$nB91zahuIhOW6vTGloPQYo6GBfQ.intercept(lambda)
11-29 11:32:16.097 30319-31012/cashpay.com.np W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
11-29 11:32:16.097 30319-31012/cashpay.com.np W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
11-29 11:32:16.097 30319-31012/cashpay.com.np W/System.err:     at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:264)
11-29 11:32:16.098 30319-31012/cashpay.com.np W/System.err:     at okhttp3.RealCall.execute(RealCall.java:93)
11-29 11:32:16.098 30319-31012/cashpay.com.np W/System.err:     at retrofit2.OkHttpCall.execute(OkHttpCall.java:188)
11-29 11:32:16.098 30319-31012/cashpay.com.np W/System.err:     at com.jakewharton.retrofit2.adapter.rxjava2.CallObservable.subscribeActual(CallObservable.java:41)
11-29 11:32:16.098 30319-31012/cashpay.com.np W/System.err:     at io.reactivex.Observable.subscribe(Observable.java:12036)
11-29 11:32:16.098 30319-31012/cashpay.com.np W/System.err:     at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
11-29 11:32:16.098 30319-31012/cashpay.com.np W/System.err:     at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:579)
11-29 11:32:16.098 30319-31012/cashpay.com.np W/System.err:     at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
11-29 11:32:16.098 30319-31012/cashpay.com.np W/System.err:     at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
11-29 11:32:16.098 30319-31012/cashpay.com.np W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
11-29 11:32:16.098 30319-31012/cashpay.com.np W/System.err:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:154)
11-29 11:32:16.098 30319-31012/cashpay.com.np W/System.err:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
11-29 11:32:16.098 30319-31012/cashpay.com.np W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
11-29 11:32:16.098 30319-31012/cashpay.com.np W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
11-29 11:32:16.099 30319-31012/cashpay.com.np W/System.err:     at java.lang.Thread.run(Thread.java:818)
11-29 11:32:16.099 30319-31012/cashpay.com.np W/System.err: Caused by: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0x55bce8b658: Failure in SSL library, usually a protocol error
11-29 11:32:16.099 30319-31012/cashpay.com.np W/System.err: error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER (third_party/openssl/boringssl/src/ssl/tls_record.cc:242 0x7f5d0eb1bb:0x00000000)
11-29 11:32:16.099 30319-31012/cashpay.com.np W/System.err:     at com.google.android.gms.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
11-29 11:32:16.099 30319-31012/cashpay.com.np W/System.err:     at com.google.android.gms.org.conscrypt.NativeSsl.doHandshake(:com.google.android.gms@19629021@19.6.29 (040408-278422107):6)
11-29 11:32:16.099 30319-31012/cashpay.com.np W/System.err:     at com.google.android.gms.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(:com.google.android.gms@19629021@19.6.29 (040408-278422107):14)
11-29 11:32:16.099 30319-31012/cashpay.com.np W/System.err: 	... 36 more
11-29 11:32:16.177 30319-31012/cashpay.com.np V/NativeCrypto: SSL handshake aborted: ssl=0x55bd011e78: Failure in SSL library, usually a protocol error
    error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER (third_party/openssl/boringssl/src/ssl/tls_record.cc:242 0x7f5d0eb1bb:0x00000000)
11-29 11:32:18.221 30319-31012/cashpay.com.np V/NativeCrypto: SSL handshake aborted: ssl=0x55bcfe0788: Failure in SSL library, usually a protocol error
    error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER (third_party/openssl/boringssl/src/ssl/tls_record.cc:242 0x7f5d0eb1bb:0x00000000)
11-29 11:32:18.222 30319-31012/cashpay.com.np W/System.err: javax.net.ssl.SSLHandshakeException: Handshake failed
11-29 11:32:18.222 30319-31012/cashpay.com.np W/System.err:     at com.google.android.gms.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(:com.google.android.gms@19629021@19.6.29 (040408-278422107):38)
11-29 11:32:18.222 30319-31012/cashpay.com.np W/System.err:     at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:320)
11-29 11:32:18.222 30319-31012/cashpay.com.np W/System.err:     at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:284)
11-29 11:32:18.222 30319-31012/cashpay.com.np W/System.err:     at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:169)
11-29 11:32:18.223 30319-31012/cashpay.com.np W/System.err:     at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:257)
11-29 11:32:18.223 30319-31012/cashpay.com.np W/System.err:     at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
11-29 11:32:18.223 30319-31012/cashpay.com.np W/System.err:     at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
11-29 11:32:18.223 30319-31012/cashpay.com.np W/System.err:     at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
11-29 11:32:18.223 30319-31012/cashpay.com.np W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
11-29 11:32:18.223 30319-31012/cashpay.com.np W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
11-29 11:32:18.223 30319-31012/cashpay.com.np W/System.err:     at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
11-29 11:32:18.223 30319-31012/cashpay.com.np W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
11-29 11:32:18.223 30319-31012/cashpay.com.np W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
11-29 11:32:18.223 30319-31012/cashpay.com.np W/System.err:     at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
11-29 11:32:18.223 30319-31012/cashpay.com.np W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
11-29 11:32:18.223 30319-31012/cashpay.com.np W/System.err:     at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:125)
11-29 11:32:18.223 30319-31012/cashpay.com.np W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
11-29 11:32:18.223 30319-31012/cashpay.com.np W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
11-29 11:32:18.223 30319-31012/cashpay.com.np W/System.err:     at cashpay.com.np.di.UnsafeOkHttpClient.lambda$getUnsafeOkHttpClient$0(UnsafeOkHttpClient.java:110)
11-29 11:32:18.223 30319-31012/cashpay.com.np W/System.err:     at cashpay.com.np.di.-$$Lambda$UnsafeOkHttpClient$nB91zahuIhOW6vTGloPQYo6GBfQ.intercept(lambda)
11-29 11:32:18.223 30319-31012/cashpay.com.np W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
11-29 11:32:18.223 30319-31012/cashpay.com.np W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
11-29 11:32:18.223 30319-31012/cashpay.com.np W/System.err:     at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:264)
11-29 11:32:18.223 30319-31012/cashpay.com.np W/System.err:     at okhttp3.RealCall.execute(RealCall.java:93)
11-29 11:32:18.224 30319-31012/cashpay.com.np W/System.err:     at retrofit2.OkHttpCall.execute(OkHttpCall.java:188)
11-29 11:32:18.224 30319-31012/cashpay.com.np W/System.err:     at com.jakewharton.retrofit2.adapter.rxjava2.CallObservable.subscribeActual(CallObservable.java:41)
11-29 11:32:18.224 30319-31012/cashpay.com.np W/System.err:     at io.reactivex.Observable.subscribe(Observable.java:12036)
11-29 11:32:18.224 30319-31012/cashpay.com.np W/System.err:     at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
11-29 11:32:18.224 30319-31012/cashpay.com.np W/System.err:     at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:579)
11-29 11:32:18.224 30319-31012/cashpay.com.np W/System.err:     at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
11-29 11:32:18.224 30319-31012/cashpay.com.np W/System.err:     at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
11-29 11:32:18.224 30319-31012/cashpay.com.np W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
11-29 11:32:18.224 30319-31012/cashpay.com.np W/System.err:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:154)
11-29 11:32:18.224 30319-31012/cashpay.com.np W/System.err:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
11-29 11:32:18.224 30319-31012/cashpay.com.np W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
11-29 11:32:18.224 30319-31012/cashpay.com.np W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
11-29 11:32:18.224 30319-31012/cashpay.com.np W/System.err:     at java.lang.Thread.run(Thread.java:818)
11-29 11:32:18.224 30319-31012/cashpay.com.np W/System.err: Caused by: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0x55bcfe0788: Failure in SSL library, usually a protocol error
11-29 11:32:18.224 30319-31012/cashpay.com.np W/System.err: error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER (third_party/openssl/boringssl/src/ssl/tls_record.cc:242 0x7f5d0eb1bb:0x00000000)
11-29 11:32:18.225 30319-31012/cashpay.com.np W/System.err:     at com.google.android.gms.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
11-29 11:32:18.225 30319-31012/cashpay.com.np W/System.err:     at com.google.android.gms.org.conscrypt.NativeSsl.doHandshake(:com.google.android.gms@19629021@19.6.29 (040408-278422107):6)
11-29 11:32:18.225 30319-31012/cashpay.com.np W/System.err:     at com.google.android.gms.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(:com.google.android.gms@19629021@19.6.29 (040408-278422107):14)
11-29 11:32:18.225 30319-31012/cashpay.com.np W/System.err: 	... 36 more
11-29 11:32:18.242 30319-31012/cashpay.com.np V/NativeCrypto: SSL handshake aborted: ssl=0x55bcff8408: Failure in SSL library, usually a protocol error
    error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER (third_party/openssl/boringssl/src/ssl/tls_record.cc:242 0x7f5d0eb1bb:0x00000000)

**Comment by yschimke** [comment]
This isn't something we can generally take any action on.  It's an SSL failure with the AOSP bundles TLS implementation.  You could raise with them or ask on stackoverflow.

Check you aren't somehow connecting to a plaintext or not HTTPS endpoint.
