### ISSUE TITLE
callEnd and callFailed executed in a request

### ISSUE THREAD

**Issue by lyqaiym** [square/okhttp#5621]
43:0.000-callStart;0.001-connectionAcquired;0.002-requestHeadersStart;0.003-requestHeadersEnd;0.003-responseHeadersStart;10.005-connectionReleased;10.005-callEnd;10.006-callFailed;

com.squareup.okhttp3:okhttp:3.11.0

**Comment by yschimke** [comment]
Please provide a reprodubicle test case or consider raising on stackoverflow.

Also please test with a currently maintained version.  3.12.x, 3.14.x or 4.2.2
