### ISSUE TITLE
Socket exception when getting the response

### ISSUE THREAD

**Issue by ramkumarnn** [square/okhttp#5643]
We are using OKHTTP3 .

Our code looks like below.

  Response okHttpResponse = client.newCall(request).execute();

After getting the response, we have executed the below logic.

**response.body().string()**

The above line code ending up with the exception stating socket is closed without returning the response back

**Comment by yschimke** [comment]
Please provide a reproduction of a bug, e.g. code that hits a specific website showing the failure.  Then reopen this ticket.

Otherwise post to stackoverflow for general usage issues.
