### ISSUE TITLE
404

### ISSUE THREAD

**Issue by tangzhulong** [square/okhttp#5648]
服务器新增加了一个接口，访问时报404，但是在浏览器里面又访问正常
![图片](https://user-images.githubusercontent.com/10388320/70846657-9d3a6900-1e96-11ea-9f97-1e9dd316d7d7.png)
![图片](https://user-images.githubusercontent.com/10388320/70846715-fc987900-1e96-11ea-8b4e-0d06fd385e83.png)
![图片](https://user-images.githubusercontent.com/10388320/70846683-cb1fad80-1e96-11ea-94d6-e4750fcd3cf8.png)

**Comment by TangHuaiZhe** [comment]
这里不是处理这种问题的地方。
建议使用Postman试试，调通接口之后可以直接生成okhttp的代码。

**Comment by tangzhulong** [comment]
> 
> 这里不是处理这种问题的地方。
> 建议使用Postman试试，调通接口之后可以直接生成okhttp的代码。

postman可以访问，但是在APP里面就报404

**Comment by tangzhulong** [comment]
--
