### ISSUE TITLE
Allow bool values in HttpUrl.Builder#addEncodedQueryParameter()

### ISSUE THREAD

**Issue by mueller-ma** [square/okhttp#5653]
If I want to add a boolean value as the value of a query parameter, I have to write `.addEncodedQueryParameter("foo", "true")`. If you add an override for `addEncodedQueryParameter()` to accept bool as value, you have a spellcheck for "true" and "false" during compilation.

**Comment by JakeWharton** [comment]
You can use `Boolean.toString(true)` in Java or `true.toString()` in Kotlin.

I'd be against adding overloads to OkHttp. You can make the same argument for characters or integers or longs or a bunch of types and now we're playing whack-a-mole.

URLs are strings and as a result you should be mindful of the string representation of what you are adding.

**Comment by swankjesse** [comment]
Yep. If you want a type system for composing URL strings, layer that on top of HttpUrl.

**Comment by mueller-ma** [comment]
Thanks for your feedback. I will go for extension functions and add `addEncodedQueryParameter(String, Boolean)`.
