### ISSUE TITLE
Document ForkJoinPool.managedBlock() usage example

### ISSUE THREAD

**Issue by leventov** [square/okhttp#5655]
When a client performs a blocking call, I think it makes sense to wrap the very blocking operation with `ForkJoinPool.managedBlock()`. Many clients make HTTP calls from a `ForkJoinPool` and don't wrap such calls with `ForkJoinPool.managedBlock()` themselves.

Another reason why the library itself rather than the clients should do this is that the library is able to isolate the very blocking operation while doing some other operations (such as compression/decompression, if it happens to be performed in the application-layer thread) outside of `ForkJoinPool.managedBlock()`. Also, if the response for the call is cached, `ForkJoinPool.managedBlock()` could be avoided inside the OkHttp library.

**Comment by yschimke** [comment]
Trying to get my head around this - there is a discussion on how to use this here

https://www.javaspecialists.eu/archive/Issue223.html

**Comment by yschimke** [comment]
Do we want this specifically around realChain.proceed in RetryAndFollowUpInterceptor.intercept

```
    while (true) {
      transmitter.prepareToConnect(request)

      if (transmitter.isCanceled) {
        throw IOException("Canceled")
      }

      var response: Response
      var success = false
      try {
        response = realChain.proceed(request, transmitter, null)
```

Or as a first pass just assume the whole of RealCall.execute?

**Comment by swankjesse** [comment]
The whole thing seems rather loose. When to use it, how to test it, whether libraries like OkHttp should do it or whether that responsibility belongs with our users.

Perhaps we should write a sample interceptor and ask the experts to check it? It might also require wrapping the response body steam as reading that will also block.

**Comment by yschimke** [comment]
I think it's worth doing, but mainly for non expert use of ForkJoinPool usage where someone doesn't understand the consequence of blocking operations.  But it seems good that it will let the pool spin up another thread to keep CPUs maxed out.

**Comment by swankjesse** [comment]
Ok, I’m on board. Could we do it exclusively in `Exchange.kt` ? Maybe just create a `blocking {}` function that does the fork join pool? Also as always I’m anxious about adding a bunch of allocations that most users won’t need.

**Comment by yschimke** [comment]
Yeah, I still don't know where/how to do it. :)

**Comment by JakeWharton** [comment]
The call is allocation-free for non-FJP theads, if memory serves.

**Comment by leventov** [comment]
It is allocation-free if somebody caches the `ManagedBlocker` object in a field, which is unidiomatic (in Java nor Kotlin). But it could be done. On the other hand, it's an allocation of an object with a single reference field (to the enclosing object), ~ 24 bytes. Isn't that negligible when we are doing a remote network HTTP call anyway?

**Comment by swankjesse** [comment]
@leventov once we return a ResponseBody there's a blocking call on each unbuffered read. In aggregate it’s a small cost. But to be the fastest HTTP client on Java and Android we choose to be performance-conscious everywhere.

**Comment by leventov** [comment]
I have a concern now that if there is somebody who already wrap client calls in `managedBlock()` themselves are not penalized by starting an extra thread. We need to make sure nested `managedBlock()` calls are "benign": http://cs.oswego.edu/pipermail/concurrency-interest/2020-January/017053.html

**Comment by yschimke** [comment]
@leventov if you get active discussion on this, I guess what would help me would be.

 - Examples of other networking libraries that have adopted
 - correct places to put this, e.g. tight around specific blocking IO calls?  Should it also be around a DNS call? OR better to just put a single call around the Call.execute method?

**Comment by leventov** [comment]
Doug Lea responded that repetitive wrapping of code into `managedBlock()` may lead to creating an extra FJP thread unnecessarily. I think it makes not reasonable to proceed with this improvement because it would penalize prudent developers, which is very unfair.

**Comment by swankjesse** [comment]
Lets leave FJP up to the callers. Documenting how to do that well is a useful next step.

**Comment by yschimke** [comment]
Good example here https://docs.scala-lang.org/overviews/core/futures.html

With helper method in Scala `blocking { ... }`

**Comment by yschimke** [comment]
Won't fix.
