### ISSUE TITLE
Transparent gzip not working

### ISSUE THREAD

**Issue by Hajzenberg** [square/okhttp#5658]
okhttp doesn't transparently ungzip reponse, and I didn't manually add "Accept-Encoding" with value "gzip", as suggested here: https://github.com/square/okhttp/issues/2132#issuecomment-169500736

My response/request looks like this

REQUEST:
Request URL:XXXXX
Request Method:GET
Status Code:200 OK
Provisional headers are shown
Accept-Encoding:gzip
Authorization:Token token=XXXXX
Connection:Keep-Alive
Host:XXXXX
User-Agent:okhttp/4.2.2

RESPONSE:
Cache-Control:max-age=0, private, must-revalidate
Connection:keep-alive
Content-Encoding:gzip
Content-Type:text/plain; charset=utf-8
Date:Sat, 21 Dec 2019 14:02:51 GMT
ETag:W/"eb678bc2878357cc263335b7b5204006"
Server:nginx
Transfer-Encoding:chunked
X-Content-Type-Options:nosniff
X-Frame-Options:SAMEORIGIN
X-Powered-By:cloud66
X-Request-Id:f340d09a-4fab-4905-b6c7-eeffc93fe30c
X-Runtime:7.171759
X-XSS-Protection:1; mode=block

Note that Accept-Encoding:gzip was added automatically, not by me. The only header I have specified is Authorization.

I have implemented manual ungzipping in the interceptor, and it works, but I'm wondering, why doesn't okhttp does ungzipping it on it's own?

**Comment by swankjesse** [comment]
Put a breakpoint on line 91 here? Also if you can provide an executable test case to reproduce the problem that would be rad.

https://github.com/square/okhttp/blob/master/okhttp/src/main/java/okhttp3/internal/http/BridgeInterceptor.kt#L91

**Comment by yschimke** [comment]
@Hajzenberg please reopen with a test case if possible.
