### ISSUE TITLE
Content-Type header in multipart does not contain required parameter boundary

### ISSUE THREAD

**Issue by iamareebjamal** [square/okhttp#5660]
RFC: https://tools.ietf.org/html/rfc7578#appendix-A

Related Comment and issue: https://github.com/django/channels/issues/1386#issuecomment-568215439
https://twistedmatrix.com/trac/ticket/9739

### Background: 

Consider a multipart request as such:

Body:
```
--d66f495a-c4d1-487c-9277-9ab1a20001cc
Content-Disposition: form-data; name="content"
Content-Type: multipart/form-data; charset=utf-8

Anything
--d66f495a-c4d1-487c-9277-9ab1a20001cc--
```

Header:
`Content-Type: multipart/form-data; boundary=d66f495a-c4d1-487c-9277-9ab1a20001cc`

A new change in Python 3.7 considers this request multipart header as invalid, which according to @twm is not compliant with the latest change in the RFC (2015).

Hence, on new Python versions, when the request is parsed, it tries to get the boundary from the multipart body `Content-Type` header and it returns empty string since there is none, and throws saying that is is `Invalid Boundary`

**Comment by twm** [comment]
To be clear, this is the problem line:

```
Content-Type: multipart/form-data; charset=utf-8
```

`multipart/form-data` requires a `boundary`. That is why Python's `cgi` module is choking. However, the solution isn't to add a boundary &mdash; the content of this part isn't nested multipart. Instead, change the `Content-Type` header to match the actual content. Something like:

```
Content-Type: text/plain; charset=utf-8
```

Or, omit the `Content-Type` header entirely &mdash; only the `Content-Disposition` header is required.

**Comment by iamareebjamal** [comment]
Yes, that would work in this example as this is just a bare minimum example. Whereas in real world, the request contains form fields and a file in the multipart body and because the file is broken into multipart itself, it will fail again

**Comment by twm** [comment]
Sorry, I don't follow. Why would a file be split into multipart? Did you mean multiple files (`multipart/mixed`, [section 4.3](https://tools.ietf.org/html/rfc2388#section-4.2))? Or chunked transfer encoding, which happens at a different layer?

**Comment by iamareebjamal** [comment]
I'll attach the actual request soon to make it clear. I may be wrong here

**Comment by twm** [comment]
I don't see anything in https://github.com/square/okhttp/blob/master/okhttp/src/main/java/okhttp3/MultipartBody.kt that would generate this header. Nor do I see such sniffing here https://github.com/square/okhttp/blob/master/okhttp/src/main/java/okhttp3/RequestBody.kt Does your application code set it?

**Comment by iamareebjamal** [comment]
No, this is the API interface

```java
	@Multipart
    @POST("post/submit")
    Call<NewsPost> postStoryWithFiles(
            @Part("post_type") RequestBody postType,
            @Part("category_id") RequestBody categoryId,
            @Part("post_location_id") RequestBody locationId,
            @Part("title") RequestBody title,
            @Part("content") RequestBody content,
            @Part("keywords") RequestBody keywords,
            @Part("by_visitor") RequestBody byVisitor,
            @Part("by_page_admin") RequestBody byPageAdmin,
            @Part("page_id") RequestBody pageID,
            @Part List<MultipartBody.Part> files);
```

Then each post attachment is converted to parts and sent with the request

**Comment by swankjesse** [comment]
@iamareebjamal it looks like each of your `RequestBody` parameters should be created like so:

```
RequestBody.create(MediaType.get("text/plain"), "foo")
```

I think you’re creating them with a media type of `multipart/form-data` somehow and that’s not right.

**Comment by iamareebjamal** [comment]
Thanks. Will try and revert

**Comment by filipatbnp** [comment]
> Or chunked transfer encoding, which happens at a different layer?

@twm At which layer?
