### ISSUE TITLE
How to make get request support upload body？

### ISSUE THREAD

**Issue by ForgetSky** [square/okhttp#5664]
Start by telling us what problem you’re trying to solve. Often a solution already exists!

Don’t send pull requests to implement new features without first getting our support. Sometimes we leave features out on purpose to keep the project small.

**Comment by yschimke** [comment]
We won't support this, OkHttp strictly follows the RFCs and when they are a bit ambiguous follows conventions of browsers like Chrome and Firefox. It isn't setup to allow you to make "invalid" requests etc.
