### ISSUE TITLE
Okhttp3 is very slow

### ISSUE THREAD

**Issue by vinay-500** [square/okhttp#5665]
In okhttp3 - client.newCall(request).execute(); taking 0.58 seconds on an average. In the request call i am inserting some data in one table. And also i tested logs of request url, It is taking around 0.15-0.20 seconds to complete whole workflow. So where is remaining time around >0.3 seconds, can anyone explain where i am doing wrong?

**Comment by yschimke** [comment]
Please ask these types of questions on stackoverflow.

As a hint, use https://square.github.io/okhttp/events/ to output the timing
