### ISSUE TITLE
Remove most usage of wall clock time from tests

### ISSUE THREAD

**Issue by yschimke** [square/okhttp#5673]
e.g. replace https://github.com/square/okhttp/pull/5672/files

```
Thread.sleep(250)
```

With a count down latch, hopefully in a clean repeatable kotlin way e.g. some mini rendezvous design pattern.

**Comment by swankjesse** [comment]
I like using LinkedBlockingDeque for this kind of coordination.

**Comment by yschimke** [comment]
Potentially relates to https://github.com/square/okhttp/issues/2134

**Comment by yschimke** [comment]
Closing as low priority
