### ISSUE TITLE
App crashed while send request

### ISSUE THREAD

**Issue by qqcake** [square/okhttp#5681]
12-26 11:42:44.231  2227  9958 E AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
12-26 11:42:44.231  2227  9958 E AndroidRuntime: Process: net.oneplus.weather, PID: 2227
12-26 11:42:44.231  2227  9958 E AndroidRuntime: java.lang.IllegalArgumentException: port out of range:-1
12-26 11:42:44.231  2227  9958 E AndroidRuntime: 	at java.net.InetSocketAddress.checkPort(InetSocketAddress.java:144)
12-26 11:42:44.231  2227  9958 E AndroidRuntime: 	at java.net.InetSocketAddress.createUnresolved(InetSocketAddress.java:269)
12-26 11:42:44.231  2227  9958 E AndroidRuntime: 	at sun.net.spi.DefaultProxySelector$1.run(DefaultProxySelector.java:315)
12-26 11:42:44.231  2227  9958 E AndroidRuntime: 	at sun.net.spi.DefaultProxySelector$1.run(DefaultProxySelector.java:219)
12-26 11:42:44.231  2227  9958 E AndroidRuntime: 	at java.security.AccessController.doPrivileged(AccessController.java:43)
12-26 11:42:44.231  2227  9958 E AndroidRuntime: 	at sun.net.spi.DefaultProxySelector.select(DefaultProxySelector.java:218)
12-26 11:42:44.231  2227  9958 E AndroidRuntime: 	at f.h0.f.f.a(Unknown Source:20)
12-26 11:42:44.231  2227  9958 E AndroidRuntime: 	at f.h0.f.f.<init>(Unknown Source:34)
12-26 11:42:44.231  2227  9958 E AndroidRuntime: 	at f.h0.f.g.<init>(Unknown Source:13)
12-26 11:42:44.231  2227  9958 E AndroidRuntime: 	at f.h0.g.j.a(Unknown Source:22)
12-26 11:42:44.231  2227  9958 E AndroidRuntime: 	at f.h0.g.g.a(Unknown Source:140)
12-26 11:42:44.231  2227  9958 E AndroidRuntime: 	at f.h0.g.g.a(Unknown Source:6)
12-26 11:42:44.231  2227  9958 E AndroidRuntime: 	at e.a.a.f.b$b.a(Unknown Source:33)
12-26 11:42:44.231  2227  9958 E AndroidRuntime: 	at f.h0.g.g.a(Unknown Source:140)
12-26 11:42:44.231  2227  9958 E AndroidRuntime: 	at f.h0.g.g.a(Unknown Source:6)
12-26 11:42:44.231  2227  9958 E AndroidRuntime: 	at f.z.a(Unknown Source:94)
12-26 11:42:44.231  2227  9958 E AndroidRuntime: 	at f.z$a.b(Unknown Source:4)
12-26 11:42:44.231  2227  9958 E AndroidRuntime: 	at f.h0.b.run(Unknown Source:17)
12-26 11:42:44.231  2227  9958 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
12-26 11:42:44.231  2227  9958 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
12-26 11:42:44.231  2227  9958 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:919)

**Comment by swankjesse** [comment]
Executable test case please.

**Comment by wanggaohui** [comment]
![image](https://user-images.githubusercontent.com/40512643/115984085-c7964d80-a5d7-11eb-93f6-5920c7f2da53.png)


I also got the same problem

**Comment by huangyanan** [comment]
has the same problem,has anyone find what cause this crash?

**Comment by furusin** [comment]
me either

**Comment by san-sk** [comment]
what is cause of the crash or how to handle it?
