### ISSUE TITLE
POM description is "null"

### ISSUE THREAD

**Issue by koral--** [square/okhttp#5683]
POM of `com.squareup.okhttp3:okhttp:4.3.0` on Maven Central repo contains:
`<description>null</description>`
https://search.maven.org/artifact/com.squareup.okhttp3/okhttp/4.3.0/jar

I would rather expect something more descriptive like `An HTTP client for Android, Kotlin, and Java.`
Not sure if this is caused by okhttp not providing description or some issue with plugin you are using to deploy artifacts but first trying here.

**Comment by swankjesse** [comment]
Yeah I think we should probably omit the optional `<description>` field altogether. That’s what we did in 3.x. https://search.maven.org/artifact/com.squareup.okhttp3/okhttp/3.14.0/jar

**Comment by swankjesse** [comment]
I think we probably just wait for the publish plugin to fix this.
