### ISSUE TITLE
Is there a way to make logging less verbose?

### ISSUE THREAD

**Issue by AdityaAnand1** [square/okhttp#5694]
Would be great if there were a way to somehow hide away all the (what I deem to be) unnecessary stuff (in my use-case).

E.g: The following strings `INFO:`, `Jan 04, 2020 7:47:35 PM okhttp3.internal.platform.Platform log`

![image](https://user-images.githubusercontent.com/13274079/71766905-4e2ea380-2f2b-11ea-8a0e-cd3da1b087a7.png)

**Comment by yschimke** [comment]
This is an opt in feature. It's not enabled without the Logging interceptor.

**Comment by AdityaAnand1** [comment]
The issue is still valid. 

> Is there a way to make **opt-in** logging less verbose?

**Comment by yschimke** [comment]
The API itself allows you to log at different levels, have you tried those different levels?  

```
  enum class Level {
    /** No logs. */
    NONE,

    /**
     * Logs request and response lines.
     *
     * Example:
     * ```
     * --> POST /greeting http/1.1 (3-byte body)
     *
     * <-- 200 OK (22ms, 6-byte body)
     * ```
     */
    BASIC,

    /**
     * Logs request and response lines and their respective headers.
     *
     * Example:
     * ```
     * --> POST /greeting http/1.1
     * Host: example.com
     * Content-Type: plain/text
     * Content-Length: 3
     * --> END POST
     *
     * <-- 200 OK (22ms)
     * Content-Type: plain/text
     * Content-Length: 6
     * <-- END HTTP
     * ```
     */
    HEADERS,

    /**
     * Logs request and response lines and their respective headers and bodies (if present).
     *
     * Example:
     * ```
     * --> POST /greeting http/1.1
     * Host: example.com
     * Content-Type: plain/text
     * Content-Length: 3
     *
     * Hi?
     * --> END POST
     *
     * <-- 200 OK (22ms)
     * Content-Type: plain/text
     * Content-Length: 6
     *
     * Hello!
     * <-- END HTTP
     * ```
     */
    BODY
  }
```

What level is missing for you?

Also see previous responses to such issues or PRs? https://github.com/square/okhttp/pull/5173#issuecomment-500085763

> I think our logging interceptor is simple enough that if you wanna customize it, it's better to copy it into your project instead of growing the API for everyone.
