### ISSUE TITLE
Setup CI build for Android 5.0 and 11.0

### ISSUE THREAD

**Issue by yschimke** [square/okhttp#5704]
Need to catch Android regressions due to code changes or new OS releases

**Comment by yschimke** [comment]
Steal config from here https://twitter.com/colinwhi/status/1244426550918823937

**Comment by JakeWharton** [comment]
Also https://github.com/square/retrofit/blob/bcf07d0dffefb4ca1a33d431f5d38cab888b7d11/.github/workflows/build.yml#L40-L65

**Comment by yschimke** [comment]
I was playing around with our circleci docker images here

https://github.com/square/okhttp/pull/6103

I wonder whether we can build a docker image that we know works in 3 places

- circleci
- github
- locally (docker desktop

So we can test with the same results against all 3 environments.
