### ISSUE TITLE
Okhttp user cached data when the system time is wrong

### ISSUE THREAD

**Issue by 543441727** [square/okhttp#5712]
Hi ,I found when the mobile system time is wrong 2015.01.01  .okhttp get the  cached data. Even though my phone is connected to the Internet.I want to know the reason

**Comment by yschimke** [comment]
This sort of question is better for stackoverflow. My guess is the cache data won’t expire for 5 years and SSL certs won’t be valid until another 5 years passes!

This report is not in a reproducible form as is. And not sure we generally consider this definable behaviour.
