### ISSUE TITLE
source.readUtf8LineStrict(headerLimit)    java.net.SocketTimeoutException: timeout

### ISSUE THREAD

**Issue by jikun2008** [square/okhttp#5719]
when i use  websocket  

```java
   Request request = new Request.Builder()
                .url("ws://192.168.3.107:8072/driver")
                .build();
            okHttpBuilder = new OkHttpClient.Builder()
     
                    .readTimeout(500, TimeUnit.MILLISECONDS) 
okHttpClient.newWebSocket(request, webSocketListener);

```
i use this code it cause java.net.SocketTimeoutException: timeout
but when i  change code 
```
 .readTimeout(500, TimeUnit.SECONDS) 
```
the websocket connect success 

i think is some thing  is wrong. 
it  shouldn't spend so long time
for a while 
if found what happen  in okhttp code  
```
Http1ExchangeCodec.class 
  override fun readResponseHeaders(expectContinue: Boolean): Response.Builder? {
    check(state == STATE_OPEN_REQUEST_BODY || state == STATE_READ_RESPONSE_HEADERS) {
      "state: $state"
    }

    try {
      val statusLine = StatusLine.parse(**readHeaderLine()**)
}.....
```

```
  private fun readHeaderLine(): String {
    **val line = source.readUtf8LineStrict(headerLimit)**
    headerLimit -= line.length.toLong()
    return line
  }
```
i debug it 
val line = source.readUtf8LineStrict(headerLimit) is too slow 
but var line ="HTTP/1.1 101 "  
line it not big just "HTTP/1.1 101 "  can you fix it?  
i also can help you. if you want some code

**Comment by JakeWharton** [comment]
This seems to be working as intended. 500ms is far too low of a timeout unless the server is on the same machine or colocated very close by on the same network. For a server that's accessed over the internet you'll want something on the order of seconds. And for mobile, you should double or triple that value. The default is 10 seconds which should be suitable, is there a reason that won't do?

**Comment by jikun2008** [comment]
my service and phone is in same wifi 。 i will be try it angain .  i try it with 10s is  fine. but also  connect too slow  but success。 i dont konw what happen。 it seem not good  but i will test it on   ali yun service Tomorrow

**Comment by swankjesse** [comment]
Unclear what action to take here.
