### ISSUE TITLE
Limit retry count for authentication challenge

### ISSUE THREAD

**Issue by i-schuetz** [square/okhttp#5725]
I'd like to be able to limit the retry count in Authenticator to 3. At the moment it appears to be 20. I don't see anything to do this and didn't get an answer in [StackOverflow](https://stackoverflow.com/questions/59680324/limit-retry-count-of-authenticator), so assuming it's not possible at the moment.

**Comment by swankjesse** [comment]
I think we'd benefit a lot from adding more documentation to Authenticator. I think that's the best approach to fixing this.

**Comment by i-schuetz** [comment]
Someone linked to the recipe, in SO. I wonder if it would not be possible to add a config parameter for this, since you have already the retry limit internally? Incrementing a counter in Authenticator and retuning `null` seems hacky IMO.

**Comment by swankjesse** [comment]
Yeah, that was me on StackOverflow. What I’m (possibly foolishly) trying to optimize for is making it easy for you to implement your own policies. You might want a limit of 3 attempts, but you might also want to permit more attempts if each attempt uses different credentials.

**Comment by yschimke** [comment]
A kotlin extension method also available as a Java utility method could be useful here.

**Comment by Simonida** [comment]
Is it still possible to configure the retry count (okhttp version 4.9.0)?
Because an error pops up when setting function like this (but in Kotlin) https://user-images.githubusercontent.com/231923/81386588-25066580-910d-11ea-8015-b95a3d5ca483.png
`Using 'priorResponse(): Response?' is an error. moved to val`

**Comment by yschimke** [comment]
Yep - just follow the instructions it gave you.  Intellij should even apply the fix for you.  In Kotlin `response.priorResponse()` becomes just `response.priorResponse`
