### ISSUE TITLE
Unable to create newPin: Invalid pattern https://certs-qa.somedomain.ru/v1/

### ISSUE THREAD

**Issue by Jacks0N23** [square/okhttp#5804]
```
val certificatePinner = CertificatePinner.Builder()
                .add(url, pin(certificate))
                .build()
```

if url containt https and slashes after host it consider invalid, but why?

I upgrade after 3.12 to 4.4.0 and saw this bug.
But if downgrade to 4.2.0  - it's all ok

**Comment by swankjesse** [comment]
We used to silently ignore invalid patterns. See the syntax here and make sure you fix your pins to work in OkHttp 4.4, otherwise they won’t get used at all.
https://square.github.io/okhttp/4.x/okhttp/okhttp3/-certificate-pinner/
