### ISSUE TITLE
MockWebServer should allow GET with a body

### ISSUE THREAD

**Issue by lazystone** [square/okhttp#5852]
`okhttp3.internal.http.HttpMethod` forbids having body on GET request:

```
fun permitsRequestBody(method: String): Boolean = !(method == "GET" || method == "HEAD")
```

While I agree that this is a bad practice to use GET with a body, problem is that we have to work with 3rd party APIs which no one will ever change and they do demand GET with a body.

In this case it's a huge show-stopper for us :(

I propose to either remove GET from permitsRequestBody or at least make it somehow configurable.

Or, at least remove this validation from MockWebServer.

**Comment by yschimke** [comment]
This is by design and to spec.  See also https://github.com/square/okhttp/issues/5803

**Comment by lazystone** [comment]
@yschimke could you point out to the specs? I think that they do not forbid GET+body explicitly.

[Elasticsearch](https://www.elastic.co/guide/en/elasticsearch/guide/current/_empty_search.html#get_vs_post)(and they actually prefer GET+body) say that RFC 7231 does not forbid get+body.

So, saying that it's forbidden by spec is not true I believe.

And don't get me wrong - I don't like GET+body, but forbidding something which is allowed by specs making okhttp unusable in some cases.

There are other ways to encourage best practices as Spring Framework does for example - they do not allow body in their builder when you use `.get()` but in order to allow user provide body on GET request they have another API call `.method(HttpMethod.GET).body(...)`.

**Comment by yschimke** [comment]
Sorry. But no current plans to support this.

**Comment by swankjesse** [comment]
I'm under the impression that the weird Elasticsearch endpoint that uses a GET body is also available as a POST.

**Comment by lazystone** [comment]
Elasticsearch was just an example - there are other APIs which use the same approach. As I mentioned before - it's not forbidden by specs to use GET+body.

Also fixing this is one line change in `okhttp3.internal.http.HttpMethod`

**Comment by yschimke** [comment]
@lazystone It's a deliberate opinionated decision.  Not something that was missed.

**Comment by lazystone** [comment]
That's Ok, but then please stop saying that it's forbidden by specs, because it's not true.

If you deliberately restrict some functionality - be fair. Say that you forbid it because you don't like it, not because it violates HTTP specs.

**Comment by swankjesse** [comment]
> Also fixing this is one line change in okhttp3.internal.http.HttpMethod

Changing Boolean to support a new value `probably` value is also a simple one line change!

We don't want GET to have bodies because it adds more work for people using it:

 * the cache needs to change to not cache GET requests with body
 * interceptors can no longer assume GET requests lack a body for caching and logging
 * URLs for GET requests no longer uniquely identify the request
 * Existing code that includes a length header like `Transfer-Encoding: chunked` in GET requests will require the corresponding bytes or crash

One of the major benefits of the GET request is that it doesn't include a body! And that makes it easier to work with. That the Elastic maintainers don't appreciate this is their foolishness. I won't subject OkHttp’s users to that unnecessary complexity so they can be cute.

**Comment by lazystone** [comment]
As I said above:
> That's Ok, but then please stop saying that it's forbidden by specs

I'm OK with maintainers decision to not support something. I do understand that if you considered GET+body as impossible then there are might be some dark corners in the code that need to be fixed in order to support this. That is OK.

If you are honest about that, then you can add little "known limitations" somewhere on [this page](https://square.github.io/okhttp/#requirements).

But just closing tickets with "forbidden by specs" or "it's by design" is wrong I believe, because first of all it's not forbidden and then you don't give a chance for somebody else to contribute.

**Comment by yschimke** [comment]
@lazystone I said this once at the top of the thread.  And saying it is to spec is just as correct as saying it is against the spec.  The spec is ambiguous here.  I also included our rational when things are ambiguous e.g. we follow best practices from browsers etc.

But I *promise* I will stop saying it's forbidden by the spec.

> This is by design and to spec. See also #5803
> 
> Sorry we can't help here. OkHttp is quite opinionated in following the Spec (doing things correctly) and following the browsers (Firefox, Chrome) and very common servers (Nginx, Apache etc) when it's ambiguous.

**Comment by mizosoft** [comment]
I'm facing the same issue and it's hindering my tests. I think the reasoning given here totally misses the topic of this issue, which is to make `MockWebServer` lenient with GETs with a body, not `OkHttpClient`. I believe it's totally understandable for `OkHttpClient` to disallow bad practices, but that's a weird thing to be done by `MockWebServer`. It should be able to allow scenarios that are disallowed by OkHttp's opinionated decisions, as these facilitate testing corner cases. Heck, `SocketPolicy` is full of switches that allow simulating totally disastrous scenarios, why can't accepting a GET with a body be one of them?

**Comment by yschimke** [comment]
@mizosoft I understand why it's frustrating to you. It's a reasonable request. But we generally choose to make OkHttp and MockWebServer opinionated libraries to keep a focus on the "correct" way of doing things.

For MockWebServer and HttpLoggingInterceptor there are a bunch of individual feature requests that individually might make borderline sense, but in aggregate would cause a lot of feature creep over time, and maintenance, that we choose to opt out of.  For HttpLoggingInterceptor it's small enough that we just advise people to copy and paste it and make it fit their needs.  That probably isn't as appealing with MockWebServer but it's likely the honest answer here. 

If MockWebServer was a standalone project we would probably encourage way more innovation of it.

**Comment by mizosoft** [comment]
I think I understand your philosophy. I just don't get why it's strictly applied on something like `MockWebServer`. I think it should allow these scenarios even if they're questionable since I believe one of its goals is testing corner cases & misbehaves? 

I think forking `MockWebServer` isn't totally viable. I don't feel like switching either as `MockWebServer` seems better & way simpler than alternatives. I currently have no option but to disable tests with GETS + body.

**Comment by lazystone** [comment]
> I currently have no option but to disable tests with GETS + body.

That's for sure looks like best practices /s

@mizosoft give a try to https://www.mock-server.com/

**Comment by mizosoft** [comment]
@lazystone Thanks for the suggestion. The last time I tried to use mock-server it wasn't operable with Java 9 modules. This is a bummer as I'm targeting Java 11. I believe that's still the case.

**Comment by yschimke** [comment]
@lazystone Thanks for the link.  That project looks great, and a good argument for why OkHttp's MockWebServer doesn't need to try to be everything for everyone. I don't think the OkHttp maintainers have time to compete with a well funded project like that. Fixing the issues like JDK 11 support in that project is probably the way forward.
