### ISSUE TITLE
Status code is not standard in status line,like 6004963,then throw a exception

### ISSUE THREAD

**Issue by hongui** [square/okhttp#5865]
I find method parse in class StatusLine parse status line fix in 3 digits,if status line is not standard line,then request is failed.

**Comment by swankjesse** [comment]
True story!

**Comment by zchtcl** [comment]
Why close this ?
you can completely split different parts by spaces, wish to change

**Comment by swankjesse** [comment]
What’s your use case? Limiting to 3 digits is a feature.

**Comment by zchtcl** [comment]
The implementation of `HttpURLConnection.getResponseCode()` in Android splitS status code and reason phrase by space.

The format in https://www.w3.org/Protocols/rfc2616/rfc2616-sec6.html likes this
> Status-Line = HTTP-Version SP Status-Code SP Reason-Phrase CRLF
each element separates by SP

So we should not assume that the status code must be a 3-digit number, it's just a number

**Comment by JakeWharton** [comment]
RFC 2616 was obsoleted by RFC 7230 which itself was obsoleted by RFC 9112.

[RFC 9112](https://datatracker.ietf.org/doc/html/rfc9112#name-status-line) says

> The status-code element is a 3-digit integer code describing the result of the server's attempt to understand and satisfy the client's corresponding request.

**Comment by zchtcl** [comment]
Thanks for providing RFC, now I can convince the backend developers ~ ^_^
