### ISSUE TITLE
OkHttp public API for X509ExtendedTrustManager

### ISSUE THREAD

**Issue by yschimke** [square/okhttp#5870]
As seen in https://github.com/square/okhttp/pull/5868/files there isn't a common API to implement a TrustManager on Android and JVM to do something like allow devserver, or alternative host validation.  n.b. We only need to do the client side i.e. checkServerTrusted.

javax.net.ssl.X509ExtendedTrustManager is Android API 21+

The Android alternative is duck typed to

```
  /**
   * Android method to clean and sort certificates, called via reflection.
   */
  fun checkServerTrusted(chain: Array<out X509Certificate>, authType: String, host: String): List<Certificate>
```

It would be nice to have a OkHttpX509TrustManager that implemented a common OkHttp API, that we could bridge to Android and JVM via Platform.  This sub-interface of TrustManager would be detected via instanceof checks, and we could wire it up correctly.

```
  val client = OkHttpClient.Builder()
      .sslSocketFactory(sslSocketFactory, trustManager)
      .build()
```

**Comment by swankjesse** [comment]
Rather than providing an interface, should we just provide the implementation? My expectation is that most developers don’t want anything novel in a trust manager; they want some behavior that is currently only available by implementing that interface.

**Comment by yschimke** [comment]
What are the sort of things people would want to do?

- Turn off all checks (insecure)
- Turn off some checks (allowlist)
- (Maybe) Add own checks (outside cert cleaning, pinning and hostname verification?)

The issue with the implementation only is that you can't have a class that implements the JVM X509ExtendedTrustManager.  So I can make a base class that extends TrustManager with an additional method taking host, returning boolean if it passes.

**Comment by yschimke** [comment]
Going to just add the insecure option in https://github.com/square/okhttp/pull/5872
