### ISSUE TITLE
Caused by: java.lang.IllegalStateException: Unable to extract the trust manager on Android10Platform, sslSocketFactory is class com.android.org.conscrypt.OpenSSLSocketFactoryImpl

### ISSUE THREAD

**Issue by andnux** [square/okhttp#5878]
Process: com.chaincat.wallet, PID: 8914
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.chaincat.wallet/top.andnux.moudles.base.ui.main.MainActivity}: java.lang.IllegalStateException: Unable to extract the trust manager on Android10Platform, sslSocketFactory is class com.android.org.conscrypt.OpenSSLSocketFactoryImpl
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3333)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3477)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2043)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7464)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:549)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:955)

**Comment by yschimke** [comment]
I assume you are calling the deprecated form of sslSocketFactory, which is broken on newer Android versions.

https://github.com/square/okhttp/blob/master/okhttp/src/main/java/okhttp3/OkHttpClient.kt#L719

```
    /**
     * Sets the socket factory used to secure HTTPS connections. If unset, the system default will
     * be used.
     *
     * @deprecated [SSLSocketFactory] does not expose its [X509TrustManager], which is a field that
     *     OkHttp needs to build a clean certificate chain. This method instead must use reflection
     *     to extract the trust manager. Applications should prefer to call
     *     `sslSocketFactory(SSLSocketFactory, X509TrustManager)`, which avoids such reflection.
     */
    @Deprecated(
        message = "Use the sslSocketFactory overload that accepts a X509TrustManager.",
        level = DeprecationLevel.ERROR
    )
    fun sslSocketFactory(sslSocketFactory: SSLSocketFactory) = apply {
      if (sslSocketFactory != this.sslSocketFactoryOrNull) {
        this.routeDatabase = null
      }

      this.sslSocketFactoryOrNull = sslSocketFactory
      this.certificateChainCleaner = Platform.get().buildCertificateChainCleaner(sslSocketFactory)
    }
```

**Comment by yschimke** [comment]
Fix is required in client code.

**Comment by nysin** [comment]
这个问题是在okhttp那个版本上修复的

**Comment by spwCoding** [comment]
> 这个问题是在okhttp那个版本上修复的

貌似没有修复。

**Comment by 1181631922** [comment]
貌似还没修复

**Comment by xyldrun** [comment]
Has anyone found a work around for this? I'm working on a legacy project and we do not have enough resources yet to refactor the entire module.

**Comment by yschimke** [comment]
There isn't a workaround, that method has been deprecated for 6 years. The client code needs to call the form with two parameters, precisely because we can't reliable extract the trust manager on all various versions of Android, especially including future versions with different ssl socket implementations.

If you can find a workaround in your client code for this, presumably you could just call the two param method instead.

**Comment by xyldrun** [comment]
> There isn't a workaround, that method has been deprecated for 6 years. The client code needs to call the form with two parameters, precisely because we can't reliable extract the trust manager on all various versions of Android, especially including future versions with different ssl socket implementations.
> 
> If you can find a workaround in your client code for this, presumably you could just call the two param method instead.

Thank you, @yschimke.

**Comment by chitgoks** [comment]
Just use the 2 param method. worked for me.
builder.sslSocketFactory(sslSocketFactory, (X509TrustManager) trustAllCerts[0]);

**Comment by mohsinbmwm3** [comment]
Hi, in my case 
compile 'com.squareup.retrofit2:retrofit:2.0.2'
    compile 'com.squareup.retrofit2:converter-gson:2.0.2'
    compile 'com.squareup.okhttp3:logging-interceptor:3.2.0'
these 3 dependeicies are being used, now which one should i upgrade to 
user builder.sslSocketFactory(sslSocketFactory, (X509TrustManager) trustAllCerts[0]); this method?
