### ISSUE TITLE
GMS and Conscrypt don't negotiate HTTP/2 on Android 10+ and 3.12.x 

### ISSUE THREAD

**Issue by yschimke** [square/okhttp#5884]
From https://github.com/square/okhttp/issues/5879

3.12.9 added Android10Platform which IIRC we did to avoid issues with graylisted (and eventually blacklisted in 11) APIs via Reflection. So we backported it from 4.x.

c2e9ee2#diff-55fc33d7feaf12483a0809e1db851f58

**Comment by yschimke** [comment]
We can fix in one of two ways

1) Backport all of SocketAdapter from 4.4 kotlin to 3.12 Java
2) Bump the Android10 check to Android 11+, but will still fail on Android 11

**Comment by yschimke** [comment]
I'm going to close in a week unless we decide to support.  It is working with security on older Android, just not with Android 10+.  I don't personally view this as a critical security fix.

Workaround for app developers is an app bundle with older features for < Android 5.
https://developer.android.com/google/play/publishing/multiple-apks

**Comment by swankjesse** [comment]
I think HTTP/1 is fine for Android 10+ on OkHttp 3.12.x.
