### ISSUE TITLE
Timeout HTTP 1.0/1.1 requests when no data has been sent in either direction for some time.

### ISSUE THREAD

**Issue by LukeButters** [square/okhttp#5893]
I would like to use okhttp to upload large files or download large files. This operation is not always running on a reliable connection or fast one. In strange cases connections seem to get stuck and no more data is sent back down or uploaded. In this case we can use timeouts to give up on problematic connections. Although this generally works the timeouts offered are surprising and probably not what anyone wants.

The timeouts offered are:
* write timeout.
* read timeout.

These don't really make any sense because:
* I doubt anyone wants a write timeout to occur when data is being downloaded.
* I doubt anyone wants a read timeout to occur when data is being uploaded. See https://stackoverflow.com/questions/60751152/ok-http-to-only-time-out-when-no-data-has-been-sent-or-recieved-for-some-time 

The timeout that I suspect users want (and probably expect) is a timeout which times out when **no data has been sent in either direction** rather than timeouts that timeout when data hasn't been sent in one direction even though data might be flowing in the other direction.

like most useful features I suspect this will be a little harder to implement than the other two timeouts.

**Comment by swankjesse** [comment]
HTTP is never concurrently attempting a read and a write; it's either one or the other. You can set both timeouts to achieve what you've specified.

**Comment by LukeButters** [comment]
Ah so maybe what my test is showing is that okhttp has written all data it thinks it needs to. That data has not arrived to the server. okhttp is now in a state of waiting for the server to respond but it wont respond until the data has actually arrived .

Ah I didn't realise that HTTP wont let you read and write at the same time, I assume this means it wont let a client write some data , then read some data then write some more data.
