### ISSUE TITLE
Read error: ssl=0xba7d7378: I\\/O error during system call, Software caused connection abort

### ISSUE THREAD

**Issue by xiemuyou** [square/okhttp#5900]
There was no way to redo it when it was developed,Exceptions collected by online users

**Comment by xiemuyou** [comment]
ErrInfo : Read error: ssl=0xba7d7378: I\\/O error during system call, Software caused connection abort
PhoneModel : Android BKL-AL20
SystemVersion : 10
-------------------------
ErrInfo : Read error: ssl=0xb13a9fd8: I\\/O error during system call, Software caused connection abort
PhoneModel : Android VOG-AL00
SystemVersion : 10
-------------------------
ErrInfo : Read error: ssl=0xd4346008: I\\/O error during system call, Software caused connection abort
PhoneModel : Android ELE-AL00
SystemVersion : 10
-------------------------
ErrInfo : Read error: ssl=0xd5cde208: I\\/O error during system call, Software caused connection abort
PhoneModel : Android VCE-AL00
SystemVersion : 10
-------------------------
ErrInfo : Read error: ssl=0xc10062c8: I\\/O error during system call, Software caused connection abort
PhoneModel : Android TAS-AL00
SystemVersion : 10
-------------------------
ErrInfo : Read error: ssl=0xc48680c0: I\\/O error during system call, Software caused connection abort
PhoneModel : Android vivoX21A
SystemVersion : 8.1.0
--------------------------
more ....

**Comment by yschimke** [comment]
There isn't anything we can do with this report. No repro, no information.

**Comment by 793383996** [comment]
Problems caused by downloading and disconnecting the network

**Comment by CodeMAI** [comment]
Me too，Have you solved it? How did you solve it?

**Comment by 793383996** [comment]
I checked the status of the network and did not request if there was no network.
