### ISSUE TITLE
🙉Commercial Usage of okhttp

### ISSUE THREAD

**Issue by hi2rashid** [square/okhttp#5915]
Can we use OkHTTP for commercial purpose.

Our start up is using okhttp java version.

**Comment by yschimke** [comment]
Yes.  Without restrictions.

See https://github.com/square/okhttp/blob/master/LICENSE.txt

<img width="999" alt="image" src="https://user-images.githubusercontent.com/231923/78008284-6437de80-7337-11ea-94e8-7e6419b6c9f2.png">
