### ISSUE TITLE
Potential copyright infringement 

### ISSUE THREAD

**Issue by Dinth** [square/okhttp#5922]
Hi. Sorry for opening a question here, but I wanted to let okhttp developers know that iOS and Android apps released by Poland's Home Office are reportedly (according to this post: https://github.com/OpenSC/OpenSC/issues/1992#issuecomment-609399574) using okhttp code linked statically, without a mention of using okhttp code in their license.

**Comment by yschimke** [comment]
@swankjesse Is this even an issue for our Apache license? OpenSC is GNU Lesser General Public License v2.1.

n.b. I'm not making any statement on this, IANAL.

**Comment by Dinth** [comment]
Isnt in breach of article 4A of the license?

**Comment by swankjesse** [comment]
This isn’t copyright infringement. At worst it’s an oversight to include a license file that's widely available online.

We will not take further action on this.
