### ISSUE TITLE
Deprecate PlainText only support

### ISSUE THREAD

**Issue by yschimke** [square/okhttp#5940]
Forked from https://github.com/square/okhttp/issues/3773

There is probably a time when removing plaintext only support is worthwhile, would simplify some code in OkHttpClient.  Or making it non-default.

**Comment by swankjesse** [comment]
We can turn off plaintext today via `ConnectionSpec`, though it’s not the default.

Changing defaults here is really annoying to our userbase, especially since the places OkHttpClients get configured are not necessarily the places that know whether plaintext is available.
