### ISSUE TITLE
GZIP: java.io.EOFException: source exhausted prematurely

### ISSUE THREAD

**Issue by Dogwei** [square/okhttp#5951]
![QQ截图20200414111541](https://user-images.githubusercontent.com/14845492/79182397-4abb8a00-7e41-11ea-9444-a4a1f1de4132.png)

This error is raised when the server turns on GZIP compression.
Java client code:

![QQ截图20200414110117](https://user-images.githubusercontent.com/14845492/79182334-2069cc80-7e41-11ea-880e-9edf137d5798.png)

c# server code:

![QQ截图20200414110729](https://user-images.githubusercontent.com/14845492/79182262-00d2a400-7e41-11ea-8aeb-da577f8b15ee.png)

**Comment by yschimke** [comment]
Could you either

a) Post a simpler example e.g. a failing test case using MockWebServer and some example bytes from your webserver.
b) Post your question on stackoverflow and ask for advice? 

Please Reopen with a reproducible bug, this isn't reproducible as is.

**Comment by otacu** [comment]
request header add Accept-Encoding=text/html
