### ISSUE TITLE
ConnectionPool ThreadPool why use Integer.MAX_VALUE maximumPoolSize param ?

### ISSUE THREAD

**Issue by fudali113** [square/okhttp#5963]
https://github.com/square/okhttp/blob/25186b401fef60ae48c47716d3db3f2a6bf6521b/okhttp/src/main/java/okhttp3/internal/connection/RealConnectionPool.java#L47

i use okhttp3 in back-end service，when big QPS to service will threw OOM exception;

because maximumPoolSize is Integer.MAX_VALUE，thread growing too fast，no memory to create native thread.

Are okhttp back-end services not recommended?

**Comment by yschimke** [comment]
Please post your question on a forum like stackoverflow, this isn't a reproducible bug as is.  We can answer there as well as the broader user community.

If you drop a link here, we can continue the discussion there.
