### ISSUE TITLE
Allow to directly set a java.net.Authenticator

### ISSUE THREAD

**Issue by sschuberth** [square/okhttp#5967]
As a follow-up to @swankjesse's [comment](https://github.com/square/okhttp/issues/4108#issuecomment-616665380), it would be nice to have an overload of `OkHttpClient.Builder.proxyAuthenticator()` that takes a `java.net.Authenticator`, so we could e.g. do

    OkHttpClient.Builder().proxyAuthenticator(java.net.Authenticator.getDefault()).build()

This would be in line with `OkHttpClient.Builder.proxySelector()` which takes a `java.net.ProxySelector`, and ease the OkHttp client setup for programs that already properly set standard JRE's `java.net.ProxySelector` and `java.net.Authenticator`.

**Comment by yschimke** [comment]
Is it this simple? https://github.com/square/okhttp/pull/5978

**Comment by yschimke** [comment]
There is a broader fix possible using reflection to allow any implementation of java.net.Authenticator without global registration, but this is not it.

**Comment by sschuberth** [comment]
Thanks for implementing this so quickly!

**Comment by sschuberth** [comment]
> There is a broader fix possible using reflection to allow any implementation of java.net.Authenticator without global registration, but this is not it.

But couldn't this have been done without reflection by adding an overloaded `proxyAuthenticator()` function to the builder that takes a `java.net.Authenticator` as the parameter, as suggested in my initial post?

**Comment by yschimke** [comment]
Have a look at the java.net.Authenticator API and implementation.  It's cursed, a weird mixture of static methods and subclassing.
