### ISSUE TITLE
Exception thrown in case of 304

### ISSUE THREAD

**Issue by diegocstn** [square/okhttp#5968]
Hi,
I'm experiencing an issue with okhttp in a React Native project.

When a request has a 304 status, a `Content-Length and stream length disagree` exception is being thrown :
https://github.com/square/okhttp/blob/ff0dee1c34fc06084357c93dc480f6ad89fef24a/okhttp/src/main/java/okhttp3/ResponseBody.kt#L148

Based on my knowledge, if the response has the `Content-length` header, it should be equal to the number of octects of the corresponding 200 response body.
In my case, the response has a `Content-length` value different than 0 but the stream is empty.
Is the stream empty because the previous 200 response hasn't been cached?

**Comment by yschimke** [comment]
Can you provide a repro or a test URL for us?

**Comment by diegocstn** [comment]
Unfortunately I can't provide a url, here's the two requests headers:
```

:status: 200
date: Wed, 22 Apr 2020 02:47:25 GMT
content-type: application/json
content-length: 715
x-custom-header: customheadervalue
```

```
:status: 304
date: Wed, 22 Apr 2020 02:50:06 GMT
content-type: application/json
content-length: 57
x-custom-header: customheadervalue
```

Does the `Content-length` play a role in how the request is retrieved from the internal cache? Is there anything I can do on my side to help you and to verify the current cache behavior?

**Comment by yschimke** [comment]
I suggest asking on stackoverflow, this isn't a reproducible bug.  Sorry.
