### ISSUE TITLE
From release 4.0.0, we can't get OkHttp version from okhttp3.internal.Version.userAgent()

### ISSUE THREAD

**Issue by Kevinrob** [square/okhttp#5969]
In our application, we set user agent with custom information but we also add OkHttp version at the end by adding `okhttp3.internal.Version.userAgent()`.
```kotlin
import okhttp3.internal.Version

[...]

val userAgent = "Example_app/${BuildConfig.VERSION_CODE} (${Build.BRAND}/${Build.MODEL}; Android/${Build.VERSION.RELEASE}) ${Version.userAgent()}"
```

Since OkHttp 4.0.0, the okhttp3.internal package is not a published API.
Can we move `Version.userAgent()` outside this package or maybe we can add a way to get OkHttp version or default user agent?

**Comment by yschimke** [comment]
This seems fair. We should work out the API we want.

For a workaround you can copy paste the method logic.

**Comment by Kevinrob** [comment]
[In the source](https://github.com/square/okhttp/blob/parent-4.0.0/okhttp/src/main/java-templates/okhttp3/internal/Version.kt), I see:
```kotlin
@file:JvmName("Version")
package okhttp3.internal

const val userAgent = "okhttp/$projectVersion"
```

How can I get `projectVersion` from my application?

PS: I can help with a PR that expose something like `defaultUserAgent`

**Comment by yschimke** [comment]
Sorry, I was thinking we were reading from a META-INF package version or similar.  It does make me wonder whether the right API is the Java package implementation version, rather than a new public method.

Feel free to submit a PR.
