### ISSUE TITLE
Android PublicSuffix topPrivateDomain results don't match.

### ISSUE THREAD

**Issue by nauman404** [square/okhttp#5997]
Hi,

I am using two methods to get top Private domains but it returns a false result with "web.app" TLD.

1:
String domain = PublicSuffixDatabase.Companion.get().getEffectiveTldPlusOne("anything.web.app");

2:
String domain1 =  HttpUrl.Companion.get("http://anything.web.app").topPrivateDomain();

I guess the library is using old public suffix data. If it is then how to update public suffix DB?

**Comment by swankjesse** [comment]
oooh, we should update.

**Comment by swankjesse** [comment]
https://github.com/square/okhttp/pull/5998
