### ISSUE TITLE
Log MDC while logging request and response

### ISSUE THREAD

**Issue by shubh1m** [square/okhttp#6001]
Is there a way currently to log MDC using LoggingInterceptor? In production env, without logging MDC, is there a way to stitch the logs

**Comment by swankjesse** [comment]
Consider writing your own logging interceptor! It's pretty easy.

**Comment by yschimke** [comment]
Closing as we won't take direct dependency on any logging libraries except JUL and Android logging.

**Comment by yschimke** [comment]
@shubh1m If you get a good code sample, consider posting on stackoverflow and I'll upvote.
