### ISSUE TITLE
EventListener's callend method will not be called

### ISSUE THREAD

**Issue by KaiXuan666** [square/okhttp#6006]
![image](https://user-images.githubusercontent.com/15888816/80575451-3331f300-8a36-11ea-84f2-788a523ecb2a.png)
![image](https://user-images.githubusercontent.com/15888816/80575467-3c22c480-8a36-11ea-8ae2-8020f773583f.png)
As shown in the figure, the callend method has never been called
Okhttp version is 3.12.10

**Comment by swankjesse** [comment]
Are you closing the response body?
Please send an executable test case.

**Comment by yschimke** [comment]
Please reopen with a reproduction and confirmation that you are closing the response body.
