### ISSUE TITLE
Retrying a failed PUT request corrupts data

### ISSUE THREAD

**Issue by vyelevich** [square/okhttp#6013]
Hi folks! 
We've noticed a change in behavior between 3.13.1 -> 3.14.0 which looks to corrupt the destination data on a PUT when retrying the same request. When uploading with okhttp from an input stream in our application we sometimes see IOException's from our input stream due to an unreliable input source from our clients. Since 3.14.0 when we retry the PUT request it looks like the same connection is being reused for the second request and the data which is being uploaded is actually concatenated with the HTTP request data for the second request. Example:  "PUT /debug ..." from the second request.

I've put together an example which demonstrates this behavior.
[okhttp-retry-output-corruption](https://github.com/vyelevich/okhttp-retry-output-corruption)

```
./gradlew test
...
org.junit.ComparisonFailure: expected:<[Some data.]> but was:<[PUT /debug]>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at UploaderTest.uploadDataMatchesReceivedData(UploaderTest.java:23)
```

The issue is illustrated [here](https://github.com/vyelevich/okhttp-retry-output-corruption/blob/master/src/main/java/Uploader.java) when the first upload call fails (in our case due to an IO error) and **fewer bytes were sent than the content length**.

```
        //First try to upload with a body which fails to read source stream
        try {
            logger.info("Produce error while reading body");
            uploadStream(url, createRequestBodyFailsDuringIO(data.length()));
        } catch (Throwable e) {
            logger.info("Handling upload error", e);
        }

        //Second try - should be OK
        try (InputStream inputStream = new ByteArrayInputStream(data.getBytes())) {
            logger.info("No EOF");
            long contentLength = data.length();
            uploadStream(url, createRequestBodyHappyPath(inputStream, contentLength));
        }
```

This looks like a connection reuse issue, since setting the connection pool with 0 maxIdleConnections addresses the problem, but we're left without connection pooling.
```
new ConnectionPool(0, 10, TimeUnit.MILLISECONDS)
```
Since we have no handle on the connection, there is no way for us to close or cancel the request without evicting all connections from the pool. 

Please let me know if further info is needed.

**Comment by yschimke** [comment]
@vyelevich Thanks for the amazingly good test case.  It's a rarity.

**Comment by yschimke** [comment]
The test passes on 4.6.0, so consider upgrading.  Support for 3.14.x will stop at end of June, and we'll continue supporting 3.12.x (for legacy Android) and 4.x only.

**Comment by yschimke** [comment]
I suspect that the fix comes here in 4.3.0

```
@@ -204,6 +205,7 @@ class Transmitter(
   fun exchangeDoneDueToException() {
     synchronized(connectionPool) {
+      exchange?.detachWithViolence()
       check(!noMoreExchanges)
       exchange = null
     }
```

**Comment by yschimke** [comment]
@vyelevich debugging is easier with EventListener

```
     private OkHttpClient newOkHttpClient() {
         return new OkHttpClient.Builder()
-                .addInterceptor(new HttpLoggingInterceptor().setLevel(HttpLoggingInterceptor.Level.HEADERS))
+                //.addInterceptor(new HttpLoggingInterceptor().setLevel(HttpLoggingInterceptor.Level.HEADERS))
+                .eventListenerFactory(new LoggingEventListener.Factory(
+    )
                 .build();
     }
```

**Comment by yschimke** [comment]
A bit of context on the 3.14.x deprecation.  This code itself has been refactored since on 4.x branch, so maintenance of 3.14.x is generally only for critical security fixes.  Maintaining all fixes on 3 branches is not feasible.
