### ISSUE TITLE
Make `Call.Factory` a function interface in Kotlin 1.4

### ISSUE THREAD

**Issue by ZacSweers** [square/okhttp#6014]
Feature request that I wanted to file for the future.

```kotlin
fun interface Factory {
  fun newCall(request: Request): Call
}
```

Then it could be used as a lambda with 1.4's SAM support

```kotlin
Retrofit.Builder()
  .callFactory { ... }
```

**Comment by yschimke** [comment]
Good call, I'll add to https://github.com/square/okhttp/pull/5947

**Comment by ZacSweers** [comment]
The same could go for Interceptor I suppose too!

**Comment by yschimke** [comment]
Any view of this list? https://github.com/square/okhttp/pull/5947/commits/9eccc9f36bb825a105b0d2679cc08d2070137fdd

**Comment by ZacSweers** [comment]
I like it!

**Comment by yschimke** [comment]
And cleanup https://github.com/square/okhttp/pull/5947/commits/d58b5b255e557fa51dcc6bf4d149e7d60a400126

e.g.

<img width="1523" alt="image" src="https://user-images.githubusercontent.com/231923/80908810-e0e52080-8d1a-11ea-9684-9feaa9895c77.png">
