### ISSUE TITLE
MockWebServer and Multiplatform

### ISSUE THREAD

**Issue by JavierSegoviaCordoba** [square/okhttp#6016]
I have am using MockWebServer in `jvmTest` but I get this error when I run `gradle allTest`:
```
okHttpName
java.lang.NoSuchFieldError: okHttpName
```

I even tried to just do a simple test:

```
class SomeTest {

@Test
    fun someTest() {
        val mockWebServer = MockWebServer()
        assert(true)
    }
}
```
And it fails.

The `Test` annotation is from `kotlin.test.Test`

**Comment by swankjesse** [comment]
I don't think is a problem we could have caused. Do other libraries work?

**Comment by swankjesse** [comment]
Are you using the same versions of OkHttp and MockWebServer?

**Comment by JavierSegoviaCordoba** [comment]
I just ported the project from only jvm to multiplarform and I changed the Test annotation. I am not adding okhttp, just mockwebserver

**Comment by JavierSegoviaCordoba** [comment]
I added OkHttp, it seems to fix the problem, thank you!

**Comment by VN-tunt89** [comment]
Reopen

**Comment by JavierSegoviaCordoba** [comment]
@VN-tunt89 can you explain why?

**Comment by yschimke** [comment]
@JavierSegoviaCordoba there has been a lot of spam from this account, for now I'd assume the poor chaps account has got hacked, and just ignore it.
