### ISSUE TITLE
Cache behaviour changes

### ISSUE THREAD

**Issue by yschimke** [square/okhttp#6022]
1. Should we take/allow a stale cache entry over a network failure?

2. Should we add warnings to the cacheHit API of event listener?

3. Should cache strategy be adaptable via EventListener or a control API? e.g. based on network availability, Wifi/3G.  Or should we continue with current mode requiring external retries etc.

4. Should we encourage explicit use of the Cache API? e.g. check cache yourself before making a request?

**Comment by swankjesse** [comment]
1. No. We could offer a recipe or an API for doing stale-while-revalidate though. Stale data would potentially hide bugs. I’m imagining a request to a pricing service.

2. No. I don’t expect warnings to be useful in practice. (They’re available in the response headers if anyone looks.)

3. There’s a higher level HTTP API that this is hinting at. I think such a thing might compose OkHttp requests (Retrofit, Coil, etc.) but doing it in OkHttp with our current API is really hard. I really like Coil being at the layer of “just give me an image”.

4. No. Look before you leap is racy. We either want higher-level APIs for that, or callers to say only-if-cached.
