### ISSUE TITLE
HttpLoggingInterceptor 4.2.1 not working...

### ISSUE THREAD

**Issue by AnasMirza8630** [square/okhttp#6026]
I faced some error while I am using HttpLoggingInterceptor with a retrofit in these two lines but when I remove these lines Its working fine and I also used the latest version of both Interceptor and retrofit. Here are these two lines:-

``HttpLoggingInterceptor interceptor = new HttpLoggingInterceptor();
            interceptor.level(HttpLoggingInterceptor.Level.BODY);`

Version Used:-

`    implementation 'com.squareup.retrofit2:retrofit:2.6.0'
    implementation 'com.squareup.retrofit2:converter-gson:2.6.0'
    implementation "com.squareup.okhttp3:logging-interceptor:4.2.1"`

And, This is my code:-

HttpLoggingInterceptor interceptor = new HttpLoggingInterceptor();
            interceptor.level(HttpLoggingInterceptor.Level.BODY);
            OkHttpClient.Builder httpClient = new OkHttpClient.Builder();
            httpClient
                    .addInterceptor(chain -> {
                        Request original = chain.request();
                        Request request = original.newBuilder()
                                .header("Content-Type", "application/json")
                                .method(original.method(), original.body())
                                .build();
                        return chain.proceed(request);
                    }).addInterceptor(interceptor);
            OkHttpClient client = httpClient.build();
            retrofit = new Retrofit.Builder()
                    .baseUrl(ROOT_URL)
                    .addConverterFactory(GsonConverterFactory.create())
                    .client(client)
                    .build();

And, The error log is:-

`2020-05-07 18:41:39.973 13592-13887/<package> E/AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
    Process:<package> , PID: 13592
    java.lang.NoSuchMethodError: No virtual method log(ILjava/lang/String;Ljava/lang/Throwable;)V in class Lokhttp3/internal/platform/Platform; or its super classes (declaration of 'okhttp3.internal.platform.Platform' appears in /data/app/<package> -CYEfKYjbugvyG3TfUoxLxA==/base.apk!classes3.dex)
        at okhttp3.logging.HttpLoggingInterceptor$Logger$Companion$DEFAULT$1.log(HttpLoggingInterceptor.kt:116)
        at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.kt:164)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
        at <package> .web.ApiClient.lambda$getApiClient$0(ApiClient.java:65)
        at <package> .web.-$$Lambda$ApiClient$72kk7lSGJ-V_LFrKbGmUvAutC8g.intercept(Unknown Source:0)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
        at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:197)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:502)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)`

I also added this line in proguard but it still not working.

`-keep class okhttp3.** { *; }`

Could anyone please let me know if I am doing something wrong?

**Comment by AnasMirza8630** [comment]
> I faced some error while I am using HttpLoggingInterceptor with a retrofit in these two lines but when I remove these lines Its working fine and I also used the latest version of both Interceptor and retrofit. Here are these two lines:-
> 
> ``HttpLoggingInterceptor interceptor = new HttpLoggingInterceptor();
> interceptor.level(HttpLoggingInterceptor.Level.BODY);`
> 
> Version Used:-
> 
> ` implementation 'com.squareup.retrofit2:retrofit:2.6.0' implementation 'com.squareup.retrofit2:converter-gson:2.6.0' implementation "com.squareup.okhttp3:logging-interceptor:4.2.1"`
> 
> And, This is my code:-
> 
> `HttpLoggingInterceptor interceptor = new HttpLoggingInterceptor(); interceptor.level(HttpLoggingInterceptor.Level.BODY); OkHttpClient.Builder httpClient = new OkHttpClient.Builder(); httpClient .addInterceptor(chain -> { Request original = chain.request(); Request request = original.newBuilder() .header("Content-Type", "application/json") .method(original.method(), original.body()) .build(); return chain.proceed(request); }).addInterceptor(interceptor); OkHttpClient client = httpClient.build(); retrofit = new Retrofit.Builder() .baseUrl(ROOT_URL) .addConverterFactory(GsonConverterFactory.create()) .client(client) .build();`
> 
> And, The error log is:-
> 
> `2020-05-07 18:41:39.973 13592-13887/<package> E/AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher Process:<package> , PID: 13592 java.lang.NoSuchMethodError: No virtual method log(ILjava/lang/String;Ljava/lang/Throwable;)V in class Lokhttp3/internal/platform/Platform; or its super classes (declaration of 'okhttp3.internal.platform.Platform' appears in /data/app/<package> -CYEfKYjbugvyG3TfUoxLxA==/base.apk!classes3.dex) at okhttp3.logging.HttpLoggingInterceptor$Logger$Companion$DEFAULT$1.log(HttpLoggingInterceptor.kt:116) at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.kt:164) at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100) at <package> .web.ApiClient.lambda$getApiClient$0(ApiClient.java:65) at <package> .web.-$$Lambda$ApiClient$72kk7lSGJ-V_LFrKbGmUvAutC8g.intercept(Unknown Source:0) at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100) at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:197) at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:502) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) at java.lang.Thread.run(Thread.java:919)`
> 
> Could anyone please let me know if I am doing something wrong?

**Comment by yschimke** [comment]
Can you make sure that you are using the same version of all okhttp dependencies.  This will be caused by versions not matching.

This is also an older version of okhttp, so if it does indicate some bug in OkHttp we would need you to test with the latest version of OkHttp for all dependencies.

Please use stackoverflow for these types of issues, rather than raising an issue against the github project.

**Comment by AnasMirza8630** [comment]
Sure @yschimke, I used the latest version of OkHttp and Retrofit but the error still exists.

**Comment by yschimke** [comment]
4.6.0 is the latest version of okhttp

**Comment by AnasMirza8630** [comment]
Thanks @yschimke It helped me a lot. Actually android studio didn't warn about this updated version.
