### ISSUE TITLE
SSE EventSource 'text/event-stream' MIME type should be implicitly set

### ISSUE THREAD

**Issue by RalphSteinhagen** [square/okhttp#6038]
Firstly, thanks for this great library!

I noticed a slight inconsistency of the SSE EventSource implementation where the `text/event-stream` MIME-type is being checked for the event receiving path 
https://github.com/square/okhttp/blob/e31cb03d86b9c4daf2124c6e62e218b32e72e056/okhttp-sse/src/main/kotlin/okhttp3/internal/sse/RealEventSource.kt#L58-L62
but not the initial request ('Accept' 'header-ist' of the EventSource) as done e.g. in browsers such as Firefox and Chrome etc.  A more detailed description can be found [here](https://html.spec.whatwg.org/multipage/server-sent-events.html).

As a workaround the following is possible:
```Java
OkHttpClient okClient = new OkHttpClient();
Request request = new Request.Builder().url(path).addHeader("Accept", "text/event-stream").build();

EventSource.Factory factory = EventSources.createFactory(okClient);
EventSource sseEventSource = factory.newEventSource(request, EVENT_SOURCE_LISTENER);
```

It would be nice if this could be kept consistent and the MIME-type `text/event-stream` be set implicitly by the EventSource constructor, in the `connect(...)' call, its Factory, or equivalently.

Many thanks in advance for your consideration.

P.S. out of curiosity: why is `EventSourceListener` an abstract class and not an interface.

**Comment by yschimke** [comment]
We use an abstract class so we can add new events without breaking clients built against older versions. 

See a similar changes in EventListener https://github.com/square/okhttp/commit/8cebf9012bbdfdbad6b833effc545ff5b8b8e48b#diff-5ca874acb455fb0ee586729d2fb6a89d

**Comment by yschimke** [comment]
This seems like a sensible change if the Accept header isn't already set in the request.  It clearly shows the intention of the request.  There is some risk for setting it when older clients were not, but it likely shows a flaw in the server implementation and the workaround would be easy.

**Comment by RalphSteinhagen** [comment]
Thanks for the clarification and your consideration.

N.B. the origin for the "text/event-stream": our service can serve replies using different user-defined/preferred protocols for 'GET' (and other) calls for each of its tree-like structured endpoints. Depending on the 'Accept' header the reply is served either as an html (e.g. for web-browsers), binary, json, xml, yaml, ..., via long-polling and/or SSE notifications on content change followed by a user-driven pull using one of the previously mentioned formats.

Presently, as mentioned above, setting the Accept header explicitly works and I feel is better than defining yet another endpoint just for SSE-ing. My reasoning for this issue was -- since other clients already implicitly already set this header info -- that this would simplify life for other end-users that do not necessarily use our wrapper around your lib.

**Comment by RalphSteinhagen** [comment]
@yschimke thanks for the quick follow-up, much appreciated. :+1:
