### ISSUE TITLE
http1.1 protocol cannot reuse  a   realConnection in  "ConnectionPool "?

### ISSUE THREAD

**Issue by docwei2050** [square/okhttp#6043]
branch: parent-4.6.0

when I make a "GET" request  with http1.1 protocol ,everytime it will create a new RealConnection.   when i  try  that   more times, ConnectionPool will contains multiple realConenctions.  it cannot reuse connection.

i found  the code :
internal fun isEligible(address: Address, routes: List<Route>?): Boolean {
        if (transmitters.size >= allocationLimit || noNewExchanges) return false
     .....
transmitters.size=1   allocationLimit=1      cause   connection cannot be  reused。

when i  delete that condition judgment , it can reuse the old realConnection in "ConnectionPool ", but  i get a error "Unexpected status line: 499"。

**Comment by yschimke** [comment]
Please don't try modifying the code like this.  Can you post your issue on a forum like stackoverflow.  Only raise here if you can create a reproducible bug.  Http 1.1 doesn't allow concurrent requests over a connection, only http/2 does.  So you should write a test against a url like https://nghttp2.org/httpbin/delay/5 which will wait 5 seconds and then return a response.
