### ISSUE TITLE
Allow DELETE Request Body, Ensure Sane Behavior

### ISSUE THREAD

**Issue by JakeWharton** [square/okhttp#605]
The RFC is unclear in this regard as it only specifies that this should invalidate the cache entry (if any).

Refs https://github.com/square/retrofit/issues/426

**Comment by danielgomezrico** [comment]
I get a `protocol=http/1.1, code=502, message=Bad Gateway` using:

          Request request = new Request.Builder()
	  .url(url)
	  .addHeader("Authorization", authHeader)
	  .delete()
	  .build();

client.newCall(request)
It´s because of me?

**Comment by swankjesse** [comment]
@danielgomezrico I think you want to ask on stackoverflow

**Comment by danielgomezrico** [comment]
It works... :)
