### ISSUE TITLE
How to using same TCP connection for http2.0 and async?

### ISSUE THREAD

**Issue by snpcp** [square/okhttp#6051]
Why is this still a issue? 

when I using async send two requests for http2.0, I found two TCP connections by wireshark.

when I using sync send two requests, no problem.

I guarantee that the protocol is http2.0.

Here is my code:
---------------------------

```
OkHttpClient httpClient = new OkHttpClient.Builder()
                .sslSocketFactory(factory, (X509TrustManager) TRUST_MANAGERS[0])
                .hostnameVerifier((s, sslSession) -> true)
                .protocols(Arrays.asList(Protocol.HTTP_2, Protocol.HTTP_1_1))
                .retryOnConnectionFailure(true)
                .connectionPool(new ConnectionPool(5, 60, TimeUnit.SECONDS))
                .build();

Request request = new Request.Builder()
                .url("https://xxx.com/")
                .build();

int count = 2;

long startTime = System.currentTimeMillis();

final CountDownLatch countDownLatch = new CountDownLatch(count);

for (int i = 1; i <= count; ++i) {
    httpClient.newCall(request).enqueue(new Callback() {
                @Override
                public void onFailure(Call call, IOException e) {
                    System.out.println(Thread.currentThread().getName() + "-failed-" + e.getMessage());
                    finish();
                }

                @Override
                public void onResponse(Call call, Response response) throws IOException {
                    finish();
                }

                private void finish() {
                    countDownLatch.countDown();
                }

            });

    }
 
        countDownLatch.await();

        System.out.println("Time: " + (System.currentTimeMillis() - startTime) );

        System.exit(0);

}
```

---------------------------

okhttp: 4.5.0
os: windows 10
jdk: 1.8

Please tell me how to working, Thanks very much.

**Comment by snpcp** [comment]
I'm not sure it had anything to do with 'https://github.com/square/okhttp/pull/3207'.

**Comment by yschimke** [comment]
Use LoggingEventListener if you want to see what is going on. 

Generally when we first connect we can't know ahead of time that a single connection will be http/2 and able to server both requests.  So when the connection pool is empty, OkHttp will establish 2 connections, discover they are both http/2 and then disconnect one.

So likely both requests use a single connection, but you see two established.

**Comment by yschimke** [comment]
Thanks for the repro, but please consider using stackoverflow for these sorts of user questions in future.  It helps build good documentation for this sort of behaviour for others.

**Comment by snpcp** [comment]
So, I don't usingsame TCP connection for http2.0 async?

**Comment by snpcp** [comment]
Ok, I will use stackoverflow in next issue.

**Comment by snpcp** [comment]
I using Thread.sleep(1000) processing when exec second request,  it will take an extra second.

In tests, it's no problem. but in production env, it's issue.

Why don't we proactively specify HTTP2? or whether an additional configuration is required to indicate whether multiplexing is used? if used, we using multiplexing?

Please tell me your idea. Thanks very much.

**Comment by yschimke** [comment]
Can you continue discussion on stackoverflow, this isn't a general support forum.

**Comment by snpcp** [comment]
How to operate?

**Comment by snpcp** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        Hi,
            Could I reply here?Thanks,Snpcp
    
        
            
        
    
    
        
        

        
    

    On 5/14/2020 15:35，Yuri Schimke<notifications@github.com> wrote： 



Can you continue discussion on stackoverflow, this isn't a general support forum.

**Comment by yschimke** [comment]
Why don't you post a link here with the stackoverflow question.

**Comment by snpcp** [comment]
Please see https://stackoverflow.com/questions/61792896/how-to-using-same-tcp-connection-for-http2-0-and-async-in-okhttp3

**Comment by snpcp** [comment]
Please tell me your answer in the stackoverflow. Thanks.
