### ISSUE TITLE
Httpok 3.11 old Android device start handshake with sslv3

### ISSUE THREAD

**Issue by kiarashheydari** [square/okhttp#6068]
We devoloped some code which use httpok 3.11 library and make ssl connection 
In httpok release note sslv3 is disabled on httpok version 2.2 and above.
On my web server (nginix) I get this error 
 [info] 51340#0: *3568905185 SSL_do_handshake() failed (SSL: error:140943FC:SSL routines:ssl3_read_bytes:sslv3 alert bad record mac:SSL alert number 20) while SSL handshaking, client: , server: 0.0.0.0:443.
Some plz explain what happened!?

**Comment by yschimke** [comment]
Can you ask this sort of question on stackoverflow, this is for reproducible bug reports.  Also 3.11 is not an actively supported version.
