### ISSUE TITLE
SSLPinning is not working on android 23 and below 

### ISSUE THREAD

**Issue by vikasrathore** [square/okhttp#6076]
1-We are able to intercept request/response in burpsuite tool for api <=23. 
2-When i pass incorrect sha-256 pin to certificate pinner then it throws exception 
com.android.volley.NoConnectionError: javax.net.ssl.SSLPeerUnverifiedException: Certificate pinning failure!
3- when i pass correct pin it works request gets success.
4- we are not setting up static sha in network security config. we are doing programatically for all versions. 
Please check what i am missing.
 
Using **'com.squareup.okhttp3', name: 'okhttp', version: '3.11.0**
and **network security config** is 
```
<network-security-config>
    <base-config cleartextTrafficPermitted="true"/>
    <debug-overrides>
        <trust-anchors>
            <certificates src="user" />
        </trust-anchors>
    </debug-overrides>
    <domain-config cleartextTrafficPermitted="true">
        <domain includeSubdomains="true">abc.com</domain>
    </domain-config>
</network-security-config>
```
and **ssl pinning android code**  
```
public static HurlStack getOkHttpStack(Context context) {
        HurlStack stack = null;
        try {
            TrustManagerFactory trustManagerFactory = TrustManagerFactory.getInstance(
                    TrustManagerFactory.getDefaultAlgorithm());
            trustManagerFactory.init((KeyStore) null);
            TrustManager[] trustManagers = trustManagerFactory.getTrustManagers();
            if (trustManagers.length != 1 || !(trustManagers[0] instanceof X509TrustManager)) {
                throw new IllegalStateException("Unexpected default trust managers:"
                        + Arrays.toString(trustManagers));
            }
            X509TrustManager trustManager = (X509TrustManager) trustManagers[0];
            CertificatePinner certPinner = buildCertificatePinner(context);
            stack = new OkHttpStack(trustManager, certPinner);
        } catch (Exception e) {
            e.printStackTrace();
        }

        if (stack == null) {
            stack = new HurlStack();
        }
        return stack;
    }
```
**CertificatePinner object creation** 
```
 private static CertificatePinner buildCertificatePinner(Context context) {

        CertificatePinner pinner = null;

        if (context != null) {
                try {
                    if(pins != null && pins.size() > 0) {

                        CertificatePinner.Builder builder = new CertificatePinner.Builder();

                        for (PinPOJO pin : pins) {

                            try {
                                if (pin.isValid()) {
                                    builder.add(pin.getDomain(), pin.getValue());
                                }
                            }catch (Exception ex){}
                        }

                        pinner = builder.build();
                    }
                } catch (Exception ex) { }
            }
        }
        return pinner;
    }
```
**Okhttp client object creation** 

  ```
  public OkHttpStack(X509TrustManager trustManager, CertificatePinner certPinner) throws Exception {
        OkHttpClient.Builder builder = new OkHttpClient.Builder();
        if (trustManager != null) {
            TLSSocketFactory factory = new TLSSocketFactory(trustManager);
            builder.sslSocketFactory(factory, trustManager);
        }
        if(certPinner != null){
            builder.certificatePinner(certPinner);
        }
        mClient = builder.build();
    }
```

**Comment by swankjesse** [comment]
Can you provide an executable test case? This is just a bunch of code that I can’t execute to reproduce your problem.

**Comment by yschimke** [comment]
I've tested on Android 21 with 3.11.0 and 3.12.12 and pinning is working.  So without a reproducible case there isn't much we can do.

**Comment by yschimke** [comment]
Please reopen with a confirmed repro. Or consider StackOverflow for advice. Thanks.

**Comment by yschimke** [comment]
Managed to repro on Android 16, with 3.12.12

**Comment by yschimke** [comment]
Nope, My bad, the failure was certificate pinning correctly working as designed.

Branch here

https://github.com/square/okhttp/tree/repro_android_3_12_x

ANDROID_SDK_ROOT=/Users/yschimke/Library/Android/sdk ./gradlew :android-test:connectedCheck

**Comment by vikasrathore** [comment]
I am testing on marshmallow android-23. We are binding two pin sha-256 for domain 
"*.abc.com" = "value1"
"*.xyz.com" = "value1" both root cert have same SHA-256 PIN . 
i am able to inttercept the requests

**Comment by yschimke** [comment]
These are not valid hostname patterns, please use *.abc.com

See docs here https://square.github.io/okhttp/3.x/okhttp/okhttp3/CertificatePinner.html

In future, details like this are really useful in initial reports and please consider using stackoverflow for usage issues.  Thanks for clearing this up.

**Comment by vikasrathore** [comment]
This is my apps config, Apps code is very big please suggest how can we solve this ?
<network-security-config>
    <base-config cleartextTrafficPermitted="true"/>
    <debug-overrides>
        <trust-anchors>
            <certificates src="user" />
        </trust-anchors>
    </debug-overrides>
    <domain-config cleartextTrafficPermitted="true">
        <domain includeSubdomains="true">abc.com</domain>
    </domain-config>
</network-security-config>

**Comment by yschimke** [comment]
Please continue this discussion in stackoverflow, this is not a support forum.

**Comment by yschimke** [comment]
I was going to add validation, but we actually already throw an exception here

```
java.lang.IllegalArgumentException: Invalid URL host: ".facebook.com"
at okhttp3.HttpUrl$Builder.parse(HttpUrl.java:1405)
at okhttp3.HttpUrl.get(HttpUrl.java:916)
at okhttp3.CertificatePinner$Pin.<init>(CertificatePinner.java:272)
at okhttp3.CertificatePinner$Builder.add(CertificatePinner.java:334)
at okhttp.android.test.compare.OkHttpClientTest.<init>(OkHttpClientTest.kt:40)
```

**Comment by vikasrathore** [comment]
Yes we are using '*.abc.com' in same format.  ok let me take it to stackoverflow
