### ISSUE TITLE
Gradle promoted library version from 3.12.12 to 3.14.9

### ISSUE THREAD

**Issue by inat-tv** [square/okhttp#6077]
![ScreenShot_20200520190044](https://user-images.githubusercontent.com/31779629/82470292-d2925500-9acd-11ea-84f1-543d58597aad.png)

Why can't I use older versions. That's why I think I have problems with the tickets I opened earlier.

**Comment by swankjesse** [comment]
Try `./gradlew foo:dependencies --configuration runtimeClasspath` where `foo` is the name of your subproject.

**Comment by JakeWharton** [comment]
Retrofit 2.8.2 depends on OkHttp 3.14.9. The newer version wins. You either need to use an older Retrofit or use Gradle's [resolution strategy](https://docs.gradle.org/current/dsl/org.gradle.api.artifacts.ResolutionStrategy.html) to force OkHttp to an older version.

**Comment by inat-tv** [comment]
> Retrofit 2.8.2 depends on OkHttp 3.14.9. The newer version wins. You either need to use an older Retrofit or use Gradle's [resolution strategy](https://docs.gradle.org/current/dsl/org.gradle.api.artifacts.ResolutionStrategy.html) to force OkHttp to an older version.

    implementation 'com.squareup.retrofit2:retrofit:2.6.4'

thanks dude. I downgraded version and it worked.
