### ISSUE TITLE
Why not override ResponseBody#toString()

### ISSUE THREAD

**Issue by VergeDX** [square/okhttp#6084]
I'm confused about the method `ResponseBody#string()`...
Because I think a better choice is override `toString()` method to return the string of response body, and I also don't know why not do that...

**Comment by yschimke** [comment]
I'm not 100% sure about original reasons.

For me, at this point it is a deliberate design choice because it is a potentially destructive operation that has side effects like consuming the response byte stream. 

We won't change this.  It is by design.  Sorry.

**Comment by VergeDX** [comment]
Thanks for your answer!

**Comment by swankjesse** [comment]
Yep, it's because it's destructive. You can call `string()` exactly once, but you can call `toString()` may times.

It'd suck if you accidentally logged sensitive user data by including a response in a log message.
