### ISSUE TITLE
java.lang.OutOfMemoryError

### ISSUE THREAD

**Issue by yangxuqiang9** [square/okhttp#6091]
Failed to allocate a 32 byte allocation with 9574016 free bytes and 9MB until OOM, max allowed footprint 402653184, growth limit 402653184; failed due to fragmentation (largest possible contiguous allocation 0 bytes)

## Stack information

okhttp3.internal.http2.Http2Stream.checkOutNotClosed(TbsSdkJava:629)
--
2 okhttp3.internal.http2.Http2Stream$FramingSink.emitFrame(TbsSdkJava:563)
3 okhttp3.internal.http2.Http2Stream$FramingSink.write(TbsSdkJava:543)
4 okio.ForwardingSink.write(TbsSdkJava:35)
5 okhttp3.internal.http.CallServerInterceptor$CountingSink.write(TbsSdkJava:149)
6 okio.RealBufferedSink.emitCompleteSegments(TbsSdkJava:179)
7 okio.RealBufferedSink.write(TbsSdkJava:42)
8 okio.ForwardingSink.write(TbsSdkJava:35)
9 cn.tuhu.net.g$1.write(TbsSdkJava:61)
10 okio.RealBufferedSink.emitCompleteSegments(TbsSdkJava:179)
11 okio.RealBufferedSink.writeAll(TbsSdkJava:107)
12 okhttp3.RequestBody$3.writeTo(TbsSdkJava:120)
13 cn.tuhu.net.g.writeTo(TbsSdkJava:48)
14 okhttp3.MultipartBody.writeOrCountBytes(TbsSdkJava:173)
15 okhttp3.MultipartBody.writeTo(TbsSdkJava:114)
16 okhttp3.internal.http.CallServerInterceptor.intercept(TbsSdkJava:72)
17 okhttp3.internal.http.RealInterceptorChain.proceed(TbsSdkJava:147)
18 okhttp3.internal.http.RealInterceptorChain.proceed(TbsSdkJava:121)
19 cn.tuhu.net.interceptor.a.intercept(TbsSdkJava:15)
20 okhttp3.internal.http.RealInterceptorChain.proceed(TbsSdkJava:147)
21 okhttp3.internal.connection.ConnectInterceptor.intercept(TbsSdkJava:45)
22 okhttp3.internal.http.RealInterceptorChain.proceed(TbsSdkJava:147)
23 okhttp3.internal.http.RealInterceptorChain.proceed(TbsSdkJava:121)
24 okhttp3.internal.cache.CacheInterceptor.intercept(TbsSdkJava:93)
25 okhttp3.internal.http.RealInterceptorChain.proceed(TbsSdkJava:147)
26 okhttp3.internal.http.RealInterceptorChain.proceed(TbsSdkJava:121)
27 okhttp3.internal.http.BridgeInterceptor.intercept(TbsSdkJava:93)
28 okhttp3.internal.http.RealInterceptorChain.proceed(TbsSdkJava:147)
29 okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(TbsSdkJava:126)
30 okhttp3.internal.http.RealInterceptorChain.proceed(TbsSdkJava:147)
31 okhttp3.internal.http.RealInterceptorChain.proceed(TbsSdkJava:121)
32 cn.tuhu.net.interceptor.e.intercept(TbsSdkJava:38)
33 okhttp3.internal.http.RealInterceptorChain.proceed(TbsSdkJava:147)
34 okhttp3.internal.http.RealInterceptorChain.proceed(TbsSdkJava:121)
35 cn.tuhu.net.interceptor.c.intercept(TbsSdkJava:29)
36 okhttp3.internal.http.RealInterceptorChain.proceed(TbsSdkJava:147)
37 okhttp3.internal.http.RealInterceptorChain.proceed(TbsSdkJava:121)
38 cn.tuhu.net.interceptor.b.intercept(TbsSdkJava:22)
39 okhttp3.internal.http.RealInterceptorChain.proceed(TbsSdkJava:147)
40 okhttp3.internal.http.RealInterceptorChain.proceed(TbsSdkJava:121)
41 okhttp3.RealCall.getResponseWithInterceptorChain(TbsSdkJava:250)
42 okhttp3.RealCall$AsyncCall.execute(TbsSdkJava:201)
43 okhttp3.internal.NamedRunnable.run(TbsSdkJava:32)
44 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
45 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
46 java.lang.Thread.run(Thread.java:764)

**Comment by swankjesse** [comment]
Unclear what action to take here. If this is a bug report please add an executable test case that reproduces the problem. If you'd like help debugging something, try StackOverflow.
