### ISSUE TITLE
JUnit Test Extension for MockWebServer

### ISSUE THREAD

**Issue by SethiPandi** [square/okhttp#6099]
When wrapping APIs we test the code using `mockwebserver` in JUnit.
I use to inline the HTTP responses in Strings, but eventually moved to putting the responses in files in the test resource classpath instead as some APIs can return _huge_ responses. This isn't really a big deal but can be very messy and repetitive.

I feel it would be nice if there was a way to create a `MockResponse` using a resource in the classpath.

Following this it would be even better if there was a simple JUnit 5 Extension that could be used to start and stop the server, and create the MockResponse via an annotation.

I've already made something which does the `MockResponse` part as I actively desired this, you can see it here:

https://gist.github.com/SethiPandi/4c31a2fd01f6d7f0702fc089815d6c67

The classes `TestUtils`, `Response`, and `MockResponseExtension` are the implementation.
`SteamTest` is just what it would look like to use it.

The example code I've provided is probably nowhere near good enough for an official implementation; it's just to give an idea of what I mean and why I think it'd be nice.

**Comment by yschimke** [comment]
Sorry, we aren't going to commit to doing this.

See a mostly dupe issue https://github.com/square/okhttp/issues/4667

> MockWebserver probably isn't considered a top priority public API compared to the client, and upgrading this is awkward.

We have also avoided incremental improvements for this reason

https://github.com/square/okhttp/issues/5392
https://github.com/square/okhttp/issues/5380
