### ISSUE TITLE
Too many follow-up requests:21

### ISSUE THREAD

**Issue by Jeromews** [square/okhttp#6105]
Hi! Recently, i've had a problem. when i use the proxy to visit a url, moreover the proxy need to authenticate. And i used the proxyAuthenticator to auth it.
```
            builder.proxy(new Proxy(Proxy.Type.HTTP, new InetSocketAddress(httpProxyHost, httpProxyPort)))
                .proxyAuthenticator((route, response) -> {
                    String credential = Credentials.basic(httpProxyUserName, httpProxyPassword);
                    return response.request().newBuilder()
                            .header("Proxy-Authorization", credential)
                            .build();
                });`
```

 But i accidentally filled in the wrong userName. Then the proxy server return the 407 code——Proxy Authentication Required. But i found that when the responseCode equals 407, the RetryAndFollowUpInterceptor will retry automatically. And when the followUpCount is greater than 20, an exception will be thrown.That is **_throw new ProtocolException("Too many follow-up requests: " + followUpCount);_**. And finally ,i can only discover an exception trace that the full message is Too many follow-up requests:21. And when i saw this exception, i have no idea why the request will be retry more than 20 times.I have to Investigate this problem with other ways such as add a new Interceptor to record the log.
My suggest is that some http reasonCode such as 407(Proxy Authentication Required) can response directly rather than retry automatically cause it mainly need us to modify the parameter. By this way, we can find the error Intuitively. Thank you for checking and looking forward to your reply！

**Comment by Jeromews** [comment]
or maybe record more stackTrace to show why the request will be retry when throw the ProtocolException

**Comment by yschimke** [comment]
This is already covered in the docs

https://github.com/square/okhttp/pull/3092/files

See https://github.com/square/okhttp/blob/cbe7baa4746954a06a8fbc8c622b4f7d66c09964/samples/guide/src/main/java/okhttp3/recipes/Authenticate.java#L33-L35
