### ISSUE TITLE
Support HTTP/2 on Android 4 when an `SSLSocket` with working ALPN is provided

### ISSUE THREAD

**Issue by cgrushko** [square/okhttp#6129]
Due to a buggy ALPN implementation, OkHttp refuses to use HTTP/2 on Android 4 (unless `GMSCore_OpenSSL` is present).

However, I happen to have an `SSLSocket` with a working ALPN implementation, and I'd like to use it to issue HTTP/2 requests on Android 4.

Proposal: 
1. Modify `AndroidPlatform.getSelectedProtocol()` and `configureTlsExtensions` to check whether its input `SSLSocket` implements the interface `SSLSocketWithWorkingALPN` or something like that.
2. The new interface is:
```
interface SSLSocketWithWorkingALPN {
    byte[] getAlpnSelectedProtocol();
    void setAlpnProtocols(byte[] protocols);
}
```
3. If it is of that interface, call these methods instead of using the `getAlpnSelectedProtocol` and `setAlpnProtocols` fields of AndroidPlatform.

P.S. - if this proposal is accepted, any chance of backporting it to v3.12.x?

**Comment by yschimke** [comment]
No we wouldn't accept this PR, and definitely wouldn't backport it to 3.12.x.

I suggest you look at either

1) Fork OkHttp 3.12.x and add the support you need
2) Look at bundling conscrypt-android (https://github.com/google/conscrypt) and using that which is supported.
