### ISSUE TITLE
Missing Data

### ISSUE THREAD

**Issue by Serkan-Karacelikler** [square/okhttp#6130]
Hi, I am trying to get html codes of a site but the incoming data is missing. How can I solve this problem?

Here is my code:
`
public class cordovaokhttp extends CordovaPlugin {
    OkHttpClient client = new OkHttpClient();

    String run(String url) throws IOException {
        Request request = new Request.Builder()
            .url(url)
            .header("User-Agent", "Mozilla/5.0 (Linux; Android 7.0; SM-G930V Build/NRD90M) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.125 Mobile Safari/537.36")
            .header("Referer", "http://www.bolumd.me/tv1")
            .build();

        try (Response response = client.newCall(request).execute()) {
            return response.body().string().toString();
        }
    }

    @Override
    public boolean execute(String action, JSONArray args, CallbackContext callbackContext) throws JSONException {
        if (action.equals("coolMethod")) {
            String message = args.getString(0);
            this.coolMethod(message, callbackContext);
            return true;
        }
        return false;
    }

    private void coolMethod(String message, CallbackContext callbackContext) {
        String url = "http://www.bolumd.me/yabanci-diziler";
        cordovaokhttp example = new cordovaokhttp();
        try {
            String response = example.run(url);
            callbackContext.success(response);
        }
        catch(IOException e) {
            e.printStackTrace();
        }

    }
}
`

Note: Stackoverflow doesn't allow me to ask questions.

**Comment by yschimke** [comment]
This isn't a channel for user support.  If you have a reproducible bug report, then please post and reopen, but as is we can't investigate.

I suggest finding a way to post to stackoverflow, or asking a colleague to if you have been blocked from posting.
