### ISSUE TITLE
javax.net.ssl.SSLProtocolException: Read error: ssl=0x7efd216488: Failure in SSL library, usually a protocol error     error:10000416:SSL routines:OPENSSL_internal:SSLV3_ALERT_CERTIFICATE_UNKNOWN (external/boringssl/src/ssl/tls_record.cc:587 0x7f0bb4ea48:0x00000001)

### ISSUE THREAD

**Issue by KeyonChan** [square/okhttp#6132]
server is win server 2008R2 and .net core 3.1, app request with a .pfx certificate. 
onFailure：
javax.net.ssl.SSLProtocolException: Read error: ssl=0x7efd216488: Failure in SSL library, usually a protocol error     error:10000416:SSL routines:OPENSSL_internal:SSLV3_ALERT_CERTIFICATE_UNKNOWN (external/boringssl/src/ssl/tls_record.cc:587 0x7f0bb4ea48:0x00000001)

**Comment by yschimke** [comment]
This isn't a reproducible bug report, please consider using a site like stackoverflow with a concise correct example.  Also without access to your server or certificates there is not much we can help with.

This just means that we can't establish a trusted connection between client and server.

https://github.com/grpc/grpc-java/issues/6374
