### ISSUE TITLE
Jdk9Platform.kt: Unresolved reference: applicationProtocols

### ISSUE THREAD

**Issue by jiangkang** [square/okhttp#6136]
```
e: /okhttp/src/main/kotlin/okhttp3/internal/platform/Jdk9Platform.kt: (36, 19): Unresolved reference: applicationProtocols
```

**Comment by yschimke** [comment]
You need to build with JDK9, you will get this error if you are using building with JDK8.

**Comment by jimandreas** [comment]
`Unresolved reference: applicationProtocols`  Yes I see this too when trying a new pull / build of okhttp.

Hmm.  There is something rather mysterious going on here.   What I get when I dig a bit deeper is this hover-note from Android Studio 4.1 + JDK9:

`Call requires API level 29 (current min is 21): javax.net.ssl.SSLParameters#getApplicationProtocols`

The code is there (as kindly provided by the bytecode decompiler)

    public class SSLParameters { ...
    public String[] getApplicationProtocols() {
        return (String[])this.applicationProtocols.clone();
    }

but as yet I haven't found the source for JDK9.   Seems to be [difficult to find](https://community.oracle.com/tech/developers/discussion/4119198/where-to-download-jdk-9-source-code).  So no hints so far about why this requires API 29 and above.   There are no helpful comments in [SO](https://stackoverflow.com/search?q=ApplicationProtocols+okhttp) and mostly sad confusion regarding JDK9 on the [issue tracker](https://issuetracker.google.com/issues/67495440).   This is my first foray into this jungle of Java versionitis so I will tread carefully and keep a sharp eye out for poisonous bugs.

**Comment by yschimke** [comment]
Android and JDKs don't move in lockstep with the core APIs.  So it can be messy.  We need to build okhttp against a modern JDK, and then run classes selectively on lower platforms for Android (5+ to 11) and JDK (8 - 15).

If you can't get past this then edit in Android Studio or Intellij and then run a gradle build which shouldn't face the same issue.
