### ISSUE TITLE
MockWebServer exception with android studio 4.2: java.lang.NoSuchFieldError: okHttpName

### ISSUE THREAD

**Issue by auras** [square/okhttp#6140]
Running a unit test with `MockWebServer` on Android Studio 4.2 will throw an exception:

```
java.lang.NoSuchFieldError: okHttpName

	at okhttp3.internal.concurrent.TaskRunner.<clinit>(TaskRunner.kt:309)
	at okhttp3.mockwebserver.MockWebServer.<init>(MockWebServer.kt:103)
```

Example:

```
class MockTest {
    private val server = MockWebServer()

    @Test
    fun `not important`() {
    }
}
```

```
android.testOptions {
        animationsDisabled = true

        unitTests {
            all {
                // Skip bytecode verification when running tests.
                // This line is added because the addition of the foursquare's Pilgrim SDK
                // was breaking unit tests (java.lang.VerifyError) -
                // possibly because that dependency was compiled with a different version of Java.
                jvmArgs '-ea', '-noverify'
                jacoco {
                    includeNoLocationClasses = true
                }
            }
            includeAndroidResources true
            returnDefaultValues = true
        }
        execution 'ANDROIDX_TEST_ORCHESTRATOR'
    }
```

Using AGP 4.0.0

The same tests run ok using Gradle CLI

**Comment by swankjesse** [comment]
Configure the same version of OkHttp and MockWebServer. This error happens if the versions are inconsistent.

**Comment by auras** [comment]
@swankjesse like I said, the same tests run ok with the Gradle CLI. And yes, they are the same version.

**Comment by swankjesse** [comment]
You may need to configure Android Studio to use the same versions of OkHttp and MockWebServer. If it's using different versions, you'll see that in the command line that is logged when it runs your tests.

You might work around by using Gradle for both compilation and test execution; this is an option in the IntelliJ settings and is likely in Android Studio also.

No action for us to take here. If you want to report a bug, you should report it to JetBrains or Android Studio.

**Comment by sebaslogen** [comment]
@swankjesse do you know what is the exact name of the option in IntelliJ Idea? I can't find it in Android Studio
