### ISSUE TITLE
java version support

### ISSUE THREAD

**Issue by SushmaReddyLoka** [square/okhttp#6143]
https://stackoverflow.com/questions/44599872/how-to-open-mulitple-streams-explicitly-in-okhttp-client-connection. This says that java support is from java 9+. But github doc i.e. https://github.com/square/okhttp#requirements says its java 8+. Which one is correct ?

**Comment by swankjesse** [comment]
OkHttp requires Java 8+.

OkHttp HTTP/2 support depends on your Java security provider. If you don't have a custom security provider, you'll need Java 9.
https://square.github.io/okhttp/security_providers/
