### ISSUE TITLE
Fatal Exception: java.lang.RuntimeException java.net.URISyntaxException: Illegal character in authority at index 8: https://40.2"n/ okhttp3.HttpUrl.uri

### ISSUE THREAD

**Issue by Mayank1904** [square/okhttp#6144]
Caused by java.net.URISyntaxException
Illegal character in authority at index 8: https://40.2"n/
java.net.URI$Parser.fail (URI.java:2893)
java.net.URI.<init> (URI.java:584)
okhttp3.HttpUrl.uri (HttpUrl.java:377)
okhttp3.internal.connection.RouteSelector.resetNextProxy (RouteSelector.java:117)
okhttp3.internal.connection.RouteSelector.<init> (RouteSelector.java:61)
okhttp3.internal.connection.StreamAllocation.<init> (StreamAllocation.java:89)
okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept (RetryAndFollowUpInterceptor.java:107)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:92)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:67)
okhttp3.RealCall.getResponseWithInterceptorChain (RealCall.java:185)
okhttp3.RealCall$AsyncCall.execute (RealCall.java:135)
okhttp3.internal.NamedRunnable.run (NamedRunnable.java:32)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1167)
java.lang.Thread.run (Thread.java:764)

**Comment by swankjesse** [comment]
Can you upgrade to the latest OkHttp and see if this still is a problem?

**Comment by Mayank1904** [comment]
I have upgraded to 3.14.9 ..lets see if this problem will happen or not
Thanks for your response

**Comment by swankjesse** [comment]
The latest OkHttp is 4.7.2. We don’t fix anything beyond severe security bugs in 3.14, and we’re going to stop doing that at the end of the month.

**Comment by Mayank1904** [comment]
Yeah sure we will update to the latest version soon.. As there are so many changes in the latest version,  I am working on it to understand the changes and do the changes at the earliest. 

The issue I have mentioned is due to the security bugs,   right?

**Comment by swankjesse** [comment]
No, we won't backport a fix for that.

**Comment by Mayank1904** [comment]
I have upgraded to the latest version 4.7.2 , hope I will not face the above mentioned issue.. If persists will let you know
