### ISSUE TITLE
Forcing WS and WSS to be HTTP and HTTPS causes connection failure

### ISSUE THREAD

**Issue by rawnsley** [square/okhttp#6159]
An okhttp3 Request object uses HttpUrl, which only supports HTTP and HTTPS schemes. Any URL string passed to the Request object by the Builder [is silently changed](https://github.com/square/okhttp/blob/19771365f25d986d125478a75c15d24d6e285e12/okhttp/src/main/kotlin/okhttp3/Request.kt#L173) from WS to HTTP or WSS to HTTPS.

In at least one case I have seen a server that responds differently to HTTPS connections: the server appears to assume they are browser requests and sends a redirect notice rather than negotiating WebSocket.

Ideally the scheme should be preserved by HttpUrl.

**Comment by JakeWharton** [comment]
Do you have more information? Where does the server see the scheme?

HTTP sends only the host and the path separately in the protocol. The initial web socket request is a normal HTTP request with a signaling header for triggering the protocol switch.

**Comment by rawnsley** [comment]
It's not my server so I can't be sure; perhaps it's being redirected before it even reaches the WebSocket server code? Here is an example request:

wss://unruffled-sorcerer.apart-internal.com/?roomId=C4HMrDZ&peerId=899ac227-1c1a-44e3-8380-53462a974c39

This is made as part of the negotiation in a Mozilla Hubs room: https://show.apartposters.com/C4HMrDZ

**Comment by swankjesse** [comment]
The scheme is never sent to the server, so if it’s failing it’s something else. We use `https`/`http` everywhere because otherwise we’d either need more types.

**Comment by rawnsley** [comment]
The server could have access to the full request URL couldn't it? Apache offers [REQUEST_SCHEME](http://httpd.apache.org/docs/current/mod/mod_rewrite.html) for instance or is this just based on the port it comes in on?

Perhaps I have jumped to conclusions. The actual error I get is: Expected HTTP 101 response but was '200 OK'. It appears to have followed the redirect you can see when you curl the https version of the URL.

**Comment by swankjesse** [comment]
Yeah, that’s likely computed from the request port.

It’s unclear what action we should take here. Could you create a test case that demonstrates the difference between OkHttp and your expectations?

**Comment by rawnsley** [comment]
When I tried to make a test case with a different library I'm seeing similar issues so perhaps this is some sort of server problem. I'll close for now - thanks for your help.

**Comment by hengbenkeji** [comment]
I need to access a third party wss server in my kotlin project. But open fun url(url: String): Builder changes the wss scheme into https. I also tried using return Request.Builder().url(HttpUrl.Builder().scheme("wss")....Build(), but it doesn't work. @swankjesse, would you please add more types including wss and ws in the OkHttp library? If you can do, just do it. If you cann't do, keep silent
