### ISSUE TITLE
Application getting crash with error Fatal Exception: java.lang.IllegalStateException Unbalanced enter/exit

### ISSUE THREAD

**Issue by sanketmthakare** [square/okhttp#6162]
I am using  
 "com.squareup.retrofit2:retrofit:2.8.1" and  "com.squareup.okhttp3:logging-interceptor:4.3.1" to make web request in my android application. I am using android studio 3.6.1. Is there any D8 related issue or something else?  I am getting this issue on most of the Samsung phone. 

**Below are the logs for references.**

```
okio.AsyncTimeout.enter (AsyncTimeout.java:49)
okio.AsyncTimeout$source$1.read (AsyncTimeout.java:343)
okio.RealBufferedSource.read (RealBufferedSource.java:188)
okhttp3.internal.http1.Http1ExchangeCodec$AbstractSource.read (Http1ExchangeCodec.java:352)
okhttp3.internal.http1.Http1ExchangeCodec$FixedLengthSource.read (Http1ExchangeCodec.java:389)
okhttp3.internal.Util.skipAll (Util.java:336)
okhttp3.internal.Util.discard (Util.java:357)
okhttp3.internal.http1.Http1ExchangeCodec$FixedLengthSource.close (Http1ExchangeCodec.java:408)
okio.ForwardingSource.close (ForwardingSource.java:34)
okhttp3.internal.connection.Exchange$ResponseBodySource.close (Exchange.java:312)
okio.RealBufferedSource.close (RealBufferedSource.java:498)
okhttp3.internal.Util.closeQuietly (Util.java:462)
okhttp3.ResponseBody.close (ResponseBody.java:192) 
```

**Comment by xiongkai** [comment]
I also encountered the same exception when using websocket. When the connection was disconnected, I reconnected for 2 seconds, using OKHttp version 4.7.2.

**Comment by xiongkai** [comment]
I encountered the same exception when using websocket, using OKHttp version 4.7.2. Delayed reconnection when the connection is disconnected, the shorter the set delay, the easier it is to reproduce.

**Comment by swankjesse** [comment]
Are you operating on that steam from multiple threads concurrently? Perhaps closing it while you're still reading?

Please provide an executable test case to reproduce this crash.

**Comment by yschimke** [comment]
Reopen with a repro

**Comment by M2dL1fe** [comment]
![image](https://user-images.githubusercontent.com/8074125/90591116-ce80eb00-e214-11ea-8642-6035e831e735.png)

I have the same problem， retrofit：2.8.1        okhttp:4.8.0

**Comment by SharkChao** [comment]
> ![image](https://user-images.githubusercontent.com/8074125/90591116-ce80eb00-e214-11ea-8642-6035e831e735.png)
> 
> I have the same problem， retrofit：2.8.1 okhttp:4.8.0

I have the same problem， retrofit：2.8.1 okhttp:4.8.0
