### ISSUE TITLE
Change default value for Header: User-Agent

### ISSUE THREAD

**Issue by ujjwalagrawal17** [square/okhttp#6163]
**Description:**

Change default value for Header: User-Agent from okhttp to below format. 

ProjectName/AppVersionCode (packageName); Android 10.1.1 okhttp/3.1.1; 

It's similar to how alarmofire sets it for iOS apps:
ProjectName/1.0 (com.company.packagename; build:1; iOS 13.2.2) Alamofire/4.7.3

**Comment by yschimke** [comment]
You can set your own application interceptor to define it to whatever you want

https://square.github.io/okhttp/interceptors/

But we don't currently have special hooks in Android to introspect the running application etc.

Out of scope for now.

**Comment by swankjesse** [comment]
Also it's information leakage. This is not a feature I ever want.

**Comment by ujjwalagrawal17** [comment]
Got it. Thanks for responding.
