### ISSUE TITLE
com.squareup.okhttp3 - 3.11.0 Getting quarantined by Nexus Artifactory

### ISSUE THREAD

**Issue by DannMendis** [square/okhttp#6165]
Hi Team

I am not expecting any specific action on this report. Logging this to help your team and the community. Three of my team members worked around 8 hours to come to this conclusion and putting it out there......

SETUP:
We are currently doing an automation project for a government client and all the Maven packages are coming via NEXUS Artifactory. It got a upstream link to Maven Central and all packages from Maven Central is scanned for known security vulnerabilities.

Issue:
As you may know Selenium Java latest and past versions marked okhttp3 - 3.11.0 as a transitive dependency and above issue is preventing us using Selenium Java for our project.
Link: https://mvnrepository.com/artifact/org.seleniumhq.selenium/selenium-java/3.141.59 version

Why we can't change the version:
Selenium certified it's versions after unit testing and we like to request if this vulnerability can be fixed and re-deploy as same version. Also we did test latest and other versions of OKHTTP but it's not properly integrating with Selenium properly and test are failing intermittently. I know this is not a problem with OKHTTP and will report this with Selenium.

I did request the security vulnerability details from security team and once they provide it, I will post it.

**Comment by swankjesse** [comment]
Interesting. No action taken.

**Comment by yschimke** [comment]
Maybe https://ossindex.sonatype.org/vuln/f265fef7-39d9-46b0-b42a-4e98261d93e3

**Comment by yschimke** [comment]
https://github.com/square/okhttp/issues/4967

**Comment by DannMendis** [comment]
Thanks @yschimke I will use this info and get security to release it from Nexus. Thanks for sharing this valuable information.
