### ISSUE TITLE
Replace BouncyCastle with our own DER encoder

### ISSUE THREAD

**Issue by swankjesse** [square/okhttp#6167]
This is mostly done, but it hasn’t had a tracking bug and it needs one.

The goal is to stop okhttp-tls from depending on Bouncy Castle. Bouncy Castle is great! It’s powerful & capable. But we want to minimize dependencies and it’s a tricky one:
 * 6.5 MiB of code
 * installs as a SecurityProvider which impacts VM-wide behavior
 * .jar file is signed and resists shadowing
 * the APIs we were using are deprecated!

One potential upside is we may consider offering DER-dependent features stuff in the core `okhttp` library. (Not yet, that’ll be a separate issue if or when it comes.)

Here’s the code changes implemented thus far:

 * [Early implementation of an ASN.1 DER decoder](https://github.com/square/okhttp/pull/6135)
 * [DER encoder](https://github.com/square/okhttp/pull/6139)
 * [Limited support for decoding extensions](https://github.com/square/okhttp/pull/6145)
 * [Move tag management in DerAdapters](https://github.com/square/okhttp/pull/6148)
 * [Fix bugs so we can roundtrip certificates](https://github.com/square/okhttp/pull/6151)
 * [Use OkHttp's certificate creation code](https://github.com/square/okhttp/pull/6152)
 * [Stop using Bouncycastle to do PKCS8 to PKCS1](https://github.com/square/okhttp/pull/6153)
 * [Honor RFC 5280 when choosing a time format](https://github.com/square/okhttp/pull/6154)
 * [Improve code style for the new DER package](https://github.com/square/okhttp/pull/6157)
 * [Add limits to what length values DerReader supports](https://github.com/square/okhttp/pull/6164)
 * [[WIP] testing Device Attestation](https://github.com/square/okhttp/pull/6160)
 * [Drop support for indefinite length in DER](https://github.com/square/okhttp/pull/6166)

Next steps are improving confidence in the implementation and potentially offering it as a public API somehow. For now the only way to use it is through the `HeldCertificate` class, which uses our DER encoder to create a TLS certificate.

**Comment by swankjesse** [comment]
I crawled ~5300 TLS hosts and decoded all of their certificates without problems. Here’s extension object identifiers and their relative popularity:

| Object identifier         | Count |
| :------------------------ | ----: |
| 2.5.29.14                 | 99777 | 
| 2.5.29.15                 | 99562 | 
| 2.5.29.19                 | 98147 | 
| 2.5.29.35                 | 74199 | 
| 1.3.6.1.5.5.7.1.1         | 66544 |         
| 2.5.29.32                 | 66504 | 
| 2.5.29.31                 | 51328 | 
| 2.5.29.37                 | 43275 | 
| 2.5.29.17                 | 33249 | 
| 1.3.6.1.4.1.11129.2.4.2   | 32983 |               
| 1.3.6.1.4.1.311.21.7      |  1619 |            
| 1.3.6.1.4.1.311.21.10     |  1619 |             
| 1.2.840.113635.100.6.48.1 |     5 |                 
| 1.2.840.113549.1.9.15     |     4 |             
| 2.5.29.30                 |     1 |

**Comment by yschimke** [comment]
Closing this as 4.8 released.
