### ISSUE TITLE
Proxy rotation on a per-request basis support

### ISSUE THREAD

**Issue by ivkomarov** [square/okhttp#6168]
Currently, OkHttp version 4.6.0 does not support calling ProxySelector.select for each request. This method is getting called usually from 1 to 3-4 times and from this moment, application is running behind the selected proxies. 

This feature might be needed for web-scrapping projects, for multi-backend environment, where each of the connections should be over particular proxies. 

If this is a bug – please, let me know. Just in case, here is my OkHttpClient configuration: 

```
private val SPEC_CHROME = ConnectionSpec.Builder(ConnectionSpec.COMPATIBLE_TLS)
        .tlsVersions(TlsVersion.TLS_1_2)
        .cipherSuites(
            CipherSuite.TLS_AES_128_GCM_SHA256,
            CipherSuite.TLS_AES_256_GCM_SHA384,
            CipherSuite.TLS_CHACHA20_POLY1305_SHA256,
            CipherSuite.TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,
            CipherSuite.TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,
            CipherSuite.TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,
            CipherSuite.TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,
            CipherSuite.TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256,
            CipherSuite.TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256,
            CipherSuite.TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA,
            CipherSuite.TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA,
            CipherSuite.TLS_RSA_WITH_AES_128_GCM_SHA256,
            CipherSuite.TLS_RSA_WITH_AES_256_GCM_SHA384,
            CipherSuite.TLS_RSA_WITH_AES_128_CBC_SHA,
            CipherSuite.TLS_RSA_WITH_AES_256_CBC_SHA,
            CipherSuite.TLS_RSA_WITH_3DES_EDE_CBC_SHA)
        .build()

OkHttpClient.Builder()
            .protocols(listOf(Protocol.HTTP_2, Protocol.HTTP_1_1))
            .connectionSpecs(listOf(SPEC_CHROME))
            // empty connection pool was an attempt to rotate proxies
            .connectionPool(ConnectionPool(0, 5, TimeUnit.MINUTES))
            .followRedirects(true)
            .followSslRedirects(true)
            .dns(DNS)
            .hostnameVerifier(TrustAllHostnameVerifier)
            .sslSocketFactory(sslContext.socketFactory, TrustAllCerts)
            .proxySelector(CustomProxySelector(proxiesCache))
            .proxyAuthenticator(CustomProxyAuthenticator(proxiesCache))
            .eventListener(HttpEventListener)
            .build()
```

You can replace CustomProxySelector/CustomProxyAuthenticator with simple implementations for logging purposes to see, whether the same behaviour takes place.

**Comment by swankjesse** [comment]
In order to maximize connection pooling OkHttp doesn't recheck the ProxySelector if there's already a connection to that host on an existing proxy.

I think this is good behavior. But if you need otherwise consider turning off connection pooling. That'll cause proxies to be rechecked per call.

**Comment by ivkomarov** [comment]
@swankjesse according to the code above you can see, that connection pooling is disabled, so, probably a bug?

**Comment by swankjesse** [comment]
Quite possibly. Care to write an executable test case?

**Comment by yschimke** [comment]
You aren't disabling connection pooling above, just setting idle count to 0. I actually don't think we have a way to disable all connection pooling, unless you force HTTP/1.1.  HTTP/2 should reuse connections that are not currently idle.

You could test to confirm with something like this, but note we don't have any supported way to do this.  It isn't public API and below is probably racy anyway.

```
    val f = object : EventListener.Factory {
      override fun create(call: Call): EventListener {
        return object : EventListener() {
          override fun connectionAcquired(
            call: Call,
            connection: Connection
          ) {
            (connection as RealConnection).noNewExchanges = true
          }
        }  
      }
    }
```

**Comment by yschimke** [comment]
Closing as we don't support this requirement and don't plan to.

**Comment by yschimke** [comment]
Also, if you can calculate the proxy for the request, you can make lightweight copies of a root client instance that set the specific proxy and it should do the right connection pooling and open connections when the proxy changes.

```
var requestClient = client.newBuilder().proxy(proxy4).build()
```

**Comment by ivkomarov** [comment]
@yschimke thanks for the answer. May i ask, approximately, how much would the approach with copying clients affect performance? I am curious more about RAM usage.

**Comment by yschimke** [comment]
It is a shallow copy.  You should confirm but if you only kept setting the same proxy it should be no different than using a single client. If it's recreating new connections then please raise a bug.

**Comment by yschimke** [comment]
It is a shallow copy.  You should confirm but if you only kept setting the same proxy it should be no different than using a single client. If it's recreating new connections then please raise a bug.

It should make the optimal number of connections.
