### ISSUE TITLE
Implement clean CookieStore and deprecate okhttp-urlconnection

### ISSUE THREAD

**Issue by jverne** [square/okhttp#6172]
See [this SO report](https://stackoverflow.com/q/62758635/437212) against the problems with split package naming in okhttp-urlconnection.

Posted by request.

**Comment by swankjesse** [comment]
I looked into this, and I think I have a slightly more involved but much more satisfying solution.

Lets just create a built-in in-memory cookie store in the core package. It means you’ll only need one artifact, and we can deprecate the entire okhttp-urlconnection module.

**Comment by yschimke** [comment]
https://github.com/square/okhttp/issues/2890 ?

**Comment by swankjesse** [comment]
Yep. Tracking as https://github.com/square/okhttp/issues/2890
