### ISSUE TITLE
OKHttp version 3.14.0 is doing 100's of retry even after disabling the retry flag

### ISSUE THREAD

**Issue by ravichauhan03** [square/okhttp#6177]
We started using OKHttp version 3.14.0 as mentioned below:

 ConnectionPool pool = new ConnectionPool(maxIdleConnections, 5, TimeUnit.MINUTES);
        return httpClient.newBuilder().connectionPool(pool).connectTimeout(connectTimeOut, TimeUnit.MILLISECONDS)
                .readTimeout(readTimeout, TimeUnit.MILLISECONDS).build();
    }

and we started seeing 100's of retry request suddenly happening and not just that also, the requests which were sent to downstream service the data was also messed up. Fields were misplaced here and there.

Then we read a couple of blogs and started using like below with:
.retryOnConnectionFailure(false)
                .cache(null)

Conclusion after doing above is, we are still facing the same issue of misplacing fields and retries.

**Comment by swankjesse** [comment]
Executable test case?

OkHttp 3.14.x is obsolete; please upgrade to the current release. (Currently 4.7.2).

**Comment by wuyinlei** [comment]
I have updated to the latest version 4.7.2，and user 
.retryOnConnectionFailure(false)
.cache(null),no work. Will still repeat the request 4 times, when the network is abnormal

**Comment by yschimke** [comment]
Please provide a reproducible test case, you can use MockWebServer or test against something like https://httpbin.org.

Otherwise, please raise a general usage question on stackoverflow, but as is we can't help you with this report.
