### ISSUE TITLE
Dependency convergence error between Okio and Okhttp

### ISSUE THREAD

**Issue by Dragas** [square/okhttp#6184]
Recently I've started to use maven-dependency plugin to make sure my project's runtime has all of its dependencies copied over into necessary folder and maven-enforcer plugin to ensure that there are no dependency tree issues. After implementing the enforcer plugin, I started getting the following issue:

```
[INFO] --- maven-enforcer-plugin:3.0.0-M3:enforce (enforcer) @ eternal-witness-deck-downloader-api ---
[WARNING] 
Dependency convergence error for org.jetbrains.kotlin:kotlin-stdlib:1.3.70 paths to dependency are:
+-lt.saltyjuice.dragas:eternal-witness-deck-downloader-api:2.0.0-SNAPSHOT
  +-com.squareup.okhttp3:okhttp:4.8.0
    +-com.squareup.okio:okio:2.7.0
      +-org.jetbrains.kotlin:kotlin-stdlib:1.3.70
and
+-lt.saltyjuice.dragas:eternal-witness-deck-downloader-api:2.0.0-SNAPSHOT
  +-com.squareup.okhttp3:okhttp:4.8.0
    +-org.jetbrains.kotlin:kotlin-stdlib:1.3.72
```
It seems that okhttp3 depends on kotlin stdlib 1.3.72, while its dependency, okio, depends on 1.3.70. While I am sure that there are no API changes between the two, convergence errors can still lead to seemingly random errors that require having experienced the mismatching dependencies in your project to figure out what went wrong.

Consider either updating okio's kotlin dependency or using the following on okio dependency
```
exclude group: 'org.jetbrains.kotlin', module: 'kotlin-stdlib'
```

**Comment by JakeWharton** [comment]
Seems like it's basically the same as https://github.com/square/okhttp/issues/6007

I would exclude the kotlin-stdlib from this tool. I don't believe this to be a problem in the same way that it's not a problem if Okio was compiled with Java 6 and OkHttp was compiled with Java 8 (which is actually the case).

**Comment by yschimke** [comment]
+1 to what @JakeWharton said...

This isn't something that we are actively focusing on keeping inline. I'd go so far as to say if this is a problem, then we should raise a tracking bug with Jetbrains and they would fix with some urgency.  Kotlin 1.4 is possibly worth synchronising, but even then if we delay there is nothing to stop OkHttp being used in an application that has already moved to 1.4.

According to Koltlin versioning policy, this should continue to work.  You can read up about Kotlin's version compatibility.

https://kotlinlang.org/docs/reference/evolution/kotlin-evolution.html#incompatible-changes
https://kotlinlang.org/foundation/language-committee-guidelines.html

**Comment by Dragas** [comment]
I see. Though after excluding `1.3.70` in favor of the newer, OkHTTP becomes unusable due to following error:
```
Caused by: java.lang.ClassNotFoundException: kotlin.TypeCastException
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 57 more
```
Meanwhile, if you exclude the `1.3.72` version everything seems to work alright.

**Comment by swankjesse** [comment]
I suspect your exclusion strategy isn't picking a version; rather it's removing Kotlin altogether or not.

**Comment by Dragas** [comment]
I suppose exclusion strategies work the same in maven as they do in gradle.
```
            <dependency>
                <groupId>com.squareup.okhttp3</groupId>
                <artifactId>okhttp</artifactId>
                <version>4.8.0</version>
                <exclusions>
                    <exclusion>
                        <groupId>org.jetbrains.kotlin</groupId>
                        <artifactId>kotlin-stdlib</artifactId>
                    </exclusion>
                    <exclusion>
                        <groupId>org.jetbrains.kotlin</groupId>
                        <artifactId>kotlin-stdlib-common</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>
            <dependency>
                <groupId>org.jetbrains.kotlin</groupId>
                <artifactId>kotlin-stdlib</artifactId>
                <version>1.3.72</version>
            </dependency>
            <dependency>
                <groupId>org.jetbrains.kotlin</groupId>
                <artifactId>kotlin-stdlib-common</artifactId>
                <version>1.3.72</version>
            </dependency>
```
This was how I had previously defined kotlin-stdlib reimport
