### ISSUE TITLE
RecordedRequest body size is 0 for POST request

### ISSUE THREAD

**Issue by hram** [square/okhttp#6190]
okhttp:4.8.0 and mockwebserver:4.8.0
I have some request recorded by mockwebserver
All POST reqest have equals bodySize and body.size
![изображение](https://user-images.githubusercontent.com/2150637/87943660-04607180-caa7-11ea-9547-7c8d8820f89c.png)

But one of them have right bodySize value and zerro body.size
![изображение](https://user-images.githubusercontent.com/2150637/87943516-d5e29680-caa6-11ea-914b-f2364e0f3d76.png)

And I do not see any specifc with this request

**Comment by swankjesse** [comment]
Unclear what action to take on this.
If this is a question, please ask on StackOverflow.
If this is a bug report, please provide an executable test case.
