### ISSUE TITLE
APPROVED_CIPHER_SUITES incompatible with mozilla

### ISSUE THREAD

**Issue by halaei** [square/okhttp#6193]
The list of approved cipher suites is incompatible with the green (modern) ones listed by mozilla: https://wiki.mozilla.org/Security/Cipher_Suites

More precisely, the followings are not in the okhttp APPROVED_CIPHER_SUITES, although weaker suits are already present:

* TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256   (stronger than TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA because of the length)
* TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256 (higher priority than TLS_RSA_WITH_AES_128_GCM_SHA256 in mozilla list)
* TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384   (stronger than TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA because of the lenght)
* TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384 (higher priority than TLS_RSA_WITH_AES_128_GCM_SHA256 in mozilla list)

It causes network connection issues for our React Native application when trying to connect to a cloudfront subdomain, depending on the client's network. Here is some OKHttp and DNS log I put in the code:

```
759270.149 connectStart https://oursubdomain.cloudfront.net/...

759270.391 secureConnectStart https://oursubdomain.cloudfront.net/..

system find [oursubdomain.cloudfront.net/13.224.194.10, oursubdomain.cloudfront.net/13.224.194.45, oursubdomain.cloudfront.net/13.224.194.23, oursubdomain.cloudfront.net/13.224.194.99] for oursubdomain.cloudfront.net

759289.581 connectFailed https://oursubdomain.cloudfront.net/...

IOException:
0: com.google.android.gms.org.conscrypt.NativeCrypto.SSL_do_handshake(-2)
1: com.google.android.gms.org.conscrypt.NativeSsl.doHandshake(6)
2: com.google.android.gms.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(16)
3: okhttp3.internal.connection.RealConnection.connectTls(336)
4: okhttp3.internal.connection.RealConnection.establishProtocol(300)
5: okhttp3.internal.connection.RealConnection.connect(185)
6: okhttp3.internal.connection.ExchangeFinder.findConnection(224)
7: okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(107)
8: okhttp3.internal.connection.ExchangeFinder.find(87)
9: okhttp3.internal.connection.Transmitter.newExchange(169)
10: okhttp3.internal.connection.ConnectInterceptor.intercept(41)
11: okhttp3.internal.http.RealInterceptorChain.proceed(142)
12: okhttp3.internal.http.RealInterceptorChain.proceed(117)
13: okhttp3.internal.cache.CacheInterceptor.intercept(94)
14: okhttp3.internal.http.RealInterceptorChain.proceed(142)
15: okhttp3.internal.http.RealInterceptorChain.proceed(117)
16: okhttp3.internal.http.BridgeInterceptor.intercept(93)
17: okhttp3.internal.http.RealInterceptorChain.proceed(142)
18: okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(88)
19: okhttp3.internal.http.RealInterceptorChain.proceed(142)
20: okhttp3.internal.http.RealInterceptorChain.proceed(117)
21: okhttp3.RealCall.getResponseWithInterceptorChain(221)
22: okhttp3.RealCall$AsyncCall.execute(172)
23: okhttp3.internal.NamedRunnable.run(32)
24: java.util.concurrent.ThreadPoolExecutor.runWorker(1167)
25: java.util.concurrent.ThreadPoolExecutor$Worker.run(641)
26: java.lang.Thread.run(764)
```

**Comment by yschimke** [comment]
The policies are defined here https://square.github.io/okhttp/https/

> These loosely follow the model set in Google Cloud Policies. We track changes to this policy.

Can you check the host with https://www.ssllabs.com/ssltest/analyze.html?d=cloudfront.net

Since you've done your own research, you can set your own policy for your client.

I'm out of my depth here, but I believe it's mainly because the older ones you reference are there for legacy and compatibility reasons.  And the newer ones have some concerns (CBC vs GCM), and generally most modern servers will support better ciphers.  It's probably not the length particularly.

**Comment by halaei** [comment]
Cloudfront only supports TLSv1.2 (but not TLSv1.3) and these are the supported cipher suites:

```
TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384
TLS_RSA_WITH_AES_128_GCM_SHA256
TLS_RSA_WITH_AES_256_GCM_SHA384
TLS_RSA_WITH_AES_128_CBC_SHA256
```
 
![image](https://user-images.githubusercontent.com/7089140/88096884-9d2ce500-cbac-11ea-9bff-223accd6379b.png)

It is suspicious that all CBC suites listed above are missing from APPROVED_CIPHER_SUITES and connections with GCM suites fail in my network. Maybe my internet provider is trying to spy on me!

**Comment by halaei** [comment]
I tested all the cipher suites with `curt -v --tlsv1.2 --cipher <cipher name>` on my laptop, all are working fine, so maybe no problem with my ISP. Here are the corresponding suite names for curl:
```
ECDHE-RSA-AES256-GCM-SHA384
ECDHE-RSA-AES128-GCM-SHA256
ECDHE-RSA-AES256-SHA384
ECDHE-RSA-AES128-SHA256
AES256-GCM-SHA384
AES128-GCM-SHA256
AES128-SHA256
```

**Comment by yschimke** [comment]
I'm going to close this out, maybe continue in a stackoverflow post.  Or make a simple reproduction and reopen this ticket.

It's worth remembering the selected cipher is effectively the intersection of 3 policies.

1) Server 
2) OkHttp version 
3) Platform (Android or JVM) or Provider (opting into Conscrypt etc)

So you could look at whether it's particular old devices that are the problem.

**Comment by swankjesse** [comment]
Time to update our list!
https://tinyurl.com/okhttp-cipher-suites

**Comment by halaei** [comment]
Is there any limit on the number of items in cipher suites array? I find my connection issue is somehow related to the size of array too. Probably the array is getting truncated somewhere?

**Comment by swankjesse** [comment]
I've never heard of that before. Though if you have some suites in the list the server should reject you, notably, `TLS_FALLBACK_SCSV`.
