### ISSUE TITLE
HttpUrl#resolve problem 

### ISSUE THREAD

**Issue by fabien-nisol** [square/okhttp#6194]
Is this the expected behavior? 

testRelativeWithoutTrailingSlash test will fail in this test. 

`package com.sg.app.util;

import com.squareup.okhttp.HttpUrl;
import org.junit.Assert;
import org.junit.Test;

public class HttpUrlTest {

    @Test
    public void testRelativeWithoutTrailingSlash()
    {
        String url = HttpUrl.parse("http://domain/root")
                .resolve("./relative").url().toString();

        Assert.assertEquals("http://domain/root/relative",url);
    }

    @Test
    public void testRelativeWithTrailingSlash()
    {
        String url = HttpUrl.parse("http://domain/root/").resolve("./relative").url().toString();

        Assert.assertEquals("http://domain/root/relative",url);
    }
}
`

**Comment by JakeWharton** [comment]
If you think of it as `root.txt` vs `root/` and resolving `./relative.txt` the existing behavior becomes more clear. But yes, this is working as expected.

**Comment by swankjesse** [comment]
Another example, where I'm using “6194” instead of “root” and “6193” instead of “relative”.

```
<a href="./6193">./6193</a>
```

<a href="./6193">./6193</a>

**Comment by fabien-nisol** [comment]
makes sense, I was wrapping this around my head, but did not see this one coming :D 

Thanks for the prompt answer!
