### ISSUE TITLE
java.net.UnknownServiceException: CLEARTEXT communication to localhost not permitted by network security policy

### ISSUE THREAD

**Issue by CyrusCeasar** [square/okhttp#6196]
I am sorry, I know this problem shouldn't post here but StackOverFlow,  I have post the[ question](https://stackoverflow.com/questions/63032000/java-net-unknownserviceexception-cleartext-communication-to-t-main-wedeep-com-c) there but none of answers could sort my matter out. I have stucked by this problem for a long time.
I got above error when executed my AndroidJunit4Test.  I checked the source code . This exception throwed out by following code, although **CleartextTraffic is Permitted**

```
   if (!Platform.get().isCleartextTrafficPermitted(host)) {
        throw new RouteException(new UnknownServiceException(
            "CLEARTEXT communication to " + host + " not permitted by network security policy"));
      }

```
Any ideas for this problem? Thanks.

**Comment by yschimke** [comment]
I'll take a look on stackoverflow, closing this out.

**Comment by CyrusCeasar** [comment]
Ok, Thank you very much!

**Comment by yschimke** [comment]
I didn't have anything to add, looks like you have the correct answers there.  Next step is debugging it, but suggest either way to continue the discussion on stackoverflow, not here.

You can try using mockWebServer.useTls and client.insecureHost to use SSL for the test connections.
