### ISSUE TITLE
More helpful exception

### ISSUE THREAD

**Issue by paul-hammant** [square/okhttp#6197]
https://github.com/square/okhttp/blob/master/okhttp/src/main/kotlin/okhttp3/HttpUrl.kt#L1261 >>>

    throw IllegalArgumentException("Expected URL scheme 'http' or 'https' but no colon was found")

.. could the message also contain the offending URL please? 

Without that addition, a debugger is called, which isn't impossible to setup, but it would be so much easier if "input" were tacked on to the message.

**Comment by JakeWharton** [comment]
Maybe. Unfortunately the string you supplied might contain sensitive information such as API keys which we might inadvertently log as a result of putting it into the exception message.

**Comment by yschimke** [comment]
IIRC there are hardly any places that we internally parse a HttpUrl.  So mostly it will be in client code, can you add your own utility to catch, improve the message and rethrow.

My guess is, if we made this change and surprised client teams at large companies by starting to log URLs it would likely be a privacy sev.

**Comment by paul-hammant** [comment]
yeah, there's probably a long tail of URLs out there with /user/xxx?pw=yyy in them

**Comment by swankjesse** [comment]
When it parses successfully we can redact everything after the host. But since this doesn't parse I think our hands are tied.
