### ISSUE TITLE
Automate explanation of mixed dependency versions

### ISSUE THREAD

**Issue by yschimke** [square/okhttp#6200]
Between okhttp, okio, okhttp-tls, mockwebserver, we should check dependency versions match and proactively fail.

Failing proactively will save a lot of effort for people getting versions mixed up in builds.  Worse if the error only happens in an edge case.

**Comment by yschimke** [comment]
See https://github.com/square/okhttp/issues/6199

**Comment by yschimke** [comment]
PR https://github.com/square/okhttp/pull/6208/files

**Comment by yschimke** [comment]
We should consider closing this out, but going to tag every bug report that is because of mixed versions for now, see what the actual effect on users is.

**Comment by swankjesse** [comment]
Can we fix all our docs to recommend the BOM?
