### ISSUE TITLE
RealConnection.java:304 crash by IndexOutOfBoundsException

### ISSUE THREAD

**Issue by haipengc51** [square/okhttp#6215]
I find a crash , my okhttp version is:com.squareup.okhttp3:okhttp:3.9.0
crash log is: 
08-06 20:04:14.122  6342 12275 E AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
08-06 20:04:14.122  6342 12275 E AndroidRuntime: Process: com.aispeech.sample, PID: 6342
08-06 20:04:14.122  6342 12275 E AndroidRuntime: java.lang.IndexOutOfBoundsException: Index: 0
08-06 20:04:14.122  6342 12275 E AndroidRuntime: 	at java.util.Collections$EmptyList.get(Collections.java:4502)
08-06 20:04:14.122  6342 12275 E AndroidRuntime: 	at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:304)
08-06 20:04:14.122  6342 12275 E AndroidRuntime: 	at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:268)
08-06 20:04:14.122  6342 12275 E AndroidRuntime: 	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:160)
08-06 20:04:14.122  6342 12275 E AndroidRuntime: 	at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:256)
08-06 20:04:14.122  6342 12275 E AndroidRuntime: 	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:134)
08-06 20:04:14.122  6342 12275 E AndroidRuntime: 	at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:113)
08-06 20:04:14.122  6342 12275 E AndroidRuntime: 	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
08-06 20:04:14.122  6342 12275 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
08-06 20:04:14.122  6342 12275 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
08-06 20:04:14.122  6342 12275 E AndroidRuntime: 	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
08-06 20:04:14.122  6342 12275 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
08-06 20:04:14.122  6342 12275 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
08-06 20:04:14.122  6342 12275 E AndroidRuntime: 	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
08-06 20:04:14.122  6342 12275 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
08-06 20:04:14.122  6342 12275 E AndroidRuntime: 	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:125)
08-06 20:04:14.122  6342 12275 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
08-06 20:04:14.122  6342 12275 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
08-06 20:04:14.122  6342 12275 E AndroidRuntime: 	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
08-06 20:04:14.122  6342 12275 E AndroidRuntime: 	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:147)
08-06 20:04:14.122  6342 12275 E AndroidRuntime: 	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
08-06 20:04:14.122  6342 12275 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
08-06 20:04:14.122  6342 12275 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
08-06 20:04:14.122  6342 12275 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:764)
thanks

**Comment by yschimke** [comment]
Can you reopen with a reproduction against either 3.12.12 or 4.8.1?

This is not a supported version.
