### ISSUE TITLE
Certificate pinner GitHub editing doc link broken

### ISSUE THREAD

**Issue by rugk** [square/okhttp#6217]
The edit button on https://square.github.io/okhttp/4.x/okhttp/okhttp3/-certificate-pinner/ links to https://github.com/square/okhttp/edit/master/docs/4.x/okhttp/okhttp3/-certificate-pinner/index.md, which returns a 404 error, i.e. it seems to be broken.

I could not find the correct file easily either.

**Comment by yschimke** [comment]
Directly from source https://github.com/square/okhttp/blob/master/okhttp/src/main/kotlin/okhttp3/CertificatePinner.kt

**Comment by PARVEENSINGH** [comment]
Can I take it up?

**Comment by swankjesse** [comment]
I'd like to remove the edit links completely.
