### ISSUE TITLE
Fix android logging with MockWebServer on API 21-23

### ISSUE THREAD

**Issue by yschimke** [square/okhttp#6220]
We already avoid logging in Android extending past 23 characters, we should fix for MockWebServer also.  This was probably broken by me.

https://stackoverflow.com/questions/63387807/java-lang-illegalargumentexception-log-tag-okhttp3-mockwebserver-mockwebserver

https://github.com/square/okhttp/blob/b086b8d1835bcb3825d60ceb44bec7dec356405b/okhttp/src/main/kotlin/okhttp3/internal/platform/android/AndroidLog.kt#L63

**Comment by russell-shizhen** [comment]
Thanks for fixing this in from inside the library.

**Comment by JakeWharton** [comment]
Also worth noting the 23 character thing stopped being a thing in API 24.

**Comment by yschimke** [comment]
That still means that OkHttp MockWebServer 4.8 is broken for development testing on support versions.  I'm pretty sure this is the only artifact, the runtime paths take care of this.

**Comment by yschimke** [comment]
PR contribution in https://github.com/square/okhttp/pull/6225

**Comment by yschimke** [comment]
Closing with https://github.com/square/okhttp/pull/6229
