### ISSUE TITLE
Add a method to send bytes through WebSocket with MsgType=Text

### ISSUE THREAD

**Issue by 1354092549** [square/okhttp#6224]
I know this is a strange request but it really could be useful for some special cases.

**Comment by 1354092549** [comment]
It's easy to do that just making the internal function public will be okey
https://github.com/square/okhttp/blob/96a2118dd447ebc28a64d9b11a431ca642edc441/okhttp/src/main/kotlin/okhttp3/internal/ws/RealWebSocket.kt#L400

**Comment by yschimke** [comment]
Going to mark this as won't fix.  OkHttp public API is deliberately stable and focused on common correct use cases.  So we likely wouldn't change public API for this, and would like to avoid extra confusion for users.  Sorry.
