### ISSUE TITLE
Is it possible to use brotli compression with okhttp version 3.12?

### ISSUE THREAD

**Issue by varun0922** [square/okhttp#6227]
I am working on an app with min android sdk version 17. It is not possible for me to update to sdk version 21.
Transparent brotli compression is supported for okhttp version 4+ which requires the min sdk version 21 for android.
Please help.

**Comment by swankjesse** [comment]
You can create your own Brotli interceptor for OkHttp 3.12.x. You can start with the 4.x one.

**Comment by varun0922** [comment]
Thanks for the prompt response @swankjesse will try the same.

**Comment by varun0922** [comment]
Just posting interceptor code for reference which works with 3.12 

`import okhttp3.Interceptor
import okhttp3.Response
import okhttp3.ResponseBody
import okio.GzipSource
import okio.buffer
import okio.source
import org.brotli.dec.BrotliInputStream

/**
 * Transparent Brotli response support.
 *
 * Adds Accept-Encoding: br to request and checks (and strips) for Content-Encoding: br in
 * responses.  n.b. this replaces the transparent gzip compression in BridgeInterceptor.
 */
object BrotliKotlinCustomObject : Interceptor {
    override fun intercept(chain: Interceptor.Chain): Response =
            if (chain.request().header("Accept-Encoding") == null) {
                val request = chain.request().newBuilder()
                        .header("Accept-Encoding", "br,gzip")
                        .build()

                val response = chain.proceed(request)

                uncompress(response)
            } else {
                chain.proceed(chain.request())
            }

    internal fun uncompress(response: Response): Response {
        val body = response.body() ?: return response
        val encoding = response.header("Content-Encoding") ?: return response

        val decompressedSource = when {
            encoding.equals("br", ignoreCase = true) ->
                BrotliInputStream(body.source().inputStream()).source().buffer()
            encoding.equals("gzip", ignoreCase = true) ->
                GzipSource(body.source()).buffer()
            else -> return response
        }


        return response.newBuilder()
                .removeHeader("Content-Encoding")
                .removeHeader("Content-Length")
                .body(ResponseBody.create(body.contentType(), -1, decompressedSource))
                .build()
    }
}`
