### ISSUE TITLE
TLS handshake is taking 100ms in same data centre API calls

### ISSUE THREAD

**Issue by chandresh-pancholi** [square/okhttp#6230]
Hi,

We are using okhttp3 for external service calls. We are running our service in AWS mumbai DC and upstream service is running in same DC. I have enables event listener and reviewing it to find out TLS handshake in each call is taking 200-300 ms.

Can you please help.

**Comment by yschimke** [comment]
Please raise this in stackoverflow, with some additional information. This is not for general user support.  We would require a reproducible bug in order to investigate here.
