### ISSUE TITLE
network interceptor -> chain -> get first/previous request?

### ISSUE THREAD

**Issue by ogolovanov** [square/okhttp#6236]
Hi.

It seems it is not possible to get "requests stack" from network interceptor chain.
For example: i request site-a.com -> redirect to site-b.com.
In network interceptor when request goes to site-b.com - i would like to get info about original/first request in that chain ( site-a.com  ).
It is not possible, right?
Why there is no such info and do you have plans do add that info?

Thanks.

**Comment by yschimke** [comment]
It should be available from response.priorResponse.

**Comment by swankjesse** [comment]
Hmmm ... the network interceptor won’t be able to use `Response.priorResponse` because the interceptor is only given a `Request`. You could probably sneak it in by remembering the prior response in a mutable `Tag` though.

```
  static class AllResponsesTag {
    List<Response> responses = new ArrayList<>();
  }
```

```
    OkHttpClient client = new OkHttpClient.Builder()
        .addInterceptor(new Interceptor() {
          @Override public Response intercept(Chain chain) throws IOException {
            return chain.proceed(chain.request().newBuilder()
                .tag(AllResponsesTag.class, new AllResponsesTag())
                .build());
          }
        })
        .addNetworkInterceptor(new Interceptor() {
          @Override public Response intercept(Chain chain) throws IOException {
            Response response = chain.proceed(chain.request());
            AllResponsesTag allResponsesTag = chain.request().tag(AllResponsesTag.class);
            System.out.println("response " + response + " after " + allResponsesTag.responses);
            allResponsesTag.responses.add(response);
            return response;
          }
        })
        .build();
```

**Comment by yschimke** [comment]
Whoops, sorry.

**Comment by swankjesse** [comment]
No, it’s okay to close this. The above code sample is sufficient.
