### ISSUE TITLE
Use of finals prevents mocking

### ISSUE THREAD

**Issue by jimshowalter** [square/okhttp#6237]
We needed to mock network calls, and tried to do that with okhttp, but were thwarted by finals on okhttp3.Request and okhttp3.Response.

Why are those classes final? Can the finals be removed to make it easier to test?

**Comment by swankjesse** [comment]
You shouldn’t mock value objects. You wouldn’t mock `String`! If you wanna create fake instances use the builders.
https://publicobject.com/2019/06/10/value-objects-service-objects-and-glue/
