### ISSUE TITLE
 okhttp3.internal.http2.StreamResetException: stream was reset: CANCEL

### ISSUE THREAD

**Issue by mytxoo** [square/okhttp#6238]
This happens occasionally in APP usage. Okhttp3. Internal. Http2. StreamResetException: stream was reset: CANCEL. I can't figure out why.

**Comment by mytxoo** [comment]
okhttp:4.7.2

**Comment by yschimke** [comment]
Looks like a dupe of https://github.com/square/okhttp/issues/3948 and https://github.com/square/okhttp/issues/3955

We would need a lot more information to investigate
