### ISSUE TITLE
idleDurationNs in cleanup function in RealConnectionPool will always equal to "keepAliveDurationNs"!!!

### ISSUE THREAD

**Issue by zwhcoder** [square/okhttp#6244]
![image](https://user-images.githubusercontent.com/55433781/91659624-8068c300-eb03-11ea-85d8-52c9eab965b6.png)

1. In pruneAndGetAllocationCount function "connection.idleAtNanos = now - keepAliveDurationNs";
2.in cleanup funtion "long idleDurationNs = now - connection.idleAtNano", idleDurationNs  will always equal to "keepAliveDurationNs".  Because idleDurationNs = now - connection.idleAtNano = now -  now + keepAliveDurationNs = keepAliveDurationNs.

**Comment by swankjesse** [comment]
No obvious action to take on this. If you’d like to submit a pull request that simplifies the code while still passing all tests, please do.
