### ISSUE TITLE
Update HttpUrl "Different URLs should be different" example

### ISSUE THREAD

**Issue by Marcono1234** [square/okhttp#6252]
Currently the documentation for `HttpUrl` has as example for "[Different URLs should be different](https://square.github.io/okhttp/4.x/okhttp/okhttp3/-http-url/#different-urls-should-be-different)" the two URLs `http://square.github.io/` and `http://google.github.io/`. However, at the moment these URLs are in fact not considered equal because the hosts have different IP addresses (maybe that was different when the doc was written):
```java
new URL("http://square.github.io/").equals(new URL("http://google.github.io/")) // false
```

It would therefore be good to replace this example with one which actually still demonstrates this issue. For that the reserved [example domains](https://tools.ietf.org/html/rfc2606#section-3) `example.net` and `example.com` could be used:
```java
new URL("https://example.net").equals(new URL("https://example.com")) // true
```

Ideally the KDoc would then highlight the different top level domains (since the second level domains are the same) and also include the code snippet from above to make it easier for users to reproduce:
```diff
- *  * http://square.github.io/
- *
- *  * http://google.github.io/
+ *  * [https://example.**net**](https://example.net)
+ *
+ *  * [https://example.**com**](https://example.com)
+ *
+ * ```
+ * new URL("https://example.net").equals(new URL("https://example.com")) // true
+ * ```
```

**Comment by yschimke** [comment]
Care to submit a PR?

**Comment by Marcono1234** [comment]
I first wanted to gather some feedback on the suggestion. Also I won't submit a pull request for this if that requires signing the CLA.
