### ISSUE TITLE
Program stuck in socketRead0

### ISSUE THREAD

**Issue by redouane59** [square/okhttp#6254]
Hi,

I developed a Java library for Twitter API [here](https://github.com/redouane59/twittered) using OkHttp3 4.8.1.
Unfortunately, it looks like after having sent a request, the program never stops and is stuck somewhere.
![image](https://user-images.githubusercontent.com/4500524/92411087-c39be500-f146-11ea-8bde-22715f8aab18.png)

I tried everything, closing connection explicitly in my code, updating the version of OkHttp, but still the same. Any idea ?

If needed, [here](https://github.com/redouane59/twittered/blob/develop/src/main/java/com/github/redouane59/twitter/helpers/RequestHelperV2.java#L33)  is the code where the request is done.

**Comment by yschimke** [comment]
This is a better question for stackoverflow. I have a OkHttp command line client and have written numerous twitter clients, that show it works perfectly fine against Twitter APIs (not V2 as I haven't been approved after some months yet).

Any chance this is an infinite streaming API that is just in a tight loop?  What does debugging show you?

**Comment by yschimke** [comment]
Also since it's Http2, the socket and connection is retained after any particular request finishes.  So try cleanly shutting down

https://square.github.io/okhttp/4.x/okhttp/okhttp3/-ok-http-client/#shutdown-isnt-necessary

**Comment by redouane59** [comment]
> Also since it's Http2, the socket and connection is retained after any particular request finishes. So try cleanly shutting down

Just tried it [here](https://github.com/redouane59/twittered/pull/61/files) but same behaviour. Debugging I correctly enter on this code, I get the result of my request which is OK, but after all it is stuck in `socketRead0` method...

**Comment by yschimke** [comment]
Moving to stackoverflow
