### ISSUE TITLE
Multiple eventListener support

### ISSUE THREAD

**Issue by neworld** [square/okhttp#6256]
There is no easy way to integrate two monitoring services upon `eventListener`, because the client supports only one. I could create a custom `CompositeEventListener` which calls all included listeners. But shouldn't this be included in the library?

**Comment by swankjesse** [comment]
Please create your own composite.

**Comment by neworld** [comment]
`OkHttpClient` accepts multiple interceptors, but only a single event listener. What is the reason to support only one listener?

> Please create your own composite.

EventListener is an abstract class with all methods implemented. That makes it fairly easy to miss to delegate [newly added methods](https://github.com/square/okhttp/blob/master/CHANGELOG.md#user-content-version-470). It is more tricky if 3rd party monitoring tool uses a newer version of OkHttp and expects new methods.

**Comment by swankjesse** [comment]
I saw a complaint recently that OkHttp is too big! So on behalf of everyone who isn’t going to use this feature I’m reluctant to add it.

What’s your use case?

**Comment by neworld** [comment]
> I saw a complaint recently that OkHttp is too big!

It was not expected. Just idea, but maybe could monitoring capabilities be moved to a different artifact? It could help to reduce the main package.

> What’s your use case?

I have custom EventListener to monitor connectivity health, and I am planning to introduce another 3rd party monitoring tool. From the docs:

> This will track requests timing information (TTFB, DNS resolution, …) and append it to RUM Resource events.

**Comment by yschimke** [comment]
Each sensible utility like this introduces a public API but actually contributes minimal value since it's so easy to write yourself.

**Comment by erawhctim** [comment]
I put this up in a gist if anyone wants to use it as a starter for their own projects:
https://gist.github.com/erawhctim/f0ce324278aad6d4dd956dcdb1e90902

**Comment by AlexTrotsenko** [comment]
@erawhctim I believe you are happy that other can other can freely use your implementation?
If so - would it be ok for you to add permissive license header to your gist? 
E.g. like following: 
https://github.com/Kotlin/kotlinx.coroutines/issues/1686#issuecomment-825547551

**Comment by erawhctim** [comment]
I wasn't even aware that was a requirement lol, sure
