### ISSUE TITLE
Add more context when failing to read from the cache

### ISSUE THREAD

**Issue by ian-ellis** [square/okhttp#6260]
I am currently trying to debug the following crash reported through firebase crashalytics for our Android application. Unfortunately but we cannot actually reproduce the issue, ourselves so the below stacktrace is all we have to go on.

```
okhttp3.Cache$Entry.readCertificateList (Cache.java:609)
okhttp3.Cache$Entry.<init> (Cache.java:529)
okhttp3.Cache.get$okhttp (Cache.java:177)
okhttp3.internal.cache.CacheInterceptor.intercept (CacheInterceptor.java:47)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:109)
okhttp3.internal.http.BridgeInterceptor.intercept (BridgeInterceptor.java:83)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:109)
okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept (RetryAndFollowUpInterceptor.java:76)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:109)
okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp (RealCall.java:201)
okhttp3.internal.connection.RealCall$AsyncCall.run (RealCall.java:517)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1167)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:641)
java.lang.Thread.run (Thread.java:764)
```

It stems from the null coalescing found here: https://github.com/square/okhttp/blob/fc6c29c4f93a7604fb0fee88be4bbc91dde6551d/okhttp/src/main/kotlin/okhttp3/Cache.kt#L609

What is making this incredibly hard to debug is the lack of information about the request itself. Firstly we are not setting a cache on our own OKhttp instance, which leads me to suspect a third party lib. However, without knowing any details about the request that we are failing to read from the cache it is almost impossible to tell.

My suggestion is to instead of using `!!` on the decoded certificate, we null check and then throw a `CertificateReadException` that provides more info about the response - mainly the URL but any other information that would be considered safe to end up in crash logs.s

>

**Comment by yschimke** [comment]
What version of OkHttp and Okio are you including in your app?

Look similar-ish to https://github.com/square/okhttp/issues/2281

What would your suggested change be?  Care to submit a PR? We don't expect this bug or similar to happen, so we don't throw full context about urls for every logic bug. By the time we land a fix, or add in enough context for you to faithfully debug this, you probably will get an answer more directly by either

1) Building a local dev build of okhttp, with your suggested fix instead of waiting for a 4.10 release.
or
2) Work out which client is making this call and configuring them to use an EventListener to capture some debugging information.

**Comment by yschimke** [comment]
Seems like a reasonable request if cache is corruptible (e.g. external file system changes) such that it doesn't always show a logic bug.

**Comment by yschimke** [comment]
For discussion, tests to confirm the fix after agreing on direction.

**Comment by swankjesse** [comment]
Looks like the response metadata file is truncated, despite our atomic rename.

Or we’re trying to use an HTTP cache entry to serve an HTTPS request?!

**Comment by yschimke** [comment]
So separating the cause from our handling of errors?  Are you ok with the approach of preferring a mechanism to repair after failure?  Otherwise we pretty much corrupt until you reinstall the App.

**Comment by swankjesse** [comment]
I'd like to understand what's happening here. Is it a logic bug or is this file changing spontaneously?

**Comment by dave-r12** [comment]
@ian-ellis this might be redundant but can you include the exception that you're seeing along with the stack trace?

**Comment by martin-academia** [comment]
I have started seeing a similar crash in my app in the field, being reported by Firebase. Since I don't have a device with the problem in front of me I can't get a lot more information. 
But the stack trace is similar:
```okio.Buffer.write (Buffer.java:955)
okhttp3.Cache$Entry.readCertificateList (Cache.java:668)
okhttp3.Cache$Entry.<init> (Cache.java:581)
okhttp3.Cache.get (Cache.java:208)
okhttp3.Cache$1.get (Cache.java:145)
okhttp3.internal.cache.CacheInterceptor.intercept (CacheInterceptor.java:55)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:142)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:117)
okhttp3.internal.http.BridgeInterceptor.intercept (BridgeInterceptor.java:93)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:142)
okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept (RetryAndFollowUpInterceptor.java:88)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:142)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:117)
okhttp3.logging.HttpLoggingInterceptor.intercept (HttpLoggingInterceptor.java:144)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:142)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:117)
com.instabug.library.okhttplogger.InstabugOkhttpInterceptor.populateNetworkResponse (InstabugOkhttpInterceptor.java:236)
com.instabug.library.okhttplogger.InstabugOkhttpInterceptor.intercept (InstabugOkhttpInterceptor.java:92)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:142)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:117)
com.academia.network.NetworkModel$okHttpClient$1$1.intercept (NetworkModel.kt:121)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:142)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:117)
com.academia.network.AuthInterceptor.intercept (AuthInterceptor.kt:52)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:142)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:117)
okhttp3.RealCall.getResponseWithInterceptorChain (RealCall.java:229)
okhttp3.RealCall$AsyncCall.execute (RealCall.java:172)
okhttp3.internal.NamedRunnable.run (NamedRunnable.java:32)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1167)
```

**Comment by yschimke** [comment]
Another instance of this with 3.12.x

https://github.com/square/okhttp/issues/2281#issuecomment-707560056

Maybe best case here is to cleanly fail on corrupted base64 content instead of NPE?

**Comment by yschimke** [comment]
Also relevant https://github.com/square/okhttp/issues/6453

**Comment by Reoger** [comment]
I also encountered this problem, and found that basically it happened in the background (accounting for 98%). I guess the string resource was recycled by the system in the background, resulting in the scheme leaving only empty strings.

**Comment by yschimke** [comment]
Thanks for the context, much appreciated.  We have changed the code to fail earlier, and we are working on better IO abstractions that should allow us to make it easier to debug this type of problem.  If you are able to reliably reproduce this, please let me know and I'll give you a build to test with.  Thanks!

**Comment by rajbopched11** [comment]
@swankjesse @yschimke any possible suggestions/workarounds to overcome this ?? Was it gracefully handled in any up-versions ?

**Comment by yschimke** [comment]
Cache now takes a FileSystem, so I think there are options now for adding additional debugging if you can repro. 

Is anyone hitting this on 4.11 or 5.0.0-alpha11?
