### ISSUE TITLE
HttpLoggingInterceptor() doesn't show all headers anymore?

### ISSUE THREAD

**Issue by valeriyo** [square/okhttp#6261]
With OkHttp 4.8.1, I noticed that I don't see all custom headers anymore (I haven't touched this code in a while, and IIRC it used to work):

```
          .addNetworkInterceptor(UserAgentInterceptor(userAgent))
          .addInterceptor(HttpLoggingInterceptor().apply { level = HEADERS })
```

This doesn't print custom User-Agent header added by the interceptor above. I tried moving these around, with no luck. The only combination that appears to work is this (with `.addNetworkInterceptor`):

```
          .addNetworkInterceptor(UserAgentInterceptor(userAgent))
          .addNetworkInterceptor(HttpLoggingInterceptor().apply { level = HEADERS })
```

But as I understand, this is not correct (although it does show all headers), because all examples are pointing to `.addInterceptor` as the right thing to do. There is also a weird "h2" printed at the end of request lines like this:

```
--> GET https://example.com/blob/get h2
```

What's happening?

**Comment by JakeWharton** [comment]
The interceptor doc, especially the image, should clear up why this is happening and why particular configurations work: https://square.github.io/okhttp/interceptors/. Order matters, but also there's a difference between regular and network interceptors.

h2 means HTTP/2 is being used.
