### ISSUE TITLE
Fatal Exception: java.lang.IllegalStateException Unbalanced enter/exit

### ISSUE THREAD

**Issue by M2dL1fe** [square/okhttp#6262]
![image](https://user-images.githubusercontent.com/8074125/92852854-c5ed9000-f421-11ea-8cef-647fc1ec5a81.png)

retrofit：2.8.1 okhttp:4.8.0

https://github.com/square/okhttp/issues/6162#issuecomment-675840713

**Comment by swankjesse** [comment]
Weird. Any steps to reproduce? How often is this happening?

**Comment by M2dL1fe** [comment]
Usually when you use WebSocket

**Comment by swankjesse** [comment]
Tracking as https://github.com/square/okhttp/issues/6279
