### ISSUE TITLE
Documentation: Recipes code samples are not formatted correctly

### ISSUE THREAD

**Issue by sigute** [square/okhttp#6268]
The [Recipes](https://square.github.io/okhttp/recipes/) page does not display code formatting correctly, code is mixed between code blocks and plain text, making it difficult to read. 

[Markdown](https://github.com/square/okhttp/blob/master/docs/recipes.md) looks ok on github viewer, so the issue might be in website generation.

Screenshot showing the formatting on Chrome:
![Screenshot 2020-09-14 at 10 58 23](https://user-images.githubusercontent.com/5782728/93065610-3a6e3c00-f679-11ea-82f9-f341688bba5f.png)

**Comment by levis9527** [comment]
now ，the github markdown page is warn
![image](https://user-images.githubusercontent.com/26116831/93576086-07a3ab00-f9cd-11ea-85c9-3053aa08cb84.png)

**Comment by sigute** [comment]
Fixed in https://github.com/square/okhttp/pull/6270
