### ISSUE TITLE
[okhttp-tls] HeldCertificate.decode using an RSA key

### ISSUE THREAD

**Issue by dhartwich1991** [square/okhttp#6271]
Hello dear okhttp team!

We recently had to implement a request to receive AWS credentials from our AWS IoT certificate using this process. (https://aws.amazon.com/blogs/security/how-to-eliminate-the-need-for-hardcoded-aws-credentials-in-devices-by-using-the-aws-iot-credentials-provider/) 

Since this request requires you to include the certificate in it to authenticate you we found `okhttp-tls`.
Quickly, we figured out that the `HeldCertificate.decode([cerificatePem, privateKey])` API would convert our AWS certificate PEM + Private Key, into something we could hand into the `OkHttpClient` using the `OkHttpClient.Builder#sslSocketFactory` function.

However, we noticed a problem with our private key (RSA) as we handed it to the `HeldCertificate.decode` function it threw an exception at us, because our key had an unexpected type. (https://github.com/square/okhttp/blob/master/okhttp-tls/src/main/kotlin/okhttp3/tls/HeldCertificate.kt#L518)

Our private key starts with `-----BEGIN RSA PRIVATE KEY-----` and ends with `-----END RSA PRIVATE KEY-----`

So, our "solution" was to remove the RSA from the start and end of the key and the decoding started to work.

However, now we are not sure if this is:
a) needed
b) a bug(?) (not supported?) in okhttp-tls (I am more than happy to fix it if necessary)
c) vodoo magic

It would be awesome if you could give us feedback on how to proceed from here.

Should we leave this "solution" from above in place or is there a better way to do what we want to do here.

Thank you very much in advance! ✌️

**Comment by swankjesse** [comment]
These different strings indicate different contents.

`BEGIN RSA PRIVATE KEY` is PKCS#1
`BEGIN PRIVATE KEY` is PKCS#8

https://stackoverflow.com/a/20065522/40013

Do you know which kind you have?

**Comment by swankjesse** [comment]
...Now that we have our own DER decoder, we should change that function to accept either format. But it’s important to not pass a PKCS#8 value to a function expecting PKCS#8 and vice versa.

**Comment by dhartwich1991** [comment]
We have 

BEGIN RSA PRIVATE KEY is PKCS#1

**Comment by yschimke** [comment]
TIL: Good answer here on PKCS#1 vs PKCS#8 https://stackoverflow.com/a/48960291/1542667

**Comment by yschimke** [comment]
@swankjesse What about uplifting this to certifikit and implementing there (currently only exists in tests?).  

Then allow certifikit combined with okhttp-tls?

**Comment by swankjesse** [comment]
Yep!

**Comment by dhartwich1991** [comment]
So just to understand and summarize a bit:
So PKCS#1 and PKCS#8 are both "hashed" using `DER` which is why our current solution to just remove `RSA` from the key _works_.
Is there anything that needs / can be done from my side or is this solely on you now?

Thank you for the help so far!

**Comment by yschimke** [comment]
I'd stick with a workaround if it's working fine for you.  I'll raise a bug in certifikit and we'll implement and make some example code for using with OkHttp.

OkHttp shouldn't be a kitchen sink. Hence avoiding any PR that adds this directly to this project.

**Comment by yschimke** [comment]
@dhartwich1991 Any thoughts on https://github.com/cashapp/certifikit/pull/53/files and want to try?

**Comment by yschimke** [comment]
> So PKCS#1 and PKCS#8 are both "hashed" using `DER` which is why our current solution to just remove `RSA` from the key _works_.

This surprises me, I think they are different entities being encoded.

**Comment by dhartwich1991** [comment]
Hey @yschimke I just reviewed and approved the PR, looks nice!

**Comment by swankjesse** [comment]
No action to take on this.
