### ISSUE TITLE
Adopt JDK toolchain for Gradle 6.7

### ISSUE THREAD

**Issue by yschimke** [square/okhttp#6273]
https://docs.gradle.org/6.7-rc-1/release-notes.html

Should simplify the CI builds drastically.

Toolchain support for JVM projects

By default, Gradle uses the same Java version for running Gradle itself and building JVM projects.

This is not always desirable. Building projects with different Java versions on different developer machines and CI servers may lead to unexpected issues. Additionally, you may want to build a project using a Java version that running Gradle is not compatible with.

Before this release, it required several steps to configure a different Java version for compilation, testing, generating Javadoc, and executing applications.

This release introduces the toolchain concept to simplify such a setup. A Java toolchain is a set of tools (javac compiler,java command etc), taken from a local Java installation and used during the build. Instead of manually specifying executables for the various tasks, toolchains provide a centralized place to define the Java version requirements in the build.

Setting up a toolchain can be done through the java extensions:

```
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(14)
    }
}
```

**Comment by mkrzywanski** [comment]
This means that in scope of this also gradle should be upgraded to `6.7-rc-1`?

**Comment by yschimke** [comment]
That's in JDK 15 upgrade also https://github.com/square/okhttp/pull/6272

**Comment by yschimke** [comment]
Testing on https://github.com/square/okhttp/pull/6320
