### ISSUE TITLE
WSS/HTTPS Error: Hostname not verified

### ISSUE THREAD

**Issue by baldhead69** [square/okhttp#6276]
Hi,

I am implementing a websocket server on esp32 and i am using okhttp lib on app running on android studio simulator.

I already tested with only ws/http and works ok.
I already tested with wss/https accessing site "wss://echo.websocket.org" and works ok.
I was told that the site "wss://echo.websocket.org" uses a certificate from letsencrypt.

When accessing my webserver on esp32 the android/okhttp error appear: "java.security.cert.CertPathValidatorException: Trust anchor for certification path not found".
So i searched in the web and "https://developer.android.com/training/articles/security-ssl#java", and i put the same certificate of the server inside the android app.
The error is gone, but new one appear: "Hostname not verified", see image in annex.  

I want to use the https/wss protocol in a local area network for communication between esp32 websocket server and android / ios app.
Maybe in the future i will run a server in the cloud to communicate with the app and also communicate with the esp32 local websocket server(sporadic communication).
At first the esp32 local websocket server will not have a domain, only an ip ( doubt ).

I am using a self assigned certificate generated by openssl command:
openssl req -newkey rsa:2048 -nodes -keyout prvtkey.pem -x509 -days 3650 -out cacert.pem -subj "/CN=ESP32 HTTPS server example"

I am not sure if the problem is in android/java or okhttp lib.

How can i solve this problem, already thinking about the production version ?

Notes:
* I have control of both the esp32 local secure websocket server and the client application ( and cloud server ).
* Esp32 local area network secure websocket server.
* okhttp version: implementation 'com.squareup.okhttp3:okhttp:4.9.0'.
* I have very little knowledge about ssl/tls. 

Thank's for the help.

![Screenshot](https://user-images.githubusercontent.com/17574492/93723785-1bd7db80-fb78-11ea-88fc-5a7b87e4f6e9.png)

**Comment by yschimke** [comment]
Please ask on stackoverflow, if you post a link there I'll respond in that reply, but this is only for reproducible bug reports (which this is not yet), so let's continue over there.

**Comment by baldhead69** [comment]
I tried to open a question on site stackoverflow, but the question was closed, alleging that it was out of scope.

https://pt.stackoverflow.com/questions/473207/wss-https-error-hostname-not-verified

**Comment by yschimke** [comment]
It should just be a matter of using a custom HostnameVerifier, since the certificate subjectAltNames don't match (are empty).

**Comment by baldhead69** [comment]
@yschimke,

How could i solve this inside okhttp ? 
Do you have any suggestions ?
I need to have a domain/subdomain in local websocket server(for production) ?

Sorry, for now i am a little lost.

Thank's.

**Comment by baldhead69** [comment]
Hi @yschimke,

Why did you close my question if the problem has not yet been solved ?

**Comment by yschimke** [comment]
The right place to solve it is in stackoverflow, consider addressing their concerns and reopen there, or try the english language section of stackoverflow.  That is a community with a number of people available to answer and work through your problem.  Myself and other maintainers are active participants there.

The first stage of you raising this issue tried to make this clear.

![image](https://user-images.githubusercontent.com/231923/94237666-1b886900-ff07-11ea-8b3e-36cede2f5f03.png)

If you want to reopen this issue, then please provide a reproducible bug report such as code we can use to confirm an issue and the fix.  http://sscce.org/ is a good guide for this.

I suspect the portugese stackoverflow site just closed your issue because you asked the question in English.

**Comment by baldhead69** [comment]
Hi @yschimke,

I solved the problem partially as follows:

I add ".hostnameVerifier(hostnameVerifier)" in OkHttpClient class.
In addition i also added the server certificate in the client application before, as stated in my first question above.
 
I would really like to do it correctly, to generate the server's certificate and private key in the right way, using openssl command line tool.
And using the class HostnameVerifier in the correct way too, not only returning true.
```
HostnameVerifier hostnameVerifier = new HostnameVerifier()
{
    @Override
    public boolean verify(String hostname, SSLSession session)
    {
        return true;

/*
        output( hostname );

        try
        {
            Thread.sleep( 5000 );
        }
        catch (InterruptedException e)
        {
            e.printStackTrace();
        }

        HostnameVerifier hv = HttpsURLConnection.getDefaultHostnameVerifier();
        return hv.verify("192.168.0.8", session);
*/

    }
};


private final OkHttpClient client = new OkHttpClient.Builder()
                                                       .connectTimeout(5, TimeUnit.SECONDS)
                                                       //.writeTimeout(10, TimeUnit.SECONDS)
                                                       //.readTimeout(30, TimeUnit.SECONDS)
                                                       .pingInterval(25,TimeUnit.SECONDS) 
                                                       .hostnameVerifier(hostnameVerifier)
                                                       .build();  // OkHttpClient.Builder() to create a shared instance with custom settings.
``` 

Thank's.
