### ISSUE TITLE
Make GraalVM easy

### ISSUE THREAD

**Issue by swankjesse** [square/okhttp#6285]
We should add code or documentation to make it trivially easy for applications to deploy to GraalVM.

**Comment by swankjesse** [comment]
<img width="377" alt="Screen Shot 2020-09-28 at 14 17 26" src="https://user-images.githubusercontent.com/133019/94470227-5dc6da00-0195-11eb-9d04-913d6b34a8b4.png">

I’d like to get to the point where we can say this.

**Comment by JakeWharton** [comment]
It's probably safe to say that already. But yeah we should document or publish the 5-line `Platform` shim that is needed.

**Comment by yschimke** [comment]
> It's probably safe to say that already. But yeah we should document or publish the 5-line `Platform` shim that is needed.

Can't we just include that with provided svm dependencies?

**Comment by yschimke** [comment]
Does graal on JDK8 support ALPN now?

**Comment by yschimke** [comment]
I ended up with

```


@TargetClass(AndroidPlatform::class)
@Delete
class TargetAndroidPlatform {
}

@TargetClass(Android10Platform::class)
@Delete
class TargetAndroid10Platform {
}

@TargetClass(BouncyCastlePlatform::class)
@Delete
class TargetBouncyCastlePlatform {
}

@TargetClass(ConscryptPlatform::class)
@Delete
class TargetConscryptPlatform {
}

@TargetClass(Jdk8WithJettyBootPlatform::class)
@Delete
class TargetJdk8WithJettyBootPlatform {
}

@TargetClass(OpenJSSEPlatform::class)
@Delete
class TargetOpenJSSEPlatform {
}

@TargetClass(Platform.Companion::class)
class TargetPlatform {
  @Substitute
  fun findPlatform(): Platform {
    return Jdk9Platform.buildIfSupported()!!
  }
}
```

**Comment by yschimke** [comment]
Is this what you were imagining https://github.com/square/okhttp/pull/6292?

Working with okcurl showed it's pretty bad with it's log output, but leaving that for another day.  Noone is using this I hope.

**Comment by yschimke** [comment]
Should be supported in core module, still a possibility we find other cases in the secondary modules.

**Comment by yschimke** [comment]
Tested okcurl:nativeImage on mac, which works fine.

**Comment by adriancole** [comment]
for those watching at home..

```bash
./gradlew :okcurl:nativeImage
okcurl/build/graal/okcurl
```

**Comment by yschimke** [comment]
Also here https://github.com/square/okhttp#graalvm-native-image

**Comment by yschimke** [comment]
Tested downstream build which workied fine with okhttp.  Most likely source of issues I'm worried about remain some codepath in additional modules or error handling, possibly something obscure like actually broken SSL implementation (literally the return 42 case).
