### ISSUE TITLE
Do we want to switch brotli packaging?

### ISSUE THREAD

**Issue by yschimke** [square/okhttp#6291]
https://github.com/nixxcode/jvm-brotli

Jvm-Brotli aims to:

    Take the up-to-date c/c++ and Java code from google/brotli.
    Compile it on multiple platforms.
    Package the pre-compiled native libraries into JARs and upload them to maven central

**Comment by swankjesse** [comment]
Looks like a nice project. Let's wait til there's a 1.0.

**Comment by yschimke** [comment]
I was going to ask about 1.0 plans, but it doesn't seem actively maintained so closing this out.
