### ISSUE TITLE
Document GraalVM as a security provider

### ISSUE THREAD

**Issue by swankjesse** [square/okhttp#6297]
I think it’s worth a row in this table. In particular we should note TLSv1.3 and HTTP/2 support.

https://square.github.io/okhttp/security_providers/

**Comment by yschimke** [comment]
https://github.com/square/okhttp/pull/6298

**Comment by yschimke** [comment]
![image](https://user-images.githubusercontent.com/231923/94931101-3f2b5080-04bf-11eb-85b4-d7fccac9b7b3.png)
