### ISSUE TITLE
Minor issue with the current documentation.

### ISSUE THREAD

**Issue by rit001** [square/okhttp#6309]
The "Post to a Server" example provided within the Overview section of the documentation has issues, as does the full example it links to

    https://square.github.io/okhttp/

- The example uses RequestBody.create which seems to be deprecated for 4.x based development

- The example use of RequestBody.create (json, JSON) seems to be incorrect for 3.x code as the contentType of JSON should be the first parameter, not the second.

Combined these do a great job of tripping up anyone who is new to the library.

**Comment by rit001** [comment]
OK, I can answer my own issue now - it would still seem like a good idea for the documentation to be clearer than it currently is.

The problem comes from the changes made between 3.x and 4.x code bases, combined with what can be found on the internet and the fact that you can't really tell what basic published examples are coded against, even if import statements are part of the example.

Between 3.x and 4.x RequestBody.create went from a parameter list of (JSON, json) to (json, JSON) where json is the String and JSON is the media type. This is easy to find in the 3.x API docs, but the 4.x API docs are far more complex as RequestBody has become an abstract class. There is a Companion Object Fuction listed call toRequestBody which when you go into its detail you find a Kotlin annotation that maps toRequestBody back to .create. For many hacks/basic developers this is 'as clear as mud'.

Trying to understand all of this was made more complicated by the design of the Request class - its toString method does not output a representation of the request's body, while the RequestBody toString method just outputs the name assigned to the class instance. These slow down the process of understanding what is going on - but I got there in the end.

**Comment by yschimke** [comment]
This appears right for 4.x onwards

```
    Request request = request().post(RequestBody.create("Hi?", PLAIN)).build();
```
