### ISSUE TITLE
Cache response of 404 remains in DIRTY state

### ISSUE THREAD

**Issue by clhols** [square/okhttp#6310]
I am loading images and some return 404 with Cache-Control: public,max-age=14400, so they are expected to be cached and should return the same response from the cache if the request is fired immediately after.

But OkHttp continues to make network calls for the same URLs that previously returned 404.

By debugging I see that the responses are being added to the cache.
And I also see that when DiskLruCache.get is called, it find and entry like this:

entry = {DiskLruCache$Entry@13303} 
 cleanFiles = {ArrayList@13314}  size = 2
 currentEditor = {DiskLruCache$Editor@13315} (done = false)
 dirtyFiles = {ArrayList@13316}  size = 2
 key = "8de3449f0d6a2600f14b90d117fdec10"
 lengths = {long[2]@13318} 
 lockingSourceCount = 0
 readable = false
 sequenceNumber = 0
this$0 = {DiskLruCache@9735} 
zombie = false

So because readable is false, the get() call returns null.
The cache entry remains in dirty state and never becomes clean.
completeEdit is never called for that entry.

I need a little help where to put the next breakpoint to determine why it never becomes clean.

**Comment by yschimke** [comment]
The stock answer I think on this tends to be that you need to consume the body for caching to work.  Are you reading the cached body?

**Comment by clhols** [comment]
It's Coil that loads the images. But I will try to make a request manually and read the body and see if the cache entry becomes "clean".

**Comment by yschimke** [comment]
Can you enable the logging event listener which should include cache events.

**Comment by clhols** [comment]
I did the manual request and you were right. When I read the body the cache entry becomes "clean".
I will report a bug to Coil. Thank you for helping out!
