### ISSUE TITLE
HttpLoggingInterceptor logs cluttered by long or binary files bodies

### ISSUE THREAD

**Issue by 14v** [square/okhttp#6312]
Some requests contain data that is not filtered by HttpLoggingInterceptor's `Buffer.isProbablyUtf8` e.g. `multipart/form-data`, `image/jpeg`
```
I/okhttp.OkHttpClient: H�!����
```
Search gives some attempts to fix that:
https://github.com/square/okhttp/pull/3833
https://stackoverflow.com/questions/46340230/make-httplogginginterceptor-do-not-log-images

But none of them protect from cluttering logs by certain content type that can represent big files uploaded to server which contents does not matter to log.

Is it OK to implement filtering by content type
```
var omitBodyContentTypes = arrayOf()

if(contentType in omitBodyContentTypes) {
       logger.log(
              "--> END ${request.method} (content type $contenType excluded, ${requestBody.contentLength()}-byte body omitted)")
}
else if (buffer.isProbablyUtf8()) {
          ...
        } 
else {
          logger.log(
              "--> END ${request.method} (binary ${requestBody.contentLength()}-byte body omitted)")
        }
```
and init 
```
.addInterceptor(HttpLoggingInterceptor()
                    .setLevel(HttpLoggingInterceptor.Level.BODY))
                    .setOmitBodyContentTypes(arrayOf("multipart/form-data", "image/jpeg"))
```

Please comment if I can make PR with code above or need to improve something.

logging-interceptor:4.9.0

**Comment by yschimke** [comment]
We are holding a pretty consistent line on this.

https://github.com/square/okhttp/issues/6085#issuecomment-633201058

> 
> We generally don't add incremental new features to the http logging interceptor. Even if clearly useful like this.
> 
> I'd suggest you fork this module and add the features you need to a local codebase. If you feel strongly it should be in a shared utility library instead of your codebase, you could even publish it as a library on GitHub. There are lots of individual requests that all make sense for this area, which is why we don't add them. The change rate of the public API for this would be much faster than the rest of the core of OkHttp.
