### ISSUE TITLE
CookieJar override "Cookie" header

### ISSUE THREAD

**Issue by nv95** [square/okhttp#6316]
**Stepss to reproduce:**
1) Set CookieJar using `OkHttpClient.Builder.cookieJar`
2) Receive any cookies from server
3) Try to pass "Cookie" header in request using `Request.Builder.addHeader("Cookie", "your_custom_cookie")`

**Expectations:**
Request contain header, passed using `Request.Builder.addHeader`

**Actual result:**
Cookies from `CookieJar` are exists in request headers, but cookie passed via request builder is missing

I think problem in [BridgeInterceptor:76](https://github.com/square/okhttp/blob/924bd081d008c18ebed377462765734ce9dfc07f/okhttp/src/main/kotlin/okhttp3/internal/http/BridgeInterceptor.kt#L76)
It call 
`requestBuilder.header("Cookie", cookieHeader(cookies))`
that remove any headers with name "Cookie" from request. Maybe, simple replacing it with 
`requestBuilder.addHeader("Cookie", cookieHeader(cookies))`
will resolve this problem

**Comment by yschimke** [comment]
@swankjesse Any thoughts?

https://tools.ietf.org/html/rfc6265#section-4.2.2

   Although cookies are serialized linearly in the Cookie header,
   servers SHOULD NOT rely upon the serialization order.  In particular,
   if the Cookie header contains two cookies with the same name (e.g.,
   that were set with different Path or Domain attributes), servers
   SHOULD NOT rely upon the order in which these cookies appear in the
   header.

Seems like overriding/selection is expected by the client, as the server can't do anything intelligent (no attributes like path are sent), but needs to do something other than rely on the ordering.

**Comment by swankjesse** [comment]
Natural workaround is to set manual cookies via the Cookie jar, not via headers.

**Comment by nv95** [comment]
@swankjesse what if I need cookies for specified request but not for specific host?
I

**Comment by swankjesse** [comment]
@nv95 that’s not typically how cookies work.

**Comment by swankjesse** [comment]
(you can specify a host and path when you add a cookie)

**Comment by yschimke** [comment]
@swankjesse as it seems intentional by the client, any objections if we take an explicit cookie header as a signal to use either

a) that individual cookie name as the one to send
b) skip settings cookies overall?

I can see this breaking someone somewhere.

alternative is 

c) use addHeader and send both

@nv95 a workaround it to set this in a network interceptor after the BridgeIntercetor where these are set.

**Comment by swankjesse** [comment]
Yeah I'm mostly worried about breaking someone. For example, what if the same cookie is in both the user's header and the cookie jar?

**Comment by nv95** [comment]
> @nv95 a workaround it to set this in a network interceptor after the BridgeIntercetor where these are set.

I tried to add cookie in Request builder, not in Interceptor

**Comment by yschimke** [comment]
Closing as won't fix.  Cookie's are not exposed at the request level at the moment.  They are more stateful for a client to have a sequence of operations against a server. The fix will break someone, and there is a clear workaround.
