### ISSUE TITLE
Okhttp not working after update android studio

### ISSUE THREAD

**Issue by bolds07** [square/okhttp#6331]
I've an Android app using retrofit 2 and okhttp for its json requests. everything was going fine until android studio(AS) oferred me the update from 3.9.6 to 4.1
The update is done easily inside the AS and it also updates the gradle plugin. 

Once the update was finished I rebuild and compiled a new aab, then i notice the new file generated was 100kb smaller than the previous one (altough no code or assets changes were made, only the IDE version updated)... then i release on google play and download it in my test device (real phone). It didn't work. The app opens but it is not able to perform any okhttp request

I tried to run inside AS emulator ->  it worked fine.
I tried to run in the emulator with minifyEnabled true shrinkResources true -> it worked fine

so i added to the code several debug calls in order to let me know exaclty until what line the app was working.... and i got.

 ```
try {
                okHttpClient.newCall(new Request.Builder().get().url("https://www.google.com").build()).execute();
                return true;
            } catch (Exception e) {
                return false;
            }
``` 

this is a little snippet i use to test if user has internet connection.
No exception is thrown, no value is returned, the call simple dive into the okhttp api and never come back...

So i want to let clear: no code was changed, no api was updated, no r8 rules was changed
the only thing changed was the AS updated from 3.9.6 to 4.1 and some mandatory gradle plugin updated as well
after that the signed aab built got 100kb smaller and this very weird behavior started happening...

I've already tried EVERYTHING i can, but still no idea how to solve. does anyone ever face a similar problem or have idea what to do?

there are my imports

```
  implementation 'com.squareup.picasso:picasso:2.71828'
    implementation 'androidx.lifecycle:lifecycle-extensions:2.2.0'

    implementation('com.facebook.android:facebook-login:5.13.0') {
        exclude group: 'com.android.support', module: 'appcompat-v7'
    }

    //retrofit
    implementation('com.squareup.retrofit2:retrofit:2.9.0') {
        exclude group: 'com.squareup.okhttp3', module: 'okhttp'
    }

 
    implementation "com.squareup.okhttp3:okhttp:4.10.0-RC1"
    implementation 'com.squareup.okio:okio:2.9.0'
    implementation 'com.google.code.gson:gson:2.8.6'
    implementation('com.squareup.retrofit2:converter-gson:2.9.0') {
        exclude group: "com.google.code.gson", module: "gson"
    }
```

**Comment by swankjesse** [comment]
Wanna ask on StackOverflow? There's not enough to go on here to reproduce or fix the problem.

**Comment by bolds07** [comment]
@swankjesse 
can you please re-open? i can provide extra info as much a you need just tell me.

in a brief sentence the problem is:
after update AS from 3.9.6 to 4.1 okhttp doest work for signed apk. non signed apk still work fine

I mean:
 inside the 4.1 AS if i build unsigned apk and install in the phone it works 100%
if i build signed apk and install in the same phone no requests work... they dont throw exception nor return anything

any more info you want im really here to look for

**Comment by bolds07** [comment]
```
  AsyncTask.THREAD_POOL_EXECUTOR.execute(() -> {
             
                    runOnUiThread(() -> {
                        new AlertDialog.Builder(this).setMessage("a").show();
                    });
                    try {
                        new OkHttpClient.Builder().build().newCall(new Request.Builder().get().url("https://www.google.com.br/").build()).execute();
                    } catch (IOException e) {
                        runOnUiThread(() -> {
                            new AlertDialog.Builder(this).setMessage("c").show();
                        });
                    }
                    runOnUiThread(() -> {
                        new AlertDialog.Builder(this).setMessage("b").show();
                    });

                      
            }
```

running this during the onCreate of the main activity.

if the apk is signed it will show 'a' then loop forever
if unsigned apk it will show 'a' then 'b'

**Comment by swankjesse** [comment]
What else is different between signed and unsigned APKs? Are you using R8 or Proguard? Do you have ProGuard rules that strip out methods like Object.notify() ?
