### ISSUE TITLE
Okhttp mDNS

### ISSUE THREAD

**Issue by baldhead69** [square/okhttp#6332]
Has Okhttp a mDNS support library implementation ?

I am trying to use dns-sd in android plataform.

**Comment by swankjesse** [comment]
OkHttp doesn't do mDNS and I'm not sure how it'd work if we had it. What did you have in mind?

**Comment by baldhead69** [comment]
Hi @swankjesse ,

Finding devices in a local network.

Example:
iot devices running some type of server like websocket or other server types.

**Comment by yschimke** [comment]
Can I suggest moving this discussion to stackoverflow?

It's not clear that OkHttp can solve the discovery part, but you could make this work at either the DNS or SocketFactory level I assume.

https://stackoverflow.com/questions/1233204/are-there-any-other-java-libraries-for-bonjour-zeroconf-apart-from-jmdns
https://stackoverflow.com/questions/28482168/dns-sd-experience-with-mdnsjava

**Comment by baldhead69** [comment]
Hi,

i used the nsd lib, but the lib are a little complicated to use, or i didnt understand how to use/config

I was able to connect to a local websocket server using this lib. 
 My idea would be to present a list (recycler view?) of devices on the local network for the user to select which device to connect.

A okhttp user friendly lib would be welcome, or not ?

Nsd:
https://developer.android.com/training/connect-devices-wirelessly/nsd#java

**Comment by yschimke** [comment]
For this I suggest you publish your own library. Nothing for OkHttp here
