### ISSUE TITLE
Getting bad request for web socket connection?

### ISSUE THREAD

**Issue by wishy-viewlift** [square/okhttp#6337]
I am creating a web socket connection from my android app but I am getting the bad request. The connection is not opening.

I am using the below code

`String TAG = "AppCMSSocket";
        OkHttpClient clientCoinPrice = new OkHttpClient();

        Request requestCoinPrice = new Request.Builder().url("https://staging-api.viewlift.com" + "/notification?token=" + getAuthToken()).build();
        WebSocketListener listener=new WebSocketListener() {
            @Override
            public void onClosed(okhttp3.WebSocket webSocket, int code, String reason) {
                Log.i(TAG + " " + ("onClosed"), reason);
            }

            @Override
            public void onClosing(okhttp3.WebSocket webSocket, int code, String reason) {
                webSocket.close(1000, null);
                webSocket.cancel();
                Log.i(TAG + " " + ("onClosing"), reason);
            }

            @Override
            public void onFailure(okhttp3.WebSocket webSocket, Throwable t, okhttp3.Response response) {
                if (response != null) {
                    Log.e(TAG + " " + ("onFailure"), response.message());
                    if (response.networkResponse() != null)
                        Log.e(TAG + " " + ("onFailure"), response.networkResponse().toString());
                    if (response.body() != null)
                        Log.e(TAG + " " + ("onFailure"), response.body().toString());
                }
            }

            @Override
            public void onMessage(okhttp3.WebSocket webSocket, String text) {
                Log.i(TAG + " " + ("onMessage"), text);
            }

            @Override
            public void onMessage(okhttp3.WebSocket webSocket, ByteString bytes) {
                super.onMessage(webSocket, bytes);
            }

            @Override
            public void onOpen(okhttp3.WebSocket webSocket, okhttp3.Response response) {
                webSocket.send(new Gson().toJson(new SocketData("subscribe", "SUBSCRIPTION", getAuthToken())));
                Log.i(TAG + " " + ("onOpen"), response.message());
            }
        };

        clientCoinPrice.newWebSocket(requestCoinPrice, listener);
        clientCoinPrice.dispatcher().executorService().shutdown();`

Can you point me what is wrong here

`onFailure: Bad Request
             onFailure: Response{protocol=http/1.1, code=400, message=Bad Request,
            `

**Comment by yschimke** [comment]
This isn't really something we can help you with.  You should make a reproducible test case and ask on stackoverflow, but this doesn't appear to be a bug report.
