### ISSUE TITLE
Google still warns of NonSdkApiUsedViolation for 3.14.9

### ISSUE THREAD

**Issue by JimJayLee** [square/okhttp#6344]
I found the reflection of no-sdk-api remains in used below android 11.

```java
@Nullable
  public static Platform buildIfSupported() {
    if (!Platform.isAndroid()) {
      return null;
    }
    
    try {
      if (getSdkInt() >= 29) {
        
        sslParametersClass = Class.forName("com.android.org.conscrypt.SSLParametersImpl");
        
        return new Android10Platform(sslParametersClass);
      } 
    } catch (ReflectiveOperationException sslParametersClass) {}

    
    return null;
  }
```

I uploaded the APK to google developer console for test, they keep complaining  about the NO-SDK-API use. Is it safe to ignore these warnings. Because I end up finding out even above 4.x , okhttp still uses these no-sdk-apis.

<img width="595" alt="image" src="https://user-images.githubusercontent.com/11881446/97145486-403f5d00-17a1-11eb-9455-a08a252a7f9d.png">

**Comment by yschimke** [comment]
We don't support the 3.14.x branch anymore, see https://square.github.io/okhttp/security/

This (hopefully) shouldn't be an issue anymore with 4.9 builds.  See https://github.com/square/okhttp/blob/master/okhttp/src/main/kotlin/okhttp3/internal/platform/android/Android10SocketAdapter.kt

**Comment by JimJayLee** [comment]
@yschimke Thank for your nice reply.  However,  our project is avoiding using Kotlin, so we keep okhttp below 4.x. Is that another way to fix that problem?

**Comment by yschimke** [comment]
You can fork the codebase and make the changes you need in a private build?
