### ISSUE TITLE
okhttp overwrites the host header for HTTP/1.1

### ISSUE THREAD

**Issue by XiaoHanChina** [square/okhttp#6345]
Either way, okhttp will overwrite my host header to google.com. 
```
new Request.Builder().url("http://google.com").header("Host","github.com")...

new OkHttpClient.Builder(). .addNetworkInterceptor(chain -> {
            Request request = chain.request().newBuilder()
                .header("Host", "github.com")
                .build();
            return chain.proceed(request);
          })
```

Is there any way to make the host header diffrent with the url's host.

**Comment by krishnakeshan** [comment]
```
Request request = new Request.Builder()
.url("https://google.com")
.header("Host", "github.com")
.build();
System.out.println(request);
```

This produces the following output for me:
`Request{method=GET, url=https://google.com/, headers=[Host:github.com]}`

Could you elaborate some more on your issue?

**Comment by yschimke** [comment]
This should be definitely be supported in a network interceptor for domain fronting

https://github.com/square/okhttp/commit/8864c5d687df432021a4409aad4e0448ed030c5a
https://github.com/square/okhttp/issues/4083

**Comment by XiaoHanChina** [comment]
> ```
> Request request = new Request.Builder()
> .url("https://google.com")
> .header("Host", "github.com")
> .build();
> System.out.println(request);
> ```
> 
> This produces the following output for me:
> `Request{method=GET, url=https://google.com/, headers=[Host:github.com]}`
> 
> Could you elaborate some more on your issue?

If you print header on the server side (in this case, "google.com" is your server), the host header which your server receive is "google.com", but not "github.com" you set.

**Comment by XiaoHanChina** [comment]
> ```
> Request request = new Request.Builder()
> .url("https://google.com")
> .header("Host", "github.com")
> .build();
> System.out.println(request);
> ```
> 
> This produces the following output for me:
> `Request{method=GET, url=https://google.com/, headers=[Host:github.com]}`
> 
> Could you elaborate some more on your issue?

If you print header on the server side (in this case, "google.com" is your server), the host header which your server receive is "google.com", but not "github.com" you set.

**Comment by yschimke** [comment]
I think this is a problem with your server, testing with httpbin shows it is working

```
fun main() {
  val client = OkHttpClient.Builder().addNetworkInterceptor {
    println(it.request().headers)
    it.proceed(it.request().newBuilder().header("Host", "www.httpbin.org").build())
  }.build()

  println(client.newCall(Request.Builder().url("https://httpbin.org/get").build()).execute().body?.string())
}
```

Response

```
{
  "args": {}, 
  "headers": {
    "Accept-Encoding": "gzip", 
    "Host": "www.httpbin.org", 
    "User-Agent": "okhttp/4.10.0-SNAPSHOT", 
    "X-Amzn-Trace-Id": "Root=1-5f97ab1b-3e4cc3071f33c3b764b309e8"
  }, 
  "origin": "82.0.236.178", 
  "url": "https://www.httpbin.org/get"
}
```

**Comment by XiaoHanChina** [comment]
> I think this is a problem with your server, testing with httpbin shows it is working
> 
> ```
> fun main() {
>   val client = OkHttpClient.Builder().addNetworkInterceptor {
>     println(it.request().headers)
>     it.proceed(it.request().newBuilder().header("Host", "www.httpbin.org").build())
>   }.build()
> 
>   println(client.newCall(Request.Builder().url("https://httpbin.org/get").build()).execute().body?.string())
> }
> ```
> 
> Response
> 
> ```
> {
>   "args": {}, 
>   "headers": {
>     "Accept-Encoding": "gzip", 
>     "Host": "www.httpbin.org", 
>     "User-Agent": "okhttp/4.10.0-SNAPSHOT", 
>     "X-Amzn-Trace-Id": "Root=1-5f97ab1b-3e4cc3071f33c3b764b309e8"
>   }, 
>   "origin": "82.0.236.178", 
>   "url": "https://www.httpbin.org/get"
> }
> ```

Hi there, thanks for your help.

After serveral test, I have located the problem.

In your case, if you change your url `https://httpbin.org/get` to `http://httpbin.org/get`, the host you set `www.httpbin.org` will be reset to `httpbin.org`. In https, the host header will not be reset.

**Comment by yagyank** [comment]
Hi,
Is this still an open issue? Can I pick it up?

**Comment by swankjesse** [comment]
Yeah, the host header us replaced on redirect. If you want that to survive a redirect please do it in a network interceptor.
