### ISSUE TITLE
when websocket execute webSocket.close(1000, null),WebSocketListener onfailue java.net.socketexception:socket closed

### ISSUE THREAD

**Issue by huwencheng** [square/okhttp#6348]
when websocket execute webSocket.close(1000, null),WebSocketListener onfailue java.net.socketexception:socket closed

**Comment by yschimke** [comment]
Please post a reproduction on stackoverflow for community support.

**Comment by Alanqiu** [comment]
Hello, I also encountered the same situation, how did you solve it?
