### ISSUE TITLE
Migrate all tests to Junit 5

### ISSUE THREAD

**Issue by yschimke** [square/okhttp#6360]
Related to https://github.com/square/okhttp/issues/6296

We should run our tests with Junit 5, for better test features, graal support and dogfooding our mockwebserver-junit5.

**Comment by swankjesse** [comment]
And run the GraalVM tests in CI!

**Comment by yschimke** [comment]
Is this 4.10 blocking?

**Comment by swankjesse** [comment]
For 4.10 I’d like to know what our GraalVM bugs are.

**Comment by yschimke** [comment]
Closing with https://github.com/square/okhttp/pull/6421

Separate task for CI.
