### ISSUE TITLE
Run GraalVM tests in CI

### ISSUE THREAD

**Issue by yschimke** [square/okhttp#6364]
Related to https://github.com/square/okhttp/issues/6360

**Comment by yschimke** [comment]
Moved to 4.10 per https://github.com/square/okhttp/issues/6360#issuecomment-719951296

**Comment by yschimke** [comment]
@swankjesse if any of the test PRs I've put up overlap with yours then feel free to close or takeover. Otherwise put comments as needed for me to address.

**Comment by yschimke** [comment]
@swankjesse do you have anyone at square who wants to do the CI migration to github? Add in targets for Graal and Android?

It feels a good point to bank the win of getting Graal and Android tests working post Junit5.  But I don't have motivation, time or access to get involved in that side of things.

Also relates to https://github.com/square/okhttp/issues/5704

**Comment by swankjesse** [comment]
Just me as far as I know!

**Comment by yschimke** [comment]
https://github.com/square/okhttp/pull/6459

**Comment by yschimke** [comment]
Think we are hitting memory limits - https://app.circleci.com/pipelines/github/square/okhttp/4334/workflows/12974832-b144-48b4-aef5-f4d0808c91b8/jobs/19477
