### ISSUE TITLE
OkHttpClient injected with Koin loses Authorization header

### ISSUE THREAD

**Issue by QuarK264** [square/okhttp#6393]
I'm adding DI to the existing project, in process I faced problem that header Authorization disappears from request. There is no any exceptions or logs from Retrofit/OkHttp. My dependencies are:

    implementation 'com.squareup.retrofit2:retrofit:2.6.0'
    implementation 'com.squareup.okhttp:okhttp:2.7.5'
    implementation 'com.squareup.okhttp3:logging-interceptor:3.10.0'
    implementation 'org.koin:koin-android:2.1.3'

I create http client using `provideClient`:

    class OkHttpProvider private constructor() {
    
        companion object {
    
            fun provideClient(credentials: UsernamePasswordCredentials? = null, context: Context): OkHttpClient {
                val client = OkHttpClient.Builder()
                // logs
                if (BuildConfig.DEBUG) {
                    client.addInterceptor(
                            HttpLoggingInterceptor().setLevel(HttpLoggingInterceptor.Level.BODY)
                    )
                }
    
                if (credentials != null) {
                    val creds = Credentials.basic(credentials.userName, credentials.password)
                    val headerInterceptor = Interceptor { chain ->
                        var request = chain.request()
                        val headers = request
                                .headers()
                                .newBuilder()
                                .add("Authorization", creds)
                                .build()
                        request = request.newBuilder().headers(headers).build()
                        chain.proceed(request)
                    }
                    //client.addInterceptor(AccessTokenInterceptor(credentials))
                    client.addInterceptor(headerInterceptor)
                }
    
                client
                        .callTimeout(60L, TimeUnit.SECONDS)
                        .connectTimeout(10L, TimeUnit.SECONDS)
                        .readTimeout(60L, TimeUnit.SECONDS)
                        .writeTimeout(60L, TimeUnit.SECONDS)
                        .sslSocketFactory(getSslContext().socketFactory).hostnameVerifier { _, _ -> true }
    
                client.addInterceptor(ChuckInterceptor(context))
    
                return client.build()
            }
    
            private fun getSslContext(): SSLContext {
                ...implementation...
            }
        }
    }

My modules for http client and Retrofit are below:

    object HttpClientModule {
        val module = module {
            single(named(COMMON)) {
                OkHttpProvider.provideClient(
                        get<SharedPreferenceManager>().getUserCredentials(),
                        androidContext()
                )
            }
            ...other versions...
        }
    
        const val COMMON = "common"
    }

    object ApiModule {
        val module = module {
            single {
                RetrofitFactory.getServiceInstance(
                        ApiService::class.java,
                        get<SharedPreferenceManager>().getString(LocalDataSource.BUILD_OPTION_API, ""),
                        get(named(HttpClientModule.COMMON))
                )
            }
            ...other apis...
        }
    }

    object RetrofitFactory {
        const val GEO_URL = "http://maps.googleapis.com/maps/api/"
    
        fun <T> getServiceInstance(
                clazz: Class<T>,
                url: String = GEO_URL,
                client: OkHttpClient
        ): T = getRetrofitInstance(url, client).create(clazz)
    
        private fun getRetrofitInstance(
                url: String,
                client: OkHttpClient
        ) = Retrofit.Builder()
                .baseUrl(url)
                .addConverterFactory(GsonConverterFactory.create())
                .client(client)
                .addCallAdapterFactory(CoroutineCallAdapterFactory())
                .build()
    }

App starts to work with "admin" user and has some credentials saved in shared preferences, when user starts login with phone and sms and requests are sent with "admin" Authorization header, when user inputs code from sms and his new user credentials are saved in shared preferences. After that app sends two requests and Authorization header isn't presented in them. I saw it in Chuck, I even rechecked it using Charles.

<img src="https://i.stack.imgur.com/Mix2g.jpg" width="300"> <img src="https://i.stack.imgur.com/Ar1bV.jpg" width="300">

To fix this problem I tried few solutions. Firstly, I changed inject for http client from `single` to `factory`, that didn't work. Secondly, I googled the problem, but I didn't mentions of this phenomenon. Thirdly, I wrote `AccessTokenInterceptor` according to <a href="http://sangsoonam.github.io/2019/03/06/okhttp-how-to-refresh-access-token-efficiently.html">this</a> article and also cover everything with logs. I noticed that interceptor works fine in normal cases, but when Authorization header is missing method `intercept` is not called. This might be reason why default `headerInterceptor` also not working. Fourthly, I upgraded versions of Retrofit and OkHttp, this also didn't helped.

I noticed interesting thing about that bug: if I restart app after Retrofit lost Authorization header, app works fine test user is properly logged with correct token. Any attempts to relog without restarting the app fails.

**Comment by swankjesse** [comment]
This sounds like a Koin bug. There's not much we can do about it. Have you considered Anvil or Hilt?

**Comment by QuarK264** [comment]
Do you think this a Koin bug? Ok, thanks I will research that way then. No, I haven't tried them, maybe I really should try another DI.
