### ISSUE TITLE
Custom truststores on IBM WebSphere Application Server have no effect on okhttp ssl connection

### ISSUE THREAD

**Issue by dicer** [square/okhttp#6394]
This was tested on okhttp 3.14.9, because we are using retrofit 2.9.0, but I had a look at the current source and it seems nothing changed when it comes to the problem I'm describing below:

WebSphere Application Server (Version 9.0.5.3 here) allows you to add TLS certificates to a custom truststore in the WebUI that is then used by the applications running on the server. That is: Both the IBM JDKs truststore as well as the custom truststore are somehow merged and used when making SSL connections in a Java app running on WAS.

This gives you an easy way to import a custom (self-signed) CA.
That was working fine for all our backends (DB, LDAP, Webservices etc), except for one and that one was using okhttp to make the connection. It first failed with no matching cipher (which was easily fixed by adding com.ibm.jsse2.overrideDefaultTLS=true) and then failed with a PKIX error when trying to find a valid certification path. Turns out okhttp does not use both truststores, but only the JDK one without my custom CA.

What I found out:
1. If you get the TrustManager the following way, you will always end up with the JDK certs **only**. The certs in the custom truststore would not be there.
```
TrustManagerFactory tmf = TrustManagerFactory.getInstance(TrustManagerFactory.getDefaultAlgorithm());
tmf.init((KeyStore) null);
```
2. Getting a SSLSocketFactory using `SSLContext.getInstance("SSL").getSocketFactory()` will also give you the JDK certs **only**.

3. I tried hard to find a way to get the TrustManager out of socket factories (with reflection) but only succeeded when running on the IBM JDK on the **command line**. When running on a **WebSphere server**, the SSLSocketFactory you get looks complete different again and does not seem to contain a TrustManager object... see https://github.com/square/okhttp/issues/2427#issuecomment-722336577 for the cmdline approach.

4. I found a way to get a SSLSocketFactory though that does work! `HttpsURLConnection.getDefaultSSLSocketFactory()` gives you one that queries both TrustStores!

I now have it working using something like this:
```
tmf = TrustManagerFactory.getInstance(TrustManagerFactory.getDefaultAlgorithm());
tmf.init((KeyStore) null);
defaultJDKTrustmanger = trustManagerFactory.getTrustManagers()
...
builder.sslSocketFactory(HttpsURLConnection.getDefaultSSLSocketFactory(), defaultJDKTrustmanger)
``` 

The obvious problem here: HttpsURLConnection gives you the correct trusts, where defaultJDKTrustmanger contains only the JDKs trusted certs.
So as far as I can see, certificate pinning does not work with this approach.

I actually wanted to do a pull request to fix the whole IBM JDK/WAS mess (of course not your fault), but I have no idea if e.g. the change to HttpsURLConnection.getDefaultSSLSocketFactory() makes sense to implement by default? That would also get rid of issue #5372 but might have other consequences I can't foresee.
Same when it comes to the mismatching TrustManagers. Would it make sense to detect the IBM JDK and not have a certificateChainCleaner in that case? What are the security implications of that?
Or do you know of a different way to get the default trustmanager?

I wasn't sure if I should report this here, as it seems to be IBMs fault for implementing this weird. Maybe you have some more ideas about this or in the very least this can serve as some form of documentation for others.

**Comment by yschimke** [comment]
It seems like one to raise with IBM.  There are public APIs here like X509TrustManager, if you have one that you can show doing valid operations and OkHttp does the wrong things, then it's a bug for us.

If you can show that IBM is doing the wrong thing here, then it's on them.

We won't implement any platform specific logic here for them, so it's on you to do all the extra logic and set a custom socket factory and trust manager.


Consider something like https://github.com/yschimke/okurl/blob/07e79795e14b9163bcf4342f39c23020f51ecf64/src/main/kotlin/com/baulsupp/okurl/security/MergedX509TrustManager.kt if you need to combine two distinct trustmanagers.
