### ISSUE TITLE
The documentation is not clear enough about sharing a single okhttp client.

### ISSUE THREAD

**Issue by afaucogney** [square/okhttp#6396]
In the documentation, it is clear said that we should share a single instance. Ok
If an app deals with several Apis or EndPoints, app has still to share it instance, but may configure it with "newBuilder" to setup specificities

However in the doc, this is said : 
`You can customize a shared OkHttpClient instance with newBuilder. This builds a client that shares the same connection pool, thread pools, and configuration. Use the builder methods to configure the derived client for a specific purpose.`

What is the share `configuration` about ?

Is any setup done with the builder, is share then to the new setup build with new builder ? (interceptor, cache, timeouts, headers....)

https://square.github.io/okhttp/4.x/okhttp/okhttp3/-ok-http-client/#okhttpclients-should-be-shared

**Comment by swankjesse** [comment]
The newBuilder() call retains everything.

**Comment by afaucogney** [comment]
Ok it does mean that the single okhttp instance should only setup common configuration, because every configuration cannot be removed ? is that right ?

**Comment by swankjesse** [comment]
Yep, that sounds good.

**Comment by yschimke** [comment]
@afaucogney feel free to submit a doc PR for review to clarify, otherwise closing this out.

**Comment by afaucogney** [comment]
@yschimke https://github.com/square/okhttp/pull/6449
