### ISSUE TITLE
When I use Okhttp 4.9.0 and open minifyEnabled will crash

### ISSUE THREAD

**Issue by xloger** [square/okhttp#6448]
I recently integrated Okhttp in my project,when I `implementation("com.squareup.okhttp3:okhttp:4.9.0")`,  my project will crash:
> lateinit property timeLineLayout has not been initialized

This is very strange, I just implementation okhttp, it has not been initialized with code.if I use debug build or `minifyEnabled false`,it is normal.if I use Okhttp 4.8.1 or last,it is normal,4.9.0 and 4.10.0-RC1 will crash.

This "TimeLineLayout" is my custom view, I created it in an Activity and held its reference in a Kotlin Object through lateinit.It should have nothing to do with Okhttp.I believe the way I use it is correct,and it has been running normally for several months.

I think it's more like proguard's problem?I tried to reproduce this problem in a new project, but I'm sorry I failed.

I really want to provide a lot of information, but I have no clue,sorry.I will use 4.8.1,it is normal.

I think I should tell you about it. Maybe you know why.If you don't know what this means, you can close this issue.

**Comment by yschimke** [comment]
Please raise this type of issue on stackoverflow, or reduce to a failing build in a github project we can debug.

**Comment by xloger** [comment]
I finally found a solution to reproduce bugs with new projects...and know reason
this project:<https://github.com/xloger/OkHttpTest> can reproduce this crash.
This is a kotlin bug caused by gradle, which has nothing to do with okhttp.I'm sorry to bother you, you can ignore the after content.But if you are interested, I can describe it.
I have a father class,son class extends for some feature:
```kotlin
open class TimeLineHelper {
    protected lateinit var timeLineLayout: TimeLineLayout

    open fun init(timeLineLayout: TimeLineLayout) {
        this.timeLineLayout = timeLineLayout
    }
}
```
a son class:
```kotlin
object FrameHelper : TimeLineHelper() {

//    override fun init(timeLineLayout: TimeLineLayout) {
//        super.init(timeLineLayout)
//    }

    fun useTest() {
        println("test: will use")
        println("test:${timeLineLayout.text}")
    }
}
```
`FrameHelper.init(this)` will call on TimeLineLayout initialize.
I think my writing is fine, except that the object extends class is a little strange.It runs normally in my previous version until today.
It is normal in debug or okhttp 4.8.1.
I keep trying and find that if I implementation init fun, it will be normal in any case,Although it doesn't change any function.Its content is just like my annotation.

At that time, I tried to reproduce this problem in the new project, but it still did not take effect.Then I find if I make gradle version from 6.1.1 to 6.5, gradle build tools frome 4.0.0 to 4.1.1,it will be normal.
So I think it is a bug for gradle and kotlin and proguard.When I implementation 4.9.0 okhttp,I was forced to use a higher version of gradle, which triggered this bug.
I'm sorry to bother you because of this.
