### ISSUE TITLE
Code 302: Found after redirect results in isSuccessful == false

### ISSUE THREAD

**Issue by szsoftware** [square/okhttp#6456]
https://github.com/square/okhttp/blob/858939f025068c6d3581338317bba03e63ebd909/okhttp/src/main/kotlin/okhttp3/Response.kt#L147

**Comment by yschimke** [comment]
Not sure we would change this, as it may break others.

Why not just define your own custom `response.isSuccessful` logic instead of the ResonseCodeInterceptor?

**Comment by szsoftware** [comment]
The problem happens in a foreign implementing project, as you can see in the mentioned bug report.

So, you're right: The problem can be solved at another place (too).

However, I'm wondering, why a 302 should be a non successful response? It's just the endpoint of a redirect(ion chain).

**Comment by yschimke** [comment]
I'm also confused why it's not following the redirect, if it's just using the defaults from Retrofit.  If you can create a reproduction test case we can take a look. Let me know and we will reopen.

But if it's ultimately some external configuration and you the implementation of isSuccessful doesn't work for your case then it's something to discuss with the library maintainer. OkHttp is providing the headers and body for this request, just dropped in the library.
