### ISSUE TITLE
Is it possible to use both v3.12.x for pre-21 and v4.x for 21 above

### ISSUE THREAD

**Issue by mochadwi** [square/okhttp#6472]
Our apps still needs minimum API of 16, thus we're afraid to updates from v3.12.x to v4.x that might crashing a lot of our user below 21?

based on a lot of issue such as https://github.com/square/okhttp/issues/4622#issuecomment-465447196 did we stuck at v3.12.x then?

**Comment by yschimke** [comment]
Not sure, I'm not an expert on the options.  Is this build variants.  https://developer.android.com/studio/build/build-variants

You might get a solid answer from one of the other project maintainers, but generally this is a better question for stackoverflow.

I will say that 4.9.0 just flat out won't work on API 16, it breaks various assumptions so you should either stick to 3.12.12 or adopt some variant of your builds like your issue subject suggests.
