### ISSUE TITLE
java.lang.ExceptionInInitializerError

### ISSUE THREAD

**Issue by ramyfarah** [square/okhttp#6473]
version_okhttp = '4.8.1'
version_retrofit = '2.9.0'
Device: samsung Galaxy S10
android version: 10.0

When attempting to run the app in Android 10, the app immediately crashes with the following exception:

Fatal Exception: java.lang.ExceptionInInitializerError
okhttp3.HttpUrl$Builder.parse$okhttp (HttpUrl.kt:1239)
okhttp3.HttpUrl$Companion.get (HttpUrl.kt:1633)
okhttp3.HttpUrl$Companion.parse (HttpUrl.kt:1642)
okhttp3.HttpUrl.parse (Unknown Source:2)
com.android.papershiftstempeluhr.di.modules.ApiModule.<clinit> (ApiModule.java:56)
com.android.papershiftstempeluhr.common.ClockApp.createAppComponent (ClockApp.kt:74)
com.android.papershiftstempeluhr.common.ClockApp.onCreate (ClockApp.kt:49)
android.app.Instrumentation.callApplicationOnCreate (Instrumentation.java:1190)
android.app.ActivityThread.handleMakeApplication (ActivityThread.java:7184)
android.app.ActivityThread.handleBindApplication (ActivityThread.java:7134)
android.app.ActivityThread.access$1600 (ActivityThread.java:274)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:2102)
android.os.Handler.dispatchMessage (Handler.java:107)
android.os.Looper.loop (Looper.java:237)
android.app.ActivityThread.main (ActivityThread.java:8167)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:496)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1100)
okio.Buffer.readInt (Buffer.kt:1150)
okio.Options$Companion.of (Options.kt:77)
okhttp3.internal.Util.<clinit> (Util.kt:72)
okhttp3.HttpUrl$Builder.parse$okhttp (HttpUrl.kt:1239)
okhttp3.HttpUrl$Companion.get (HttpUrl.kt:1633)
okhttp3.HttpUrl$Companion.parse (HttpUrl.kt:1642)
okhttp3.HttpUrl.parse (Unknown Source:2)
com.android.papershiftstempeluhr.di.modules.ApiModule.<clinit> (ApiModule.java:56)
com.android.papershiftstempeluhr.common.ClockApp.createAppComponent (ClockApp.kt:74)
com.android.papershiftstempeluhr.common.ClockApp.onCreate (ClockApp.kt:49)
android.app.Instrumentation.callApplicationOnCreate (Instrumentation.java:1190)
android.app.ActivityThread.handleMakeApplication (ActivityThread.java:7184)
android.app.ActivityThread.handleBindApplication (ActivityThread.java:7134)
android.app.ActivityThread.access$1600 (ActivityThread.java:274)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:2102)
android.os.Handler.dispatchMessage (Handler.java:107)
android.os.Looper.loop (Looper.java:237)
android.app.ActivityThread.main (ActivityThread.java:8167)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:496)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1100)

**Comment by yschimke** [comment]
This looks like a better question for stackoverflow or to step through with a debugger.  We can't reproduce from this bug report. Sorry.

What URL are you trying to parse?
