### ISSUE TITLE
Javadoc jar is empty

### ISSUE THREAD

**Issue by ansman** [square/okhttp#6475]
The javadoc jar that okhttp publishes is empty. This is likely because `withJavadocJar()` is used which doesn't support dokka. 

To fix it you should be able to create a dokka task named `javadocJar` before calling it.

**Comment by yschimke** [comment]
Dupe of https://github.com/square/okhttp/issues/6475, thanks for reporting!

**Comment by ansman** [comment]
I think the dupe link is incorrect because it points back to this issue.
