### ISSUE TITLE
Feature request: replace SSLPeerUnverifiedException with a custom exception class

### ISSUE THREAD

**Issue by francescocervone** [square/okhttp#6478]
Platform: Android

Since `javax.net.ssl.SSLPeerUnverifiedException` is included in the Android framework, it cannot be obfuscated with well known tools such as Proguard, DexGuard or R8.
Not being able to obfuscate this class (and some others of `java.security` package), client apps are exposed to a security risk. Since attackers know that a `SSLPeerUnverifiedException` is thrown when certificate pinning fails, they would be able to easily inject custom code in the method that throws the exception (with hooking tools) and bypass certificate pinning.

Using a custom `okhttp3.SSLPeerUnverifiedException` instead of `javax.net.ssl.SSLPeerUnverifiedException` would allow client apps to obfuscate/encrypt it and make the attacker's life harder.

I am open to any other solution that makes OkHttp's certificate pinning stronger and less easy to break.

Thanks.

**Comment by swankjesse** [comment]
I don't think this that we can win the fight against researchers and hackers who decompile your application to change its behavior. 

`SSLPeerUnverifiedException` is easy, but if we obfuscate that it's still not that difficult to find code that calls a specific hash function to create the pin for comparison.

If you want to increase the difficulty of inspecting and potentially reverse engineering your network protocols, I recommend increasing the cost of making a valid API call:
 - Use [attestation](https://developer.android.com/training/safetynet/attestation) to get the device’s secure element to tell you about the state of the calling APK
 - Add extra requirements to your network calls. For example, require a Content-Hmac header with an HMAC of the body and other headers using a hidden key, possibly from the enclave.
 - Add an extra round of certificate pinning using your own bespoke implementation. You can do this in an interceptor.

Good luck in this arms race!

**Comment by francescocervone** [comment]
Thanks @swankjesse
