### ISSUE TITLE
Using openjdk8_252 but report not supported on jdk9+ after version 4.6.0

### ISSUE THREAD

**Issue by Qchrlis** [square/okhttp#6479]
Ref to source: okhttp3/internal/platform/Jdk9Platform.kt
```
companion object {
    val isAvailable: Boolean

    init {
      val jdkVersion: String? = System.getProperty("java.specification.version")

      val majorVersion = jdkVersion?.toIntOrNull()

      isAvailable = if (majorVersion != null) {
        majorVersion >= 9
      } else {
        try {
          // also present on JDK8 after build 252.
          SSLSocket::class.java.getMethod("getApplicationProtocol")
          true
        } catch (nsme: NoSuchMethodException) {
          false
        }
      }
    }

    fun buildIfSupported(): Jdk9Platform? = if (isAvailable) Jdk9Platform() else null
  }
```
At this code "System.getProperty("java.specification.version")" I got the value is **1.8** in openjdk8_252

So the "jdkVersion?.toIntOrNull()" is null here!!!

Then the openjdk8 version has been judged to **jdk9+** with the error report：java.lang.UnsupportedOperationException: clientBuilder.sslSocketFactory(SSLSocketFactory) not supported on JDK 9+

**Comment by swankjesse** [comment]
Yeah we should fix the wording of that message. It used to be that JDK 9 was the first release to support ALPN, but that was backported to JDK 8.

Your fix will be to call the two-argument overload of that function.

**Comment by Qchrlis** [comment]
> Your fix will be to call the two-argument overload of that function.

But the old code still followed the old execution path，it not easy to update them, like spring framework.

**Comment by yschimke** [comment]
Can you send a stack trace? We can raise an bug against them.  In the meantime you probably need to maintain a OkHttp patched version until they fix. The method has been deprecated for multiple years.

**Comment by yschimke** [comment]
PR to clear up the message https://github.com/square/okhttp/pull/6481

@Qchrlis if it feels like we are being pedantic here, it's because the goal is to have the simplest bug free experience on whatever but particularly modern systems (Android 10, JDK 9+ etc).  So we optimise this code path, but keep older clients working.  In this case to revert this behaviour we would have to commit to keeping the more complicated logic around that is potentially going to keep breaking, we don't know whether the reflection works on JDK8 > 252 and I don't really want to find out and guarantee to keep it working no matter what Oracle decide to backport.

**Comment by yschimke** [comment]
I did a quick search of spring projects on github but they all seem to use teh correct method.  Is there a particular project/version that you are hitting it with?

https://github.com/spring-projects/spring-credhub/blob/1f454ef721048b25dc124a24cb6514fcb6a25ceb/spring-credhub-core/src/main/java/org/springframework/credhub/configuration/ClientHttpRequestFactoryFactory.java

https://github.com/spring-projects/spring-vault/blob/25c3bf8fc0926d5c0914f6fa6a8cad724c819a4b/spring-vault-core/src/main/java/org/springframework/vault/client/ClientHttpRequestFactoryFactory.java

I didn't find this call in spring-boot yet.  So stacktrace would be really helpful.

Closing for now, as no further action apart from a purely informational exception message.
