### ISSUE TITLE
RetryAndFollowUpInterceptor doesn't update Host header

### ISSUE THREAD

**Issue by Adamantcheese** [square/okhttp#6487]
Some hosts expect the actual request URL host and the Host header (if it exists) to match up. When following up redirects, that header isn't updated so those hosts return a 404. If the Host header is correctly set to match up with the request URL, those hosts will properly return either another redirect or the requested content.

Test Stuff:
Initial URL: https://arch.b4k.co/mlp/image/1607719700690.png, Host header is set to "arch.b4k.co"
First redirect URL: https://b4k.co/4chan-arch-find-img.php?/mlp/1607719700690.png
You can try it out with curl -I -H "Host: arch.b4k.co" \<First redirect URL> and curl -I -H "Host: b4k.co" \<First redirect URL> and you'll see one returns a 404 and the other a 302, which should be followed up again and successfully this time.
OkHttp will always currently return a 404 in this second-redirect case because the header is still set to "arch.b4k.co". However, it should successfully follow up the second time if the Host header is set correctly.

Pay no attention to the image content, it's the first thing I picked to test with.

**Comment by swankjesse** [comment]
Omit the Host header when you construct your request. OkHttp will add it for you, and track it across redirects. The interceptor you're looking for is BridgeInterceptor.
