### ISSUE TITLE
mockwebserver3-junit5 not available on Maven Central

### ISSUE THREAD

**Issue by anadimisra** [square/okhttp#6489]
I was going through the documentation of mockwebserver3-junit5 and added the following dependency in my `pom.xml`

        <dependency>
            <groupId>com.squareup.okhttp3</groupId>
            <artifactId>mockwebserver3-junit5</artifactId>
            <version>4.9.0</version>
            <scope>test</scope>
        </dependency>

For which I get an `Dependency 'com.squareup.okhttp3:mockwebserver3-junit5:4.9.0' not found ` error.

**Comment by swankjesse** [comment]
It's too new. I'd like to cut a preview release soon.

**Comment by yschimke** [comment]
5.0.0-alpha.2 is available https://mvnrepository.com/artifact/com.squareup.okhttp3/mockwebserver3-junit5
