### ISSUE TITLE
Ciphers ignored, why?

### ISSUE THREAD

**Issue by ogolovanov** [square/okhttp#6492]
Hi.

I am building ConnectionSpec object like that:

```
new ConnectionSpec.Builder(ConnectionSpec.MODERN_TLS).
tlsVersions(TlsVersion.TLS_1_2).
cipherSuites(
        CipherSuite.TLS_AES_128_GCM_SHA256,
        CipherSuite.TLS_CHACHA20_POLY1305_SHA256,
        CipherSuite.TLS_AES_256_GCM_SHA384,
        CipherSuite.TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,
        CipherSuite.TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,
        CipherSuite.TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256,
        CipherSuite.TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256,
        CipherSuite.TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,
        CipherSuite.TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,
        CipherSuite.TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA,
        CipherSuite.TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA,
        CipherSuite.TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA,
        CipherSuite.TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA,
        CipherSuite.TLS_RSA_WITH_AES_128_GCM_SHA256,
        CipherSuite.TLS_RSA_WITH_AES_256_GCM_SHA384,
        CipherSuite.TLS_RSA_WITH_AES_128_CBC_SHA,
        CipherSuite.TLS_RSA_WITH_AES_256_CBC_SHA,
        CipherSuite.TLS_RSA_WITH_3DES_EDE_CBC_SHA
).
build();
```

While debugging via Charles software, i see the following:

> Client Supported:
> TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA
> TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA
> TLS_RSA_WITH_AES_256_CBC_SHA
> TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA
> TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA
> TLS_RSA_WITH_AES_128_CBC_SHA
> TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
> TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
> TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
> TLS_RSA_WITH_AES_256_GCM_SHA384
> TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
> TLS_RSA_WITH_AES_128_GCM_SHA256
> TLS_RSA_WITH_3DES_EDE_CBC_SHA

Question:
why some ciphers are missed?
For example, TLS_AES_128_GCM_SHA256, that is always sent by real firefox/chrome browsers.

**Comment by swankjesse** [comment]
Typically this is due to lack of support in the host TLS stack.
https://tinyurl.com/okhttp-cipher-suites

**Comment by ogolovanov** [comment]
Hi!

I have code from my first message, where cipher TLS_AES_128_GCM_SHA256 used.
I have okhttp 3.14.2, that supports that cipher.
i have java 15.0.1, that also supports that cipher.
i have openssl, that also supports that cipher.

And still i do not see that cipher in list of supported ciphers in client request: https://prnt.sc/wnrbdd.
But i see it from firefox/chrome requests.

Why? :<

```
System.out.println(System.getProperty("java.version"));
>> 15.0.1
```

```
openssl ciphers -v | grep '^AES128-GCM-SHA256'
>> AES128-GCM-SHA256       TLSv1.2 Kx=RSA      Au=RSA  Enc=AESGCM(128) Mac=AEAD
```

**Comment by swankjesse** [comment]
That's a TLSv1.3-only cipher suite and you're seeing a TLSv1.2 handshake.

https://square.github.io/okhttp/tls_configuration_history/#tlsv13_only
