### ISSUE TITLE
3.x Version has a bug that causes the request body to be sent incorrectly.

### ISSUE THREAD

**Issue by goodcode-best** [square/okhttp#6496]
As shown below, when send the request body, the request header is send as the body content.
![image](https://user-images.githubusercontent.com/58644206/103353742-92279a80-4ae4-11eb-9b99-1c79a2131c3b.png)

I compared the 3.x and 4.x codes, find two versions on the processing of RetryAndFollowUpInterceptor.intercept() is different.

The 4.x version calls the detachWithViolence methods in the finally to release the resource, but the 3.x version does not release the resource if an exception occurs, this results in unsuccessfully send data in the Buffer being consumed by the next request.

Please helop to fix this BUG in version 3.x, thank you!

**Comment by yschimke** [comment]
Please reopen with a bug reproduction.  We can't take any action on this as is. And screenshot really isn't helpful here.

If you can't easily reproduce, then consider posting a working sample to stackoverflow and seeing if anyone else can advise.  We can't help debug your client program.

**Comment by yschimke** [comment]
Are you using 3.12.12?

**Comment by goodcode-best** [comment]
Version 3.14.4

**Comment by goodcode-best** [comment]
List 135 of  class okhttp3.internal.http.RetryAndFollowUpInterceptor  does not execute when an excption is thrown
