### ISSUE TITLE
3.x Version has a bug that causes the request body to be sent incorrectly.

### ISSUE THREAD

**Issue by goodcode-best** [square/okhttp#6497]
As shown below, when send the request body, the request header is send as the body content.
image

I compared the 3.x and 4.x codes, find two versions on the processing of RetryAndFollowUpInterceptor.intercept() is different.

The 4.x version calls the detachWithViolence methods in the finally to release the resource, but the 3.x version does not release the resource if an exception occurs, this results in unsuccessfully send data in the Buffer being consumed by the next request.

Please help to fix this BUG in version 3.x, thank you!

List 135 of class okhttp3.internal.http.RetryAndFollowUpInterceptor does not execute when an excption is thrown.
` public Response intercept(Chain chain) throws IOException {
    Request request = chain.request();
    RealInterceptorChain realChain = (RealInterceptorChain) chain;
    Transmitter transmitter = realChain.transmitter();
    int followUpCount = 0;
    Response priorResponse = null;
    while (true) {
      transmitter.prepareToConnect(request);

      if (transmitter.isCanceled()) {
        throw new IOException("Canceled");
      }

      Response response;
      boolean success = false;
      try {
        response = realChain.proceed(request, transmitter, null);
        success = true;
      } catch (RouteException e) {
        // The attempt to connect via a route failed. The request will not have been sent.
        if (!recover(e.getLastConnectException(), transmitter, false, request)) {
          throw e.getFirstConnectException();
        }
        continue;
      } catch (IOException e) {
        // An attempt to communicate with a server failed. The request may have been sent.
        boolean requestSendStarted = !(e instanceof ConnectionShutdownException);
        if (!recover(e, transmitter, requestSendStarted, request)) throw e;
        continue;
      } finally {
        // The network call threw an exception. Release any resources.
        if (!success) {
          transmitter.exchangeDoneDueToException();
        }
      }

      // Attach the prior response if it exists. Such responses never have a body.
      if (priorResponse != null) {
        response = response.newBuilder()
            .priorResponse(priorResponse.newBuilder()
                    .body(null)
                    .build())
            .build();
      }

      Exchange exchange = Internal.instance.exchange(response);
      Route route = exchange != null ? exchange.connection().route() : null;
      Request followUp = followUpRequest(response, route);

      if (followUp == null) {
        if (exchange != null && exchange.isDuplex()) {
          transmitter.timeoutEarlyExit();
        }
        return response;
      }

      RequestBody followUpBody = followUp.body();
      if (followUpBody != null && followUpBody.isOneShot()) {
        return response;
      }

      closeQuietly(response.body());
      if (transmitter.hasExchange()) {
        exchange.detachWithViolence();
      }

      if (++followUpCount > MAX_FOLLOW_UPS) {
        throw new ProtocolException("Too many follow-up requests: " + followUpCount);
      }

      request = followUp;
      priorResponse = response;
    }
  }`

**Comment by goodcode-best** [comment]
Version 3.14.4

**Comment by swankjesse** [comment]
Fixed in 4.9.0.

**Comment by goodcode-best** [comment]
Because the difference between the two version is too big, the team will not upgrade for the time being. 
Could you fix the BUG on the 3.x version?

**Comment by goodcode-best** [comment]
The team does not currently have the ability to nurse Kotlin.

**Comment by yschimke** [comment]
No, if you need a fix made to 3.14.x you should maintain your own fork with the fix.

See our supported versions here https://square.github.io/okhttp/security/

I don't understand the meaning of "nurse" Kotlin.  This is an implementation decision, much like you might depend on a library that happens to be implemented in Scala like Spark. We didn't change the APIs to use kotlin types, it should be binary forward compatible.

**Comment by goodcode-best** [comment]
The team does not currently have the capability to maintain Kotlin.

**Comment by goodcode-best** [comment]
3.14.x version is compatible with 4.x version platform

**Comment by swankjesse** [comment]
I recommend upgrading to OkHttp 4.9.0 or downgrading to 3.12. the 3.14 line is no longer receiving bug fixes.
