### ISSUE TITLE
FormBody.Builder encode my email and password

### ISSUE THREAD

**Issue by power721** [square/okhttp#6499]
```kotlin
formBuilder.addEncoded("username", "username@example.com")
formBuilder.addEncoded("password", "password@example.com")
```

The email encoded to 'username%40example.com" which made login failed.

```xml
      <dependency>
            <groupId>com.squareup.okhttp3</groupId>
            <artifactId>okhttp</artifactId>
            <version>4.9.0</version>
        </dependency>
```

Reference:
https://github.com/square/retrofit/issues/1407

**Comment by MyFisherTiger** [comment]
how to fix it. so annoyed

**Comment by yschimke** [comment]
The difference between add and addEncoded is to specify whether % is an encoded already.  But OkHttp doesn't provide APIs to let you send invalid requests deliberately, so it will correctly encode @.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/POST
