### ISSUE TITLE
mockwebserver3-junit5: field injection

### ISSUE THREAD

**Issue by michielboekhoff** [square/okhttp#6511]
Hello there,

First off: thanks so much for this project. I came across the mockwebserver3-junit5 module that, as of yet, is unpublished. I started playing around with it a bit in one of my Spring Boot applications. What I wanted to do looks something like this:

```java
@ExtendWith(MockWebServerExtension.class)
@SpringBootTest
class WebServiceClientTest {

  @InjectMockWebServer static MockWebServer mockWebServer;

  @Autowired WebServiceClientProperties properties;

  @Autowired WebServiceClient usageRegistrationClient;

  @Test
  void test() {
    // some test
  }

  @DynamicPropertySource
  static void propertySource(DynamicPropertyRegistry registry) {
    registry.add("webservice.base-url", () -> mockWebServer.url("/").toString());
  }
}
```
where the `WebServiceClientProperties` is a class annotated with `@ConfigurationProperties` (and hence binds properties). The method annotated with `@DynamicPropertySource` has to be static. 

I had a play around with this, and I got something working by modifying the `MockWebServerExtension`, but I wanted to know if this is something you'd be interested in accepting into the project.

**Comment by swankjesse** [comment]
Could you explain it to me as somebody who doesn't use Spring Boot?

**Comment by michielboekhoff** [comment]
Of course, sorry about that @swankjesse.

I'm trying to inject the base URL as a property (the `webservice.base-url` property, which is loaded by Spring Boot). Spring Boot loads these properties before it loads the beans (`WebServiceClient` in this example), but it can load dynamic properties (such as the mock web server's URL) if you have a method annotated with `@DynamicPropertySource`, as I have above, but this method has to be static. That rules out both test parameter injection and constructor injection, as neither of these would be available in a static context.

**Comment by swankjesse** [comment]
Gotcha. I recommend against using a static MockWebServer instance. That is dangerous for concurrency and potentially leaks resources. Using a non-static field for it is a better fit.

**Comment by michielboekhoff** [comment]
Sadly that wouldn't cover my use case. I agree that it poses a problem with concurrency, but I don't understand why it might leak resources, as you could clean up after the test execution. For this particular use case, I can't use a non-static field for it, as Spring Boot requires it to be available from a static context. 

Ideally, I'm looking for behaviour analogous to what the Testcontainers project does - static, annotated fields (representing Docker containers) have their lifecycle managed by the extension (e.g. starting & stopping the MockWebServer), which can then be used inside of tests, and can be used in the method annotated with `@DynamicPropertySource`.

**Comment by yschimke** [comment]
Part of the point of the recent refactor has been to allow N*M integrations in a clean library. This sounds ideal as a spring-boot-mockwebserver library. Hopefully it's now simple to do this and self publish.

**Comment by michielboekhoff** [comment]
@yschimke - I like this suggestion. I think it's close enough to what I want, and I understand you might not want to introduce static field injection if you're designing this for concurrent tests. With that, I'll close this ticket and publish that library when I can. Thanks, everyone for your input and help!
