### ISSUE TITLE
Debug caching behavior

### ISSUE THREAD

**Issue by AAverin** [square/okhttp#6512]
Talking to a 3rd party dependency API that sets some caching headers, it would be great to be able somehow debug OkHttp caching logic to understand why and how cache was actually used.

Looking at the headers, everything should work, but it doesn't and Etag-based caching doesn't seem to kick in for some reason. Is there already a way to enable some kind of logging to debug besides networkInterceptor that just prints headers?

**Comment by swankjesse** [comment]
The most common reason a response is not cached is not reading the entire response body. Is this you?

**Comment by AAverin** [comment]
If `body.string()` reads entire response body then it's not the case of my problem.
But not speaking about my specific problem, generally it would be good to be able to understand why cache was used or why wasn't it. Maybe it was some header like `Vary: session` that affected the decision, maybe something else.

**Comment by yschimke** [comment]
Do you get enough detail with EventListener?

https://square.github.io/okhttp/caching/
https://square.github.io/okhttp/events/

You can show the cache events, or output the types cache objects or relevant raw headers.

**Comment by yschimke** [comment]
No action to take here, we expose the headers and cache events in our APIs.
