### ISSUE TITLE
Feeling confuse about these Classes

### ISSUE THREAD

**Issue by EdisonLiao** [square/okhttp#6536]
I have decompiled an App, and find some classes which make me confuse, because these classes can not find in okhttp3 doc file, someone can tell me about it? thank you!

![1901612077625_ pic](https://user-images.githubusercontent.com/14108176/106377537-9cd19a00-63d8-11eb-8a4a-f690c56fab5a.jpg)

**Comment by yschimke** [comment]
Which app, where did you install it from? Tahis is a better question for stackoverflow. But they dont come from this project.

**Comment by EdisonLiao** [comment]
It's an Chinese app, this link: https://app.mi.com/details?id=com.ptu.photoeditor. What's more, I find this app's progress can not be killed..

**Comment by yschimke** [comment]
Shows up here in a malware analysis tool https://www.joesandbox.com/analysis/339890/0/html

**Comment by yschimke** [comment]
Some links to http://api.gspaceteam.com/cms/private_policy_en.html http://api.gspaceteam.com/cms/terms_service_en.html

Which refer to cloning apps
