### ISSUE TITLE
Make it possible to configure a Dispatcher so that there is never any queuing

### ISSUE THREAD

**Issue by BrassyPanache** [square/okhttp#6537]
I'd like to be able to specify a `Dispatcher` queue size. At the moment queued calls are added to an unbounded `ArrayDeque`. This can result in a situation where new calls are appended indefinitely whilst the in-flight requests is not below the maximum request limit (global or per-host).

Ideally the oldest queued item should be dropped.

It should also be possible to specify a queue size of 0 such that all calls exceeding the in-flight capacity are immediately failed.

It would be enough to make the `Dispatcher` and interface which I could implement.  At the moment it is final.

**Comment by yschimke** [comment]
OkHttp is quite selective about which knobs are tunable.  We only have a few places using customisable interfaces so we have predictable behaviour in much of the core of OkHttp.  I don't see us making this change as it would require handling failure cases in a bunch of additional places, possibly while we are in the middle of some operation we expect to complete successfully.  We assume the underlying platform is unpredictable enough and aim to make most of the code paths with OkHttp well defined.

Let's wait for other input, but I don't want to encourage you by saying put up a PR if we wouldn't ever land this.

**Comment by BrassyPanache** [comment]
Thanks for the quick reply.  Understand your view.  Simplicity is definitely a boon.

I would just add that from my point of view this is the most simple place to put a control of this nature. It is really difficult to implement something like this outside of the dispatcher as the dispatcher is the one place where all of the relevant context comes together (maximum requests, maximum requests per host, queued requests, etc).

Just to address your point regarding the handling of failure cases - I don't see too many pitfalls from my brief look at the code as the point at which you'd drop the `AsyncCall` would be prior to network interaction (which seems to be where a lot of the complexity comes in).

In any case - thanks for your quick and direct reply. I very much appreciate the OkHttp library. It abstracts a lot of underlying complexity behind an extremely simple interface! It is one of my most loved libraries.

**Comment by swankjesse** [comment]
Dispatcher is implemented as a mechanism to make effective use of the network. It doesn't attempt to do application-side policy.

I recommend writing a RequestQueue class to sit in front of Dispatcher that implements whichever policy you like. Such a class should promote ready calls to the Dispatcher when ready. You can wrap Callbacks to receive a signal when calls complete.

This will let you have full control over policy: LIFO, FIFO, canceling calls queued too long, whatever.

**Comment by yschimke** [comment]
@swankjesse in front of Dispatcher or a Call.Factory?

**Comment by swankjesse** [comment]
In front of Call.Factory.
