### ISSUE TITLE
Builder should be a data class

### ISSUE THREAD

**Issue by sschuberth** [square/okhttp#6538]
The are cases when it would be beneficial to know if two Builders would create the same client (configuration-wise), like caching of client instances with Builder instances as the keys. Such a comparison of Builders would be much easier if Builder was a Kotlin `data class`, and I'm wondering whether there's a reason to not make Builder a `data class`.

**Comment by yschimke** [comment]
In the past we've actively removed these from any public APIs because of API breakage like constructors.  I think we can't do this safely.

https://github.com/square/okhttp/pull/5133

**Comment by sschuberth** [comment]
Hmm, maybe that could be circumvented by wrapping the data class in a sealed class, and then for API changes introduce a new data class member in the sealed class?

**Comment by yschimke** [comment]
I'm not sure it's even that simple.  There are special behaviours with some fields of client build that determine whether they reset the routeDatabase, or whether it rebuilds the TLS stack.  And internally whether we can reuse connections between two similar-ish instances of an OkHttp client. Using equals for this isn't really correct.
