### ISSUE TITLE
Cache constructor with FileSystem parameter should be public

### ISSUE THREAD

**Issue by lsrom** [square/okhttp#6540]
Cache class has internal constructor which accepts FileSystem, which is as far as I can tell only way to encrypt cache files on disk. FileSystem interface even says it is designed for this usecase in it's Javadoc. But the constructor itself is marked as internal so I can't call it from Kotlin code. Can this please be fixed? Thanks.

Version 4.9.0.

**Comment by yschimke** [comment]
Stay tuned... Possibly a feature in 5.0.

**Comment by yschimke** [comment]
https://github.com/square/okhttp/pull/6550
