### ISSUE TITLE
The type java.time.Duration cannot be resolved when using Java 7

### ISSUE THREAD

**Issue by yschimke** [square/okhttp#6547]
Haven't investigated but looks like a bug in v3.12.13

https://stackoverflow.com/questions/66067782/the-type-java-time-duration-cannot-be-resolved-when-using-java-7

**Comment by yschimke** [comment]
> It's an Eclipse problem, not of the library, because when I compile my project the compiler does not throw any error, even if the library implicitly references java.time package.

**Comment by realizm** [comment]
It's not Eclipse problem.
I compile my project the compiler does not throw any error, too.
but in runtime, throw java.lang.Error: Unresolved compilation problem:

I used java 1.7.0_21, okhttp3 3.12.12, okio 1.15.0

**Comment by adr31** [comment]
https://github.com/square/okhttp/issues/6547#issue-802378675
