### ISSUE TITLE
.connectTimeout() doesn't work

### ISSUE THREAD

**Issue by hannesa2** [square/okhttp#6548]
I use `implementation "com.squareup.okhttp3:okhttp:4.9.0"` and this doesn't work 

`.connectTimeout(Duration.ofSeconds(4))`

It's finish too fast !

For demonstration I made a repo with CI https://github.com/hannesa2/okHttpTest/pull/1/checks?check_run_id=1842237161

I run it on Emulator and try from Emulator to connect to a non-hosted server. My expectation is a timeout of 4 seconds

# A: Local

Simply run `./gradlew test`

![image](https://user-images.githubusercontent.com/3314607/107096167-61850000-680a-11eb-8057-e194b6991506.png)

 # B: CI
https://github.com/hannesa2/okHttpTest/pull/2/checks?check_run_id=1842293253

![image](https://user-images.githubusercontent.com/3314607/107096311-c2143d00-680a-11eb-8947-803e33a6f4a6.png)

## Who can explain what's going on here ?

Why does a connect to Emulator hosted non-existing-server (for test purpose) the `.connectTimeout(Duration.ofSeconds(4))` doesn't work ?

**Comment by swankjesse** [comment]
The connectTimeout only measures a single hop if there’s proxies involved. Consider using the call timeout alongside.

**Comment by hannesa2** [comment]
@swankjesse 
I use call timeout as well     

```
private var client = OkHttpClient.Builder()
        .connectTimeout(Duration.ofSeconds(4))
        .writeTimeout(Duration.ofSeconds(7))
        .readTimeout(Duration.ofSeconds(7))
        .callTimeout(Duration.ofSeconds(10))
        .retryOnConnectionFailure(false)
        .build()
```

What I do is this

        val request: Request = Request.Builder()
            .url(server) // non routable address
            .build()
        catchThrowable { client.newCall(request).execute() }

**but this 10 seconds aren't respect as well.** (from my point of view not working) Or how to explain that ?

**Comment by hannesa2** [comment]
To ask different: what to do, to get an answer after 4 or 10 seconds ?

**Comment by yschimke** [comment]
Please ask on stackoverflow and we can answer there.  This is for bug reports, we'd prefer to build stackoverflow as a knowledgeable and for usage questions.

**Comment by hannesa2** [comment]
Ok, here is the SO question https://stackoverflow.com/q/66076050/1079990

Btw, with my current understanding this is a bug

**Comment by yschimke** [comment]
No, a timeout is a maximum time.  If the network returns an error sooner, then it's expected.

**Comment by hannesa2** [comment]
@yschimke 
Thank you. This makes sense
