### ISSUE TITLE
 java.lang.IllegalStateException:invalid dictionary: prefix not unique

### ISSUE THREAD

**Issue by firelotus** [square/okhttp#6552]
I'm facing this issue on android 11,        implementation 'com.squareup.okhttp3:okhttp:3.14.9'

1 java.lang.ExceptionInInitializerError:
--
2 okhttp3.internal.http2.Huffman.get(Huffman.java:82)
3 ......
4 Caused by:
5 java.lang.IllegalStateException:invalid dictionary: prefix not unique
6 okhttp3.internal.http2.Huffman.addCode(Huffman.java:180)
7 okhttp3.internal.http2.Huffman.buildTree(Huffman.java:168)
8 okhttp3.internal.http2.Huffman.<init>(Huffman.java:88)
9 okhttp3.internal.http2.Huffman.<clinit>(Huffman.java:79)
10 okhttp3.internal.http2.Huffman.get(Huffman.java:82)
11 okhttp3.internal.http2.Hpack$Writer.writeByteString(Hpack.java:552)
12 okhttp3.internal.http2.Hpack$Writer.writeHeaders(Hpack.java:520)
13 okhttp3.internal.http2.Http2Writer.headers(Http2Writer.java:282)
14 okhttp3.internal.http2.Http2Connection.newStream(Http2Connection.java:266)
15 okhttp3.internal.http2.Http2Connection.newStream(Http2Connection.java:238)
16 okhttp3.internal.http2.Http2ExchangeCodec.writeRequestHeaders(Http2ExchangeCodec.java:116)
17 okhttp3.internal.connection.Exchange.writeRequestHeaders(Exchange.java:72)
18 okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:43)
19 okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
20 okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:43)
21 okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
22 okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
23 okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
24 okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
25 okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
26 okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
27 okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
28 okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88)
29 okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
30 okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
31 com.sf.gather.http.RetryInterceptor.intercept(RetryInterceptor.java:30)
32 okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
33 okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
34 okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229)
35 okhttp3.RealCall.execute(RealCall.java:81)
36 com.sf.gather.http.HttpReportWorker.doReportHttp(HttpReportWorker.java:172)
37 com.sf.gather.http.HttpReportWorker.doReportInner(HttpReportWorker.java:161)
38 com.sf.gather.http.ReportWorker.handleMessage(ReportWorker.java:139)
39 com.sf.gather.utils.ThreadHandler.handleMessage(ThreadHandler.java:43)
40 android.os.Handler.dispatchMessage(Handler.java:102)
41 android.os.Looper.loop(Looper.java:239)
42 android.os.HandlerThread.run(HandlerThread.java:67)

please help me to figure it out. Thanks

**Comment by yschimke** [comment]
Do you have a request we can reproduce this with? Or any other context? n.b. we don't actively maintain 3.14.9, can you retest with 4.9.1 or with 3.12.13.

**Comment by firelotus** [comment]
> Do you have a request we can reproduce this with? Or any other context? Note, we don't actively maintain 3.14.9, can you retest with 4.9.1 or with 3.12.13.

This is an occasional problem, which has not been repeated. I will try to use version 3.12.13,
The test results will be fed back later, thank you

**Comment by yschimke** [comment]
Previous report was upstreamed to vendor
https://github.com/square/okhttp/issues/6517

https://stackoverflow.com/questions/65784940/java-lang-illegalstateexception-invalid-dictionary-prefix-not-unique

**Comment by firelotus** [comment]
I tried version 3.12.13 and the problem still exists. All the problems happened on Android 11 machines, occasionally.
