### ISSUE TITLE
response.body.charStream not ready

### ISSUE THREAD

**Issue by heuermh** [square/okhttp#6560]
Hello,

Please accept my apologies if this is simply user error!

I need to write the response body as a character stream to a `PrintWriter`. With this
```java
try (BufferedReader streamReader = new BufferedReader(response.body().charStream())) {
  while (streamReader.ready()) {
    writer.println(streamReader.readLine());
  }
}
```
I receive HTTP 1.1 OK response with body content but `streamReader.ready()` never returns true.  A workaround is to check `streamReader.readLine() != null`.

https://github.com/heuermh/ensembl-mart-runner/blob/main/src/main/java/com/github/heuermh/ensemblmartrunner/EnsemblMartRunner.java#L106

To reproduce
```bash
$ git clone https://github.com/heuermh/ensembl-mart-runner.git
$ mvn package

# short response
$ ./target/appassembler/bin/ensembl-mart-runner \
  -i src/test/resources/hla-a.mart-query.xml \
  -o hla-a.txt

# long response
$ ./target/appassembler/bin/ensembl-mart-runner \
  -i src/test/resources/hgnc-mapping.mart-query.xml \
  -o hgnc-mapping.txt
```

**Comment by swankjesse** [comment]
I believe this is consistent with how `BufferedReader` is designed. If you want to make it easy on yourself, consider reading lines with Okio’s BufferedSource instead.

```
try (BufferedSource source = response.body().source()) {
  for (String line; (line = source.readUtf8Line()) != null; ) {
    writer.println(line);
  }
}
```

**Comment by heuermh** [comment]
Thank you for the quick reply, @swankjesse!  `okio.BufferedSource` works great.
