### ISSUE TITLE
The type java.time.Duration cannot be resolved when using Java 7

### ISSUE THREAD

**Issue by realizm** [square/okhttp#6568]
It's not Eclipse problem.
I compile my project the compiler does not throw any error, too.
but in runtime, throw java.lang.Error: Unresolved compilation problem:

I used java 1.7.0_21, okhttp3 3.12.12, okio 1.15.0

_Originally posted by @realizm in https://github.com/square/okhttp/issues/6547#issuecomment-783928964_

**Comment by adr31** [comment]
> It's not Eclipse problem.
> I compile my project the compiler does not throw any error, too.
> but in runtime, throw java.lang.Error: Unresolved compilation problem:
> 
> I used java 1.7.0_21, okhttp3 3.12.12, okio 1.15.0
> 
> _Originally posted by @realizm in [#6547 (comment)](https://github.com/square/okhttp/issues/6547#issuecomment-783928964)_

**Comment by realizm** [comment]
> It's not Eclipse problem.
> I compile my project the compiler does not throw any error, too.
> but in runtime, throw java.lang.Error: Unresolved compilation problem:
> 
> I used java 1.7.0_21, okhttp3 3.12.12, okio 1.15.0
> 
> _Originally posted by @realizm in [#6547 (comment)](https://github.com/square/okhttp/issues/6547#issuecomment-783928964)_

change to okhttp3 3.11.0, okio 1.14.0
It's work.

**Comment by yschimke** [comment]
Sounds like it's working after a version change.
