### ISSUE TITLE
Should we use explicit API mode

### ISSUE THREAD

**Issue by yschimke** [square/okhttp#6575]
https://umang91.medium.com/explicit-api-mode-kotlin-a527843d94f3

> Kotlin compiler offers explicit API mode for library authors. In this mode, the compiler performs additional checks that help make the library’s API clearer and more consistent.

**Comment by JakeWharton** [comment]
Do you mean should-have-been-the-default-in-the-first-place mode?

**Comment by yschimke** [comment]
Closing in favour of existing API checks.
