### ISSUE TITLE
Websocket connection active even after calling close and activity being destroyed

### ISSUE THREAD

**Issue by kevindesai777** [square/okhttp#6584]
When pressing back on my activity, onDestroy is triggered which tries to close the websocket

```
    override fun disconnect() {
        Logger.d(TAG, "Socket attempting to disconnect")
        if (::webSocket.isInitialized) {
            webSocket.close(1000, "Disconnecting websocket")
        }
    }
```

This triggers a callback in the websocket listener, where I close the websocket connection again. 

```
            override fun onClosing(webSocket: WebSocket, code: Int, reason: String?) {
                webSocket.close(1000, null)
                Logger.i(TAG, "Web socket connection with GB closing due to: $reason")
                super.onClosing(webSocket, code, reason)
            }

            override fun onClosed(webSocket: WebSocket, code: Int, reason: String?) {
                Logger.i(TAG, "Web socket connection with GB closed due to: $reason")
                super.onClosed(webSocket, code, reason)
            }
```

The activity is also removed from the recents page. 
Even after that, I still see a heartbeat from the websocket.

```
021-03-11 10:45:50.804 16233-16233/GreenboxWebSocket: Socket attempting to disconnect
2021-03-11 10:45:50.859 16233-17261/GreenboxWebSocket: Web socket connection with GB closing due to: Disconnecting websocket
2021-03-11 10:45:50.859 16233-17261/GreenboxWebSocket: Web socket connection with GB closed due to: Disconnecting websocket
2021-03-11 10:45:51.542 16233-16936/GreenboxWebSocket: Incoming message from GB websocket: h
2021-03-11 10:46:16.537 16233-16936/GreenboxWebSocket: Incoming message from GB websocket: h
2021-03-11 10:46:41.516 16233-16936/GreenboxWebSocket: Incoming message from GB websocket: h
2021-03-11 10:47:06.501 16233-16936/GreenboxWebSocket: Incoming message from GB websocket: h
```

Also tried         
`   okHttpClient.connectionPool().evictAll()` after closing the connection. But still the same result

Using OkHttp 3.12

**Comment by yschimke** [comment]
Would you be able to make a failing test case for this? Otherwise consider asking on a forum like stackoverflow to start with.  This isn't immediately reproducible from the bug report.

**Comment by Lull3n** [comment]
Im having the same issue, though it only happens if the activity being destroyed due to the app being killed.

**Comment by yuyuan20** [comment]
> Im having the same issue, though it only happens if the activity being destroyed due to the app being killed. Edit2: Apparently the issue was when closing the socket directly on the main thread.

How did you solve the issue?

**Comment by Lull3n** [comment]
> > Im having the same issue, though it only happens if the activity being destroyed due to the app being killed. Edit2: Apparently the issue was when closing the socket directly on the main thread.
> 
> How did you solve the issue?

Can't remember, but looks like I might have spun off closing the socket on another thread.
