### ISSUE TITLE
UnknownHostException - Occurs only for Android 11

### ISSUE THREAD

**Issue by leehanmo** [square/okhttp#6591]
**Problem: Once an UnknownHostException is returned, the user continues to receive the same error unless the app is reinstalled or the device is rebooted.**

Of the users whose OS is Android 11, only a few users are having problems.
The biggest problem is that when an error occurs, the same error is returned continuously for each request.

According to users It is said that re-installing the app or rebooting the device will work again.

It seems that 99% are users of Samsung devices. Sometimes there are also Google Pixel phones.

Both Http and Https give the same error.
Both Wifi, 5G and LTE give the same error.
The request method is using POST and I don't know if it happens to GET as well, I don't use GET.
Also, either Thread is Background or Foreground, or both.

In response to this
Okhttp version was raised from 3.10.0 to 4.9.0
I upgraded the Retrofit2 version from 2.4.0 to 2.9.0 
but the same issue is occurring.

**Comment by yschimke** [comment]
Thanks for moving to stackoverflow https://stackoverflow.com/questions/66703751/unknownhostexception-after-android-11-update

**Comment by zackees** [comment]
Can we not close this bug? I'm hitting this too. It's causing havoc on our app deployments.

**Comment by zackees** [comment]
Seems like it might be fixed in `4.11.0` actually.

**Comment by shriharsha-bhagwat** [comment]
@zackees Any updates on this one ? Started facing it in Samsung Android 13 mainly.

**Comment by zackees** [comment]
Yes, the issue was that we were attempting to access the network blindly, that's when the bug manifests. The work around is to only attempt the network connection if the async network manager indicates that you have an actual connection to the internet. Otherwise you are in danger of poisoning your DNS cache which is manifesting this issue.

```kotlin
    val mNetworkCallback = object : ConnectivityManager.NetworkCallback() {
        override fun onAvailable(network: android.net.Network) {
            super.onAvailable(network)
            mIsConnected.set(true)
        }

        override fun onLost(network: android.net.Network) {
            super.onLost(network)
            mIsConnected.set(false)
        }
    }
```

Block all network connections until the async network manager responds with a network state. Don't attempt to acces
