### ISSUE TITLE
Why the ThreadPoolExecutor corePoolSize = 0🙉

### ISSUE THREAD

**Issue by pengfeigao** [square/okhttp#6592]
What is the purpose of OKHttp setting the corePoolSize in ThreadPoolExecutor to 0

**Comment by yschimke** [comment]
If there is no traffic after 60 seconds we don't keep a thread hanging around doing nothing in the thread pool.

Tuning docs https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/ThreadPoolExecutor.html

```
    private val executor = ThreadPoolExecutor(
        0, // corePoolSize.
        Int.MAX_VALUE, // maximumPoolSize.
        60L, TimeUnit.SECONDS, // keepAliveTime.
        SynchronousQueue(),
        threadFactory
    )
```

**Comment by TangHuaiZhe** [comment]
`corePoolSize` is the number of threads to keep in the pool, eve if they are idle.

Perhaps the comment of `newCachedThreadPool` can give you an answer.
 
![image](https://user-images.githubusercontent.com/7965577/111746788-7785e600-88c9-11eb-90b4-1fcc68d5f342.png)
