### ISSUE TITLE
WebSocketWriter flagged by Veracode CWE-331

### ISSUE THREAD

**Issue by dsuresh-ap** [square/okhttp#6594]
Our veracode scan flagged `WebSocketWriter.random` as a vulnerability due to its use of `Random`.

https://cwe.mitre.org/data/definitions/331.html

According to [Websocket Protocol](https://tools.ietf.org/html/rfc6455#section-10.3):

> For example, each masking could be drawn from a cryptographically strong random number generator.  If the same key is used or a decipherable pattern exists for how the next key is chosen, the attacker can send a message that, when masked, could appear to be an HTTP request (by taking the message the attacker wishes to see on the wire and masking it with the next masking key to be used, the masking key will effectively unmask the data when the client applies it).

According to this specification the library should be using `SecureRandom` to prevent brute force attacks.

Version: 4.0.9

**Comment by JakeWharton** [comment]
This came up before in https://github.com/square/okhttp/issues/4974. The randomness is used to defeat proxies (specifically caching proxies) and isn't for cryptographic purposes.

We could probably switch if it will help silence this kind of automated tooling.

**Comment by tcolligan** [comment]
@JakeWharton Even though https://tools.ietf.org/html/rfc6455#section-5.3 says the following?

`The masking key is a 32-bit value chosen at random by the client.
   When preparing a masked frame, the client MUST pick a fresh masking
   key from the set of allowed 32-bit values.  The masking key needs to
   be unpredictable; thus, the masking key MUST be derived from a strong
   source of entropy, and the masking key for a given frame MUST NOT
   make it simple for a server/proxy to predict the masking key for a
   subsequent frame.  The unpredictability of the masking key is
   essential to prevent authors of malicious applications from selecting
   the bytes that appear on the wire.  RFC 4086 [RFC4086] discusses what
   entails a suitable source of entropy for security-sensitive
   applications.`

**Comment by JakeWharton** [comment]
I guess if you're using HTTP and not HTTPS across an untrusted network. It's a pretty annoying spec inclusion given the fact that TLS obviates it and HTTP is only used on trusted networks (such as local unix domain sockets).

**Comment by swankjesse** [comment]
@tcolligan please reopen if you have an example where this would improve security in practice. Otherwise I think it's just an overly sensitive detector.
