### ISSUE TITLE
ArrayIndexOutOfBoundsException 

### ISSUE THREAD

**Issue by h-zhouwenjun** [square/okhttp#6600]
1okio.Buffer.indexOf(Buffer.kt:21)
--
okio.RealBufferedSource.indexOf(RealBufferedSource.kt:6)
okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.kt:2)
okhttp3.internal.http1.HeadersReader.readLine(HeadersReader.kt:1)
okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.kt:2)
okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.kt:1)
okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:25)
okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:12)
okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:4)
okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:12)
okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:27)
okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:12)
okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:22)
okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:12)
okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:7)
okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:12)
okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:16)
okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:6)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
java.lang.Thread.run(Thread.java:764)

**Comment by swankjesse** [comment]
Executable test case? This isn't actionable as-is.

**Comment by c0dingEverything** [comment]
Process Name: 'com.szlanyou.iov' Thread Name: 'OkHttp Dispatcher' Back traces starts. java.lang.ArrayIndexOutOfBoundsException: size=0 offset=6 byteCount=1 at okio.-Util.checkOffsetAndCount(-Util.kt:26) at okio.Buffer.getByte(Buffer.kt:1084) at okio.internal.BufferKt.readUtf8Line(Buffer.kt:82) at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.kt:321) at okhttp3.internal.http1.HeadersReader.readLine(HeadersReader.kt:29) at okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.kt:178) at okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.kt:106) at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:79) at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34) at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95) at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83) at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76) at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201) at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) at java.lang.Thread.run(Thread.java:919) Back traces ends.

**Comment by c0dingEverything** [comment]
version:4.9.1
there isn't a proper test case. I just place the phone there without using it and it crashed. It could be something wrong with websocket.
