### ISSUE TITLE
Support creating a RequestBody from a FileDescriptor

### ISSUE THREAD

**Issue by nic0lette** [square/okhttp#6609]
In Android 11, changes related to Scoped Storage have made it so it isn't always possible to create a `File` reference to content, such as content that's retrieved via the Storage Access Framework. It _is_ possible to get a `FileDescriptor` (or `FileInputStream`) to the data, however.

Since `FileDescriptor` is part of the standard Java API, including it would allow Android developers who need to work within the Scoped Storage changes without adding a dependency on the Android SDK.

**Comment by JakeWharton** [comment]
It's just for `FileDescriptor`, and came in on Slack since it's becoming a fairly ubiquitous type in Android APIs as they eliminate the ability to use `File`. Jesse said yes, and requested it be moved to an issue.
