### ISSUE TITLE
Crash: Fatal Exception: java.net.UnknownHostException

### ISSUE THREAD

**Issue by morichany** [square/okhttp#6610]
Hey, 
I'm using okhttp3:3.9.0 retrofit:2.9.0 in my project.
Recently I noticed the following crash in firebase crashlytics (I wasn't able to reproduce it).
It happens on a main flow in my app and didn't find any solution, please advise. 

Crash:
Fatal Exception: java.net.UnknownHostException
Unable to resolve host "xxx.example.com": No address associated with hostname

Caused by android.system.GaiException
android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)

stack trace:
okhttp3.Dns.lambda$static$0 (Dns.java:39)
okhttp3.-$$Lambda$Dns$9evC3uO-H_z08sS9O-4-hLhZ8es.lookup (-.java)
okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress (RouteSelector.java:171)
okhttp3.internal.connection.RouteSelector.nextProxy (RouteSelector.java:135)
okhttp3.internal.connection.RouteSelector.next (RouteSelector.java:84)
okhttp3.internal.connection.ExchangeFinder.findConnection (ExchangeFinder.java:187)
okhttp3.internal.connection.ExchangeFinder.findHealthyConnection (ExchangeFinder.java:108)
okhttp3.internal.connection.ExchangeFinder.find (ExchangeFinder.java:88)
okhttp3.internal.connection.Transmitter.newExchange (Transmitter.java:169)
okhttp3.internal.connection.ConnectInterceptor.intercept (ConnectInterceptor.java:41)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:142)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:117)
okhttp3.internal.cache.CacheInterceptor.intercept (CacheInterceptor.java:94)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:142)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:117)
okhttp3.internal.http.BridgeInterceptor.intercept (BridgeInterceptor.java:93)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:142)
okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept (RetryAndFollowUpInterceptor.java:88)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:142)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:117)
okhttp3.logging.HttpLoggingInterceptor.intercept (HttpLoggingInterceptor.java:143)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:142)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:117)
com.fiverr.insertcreditcard.RetrofitManager$builder$1.intercept (RetrofitManager.java:38)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:142)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:117)
okhttp3.RealCall.getResponseWithInterceptorChain (RealCall.java:229)
okhttp3.RealCall.execute (RealCall.java:81)
com.google.firebase.perf.network.FirebasePerfOkHttpClient.execute (FirebasePerfOkHttpClient.java:43)
retrofit2.OkHttpCall.execute (OkHttpCall.java:204)
retrofit2.DefaultCallAdapterFactory$ExecutorCallbackCall.execute (DefaultCallAdapterFactory.java:108)
com.fiverr.insertcreditcard.CreditCardViewModel$validateSavedCreditCard$1.invoke (CreditCardViewModel.java:66)
com.fiverr.insertcreditcard.CreditCardViewModel$validateSavedCreditCard$1.invoke (CreditCardViewModel.java:21)
kotlin.concurrent.ThreadsKt$thread$thread$1.run (ThreadsKt.java:30)

**Comment by JakeWharton** [comment]
This is a normal IOException subtype that occurs when the internet is down and needs to be handled your code.
