### ISSUE TITLE
OSGi metadata needs tweaking

### ISSUE THREAD

**Issue by kriegfrj** [square/okhttp#6618]
I've been trying to find an open-source mock HTTP(S) server for Java that will work in an OSGi environment. So far I have not found one. It seems to me that mockwebserver is the first project of its kind to make an attempt.

I realise that the current version is a rewrite and still in alpha. But I can see that there are some problems with the OSGi metadata as it stands:

1. The bundles don't export anything. In order to be useful in OSGi, they'll need to export the public API so that OSGi-based test cases can import the packages that they need.
2. Some classes are in "internal" packages that probably shouldn't be. An example is MockWebServerExtension in the mockwebserver3-junit5 bundle, which is in the package `mockwebserver3.junit5.internal`. In order to be useful to Jupiter users it needs to be part of the public API and shouldn't be internal.

**Comment by yschimke** [comment]
@kriegfrj Can you put up a PR that addresses those and we can work through it.  These are exactly the sorts of issues that we need to work through before 5.0. Thanks for the feedback, it's really timely.

The okhttp maintainers lack the motivating use cases and experience to get it exactly right, so you are welcome to help us here.

**Comment by kriegfrj** [comment]
Thank you for your response @yschimke .

I would love to be able to help. Unfortunately, unless I have a direct and immediate need for the functionality for our own internal projects, I am unlikely to be able to find the time for it. I am looking for the path of least resistance, and at the moment I'm pursing another path with slightly less resistance. But if I hit a blockage on the other path, then this will probably be the path of next-least resistance and I'll end up back here. :smile:

**Comment by yschimke** [comment]
Likely we won't fix without someone submitting a PR and testing it. Hard to try to support it without someone with skin in the game.
