### ISSUE TITLE
Want "mockWebServer.dispatcher.clear()"

### ISSUE THREAD

**Issue by lathspell** [square/okhttp#6620]
I have a JUnit file with several test functions that share a MockWebServer instance. The reason that they share it is that I need to declare it statically so that I can use Spring's `@DynamicPropertySource` to inject the MockWebServer's port number as Spring environment variable.
Anyway, Sometimes I enqueue a response and then test function A fails and does not take the response off the queue as expected. Then the next test function B is executed, I enqueue another response but the next call to the mock retrieves the first response in the queue - that was intended for the test function A.

What I propose is a `mockWebServer.dispatcher.clear()` method that empties the response queue. I could call this in a `@BeforeEach` annotated JUnit method.

**Comment by JakeWharton** [comment]
Seems reasonable for QueueDispatcher but not Dispatcher.

**Comment by lathspell** [comment]
In `MockWebServer.enqueue(response: MockResponse)` the "dispatcher" is cast to QueueDispatcher to calll its "enqueue()" method. I would propose the same for "clear()".

**Comment by ansgarkonermann** [comment]
I also ran into this. Clearing the mock server response queue would truly be a valuable feature enhancement for me.

**Comment by yschimke** [comment]
To be clear on the status of this, enhancements for MockWebServer isn't a big focus for the OkHttp maintainers, but as this seems like a reasonable request, it's probably something that would be accepted given a nice simple clean PR.  @lathspell Any interest in working on this?

**Comment by lathspell** [comment]
see https://github.com/square/okhttp/pull/6736

**Comment by mtorba** [comment]
Any news for this issue? A solution has been **merged** since July 2021, and yet it's still not part of any public release (as far as I can tell)

**Comment by yschimke** [comment]
Released in 5 alphas.

**Comment by garashis** [comment]
Can someone paste the how to use solution in 5 alphas

**Comment by datadidit** [comment]
Will this be in a non alpha release 4.11.0 is newer than your latest alpha but doesn't have this change ported to it.

**Comment by DavidTheProgrammer** [comment]
I'm literally in this same predicament. I'm considering creating the mockwebserver with a static port and counting on that for my tests, but that seems error prone.
