### ISSUE TITLE
Issue working on cache and interceptor

### ISSUE THREAD

**Issue by ArcherEmiya05** [square/okhttp#6621]
Good day, I am migrating to using Retrofit2 with RxJava and OkHttp which are really nice to use. However I am having trouble to work with caching as Retrofit does not automatically cache response. Basically I am having `HTTP 504 Unsatisfiable Request (only-if-cached)` this seems to happen when the app just perform a fetch for the very first time which basically means that there is no cache at all available, but I am expecting the interceptor to use the response from server instead of cache unless there is an error like network and of course the cache available. Any help is greatly appreciated. Thank you!

I have posted it [here](https://stackoverflow.com/q/67002032/10053046) in SO.

**Comment by yschimke** [comment]
Thanks, I'll take a look on stackoverflow.  We won't keep this open unless you/we can make a reproducible test case showing the failure.
