### ISSUE TITLE
Redirection of a POST request turns into a GET

### ISSUE THREAD

**Issue by Boobby69** [square/okhttp#6627]
Hi !

I'm trying to make a POST call to a server with a HTTP scheme. 
My server is redirecting me with a 301 response code, giving me the same URL in HTTPS.

But the newer request is now a GET request, failing because my backend doesn't handle this endpoint with a GET method.

Sorry, I can't attach a log, but :
- response:
  - priorResponse:
    - headers: Location: https://my.server.com/ws/
    - request : POST, lots of parameters
  - request : GET, same parameters

Tested with okhttp:4.8.1 on Android 11.

**Comment by JakeWharton** [comment]
Your server should return an HTTP 308 instead of a 301 if it wants the HTTP method to be guaranteed to be the same: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/308.

HTTP 301 is not recommended for anything except GET or HEAD requests: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/301

**Comment by Boobby69** [comment]
OK, it is recommended to redirect through an HTTP 308. Why ? Because some user-agents doesn't handle the redirection correctly.

As I can read here (https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/301): "Even if **the specification requires the method (and the body) not to be altered** when the redirection is performed, not all user-agents align with it - you can still find this type of **bugged software** out there.".

And the RFC 7231 (https://tools.ietf.org/html/rfc7231#section-6.4.2) is also clear : "For historical reasons, a user agent MAY change the request method from POST to GET for the subsequent request." MAY, not should and … historical !!! The library is not even 10 years old ! 
In an older RFC (https://tools.ietf.org/html/rfc2616#section-10.3.2), June 1999, 14 years before the first tag, it's already noted that "When automatically redirecting a POST request after receiving a 301 status code, some existing HTTP/1.0 user agents will **erroneously** change it into a GET request."

It seems clear to me that it's a bug ! Therefore, it should be fixed.

RetryAndFollowUpInterceptor.kt:309 : just add the `|| responseCode == HTTP_MOVED_PERM` in the conditions, and also in if the `if` below, a nice ` && responseCode != HTTP_MOVED_PERM`.
URLConnectionTest.java:2136 : change the test with a foreach with all response codes that should redirect, or write multiple tests, at your convenience.

And if it's not the right fix, then just find it.

**Comment by swankjesse** [comment]
@Boobby69 you can rewrite the code from 301 to 308 in an interceptor. We don't do it in OkHttp because it's a backwards-incompatible change. Though maybe we could consider it for OkHttp 5.

**Comment by yschimke** [comment]
Can we do it for 5.0 behind a more general correctness flag following the evolving web ecosystem? Defaulted to on? Give ourselves wiggle room to fix these as standards evolve?
