### ISSUE TITLE
Investigate whether ConnectionPool early release saves radio battery & servers

### ISSUE THREAD

**Issue by bvermeule** [square/okhttp#665]
I'm using OkHttp in combination with RetroFit on Android. I cannot afford opening multiple connections to my API because this uses an ungodly amount of memory on the server.

I've instantiated a ConnectionPool like this for an OkHttpClient that lives throughout the apps lifetime:

```
ConnectionPool pool = new ConnectionPool(1, 10000);
client.setConnectionPool(pool);
```

However, netstat on both the server and the client shows that for every request a new connection is created. Is there more to it or is the pooling working incorrectly?

**Comment by swankjesse** [comment]
We now always close the longest-idle connection.
