### ISSUE TITLE
Incorrectly assigned of connection.idleAtNs

### ISSUE THREAD

**Issue by huabenshuai** [square/okhttp#6653]
The connection is closed before the keepAliveDurationNs is reached.

connection.idleAtNs has been assigned in releaseConnectionNoEvents() method，Re-assignment cannot be performed here 
// If this was the last allocation, the connection is eligible for immediate eviction.
if (references.isEmpty()) {
  connection.idleAtNs = now - keepAliveDurationNs
  return 0
}
in pruneAndGetAllocationCount.

**Comment by yschimke** [comment]
I'd suggest continuing the discussion on the stackoverflow questions you've raised.  If you consider this a bug, please reopen with a reproduction, that would really help us to confirm we've fixed it also.

Closing in favour of the parallel stackoverflow discussion.
