### ISSUE TITLE
Using ResponseBody.create give deprecated error in java

### ISSUE THREAD

**Issue by mikolasz** [square/okhttp#6655]
Hi Colleagues,

We are using okhttp3 and one of our test we have this code:
![image](https://user-images.githubusercontent.com/46314078/116371803-1a584b00-a80c-11eb-8554-d0c9eb99338e.png)

As you can see the ResponseBody.create shows that it is deprecated.
Okay I see that there is a `toResponsyBody` method instead so I wanted to use it but the code compiler doesn't give that.
![image](https://user-images.githubusercontent.com/46314078/116373067-4fb16880-a80d-11eb-8c64-d23035485af3.png)

Is it possible to use it in Java 8? If yes, can you please guide me?

pom.xml:
```
<dependency>
    <groupId>com.squareup.okhttp3</groupId>
    <artifactId>okhttp</artifactId>
    <version>4.9.0</version>
</dependency>
```

Best Regards,
Laszlo

**Comment by swankjesse** [comment]
Try reversing the order of the arguments to ResponseBody.create()?

**Comment by mikolasz** [comment]
Ohh, I can't believe it! :D 
I was focusing the method name and not the parameters...
It solved my problem.
Thanks Jesse!
