### ISSUE TITLE
getStatusText becomes empty while actual status code is 404

### ISSUE THREAD

**Issue by toyopilgrim** [square/okhttp#6656]
I found discrepancy between actual status code and StatusText in an edge case.
StatusText can be empty likely when http response is 404. (It occurred when an external server had not whitelisted our http client app.)

Here's a sample http error handler interceptor in Spring. The Java doc doesn't describe it can be empty so I consider it a bug.

```
@Slf4j
@Component
public class FooResponseErrorHandler extends DefaultResponseErrorHandler {

    @Override
    public void handleError(@NotNull final ClientHttpResponse response) {
            log.error("HTTP Client Error: status: {}", response.getStatusText());
    }
}

```

Occured at "com.squareup.okhttp3:okhttp:3.14.9"

**Comment by swankjesse** [comment]
Is this a Spring bug? These aren't OkHttp APIs.

**Comment by toyopilgrim** [comment]
I appreciate the fast reply. 
You're right. My description wasn't sufficient.

Apparently, I thought it's related to OkHttp's RestClient behavior under the hood.

The above error handler interceptor receives response given from OkHttpClient.

* How rest template bean was created with OkHttp.  For the sake of simplicity, I cut off detail configurations.

```
        final var okHttpClient = new OkHttpClient.Builder().build() 

        final var templateBuilder =  new RestTemplateBuilder().requestFactory(() -> new OkHttp3ClientHttpRequestFactory(okHttpClient))
            .errorHandler(new FooResponseErrorHandler());

        final var restTemplate = templateBuilder..build();

        return new RestApiClientImpl(restTemplate);

```


* How it's used to get 404
```
public class RestApiClient  {

    @NotNull
    private final RestTemplate restTemplate;

    public void callApi(@NotNull final RequestEntity<?> requestEntity) {
        final var responseEntity = restTemplate.exchange(requestEntity.getUrl().toString(), getMethod(requestEntity),
            requestEntity, Void.class);
    }
}
```

At this point, when the status code is not success, it will be passed to the error handler interceptor in Spring. But received ClientHttpResponse.getStatusText wasn't expected. 

Thx.

**Comment by swankjesse** [comment]
Gotcha. Without knowing much more I think this is a in Spring bug.

**Comment by toyopilgrim** [comment]
Thx. Then I'm closing this now and will take a closer look at Spring regarding this issue.
