### ISSUE TITLE
Take nth RecordedRequest of MockWebServer

### ISSUE THREAD

**Issue by Tuanpm31** [square/okhttp#6662]
When I have multiple requests but `takeRequest` function only can take the first request of the queue, But some time, i  want to take nth of request. How i can do it?

**Comment by yschimke** [comment]
Use a loop to take all proceeding requests. It could be a useful addition to peek at the full list of current requests, if you want to put up a PR.  But it may get shot down, we are careful about adding new public API, especially if usage might be non obvious.  But I think this could be clean.

**Comment by Step2Web** [comment]
I would take this issue if that's ok with you guys.

Before starting, what should the behaviour be?

* Should the elements before the nth element be discarded? Essentially n `take` calls on the queue and return the last?
* Should the list up to the nth element be returned (basically mirror the `take(n)` method on the queue)?

**Comment by Tuanpm31** [comment]
I think we should return the list of requests

**Comment by yagyank** [comment]
Hi, 
Is  this issue fixed? If not can I take it?

**Comment by swankjesse** [comment]
Please don't submit code for this feature; it's not generally useful enough to include in the library.

No action to take on this.
