### ISSUE TITLE
Follow up to 21

### ISSUE THREAD

**Issue by claudiopizzillo** [square/okhttp#6666]
Hi, i'm trying to consume a rest service from Italian Tax Public Service: https:// ivaservizi.agenziaentrate.gov.it.
This service require a post login, but the redirects are 21 and no 20 as max value defined in okhttp. 
I'm succesfull log in using python script in my repo. Is this limit standard or bypassable?

**Comment by yschimke** [comment]
Please ask usage questions like this on stackoverflow.  It's most likely a redirect loop.

If you want to report an actual bug, the following options can help you make something we can work against.  https://stackoverflow.com/a/66398516/1542667
