### ISSUE TITLE
Compilation Error In all the Recipes Code : Wrong Order of the parameters

### ISSUE THREAD

**Issue by prash-kr-meena** [square/okhttp#6669]
https://github.com/square/okhttp/blob/4ebc5f644c92ad08e41908db2ccaff4819cd0cbe/samples/guide/src/main/java/okhttp3/recipes/PostString.java#L42

**Compilation Error**, Due to wrong Order of the parameters.
These kind of error exists in all of the examples mentioned in the recipes page [Not on the page, but in the git source file that is linked on the topic]

**Comment by swankjesse** [comment]
Are you using OkHttp 4.x?

**Comment by prash-kr-meena** [comment]
@swankjesse  The code example is for okHttp3, so i am using that only.

**Comment by swankjesse** [comment]
Try updating your Maven dependency to the latest 4.x. The package you import should still say okhttp3.
