### ISSUE TITLE
Retrieve original response http headers

### ISSUE THREAD

**Issue by bolds07** [square/okhttp#6670]
OkHttp always convert the http response headers to lowercase.
I know that headers should be case insensitive and i've seen many other issues here that were closed with the same content as mine

But as I see this api should not alter any response header unless strictly necessary...

I was trying to debug an error in my server using okhttp and the error became masked when okhttp set all response headers to lowercase...

Again, the error was in my server, but okhttp made impossible to detect/debug it because it unwantedly lowercased the response.

It should not be the library decision to do it, and if so there should be a parameter to change this settings

Is there any way to get the original response headers with okhttp 5/4.9 ??

**Comment by swankjesse** [comment]
In HTTP/2 the protocol requires lowercase headers. If this doesn't work for you, please disable HTTP/2. You'll enjoy HTTP/1 which retains the case of headers.

**Comment by bolds07** [comment]
http2 rfc says all headers should be lowercase and uppercase headers MUST be treated as malformed...
 it doesn't say:

"is up to the client library to forcefully lowercase the response headers, tricking the developper into thinking they already came like this"

You are probably tired of answering this very same question, but im sorry to say YOU ARE WRONG... I can't say whose decision was to design okhttp to forcefully fix missplaced headers but it isn't helping nobody... it is tricking them into think they are doing right when indeed there is a minor issue in the code....

and as always it can grow and become a huge snowball, all because the api masked the error while it was small

**Comment by swankjesse** [comment]
@bolds07 I'm lost. Can you point to our code where this happens? OkHttp attempts to preserve case wherever possible. The server must send lowercase if it's HTTP/2. The only other place we do anything is in Headers.toMultimap(). That's because maps don't support case-insensitive strings very well.

**Comment by swankjesse** [comment]
Here's one of our code samples that shows OkHttp preserving case.
https://square.github.io/okhttp/interceptors/

**Comment by bolds07** [comment]
I didnt dive in the okhttp code to understand where the change happens but i've used a proxy to log the request/response and the proxy logged response with capitals and when i logged the same resp using okhttp methods the keys were always lowercase

**Comment by swankjesse** [comment]
@bolds07 does OkHttp talk to the proxy via HTTP/2?
