### ISSUE TITLE
OOM happened some Android devices due to Http2Connection creates too many threads 

### ISSUE THREAD

**Issue by LuffyBySunny** [square/okhttp#6677]
**Http2Connection creates too many threads when I create many net requests。**

There is source code in okhttp3 library version is 3.12.0.

```
void start(boolean sendConnectionPreface) throws IOException {
    if (sendConnectionPreface) {
      writer.connectionPreface();
      writer.settings(okHttpSettings);
      int windowSize = okHttpSettings.getInitialWindowSize();
      if (windowSize != Settings.DEFAULT_INITIAL_WINDOW_SIZE) {
        writer.windowUpdate(0, windowSize - Settings.DEFAULT_INITIAL_WINDOW_SIZE);
      }
    }
    new Thread(readerRunnable).start(); // Not a daemon thread.
  }
```

Why not use threadPool? How should I do to avoid this when I need create many requests?

**Comment by swankjesse** [comment]
Are you using one OkHttpClient or many? We changed which threads we use in the latest 4.x releases.

**Comment by LuffyBySunny** [comment]
> Are you using one OkHttpClient or many? We changed which threads we use in the latest 4.x releases.

I am using one OkHttpClient.

**Comment by luis33338** [comment]
forck

**Comment by yschimke** [comment]
We can't easily reproduce this as is.  Can you post a reproduction, but ideally stackoverflow is the right type of forum to work through this type of issue.  Unless we have a bug reproduction.
