### ISSUE TITLE
I want to use DiskLruCache but it only has a internal constructor in kotlin

### ISSUE THREAD

**Issue by anxinxu** [square/okhttp#6679]
Good bug reports include a failing test! Writing a test helps you to isolate and describe the problem, and it helps us to fix it fast. Bug reports without a failing test or reproduction steps are likely to be closed.

Here’s an example test to get you started.
https://gist.github.com/swankjesse/981fcae102f513eb13ed

**Comment by JakeWharton** [comment]
It is an implementation detail and not meant for public usage. You can copy its sources into your project in order to use it.
