### ISSUE TITLE
Unexpected CertificatePinner Invalid pattern Exception 

### ISSUE THREAD

**Issue by AbdulrahmanGamal** [square/okhttp#6681]
java.lang.IllegalArgumentException: Invalid pattern: https://www.domain.com/
        at okhttp3.CertificatePinner$Pin.<init> Method String.toCanonicalHost() is not working as expected
i got this crash although it was working on okhttp version 3.+

**Comment by yschimke** [comment]
You shouldn't be passing a URL there. It should be a host string or wildcard pattern.
