### ISSUE TITLE
CertificateChainCleaner with custom TrustManager removes all certs.

### ISSUE THREAD

**Issue by davidamey** [square/okhttp#6682]
So, this may be intentional, but I've come across a difference between okhttp3 and 4.

We do our own certificate pinning in a network interceptor:
```kotlin
private fun pin(): (Interceptor.Chain) -> Response = {
  val leafCert = it.connection()?.handshake()?.peerCertificates?.firstOrNull()
  // ...
}
```
This works fine in 3 and 4.

But, we also produce a build variant that disables SSL verification with:
```kotlin
    private fun OkHttpClient.Builder.insecure(): OkHttpClient.Builder {
        val tm = object : X509TrustManager {
            override fun getAcceptedIssuers() = arrayOf<X509Certificate>()
            override fun checkClientTrusted(chain: Array<X509Certificate>, authType: String) = Unit
            override fun checkServerTrusted(chain: Array<X509Certificate>, authType: String) = Unit
        }

        return this
                .hostnameVerifier { _, _ -> true }
                .sslSocketFactory(SSLContext.getInstance("TLSv1.2").apply {
                    init(null, arrayOf(tm), SecureRandom())
                }.socketFactory, tm)
    }
```
which, again works in 3 and 4.

However, when we apply the custom TM in okhttp4, the CertificateChainCleaner removes all the certificates leaving `peerCertificates` empty when the interceptor gets to it.

If it's intentional, I can work around it, but it's an unexpected change between 3 and 4. Perhaps being able to disable the CertPinner entirely if it's not going to be used would be nice, but I don't think currently possible?

**Comment by swankjesse** [comment]
Fix the deprecation warning on the call to SSLSocketFactory and you should be good.

**Comment by yschimke** [comment]
It looks like the sample code is using the non deprecated method? tm is last argument.

**Comment by davidamey** [comment]
I see no deprecation warnings.

What I believe is happening, is the Platform class passes, into the BasicTrustRootIndex, the accepted issuers from the TrustManager, which in my case is empty.
```
 open fun buildTrustRootIndex(trustManager: X509TrustManager): TrustRootIndex =
      BasicTrustRootIndex(*trustManager.acceptedIssuers)
```

Then, the BasicTrustRootIndex uses that empty list to look-up certs during cleaning:
```
  override fun findByIssuerAndSignature(cert: X509Certificate): X509Certificate? {
    val issuer = cert.issuerX500Principal
    val subjectCaCerts = subjectToCaCerts[issuer] ?: return null
```

So, when the BasicCertificateChainCleaner calls:
```
      val trustedCert = trustRootIndex.findByIssuerAndSignature(toVerify)
```
it always gets `null` and discards the cert.

I haven't been through the okhttp3 code to see how this behaved before.

**Comment by yschimke** [comment]
I think this was intentional and debated.  We need to return the cleaned certs but have nothing to trust, so we return an empty list at some point.

I don't think we have a good fix for this, but you can workaround by looking directly at the SSLSocket in an event listener.  But the meaning of certificate pinning with disabled security isn't clear anyway.

**Comment by davidamey** [comment]
Fair enough, I did wonder if it was intentional.

When we're testing against some internal environments, the certificates are self-signed, but can still be pinned and I didn't want to modify or disable that pinning code.

Have worked around it now though. Thank you anyway :-)
