### ISSUE TITLE
Why Maven repository says deprecated

### ISSUE THREAD

**Issue by mwshubham** [square/okhttp#6686]
https://mvnrepository.com/artifact/com.squareup.okhttp3/mockwebserver

![1](https://user-images.githubusercontent.com/29930308/119262179-eea46700-bbf7-11eb-8c6b-940156737e54.png)

**Comment by swankjesse** [comment]
We're renaming the artifact in 5.0. But you can continue to use the existing artifact, it's your best choice.

**Comment by mwshubham** [comment]
Thanks for the INFO.
