### ISSUE TITLE
Give a way to customize ping-pong logic

### ISSUE THREAD

**Issue by PratimMallick** [square/okhttp#6690]
We want to have a custom ping-pong logic, where the `failWebSocket` is called only when the last pong was received `x` seconds ago and the interval of sending ping is `y` . In our use case `x`  > `y`

Currently there is no way where to achieve this because, websocket is shutdown as soon as `writePingFrame` of `RealWebSocket` sees that `awaitingPong` is `TRUE`. This means we cannot have different `x` and `y` values.  

Please suggest if there is a way to have different values of `pingInterval` and the time to check `last pong received` time.

**Comment by yschimke** [comment]
This is probably covered by https://github.com/square/okhttp/issues/5855
