### ISSUE TITLE
RetryAndFollowUpInterceptor needs to consider cookies

### ISSUE THREAD

**Issue by Junzzzz** [square/okhttp#6692]
Some redirect requests will set cookies in the request header.

https://github.com/square/okhttp/blob/f8fd4d08decf697013008b05ad7d2be10a648358/okhttp/src/main/kotlin/okhttp3/internal/http/RetryAndFollowUpInterceptor.kt#L291-L331

I think this code can be enhanced, consider the problem of `Set-Cookie`.

**Comment by swankjesse** [comment]
@Junzzzz could you please provide an executable test case to demonstrate the problem?

**Comment by Junzzzz** [comment]
@swankjesse 
Sorry for the late reply.
I found that I can use `CookieJar` to solve this problem, as long as it is used to save the `Cookies` of each response.
