### ISSUE TITLE
WebSocket: onFailure java.lang.SecurityException: getDeviceId: The user 10179 does not meet the requirements to access device identifiers., null

### ISSUE THREAD

**Issue by 555chy** [square/okhttp#6695]
Android 9.0 is OK, but Android 10 use websocket  connect success, but send fail, then invoke onFailure method, and report this

WebSocket: onFailure java.lang.SecurityException: getDeviceId: The user 10179 does not meet the requirements to access device identifiers., null

**Comment by 555chy** [comment]
send return true, but no response, and invoke onFailure method

**Comment by yschimke** [comment]
Can you provide the stacktrace?

**Comment by yschimke** [comment]
Most likely this is not related to OkHttp, but some code your app is calling directly or indirectly.
