### ISSUE TITLE
HttpLogginInterceptor with bodies but without headers

### ISSUE THREAD

**Issue by bartek-wesolowski** [square/okhttp#6699]
I'd like to use `HttpLoggingInterceptor` to log requests and responses with their bodies. I don't care about headers. I'd like there to be a way to do it via a new log level or a flag, e.g. `loggingInterceptor.logHeaders = false`. I believe I'm not the only one in need of this functionality:
https://stackoverflow.com/questions/56922533/okhttp3-httplogginginterceptor-log-body-without-logging-header

**Comment by swankjesse** [comment]
Our aspirations with the logging interceptor is to include something basic and small. If you need something more capable, I recommend either writing your own interceptor or using a tool like Chucker or Charles.

**Comment by bartek-wesolowski** [comment]
Adding an additional if statement wouldn't make `HttpLoggingInterceptor` much more complicated, but I guess it's your call. I can still copy-paste the code and make the necessary adjustments myself, but I was thinking that more people needed the same functionality.

Also, `isProbablyUtf8()` in `utf8.kt` is internal, so that's another thing you need to copy-paste if you want to extend `HttpLoggingInterceptor`.

**Comment by swankjesse** [comment]
@bartek-wesolowski agreed that it would nbe a small fix. I'm attempting to convince you & others that there are better tools for this job than the logging interceptor. I use Charles for this stuff and it's wonderful. It even works with protocol buffers!

**Comment by swankjesse** [comment]
Yep!

**Comment by yschimke** [comment]
I added a nub of an article with two links.  If you have a recent screenshot of Charles with realistic traffic, maybe edit with a screenshot if you feel like it.  https://stackoverflow.com/a/67954642/1542667
