### ISSUE TITLE
okHttp and graalvm not working with latest stable (4.9.1) - only RC?

### ISSUE THREAD

**Issue by Excpt0r** [square/okhttp#6704]
Hey,
I was playing around with okHttp and graalvm, so I'm not experienced with both.
I had problems with some classes/unresolved types i.e.:
OpenJSSEPlatform, ConscryptPlatform, BouncyCastlePlatform

As the okHttp website states it is ready for graalvm, I thought the fault is with my configuration and studied stackoverflow and okcurl.
But at the end, using okhttp version 4.10.0-RC1 instead of the latest stable 4.9.0 just did the trick.
The relevant change seems to be okhttp/src/main/kotlin/okhttp3/internal/graal/svm.kt

Hope this helps some people, and maybe it would be worth mentioning this here:
https://square.github.io/okhttp/#graalvm-native-image

**Comment by yschimke** [comment]
@Excpt0r yep, good point. We are adding support in 5.0.0-alpha.2 now. I'll put a note.

**Comment by yschimke** [comment]
@Excpt0r OkHttp 5 will follow on from Okio 3.0, so it's not imminent.
