### ISSUE TITLE
SSLProtocolException caught in Http2Connection$ReaderRunnable.execute() does not propagate to application layer and  request gets retried forever

### ISSUE THREAD

**Issue by acme2016** [square/okhttp#6717]
OKHttp Version 3.14.9
Platform: Android 10/11
I'm connecting to a server which supports http2 and the server requires client certificate. We rely on the exception from OkHttp layer during connection to judge whether provide the client certificate. 
During the connection, the following exceptions happens when start the http2Connection in the  Http2Connection$ReaderRunnable.execute()
- javax.net.ssl.SSLProtocolException: Read error: ssl=0x7b7b069008: Failure in SSL library, usually a protocol error error:10000410:SSL routines:OPENSSL_internal:SSLV3_ALERT_HANDSHAKE_FAILURE (external/boringssl/src/ssl/tls_record.cc:587 0x7bd930b6c8:0x00000001)

The the exception then got handled at the end of the CallServerInterceptor.intercept(), and the trackFailure was called, due to the isMultiplexed (because http2 used) returns true, the failure is not get recorded, the routeFailureCount is not get increased.Then when this exception is caught by the RetryAndFollowUpInterceptor, in its logic to check whether the exception is recovered, it would pass the check, then the request get retried, exception was not thrown to upper layer, and then the process get repeated forever, app hangs without know why. 

Could you please help to analysis? As I'm not quite familiar with the whole connection workflow, not sure if it is an expected behavior, though it does seem to be an issue to me. 

It does not happen if force to connect using Http1.1.

**Comment by yschimke** [comment]
3.14.x is not maintained, can you reproduce with 4.9.1 and if so we can fix.  Are you able to provide a clean repro or unit test of the issue?

**Comment by acme2016** [comment]
@yschimke Thanks for the info. I tried 4.9.1 and the issue is gone when I connect to the Tomcat server. Checked the history a little bit, seems the issue has been addressed in the commit from this PR https://github.com/square/okhttp/pull/5787.
Great news, thanks! I still have a webLogic14.1 server to verify, hopefully it should also be fine.
