### ISSUE TITLE
Error while closing callback response

### ISSUE THREAD

**Issue by andron3000** [square/okhttp#6718]
Hi, I don't have any clue why such kind of issue happens on our side from time to time. Please assist.
Thanks.

okhttp version: **3.4-2**

```
  private String closeResponse(Response response) throws IOException {
    try {
      return response.body().string();
    } catch (Exception e) {
      log.error("Error while closing callback response, ", e);
      throw e;
    } finally {
      response.close();
    }
  }
```

error stack-trace:
```
java.io.EOFException: null
	at okio.RealBufferedSource.require(RealBufferedSource.java:59)
	at okio.GzipSource.consumeHeader(GzipSource.java:114)
	at okio.GzipSource.read(GzipSource.java:73)
	at okio.Buffer.writeAll(Buffer.java:993)
	at okio.RealBufferedSource.readByteArray(RealBufferedSource.java:106)
```

**Comment by yschimke** [comment]
Does it happen with 4.9.1? 3.4.x isn't a supported version, so please try upgrading and provide an executable reproduction.

**Comment by liedQM** [comment]
We see the crash with 4.9.1:
{code}
Stacktrace: java.io.EOFException
        at okio.RealBufferedSource.require(RealBufferedSource.kt:199)
        at okio.GzipSource.consumeHeader(GzipSource.kt:104)
        at okio.GzipSource.read(GzipSource.kt:62)
        at okio.Buffer.writeAll(Buffer.kt:1642)
        at okio.RealBufferedSource.readByteArray(RealBufferedSource.kt:236)
        at okhttp3.ResponseBody.bytes(ResponseBody.kt:124)
{code}

for the following response:
{code}
HTTP/2 202 
date: Fri, 23 Jul 2021 09:48:26 GMT

content-length: 0
content-encoding: gzip
content-security-policy: default-src 'self'
strict-transport-security: max-age=31536000; includeSubDomains
vary: Accept-Encoding
x-content-type-options: nosniff
x-dns-prefetch-control: off
x-download-options: noopen
x-frame-options: DENY
x-vcap-request-id: xxxxxx
x-xss-protection: 1; mode=block
{code}

**Comment by yschimke** [comment]
I don't think a gzip response makes sense with 0 bytes content length. This looks like a server bug.

**Comment by liedQM** [comment]
@yschimke: I'm not the reporter, I just looked if the crash was already mentioned and saw your question regarding 4.9.1.
I'm not in any contact with the original thread owner @andron3000, I just wanted to show you an example for 4.9.1.

**Comment by liedQM** [comment]
@yschimke If it is really a server bug, why does the iOS system not reject / crash for such a response?

**Comment by yschimke** [comment]
Is there an example URL. Is it a well known public service? Or something bespoke?

**Comment by liedQM** [comment]
In our case it is a private API which I can't share but without a fix on your side we need to add such an ugly workaround:
```
val responseData = responseBody?.takeIf { response.networkResponse?.headers?.get("content-length")?.toIntOrNull()?.let { it > 0 } == true }?.bytes()
```
We even need to take the `networkResponse` because the content length header is not available in the response headers.

And I also double checked the [RFC2616](https://datatracker.ietf.org/doc/html/rfc2616#section-14.11) and there is no mention, that the `Content-Encoding` header is only allowed to be sent when a body is available or `Content-Length` > 0.

**Comment by yschimke** [comment]
But the content-length is bytes after the encoding. And it won't be 0 with gzip. This is a bug to fix in your server if I understand correctly.

**Comment by GisTom2** [comment]
> I don't think a gzip response makes sense with 0 bytes content length. This looks like a server bug.

so.... Why does okio check the content if the length is zero?
I do not think it makes sense to check the content if the content-length is ZERO.

The logic of okio needs to be updated to NOT check the content if the content-length is ZERO. 
What do you think?

**Comment by yschimke** [comment]
If it's gzipped - the even zero length content will have the header?

```
  private fun consumeHeader() {
    // Read the 10-byte header. We peek at the flags byte first so we know if we
    // need to CRC the entire header. Then we read the magic ID1ID2 sequence.
    // We can skip everything else in the first 10 bytes.
    // +---+---+---+---+---+---+---+---+---+---+
    // |ID1|ID2|CM |FLG|     MTIME     |XFL|OS | (more-->)
    // +---+---+---+---+---+---+---+---+---+---+
    source.require(10)
```

**Comment by GisTom2** [comment]
> If it's gzipped - the even zero length content will have the header?

There are many servers that send the additional header(s). We cannot change all of them because we do not control them. Such servers can work without issues if the client is able to handle this additional header. 


The only question in this situation is:
Is it ok for you if a not critical issue(!) with the server becomes a critical problem for your product?
This question is not about bugs. This question is about a responsibility.

The answer on this questions defines a strategy.

**Comment by yschimke** [comment]
The strategy is documented in the project README

https://github.com/square/okhttp?tab=readme-ov-file#a-well-behaved-user-agent

> OkHttp is principled and avoids being overly configurable, especially when such configuration is to workaround a buggy server, test invalid scenarios or that contradict the relevant RFC. Other HTTP libraries exist that fill that gap allowing extensive customisation including potentially invalid requests.

That said, OkHttp provides interceptors that let you implement this transparently the caller. So you aren't blocked, the logic you want OkHttp to assume for everyone, is better placed in your own custom interceptor. Other users of the library might be assuming the correctness that we currently implement.
