### ISSUE TITLE
Feature Request: Use MockWebServer in the production version of the app for selected Requests

### ISSUE THREAD

**Issue by bizzguy** [square/okhttp#6720]
New Feature Request: Use MockWebServer inside app instead of tests

Here's the use case:

- Some set API endpoints do not exist on any server (yet or maybe ever)
- I would like the production version of the app to be able to call those endpoint through the OkHttp stack even though they do not actually exist
- I would like to use MockWebServer to define the call (ie request headers, response status, response headers, response body)
- OkHttp would then be able to make the call and return the response as though it was a real call

Although a MockWebServer can be started in an app now, there is no way to start it for each WebRequest and pass the reference to the call.

# Summary

I would like to be able to use MockWebServer in the app itself rather than in instrumentation tests

**Comment by swankjesse** [comment]
You have my permission. If you use the OkHttp 5.x snapshot you don't even need a JUnit dependency.
