### ISSUE TITLE
Thread Unsafe detection for Sink, Source, Filesystem, Response etc.

### ISSUE THREAD

**Issue by yschimke** [square/okhttp#6725]
The class of bugs like https://github.com/square/okhttp/issues/6723 are tricky to hunt down.  We should consider how to wrap key Okio or OkHttp abstractions to detect unsafe thread use.

Maybe one that records and warns on switching threads, or concurrent use, or after a failure prints out the observed threads for any operation failing with a RuntimeException.

**Comment by yschimke** [comment]
Probably also dual reading of a response? like a debug call to .string() before continuing to consume.

**Comment by yschimke** [comment]
No current plans, and most recent issue was actually a WebSocket concurrency bug.

**Comment by wylswz** [comment]
I think it's nice to have something like this, we're currently having a hard time troubleshooting inconsistent Segments...
