### ISSUE TITLE
Got "clientBuilder.sslSocketFactory(SSLSocketFactory) not supported on JDK 9+" on JDK 1.8.0_252

### ISSUE THREAD

**Issue by hailin84** [square/okhttp#6731]
I's using okhttp3 as http client to test my code. I got a exception:
Caused by: java.lang.RuntimeException: java.lang.UnsupportedOperationException: clientBuilder.sslSocketFactory(SSLSocketFactory) not supported on JDK 9+

I am using JDK 1.8.0_252. I check the code, here is the reason:
```
  public static Jdk9Platform buildIfSupported() {
    // Find JDK 9 new methods
    try {
      Method setProtocolMethod =
          SSLParameters.class.getMethod("setApplicationProtocols", String[].class);
      Method getProtocolMethod = SSLSocket.class.getMethod("getApplicationProtocol");

      return new Jdk9Platform(setProtocolMethod, getProtocolMethod);
    } catch (NoSuchMethodException ignored) {
      // pre JDK 9
    }

    return null;
  }
```
Unfortunately, jdk supports those two methds since jdk 1.8.0_251, not only JDK9+.

**Comment by yschimke** [comment]
We've fixed in master already

```
      isAvailable = if (majorVersion != null) {
        majorVersion >= 9
      } else {
        try {
          // also present on JDK8 after build 252.
          SSLSocket::class.java.getMethod("getApplicationProtocol")
          true
        } catch (nsme: NoSuchMethodException) {
          false
        }
      }
```

Apart from the message being wrong and confusing, the behaviour you are experiencing is correct.  You should avoid using that method, it's been deprecated for literally years.

**Comment by hailin84** [comment]
Looks like that's not a bug, cause method clientBuilder.sslSocketFactory(SSLSocketFactory) marks as Deprecated.

And I use this method can fix it:
sslSocketFactory(
        SSLSocketFactory sslSocketFactory, X509TrustManager trustManager) 

So I close this issue. Sorry to interrupt.

**Comment by hailin84** [comment]
> We've fixed in master already
> 
> ```
>       isAvailable = if (majorVersion != null) {
>         majorVersion >= 9
>       } else {
>         try {
>           // also present on JDK8 after build 252.
>           SSLSocket::class.java.getMethod("getApplicationProtocol")
>           true
>         } catch (nsme: NoSuchMethodException) {
>           false
>         }
>       }
> ```
> 
> Apart from the message being wrong and confusing, the behaviour you are experiencing is correct. You should avoid using that method, it's been deprecated for literally years.

You are right, thanks.
