### ISSUE TITLE
Android UI Tests fail on GitHub actions due to race condition of mockwebserver

### ISSUE THREAD

**Issue by TheReprator** [square/okhttp#6733]
Description
My All UI android test fail on Github action but when I run the tests locally, all tests pass. So, most probably it's due to race condition of mockwebserver.

Expected behavior
All tests should pass

Actual behavior
All UI tests are failing

Repro Details

Workflow Result:
https://github.com/TheReprator/Wipro/actions/runs/979383000

Repo: https://github.com/TheReprator/Wipro
Branch: codeCoverage
workflow: non_master_push.yml

Please let me know, how can i avoid this race condition.

Looking forward for a solution.

Regards,
Vikram Singh

**Comment by yschimke** [comment]
I'd start with the fact your tests are running on port 8080, see

```
  /**
   * Starts the server on the loopback interface for the given port.
   *
   * @param port the port to listen to, or 0 for any available port. Automated tests should always
   * use port 0 to avoid flakiness when a specific port is unavailable.
   */
  @Throws(IOException::class)
  @JvmOverloads fun start(port: Int = 0) = start(InetAddress.getByName("localhost"), port)
```

and in your tests

```
    @Before
    fun setUp() {
        hiltRule.inject()

        mockWebServer.start(8080)
```

But please continue this sort of investigation in a more appropriate forum like stackoverflow or getting a colleague to help you debug. Please reopen with a bug reproduction in OkHttp if you feel it's a bug in MockWebServer. The CI runs in an OkHttp PR should cover the same situation you are describing.

**Comment by TheReprator** [comment]
@yschimke  even with " mockWebServer.start() or  mockWebServer.start(0)", it's throwing me error `"Caused by: java.lang.IllegalArgumentException: Invalid URL port: "0"
	at okhttp3.HttpUrl$Builder.parse$okhttp(HttpUrl.kt:1329)
	at okhttp3.HttpUrl$Companion.get(HttpUrl.kt:1633)"`

**Comment by yschimke** [comment]
That isn't a complete stack trace that I can provide any help with. As I suggested before "please continue this sort of investigation in a more appropriate forum like stackoverflow", we can't provide personal 1:1 user support here.

**Comment by TheReprator** [comment]
@yschimke Please find the question on stackoverflow, https://stackoverflow.com/questions/68190725/android-ui-tests-fail-on-github-actions-due-mockwebserver

**Comment by TheReprator** [comment]
@yschimke , i had configured everything as per, https://github.com/TheReprator/Wipro/blob/mockwebserver/appModules/factList/src/androidTest/kotlin/reprator/wipro/factlist/di/TestFactListModule.kt(line no 58), but still my test(https://github.com/TheReprator/Wipro/blob/mockwebserver/appModules/factList/src/androidTest/kotlin/reprator/wipro/factlist/test/FactListKaspressoTest.kt) fails

**Comment by yschimke** [comment]
It all looks correct. I'm sorry unless you can make a simple reproduction as a test we can't really help you. Can you debug with a colleague to find the root cause.
