### ISSUE TITLE
OkHttp - connecting to https on LAN

### ISSUE THREAD

**Issue by bigalnz** [square/okhttp#6734]
Hello,

I have made a connection to a https://www.google.com with a fatjar from CLI - very easy.

Now I want to connect to a https website on our LAN. We do not enforce proxy for LAN sites, so it should just be a case of changing the URL to https://www.contoso.com but when I try this I get a error:

PKIX Path Building Error

How can I fix this?

**Comment by yschimke** [comment]
Please ask usage questions like this on stackoverflow.
