### ISSUE TITLE
An issue when I inherit OkHttp dependency from another module

### ISSUE THREAD

**Issue by ExerciseBook** [square/okhttp#6735]
https://github.com/ExerciseBook/okhttp-issue-in-kotlin

### Dependency Graph

```
    OkHttp -> Framework -> Project
```

In this case, we can assume that framework prepares some commonly used OkHttp operations for every module in the whole project.

#### `framework` module

In module `framework`, we can run all the OkHttp operations successfully.

But we can't compile `MediaType.parse("plain/text; charset=utf-8")` in the main function, because the code of OkHttp blocked it.

```
    @JvmName("-deprecated_parse")
    @Deprecated(
        message = "moved to extension function",
        replaceWith = ReplaceWith(
            expression = "mediaType.toMediaTypeOrNull()",
            imports = ["okhttp3.MediaType.Companion.toMediaTypeOrNull"]),
        level = DeprecationLevel.ERROR)     // <------- this line
    fun parse(mediaType: String): MediaType? = mediaType.toMediaTypeOrNull()
```

#### `project` module

In module `project`, we can only run the OkHttp operation which is written by java in `framework` successfully.

But we can compile `MediaType.parse("plain/text; charset=utf-8")` in the main function.

## Something I guess

In `framework` module, `@Deprecated` blocks this kind of usage, but `@JvmStatic @JvmName` let the function below visible to `project`.

```
    @JvmStatic
    @JvmName("parse")
    fun String.toMediaTypeOrNull(): MediaType? {
      return try {
        toMediaType()
      } catch (_: IllegalArgumentException) {
        null
      }
    }
```

We can use `MediaType.parse("plain/text; charset=utf-8")` in `project` module.

Because of the same reason. `@JvmStatic @JvmName` let `okhttp3.MediaType.Companion.toMediaTypeOrNull` become `okhttp3.MediaType.parse`.

We can see an `Exception in thread "main" java.lang.NoSuchFieldError: Companion` error when running main function of `project` module.

## Conclusion

I am not sure what this issue blame to, but I prefer to change the `DepreciationLevel` to a lower level to resolve this issue temporary.

**Comment by TangHuaiZhe** [comment]
![image](https://user-images.githubusercontent.com/7965577/124053799-754c2f80-da53-11eb-8e4b-9d67b4271744.png)

It seems that the version of okhttp is downgraded to `3.14.9` in the project module, and the okhttp version that the framework module depends on is `4.9.0`, which causes different behaviors between the two modules.

Try this command and you can get the dependencies.
`./gradlew project:dependencies`

Follow the Gradle doc about version confilct: 
 https://docs.gradle.org/current/userguide/dependency_resolution.html#sec:version-conflict

**Comment by swankjesse** [comment]
Yeah if you use a consistent version of OkHttp you'll be fine.
