### ISSUE TITLE
okhttp3.Authenticator#authenticate to be called for java.net.HttpURLConnection#HTTP_FORBIDDEN ?

### ISSUE THREAD

**Issue by nightfixed** [square/okhttp#6737]
The API I am interacting with, requires JWT tokenization for its requests.
For this purpose, I have built an `class AccessTokenAuthenticator : Authenticator` which manages the tokenization of requests, as well as refreshing the token, in case of expiry.

All works fine, except for one case: there is one API endpoint that will return `response code 403` in case of expired token. Because of this, my `Authenticator` is not called in this particular case.

Is there a chance there might be a change at the library level, in the future?
I will just go with the `Interceptor` approach, for the time being.

**Comment by yschimke** [comment]
Yep. Use an interceptor to translate these response to 401.

**Comment by yschimke** [comment]
It's valid, but it explicitly means that reauthorization won't help.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/403

So I think OkHttp is doing the right thing here. And there is already a workaround in interceptors to fix.

Or you could handle in the app by switching to your second account.
