### ISSUE TITLE
Suport specify the “address” and “host” for the request

### ISSUE THREAD

**Issue by johnyannj** [square/okhttp#6744]
At present，okhttp's HttpUrl only can  be set "host",  okhttp will resovle the host with "client.Dns".

some time I want Specify the “address” and “host” for the request

For comparison， apache httpclient api：

client.execute(httpHost, httpPost)

httpHost can be set the “address” and “host”.

**Comment by swankjesse** [comment]
You can set the `Host` header on a request and it doesn't need to match the HttpUrl. Does that help?

**Comment by johnyannj** [comment]
@swankjesse   
It is not enough  for "https",  the host name verifier will failed.

**Comment by swankjesse** [comment]
Are you on the latest OkHttp?

**Comment by johnyannj** [comment]
@swankjesse  3.14.4

**Comment by johnyannj** [comment]
okhttp3.internal.connection.RealConnection#connectTls  will vertify the host in cert  with address.url().host()

**Comment by swankjesse** [comment]
Yes. There's several hostnames at play:
 - the hostname used for DNS
 - the hostname used for SNI
 - the hostname used for the Host header
 - the hostname used for cert checking

What's your use case?

**Comment by johnyannj** [comment]
Hi @swankjesse 

my use cases:
the hostname used for the Host header
the hostname used for cert checking

**Comment by johnyannj** [comment]
> Hi @swankjesse
> 
> my use cases:
> the hostname used for the Host header
> the hostname used for cert checking

I have multi IPs  with same hostname,
I want connect every ip  with the same hostname.

**Comment by swankjesse** [comment]
I think you want a custom implementation of Dns. You can delegate to the built-in one if you need.

**Comment by johnyannj** [comment]
@swankjesse 
1、dns  belongs to client，not  request
2、use dns， client will only first try the first address，then others,  can't  balance multi address

I can built one dns  through  "ThreadLocal"  etc ， but I think it is not a good way

**Comment by yschimke** [comment]
> You can set the `Host` header on a request and it doesn't need to match the HttpUrl. Does that help?

I think this is likely the easier route. Use DNS to get all known hosts. Hit each with URL using IP, but set the Host header.

**Comment by swankjesse** [comment]
@johnyannj another option: use OkHttpClient.newBuilder() to configure a custom Dns object immediately before making the call.

**Comment by johnyannj** [comment]
@yschimke  if you use  ip in request url,  the dns will be unused.

**Comment by johnyannj** [comment]
@swankjesse It seems to be a feasible option, and we will try it. Thank you.

**Comment by johnyannj** [comment]
@swankjesse 
Hello,  the method is effective. 

but I still recommend that okhttp support this feature。

DNS  is used for known host ， to resovle the IP。
I now kown the IP and want to specify a host.

**Comment by yschimke** [comment]
We are very careful about changes like this that introduce new public API or potentially cause a breaking change in behaviour to existing clients based on the old APIs.  So I think having a clean workaround is the best we can target right now.

I think we made an explicit call to support domain fronting in the past to unblock legitimate privacy sensitive use cases, but unlikely to do that here when you have a valid workaround.
