### ISSUE TITLE
Okhttp3 3.14.4 does not close the connection automatically while the contentLength is oversized

### ISSUE THREAD

**Issue by ChrisZzzzzzzzz** [square/okhttp#6745]
Here is the thing, i am writting a TOOL KIT to implement transfering file data with my server by using okhttp3, and overrided RequestBody class in my code. The wired thing happens when i am setting a contentLength which is larger than the file actual size, for example, the file size is 2735 and contentLengh set to 3000, the connection does not automatically close immediately after the file data transfering finished, and i make a new call immediatly would cause the new request url data printed in the server file. I have tried a couple solutions:

1. Let the server close the connection would not be helpful, because the server has to wait the client all data transfered in order to close.
2. Setting a shorter connection timeout may solve this problem, but I am offering a setTimeout api to my users. 
2. Also, I tried to call Response.close() which does not help because newcall.execute() gives a null response value on the second call. 
3. When I tried call close() in my BufferedSink() method when it finishes transferring local file data, the call throws a exception : unexpected end of stream.

**Comment by swankjesse** [comment]
You must not let these sizes mismatch. If you don't know the size use -1.

**Comment by ChrisZzzzzzzzz** [comment]
> You must not let these sizes mismatch. If you don't know the size use -1.

I can't set contentLength to -1 because the server side uses the parameter.

**Comment by swankjesse** [comment]
I think this is better served by StackOverflow. Wanna ask over there? I don't think there's anything actionable by the OkHttp team here.
