### ISSUE TITLE
Expect 100-continue does not appear to work

### ISSUE THREAD

**Issue by ifedorenko** [square/okhttp#675]
This maybe my misunderstanding of HttpURLConnection API or HTTP protocol itself, but I can't get okhttp do Expect 100-continue handshake as described in rfc [1]. Identical code using standard HttpURLConnection implementation appears to work. [2] has is an example that shows both okhttp and jdk tests I did

[1] http://www.w3.org/Protocols/rfc2616/rfc2616-sec8.html
[2] https://github.com/ifedorenko/bug430772/blob/master/src/test/java/bug430772/Expect100ContinueTest.java

**Comment by swankjesse** [comment]
I started looking into this. Seems relatively straightforward. We need to add some special support in HTTP/2, since the `100: Continue` comes back as a 2nd set of headers there.
http://httpwg.org/specs/rfc7540.html#rfc.section.8.1.3
