### ISSUE TITLE
Attempt to invoke virtual method 'int java.lang.Object.hashCode()' on a null object reference

### ISSUE THREAD

**Issue by Apeplan** [square/okhttp#6752]
java.lang.NullPointerException
Attempt to invoke virtual method 'int java.lang.Object.hashCode()' on a null object reference

okhttp3.internal.tls.BasicCertificateChainCleaner.hashCode(BasicCertificateChainCleaner.kt:112)

1
okhttp3.internal.tls.BasicCertificateChainCleaner.hashCode(BasicCertificateChainCleaner.kt:112)
2
okhttp3.CertificatePinner.hashCode(CertificatePinner.kt:238)
3
java.util.Objects.hashCode(Objects.java:98)
4
okhttp3.Address.hashCode(Address.kt:183)
5
okhttp3.Route.hashCode(Route.kt:84)
6
java.util.HashMap.hash(HashMap.java:338)
7
java.util.HashMap.containsKey(HashMap.java:595)
8
java.util.HashSet.contains(HashSet.java:203)
9
okhttp3.internal.connection.RouteDatabase.shouldPostpone(RouteDatabase.kt:40)
10
okhttp3.internal.connection.RouteSelector.next(RouteSelector.kt:74)
11
okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:205)
12
okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
13
okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
14
okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
15
okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
16
okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
17
okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
18
okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
19
okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
20
okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
21
okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
22
okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
23
okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
24
okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
25
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
26
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
27
java.lang.Thread.run(Thread.java:764)

**Comment by swankjesse** [comment]
Oooh ouch. Any steps to reproduce?

**Comment by yschimke** [comment]
Without a way to repro, going to have to close this.  It doesn't look possible outside of a VM bug, or something in the build process.  Please reopen if you can repro or provide more context like frequency by device.
