### ISSUE TITLE
Intermittent failures with diffbot

### ISSUE THREAD

**Issue by hasandiwan** [square/okhttp#6757]
Test case:
final HttpUrl baseUrl = HttpUrl.parse("https://api.diffbot.com/v3/article").newBuilder()
				.addEncodedQueryParameter("discussion", "false").addEncodedQueryParameter("paging", "false")
				.addEncodedQueryParameter("timeout", "50000")
				.addQueryParameter("token", TOKEN_FOR_DIFFBOT)
				.addQueryParameter("url", params.get("link")).build();
okhttp3.Request request = new okhttp3.Request.Builder().url(baseUrl).get().build();
okhttp3.Response response = null;
try {
	response = new OkHttpClient().newCall(request).execute();
} catch (final IOException e) {
	ret.clear();
	ret.put("error", "Upstream resource -- diffbot helper -- unavailable");
	return ret;
}

It's most likely something silly,  but the code works from curl, postman and chrome. It's an intermittent failure from Java. 

I would debug, but am not confident enough to look through the okhttp source. However, I'm willing to have my hand held as I do so.

**Comment by swankjesse** [comment]
Nothing actionable here. Try StackOverflow or provide an executable test case? Thanks!

**Comment by hasandiwan** [comment]
It seems to work now, reliably, I'll reopen if the issue rears its mysterious head again
