### ISSUE TITLE
EventListener is not being correctly invoked between requestBodyStart and requestBodyEnd

### ISSUE THREAD

**Issue by Schlud** [square/okhttp#6759]
Installing an EventListener for Monitoring an http-post request sending 65KBytes of data and receiving 65KBytes in the response seems that 4 miliseconds between invokation of requestBodyStart and requestBodyEnd are ways to short.

I have implemented following EventListener Derivate:

```
inner class RoundTripEventListener : EventListener(), Loggable {
        @Volatile var sslHandshakeStartTimestamp: Long? = null
        @Volatile var requestBodyStartingTime: Long? = null
        @Volatile var responseBodyStartingTime: Long? = null

        fun resetMetricData() {
            logi("[RoundTrip] *** resetMetricData")
            sslHandshakeStartTimestamp = null
            requestBodyStartingTime = null
            responseBodyStartingTime = null
            sslHandshakeTimeMS = 0 // resetting last ssl timestamp
            requestBodyTimeMS = 0
            requestBodyPayload = 0
            responseBodyTimeMS = 0
            responseBodyPayload = 0
        }

        override fun callStart(call: Call) {
            logi("[RoundTrip] *** callStart")
            resetMetricData()
        }

        override fun secureConnectStart(call: Call) {
            logi("[RoundTrip] *** secureConnectStart")
            sslHandshakeStartTimestamp = System.currentTimeMillis()
        }

        /**
         * this method will be invoked after a ssl-handshake has been finished
         */
        override fun secureConnectEnd(call: Call, handshake: Handshake?) {
            logi("[RoundTrip] *** secureConnectEnd")
            sslHandshakeStartTimestamp?.let {
                sslHandshakeTimeMS = System.currentTimeMillis() - it
            }
        }


        override fun connectionAcquired(call: Call, connection: Connection) {
            logi("[RoundTrip] *** connectionAcquired")
        }

        override fun requestHeadersStart(call: Call) {
            logi("[RoundTrip] *** requestHeadersStart")
        }

        override fun requestHeadersEnd(call: Call, request: Request) {
            logi("[RoundTrip] *** requestHeadersEnd")
        }

        override fun requestBodyStart(call: Call) {
            logi("[RoundTrip] *** requestBodyStart")
            requestBodyStartingTime = System.currentTimeMillis()

        }

        override fun requestBodyEnd(call: Call, byteCount: Long) {
            requestBodyStartingTime?.let {
                requestBodyTimeMS = System.currentTimeMillis() - it
            }
            requestBodyPayload = byteCount
            logi("[RoundTrip] *** requestBodyEnd, requestBodyStartingTime: $requestBodyStartingTime , requestBodyTimeMS: $requestBodyTimeMS , requestBodyPayload: $requestBodyPayload")
        }

        override fun responseHeadersStart(call: Call) {
            logi("[RoundTrip] *** responseHeadersStart")
        }

        override fun responseBodyStart(call: Call) {
            logi("[RoundTrip] *** responseBodyStart")
            responseBodyStartingTime = System.currentTimeMillis()
        }

        override fun responseBodyEnd(call: Call, byteCount: Long) {
            responseBodyStartingTime?.let {
                responseBodyTimeMS = System.currentTimeMillis() - it
            }
            responseBodyPayload = byteCount
            logi("[RoundTrip] *** responseBodyEnd responseBodyStartingTime: $responseBodyStartingTime , responseBodyTimeMS: $responseBodyTimeMS , responseBodyPayload: $responseBodyPayload")
        }
    }
```
    
 I have installed the listener like this:
 
 `private val client = OkHttpClient.Builder().eventListener(RoundTripEventListener()).build()`
 
 I'm sending the post request like this:
 
```
val request: Request = Request.Builder()
                                .url(url)
                                .post(body) // 65KBytes
                                .header(AUTHORIZATION_HEADER, authorizationValue)
                                .build()


client.newCall(request).execute().use { // do some stuff with the Response}
```
 

 and I record doing the post request following log sequence:
 
 *** callStart
*** resetMetricData
*** secureConnectStart
*** secureConnectEnd
*** connectionAcquired
*** requestHeadersStart
*** requestHeadersEnd
*** requestBodyStart
*** requestBodyEnd, requestBodyStartingTime: 1626892169366 , requestBodyTimeMS: 4 , requestBodyPayload: 65850
*** responseHeadersStart
*** responseBodyStart
*** responseBodyEnd responseBodyStartingTime: 1626892169564 , responseBodyTimeMS: 415 , responseBodyPayload: 65862

It's not plausible to upload 65KB in 4 milliseconds with my mobile device,  if a download of same data (plus 12Bytes ) takes 415 ms . If I'm sending same request via Postman from my macbook it takes 63ms for uploading and 20 ms for downloading

I therefore thrust the 415 ms but not the 4 milliseconds. the 4ms are therefore a bug as far as I see.

I calculate the 4 milliseconds as you can see in the code by taking the time difference between requestBodyStart and requestBodyEnd. Further I did output some log file content to calculate the times from the Log timestamps  with the same result.

Shouldn't requestBodyEnd be invoked if the whole payload from the body has been sent over http?
4 ms is ways too short transfering 65KB from my mobile to a backend....
Or is that the time for only passing the data to another local pheripherie? But then how can the time for sending a requestBody be measured?

Thanks in advance for your feedback!

**Comment by yschimke** [comment]
This should just be the time writing to the socket (TCP or TLS) and internally is unlikely to be have received by the remote server. I don't think there it too much we want to assume about the behaviour of the OutputStream for a connection with respect to write or flush, so I think having written to the Socket is generally the best we can aim for.

To debug through this, you may want to look at HTTP/2 frames, or wireshark. You might have a response from the server in the form of a settings frame with an update to the transfer window.

But at the level OkHttp operates at based on the synchronous Socket API, I believe you are seeing the expected behaviour.
