### ISSUE TITLE
Support newBuilder methods on Cookie

### ISSUE THREAD

**Issue by Adamantcheese** [square/okhttp#6762]
I've got a bunch of cookies that need to be rebuilt with different expiration dates in some interceptors, but all the other fields I want to leave as-is without changing them. Currently, I read the headers with Cookie.parseAll, then manually iterate and recreate the cookie again, pulling all the same data from the old cookie. Here's an example of that code (Java, sorry)
```
public static void clearCookies(HttpUrl url) {
    List<Cookie> cookieList = client.cookieJar().loadForRequest(url);
    List<Cookie> expiredList = new ArrayList<>();
    for (Cookie c : cookieList) {
        Cookie.Builder builder = new Cookie.Builder()
                                           .path(c.path())
                                           .name(c.name())
                                           .value(c.value())
                                           .expiresAt(0);
        if (c.secure()) builder.secure();
        if (c.httpOnly()) builder.httpOnly();
        if (c.hostOnly()) {
            builder.hostOnlyDomain(c.domain());
        } else {
            builder.domain(c.domain());
        }
        expiredList.add(builder.build());
    }
    client.cookieJar().saveFromResponse(url, expiredList);
}
```
It would be nice if there was a newBuilder option on cookies much like there is on clients or headers or a bunch of other things so that I could get rid of this mess of code and only change what I needed to. That being said, I can already see that things like secure or hostOnly would need to be changed so that the cookie builder could modify all the fields before being built instead of relying on wrapper methods, hostOnlyDomain for example.

**Comment by yschimke** [comment]
Seems like it's missing given the Builder pattern implies it. Only reason I can see to not add it would be encouraging a pattern of clients mutating server provided Cookies and subverting security etc.  But that seems overly protective.

**Comment by yschimke** [comment]
https://github.com/square/okhttp/pull/6766/files
