### ISSUE TITLE
Mark extension functions in okhttp3/internal/Util.kt as `internal` so they don't appear in auto-complete for users

### ISSUE THREAD

**Issue by angusholder** [square/okhttp#6763]
Key offenders being `Any.notify()`, `Any.notifyAll()`, and `Any.wait()`, because they appear for all types

![image](https://user-images.githubusercontent.com/7407345/126993673-8a167951-efeb-4612-9ff2-7dbdbbda597e.png)

**Comment by yschimke** [comment]
This isn't ideal, we can only make them internal when not used in other modules.  So it looks semi random, but this is a fair point. We may need to remove some later if used across modules.

https://github.com/square/okhttp/pull/6765

For less critical ones you may need to use Intellij hints to avoid this.

https://stackoverflow.com/questions/51863754/is-there-any-way-to-disable-autocomplete-for-certain-extension-functions

**Comment by angusholder** [comment]
Thanks!
