### ISSUE TITLE
The username and password fields are not resulting in an Authorization header

### ISSUE THREAD

**Issue by proletarius101** [square/okhttp#6764]
````java
HttpUrl url = new HttpUrl.Builder()
                .scheme("https")
                .host("httpbin.org")
                .addPathSegment("/basic-auth/myusername/supersecretpassword")
                .username("myusername")
                .password("supersecretpassword")
                .build();
Request request = new Request.Builder()
                .url(url)
                .header("User-Agent", "Test Case")
                .build();
````

It's is expected that the `username` and the `password` fields in `HttpUrl` are honored by `Okhttp3.Request`. However, there won't be an `Authorization` header in `request.headers()`.

**Comment by swankjesse** [comment]
This is working as intended.

If you want to authenticate, see this:
https://github.com/square/okhttp/blob/master/samples/guide/src/main/java/okhttp3/recipes/Authenticate.java

            String credential = Credentials.basic("jesse", "password1");
            return response.request().newBuilder()
                .header("Authorization", credential)
                .build();
