### ISSUE TITLE
Maven Central shows MockWebServer as "Deprecated"

### ISSUE THREAD

**Issue by hubertgrzeskowiak** [square/okhttp#6769]
According to https://mvnrepository.com/artifact/com.squareup.okhttp3/mockwebserver/4.9.1 the package is "Deprecated", but according to the Readme within this repo, it's the newest version. Did somebody maybe wrongly label it as Deprecated?

Related https://github.com/square/okhttp/issues/6770

**Comment by yschimke** [comment]
Not showing deprecated https://mvnrepository.com/artifact/com.squareup.okhttp3/mockwebserver/4.11.0
