### ISSUE TITLE
java.lang.IllegalArgumentException  FRAME_SIZE_ERROR length > 0: 4

### ISSUE THREAD

**Issue by Apeplan** [square/okhttp#6771]
OS：Android 9,level 28
CPU：arm64-v8a
okhttp：4.9.0

1. okhttp3.internal.http2.Http2Writer.frameHeader(Http2Writer.kt:259)
2. okhttp3.internal.http2.Http2Writer.rstStream(Http2Writer.kt:128)
3. okhttp3.internal.http2.Http2Connection.writeSynReset$okhttp(Http2Connection.kt:354)
4. okhttp3.internal.http2.Http2Connection$writeSynResetLater$$inlined$execute$1.runOnce(TaskQueue.kt:220)
5. okhttp3.internal.concurrent.TaskRunner.runTask(TaskRunner.kt:116)
6. okhttp3.internal.concurrent.TaskRunner.access$runTask(TaskRunner.kt:42)
7. okhttp3.internal.concurrent.TaskRunner$runnable$1.run(TaskRunner.kt:65)
8. java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
9. java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
10. java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
11. java.lang.Thread.run(Thread.java:784)

**Comment by yschimke** [comment]
We will need more information in order to debug this.  How common is it?

The 0 is coming from the code below, so it seems like the server is sending a max frame size of 0.  Without access to the HTTP/2 frames it's hard to debug.

```
  /** Applies `peerSettings` and then sends a settings ACK. */
  @Synchronized @Throws(IOException::class)
  fun applyAndAckSettings(peerSettings: Settings) {
    if (closed) throw IOException("closed")
    this.maxFrameSize = peerSettings.getMaxFrameSize(maxFrameSize)
```
