### ISSUE TITLE
Gradle Stuck at Download okhttp

### ISSUE THREAD

**Issue by cricbhavinlaiya** [square/okhttp#6778]
Gradle sync taking too much time while creating signed build or make change in gradle.
It will stuck at download okhttp4.9.pom

**Comment by yschimke** [comment]
Sorry, we can't help debug your build issues.

**Comment by cricbhavinlaiya** [comment]
It's not build issue. We are having issue with this library while gradle.
It will stuck in okhttp.

**Comment by yschimke** [comment]
We don't host the pom files ourselves. Maybe try with 4.9.1.  But if it's still failing I suggest posting a reproduction to stackoverflow and maybe someone there can help with your gradle build issue.
