### ISSUE TITLE
kotlin/KotlinNothingValueException for clients with cache

### ISSUE THREAD

**Issue by Lukier1** [square/okhttp#6783]
Hello, 

While executing request for client with configured cache I get exception: 
`java.lang.NoClassDefFoundError: kotlin/KotlinNothingValueException

	at okhttp3.internal.cache.DiskLruCache.edit(DiskLruCache.kt:490)
	at okhttp3.internal.cache.DiskLruCache.edit$default(DiskLruCache.kt:448)
	at okhttp3.Cache.put$okhttp(Cache.kt:217)...`

Here is the test which reproduce this exception:
https://gist.github.com/Lukier1/99ff2ed0da3008869474fee1cce1717e

I'm using JDK 14 for compilation and run this test. 

Is there something wrong with my configuration of OkHttpClient ?

**Comment by yschimke** [comment]
I've run that test with 14.0.2, but it's passing for me.  

Can you reproduce in CI via this PR branch? https://github.com/square/okhttp/pull/6784/files

**Comment by Lukier1** [comment]
Tests from your project are also passing on machine. 
I also have created a new empty project to test this, and it also passing in this new one. 

Is there a possibility that this OkHttp cache is interfering with some Spring libraries ?
