### ISSUE TITLE
Sample for Android

### ISSUE THREAD

**Issue by namgk** [square/okhttp#6785]
Hi there,

Any samples for integrating into Android apps? Where should I declare the OkHttpClient to be shared across http calls? Do I add it to a custom application context, or a forever running service?

Thanks

**Comment by yschimke** [comment]
There are tons of tutorials - you should read those first.  The best practice in something like Android changes regularly or depends on which libraries you use like ktor or retrofit, or DI like Dagger.

https://www.google.com/search?q=okhttp+android+guide

We document a minimal set of best practices here https://square.github.io/okhttp/4.x/okhttp/okhttp3/-ok-http-client/
