### ISSUE TITLE
HttpUrl#addPathSegment does not encode square brackets "[", "]"

### ISSUE THREAD

**Issue by miloszivkovic** [square/okhttp#6791]
Was wondering if there are any plans on adding square brackets in list of characters that should be escaped in path segment. [RFC3986](https://www.ietf.org/rfc/rfc3986.txt) says these are allowed only in host part of the URL and I recently had web server returning 400 because "[" in path segment was not escaped.

**Comment by JakeWharton** [comment]
Dupe of #6790
