### ISSUE TITLE
failed to connect to a ipv6 address after 15000ms

### ISSUE THREAD

**Issue by zhujiaming** [square/okhttp#6796]
My app encountered the following problem when using OkHttp4.3.1:

The connection timed out when connecting to wifi,throws **failed to connect to (a ipv6 address) after 15000ms.**
But switching to mobile network works.

after wifi debug, I found **the wifi network does not support ipv6** , But why is okttp connected to ipv6？

okhttp version:4.3.1

may I ask why this is, and how to solve it?

**Comment by yschimke** [comment]
Please ask this sort of question on stackoverflow, we can't offer usage advice through our issue tracker.
