### ISSUE TITLE
MockWebServer issues with github CI

### ISSUE THREAD

**Issue by yschimke** [square/okhttp#6813]
Related to https://github.com/square/okhttp/pull/6811

Issue surfaces like miningmadness.com vs MiningMadness.com for 127.0.0.1.  Imagine the host file has a bunch of blockholed hosts similar to https://gist.github.com/Jolg42/100b52fd6d88ac81740f2cb5086c9b55

Probably also causes delays.  But what should the behaviour be for MockWebServer.getHostName() and RecordedRequest.requestUrl which contains a hostname involving a reverse dns lookup.

**Comment by yschimke** [comment]
This is currently failing the Windows CI jobs, hence the urgency.

**Comment by swankjesse** [comment]
I believe this is fixed here:
https://github.com/square/okhttp/pull/6919
