### ISSUE TITLE
missing filename. request should include a content-disposition header with a filename parameter

### ISSUE THREAD

**Issue by karelantonio** [square/okhttp#6815]
Hi, using a Multipart Body I received a unexpected error from the server:
```
missing filename. request should include a content-disposition header with a filename parameter
```
```
...
Request.Builder b =...
b.patch(new MultipartBody.Builder()
          .addFormDataPart("a", "b")
          .addFormDataPart("c", "d")
          .build()
          );
b.build();
...
```
Sorry if the code is not accurate, I didn't check before post this, anyway this is a simple code
Did anyone knows How to fix this? Or what I did wrong?

**Comment by yschimke** [comment]
See documentation https://square.github.io/okhttp/recipes/#posting-a-multipart-request-kt-java

Please use stackoverflow for such usage questions in future, the issue tracker is really only for bug reports.
