### ISSUE TITLE
Update snapshot and release publishing after gradle 7 upgrade

### ISSUE THREAD

**Issue by yschimke** [square/okhttp#6821]
Need to use similar approach to okio, replacing uploadArchives with publish.  Currently blocked on signing key.

See okio for modern config https://github.com/square/okio/blob/079c09ea4c5b7dea947596debc478efd26d36922/buildSrc/src/main/kotlin/okio-publishing.gradle.kts

**Comment by Goooler** [comment]
I think we can upgrade Dokka 1.5.0 with this change.

**Comment by yschimke** [comment]
I'm not sure these are related, think they can land separately.

Previous exploration which was blocked at the time, hopefully we can crib the config from similar square projects

https://github.com/square/okhttp/issues/6450
https://github.com/Kotlin/dokka/issues/1592 (fixed)
https://github.com/square/okhttp/pull/6342

**Comment by Goooler** [comment]
I've converted all gradle files to kts but root `build.gradle`, hopefullly to convert it after this.

**Comment by Goooler** [comment]
May refer to [kotlinpoet](https://github.com/square/kotlinpoet) (with latest [gradle-maven-publish-plugin](https://github.com/vanniktech/gradle-maven-publish-plugin) and `Dokka`), which I think it's better than okio.

**Comment by yschimke** [comment]
@Goooler whats the current best advice for this? You seem to have a clearer idea than I do.

**Comment by Goooler** [comment]
It seems like publishing to mavenLocal is ok.

![image](https://user-images.githubusercontent.com/10363352/143808543-8a20adb7-7bb5-4a21-8dc1-4e893c5a3554.png)

**Comment by Goooler** [comment]
Just copy publishing artifacts & website job from okio, anything we left ?

**Comment by Goooler** [comment]
@yschimke Should we add github cache actions on CI? See https://github.com/actions/cache
