### ISSUE TITLE
OAuth2 Support

### ISSUE THREAD

**Issue by surapuramakhil** [square/okhttp#6826]
Start by telling us what problem you’re trying to solve. Often a solution already exists!

There is a lot of adoption of oauth2. Lot of server relies on/build with oauth2 for authorization & authorization is underneath of oauth2 mechanism. Earlier, okhttp had plugin/works-with "okhttp-signpost" it hasn't become strong weather component, and it's no more live.

https://github.com/pakerfeldt/okhttp-signpost/issues/21 

Don’t send pull requests to implement new features without first getting our support. Sometimes we leave features out on purpose to keep the project small.

**Comment by yschimke** [comment]
This is out of scope for OkHttp.  Trust me, you really don't want this to be a core part of OkHttp.  We have a slow methodical release process and try to maintain API stability.  This sort of additional functionality is much better as an optional library that can release on it's own schedule, and have whatever features are needed for users who adopt it.
