### ISSUE TITLE
OKHttp client to support Keystore and Trustore (.p12 .jks) file within its API

### ISSUE THREAD

**Issue by patpatpat123** [square/okhttp#6848]
Hello okhttp team,

First of all, wanted to say big thanks for this cool project.
I have been using it for a while now, and it is very easy to use, easy to understand, thanks a lot!

Now, I am using okhttpclient, to another server.
This another server, which I do not control, will perform client certificate validation, meaning, this other server will look at the content, OU field, CN field of my client certificate.

What I have in my program is a ready keystore.p12 file and a ready truststore.p12 file.

Other http clients have in the api a direct possibility to use the files.

I have looked at the okhttp-ssl, and it is not about self signed certificate, localhost, etc, I have some real  keystore.p12 and truststore.p12 files.

Also, since they are here, I would like to avoid having to code the private key etc as code. Also would like to avoid having to open/extract the files again in the code.

Therefore, I was hoping okhttp could allow to so something similar to this:

```
try {
            final Path     keystorePath = Paths.get(keyStorePath);
            final KeyStore keyStore     = KeyStore.getInstance(keyStoreType);
            try (InputStream keyStoreFile = Files.newInputStream(keystorePath)) {
                String keyStorePassPhrase;
                keyStore.load(keyStoreFile, keyStorePassPhrase.toCharArray());
            }
            final KeyManagerFactory keyManagerFactory = KeyManagerFactory.getInstance(KeyManagerFactory.getDefaultAlgorithm());
            keyManagerFactory.init(keyStore, keyPassPhrase.toCharArray());

            final Path     truststorePath = Paths.get(trustStorePath);
            final KeyStore trustStore     = KeyStore.getInstance(keyStoreType);
            try (InputStream trustStoreFile = Files.newInputStream(truststorePath)) {
                trustStore.load(trustStoreFile, trustStorePassPhrase.toCharArray());
            }
            final TrustManagerFactory trustManagerFactory = TrustManagerFactory.getInstance(TrustManagerFactory.getDefaultAlgorithm());
            trustManagerFactory.init(trustStore);

            SslContext sslContext = SslContextBuilder.forClient().keyManager(keyManagerFactory).trustManager(trustManagerFactory).build();
            OkHttpClient okHttpClient = OkHttpClient.Builder()
                    .sslContect(sslContext)
                    .build();
```

or 

```
         OkHttpClient okHttpClient = OkHttpClient.Builder()
                    .keyManager(keyManagerFactory)
                    .trustManager(trustManagerFactory)
                    .build();
```

Could you please kindly consider this enhancement request where okhttp uses the keystore and truststore files directly please?

Thank you

**Comment by yschimke** [comment]
This space is so broad that we've focused on making a few use cases simple and safe.  Like loading from local files (pem format), or generating self signed certificates.  

You can use the libraries in okhttp-tls to load from locally stored certificates, you will need to read the file into a string but that is basically a one liner.  You would need to convert the certificate files.  The docs for okhttp-tls https://github.com/square/okhttp/blob/master/okhttp-tls/README.md show examples for loading a private key and intermediate certificate chain (heldCertificate) as well as trusting server certificates (addTrustedCertificate).  More sample code in https://github.com/square/okhttp/blob/master/samples/guide/src/main/java/okhttp3/recipes/CustomTrust.java 

That is the easy path for most app developers.

But basically once you are at the point that you have your own certificate setup and know exactly how you want to create the SslContext and TrustManager, then you probably don't need us to write that code.  You can maintain that yourself and just provide it to the OkHttpClient.

**Comment by patpatpat123** [comment]
Thanks @Yuri!
