### ISSUE TITLE
okhttp integration with tracing

### ISSUE THREAD

**Issue by patpatpat123** [square/okhttp#6849]
Hello okhttp Team,

May I ask for an enhancement request, to include trace identifiers in okhttp client please?

This would be very helpful for overall systems to system calls, having the possibility for open tracing etc.
For instance as of now, when using okhttp client to send a request:
```
        final RequestBody body = RequestBody.create("{\"key\": \"value\"}", MediaType.parse("application/json; charset=utf-8"));
        final Request request = new Request.Builder()
                .url("https://some-url")
                .addHeader("Content-Type", "application/json")
                .post(body)
                .build();
```

and in order to add tracing (since I am the client) I would need to manually add something like this:

```
                .addHeader("X-B3-TraceId", "47c8ff31719875aa")
```
or
```
                .addHeader("X-B3-TraceId", generateTraceId())

```

A nice feature would be with an option, or directly when importing a jar, to have the trace / span and parent included.

Thank you

**Comment by swankjesse** [comment]
Can you do this with an interceptor?

**Comment by yschimke** [comment]
I don't think we should integrate one particular standard here, even if the industry is converging.  As @swankjesse says you can use an interceptor.

We'd be essentially competing with libraries like these

https://github.com/openzipkin/brave/blob/master/instrumentation/okhttp3/src/main/java/brave/okhttp3/TracingInterceptor.java
https://github.com/opentracing-contrib/java-okhttp/blob/master/opentracing-okhttp3/src/main/java/io/opentracing/contrib/okhttp3/TracingInterceptor.java

And they are the rightful experts to do this right.

**Comment by patpatpat123** [comment]
Understood, thanks! Closing.

(Just asking are you guys aware of any project where the interceptor is used please?  It is a new concept for me, and having some example would help in the understanding)

**Comment by yschimke** [comment]
This is a sample I found via a codesearch for the opentracing interceptor

https://sourcegraph.com/github.com/opentracing-contrib/java-opentracing-walkthrough/-/blob/microdonuts/src/main/java/com/otsample/api/KitchenConsumer.java

Adding an interceptor is one line, but generally you want to understand how to correctly setup the tracing.  There are generally three aspects there, 1) sending the tracing headers in the request, 2) hooking into call lifecycle events to record some tracing data for the request, 3) publishing the call trace data to the tracing server.  These should be done following the instructions for the tracing library you use, not something we can help with.
