### ISSUE TITLE
 java.lang.IndexOutOfBoundsException  Glide version 4.12.0

### ISSUE THREAD

**Issue by KingShing** [square/okhttp#6851]
`# OkHttp Dispatcher(17924)

java.lang.IndexOutOfBoundsException

Index: 0, Size: 0

解析原始
1
java.util.ArrayList.remove(ArrayList.java:503)
2
java.util.Collections$SynchronizedList.remove(Collections.java:2470)
3
cn.futu.component.glide.glideimageview.progress.ProgressManager$2.void onProgress(java.lang.String,long,long,boolean,com.bumptech.glide.load.engine.GlideException)(ProgressManager.java:58)
4
cn.futu.component.glide.glideimageview.progress.ProgressManager$1.okhttp3.Response intercept(okhttp3.Interceptor$Chain)(ProgressManager.java:38)
5
okhttp3.internal.http.RealInterceptorChain.okhttp3.Response proceed(okhttp3.Request,okhttp3.internal.connection.StreamAllocation,okhttp3.internal.http.HttpCodec,okhttp3.internal.connection.RealConnection)(RealInterceptorChain.java:147)
6
okhttp3.internal.connection.ConnectInterceptor.okhttp3.Response intercept(okhttp3.Interceptor$Chain)(ConnectInterceptor.java:45)
7
okhttp3.internal.http.RealInterceptorChain.okhttp3.Response proceed(okhttp3.Request,okhttp3.internal.connection.StreamAllocation,okhttp3.internal.http.HttpCodec,okhttp3.internal.connection.RealConnection)(RealInterceptorChain.java:147)
8
okhttp3.internal.http.RealInterceptorChain.okhttp3.Response proceed(okhttp3.Request)(RealInterceptorChain.java:121)
9
okhttp3.internal.cache.CacheInterceptor.okhttp3.Response intercept(okhttp3.Interceptor$Chain)(CacheInterceptor.java:93)
10
okhttp3.internal.http.RealInterceptorChain.okhttp3.Response proceed(okhttp3.Request,okhttp3.internal.connection.StreamAllocation,okhttp3.internal.http.HttpCodec,okhttp3.internal.connection.RealConnection)(RealInterceptorChain.java:147)
11
okhttp3.internal.http.RealInterceptorChain.okhttp3.Response proceed(okhttp3.Request)(RealInterceptorChain.java:121)
12
okhttp3.internal.http.BridgeInterceptor.okhttp3.Response intercept(okhttp3.Interceptor$Chain)(BridgeInterceptor.java:93)
13
okhttp3.internal.http.RealInterceptorChain.okhttp3.Response proceed(okhttp3.Request,okhttp3.internal.connection.StreamAllocation,okhttp3.internal.http.HttpCodec,okhttp3.internal.connection.RealConnection)(RealInterceptorChain.java:147)
14
okhttp3.internal.http.RetryAndFollowUpInterceptor.okhttp3.Response intercept(okhttp3.Interceptor$Chain)(RetryAndFollowUpInterceptor.java:126)
15
okhttp3.internal.http.RealInterceptorChain.okhttp3.Response proceed(okhttp3.Request,okhttp3.internal.connection.StreamAllocation,okhttp3.internal.http.HttpCodec,okhttp3.internal.connection.RealConnection)(RealInterceptorChain.java:147)
16
okhttp3.internal.http.RealInterceptorChain.okhttp3.Response proceed(okhttp3.Request)(RealInterceptorChain.java:121)
17
cn.futu.component.glide.module.ReportInterceptor.okhttp3.Response intercept(okhttp3.Interceptor$Chain)(ReportInterceptor.java:57)
18
okhttp3.internal.http.RealInterceptorChain.okhttp3.Response proceed(okhttp3.Request,okhttp3.internal.connection.StreamAllocation,okhttp3.internal.http.HttpCodec,okhttp3.internal.connection.RealConnection)(RealInterceptorChain.java:147)
19
okhttp3.internal.http.RealInterceptorChain.okhttp3.Response proceed(okhttp3.Request)(RealInterceptorChain.java:121)
20
okhttp3.RealCall.okhttp3.Response getResponseWithInterceptorChain()(RealCall.java:200)
21
okhttp3.RealCall$AsyncCall.void execute()(RealCall.java:147)
22
okhttp3.internal.NamedRunnable.void run()(NamedRunnable.java:32)
23
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
24
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
25
java.lang.Thread.run(Thread.java:764)
`

**Comment by yschimke** [comment]
This seems like an issue for Glide or the cn.futu app developers.
