### ISSUE TITLE
4.9.1 jar does not exists in maven repo

### ISSUE THREAD

**Issue by bonythomas-sof** [square/okhttp#6852]
Good bug reports include a failing test! Writing a test helps you to isolate and describe the problem, and it helps us to fix it fast. Bug reports without a failing test or reproduction steps are likely to be closed.

Here’s an example test to get you started.
https://gist.github.com/swankjesse/981fcae102f513eb13ed

http://maven.owfg.com/nexus/content/groups/public/com/squareup/okhttp3/okhttp/4.9.1/

My Build is failing as it complains that the Jar file is missing from the above location. Please build and publish the Jar to maven repo

**Comment by JakeWharton** [comment]
This project releases to Maven central at https://repo1.maven.org/maven2/com/squareup/okhttp3/okhttp/4.9.1/. If I had to guess you're looking at a read-through proxy that only contains artifacts once they're requested.
