### ISSUE TITLE
javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.

### ISSUE THREAD

**Issue by vanniktech** [square/okhttp#6854]
For the following url:

https://www.premar-atlantique.gouv.fr/avis/rss/AVIRAD?format=rss

when using okhttp I get a:

```
javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
```

The weird thing is that on my Desktop's Chrome browser everything works fine:

<img width="462" alt="Screenshot 2021-09-11 at 11 04 41" src="https://user-images.githubusercontent.com/5759366/132942616-4ca98644-7713-4365-805f-26b3cc1118b6.png">

When I open the exact same url on the same phone using Google Chrome it's also fine:

![android_screenshot_1631351180](https://user-images.githubusercontent.com/5759366/132942655-ce78dff0-0133-4be7-9e30-c4fe704fb44c.png)

---

Why can't my application request that RSS site and get the content?

This is my HTTP Client:

```kotlin
private val okHttpClient by lazy(NONE) {
  val interceptor = HttpLoggingInterceptor { message ->
    Timber.tag("Http").v(message)
  }
  interceptor.level = BODY

  val userAgent = object : Interceptor {
    override fun intercept(chain: Chain): Response {
      return chain.proceed(chain.request()
        .newBuilder()
        .header("User-Agent", "com.vanniktech.rssreader:${BuildConfig.VERSION_NAME}")
        .build())
    }
  }

  OkHttpClient.Builder()
      .cache(Cache(cacheDir, 200_000_000))
      .addInterceptor(interceptor)
      .addNetworkInterceptor(userAgent)
      .hostnameVerifier { _, _ -> true } // Allow every website.
      .authenticator(object : Authenticator {
        override fun authenticate(
          route: Route?,
          response: Response,
        ): Request? {
          if (response.request.header("Authorization") != null) {
            return null // Give up, we've already attempted to authenticate.
          }

          // To support urls such as https://74845:99424@secret-rss.club/shows/123512/feed
          val url = response.request.url
          val username = url.username.takeIf { it.isNotBlank() }
          val password = url.password.takeIf { it.isNotBlank() }

          return when {
            username != null && password != null -> response.request.newBuilder()
              .header("Authorization", Credentials.basic(username, password))
              .build()
            else -> null
          }
        }
      })
      .build()
}
```

**Comment by yschimke** [comment]
Please use stackoverflow for these types of usage questions.  We can't provide personalized support given the various legitimate ways that HTTPS can fail without it being an OkHttp bug.

If you can create a reproduction of a bug, then please reopen.

Also sites like https://www.ssllabs.com/ssltest/analyze.html?d=premar%2datlantique.gouv.fr&latest, which suggests it is serving an incomplete chain.
