### ISSUE TITLE
Missing module-info.java in okhttp-urlconnection

### ISSUE THREAD

**Issue by igouss** [square/okhttp#6857]
error: module okhttp3.urlconnection reads package okhttp3 from both okhttp3 and okhttp3.urlconnection

https://stackoverflow.com/questions/62758635/split-package-okhttp3-errors-out-build-if-okhttp-urlconnection-dependency-adde

**Comment by yschimke** [comment]
Not sure we have an easy fix for this.  If you are using Authenticator you can use okhttp.Authenticator.JAVA_NET_AUTHENTICATOR directly.

Not sure about JavaNetCookieJar.

**Comment by igouss** [comment]
OK, thank you. With Java 17 LTS released, I think it is time to add module support.

**Comment by yschimke** [comment]
@igouss What's your request here?  Something more than Automatic-Module-Name? Or that we fix okhttp-urlconnection to support JavaNetCookieJar?

**Comment by igouss** [comment]
Well, I've tried to use latest Java, but it seems that they broke everything with the strict module support. I'm still on JVM 11, so I don't 100% know why my app does not work, but with JVM 16/17 I get a lot of errors related to modules. Such as when two jars have files with the same namespace or when jar has no module-info.java.

I'm not 100% sure what I'm need from you ;-) (that's why i've closed the ticket), JDK 17 compatibility of some sort i guess.

**Comment by yschimke** [comment]
The most effective workaround now is probably to copy JavaNetCookieJar into your repository and drop the dependency on okhttp-urlconnection

**Comment by swankjesse** [comment]
Tracking here.
https://github.com/square/okhttp/issues/4184
