### ISSUE TITLE
Deprecated method used in README.md

### ISSUE THREAD

**Issue by gstaykov** [square/okhttp#6859]
`RequestBody.Companion.create(json, JSON);` is deprecated but it is used in the example POST request in the README.md: 
```java
public static final MediaType JSON
    = MediaType.get("application/json; charset=utf-8");

OkHttpClient client = new OkHttpClient();

String post(String url, String json) throws IOException {
  RequestBody body = RequestBody.Companion.create(json, JSON);
  Request request = new Request.Builder()
      .url(url)
      .post(body)
      .build();
  try (Response response = client.newCall(request).execute()) {
    return response.body().string();
  }
}
```

I have tried everything from here https://stackoverflow.com/questions/57100451/okhttp3-requestbody-createcontenttype-content-deprecated but without success. I can not find working solution for JAVA 16 Only the deprecated method works for me.

I'm using okhttp client with maven like this:
```
<dependency>
	<groupId>com.squareup.okhttp3</groupId>
	<artifactId>okhttp</artifactId>
	<version>4.9.1</version>
</dependency>
```

**Comment by yschimke** [comment]
That method is not deprecated, the form with swapped parameter order is. See this edit to the post example

<img width="524" alt="image" src="https://user-images.githubusercontent.com/231923/133200811-a2746987-aa67-4535-837d-6e04b1dd1952.png">

For kotlin, it actually directs to 

```
    val rb = "{}".toRequestBody("application/json".toMediaTypeOrNull())
```

**Comment by gstaykov** [comment]
This solution is proposed in the stackoverflow question that I have sent above and as I said I have tried every solution from there and nothing works. Try to execute this code with JAVA 16 (openjdk-16). I get the following exception:

```
java.lang.NoSuchMethodError: 'okhttp3.RequestBody okhttp3.RequestBody.create(java.lang.String, okhttp3.MediaType)'
```

**Comment by yschimke** [comment]
You must be using an old version in your classpath.  Check the resolved dependencies in your build.

**Comment by gstaykov** [comment]
Yes you are correct. I'm using spring with spring boot parent pom and the version of the okhttp dependecy was getting overwritten. However the README.md still uses the deprecated version I will create pull request to replace `RequestBody.create(JSON, json)` with `RequestBody.create(json, JSON)`. Thanks :)
