### ISSUE TITLE
Websocket Secure(WSS) Authentication

### ISSUE THREAD

**Issue by baldhead69** [square/okhttp#6860]
Hi,

I am developing a websocket secure server in a iot device(esp32).

I already use a simple android app(for now) with OKHTTP websocket client(ws or wss).

I am trying to put a login(users and admin) in my Websocket Secure Server.

I am searching for a "full" secure method to iot authentication, maybe "Mutual authentication".

I want to use https/wss in the server and i'm in doubt how to acomplish the authentication.

Maybe login in the server before handshake is finished, ie, https, and if login is ok, switch to wss protocol. When the connection open the protocol is https at first and after switch to websocket( i dont know if used in this way the same socket can be kept, before and after login).

Some suggestion are welcome.

Thank's.

**Comment by yschimke** [comment]
Please ask questions like this on stackoverflow.  It builds a public knowledgebase, and we only use this issue tracker for confirmed bug reports.

OkHttp supports HTTPS for WebSockets, so this is a general usage question, not a feature request or bug report as I understand it.

**Comment by baldhead69** [comment]
This is not related with this ?

https://github.com/square/okhttp/issues/6454

https://github.com/square/okhttp/issues/4321

**Comment by yschimke** [comment]
TLS/WSS and Mutual Authentication (client authenticating from PKI) at the transport layer is unrelated to app level authentication via "Authorization" headers or 401 handling and Authenticator's.

You can have neither or both.  You could decide to use WSS (TLS + HTTP/1.1) and combine it with preemptively sending a "Authorization" header.

**Comment by baldhead69** [comment]
> You could decide to use WSS (TLS + HTTP/1.1) and combine it with preemptively sending a "Authorization" header.

I think this way is enough. Does not need mutual authentication. Only a basic http authentication over tls.

But it is websocket, and there is a protocol switching from https to websocket, so i have doubts whether authentication occurs before(https) or after(wss) protocol switching (ie, handshake is finished).

The server also needs to support this https/wss "basic authentication", and i'm not sure if it does "in background" or is there any way to implement this in the "server user code implementing" area.
