### ISSUE TITLE
Unsatisfiable Request (only-if-cached) in offline

### ISSUE THREAD

**Issue by peterpp** [square/okhttp#6866]
Cached response is not reachable when offline (OkHttp 4.9.1).

Steps:
1) Device is online, basic GET request.
```java
Request.Builder builder = new Request.Builder()
        .url(url)
        .header("Accept", "application/json")
        .header("Accept-Charset", "utf-8")
        .build();
```

Response 200 with relevant HTTP headers:
```
Cache-Control: max-age=0
ETag: 163234628770774
```
Header `Pragma` or other caching headers are not present in response.

2) Online. Try to get cached response without validating.
```java
Request.Builder builder = new Request.Builder()
        .url(url)
        .cacheControl(new CacheControl.Builder()
                .onlyIfCached()
                .maxStale(90, TimeUnit.DAYS)
                .build())
        .build();
```

Response 200 is returned. Object `Response` has variable `cacheResponse` filled, `networkResponse` is `null`. Response contains additional HTTP header `Warning: 110 HttpURLConnection "Response is stale"`. So everything as expected so far.

3) Switch the device to offline and repeat request from step 2.

Response 504 Unsatisfiable Request (only-if-cached) is returned. And that's the problem. I believe there should be no difference and cached response should be available. The purpose of `only-if-cached` request is to avoid network connection. `max-stale` is used to say that an old response is still OK.

**Comment by yschimke** [comment]
Can you run both cases with an event listener https://square.github.io/okhttp/events/ and https://square.github.io/okhttp/4.x/okhttp/okhttp3/-event-listener/

I'd love to the see the full flow of connection and cache events, including whether it's reusing a connection from online attempt in the second. 

Thanks

**Comment by peterpp** [comment]
Here are the events:

Online attemp:
```
callStart
cacheHit
callEnd
```

Offline attempt:
```
callStart
satisfactionFailure
callEnd
```

The documantation for `satisfactionFailure` says:

> Invoked when a call fails due to cache rules. For example, we’re forbidden from using the network and the cache is insufficient

So, I don't understand why the cache is insufficient while offline, but sufficient while online. Is there a way to get the real reason somehow?

**Comment by peterpp** [comment]
Ohhhh, I've just found the reason. The URL is a little bit different in offline mode and I overlooked it 🙈🤦‍♂️
My bad, sorry for the noise.
