### ISSUE TITLE
Let `followRedirects()` take a `Predicate`

### ISSUE THREAD

**Issue by tajakobsen** [square/okhttp#6871]
I would like `followRedirects()` to have an overload where it can take a `java.util.function.Predicate`, with the `location` as the predicates parameter.

I have a usecase where I only want to follow the redirect if the `location` header is to my own server. And I think the proposal above would be a really clean and nice solution.

**Comment by yschimke** [comment]
We have a high bar to change public API like this.  In this case you can implement this with a workaround using an interceptor.

Either

a) network interceptor interrupt the normal redirect by changing headers.
b) possibly cleaner, disable redirects, but implement your own follow up request in the application interceptor.

**Comment by swankjesse** [comment]
I think it's much simpler to do this in a NetworkInterceptor. Remove the server’s `Location` response header if you don't want to redirect. You can add it back as say `Original-Location` if you need it. If you want to preserve everything you can even change things back to how they were in a 2nd application interceptor.
