### ISSUE TITLE
Looking for your KEYS.TXT file

### ISSUE THREAD

**Issue by rodwiddowson** [square/okhttp#6874]
I'm calling this a feature request..

It turns out that `okhttp`, `okio` and `retrofit` are part of the general collection of jars that maven pulls down when it is booting itself.  I could do the analysis if it interests you.

I am looking for the following keys used to sign the following artifacts in maven central.
`0x8671A8DF71296252` for `com.squareup.okhttp3:okhttp:3.12.0` and `com.squareup.okio:okio:1.15.0`
`0xE0CB7823CFD00FBF` for `com.squareup.retrofit2:retrofit:2.5.0`

I was hoping to see a KEYS.TXT at the top level of one of these projects but I have missed it (or perhaps in @swankjesse 's space)

Thanks

Rod

**Comment by rodwiddowson** [comment]
Actually I might be wrong - it could be eclipse that brings it down., not maven itself

**Comment by yschimke** [comment]
Not clear we can help here, I assume it's a private key for @swankjesse - but I'm out of my depth here.  But I don't think we are actively addressing this issue.

**Comment by swankjesse** [comment]
We're migrating this project and others to release on GitHub actions via a Square-wide key. We can make its information available.

**Comment by swankjesse** [comment]
@rodwiddowson how do tools consume this information? If we rotate our keys again (as we did with the recent TravisCI incident), does that break everything?

**Comment by swankjesse** [comment]
(got a link to another project that publishes their keys? Also perhaps a spec?)

**Comment by swankjesse** [comment]
Some samples I found. I definitely prefer we publish a very small set of keys owned by our CI system instead the keys of every releaser. Yuck!
https://github.com/eclipse/jetty.project/blob/jetty-10.0.x/KEYS.txt
https://downloads.apache.org/commons/KEYS
https://downloads.apache.org/logging/KEYS

**Comment by rodwiddowson** [comment]
@swankjesse Thanks for reaching out to me,
> how do tools consume this information? 
Our tool (it's a maven enforcer plugin) is looking at detecting supply chain attacks.  Mostly we use it to ensure that any jars that we ship (i.e. our code's dependencies, usually downloaded from maven central) have been signed by a verified (by us) keyring (we have one keyring per maven group).  

There is secondary effort under way to use the same technology to walk over a maven repository making the same checks.  The attack we are mitigating against here are forged plugins which then disrupt the artifacts we create (rather than the ones we package).  This is a much harder task particularly in a development environment (have you see how much antique code is downloaded by some maven plugins?); but we do have it enabled for our important CI builds.

(IIRC) where okhttp comes in is for developers

Anyway..

> If we rotate our keys again (as we did with the recent TravisCI incident), does that break everything?
I would hope so!  We really need to know that a signing key has changed.  OTOH if okhttp is only used in a development environment we not be seeing it right now.

We are still developing our processes to deal with key changes, but if a one is detected we reach out to the person or team in question and look for some out of band "validation" (where that terms is intentionally left undefined) that this is an expected change.  We do not expect keys to change frequently and we believe that the cost of doing validation after a key change is more than balanced by the knowledge that we are not inadvertently becoming part of a supply chain attack.

> I definitely prefer we publish a very small set of keys owned by our CI system instead the keys of every releaser. Yuck!
Me too - although I have picked out individual keys from such locations when i was boot strapping the process by "grandfathering" in keys ("we have trusted this jar unverified to date with no signature checking, therefore we have implicitly trusted the key that signed it"),

Thanks once again.

Rod

**Comment by swankjesse** [comment]
Is there a standard format for keys in repos? It'd be nice to automate the heck out of this. As a repo owner I wanna be alerted when keys are added, when new keys are used to publish artifacts, and when an artifact’s key changes. Something machine- and human-readable like JSON or markdown would be nice.

**Comment by rodwiddowson** [comment]
We use old style GPG keyring - because thats what BouncyCastle (the library we use to check signatures with) accepts.

The code can also be persuaded to just a consume a concatenated list of asc files (as per those downloads you found) - this is the usual way of distributing keys since you can then pick out exactly the one you want with a text editor and import it into your keyring.  In our case: ```gpg --no-default-keyring --keyring ./com.squareup.okhttp3.gpg  --import foo.asc``` does the work

**Comment by swankjesse** [comment]
Our official key is here:
https://keyserver.ubuntu.com/pks/lookup?search=opensource%40squareup.com&fingerprint=on&hash=on&op=index

I would prefer to not post them on GitHub, as GitHub already has custody of our private signing key. To defend against an attacker’s signature, it’s best to verify with a key from a different source.

I will post a link to Ubuntu’s copy of our key on our security page.

**Comment by swankjesse** [comment]
Obligatory blog post of stuff I did in the process of working on this issue.
https://publicobject.com/2022/02/26/manually-verify-maven-artifacts/
