### ISSUE TITLE
`Function invocation 'encodedPath()' expected`

### ISSUE THREAD

**Issue by ColtonIdle** [square/okhttp#6879]
Started seeing this in my IDE. Not sure if it's because of studio updates or okhttp updates. I'm going to look into it more, but figured I'd post it here to see if this is expected/known.
<img width="717" alt="Screen Shot 2021-10-12 at 11 39 45 AM" src="https://user-images.githubusercontent.com/31751141/136987231-0e04542a-3c73-4342-b23e-5dc45e9f603d.png">

**Comment by yschimke** [comment]
Can you expand the screenshot? The javadoc looks wrong and I'd like to see the version number of the dependency at least.

<img width="612" alt="image" src="https://user-images.githubusercontent.com/231923/137073988-2dcc0d55-9c87-42d4-8979-f7e20b67c4f8.png">
