### ISSUE TITLE
3.12.12 BOM references invalid okhttp-logging-interceptor coordinate

### ISSUE THREAD

**Issue by nfisher** [square/okhttp#6880]
When using the 3.12.12 BOM it's necessary to manually specify the version for logging-interceptor as the BOM published references the coordinate `com.squareup.okhttp3:okhttp-logging-interceptor` which is not published in maven central. It appears to be fixed in 4.x of OkHttp but would be nice to backport the fix to 3.12.12.

**Comment by yschimke** [comment]
Waiting on a high priority fix on 3.12.x for a release.

**Comment by swankjesse** [comment]
Unlikely we’ll do another 3.x release.
