### ISSUE TITLE
java.lang.ClassNotFoundException: kotlin.jvm.internal.markers.KMappedMarker

### ISSUE THREAD

**Issue by a33a3touesa** [square/okhttp#6885]
I get the following error:
```
MapOutputTracketMasterEndpoint stopped!
Caused by: java.lang.ClassNotFoundException: kotlin.jvm.internal.markers.KMappedMarker
```
Only by running:
```
OkHttpClient client = new OkHttpClient();
```
I'm running an Apache Spark job and this command shuts the job down for some reason.

**Comment by yschimke** [comment]
There isn't anything we can help you with here.  It is likely an issue with classloaders, your build or how jobs are launched in Spark.

I suggest asking a question on stackoverflow with a reproduction.  

As a workaround you could try downgrading to OkHttp 3.12.x.  It would at least tell you whether it's a kotlin specific issue or if you hit an issue with okio missing (another dependency).
