### ISSUE TITLE
no check for LinkProperties.getPrivateDnsServerName() on Android

### ISSUE THREAD

**Issue by eighthave** [square/okhttp#6889]
Android API 28 added two important new methods for apps/libraries that do their own DNS.  Since OkHTTP supports handling the DNS, it should use these methods to respect the user's private DNS settings:

* [LinkProperties.getPrivateDnsServerName()](https://developer.android.com/reference/android/net/LinkProperties#getPrivateDnsServerName())
* [LinkProperties.isPrivateDnsActive()](https://developer.android.com/reference/android/net/LinkProperties#isPrivateDnsActive())

The docs provide more info:
> Returns the private DNS server name that is in use. If not null, private DNS is in strict mode. In this mode, applications should ensure that all DNS queries are encrypted and sent to this hostname and that queries are only sent if the hostname's certificate is valid. If null and isPrivateDnsActive() is true, private DNS is in opportunistic mode, and applications should ensure that DNS queries are encrypted and sent to a DNS server returned by getDnsServers(). System DNS will handle each of these cases correctly, but applications implementing their own DNS lookups must make sure to follow these requirements.

Searching the OkHTTP code base returns no results for either `getPrivateDnsServerName` or `isPrivateDnsActive`.  This issue becomes much more important when ECH https://github.com/square/okhttp/issues/6539#issuecomment-946164036 is in use because unencrypted DNS would be the only leak of key metadata like the domain name.

FYI @yschimke

**Comment by eighthave** [comment]
I just found out that Apple has implemented a good system in iOS/macOS for handling all the issues around DNS here. Apple supports DoT & DoH system-wide a well as per-domain (HTTPS RR) and per-app resolver settings.  This is the priority order for how Apple decides which resolver to use for a given query:

1. Resolution of captive portal test zones using the network provided DNS resolver
2. VPN or DNS proxy configurations and DNS resolvers set by enterprise policies
3. System wide encrypted resolvers configured directly by device owners
4. Encrypted resolvers designated by domain owners (DNS [HTTPS/SVCB](https://www.ietf.org/archive/id/draft-ietf-dnsop-svcb-https-07.html) RR Type)
5. Encrypted resolver designated by apps
6. Unencrypted resolvers (e.g., resolvers specified via DHCP or RA)

* https://support.opendns.com/hc/en-us/articles/360049861971-DNS-Resolver-Selection-in-iOS-14-and-macOS-11
* https://developer.apple.com/forums/thread/663371
* https://mailarchive.ietf.org/arch/msg/add/MbOOWPVHRHM_wvbKhfHuzUTwimI/

**Comment by yschimke** [comment]
Going to close this out, I'd love to provide samples for people to use, but as @swankjesse says "I think it's potentially hazardous for OkHttp to do anything automatic here."

But if we can show there is a clear improvement, especially with ECH, we can review the samples.
