### ISSUE TITLE
StringIndexOutOfBoundsException on JavaNetCookieJar.java:103 - when the value contains only one double quote

### ISSUE THREAD

**Issue by usenbekov** [square/okhttp#6897]
okhttp_3.12.x
JavaNetCookieJar.java (https://github.com/square/okhttp/blob/okhttp_3.12.x/okhttp-urlconnection/src/main/java/okhttp3/JavaNetCookieJar.java)
Line: 103

```
if (value.startsWith("\"") && value.endsWith("\"")) {
  value = value.substring(1, value.length() - 1);
}
```

Fails when the value contains only one double quote ("), because the length of the value=1, but it tries to substring with the startIndex=1

**Comment by viljark** [comment]
Looking forward for the fix to be released, do I understand that all of the versions are still affected by this issue?

**Comment by yschimke** [comment]
No planned release of 3.12.x
