### ISSUE TITLE
🙉Authenticator.athenticate() is always called with 401 code

### ISSUE THREAD

**Issue by tranminhhoainhan** [square/okhttp#6899]
Hi all,

    public Request authenticate(Route route, Response response) throws IOException {    
        String accessToken = refreshToken();
        return response.request().newBuilder().header("Authorization", "Bearer " + accessToken).build();
    }

My implementation is something like above. The weird this is that authenticate() always be called when test with real service. When test with mockserver, everything is oke, 
And postman test with real service is ok too (returned response is 200)

**Comment by yschimke** [comment]
This sort of usage question is best handled through something like stackoverflow.

Or please reopen with a reproducible test case, we can't take action with this report as is.
