### ISSUE TITLE
Constant  Dns.java line 5 errors on crashlytics

### ISSUE THREAD

**Issue by sarthakgandhidunzo** [square/okhttp#6901]
I have implemented my okhttp client as follows in my app: 

       fun getOkhttpClient(): OkHttpClient {
        val chuckerCollector = ChuckerCollector(
            context = MyApplication.appInstance!!,
            // Toggles visibility of the push notification
            showNotification = BuildConfig.DEBUG,
            // Allows to customize the retention period of collected data
            retentionPeriod = RetentionManager.Period.ONE_WEEK
        )

        // Create the Interceptor
        val chuckerInterceptor = ChuckerInterceptor.Builder(MyApplication.appInstance!!)
            // The previously created Collector
            .collector(chuckerCollector)
            // The max body content length in bytes, after this responses will be truncated.
            .maxContentLength(250_000L)
            .alwaysReadResponseBody(BuildConfig.DEBUG)
            .build()

        val executorService: ExecutorService =
            ThreadPoolExecutor(20, 20, 1, TimeUnit.HOURS, LinkedBlockingQueue())
        val myDispatcher = Dispatcher(executorService)

        return OkHttpClient.Builder()
            .connectTimeout(15000, TimeUnit.MILLISECONDS)
            .retryOnConnectionFailure(true)
            .readTimeout(60, TimeUnit.SECONDS)
            .writeTimeout(60, TimeUnit.SECONDS)
            .protocols(listOf(Protocol.HTTP_1_1))
            .addInterceptor(HeaderInterceptor())
            .addInterceptor(chuckerInterceptor)
            .dispatcher(myDispatcher)
            .apply {
                if (BuildConfig.DEBUG) {
                    val logging = HttpLoggingInterceptor()
                    logging.setLevel(HttpLoggingInterceptor.Level.BODY)
                    addInterceptor(logging)
                }
            }
            .build()
     }
 
1. Open the app for the first time everything works fine. 
2. Put the app in background for about 30 to 40 mins and come back to the app.
3. Call any api and it will give - 
`Non-fatal Exception: java.net.UnknownHostException
Unable to resolve host "host_url": No address associated with hostname
java.net.Inet6AddressImpl.lookupHostByName (Inet6AddressImpl.java:157)
java.net.Inet6AddressImpl.lookupAllHostAddr (Inet6AddressImpl.java:105)
java.net.InetAddress.getAllByName (InetAddress.java:1154)
okhttp3.Dns$Companion$DnsSystem.lookup (Dns.java:5)
okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress (RouteSelector.java:133)
okhttp3.internal.connection.RouteSelector.nextProxy (RouteSelector.java:20)
okhttp3.internal.connection.RouteSelector.next (RouteSelector.java:17)
okhttp3.internal.connection.ExchangeFinder.findConnection (ExchangeFinder.java:196)
okhttp3.internal.connection.ExchangeFinder.findHealthyConnection (ExchangeFinder.java)
okhttp3.internal.connection.ExchangeFinder.find (ExchangeFinder.java:47)
okhttp3.internal.connection.RealCall.initExchange$okhttp (RealCall.java:31)
okhttp3.internal.connection.ConnectInterceptor.intercept (ConnectInterceptor.java:11)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:166)
okhttp3.internal.cache.CacheInterceptor.intercept (CacheInterceptor.java:191)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:166)
okhttp3.internal.http.BridgeInterceptor.intercept (BridgeInterceptor.java:167)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:166)
okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept (RetryAndFollowUpInterceptor.java:34)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:166)
com.chuckerteam.chucker.api.ChuckerInterceptor.intercept (ChuckerInterceptor.java:9)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:166)
com.pharmasentinel.medsii.retrofit.HeaderInterceptor.intercept (HeaderInterceptor.java:37)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:166)
okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp (RealCall.java:113)
okhttp3.internal.connection.RealCall$AsyncCall.run (RealCall.java:51)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1167)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:641)
java.lang.Thread.run (Thread.java:764) `

`Caused by android.system.GaiException
android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
libcore.io.Linux.android_getaddrinfo (Linux.java)
libcore.io.BlockGuardOs.android_getaddrinfo (BlockGuardOs.java:172)
java.net.Inet6AddressImpl.lookupHostByName (Inet6AddressImpl.java:137)
java.net.Inet6AddressImpl.lookupAllHostAddr (Inet6AddressImpl.java:105)
java.net.InetAddress.getAllByName (InetAddress.java:1154)
okhttp3.Dns$Companion$DnsSystem.lookup (Dns.java:5)
okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress (RouteSelector.java:133)
okhttp3.internal.connection.RouteSelector.nextProxy (RouteSelector.java:20)
okhttp3.internal.connection.RouteSelector.next (RouteSelector.java:17)
okhttp3.internal.connection.ExchangeFinder.findConnection (ExchangeFinder.java:196)
okhttp3.internal.connection.ExchangeFinder.findHealthyConnection (ExchangeFinder.java)
okhttp3.internal.connection.ExchangeFinder.find (ExchangeFinder.java:47)
okhttp3.internal.connection.RealCall.initExchange$okhttp (RealCall.java:31)
okhttp3.internal.connection.ConnectInterceptor.intercept (ConnectInterceptor.java:11)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:166)
okhttp3.internal.cache.CacheInterceptor.intercept (CacheInterceptor.java:191)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:166)
okhttp3.internal.http.BridgeInterceptor.intercept (BridgeInterceptor.java:167)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:166)
okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept (RetryAndFollowUpInterceptor.java:34)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:166)
com.chuckerteam.chucker.api.ChuckerInterceptor.intercept (ChuckerInterceptor.java:9)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:166)
com.pharmasentinel.medsii.retrofit.HeaderInterceptor.intercept (HeaderInterceptor.java:37)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:166)
okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp (RealCall.java:113)
okhttp3.internal.connection.RealCall$AsyncCall.run (RealCall.java:51)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1167)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:641)
java.lang.Thread.run (Thread.java:764) 
`
Which i am logging from my interceptor using try catch.

4. Open any other app and they work fine.
5. Kill the app and restart resolves the problem, and sometimes switching between wifi and cellular also solves it.

**Comment by yschimke** [comment]
You should ask this sort of usage question on Stackoverflow.  The call that is failing is `InetAddress.getAllByName` which is a system method, not in our control.
