### ISSUE TITLE
POST Data using form builder with integer parameter

### ISSUE THREAD

**Issue by LordAvorio** [square/okhttp#6902]
Greetings everyone,

I Wanna ask a question,
I want POST data to API that have parameter with integer data type, I already convert my parameter request  that have integer value to string because Form Builder just accept String value.
But the server that I want to send expect integer value.
Is there any solution that I can use ?
The Server using header :  Content-Type : x-www-form-urlencoded;

Thank you

**Comment by zion223** [comment]
maybe you can ask your server developer  to accept string value, it's easy for them. Or

```java
    @FormUrlEncoded
    @POST("xxx/xxx")
    Call<Result> login(@Field("id") Integer id, @Field("name") String name);

```

**Comment by yschimke** [comment]
Please ask such questions on stackoverflow, we can't provide support like this, unless it's a reproducible bug.
