### ISSUE TITLE
mockwebserver should be startable after being shutdown

### ISSUE THREAD

**Issue by coopstah13** [square/okhttp#6906]
I use mockwebserver in a spock test where it is set up as `@Shared` so it is only initialized once per class. I would like to be able to write a test where I can first shutdown the server and then execute my code to verify the behavior when a connection is refused because the server is down. However to clean up for any downstream tests, I need to start the server again. Currently there is a check in start that checks to see if it is already "started" to disallow calling it twice. It seems to me that shutdown should clear the started flag, is there any downside to that? Are there any other things that need to be cleaned up to enable that as well?

**Comment by yschimke** [comment]
It is a very reasonable request.  But it seems like something you can probably work around in your test code, can you just adjust the URL between the two test runs with a url from a fresh MockWebServer?

There is a deliberate design choice to make MockWebServer single use.  If you look at MockWebServerRule (junit4) or MockWebServerExtension (junit5) you will see that is how they are implemented. Generally you should only use a mock webserver for a single test, but it seems that might be the scope of a single Spock class?

But making MockWebServer reusable might break assumptions users have, or that we have internally.  For instance, we start it automatically when certain operations are done, like reading the server url, and assign a port. It might be flaky if we reused the same port (not sure if we configure socket reuse).  We'd at least need to define how the QueueDispatcher behaves when it has some pending requests, things that we don't currently specify.

**Comment by swankjesse** [comment]
Is it possible to not shut it down in such cases?
