### ISSUE TITLE
why are all your examples not working

### ISSUE THREAD

**Issue by kaizer1** [square/okhttp#6908]
And the question is - why are all your examples not working? That is, everything. That is, both on the site and here - if you run them, there will be errors that need to be corrected, is this what was intended?

**Comment by yschimke** [comment]
Hey, can you be specific, starting with which ones are broken.  I tried both an online Recipe and a code in the sample project.  The sample project compiles fine and a ran a random one without issue.

Please reopen with more specifics, this is unactionable as is.
