### ISSUE TITLE
Url segments in baseUrl was removed

### ISSUE THREAD

**Issue by WilliamChen-luckbob** [square/okhttp#6909]
As I mentioned in [Retrofit issue](https://github.com/square/retrofit/issues/3658):

The baseUrl prefix was removed in okhttp3.HttpUrl.class line 1450.

![image](https://user-images.githubusercontent.com/58684828/141425392-581ad06e-b934-4ccb-9394-ba74349adf86.png)

My baseUrl was generated in this way:
```
//generated by other functions dynamically
strategy = "http";
gateway = "192.168.0.200:8080";
moduleName = "web-security";

//getting baseUrl ( at last it will be http://192.168.0.200:8080/web-security/)
String baseUrl = String.format("%s://%s/%s/", strategy, gateway, moduleName);
```
but the tail of the baseUrl `web-security` will always be removed.

**Comment by yschimke** [comment]
This is the documented behaviour.  Not a bug.

https://square.github.io/retrofit/

"android/test/conn" is relative

"/android/test/conn" is absolute.

**Comment by WilliamChen-luckbob** [comment]
@yschimke I see. I've changed my codes. Thank you for your answer!
