### ISSUE TITLE
Difference in DNS caching between execute() and enqueu() methods

### ISSUE THREAD

**Issue by samanton6** [square/okhttp#6911]
Good bug reports include a failing test! Writing a test helps you to isolate and describe the problem, and it helps us to fix it fast. Bug reports without a failing test or reproduction steps are likely to be closed.

Here’s an example test to get you started.
https://gist.github.com/swankjesse/981fcae102f513eb13ed

We invoke downstream application using host name  which is resolved to an Load Balancer and it is mapped to different IP addresses. 

When we invoke Synchronous request using execute() method, then okhttp client is able to identifiy the new active ip address which is attached to the load balancer and gets the response back.

But when we invoke Asynchronous request using enqueue() method, then okhttp client is taking the IP address from the cache and goes to the ip address which is not currently attached to load balancer.

Is there dns caching done in enqueue() which is not done in execute() method and if so, how to resolve the dns caching that is being done in enqueu() method as we need to resolve the DNS for the host and go against the active IP which is attached to the load balancer and not to the inactive ip which would be available in the cache.

**Comment by yschimke** [comment]
The enqueue and execute both treat Dns the same way.  There can be some differences between connection reuse if you execute them at the same time, so there can be other reasons.

We can't really offer 1:1 support for issues like this.  I suggest making a reproducible example and posting to stackoverflow.

Or reopen with a bug reproduction.
