### ISSUE TITLE
Class field can be replaced by local variable

### ISSUE THREAD

**Issue by noobyu6** [square/okhttp#6915]
Hi,
    Recently I work on Class field replacement, when I test this project then I find a class contains some fields can be replaced by local variables. The Class path is "okhttp-parent-3.12.13/okhttp/src/main/java/okhttp3/internal/tls/DistinguishedNameParser.java".
Field like "beg","end" can be replaced by local variables. I expect to receive your reply, thanks!

[testfile.txt](https://github.com/square/okhttp/files/7568252/testfile.txt)

**Comment by yschimke** [comment]
That branch gets critical bug and all security fixes.  The class doesn't exist at head since https://github.com/square/okhttp/commit/8464c2502c5478ea22aaf2f5106dee5c3fe92c96

Please provide a reproducible test showing a bug, given it's not designed to be thread safe or reused.
