### ISSUE TITLE
Setting callTimeout causes tiemout exception

### ISSUE THREAD

**Issue by Timelessprod** [square/okhttp#6922]
Hi,

I encounter an issue that is mainly reported on the web but not here. It seems to happen to a lot of people on many different use cases. For me, it's when I configure my Okhttp3 client like so (with `TIMEOUT` being a global variable so let's suppose `TIMEOUT = 20000` for example) :

```scala
val client: OkHttpClient = new OkHttpClient.Builder().followRedirects(false)
                                                     .followSslRedirects(false)
                                                     .connectTimeout(TIMEOUT, TimeUnit.MILLISECONDS)
                                                     .readTimeout(TIMEOUT, TimeUnit.MILLISECONDS)
                                                     .writeTimeout(TIMEOUT, TimeUnit.MILLISECONDS)
                                                     .callTimeout(3 * TIMEOUT, TimeUnit.MILLISECONDS)
                                                     .build()
```
Then, whenever I make a call using a request I build, the program tries to make the request for 1 minute (3 times `TIMEOUT` duration as I set `callTimeout` to `3 * TIMEOUT`) and then throw a Timeout Exception :

```java
java.net.SocketTimeoutException: timeout
	at okio.SocketAsyncTimeout.newTimeoutException(JvmOkio.kt:143)
	at okio.AsyncTimeout.access$newTimeoutException(AsyncTimeout.kt:162)
	at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:335)
	at okio.RealBufferedSource.request(RealBufferedSource.kt:206)
	at okio.RealBufferedSource.require(RealBufferedSource.kt:199)
	at okio.RealBufferedSource.readHexadecimalUnsignedLong(RealBufferedSource.kt:381)
	at okhttp3.internal.http1.Http1ExchangeCodec$ChunkedSource.readChunkSize(Http1ExchangeCodec.kt:429)
	at okhttp3.internal.http1.Http1ExchangeCodec$ChunkedSource.read(Http1ExchangeCodec.kt:408)
	at okhttp3.internal.connection.Exchange$ResponseBodySource.read(Exchange.kt:276)
	at okio.Buffer.writeAll(Buffer.kt:1642)
	at okio.RealBufferedSource.readByteArray(RealBufferedSource.kt:236)
	at okhttp3.ResponseBody.bytes(ResponseBody.kt:124)
```

Removing the `callTimeout` fix the issue and the request only take a few seconds to be done.

I hesitate to write it on StackOverflow but when looking on the web, I see a lot of people having the same issue with no other solution than removing this parameter, so I think it might be a bug and not a wrong usage.

Thanks !

**Comment by swankjesse** [comment]
Can you make a test case that demonstrates this? I wouldn't expect the presence of a timeout to increase the duration of a call.

**Comment by yschimke** [comment]
Please re-open with a reproducible test case.  Consider using https://httpbin.org/delay/5 or similar.  OTherwise stackoverflow might be the most appropriate venue for support.

**Comment by liushuaikobe** [comment]
@Timelessprod Have you solved this issue? I meet the same issue now.
After I adding `.callTimeout(8, TimeUnit.SECONDS)` to the builder parameters, the CPU increase to almost 100%, and many threads keep running but no blocking.
![image](https://user-images.githubusercontent.com/2098020/162133334-a8dfd794-bfba-4e51-a5d7-d5db9f8d76c3.png)

**Comment by Timelessprod** [comment]
@liushuaikobe I wasn't able to solve it so I simply remove this option and let the Read, Write and Connect timeouts which I think are sufficient enough to handle timouts.

**Comment by liushuaikobe** [comment]
But in my case, I need to control the total time cost of one call. 
There are some cases that the Read, Connect, Write timeouts are all reasonable but the network speed (transfer speed) is low.
I'm thinking that if `.retryOnConnectionFailure(false)` works for this issue.
