### ISSUE TITLE
Timeout not worked when pull out WAN line from router.

### ISSUE THREAD

**Issue by wxj978566042** [square/okhttp#6928]
I use a android device connecting network by ethernet interface，the problem which causes no response occurred when I pull out WAN line from router. 
About 40% chance to reproduce.
When this occurred, no response will return despite what timeout set.
Here is my simple code, please have a look, thx.
```
private static final String PING_URL = "http://www.baidu.com";

    static OkHttpClient client = new OkHttpClient.Builder()
        .writeTimeout(3, TimeUnit.SECONDS)
        .readTimeout(3, TimeUnit.SECONDS)
        .connectTimeout(3, TimeUnit.SECONDS)
        .callTimeout(3, TimeUnit.SECONDS)
        .retryOnConnectionFailure(false)
        .build();

    public static void startDownloadByOKHttp() {
        mExecutor.execute(() -> {
            Log.d(TAG, "start download by okhttp...");
            Request request = new Request.Builder()
                .url(PING_URL)
                .get()
                .build();
            client.newCall(request).enqueue(new Callback() {
                @Override
                public void onFailure(@NonNull Call call, @NonNull IOException e) {
                    Log.d(TAG, "onFailure:ex:" + e.getMessage());
                    e.printStackTrace();
                }

                @Override
                public void onResponse(@NonNull Call call, @NonNull Response response) throws IOException {
                    Log.d(TAG, "onResponse:responseCode:" + response.code());
                }
            });

        });
```

**Comment by yschimke** [comment]
Unfortunately we can't use this sample to reproduce the problem.  Without this we can't help.  I suggest raising on stackoverflow as we don't generally offer 1:1 usage advice through the issue tracker.

**Comment by wxj978566042** [comment]
> Unfortunately we can't use this sample to reproduce the problem. Without this we can't help. I suggest raising on stackoverflow as we don't generally offer 1:1 usage advice through the issue tracker.

Fine，I will check it in stackoverflow.   By the way, this question opened in HttpClient\HttpUrlConnection\OKHttp，maybe related to android device,hhh.
