### ISSUE TITLE
Run build failed on apple sillicon chips

### ISSUE THREAD

**Issue by Goooler** [square/okhttp#6943]
I run the project on my new MacBook pro with m1 pro, Adopt JDK download failed.

```
Execution failed for task ':okhttp:compileKotlin'.
> Error while evaluating property 'kotlinJavaToolchainProvider.javaVersion' of task ':okhttp:compileKotlin'
   > Failed to calculate the value of property 'providedJvm$kotlin_gradle_plugin'.
      > Unable to download toolchain matching these requirements: {languageVersion=11, vendor=ADOPTOPENJDK, implementation=vendor-specific}
         > Unable to download toolchain. This might indicate that the combination (version, architecture, release/early access, ...) for the requested JDK is not available.
            > Could not read 'https://api.adoptopenjdk.net/v3/binary/latest/11/ga/mac/aarch64/jdk/hotspot/normal/adoptopenjdk' as it does not exist.

```

**Comment by JakeWharton** [comment]
Adopt doesn't exist anymore anyway. Send a PR to replace with Zulu.

**Comment by Goooler** [comment]
Replaced it with 
```kotlin
  configure<JavaPluginExtension> {
    toolchain {
      languageVersion.set(JavaLanguageVersion.of(11))
      vendor.set(JvmVendorSpec.AZUL)
    }
  }
```
but still failed
```
Execution failed for task ':okhttp:compileKotlin'.
> Error while evaluating property 'kotlinJavaToolchainProvider.javaVersion' of task ':okhttp:compileKotlin'
   > Failed to calculate the value of property 'providedJvm$kotlin_gradle_plugin'.
      > No compatible toolchains found for request filter: {languageVersion=11, vendor=AZUL, implementation=vendor-specific} (auto-detect true, auto-download true)

```

**Comment by Goooler** [comment]
And kapt `info.picocli:picocli-codegen` failed, filed a bug [here](https://github.com/remkop/picocli/issues/1480).

**Comment by yschimke** [comment]
Seems we might be blocked here?

https://github.com/gradle/gradle/issues/19140 - Support "Zulu OpenJDK Discovery API" for auto provisioning toolchains
https://github.com/gradle/gradle/issues/16596 - Support auto-download of Java toolchains for more vendors than just AdoptOpenJDK

**Comment by yschimke** [comment]
Seems like this might be close

https://docs.gradle.org/current/userguide/toolchains.html#sec:provisioning

`org.gradle.jvm.toolchain.install.adoptopenjdk.baseUri=https://api.company.net/`

and 

https://github.com/foojayio/discoapi

**Comment by Goooler** [comment]
I'll try it later.

**Comment by Goooler** [comment]
Add `org.gradle.jvm.toolchain.install.adoptopenjdk.baseUri=https://api.company.net/` with error:
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':okhttp:compileKotlinJvm'.
> Error while evaluating property 'kotlinJavaToolchainProvider.javaVersion' of task ':okhttp:compileKotlinJvm'
   > Failed to calculate the value of property 'providedJvm$kotlin_gradle_plugin'.
      > Unable to download toolchain matching these requirements: {languageVersion=11, vendor=ADOPTOPENJDK, implementation=vendor-specific}
         > Could not read /Users/snebula/.gradle/jdks/adoptopenjdk-11-aarch64-mac.tar.gz.
            > Not in GZIP format
```
 
Refer to gradle/gradle#19140, add `org.gradle.jvm.toolchain.install.adoptopenjdk.baseUri=https://api.company.net/` is ok.

**Comment by Goooler** [comment]
After #7068 & #7091, it works.

**Comment by yschimke** [comment]
FYI looks possible now with https://github.com/gradle/gradle/blob/d0dffdcc004dba9515626cfbd2abce262454a286/subprojects/docs/src/docs/release/notes.md#added-support-for-java-toolchain-downloads-from-arbitrary-repositories in Gradle 7.6

**Comment by Goooler** [comment]
Yeah, it's possible to use zulu vendor in Gradle 7.6

**Comment by IgorGanapolsky** [comment]
I am still getting this error on M1 MacBook Air with Android Studio 2022.1.1 Canary 10

**Comment by SomeoneWickedThisWayComes** [comment]
Same with M1 MacBook Pro 2020 with IntelliJ IDEA 2023.1 CE EAP

**Comment by yschimke** [comment]
You should be able to install the JDK yourself from Intellij. It will use those if available. I develop on a MacBook m1.

**Comment by SomeoneWickedThisWayComes** [comment]
> You should be able to install the JDK yourself from Intellij. It will use those if available. I develop on a MacBook m1.

Can you please show me which exact settings do you use? I've tried different ones but get the same error.

**Comment by yschimke** [comment]
<img width="1017" alt="image" src="https://user-images.githubusercontent.com/231923/226166453-34c4c505-f954-46b5-9431-d5d2f7d6ec4c.png">

<img width="724" alt="image" src="https://user-images.githubusercontent.com/231923/226166518-6aa9b9fb-b453-4d0d-8341-4bcfdbf84506.png">

**Comment by SomeoneWickedThisWayComes** [comment]
> <img alt="image" width="1017" src="https://user-images.githubusercontent.com/231923/226166453-34c4c505-f954-46b5-9431-d5d2f7d6ec4c.png">
> 
> <img alt="image" width="724" src="https://user-images.githubusercontent.com/231923/226166518-6aa9b9fb-b453-4d0d-8341-4bcfdbf84506.png">

Thank you for your help! Unfortunately I still have same errors. Something's not right on my side.

**Comment by SomeoneWickedThisWayComes** [comment]
I've changed to Intellij IDEA version 2022.3 and set SDK version to 18 and voila! Everything works now.

**Comment by TakanashiHitomi** [comment]
![image](https://github.com/square/okhttp/assets/13413818/19a27cf4-3a7c-4500-9e22-4dc2dc03b816)
Thank you for your help too! But I have same error too.
I also change version to `azul-18` but nothing changes.
