### ISSUE TITLE
Convert Parameter keys to a,b,c,,,,

### ISSUE THREAD

**Issue by AhmedElkholyEva** [square/okhttp#6946]
In my project, when i use post request ,, the keys of parameters coverts to alphabetical letters before send to API.

Example : 

it sends : {"a":"amr@gmail.com","b":"amr12345","c":"en","d":"Android","e":"en","f":"1.0"}
instead of {"device_id":"en","email":"amr@gmail.com","language":"en","password":"amr12345","platform":"Android","version":"1.0"}

**Comment by JakeWharton** [comment]
Sounds like you're using an obfuscation tool and a reflection-based serialization library. Neither of these have to do with OkHttp as the body is supplied as bytes and OkHttp merely copies it to the underlying socket in the right place of the HTTP protocol. I would suggest looking at the documentation of your serialization library and/or your obfuscation tool for ways to prevent this behavior.
