### ISSUE TITLE
Shorten qualified thread names

### ISSUE THREAD

**Issue by chao2zhang** [square/okhttp#6950]
The trace produced by the Android Studio Profiler shows the truncated thread names by 15 characters, in some cases, the thread is truncated to nearly unreadable. 

For the screenshot below, we have `ddit.com Writer` - This is in fact truncated from `OkHttp www.reddit.com Writer`
![21638602356_ pic](https://user-images.githubusercontent.com/1175468/144701589-9ec4c92d-0648-4fe0-853f-fb278e32ca6e.jpg)

Other notes:
- There was a similar effort for work manager in https://issuetracker.google.com/issues/198236485 to carefully design the thread names, but this has to be done across the board.
- This is only impacting Profiler and maybe other tools agnostic of the execution environment. The debugging flow has the full visibility of thread names.
- We may only be able to shorten thread names to a certain degree, 15 characters is sometimes too restricted that we can't fit meaningful and readable names under that limit.

**Comment by yschimke** [comment]
@chao2zhang Great suggestion, since you are actively using these, what would you suggest as a starting point?

**Comment by chao2zhang** [comment]
Thanks for the endorsement. I will probably contribute to a PR, after studying what and how many the internal thread pools are. The PR should be a simple one.

**Comment by chao2zhang** [comment]
The change in https://github.com/square/okhttp/commit/ef4b5ec34849d088021dc89f290223d6043e79d2 changes the current TaskRunner thread name to include the running task name.

It seems that the existing implementation helps with the debuggability, so I would like to wait for @swankjesse 's opinion on this issue.

**Comment by swankjesse** [comment]
What's the 15 character version of `OkHttp www.reddit.com Writer` ? I’d like to avoid regressing on full length names to satisfy this use case.

**Comment by chao2zhang** [comment]
```
    val currentThread = Thread.currentThread()
    val oldName = currentThread.name
    currentThread.name = task.name
```
This piece of code in `TaskRunner` is changing the thread name to the current task name. I am considering removing this logic, so that all the threads will have a stable name through the lifecycle `OkHttp TaskRunner` (Or probably `OkHttp TaskRunr to fit below 15 characters)

**Comment by swankjesse** [comment]
If you want a stable identifier for a thread, use its ID? The name shouldn't need to be stable.

**Comment by chao2zhang** [comment]
Thread id is not human-readable, and many of the toolings like Debugger or Profiler uses thread names.
Screenshots from debugger:
![Screen Shot 2021-12-07 at 8 27 46 AM](https://user-images.githubusercontent.com/1175468/145067809-ba8c7192-39a3-4fa5-8ecf-98904ca10ea7.png)
Screenshots from profiler (With 4.9):
![image](https://user-images.githubusercontent.com/1175468/145068870-786638aa-b4f9-45ce-8fdc-89e768593559.png)

**Comment by swankjesse** [comment]
If we keep useful thread names is there any mitigation here? Seems like the bug is in the Android Studio Profiler and not OkHttp.

**Comment by chao2zhang** [comment]
If we think updating thread names by the current task name is useful for debugging, I can close this issue and regard this as the expected behavior.

**Comment by swankjesse** [comment]
Yeah, that's what it's for.
