### ISSUE TITLE
Trust anchor for certification path not found

### ISSUE THREAD

**Issue by pavolfranekdev** [square/okhttp#6952]
I use OKHttp lib in the application which is unchanged for more than a year. Now, all of a sudden, users are reporting a problem in an application that I haven't changed. Has anything changed on your side?

OkHttpClient: <-- HTTP FAILED: javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found

**The problem is only on the old Android 5.1 api 22 on newer it works without problems**

Server has valid SSL certificate . I try version 3 and the latest version 4.9.3 but is the same problem.

Any idea ?

**Comment by yschimke** [comment]
Do you have a server name we can test against? Generally it will be some change to SSL Certificates and minimum TLS levels/ciphers. Or expiry/revocation of some intermediate cert?

There are sites like https://www.ssllabs.com/ssltest/analyze.html?d=smh.com.au&s=13.227.66.83&latest you can use to test the server and see if it's doing anything problematic.

**Comment by yschimke** [comment]
Best ask this type of question on stackoverflow with a reproduction in code. Or at least server details.

**Comment by hellday** [comment]
I had this problem with the same Android version, OkHttp was in 4.3.0, upgraded to the latest 4.9.3 fixed this problem.

**Comment by bsprengelmeijer** [comment]
Same issue here, did you ever figure this out?

**Comment by bala-saptanglabs** [comment]
same issue here, cannot even send the request to webhook.site from android api version **21 to 24**, any solution available

**Comment by yschimke** [comment]
See https://stackoverflow.com/questions/64844311/certpathvalidatorexception-connecting-to-a-lets-encrypt-host-on-android-m-or-ea

**Comment by bala-saptanglabs** [comment]
thanks for sharing , as you guessed i am using Let's encrypt for ssl certificate and okhttp as http client, below android api below 24 are throwing this certPathValidatorException.problem is workarounds are done in application (modifying source code). i guess there is no option execpt changing cert authority for permanent solution. i also referred this : https://community.letsencrypt.org/t/letsencrypt-certificates-fails-on-android-phones-running-android-7-or-older/205686

**Comment by yschimke** [comment]
There are options provided in that stackoverflow link, that work below 24.
