### ISSUE TITLE
okhttp-bom react native bad gateway issue

### ISSUE THREAD

**Issue by leah9227-arkus** [square/okhttp#6955]
Hello there! I just wanna share with you this issue. The following library is returning a 502 bad gateway error:

[http://tokbox.bintray.com/maven/com/squareup/okhttp3/okhttp-bom/4.4.1/okhttp-bom-4.4.1.pom](url)

![image](https://user-images.githubusercontent.com/58701932/145472230-93256ef6-2307-4a9b-a09a-62e0516b18c9.png)

So I just can't make a build and generate an APK from a react native project:

![image](https://user-images.githubusercontent.com/58701932/145472509-02ad6238-8aea-4887-a328-b2684d30e8a9.png)

![image](https://user-images.githubusercontent.com/58701932/145472541-87ab508d-e97a-46cd-8f06-43c7f4541211.png)

Are you guys having also issues with it? Any information about this? Any possible fix or work around?

**Comment by JakeWharton** [comment]
Somewhere you define a list of repositories. `mavenCentral()` should be first. Beyond that this isn't a problem with OkHttp itself and we aren't well suited to help diagnose exactly what's going on in your specific build.

**Comment by leah9227-arkus** [comment]
I just found that and I replaced the url with the new one and now is working! Thank you so much @JakeWharton!
