### ISSUE TITLE
can okhttp3 use dpdk or kernel bypass or io_uring to improve the performance?

### ISSUE THREAD

**Issue by xtuyaowu** [square/okhttp#6957]
hi all:
    can okhttp3 use dpdk or kernel bypass or io_uring to improve the performance?
thanks

**Comment by yschimke** [comment]
Not directly.  OkHttp uses the java.io.Socket interface with multiple implementations (TCP, SSL, proxy, unix domain). The use of these APIs likely makes it hard to even implement io_uring behind this.  You could swap out a complete replacement implementation as an interceptor like EnvoyMobile or Cronet, but this sort of capability isn't likely to happen unless the JDK provides an optimised io_uring implementation which may not be feasible.  We don't even use the existing java NIO APIs.

**Comment by swankjesse** [comment]
We might get this for free with Loom!

**Comment by yschimke** [comment]
Nice - https://cr.openjdk.java.net/~rpressler/loom/loom/sol1_part1.html
