### ISSUE TITLE
java.lang.reflect.InvocationTargetException

### ISSUE THREAD

**Issue by Siahkali** [square/okhttp#6981]
Hi
I use retrofit2:retrofit:2.9.0 but I get this error in Android version 4.4.2. After a lot of research, I realized that this problem is due to the lack of support for OkHttpClient in Android 4.x 
What should I do to fix this error?

```
OkHttpClient okHttpClient;
List tlsSpecs = Arrays.asList(ConnectionSpec.MODERN_TLS);
if (Build.VERSION.SDK_INT < Build.VERSION_CODES.LOLLIPOP) {
                    tlsSpecs = Arrays.asList(ConnectionSpec.COMPATIBLE_TLS);
                    okHttpClient = new OkHttpClient.Builder().connectionSpecs(tlsSpecs).build();
} else
 okHttpClient = new OkHttpClient.Builder()
                      .connectTimeout(GlobalInfo.ConnectTimeout, TimeUnit.MILLISECONDS)
                      .writeTimeout(GlobalInfo.ConnectTimeout, TimeUnit.MILLISECONDS)
                      .readTimeout(GlobalInfo.ConnectTimeout, TimeUnit.MILLISECONDS)
                      .build();

retrofit = new Retrofit.Builder()
                        .baseUrl(GlobalInfo.BaseURL)
                        .addConverterFactory(GsonConverterFactory.create())
                        .client(okHttpClient)
                        .build();
```

**Comment by yschimke** [comment]
Both Retrofit and OkHttp require a minimum of API 21 now.

https://square.github.io/retrofit/

> Retrofit requires at minimum Java 8+ or Android API 21+.

https://square.github.io/okhttp/security/

> Android 5.0+ (API level 21+) and on Java 8+.

You will have to use 3.12.x of OkHttp, however it is no longer actively supported.  Only a very serious security issue would warrant a patch to break that policy and fix it.

For retrofit, I think it's 2.6.4 https://github.com/square/retrofit/blob/master/CHANGELOG.md#version-270-2019-12-09
