### ISSUE TITLE
Interceptor is not called if followRedirects(true) and get Redirection status code (3xx)

### ISSUE THREAD

**Issue by shaburov** [square/okhttp#6989]
com.squareup.okhttp3:okhttp:4.9.3

Precondition: `OkHttpClient.Builder().followRedirects(true)`

When the Redirect status is received, the Interceptor is triggered once and only for http status 200..299 or 400..599.

An interceptor is expected to be called for each HTTP call within the following redirects. This is the main task of the Interceptor.

The simplest example: when call on an unsecured URL `http://github.com/` we get `Status Code: 307 Internal Redirect` with header `Non-Authoritative-Reason: HSTS`. But we have no way of intercepting.

In my case, the `Set-Cookie` header comes in, which I cannot process in any way if `followRedirects(true)`.

Test here https://gist.github.com/shaburov/9d0273984dee29e325891cd23fa4778e

**Comment by yschimke** [comment]
Thanks for the repro! I'll take a look.

**Comment by yschimke** [comment]
This is documented behaviour https://square.github.io/okhttp/interceptors/

```
The URL http://www.publicobject.com/helloworld.txt redirects to https://publicobject.com/helloworld.txt, and OkHttp follows this redirect automatically. Our application interceptor is called once and the response returned from chain.proceed() has the redirected response:
```

This is the difference with application interceptors vs network interceptors.

**Comment by shaburov** [comment]
@yschimke Thanks!

**Comment by ali0399** [comment]
I faced an issue where the redirect location that i got from the 1st Api call had a different subdomain. but the **host** header retains the domain of the first api. this causes error in my server and i get 404.
**1st Api:** https://abcalert.extensions.sit.abcx1.de/fp/install.  
**2nd Api:** https://api.sit.abcx1.de/authentication/v1.0/company/111/oauth/authorize
the header, host: abcalert.extensions.sit.abcx1.de remains same in both.

Work around: removed host header using network interceptor
