### ISSUE TITLE
Unexpected behavior while measuring download time using eventListener

### ISSUE THREAD

**Issue by mustansarsaeed** [square/okhttp#6991]
Hi, I hope everyone is fine. I'm using `okhttp` version `4.3.1`. I'm trying to measure the download time for a file. For that I have used the following code:

```
val okHttpClientBuilder = OkHttpClient.Builder()
                .connectTimeout(5, TimeUnit.MINUTES) // connect timeout
                .writeTimeout(5, TimeUnit.MINUTES) // write timeout
                .readTimeout(5, TimeUnit.MINUTES)

                .eventListener(object : EventListener() {
                    override fun callStart(call: Call) {
                        val callTimeEnd = System.currentTimeMillis()
                        Log.v(TAG, "callTimeEnd: $callTimeEnd")
                    }

                    override fun callEnd(call: Call) {
                        val callTimeStart = System.currentTimeMillis()
                        Log.v(TAG, "callTimeEnd: $callTimeEnd")
                    }
                })
```

It logged the following timestamps:

callStart: 1641622023750
callEnd:  1641622031159

and `callEnd` - `callStart` = `~7.4seconds`. My device (Android 9.0) has downloading speed of 5 Mega bits per second. File size is 25 Mega Bytes. Ideally, downloading time should be ~40 seconds. Am I missing something or do the library is doing something under the hood?

Moreover, another device (Android 8.0) with downloading speed of 20 Mega bits per second is downloading the same file in ~ 10 seconds i.e., taking longer time than Android 9.0 device. Any pointer will be appreciated.

**Comment by yschimke** [comment]
Possibly gzip or caching? I'd suggest adding an event listener https://square.github.io/okhttp/events/ and recording the byteCount for response body.

I'm going to close this, I suggest continuing on somewhere like stackoverflow, post a link to this request and we'll check there.  But we avoid use of the issue tracker for anything other than reproducible bugs.

**Comment by mustansarsaeed** [comment]
@yschimke I have already posted question on https://stackoverflow.com/questions/70631482/unexpected-behavior-while-measuring-download-time-using-okhttp-eventlistener-on . Please see for further comments. Thanks.
