### ISSUE TITLE
POST, PUT, and PATCH requests with NULL body should be allowed

### ISSUE THREAD

**Issue by ruphin** [square/okhttp#7005]
The resolution to issue #1131 was that certain request types (POST, PUT, PATCH) are no longer allowed to have no body. However, this is not in line with the HTTP specifications.

Nowhere in the HTTP spec is mentioned that a body is required for POST requests: https://www.rfc-editor.org/rfc/rfc7231#section-4.3.3

An earlier version of the spec explicitly defined that a request payload  is _optional_ for all request types: https://datatracker.ietf.org/doc/html/draft-ietf-httpbis-p3-payload-11#section-3

In this thread you can find responses from HTTP working group members that indicates POST requests without a body should be valid: https://lists.w3.org/Archives/Public/ietf-http-wg/2010JulSep/0272.html

**Comment by yschimke** [comment]
Can you describe what you are trying to achieve? Is there some API that takes advantage/requires this?

I expect it would take a strong justification for us to change this.  The email thread is from 4 years before the current spec, so I'm not sure how to read that exactly.

We often look at other clients and standards, so evidence that this is a common implementation choice would help.  Looking at docs like Mozilla Docs they agree with the current implementation

https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/POST - Request Body  - Yes
https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/DELETE - Request Body - May

**Comment by ruphin** [comment]
We have a transaction approval system that allows users to signal they approve a transaction by making a POST request to and endpoint that looks like `https://api.service.com/approvals/<approval-id>/ok`. This system has been in use and functioning for years on our web platform.

We have Android and iOS applications that expose web functionality through webviews, allowing us to reuse our web platform to service mobile customers. Here we intercept all API requests made in the webview, and route them through the mobile app security framework.

On every other platform (web, iOS) everything is working as expected, but the transaction approval system is broken on Android because this library won't forward the POST requests without a body.

We now have to implement workarounds (by attaching emptystring bodies to requests without a body) specifically to keep systems that use this library from failing. Since this library is the only HTTP request tool across all platforms we use that is breaking on these requests, I would consider its behaviour outside the norm, specifically because the HTTP standard does not disallow these types of request.

It looks to me like the Mozilla documentation is also incorrect on this topic. Thanks for bringing it to my attention, I will create an issue there as well.

**Comment by yschimke** [comment]
I'll wait for others to weigh in on this, it's comforting to know that you have a workaround for this (empty body), so you are not currently blocked.

**Comment by ruphin** [comment]
As an evidence that other clients commonly support sending POST requests without body, I propose looking at the behaviour of web browsers.

You can try this by going to [httpbin.org](http://httpbin.org) in your browser of choice and running this code:

```js
const http = new XMLHttpRequest();
http.open('POST', "http://httpbin.org/anything");
http.onreadystatechange = () => console.log(http.responseText);
http.send();
```

As far as I know all (major) browsers will happily send an HTTP POST request with no body.

**Comment by swankjesse** [comment]
@ruphin is the a meaningful difference between an empty body and no body at all?

**Comment by ruphin** [comment]
I think yes. For one, this library will send a request with empty body but refuse to send one with no body ;)

Over the wire the difference is expressed by the presence of "Content-Length" header. According to [the spec](https://datatracker.ietf.org/doc/html/rfc7230#section-3.3.2), a message with a body MUST have a "Content-Length" (or "Transfer-Encoding") header. The content length MUST be 0 or higher. Thus, a message with empty body should have a Content-Length header with value 0, and a message with no body should have no Content-Length header.

Semantically I think there is also a difference. Imagine a (badly designed) message service that allows you to post chat messages by putting your message in the body of a POST request. A POST request with empty body (Content-Length 0) should post an empty message, but a POST request with no body is not semantically valid in this context and should be ignored (by the server).

--------------

Regardless of the answer to the question, I think this API throwing error on no body is a bug. Consider the options:

 - If there is a meaningful difference, the API should allow me to POST with "" and `null` because they are different.
 - If there is no meaningful difference, then the API is wrong to allow one and disallow the other, because they are the same.

**Comment by swankjesse** [comment]
Is this a feature request to support hypothetical badly designed APIs that have different behavior for null vs. empty?

Do browsers support this distinction? Does HTTP/2?

**Comment by swankjesse** [comment]
I think that because absent vs. empty is ambiguous in HTTP/2 we shouldn't offer a mechanism to make them different in OkHttp.

> A request or response that includes a payload body can include a content-length header field. A request or response is also malformed if the value of a content-length header field does not equal the sum of the DATA frame payload lengths that form the body.

https://httpwg.org/specs/rfc7540.html#malformed

**Comment by swankjesse** [comment]
Yeah also the HTTP/1 docs don't suggest a difference between absent and empty for methods that enclose a body.

```
   A user agent SHOULD send a Content-Length in a request message when
   no Transfer-Encoding is sent and the request method defines a meaning
   for an enclosed payload body.  For example, a Content-Length header
   field is normally sent in a POST request even when the value is 0
   (indicating an empty payload body).  A user agent SHOULD NOT send a
   Content-Length header field when the request message does not contain
   a payload body and the method semantics do not anticipate such a
   body.
```

**Comment by ruphin** [comment]
The feature request is not to support hypothetical badly designed APIs. It was just a hypothetical example that you could use as an argument to claim they are different. I don't have a position in this, if you want to interpret these two requests as different or the same, that's up to you, as the spec is indeed ambiguous about this.

If you think making an HTTP request with no body and one with an empty body is the same, then my point is that it's odd that your library specifically forbids one but allows the other. For example, browsers accept both emptystring and undefined body, and will send an HTTP POST with Content-Length 0 over the wire in both cases, which is a strong argument to interpret these two as the same.

Aside from how you feel about ambiguity in the HTTP spec, the core issue I have is that this type of request is working in every other HTTP client that we use, _except_ for this library, so we need to write workarounds just for this library because it has different behaviour.

**Comment by swankjesse** [comment]
We insist on an non-null body for HTTP methods like POST where a possibly-empty HTTP body must always be sent to comply with the spec.

We insist on a null body for HTTP methods like GET where no HTTP body may be sent to comply with the spec.

My model of it is:
 * If there's a body there's a content-length header (or transfer-encoding for streaming bodies!)
 * If there's no body there's no content-length header (and no transfer-encoding header either)

In particular HTTP GET is different here because it doesn't permit any body, not even an empty body. So there is a distinction. It's just that GET never has a body and POST always has one.

We could unambiguously convert null request bodies to empty request bodies for POST requests. We don't do that because it's simple for you to create an empty body instead.

JavaScript famously converts arbitrary values between types as a user convenience. The typical user response is not delight but WAT. We shy away from such conveniences in this library.

**Comment by yschimke** [comment]
Looking back at decisions we've made in this category.  We have often taken positions in grey areas to focus on either a) following important industry standards (where features are implemented by browsers and actively used that way), or b) encouraging good practices, making it hard to make accidental bad requests (meticulous, opinionated, ergonomic, ...).

But also we've avoided changing existing behaviour often when there is a reasonable workaround. Even if it isn't pretty but keeps the standard cases cleaner. I think that also applies in this case.

**Comment by ruphin** [comment]
To put some perspective on how this issue can impact users; we had a production incident impacting one of our services on our Android platform, because this library throws on some inputs. My team works on platform infrastructure that is responsible for forwarding and handling all HTTP traffic created by product/application teams, and we don't know what kinds of requests are created by our teams, we just have to forward them using the appropriate methods. One such team had a service that has been running without issues on our web platform for years, and recently enabled this service on our mobile Android and iOS platforms, which caused failures specifically on Android because we use this library as our general purpose HTTP client on our Android platform.

I agree that their HTTP request structure is questionable, but consider this from the product team's perspective. Their request scheme has been working for several years across many different browsers/ HTTP clients, and HTTP/proxy/application server backends. Without having an engineer on their team who is familiar with all details of the HTTP spec, I think it is reasonable that they reach the conclusion that their implementation is valid. 

I can name off the top of my head over 10 HTTP client/server implementations that allow undefined/no body in POST requests:

 - XMLHTTPRequest API (IE11, Edge Legacy, Chromium, Firefox, Safari, probably every other browser)
 - Fetch API (Chromium, Firefox, Safari, Deno, fetch polyfill from whatwg)
 - Nginx
 - Apache

I don't know a of a single one that will throw or fail on such requests.

As you mentioned yourself in earlier posts, you like to be aligned with other HTTP client implementations. Given this, I still consider the current behaviour of this library a bug. At least from our perspective, if we cannot trust the httpok implementation to be aligned with other HTTP clients and it can randomly refuse to send certain HTTP requests because you consider the request to be invalid according to your interpretation of the spec, it is not usable for us as a general purpose HTTP client.

**Comment by swankjesse** [comment]
I appreciate your frustration. I'm doing my best to make OkHttp predicable and don't want to be unreasonable.

But I'm also confused. What happened that caused your Android app to send a POST request with a null body? Our typical users might encounter that NullPointerException in development, then switch to an empty request body instead.

**Comment by ruphin** [comment]
Our developers build "application" logic for the web platform. Our Android applications use webviews to wrap existing applications, and intercept/forward all HTTP requests through our Android security library for authentication purposes.

The Android app is trying to send a POST request with a null body because it intercepted such a request from a web application in a webview and is trying to forward it. The web application in question has been running in production on other platforms for years, and the original developers never encountered any exceptions back when it was in development. The exception is only happening now that their application/functionality is exposed in one of our Android applications.

The team that handles the Android request interception/forwarding must rely on an HTTP library to forward any request that we intercept from existing web applications.

**Comment by swankjesse** [comment]
Thanks for the context, that helps!
