### ISSUE TITLE
OkHttp using stale Connection after introducing IDLE_CONNECTION_HEALTHY_NS

### ISSUE THREAD

**Issue by Avishayy** [square/okhttp#7007]
[Commit that introduced the optimization](https://github.com/square/okhttp/commit/19cb19ab4ac31aa789bc94759d13898f64f93ce3)

[Relevant issue on react-native](https://github.com/facebook/react-native/issues/32842#issuecomment-1009023135)

tl;dr on above issue: After upgrading react-native for my app, the OkHttp version changed from 3.12.1 to 4.9.1, the connection is being shutdown by the peer and `candidate.isHealthy()` deems the connection as healthy because it hasn't been idle for more than 10 seconds (which wasn't present on 3.12.1), but this is wrong because the connection is already closed and the next read will cause an `EOFException`

I'm not entirely sure if `react-native` was supposed to check if the peer shut the connection down or if the assumption in the above commit is bad, but someone did something wrong here, I'm not proficient enough to get a good answer on that, so I hope to get an answer here (and potentially fix the underlying issue).

**Comment by yschimke** [comment]
Thanks for the thorough investigation on this.

**Comment by Avishayy** [comment]
You're welcome, I'd love to hear your thoughts on this issue.

**Comment by swankjesse** [comment]
@Avishayy any luck with `retryOnConnectionFailure (true)` ? 

One sneaky option we could try is being more aggressive about performing expensive checks if we know we're not going to retry if it fails.

**Comment by Avishayy** [comment]
It does work with `retryOnConnectionFailure(true)`, and I like you idea.

**Comment by swankjesse** [comment]
After some brief investigation, I think it’s best to fix this on the server. If it’s going to close a socket within 10 seconds of the HTTP response, it should send the `Connection: close` response header. That way OkHttp won’t pool the connection.

**Comment by jacob-pro** [comment]
Would it be possible for OkHttp to make the `IDLE_CONNECTION_HEALTHY_NS` configurable?

- I am not able to make any changes to the HTTP server behaviour, so need to fix this in the client side.
- `retryOnConnectionFailure (true)` doesn't help because the request bodies have `isOneShot=true`

**Comment by yschimke** [comment]
OkHttp generally doesn't expose all tuning knobs, preferring correct sensible default when that exists.

I'll look if there is a simple clean workaround using connection pool events.

**Comment by yschimke** [comment]
@swankjesse thoughts on checking isOneShot?
