### ISSUE TITLE
Upgrade from IDN2003 to UTS #46 Non-transitional

### ISSUE THREAD

**Issue by swankjesse** [square/okhttp#7008]
There’s a few IDN specs:

 * IDNA2003, what OkHttp gets for free from the JVM
 * IDNA2008, a spec that never gained widespread adoption
 * [UTS #46](https://www.unicode.org/reports/tr46/)

According to [this comment](https://github.com/whatwg/url/issues/110#issuecomment-284941364) on the URL standard, if we follow non-transitional rules we’ll be in good company with major browsers.

And here’s a handy test suite:
https://wpt.fyi/results/url/toascii.window.html?label=experimental&label=master&aligned

Lets do the following:

 * See what APIs Android and OpenJDK offer in this space
 * Upgrade to UTS 46 Non-transitional, possibly by writing our own implementation

**Comment by swankjesse** [comment]
https://github.com/web-platform-tests/wpt/blob/master/url/resources/toascii.json

**Comment by yschimke** [comment]
relevant to https://github.com/square/okhttp/issues/6910

**Comment by swankjesse** [comment]
https://github.com/square/okhttp/pull/7789

**Comment by swankjesse** [comment]
This is implemented! I’ll open a low-priority tracking bug to track some edge cases we could do better on.

**Comment by swankjesse** [comment]
https://github.com/square/okhttp/issues/7813

**Comment by swankjesse** [comment]
(I’m not opening tracking bugs for the other suppressed tests; as-is we’re consistent with Chromium on them.)
