### ISSUE TITLE
Specify base url for cache

### ISSUE THREAD

**Issue by yoobi** [square/okhttp#7012]
### Start by telling us what problem you’re trying to solve. Often a solution already exists!

So my problem is my baseUrl from Retrofit can change from one start of the application to another. 
Let's say in the first start my baseUrl is `https://my_api.com/` my user browse though the application and everything is fine and close the app. 
Later on he re-opens it but this time my baseUrl is `https://my_clone_api.com/` and all the cache he had built in the first session is now useless as the cache will only respond to `https://my_api.com/`.

That's why I'm asking if you find it useful to add this optional setter in the cache instance to specify a base_url or something else. It was just my first though about it.

Thanks

**Comment by swankjesse** [comment]
The level of effort to implement this safely and securely is huge, especially since there's TLS certificates in the cache entries for https requests.

If you need this, I advise not using OkHttp’s cache for it. Instead do your own caching by writing downloaded files to the filesystem manually.

**Comment by yschimke** [comment]
I suspect you _might_ be able to get creative to achieve this, like overriding the SocketFactory? But haven't tried it to see what else needs to be overridden, like TrustManager verifying the host?

**Comment by yoobi** [comment]
Yep I found something specific to my application that allows me to make it work
