### ISSUE TITLE
java.lang.NoSuchFieldError: Companion

### ISSUE THREAD

**Issue by SasonBraha** [square/okhttp#7049]
Hi,
I'm trying to use OkHttp 4.9.3 in my Kotlin project, but I'm getting the following error when using extension methods:
```
org.springframework.web.util.NestedServletException: Handler dispatch failed; nested exception is java.lang.NoSuchFieldError: Companion
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1055)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doPut(FrameworkServlet.java:920)

```

This seems to be caused by version mismatch. When adding OkHttp 4.9.3 to `build.gradle`, two versions are actually downloaded:
build.gradle:
```
dependencies {
    implementation 'com.squareup.okhttp3:okhttp:4.9.3'
}
```
Will result in two versions:
![image](https://user-images.githubusercontent.com/30155843/151963710-9fc289c8-c9ff-4245-a8f7-8301e04813d7.png)

**When removing 4.9.3 from the build.gradle, both versions are removed from external libraries.** It seems no other dependency is using OkHttp 3.14.9 in our project.

How can I resolve this? Thanks!

**Comment by yschimke** [comment]
You should be able to apply the BOM https://github.com/square/okhttp#releases

```
       // define a BOM and its version
       implementation(platform("com.squareup.okhttp3:okhttp-bom:4.9.3"))

       // define any required OkHttp artifacts without version
       implementation("com.squareup.okhttp3:okhttp")
       implementation("com.squareup.okhttp3:logging-interceptor")
```

**Comment by yschimke** [comment]
Closing as we can't provide 1:1 support with project builds, please consider using a site like Stackoverflow if the problem continues.

**Comment by yschimke** [comment]
No, I use it on various projects, so I'm fairly certain it works.

**Comment by 954L** [comment]
I also found this issue。4.9.3
