### ISSUE TITLE
Support download of intermediate certificates aka AIA Fetching

### ISSUE THREAD

**Issue by pke** [square/okhttp#7052]
We are using okhttp in an react native app and discovered a minor problem for targets that have incomplete certificate chains.
On iOS the app is able to download the missing intermediate certificate itself (not using okhttp obviously) and we would hope this could be possible in the android versions too.

Browsers have built in support to download such certificates transparently.

As an introduction to this problem I suggest [this article](https://www.thesslstore.com/blog/aia-fetching/). 

When this might be implemented one could use this site to test the proper behaviour of the new feature:
https://incomplete-chain.badssl.com/

This is how the nodejs guys tackled the problem:

Reference issue in nodejs. https://github.com/request/request/issues/3106

**Comment by yschimke** [comment]
I agree it would be a nice feature. In normal use OkHttp doesn't get involved in this, we leave the certificate validation to the platform stack.  So we'd expect Android to implement this for SSLSession/SSLSocket.

I suspect getting this supported in Google Conscrypt is the clean correct way to do this. https://github.com/google/conscrypt . It would be available via unbundled Conscrypt for all versions, and make its way into the Android platform.

Do you have any examples from JDK or Android HTTP clients that handle this? I didn't see it in Netty, but might have missed it. They have an example of OCSP for servers which is in a similar part of the process.

In theory on Android we could a implement this inside a custom TrustManager, doing synchronous calls to fetch the certificate.
https://github.com/square/okhttp/blob/f8fd4d08decf697013008b05ad7d2be10a648358/okhttp-tls/src/main/kotlin/okhttp3/tls/internal/InsecureAndroidTrustManager.kt

It would be a plaintext request (http) but I think that check is via OkHttp checking the platform network config, so we could make it anyway.

But it makes us responsible for a very critical security implementation, hence hoping we can see if it is something better for Conscrypt?

On JDK I think you can enable com.sun.security.enableAIAcaIssuers https://docs.oracle.com/javase/9/security/java-pki-programmers-guide.htm#JSSEC-GUID-E6E737DB-4000-4005-969E-BCD0238B1566

**Comment by yschimke** [comment]
Example AIA record

```
https://crt.sh/?id=6094989521
Authority Information Access: 
                OCSP - URI:http://ocsp.digicert.com/
                CA Issuers - URI:http://cacerts.digicert.com/DigiCertTLSHybridECCSHA3842020CA1-1.crt
```

**Comment by yschimke** [comment]
@pke what is the main driver here? Badly configured servers, or changing root CAs on older devices?

Also doesn't look like Node request implemented anything, got closed for going stale.

**Comment by pke** [comment]
thanks for the discussion! I just came to okhttp as the default client used in react native apps didn't know about Conscrypt. I just did a little research and it seems this scenario is not handled on Android at all. It is handled in Desktop Java and we enabled it in the JDK for our severs already (as per com.sun.security.enableAIAcaIssuers).

> @pke what is the main driver here? Badly configured servers, or changing root CAs on older devices?

The scenario are solely badly configured servers.

iOS seems to handle it automagically already (in react native at least).

> But it makes us responsible for a very critical security implementation, so I'd be nervous about implementing it in OkHttp instead of Conscrypt?

If other clients could benefit from that this would definitely be the way to go and not put this security related issue in the hands of okhttp.

**Comment by yschimke** [comment]
Going to close this out and follow along with Conscrypt.  @prbprbprb mentioned this https://bugs.chromium.org/p/boringssl/issues/detail?id=42, which possibly indicates a move away from fetching on incomplete chains.

But I don't think we can justify implementing this critical security feature inside of OkHttp, I don't want to explain the CVE afterwards :) 

I suspect, you can technically implement this inside of React Native with a custom TrustManager, but do you really want to be responsible for correctness of the TLS implementation. If it's badly configured servers, there is also the argument that the client failures are a prompt for servers to fix their setup.
