### ISSUE TITLE
Remove external link icon in website

### ISSUE THREAD

**Issue by swankjesse** [square/okhttp#7060]
The indicator for external sites makes the docs look cluttered, and it is broken in light mode. Let’s figure out how to remove it?

<img width="846" alt="Screen Shot 2022-02-06 at 12 38 14" src="https://user-images.githubusercontent.com/133019/152693556-5cef1fdc-9f55-4c4d-ae79-5bc3cc556921.png">
<img width="861" alt="Screen Shot 2022-02-06 at 12 38 10" src="https://user-images.githubusercontent.com/133019/152693557-ec80f053-f0f7-4e96-9d97-e1b2c46b4dc5.png">

**Comment by Andre601** [comment]
The style could perhaps be solved using CSS.

This would also be the place to alter when the icon shows.
