### ISSUE TITLE
GraalVM - Unable to load PublicSuffixDatabase.gz resource from the classpath

### ISSUE THREAD

**Issue by yamin8000** [square/okhttp#7061]
I'm using `com.squareup.okhttp3:okhttp:5.0.0-alpha.4` and `graalvm-ee-java11-22.0.0.2`
When using `native-image` I encounter this error:

```java
Exception in thread "OkHttp Dispjava.lang.IllegalStateException: Unable to load PublicSuffixDatabase.gz resource from the classpath.
        at okhttp3.internal.publicsuffix.PublicSuffixDatabase.findMatchingRule(PublicSuffixDatabase.kt:109)
        at okhttp3.internal.publicsuffix.PublicSuffixDatabase.getEffectiveTldPlusOne(PublicSuffixDatabase.kt:71)
```
My project is console kotlin app and there's no proguard or r8. I actually checked any that file `PublicSuffixDatabase.gz` is indeed inside my `jar` file but after creating native executable this happens.

**Comment by yschimke** [comment]
I think I forgot to add them to the automatic registration.

```
            ResourcesRegistry resourcesRegistry = ImageSingletons.lookup(ResourcesRegistry.class);
                    resourcesRegistry.addResources("...");
```    

But until then you will need to manually register it

https://www.graalvm.org/22.0/reference-manual/native-image/Resources/

**Comment by yamin8000** [comment]
> I think I forgot to add them to the automatic registration.
> 
> ```
>             ResourcesRegistry resourcesRegistry = ImageSingletons.lookup(ResourcesRegistry.class);
>                     resourcesRegistry.addResources("...");
> ```
> 
> But until then you will need to manually register it
> 
> https://www.graalvm.org/22.0/reference-manual/native-image/Resources/

Thanks, I was able to generate required configs for creating a native-image using link you provided and also [this one](https://medium.com/graalvm/working-with-native-image-efficiently-c512ccdcd61b).

```json
{
  "resources":{
    "includes":[
      {
        "pattern":"\\Qokhttp3/internal/publicsuffix/PublicSuffixDatabase.gz\\E"
      }
    ]}
}
```

**Comment by EeeMt** [comment]
> > I think I forgot to add them to the automatic registration.
> > ```
> >             ResourcesRegistry resourcesRegistry = ImageSingletons.lookup(ResourcesRegistry.class);
> >                     resourcesRegistry.addResources("...");
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > But until then you will need to manually register it
> > https://www.graalvm.org/22.0/reference-manual/native-image/Resources/
> 
> Thanks, I was able to generate required configs for creating a native-image using link you provided and also [this one](https://medium.com/graalvm/working-with-native-image-efficiently-c512ccdcd61b).
> 
> ```json
> {
>   "resources":{
>     "includes":[
>       {
>         "pattern":"\\Qokhttp3/internal/publicsuffix/PublicSuffixDatabase.gz\\E"
>       }
>     ]}
> }
> ```

what does the `\\Q` `\\E` mean?
thx
