### ISSUE TITLE
Sample of a CapturingTrustManager to simplify handshake failures

### ISSUE THREAD

**Issue by yschimke** [square/okhttp#7066]
Something like https://github.com/cashapp/certifikit/blob/373224a571b9328f340dfa225a127f90dda5ab72/certifikit-cli/src/jvmMain/kotlin/app/cash/certifikit/cli/okhttp/CapturingTrustManager.kt

Delegates the the real trust manager.

Captures the certificates from the server, before cleaning and even if handshake fails.

Ideally would look at the certificates and acceptedissuers and print out the problem, maybe even identify an incomplete chain that could be fetched?

**Comment by PradeepKumar100791** [comment]
Is this related to Error "com.androidnetworking.error.ANError: javax.net.ssl.SSLHandshakeException: Chain validation failed". We have some android devices and only a few are showing this error message - SSL Certificate is also valid for the next two months and the date and timezone is also correct in the devices.

**Comment by yschimke** [comment]
Yes, quite likely. You can try the one I link to and see what the certificates show.  But quite possibly those devices don't trust the root CA from your chain.

**Comment by yschimke** [comment]
cc @apkelly in case you are still stuck on debugging this

**Comment by yschimke** [comment]
Closing as low priority, this sample above should be sufficient.
