### ISSUE TITLE
should we use `call.execute()` or `call.enqueue(callback)` in duplex?

### ISSUE THREAD

**Issue by wangpingsx** [square/okhttp#7070]
# 🎉

_Originally posted by @swankjesse in https://github.com/square/okhttp/issues/4267#issuecomment-467776927_

> # 🎉

Thanks for this wonderful feature. 

Could you please share some example code of using this?

I found the test code: https://github.com/square/okhttp/blob/3ad1912f783e108b3d0ad2c4a5b1b89b827e4db9/okhttp/src/jvmTest/java/okhttp3/DuplexTest.java

Should I use `call.execute()` or `call.enqueue(callback)`. I found `call.execute()` doesn't work for me, it just blocked everything.... 

And I also found if I do `responseBody!!.readUtf8Line() `  more times, it just throw an exception:  `Unbalanced enter/exit`

**Comment by yschimke** [comment]
cc @oldergod Your name is all over the Wire implementation and OkHttp support.

I believe you can use both, but I'm not 100%.  If you call execute it won't return until the Request completes, so you will need to use the writeTo method as described in the docs.

But even for enqueue, you don't have a Sink to write to until the writeTo method is called.

https://github.com/square/okhttp/blob/b97eeacaa31a2c72a9396f5a4eab82f69b39cda8/okhttp/src/jvmMain/kotlin/okhttp3/RequestBody.kt#L72-L74

**Comment by oldergod** [comment]
You can have a look at [RealGrpcStreamingCall](https://github.com/square/wire/blob/master/wire-library/wire-grpc-client/src/jvmMain/kotlin/com/squareup/wire/internal/RealGrpcStreamingCall.kt) to see how we use it in Wire.

**Comment by wangpingsx** [comment]
> cc @oldergod Your name is all over the Wire implementation and OkHttp support.
> 
> I believe you can use both, but I'm not 100%. If you call execute it won't return until the Request completes, so you will need to use the writeTo method as described in the docs.
> 
> But even for enqueue, you don't have a Sink to write to until the writeTo method is called.
> 
> https://github.com/square/okhttp/blob/b97eeacaa31a2c72a9396f5a4eab82f69b39cda8/okhttp/src/jvmMain/kotlin/okhttp3/RequestBody.kt#L72-L74

`even for enqueue, you don't have a Sink to write to until the writeTo method is called.` you are right! this is a big pain for me!!!

Thanks for replying to my question!! Thanks so much.  I have to call sleep and retry... :-(
I will have a read of the [RealGrpcStreamingCall](https://github.com/square/wire/blob/master/wire-library/wire-grpc-client/src/jvmMain/kotlin/com/squareup/wire/internal/RealGrpcStreamingCall.kt) from oldergod.

Before that I would like to list all my questions/issues here. So, if I can find out the answers from [RealGrpcStreamingCall](https://github.com/square/wire/blob/master/wire-library/wire-grpc-client/src/jvmMain/kotlin/com/squareup/wire/internal/RealGrpcStreamingCall.kt), then I can list them here later to help other users in the future.

Questions, issues:

1. As the title,  should we use execute or enqueue?
2. What is the best way to get the sink?  can I get the sink before "execute"?
3. This is maybe not an issue once I know the right way of getting the sink: but I found setting up the `client` and executing the`Call` can take time. How can I setup everything and make sure sink is ready to use before the very first ByteArray's arrival?  
4. If we are sending audio or video stream, I guess we have to write to the Sink sequentially, right? Otherwise the serverside will miss up, right?
5. What is the best way of doing `responseBody!!.readUtf8Line()`?  I got`Unbalanced enter/exit` sometimes. Is that because I have multi threads reading from the `responseBody` at the same time?
6. I am very naively trying to run `client.execute()` from a new thread, but the app just crashed, without detail exception info....  `E/AndroidRuntime: FATAL EXCEPTION: Thread-7` this is all I got... No stacktraces..... why?
Thanks

**Comment by yschimke** [comment]
Can you provide a sample test we can discuss?

**Comment by swankjesse** [comment]
Do not read the response body from multiple threads concurrently. That just returns garbage. If you want to process the lines of a response as they arrive, have one producer thread drop the lines into a concurrent data structure like LinkedBlockingDeque or Kotlin’s channel, and multiple consumer threads pulling from that.

**Comment by swankjesse** [comment]
You may use either enqueue or execute with duplex. You should hand off the BufferedSink received by your RequestBody to another thread so that writeTo() may return. Then you have two threads, one for the request ane another for the response.

**Comment by wangpingsx** [comment]
> You may use either enqueue or execute with duplex. You should hand off the BufferedSink received by your RequestBody to another thread so that writeTo() may return. Then you have two threads, one for the request ane another for the response.

Just a quick update:  
replay your previous comment: I am not using multi-threads to concurrently read. Just 2 threads:  1. the callback 2. the main thread for writing. 

I also found "call execute()" from a new thread also not blocking my app. I guess execute() actaully blocks the thread, because it should hold the connection and streams... If I run on my "main" thread (which keeps polling byteArray from somewhere), it will block the "main" thread. . So creating a new thread to keep it happy should work.  I guess enqueue is doing something similar.

**Comment by wangpingsx** [comment]
> You can have a look at [RealGrpcStreamingCall](https://github.com/square/wire/blob/master/wire-library/wire-grpc-client/src/jvmMain/kotlin/com/squareup/wire/internal/RealGrpcStreamingCall.kt) to see how we use it in Wire.

Thanks for the code example.  I think I understand how you get the sink before the "writeTo" get called. You are using a [pipe](https://github.com/square/wire/blob/85dc2120adfdf489d66ed425f2cbad0ecbf0184a/wire-library/wire-grpc-client/src/jvmMain/kotlin/com/squareup/wire/internal/PipeDuplexRequestBody.kt) to hold the data.  Smart!

**Comment by wangpingsx** [comment]
> > cc @oldergod Your name is all over the Wire implementation and OkHttp support.
> > I believe you can use both, but I'm not 100%. If you call execute it won't return until the Request completes, so you will need to use the writeTo method as described in the docs.
> > But even for enqueue, you don't have a Sink to write to until the writeTo method is called.
> > https://github.com/square/okhttp/blob/b97eeacaa31a2c72a9396f5a4eab82f69b39cda8/okhttp/src/jvmMain/kotlin/okhttp3/RequestBody.kt#L72-L74
> 
> `even for enqueue, you don't have a Sink to write to until the writeTo method is called.` you are right! this is a big pain for me!!! I have to call `sleep(100)` and retry... :-(
> 
> Thanks for replying to my question!! Thanks so much. I will have a read of the [RealGrpcStreamingCall](https://github.com/square/wire/blob/master/wire-library/wire-grpc-client/src/jvmMain/kotlin/com/squareup/wire/internal/RealGrpcStreamingCall.kt) from oldergod.
> 
> Before that I would like to list all my questions/issues here. So, if I can find out the answers from [RealGrpcStreamingCall](https://github.com/square/wire/blob/master/wire-library/wire-grpc-client/src/jvmMain/kotlin/com/squareup/wire/internal/RealGrpcStreamingCall.kt), then I can list them here later to help other users in the future.
> 
> Questions, issues:
> 
> 1. As the title,  should we use execute or enqueue?
> 2. What is the best way to get the sink?  can I get the sink before "execute"?
> 3. This is maybe not an issue once I know the right way of getting the sink: but I found setting up the `client` and executing the`Call` can take time. How can I setup everything and make sure sink is ready to use before the very first ByteArray's arrival?
> 4. If we are sending audio or video stream, I guess we have to write to the Sink sequentially, right? Otherwise the serverside will miss up, right?
> 5. What is the best way of doing `responseBody!!.readUtf8Line()`?  I got`Unbalanced enter/exit` sometimes. Is that because I have multi threads reading from the `responseBody` at the same time?
> 6. ~I am very naively trying to run client.execute() from a new thread, but the app just crashed, without detail exception info....  E/AndroidRuntime: FATAL EXCEPTION: Thread-7 this is all I got... No stacktraces..... why?~ [Answer: I was not on VPN.... 👎  ]
> 7. How do we do error handling. e.g.  after couple of good read from the `responseBody`, if there is an issue on server side, will the server side return 4xx or 5xx? will we get a new response code ? or what willl happen? how should we deal with it?
>    Thanks

I think I got most of my answers.  I have updated my list hope that can help other users. 

But I am still keen to know if I can make an empty post while my app is prepare the first bytearray. So, we don't have to wait for about 200 ms for the writeTo get called.
And also about error handling. Do you know what errors we may can may can face if the server side have issue during duplex  communication?

Thanks

**Comment by wangpingsx** [comment]
@swankjesse  @oldergod  @yschimke   could you please suggest for the above 2 questions? thanks!!!

**Comment by yschimke** [comment]
I don't see why you need the byte array to execute or enqueue the request.  The writeTo, can hand off the BufferedSink to another thread which can wait for the byte array to be available.

You have a custom RequestBody, so it's not like you are forced to give it a byte array.

The others will have more knowledgeable answers, but assume any IOException is my guess, the server could fail in many spectacular ways from sending HTTP/2 goaway to closing socket, to sending invalid data...

**Comment by yschimke** [comment]
Going to close this out.  I suggest if there are further questions, put them in stackoverflow, add a link here and we can answer there to build the knowledge base.
