### ISSUE TITLE
MockWebServer: have a way to emit chunks of different sizes and with delays

### ISSUE THREAD

**Issue by BoD** [square/okhttp#7078]
Currently, MockWebServer has limited support of `chunked` transfer encoding, via the [`MockResponse.setChunkedBody`](https://github.com/square/okhttp/blob/e1af67f082027dd7811c88434749b7b8f807ceca/mockwebserver/src/main/kotlin/mockwebserver3/MockResponse.kt#L196) API, which returns the body in chunked of a fixed size.

It would be useful to extend this support to allow emitting arbitrary sized chunks, and with delays, in order to test streaming cases.

I could find this previously mentioned in [this "meta" issue](https://github.com/square/okhttp/issues/2903#issuecomment-303878567).

As said in this comment, I believe one way to do this could be to change the body of `MockResponse` to be a `Source` instead of a `Buffer` - of course this would be a breaking change on the API.

**Comment by yschimke** [comment]
Our recent answer for MockWebServer feature requests is

> To be clear on the status of this, enhancements for MockWebServer isn't a big focus for the OkHttp maintainers, but as this seems like a reasonable request, it's probably something that would be accepted given a nice simple clean PR.

But please consider how to make this change without breaking the API.  Breaking the existing API would probably mean we wouldn't land the PR.

**Comment by swankjesse** [comment]
Oooh interesting. I think this is a bad fit for MockWebServer now in terms of general utility vs. complexity. If you’d like it, please consider making your own fork. It’s not a particularly complicated library.
