### ISSUE TITLE
error: cannot find symbol Util.toHumanReadableAscii(agent)

### ISSUE THREAD

**Issue by natalyayyad** [square/okhttp#7080]
Hello, 

I'm using okhttp version: 3.12.12
and okio version:  1.17.5

I get this error in OkHttpURLConnection class
```
private String defaultUserAgent() {
    String agent = System.getProperty("http.agent");
    return agent != null ? Util.toHumanReadableAscii(agent) : Version.userAgent();
  }
```

Also, I have this error in the same file 

error: cannot find symbol .url(Internal.instance.getHttpUrlChecked(getURL().toString()))
```
 Request request = new Request.Builder()
        .url(Internal.instance.getHttpUrlChecked(getURL().toString()))
```

would appreciate some help 
Thank you

**Comment by yschimke** [comment]
The classes in internal packages are not stable and change frequently in each release, even minor ones.

If you need these functions you should copy them from the source code and not try to use them directly.

**Comment by natalyayyad** [comment]
Thank you @yschimke . but where exactly can I find them? I tried to search for getHttpUrlChecked but couldn't find it. is there a specific release that I can get them from?

**Comment by yschimke** [comment]
Maybe this https://github.com/square/okhttp/issues/3164

You might get a response from others, but this is code archaeology for me, so not something I can help with.
