### ISSUE TITLE
Can OkHttp support the maximum number of connections limit

### ISSUE THREAD

**Issue by manzhizhen** [square/okhttp#7084]
When using okhttp, we find that neither RealCall#execute() nor RealCall#enqueue(Callback responseCallback) can directly limit the maximum number of connections generated during traffic surge (of course, RealCall#enqueue(Callback responseCallback) can have a certain limiting effect by controlling its Dispatcher#maxRequests and Dispatcher#executorService), This may bring some risks to the system. As far as I know, HttpClient can limit the maximum number of connections through PoolingHttpClientConnectionManager#setMaxTotal, so is there any other consideration for okhttp not providing this capability?

**Comment by swankjesse** [comment]
It's on purpose. If we were to limit it, you'd have stalled threads not doing HTTP when there wasn't a connection available. This has a nasty cascading effect, and it's possible to deadlock if say, an interceptor needs to make a recursive HTTP call for authentication.

Instead we'd rather you limit the number of threads that are calling Call.execute() concurrently. Or use enqueue() which doesn't spend a thread until we have a connection for it.

**Comment by manzhizhen** [comment]
> It's on purpose. If we were to limit it, you'd have stalled threads not doing HTTP when there wasn't a connection available. This has a nasty cascading effect, and it's possible to deadlock if say, an interceptor needs to make a recursive HTTP call for authentication.
> 
> Instead we'd rather you limit the number of threads that are calling Call.execute() concurrently. Or use enqueue() which doesn't spend a thread until we have a connection for it.

Thank you for your answer
