### ISSUE TITLE
Use Map param to add Header

### ISSUE THREAD

**Issue by Joebig7** [square/okhttp#7086]
hello,when i want to request a url use okhttp,if i have heder params, i have to do like this:
```java
new Request.Builder().addHeader(key,value)
```
but if i hava several params,i hava to call this method many times,do hava i method like addHeader(Map<String,String>)，if you know please tell me thank you

**Comment by yschimke** [comment]
```
    Map<String, String> headerMap = new HashMap<>();
    Request r = new Request.Builder()
      .url("...")
      .headers(Headers.of(headerMap))
      .build();
```

Hope this helps.  Please use a forum like stackoverflow in future, we keep this for bug reports and try to build a knowledgebase in stackoverflow.

**Comment by jambestwick** [comment]
@Joebig7 plz ,note stackoverflow  URL
