### ISSUE TITLE
Is clearing web socket call's timeout causing web socket connection hang forever?

### ISSUE THREAD

**Issue by Metal-joker** [square/okhttp#7088]
I'm using OkHttp 3.12.12 and I noticed this code in `package okhttp3.internal.ws;` `public final class RealWebSocket`.
```java
  public void connect(OkHttpClient client) {
    client = client.newBuilder()
        .eventListener(EventListener.NONE)
        .protocols(ONLY_HTTP1)
        .build();
    final Request request = originalRequest.newBuilder()
        .header("Upgrade", "websocket")
        .header("Connection", "Upgrade")
        .header("Sec-WebSocket-Key", key)
        .header("Sec-WebSocket-Version", "13")
        .build();
    call = Internal.instance.newWebSocketCall(client, request);
    call.timeout().clearTimeout();
    call.enqueue(new Callback() {...});
  }
```
call's timeout is being cleared before call enqueue callbacks, will this cause the connection to hang forever if there's no response?

**Comment by yschimke** [comment]
No, call timeout is from the start of the call until it completes.  It is different for a WebSocket because it could effectively live forever. The other timeouts (read, write, connect) and the pings will ensure an unhealthy connection is detected.

**Comment by yschimke** [comment]
I'd suggest asking follow ups on stackoverflow.  Or if you think there is a bug, make a test reproducing it and we can investigate.
