### ISSUE TITLE
Documentation for HTTPS configuration

### ISSUE THREAD

**Issue by hanct** [square/okhttp#7090]
Hi,
Is there any sample codes/manual guide that show how to configure HTTPS using okhttp library. 
If not, possible to include one?

**Comment by yschimke** [comment]
HTTPS client specs etc - https://square.github.io/okhttp/features/https/

HTTPS certificate selection - https://github.com/square/okhttp/tree/master/okhttp-tls

But for more specifics, consider asking on a forum like stackoverflow.  A lot of specific details are more JDK and environment related, and we can't offer direct help with your setup.

I hope the docs help you.
