### ISSUE TITLE
allow Response.close to complete normally in all cases

### ISSUE THREAD

**Issue by jtnord** [square/okhttp#7104]
when handling a `Response` in `onResponse(Call call, Response response)`  it is cumbersome to correctly `close` the response in all cases.

This is because the `ResponseBody` may not even be read for the case that the response is not a `200`, or if the response had no body.

Currently if the `Response` has no body the code errors with an `IllegalStateException` which means a simple handling like:

```java
public void onResponse(Call call, Response response) {
   try(response) { // java try with resources ensure that all code paths always close the Response
     // lots if if conditional blocks for handling various cases
     // .....
   }
}
```

is not possible.

This means that code has to contain more boilerplate, is tedious to write, and potentially will contain more bugs.

**Comment by swankjesse** [comment]
The response passed to onResponse **always** has a body and it's unnecessary to confirm this. The only time a `Response` doesn't have a body is when it's returned from `Response.priorResponse`, `Response.networkResponse`, and `Response.cacheResponse`.
