### ISSUE TITLE
MultipartBody with Content-Type at the top, but not in the parts

### ISSUE THREAD

**Issue by sdandois** [square/okhttp#7140]
I'm communicating with a server in an embedded device that doesn't have a robust server implementation.  I need to upload a multipart form with a file on it. It works fine from Google Chrome, but doesn't work using this client.

I've realized that the problem was because the server doesn't recognize the header Content-Type inside a Body Part. This is not that uncommon, as it's mentioned in #2604.

However, the workarounds present in there are of no use for me. They work by returning `-1` in the `contentLength` method. If you do that, you also can't know the contentLength of the whole request.

If the `contentLength` of the whole request is unknown, instead of the `Content-Length` header the `Transfer-Encoding: chunked` header is used.

I want to have the Content-Length header at the top of the request, but don't want to have it inside a body part.

I've managed to solve this by rewriting the MultipartBody class, deleting the place where the `Content-Length` header is written. Since the most popular HTTP client in the world (Google Chrome) doesn't use this header, I thought it would be nice to upstream the change. 

Here is my pull: https://github.com/square/okhttp/pull/7139

**Comment by swankjesse** [comment]
Please copy MultipartBody into your project and customize to taste.
