### ISSUE TITLE
multiRequests

### ISSUE THREAD

**Issue by SudoDios** [square/okhttp#7145]
Hello.
I am working on a project and I used okhttp in it
But sometimes if the internet is weak, a request is repeated twice.
I used `retryOnConnectionFailure(false)` but I get a socketTimeOut error.
Is it possible to solve this by not sending a double request? 
Because information is important and should not be mistaken.

**Comment by yschimke** [comment]
Please ask on stackoverflow with a full code example showing the problem. We can't provide 1:1 support unless you can provide a reproducible test case.
