### ISSUE TITLE
OkHttpClient integration with Spark

### ISSUE THREAD

**Issue by juandiegoreyesponce-tomtom** [square/okhttp#7160]
Hi all,

We have a feature proposal in our project and we're planning to use distributed computing capabilities of Spark (where components are serialized and sent to Spark workers) with OkHttpClient features (where the Spark executor could make HTTP calls), but we found out that the client is not serializable at all. We have few options:

- Make a OkHttpSerializableClient extends OkHttp implements Serializable {} => The downside of this is that we cannot extend the Builder. Therefore, we cannot extend OkHttpClient timeout capabilities :( 
- Define a encoder in Kryo (but it quickly scalate since we have to tell it how to serialize every single property that OkHttpClient has)

What could be the suggestion from your side? We really need to pass the client to the Spark workers so that we can make calls in parallel.

Cheers!

**Comment by yschimke** [comment]
Can you use Call.Factory as the client API, and just make an implementation that serializes with whatever config you expect and deserializes.  The other thing I would worry about is accidentally creating thousands of clients in a single job, so perhaps consider how you have as close to one client instance.  Although you may ignore that if strict job independence is required.

**Comment by yschimke** [comment]
Not sure if there is anything left to do here. We won't open OkHttpClient to make it serializable.
