### ISSUE TITLE
HTTP FAILED: java.io.IOException: exhausted all routes

### ISSUE THREAD

**Issue by kkartheek134** [square/okhttp#7161]
While trying to use implementation 'com.squareup.okhttp3:logging-interceptor:4.9.0' in app module and my library module as well getting 

okhttp.OkHttpClient: <-- HTTP FAILED: java.io.IOException: exhausted all routes

and API call gets failed.

But if we use implementation 'com.squareup.okhttp3:logging-interceptor:4.4.1' and below, it is working perfectly.

**Comment by yschimke** [comment]
Please create a reproducible test case and reopen, we can't investigate based on this report.
