### ISSUE TITLE
enqueue is not a real async request,it is not NIO

### ISSUE THREAD

**Issue by YANGJINJUE** [square/okhttp#7162]
public void enqueue(Callback responseCallback),the method will start a threadExecutor,it means active  more threads when you send a lot of blocking requests,it is not NIO.

I have a watch case,I will send a lot of blocking requests wait the watch service changed,enqueue method will cost a lot of threads to support the operation, how to reduce the thread and it work correctly?

**Comment by JakeWharton** [comment]
`Dispatcher` has APIs to limit connections which implicitly limits threads. Ultimately you're free to supply an executor (service) and limit them however you want.

**Comment by YANGJINJUE** [comment]
> 

if limit the threads,it will limit the new  blocking requests send until the availavle threads,okhttp how to use NIO to support real async request,

**Comment by swankjesse** [comment]
OkHttp doesn't use NIO and gets good performance as a consequence. No action to take here.

**Comment by YANGJINJUE** [comment]
> 

I have a watch service case,the request will cost 1 minute to response,if I send 1000 request,it will active 1000 thread to deal the operation,it is very waste

**Comment by swankjesse** [comment]
If you need to make 1000 concurrent requests in an Android app OkHttp requires 1000 threads. This will likely exhaust memory on some devices.

I recommend setting limits on the number of concurrent requests to something smaller (256?) or switching to another HTTP client.

**Comment by YANGJINJUE** [comment]
> 

Thank you for your reply. I have found a solution,it  is Vert.x

**Comment by iseki0** [comment]
Thanks to the thread. It's a major feature about okhttp. I think it should be documented at a prominent location. By the reason, I have to use vert.x or ktor again...
