### ISSUE TITLE
Certificates are not validated after one valid connection was established

### ISSUE THREAD

**Issue by robmo90** [square/okhttp#7163]
Hi,

we've recently encountered an issue in a penetration test regarding certificate validation in our Android app which can be reproduced as follows;

1. You need to setup [Burp Suite to proxy all requests on your Android phone or emulator](https://portswigger.net/support/configuring-an-android-device-to-work-with-burp) and have the PortSwigger CA Cert installed as a system certificate (this requires a rooted Android device or emulator).
2. Create an OK Http Client and reuse it, e.g. in a click listener, to get a site via https, e.g. the ok http website.

Burp allows you to change the certificate the proxy uses, and we could observe the following behaviour; 

- If you created one valid connection with a CA-signed per-host certificate, you can then change the proxy to use self-signed certificates / signed certificates with specific hostnames, which should be declined. The client still works and approves the connection though.
- If you start using these invalid certificates, the client declines them outright until a valid certificate "unlocks" the client again and you can use invalid certificates again. 
- If you always use a fresh client, the problem does not occur.

Since the best practice is to reuse an ok http client, this looks like an issue to me. If this is intentional though, it would be good to know the reasoning for the next penetration test.

Best regards,
Rob

**Comment by yschimke** [comment]
I can take a look tonight, but what would help is output from an event listener to explain what is going on.

https://square.github.io/okhttp/features/events/

I'm not sure what declines means... the event logger output should explain a lot of this.

**Comment by robmo90** [comment]
Hey,

after analyzing the event logs and talking with the penetration tester, we came to the conclusion that this is a non-issue, since the same secure connection is re-used so the client never interacts with the invalid certificates;

OkHttp Event: call start
OkHttp Event: proxy select start
OkHttp Event: proxy select end
OkHttp Event: dns start
OkHttp Event: dns end
OkHttp Event: connect start
OkHttp Event: secure connect start
OkHttp Event: secure connect end
OkHttp Event: connect end
OkHttp Event: connection acquirted
OkHttp Event: request headers start
OkHttp Event: request headers end
OkHttp Event: response headers start
OkHttp Event: response headers end
OkHttp Event: response body start
OkHttp Event: response body end
OkHttp Event: request headers start
OkHttp Event: request headers end
OkHttp Event: response headers start
OkHttp Event: response headers end
OkHttp Event: call start
OkHttp Event: connection acquirted
OkHttp Event: request headers start
OkHttp Event: request headers end
OkHttp Event: response headers start
OkHttp Event: response headers end
OkHttp Event: response body start
OkHttp Event: response body end
OkHttp Event: request headers start
OkHttp Event: request headers end
OkHttp Event: response headers start
OkHttp Event: response headers end
