### ISSUE TITLE
Confusing round-trip latency when using persistent http connections(Connection: keep-alive)

### ISSUE THREAD

**Issue by xiaoming-qxm** [square/okhttp#7173]
Hi all, we got an unexpected high average latency(**>=40ms**) when sending 1000 http requests in a sequential order via the persistent http connections(Connection: keep-alive) to the backend server using OkHttp client. The request is built using the following code snippet:
```java
Request request = new Request.Builder()
        .url("http://localhost:10000/test")
        .header("Connection", "keep-alive")
        .build();
``` 
However the average latency decreases to less than **3ms** which we expect when we modify the request header *Connection* from `keep-alive` to `close`. 
```java
Request request = new Request.Builder()
        .url("http://localhost:10000/test")
        .header("Connection", "close")
        .build();
``` 

This is very weird for the http *Connection* header. Is there any explanation for this?

For reproduction, the following is the complete client-side and server-side code. The OkHttp version 4.8.0

Client-side code: 
```java
public static void main( String[] args ) {
    OkHttpClient httpclient = new OkHttpClient.Builder().build();
    OkHttpClient okclient = httpclient.newBuilder()
                                .readTimeout(5000, TimeUnit.MILLISECONDS)
                                .connectTimeout(5000, TimeUnit.MILLISECONDS)
                                .connectionPool(new ConnectionPool(10, 5000, TimeUnit.MILLISECONDS))
                                .build();

    int iters = 1000;
    Request request = new Request.Builder()
        .url("http://localhost:10000/test")
        .header("Connection", "close")
        .build();
   
     // Request request = new Request.Builder()
     //   .url("http://localhost:10000/test")
     //   .header("Connection", "close")
     //   .build();

    Instant start = Instant.now();
    for (int i = 0; i < iters; ++i) {
        try {
            Response response = okclient.newCall(request).execute();
            response.body().close();
        } catch (Exception e) {
            continue;
        }
    }
    Instant end = Instant.now();
    Duration timeElapsed = Duration.between(start, end);
    System.out.println("OkTest Time taken: "+ timeElapsed.toMillis() +" milliseconds");
}
```

Server-side code: (using cpp-httplib(https://github.com/yhirose/cpp-httplib), but also cross-validated by other http servers)
```cpp
int main(void) {
  Server svr;
  svr.set_keep_alive_max_count(100);
  svr.set_keep_alive_timeout(10000);

  svr.Get("/test", [](const Request & /*req*/, Response &res) {
    std::string content(64, 'a');
    res.set_content(content, "text/plain");
  });
  svr.listen("0.0.0.0", 10000);
}
```

**Comment by yschimke** [comment]
Thanks.  What would help debugging it quicker would be a trace of events using an EventListener.

https://square.github.io/okhttp/features/events/

You could maybe add the event listener but making sure to log some incrementing counter for each call. We could see the call start, end, the connection acquiring etc, and pin down where it's happening.

**Comment by swankjesse** [comment]
...I must admit that 40 milliseconds vs. 3 milliseconds is a lot here. I would have expected our heuristic to take effectively 0 ms for a 64-byte body. That’s surprising and I’d love to see what EventListener tells us.

**Comment by xiaoming-qxm** [comment]
UPDATE: The high latency(>=40ms) comes from bad interaction between Nagle's algorithm and delayed ack features of TCP. Aka, the famous "40ms bug"
