### ISSUE TITLE
Consider supporting Call.Factory for API 15

### ISSUE THREAD

**Issue by yschimke** [square/okhttp#7175]
> OkHttp works on Android 5.0+ (API level 21+) and Java 8+.

Since the driving reason was secure connectivity, should we allow a Call.Factory for Cronet or EnvoyMobile to decide to suppor down to 15 (the Okio min?)

https://github.com/envoyproxy/envoy-mobile/blob/d15598e31be615ef672c08aef781a5b4216632c8/library/java/org/chromium/net/ChromiumNetManifest.xml#L5

Is there anything else blocking this? Or is it purely a docs change since okhttp core is a JAR so doesn't specify versions. Does R8 Java 8 support (https://developer.android.com/studio/write/java8-support) get us down there also?

From https://code.cash.app/okhttp-3-13-requires-android-5

> Today we’re releasing OkHttp 3.13. With this update we’re bumping the project’s requirements from this:
> 
> Android 2.3+ / API 9+ (released December 2010)
> Java 7+ (released July 2011)
> to this:
> 
> Android 5.0+ / API 21+ (released November 2014)
> Java 8+ (released March 2014)
> ...
> 
> Now it’s time to drop both TLSv1 and TLSv1.1 and to make TLSv1.2 the Internet’s new minimum standard. On October 15 our colleagues at [Google](https://security.googleblog.com/2018/10/modernizing-transport-security.html), [Mozilla](https://blog.mozilla.org/security/2018/10/15/removing-old-versions-of-tls/), [Microsoft](https://blogs.windows.com/msedgedev/2018/10/15/modernizing-tls-edge-ie11/), and [Apple](https://webkit.org/blog/8462/deprecation-of-legacy-tls-1-0-and-1-1-versions/) announced that their browsers will require TLSv1.2 or better starting in early 2020.
> 
> Google added support for TLSv1.2 in Android 5.0. Oracle added it in Java 8. In OkHttp 3.13 we require that the host platform has built-in support for TLSv1.2.

**Comment by swankjesse** [comment]
It's probably just a docs change but I'd prefer to not make the docs change. I think there might be other things we've broken on API 15 either deliberately or accidentally.

Either way I think it's too complicated a message to say we support API 15 but only without HTTPS.

I want our users to get good performance and very good security without fuss when they use OkHttp. This comes at a cost in device support; currently at 1.1% of the device population.

Teams that need to support 100% of the device population have a difficult problem! Using Cronet or Envoy on 7+-year-old devices is also going to be tough work! I don't want to sign up for it.

**Comment by yschimke** [comment]
It wasn't without HTTPS.  I meant just declaring that the API is supported if you use Cronet or Envoy and they ship a module that works down to that version.

But let's close if no appetite.  If it's not officially supported, you can still use the Call.Factory interface, and we could fix most problems using a missing Java API feature by using a kotlin alternative that compiles down.
