### ISSUE TITLE
Missing class when release with Android Studio

### ISSUE THREAD

**Issue by vTechGIS** [square/okhttp#7183]
I use Okhttp v4.9.3 and got this warning when releasing apk file on Android Studio. What do i need to do to fix the problem?

Thank you very much,

`Missing class org.bouncycastle.jsse.BCSSLParameters (referenced from: void okhttp3.internal.platform.BouncyCastlePlatform.configureTlsExtensions(javax.net.ssl.SSLSocket, java.lang.String, java.util.List) and 1 other context)
Missing class org.bouncycastle.jsse.BCSSLSocket (referenced from: void okhttp3.internal.platform.BouncyCastlePlatform.configureTlsExtensions(javax.net.ssl.SSLSocket, java.lang.String, java.util.List) and 5 other contexts)
Missing class org.bouncycastle.jsse.provider.BouncyCastleJsseProvider (referenced from: void okhttp3.internal.platform.BouncyCastlePlatform.<init>())
Missing class org.conscrypt.Conscrypt$Version (referenced from: boolean okhttp3.internal.platform.ConscryptPlatform$Companion.atLeastVersion(int, int, int))
Missing class org.conscrypt.ConscryptHostnameVerifier (referenced from: okhttp3.internal.platform.ConscryptPlatform$DisabledHostnameVerifier)
Missing class org.openjsse.javax.net.ssl.SSLParameters (referenced from: void okhttp3.internal.platform.OpenJSSEPlatform.configureTlsExtensions(javax.net.ssl.SSLSocket, java.lang.String, java.util.List))
Missing class org.openjsse.javax.net.ssl.SSLSocket (referenced from: void okhttp3.internal.platform.OpenJSSEPlatform.configureTlsExtensions(javax.net.ssl.SSLSocket, java.lang.String, java.util.List) and 1 other context)
Missing class org.openjsse.net.ssl.OpenJSSE (referenced from: void okhttp3.internal.platform.OpenJSSEPlatform.<init>())`

**Comment by yschimke** [comment]
There isn't an easy fix.  OkHttp compiles against (but doesn't depend) various libraries so it has a single jar that works on various android versions, and various JVM versions.  You shouldn't fix these by including them, so unfortunately you will probably have to live with the warning.

It isn't fatal, and I don't know how to disable this warning.

**Comment by yamin8000** [comment]
> It isn't fatal, and I don't know how to disable this warning.

Not really. I got this warning too when releasing APK; unfortunately, no HTTPS requests work in the release version.
