### ISSUE TITLE
Provide override-able methods that allow customization of Builder

### ISSUE THREAD

**Issue by czee** [square/okhttp#7193]
The main problem I am trying to solve is to disable self signed certificate validation with a client that extends OkHttp.

Extending `OkHttpClient` is difficult when there is no method that accepts a `Builder` or when the `OkHttpClient` has no public constructor that accepts `Builder` (currently internal).

Are there any plans to implement a flag that disables self signed certificate validation or give OkHttp greater class visibility?

**Comment by yschimke** [comment]
OkHttpClient shouldn't (and can't) be extended.

You can use `client.newBuilder().sslSocketFactory(..., ...).build()` to create a new client from an existing one and change what you need.
