### ISSUE TITLE
signal 6 (SIGABRT)

### ISSUE THREAD

**Issue by dingjiaxing** [square/okhttp#7221]
android 7.1.1 ssl's problem, because our project only okhttp about ssl

#00 pc 0004a188  /system/lib/libc.so (tgkill+12)   
#01 pc 00047903  /system/lib/libc.so (pthread_kill+34)   
#02 pc 0001d7e5  /system/lib/libc.so (raise+10)   
#03 pc 00019321  /system/lib/libc.so (__libc_android_abort+34)   
#04 pc 00017388  /system/lib/libc.so (abort+4)   
#05 pc 0001b7df  /system/lib/libc.so (__libc_fatal+22)   
#06 pc 00066f9f  /system/lib/libc.so (ifree+962)   
#07 pc 00067067  /system/lib/libc.so (je_free+74)   
#08 pc 0001b783  /system/lib/libssl.so (SSL_clear+102)   
#09 pc 0000fb0d  /system/lib/libjavacrypto.so   
#10 pc 0007b0fb  /system/framework/arm/boot-conscrypt.oat (offset 0x6c000) (com.android.org.conscrypt.NativeCrypto.SSL_shutdown+142)   
#11 pc 00094151  /system/framework/arm/boot-conscrypt.oat (offset 0x6c000) (com.android.org.conscrypt.OpenSSLSocketImpl.shutdownAndFreeSslNative+100)   
#12 pc 00094849  /system/framework/arm/boot-conscrypt.oat (offset 0x6c000) (com.android.org.conscrypt.OpenSSLSocketImpl.close+372)   
#13 pc 03c81d37  /data/app/plg-2/oat/arm/base.odex (offset 0x3937000)

**Comment by yschimke** [comment]
You should raise a bug with https://github.com/google/conscrypt.  But I doubt they can fix it.
