### ISSUE TITLE
signal 11 (SIGSEGV)

### ISSUE THREAD

**Issue by dingjiaxing** [square/okhttp#7222]
android 7.1.1 ssl's problem

#00 pc 00012ada  /system/lib/libssl.so   
#01 pc 00012665  /system/lib/libssl.so   
#02 pc 00012b13  /system/lib/libssl.so   
#03 pc 00019ef5  /system/lib/libssl.so (SSL_shutdown+136)   
#04 pc 0000fac9  /system/lib/libjavacrypto.so   
#05 pc 0007b0fb  /system/framework/arm/boot-conscrypt.oat (offset 0x6c000) (com.android.org.conscrypt.NativeCrypto.SSL_shutdown+142)   
#06 pc 00094151  /system/framework/arm/boot-conscrypt.oat (offset 0x6c000) (com.android.org.conscrypt.OpenSSLSocketImpl.shutdownAndFreeSslNative+100)   
#07 pc 00094849  /system/framework/arm/boot-conscrypt.oat (offset 0x6c000) (com.android.org.conscrypt.OpenSSLSocketImpl.close+372)   
#08 pc 03c42585  /data/app/pkg-1/oat/arm/base.odex (offset 0x391f000)

**Comment by yschimke** [comment]
You should raise a bug with https://github.com/google/conscrypt.  But I doubt they can fix it.
