### ISSUE TITLE
Kotlin operator for HttpUrl

### ISSUE THREAD

**Issue by yschimke** [square/okhttp#7233]
Inspired by Okio Path

```
    val aiortc = "https://cloudflare-quic.com/b/".toHttpUrl()
    
    val postRequest =
      Request(
        url = aiortc + "post",
        body = "{}".toRequestBody("application/json".toMediaType())
      )
```

```
private operator fun HttpUrl.plus(link: String): HttpUrl {
  return this.resolve(link)!!
}
```

**Comment by JakeWharton** [comment]
Resolve is not necessarily additive, though. This is surprising: `"http://foo.com/bar".toHttpUrl() + "/baz"`.

**Comment by swankjesse** [comment]
Yeah, also the way this interacts with queries could be surprising. I think the most tempting options are `[]` accessors for path segments or query parameters, and I think that’s also a tough sell cause it's not necessary obvious which applies where.

**Comment by yschimke** [comment]
Makes sense, thought it worth asking.
