### ISSUE TITLE
EventListener.secureConnectStart() is suspend in case of setting the phone time to future

### ISSUE THREAD

**Issue by hyvenzhu** [square/okhttp#7235]
I am using okhttp-3.14.7 library.

Case：Set the phone time to future

The following method of EventListener has been called，but no more method was called any more. 

callStart
dnsStart
dnsEnd
connectStart
secureConnectStart

**Comment by yschimke** [comment]
Can you post your EventListener implementation? SSL connections will fail if time is wrong, so almost certainly it's not hanging or suspending, just failing and throwing an exception.

Please reopen if you can provide a reproducible test case that shows it hanging when the time is changed on an emulator.
