### ISSUE TITLE
For custom provider, ALPN extension cannot be enabled in devices below android api 29.

### ISSUE THREAD

**Issue by love-ginger** [square/okhttp#7238]
We currently use a custom Provider, and support devices lower than Android API 29 to use TLS1.3, but during testing, we found that devices lower than Android API 29 cannot use HTTP2.0 protocol, and subsequent debugging found that `AndroidPlatform` restricts the SSLSocket class. SSLSocket must be the `com.android.org.conscrypt.OpenSSLSocketImpl` class to allow the `configureTlsExtensions` implementation to be executed.

Can someone tell why there is such a restriction?

```kotlin
  override fun configureTlsExtensions(
    sslSocket: SSLSocket,
    hostname: String?,
    protocols: List<Protocol>
  ) {
    // No TLS extensions if the socket class is custom.
    if (matchesSocket(sslSocket)) {
      try {
        // Enable session tickets.
        setUseSessionTickets.invoke(sslSocket, true)

        if (hostname != null) {
          // This is SSLParameters.setServerNames() in API 24+.
          setHostname.invoke(sslSocket, hostname)
        }

        // Enable ALPN.
        setAlpnProtocols.invoke(
            sslSocket,
            Platform.concatLengthPrefixed(protocols)
        )
      } catch (e: IllegalAccessException) {
        throw AssertionError(e)
      } catch (e: InvocationTargetException) {
        throw AssertionError(e)
      }
    }
  }

```

**Comment by swankjesse** [comment]
There's no public API for ALPN until API 29.
https://developer.android.com/reference/javax/net/ssl/SSLSocket#setHandshakeApplicationProtocolSelector(java.util.function.BiFunction%3Cjavax.net.ssl.SSLSocket,%20java.util.List%3Cjava.lang.String%3E,%20java.lang.String%3E)

**Comment by love-ginger** [comment]
> There's no public API for ALPN until API 29. https://developer.android.com/reference/javax/net/ssl/SSLSocket#setHandshakeApplicationProtocolSelector(java.util.function.BiFunction%3Cjavax.net.ssl.SSLSocket,%20java.util.List%3Cjava.lang.String%3E,%20java.lang.String%3E)

But my custom SSLSocket class implement `setAlpnProtocols` methods.

**Comment by love-ginger** [comment]
> There's no public API for ALPN until API 29. https://developer.android.com/reference/javax/net/ssl/SSLSocket#setHandshakeApplicationProtocolSelector(java.util.function.BiFunction%3Cjavax.net.ssl.SSLSocket,%20java.util.List%3Cjava.lang.String%3E,%20java.lang.String%3E)

I tested it with okhttp 3.12.1, there is no restriction of SSLSocket class, and the HTTP2.0 protocol can be used normally.

**Comment by swankjesse** [comment]
We don't want to use reflection on unknown classes. Your class might work, but a custom Android OEM’s SSLSocketFactory might crash if we call this function. We try to be conservative when using non-public APIs.

**Comment by love-ginger** [comment]
> We don't want to use reflection on unknown classes. Your class might work, but a custom Android OEM’s SSLSocketFactory might crash if we call this function. We try to be conservative when using non-public APIs.

Can you add an interface that allows app to set a custom provider `Platform` instead of the default `AndroidPlatform`, like `ConscryptPlatform`.

**Comment by love-ginger** [comment]
Or remove the restriction and add try catch in the reflection code, and check reflection method exists in target class first.

**Comment by swankjesse** [comment]
Calling functions reflectively is dangerous and I'm reluctant to do it, even if it's present in the API.

**Comment by swankjesse** [comment]
I think the feature request is, ‘recommended way to enable TLSv1.3 on older Android devices’ right?

**Comment by love-ginger** [comment]
> I think the feature request is, ‘recommended way to enable TLSv1.3 on older Android devices’ right?

maybe 'enable TLSv1.3+HTTP2.0(ALPN Extension) on below Android 10 devices for custom Provider'

**Comment by yschimke** [comment]
Is this a publicly documented Provider? If you use Conscrypt this should work.

Which version of OkHttp are you running against?  The current implementation supports providers via SocketAdaptors, so the different forms of Conscrypt can work. 

https://github.com/square/okhttp/blob/okhttp_4.10.x/okhttp/src/main/kotlin/okhttp3/internal/platform/AndroidPlatform.kt#L46

**Comment by love-ginger** [comment]
> Is this a publicly documented Provider? If you use Conscrypt this should work.
> 
> Which version of OkHttp are you running against? The current implementation supports providers via SocketAdaptors, so the different forms of Conscrypt can work.
> 
> https://github.com/square/okhttp/blob/okhttp_4.10.x/okhttp/src/main/kotlin/okhttp3/internal/platform/AndroidPlatform.kt#L46
> 
> I'm with @swankjesse here, we don't want public API for this, as it will be hard to support clients that change this. There is an internal API to reset the Platform, but this can be changed at any moment, so I would advise against using it.
> 
> ```
>     fun resetForTests(platform: Platform = findPlatform()) {
>       this.platform = platform
>     }
> ```

The SSLSocket type restriction is from okhttp-3.13, we are not using ConscryptProvider, but a custom implemented Provider. We found that even devices below Android 10 can support HTTP2 using the system's SSLSocket, but the custom SSLSocket that supports ALPN cannot use HTTP2 because it is not android system SSLSocket class.

**Comment by love-ginger** [comment]
Restriction starts with the following commit

[Restore support for custom trust managers on Android ](https://github.com/square/okhttp/pull/4593/commits/ad8d8099a5e475475ddce44cde1b5e1d360990c4)

**Comment by yschimke** [comment]
3.x is unmaintained, so we wouldn't make any changes on that branch.

You may find it easiest to fork 3.x and make the changes you need.

**Comment by yschimke** [comment]
@swankjesse this code frequently changes so it's terrible public API. If we ever decided to support this, then DeferredSocketAdapter.Factory is probably the API. Making Platform, effectively public API would be even worse.

```
  interface Factory {
    fun matchesSocket(sslSocket: SSLSocket): Boolean
    fun create(sslSocket: SSLSocket): SocketAdapter
  }
```

**Comment by yschimke** [comment]
> > I think the feature request is, ‘recommended way to enable TLSv1.3 on older Android devices’ right?
> 
> maybe 'enable TLSv1.3+HTTP2.0(ALPN Extension) on below Android 10 devices for custom Provider'

Is the custom Provider just to support TLSv1.3+HTTP2.0? If so, you can do this with the ProviderInstaller, or bundling Conscrypt.

**Comment by love-ginger** [comment]
> > > I think the feature request is, ‘recommended way to enable TLSv1.3 on older Android devices’ right?
> > 
> > 
> > maybe 'enable TLSv1.3+HTTP2.0(ALPN Extension) on below Android 10 devices for custom Provider'
> 
> Is the custom Provider just to support TLSv1.3+HTTP2.0? If so, you can do this with the ProviderInstaller, or bundling Conscrypt.
> 
> If it's more than this, then it could help understand the relevance and importance of your specific Custom Provider.

Sorry, We must use the custom Provider, and wo found there are many Platforms that adapt to different Providers in the source code. In fact, we also want to implement our custom Platform to support custom Provider, This can eliminate the need to use reflection. But Platform is an internal implementation.

**Comment by swankjesse** [comment]
Agreed that Platform won't work as a public API.

@love-ginger could you expand on what your needs are? I like learning what problem people are trying to solve when considering potential solutions!

**Comment by love-ginger** [comment]
> 

At least a non-system SSLSocket can enable ALPN in `configureTlsExtensions` function.

**Comment by yschimke** [comment]
@swankjesse a minimal API for this would be to allow something like 

`Platform.get().registerSocketAdapter(sa)`

And make this public API?

```
interface SocketAdapter {
  fun isSupported(): Boolean
  fun trustManager(sslSocketFactory: SSLSocketFactory): X509TrustManager? = null
  fun matchesSocket(sslSocket: SSLSocket): Boolean
  fun matchesSocketFactory(sslSocketFactory: SSLSocketFactory): Boolean = false

  fun configureTlsExtensions(
    sslSocket: SSLSocket,
    hostname: String?,
    protocols: List<Protocol>
  )

  fun getSelectedProtocol(sslSocket: SSLSocket): String?
}
```

@swankjesse I don't think the payoff is there for opening up Platform, but without that or this above, we are gatekeepers for supporting new Providers.  Like Amazon Corretto for JVM instead of Android, which we added because I expected some people to be running production workloads on it.  I'm not convinced a public `registerSocketAdapter` is wise, but can see the argument.

**Comment by swankjesse** [comment]
Yeah I’d prefer we live by the API limitations of the Java sockets APIs. We do limited ‘progressive enhancement’ when we have a very well known implementation via Platform internals, but I don't think it's appropriate for us to open up this as a user API.

One example we aught to confirm we can handle: HTTP/2 + TLSv1.3 on older devices that have the Google Play Services location provider installed. That could be out recommended configuration for people with @love-ginger’s general needs. (Understanding that Play Services is Google’s proprietary AOSP-based product and not on all devices we target.)

**Comment by yschimke** [comment]
@swankjesse I've tested this before, and found issues which led to the whole SocketAdapter approach.  But I can check again.

I'm going to close this one so we don't just keep discussing it without saying it.
