### ISSUE TITLE
Fatal Exception: java.lang.IllegalStateException: Unable to take ownership of connection

### ISSUE THREAD

**Issue by rohitkeszoom** [square/okhttp#7239]
As mentioned here Issue #7237, we are facing below issue 
We have the latest version of okhttp 4.9.3 implemented along with com.github.nkzawa:socket.io-client:0.6.0
![image](https://user-images.githubusercontent.com/100447505/163391744-8a207c0d-ff00-4234-bc35-bf4ac33d14e3.png)

Could you please check if the issue is still persisting in the version of okhttp 4..9.3

**Comment by yschimke** [comment]
You'll need to provide a repro for us to investigate.  But generally probably simpler if you update, and confirm whether the problem still exists.  We can't provide support for older versions, so if it does still exist and you can reproduce it, that would be the first step we need to fix it.

Jake: "This should have been fixed as a side-effect of the stream allocation model. Please re-open if it's still a problem on version 3.4.0 or newer."

**Comment by rohitkeszoom** [comment]
thanks for valuable feedback, yes we have updated many other libraries used in our project to latest versions and will release new version of our app, if it has been due to side effect of other old libraries which is now upgraded we should not be facing this issue and will update on this once our app is updated on playstore
