### ISSUE TITLE
after idel for 5 mins the socket is exhausted and route cannot reuse

### ISSUE THREAD

**Issue by pokemondalao** [square/okhttp#7243]
okhttp3.internal.connection.RealConnection#isHealthy
source.exhausted()

this source will return true and the route can't be reuse after 5 mins.

**Comment by swankjesse** [comment]
Unclear what action to take on this. Please describe your expected behavior and what OkHttp did differently?

**Comment by yschimke** [comment]
Please reopen with more information.
