### ISSUE TITLE
JUnit 4 gets published as compile dependency, i.e. becomes a transitive dependency in projects using mockwebserver

### ISSUE THREAD

**Issue by cebence** [square/okhttp#7249]
This is not a bug in the functionality of mockwebserver, but a bug in packaging the `pom.xml` in the JAR (I suppose, haven't used Gradle).

## Step to reproduce

1. Create a (Maven) project and add JUnit 5 as test dependency (or open an existing project that uses JUnit 5) in your IDE of choice.
2. Add the `mockwebserver` as a test dependency to the project.
3. Create a test class, type in "Test" and invoke intellisense.

## Expected behavior

Intellisense offers `org.junit.jupiter.api.Test` from JUnit 5, as that is the testing library specified in the project.

## Actual behavior

Intellisense offers both `org.junit.Test` (JUnit 4) and `org.junit.jupiter.api.Test`. The former one is the first in the pick list so I need to be very careful when doing this.

## Some help

Notice the JUnit `compile` dependency in the `https://repo1.maven.org/maven2/com/squareup/okhttp3/mockwebserver/4.9.3/mockwebserver-4.9.3.pom` file.
I suppose the POM is generated by Gradle.

**Comment by swankjesse** [comment]
Upgrade to the latest 5.0 alpha. Should be fixed there, as we've created a new MockWebServer artifact with no JUnit dependency.

**Comment by cebence** [comment]
I just checked the 5.0 POM (https://repo1.maven.org/maven2/com/squareup/okhttp3/mockwebserver/5.0.0-alpha.6/mockwebserver-5.0.0-alpha.6.pom), JUnit is compile dependency too.

**Comment by cebence** [comment]
This might be an issue with the Gradle POM plugin (or whatever this is):
https://github.com/square/okhttp/blob/master/build.gradle.kts#L213

**Comment by JakeWharton** [comment]
The dependency is correct. It's a test artifact for JUnit 4. You'll want to use mockwebserver-junit5.

**Comment by cebence** [comment]
OK, will https://mvnrepository.com/artifact/com.squareup.okhttp3/mockwebserver3-junit5 a try. Thanks.

**Comment by cebence** [comment]
Yup, that resolves the issue 😄 Thanks.
