### ISSUE TITLE
Support multiple segments of headers and data on the same stream in HTTP/2

### ISSUE THREAD

**Issue by codefromthecrypt** [square/okhttp#725]
Arguably under-documented in the spec, the END_SEGMENT flag for HEADERS and DATA frames allows you to send many interleaved segments of headers and data per stream.  For example, you can send the following:

```
    HEADERS (request headers)   +END_HEADERS
    DATA
    HEADERS (for attributes related to the data) +END_SEGMENT  +END_HEADERS
    DATA
    HEADERS (for attributes related to the data) +END_SEGMENT  +END_HEADERS
    HEADERS (for request footers)  +END_HEADERS  +END_STREAM
```

This mandatory feature of HTTP/2 draft 10+ can be used for things such as gzip contexts per segment, porting 1.1 chunked encoding, and layering protocols like WebSocket over HTTP/2.

Here's a more comprehensive explanation by @jpinner:

```
END_SEGMENTS allows the layering of record-based semantics onto the framing layer.

Consider this use case in HTTP/1.1. An API provides a stream of data using HTTP/1.1 chunked encoding. Each chunk contains a single record, and the length of this record is indicated by the chunk length. In HTTP/1.1 the length of these chunks was unconstrained, but when translating into HTTP/2, these chunks must be segmented into multiple data frames to fit within the frame size limit.

If the chunk delineation was meaningful, then END_SEGMENT allows this meaning to be preserved.

The flag is also useful for layering other record-based protocols on top of HTTP.
```

**Comment by jcoatgoogle** [comment]
A concrete use case for trailers is GRPC...

http://www.grpc.io/docs/guides/wire.html

GRPC uses trailers on both request and response. I was attempting to use OkHttp with GRPC and this complicated things (I have somewhat been able to get around it since you can sometimes guess what grpc-status is, but that's a hack, and while maybe not enough to motivate you to add trailers, this is a case where they are used :)

**Comment by jhump** [comment]
@jcoatgoogle, to use okhttp with grpc, I'd recommend just using the [grpc-provided library](https://mvnrepository.com/artifact/io.grpc/grpc-okhttp).

Admittedly, it doesn't use an okhttp library that you can link against. Instead, it has a version [shaded into their library](https://github.com/grpc/grpc-java/tree/master/okhttp/third_party/okhttp).

Also, it doesn't use the standard okhttp APIs, so this issue wasn't a blocker. Instead, the core grpc stream and transport implementations use okhttp's lower-level classes (the actual http/2 protocol implementation) [directly](https://github.com/grpc/grpc-java/blob/master/okhttp/src/main/java/io/grpc/okhttp/OkHttpClientTransport.java#L59).

**Comment by jcoatgoogle** [comment]
Thank you for the explanation!
