### ISSUE TITLE
Why does this project use kotlin version 1.4.10?

### ISSUE THREAD

**Issue by jeffreyxuworld** [square/okhttp#7251]
Why does this project use kotlin version 1.4.10, not 1.6.20 ?

**Comment by JakeWharton** [comment]
Keeping the Kotlin version low means greater support for usage in locations like IntelliJ plugins and Gradle plugins where the Kotlin version may be forced to be older than the latest. Gradle is an especially bad actor here.

**Comment by yschimke** [comment]
Agreed - Kotlin has always been really careful to be forward compatible (is that the right word).

With that said there is a version bump on the soon to be released 4.10.x branch.

https://github.com/square/okhttp/pull/7225/files

@JakeWharton do you have concerns about this proactive bump, I wanted to separate these out from the 5.x release.

**Comment by JakeWharton** [comment]
The only place of real concern is inside the Gradle buildscript classpath where Kotlin is forced to a ridiculous old version. As far as I know, Gradle does not maintain a public page with a mapping from their version to the outdated Kotlin version they forced on plugins and build scripts. It's only a problem in practice if you use a newer stdlib API which the 4.x branch does not.

I'm still against shipping a 4.x with a newer version of Kotlin simply to silence broken CVE tooling, though.
