### ISSUE TITLE
Make UnreadableResponseBody visible

### ISSUE THREAD

**Issue by NicolaVerbeeck** [square/okhttp#7262]
In 5.0.0-alpha7 unreadable response bodies are no longer returned as null but instead are an opaque non-readable body. This unreadable body class is also internal. For network inspection tools such as [Niddler](https://github.com/Chimerapps/niddler) that have a generic 'read this body' method, we can not check if a response body will be readable or not, only relying on catching the thrown exception.

Suggestion: make `UnreadableResponseBody` visible again, the alternative would be a field on ResponseBody that indicates if it can be read or not (which adds pollution to the general use API).

**Comment by swankjesse** [comment]
How does it even get a reference to these unreadable bodies? They're never the body of tbe response that the application layer interacts with.

**Comment by NicolaVerbeeck** [comment]
```java
   final Response networkResponse = response.networkResponse();

   // Somewhere down the line
   serializeBody(networkResponse.body())
```

**Comment by swankjesse** [comment]
If we change it to an IOException, does that work for you? I don't want to make this API public.

**Comment by yschimke** [comment]
Reopening - it's something that has observably changes between 4.x and 5.x so we should agree a plan, or document that this use case is no longer possible in 5.x.

**Comment by swankjesse** [comment]
We've already documented that the response body is not readable on these special response objects.

We’re going from ‘you can't read it because it’s null’ to ‘you can’t read it even though it’s not null’, which is certainly more annoying in generic use cases. But unsupported operations is not new and rarely problematic; like forbidding `add()` on a `Collections.emptyList()`

**Comment by NicolaVerbeeck** [comment]
Except that network responses did not use to return null

**Comment by swankjesse** [comment]
I think they did?

https://github.com/square/okhttp/blob/parent-4.10.0-RC1/okhttp/src/main/kotlin/okhttp3/Response.kt#L394

**Comment by NicolaVerbeeck** [comment]
Yes, thanks for helping me out here, I have some new ideas on how to improve the inspector
