### ISSUE TITLE
Possibility to use addUnsafeNonAscii header on Request.Builder

### ISSUE THREAD

**Issue by iruizmar** [square/okhttp#7275]
When trying to add new headers inside an interceptor, I usually do the following:
```kotlin
OkHttpClient.Builder()
    .addInterceptor { chain ->
        chain.proceed(
             chain.request()
                 .newBuilder()
                 .addHeader(X, Y)
                 .build()
        )
    }
```
But what if I want to use the internal header builder `addUnsafeNonAscii` method? There isn't any shortcut for that.
The workaround is something like:

```kotlin
OkHttpClient.Builder()
    .addInterceptor { chain ->
        chain.proceed(
             chain.request()
                 .newBuilder()
                 //We need to use headers already in the request.
                 .headers(chain.request().headers.newBuilder().apply {
                     addUnsafeNonAscii(X, Y)
                 }.build())
                 .build()
        )
    }
```

It would be easy to add a new `addUnsafeNonAscii` method to `Request.Builder` that will use the internal header builder's `addUnsafeNonAscii`.

**Comment by yschimke** [comment]
This was a deliberate API decision https://github.com/square/okhttp/pull/4296#issuecomment-425671681

I think it's the right call, technically possible but not a suggestion on the easy path.  Since it's possible but more verbose, I'm going to close this.
