### ISSUE TITLE
The class HttpDate had been remove ?

### ISSUE THREAD

**Issue by landsnail** [square/okhttp#7277]
when i want use HttpDate to parse server Date , i found that HttpDate cannot import
my okhttp3 version is 5.0.0-alpha2

Date parse = HttpDate.parse(standardTime);

if i want use that function , how can i do?

**Comment by yschimke** [comment]
It's in the internal package not part of our public API.

If you need it, copy it into your codebase.

https://github.com/square/okhttp/blob/3ad1912f783e108b3d0ad2c4a5b1b89b827e4db9/okhttp/src/jvmMain/kotlin/okhttp3/internal/http/dates.kt

or the older java version https://raw.githubusercontent.com/square/okhttp/33db7d9ef67ebc876fac50aea7eee7d81ff4bc2f/okhttp/src/main/java/okhttp3/internal/http/HttpDate.java
