### ISSUE TITLE
Hello, may I ask how HTTP head of line blocking is implemented?🙉

### ISSUE THREAD

**Issue by WuJingLearn** [square/okhttp#7291]
Hello, may I ask how HTTP head of line blocking is implemented?

**Comment by yschimke** [comment]
This isn't really a general support forum. I'd suggest asking in other forums for this type of question. We try to keep this for tracking bugs and feature requests.

StackOverflow or an Android Slack is probably a better place than here. 

Or you might want to read up on HTTP/2 and the existing docs on connection pools first.
