### ISSUE TITLE
Use MockWebServer to test ConnectionTimeoutException

### ISSUE THREAD

**Issue by dorus-private** [square/okhttp#7300]
Hi team, 
I was searching to find out if there is a way to use MockWebServer to simulate a connection timeout exception. Could you please help me in this issue?
Thank you very much,
Doru

**Comment by yschimke** [comment]
I don't think it's possible with MockWebServer directly. It's pretty good at accepting sockets and then handing them off without blocking, and without applying any policy.

I suspect best options are to mess with the client. Either a SocketFactory that throws that exception, or Dns to an unresolvable host.

```
      client = client.newBuilder()
        .dns(Dns {
          listOf(Inet4Address.getByName("192.0.2.0"))
        })
        .build()
```

Please use a site like stackoverflow in future for such questions, and if you have more questions, please post a link to SO and I can answer there.
