### ISSUE TITLE
Http2 stream was reset: CANCEL

### ISSUE THREAD

**Issue by qyxghcl** [square/okhttp#7310]
https://gist.github.com/qyxghcl/04aadf6de5cfe62b298c5b7a2774d8fa

**Comment by qyxghcl** [comment]
This problem occurs in Http2.0. 
As is shown above, 
if I use content, it will throw stream was reset: CANCEL.
if I use content2, it will preform will.
It seems like length is the point.

**Comment by qyxghcl** [comment]
I found that  
if I use content, Http2Reader (nextFrame):  TYPE_SETTINGS -> TYPE_WINDOW_UPDATE -> TYPE_SETTINGS -> TYPE_GOAWAY
if I use content2,Http2Reader (nextFrame): TYPE_SETTINGS -> TYPE_WINDOW_UPDATE -> TYPE_SETTINGS -> TYPE_WINDOW_UPDATE -> TYPE_HEADERS -> TYPE_DATA -> TYPE_GOAWAY

**Comment by swankjesse** [comment]
It it possible the server is canceling the stream because the URL is too long?

**Comment by LouisShark** [comment]
What should I do in this situation , Is there a solution for okhttp?

**Comment by swankjesse** [comment]
If the server has a maximum URL size you'll encounter it for every HTTP client.

**Comment by LouisShark** [comment]
It sounds like the client needs to limit the length of the upload url

**Comment by qyxghcl** [comment]
Yes, the server has a maximum URL size. But I find that it will perform well if I use Http1.1 at the same URL. And sometimes http2 fail then it will degrade to Http1.1, but most time it will not. If there is a solution for making this degrade stable？

**Comment by swankjesse** [comment]
Seems likely server-dependent. Avoiding super long URLs is the best fix.
