### ISSUE TITLE
Performance problems with Http2

### ISSUE THREAD

**Issue by mrozk** [square/okhttp#7346]
Hi! Guys, it seems that OkHttpClient has problems with performance on HTTP_2. We are testing HTTP_2 on our microservices. Our client uses Feign and Spring Cloud Loadbalancer under the hood and we added OkHttpClient with HTTP_2 enabled(PRIOR_KNOWLEDGE). Our downstream service is a cluster of 120 pods. We saw that resource consumption was increased several times, especially threads count. We did a thread dump and saw, that OkHttpClient creates a thread per a connection, although OkHttpClient with HTTP_1 doesn't do it. 
<img width="1639" alt="Screenshot 2022-06-20 at 14 21 45" src="https://user-images.githubusercontent.com/5927078/174613177-6552194a-f65d-4f37-a61d-eb70f57ed5d8.png">
<img width="1653" alt="Screenshot 2022-06-20 at 10 24 02" src="https://user-images.githubusercontent.com/5927078/174613626-d1150ca6-fe39-4070-9a95-fb19d3b0e8ba.png">

Did we do something wrong during the  OkHttpClient configuration, or is it normal library behavior?

**Comment by swankjesse** [comment]
Yes, one thread per connection is expected. Is this causing performance problems beyond the thread use?

**Comment by mrozk** [comment]
Thanks for answering. Actually, 250 running threads instead of 50, is already a performance problem, which causes extra context switching, etc. I believe that switching on http/2 should save resources, not increase its consumption several times.

**Comment by swankjesse** [comment]
Yeah, for HTTP/1 OkHttp doesn’t need a thread to wait on the inbound socket in case a frame arrives. For HTTP/2 we need a thread per socket. It’s usually not a problem because usually the number of HTTP/2 connections isn’t substantial.

One potential fix for this is Project Loom, wherein a waiting thread doesn’t cost many resources.

**Comment by yschimke** [comment]
Closing, as this is intended and not something we can fix until Loom.
