### ISSUE TITLE
ConnectionPool cannot be cleared by force

### ISSUE THREAD

**Issue by Bruc3Stark** [square/okhttp#7353]
I want to clean up okhttp connection pool by using the following code:
` client.dispatcher().executorService().shutdown();
  client.connectionPool().evictAll();`
However, the connectionCount still did not decrease.
Is there any methods to clean up connection pool by force, instead of just waiting for the connections to become idle?

**Comment by swankjesse** [comment]
Try this:
```
client.dispatcher().cancelAll(); 
client.connectionPool().evictAll();
```

**Comment by swankjesse** [comment]
`cancelAll()` isn’t immediate unfortunately, so it'll take a few milliseconds before the connections become eligible for eviction. If you need that you could use EventListener to tell you when connections are released.

**Comment by yschimke** [comment]
@swankjesse I don't think EventListener gives you Connection events, only Call level as far as they relate to acquiring a connection.

**Comment by Bruc3Stark** [comment]
> Try this:
> 
> ```
> client.dispatcher().cancelAll(); 
> client.connectionPool().evictAll();
> ```

Thanks a lot.
