### ISSUE TITLE
okhttp:5.0.0-alpha.10 can run into `java.lang.ClassNotFoundException: kotlin.time.DurationUnit`

### ISSUE THREAD

**Issue by staktrace** [square/okhttp#7361]
See previous discussions in https://github.com/square/okhttp/pull/7267, https://github.com/square/okhttp/pull/7329, and https://github.com/square/okhttp/pull/7343. This is a continuation of that thread of problems, trying to iron out issues when using okhttp in a gradle plugin where the runtime kotlin version is restricted to 1.5.

Now I have put together a minimal standalone reproduction of the problem. It can be found at https://github.com/staktrace/20220627-okhttp-durationunit/tree/57afefa7bbe4f1cf1ae0b1dd8b6d4e01c4b738ff. To reproduce, clone the repo and run the `./reproduce.sh` script. The setup is that there are two separate gradle projects - one is a plugin that uses okhttp, and the other is a consumer that uses the plugin.

Some things I discovered along the way of creating this reproducer:
- If the plugin lives in the `buildSrc` folder of the consumer project, the problem doesn't reproduce
- The `kotlin-dsl` plugin being applied is important since it seems to be the thing that actually pins the gradle version to 1.5.31.

**Comment by yschimke** [comment]
@staktrace do you still have that repro repo?

**Comment by staktrace** [comment]
The repro is linked in the top comment - https://github.com/staktrace/20220627-okhttp-durationunit (main branch)

**Comment by yschimke** [comment]
@staktrace is it private?

**Comment by staktrace** [comment]
Ah sorry! Yes, it was private. Made it public now.

**Comment by yschimke** [comment]
I think this https://github.com/gradle/gradle/pull/19539

and this https://github.com/gradle/gradle/issues/16345, discussed here https://twitter.com/martinbonnin/status/1550035276604522498

Mean that we can revert this.  So suggest that we do, I'll put a PR up and compile against 1.6.21.

**Comment by yschimke** [comment]
Or is this the issue? https://github.com/gradle/gradle/issues/19568

> Gradle 7.5 will ship with Kotlin 1.6.21 but still target language/api 1/4 for backwards compatibility reasons. This can only be changed in a major version, next one being Gradle 8.0.

**Comment by yschimke** [comment]
Your test PR, with 7.6 works.  So going to revert this!

**Comment by yschimke** [comment]
from https://downloads.gradle-dn.com/distributions-snapshots/gradle-7.6-20220719081901+0000-bin.zip

**Comment by martinbonnin** [comment]
> If the plugin lives in the buildSrc folder of the consumer project, the problem doesn't reproduce

Got curious and made a small test there https://github.com/martinbonnin/classloaders. Looks like the dependencies of `buildSrc` are also put in the classpath albeit with a lower precedence than the embedded Kotlin jar. This way, you effectively [end up with 2 versions of `kotlin-stdlib` on the classpath](https://storage.googleapis.com/programming-idioms-pictures/idiom/149/princess-java.png). So `kotlin-stdlib` symbols will resolve to the `1.5.31` version, except those that are not present that will fallback and load from the `1.6.10` jar. Gradle classloaders never cease to amaze 🙃 .

In all cases, Gradle 7.5 will fix the issue as it will put `1.6.something` by default and this one has `DurationUnit` available.

**Comment by yschimke** [comment]
@martinbonnin sounds like you agree we can revert the existing attempts and ask people to upgrade to 7.5?

**Comment by martinbonnin** [comment]
Yep, users that want to use OkHttp in Gradle plugin should be able to do so with Gradle 7.5. Maybe you could add a runtime check when building a new client to point to this issue or give an actionable error message?

**Comment by yschimke** [comment]
I know OkHttp already understands Android vs JVM platforms, but doing so for a build system seems a step too far.

**Comment by martinbonnin** [comment]
Yup, that's fair 👍

**Comment by staktrace** [comment]
I also confirmed that the original problem I was seeing goes away with gradle 7.5. So 👍 from me for reverting all the things.
