### ISSUE TITLE
OkHttp 5 blockers

### ISSUE THREAD

**Issue by yschimke** [square/okhttp#7366]
- [x] HttpUrl multiplatform (@swankjesse )
- [x] ~Suspend JS support~
- [x] Status Code fixes https://github.com/square/okhttp/issues/2257
- [x] MockWebServer immutable 
- [x] MockWebserver natively support duplex
- [ ] Cancel listeners for Interceptors https://github.com/square/okhttp/issues/7164
- [x] Update cipher suites
- [x] Loom

**Comment by yschimke** [comment]
@swankjesse is Loom support in or out? https://github.com/square/okhttp/issues/6385

Even just confirming it's supported, if not a distinct TaskRunner.Backend?

**Comment by swankjesse** [comment]
I think Loom is out only because I don't expect it'll need API changes.

**Comment by yschimke** [comment]
I do think we'll need a new module with JDK 19+ dependencies, and probably change the implementation, potentially changes, maybe minor API changes, to TaskRunner.

**Comment by yschimke** [comment]
Going to mark https://github.com/square/okhttp/pull/7393 as done based on confirmation of current set against Chrome.

**Comment by yschimke** [comment]
@swankjesse Adding back Loom as I think https://github.com/square/okhttp/pull/7367 showed we need to remove wait()/notify() and use Conditions instead in okhttp and okio.

**Comment by yschimke** [comment]
Also for KMP, I'm looking at using okcurl as a cross platform CLI buildable with all of graal, native, js. https://github.com/square/okhttp/pull/7416

**Comment by yschimke** [comment]
HttpUrl supported, but without IDN.

**Comment by yschimke** [comment]
Suspend JS support is likely just the current example shown for ktor https://github.com/square/okhttp/pull/7326/files#diff-772553bc9e67a5b9842ab416490ff3fd80a8e7bd878ac641a9c0d644bce96492

Response will be read as part of the suspending executeAsync method.

**Comment by justinadkins** [comment]
Is there any news on when we can expect OkHttp 5 to be released?

**Comment by gesellix** [comment]
https://github.com/square/okhttp/issues/5874 (HTTP 1.1 Upgrades) would be great to be included. It might not be a release blocker, though.

**Comment by yschimke** [comment]
I suspect https://github.com/square/okhttp/issues/7164 could be a 5.1 feature if not in 5.0
