### ISSUE TITLE
sendPing and onPong

### ISSUE THREAD

**Issue by jobpaardekooper** [square/okhttp#7370]
I was wondering if it would be possible to add the possibility for custom ping and pong handeling. This has been discussed quite a few times in the past. (Most issues I found about this topic are a few years old by now)

Custom ping/pong handeling would add support for a few uses cases that are for example mentioned in the [WebSockets
Living Standard section 5](https://websockets.spec.whatwg.org//#ping-and-pong-frames). Specifically: 

> User agents may send ping and unsolicited pong frames as desired, for example in an attempt to maintain local network NAT mappings, to detect failed connections, or to display latency metrics to the user.

There was a PR (#6730) about a year ago that suggested an implementation for better ping/pong support. In the replies this got from maintainers it seems like there was genuine interest in improving/offering better support for these use-cases. Sadly though, the suggested changes didn't seem like the right way to go and the PR was closed for the time being. The main pain point was a breaking API change it introduced. I agree with that decision and in my opinion the suggested changes in that PR still lack an easy and intuitive api for better control over ping/pong.

I want to suggest 4 functions with the following signatures:
For `WebSocket`:
- `sendPing(text: String): Boolean`
- `sendPing(bytes: ByteString): Boolean`

For `WebSocketListener`:
- `onPong(webSocket: WebSocket, text: String)`
- `onPong(webSocket: WebSocket, text: ByteString)`

People who are currently using pings through the built in `pingIntervalMillis` can continue to use that with no problems. People who need fine grained support for ping and pong messages can use this new API also with no problems. This solution would not make any breaking changes to the current API. It provides a clean and intuitive way for developers to take advantage of the ping and pong functionality introduced by [RFC 6455](https://datatracker.ietf.org/doc/html/rfc6455).

I would be happy to help with the implementation. Looking forward to your feedback.

**Comment by swankjesse** [comment]
What's your use case? We intend to keep pings for connection health and not for application layer use.

**Comment by jobpaardekooper** [comment]
As mentioned one use for it is measuring latency. Also most other WebSocket interfaces expose the ping/pong functionality in a way like this instead of having it be handled exclusively internally by only providing an interval you can set. It would also provide easier interoperability with WebSocket implementations written for the server. **This feature would be especially useful when you are writing a client for an existing server that is not under your control.** For example when this server needs to interact with multiple different client implementations. It will likely make use of these features defined in the spec. It might also have specific requirements for clients regarding pings and pongs.

After thinking about it a bit more I think there should also be methods for `onPing` and `sendPong` added to support all the uses cases that the spec has to offer.

I think that adding this will be useful for a bunch of different use-cases but I will now explain my specific reason for requesting this feature. I realise that my reasoning for wanting this is not enough on its own but, there are a lot of other use-cases like I explained above that would greatly benefit from having this added. Also hopefully if this won't be added you might be able to give advice for this specific case that I am about to describe.

React native currently uses OkHttp for its android implementation of their 'cross platform' WebSocket api. Due to the fact that OkHttp does not expose methods for ping/pong this is also not possible to do when writing apps with react native. When looking at other implementations of WebSockets (on iOS or server implementations) this method of only being able to set a ping interval is quite unusual.

What are your thoughts?

**Comment by swankjesse** [comment]
Browsers don't offer pings and pongs and that makes me reluctant to offer them in OkHttp.

**Comment by jobpaardekooper** [comment]
I can understand that but, I think it would be great for many people if these features would be considered.

Browsers and the [WebSockets Living Standard](https://websockets.spec.whatwg.org/) do indeed not offer pings and pongs. They also don't offer an option to set a pingInterval or any internal ping support and yet OkHttp _does_.

Also the standard mentions that pings and pongs are not exposed in the api but does not give a reason why. Actually the standard does the opposite. It mentions [reasons](https://websockets.spec.whatwg.org/#ping-and-pong-frames) why it would be good to expose this functionality (even though it does not).

**Comment by yschimke** [comment]
I don't think any of the reasons listed are exposing these to clients. The user agent here is OkHttp (debatable).

"User agents may send ping and unsolicited pong frames as desired, for example in an attempt to maintain local network NAT mappings, to detect failed connections, or to display latency metrics to the user."

It's way easier to commit to additional public APIs, when they follow existing dominant conventions by browsers. When they don't we risk  implementing features that only work in the most carefully controlled environments, and suddenly stop working when a server changes it behaviour.

**Comment by yschimke** [comment]
Closing, rather than keeping open hope that we will eventually get to this.

**Comment by MarioBolivar** [comment]
Hello! Circling back on this topic - Is this something that the team would care to revisit? I +1 the benefit of exposing a way for application-level ping/pong-ing

There is a current gap (at least to my current understanding) in natively checking for connection health of a given websocket connection via okhttp. At the moment, there seems to be no direct way to understand if a connection is truly healthy (at the app-level) aside from heartbeating/ping-pong'ing. This seems like trivial functionality to expose on top of the background mechanism via the `pingInterval()` configuration.

Ideally:
1. We should be able to setup a `pingInterval()` at the configuration level for periodic/background heartbeating
2. We should be able to manually heartbeat/ping-pong (and handle the response or lack-thereof) via some exposed methods potentially as originally proposed above by @jobpaardekooper.

**Comment by swankjesse** [comment]
@MarioBolivar would you consider doing heartbeat messages at the application layer instead? That way it’ll also work with web browsers which also don’t offer user control to these internals.
