### ISSUE TITLE
SSLSocketFactory

### ISSUE THREAD

**Issue by lissi4ka** [square/okhttp#7385]
Hi! I need test my app on my local server without cert, I try find how off SSL trust and find same as 

`fun instance() {
        var manager: X509TrustManager = object: X509TrustManager {

            override fun checkClientTrusted(chain: Array<X509Certificate?>?, authType: String?) {
            }

            override fun checkServerTrusted(p0: Array<out X509Certificate>?, p1: String?) {
            }

            override fun getAcceptedIssuers(): Array<X509Certificate> {
                return arrayOf()
            }
        }
        val trustAllCerts: Array<TrustManager> = arrayOf<TrustManager>(manager)
        val sslContext = SSLContext.getInstance("SSL")
        sslContext.init(null, trustAllCerts, null)
        val sslSocketFactory = sslContext.socketFactory
        val builder = OkHttpClient.Builder()
        builder.connectionSpecs(listOf(ConnectionSpec.COMPATIBLE_TLS))
        builder.socketFactory(sslSocketFactory)
        builder.hostnameVerifier(HostnameVerifier { s, sslSession -> true })
        _client = builder
            .addInterceptor(AuthorizationInterceptor())
            .build()`

but when i started app i see exception

Caused by: java.lang.IllegalArgumentException: socketFactory instanceof SSLSocketFactory
        at okhttp3.OkHttpClient$Builder.socketFactory(OkHttpClient.kt:723)
        at com.admin.panel.newvr.common.api.NetworkService.instance(NetworkService.kt:75)

**Comment by yschimke** [comment]
There is sslSocketFactory, call that instead of socketFactory
