### ISSUE TITLE
Running multiple tests fails

### ISSUE THREAD

**Issue by JavierSegoviaCordoba** [square/okhttp#7388]
If I run each test individually, all pass perfectly.

Meanwhile, if I run all from CLI, they start to fail with "remote errors".

I just have a `BaseClass` for all tests:

```kotlin
internal abstract class BaseTest<F, S> {

    internal open val mockWebServer = MockWebServer()
  
	// ...

    @BeforeTest
    fun `start mockWebServer and enqueue response`() {
        mockWebServer.start()
        mockWebServer.enqueue(mockResponse(codeToFile, headers))
    }

    @AfterTest
    fun `close mockWebServer`() {
        mockWebServer.shutdown()
    }
}
```

And its usage:

```kotlin
internal class Success2xxTest : BaseTest<ErrorDTO, DogDTO>() {

    // ...

    @Test fun `suspend call 2xx`() = runTest { service.getDog() shouldBe expected }
}
```

I would expect each test to have its own `MockWebServer` instance and be independent, but it is not being the case (I think).

I am seeing some warnings:

```text
WARNING: MockWebServer[59693] connection from /127.0.0.1 didn't make a request
```

**Comment by JavierSegoviaCordoba** [comment]
I have tried the JUnit 4 rule with 5.0.0-alpha.10, and I got the same problem.

**Comment by JavierSegoviaCordoba** [comment]
Disabling parallel tests fixes the problem, but it is not an ideal solution...

```
tasks.withType<Test>().configureEach  {
    maxParallelForks = 1
}
```

**Comment by yschimke** [comment]
I'll take a look on the weekend.

**Comment by yschimke** [comment]
I don't think it's that they are not independent.  I think CPU contention might make your tests flaky.

Try this test

```
class ExampleText: BaseTest() {
  @Test public fun one() {
    println(mockWebServer.url("/"))
  }

  @Test public fun two() {
    println(mockWebServer.url("/"))
  }
}
```

You should see output like

```
http://localhost:51590/
http://localhost:51591/
```

We can do more here, like taking real time out of the equation (see https://github.com/square/okhttp/issues/5673), but not currently planned.

I'm going to close as I can't reproduce.  But please make a test that shows that multiple tests are interacting, and we can reopen.

**Comment by JavierSegoviaCordoba** [comment]
Well it is a lib that has adapters for Retrofit and Ktor, and the flakiness is only appearing in the Retrofit tests for the same amount of tests, as you said it can be caused by the CPU contention, but should be great a workaround for that, I don't care if tests are more slowly but I have seen this issue when the test class has more than 1 test too even disabling parallelization of tests via Gradle.

**Comment by yschimke** [comment]
Just confirm your test library is making new test instances for each test method to run.

Or use MockWebserverExtension to make sure it is.

**Comment by JavierSegoviaCordoba** [comment]
Yeah, it there is a new MockWebServer instance for each test class and there are more than 50-100 classes. Should I rewrite all tests to avoid having a lot of those classes? It could work in my case but not sure if this can be a problem in a big company where it is necessary to have a lot of different MockWebServer instances.

**Comment by yschimke** [comment]
I don't have a magic answer. I think it's a limitation of testing with lots of real network connections, that it can be flaky on slow machines or with contention.

**Comment by yschimke** [comment]
> And I am not sure what can happens when using the same instance and two tests try to send a different response at the same time.

You should avoid two tests using the same MockWebServer instance.

**Comment by JavierSegoviaCordoba** [comment]
> You should avoid two tests using the same MockWebServer instance.

Then I think I have to try another alternative like Retrofit Mock or something so.

But it is weird this is not happening to more people, 50-100 test classes are not so high for any company.
