### ISSUE TITLE
Get the server settings that are sent back for an HTTP/2 connection

### ISSUE THREAD

**Issue by himanshumps** [square/okhttp#7394]
I want to make a client call to get the HTTP/2 settings that the server returns for an HTTP/2 call. I want to use those settings to configure my connection pool accordingly. This is what the nghttp returns

```
user@machine ~ % nghttp -nv http://localhost:8443/healthz
[  0.014] Connected
[  0.017] send SETTINGS frame <length=12, flags=0x00, stream_id=0>
          (niv=2)
          [SETTINGS_MAX_CONCURRENT_STREAMS(0x03):100]
          [SETTINGS_INITIAL_WINDOW_SIZE(0x04):65535]
[  0.017] send PRIORITY frame <length=5, flags=0x00, stream_id=3>
          (dep_stream_id=0, weight=201, exclusive=0)
[  0.017] send PRIORITY frame <length=5, flags=0x00, stream_id=5>
          (dep_stream_id=0, weight=101, exclusive=0)
[  0.017] send PRIORITY frame <length=5, flags=0x00, stream_id=7>
          (dep_stream_id=0, weight=1, exclusive=0)
[  0.017] send PRIORITY frame <length=5, flags=0x00, stream_id=9>
          (dep_stream_id=7, weight=1, exclusive=0)
[  0.017] send PRIORITY frame <length=5, flags=0x00, stream_id=11>
          (dep_stream_id=3, weight=1, exclusive=0)
[  0.017] send HEADERS frame <length=45, flags=0x25, stream_id=13>
          ; END_STREAM | END_HEADERS | PRIORITY
          (padlen=0, dep_stream_id=11, weight=16, exclusive=0)
          ; Open new stream
          :method: GET
          :path: /healthz
          :scheme: http
          :authority: localhost:8443
          accept: */*
          accept-encoding: gzip, deflate
          user-agent: nghttp2/1.48.0
[  0.140] recv SETTINGS frame <length=12, flags=0x00, stream_id=0>
          (niv=2)
          [SETTINGS_MAX_CONCURRENT_STREAMS(0x03):100]
          [SETTINGS_MAX_HEADER_LIST_SIZE(0x06):8192]
[  0.140] recv SETTINGS frame <length=0, flags=0x01, stream_id=0>
          ; ACK
          (niv=0)
[  0.140] recv (stream_id=13) :status: 200
[  0.140] recv (stream_id=13) content-type: application/json;charset=UTF-8
[  0.140] recv (stream_id=13) content-length: 22
[  0.140] recv HEADERS frame <length=42, flags=0x24, stream_id=13>
          ; END_HEADERS | PRIORITY
          (padlen=0, dep_stream_id=11, weight=16, exclusive=0)
          ; First response header
[  0.140] send SETTINGS frame <length=0, flags=0x01, stream_id=0>
          ; ACK
          (niv=0)
[  0.146] recv DATA frame <length=22, flags=0x01, stream_id=13>
          ; END_STREAM
[  0.146] send GOAWAY frame <length=8, flags=0x00, stream_id=0>
          (last_stream_id=0, error_code=NO_ERROR(0x00), opaque_data(0)=[])**
```

The EventListener doesn't have any method to get notified of the settings change that the server requested.

I tried with okhttp 4.x as well as 5.x latest libraries.

**Comment by yschimke** [comment]
This isn't public API, and not something we will likely expose.

If you need this level of control, than you might want to use something like Netty to construct a client exactly as you require.  OkHttp tries to handle this without clients needing to be aware of it, and as internal details that we can change without breaking clients.

We are more likely to enhance frame logging to include more details, or maybe the frame in log event for more detailed logging, but that would be an ugly solution to your request.

I'm going to close as this is not public API. Sorry.

**Comment by himanshumps** [comment]
@yschimke Why can't we add onSettings methods in EventListener to expose server settings in case the of HTTP/2 connection. We can still have dedicated listener for HTTP2Connection. The method can return null for HTTP 1.1 connections. I do not think it is a breaking change and should be supported to take informed decision. What if I set the max streams to 10 and server supports only 2. There is no way to check it currently

**Comment by yschimke** [comment]
I'll reopen temporarily, to discuss this concrete example.  But I don't think we will implement or accept a PR that does.

**Comment by yschimke** [comment]
I'm going to close this for any new API to expose this.  No plans to add support, we have a high bar for new API.

If we could add via logging, it might be worthwhile. Extending the current Http2 frame logging.
