### ISSUE TITLE
Invalid URL host RFC4007 (IPV6) 

### ISSUE THREAD

**Issue by ncnnnnn** [square/okhttp#7396]
android 7.1
code 1:
```
val okclient = OkHttpClient()  
 var ENDPOINT="http://[fe80::21fe:aaaa:4ffb:4ef7%wlan0]:3000/"
val request = Request.Builder()  
                       .url(ENDPOINT)
                       .build();
 val response = okclient.newCall(request).execute()
```

error:
```
java.lang.IllegalArgumentException: Invalid URL host: "[fe80::21fe:aaaa:4ffb:4ef7%wlan0]" 
 at okhttp3.HttpUrl$Builder.parse$lib(HttpUrl.kt:1338)
```

code 2:
```
 var ENDPOINT="http://[fe80::21fe:aaaa:4ffb:4ef7]:3000/"
```

error:
```
java.net.ConnectException: Failed to connect to /fe80::21fe:aaaa:4ffb:4ef7:3000
```

**Comment by yschimke** [comment]
Previous discussion https://github.com/square/okhttp/issues/1706

**Comment by yschimke** [comment]
The issue was security related https://github.com/square/okhttp/pull/4865

So likely we won't accept this.

There is a manual workaround using your own custom socket factory, so you aren't blocked.

**Comment by yschimke** [comment]
What would help in general is more context on the use case, why it's required. And if other browsers and user agents support this also. Firefox, chrome, curl, python requests etc.

**Comment by ncnnnnn** [comment]
thanks
