### ISSUE TITLE
Unacceptable certificate: CN=RapidSSL Global TLS RSA4096 SHA256 2022 CA1, O="DigiCert, Inc.", C=US

### ISSUE THREAD

**Issue by XingAndroid** [square/okhttp#7405]
Unacceptable certificate: CN=RapidSSL Global TLS RSA4096 SHA256 2022 CA1, O="DigiCert, Inc.", C=US.

**Comment by XingAndroid** [comment]
why

**Comment by yschimke** [comment]
There is nothing to go on from this report.

Please provide a reproducible test, or a server we can test against, or include the certificate, or include results from a site like

https://www.ssllabs.com/ssltest/
