### ISSUE TITLE
Please open this class: okhttp3.Cache

### ISSUE THREAD

**Issue by hungntv** [square/okhttp#7407]
I need to delete some cache of **ONE specific url**, not delete all the cache.
To do that, I need to access methods of class: `okhttp3.Cache`.
But all of its methods (include constructors) are internal. This class is final too, can not subclass.

Please: (this class is `okhttp3.Cache`)
- make this class is open, so I can subclass it.
- make all its methods is public.

I believe after you do above things, people can make awesome cache by themself.

Thanks!

**Comment by JakeWharton** [comment]
This is already supported. Iterate via `urls()` and then call `remove()` on the entry you want to delete.

API here: https://square.github.io/okhttp/4.x/okhttp/okhttp3/-cache/urls/

**Comment by hungntv** [comment]
> This is already supported. Iterate via `urls()` and then call `remove()` on the entry you want to delete.
> 
> API here: https://square.github.io/okhttp/4.x/okhttp/okhttp3/-cache/urls/

I'm gonna delete this post after I see it as my bad.
Anyway, thanks for your response!
