### ISSUE TITLE
Document Congestion Control Algorithm Tuning

### ISSUE THREAD

**Issue by maltfield** [square/okhttp#7413]
Request: Please add to the [OkHttp documentation](https://square.github.io/okhttp/) a section describing which [TCP Congestion Control Algorithm](https://en.wikipedia.org/wiki/TCP_congestion_control#Algorithms) is used, and how it can be tuned by the user.

**Comment by maltfield** [comment]
See also https://stackoverflow.com/questions/73258421/which-tcp-congestion-control-algorighms-are-supported-and-used-by-okhttp

**Comment by yschimke** [comment]
I don't think we can answer this, it's not in our control.

Answered on StackOverflow.

**Comment by maltfield** [comment]
If it's not in your control, then you should definitely document it under a `Limitations` section and point the user to another relevant resource on how to further improve their app's HTTP connections via tuning the TCP Congestion Control Algorithm it uses

**Comment by yschimke** [comment]
It's effectively in the JVM/Android and Developers hands.  They can override it.  If you can summarise some clear unambiguous advice, it could be appropriate for our docs. If it measurably improves app experience, then it would be a great win. We could even make it a default under some environments, we do customise the networking stack (more SSL) per environment.  If there are similar things for particular JDKs, then it's possible.

But I can't promise it will be accepted, if it ends up with debatable or extremely nuanced advice.
