### ISSUE TITLE
 okhttp3.Cookie.name null object reference

### ISSUE THREAD

**Issue by ilkcanbs** [square/okhttp#7420]
Hello,
I show that crash in Crashlytics, but I couldn't catch the tests. I use Okhttp 4.9.1.
Obfuscated value is okhttp.cookie.name

Fatal Exception: java.lang.NullPointerException: Attempt to read from field 'OBFUSCATED VALUE' on a null object reference
       at okhttp3.Cookie.name(Cookie.java:46)
       at okhttp3.internal.http.BridgeInterceptor.cookieHeader(BridgeInterceptor.kt:113)
       at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:76)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
       at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
       at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
       at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run(Thread.java:764)

I use CookieJar implementation; after I get response; I add new cookies to my cookie list (If my list has new cookie (same name & domain) ; I don't add this cookie). I add my cookie list to request next call. (list isn't null; first emptylist)

I check backend IIS logs; I don't see a cookie name is null. And I don't understand at what stage this error happens. loadForRequest or saveFromResponse, do you have any idea? 

How can I handle this error?

```
class CookieStore : CookieJar {
    @Override
    override fun saveFromResponse(url: HttpUrl, cookies: List<Cookie>) {
        ConstantCookie.addCookie(cookies)
    }

    override fun loadForRequest(url: HttpUrl): List<Cookie> {

        var cookies = ConstantCookie.getCookie()

        cookies?.let {
            return cookies
        }

        return emptyList()
    }
}
```

**Comment by yschimke** [comment]
We can't help with this, it looks like `ConstantCookie.getCookie()` is returning listOf(null) of similar.

**Comment by ilkcanbs** [comment]
Hello Yschimke,
Thanks for reply.
I share my code block for ConstantCookie class. I checked that, it cannot be null. Do you have any recommend?


import okhttp3.Cookie
import java.lang.StringBuilder
import java.util.*

class ConstantCookie {

    companion object {

        private val sessionCookie: MutableList<Cookie> = mutableListOf()

        fun addCookie(newCookies: List<Cookie>?) {

            try {

                newCookies?.let { newServerCookies ->

                    if (sessionCookie.isNotEmpty()) {

                        val removeCookie = mutableListOf<Cookie>()
                        val synchronizedSessionCookie = Collections.synchronizedList(sessionCookie)

                        synchronized(synchronizedSessionCookie) {

                            val sessionCookieIterator = synchronizedSessionCookie.listIterator()
                            val synchronizedNewServerCookies = Collections.synchronizedList(newServerCookies)

                            synchronized(synchronizedNewServerCookies) {

                                val serverCookiesIterator = synchronizedNewServerCookies.listIterator()

                                while (serverCookiesIterator.hasNext()) {

                                    val newCookie = serverCookiesIterator.next()

                                    while (sessionCookieIterator.hasNext()) {

                                        val oldCookie = sessionCookieIterator.next()

                                        if (oldCookie != null && newCookie != null) {
                                            val sameName = !oldCookie.name.isNullOrEmpty() && !newCookie.name.isNullOrEmpty() && oldCookie.name == newCookie.name
                                            val sameDomain = !oldCookie.domain.isNullOrEmpty() && !newCookie.domain.isNullOrEmpty() && oldCookie.domain == newCookie.domain

                                            if (sameName && sameDomain) {
                                                removeCookie.add(oldCookie)
                                            }
                                        }
                                    }
                                }

                                if (removeCookie.size > 0) {
                                    sessionCookie.removeAll(removeCookie)
                                }
                            }
                        }
                    }

                    sessionCookie.addAll(newServerCookies)
                }
            } catch (e: Exception) {
            }
        }

        fun getCookie(): MutableList<Cookie> {
            return sessionCookie
        }

        fun clearCookie() {
            sessionCookie.clear()
        }
    }
}

**Comment by yschimke** [comment]
Ask on a site like stackoverflow, we can't offer 1:1 debugging help. If you think it's a bug in OkHttp please make a reproducible test case.

**Comment by ilkcanbs** [comment]
Ok, thanks. I will try to get answer my question on Stackoverflow. 👍
