### ISSUE TITLE
intermittently stream was reset : cancel exception

### ISSUE THREAD

**Issue by yungu-kang** [square/okhttp#7429]
I use okhttp version 4.9.3 on android device.

Intermittently, got exception 'Stream was reset: Cancel'
I tried many ways but couldn't solve it.

Stacktrace
`
Caused by okhttp3.internal.http2.StreamResetException
stream was reset: CANCEL
okhttp3.internal.http2.Http2Stream.takeHeaders (Http2Stream.kt:148)
okhttp3.internal.http2.Http2ExchangeCodec.readResponseHeaders (Http2ExchangeCodec.kt:96)
okhttp3.internal.connection.Exchange.readResponseHeaders (Exchange.kt:106)
okhttp3.internal.http.CallServerInterceptor.intercept (CallServerInterceptor.kt:79)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.kt:109)
okhttp3.internal.connection.ConnectInterceptor.intercept (ConnectInterceptor.kt:34)
`

Do you have any ideas?
Url length is short, GET method and have one query parameter.

**Comment by yschimke** [comment]
I think most likely reason is that you are either getting a timeout, or something is cancelling the Call instance.  We can't offer direct support here, so please continue on a forum like stackoverflow.
