### ISSUE TITLE
Request header "Connection=close" affects HTTP/2 connections

### ISSUE THREAD

**Issue by klboke** [square/okhttp#7432]
https://github.com/square/okhttp/blob/6bca734a7b2eacb9caf3ba3184fd57f93ee769d1/okhttp/src/jvmMain/kotlin/okhttp3/internal/http/CallServerInterceptor.kt#L132-L135
 http://tools.ietf.org/html/draft-ietf-httpbis-http2-09#section-8.1.3. There is no longer a "Connection" request header in HTTP/2, but it is possible to set the request header "Connection=close" to affect the HTTP/2 connection behavior, is that a problem?

**Comment by yschimke** [comment]
It should be skipped here 

https://github.com/square/okhttp/blob/58ee1ce170c2aea75a113012956260873e808dad/okhttp/src/jvmMain/kotlin/okhttp3/internal/http2/Http2ExchangeCodec.kt#L190

Please reopen if you can reproduce it not being filtered.

**Comment by klboke** [comment]
Yes, I used version 5.0.0-alpha.10, the problem is still there, as follows, it is the request I constructed, but it is actually an HTTP/2 request
```java
                    Request.Builder()
                        .url(TEST_URL)
                        .addHeader("Accept-Encoding", "identity")
                        .addHeader("Connection", "close")
                        .addHeader("Cache-Control", "no-cache")
                        .build()
```
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/18591662/188321838-3b99edc3-40ad-4f88-95e1-73f58eb3dcd8.png">

**Comment by yschimke** [comment]
Ahhh, I see what you mean.  This doesn't make it to the server, nor get returned

**Comment by swankjesse** [comment]
I don't think we want any behavior changes here. The header has the desired effect, despite doing things the HTTP/2 way.
