### ISSUE TITLE
Provide way on HttpLoggingInterceptor to redact query params

### ISSUE THREAD

**Issue by DavidRigglemanININ** [square/okhttp#7476]
Currently, support is available for redacting headers on the logging interceptor. The docs even warn that you could be leaking sensitive info if at the level of BODY or HEADERS. However, even BASIC has the potential to leak sensitive info if information is encoded in the url via query params (AWS is one example of where this can happen). So it'd be great if there was an easy way to specify a query param that should be redacted from logging. Thanks for the consideration!

**Comment by yschimke** [comment]
https://github.com/square/okhttp/pull/7458

**Comment by DavidRigglemanININ** [comment]
Unless I'm missing something, the issue you linked is about headers, not query params, which is my issue. Or maybe you were just linking an issue to show how it was done for headers?

**Comment by yschimke** [comment]
You are right, I was getting confused.  Probably worth discussing them together, even if we implement separately or at all.

**Comment by yschimke** [comment]
OK, just summarising what we have now

`internal.isSensitiveHeader()` - checks for known headers like Authorization.

Request PR https://github.com/square/okhttp/pull/7458 - adding check for `isSensitiveHeader`

`HttpLoggingInterceptor`
`redactHeader()` - adds a new header to be redacted.

I think we should treat this seriously, but I don't think we can know the full set of query params or even headers to redact.

I'd suggest we add a redacted for of Request.toString(redactedHeaders, redactedParams) that is public API, with the current defaults.  And make this configurable in HttpLoggingInterceptor.

@swankjesse thoughts?

**Comment by swankjesse** [comment]
If I had to implement this, I think I’d want a `UrlRedacter` interface that converted a URL to a String.

But I continue to believe that HttpLoggingInterceptor is not designed for production use. Speculative logging is too noisy. For development I love Chucker; for production I’d like something that does spans like Datadog or Chronosphere.

**Comment by yschimke** [comment]
Closing as low priority, HttpLoggingInterceptor can be copy and pasted and is not part of OkHttp core.
