### ISSUE TITLE
stream was reset: PROTOCOL_ERROR

### ISSUE THREAD

**Issue by tianshaokai** [square/okhttp#7478]
okhttp: 3.12.2

This problem(stream was reset: PROTOCOL_ERROR) is always reported when downloading files using okhttp, We have turned off http2，I don't know why, but I will still report this problem

**Comment by yschimke** [comment]
Can you try with OkHttp 4.10?

**Comment by tianshaokai** [comment]
No, because the app needs to release a new version, 3.12.2 and 4.10. Is there any difference？

**Comment by tianshaokai** [comment]
I closed http2 directly by the server gateway. Whether to set Protocol HTTP_ 1_ 1 can close http2?

**Comment by yschimke** [comment]
Well, there have been _potentially_ relevant fixes in 4.x.  I'm not sure if it's specifically fixed or the route cause but 3.x is not maintained, so we can't fix even if we find a bug.  And not worth doing that unless we know it exists on the maintained branches.

Please reopen with a bug report against 4.10.
