### ISSUE TITLE
I have customized httpdns. How do I determine the specific IP address of the sockettimeoutexception when I create a socket?

### ISSUE THREAD

**Issue by tianshaokai** [square/okhttp#7492]
I have customized httpdns. How do I determine the specific IP address of the sockettimeoutexception when I create a socket?

**Comment by yschimke** [comment]
Can you move this question to stackoverflow?  Post a link there and I can answer with some options there. This is for issues, not general support queries.

Also, I don't quite understand how you have customised it, so I'm not sure if I'm answering the right question.  Please include some sample explaining what you have done.

Thanks.
