### ISSUE TITLE
Group logs from requests and responses

### ISSUE THREAD

**Issue by iadcialim** [square/okhttp#7513]
Right now, I am using HttpLoggingInterceptor.Logger (com.squareup.okhttp3:logging-interceptor:4.4.1) to intercept logs from Retrofit and log them into the console or file (using https://github.com/elvishew/xLog)

The thing is I want to group logs from a request or response rather just logging whatever strings comes from 
`HttpLoggingInterceptor.Logger.log(message: String)`

So I subclassed HttpLoggingInterceptor.Logger and worked on a simple string manipulation logic here to group these logs.

```
abstract class MyHttpLogger : HttpLoggingInterceptor.Logger {
    private var sb = StringBuilder()

    /**
     * This combines logs from Retrofit into one block of related logs (request, response)
     * Sample request:
     * --> GET https://domain.com/api/v1/endPoint
     * --> END GET
     * Sample Response:
     * <-- 200 https://domain.com/api/v1/endPoint (167ms)
     * ...
     * <-- END HTTP (2871-byte body)
     *
     * @param message the line-by-line logs from Retrofit
     */
    override fun log(message: String) {
        if (message.isBlank()) return

        try {
            if (message.startsWith("-->")) {
                if (message.contains("--> END")) {
                    // its the end part of the request network call logs
                    sb.append(message)
                    groupedLog(sb.toString()) // logs that should be grouped
                    sb.clear()
                } else {
                    // its the beginning part of the request network call logs
                    sb.clear()
                    sb.append(message + "\n")
                }
            } else if (message.startsWith("<--")) {
                if (message.startsWith("<-- END")) {
                    // its the end part of the response network call logs
                    sb.append(message)
                    groupedLog(sb.toString()) // logs that should be grouped
                    sb.clear()
                } else {
                    // its the beginning part of the response network call logs
                    sb.clear()
                    sb.append(message + "\n")
                }
            } else if (sb.isNotEmpty()) {
                // middle logs between the beginning and ending tags
                sb.append(message + "\n")
            }
        } catch (e: Exception) {
            e.printStackTrace()
        }
    }
```

Most of the time this works. But when multiple APIs are called at the same time, I expect that logs from those calls are messed up here and it breaks the logic.

So there should be a way like an `ID or source param in override fun log(message: String)` to know where this log is coming from.
Like is it coming from request of API#1, or response from API#2, etc.
What do you think?

**Comment by yschimke** [comment]
HttpLoggingInterceptor isn't under particularly active development.  And we wouldn't break the public APIs of it.

So probably best to copy the implementation into your project and make the changes you need.

You could also look at EventListeners, which are another way of getting call events.

Or look at alternatives such as https://github.com/ihsanbal/LoggingInterceptor
