### ISSUE TITLE
🙉maxRequests and maxRequestsPerHost not working as i expect

### ISSUE THREAD

**Issue by Turalllb** [square/okhttp#7520]
У меня есть 

```
companion object {
        private val dispatcher = Dispatcher().apply {
            maxRequests = 1
            maxRequestsPerHost = 1
        }
    }
```

   All Retrofits use okHttpClient in which this dispatcher. I expect that when the first request occurs, the next ones are queued, after the first request has received a response, the next request is taken from the queue.
 I'm running a test: at the start of the application, I have 14 simultaneous requests, they happen within 1-2 seconds. The very first request I stop with a sniffer and expect that no other requests will be made, but all other requests are not stopped. I tried many similar experiments, but none showed that the requests were being queued.

Maybe I misunderstood the description of maxRequests, should it work as it seemed to me?

**Comment by yschimke** [comment]
Can you provide a repro? Are you using enqueue or execute? These limits only apply to enqueued requests. Executed requests will run immediately.

**Comment by swankjesse** [comment]
No action to take on this for now.

**Comment by Turalllb** [comment]
I don't use a queue, I thought this setting is generally applicable to all requests, thanks for the clarification, I'll think about how possible it is to use the queue exclusively in the application. I want my application to never make more than 10 parallel requests. That is, 10 requests are made and as soon as 1 of them answers, you can make another one, in general, 10 active requests awaiting a response, no more, and it seemed that this setting should help
