### ISSUE TITLE
Android: okhttp not respect `SSLParameters.setServerNames` parameter

### ISSUE THREAD

**Issue by vvb2060** [square/okhttp#7524]
android 5 (API 21): SNI disabled default
android 6 (API 23): add `jsse.enableSNIExtension` property, default true
android 7 (API 24): add `SSLParameters.setServerNames()`
android 10 (API 29): hidden api, okhttp use Android10SocketAdapter

https://github.com/square/okhttp/blob/d5c180498d2d7df6a6d76f2eb924e04befe64b05/okhttp/src/jvmMain/kotlin/okhttp3/internal/platform/android/AndroidSocketAdapter.kt#L55-L58

For devices under Android 10(StandardAndroidSocketAdapter), okhttp always setHostname before TLS handshake, which causes SNI to be forced enabled and overrides any previous configuration. 
https://cs.android.com/android/platform/superproject/+/android-5.0.0_r1.0.1:external/conscrypt/src/main/java/org/conscrypt/OpenSSLSocketImpl.java;l=855

test app: https://github.com/vvb2060/okhttpsni

android 10 (Android10SocketAdapter)
peerHost is cloudflare-dns.com, same as `serverName`: 
```
old SNI: [type=host_name (0), value=sni.cloudflaressl.com]
hostname: sni.cloudflaressl.com
peerHost:cloudflare-dns.com
cert: cloudflare-dns.com
cert: *.cloudflare-dns.com
cert: one.one.one.one
```

android 8 (StandardAndroidSocketAdapter)
SSL handshake aborted:
```
Caused by: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0x759043da00: Failure in SSL library, usually a protocol error
error:10000410:SSL routines:OPENSSL_internal:SSLV3_ALERT_HANDSHAKE_FAILURE (external/boringssl/src/ssl/tls_record.cc:579 0x759041b2a0:0x00000001)
error:1000009a:SSL routines:OPENSSL_internal:HANDSHAKE_FAILURE_ON_CLIENT_HELLO (external/boringssl/src/ssl/handshake_client.cc:893 0x7585c740ab:0x00000000)
	at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
	at com.android.org.conscrypt.SslWrapper.doHandshake(SslWrapper.java:374)
	at com.android.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(ConscryptFileDescriptorSocket.java:217)
	... 17 more
```

**Comment by yschimke** [comment]
Going to close this, as we have a solution for the actual requirement. We can't honour this easily as we need to set in various scenarios.
