### ISSUE TITLE
Unable to edit Okhttp idle connection pool 5 minutes default timing

### ISSUE THREAD

**Issue by germanSuplex23** [square/okhttp#7528]
Im using okhttp-4.2.2 and im getting the following error as soon as the post call exceeds 5 minutes on the client side despite attempts to increase the idle timeout and builder timeouts.

        ERROR [stderr] (default task-11819) java.net.SocketException: Connection reset
        ERROR [stderr] (default task-11819)     at java.net.SocketInputStream.read(SocketInputStream.java:210)
        ERROR [stderr] (default task-11819)     at java.net.SocketInputStream.read(SocketInputStream.java:141)
        ERROR [stderr] (default task-11819)     at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
        ERROR [stderr] (default task-11819)     at sun.security.ssl.InputRecord.read(InputRecord.java:503)
        ERROR [stderr] (default task-11819)     at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:975)
        ERROR [stderr] (default task-11819)     at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:933)
        ERROR [stderr] (default task-11819)     at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
        ERROR [stderr] (default task-11819)     at okio.InputStreamSource.read(Okio.kt:102)
        ERROR [stderr] (default task-11819)     at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:159)
        ERROR [stderr] (default task-11819)     at okio.RealBufferedSource.indexOf(RealBufferedSource.kt:349)
        ERROR [stderr] (default task-11819)     at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.kt:222)
        ERROR [stderr] (default task-11819)     at okhttp3.internal.http1.Http1ExchangeCodec.readHeaderLine(Http1ExchangeCodec.kt:210)
        ERROR [stderr] (default task-11819)     at okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.kt:181)
        ERROR [stderr] (default task-11819)     at okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.kt:105)
        ERROR [stderr] (default task-11819)     at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:82)
        ERROR [stderr] (default task-11819)     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        ERROR [stderr] (default task-11819)     at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:37)
        ERROR [stderr] (default task-11819)     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        ERROR [stderr] (default task-11819)     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
        ERROR [stderr] (default task-11819)     at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:82)
        ERROR [stderr] (default task-11819)     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        ERROR [stderr] (default task-11819)     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
        ERROR [stderr] (default task-11819)     at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:84)
        ERROR [stderr] (default task-11819)     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        ERROR [stderr] (default task-11819)     at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:71)
        ERROR [stderr] (default task-11819)     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        ERROR [stderr] (default task-11819)     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
        ERROR [stderr] (default task-11819)     at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.kt:184)
        ERROR [stderr] (default task-11819)     at okhttp3.RealCall.execute(RealCall.kt:66)

This are the changes ive made to the client builder.

        OkHttpClient.Builder builder = new OkHttpClient.Builder();
						   	         builder.connectTimeout(900, TimeUnit.SECONDS); 
						   	         builder.readTimeout(900, TimeUnit.SECONDS); 
						   	         builder.writeTimeout(900, TimeUnit.SECONDS);
						   	         builder.callTimeout(900, TimeUnit.SECONDS);
						   	         builder.retryOnConnectionFailure(false);
						   	         builder.connectionPool(new ConnectionPool(0, 10, TimeUnit.MINUTES));

         OkHttpClient httpClient = new OkHttpClient();
			       httpClient = builder.build();
        
         RequestBody body = RequestBody.create(jsonString, MediaType.parse("application/json; charset=utf-8"));
        
         Request request = new Request.Builder()
                        .url(applicationPath)
                        .addHeader("Authorization", "Bearer "+jsonStringAuth.getString("access_token"))
                        .header("Connection", "Keep-Alive")
                        .post(body)
                        .build();

**Comment by yschimke** [comment]
Can you make a repro and list the JVM/Android versions?

**Comment by germanSuplex23** [comment]
> Can you make a repro and list the JVM/Android versions?

My web app is running on JVM version 1.8

**Comment by swankjesse** [comment]
Please open a new issue once you have a test case, or something more actionable for us. Thanks!
