### ISSUE TITLE
server cannot receive the request

### ISSUE THREAD

**Issue by charlesxv** [square/okhttp#7556]
I sent three requests and analyzed them with tcpdump packet capture. It was found that one of the request options [... ecr] referenced options [... val] five minutes ago, causing the server to not receive the request.

**Comment by charlesxv** [comment]
I sent three "post" requests, two of which are once a minute, and the other one is once a second.By capturing the tcpdump data, it is found that the request sent once a second after running for several hours cannot be received by the server.

**Comment by yschimke** [comment]
I'm sorry, but I don't know how to test this. Please reopen with a reproduction against a server like https://httpbin.org/

Even a single java file I can run myself without further editing to reproduce this scenario.
