### ISSUE TITLE
Request head, Cache-control: only-if-cached returns 504

### ISSUE THREAD

**Issue by ghost** [square/okhttp#7557]
**Description:**
I need to make request with method=head, Cache-control: only-if-cached, to check cache on remote server.
According to this documentation: 
[IPFS: path gateway head](https://github.com/ipfs/specs/blob/main/http-gateways/PATH_GATEWAY.md#head-ipfscidpathparams)
Even if okhttp cache is not enabled I always get result 504: Unsatisfiable Request (only-if-cached).
According to the line below it's supposed that "Cache-control: only-if-cached" forbids making http request to remote server.
[okhttp3/internal/cache/CacheStrategy.kt:132](https://github.com/square/okhttp/blob/master/okhttp/src/jvmMain/kotlin/okhttp3/internal/cache/CacheStrategy.kt#L133)

I didn't find workaround to resolve this issue in okhttp and checked cache implementation in ktor client, their cache handles only method=get requests. Probably, it's right.

**Conditions:**
Http Request
method: head
Cache-control: only-if-cached

**Actual result:**
504: Unsatisfiable Request (only-if-cached)

**Expected result:**
Execute http request to remote server

**Comment by JakeWharton** [comment]
> I didn't find workaround to resolve this issue

Maybe add the header in a network interceptor?
