### ISSUE TITLE
Loom Support

### ISSUE THREAD

**Issue by techwnn** [square/okhttp#7576]
Project Loom, known as [JEP 425](https://openjdk.org/jeps/425) has published in JDK 19 as preview features.

Spring community is also [embracing the change](https://spring.io/blog/2022/10/11/embracing-virtual-threads).

Tomcat also [add support as preview feature](https://medium.com/naukri-engineering/virtual-thread-performance-gain-for-microservices-760a08f0b8f3)

Is there any roadmap for okhttp support it since it will be officially publish with JDK 21, probably at 09/23.

**Comment by yschimke** [comment]
We looked at it in https://github.com/square/okhttp/pull/7367

It's likely blocked on okio first. I think it should work well given okio/okhttp design.

A lot of changing synchronized blocks to locks and conditions, that should be fine even without loom.

**Comment by yschimke** [comment]
Okio issue https://github.com/square/okio/issues/1169

**Comment by yschimke** [comment]
While we can always test, benchmark more, the okio and okhttp support is in place. Can incrementally fix more as we go.
