### ISSUE TITLE
MockWebServer responds with malformed HTTP message

### ISSUE THREAD

**Issue by nstdio** [square/okhttp#7577]
Consider test case:

```kotlin
import mockwebserver3.MockResponse
import mockwebserver3.MockWebServer
import mockwebserver3.junit5.internal.MockWebServerExtension
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.extension.ExtendWith

@ExtendWith(MockWebServerExtension::class)
class NotModifiedTest(private val mockWebServer: MockWebServer) {

  @Test
  fun `Should not fail`() {
    //given
    val statusCode = 304
    val body = "anything"
    val nRequests = 2
    val url = mockWebServer.url("/test").toUri().toURL()

    repeat(nRequests) {
      mockWebServer.enqueue(
        MockResponse()
          .setResponseCode(statusCode)
          .setBody(body),
      )
    }

    //when + then
    repeat(nRequests) {
      url.openStream().use { it.readAllBytes() }
    }
  }
}
```

On a second repeat it does fail with:
```
java.io.IOException: Invalid Http response

	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1707)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
	at java.base/java.net.URL.openStream(URL.java:1161)
```

**Comment by yschimke** [comment]
You are configuring an invalid MockResponse, if you remove the body, the test should pass.

See https://httpwg.org/specs/rfc9110.html#status.304

**Comment by nstdio** [comment]
yup, if it's invalid the test should have same behavior when `nRequests = 1`

**Comment by yschimke** [comment]
@nstdio I assume you are seeing http request smuggling because of connection pipelining.  With MockWebServer you are responsible for configuring valid responses, and if you setup an invalid scenario, the next request can fail.

See https://portswigger.net/web-security/request-smuggling

![image](https://user-images.githubusercontent.com/231923/209467090-8f86ec2d-783f-4d95-9659-1cfc73a95326.png)

**Comment by yschimke** [comment]
In general for OkHttpClient we strongly favour not allowing invalid scenarios. But for MockWebServer there isn't the same rigour in stopping all problem scenarios like this. And in fact there is a tension between people wanting to test invalid scenarios, and those expecting it to proactively stop these sorts of issues.

So I'm not sure we would take a PR that handled this specifically, as it likely creates a long pipeline of work to make MockWebServer fully compliant.  

Maybe noisy logging in MockWebServer when asked to do invalid things would work?

**Comment by nstdio** [comment]
> you are seeing something like http request smuggling

yeah, exactly. The body of first request becomes first line of second request like: `anythingHTTP 1.1 304 Redirection`

**Comment by swankjesse** [comment]
MockWebServer is deliberately-built to support doing weird things and to violate specs. Making it compliant or secure would make it worse.
