### ISSUE TITLE
Add commonSequence() extension for Headers.

### ISSUE THREAD

**Issue by Isira-Seneviratne** [square/okhttp#7606]
This issue proposes to add a `commonSequence` extension function for `Headers`, which would return a [sequence](https://kotlinlang.org/docs/sequences.html) containing each key-value pair in the headers.

Since sequences are lazily evaluated, this could be used to avoid unnecessary allocations, such as in the `commonIterator` extension, which currently creates an array with each key-value pair before iterating over the pairs.

**Comment by yschimke** [comment]
Are there some places in OkHttp or typical client use that would definitely benefit from this? Do you have a project using OkHttp that needs this?

If it's new public API, I'm by default against it for a micro optimisation.  

If it cleans up existing OkHttp code, it sounds more worthwhile, but I can't see a bunch of uses at the moment.

**Comment by Isira-Seneviratne** [comment]
> If it's new public API, I'm by default against it for a micro optimisation.

No, it would be an internal API, like the other `common` extensions.

> If it cleans up existing OkHttp code, it sounds more worthwhile, but I can't see a bunch of uses at the moment.

It could be used in the `commonIterator` function, for example. That function currently creates an array with the key-value pairs, while the sequence extension would avoid creating an array for the purpose of iterating over the key-value pairs.

**Comment by yschimke** [comment]
I don't think we want to make this sort of incremental minor improvements to the codename. We have basically two active maintainers to review most PRs. Unless there is some clear context or driving reason behind the change, I suggest we leave as is.
