### ISSUE TITLE
[Wishlist / feature request] Add a new okhttp-server module providing a Java IO loom based HTTP Server

### ISSUE THREAD

**Issue by pull-vert** [square/okhttp#7639]
* Okio provides really useful InputStream / OutputStream utilities, and is already supported by various HTTP related libraries like `moshi` or `kotlinx-serialization`.
* Okhttp (client-side for now) already provides a lot of the HTTP/1 and HTTP/2 features, a core could be extracted from the current code base so that a new `okhttp-server` would not be built from scratch.
* Project Loom provides [virtual threads since Java 19 as a preview feature](https://openjdk.org/jeps/425), so a highly efficient HTTP server with one new virtual thread per request is now possible with the good old Java IO ServerSocket, without complex thread pools, and could fully benefit from Okio internally.

I am not sure about the multiplatform part, maybe a JVM only server is good enough !
I am not sure a NIO Server option (along the IO one proposed here) is needed, but it could be done later.

This issue is related to #7576

**Comment by yschimke** [comment]
This is not in scope. Building a server requires a different set of tradeoffs than a client. There are so many other great JVM server frameworks we'd never catch up to.

For something Okio inspired, maybe its https://github.com/cashapp/misk

**Comment by pull-vert** [comment]
I can understand that.
