### ISSUE TITLE
Provide a way to select proxy authenticator 

### ISSUE THREAD

**Issue by iseki0** [square/okhttp#7641]
I create a proxy selector that read environment variables `http_proxy` `https_proxy` `all_proxy` and `no_proxy`. The proxy is selected by schema.
But I found no way to create an authenticator matching the proxy selection flow.
In `proxyAuthenticator` I cannot get anything about which proxy is selected, and... How to configure SOCKS5 authenticator?(By proxySelector)

**Comment by swankjesse** [comment]
OkHttp doesn’t know hardly anything about SOCKS authentication.

Consider making a custom `SocketFactory` that does SOCKS, and specifying the Proxy as NO_PROXY to OkHttp.

**Comment by iseki0** [comment]
thank you. And how can I get the proxy info in proxyAuthenticator ?

**Comment by iseki0** [comment]
I notice that OkHttp only use `SocketFactory::createSocket()` to create an empty socket. I suppose after that OkHttp will use `connect(SocketAddress, int)` to connect remote. So I lost the host. There're 2 problem at least:
- I can't use `socks5h` schema, that means the DNS query will do local only.(In some network it's a major problem)
- I can't support proxy environment variable `no_proxy`. It should handle hostname match

**Comment by iseki0** [comment]
My problem partial solved. I miss the parameter `route: Route?` 🤐 Thank you for your reply. But the Socks5 is also a problem. Even the hostname match will be done at proxy selection phrase, the hostname can't pass to proxy.

**Comment by swankjesse** [comment]
Just curious: is the SOCKS for Tor? Something else? Making Tor easy seems like a good idea.

**Comment by iseki0** [comment]
Not only for tor. We'd best support proxy as many as possible. Such as we use shadowsocks and v2ray as proxy tools. Both of them allow socks5 inbound. (They support http proxy also, so it's not a big problem)

**Comment by yschimke** [comment]
Maybe this is a good target, document how to cleanly support this via the socket factory with examples.

**Comment by yschimke** [comment]
A testing PR https://github.com/square/okhttp/pull/7645/files

I've replaced Dns with just faking a localhost address.
And using a Socks5 SocketFactory.
The test is using shadowsocks docker image.  But I don't know what I'm doing.

```
Exception in thread "main" java.net.SocketTimeoutException: Read timed out
	at java.base/sun.nio.ch.NioSocketImpl.timedRead(NioSocketImpl.java:283)
	at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:309)
	at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:350)
	at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:803)
	at java.base/java.net.Socket$SocketInputStream.read(Socket.java:976)
	at java.base/java.net.Socket$SocketInputStream.read(Socket.java:971)
	at sockslib.utils.StreamUtil.read(StreamUtil.java:42)
	at sockslib.client.GenericSocksMethodRequester.doRequest(GenericSocksMethodRequester.java:66)
	at sockslib.client.Socks5.buildConnection(Socks5.java:200)
	at sockslib.client.SocksSocket.connect(SocksSocket.java:208)
	at okhttp3.internal.platform.Platform.connectSocket(Platform.kt:138)
```

**Comment by yschimke** [comment]
Ok working with https://hub.docker.com/r/serjs/go-socks5-proxy/

But it's using DNS in the client.

Will try to avoid Dns.

**Comment by yschimke** [comment]
@iseki0 do you have any advice on how to achieve this in Java? I can't find an API for this.

**Comment by iseki0** [comment]
I'm create a simple socks5 [SocketFactory implementation](https://gist.github.com/iseki0/ef9fd5e4f9529ce0f6bde859fc602cca), soon I will create a PR for it.

**Comment by iseki0** [comment]
@yschimke Is this kind of pull request allowed by the repository? I can’t find any place for the code.

**Comment by yschimke** [comment]
@iseki0 I don't think we are the best repository to host and maintain a Socks5 socket handler. It's not OkHttp specific, so should be useful for others.

Suggestions

1) Host this in an existing Socks related github project, and we add a sample including docker image to OkHttp
2) Host this in a new github project and publish to jitpack, and we add a sample including docker image to OkHttp
3) We include this just as a sample, but developers will need to copy and paste into their project.

Is there a natural home for it.
