### ISSUE TITLE
Support a non-ExecutorService Executor as a dispatcher

### ISSUE THREAD

**Issue by dkhalanskyjb** [square/okhttp#7647]
See https://github.com/Kotlin/kotlinx.coroutines/issues/3579.

I understand that I may be completely wrong on all accounts here, not being the user of your library myself, but I did dig into the issue a bit to answer our user, and maybe my thoughts on this could help, who knows?

Looking through your code, I see two ways the fact that the `Executor` is an `ExecutorService` is used:
1. After the client is no longer needed, the user of okhttp is supposed to call `shutdown` on the `ExecutorService`,
2. `isShutdown` is checked in `okhttp3.Dispatcher#promoteAndExecute`.

W.r.t. 1: Yeah, I guess there's no way around this explicit step, given that you create a thread pool by default. An easy way out is to check if the executor is an `ExecutorService`, and if so, throw an `UnsupportedOperationException` when attempting to shut it down.

Another option to consider (which I like much more) is to remove `shutdown()` and instead always require that the thread pool is supplied manually. This way, people will be able to leverage the `use` function (https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.io/use.html) / Java's try-with-resources, like in
```kotlin
OkHttpDefaultThreadPool().use { pool ->
  val client = OkHttpClient.Builder()
    .dispatcher(pool)
    .build()
  // etc
}
```
This is not more lines of code than what's here now (given that you're supposed to call `shutdown` manually instead), but will automatically fix problems like https://stackoverflow.com/questions/56395158/getting-memory-leaks-with-okhttp. I see a couple of places even in the `samples/` dir where you don't shut the client down or don't do it in a `finally` block. This should help for one-shot clients, and for the typical use case of the client being stored somewhere as a singleton, people still can explicitly make the tradeoff of never closing it.

W.r.t. 2: it looks like this check is just a performance optimization and doesn't affect any functionality (if not, the code would also have a parallelism bug if shutting the `ExecutorService` down happens after the check but before the tasks are submitted). If the executor service *is* shut down and will not accept new tasks, still, `failRejected` will be called, and `okhttp3.Dispatcher#finished$okhttp(okhttp3.internal.connection.RealCall.AsyncCall)` will make sure that the counter is decremented and the rejected task is removed from the queue. Looks pretty identical, except that failing to check `isShutdown` leads to an `O(tasks submitted)` recursion of `promoteAndExecute` calls.

**Comment by yschimke** [comment]
I'm pretty sure we won't change the API here with OkHttpDefaultThreadPool. But we should make this optimal for typical Android apps using coroutines and OkHttp.

I actually this the `fun CoroutineDispatcher.asExecutorService` example looks optimal.

@swankjesse I suspect you have stronger opinions than I do on this.

Would you be happy to improve the pattern for sharing threads with okhttp `Dispatcher` and coroutines `Dispatchers.IO`?  If we agree a pattern, we can support this in okhttp-coroutines in 5.0, and can be copy pasted into place for 4.x.

**Comment by dkhalanskyjb** [comment]
This wrapper is really a hack though. We're tricking the type system into accepting a plain `Executor` where "an `Executor` that can be shut down" is expected. This works only because it's *not* actually needed that the `Executor` can be shut down. That's a really roundabout way of saying, "any executor is fine for this."

> I'm pretty sure we won't change the API here with OkHttpDefaultThreadPool

Not really my business, but I'm genuinely curious why not. Is backward compatibility with the existing tutorials etc., the only concern, or are there technical reasons for this?

> I actually this the `fun CoroutineDispatcher.asExecutorService` example looks optimal.

API-wise, it's just a quick hack. Thinking about it for a bit, a cleaner way to do this would be to split the logic:
```kotlin
fun Executor.asNonTerminatingExecutorService(): ExecutorService = object : Executor by this, AbstractExecutorService() {
    override fun shutdown() {
        throw UnsupportedOperationException("shutdown is not implemented")
    }

    override fun shutdownNow(): MutableList<java.lang.Runnable> {
        throw UnsupportedOperationException("shutdownNow is not implemented")
    }

    override fun isShutdown(): Boolean = false

    override fun isTerminated(): Boolean = false

    override fun awaitTermination(timeout: Long, unit: TimeUnit): Boolean = false
}

fun CoroutineDispatcher.asExecutorService(): ExecutorService = asExecutor().asNonTerminatingExecutorService()
```
... and then not provide the second function at all, because it's trivial. And the first one has really nothing to do with coroutines. In fact, you can take the first function as is and just use it in your implementation to allow passing an arbitrary `Executor` to `dispatcher`, making your API a bit more general.

> Would you be happy to improve the pattern for sharing threads with okhttp `Dispatcher` and coroutines `Dispatchers.IO`?

Not really sure what we can do from the coroutines side, but sure, I'll help if I can.

**Comment by swankjesse** [comment]
We don’t break binary compatibility in OkHttp so changing the field’s type is a no-go.

The adapter is a fine hack and I’d recommend you use it if you’d like to use a CoroutineDispatcher as an ExecutorService. You can probably change the shutdown functions to reject future tasks on that adapter, without impacting the underlying CoroutineDispatcher.

We’re not going to include this API in OkHttp, just in the interest of keeping the library small. We aim to cover the intersection of most users’ needs, not the union of them.

**Comment by swankjesse** [comment]
BTW, I think having “one big app-wide thread pool” is a bad strategy in general. It prevents you from guaranteeing high-urgency work will be able to start immediately while low-urgency work can queue up.

**Comment by dkhalanskyjb** [comment]
> We don’t break binary compatibility in OkHttp so changing the field’s type is a no-go.

The field's type wouldn't be changed. Essentially, I'm just proposing a new constructor for `class Dispatcher`:
```kotlin
  constructor(executor: Executor) : this() {
    this.executorServiceOrNull = executor.asNonTerminatingExecutorService()
  }
```

**Comment by swankjesse** [comment]
Gotcha. I still don’t think it’s broadly useful for inclusion in OkHttp. (I can be convinced here!)

**Comment by dkhalanskyjb** [comment]
> You can probably change the shutdown functions to reject future tasks on that adapter

Sure, but what purpose would it serve? Calling `shutdown` on it could leave the caller with the impression that some threads would be stopped, when in fact, they wouldn't. Easier to just not call `shutdown` at all. Throwing from `shutdown` solves that.

> BTW, I think having “one big app-wide thread pool” is a bad strategy in general.

It's possible to use `Dispatchers.IO` in a way that deals with this well: if someone uses `Dispatchers.IO.limitedParallelism(64)` as OkHttp's dispatcher, then up to 64 new threads can be created dynamically just to deal with a burst of urgent work in OkHttp.

> I still don’t think it’s broadly useful for inclusion in OkHttp.

My whole point is this: `constructor(executorService: ExecutorService)` doesn't meaningfully use the fact that the executor is also an executor service, so there's no reason for it to *require* a service.

**Comment by swankjesse** [comment]
Yep, agreed that our API as-is got it wrong. But the amount of code to work-around that small mistake is too high.

**Comment by dkhalanskyjb** [comment]
Well, I'm out of arguments, and I've reached my goal of raising awareness of this problem, so it's your call at this point.
