### ISSUE TITLE
java.lang.reflect.InaccessibleObjectException: Unable to make field private final java.lang.String java.security.cert.Certificate.type

### ISSUE THREAD

**Issue by PragnikaP** [square/okhttp#7674]
Getting the below exception while making a get call with authToken
Request request = new Request.Builder()
                    .url("https://sampleurlexample12345.com/api/apiname?param1=value1&param2=value2")
                    .addHeader("Accept", "application/xyz.v1+json")
                    .addHeader(AUTHORIZATION_HEADER_VALUE,
                            BEARER_TOKEN + accessToken)
                    .build();
java.lang.reflect.InaccessibleObjectException: Unable to make field private final java.lang.String java.security.cert.Certificate.type accessible: module java.base does not "opens java.security.cert" to unnamed module

**Comment by yschimke** [comment]
Without more information we can't confirm the issue. It's likely an issue with newer JVM and java modules.

Consider posting to a site like stackoverflow with a full stacktrace and JVM version

**Comment by PragnikaP** [comment]
This is coming in response object of the get call, not getting an exception from our application, below is the full response object.

Response{protocol=h2, code=200, message=, url=https://sampleurlexample12345.com/api/apiname?param1=value1&param2=value2}
java.lang.reflect.InaccessibleObjectException: Unable to make field private final java.lang.String java.security.cert.Certificate.type accessible: module java.base does not "opens java.security.cert" to unnamed module

**Comment by yschimke** [comment]
That looks like the Response ends before that warning.  Please continue on stackoverflow or with colleagues.

We can't provide 1:1 support.
