### ISSUE TITLE
`RealCall` leaking in `ConnectionListener` `connectEnd`

### ISSUE THREAD

**Issue by lauzadis** [square/okhttp#7680]
`RealCall` is leaked into the public in `connectEnd`. Should it be a reference to `Call` instead?

https://github.com/square/okhttp/blob/5402ebaaa67ae05975e7d02490ef4003fdf3a4da/okhttp/src/jvmMain/kotlin/okhttp3/ConnectionListener.kt#L42

**Comment by yschimke** [comment]
@lauzadis Thanks, good catch.
