### ISSUE TITLE
PublicSuffix list looks to be quite outdated and missing recent additions

### ISSUE THREAD

**Issue by CDRussell** [square/okhttp#7699]
Hey 👋

I'm looking here https://github.com/square/okhttp/tree/master/okhttp/src/jvmMain/resources/okhttp3/internal/publicsuffix and seeing the public suffix list hasn't been updated in 2 years. 

I ask because I noticed `foo.myshopify.com` and `bar.myshopify.com` are both returning `myshopfiy.com` as e-TLD+1, despite `myshopify.com` being on the [public suffix list](https://publicsuffix.org/list/public_suffix_list.dat).

**Questions**

1. Is the file I linked to above just a placeholder, and an updated version is grabbed some other way, or is it really just quite outdated?
2. Is there some mechanism I should be doing outside of `okhttp` to provide a newer public suffix list for `okhttp` to consume?

Thanks!

**Comment by yschimke** [comment]
We should re-run https://github.com/square/okhttp/blob/50a71e76d290e5cc56ee6d1d626dee4b3f6492b1/okhttp/src/jvmTest/java/okhttp3/internal/publicsuffix/PublicSuffixListGenerator.java#L16

And get it into a 4.11.

**Comment by JakeWharton** [comment]
You can run it weekly on CI and have it make a PR if it has changed.

Here's an example to copy: https://github.com/mdogan/homebrew-zulu/blob/master/.github/workflows/upgrade.yml

**Comment by CDRussell** [comment]
Or since it only currently matters at the point of cutting a release, generating an updated suffix list at point of release maybe?

Would it be possible to get an idea on:

1. how likely this will be updated in the next release?
2. when that 4.11 might appear?

Even if you currently have no estimate to offer, knowing even that would still be useful for me to make some decisions around this. Ta!

**Comment by yschimke** [comment]
5.x PR https://github.com/square/okhttp/pull/7700
4.x PR https://github.com/square/okhttp/pull/7701

@swankjesse does the releases, but I don't think he'll want to give an exact date. My guess is small number of weeks rather than months.

**Comment by CDRussell** [comment]
Sorry for the bump, but wondering if there's likely to be any movement on this soon?
