### ISSUE TITLE
Make content-type header for each part of MultiPartBody configurable

### ISSUE THREAD

**Issue by xiangma9712** [square/okhttp#7725]
I'm using packages below and try to use multipart/form-data API.
- spring boot (as api client)
- open api generator (org.openapi.generator:6.2.1)
- okhttp (com.squareup.okhttp3:okhttp:4.10.0)

Tho I want to set content-type application/json to A part of request body so that backend service can property parse it,
okhttp doesn't allow the configuration.

https://github.com/square/okhttp/blob/ee1ba4656d80ed62485387217271c7fa31dc888e/okhttp/src/jvmMain/kotlin/okhttp3/MultipartBody.kt#L205

OpenApiSpecification supports encoding to set each part's content-type and open api generator recognize that configuration and try to set it but results in request failure.

**Comment by yschimke** [comment]
Seems closely related to https://github.com/square/okhttp/issues/5627

**Comment by yschimke** [comment]
Closing as a duplicate
