### ISSUE TITLE
PublicSuffixDatabase Cause ANR

### ISSUE THREAD

**Issue by sim0124** [square/okhttp#7749]
`PublicSuffixDatabase.get().getEffectiveTldPlusOne`
in this method，if readTheListUninterruptibly faild that will throw a exception
when call this method next, it will cause anr, because it always await.
it should reset the `listRead` when throw IllegalStateException

![image](https://user-images.githubusercontent.com/129145386/228138013-a7b6cee7-32f9-4cb0-aa75-17e653f1bf38.png)

**Comment by yschimke** [comment]
Thanks for the report, It's a bug we should fix, not sure of the right change to make. 

But a couple of questions

1) I'm surprised it is causing an ANR, since it's presumably doing that blocking call on the main thread.  Can you provide a stacktrace?

2) Can you explain why it's failing? This is hopefully lower priority since it signals a problem with your app. Or is there some reason it's happening in normal conditions?

**Comment by root0301** [comment]
> 

1、stacktrace is not convenient to provide。But you can easily reproduce this Anr。
In first read，you can make "PublicSuffixDatabase.class.getResourceAsStream(PUBLIC_SUFFIX_RESOURCE)" to return null，then the second call the "getEffectiveTldPlusOne" will cause Anr。

2、About the reason for the failure，google make a experiment about dynamic-feature，it may cause the read failure，we have many cases。

By the way, regardless of the reason for the read failure，it should reset the 'listRead' when throw IllegalStateException？

**Comment by sim0124** [comment]
> Thanks for the report, It's a bug we should fix, not sure of the right change to make.
> 
> But a couple of questions
> 
> 1. I'm surprised it is causing an ANR, since it's presumably doing that blocking call on the main thread.  Can you provide a stacktrace?
> 2. Can you explain why it's failing? This is hopefully lower priority since it signals a problem with your app. Or is there some reason it's happening in normal conditions?

1、stacktrace is not convenient to provide。But you can easily reproduce this Anr。
In first read，you can make "PublicSuffixDatabase.class.getResourceAsStream(PUBLIC_SUFFIX_RESOURCE)" to return null，then the second call the "getEffectiveTldPlusOne" will cause Anr。

2、About the reason for the failure，google make a experiment about dynamic-feature，it may cause the read failure，we have many cases。

By the way, regardless of the reason for the read failure，it should reset the 'listRead' when throw IllegalStateException？

**Comment by sim0124** [comment]
> Thanks for the report, It's a bug we should fix, not sure of the right change to make.
> 
> But a couple of questions
> 
> 1. I'm surprised it is causing an ANR, since it's presumably doing that blocking call on the main thread.  Can you provide a stacktrace?
> 2. Can you explain why it's failing? This is hopefully lower priority since it signals a problem with your app. Or is there some reason it's happening in normal conditions?

add a message，we use the old version(java), in the readList method，
`    InputStream resource = PublicSuffixDatabase.class.getResourceAsStream(PUBLIC_SUFFIX_RESOURCE);
    if (resource == null) return;`
it return when the resource is null, but the readCompleteLatch is not countdown，so the second call will block。
But I see the kotlin version seems that there is no such problem。
In your commit，if read fail，it seems not to read the resource anymore?

**Comment by yschimke** [comment]
@sim0124 Yep - I'm assuming a read is permanently failed.  So I countdown the latch, so it is considered complete.  But it already throws when it can't read.

There is no point doing the I/O repeatedly if it's failing.  failing cheap, instead of expensive.

**Comment by sim0124** [comment]
> @sim0124 Yep - I'm assuming a read is permanently failed. So I countdown the latch, so it is considered complete. But it already throws when it can't read.
> 
> There is no point doing the I/O repeatedly if it's failing. failing cheap, instead of expensive.

But in that google dynamic-feature experiment, we found that it read fail at some time..,not permanently failed...
That's why I mention retry，lol

**Comment by yschimke** [comment]
That doesn't sound healthy? Are OkHttp classes ending up in a different binary than the public suffix data file?

> About the reason for the failure，google make a experiment about dynamic-feature，it may cause the read failure，we have many cases。

It wasn't clear from this.  I'm not sure we want to support this file not being present initially and then appearing.

**Comment by sim0124** [comment]
> It wasn't clear from this. I'm not sure we want to support this file not being present initially and then appearing.

We have other solutions, here are just to give you the possible situation～  Looking at this problem from a different angle, retrying or not retrying is ok～

**Comment by swankjesse** [comment]
Agreed with @yschimke: if the file is absent we expect it to stay absent. Perhaps we could test to confirm that if it fails once, it fails on all subsequent attempts. (I believe we already have this behaviour.)

**Comment by sim0124** [comment]
> We currently hang. The behaviour you want comes in #7827

ok～ thank you so much

**Comment by yschimke** [comment]
@sim0124 That reply was to Jesse, it will fail permanently after the first failure. I'm not sure you are happy with that behaviour.
