### ISSUE TITLE
Authentication retries docs are misformated + missing kotlin version

### ISSUE THREAD

**Issue by ColtonIdle** [square/okhttp#7752]
Looks to be misformatted and missing kotlin version of the code snippet

<img width="719" alt="2023-03-31 at 18 14 33" src="https://user-images.githubusercontent.com/31751141/229242321-a024dfa4-af37-4da3-a55e-cb909b82ac5b.png">

**Comment by yschimke** [comment]
Formatting should be fixed by https://github.com/square/okhttp/pull/7548

We don't have kotlin for all kdocs, if you think it's novel enough to deserve a sample, feel free to put up a PR.

Closing for now.
