### ISSUE TITLE
Prioritizing network requests per host

### ISSUE THREAD

**Issue by zsweigart** [square/okhttp#7757]
This is a feature request similar to https://github.com/square/okhttp/issues/1361 and https://github.com/square/okhttp/issues/404

Because of the complexities mentioned by @swankjesse in this [comment](https://github.com/square/okhttp/issues/1361#issuecomment-72937939) we were trying to find a solution that could be built on top of OkHttp with our specific parameters. One solution we thought we found was to override some of the internals of OkHttp, but we were limited due to the fact that these classes are final or have internal/private constructors. One such solution is described below.

The **TL;DR** feature request is to support more customizability in the queuing structure. **Option 1:** make Dispatcher an interface that we can implement and make the current `Dispatcher` a `Default Dispatcher`. **Option 2:** make `OkHttpClient` constructor that takes a `Builder` would be made public and `RealCall` could be made an `open` class with a public constructor.

We are trying to add a priority queue to our OkHttp requests as we have 3 different types of network requests that should be executed in priority order even with the consideration that that may starve lower priority requests. All of these calls go to the same host so the max requests per host limit is in effect. Additionally, we don't want to increase max requests per host to the max requests value so we don't overload our servers. We have two possible suggestions for how this could be done.

**Option 1:** Make `Dispatcher` an interface so that we can build our own dispatcher according to our business rules and can control when requests are executed. All of the current `internal` and public functions would be made public and would be part of the interface with `enqueue` being the key function to implement. This would make `enqueue` public which may be less than ideal since developers usually shouldn't be enqueuing themselves directly, but would allow for more customization in dispatch logic.

*Option 2:** suggested by @swankjesse was to create our own `Call.Factory`. `OkHttpClient` is an `open` class which implements `Call.Factory` so we could subclass it and override `newCall` to return a new type of `Call` that extends `RealCall` and implements it's own `enqueue` to add it's call to the priority queue. We would then have then have to have an `EventListener` that keeps track of the number of active calls per host and total calls since that is not public from the `Dispatcher` by listening for `start` to increment and `cancelled`, `callEnd` or `callFailed` to pop off a value and enqueue it to the `Dispatcher`.

The problem with this solution is that while `OkHttpClient` is `open`, it's constructor is `internal`. It does have a public constructor but that uses a default `Builder` which means we can't override the parameters like adding network interceptors which then is a problem. Also `RealCall` is a final class so we can't simply extend it and we would have to copy-paste most of it's logic.

**Comment by yschimke** [comment]
The Call.Factory solution doesn't require extending OkHttpClient.  Just create a new Call.Factory that delays the actual enqueue.

Below is an example Call.Factory to creates a new subclass of Call, that defers enqueue until a high bandwidth network is available, and then submits.     

See https://github.com/google/horologist/blob/38d3c1e089d22ccfff34bbd739de8bc5462e867d/network-awareness/okhttp/src/main/java/com/google/android/horologist/networks/okhttp/NetworkSelectingCallFactory.kt#L73-L86

https://github.com/google/horologist/blob/38d3c1e089d22ccfff34bbd739de8bc5462e867d/network-awareness/okhttp/src/main/java/com/google/android/horologist/networks/okhttp/impl/HighBandwidthCall.kt#L72-L84

You could do something similar.
