### ISSUE TITLE
Cache return a response 200 when critical error 401 or 404 🙉

### ISSUE THREAD

**Issue by cchaouachi** [square/okhttp#7763]
Hello,

We want to use okhttp to cache our data, and use it if no internet connection or if the response is an internal server http code error like 503.. 500 and throw the exception when critical http code error like 401, 404.
 
The cache okhttp keeps returning a response 200 even the network response is critical.
 
Is it the intended behavior ?
 
okhttp version : 4.10.0
Plateform : Android.

**Comment by yschimke** [comment]
I can't explain what you are seeing.  Add an event listener, including cache events, and post here so we can investigate.

I think OkHttp will return these failures in all cases, and conditionally write the error to the cache. This is assuming conditional requests and you don't get a 304.

See https://github.com/square/okhttp/blob/57005571fa7cc4345d8446e540eb974787ba9ed9/okhttp/src/jvmMain/kotlin/okhttp3/internal/cache/CacheInterceptor.kt#L128

The different error codes do affect whether the cache is cleared https://github.com/square/okhttp/blob/57005571fa7cc4345d8446e540eb974787ba9ed9/okhttp/src/jvmTest/java/okhttp3/CacheTest.java#L112

I suspect you can do this with an Application Interceptor. The interceptor can catch the failed response, check if the cache was populated and then resubmit a second request with `request.newBuilder().cacheControl(CacheControl.FORCE_CACHE).build()`
