### ISSUE TITLE
SocketTimeoutException while trying to play video stream

### ISSUE THREAD

**Issue by menscikov** [square/okhttp#7764]
Hello,

One of the users sent to me public video stream link: [Video](https://streaming-live-app.rtp.pt/liverepeater/smil:rtp1HD.smil/playlist.m3u8)

With OkHttp i get SocketTimeoutException.
With other libraries, for example ExoPlayer DefaultHttpDataSource or Cronet everything is working fine.

Is it possible to fix that bug?

**Comment by yschimke** [comment]
This doesn't have enough information to reproduce.  I quick test in an android test shows both URLConnection and OkHttp get a 204, with 0 content.

And curl also shows the same result.

Please consider asking on a site like stackoverflow, we can't help 1:1 with usage issues.

```
import java.net.URL
import okhttp3.Headers
import okhttp3.HttpUrl.Companion.toHttpUrl
import okhttp3.OkHttpClient
import okhttp3.Protocol
import okhttp3.Request
import org.junit.jupiter.api.Test

class VideoTest {
  @Test
  fun testQuery() {
    val client = OkHttpClient.Builder()
      .protocols(listOf(Protocol.HTTP_1_1))
      .build()

    val request = Request(
      url = "https://streaming-live-app.rtp.pt/liverepeater/smil:rtp1HD.smil/playlist.m3u8".toHttpUrl(),
      headers = Headers.headersOf("User-Agent", "")
    )
    val response = client.newCall(request).execute()

    println(response.code)
    println(response.headers)

    val conn = URL(request.url.toString()).openConnection()
    conn.connect()
    println(conn.contentType)
    println(conn.headerFields)
  }
}
```

**Comment by menscikov** [comment]
@yschimke thank you very much for testing this link.
I tried your code, and i can confirm that everything is fine.

The problem is when i use it with `OkHttpDataSource` in ExoPlayer. I will contact them about the problem.

**Comment by yschimke** [comment]
Are you using the latest version? There is at least one error in an older version, that could cause timeouts like this over HTTP2, that is fixed in the latest version.

**Comment by menscikov** [comment]
@yschimke yes, i'm using the latest version of `OkHttp` and `ExoPlayer` libraries.
I tried to increase `OkHttp` timeout, but it doesn't help. It looks like something is on `ExoPlayer OkHttpDataSource` extension side. With their default `DefaultHttpDataSource` everything is working fine.
The problem is only with this video stream link, all other streams are working fine.

**Comment by yschimke** [comment]
Add an event listener to print the events out. If you can reproduce in the exoplayer sample project I can take a look.

I'm using exoplayer with OkHttp myself without issue.

Also previous problems (including dead socketsz android doesn't always close properly) are worked around by OkHttp/1.1, so might be worth seeing if it happens when http/2 is disabled.

**Comment by menscikov** [comment]
@yschimke i get only this in the `OkHttp` log: `HTTP FAILED: java.net.SocketTimeoutException: timeout`. Or you mean event listener for `ExoPlayer`?
Have you tried to open this video link in your `ExoPlayer + OkHttp` project?

This video link is not working with VLC player also for example, but is loading with `ExoPlayer + DefaultHttpDataSource`.

If you can't reproduce, i can try to make a sample project.

**Comment by yschimke** [comment]
I don't have a client handy, something like the demo app might work https://github.com/google/ExoPlayer/blob/release-v2/demos/main/src/main/java/com/google/android/exoplayer2/demo/PlayerActivity.java

But if you can make a sample project to reproduce, I can take a look.

I meant this event listener

https://square.github.io/okhttp/features/events/

**Comment by menscikov** [comment]
@yschimke here is the files to replace in the demo project.
Please check, video will throw exception.
If you comment 93 line in the `DemoUtil.java` class, video will play.

[demo.zip](https://github.com/square/okhttp/files/11243106/demo.zip)

**Comment by yschimke** [comment]
Cronet also fails for me with

```
20:22:33.841  E  internalError [eventTime=0.09, mediaPos=0.00, window=0, loadError
                   com.google.android.exoplayer2.ParserException: Input does not start with the #EXTM3U header.
                       at com.google.android.exoplayer2.source.hls.playlist.HlsPlaylistParser.parse(HlsPlaylistParser.java:260)
                       at com.google.android.exoplayer2.source.hls.playlist.HlsPlaylistParser.parse(HlsPlaylistParser.java:68)
                       at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:176)
                       at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:412)
                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
                       at java.lang.Thread.run(Thread.java:923)
                 ]
```

I'm guessing they are actively blackholing this traffic, based on some identification of the client. Do you have permission to use this feed?

**Comment by menscikov** [comment]
@yschimke yes i see that it fails on `Cronet` also, only `DefaultHttpDataSource` is able to play this video stream.

Unfortunately i don't have any information about this video stream, the user said that this is a legal public video stream, so i tried to check why it's not working.
If you think that the problem is created specifically on the service side of this video to protect against unauthorised connections, then please close this issue.

**Comment by yschimke** [comment]
It seems to fail everywhere in different ways, including firefox and curl.  So it's not healthy.

If you find it working generally, and just not for OkHttp then I can take a further look.

**Comment by menscikov** [comment]
@yschimke i'm a Mac user and i just tried to open that link in the QuickTime Player, video opened immediately.

But maybe you're right about blackholing the traffic. According to a link, i opened the website rtp.pt and found this video here: https://www.rtp.pt/play/direto/rtp1.
I think that user just extracted the video link from this website and tried to watch it in the external video player.

But it's strange that it's working with `DefaultHttpDataSource` class and QuickTime Player, but it's not working with different libraries.
