### ISSUE TITLE
 HTTP FAILED: java.lang.ArrayIndex0utofBoundsException: length=8192; index=-16

### ISSUE THREAD

**Issue by sasa2211** [square/okhttp#7776]
When making a request, project-global: HTTP FAILED: java,lang.ArrayIndex0utofBoundsException: length=8192; index=-16. I removed .cache(cache) from okhttp and the error doesn't appear anymore. I don't understand why this happens

**Comment by sasa2211** [comment]
Has anyone had a similar problem?

**Comment by yschimke** [comment]
Usually this error suggest non thread safe usage of OkHttp Response. But I'm not sure why cache is affecting it.

**Comment by yschimke** [comment]
Closing, but please reopen with a reproduction or at least a stacktrace.
