### ISSUE TITLE
Update Docs and Repo for 4.11

### ISSUE THREAD

**Issue by vanshg** [square/okhttp#7788]
Seems like a 4.11 release was made last week. This doesn't seem to be reflected in the docs website or README or CHANGELOG. Only reference I found is [here](https://github.com/square/okhttp/blob/master/docs/changelogs/changelog_4x.md)

https://mvnrepository.com/artifact/com.squareup.okhttp3/okhttp/4.11.0
https://github.com/square/okhttp/compare/parent-4.10.0...parent-4.11.0

**Comment by techwnn** [comment]
Me too, I don't know what's updated.

**Comment by m15o** [comment]
@yschimke 
Could you please update `https://square.github.io/okhttp/changelogs/changelog_4x/` too.

**Comment by andregasser** [comment]
Would be interested in an official changelog for 4.11 as well, as Github's Dependabot told me couple of weeks ago that 4.11 was released and I should upgrade.

**Comment by yschimke** [comment]
This is the official changelog https://github.com/square/okhttp/blob/master/docs/changelogs/changelog_4x.md

Updating the docs site is a separate process, not sure when it will be run.
