### ISSUE TITLE
Passing Instant.MIN to Headers.Builder#add(String, Instant) causes ArithmeticException

### ISSUE THREAD

**Issue by dfraser** [square/okhttp#7796]
java.lang.ArithmeticException: long overflow
	at java.base/java.lang.Math.multiplyExact(Math.java:1004)
	at java.base/java.lang.Math.multiplyExact(Math.java:980)
	at java.base/java.time.Instant.toEpochMilli(Instant.java:1236)
	at okhttp3.Headers$Builder.add(Headers.kt:297)

Java 17, with okhttp maven version 4.11.0

**Comment by OpticKing12** [comment]
> java.lang.ArithmeticException: long overflow at java.base/java.lang.Math.multiplyExact(Math.java:1004) at java.base/java.lang.Math.multiplyExact(Math.java:980) at java.base/java.time.Instant.toEpochMilli(Instant.java:1236) at okhttp3.Headers$Builder.add(Headers.kt:297)
> 
> Java 17, with okhttp maven version 4.11.0

**Comment by yschimke** [comment]
I'm not sure what a fix is here. DateTimeFormatter breaks for me trying to format those dates. So you might want to set a string yourself if you really need this.
