### ISSUE TITLE
Media range matching

### ISSUE THREAD

**Issue by swankjesse** [square/okhttp#782]
We could implement support for [matching media types](http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html):

```
       Accept: audio/*; q=0.2, audio/basic
```

As suggested by @rubUx4 here https://github.com/square/okhttp/pull/762

**Comment by swankjesse** [comment]
Iceboxing this. Accepting small, well-motivated patches.

**Comment by yschimke** [comment]
Closing as low priority.  Re-open if there is a compelling sue case we are missing.
