### ISSUE TITLE
Getting SocketException: Connection reset with OHttp3 Client

### ISSUE THREAD

**Issue by dineshv1234567** [square/okhttp#7848]
**Problem:**
I am using OkHttp3 Client in Quarkus project, but I am getting the following error in production:
`java.net.SocketException: Connection reset at java.net.SocketInputStream.read(SocketInputStream.java:186) ~[?:?] at java.net.SocketInputStream.read(SocketInputStream.java:140)`

**Details**
My project is a type of middle layer that is calling the Backend APIs as a client, parses the response, and sends it back to the Front end. But sometimes, it throws the above exception when calling downstream APIs. In the case of a GET request, it retries two times, gets same exception and in third retry, a successful response is returned. But in POST request, it does not retries because of idempotency and fails in the first occurrence only.

_Code:_

```
public class CustomOkHttpClient extends HttpClient {
    private OkHttpClient client;
	public Response callDownstream(HttpRequest clientRequest){
	Response clientResponse = null;
        try {
            Call call = client.newCall(clientRequest);
            clientResponse = call.execute();
            return parseClientResponse(clientResponse, responseClass);
        } catch (final Exception exception) {
            logger.error("Exception occurred");
            throw exception;
        } finally {
            if (null!=clientResponse) {
                clientResponse.close();
            }
        }
     }
  }

```

_Dependencies used:_ 
 com.squareup.okhttp3:
-     okhttp-urlconnection: 5.0.0-alpha.2
-     logging-interceptor: 4.9.3
-     mockwebserver: 4.9.0

**Ways tried**

- Used finally block to close the connection.
- Increased readTimeOut value of http client, but same error is happenning.

**Request by Team**

- What approach can I do further? 
- Is this possible that the connection gets closed due to idle time period because no traffic is present during that time, and when after some long time, when request hit is made, it gets failed.

**Comment by yschimke** [comment]
Use an application interceptor and implement your custom retry logic.

https://square.github.io/okhttp/features/interceptors/#choosing-between-application-and-network-interceptors

Generally we can't avoid network errors, and follow GET/POST rules for whether we can safely retry. But you can implement knowing whether POSTs are safe in your case. There are lots of blog posts discussing this topic.

For HTTP/2 you can set a ping interval https://square.github.io/okhttp/4.x/okhttp/okhttp3/-ok-http-client/-builder/ping-interval/
