### ISSUE TITLE
OkHttp 4.11 prints to stdout on connect timeout when hitting some servers

### ISSUE THREAD

**Issue by madisp** [square/okhttp#7851]
When hitting non-existent APIs with multiple IP addresses then OkHttp prints exceptions to stdout.

Reproducing Kotlin code:

```kotlin
import okhttp3.OkHttpClient
import okhttp3.Request

fun main() {
  val client = OkHttpClient.Builder().build()
  val request = Request.Builder().url("https://api.emulator.wtf:1234").build()
  client.newCall(request).execute().use { println(it.body?.string()) }
}
```

Running this prints the stacktrace to stderr (expected) and an exception array to stdout (unexpected!)

```
[java.net.SocketTimeoutException: Connect timed out, java.net.SocketTimeoutException: Connect timed out]
```

output is printed from here:

https://github.com/square/okhttp/blob/68a106d3269b0ad02136a1bfa81c07a6c006fffe/okhttp/src/main/kotlin/okhttp3/internal/Util.kt#LL622C5-L622C5

---

This only happens to some hosts - e.g. `api.emulator.wtf` prints stuff while hitting `google.com:1234` does not.
I think this is related to the `api.emulator.wtf` host having multiple `A` DNS records? Does OkHttp do round-robin retries while adding previous attempts to a suppressed list?

```
$ dig a api.emulator.wtf +short
52.51.141.114
54.72.85.49
54.229.83.45
$ dig a google.com +short
216.58.209.174
```

---

we use OkHttp in a cli tool that is expected to only write JSON to standardout, the only current workaround seems to be replacing `System.out` completely to make sure nothing gets printed from OkHttp.

**Comment by madisp** [comment]
NOTE: does not appear to be an issue with 5.x alphas

**Comment by yschimke** [comment]
Thanks, not sure whether I thought this was useful at the time, or just left some debugging in place.
