### ISSUE TITLE
OkHttp caches responses with `expires: -1` headers

### ISSUE THREAD

**Issue by fpearson1111** [square/okhttp#7853]
I am contacting a server using OkHttp and the server responds with a 200 OK response with a header of expires: -1. OkHttp seems to place this in the cache because when I later send the same request again but with a different header it adds an if-modified-since header to my request. The new header I added should cause the server to respond differently, but instead it responds with a 304 Not Modified. This causes OkHttp to use the cached response which is actually not the same as what the server would respond with if OkHttp didn't add the if-modified-since header. Why does OkHttp add the first response to the cache when it has an expires: -1 header?

I tried: send a request to a server, then later send the same request with a different header

I expected: server sends a different response the second time, because of the different header

What resulted: the server sent back 304 Not Modified because OkHttp added if-modified-since to my second request

I am using OkHttp 4.10.0. I see the same behaviour on 4.11.0 and 5.0.0-alpha.11.

**Comment by yschimke** [comment]
I think we are following the spec here

https://www.rfc-editor.org/rfc/rfc7234#section-5.3

> The "Expires" header field gives the date/time after which the
   response is considered stale.  See [Section 4.2](https://www.rfc-editor.org/rfc/rfc7234#section-4.2) for further discussion
   of the freshness model.

>    A cache recipient MUST interpret invalid date formats, especially the
   value "0", as representing a time in the past (i.e., "already
   expired").

https://www.rfc-editor.org/rfc/rfc7234#section-4.2

>    If an origin server wishes to force a cache to validate every
   request, it can assign an explicit expiration time in the past to
   indicate that the response is already stale.

If you are sure this is incorrect can you provide a executable reproduction? A test? or a server to run requests against? Or logs including all headers?

**Comment by yschimke** [comment]
@swankjesse Just saw https://stackoverflow.com/questions/76339871/why-does-okhttp-cache-responses-with-expires-1-header, but it doesn't match my reading of the spec.

**Comment by fpearson1111** [comment]
Thanks @yschimke. So does that mean OkHttp is allowed to cache responses with `expires: -1` and to try and validate them later (by adding e.g. `if-modified-since`), and servers need to support this possibility? Just want to make sure I understand the spec.

**Comment by yschimke** [comment]
That's my understanding. But happy to debate, this was my first or at least only recent reading of this spec.
