### ISSUE TITLE
A Configurable Number of Redirects Followed

### ISSUE THREAD

**Issue by tyrantkhan** [square/okhttp#7868]
Back in https://github.com/square/okhttp/issues/82 it was asked to increase the number of redirects. This was covered in https://github.com/square/okhttp/pull/93.

It would be cool if instead we allowed the capability to make this value configurable. This would (Like say if i wanted on request to only follow up-to 5 redirects), but by default perform 20.

**Comment by yschimke** [comment]
Yep - it's now here https://github.com/square/okhttp/blob/b14b129a3f16139c9fe0ff23bcb46e0b00dbdfe7/okhttp/src/jvmMain/kotlin/okhttp3/internal/http/RetryAndFollowUpInterceptor.kt#L326

You should be able to disable retryOnConnectionFailure, and implement your own custom retry logic in an application interceptor.

Generally OkHttp doesn't aim to be hugely configurable or tunable, preferring to allow apps to take over when more complicated requirements are needed.

**Comment by tyrantkhan** [comment]
ok thanks for the context, much appreciated!
