### ISSUE TITLE
SNI failing on some hosts

### ISSUE THREAD

**Issue by tishma** [square/okhttp#7873]
Hi, I'm experiencing exactly the same issue as [here](https://github.com/square/okhttp/issues/4324#issuecomment-1136989382), so we now have at least 2 situations where http client is not succeessful doing SNI handshake part:

```
 ERROR  [dsa] javax.net.ssl.SSLPeerUnverifiedException: Hostname www.juwelier-boeckelmann.de not verified:
    certificate: sha256/dm0ek1u8AG4qjywoVqlmafQpsup7NIi5mlrheVGtkdE=
    DN: CN=letsencrypt-nginx-proxy-companion
```

I prefer not to mention host I'm trying to access, but you can still reproduce the problem like this:
```
        this.client = new OkHttpClient();
        Request request = new Request.Builder()
                .url("https://www.juwelier-boeckelmann.de")
                .build();
        try {
            this.client.newCall(request).execute();
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
```

It looks like during handshake - server is responding with the certificate as if we were using the ip address - not playing along with SNI.

I understand SNI is somehow part of Java since v8 (I'm using 11), and I've tried apache http client too without luck. That smells like a Java bug, and I'm wondering if there could be a workaround on lib level.

**Comment by tishma** [comment]
Okay, this was definitely Java related, and not a bug at all, but I can't stop thinking it's unfair to say that lib will automatically by default use a Java feature that's off by default.
So, adding a simple:
```
System.setProperty("jsse.enableSNIExtension", "true");
```
is what is called for.

**Comment by yschimke** [comment]
We make fairly opinionated decisions with fairly strong defaults, using the most secure capabilities of the underlying platform. In this case we are following the lead of the browser vendors more than the JVM.

I know it's frustrating, but SNI is a safe default we want on by default, and have some workarounds for when you really need to disable it.

**Comment by tishma** [comment]
@yschimke Thanks for your comment. Of course - it's your call if you want to mention it in the README or not. At least with this ticket - people like me will be able to relate the `SSLPeerUnverifiedException` with SNI being off much faster :)

**Comment by yschimke** [comment]
Let me take a look again. I thought the other issue was about needing to disable SNI when hosts don't support. 

Is your case because it's defaulted off and you want it enabled.

I'm also reading on mobile, so maybe just confused

**Comment by tishma** [comment]
Yes. I was just trying to consume the API that's out of my hands (and it worked until the partner changed their hosting to require SNI).
The host now has SNI on and returns wrong cert if client is not following.
My JVM had SNI extension off by default (thankfully both in dev and prod), so I've spent quite a while to sort it out.

**Comment by yschimke** [comment]
I don't think there is something for us to document here.  I think you should focus on why it's set to `false` for you.

From JDK 7 it defaults to `true`.

https://docs.oracle.com/javase/7/docs/technotes/guides/security/jsse/JSSERefGuide.html



Server Name Indication option | true | * jsse.enableSNIExtension system property. Server Name Indication (SNI) is a TLS extension, defined in RFC 4366. It enables TLS connections to virtual servers, in which multiple servers for different network names are hosted at a single underlying network address.  Some very old SSL/TLS vendors may not be able handle SSL/TLS extensions. In this case, set this property to false to disable the SNI extension.
-- | -- | --

**Comment by yschimke** [comment]
How about putting a conditional break point on System.setProperty and seeing who is calling it.  Or alternatively in the first line of your main to see if it's already set at launch?

**Comment by yschimke** [comment]
There are some JDK bugs that are relevant on early JDK 8 such as https://bugs.openjdk.org/browse/JDK-8144566 https://stackoverflow.com/questions/30817934/extended-server-name-sni-extension-not-sent-with-jdk1-8-0-but-send-with-jdk1-7

But we are still in the category of things that should be fixed already if you are using a recent JDK 11.

**Comment by tishma** [comment]
Thanks.

My IntelliJ uses bundled liberica-11.0.14.1 and my production JVM
is openjdk 11.0.4.

The former launches using gradle, and setProperty is not being called per
debugger/conditional breakpoint.
The latter is in ubuntu, so I'm able to see the java command invoking the
process, and it is pretty much vanilla - no property flags or files in
command line.

If it's just me, than you're certainly right that nothing should be
documented, and people should be able to find my comments if they stumble
upon this case.

Best,
Vladimir
