### ISSUE TITLE
java.net.SocketException: Socket closed

### ISSUE THREAD

**Issue by MrYeLiang** [square/okhttp#7875]
07-10 09:29:21.552 +0000 10127 10127 E AndroidRuntime: Caused by: java.net.SocketException: Socket closed
07-10 09:29:21.552 +0000 10127 10127 E AndroidRuntime: 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:394)
07-10 09:29:21.552 +0000 10127 10127 E AndroidRuntime: 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:230)
07-10 09:29:21.552 +0000 10127 10127 E AndroidRuntime: 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212)
07-10 09:29:21.552 +0000 10127 10127 E AndroidRuntime: 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)
07-10 09:29:21.552 +0000 10127 10127 E AndroidRuntime: 	at java.net.Socket.connect(Socket.java:621)
07-10 09:29:21.552 +0000 10127 10127 E AndroidRuntime: 	at okhttp3.internal.platform.AndroidPlatform.connectSocket(SourceFile:1)
07-10 09:29:21.552 +0000 10127 10127 E AndroidRuntime: 	at okhttp3.internal.connection.RealConnection.connectSocket(SourceFile:9)
07-10 09:29:21.552 +0000 10127 10127 E AndroidRuntime: 	at okhttp3.internal.connection.RealConnection.connect(SourceFile:14)
07-10 09:29:21.552 +0000 10127 10127 E AndroidRuntime: 	at okhttp3.internal.connection.StreamAllocation.findConnection(SourceFile:36)
07-10 09:29:21.552 +0000 10127 10127 E AndroidRuntime: 	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(SourceFile:1)
07-10 09:29:21.552 +0000 10127 10127 E AndroidRuntime: 	at okhttp3.internal.connection.StreamAllocation.newStream(SourceFile:6)
07-10 09:29:21.552 +0000 10127 10127 E AndroidRuntime: 	at okhttp3.internal.connection.ConnectInterceptor.intercept(SourceFile:5)
07-10 09:29:21.552 +0000 10127 10127 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:10)
07-10 09:29:21.552 +0000 10127 10127 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:1)
07-10 09:29:21.552 +0000 10127 10127 E AndroidRuntime: 	at okhttp3.internal.cache.CacheInterceptor.intercept(SourceFile:22)
07-10 09:29:21.552 +0000 10127 10127 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:10)
07-10 09:29:21.552 +0000 10127 10127 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:1)
07-10 09:29:21.552 +0000 10127 10127 E AndroidRuntime: 	at okhttp3.internal.http.BridgeInterceptor.intercept(SourceFile:22)
07-10 09:29:21.552 +0000 10127 10127 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:10)
07-10 09:29:21.552 +0000 10127 10127 E AndroidRuntime: 	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(SourceFile:9)
07-10 09:29:21.552 +0000 10127 10127 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:10)
07-10 09:29:21.552 +0000 10127 10127 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:1)
07-10 09:29:21.552 +0000 10127 10127 E AndroidRuntime: 	at d.e.e.t.c.intercept(SourceFile:45)
07-10 09:29:21.552 +0000 10127 10127 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:10)
07-10 09:29:21.552 +0000 10127 10127 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:1)
07-10 09:29:21.552 +0000 10127 10127 E AndroidRuntime: 	at d.e.e.e.intercept(SourceFile:14)
07-10 09:29:21.552 +0000 10127 10127 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:10)
07-10 09:29:21.552 +0000 10127 10127 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:1)
07-10 09:29:21.552 +0000 10127 10127 E AndroidRuntime: 	at com.a.b0.d.intercept(SourceFile:6)
07-10 09:29:21.552 +0000 10127 10127 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:10)
07-10 09:29:21.552 +0000 10127 10127 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:1)
07-10 09:29:21.552 +0000 10127 10127 E AndroidRuntime: 	at com.b.c0.c.intercept(SourceFile:9)
07-10 09:29:21.552 +0000 10127 10127 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:10)
07-10 09:29:21.552 +0000 10127 10127 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:1)
07-10 09:29:21.552 +0000 10127 10127 E AndroidRuntime: 	at okhttp3.RealCall.getResponseWithInterceptorChain(SourceFile:13)
07-10 09:29:21.552 +0000 10127 10127 E AndroidRuntime: 	at okhttp3.RealCall.execute(SourceFile:9)
07-10 09:29:21.552 +0000 10127 10127 E AndroidRuntime: 	at m.i.execute(SourceFile:15)
07-10 09:29:21.552 +0000 10127 10127 E AndroidRuntime: 	at d.e.e.u.c.a(SourceFile:11)
07-10 09:29:21.552 +0000 10127 10127 E AndroidRuntime: 	at d.e.e.o.d.a(SourceFile:23)
07-10 09:29:21.552 +0000 10127 10127 E AndroidRuntime: 	... 11 more

how to fix this issue?

**Comment by yschimke** [comment]
Use a site like stackoverflow, we can't give direct support.
