### ISSUE TITLE
java.io.EOFException: \n not found: limit=0 content=…

### ISSUE THREAD

**Issue by speekha** [square/okhttp#7880]
We recently upgraded from OkHttp 3.14 to OkHttp 4.10.0. Since then, we regularly run into the issue described in https://github.com/square/okhttp/issues/5390. It is not systematic but happens randomly, which would be consistent with the thread pool problem mentionned in the comments.

Apparently, this issue was closed after a month in 2019 but no fix is associated with it and other comments over the last 4 years show that other people have had it. The common workaround seems to be by using a retryOnConnectionFailure, but that's not an acceptable solution because we can see (through a local proxy) that the request (a POST request in our case) has been fully executed and the response returned. The issue lies with OkHttp reading said response. A retry means that the same POST request would get executed twice on the server.

Reverting to OkHttp 3.14 solves the issue.

**Comment by yschimke** [comment]
Without a reproduction I'm not sure there is much we can do.

There is a fix for 5.0 with a concurrency issue for websockets, but apart from that, I'm not sure of any fixes or known issues.

**Comment by speekha** [comment]
@yschimke Tried the migration again with 4.11, but ran into the same problem. I also used the retryOnConnectionFailure since the documentation says it only applies to establishing connection, but I had the exact problem I expected : the same request got executed twice, which won't work for a POST.
Is there any kind of logs I could gather to help you understand the cause?

**Comment by speekha** [comment]
As far as I can tell, the connection is established normally, the request gets posted, but the client can't read the response somehow.
