### ISSUE TITLE
请求回调耗时滞后

### ISSUE THREAD

**Issue by xiaxinqing** [square/okhttp#7885]
启动app首次调用网络请求，网络请求耗时延迟200~700毫秒不等
框架打印耗时56ms 但是到回调接口时却用了827ms
复现：杀掉app，重新启动。或者卸载重装
详见图片：
<img width="1416" alt="246043702-be022219-80b4-4a56-8795-1ed82ba67e00" src="https://github.com/square/okhttp/assets/15827197/cd2116cc-b571-49d3-80b3-d6a1cede775c">

**Comment by yschimke** [comment]
> Start the app to call the network request for the first time, and the network request time-consuming delay ranges from 200 to 700 milliseconds
It took 56ms to print the frame, but it took 827ms to reach the callback interface
To reproduce: kill the app and restart it. or uninstall and reinstall
See pictures for details:

You should profile your app on device, see what's taking the time.  It could be SSL initialisation.  But please continue the discussion on a site like stackoverflow, unless you have a confirmed reproducible bug.

We can't provide 1:1 support through the issue tracker.
