### ISSUE TITLE
add Headers：Authorization 乱码问题  4.11.0版本出现 使用Java 11

### ISSUE THREAD

**Issue by yywanbin** [square/okhttp#7902]
![a21b901bab533d11363116d38c599bc](https://github.com/square/okhttp/assets/31680083/b67314cc-7558-49f3-92b2-3cff7c530118)

升级使用v4.11.0版本后，Authorization 的Headers无法添加对应的Token  打印log显示乱码。
在回退版本v4.9.1版本 恢复正常。测试发现从 v4.9.3版本开始Authorization就出现上述问题。

**Comment by yschimke** [comment]
> After upgrading to version v4.11.0, the corresponding Token cannot be added to the Authorization Headers, and the print log shows garbled characters.
 Return to normal in the fallback version v4.9.1.  The test found that the above problems occurred in Authorization from the v4.9.3 version.

**Comment by yschimke** [comment]
Header redaction is a feature, are you sure it's not just this?

Please make a failing test case so we can reproduce this. Even a main file calling httpbin org

**Comment by yschimke** [comment]
I'd suggest using a site like stackoverflow, other wise will reopen with a reproduction.
