### ISSUE TITLE
How do I use an interceptor (or something else) to remove a Referer from a request after a redirect?

### ISSUE THREAD

**Issue by 821938089** [square/okhttp#7915]
(For some reason I can't sign up for StackOverflow right now, please don't close my issue.)

I find this seems to be impossible, except for handling redirects manually.
Any other way to do this would be appreciated.

**Comment by yschimke** [comment]
Use a network interceptor, and you can check the request and remove it.  

```
    val client = OkHttpClient.Builder()
        .addNetworkInterceptor(
            Interceptor {  chain ->
                chain.proceed(removeReferer(chain.request()))
            }
        ).build()

    private fun removeReferer(request: Request) = request.newBuilder()
        .removeHeader("Referer")
        .url(request.url.newBuilder().removeAllQueryParameters("referer").build())
        .build()
```

Please find a way to join stackoverflow, we can't provide 1:1 support here.

**Comment by 821938089** [comment]
You may have misunderstood me, or I may not have been clear enough.
I need to remove the Referer from requests after redirection, not all requests.

**Comment by yschimke** [comment]
Yep, you'll need to disable followRedirects on the client, and manually handle redirects in an application interceptor, or your application.

I am curious, OkHttp isn't adding the referer header, is this in your original request?

**Comment by 821938089** [comment]
Yes.

In browsers, the Referer is removed from the redirected request, but that's not the case with okhttp.

Handling redirects manually is far less convenient than using interceptors.

Hopefully in future releases something like the number of redirects or previous responses will be added to the request object to provide more information to process.

**Comment by yschimke** [comment]
OkHttp isn't adding the referer header
