### ISSUE TITLE
can UnixSocketAddress used for android？

### ISSUE THREAD

**Issue by BFELFISH** [square/okhttp#7927]
I want to user Unix Domain Socket in android with grpc.Here is my code:
`           InetSocketAddress address = new InetSocketAddress("localhost", port);
            Server server = OkHttpServerBuilder.forPort(address,InsecureServerCredentials.create()).socketFactory(new UnixDomainServerSocketFactory(socketFile))
                    .build().start();`

**Comment by BFELFISH** [comment]
But  got a runtime error,Here is the error:

`java.lang.ExceptionInInitializerError: Cannot determine cpu address size
E/AndroidRuntime(19579): 	at jnr.ffi.Platform.calculateAddressSize(Platform.java:314)
E/AndroidRuntime(19579): 	at jnr.ffi.Platform.<init>(Platform.java:290)
E/AndroidRuntime(19579): 	at jnr.ffi.Platform.<init>(Platform.java:31)
E/AndroidRuntime(19579): 	at jnr.ffi.Platform$Supported.<init>(Platform.java:582)
E/AndroidRuntime(19579): 	at jnr.ffi.Platform$Linux.<init>(Platform.java:730)
E/AndroidRuntime(19579): 	at jnr.ffi.Platform.determinePlatform(Platform.java:193)
E/AndroidRuntime(19579): 	at jnr.ffi.Platform.determinePlatform(Platform.java:211)
E/AndroidRuntime(19579): 	at jnr.ffi.Platform.access$000(Platform.java:31)
E/AndroidRuntime(19579): 	at jnr.ffi.Platform$SingletonHolder.<clinit>(Platform.java:40)
E/AndroidRuntime(19579): 	at jnr.ffi.Platform.getNativePlatform(Platform.java:327)
E/AndroidRuntime(19579): 	at jnr.unixsocket.SockAddrUnix.<clinit>(SockAddrUnix.java:34)
E/AndroidRuntime(19579): 	at jnr.unixsocket.SockAddrUnix.create(SockAddrUnix.java:174)
E/AndroidRuntime(19579): 	at jnr.unixsocket.UnixSocketAddress.<init>(UnixSocketAddress.java:47)
E/AndroidRuntime(19579): 	at com.example.grpc_proxy.unixdomainsockets.UnixDomainServerSocketFactory$UnixDomainServerSocket.bind(UnixDomainServerSocketFactory.java:54)
E/AndroidRuntime(19579): 	at java.net.ServerSocket.bind(ServerSocket.java:331)
E/AndroidRuntime(19579): 	at io.grpc.okhttp.OkHttpServer.start(OkHttpServer.java:79)
E/AndroidRuntime(19579): 	at io.grpc.internal.ServerImpl.start(ServerImpl.java:185)
E/AndroidRuntime(19579): 	at io.grpc.internal.ServerImpl.start(ServerImpl.java:94)`

so how can I use Unix Domain Socket for android with grpc

**Comment by yschimke** [comment]
Grpc is a different project. Ask there.

**Comment by yschimke** [comment]
https://stackoverflow.com/questions/74297407/can-i-use-a-unix-domain-socket-on-android

**Comment by BFELFISH** [comment]
> https://stackoverflow.com/questions/74297407/can-i-use-a-unix-domain-socket-on-android

thank you for your answer
