### ISSUE TITLE
TaskRunner with custom ExecutorService

### ISSUE THREAD

**Issue by MihaiRobescu** [square/okhttp#7957]
I'm trying to pass my own ExecutorService through the Dispatcher when executing requests with an OkHttpClient:

```
ExecutorService executorService = getContext().getExecutorService();
Dispatcher dispatcher = new Dispatcher(executorService);
((ThreadPoolExecutor) dispatcher.executorService()).setKeepAliveTime(0, TimeUnit.SECONDS);

OkHttpClient okHttpClient = new OkHttpClient.Builder()
        .dispatcher(dispatcher)
        .build();
```
The purpose is to close all the active threads immediately as I close my application. Whatever I tried I couldn't do that because all threads closed after 60s and, I noticed that TaskRunner has a hardcoded implementation of its own ExecutorService:

```
class RealBackend(threadFactory: ThreadFactory) : Backend {
    private val executor = ThreadPoolExecutor(
        0, // corePoolSize.
        Int.MAX_VALUE, // maximumPoolSize.
        60L, TimeUnit.SECONDS, // keepAliveTime.
        SynchronousQueue(),
        threadFactory
    )
/*.....*/

companion object {
    @JvmField
    val INSTANCE = TaskRunner(RealBackend(threadFactory("$okHttpName TaskRunner", daemon = true)))

    val logger: Logger = Logger.getLogger(TaskRunner::class.java.name)
}
```

Also, in my close( ) method I have these:
```
if (okHttpClient != null) {
        okHttpClient.dispatcher().cancelAll();
        okHttpClient.dispatcher().executorService().shutdownNow();
        okHttpClient.connectionPool().evictAll();
}
```
Every time I close the app, all TaskRunner threads (and other OkHttp threads) park and close after 60 seconds.
Is there any reason to hardcode a ThreadPoolExecutor inside a TaskRunner instance?
It would be a nice feature if we could customize OkHttpClients with our own ExecutorService. Although, I can do that through the Dispatcher, but it doesn't seem to make a difference or help me achieve my expectations.

**Comment by yschimke** [comment]
You will need to replace the TaskRunner also. I'll check tonight and confirm and provide a sample.

**Comment by MihaiRobescu** [comment]
A sample with that would be really helpful. Thanks!

**Comment by yschimke** [comment]
Yeah, I don't think it's possible, I found some extra ones.  We do this in tests via internal methods, specifically because TaskRunner is not public API.

Hence in OkHttpClient

```
    internal fun taskRunner(taskRunner: TaskRunner) = apply {
      this.taskRunner = taskRunner
    }
```

**Comment by yschimke** [comment]
I am a bit confused, the TaskRunner threads are daemon, so won't hold your app open.  

```
    val INSTANCE = TaskRunner(RealBackend(threadFactory("$okHttpName TaskRunner", daemon = true)))
```

**Comment by MihaiRobescu** [comment]
I understand. 
Also, is it possible to customize the thread names? It's useful for me because I'll use an OkHttpClient per application, on multiple applications, and if I can customize every thread name, for each OkHttpClient, I can distinguish them from one another.
The threads I noticed:
- OkHttp <URL domain>
- OkHttp TaskRunner
- Okio Watchdog

For example, if I can do as below would be really helpful:
- App1 OkHttp <URL domain>
- App1 OkHttp TaskRunner
- App1 Okio Watchdog
- App2 OkHttp <URL domain>
- App2 OkHttp TaskRunner
- App2 Okio Watchdog
- etc.

All the thread leak tests that I ran on different configs passed, with that delay of 60s so, at the moment I can say it's acceptable unless, there's still a chance to do thread leaks, which is not so good.

**Comment by swankjesse** [comment]
TaskRunner is an implementation detail of OkHttp. All instances share a single ExecutorService.

**Comment by Hartigan** [comment]
Is there any chance that it can be configured with virtual threads?

**Comment by yschimke** [comment]
This is an example of OkHttp with Loom.  https://github.com/square/okhttp/blob/c73f9842ad72e4169f2c2f149b5bdee83fb73a76/okhttp/src/jvmTest/java/okhttp3/LoomTest.kt#L28

If you notice any inappropriate blocking in real use, please let us know.
