### ISSUE TITLE
Is there a way to retrieve amount of requests enqueued for sending via enqueue() method?

### ISSUE THREAD

**Issue by andron3000** [square/okhttp#7962]
I would like to monitor total amount of requests which we enqueued for sending, is there a mechanism for this?

**Comment by yschimke** [comment]
Use an EventListener https://square.github.io/okhttp/features/events/

Tally them yourself.

**Comment by JakeWharton** [comment]
The `Dispatcher` also has a `queuedCalls` list that you can take the size of.

**Comment by andron3000** [comment]
Thanks.
