### ISSUE TITLE
Dispathcer.runningCallsCount🙉() method returns unpredictable value in case of work-stealing thread pool 

### ISSUE THREAD

**Issue by andron3000** [square/okhttp#7967]
Hi folks, 

I've added a simple performance test in order to test` queuedCallsCount()` and `runningCallsCount()` Dispathcer methods.

```
ExecutorService executorService = Executors.newWorkStealingPool();

Dispatcher dispatcher = new Dispatcher(executorService);
dispatcher.setMaxRequests(1000);
dispatcher.setMaxRequestsPerHost(1000);
```

![image](https://github.com/square/okhttp/assets/18425328/85707646-3f89-4d51-bb1d-94f5de0bd4b0)

Could you please explain me why `runningCallsCount()` returns value bigger then `maxRequests: 1000`?

![image](https://github.com/square/okhttp/assets/18425328/3b15f6cd-aaf4-4505-86a2-8c963cd7ca40)

**Comment by yschimke** [comment]
These limits only apply for `enqueue`d calls, not `execute`. If you think it's still an issue, please provide an executable reproduction.
