### ISSUE TITLE
ETag is mangled with a compression method

### ISSUE THREAD

**Issue by vanniktech** [square/okhttp#7988]
Using curl

```
curl -I https://lexfridman.com/feed/podcast
```

I get the following headers, as I'd expect:

```
HTTP/1.1 200 OK
Date: Sat, 19 Aug 2023 12:14:24 GMT
Server: Apache/2.4.55 (Ubuntu)
Last-Modified: Thu, 17 Aug 2023 20:37:40 GMT
ETag: "36d4b983b1bf2e278de73dd388cbb77c"
Link: <https://lexfridman.com/wp-json/>; rel="https://api.w.org/"
Content-Type: text/xml; charset=UTF-8
```

I'm aiming for the ETag, however when using OkHttp I'm getting `"36d4b983b1bf2e278de73dd388cbb77c-gzip"`. It seems like okhttp has added the compression method?

Here's a failing test case:

```
@Test fun foo() {
  val response = OkHttpClient().newCall(Request.Builder().get().url("https://lexfridman.com/feed/podcast").build())
    .execute()

  assertEquals("36d4b983b1bf2e278de73dd388cbb77c", response.headers[HttpHeaders.ETag])
}
```

Initially, I reported this at [Ktor](https://youtrack.jetbrains.com/issue/KTOR-6213) but it seems like this is a bug in okhttp.

----

Now if you use the etag returned from OkHttp, there's no match:

```
curl -I -H 'If-None-Match: "36d4b983b1bf2e278de73dd388cbb77c-gzip"' https://lexfridman.com/feed/podcast
HTTP/1.1 200 OK
Date: Sat, 19 Aug 2023 12:18:42 GMT
Server: Apache/2.4.55 (Ubuntu)
Last-Modified: Thu, 17 Aug 2023 20:37:40 GMT
ETag: "36d4b983b1bf2e278de73dd388cbb77c"
Link: <https://lexfridman.com/wp-json/>; rel="https://api.w.org/"
Content-Type: text/xml; charset=UTF-8
```

When I remove the `-gzip` prefix though it works as expected and I get a 304 Not modified:

```
curl -I -H 'If-None-Match: "36d4b983b1bf2e278de73dd388cbb77c"' https://lexfridman.com/feed/podcast
HTTP/1.1 304 Not Modified
Date: Sat, 19 Aug 2023 12:18:52 GMT
Server: Apache/2.4.55 (Ubuntu)
Last-Modified: Thu, 17 Aug 2023 20:37:40 GMT
ETag: "36d4b983b1bf2e278de73dd388cbb77c"
```

Note that the actual value of the ETag might change by the time you've had a look.

Something else also happens for the talking kotlin RSS Feed: https://talkingkotlin.com/feed
OkHttp prepends an `W/` which also breaks the ETag usage.

**Comment by yschimke** [comment]
It seems like the server can decide what is relevant to the etag. Are you sure this is a bug?

OkHttp automatically advertises gzip support, unless you set "accept-encoding: identity", so you can disable it.

But can you change your repro to make a second request and see whether it's returning a 304?

I'll take a look tonight, don't have laptop with me this weekend.

**Comment by yschimke** [comment]
For the second case, it looks like the server is marking these as weak validated.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/ETag

Isn't the etag all server side?

**Comment by connyduck** [comment]
Seems like the etag on the server is broken, definitely no bug in okhttp. The server responds differently for HEAD and GET requests. When I do `curl https://lexfridman.com/feed/podcast` (without `-I`) I get

```
Date: Sun, 20 Aug 2023 15:29:24 GMT
Server: Apache/2.4.55 (Ubuntu)
Last-Modified: Thu, 17 Aug 2023 20:37:40 GMT
ETag: "36d4b983b1bf2e278de73dd388cbb77c-gzip"
Link: <https://lexfridman.com/wp-json/>; rel="https://api.w.org/"
Vary: Accept-Encoding
Content-Encoding: gzip
Transfer-Encoding: chunked
Content-Type: application/rss+xml; charset=UTF-8
```

And the test passes when using HEAD
```

@Test fun foo() {
    val response = OkHttpClient().newCall(Request.Builder().head().url("https://lexfridman.com/feed/podcast").build())
        .execute()
    assertEquals("\"36d4b983b1bf2e278de73dd388cbb77c\"", response.headers["ETag"])
}
```

**Comment by vanniktech** [comment]
> Isn't the etag all server side?

From my understanding not. I want to basically do the same as here: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/ETag#caching_of_unchanged_resources

But thanks for enlightening me that this is due a head/get difference, thanks!

**Comment by yschimke** [comment]
> An ETag is an opaque identifier assigned by a Web server to a specific version of a resource found at a URL.

I just think the server is taking advantage of caching compressed and uncompressed content separately.

**Comment by vanniktech** [comment]
Indeed.

> curl --compressed -I -X GET https://lexfridman.com/feed/podcast

```
HTTP/1.1 200 OK
Date: Sun, 20 Aug 2023 16:32:24 GMT
Server: Apache/2.4.55 (Ubuntu)
Last-Modified: Thu, 17 Aug 2023 20:37:40 GMT
ETag: "36d4b983b1bf2e278de73dd388cbb77c-gzip"
Link: <https://lexfridman.com/wp-json/>; rel="https://api.w.org/"
Vary: Accept-Encoding
Content-Encoding: gzip
Transfer-Encoding: chunked
Content-Type: application/rss+xml; charset=UTF-8
```

I also found a SO question on this topic: https://stackoverflow.com/questions/29127144/cant-cache-resource-when-having-both-gzip-and-etag - it seems like they suggest to remove the content encoding prefix. Which is something I could do.

**Comment by vanniktech** [comment]
Just for the record. I wrote that RSS Feed author and asked him to fix this server side. The jetbrains feed does a nice job by supporting the `-gzip` etag correctly:

> curl --compressed -I -X GET https://blog.jetbrains.com/idea/feed/

```
HTTP/2 200
etag: "f699d4a8ed7477c34339b9970db52f6e-gzip"
```

> curl --compressed -I -X GET https://blog.jetbrains.com/idea/feed/ -H 'If-None-Match: "f699d4a8ed7477c34339b9970db52f6e-gzip"'
```
