### ISSUE TITLE
Check the response type in SSE

### ISSUE THREAD

**Issue by systemoutprintlnnnn** [square/okhttp#7992]
I used EventSource.Factory to create an EventSource and set the request header to "Accept" "text/event-stream". Unfortunately, when the response type is not as expected, the program still waits for the expected response. To resolve this issue, I added an interceptor in OkHttpClient to check the content type. However, I believe it would be better if we ensure that the response type is expected in the framework.

**Comment by systemoutprintlnnnn** [comment]
By the way, the version in my machine is 4.10.0

**Comment by yschimke** [comment]
Yep. That's part of the spec. We should change.

> Otherwise, if res's status is not 200, or if res's `Content-Type` is not `text/event-stream`, then fail the connection.

https://html.spec.whatwg.org/multipage/server-sent-events.html

**Comment by yschimke** [comment]
Went to implement this, but it's already there

https://github.com/square/okhttp/blob/parent-4.11.0/okhttp-sse/src/main/kotlin/okhttp3/internal/sse/RealEventSource.kt#L58-L62

Do you mean that the Response bytes are still consumed off the socket?

Can you provide a reproduction of the issue?
