### ISSUE TITLE
Ignore receiving server sided frames/messages in Websocket after calling a method

### ISSUE THREAD

**Issue by brahmkshatriya** [square/okhttp#7995]
I am making a mock discord client for manipulating RPC Presence for the user, & I just want to send data to the websocket gateway of discord.
Right now I am using a normal Websocket, and my users are experience way too much network usage because of how much useless stuff discord sends.
What I want to do is stop receiving data after the gateway sends the confirmation message. This I can prevent skyrocketing of the network usage.

I slightly looked into the Source code to find a method to do that I would need to create a new `WebSocketReader` which allows not reading the Messages, but sadly the class is not open

I would be very grateful if anyone lets me know how to achieve this without changing the source code of okhttp

**Comment by yschimke** [comment]
I don't think WebSocket protocol supports what you are asking for, if you close the socket to stop receiving data, the server will close and stop receiving your data as well.

You should look into the Discord protocol, a quick look suggests it's designed to allow you to manage this volume of events, so maybe start there.

https://discord.com/developers/docs/topics/gateway#gateway-intents

> While some events are sent to your app automatically, most events require your app to define intents when [Identifying](https://discord.com/developers/docs/topics/gateway#identifying). Intents are bitwise values that can be ORed (|) to indicate which events (or groups of events) you want Discord to send your app. A list of intents and their corresponding events are listed in the [intents section](https://discord.com/developers/docs/topics/gateway#gateway-intents).

> Maintaining a stateful application can be difficult when it comes to the amount of data your app is expected to process over a Gateway connection, especially at scale. Gateway intents are a system to help you lower the computational burden.
> 
> Intents are bitwise values passed in the intents parameter when [Identifying](https://discord.com/developers/docs/topics/gateway#identifying) which correlate to a set of related events. For example, the event sent when a guild is created (GUILD_CREATE) and when a channel is updated (CHANNEL_UPDATE) both require the same GUILDS (1 << 0) intent (as listed in the table below). If you do not specify an intent when identifying, you will not receive any of the Gateway events associated with that intent.
