### ISSUE TITLE
Upgrade dependency to mitigate vulnerability of com.squareup.okio:okio:3.2.0 

### ISSUE THREAD

**Issue by kpytlar** [square/okhttp#8003]
Okhttp has a dependency on com.squareup.okio:okio:3.2.0 which has a [denial of service vulnerability](https://security.snyk.io/vuln/SNYK-JAVA-COMSQUAREUPOKIO-5773320). Please upgrade an okio version where the vulnerability has been fixed (version 3.4.0 or higher).

**Comment by JakeWharton** [comment]
Dupe of #7979

**Comment by kpytlar** [comment]
Is there a scheduled release that will include the fix?
