### ISSUE TITLE
The requested data is out of order

### ISSUE THREAD

**Issue by qiaojinsong** [square/okhttp#8005]
The data returned under normal circumstances is：
response.request().urlString() :http://localhost.focusteach.com/pc/electron/detail?key=uu6bs&type=22&modeType=1&lasttime=1693173300665
response.body().string() : {"code":"0","value":{"lasttime":1693383408438,"type":22}}
response.request().urlString() :http://localhost.focusteach.com/pc/electron/detail?key=uu6bs&type=9&modeType=1&lasttime=1693239268484
response.body().string() : {"code":"0","value":{"lasttime":1693383408439,"obj":[{"bannerContent":"校风：绽放生命活力","id":"w00IyRDoAw8","modeType":1,"pcFlag":0,"updateTime":1508125082000}],"type":9}}

The data of a few abnormal situations are as follows:
response.request().urlString() :http://localhost.focusteach.com/pc/electron/detail?key=uu6bs&type=22&modeType=1&lasttime=1693173300665
response.body().string() : {"code":"0","value":{"lasttime":1693383408439,"obj":[{"bannerContent":"校风：绽放生命活力","id":"w00IyRDoAw8","modeType":1,"pcFlag":0,"updateTime":1508125082000}],"type":9}}

response.request().urlString() :http://localhost.focusteach.com/pc/electron/detail?key=uu6bs&type=9&modeType=1&lasttime=1693239268484
response.body().string() : {"code":"0","value":{"lasttime":1693383408438,"type":22}}

The requested data is out of order i use okhttp 2.7.0

**Comment by qiaojinsong** [comment]
I am using enqueue mode

**Comment by yschimke** [comment]
okhttp 2.7.0 is not supported
