### ISSUE TITLE
 support  blob schema

### ISSUE THREAD

**Issue by ALAZZURRI** [square/okhttp#8006]
Hello i have my app android kotlin and have service export to file as blob schema  how download file schema blob by okhttpi have url like this "blob:https://k2staging.com/4a482de0-ef29-43df-aa34-3cdf4d149bc1" h

when try i donwload get error

Expected URL scheme 'http' or 'https' but was 'blob'

**Comment by yschimke** [comment]
This is out of scope, we don't handle URLs apart from HTTP(S) and WS(S).

You should strip and handle it yourself.
