### ISSUE TITLE
hope okhttp can support true asynchronous requests.

### ISSUE THREAD

**Issue by izhouteng** [square/okhttp#8007]
The current `enqueue` method, from a syntactical perspective, appears to be asynchronous. However, in reality, each invocation of this `enqueue` method creates a separate working thread. It does not achieve genuine asynchronous non-blocking.

Let's consider the following scenario:

I need to develop a program to download 100,000 images from an OSS (Object Storage Service). Downloading each image takes approximately 1 second. I want to download all the images as quickly as possible (disregarding factors like local network speed or OSS server bandwidth), and I want to download 1,000 images simultaneously.

If we use the `enqueue` method as it is, it would actually create 1,000 working threads. This would result in high CPU context-switching overhead and significant memory wastage.

If it could support true asynchronous non-blocking behavior, then only one working thread would be needed, resulting in a considerable performance improvement.

**Comment by yschimke** [comment]
OkHttp takes a fairly opinionated approach to adopting thread per request. For typical workloads, particularly on mobile, this is typically the most performant approach.

There are other frameworks like Netty and Jetty that take other approaches, so there is little benefit to OkHttp trying to adopt this also.

Further even for JVM servers, with Loom, it's possible that this thread per request approach becomes the ideal approach given Loom's virtual threads.

If you really need 100,000s of concurrent requests, it's quite possible that OkHttp isn't the most performant library for you.  But this isn't going to be changed.

**Comment by swankjesse** [comment]
Also I expect Loom is going to make this a non-issue.
