### ISSUE TITLE
The connection pool domain name is different, and the IP address is the same and cannot be reused

### ISSUE THREAD

**Issue by daqiang5566** [square/okhttp#8012]
**Summary of the problem**

    In ConnectionPool, obtaining available connections cannot reuse connections with different domain names and the same IP address，Therefore, reducing the reuse rate of connection pools。

**The suggestions are as follows**

    The RealConnection method isEligible can support the above suggestions and different domain names with the same IP address can be reused for logic

The code is as follows
```
public boolean isEligible(Address address, @Nullable Route route) {
    // If this connection is not accepting new streams, we're done.
    if (allocations.size() >= allocationLimit || noNewStreams) return false;

    // If the non-host fields of the address don't overlap, we're done.
    if (!Internal.instance.equalsNonHost(this.route.address(), address)) return false;

    // If the host exactly matches, we're done: this connection can carry the address.
    if (address.url().host().equals(this.route().address().url().host())) {
      return true; // This connection is a perfect match.
    }

    // At this point we don't have a hostname match. But we still be able to carry the request if
    // our connection coalescing requirements are met. See also:
    // https://hpbn.co/optimizing-application-delivery/#eliminate-domain-sharding
    // https://daniel.haxx.se/blog/2016/08/18/http2-connection-coalescing/

    // 1. This connection must be HTTP/2.
    if (http2Connection == null) return false;

    // 2. The routes must share an IP address. This requires us to have a DNS address for both
    // hosts, which only happens after route planning. We can't coalesce connections that use a
    // proxy, since proxies don't tell us the origin server's IP address.
    if (route == null) return false;
    if (route.proxy().type() != Proxy.Type.DIRECT) return false;
    if (this.route.proxy().type() != Proxy.Type.DIRECT) return false;
    if (!this.route.socketAddress().equals(route.socketAddress())) return false;

    // 3. This connection's server certificate's must cover the new host.
    if (route.address().hostnameVerifier() != OkHostnameVerifier.INSTANCE) return false;
    if (!supportsUrl(address.url())) return false;

    // 4. Certificate pinning must match the host.
    try {
      address.certificatePinner().check(address.url().host(), handshake().peerCertificates());
    } catch (SSLPeerUnverifiedException e) {
      return false;
    }

    return true; // The caller's address can be carried by this connection.
  }
```

**Comment by yschimke** [comment]
OkHttp 3.x is not supported.

https://github.com/square/okhttp/blob/okhttp_3.14.x/okhttp/src/main/java/okhttp3/internal/connection/RealConnection.java

Newer versions of OkHttp support connection coalescing, so you should update to 4.11.

**Comment by daqiang5566** [comment]
> OkHttp 3.x is not supported.
> 
> https://github.com/square/okhttp/blob/okhttp_3.14.x/okhttp/src/main/java/okhttp3/internal/connection/RealConnection.java
> 
> Newer versions of OkHttp support connection coalescing, so you should update to 4.11.

However, it only supports HTTP2.0 and does not support http1.1

![image](https://github.com/square/okhttp/assets/15732800/8f3758c2-0ad4-432d-9888-ca6b070af07a)

**Comment by yschimke** [comment]
Do you know what the browsers do?

**Comment by daqiang5566** [comment]
> Do you know what the browsers do?

I don't quite understand what you mean? Please provide a detailed explanation。

**Comment by yschimke** [comment]
What do browsers do when this is possible? Do they reuse connections? In which cases?

**Comment by daqiang5566** [comment]
It is common for multiple businesses in an app to share OKHTTP and have multiple domain names that may return the same IP.

**Comment by swankjesse** [comment]
I don’t think we should coalesce HTTP/1 connections unless we can confirm that browsers do this.
