### ISSUE TITLE
Requesting an ipv6 address and using a proxy results in a garbled response

### ISSUE THREAD

**Issue by jeesk** [square/okhttp#8019]
hi, I found a problem with okhttp using a proxy on android.  I'm using android to execute the curl command as a control group, curl has no problem accessing an ipv6 address using a proxy, but okhttp uses a socks proxy to access an ipv6 address with a garbled `Unexpected status line`.

I wrote an app to test the issue. 
But to test it, you need a socket server , if you don't have one, then I recommend github.com/things-go/go-socks5.
The program has two built in addresses, you can switch from ipv6 to ipv4 by clicking on the button at the top, the input box below the request address is the proxy addr, make sure to fill this in when testing okhttp to use a proxy to access the ipv6 address. In order to have a control group, I used the curl command in the program, which can also be tested on a computer, so that the control group can rule out a proxy problem. 

Also the two addresses above are ip in mainland China, it may be very slow. If it is slow, you can directly access your local ipv6 address, or an ipv6 address near your computer.

I uploaded the code to the repository https://github.com/jeesk/okhttp_request_ipv6_via_proxy

**Comment by yschimke** [comment]
@swankjesse do you remember the status of SOCKS5 on Android?

I think when we've looked at supporting this we've found JVM examples that work via a custom Socket factory https://github.com/square/okhttp/pull/7645/files

And I think early android only supported Socks v4.  https://github.com/square/okhttp/pull/4430/files

I'll take a look, but if it's blocking you, for the moment, I'd suggest handling in a custom socket factory, which I think should work?

**Comment by swankjesse** [comment]
OkHttp doesn’t do Socks internally. If you need it, you’ll need to set it up via a custom socket factory. That linked PR has a great sample.
