### ISSUE TITLE
Use case for cache as an interface

### ISSUE THREAD

**Issue by timrobertson100** [square/okhttp#8020]
Hi folks

I see the request for Cache to be an interface has been discussed before and closed since there is no real use case.

We make use of web service calls from an Apache Spark distributed processing environment and front it with a cache that's backed by HBase. As we're likely to tidy this area up in our own code, it would be nice if we could do an HBaseCache implementation to pass in. Before we go down the route of Interceptors, is there any interest in Cache becoming an interface, please?

Thank you

**Comment by yschimke** [comment]
Would passing in a different okio FileSystem work, or is that too granular?  That is already supported.

https://github.com/square/okhttp/blob/f4ff4f4a8dce5f44596115f9564280e41d845f98/okhttp/src/jvmMain/kotlin/okhttp3/Cache.kt#L152

**Comment by timrobertson100** [comment]
Thank you very much @yschimke 

This is more akin to an object store than an FS, so things like symlinks, creating directories, recursive listing etc wouldn't map over. Ideal to me would be a cache interface that had only the minimal init, get, put, delete (or so), with the implementor choosing how that was stored. Thank you for looking.

**Comment by yschimke** [comment]
You wouldn't need to implement those.  I think this is our POR for different Cache storage.

See https://github.com/square/okhttp/issues/2903#issuecomment-1398281781

As an example https://gist.github.com/mandrachek/5da100d508eebf57a94de81448dcadaa
