### ISSUE TITLE
okhttp cancel or timeout, the request will work for a period of time

### ISSUE THREAD

**Issue by DaiyiLL** [square/okhttp#8021]
Good bug reports include a failing test! Writing a test helps you to isolate and describe the problem, and it helps us to fix it fast. Bug reports without a failing test or reproduction steps are likely to be closed.

Here’s an example test to get you started.
https://gist.github.com/swankjesse/981fcae102f513eb13ed

I test version 3.12.0 and 4.11.0
set Charles throttle settings upload speed 50kbps, set calltimeout(10s). my request boday is 100KB(image data), will send data while timeout, and server will excute tasks. so what way to solve it? I hope that stop send data while timeout.

**Comment by yschimke** [comment]
This isn't really in a form I can do much with.  I suggest asking on a site like stackoverflow.  Without a reproduction, it's not clear what I'm attempting to fix.

Sorry.
