### ISSUE TITLE
Changing proxy dynamically

### ISSUE THREAD

**Issue by MohammadFakhraee** [square/okhttp#8023]
I'm using **OkHttpClient** with **Retrofit** which both are injected using **Dagger Hilt**. But I need an option to change proxy (which is currently set to OkHttpClient using '.proxy()') dynamically.

The situation that I am trying to implement is as so: I wanna request to an end point which returns a list of host-port pairs. I wanna set one or all of the configs in **OkHttpClient** to use these proxies if there is any.

I even created a stackoverflow question [here](https://stackoverflow.com/questions/77111640/how-to-change-okhttpclient-proxy-injected-to-retrofit-using-hilt) but no one has responded. I also saw [this question](https://stackoverflow.com/questions/74372505/setup-okhttp-proxy-at-runtime-when-using-hilt) in stackoverflow but no one responded to that either. Any suggestion to implement this work?

**Comment by yschimke** [comment]
Why not implement ProxySelector and put your logic in there?

Closing as I think this is already supported API.
