### ISSUE TITLE
Request add body throws EOFException

### ISSUE THREAD

**Issue by Zhouxuefei** [square/okhttp#803]
When the class com.squareup.okhttp.Call has been added.
when I called method call.execute(); 

the example throws a java.io.EOFException

at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:154)

String json = bowlingJson();
Request.Body body = Request.Body.create(MediaType.parse("application/json"), json);
Request request = new Request.Builder()
                .url("https://xxxxxxxxx/api/1/user/phone_test")
                .method("POST",body)
                .build();

Call call = client.newCall(request);
Response response = call.execute();

But the earlier version of the example,  Response response = client.execute(request);  
It works.

In the latest version, the method " execute(Request request)" have goon.

**Comment by dbaroncelli** [comment]
I suggest to test manually the URL you are calling.
I had the same problem, but eventually I realized it was caused by a wrong response by the webservices, for some particular calling parameters.

**Comment by zcs417327734** [comment]
This issue occurred daily,kill it
