### ISSUE TITLE
setAuthenticator missing in OkHttpClient.Builder

### ISSUE THREAD

**Issue by mirzah** [square/okhttp#8030]
I am tying to do Basic Auth, and according to web, I need to do:

```
OkHttpClient.Builder client = new OkHttpClient.Builder();
client.setAuthenticator(new Authenticator() {
 ....
```

But, OkHttpClient.Builder class have not setAuthenticator method (4.11.0, latest version currently).
It does have setAuthenticator$okhttp function, but using this prompts editor warning in Android Studio: "Usage of Kotlin internal declaration from different module"

Should I just ignore this warrning and use this function?

**Comment by yschimke** [comment]
See recipe here https://square.github.io/okhttp/recipes/#handling-authentication-kt-java

```
  private val client = OkHttpClient.Builder()
      .authenticator(object : Authenticator {
```
