### ISSUE TITLE
Lack of possibility to change charset for post requests

### ISSUE THREAD

**Issue by sdml0** [square/okhttp#8033]
I  need to post form data with some rare charset, and...
instead of addFormDataPart(name, value@rareCharset), I figued out from sources that it can be
apply { addPart(MultipartBody.Part.createFormData(name, null, value@RareCharset.toRequestBody("text/plain; charset=rareCharset".toMediaType()))) }.
BUT there is nothig I can use instead of addFormDataPart(name, filename@RareCharset, data).
There is hardcoded "utf-8" as I can see.

**Comment by swankjesse** [comment]
Would you consider copy-pasting the FormBody classes into your project?

I’m reluctant to do anything for non-UTF-8 charsets in 2023. I’d much prefer you push back on whatever COBOL server you’re talking to and ask for a fix on that end.

https://utf8everywhere.org/

No action to take on this in OkHttp.
