### ISSUE TITLE
Fatal Exception: java.lang.VerifyError

### ISSUE THREAD

**Issue by liujun724536** [square/okhttp#8044]
Verifier rejected class okhttp3.internal.http2.Http2Writer: void okhttp3.internal.http2.Http2Writer.connectionPreface(): [0xFFFFFFFF] register index out of range (32 >= 4) (declaration of 'okhttp3.internal.http2.Http2Writer' appears in base.apk!classes6.dex)

okhttp3.internal.http2.Http2Connection.<init> (Http2Connection.kt:141)
okhttp3.internal.http2.Http2Connection$Builder.build (Http2Connection.kt:601)
okhttp3.internal.connection.RealConnection.startHttp2 (RealConnection.kt:355)
okhttp3.internal.connection.RealConnection.establishProtocol (RealConnection.kt:341)
okhttp3.internal.connection.RealConnection.connect (RealConnection.kt:209)
okhttp3.internal.connection.ExchangeFinder.findConnection (ExchangeFinder.kt:226)
okhttp3.internal.connection.ExchangeFinder.findHealthyConnection (ExchangeFinder.kt:106)
okhttp3.internal.connection.ExchangeFinder.find (ExchangeFinder.kt:74)
okhttp3.internal.connection.RealCall.initExchange$okhttp (RealCall.kt:255)
okhttp3.internal.connection.ConnectInterceptor.intercept (ConnectInterceptor.kt:32)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.kt:109)
okhttp3.internal.cache.CacheInterceptor.intercept (CacheInterceptor.kt:95)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.kt:109)
okhttp3.internal.http.BridgeInterceptor.intercept (BridgeInterceptor.kt:83)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.kt:109)
okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept (RetryAndFollowUpInterceptor.kt:76)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.kt:109)
zendesk.android.internal.p.intercept (ZendeskLoggingInterceptor.kt:14)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.kt:109)
zendesk.okhttp.a.intercept (HeaderInterceptor.kt:35)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.kt:109)
okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp (RealCall.kt:201)
okhttp3.internal.connection.RealCall$AsyncCall.run (RealCall.kt:517)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1167)

java.lang.Thread.run (Thread.java:920)

**Comment by swankjesse** [comment]
Which version?

**Comment by ShubhamDambale** [comment]
@liujun724536 
Update OkHttp: Ensure that you are using the latest version of the OkHttp library. Newer versions often include bug fixes and improvements that may address issues like the one you're encountering.

implementation 'com.squareup.okhttp3:okhttp:<latest_version>'
