### ISSUE TITLE
Support WebTransport

### ISSUE THREAD

**Issue by bfelbo** [square/okhttp#8069]
We're currently using OkHttp with WebSockets for multiplayer gaming. We would love to use [WebTransport](https://developer.mozilla.org/en-US/docs/Web/API/WebTransport_API) instead as it offers a reliable channel that has better latency than WebSockets and doesn't suffer from [head-of-line blocking](https://en.wikipedia.org/wiki/Head-of-line_blocking) as it uses [UDP under the hood](https://github.com/w3c/webtransport/tree/main).

At the time of writing [WebTransport is supported for 73% users globally](https://caniuse.com/webtransport) and was recently released for Chrome on Android. Would you consider adding support for WebTransport in OkHttp?

**Comment by yschimke** [comment]
This is unlikely based on HTTP/3 requirement

> The WebTransport API provides a modern update to WebSockets, transmitting data between client and server using HTTP/3 Transport

See https://github.com/square/okhttp/issues/907 for discussion on HTTP/3.

Going to close as this would seem to make it infeasible.
