### ISSUE TITLE
com.squareup.okhttp3:okhttp:4.12.0 causes failure in Gradle 8.x

### ISSUE THREAD

**Issue by jimshowalter** [square/okhttp#8075]
When we tried to upgrade to 4.12.0, the build failed with:

`Execution failed for task ':bootJar'.

Could not resolve all files for configuration ':productionRuntimeClasspath'.
Could not find okio-jvm-3.6.0-sources.jar (com.squareup.okio:okio-jvm:3.6.0).
Searched in the following locations:
https://box.jfrog.io/box/signedthirdpartymaven/com/squareup/okio/okio-jvm/3.6.0/okio-jvm-3.6.0-sources.jar`

Downgrading to 4.11.0 is one workaround.

Keeping 4.12.0 but downgrading to Gradle 7.x is another workaround.

Originally reported in https://github.com/gradle/gradle/issues/26804.

**Comment by yschimke** [comment]
Is it valid for gradle to fail when it can't find sources? Not clear if there is anything for OkHttp to do here. 

Are you suggesting we got the dependency wrong?

Going to close, once gradle responds based on the repro you provide. I suggest opening a bug on okio if it's a bug there. But unclear. No action to take for OkHttp.
