### ISSUE TITLE
Infinite loop in MessageInflater for Binary message

### ISSUE THREAD

**Issue by Fischiii** [square/okhttp#8078]
When using Protobuf over Web Sockets we get an infinite loop in `MessageInflater`. This happens with current release and 5.0 alpha. We are using OKhttp on android.

We receive a short binary message:

![Screenshot 2023-10-26 at 15 33 56](https://github.com/square/okhttp/assets/4191475/407d0483-d59e-4c1b-bcbe-30395abef611)

Okhttp tries to inflate the message and does so successfully for the first 4 bytes (the actual payload):

![Screenshot 2023-10-26 at 15 36 15](https://github.com/square/okhttp/assets/4191475/16aa3777-aed6-4bba-b6ab-9c436f389949)

After this the inflater always returns 0 bytes inflated an as such the condition `inflater.bytesRead < totalBytesToRead` in `MessageInflater` always return true and we are stuck in an infinite loop. `inflater.bytesRead` is 6 and `totalBytesToRead` is 11.

![Screenshot 2023-10-26 at 15 41 05](https://github.com/square/okhttp/assets/4191475/e544bd6d-e5ee-4843-8b87-a4633ed98b8e)

The same message can be successfully inflated in other WebSocket frameworks such as pythons websockets or rxjs/webSocket in typscript.

We can 100% reproduce the issue on each message. So we can easily provide further information if needed.

**Comment by swankjesse** [comment]
Thanks for the detailed report. Can fix.
