### ISSUE TITLE
Update Cache docs to mention that it's not thread safe and should be a singleton

### ISSUE THREAD

**Issue by odbol** [square/okhttp#8083]
Quite a few people have been running into some concurrency issues with Cache (see https://github.com/square/okhttp/issues/8080, https://github.com/square/okhttp/issues/3938, https://github.com/square/okhttp/issues/6280, https://github.com/voghDev/PdfViewPager/issues/175, etc).

Most likely for all of them they are either creating more than one Cache object on the same directory/file, or accessing it from different threads. But it's not clear from the docs that this would cause a problem.

The doc comment for Cache should be updated to mention that it is not thread-safe and that only one Cache object per directory should be created (i.e. make it a singleton).

**Comment by yschimke** [comment]
As well as some docs, we should consider something like checking a static set of locks. ExoPlayer SimpleCache does this.

https://github.com/androidx/media/blob/3f366109b7e5cbf7b7e5b46e8b923e167e9ae893/libraries/datasource/src/main/java/androidx/media3/datasource/cache/SimpleCache.java#L83C38-L83C57

**Comment by yschimke** [comment]
@odbol I don't think it's lack of thread safety, I think it's not safe with multiple cache instances on the same directory.
