### ISSUE TITLE
Bug in PATCH method

### ISSUE THREAD

**Issue by drjerry** [square/okhttp#8091]
I'm using OkHttp3 in a Java application to interact with the [LaunchDarkly REST API](https://apidocs.launchdarkly.com/tag/Feature-flags#operation/patchFeatureFlag). It's an authenticated authenticated endpoint, but I can give sufficient details to describe the problem
```
String jsonBody = "{"
    + "\"environmentKey\": \"staging\","
    + "\"instructions\": [{"
    + "  \"kind\": \"updateFallthroughVariationOrRollout\","
    + "  \"variationId\":\"00528e0e-f10a-43b7-ade9-000000000000\""
    + "  }]"
    + "}";
RequestBody body = RequestBody.create(jsonBody, MediaType.parse("application/json"));

Request request = new Request.Builder()
    .addHeader("Authorization", "<REDACTED>")
    .addHeader("Content-Type", "application/json; domain-model=launchdarkly.semanticpatch")
    .url("https://app.launchdarkly.com/api/v2/flags/<ORG>/<APPLICATION-FLAG-KEY>")
    .patch(body)
    .build();

try (Response response = okHttpClient.newCall(request).execute()) {
  logger.info("%s", response);
} catch (IOException e) {
  logger.error("Could not connect");
}
```

**The logged response was a 400 error.** According to their [API documentation](https://apidocs.launchdarkly.com/#section/Overview/Errors) that indicates that the JSON is malformed. 

However I repeated the exact same request from the same host using cURL instead of OkHttp within the Java app:
```
curl -i -X PATCH \
  'https://app.launchdarkly.com/api/v2/flags/<ORG>/<APPLICATION-FLAG-KEY>' \
  -H 'Authorization: <REDACTED>' \
  -H 'Content-Type: application/json; domain-model=launchdarkly.semanticpatch' \
  -d '{
        "environmentKey": "staging",
        "instructions": [{
          "kind": "updateFallthroughVariationOrRollout",
          "variationId":"00528e0e-f10a-43b7-ade9-000000000000"
        }]
      }'

HTTP/2 200 
content-type: application/json
etc
```

This indicates that the problem lies in the OkHttp3 client.

**Comment by yschimke** [comment]
OkHttp 3 is no longer supported. Update to 4.12.

But I suspect that the content type format may not be supported.

You can try reproducing against http://httpbin.org

I'll try to confirm and if so provide a workaround.

**Comment by yschimke** [comment]
The content type is working fine.  It turned out to be your patch body media type, overriding the header.  Which is expected.

Change your code to

```

RequestBody body = RequestBody.create(jsonBody, MediaType.parse("application/json; domain-model=launchdarkly.semanticpatch"));

Request request = new Request.Builder()
    .addHeader("Authorization", "<REDACTED>")
    .url("https://app.launchdarkly.com/api/v2/flags/<ORG>/<APPLICATION-FLAG-KEY>")
```

**Comment by drjerry** [comment]
Thank you @yschimke. I was able to confirm that this worked.
