### ISSUE TITLE
java.lang.NoSuchFieldError: Companion at com.squareup.okhttp3.internal.Util

### ISSUE THREAD

**Issue by Janani1112** [square/okhttp#8094]
I tried using 3.x and 4.x versions of okhttp, however I am ended up with below exception

Exception in thread "main" java.lang.NoSuchFieldError: Companion
    at okhttp3.internal.Util.<clinit>(Util.kt:72)
    at okhttp3.internal.concurrent.TaskRunner.<clinit>(TaskRunner.kt:309)
    at okhttp3.ConnectionPool.<init>(ConnectionPool.kt:41)
    at okhttp3.ConnectionPool.<init>(ConnectionPool.kt:47)
    at okhttp3.OkHttpClient$Builder.<init>(OkHttpClient.kt:471)
I also tried adding okio dependency explicitly, but that did not resolve the error.

Can someone please help me on this.

We use an internal dependency which consume okhttp 4.9.0. When no okhttp is not mentioned explicitly in pom.xml it is being transitively called by the internal dependency, but we still get the exception. When added explicitly with okio 2.8.0 still ended with expection.

I also tried okhttp 4.12 and okio 3.6.0, however no luck.

**Comment by yschimke** [comment]
You can't mix versions. If you have both jars on your class path it will fail unpredictably like this. OkHttp 3, 4 and 5 all share the same packages. 

Gradle will usually select the latest version you include. But to be sure you can bring in all OkHttp libraries in your top level project with version 4.12 and exclude any older versions with your build system.

**Comment by yschimke** [comment]
We can't really help with your project build errors, make a reproduction of the problem and share to stackoverflow
