### ISSUE TITLE
OkHttp MockWebServer throws java.net.SocketTimeoutException: timeout - exception

### ISSUE THREAD

**Issue by Iqra786** [square/okhttp#8095]
I'm using OkHttp's MockWebServer for API mocking in my Android instrumentation tests. It's been effective so far, but I've encountered an issue where making a second call to the same endpoint within the same test case consistently results in a java.net.SocketTimeoutException: timeout error.

In more detail, I need to load a fragment with the web mock server's response. This part is working as expected. However, in the second part of my test, I aim to verify that the displayed data matches the API response. To do this, I need to make a second call to the repository.

I've prepared a simplified test case to illustrate the problem.

version
"com.squareup.okhttp3:mockwebserver:5.0.0-alpha.11"

```
@Before
    fun setUp() {
        hiltRule.inject()
        mockWebServer.start()
        val response = SharedUtil.searchAPIMockWebServerResponseWith200()
        mockWebServer.enqueue(response)
    }

@Test
    fun testCalls() {
// using run blocking instead of runTest for this example       
 runBlocking {
            val firstFlow = productRepo.getMatchedProducts("Search")
            val secondFlow = productRepo.getMatchedProducts("Search")

            // This call works fine
            firstFlow.collectLatest { outcome ->
                if (outcome is Outcome.Success) {
                    println("output one $outcome")
                }


            delay(1000) // to allow complete the first request 
// 2nd call                
// this call always throw exception java.net.SocketTimeoutException: timeout
                secondFlow.collectLatest { outcome ->
                    if (outcome is Outcome.Success) {
                        println("output two $outcome ")
                    }
                }

            }
        }
    }

 fun tearDown() {
        mockWebServer.shutdown()
    }
```

2nd call throw exception.
java.net.SocketTimeoutException: timeout. (Image is attached)

![image](https://github.com/square/okhttp/assets/2422839/18e0e3e9-2071-4931-a1d0-8a4c984d24f6)

**Comment by yschimke** [comment]
You need to enqueue a response for every call in sequential order.
