### ISSUE TITLE
okhttp for server

### ISSUE THREAD

**Issue by pandans** [square/okhttp#8098]
in server ，okhttp dispacther with max 64 request and 5 per/host， this may limit biz。 such if request host down 5min，this may have a large lot of request store in readycalls，then new request must exec after old req。 i try custom the dispacther but this class is final，so okhttp can open it？

**Comment by yschimke** [comment]
Dispatcher fields are mutable 

See https://github.com/square/okhttp/blob/30780c879bd0d28b49f264fac2fe05da85aef3ad/okhttp/src/jvmMain/kotlin/okhttp3/Dispatcher.kt#L35

```
  @get:Synchronized var maxRequests = 64
    set(maxRequests) {
      require(maxRequests >= 1) { "max < 1: $maxRequests" }
      synchronized(this) {
        field = maxRequests
      }
      promoteAndExecute()
    }
```

**Comment by pandans** [comment]
> Dispatcher fields are mutable 
> 
> 
> 
> See https://github.com/square/okhttp/blob/30780c879bd0d28b49f264fac2fe05da85aef3ad/okhttp/src/jvmMain/kotlin/okhttp3/Dispatcher.kt#L46
> 
> 
> 
> ```
> 
>   @get:Synchronized var maxRequests = 64
> 
>     set(maxRequests) {
> 
>       require(maxRequests >= 1) { "max < 1: $maxRequests" }
> 
>       synchronized(this) {
> 
>         field = maxRequests
> 
>       }
> 
>       promoteAndExecute()
> 
>     }
> 
> ```

no，in server case，larger request  is first but the new request will first deal may better。 old request the front my has cancel，the retry requset come，but in fifo mode the may not deal and in queque forever
