### ISSUE TITLE
okhttp for server case

### ISSUE THREAD

**Issue by pandans** [square/okhttp#8104]
#8098 topic
Dispatcher fields are mutable

See https://github.com/square/okhttp/blob/30780c879bd0d28b49f264fac2fe05da85aef3ad/okhttp/src/jvmMain/kotlin/okhttp3/Dispatcher.kt#L46

  @get:Synchronized var maxRequests = 64

    set(maxRequests) {

      require(maxRequests >= 1) { "max < 1: $maxRequests" }

      synchronized(this) {

        field = maxRequests

      }

      promoteAndExecute()

    }

no，in server case，larger request is first but the new request will first deal may better。 old request the front my has cancel，the retry requset come，but in fifo mode the may not deal and in queque forever

**Comment by yschimke** [comment]
Can you make a reproduction of this issue, to make sure we are discussing the right problem?

**Comment by madd-44** [comment]
Sorry guys

**Comment by pandans** [comment]
> Can you make a reproduction of this issue, to make sure we are discussing the right problem?

in server case，larger request is first but the new request will first deal may better。 old request in the front action may has cancel，but the new or retry requset come，in fifo mode ，new request may not deal and in queque forever。 in any case can add new request deal first？ just open final dispather or add param how dispather peek the readcall task。

**Comment by swankjesse** [comment]
Unclear what action to take here.
