### ISSUE TITLE
okhttp Failed to connect to/10.0.0.172:80?🙉

### ISSUE THREAD

**Issue by Eason-shu** [square/okhttp#8106]
Problem description: Android okhttp3 is unable to connect to the server on the mobile dedicated network card. The error message is as follows

Java. net. ConnectiException: Failed to connect to/10.0.0.172:80

After checking the APN of the mobile manufacturer, this address is 10.0.0.172:80

It's interesting, but if I switch to a different request framework, it can connect to the network, and the same code can be connected in a public network environment
In the same testing environment, Volley can go through

![image-20231115162614654](https://github.com/square/okhttp/assets/71616046/f593db4b-1985-44c4-9b7c-d19eff0f802e)

![微信图片_20231115144639](https://github.com/square/okhttp/assets/71616046/0f9c8009-6cdd-45e2-b7b0-71360e8d95d2)

**Comment by yschimke** [comment]
There isn't much to go on here. We probably need one of these to go forward

1) a reproduction with instructions on a similar device

2) add more logging, or custom socket factory and any information if you connect to a socket yourself.

The only things I can think is the timeouts OkHttp applies are stricter than volley?
