### ISSUE TITLE
Fails to retry on 503 error

### ISSUE THREAD

**Issue by gauribhoite** [square/okhttp#8107]
Good bug reports include a failing test! Writing a test helps you to isolate and describe the problem, and it helps us to fix it fast. Bug reports without a failing test or reproduction steps are likely to be closed.

Here’s an example test to get you started.
https://gist.github.com/swankjesse/981fcae102f513eb13ed
Here's a failing test

```
@Test
  void postRetryConnection() throws URISyntaxException, InterruptedException {
    MockResponse response = new MockResponse().setResponseCode(503);
    mockWebServer.enqueue(response);
    mockWebServer.enqueue(response);
    mockWebServer.enqueue(response);
    Request req =
        new Request.Builder()
            .url(mockServerBaseUrl)
            .addHeader("Retry-After", "5")
            .build();
    Assertions.assertTrue(okHttpClient.retryOnConnectionFailure());
    try {
      okHttpClient.newCall(req).execute();
    } catch (IOException e) {
      // Connection is expected to fail due to mock response
    }
    assertEquals(2, mockWebServer.getRequestCount());
  }
```

**Comment by yschimke** [comment]
This is expected. You will need to perform retries in your app, or with an Interceptor.

**Comment by JakeWharton** [comment]
Just remember not to DoS your server! A 500 means it's having problems.

**Comment by gauribhoite** [comment]
I understood that in the `RetryAndFollowUpInterceptor` class the 503 is meant to be retried at least once. So the test above was to check if it retried with 503 error. Please help me understand if I'm missing anything?
```
      HTTP_UNAVAILABLE -> {
        val priorResponse = userResponse.priorResponse
        if (priorResponse != null && priorResponse.code == HTTP_UNAVAILABLE) {
          // We attempted to retry and got another timeout. Give up.
          return null
        }

        if (retryAfter(userResponse, Integer.MAX_VALUE) == 0) {
          // specifically received an instruction to retry without delay
          return userResponse.request
        }

        return null
      }
```

**Comment by yschimke** [comment]
Damn, you are right.  Sorry, bad memory on my part.

**Comment by yschimke** [comment]
OK, so two issues.

1) Your test is setting `Retry-After` on the Request, not on the MockResponse.
2) You are using a value of 5, which follows my earlier response. You will need to implement this yourself. Only 0 is handled immediately.

**Comment by gauribhoite** [comment]
Thanks! That makes sense now 👍
