### ISSUE TITLE
WebSocket Send message after X time of inactivity

### ISSUE THREAD

**Issue by WoWP120** [square/okhttp#8112]
When connected to a websocket server
alot of the servers using a mechanism on the client that after X second of inactivity the client sends a message. so server keeps the connection alive

for example in firebase rtdb it is implemented that after 45 seconds of inactivity (no message received) the client sends "0"

*did tried to use the pingInterval but it doesnt send a message unless it received a message as far as i tried it
*tried to use a timer/scheduleAtFixedRate implementing it myself, but it always failed for some reason, maybe its because android

**Comment by yschimke** [comment]
I'd suggest implementing a BasePingingWebSocketListener that implements this.  You have all the right hooks.

The inbuilt ping is designed for this, so I don't think adding a layer of pings at the higher layer is the right thing to do.

OkHttp can't know that sending "0" is a safe ping.
