### ISSUE TITLE
https://github.com/square/okhttp/blob/master/mockwebserver/README.md#dispatcher

### ISSUE THREAD

**Issue by julian-goettingen** [square/okhttp#8130]
The Readme describes how to use Dispatcher with MockWebServer:
https://github.com/square/okhttp/blob/master/mockwebserver/README.md#dispatcher

This way of doing it is not possible because the Dispatcher-class is final.
Is this a bug introduced by the Kotlin-rewrite or is there a new intended way of doing this?

(or did I mess up something else and have some other object called `Dispatcher`?)
I am importing the dispatcher as:
```import okhttp3.Dispatcher;```
and include your project in the build.gradle as:
```testImplementation 'com.squareup.okhttp3:mockwebserver:4.10.0'```

**Comment by julian-goettingen** [comment]
(labeling it as `bug` but it may also be just a documentation-issue)

**Comment by julian-goettingen** [comment]
upgrading to 'com.squareup.okhttp3:mockwebserver:4.12.0' or 'com.squareup.okhttp3:mockwebserver:5.0.0-alpha.11' did not solve the issue.

**Comment by victorherraiz** [comment]
you have to use `import okhttp3.mockwebserver.Dispatcher`

**Comment by julian-goettingen** [comment]
Thank you, I did just have the wrong import and didn't consider there might be another one.
