### ISSUE TITLE
Kotlin older versions support

### ISSUE THREAD

**Issue by LikeTheSalad** [square/okhttp#8139]
Hi!

Some people seem to struggle with upgrading Kotlin in their projects, as shown [in this issue](https://github.com/open-telemetry/opentelemetry-java/issues/6026), and, because of compatibility issues, if a dependency uses a higher version of Kotlin than the one set in the host project, the Kotlin plugin will complain and refuse to compile :/ which is why we recently decided to provide older language version compatibility support [here](https://github.com/open-telemetry/opentelemetry-java/pull/5910).

So I was wondering if using the `languageVersion`/`apiVersion` config options to provide support for older versions of Kotlin has or could be considered for this project?

**Comment by yschimke** [comment]
@swankjesse I've been following okio versions mainly, do we have a clear strategy for this?

**Comment by swankjesse** [comment]
In general, the latest OkHttp will use the latest Okio and the latest Kotlin dependencies. All three libraries follow very strict compatibility rules.

It is safe to compile against OkHttp version X and run against version Y as long as Y > X, even across major version changes.

If for whatever reason you must run with on an old version of Kotlin, find an old version of OkHttp that uses that old version of Kotlin. Typically this is necessary for Gradle plugins that run in old versions of Gradle.

**Comment by LikeTheSalad** [comment]
I see, thank you. One important, recurring concern about using older versions is security. Since you're suggesting using older versions of OkHttp, is it safe to say that those older versions get security updates too? @swankjesse

**Comment by yschimke** [comment]
No. Only 4.x and 5 alpha get security fixes
