### ISSUE TITLE
Replace dispatcher's default executorService with VirtualThreadPerTaskExecutor

### ISSUE THREAD

**Issue by bringyou** [square/okhttp#8167]
We can find that the default executorService of `Dispatcher` is configured as below:
```kotlin
  private var executorServiceOrNull: ExecutorService? = null

  @get:Synchronized
  @get:JvmName("executorService") val executorService: ExecutorService
    get() {
      if (executorServiceOrNull == null) {
        executorServiceOrNull = ThreadPoolExecutor(0, Int.MAX_VALUE, 60, TimeUnit.SECONDS,
            SynchronousQueue(), threadFactory("$okHttpName Dispatcher", false))
      }
      return executorServiceOrNull!!
    }
```
Is there any possible to replace it with `Executors.newVirtualThreadPerTaskExecutor` when running on JVM 21 or later?
The original implement doesn't obtain a buffered-queue, and will create new threads when current threads are busy.
IMO, this strategy is very suitable for virtualThreadPerTaskExecutor.

**Comment by swankjesse** [comment]
Yep, you can configure it to use virtual threads, and that configuration is supported.

**Comment by yschimke** [comment]
Here is an example

https://github.com/square/okhttp/blob/e09a018ebf8dfca07e53d927bdd6d1f563c75e1a/okhttp/src/test/java/okhttp3/LoomTest.kt#L30

It uses reflection because we can't assume loom to compile against.

**Comment by bringyou** [comment]
@swankjesse Thanks for your reply, I knew we can change it manually but if it is possible to make it as ** the default **.
Because the main stream of the codebase seems to [be requiring 21](https://github.com/square/okhttp/commit/464010a497fd8567b98cc64d7e1908ce02b5dc82).

**Comment by bringyou** [comment]
> Here is an example
> 
> https://github.com/square/okhttp/blob/e09a018ebf8dfca07e53d927bdd6d1f563c75e1a/okhttp/src/test/java/okhttp3/LoomTest.kt#L30
> 
> It uses reflection because we can't assume loom to compile against.

And we can use `PlatformVersion.majorVersion >= 21` to avoid using reflection

**Comment by yschimke** [comment]
That might work. Although PlatformVersion is a test only class, so we'd need a copy.

Two concerns though

1) It's not clear that newVirtualThreadPerTaskExecutor is the right default from JDK 21+. Is there some flag to detect whether Loom is desired by the app?
2) The precedent seems to be to allow apps to configure this, not to make it the default.

See https://github.com/reactor/reactor-core/issues/3084 and https://github.com/jetty/jetty.project/blob/1fb3f313ceee836469fbd1e4e3f67cec10620a9d/documentation/jetty-documentation/src/main/asciidoc/programming-guide/arch-threads.adoc#virtual-threads

**Comment by yschimke** [comment]
```
e: file:///home/runner/work/okhttp/okhttp/okhttp/src/main/kotlin/okhttp3/Dispatcher.kt:23:39 Unresolved reference: newVirtualThreadPerTaskExecutor
```

**Comment by bringyou** [comment]
@yschimke Thanks for your reply

**Comment by yschimke** [comment]
I'm going to close the PR, once it's passing. Even if it's possible with Multi-Release, I am not clear it's better in all cases for apps not expecting loom.
