### ISSUE TITLE
Constructor Injection does not work with mockwebserver3-junit5

### ISSUE THREAD

**Issue by snv** [square/okhttp#8171]
While the [readme](https://github.com/square/okhttp/blob/master/mockwebserver-junit5/README.md) claims that constructor injection should work, and offers an example, this in fact does not work (and is not covered by any test [in the project itself](https://github.com/square/okhttp/tree/master/mockwebserver-junit5/src/test/java/mockwebserver3/junit5/internal)).

Following sample-test
```java
import mockwebserver3.MockWebServer;
import mockwebserver3.junit5.internal.MockWebServerExtension;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;

@ExtendWith(MockWebServerExtension.class)
public class MockWebServerInjectionTest {
  private final MockWebServer server;

  MockWebServerInjectionTest(MockWebServer server) {
    this.server = server;
  }

  @Test
  void server_is_set(){
    assert server != null;
  }
}
```
with `com.squareup.okhttp3:mockwebserver3-junit5:5.0.0-alpha.12`
and `org.junit.jupiter:junit-jupiter:5.9.0`
results in
`org.junit.jupiter.api.extension.ParameterResolutionException: No ParameterResolver registered for parameter [mockwebserver3.MockWebServer arg0] in constructor [...MockWebServerInjectionTest(mockwebserver3.MockWebServer)].`

I also tried to use the annotation `@MockWebServerInstance` for field injection into the test class without success.

I assume the `mockwebserver3.junit5.internal.MockWebServerExtension` is a bit too restrictive in its selection of injection-points.

For context:
I can not simply inject into the test-method itself, because i need to use the mockwebserver-instance inside a test-class-local producer-method for a CDI-Bean with [WeldJunit5](https://github.com/weld/weld-testing/tree/master/junit5)

**Comment by yschimke** [comment]
I'll update the docs.

The issue is the model of Junit 5 parameters is different for constructors (class) and test and lifecycle methods (class/test method).

It's simplest to only support the latter to avoid confusion of people using the API correctly, but getting weird results.

This log won't make sense, but just recording for my notes.

```
resource id  [engine:junit-jupiter]/[ExtensionLifecycleTest]
init 
resource id  [engine:junit-jupiter]/[ExtensionLifecycleTest]/[method:testClient2(mockwebserver3.MockWebServer)]
resource id  [engine:junit-jupiter]/[ExtensionLifecycleTest]/[method:testClient2(mockwebserver3.MockWebServer)]
setup 
resource id  [engine:junit-jupiter]/[ExtensionLifecycleTest]/[method:testClient2(mockwebserver3.MockWebServer)]
testClient2 
resource id  [engine:junit-jupiter]/[ExtensionLifecycleTest]/[method:testClient2(mockwebserver3.MockWebServer)]
tearDown 
resource id  [engine:junit-jupiter]/[ExtensionLifecycleTest]/[method:testClient2(mockwebserver3.MockWebServer)]

resource id  [engine:junit-jupiter]/[ExtensionLifecycleTest]
init 
resource id  [engine:junit-jupiter]/[ExtensionLifecycleTest]/[method:testClient(mockwebserver3.MockWebServer)]
resource id  [engine:junit-jupiter]/[ExtensionLifecycleTest]/[method:testClient(mockwebserver3.MockWebServer)]
setup 
resource id  [engine:junit-jupiter]/[ExtensionLifecycleTest]/[method:testClient(mockwebserver3.MockWebServer)]
testClient 
resource id  [engine:junit-jupiter]/[ExtensionLifecycleTest]/[method:testClient(mockwebserver3.MockWebServer)]
tearDown 
resource id  [engine:junit-jupiter]/[ExtensionLifecycleTest]/[method:testClient(mockwebserver3.MockWebServer)]
```

**Comment by yschimke** [comment]
Attempting a fix to make it just work with constructors also

https://github.com/square/okhttp/pull/8191

**Comment by yschimke** [comment]
I think this fix is wrong. 

As can be seen by https://github.com/junit-team/junit5/blob/84ac590dd9bdee656bfbfd45aa7afbdfd26a3478/documentation/src/test/java/example/TestInfoDemo.java#L24

Junit 5 deliberately passes in different values for Constructor and BeforeEach/AfterEach/Test methods.

So I'll update the approach, allowing both, but they won't share instances between a) constructors and b) test methods.
