### ISSUE TITLE
java.lang.VerifyError 

### ISSUE THREAD

**Issue by girllee** [square/okhttp#8187]
onFailed: canceled due to java.lang.VerifyError: Verifier rejected class
okhttp3.internal.http2.Http2:void
okhttp3.internal.http2.Http2.<clinit>() failed to verify: void
okhttp3.internal.http2.Http2.<clinit>(): [0x154] encountered data table in instruction stream (declaration of 'okhttp3.internal.http2.Http2' appears in base.apk!apkclasses9.dex)

My gradle dependencies:

implementation 'com.squareup.okhttp3:okhttp:4.10.0'

Please let me know what is the issue and how to resolve this?

**Comment by yschimke** [comment]
It's unlikely an issue for us.  Without a repro, we can't help.

Likely raise a bug against R8.  Here is a similar one https://issuetracker.google.com/issues/267463817
