### ISSUE TITLE
Will Okhttp maintain request factory for spring framework?

### ISSUE THREAD

**Issue by techwn** [square/okhttp#8188]
According to https://github.com/spring-projects/spring-boot/issues/36632, OkHttp is deprecated in Spring Framework since it use Kotlin. 
It will be remove in the next release of Spring, will OkHttp maintain this request factory?

**Comment by yschimke** [comment]
Interesting question, I think generally we'd expect integration projects like this to be hosted in the umbrella project like Spring. The integration API on their side likely changes much more frequently than OkHttpClient or Call.Factory.

I think @swankjesse will say no. And suggest it lives in a separate integration project spring-projects/spring-boot-okhttp or techwn/spring-okhttp. If it was in this project, it wouldn't make sense to release it at the same time as okhttp-core. So we would be bad owners of it.

If you do make a project, I'm happy to contribute it, given something like Apache 2 license.

But lets wait for input from others.

**Comment by swankjesse** [comment]
Seems like it’d be a great as a standalone project. We’ll link to it from here if you or another person builds it:
https://square.github.io/okhttp/works_with_okhttp/

**Comment by bsourabh1** [comment]
@swankjesse @yschimke  can you please take a look at [this](https://github.com/freefair/okhttp-spring-boot) project, if this can be added to the [Works with OkHttp](https://square.github.io/okhttp/works_with_okhttp/ ) 
cc: @larsgrefer
