### ISSUE TITLE
Not working with AGP 8.2.1

### ISSUE THREAD

**Issue by wishygupta** [square/okhttp#8203]
I recently upgraded the gradle to 8.2.1
And unable to compile the project with error

Failed to resolve: com.squareup.okhttp3:okhttp-bom:4.12.0
Failed to resolve: com.squareup.okhttp3:okhttp-urlconnection

**Comment by yschimke** [comment]
They both appear to be there

https://mvnrepository.com/artifact/com.squareup.okhttp3/okhttp-bom/4.12.0
https://mvnrepository.com/artifact/com.squareup.okhttp3/okhttp-urlconnection/4.12.0

Not sure we can help with a build issue you are facing, consider a site like stackoverflow.

If you really think it's a bug, please make a repro so we can investigate.

**Comment by lokeshbhattarai** [comment]
It was happening for me with 4.12.0 once I updated to AGP 8.2.2.  However, I replaced BOM with fully qualified dependency and it seems to work. 

Not sure if it helps but I use OKHTTP in my library project which is distributed via Maven and used in the sample app. The sample app doesn't have a direct dependency on OKHTTP.
