### ISSUE TITLE
Why there is no 4.11.0 release branch?

### ISSUE THREAD

**Issue by nienienienie** [square/okhttp#8219]
I see that there are branches like https://github.com/square/okhttp/tree/okhttp_4.10.x.

But there is no 4.11.x branch like https://github.com/square/okhttp/tree/okhttp_4.11.x.

I'm using 4.11.0 and I have to check sth exactly in that version, but I don't know which branch to search.

So far I've found only this https://github.com/square/okhttp/actions/runs/4775548800 that says "Prepare for release 4.11.0" so it seems that branch mentioned there is good starting point https://github.com/square/okhttp/tree/jwilson.0422.release_build_.

**Comment by JakeWharton** [comment]
It was probably created from the 4.10 branch. Don't rely on branches, rely on tags: https://github.com/square/okhttp/tags

**Comment by yschimke** [comment]
This branch [okhttp_4x](https://github.com/square/okhttp/tree/okhttp_4x) is now used for all further 4.x releases.

And tags like [parent-4.11.0](https://github.com/square/okhttp/tree/parent-4.11.0) exist for the release.

**Comment by nienienienie** [comment]
thanks a lot guys!
