### ISSUE TITLE
Crash unable to load publicsuffixes.gz resource from the classpath.

### ISSUE THREAD

**Issue by ShirobokovNE** [square/okhttp#8220]
We see a crash in the logs crashlytics:
```
Fatal Exception: java.lang.IllegalStateException 
Unable to load publicsuffixes.gz resource from the classpath.
okhttp3.internal.publicsuffix.PublicSuffixDatabase.findMatchingRule (PublicSuffixDatabase.kt:110)
okhttp3.internal.publicsuffix.PublicSuffixDatabase.getEffectiveTldPlusOne (PublicSuffixDatabase.kt:72)
okhttp3.Cookie$Companion.parse$okhttp (Cookie.java:469)
okhttp3.Cookie$Companion.parse (Cookie.java:368)
okhttp3.Cookie$Companion.parseAll (Cookie.java:601)
okhttp3.internal.http.HttpHeaders.receiveHeaders (HttpHeaders.kt:204)
okhttp3.internal.http.BridgeInterceptor.intercept (BridgeInterceptor.kt:85)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.kt:109)
okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept (RetryAndFollowUpInterceptor.kt:76)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.kt:109)
com.myapp.auth.AuthInterceptor$intercept$response$1.invokeSuspend (AuthInterceptor.kt:45)
```
We use okhttp version 4.10.0
Crash occurs more often on Xiaomi devices with api level 33. In crashlytics statistics 15k in 90 days, that’s a lot. 
We assume that the initialization of the publicSuffixListBytes field of the PublicSuffixDatabase class in one thread is not visible in others.
The following code in Application class solves the problem, but we would like without it

```
CoroutineScope(Dispatchers.IO + Job()).launch {
     try {
           PublicSuffixDatabase.get().getEffectiveTldPlusOne("google.com")
     } catch (exception: Exception) {
     }
 }
```

**Comment by yschimke** [comment]
I think our proguard rules improved in 4.11.0

https://square.github.io/okhttp/changelogs/changelog_4x/#version-4110

Now https://github.com/square/okhttp/blob/okhttp_4x/okhttp/src/main/resources/META-INF/proguard/okhttp3.pro

Please reopen if still happening with 4.12.0.

**Comment by hpdx** [comment]
We use okhttp version 4.12.0 and also reported this issue

 Fatal Exception: java.lang.IllegalStateException: Unable to load publicsuffixes.gz resource from the classpath.
       at okhttp3.internal.publicsuffix.PublicSuffixDatabase.findMatchingRule(PublicSuffixDatabase.kt:110)
       at okhttp3.internal.publicsuffix.PublicSuffixDatabase.getEffectiveTldPlusOne(PublicSuffixDatabase.kt:72)
