### ISSUE TITLE
Certificate Pinning disable opportunity.

### ISSUE THREAD

**Issue by userinno** [square/okhttp#8222]
We have a lot of instances of our backend hosted with different DNS names like instance1.example.com, instance2.example.com, ..., instance99.example.com Certificate Pinning feature is used in our project but depending on the backend instance we need to enable/disable the feature. 
So most of the instances are enabled with the feature while some of them not (in fact, usually the only one). 

Q1. How is it possible to disable Certificate Pinning in the case and do not check certificate by http client for example for instance1.example.com while pattern is *.example.com? Moreover, User can switch the exact backend instance to be used directly in UI application in runtime. The single http client instance is used during application lifetime and there are some reasons not to re-create it. Once the backend instance is changed the further REST API requests will use the new addresses. Before: instance1.example.com/api/v1/users, after: instance2.example.com/api/v2

Q2. Is it possible to change the backend instance to be ignored by Certificate Pinning feature in runtime? For example, from instance1.example.com to instance2.example.com

**Comment by swankjesse** [comment]
I recommend creating a new OkHttpClient instance that uses a different CertificatePinner based on your own application logic.

You can use OkHttpClient.newBuilder() to share the same configuration.
