### ISSUE TITLE
API suggestion: `buildMockResponse { }`

### ISSUE THREAD

**Issue by yogurtearl** [square/okhttp#8228]
Kotlin stdlib has a pattern for builders: 

`buildList { }`, `buildSet { }`, etc. 

OkHttp could follow that pattern by providing `buildWhevs { }` style functions like this: 

```kotlin
fun buildMockResponse(block: MockResponse.Builder.() -> Unit) = MockResponse.Builder().apply { block() }.build()
```

**Comment by JakeWharton** [comment]
I would say this pattern is for scoping mutable collections to a block and returning the read-only result. MockResponse doesn't fit that. Is it used for regular types anywhere? I can't think of any.

**Comment by yschimke** [comment]
FWIW I think @swankjesse had a physical reaction when I suggested something similar for `buildRequest {}` and went for a simpler constructor in https://github.com/square/okhttp/pull/7208.

Going to close so we don't mix API styles
