### ISSUE TITLE
removeHeader is not removing header

### ISSUE THREAD

**Issue by breakline87** [square/okhttp#8256]
As the title says.

If I use an interceptor to remove headers as suggested, this is not working:

```
public Response intercept(Chain chain) throws IOException {
    Request request = chain.request()
        .newBuilder().removeHeader("User-Agent").build();
    return chain.proceed(request);
}
```

With calling a proxy I can see that okhttp adds its own User-Agent (as okhttp\/3.10.0).

However setting my own header seems to be working:

```
public Response intercept(Chain chain) throws IOException {
    Request request = chain.request()
        .newBuilder().addHeader("User-Agent", "test").build();
    return chain.proceed(request);
}
```

In my case, the server does not accept the call unless I set specific headers (and nothing else). So the header cannot be empty, it must not be present. However it seems to me that there is no way to actually remove headers from the final call (Host, Keep-Alive, Connection, User-Agent seem to be added automatically)? 

Any solution for this?

**Comment by yschimke** [comment]
`removeHeader("User-Agent")` will only work in a network interceptor. Not in an application interceptor.

https://square.github.io/okhttp/features/interceptors/
