### ISSUE TITLE
Feature Request: Add decoders for `MultipartBody` and `FormBody` to `MockWebServer` 

### ISSUE THREAD

**Issue by yogurtearl** [square/okhttp#8271]
When using `MockWebServer` you might want to verify the contents of requests that contains a `MultipartBody` or a `FormBody`. 

It would be useful if `MockWebServer` came with a decoder for each of those that could be used to decode the `body` of a `RecordedRequest`.

**Comment by yschimke** [comment]
Mockwebserver isn't under active development for enhancements.

So it's unlikely we will add this or accept a PR.

There are alternatives like mockserver which have a much more complete feature set for advanced cases.

**Comment by yogurtearl** [comment]
@yschimke you closed as "completed". should it be closed as "not planned" instead?
