### ISSUE TITLE
Websocket connection failing few seconds after getting connected

### ISSUE THREAD

**Issue by jashwin-codes** [square/okhttp#8285]
Websocket connection is failing in a particular android device(Xiaomi POCO X2) with the below error, it is happening after handshake is succeded. 

Websocket connection Failed Read error: ssl=0xb400006da8515bc8: Failure in SSL library, usually a protocol error error:1e000065:Cipher functions:OPENSSL_internal:BAD_DECRYPT (third_party/openssl/boringssl/src/crypto/fipsmodule/cipher/e_aes.c:1065 0x6fef330bee:0x00000000) error:1000008b:SSL routines:OPENSSL_internal:DECRYPTION_FAILED_OR_BAD_RECORD_MAC (third_party/openssl/boringssl/src/ssl/tls_record.cc:294 0x6fef330bee:0x00000000)

okHttpVersion - okhttp:4.9.3

**Comment by yschimke** [comment]
This is not something we can help with.

Try stackoverflow to diagnose this particular issue.  

If all the certificates are fine and it's still failing, then you'll need to report to [conscrypt](https://github.com/google/conscrypt) or Xiaomi.
