### ISSUE TITLE
Documentation: Is it possible to update the comment with more info

### ISSUE THREAD

**Issue by sarthak-greenely** [square/okhttp#8300]
https://github.com/square/okhttp/blob/f24bc62f6351219cc2c592a3a4dfaa569ba716a6/samples/guide/src/main/java/okhttp3/recipes/WebSocketEcho.java#L23

Hello! Is it possible to get more clarity on what this line does?
As my initial thought is that it would completely stop any subsequent network request made via this `OkHttpClient` object? Was this line written for this particular sample where we are creating a new OkHttpClient object inside `run()`?
Also, for an application having a singleton `OkHttpClient` object, should this be called at all?

Thanks for reading!

**Comment by swankjesse** [comment]
This might help?
https://github.com/square/okhttp/pull/8328
