### ISSUE TITLE
downloading big file (32G) midway Report an error java.net.ProtocolException: unexpected end of stream

### ISSUE THREAD

**Issue by xian2022** [square/okhttp#8359]
我基于okhttp去进行文件分片下载，服务端容器是tomcat，代码如下：
`response.setHeader("Content-Disposition", String.format("attachment; filename=%s", path.getFileName()));`
`response.setHeader("Content-Length", String.valueOf(chunck));`
`request.setAttribute(Constants.SENDFILE_FILENAME_ATTR, path.toString());`
`request.setAttribute(Constants.SENDFILE_FILE_START_ATTR, descriptor.getOffset());`
`request.setAttribute(Constants.SENDFILE_FILE_END_ATTR, (descriptor.getOffset() + chunck));`
客户端接收使用nio接收，代码如下：
`long alreadyRead = descriptor.getOffset();`
`long allChuncks = descriptor.getOffset() + (descriptor.getFchunck() > 0 ? descriptor.getFchunck() : descriptor.getFsize());`
`while (alreadyRead < allChuncks) {`
`          alreadyRead += fc.transferFrom(soChannel, alreadyRead, allChuncks - alreadyRead);`
`}`
文件下载到一半报错，java.net.protocolException:  unexpected end of stream

**Comment by yschimke** [comment]
This isn't actionable. If you can produce a reproduction we can investigate.

Otherwise I'd suggest a site like stackoverflow.
