### ISSUE TITLE
Handle Socket tagging for traffic analysis on Android

### ISSUE THREAD

**Issue by robUx4** [square/okhttp#837]
Android provides a way to tag sockets (or sockets created in a Thread) to analyze the traffic from your app with finer details. According to [this documentation](http://developer.android.com/training/efficient-downloads/efficient-network-access.html#DDMSNetworkTraffic) the ApacheClient and HttpUrlConnection code in Android use the tag set by [`TrafficStats.setThreadStatsTag()`](http://developer.android.com/reference/android/net/TrafficStats.html#setThreadStatsTag%28int%29) on each `Socket` created in the current Thread but okhttp doesn't use this value on the sockets it creates.

**Comment by Tinker-S** [comment]
`OkHttpClient.Builder builder = new OkHttpClient.Builder();
        builder.addNetworkInterceptor(new Interceptor() {
            @Override
            public Response intercept(Chain chain) throws IOException {
                TrafficStats.setThreadStatsTag(0x12340001);
                return chain.proceed(chain.request());
            }
        });`

I use the code to set stat tag for my network request. But it seems not work. What should I do?

**Comment by niqueco** [comment]
Socket tagging has since been removed in commit dd09bdb0de1dfdcbd3d3d076e27f75608ddb0ca3 ... yet it still mentioned in Platform.java javadoc. Just saying.
