### ISSUE TITLE
Failing while building okhttp version parent-3.6.0 using mvn clean install

### ISSUE THREAD

**Issue by shivsrivastava** [square/okhttp#8378]
Package artifact id: okhttp

source code url: https://github.com/square/okhttp/tree/parent-3.6.0

Issue Description: [failed_jdk_8.txt](https://github.com/square/okhttp/files/15051000/failed_jdk_8.txt)

JDK Version: 1.8

Build CMD: mvn clean install

MVN Version: 3.9.6

Error Log: 

[ERROR]   The project com.squareup.okhttp3:benchmarks:3.6.0 (C:\code\Code-Latest\okhttp3.6.0\code\okhttp\benchmarks\pom.xml) has 2 errors
[ERROR]     'dependencies.dependency.version' for org.mortbay.jetty.alpn:alpn-boot:jar must be a valid version but is '${alpn.jdk8.version}'. @ line 122, column 20
[ERROR]     'build.plugins.plugin[org.apache.maven.plugins:maven-surefire-plugin].dependencies.dependency.version' for org.mortbay.jetty.alpn:alpn-boot:jar must be a valid version but is '${alpn.jdk8.version}'. @ com.squareup.okhttp3:parent:3.6.0, C:\code\Code-Latest\okhttp3.6.0\code\okhttp\pom.xml, line 292, column 28
	

attachement: build log attached (jdk 1.8)

OS: windows 10

**Comment by yschimke** [comment]
OkHttp 3.6.0 and 3.x generally is unmaintained.

For this, there are specific ALPN profiles per JDK.

```
    <profile>
      <id>alpn-when-jdk8_11</id>
      <activation>
        <jdk>1.8.0_11</jdk>
      </activation>
      <properties>
        <alpn.jdk8.version>8.1.0.v20141016</alpn.jdk8.version>
      </properties>
    </profile>
```
