### ISSUE TITLE
A suggestion for the removeEntry function in the DiskLruCache class

### ISSUE THREAD

**Issue by rladmsdh** [square/okhttp#8417]
In the existing code, we used the let function to work with the JournalWriter in the RemoveEntry function. Using Apply instead of let allows you to remove the unnecessary it and access the object's methods directly.
Additionally, the completeEdit function in the same file also uses apply as a scope function for journalWriter, so it will help maintain the code style.

**Comment by swankjesse** [comment]
No action to take on this.
