### ISSUE TITLE
希望ok

### ISSUE THREAD

**Issue by gghxjava** [square/okhttp#8421]
Good bug reports include a failing test! Writing a test helps you to isolate and describe the problem, and it helps us to fix it fast. Bug reports without a failing test or reproduction steps are likely to be closed.

Here’s an example test to get you started.
https://gist.github.com/swankjesse/981fcae102f513eb13ed

**Comment by gghxjava** [comment]
希望okhttp的get请求可以携带请求体 ，不然真的很恶心

**Comment by Endeavour233** [comment]
> 希望okhttp的get请求可以携带请求体 ，不然真的很恶心

这个不能算bug吧，应该算是想要新加feature。可以把这个关了，另外建个tag是enhancement的issue: permits body in a GET request，然后举一下具体的要用到这个feature的业务场景。

**Comment by iseki0** [comment]
> 举一下具体的要用到这个feature的业务场景

比如 ElasticSearch 就有这样的 API，我要是没记错 Solr 也有。
> 不过这位贴主我看他是不打算搞了···

**Comment by GuDaoCoder** [comment]
如果确实要通过OkHttp发送带Body的Get请求，可以参考下我这个处理的方式。https://github.com/GuDaoCoder/code-demo/tree/main/okhttp-get-with-body

**Comment by GuDaoCoder** [comment]
> 希望okhttp的get请求可以携带请求体 ，不然真的很恶心
如果确实要通过OkHttp发送带Body的Get请求，可以参考下我这个处理的方式。https://github.com/GuDaoCoder/code-demo/tree/main/okhttp-get-with-body

**Comment by GuDaoCoder** [comment]
> 希望okhttp的get请求可以携带请求体 ，不然真的很恶心

如果确实要通过OkHttp发送带Body的Get请求，可以参考下我这个处理的方式。https://github.com/GuDaoCoder/code-demo/tree/main/okhttp-get-with-body

**Comment by yschimke** [comment]
Closing as no plan to support GET with Body in OkHttp

**Comment by iseki0** [comment]
> Closing as no plan to support GET with Body in OkHttp

Are there any reason to share?

**Comment by yschimke** [comment]
One example https://github.com/square/okhttp/issues/5852

**Comment by iseki0** [comment]
@yschimke OK, but the people in the thread which you referred is correct. You'd better add a known-limitation item in the wiki. Since there's no forbids in the RFC.

**Comment by yschimke** [comment]
I'll add something

**Comment by iseki0** [comment]
> I'll add something

Sounds great.
