### ISSUE TITLE
Configuring timeout durations in a custom `ConnectionPool`

### ISSUE THREAD

**Issue by lauzadis** [square/okhttp#8426]
We use the public constructor of `ConnectionPool` to create a pool with a custom `keepAliveDuration`, but this [does not support configuring other timeouts](https://github.com/square/okhttp/blob/master/okhttp/src/main/kotlin/okhttp3/ConnectionPool.kt#L46-L48) (like `readTimeoutMillis`), which are all part of the `internal` constructor. 

This means we can't simultaneously configure connect/read/write timeouts **and** `keepAliveDuration`.

For our specific use-case, here is where we [configure custom timeouts](https://github.com/smithy-lang/smithy-kotlin/blob/8476e39c2426d399338afa1b23950051d97060c0/runtime/protocol/http-client-engines/http-client-engine-okhttp/jvm/src/aws/smithy/kotlin/runtime/http/engine/okhttp/OkHttpEngine.kt#L96-L98), and here is [where we create a custom connection pool](https://github.com/smithy-lang/smithy-kotlin/blob/8476e39c2426d399338afa1b23950051d97060c0/runtime/protocol/http-client-engines/http-client-engine-okhttp/jvm/src/aws/smithy/kotlin/runtime/http/engine/okhttp/OkHttpEngine.kt#L103-L109) immediately after, effectively overriding those timeouts.

Is there some way to accomplish this already? If not, I can think of a few solutions:
1. Add other timeout durations (like `readTimeoutMillis`) to the public constructor of `ConnectionPool`
2. Support configuring `keepAliveDuration` on the default `ConnectionPool` without replacing it
3. Support configuring timeout durations on an already-constructed `ConnectionPool` 

Thanks!

**Comment by swankjesse** [comment]
Configure those other values on the `OkHttpClient.Builder`, not on the `ConnectionPool`.

**Comment by swankjesse** [comment]
(The values on the ConnectionPool are only for the `AddressPolicy` feature.)
