### ISSUE TITLE
When I use EventListener, the same call is called back twice connectStart

### ISSUE THREAD

**Issue by lbybug** [square/okhttp#8427]
okhttp version: 4.9.0
test url: https://apkpure.com/cn/timemark-timestamp-solocator/com.oceangalaxy.camera.new/download

test code:
```kotlin
object Http {

    var okhttp: OkHttpClient? = null


    init {
        okhttp = OkHttpClient.Builder().eventListener(Listener()).build()
    }


    fun getReq(url: String) {
        try {
            val request = Request.Builder().url(url).build()

        okhttp?.newCall(request)?.enqueue(object: Callback {
            override fun onFailure(call: Call, e: IOException) {
//                Log.e("QAPM_TEST", "onFailure, ${e.message}")
            }

            override fun onResponse(call: Call, response: Response) {
//                Log.e("QAPM_TEST", "response : " + response.body?.string())
                response.body()?.string()
            }
        })

//            val response = okhttp?.newCall(request)?.execute()
//            response?.close()
        } catch (th: Throwable) {
            th.printStackTrace()
        }

    }
}
```

```kotlin
// run it
Http.getReq("https://apkpure.com/cn/timemark-timestamp-solocator/com.oceangalaxy.camera.new/download")
```

<img width="1174" alt="image" src="https://github.com/square/okhttp/assets/28444406/e76aee36-4296-4a00-b1f9-4af92f3f9c7b">

**Comment by Endeavour233** [comment]
> okhttp version: 4.9.0 test url: https://apkpure.com/cn/timemark-timestamp-solocator/com.oceangalaxy.camera.new/download
> 
> test code:
> 
> ```kotlin
> object Http {
> 
>     var okhttp: OkHttpClient? = null
> 
> 
>     init {
>         okhttp = OkHttpClient.Builder().eventListener(Listener()).build()
>     }
> 
> 
>     fun getReq(url: String) {
>         try {
>             val request = Request.Builder().url(url).build()
> 
>         okhttp?.newCall(request)?.enqueue(object: Callback {
>             override fun onFailure(call: Call, e: IOException) {
> //                Log.e("QAPM_TEST", "onFailure, ${e.message}")
>             }
> 
>             override fun onResponse(call: Call, response: Response) {
> //                Log.e("QAPM_TEST", "response : " + response.body?.string())
>                 response.body()?.string()
>             }
>         })
> 
> //            val response = okhttp?.newCall(request)?.execute()
> //            response?.close()
>         } catch (th: Throwable) {
>             th.printStackTrace()
>         }
> 
>     }
> }
> ```
> 
> ```kotlin
> // run it
> Http.getReq("https://apkpure.com/cn/timemark-timestamp-solocator/com.oceangalaxy.camera.new/download")
> ```
> 
> <img alt="image" width="1174" src="https://private-user-images.githubusercontent.com/28444406/334857392-e76aee36-4296-4a00-b1f9-4af92f3f9c7b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcwMzE2MDMsIm5iZiI6MTcxNzAzMTMwMywicGF0aCI6Ii8yODQ0NDQwNi8zMzQ4NTczOTItZTc2YWVlMzYtNDI5Ni00YTAwLWIxZjktNGFmOTJmM2Y5YzdiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMwVDAxMDgyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRmMWFhYzkwZDFiNjI0NWI3OWZjOTliNTI0YmFjMDNkM2E2MzY5ZjNkMzNmNGVmNzI2ZTNmNDc1ZjU4MDFhZjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CQ2BDSqR0tv65JGZj5oabFUpD24DtXFrMbCNnTUzlHI">

Probably, it's because that for one host, there are several ips we can try to connect to. You could try to print out `route` in your eventListener and check out whether they are different.

**Comment by lbybug** [comment]
So I should end with CallFailed instead of connectFailed, right?

**Comment by Endeavour233** [comment]
> So I should end with CallFailed instead of connectFailed, right?

yep
