### ISSUE TITLE
🙉 When will OKHTTP 5. x release

### ISSUE THREAD

**Issue by jiankunking** [square/okhttp#8450]
We plan to use JDK 21 in the production environment to optimize requests through coroutine, but currently there has been no release for OKHTTP, so we are unsure if there may be any issues. So, when will OKHTTP 5. x release?

**Comment by yschimke** [comment]
It's hopefully close, a few small improvements to make but that are generally existing problems in 4.x also.  But we don't promise dates.

The 4.x APIs and functionality should be considered supported still, and if you avoid the experimental APIs, then you should consider 5 production ready.
