### ISSUE TITLE
NullPointerException with HandshakeCertificates - com.android.org.bouncycastle.jcajce.provider.keystore.bc.BcKeyStoreSpi.engineSetKeyEntry

### ISSUE THREAD

**Issue by YMonnier** [square/okhttp#8482]
Hello,
I am currently developing a mobile app that utilizes client certificate-based authentication, involving a multi-step process to ensure secure communication and authentication:

1. Initiate a Request: We start by sending a request to the Server API with various pieces of information and receive an ID in response.
2. Generate Keys and CSR: Using the received ID, we generate a key pair and a Certificate Signing Request (CSR) on the client side (mobile app) as shown below:
```kotlin
...
val certificateSubject = getX500Principal(id)
val keyPair = createKeyPair(certificateSubject)
val contentSigner = JcaContentSignerBuilder(SIGNATURE_ALGORITHM).build(keyPair.private)
val certificationRequest = JcaPKCS10CertificationRequestBuilder(certificateSubject, keyPair.public).build(contentSigner)
...
private fun createKeyPair(certificateSubject: X500Principal): KeyPair {
        val keyPairGenerator = KeyPairGenerator.getInstance(KEY_ALGORITHM_EC, KEYSTORE_TYPE)
        keyPairGenerator.initialize(
            KeyGenParameterSpec.Builder(KEY_ALIAS_NAME, PURPOSE_SIGN)
                .setKeySize(KEY_SIZE)
                .setDigests(DIGEST_NONE, DIGEST_SHA256, DIGEST_SHA512)
                .setUserAuthenticationRequired(true)
                .setInvalidatedByBiometricEnrollment(true)
                .setAlgorithmParameterSpec(ECGenParameterSpec(ALGORITHM_PARAM_SPECIFIC))
                .setCertificateSubject(certificateSubject)
                .build(),
        )
        return keyPairGenerator.genKeyPair()
}
```
3. Obtain Signed Client Certificate: We send the signed CSR to the server to obtain a client certificate signed by the server.
4. Store the Client Certificate: The client certificate is then stored in the KeyStore:
```kotlin
val keyStore = getKeyStore()
val boundedCertificate = BEGIN_CERTIFICATE + NEW_LINE + certificate + NEW_LINE + END_CERTIFICATE
val trustCertificate = boundedCertificate.decodeCertificatePem()
val entry = keyStore.getEntry(KEY_ALIAS_NAME, null) as? KeyStore.PrivateKeyEntry ?: throw Error()
keyStore.setKeyEntry(KEY_ALIAS_NAME, entry.privateKey, null, arrayOf(trustCertificate))
```
5. Perform Authenticated Requests: Utilize the client certificate and private key to make authenticated API requests to the server, similar to using cURL:
```bash
curl --cert /path/to/cert.pem --key /path/to/key.pem https://your-secure-url.com
```

To enable secure API communication with the server, we implement `sslSocketFactory` from `OkHttpClient.Builder`. Below is our approach:

```kotlin
// Koin OkHttp Builder definition:
factory {
    val (socketFactory, trustManager) = CommonSecurityHelper.getSslSocketFactoryConfig(get(), isPublicService)
    val certificatePinner = CommonSecurityHelper.getCertificatePinner()

    OkHttpClient.Builder()
        ...
        .sslSocketFactory(socketFactory, trustManager)
        .certificatePinner(certificatePinner)
}
```

```kotlin
// CommonSecurityHelper.kt
fun getSslSocketFactoryConfig(context: Context): Pair<SSLSocketFactory, X509TrustManager> {
    val keyManagers = getKeyManagers()
    val trustManager = getTrustManager(context)
    val sslContext = getSslContext(keyManagers, arrayOf(trustManager))
    val socketFactory = sslContext.socketFactory
    return socketFactory to trustManager
}

private fun getKeyManagers(): Array<KeyManager>? {
        val keyManagerFactory = KeyManagerFactory.getInstance(KeyManagerFactory.getDefaultAlgorithm())
        keyManagerFactory.init(getKeyStore(), null)
        keyManagerFactory.keyManagers.getOrNull(0)?.let { arrayOf(it) }
        return keyManagers
}

private fun getKeyStore(): KeyStore {
        val keyStore = KeyStore.getInstance(KEYSTORE)
        keyStore.load(null)
        return keyStore
}

private fun getTrustManager(context: Context): X509TrustManager {
    val platformCertificates = Platform.get().platformTrustManager().acceptedIssuers.toList()
    val trustStore = KeyStore.getInstance(KeyStore.getDefaultType())
    trustStore.load(null, null)
    platformCertificates.forEachIndexed { index, certificate ->
        trustStore.setCertificateEntry(CERTIFICATE_PREFIX_NAME + index, certificate)
    }

    val factory = TrustManagerFactory.getInstance(TrustManagerFactory.getDefaultAlgorithm())
    factory.init(trustStore)

    val trustManager = factory.trustManagers.getOrNull(0) as X509TrustManager
    return trustManager
}

private fun getSslContext(keyManagers: Array<KeyManager>?, trustManagers: Array<X509TrustManager>): SSLContext {
    val sslContext = SSLContext.getInstance(SSL_CONTEXT)
    sslContext.init(keyManagers, trustManagers, SecureRandom())
    return sslContext
}
```

We attempted to manually insert the client certificate using `HandshakeCertificates` and `HeldCertificate` instead of the `getSslSocketFactoryConfig` function described earlier. However, this approach failed and resulted in the same issues as those documented in these links: https://github.com/square/okhttp/issues/6116 and https://github.com/square/okhttp/issues/6463. We encountered a `java.lang.NullPointerException` with the message: "`Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference.`"

The workaround suggested in https://github.com/square/okhttp/issues/6116 (found here: https://gist.github.com/yschimke/4a1eda31c584a64549c790d887f275e0 and detailed here: https://medium.com/@_kbremner/android-and-client-authentication-fd416af19a04) does not meet our requirements. The user experience of selecting the certificate via `KeyChain.choosePrivateKeyAlias` is not ideal.

Has there been any resolution or update to https://github.com/square/okhttp/issues/6116 that I might have overlooked? Additionally, is there another method to manually insert the certificate that might bypass these issues? (another client http library?)

**Comment by yschimke** [comment]
Does it work if you skip storing the certificate to the keystore, and just store the certificate in a file? Then load that into the OkHttpClient with HeldCertificate.

I guess the point of #6116 is that if you have something really custom, you may not be able to use the default SSL setup of OkHttpClient or okhttp-tls classes, but you can skip it completely. So I don't think this is specifically an OkHttp issue, if after 4) storing into the keystore, you can simulate 5) with a SSLSocket directly, then it's solvable.

As far as alternative Http clients, Cronet and EnvoyMobile doesn't seem to expose this. Android NetworkSecurityConfig doesn't seem to allow this if it's not a resource or in the system trust store. Everything else is likely based on SSLSocket and friends. Maybe bouncycastle could be worth trying if it's still failing.

But my suggestion, make a simple reproduction in an android app or test, and we can see where it's breaking and why.

**Comment by yschimke** [comment]
Did you look at https://github.com/square/okhttp/pull/7887/files

BTW this was a while ago, so without a specific example I can run in front of me, I might be confused.
