### ISSUE TITLE
connectjavax.net.ssl.SSLHandshakeException: Chain validation failed

### ISSUE THREAD

**Issue by louishot** [square/okhttp#8502]
Hi guys,

Today I see use okhttp to call the URL get this errors: connectjavax.net.ssl.SSLHandshakeException: Chain validation failed
But there is no problem accessing it using a browser.
After a long time of troubleshooting we found reason:because  the SSL ocsp stapling response does not match the certificate.

okhttp should run the same as browser to ignore invalid ocsp stapling response instead SSLHandshakeException.

Thank you

**Comment by louishot** [comment]
I see https://github.com/square/okhttp/issues/6930
But why does the browser work well?

**Comment by yschimke** [comment]
Can you include a stack trace. This won't be an okhttp issue. Okhttp uses the platform TLS stack.

**Comment by BinarySatan** [comment]
How to solve this problem?

**Comment by kiraraajay** [comment]
i think this problem comming becouse  the server not allow to play on privete browser or download video somethink like that
