### ISSUE TITLE
Random logs '[okhttp] check permission begin' when app starts

### ISSUE THREAD

**Issue by WebTiger89** [square/okhttp#8508]
In my android application I get the following logs

> 21:57:48.801 System.out               I  [okhttp] e:java.lang.ClassNotFoundException: com.mediatek.cta.CtaUtils
21:57:48.808 System.out               I  [socket]:check permission begin!
21:57:48.812 System.out               I  [socket] e:java.lang.ClassNotFoundException: com.mediatek.cta.CtaUtils
21:57:49.045 System.out               I  [OkHttp] sendRequest>>
21:57:49.046 System.out               I  [OkHttp] sendRequest<<
21:57:49.099 System.out               I  [socket]:check permission begin!
21:57:49.154 System.out               I  [OkHttp] sendRequest>>
21:57:49.155 System.out               I  [OkHttp] sendRequest<<
21:57:49.425 System.out               I  [okhttp]:check permission begin!
21:57:49.426 System.out               I  [okhttp]:not MMS!
21:57:49.426 System.out               I  [okhttp]:not Email!
21:57:49.428 System.out               I  [socket]:check permission begin!
21:57:49.469 System.out               I  [OkHttp] sendRequest>>
21:57:49.469 System.out               I  [OkHttp] sendRequest<<

Same logs occur, when I perform http POST.

Are these logs library related and can I prevent them?

**Comment by yschimke** [comment]
Not from OkHttp. your app must be logging them.

**Comment by xiazhichao** [comment]
I have the same problem, how to solve it
