### ISSUE TITLE
OkHttpClient Connection Metrics 

### ISSUE THREAD

**Issue by arpit-hotstar** [square/okhttp#8522]
I have configured below OkHttpClient Connection Pool Configuration 
```
new ConnectionPool(350, 60000,  TimeUnit.MILLISECONDS); 
````
When I tried to access metrics related connection via gauge as below : 
```
  meterRegistry.gauge("okhttp.client.connection.pool.total",
                    connectionPool, ConnectionPool::connectionCount);
 meterRegistry.gauge("okhttp.client.connection.pool.idle",
                    connectionPool, ConnectionPool::idleConnectionCount);
```
It's always giving `1` As connection count(ideally this should show connection/idle connection count in pool), Can you help us understand, What can be reason for this ? Let me know if there is any other way to expose connection metrics for OkhttpClient.

**Comment by yschimke** [comment]
Are you using http/2 with a single server? There is connection pooling.

To understand pooling attach an event listener.

https://square.github.io/okhttp/features/events/

**Comment by arpit-hotstar** [comment]
> Are you using http/2 with a single server?
Yes, but i wanna understand What is use of `ConnectionPool::connectionCount` and `ConnectionPool::idleConnectionCount` methods. As per definition it say total connections in connection pool https://square.github.io/okhttp/3.x/okhttp/okhttp3/ConnectionPool.html#connectionCount--

**Comment by yschimke** [comment]
Up to you, but at least to understand why it's 1. Add the event listener even just with simple logging, and see what is going on.

Is it reusing connection, or closing other ones. 

Or perhaps you are creating multiple clients instead of reusing one.

**Comment by arpit-hotstar** [comment]
> Up to you, but at least to understand why it's 1. Add the event listener even just with simple logging, and see what is going on.

I tried with basic code with hitting multiple request concurrently that also shows total connection/idle connections as one only.
Ex : Test Code 
```
 ExecutorService executorService = Executors.newFixedThreadPool(5);

  for (int i = 0; i < 5; i++) {
      executorService.submit(() -> {
          Request request = new Request.Builder()
              .url("https://httpbin.org/get")
              .build();
          try (Response response = client.newCall(request).execute()) {
              System.out.println("Response code: " + response.code());
          } catch (Exception e) {
              e.printStackTrace();
          }
      });
  executorService.shutdown();
  executorService.awaitTermination(10, TimeUnit.SECONDS);
  System.out.println("Total connections in pool: " + pool.connectionCount());
  System.out.println("Idle connections in pool: " + pool.idleConnectionCount());
```
If you see below event logs there also I can see multiple connection got acquired around 1.066/67/68 so ideally should have reflect in total connection/idle connection count.

```
0.000 callStart
0.000 callStart
0.000 callStart
0.000 callStart
0.000 callStart
0.017 dnsStart
0.017 dnsStart
0.017 dnsStart
0.017 dnsStart
0.017 dnsStart
0.041 dnsEnd
0.041 dnsEnd
0.041 dnsEnd
0.041 dnsEnd
0.041 dnsEnd
0.048 connectStart
0.048 connectStart
0.048 connectStart
0.048 connectStart
0.048 connectStart
0.274 secureConnectStart
0.274 secureConnectStart
0.274 secureConnectStart
0.276 secureConnectStart
0.288 secureConnectStart
1.018 secureConnectEnd
1.018 secureConnectEnd
1.035 connectEnd
1.044 secureConnectEnd
1.044 secureConnectEnd
1.036 connectEnd
1.061 secureConnectEnd
1.058 connectEnd
1.065 connectEnd
1.058 connectionAcquired
1.066 connectEnd
1.066 connectionAcquired
1.067 connectionAcquired
1.068 connectionAcquired
1.068 connectionAcquired
1.082 requestHeadersStart
1.082 requestHeadersStart
1.082 requestHeadersStart
1.082 requestHeadersStart
1.082 requestHeadersStart
1.095 requestHeadersEnd
1.095 requestHeadersEnd
1.095 requestHeadersEnd
1.095 requestHeadersEnd
1.095 requestHeadersEnd
1.539 responseHeadersStart
1.541 responseHeadersEnd
Response code: 200
1.544 responseBodyStart
1.544 responseBodyEnd
1.544 connectionReleased
1.544 callEnd
1.563 responseHeadersStart
1.563 responseHeadersEnd
Response code: 200
1.565 responseBodyStart
1.565 responseBodyEnd
1.565 connectionReleased
1.565 callEnd
1.586 responseHeadersStart
1.587 responseHeadersEnd
Response code: 200
1.587 responseBodyStart
1.587 responseBodyEnd
1.587 connectionReleased
1.587 callEnd
1.773 responseHeadersStart
1.777 responseHeadersEnd
Response code: 200
1.778 responseBodyStart
1.778 responseBodyEnd
1.778 connectionReleased
1.778 callEnd
2.442 responseHeadersStart
2.442 responseHeadersEnd
Response code: 200
2.445 responseBodyStart
2.445 responseBodyEnd
2.445 connectionReleased
2.445 callEnd
Total connections in pool: 1
Idle connections in pool: 1
```

> perhaps you are creating multiple clients instead of reusing one.

This is not possible if you see above code.

OkHttpClient Version : 4.12.0

**Comment by yschimke** [comment]
Connection acquired is a call acquiring from the pool.

Once the racing requests get a single pooled connection, they share it.

That's why it's 1

**Comment by yschimke** [comment]
But the metrics look correct, so closing.

**Comment by arpit-hotstar** [comment]
I just wanna understand for high rpm scenario, How this single pooled connection will shared across multiple requests ?

How this get determined in Pool, how many connections need to be opened ? As per below i have specified maxConn to 350.
```
new ConnectionPool(350, 60000,  TimeUnit.MILLISECONDS); 
```

**Comment by yschimke** [comment]
OkHttp has limited control of the connection pool in this way.  IT tries to do the right thing for typical workloads and following the HTTP/2 spec.

See https://github.com/square/okhttp/issues/4530 which discusses some possible features.

This is one hacky approach to achieve manual connection pooling https://github.com/square/okhttp/pull/7280/files
