### ISSUE TITLE
okhttp3 get result from proxy server,but not real result

### ISSUE THREAD

**Issue by lh007de** [square/okhttp#8523]
hello,guys, the question confused me for some days.
**backgroud:** 
  we use okhttp3(version 4.2.0) to get api response for java，for network cause,we must use proxy server( server not need config auth info),everything seems ok at first, when url is not exist,we expect okhttp3 return 404,504 ...anycode is ok,but we  just get 200 from proxy server.any one give some tips would be thanks.

**Comment by lh007de** [comment]
the question seems  the same as  #7763

**Comment by yschimke** [comment]
This is better asked on a site like stackoverflow or slack.

You might consider a network Interceptor to change the problematic responses when you can detect them.
