### ISSUE TITLE
FIx of #6721 lost?

### ISSUE THREAD

**Issue by jccazeaux** [square/okhttp#8527]
Hi,

I have a bug that is exactly the one reported in #6721 and fixed with PR https://github.com/square/okhttp/pull/6729
I reproduce the bug in an Android reactNative (0.72.0) application with okhttp-urlconnection:4.9.2.

The application crashes with stackTrace
```
 java.lang.StringIndexOutOfBoundsException: begin 1, end 0, length 1
 	at java.lang.String.checkBoundsBeginEnd(String.java:4466)
 	at java.lang.String.substring(String.java:2517)
 	at okhttp3.JavaNetCookieJar.decodeHeaderAsJavaNetCookies(JavaNetCookieJar.kt:98)
 	at okhttp3.JavaNetCookieJar.loadForRequest(JavaNetCookieJar.kt:59)
 	at com.facebook.react.modules.network.ReactCookieJarContainer.loadForRequest(ReactCookieJarContainer.java:44)
 	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:74)
 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
 	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
 	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
 	at java.lang.Thread.run(Thread.java:1012)
```

The PR has been merged in 06/2021 but is not in 4.9.x versions. Is this normal?

**Comment by JakeWharton** [comment]
If you click on the merged SHA it shows you what tags contain it: https://github.com/square/okhttp/commit/78813abe7604ab3aa8f8ebbe84b9c0dd7327cc84

Looks like it's only in 5.0 alphas.

![Screenshot_20240829-100528.png](https://github.com/user-attachments/assets/9b99da63-610e-4b68-b889-09d496be6afe)

**Comment by jccazeaux** [comment]
The bug was detected and fixed in 2021, why is it only for 5.0.0 alpha? I have the bug on production application, i cannot go for alpha version

**Comment by jccazeaux** [comment]
@JakeWharton could you consider reopening this issue? The bug has been fixed and back ported on 3.12 with PR https://github.com/square/okhttp/pull/6898

It should be in 4.9 as well

**Comment by yschimke** [comment]
Yep, I can backport it. I'm not sure when the next 4.x release will be.

**Comment by jccazeaux** [comment]
The "almost" won't be enough i'm afraid. The okhttp3 is a dependency of react-native. I don't think it would be a good idea to force this version jump to fix a bug.

Our application is currently on beta, and is planned to be release in october. This issue is a blocker. When it happens it crashes the application at every start until we desinstall or clean all data. For customers it will be a disaster and it could stop the final release.

It's frustrating to see that it has been detected and fixed in 2021 but not included in versions 4.9.x. Is it possible to release a fix version of okhttp-urlconnection with this small, but really important, patch?

**Comment by FairlandZ78** [comment]
I want to say something these bugs that is being  duplicate  or whatever the case may be can I have some advice as to were I can talk to the people that are working on this considering I am the one that reported these bugs and these are my files thank you please and thank uou

**Comment by JakeWharton** [comment]
The versioning is for humans. If it wasn't backwards compatible our policy is to change the name of the Maven groupId and the package name. This would require all users to actually migrate their code, not just increase a version. The "alpha" indicates we're not done with the changes which are going into it–that's it.

> I don't think it would be a good idea to force this version jump to fix a bug.

This is what you're asking for, though. But as a human, you feel more comfortable with a new 4.x and not a 5.x-alpha, despite that fact that these aren't that different.

**Comment by jccazeaux** [comment]
It's mainly because it's a transitive dependency. React native has not released a version tested with 5.0.0 for production apps. I cannot make it for them. 

Yes versioning is for humans. That's what we are. As humans, alpha versions are not for production. I understand this was not planned, but maybe the release is not that complicated as the PR already exists and was backported in 3.12?

**Comment by JakeWharton** [comment]
> As humans, alpha versions are not for production

Sorry, no. We've already covered this is not what it means.

Every alpha and every non-alpha version (and every commit actually) passes the exact same suite of tests. You're asking for a new 4.x release that will have the exact same level of testing as the current master and the current latest alpha. The only difference is the arbitrary version name we give it. We could call that 5.0 and start publishing 6.0 alphas. We could call it Pete. It's completely arbitrary and has zero correlation as to whether it is suitable for production or not. Every single commit is suitable for production.

**Comment by jccazeaux** [comment]
Okhttp is a transitive dependency. I cannot go for 5.0.0 without react native I the loop. Is it possible, or not, to have a quick fix on 4.9?

**Comment by JakeWharton** [comment]
Your app still builds with Gradle, and you have full control over the transitive dependency graph, for what it's worth.

I don't perform the releases.

**Comment by jccazeaux** [comment]
It's for a banking application with 10+ millions downloads rewritten in react native. Taking an alpha version is not an option. Even if it's a human representation, alpha means something.
I hoped his substring bug would be fixed easier on a open source library integrated in big framework like react native.

**Comment by JakeWharton** [comment]
Cash App has 100+ million downloads and runs the "alpha" just fine. I will push a 5.0 that's a bit-for-bit match with the latest alpha and we can watch as the world upgrades without incident.

**Comment by jccazeaux** [comment]
> Yep, I can backport it. I'm not sure when the next 4.x release will be.

I missed this comment in the flow. Thank you for your help.

**Comment by jccazeaux** [comment]
> Cash App has 100+ million downloads and runs the "alpha" just fine. I will push a 5.0 that's a bit-for-bit match with the latest alpha and we can watch as the world upgrades without incident.

Sorry we're too close from final release to take this risk. 5 will be taken as soon as react native validates it. I'll open an issue on react native to ask

**Comment by yschimke** [comment]
I'll backport this weekend, but I can't promise a date for the release. I don't perform the releases.

If we seem uncaring by your plight, this might explain our lack of urgency

https://www.zacsweers.dev/you-are-not-blocked/

**Comment by jccazeaux** [comment]
Thank you. I'm sorry if i'm a bit pushy but this issue is a blocker for us. I hope it will come soon. I'll try to find a workaround in the meantime.

**Comment by jccazeaux** [comment]
Great idea thanks !!

**Comment by jccazeaux** [comment]
It worked. Thanks. I close the issue
