### ISSUE TITLE
Invalidate cached URL

### ISSUE THREAD

**Issue by shaunchurch** [square/okhttp#853]
I'd like to be able invalidate an API route / method in the cache.

I have a cached response from /api/route. When I take some action in my app which updates the data on the server, I know that the previous response from /api/route is now invalid, and I need to ensure next time I call that route a network call is made to get the new data.

I'm currently working around this by calling the route with Cache-Control: no-cache set, which seems to work to force a network request and then caches the new response next time it's called without no-cache, but obviously this is not ideal, causing network activity which might never be required (or might then be again invalidated by taking action before /api/route is called again).

I'm using OKHttp as a client in retrofit. See: http://stackoverflow.com/questions/23782531/how-to-invalidate-force-update-of-cache-route-at-next-request-with-retrofit-and

**Comment by alican** [comment]
Hello,

is invalidating a specific cached URL possible now?

**Comment by swankjesse** [comment]
@alican yep. Use the iterator to iterate the URLs in the cache, then call `remove()` when you see a URL you don’t want anymore.

**Comment by alican** [comment]
Thank you Jesse for your answer :)
Have you an example code how to do this with retrofit? 
I looked in the javadocs and didint see how do get the URLs from inside an android activity.

**Comment by alenz316** [comment]
@swankjesse or @niqo01 Do either of you have a gist of how to do URL pattern invalidation for cache eviction? Like suggested in the [previous comment](https://github.com/square/okhttp/issues/853#issuecomment-65845182).

**Comment by shmueldabomb441** [comment]
Here is the example from [https://square.github.io/okhttp/caching/#pruning-the-cache]() :

```
    val urlIterator = cache.urls()
    while (urlIterator.hasNext()) {
      if (urlIterator.next().startsWith("https://www.google.com/")) {
        urlIterator.remove()
      }
    }
```
