### ISSUE TITLE
Unable to load publicsuffixes.gz resource from the classpath on minified build

### ISSUE THREAD

**Issue by yuvalgnessin-qz** [square/okhttp#8534]
First of all, thank you for maintaining this great library!

After upgrading a third party SDK ([OneTrust](https://developer.onetrust.com/onetrust/docs/android)) in our app, we ran into this crash:
```
java.lang.IllegalStateException: Unable to load publicsuffixes.gz resource from the classpath.
```

The crash only occurs in minified release builds. 

It does not come from the 3rd party SDK, but rather from our own code that uses OkHttp. But it only happened after upgrading the other SDK.

After de-obfuscating the stacktrace we determined it's coming from here:
```
java.lang.IllegalStateException Unable to load publicsuffixes.gz resource from the classpath.
    okhttp3.internal.publicsuffix.PublicSuffixDatabase.findMatchingRule (PublicSuffixDatabase.kt:110)
    okhttp3.internal.publicsuffix.PublicSuffixDatabase.getEffectiveTldPlusOne (PublicSuffixDatabase.kt:72)
```

Inside `PublicSuffixDatabase.findMatchingRule:110`, we find that this is what’s throwing the error:
```kotlin
check(::publicSuffixListBytes.isInitialized) {
    "Unable to load $PUBLIC_SUFFIX_RESOURCE resource from the classpath."
}
```

We attempted several changes to our R8 setup, but we weren’t able to fix the crash. Here are some of our findings and things we tried:
- Turning off `minifyEnabled` made the crash go away
- We built a debug version of the app with minification enabled, but the crash didn’t repro.
- Turning off `shrinkResources` had no impact, it still crashed
- Forcing okhttp version in gradle to 4.12.0 also did not help
- Inspected the output of `./gradlew app:dependencies`, but did not see OneTrust pulling in any other okhttp versions
- Reached out to OneTrust but they had never seen this before
- Inspected the minified release APK and saw that the `publicsuffixes.gz` file is there, so our hypothesis is that the file isn’t missing or renamed, but something with being able to access it
- We loaded the proguard mappings into Android Studio’s APK analyzer and validated that `PublicSuffixDatabase` is there and looks right. We noticed some of the functions come from `PublicSuffixDatabase$Companion`, so we made sure to keep everything there too. 
- We tried adding these rules to our proguard config, but they didn't work
```
-adaptresourcefilenames okhttp3/internal/publicsuffix/PublicSuffixDatabase.gz
-adaptresourcefilenames okhttp3/internal/publicsuffix/publicsuffixes.gz
-keep class okhttp3.internal.publicsuffix.PublicSuffixDatabase { *; }
-keep class okhttp3.internal.publicsuffix.PublicSuffixDatabase$Companion { *; }
```

At this point I'm pretty stumped. I thought it could be a bug with OkHttp missing some kind of keep rules or permissions with locating the file, but I don't know.

Thanks for your help & attention to this issue!

**OkHttp version: 4.12.0**
**Android Gradle Plugin version: 8.6.0** (also occurs with **8.5.2**)

**Comment by yschimke** [comment]
I'd suggest making the resource call yourself at app startup, so you know exactly what path is being called. But based on unobfuscated package names it should be in the original location.

Do you have anything peculiar like a split bundle?

Without a repro, it will be hard to workout why it's happening. But I think the first thing is to pull this into your own code just to print out the state of everything when it runs.

**Comment by yuvalgnessin-qz** [comment]
Thanks for your help!

We figured out the issue - this happened because of this in our Proguard file:
```
-repackageclasses ''
```

It turns out the old version of the OneTrust SDK was exposing many broad Proguard rules that our build was absorbing, including `-keeppackagenames`, which overrode the effects of `-repackageclasses`. Once we updated it, those rules went away, and our code was getting repackaged in a way that broke OkHttp.

The solution was to remove `-repackageclasses` from our app.

**Comment by yschimke** [comment]
Can you raise a bug on the onetrust sdk to advise them?

Thanks for the update

**Comment by Serre85** [comment]
It really helped to me. Thanks

**Comment by FernandoUFS** [comment]
> Thanks for your help!
> 
> We figured out the issue - this happened because of this in our Proguard file:
> 
> ```
> -repackageclasses ''
> ```
> 
> It turns out the old version of the OneTrust SDK was exposing many broad Proguard rules that our build was absorbing, including `-keeppackagenames`, which overrode the effects of `-repackageclasses`. Once we updated it, those rules went away, and our code was getting repackaged in a way that broke OkHttp.
> 
> The solution was to remove `-repackageclasses` from our app.

I'm having the issue, but I don't have that line in my proguard file.

**Comment by ygnessin** [comment]
> I'm having the issue, but I don't have that line in my proguard file.

@FernandoUFS maybe you have `-flattenpackagehierarchy`? Or maybe you are consuming proguard rules from a 3rd party which is providing one of those rules?

**Comment by FernandoUFS** [comment]
> > I'm having the issue, but I don't have that line in my proguard file.
> 
> [@FernandoUFS](https://github.com/FernandoUFS) maybe you have `-flattenpackagehierarchy`? Or maybe you are consuming proguard rules from a 3rd party which is providing one of those rules?

No, I don't have it. 

My current setup is:
**Gradle version 8.8**
`com.squareup.okhttp3:okhttp:5.+` (I tried with version 4.12.0, same error)

My proguard rules (that I tried to change everything already)
```
#-keep class okhttp3.internal.publicsuffix.PublicSuffixDatabase
-keep class okhttp3.internal.publicsuffix.** { *; }
-keepnames class okhttp3.internal.publicsuffix.** { *; }
-keeppackagenames okhttp3.**
#-adaptresourcefilenames okhttp3/internal/publicsuffix/PublicSuffixDatabase.gz
#-adaptresourcefilenames okhttp3/internal/publicsuffix/publicsuffixes.gz
```

Analyzing my generated apk, I found that the PublicSuffixDatabase.gz file instead of stay in `/okhttp3/internal/publicsuffix/PublicSuffixDatabase.gz` it's being moved to `J3/publicsuffix/PublicSuffixDatabase.gz` or any other coded folder like "H1" etc. 

I found that `adaptresourcefilenames` makes the folder structure to be moved. So I have commented that line, but I keep having the resources moved. Then I saw that in proguard rules from the okhttp package  (okhttp.pro), I have these lines:
```
# A resource is loaded with a relative path so the package of this class must be preserved.
-keeppackagenames okhttp3.internal.publicsuffix.*
-adaptresourcefilenames okhttp3/internal/publicsuffix/PublicSuffixDatabase.gz
```
I'm trying now not to include that proguard rules, but I don't know how.

**Comment by FernandoUFS** [comment]
I solved by using 

```
-repackageclasses 'okhttp3'
``` 

along with

```
-keep class okhttp3.internal.publicsuffix.** { *; }
-keepnames class okhttp3.internal.publicsuffix.** { *; }
-keeppackagenames okhttp3.**
```

As I only have the OkHttp3 resources, I had no problem with other packages.

**Comment by pierroo** [comment]
I am using react native, and out of nowhere, from the same build that has been working for months, 20% of my users trigger this crash:

```
Exception java.lang.IllegalStateException: Unable to load PublicSuffixDatabase.gz resource from the classpath.
  at okhttp3.internal.publicsuffix.PublicSuffixDatabase.findMatchingRule (PublicSuffixDatabase.kt:109)
  at okhttp3.internal.publicsuffix.PublicSuffixDatabase.getEffectiveTldPlusOne (PublicSuffixDatabase.kt:71)
  at okhttp3.Cookie$Companion.parse$okhttp (Cookie.kt:483)
  at okhttp3.Cookie$Companion.parse (Cookie.kt:382)
  at okhttp3.Cookie$Companion.parseAll (Cookie.kt:615)
  at okhttp3.internal.http.HttpHeaders.receiveHeaders (HttpHeaders.kt:203)
  at okhttp3.internal.http.BridgeInterceptor.intercept (BridgeInterceptor.kt:86)
  at okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.kt:109)
  at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept (RetryAndFollowUpInterceptor.kt:65)
  at okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.kt:109)
  at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp (RealCall.kt:205)
  at okhttp3.internal.connection.RealCall$AsyncCall.run (RealCall.kt:537)
  at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1133)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:607)
  at java.lang.Thread.run (Thread.java:762)
```

anyone has a clue what could be the reason?
I have a feeling this may be due to my supabase-js package, but how could I pinpoint where it comes from since it started out of the blue without any changes on my end, yet it crashes from the clients?

**Comment by yschimke** [comment]
Do you have breakdowns of affected Manufacturers, API level, regions etc?

**Comment by pierroo** [comment]
As far as I can tell, all manufacturers & all APIs.

I have users from all over the world and they seem to all be affected.

How could region have an impact here ? 
I will try to dig deeper and get back here

**Comment by yschimke** [comment]
I've seen weird things localised to regions e.g. maybe it's only happening on certain devices in the China market.

**Comment by pierroo** [comment]
You mean you recently experienced similar issue on your end ? 
It started on May 26th on my end.
No chinese users, but mainly south east asia (India / Indonesia)
Will check if other parts as well are concerned (US/Europe)

**Comment by yschimke** [comment]
Not recently, in the past with errors that made no sense. This error seems possible anyway, so I'd try to work out if someone is republishing a modified version of your app that is missing some files?

Also which version of OkHttp are you using?

**Comment by pierroo** [comment]
> Not recently, in the past with errors that made no sense. This error seems possible anyway, so I'd try to work out if someone is republishing a modified version of your app that is missing some files?
> 
> Also which version of OkHttp are you using?

1- the only mention of okhttp version I have is in my app/build.gradle:
```
force "com.facebook.fresco:imagepipeline-okhttp3:3.1.3"
```
but this is for fresco, so maybe unrelated?
and since I am using RN0.73.4, the okhttp "should" be 4.12.0 or as I see in my dependencies file:
```
    +--- com.squareup.okhttp3:okhttp-urlconnection:4.9.2
|    |    +--- com.squareup.okhttp3:okhttp:4.9.2 -> 5.0.0-alpha.11 (*)
|    |    \--- org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.4.10 -> 1.9.21 (*)
|    +--- com.squareup.okhttp3:okhttp:4.9.2 -> 5.0.0-alpha.11 (*)
```

2- those crash logs I get are from google play console;
so if anyone was distributing a modified version of my app it wouldn't be caught by google play console; + I have many checks from my backend to catch modified apk names, so not the issue.

also, the same build of my app was working fine for months on this same version, yet out of nowhere on the 26th it started crash.

what could be causing this?
2 things are doing network calls from the screen in my app that crashes:

1- a supabase query
2- a "NetInfo" to check the internet connection of the user

and last, back to your questions about localizations, it happens to my users from all over the world (asia/EU/US etc)

**Comment by yschimke** [comment]
Nope, you are using an old alpha 5.0.0-alpha.11

Either switch to 5.0.0-alpha.16 or revert to 4.12.0

**Comment by pierroo** [comment]
> Nope, you are using an old alpha 5.0.0-alpha.11
> 
> Either switch to 5.0.0-alpha.16 or revert to 4.12.0

I will do it for the next release, but what I still don't understand is:

why that version has been working for months, and overnight started crashing out of nowhere for a specific function?
can okhttp remotely break down a client?

**Comment by pierroo** [comment]
I'm coming with new info @yschimke :
as you suggested, I tried rolling back my okhttp version to 4.12.0 => it then works without issue!
However with the 5.x alpha 11, it crashes (my app in production uses alpha 11)

do you have any clue what could justify supabase websocket suddenly crashing with alpha 11? (it used to work for months before it stopped overnight as I mentioned)

and I didn't change anything in my proguard file for 4.12.0 to work, so it's weird that 
```
Unable to load PublicSuffixDatabase.gz resource from the classpath
```
would only be triggered on alpha 11 out of nowhere no?

**Comment by yschimke** [comment]
There were changes  to this in multiple alphas so check the release notes and use the latest alpha, or 14 at least
