### ISSUE TITLE
okhttp3.mockwebserver 4.12.0

### ISSUE THREAD

**Issue by mohamed928** [square/okhttp#8539]
Hello Community, 
Please Im having an issue can't figure what Im missing:

RecordedRequest request = server.takeRequest();
request.getBody().readUtf8()

Intellij, spring boot unit test is telling me can't resolve method readUtf8

any help will be greatly appreciated

This is the decompiled RecordedRequest.class. I dont see readUtf8 
![issue-mockwebserver](https://github.com/user-attachments/assets/1cb7c27c-25a8-46bf-bfcc-fd08844c4915)

**Comment by yschimke** [comment]
You should check you are using a consistent version of all okhttp modules. But not something we can directly help with

**Comment by yschimke** [comment]
readUtf8 is a method on okio Buffer. Not RecordedRequest.

But please consider using a site like stackoverflow for general build issues. We can't provide 1:1 support.
