### ISSUE TITLE
Host header update when one url redirects to another url.

### ISSUE THREAD

**Issue by ali0399** [square/okhttp#8545]
I faced an issue where the redirect location that i got from the 1st Api call had a different subdomain. but the host header retains the domain of the first api. this causes error in my server and i get 404.
1st Api: https://abcalert.extensions.sit.abcx1.de/fp/install.
2nd Api: https://api.sit.abcx1.de/authentication/v1.0/company/111/oauth/authorize
the header, host: abcalert.extensions.sit.abcx1.de remains same in both.
Work around: removed host header using network interceptor.

What is the reason for this and should it be raised as a bug? I could not find any documentation related to this.

**Comment by yschimke** [comment]
We've seen this before when the client is manually setting a host header.

https://github.com/square/okhttp/issues/6487

Please provide a reproduction, as this should be working.

**Comment by yschimke** [comment]
Just confirmed with the following test

```

  @Test
  fun redirectsUpdatesHost() {
    server2.enqueue(MockResponse(body = "Page 2"))
    server.enqueue(
      MockResponse(
        code = HttpURLConnection.HTTP_MOVED_TEMP,
        headers = headersOf("Location", server2.url("/").toString()),
      ),
    )
    val response = client.newCall(Request(server.url("/page1"))).execute()
    assertThat(response.body.string()).isEqualTo("Page 2")
    val request1 = server.takeRequest()
    assertThat(request1.headers["Host"]).isEqualTo(server.hostName + ":" + server.port)
    val request2 = server2.takeRequest()
    assertThat(request2.headers["Host"]).isEqualTo(server2.hostName + ":" + server2.port)
  }
```
