### ISSUE TITLE
http2 same url multiple request when one request is io processing other thread is blocked

### ISSUE THREAD

**Issue by ericYc** [square/okhttp#8553]
same as  https://github.com/square/okhttp/issues/5556 this issue, we found if we request same url parallel（http2），if one request is doing io process，and not finished，it will block other request。
can any help me fix this。
![Image](https://github.com/user-attachments/assets/356fe30d-e929-4a00-b330-8742b8df375e)
![Image](https://github.com/user-attachments/assets/cae119a4-0b1d-420f-8d84-184445b4ce1a)
![Image](https://github.com/user-attachments/assets/0f1ebab3-9f1b-4b9b-aad9-e488433e08b1)

**Comment by ericYc** [comment]
[jstack.log](https://github.com/user-attachments/files/17349083/jstack.log)

**Comment by yschimke** [comment]
OkHttp 3.x is no longer maintained and supported.

See https://square.github.io/okhttp/security/security/#supported-versions
