### ISSUE TITLE
MockWebServer - simulate lower-level DNS/connection/TLS/HTTP Protocol issues

### ISSUE THREAD

**Issue by cloudshiftchris** [square/okhttp#8555]
There's classes of failures below the "HTTP message" level that are hard to unit-test; this would help improve the robustness of the OkHttp client and software that builds on it (e.g. frameworks, SDKs).

Proposal: model the lower-level components in MockWebServer such that their behaviour can be adjusted.

Key areas:

* DNS lookups (simulate DNS latency, failures)
* Connection establishment (simulate connection latency, establishment failures, closing of connections at inopportune times)
* TLS negotiation (exposed ciphers, handshake latency, protocol violations)
* HTTP (/2) (protocol latency, protocol violations) (NOTE: this refers to the protocol level, not messages sent over HTTP)

A rough sampling of related issues that may be easier to prevent / diagnose with enhanced testability:

Connection issues
	* https://github.com/awslabs/aws-sdk-kotlin/issues/1214

HTTP (/2) protocol violations
	* https://github.com/square/okhttp/issues/8524
	* https://github.com/square/okhttp/issues/8408
	* https://github.com/square/okhttp/issues/7913
	* https://github.com/square/okhttp/issues/7840
	* https://github.com/square/okhttp/issues/3955

DNS failures
	* https://github.com/square/okhttp/issues/8481

**Comment by yschimke** [comment]
I'd suggest something like mockserver for this. OkHttp MockWebServer is not being actively enhanced.

https://www.mock-server.com/

**Comment by cloudshiftchris** [comment]
Was hoping part of this would be for OkHttp to improve testability/quality, whether that be with MockWebServer or otherwise.

**Comment by yschimke** [comment]
Do you have a concrete example of one of these tests? It's potentially something we would add as tests, but unlikely to provide new public API in MockWebServer. There are already better more complete mock servers out there.

For DNS, this is already possible by providing a custom Dns to the client.

For http2 frames, this is already possible internally with some examples tests.

**Comment by cloudshiftchris** [comment]
A few examples:

1) The adventure in https://github.com/awslabs/aws-sdk-kotlin/issues/1214 could be better tested to ensure connection pool / stale / closed connection / retry semantics are correct (they are questionable atm):

* Close idle connections / streams after short period of inactivity (< 10 seconds); including testing with multiple connections in the pool;
* Close connection/stream upon receipt of a message, to simulate server/software crashing (or otherwise faulting), closing the connection before sending a response;

2) Each of these look to be HTTP/2 protocol violations that could be tested (and perhaps are) to ensure OkHttp behaves correctly:

* https://github.com/square/okhttp/issues/8524
* https://github.com/square/okhttp/issues/8408
* https://github.com/square/okhttp/issues/7913
* https://github.com/square/okhttp/issues/7840
* https://github.com/square/okhttp/issues/3955

**Comment by cloudshiftchris** [comment]
A combination of built-in testing for issues we've been negatively affected by and a general desire to "make OkHttp better" where possible/practical.

**Comment by yschimke** [comment]
Sounds good. for internal project use, if there are things that you might want to add to MockWebServer, then it sounds reasonable. I think we'd just avoid new public API.
