### ISSUE TITLE
Indirect library vulnerability (relinker).

### ISSUE THREAD

**Issue by PiotrKlis** [square/okhttp#8573]
Hi team,

our client reported following indirect vulnerability in the OkHttp library, version `4.12.0`. Issue lies in the `relinker` library, that is being used internally by your library. 

Full report can be found here https://www.securetheorem.com/management/share/7H-ZIywaS5VLeSagjBri-WFmA/app/1053200002/findings/007882

Are you aware of that issue? Do you plan on removing or updating relinker version within next lib update? 

Let me know if you have any questions,

Best,
Piotr

**Comment by yschimke** [comment]
This is spurious report for OkHttp

> Android provides the java.util.zip package, which contains classes such as ZipInputStream that enable an App to read, create and modify ZIP archives. When using this API to unzip an archive, it does not protect against file names in the archive that trigger a path traversal (such as ../..). This allows a malicious archive to overwrite files within the App's container when the archive gets unzipped.

We can't fix the android dependencies.
