### ISSUE TITLE
overwrite content type header

### ISSUE THREAD

**Issue by ShaimaaSabry** [square/okhttp#8576]
I have the following code:
`
String xmlRequest = xmlMapper.writeValueAsString(updateLoginIdRequest);
byte[] bytes = xmlWithNamespace.getBytes(StandardCharsets.UTF_8);
RequestBody requestBody = RequestBody.create(bytes);

Request request = new Request.Builder()
        .url(urlBuilder.toString())
        .header("Content-Type", "application/x-wamupdateuserloginid+xml;version=1")
        .put(requestBody)
        .build();
`

The server is rejecting the request because the content type header is not correct. What am I doing wrong?

**Comment by yschimke** [comment]
RequestBody will overide the Content-Type so you should set it via requestBody instead of a Header.

 You can test things like this using a site like https://httpbin.org/#/HTTP_Methods/post_post

Make a request to https://httpbin.org/post and print out the response body.
