### ISSUE TITLE
responseBodyEnd Callback Reports Zero Byte Count for Failed Requests (4xx/5xx), Even When Backend Returns Error Body

### ISSUE THREAD

**Issue by ddas09** [square/okhttp#8598]
Description:
When handling failed requests (such as HTTP 4xx or 5xx responses), the `responseBodyEnd` callback is invoked with a `byteCount` of 0, even if the server includes a response body containing error details. This happens regardless of whether the response body is empty or contains information like error messages or stack traces.

I have set up a custom retry interceptor that retries the request up to two times. The backend API returns an **HTTP 500** error for the first two attempts and a successful **HTTP 200** response for the final retry. However, I noticed that when the backend returns a `500` error, the `responseBodyEnd` callback always reports a `byteCount` of 0, even though the body contains error details. On successful (**HTTP 200)** responses, the `byteCount` is non-zero, as expected.

Is this expected behavior? As per my understanding the `byteCount` should reflect the size of the body, even for error responses.

Below is the sample code snippets - 
**Backend API (Express):**

```
const internalError = catchAsync(async (req: Request, res: Response) => {
  const retryCount = parseInt(req.headers["x-retry-count"] as string) || 0;

  if (retryCount >= 3) {
    res.status(200).json({ message: "Success after 3 retries!" });
  } else {
    res.status(500).json({ message: "Something went wrong on the server." });
  }
});
```

**Here is the custom retry interceptor I am using to retry the request up to two times:**
```
class RetryInterceptor : Interceptor {
    private val maxRetryCount = 3
    private val retryDelayMillis = 500L

    @Throws(IOException::class)
    override fun intercept(chain: Interceptor.Chain): Response {
        var attempt = 0
        var lastException: IOException? = null
        var response: Response? = null

        do {
            attempt++

            try {
                val modifiedRequest = chain.request().newBuilder()
                    .addHeader("X-Retry-Count", attempt.toString())
                    .build()

                response = chain.proceed(modifiedRequest)

                if (response.isSuccessful) {
                    return response
                }
            } catch (e: IOException) {
                lastException = e
            }

            // we need to close the response before retrying the request again
            response?.close()

            if (attempt < maxRetryCount) {
                try {
                    TimeUnit.MILLISECONDS.sleep(attempt * retryDelayMillis)
                } catch (e: InterruptedException) {
                    Thread.currentThread().interrupt()
                }
            }
        } while (attempt < maxRetryCount)

        throw lastException ?: IOException("Unknown error after $maxRetryCount retries")
    }
```

**Comment by swankjesse** [comment]
Looks like a bug!

**Comment by ddas09** [comment]
@swankjesse, is there any other way to determine the response body size using the Events listener API?

**Comment by ddas09** [comment]
Update:

I was able to get the correct response body size(which was my original requirement) from the `Content-Length` header of the `response` object in the `responseHeadersEnd` callback.

But I still believe we should get the appropriate non-zero value for `byteCount` in the `responseBodyEnd` callback, even if the backend returns a HTTP (4xx/5xx) error. I believe this is a bug (probably of low priority), hence keeping this issue open.

**Comment by swankjesse** [comment]
Does this part of the `EventListener` documentation clarify anything?

```
   * If the response body is closed before the response body is exhausted, this is invoked at the
   * time it is closed. In such calls [byteCount] is the number of bytes returned to the
   * application. This may be smaller than the resource's byte count if were read to completion.
```

By not reading the response body in non-successful cases, OkHttp doesn’t actually process those bytes and therefore can’t count them.

**Comment by ddas09** [comment]
@swankjesse, thanks for sharing this! After looking at the doc, I feel this is an intended behaviour. Closing this issue since my original problem is solved already.
