### ISSUE TITLE
okhttp-jvm-5.0.0-alpha.13 missing from https://central.sonatype.com/artifact/com.squareup.okhttp3/okhttp-jvm

### ISSUE THREAD

**Issue by rbeazleyspot** [square/okhttp#8609]
okhttp-jvm-5.0.0-alpha.13 is missing from https://central.sonatype.com/artifact/com.squareup.okhttp3/okhttp-jvm however okhttp-5.0.0-alpha.13 is not

is it possible something broke during publishing ?

**Comment by rbeazleyspot** [comment]
is this because okhttp-jvm is not released anymore now due to KMP support being dropped ?

**Comment by JakeWharton** [comment]
Yes. The artifactId changed back to just `okhttp`.
