### ISSUE TITLE
Add global HTTP error callback method

### ISSUE THREAD

**Issue by WoKee** [square/okhttp#8631]
Requirement:
For Android, many third-party SDKs are integrated into the project development, and they also use OKHTTP internally. When there are some error message Toasts, users will give us feedback。

For example: Too many follow up requests: 21, HTTP 404, etc

Interceptor is designed for the new okhttpclient instance.

However, due to their internally initialized okhttpclient, we are unable to add an Interceptor or determine which SDK it belongs to based on Toast prompts. Therefore, there is a requirement for a global static error callback

Like RxJava:
`RxJavaPlugins.setErrorHandler(throwable -> {
});`

Or is there currently a solution?

Thanks。

**Comment by yschimke** [comment]
I share your pain. A similar issue

https://github.com/google-gemini/generative-ai-android/issues/39

But I'm not sure we want to take this control away from SDK developers. Maybe it's a secure call and another library might snoop on those.

**Comment by JakeWharton** [comment]
I'm pretty opposed to this. RxJava is a wildly-generic framework that handles data, errors, and the failure to handle errors. Its support for this is akin to the Thread uncaught handler.

OkHttp is just a library that has synchronous and asynchronous APIs and the user is expected to handle exceptions the same way they would with something like the Process API or new built-in HTTP client.
