### ISSUE TITLE
Okhttp 2.0 and OAuth

### ISSUE THREAD

**Issue by akshaydashrath** [square/okhttp#885]
I'm unsure how to implement OAuth/XAuth with the new version of the library, with version 1.5 and below I was able to sign the HttpUrlConnection without any issue, however now the connection is abstracted away.

**Comment by samskiter** [comment]
@swankjesse does this open up the possibility of having an equivalent of "google-oauth-java-client" in okhttp. has anyone started this work or is there anything to base this off yet? (I appreciate the interceptor API is very new)

**Comment by swankjesse** [comment]
@samskiter: yup, that's possible, though it wouldn't go into OkHttp but some other, independent project.

**Comment by dherges** [comment]
@samskiter started some minimalistic work in case you're interested .. https://github.com/dherges/yatc/tree/master/mobile/src/main/java/com/twitter/contrib/yatc/http/oauth .. maybe it's possible to extract the oauth portions as an independent library

**Comment by samskiter** [comment]
Looks interesting. I think I ended up using google-auth client (https://github.com/google/google-oauth-java-client) as a client of retrofit in order to get all the auth features of that (which includes auto refresh). It would be great to simplify that with an okhttp add-in
