### ISSUE TITLE
Non-ASCII Header Encoding Issues

### ISSUE THREAD

**Issue by JakeWharton** [square/okhttp#891]
When passing headers parameters containing a 'é' it is received on server side as 'Ã©'.
It might seem wird to pass such chars as arguments but I can't modify server side. 
I know this behaviour is specific to retrofit  because it worked with the old client using HttpUrlConnection and it also works with Postman chrome plugin.

via @cmorin6 from https://github.com/square/retrofit/issues/516

**Comment by yyjdelete** [comment]
Android use the below method in com.android.internal.os.RuntimeInit to set default UA, and okhttp-urlconnection direct use the UA as default http head without encode it. 
```java
    /**
     * Returns an HTTP user agent of the form
     * "Dalvik/1.1.0 (Linux; U; Android Eclair Build/MASTER)".
     */
    private static String getDefaultUserAgent() {
        StringBuilder result = new StringBuilder(64);
        result.append("Dalvik/");
        result.append(System.getProperty("java.vm.version")); // such as 1.1.0
        result.append(" (Linux; U; Android ");

        String version = Build.VERSION.RELEASE; // "1.0" or "3.4b5"
        result.append(version.length() > 0 ? version : "1.0");

        // add the model for the release build
        if ("REL".equals(Build.VERSION.CODENAME)) {
            String model = Build.MODEL;
            if (model.length() > 0) {
                result.append("; ");
                result.append(model);
            }
        }
        String id = Build.ID; // "MASTER" or "M4-rc20"
        if (id.length() > 0) {
            result.append(" Build/");
            result.append(id);
        }
        result.append(")");
        return result.toString();
    }
```
As an result, when I use okhttp-urlconnection in my apk, my server recevied the below request from an device with non-ASCII MODEL, which is invalid.

![Model with non-ASCII char](https://cloud.githubusercontent.com/assets/1819074/8028576/47bf0c38-0de3-11e5-9c7b-ed93933ed693.png)

**Comment by yyjdelete** [comment]
AnyOne?

**Comment by swankjesse** [comment]
Yep, we should sanitize the User-Agent.

**Comment by swankjesse** [comment]
Working plan: throw an exception on non-ASCII headers in `Headers.Builder`.

**Comment by vvelmurugan** [comment]
@swankjesse Why the add method is not throwing illegalArgumentException, for us developers to catch and handle the error and mostly importantly to know that this method will throw this exception. Not many will look into the source and find that the header values are sanitised strictly.

**Comment by swankjesse** [comment]
@vvelmurugan which header aren’t we being strict enough on? Most code paths that add headers are strict!

**Comment by vvelmurugan** [comment]
@swankjesse I think I am not clear with my question. My question is 
Current method is like this
`private void checkNameAndValue(String name, String value) `
but I feel it should be like this
`private void checkNameAndValue(String name, String value) **throws illegalArgumentException** `
So , 
Add method will look this
`public Builder add(String name, String value) **throws illegalArgumentException** `

if it is like this then our lint itself will suggest to handle that exception and we will look into okhttp code on why this exception is thrown. Currently many devs who come from HttpUrlConnection will not know that you sanitise headers for non-ascii characters

**Comment by swankjesse** [comment]
@vvelmurugan ahhhh. Can you open a new issue requesting better documentation on the restrictions upon headers? Also please tell us which docs you read before running into this issue so we have a good idea as to where to document it!
