### ISSUE TITLE
Lint error caused by Okio dependency

### ISSUE THREAD

**Issue by zyro** [square/okhttp#896]
OkHttp `2.0.0-RC1` - getting this lint error during the build process:

```
.gradle/caches/[...]/okio-1.0.0.jar:
Invalid package reference in library; not included in Android: java.nio.file.
Referenced from okio.Okio.
```

Do you recommend adding an entry for `okio` to my project's `lint.xml`?

**Comment by ThinkingQuest** [comment]
It's 2017  and version 3.8.1 now.
lol.
