### ISSUE TITLE
Support 307s and 308s

### ISSUE THREAD

**Issue by joreilly** [square/okhttp#936]
Does okhttp support POST'ing to redirect url returned in 301 response to a POST?  We're using v1.3 right now and it does not appear to be supported?

**Comment by alaaghribi** [comment]
Does Retrofit accepts now 307 and 308 ?

**Comment by JakeWharton** [comment]
No. 3xx shouldn't make it to Retrofit.

**Comment by alaaghribi** [comment]
I don't know why you've simply chose to disable that feature. I added setFollowRedirects into OKHttp client and pass it to RestAdapter but it's not working. Can you please give the possibility to the user to switch that feature ON or OFF ?

**Comment by JakeWharton** [comment]
What feature? OkHttp follows redirects and it offers the API for enabling.

**Comment by alaaghribi** [comment]
Strange, even when setting `setFollowRedirects` to `true` I do not have redirection, but I have the failure block that called with `307 Temporary Redirect` response failure message.

**Comment by vinceve** [comment]
Well the reason why it doesn't follow the 307 or 308 with a POST is that OkHttp really blocks this.

The code can be found here: https://github.com/square/okhttp/blob/07309c1c7d9e296014268ebd155ebf7ef8679f6c/okhttp/src/main/java/okhttp3/internal/http/RetryAndFollowUpInterceptor.java#L290

**Comment by GlennMatthys** [comment]
> Well the reason why it doesn't follow the 307 or 308 with a POST is that OkHttp really blocks this.
> 
> The code can be found here:
> 
> [okhttp/okhttp/src/main/java/okhttp3/internal/http/RetryAndFollowUpInterceptor.java](https://github.com/square/okhttp/blob/07309c1c7d9e296014268ebd155ebf7ef8679f6c/okhttp/src/main/java/okhttp3/internal/http/RetryAndFollowUpInterceptor.java#L290)
> 
> Line 290 in [07309c1](/square/okhttp/commit/07309c1c7d9e296014268ebd155ebf7ef8679f6c)
> 
>  if (!method.equals("GET") && !method.equals("HEAD")) { 
> A workaround could be:
> 
> ```java
> public Response post(String url, String content) throws IOException {
>         RequestBody body = RequestBody.create(PROTOCOL, content);
> 
>         Request.Builder requestBuilder = new Request.Builder().url(url).post(body);
>         Request request = requestBuilder.build();
>         Response response = this.client.newCall(request).execute();
> 
>         if(response.code() == 307) {
>             String location = response.header("Location");
>             return post(location, content);
>         }
> 
>         return response;
>     }
> ```

Note that you should do some sanity checking on the received location header (for example when a redirect leads to an HTTP endpoint instead of HTTPS - do you really want that? The query string or post body could contain sensitive information). Furthermore you should keep track of how many times you have been redirected and bail when exceeding for example 10 redirects, otherwise you can get stuck in an infinite loop.

Also, why was this bugreport closed? For a library abstracting the HTTP proces, this should be handled inside the library...

**Comment by swankjesse** [comment]
Tracking here: https://github.com/square/okhttp/issues/3111
