### ISSUE TITLE
Domain name lookup doesn't support cancel or timeout

### ISSUE THREAD

**Issue by swankjesse** [square/okhttp#95]
We might want to work-around this with helper threads or interrupts, or something.
See also https://code.google.com/p/android/issues/detail?id=40874

**Comment by DanielNovak** [comment]
Any news on this? It would be great if we could set a timeout for the DNS lookup. Typical use case is when a user connects to a WiFi that does not have an internet connection. It takes 20-30 seconds until the request fails and there is no way how to reduce this time.

**Comment by rtzoeller** [comment]
We are also running into issues with this. Do you know if any progress has been made on a workaround?

**Comment by swankjesse** [comment]
Nothing at the moment. It's a difficult bug to fix because DNS is completely opaque in Java.

**Comment by czfyzy** [comment]
see:http://stackoverflow.com/questions/693997/how-to-set-httpresponse-timeout-for-android-in-java/31643186#31643186

**Comment by swankjesse** [comment]
Maybe we do DNS on a background thread? That’d probably be worth the cost, although potentially surprising.

**Comment by swankjesse** [comment]
One more thing: now that our `Dns` interface is public, end-users can do this if they like.

**Comment by yschimke** [comment]
n.b. This is relevant for dnsoverhttps and there are also other viable dns clients now e.g. Netty impl is straightforward and can support timeouts.  It would be nice if this was part of an overall request timeout even for a synchronous call.execute

https://github.com/yschimke/oksocial/blob/master/src/main/kotlin/com/baulsupp/oksocial/network/NettyDns.kt

**Comment by swankjesse** [comment]
I was pondering the right API for this. Is it DnsCall + DnsCallback interfaces? That seems like a lot of code.

Another option is to make the DNS method async with coroutines, but that means we need a Kotlin dependency.

Other ideas?

**Comment by yschimke** [comment]
Punt until there is a story for a (future?) kotlin based OkHttp, hopefully with native support for coroutines?

**Comment by galderz** [comment]
Hi, I've been working on this. I've created a PR (#4674) to get some feedback. Thx

**Comment by yschimke** [comment]
Dupe of https://github.com/square/okhttp/issues/5042?

**Comment by swankjesse** [comment]
Yep, these are mutually redundant.

**Comment by distinctdan** [comment]
I just ran into this on version 4.11.0, so it appears to still be an issue, but I was able to work around it by wrapping my call with `withTimeout`. I'm using coroutines using the technique here: https://github.com/gildor/kotlin-coroutines-okhttp/blob/master/src/main/kotlin/ru/gildor/coroutines/okhttp/CallAwait.kt

As a user, it's surprising to me that the DNS timeout isn't included in the overall `callTimeout`.

**Comment by yschimke** [comment]
It would probably be more correct to use the AsyncDns implementation

https://github.com/square/okhttp/blob/6b91ea468c6b2931f9092232d8ebcf61076023ff/okhttp/src/jvmMain/kotlin/okhttp3/AsyncDns.kt

And default to Android Dns which supports it https://github.com/square/okhttp/blob/6b91ea468c6b2931f9092232d8ebcf61076023ff/okhttp-android/src/main/kotlin/okhttp3/android/AndroidAsyncDns.kt

With some other approach for JVM.  but not likely soon.
