### ISSUE TITLE
OkHttp (Okio) conflicts with /system/framework/okhttp.jar on Android L Preview

### ISSUE THREAD

**Issue by luciofm** [square/okhttp#967]
```
E  Process: com.weheartit, PID: 4437
E  java.lang.NoSuchMethodError: No static method source(Ljava/io/File;)Lokio/Source; in class Lokio/Okio; or its super classes (declaration of 'okio.Okio' appears in /system/framework/okhttp.jar)
E      at com.squareup.okhttp.internal.DiskLruCache.readJournal(DiskLruCache.java:243)
E      at com.squareup.okhttp.internal.DiskLruCache.open(DiskLruCache.java:224)
E      at com.squareup.okhttp.Cache.<init>(Cache.java:146)
E      at com.squareup.picasso.OkHttpDownloader.<init>(OkHttpDownloader.java:74)
E      at com.squareup.picasso.OkHttpDownloader.<init>(OkHttpDownloader.java:51)
E      at com.squareup.picasso.OkHttpDownloader.<init>(OkHttpDownloader.java:41)
E      at com.squareup.picasso.Utils$OkHttpLoaderCreator.create(Utils.java:407)
E      at com.squareup.picasso.Utils.createDefaultDownloader(Utils.java:255)
E      at com.squareup.picasso.Picasso$Builder.build(Picasso.java:596)
E      at com.squareup.picasso.Picasso.with(Picasso.java:473)
```

**Comment by petrLorenc** [comment]
I have the same issue again

     10-25 23:27:26.610 9472-9472/cz.united121.rxandroid E/AndroidRuntime: FATAL EXCEPTION: main
     10-25 23:27:26.610 9472-9472/cz.united121.rxandroid E/AndroidRuntime: Process: cz.united121.rxandroid, PID: 9472
     10-25 23:27:26.610 9472-9472/cz.united121.rxandroid E/AndroidRuntime: java.lang.NoSuchMethodError: No static method createNetworkService(Ljava/lang/Class;Ljava/lang/String;)Ljava/lang/Object; in class Lcz/united121/rxandroid/model/network/NetworkService; or its super classes (declaration of 'cz.united121.rxandroid.model.network.NetworkService' appears in /data/app/cz.united121.rxandroid-1/base.apk)
     10-25 23:27:26.610 9472-9472/cz.united121.rxandroid E/AndroidRuntime:     at cz.united121.rxandroid.model.recyclerModel.RecyclerModel.updateDataToDatabase(RecyclerModel.java:35)
     10-25 23:27:26.610 9472-9472/cz.united121.rxandroid E/AndroidRuntime:     at cz.united121.rxandroid.presenter.recyclerPresenter.RecyclerPresenter.updateRecyclerViewClick(RecyclerPresenter.java:64)
     10-25 23:27:26.610 9472-9472/cz.united121.rxandroid E/AndroidRuntime:     at cz.united121.rxandroid.view.recyclerView.RecyclerFragment.onClickupdateRecyclerView(RecyclerFragment.java:74)
     10-25 23:27:26.610 9472-9472/cz.united121.rxandroid E/AndroidRuntime:     at cz.united121.rxandroid.view.recyclerView.RecyclerFragment$$ViewBinder$1.doClick(RecyclerFragment$$ViewBinder.java:22)
     10-25 23:27:26.610 9472-9472/cz.united121.rxandroid E/AndroidRuntime:     at butterknife.internal.DebouncingOnClickListener.onClick(DebouncingOnClickListener.java:22)
     10-25 23:27:26.610 9472-9472/cz.united121.rxandroid E/AndroidRuntime:     at android.view.View.performClick(View.java:4785)
     10-25 23:27:26.610 9472-9472/cz.united121.rxandroid E/AndroidRuntime:     at android.view.View$PerformClick.run(View.java:19884)
     10-25 23:27:26.610 9472-9472/cz.united121.rxandroid E/AndroidRuntime:     at android.os.Handler.handleCallback(Handler.java:739)
     10-25 23:27:26.610 9472-9472/cz.united121.rxandroid E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:95)
     10-25 23:27:26.610 9472-9472/cz.united121.rxandroid E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:135)
     10-25 23:27:26.610 9472-9472/cz.united121.rxandroid E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5343)
     10-25 23:27:26.610 9472-9472/cz.united121.rxandroid E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method)
     10-25 23:27:26.610 9472-9472/cz.united121.rxandroid E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:372)
     10-25 23:27:26.610 9472-9472/cz.united121.rxandroid E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
     10-25 23:27:26.610 9472-9472/cz.united121.rxandroid E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)

the line where a call createNetworkService

    	NetworkService networkService = NetworkService.createNetworkService(NetworkService.class, NetworkService.TEST_ENDPOINT);

and function looks like this 

    public interface NetworkService {
	static <T> T createNetworkService(final Class<T> tClass, final String endPoint) {
		Retrofit retrofit = new Retrofit.Builder()
				.addCallAdapterFactory(RxJavaCallAdapterFactory.create())
				.addConverterFactory(GsonConverterFactory.create())
				.baseUrl(endPoint)
				.build();
		T service = retrofit.create(tClass);
		return service;
	}
    ....
It looks like the error from head page.

**Comment by swankjesse** [comment]
@petrlorenc: unrelated issue. Chances are you have a different version of a dependency at build time vs. runtime.

**Comment by GankLun** [comment]
> [Deleted Emanuele Ricci's question by mistake. Apologies.]
> 
> > Is there something we can do or can we just wait for the release of the update?
> 
> The error is because L preview has the okio classes in their original package (okio.*). This means they conflict with the classes being shipped in your APK. Since the ones that ship with the device are used in preference to ones in the APK it fails because the version of the classes you have is newer. In the L release they will be repackaged into com.android.okio (using jarjar).
> 
> @swankjesse mentioned two options:
> 
> 1. You can repackage your copy of the okio code using jarjar yourself to avoid the conflict.
> 2. Proguard could be used to achieve similar things by renaming (or repackaging?) the okio classes in the APK, again so there is no conflict.

I can't agree any more about you because parent classloader is preference to classloader in apk ,but as you said, it fails because the version of the classes you have is newer. but  how program knows which version is newer
