### ISSUE TITLE
Requests should send a default user-agent

### ISSUE THREAD

**Issue by mpost** [square/okhttp#982]
Requests made with okhttp 2.x do not set a proper user-agent. I would expect to see a default user agent. Maybe similar to the one used by picasso:

<code>Dalvik/1.6.0 (Linux; U; Android 4.4.4; Nexus 5 Build/KTU84P)</code>

**Comment by Magudesh** [comment]
> Requests made with okhttp 2.x do not set a proper user-agent. I would expect to see a default user agent. Maybe similar to the one used by picasso:
> 
> `Dalvik/1.6.0 (Linux; U; Android 4.4.4; Nexus 5 Build/KTU84P)`

I want to know  why that **dalvik** user agent is coming ?

Is anybody can help regarding this?
