### ISSUE TITLE
Http/2 frame size is 2 KiB.

### ISSUE THREAD

**Issue by swankjesse** [square/okhttp#983]
By default, RealBufferedSink emits after each complete segment, which means we end up with 2 KiB frames. This isn't necessarily a problem; we're preferring to conserve memory vs. throughput.

But we could potentially change RealBufferedSink.writeAll to emit less frequently, or be configurable, or we could buffer in the HTTP layer.

```
  @Override public long writeAll(Source source) throws IOException {
    if (source == null) throw new IllegalArgumentException("source == null");
    long totalBytesRead = 0;
    for (long readCount; (readCount = source.read(buffer, Segment.SIZE)) != -1; ) {
      totalBytesRead += readCount;
      emitCompleteSegments();
    }
    return totalBytesRead;
  }
```

**Comment by yschimke** [comment]
Won't fix.
