### ISSUE TITLE
OkHttpClient implies that it can use HTTP/1.0. It can not.

### ISSUE THREAD

**Issue by hgschmie** [square/okhttp#986]
There is a constant, Protocols.HTTP_1_0. However, setting the client to only use HTTP 1.0 will cause the check in https://github.com/square/okhttp/blob/master/okhttp/src/main/java/com/squareup/okhttp/OkHttpClient.java#L435 to trigger. 

I am trying to use okhttp to talk to a server that only speaks HTTP 1.0 and it seems that this is not possible.

**Comment by kunalsharma** [comment]
Hi I am still getting this issue 
Response{protocol=http/1.0, code=200, message=OK, url=http://} any solution
