### ISSUE TITLE
Runtime error NoClassDefFoundError: com.squareup.okhttp.Request$Builder

### ISSUE THREAD

**Issue by odedregev** [square/okhttp#988]
Hi,

I'm trying to integrate OkHttp in an existing project which already have Picasso in it. I updated Picasso to v2.3.2, also added okio-1.0.0 and tried the official OkHttp lib, as well as okhttp-urlconnection-2.0.0-RC2.jar. 

The project build works fine but in runtime I get the error above. I couldn't find any hint to this error on the web. Please help :)

07-10 12:13:29.139: E/AndroidRuntime(15096): java.lang.NoClassDefFoundError: com.squareup.okhttp.Request$Builder

**Comment by xckevin** [comment]
@odedregev  hi, do u resolve this problem?  Now I got the same error

**Comment by odedregev** [comment]
I got it to work a while ago so I don't really remember what I did. I think there was something related to the dependency between all the libraries involved. Make sure that you take the right okhttp-urlconnection-xxx library.

**Comment by xckevin** [comment]
finally, I fixed it with those jar:
 + okhttp-2.0.0.jar
 + okhttp-urlconnection-2.0.0.jar
 + okio-1.0.0.jar
 + picasso-2.4.0.jar
 + retrofit-1.90.jar

BUT other versions still ｀DＯ　ＮＯＴ　ＷＯＲＫ｀

**Comment by abhiKamra** [comment]
i used okhttp-3.11.0.jar and okio-1.13.0.jar.It worked for me
