### ISSUE TITLE
API to force cache-only response

### ISSUE THREAD

**Issue by savvasdalkitsis** [square/okhttp#992]
This might sound a bit weird but here goes.

Our usecase is as follows:

We have an endpoint which should never be cached (and our server correctly sends no cache headers). We would like the ability to use the last successful response when the device has no connectivity though.

I was wondering if it would be possible to allow an execution mode in which responses that are not supposed to be cached due to the headers, are put into a separate cache anyway which would be used only when the device has no network connectivity.

Now we might be able to do this manually in our code by treating this specific endpoint differently and storing the last response somewhere ourselves, but I was wondering if having this done transparently would be something that you would consider providing in the library

**Comment by passerbywhu** [comment]
@andrejvanderzee I met the same problem with you. Is it caused by response header?
