### ISSUE TITLE
Honor Android 5's android.net.network

### ISSUE THREAD

**Issue by swankjesse** [square/okhttp#995]
We could pin an OkHttpClient instance to a given network like LTE, WiFi or a VPN.

![screen shot 2014-07-18 at 1 27 00 am](https://cloud.githubusercontent.com/assets/133019/3622707/31ac21f8-0e3c-11e4-895f-bbda81a6263c.png)

**Comment by eygraber** [comment]
Does this work? I would like to use it with https://developer.android.com/reference/androidx/work/NonBlockingWorker#getNetwork()
